from sage.structure.element import Element
from sage.structure.parent import Parent

class FreeAlgebra_letterplace(Parent):
    def ngens(self) -> int: ...
    def gen(self, i: int) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def current_ring(self) -> Element: ...
    def commutative_ring(self) -> Element: ...
    def term_order_of_block(self) -> Element: ...
    def generator_degrees(self) -> Element: ...
    def is_field(self, proof: Element | int | str | bool | None) -> bool: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def degbound(self) -> Element: ...
    def set_degbound(self, d: int) -> Element: ...
    def _ideal_class_(self, n: int) -> Element: ...
    def ideal_monoid(self) -> Element: ...
    def _reductor_(self, g: Element, d: int) -> Element: ...
    def _coerce_map_from_(self, S: Element | int | str | bool | None) -> Element: ...
    def _an_element_(self) -> Element: ...
    def _from_dict_(self, D: Element | int | str | bool | None, check: bool) -> Element: ...
    def _element_constructor_(self, x: Element) -> Element: ...

class FreeAlgebra_letterplace_libsingular:
    ...
