import builtins

class _SageObject: ...

class LetterplaceIdeal:
    def __init__(
        self,
        ring: builtins.object,
        gens: builtins.object,
        coerce: builtins.object = ...,
        side: builtins.object = ...,
    ) -> None: ...
    def groebner_basis(self, degbound: builtins.object = ...) -> _SageObject: ...
    def __contains__(self, x: object) -> bool: ...
    def reduce(self, G: builtins.object) -> _SageObject: ...
