# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LetterplaceIdeal:
    def __init__(self, ring: builtins.object, gens: builtins.object, coerce: builtins.object = ..., side: builtins.object = ...) -> None: ...
    def groebner_basis(self, degbound: builtins.object = ...) -> _SageObject: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def reduce(self, G: builtins.object) -> _SageObject: ...
