from sage.structure.element import Element

class LetterplaceIdeal(Ideal_nc):
    def groebner_basis(self, degbound: Element | int | str | bool | None) -> Element: ...
    def reduce(self, G: Element | int | str | bool | None) -> Element: ...

class Ideal_nc: ...
