import builtins
from typing import Self

class _SageObject: ...

class IndexedSequence:
    def __init__(self, L: builtins.object, index_object: builtins.object) -> None: ...
    def dict(self) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def index_object(self) -> _SageObject: ...
    def plot_histogram(
        self, clr: builtins.tuple[_SageObject, ...] = ..., eps: builtins.float = ...
    ) -> _SageObject: ...
    def plot(self) -> _SageObject: ...
    def dft(self, chi: builtins.object = ...) -> _SageObject: ...
    def idft(self) -> _SageObject: ...
    def dct(self) -> _SageObject: ...
    def dst(self) -> _SageObject: ...
    def convolution(self, other: builtins.object) -> _SageObject: ...
    def convolution_periodic(self, other: builtins.object) -> _SageObject: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __eq__(self, other: object) -> bool: ...
    def fft(self) -> _SageObject: ...
    def ifft(self) -> _SageObject: ...
    def dwt(
        self, other: builtins.str = ..., wavelet_k: builtins.int = ...
    ) -> _SageObject: ...
    def idwt(
        self, other: builtins.str = ..., wavelet_k: builtins.int = ...
    ) -> _SageObject: ...
