# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def FastFourierTransform(size: builtins.object, base_ring: builtins.object = ...) -> _SageObject: ...

FFT: _SageObject
class FastFourierTransform_base:
    ...

class FastFourierTransform_complex:
    def __init__(self, n: builtins.object, stride: builtins.object = ...) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def __setitem__(self, i: builtins.object, xy: builtins.object) -> None: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def plot(self, style: builtins.object = ..., xmin: builtins.object = ..., xmax: builtins.object = ..., **args: builtins.object) -> _SageObject: ...
    def forward_transform(self) -> _SageObject: ...
    def inverse_transform(self) -> _SageObject: ...
    def backward_transform(self) -> _SageObject: ...

class FourierTransform_complex:
    ...

class FourierTransform_real:
    ...
