# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ProductProjectiveSpaces_morphism_ring:
    def __init__(self, parent: builtins.object, polys: builtins.object, check: builtins.bool = ...) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __call__(self, P: builtins.int, check: builtins.bool = ...) -> _SageObject: ...
    def __eq__(self, right: builtins.object) -> builtins.bool: ...
    def __ne__(self, right: builtins.object) -> builtins.bool: ...
    def is_morphism(self) -> builtins.bool: ...
    def as_dynamical_system(self) -> _SageObject: ...
    def global_height(self, prec: builtins.int = ...) -> _SageObject: ...
    def local_height(self, v: builtins.object, prec: builtins.int = ...) -> _SageObject: ...
