# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ProductProjectiveSpaces_point_ring:
    def __init__(self, parent: builtins.object, polys: builtins.object, check: builtins.bool = ...) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __copy__(self) -> Self: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
    def __hash__(self) -> builtins.int: ...
    def normalize_coordinates(self) -> _SageObject: ...
    def dehomogenize(self, L: builtins.object) -> _SageObject: ...
    def scale_by(self, t: builtins.object) -> _SageObject: ...
    def change_ring(self, R: builtins.int, **kwds: builtins.object) -> _SageObject: ...
    def global_height(self, prec: builtins.int = ...) -> _SageObject: ...
    def local_height(self, v: builtins.object, prec: builtins.int = ...) -> _SageObject: ...

class ProductProjectiveSpaces_point_field:
    def intersection_multiplicity(self, X: builtins.object) -> _SageObject: ...
    def multiplicity(self) -> _SageObject: ...

class ProductProjectiveSpaces_point_finite_field:
    ...
