# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def enum_product_projective_rational_field(X: builtins.object, B: builtins.object) -> _SageObject: ...

def enum_product_projective_number_field(X: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def enum_product_projective_finite_field(X: builtins.object) -> _SageObject: ...

def sieve(X: builtins.object, bound: builtins.object) -> _SageObject: ...
