import builtins

class _SageObject: ...

class AlgebraicScheme_subscheme_product_projective:
    def segre_embedding(self, PP: builtins.object = ...) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def is_smooth(self, point: builtins.object = ...) -> bool: ...
    def affine_patch(
        self, I: builtins.int, return_embedding: builtins.bool = ...
    ) -> _SageObject: ...
    def intersection_multiplicity(
        self, X: builtins.object, P: builtins.int
    ) -> _SageObject: ...
    def multiplicity(self, P: builtins.int) -> _SageObject: ...
