# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def mpz_get_pylong_large(z: builtins.object) -> _SageObject: ...

def mpz_get_pylong(z: builtins.object) -> _SageObject: ...

def mpz_get_pyintlong(z: builtins.object) -> _SageObject: ...

def mpz_set_pylong(z: builtins.object, L: builtins.object) -> _SageObject: ...

def mpz_pythonhash(z: builtins.object) -> _SageObject: ...
