from collections.abc import Sequence

from sage.rings.ideal import Ideal_generic
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.integer import Integer
from sage.structure.element import RingElement

from .scheme import Scheme


class AlgebraicScheme(Scheme):
    def ambient_space(self) -> Scheme: ...
    def _check_satisfies_equations(self, v: Sequence[RingElement]) -> bool: ...

class AlgebraicScheme_subscheme(AlgebraicScheme):
    def defining_polynomials(self) -> tuple[Polynomial, ...]: ...
    def defining_ideal(self) -> Ideal_generic: ...
    def codimension(self) -> Integer: ...
    def Jacobian(self) -> Ideal_generic: ...
