from sage.rings.ideal import Ideal_generic
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.schemes.generic.scheme import Scheme
from sage.rings.integer import Integer


class AlgebraicScheme(Scheme):
    def ambient_space(self) -> Scheme: ...

class AlgebraicScheme_subscheme(AlgebraicScheme):
    def defining_polynomials(self) -> tuple[Polynomial, ...]: ...
    def defining_ideal(self) -> Ideal_generic: ...
    def codimension(self) -> Integer: ...
    def Jacobian(self) -> Ideal_generic: ...
