import builtins

from sage.structure.element import Element

class _SageObject: ...

class AmbientSpace:
    def __init__(self, n: builtins.int, R: builtins.int = ...) -> None: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    def is_projective(self) -> bool: ...
    def base_extend(self, R: builtins.int) -> _SageObject: ...
    def ambient_space(self) -> _SageObject: ...
    def defining_polynomials(self) -> _SageObject: ...
    def identity_morphism(self) -> _SageObject: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def ngens(self) -> _SageObject: ...
    def dimension_absolute(self) -> _SageObject: ...
    dimension: _SageObject

    def dimension_relative(self) -> _SageObject: ...
