# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def DivisorGroup(scheme: builtins.object, base_ring: builtins.object = ...) -> _SageObject: ...

class DivisorGroup_generic:
    @staticmethod
    def __classcall__(cls: builtins.object, scheme: builtins.object, base_ring: builtins.object = ...) -> _SageObject: ...
    def __init__(self, scheme: builtins.object, base_ring: builtins.object) -> None: ...
    def scheme(self) -> _SageObject: ...
    def base_extend(self, R: builtins.int) -> _SageObject: ...

class DivisorGroup_curve:
    ...
