from sage.structure.element import Element

from .scheme import Scheme

class SchemeMorphism(Element):
    def domain(self) -> Scheme: ...
    def codomain(self) -> Scheme: ...

class SchemeMorphism_point(SchemeMorphism): ...

class SchemeMorphism_polynomial(SchemeMorphism): ...
