import operator
from collections.abc import Callable
from sage.categories.functor import Functor
from sage.categories.map import Map
from sage.categories.morphism import Morphism
from sage.structure.element import Element
from sage.structure.parent import Parent

class Action(Functor):
    G: Parent | type
    op: Callable[..., Element] | None
    def __init__(self, G: Parent | type, S: Parent | type, is_left: bool = True, op: Callable[..., Element] | None = None) -> None: ...
    def _apply_functor(self, x: Element) -> Element: ...
    def __reduce__(self) -> tuple[type, tuple[Element, ...]]: ...
    def __call__(self, *args: Element) -> Element: ...
    def _act_convert(self, g: Element, x: Element) -> Element: ...
    def _act_(self, g: Element, x: Element) -> Element: ...
    def act(self, g: Element, x: Element) -> Element: ...
    def __invert__(self) -> Action: ...
    def is_left(self) -> bool: ...
    def _repr_(self) -> str: ...
    def _repr_name_(self) -> str: ...
    def actor(self) -> Parent | type: ...
    def underlying_set(self) -> Parent | type: ...
    def codomain(self) -> Parent | type: ...
    def domain(self) -> Parent | type: ...
    def left_domain(self) -> Parent | type: ...
    def right_domain(self) -> Parent | type: ...
    def operation(self) -> Callable[..., Element] | None: ...

class InverseAction(Action):
    def __init__(self, action: Action) -> None: ...
    def __reduce__(self) -> tuple[type, tuple[Element, ...]]: ...
    def _act_(self, g: Element, x: Element) -> Element: ...
    def codomain(self) -> Parent | type: ...
    def __invert__(self) -> Action: ...
    def _repr_name_(self) -> str: ...

class PrecomposedAction(Action):
    def __init__(self, action: Action, left_precomposition: Map | None, right_precomposition: Map | None) -> None: ...
    def __reduce__(self) -> tuple[type, tuple[Element, ...]]: ...
    def _act_(self, g: Element, x: Element) -> Element: ...
    def domain(self) -> Parent | type: ...
    def codomain(self) -> Parent | type: ...
    @property
    def left_precomposition(self) -> Map | None: ...
    @property
    def right_precomposition(self) -> Map | None: ...
    def __invert__(self) -> PrecomposedAction: ...
    def _repr_(self) -> str: ...

class ActionEndomorphism(Morphism):
    def __init__(self, action: Action, g: Element) -> None: ...
    def _extra_slots(self) -> dict[str, Element]: ...
    def _update_slots(self, _slots: dict[str, Element]) -> None: ...
    def _call_(self, x: Element) -> Element: ...
    def _repr_(self) -> str: ...
    def __mul__(self, right: ActionEndomorphism) -> Morphism: ...
    def __invert__(self) -> ActionEndomorphism | Action: ...
