class AdditiveMagmas:
    class ElementMethods:
        ...
    class ParentMethods:
        ...
    class SubcategoryMethods:
        ...
    class AdditiveUnital:
        class ElementMethods:
            ...
        class ParentMethods:
            ...
        class SubcategoryMethods:
            ...
