# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AlgebraModules:
    def __init__(self, A: builtins.object) -> None: ...
    @classmethod
    def an_instance(cls) -> _SageObject: ...
    def algebra(self) -> _SageObject: ...
    def super_categories(self) -> _SageObject: ...
