from sage.categories.category import Category
from sage.categories.category_with_axiom import CategoryWithAxiom_over_base_ring
from sage.structure.element import Element
from sage.structure.parent import Parent

class Algebras(CategoryWithAxiom_over_base_ring):
    def __init__(self, base: Parent | Category, name: str | None = None) -> None: ...
    class SubcategoryMethods:
        def Semisimple(self) -> Category: ...
        def Supercommutative(self) -> Category: ...
    class ParentMethods:
        def characteristic(self) -> object | None: ...
        def has_standard_involution(self) -> bool: ...
    class ElementMethods:
        ...
    class Quotients:
        class ParentMethods:
            def algebra_generators(self) -> tuple[Element, ...]: ...
    class CartesianProducts:
        def extra_super_categories(self) -> list[Category]: ...
    class TensorProducts:
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            ...
        class ElementMethods:
            ...
    class DualObjects:
        def extra_super_categories(self) -> list[Category]: ...
