from sage.categories.category import Category
from sage.categories.category_with_axiom import CategoryWithAxiom_over_base_ring
from sage.structure.element import Element
from sage.structure.parent import Parent

class AlgebrasWithBasis(CategoryWithAxiom_over_base_ring):
    def __init__(self, base: Parent | Category, name: str | None = None) -> None: ...
    class ParentMethods:
        def hochschild_complex(self, *args: object, **kwargs: object) -> Parent: ...
    class ElementMethods:
        ...
    class CartesianProducts:
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            def one_from_cartesian_product_of_one_basis(self) -> Element: ...
            def one(self) -> Element: ...
    class TensorProducts:
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            def one_basis(self) -> object | tuple[object, ...]: ...
            def product_on_basis(self, left: object, right: object) -> Element: ...
        class ElementMethods:
            ...
