from .category import Category
from typing import overload
from sage.structure.category_object import CategoryObject

class CategoryWithAxiom(Category):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, base_category: Category) -> None: ...
    def ambient_category(self) -> Category: ...
    def defining_predicates(self) -> tuple[str, ...]: ...
    def defining_predicate(self, candidate: CategoryObject) -> bool: ...
class CategoryWithAxiom_over_base_ring(CategoryWithAxiom): ...
class CategoryWithAxiom_singleton(CategoryWithAxiom): ...

all_axioms: tuple[str, ...]
