from collections.abc import Hashable, Iterable, Sequence
from typing import TypeAlias, overload

from sage.rings.integer import Integer

_CategoryArg: TypeAlias = Category | int | Integer | str | type | tuple[str, ...] | None
_CategoryOption: TypeAlias = Category | bool | int | Integer | str | type | tuple[str, ...] | None

class Category:
    parent_class: type
    Constructors: type
    def __init__(self) -> None: ...
    @staticmethod
    @overload
    def join(categories: Iterable[Category]) -> Category: ...
    @staticmethod
    @overload
    def join(categories: Iterable[Category], as_list: bool) -> Category | list[Category]: ...
    @staticmethod
    @overload
    def join(
        categories: Iterable[Category],
        as_list: bool = ...,
        ignore_axioms: tuple[str, ...] = ...,
        axioms: tuple[str, ...] = ...,
    ) -> Category | list[Category]: ...
    @staticmethod
    def meet(categories: Iterable[Category]) -> Category: ...
    @classmethod
    def __classcall__(cls, *args: _CategoryArg, **options: _CategoryOption) -> Category: ...
    @classmethod
    def _set_classcall(cls, value: type) -> None: ...
    def super_categories(self) -> list[Category]: ...
    def extra_super_categories(self) -> Sequence[Category]: ...
    def is_subcategory(self, other: Category) -> bool: ...
    def Hom(self, codomain: Category) -> Category: ...
    def HomCategory(self) -> Category: ...
    def EndCategory(self) -> Category: ...
    def AutCategory(self) -> Category: ...
    def base_category(self) -> Category: ...
    def additional_structure(self) -> Category | None: ...
    def Of(self, *args: _CategoryArg, **options: _CategoryOption) -> Category: ...
    def _with_axiom(self, axiom: str) -> Category: ...
    def _make_named_class(
        self,
        name: str,
        method_provider: type,
        cache: bool = ...,
        picklable: bool = ...,
    ) -> type: ...
    def _repr_object_names(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def __and__(self, other: Category) -> Category: ...
    def __or__(self, other: Category) -> Category: ...

class CategoryWithParameters(Category):
    def _make_named_class_key(self, name: str) -> Hashable: ...
class JoinCategory(Category): ...
