from typing import Self

from sage.categories.category import Category, CategoryWithParameters
from sage.rings.ideal import Ideal_generic as Ideal
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.category_object import CategoryObject
from sage.structure.parent import Parent
from sage.structure.sage_object import SageCoercionAtom

type _IdealInput = Element | SageCoercionAtom | Ideal | NumberFieldIdeal
type _IdealArg = _IdealInput | list[_IdealInput] | tuple[_IdealInput, ...]

class Category_over_base(CategoryWithParameters):
    def __init__(self, base: Category | CategoryObject, name: str | None = None) -> None: ...
    @classmethod
    def an_instance(cls) -> Self: ...
    def base(self) -> Category | Parent: ...

class AbelianCategory(Category):
    def is_abelian(self) -> bool: ...

class Category_over_base_ring(Category_over_base):
    def __init__(self, base: Category | CategoryObject, name: str | None = None) -> None: ...
    def base_ring(self) -> Category | Parent: ...
    def __contains__(self, x: object) -> bool: ...

class Category_in_ambient(Category):
    def __init__(self, ambient: CategoryObject, name: str | None = None) -> None: ...
    def ambient(self) -> Parent: ...

class Category_module(AbelianCategory, Category_over_base_ring): ...

class Category_ideal(Category_in_ambient):
    def ring(self) -> Parent: ...
    def __contains__(self, x: object) -> bool: ...
    def __call__(self, v: _IdealArg) -> Ideal | NumberFieldIdeal: ...
