from .category import Category

class Category_over_base(Category):
    def base(self) -> Category: ...

class Category_over_base_ring(Category_over_base):
    def __init__(self, base: Category, name: str | None = None) -> None: ...
    def base_ring(self) -> Category: ...

class AbelianCategory(Category): ...
class Category_module(AbelianCategory, Category_over_base_ring): ...
