from typing import overload

from sage.categories.category_types import Category_over_base_ring
from sage.structure.category_object import CategoryObject

from .category import Category

class CategoryWithAxiom(Category):
    _base_category_class_and_axiom: tuple[type[Category], str]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, base_category: Category) -> None: ...
    def ambient_category(self) -> Category: ...
    def base_category(self) -> Category: ...
    def defining_predicates(self) -> tuple[str, ...]: ...
    def defining_predicate(self, candidate: CategoryObject) -> bool: ...

class CategoryWithAxiom_over_base_ring(CategoryWithAxiom, Category_over_base_ring): ...
class CategoryWithAxiom_singleton(CategoryWithAxiom): ...

all_axioms: tuple[str, ...]

def uncamelcase(name: str, separator: str = "_") -> str: ...
def base_category_class_and_axiom(cls: type[Category]) -> tuple[type[Category], str]: ...
def create_axiom(category_classes: type[Category] | tuple[type[Category], ...], axiom: str) -> None: ...
