from sage.categories.category import Category
from sage.categories.functor import Functor
from sage.structure.element import Element

from sage.categories.morphism import Morphism
class ChainComplexes(Category):
    def super_categories(self) -> list[Category]: ...
    class ParentMethods:
        def homology(self, n: int | None = None) -> Element: ...
        def differential(self, *args: object, **kwargs: object) -> Element: ...
        def lift_from_homology(self, x: Element) -> Element: ...
        def reduce_to_homology(self, x: Element, n: int | None = None) -> Element: ...

class HomologyFunctor(Functor):
    def __init__(self, domain: Category, n: int | None = None) -> None: ...
    def _apply_functor(self, x: Element) -> Element: ...
    def _apply_functor_to_morphism(self, f: Element) -> Morphism: ...
