from collections.abc import Iterator

from sage.categories.category import Category
from sage.categories.category_singleton import Category_singleton
from sage.structure.parent import Parent
from sage.structure.element import Element

class ClassicalCrystals(Category_singleton):
    def super_categories(self) -> list[Category]: ...
    def example(self, n: int = 3) -> Parent: ...
    def additional_structure(self) -> None: ...
    class ParentMethods:
        def demazure_character(self, w: object, f: object = None) -> Element: ...
        def character(self, R: Parent | None = None) -> Element: ...
        def __iter__(self) -> Iterator[Element]: ...
        def _test_fast_iter(self, **options: object) -> None: ...
        def cardinality(self) -> int | float: ...
    class ElementMethods:
        def lusztig_involution(self) -> Element: ...
    class TensorProducts:
        def extra_super_categories(self) -> list[Category]: ...
