from sage.categories.category import Category
from sage.combinat.colored_permutations import ColoredPermutations

class ComplexReflectionGroups:
    def super_categories(self) -> list[Category]: ...
    def additional_structure(self) -> None: ...
    def example(self) -> ColoredPermutations: ...

    class ParentMethods:
        def rank(self) -> int: ...

    class Finite(Category):
        ...
