# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ComplexReflectionOrGeneralizedCoxeterGroups:
    def super_categories(self) -> _SageObject: ...
    class SubcategoryMethods:
        def Irreducible(self) -> _SageObject: ...
    class ParentMethods:
        def index_set(self) -> _SageObject: ...
        def simple_reflection(self, i: builtins.int) -> _SageObject: ...
        def simple_reflections(self) -> _SageObject: ...
        def number_of_simple_reflections(self) -> _SageObject: ...
        def group_generators(self) -> _SageObject: ...
        semigroup_generators: _SageObject
        def simple_reflection_orders(self) -> _SageObject: ...
        def some_elements(self) -> _SageObject: ...
        def reflection_index_set(self) -> _SageObject: ...
        def reflection(self, i: builtins.int) -> _SageObject: ...
        def reflections(self) -> _SageObject: ...
        def hyperplane_index_set(self) -> _SageObject: ...
        def distinguished_reflection(self, i: builtins.int) -> _SageObject: ...
        def distinguished_reflections(self) -> _SageObject: ...
        def from_reduced_word(self, word: builtins.object, word_type: builtins.str = ...) -> _SageObject: ...
        def irreducible_component_index_sets(self) -> _SageObject: ...
        def irreducible_components(self) -> _SageObject: ...
        def number_of_irreducible_components(self) -> _SageObject: ...
        def is_irreducible(self) -> builtins.bool: ...
        def is_reducible(self) -> builtins.bool: ...
    class ElementMethods:
        def apply_simple_reflection_left(self, i: builtins.int) -> _SageObject: ...
        def apply_simple_reflection_right(self, i: builtins.int) -> _SageObject: ...
        def apply_simple_reflection(self, i: builtins.int, side: builtins.str = ...) -> _SageObject: ...
        def apply_simple_reflections(self, word: builtins.object, side: builtins.str = ..., type: builtins.str = ...) -> _SageObject: ...
        def apply_reflections(self, word: builtins.object, side: builtins.str = ..., word_type: builtins.str = ...) -> _SageObject: ...
        def __invert__(self) -> Self: ...
        def apply_conjugation_by_simple_reflection(self, i: builtins.int) -> _SageObject: ...
        def reflection_length(self) -> _SageObject: ...
        def is_reflection(self) -> builtins.bool: ...
    class Irreducible:
        class ParentMethods:
            def irreducible_components(self) -> _SageObject: ...
