from typing import TYPE_CHECKING

from sage.categories.category import Category
from sage.categories.category_singleton import Category_singleton

if TYPE_CHECKING:
    from sage.combinat.colored_permutations import ColoredPermutations

class ComplexReflectionGroups(Category_singleton):
    def super_categories(self) -> list[Category]: ...
    def additional_structure(self) -> None: ...
    def example(self) -> ColoredPermutations: ...
    class ParentMethods:
        def rank(self) -> int: ...
    class Finite(Category): ...
