class DiscreteValuationRings:
    class ElementMethods:
        ...
    class ParentMethods:
        ...
class DiscreteValuationFields:
    class ElementMethods:
        ...
    class ParentMethods:
        ...
