from sage.categories.category import Category
from sage.categories.category_types import Category_over_base_ring
from sage.categories.homsets import Homsets
from sage.rings.function_field.drinfeld_modules.drinfeld_module import DrinfeldModule
from sage.rings.integer import Integer
from sage.rings.morphism import RingHomomorphism
from sage.rings.polynomial.ore_polynomial_element import OrePolynomial
from sage.rings.polynomial.ore_polynomial_ring import OrePolynomialRing
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.polynomial.polynomial_ring import PolynomialRing_generic
from sage.rings.ring_extension import RingExtension_generic
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput, Parent

class DrinfeldModules(Category_over_base_ring):
    def __init__(self, base_morphism: RingHomomorphism, name: str = ...) -> None: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def Homsets(self) -> Homsets: ...
    def Endsets(self) -> Category: ...
    def A_field(self) -> RingExtension_generic: ...
    def base(self) -> Parent[RingElement]: ...
    def base_morphism(self) -> RingHomomorphism: ...
    def base_over_constants_field(self) -> RingExtension_generic: ...
    def characteristic(self) -> Polynomial | Integer | None: ...
    def function_ring(self) -> PolynomialRing_generic: ...
    def constant_coefficient(self) -> RingElement: ...
    def ore_polring(self) -> OrePolynomialRing: ...
    def ore_variable(self) -> OrePolynomial: ...
    def object(
        self,
        gen: OrePolynomial
        | list[ElementConstructorInput]
        | tuple[ElementConstructorInput, ...],
    ) -> DrinfeldModule: ...
    def random_object(self, rank: int | Integer) -> DrinfeldModule: ...
    def super_categories(self) -> list[Category]: ...
