from collections.abc import Callable, Iterator, Sequence
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageCoercionAtom

type EnumeratedElementInput = Element | SageCoercionAtom | Sequence[SageCoercionAtom]

class EnumeratedSets:
    class ElementMethods:
        ...
    class ParentMethods:
        def __iter__(self) -> Iterator[Element]: ...
        def __len__(self) -> int: ...
        def __getitem__(self, i: int | Integer | slice) -> Element | list[Element]: ...
        def _an_element_(self) -> Element: ...
        def is_empty(self) -> bool: ...
        def random_element(self) -> Element: ...
        def rank(self, x: EnumeratedElementInput) -> Integer | None: ...
        def map(self, f: Callable[[EnumeratedElementInput], EnumeratedElementInput], name: str | None = None, *, is_injective: bool = True) -> Parent: ...
