from sage.structure.element import Element
from sage.structure.parent import Parent

class FacadeSets:
    class ParentMethods:
        def _element_constructor_(self, element: object) -> Element: ...
        def facade_for(self) -> tuple[Parent, ...] | bool: ...
        def is_parent_of(self, element: object) -> bool: ...
        def _an_element_(self) -> Element: ...
