from sage.categories.filtered_modules import FilteredModulesCategory
from sage.categories.category import Category
from sage.categories.morphism import SetMorphism

class FilteredAlgebrasWithBasis(FilteredModulesCategory):
    def super_categories(self) -> list[Category]: ...

    class ParentMethods:
        def graded_algebra(self) -> Category: ...
        def to_graded_conversion(self) -> SetMorphism: ...
        def from_graded_conversion(self) -> SetMorphism: ...
        def projection(self, i: int) -> SetMorphism: ...
        def induced_graded_map(self, other: object, f: object) -> SetMorphism: ...
        
    class ElementMethods: ...
