# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FilteredModulesWithBasis:
    class ParentMethods:
        def basis(self, d: builtins.object = ...) -> _SageObject: ...
        def homogeneous_component_basis(self, d: builtins.object) -> _SageObject: ...
        def homogeneous_component(self, d: builtins.object) -> _SageObject: ...
        def hilbert_series(self, prec: builtins.int = ...) -> _SageObject: ...
        def graded_algebra(self) -> _SageObject: ...
        def to_graded_conversion(self) -> _SageObject: ...
        def from_graded_conversion(self) -> _SageObject: ...
        def projection(self, i: builtins.int) -> _SageObject: ...
        def induced_graded_map(self, other: builtins.object, f: builtins.object) -> _SageObject: ...
    class ElementMethods:
        def is_homogeneous(self) -> builtins.bool: ...
        def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
        def homogeneous_degree(self) -> _SageObject: ...
        degree: _SageObject
        def maximal_degree(self) -> _SageObject: ...
        def homogeneous_component(self, n: builtins.int) -> _SageObject: ...
        def truncate(self, n: builtins.int) -> _SageObject: ...
    class Subobjects:
        class ParentMethods:
            def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
        class ElementMethods:
            def degree(self) -> _SageObject: ...
            def maximal_degree(self) -> _SageObject: ...
    class FiniteDimensional:
        class ParentMethods:
            def hilbert_series(self, prec: builtins.int = ...) -> _SageObject: ...
