# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FinitelyGeneratedLambdaBracketAlgebras:
    class ParentMethods:
        def ngens(self) -> _SageObject: ...
        def gen(self, i: builtins.int) -> _SageObject: ...
        def some_elements(self) -> _SageObject: ...
    class Graded:
        ...
