# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FiniteDimensionalNilpotentLieAlgebrasWithBasis:
    class ParentMethods:
        def lie_group(self, name: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...
        def step(self) -> _SageObject: ...
        def is_nilpotent(self) -> builtins.bool: ...
