from sage.categories.category import Category
from sage.structure.parent import Parent

class FiniteCrystals:
    def extra_super_categories(self) -> list[Category]: ...
    def example(self, n: int = 3) -> Parent: ...
    class TensorProducts:
        def extra_super_categories(self) -> list[Category]: ...
