# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FiniteComplexReflectionGroups:
    def example(self) -> _SageObject: ...
    class SubcategoryMethods:
        def WellGenerated(self) -> _SageObject: ...
    class ParentMethods:
        def degrees(self) -> _SageObject: ...
        def codegrees(self) -> _SageObject: ...
        def number_of_reflection_hyperplanes(self) -> _SageObject: ...
        def number_of_reflections(self) -> _SageObject: ...
        def rank(self) -> _SageObject: ...
        def cardinality(self) -> _SageObject: ...
        def is_well_generated(self) -> builtins.bool: ...
        def is_real(self) -> builtins.bool: ...
        def base_change_matrix(self) -> _SageObject: ...
        def milnor_fiber_poset(self) -> _SageObject: ...
    class ElementMethods:
        def to_matrix(self) -> _SageObject: ...
        def character_value(self) -> _SageObject: ...
        def reflection_length(self, in_unitary_group: builtins.bool = ...) -> _SageObject: ...
    class Irreducible:
        def example(self) -> _SageObject: ...
        class ParentMethods:
            def coxeter_number(self) -> _SageObject: ...
            def absolute_order_ideal(self, gens: builtins.object = ..., in_unitary_group: builtins.bool = ..., return_lengths: builtins.bool = ...) -> _SageObject: ...
            def noncrossing_partition_lattice(self, c: builtins.object = ..., L: builtins.object = ..., in_unitary_group: builtins.bool = ...) -> _SageObject: ...
            def generalized_noncrossing_partitions(self, m: builtins.int, c: builtins.object = ..., positive: builtins.bool = ...) -> _SageObject: ...
            def absolute_poset(self, in_unitary_group: builtins.bool = ...) -> _SageObject: ...
    class WellGenerated:
        def example(self) -> _SageObject: ...
        class ParentMethods:
            def is_well_generated(self) -> builtins.bool: ...
            coxeter_element: _SageObject
            standard_coxeter_elements: _SageObject
            def coxeter_elements(self) -> _SageObject: ...
            def milnor_fiber_complex(self) -> _SageObject: ...
        class Irreducible:
            def example(self) -> _SageObject: ...
            class ParentMethods:
                def coxeter_number(self) -> _SageObject: ...
                def number_of_reflections_of_full_support(self) -> _SageObject: ...
                def rational_catalan_number(self, p: builtins.int, polynomial: builtins.bool = ...) -> _SageObject: ...
                def fuss_catalan_number(self, m: builtins.int, positive: builtins.bool = ..., polynomial: builtins.bool = ...) -> _SageObject: ...
                def catalan_number(self, positive: builtins.bool = ..., polynomial: builtins.bool = ...) -> _SageObject: ...
