from sage.categories.category import Category
from sage.categories.category_with_axiom import CategoryWithAxiom_over_base_ring
from sage.matrix.matrix2 import Matrix
from sage.structure.element import Element
from sage.structure.parent import Parent

class FiniteDimensionalAlgebrasWithBasis(CategoryWithAxiom_over_base_ring):
    def __init__(self, base: Parent | Category, name: str | None = None) -> None: ...
    class ParentMethods:
        def radical_basis(self) -> tuple[Element, ...]: ...
        def radical(self) -> Parent: ...
        def semisimple_quotient(self) -> Parent: ...
        def center_basis(self) -> tuple[Element, ...]: ...
        def center(self) -> Parent: ...
        def subalgebra(self, basis: object, **kwargs: object) -> Parent: ...
        def ideal_submodule(self, generators: object, **kwargs: object) -> Parent: ...
        def principal_ideal(self, generator: Element, side: str = "twosided") -> Parent: ...
        def orthogonal_idempotents_central_mod_radical(self) -> tuple[Element, ...]: ...
        def idempotent_lift(self, x: Element) -> Element: ...
        def cartan_invariants_matrix(self) -> Matrix: ...
        def isotypic_projective_modules(self, side: str = "left") -> tuple[Parent, ...]: ...
        def peirce_summand(self, left: Element, right: Element | None = None) -> Parent: ...
        def peirce_decomposition(self, idempotents: object) -> tuple[Parent, ...]: ...
        def is_identity_decomposition_into_orthogonal_idempotents(
            self,
            idempotents: object,
        ) -> bool: ...
        def is_commutative(self) -> bool: ...
    class ElementMethods:
        def to_matrix(self, side: str = "left") -> Matrix: ...
    class Cellular:
        class ParentMethods:
            def cell_poset(self) -> Parent: ...
            def cell_module_indices(self) -> tuple[object, ...]: ...
            def cellular_involution(self, x: Element) -> Element: ...
            def cells(self) -> tuple[object, ...]: ...
            def cellular_basis(self) -> tuple[Element, ...]: ...
            def cell_module(self, index: object) -> Parent: ...
            def simple_module_parameterization(self) -> tuple[object, ...]: ...
        class ElementMethods:
            def cellular_involution(self) -> Element: ...
        class TensorProducts:
            def extra_super_categories(self) -> list[Category]: ...
            class ParentMethods:
                def cell_poset(self) -> Parent: ...
                def cell_module_indices(self) -> tuple[object, ...]: ...
                def cellular_involution(self, x: Element) -> Element: ...
    class SubcategoryMethods:
        def Cellular(self) -> Category: ...
