from collections.abc import Iterable
from typing import overload, Literal
import sage.categories.category as category
from sage.categories.category_with_axiom import CategoryWithAxiom

from sage.rings.ring import Ring
from sage.combinat.posets.posets import FinitePoset
from sage.combinat.posets.lattices import FiniteLatticePoset
from sage.geometry.polyhedron.base import Polyhedron_base
from sage.topology.simplicial_complex import SimplicialComplex
from sage.graphs.graph import Graph
from sage.structure.element import Element
from sage.groups.group import Group

class FiniteCoxeterGroups(CategoryWithAxiom):
    def extra_super_categories(self) -> list[category.Category]: ...

    class ParentMethods:
        @property
        def w0(self) -> Element: ...
        @overload
        def long_element(self, index_set: Iterable[int] | None = ..., as_word: Literal[False] = False) -> Element: ...
        @overload
        def long_element(self, index_set: Iterable[int] | None, as_word: Literal[True]) -> list[int]: ...
        def bruhat_poset(self, facade: bool = ...) -> FinitePoset: ...
        def shard_poset(self, side: str = ...) -> FinitePoset: ...
        def bhz_poset(self) -> FinitePoset: ...
        def degrees(self) -> tuple[int, ...]: ...
        def codegrees(self) -> tuple[int, ...]: ...
        def weak_poset(self, side: str = ..., facade: bool = ...) -> FinitePoset: ...
        def inversion_sequence(self, word: Iterable[int]) -> list[Element]: ...
        def reflections_from_w0(self) -> list[Element]: ...
        def m_cambrian_lattice(self, c: Element, m: int = ..., on_roots: bool = ...) -> FiniteLatticePoset: ...
        def cambrian_lattice(self, c: Element, on_roots: bool = ...) -> FiniteLatticePoset: ...
        def is_real(self) -> bool: ...
        def permutahedron(self, point: Element | None = ..., base_ring: Ring | None = ...) -> Polyhedron_base: ...
        def coxeter_poset(self) -> FinitePoset: ...
        def coxeter_complex(self) -> SimplicialComplex: ...

    class ElementMethods:
        def absolute_length(self) -> int: ...
        def bruhat_upper_covers(self) -> list[Element]: ...
        def coxeter_knuth_neighbor(self, w: Iterable[int]) -> set[tuple[int, ...]]: ...
        def coxeter_knuth_graph(self) -> Graph: ...
        def is_coxeter_element(self) -> bool: ...
        def covered_reflections_subgroup(self) -> Group: ...
