from collections.abc import Iterable
from sage.categories.category import Category
from sage.categories.category_with_axiom import CategoryWithAxiom_over_base_ring
from sage.categories.graded_modules import GradedModulesCategory
from sage.categories.signed_tensor import SignedTensorProductsCategory
from sage.modules.fp_graded.free_module import FreeGradedModule
from sage.rings.lazy_series_ring import LazyCompletionGradedAlgebra
from sage.structure.element import Element
from sage.structure.parent import Parent

class GradedAlgebrasWithBasis(GradedModulesCategory):
    class ParentMethods:
        def graded_algebra(self) -> Parent: ...
        def free_graded_module(self, generator_degrees: Iterable[int], names: str | Iterable[str] | None = None) -> FreeGradedModule: ...
        def formal_series_ring(self) -> LazyCompletionGradedAlgebra: ...
        completion = formal_series_ring
    class ElementMethods: ...
    class FiniteDimensional(CategoryWithAxiom_over_base_ring):
        class ParentMethods:
            def top_degree(self) -> int: ...
    class SignedTensorProducts(SignedTensorProductsCategory):
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            def one_basis(self) -> tuple[int, ...]: ...
            def product_on_basis(self, t0: tuple[int, ...], t1: tuple[int, ...]) -> Element: ...
