# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GradedModulesWithBasis:
    class ParentMethods:
        def degree_negation(self, element: builtins.object) -> _SageObject: ...
        def submodule(self, gens: builtins.object, check: builtins.bool = ..., already_echelonized: builtins.bool = ..., unitriangular: builtins.bool = ..., support_order: builtins.object = ..., category: builtins.object = ..., *args: builtins.object, **opts: builtins.object) -> _SageObject: ...
        def quotient_module(self, submodule: builtins.object, check: builtins.bool = ..., already_echelonized: builtins.bool = ..., category: builtins.object = ...) -> _SageObject: ...
    class ElementMethods:
        def degree_negation(self) -> _SageObject: ...
    class Quotients:
        class ParentMethods:
            def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
        class ElementMethods:
            def degree(self) -> _SageObject: ...
