from sage.categories.category import Category
from sage.categories.category_with_axiom import CategoryWithAxiom_over_base_ring
from sage.categories.graded_modules import GradedModulesCategory
from sage.categories.with_realizations import WithRealizationsCategory
from sage.categories.examples.graded_connected_hopf_algebras_with_basis import GradedConnectedCombinatorialHopfAlgebraWithPrimitiveGenerator
from sage.structure.element import Element

class GradedHopfAlgebrasWithBasis(GradedModulesCategory):
    def example(self) -> GradedConnectedCombinatorialHopfAlgebraWithPrimitiveGenerator: ...
    class ParentMethods: ...
    class ElementMethods: ...
    class WithRealizations(WithRealizationsCategory):
        def super_categories(self) -> list[Category]: ...
    class Connected(CategoryWithAxiom_over_base_ring):
        def example(self) -> GradedConnectedCombinatorialHopfAlgebraWithPrimitiveGenerator: ...
        class ParentMethods:
            def counit_on_basis(self, i: int) -> Element: ...
            def antipode_on_basis(self, index: int) -> Element: ...
        class ElementMethods: ...
