# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GroupAlgebras:
    def extra_super_categories(self) -> _SageObject: ...
    def example(self, G: builtins.object = ...) -> _SageObject: ...
    class ParentMethods:
        def __init_extra__(self) -> _SageObject: ...
        def group(self) -> _SageObject: ...
        def center_basis(self) -> _SageObject: ...
        def coproduct_on_basis(self, g: builtins.object) -> _SageObject: ...
        def antipode_on_basis(self, g: builtins.object) -> _SageObject: ...
        def counit_on_basis(self, g: builtins.object) -> _SageObject: ...
        def counit(self, x: builtins.object) -> _SageObject: ...
        def is_integral_domain(self, proof: builtins.bool = ...) -> builtins.bool: ...
    class ElementMethods:
        def central_form(self) -> _SageObject: ...
