from sage.categories.algebra_functor import AlgebrasCategory
from sage.categories.category import Category
from sage.combinat.free_module import CombinatorialFreeModule
from sage.groups.group import Group
from sage.structure.element import Element, RingElement


class GroupAlgebras(AlgebrasCategory):
    def extra_super_categories(self) -> list[Category]: ...
    def example(
        self,
        G: Group | None = ...,
    ) -> CombinatorialFreeModule: ...

    class ParentMethods:
        def __init_extra__(self) -> None: ...
        def _latex_(self) -> str: ...
        def group(self) -> Group: ...
        def center_basis(self) -> tuple[Element, ...]: ...
        def coproduct_on_basis(self, g: Element) -> Element: ...
        def antipode_on_basis(self, g: Element) -> Element: ...
        def counit_on_basis(self, g: Element) -> RingElement: ...
        def counit(self, x: Element) -> RingElement: ...
        def is_integral_domain(self, proof: bool = ...) -> bool: ...

    class ElementMethods:
        def central_form(self) -> CombinatorialFreeModule.Element: ...
