from collections.abc import Sequence

class Homsets:
    def super_categories(self) -> Sequence[object]: ...
    class ParentMethods:
        ...
    class SubcategoryMethods:
        ...
    class Endset:
        class ParentMethods:
            ...
class HomsetsCategory:
    ...

class HomsetsOf(HomsetsCategory):
    ...
