class Homsets:
    class ParentMethods:
        ...
    class SubcategoryMethods:
        ...
    class Endset:
        class ParentMethods:
            ...
class HomsetsCategory:
    ...

class HomsetsOf(HomsetsCategory):
    ...
