from sage.categories.bialgebras import Bialgebras
from sage.categories.category import Category
from sage.categories.category_types import Category_over_base_ring
from sage.categories.realizations import RealizationsCategory
from sage.categories.super_modules import SuperModulesCategory
from sage.categories.tensor import TensorProductsCategory
from sage.structure.element import Element

class HopfAlgebras(Category_over_base_ring):
    def super_categories(self) -> list[Category]: ...
    def dual(self) -> Category: ...
    class ElementMethods:
        def antipode(self) -> Element: ...
    class ParentMethods: ...
    class Morphism(Category): ...
    class Super(SuperModulesCategory):
        def dual(self) -> Category: ...
        class ElementMethods:
            def antipode(self) -> Element: ...
    class TensorProducts(TensorProductsCategory):
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods: ...
        class ElementMethods: ...
    class DualCategory(Category_over_base_ring):
        class ParentMethods: ...
    class Realizations(RealizationsCategory):
        class ParentMethods:
            def antipode_by_coercion(self, x: Element) -> Element: ...
