import builtins
from sage.categories.bialgebras import Bialgebras
from sage.categories.category import Category
from sage.categories.category_types import Category_over_base_ring
from sage.categories.realizations import RealizationsCategory
from sage.categories.super_modules import SuperModulesCategory
from sage.categories.tensor import TensorProductsCategory

class HopfAlgebras(Category_over_base_ring):  # type: ignore[misc]
    def super_categories(self) -> list[Category]: ...
    def dual(self) -> Category: ...
    class ElementMethods:
        def antipode(self) -> builtins.object: ...
    class ParentMethods: ...
    class Morphism(Category): ...  # type: ignore[misc]
    class Super(SuperModulesCategory):  # type: ignore[misc]
        def dual(self) -> Category: ...
        class ElementMethods:
            def antipode(self) -> builtins.object: ...
    class TensorProducts(TensorProductsCategory):  # type: ignore[misc]
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods: ...
        class ElementMethods: ...
    class DualCategory(Category_over_base_ring):  # type: ignore[misc]
        class ParentMethods: ...
    class Realizations(RealizationsCategory):  # type: ignore[misc]
        class ParentMethods:
            def antipode_by_coercion(self, x: builtins.object) -> builtins.object: ...
