from sage.structure.element import Element

class InfiniteEnumeratedSets:
    class ParentMethods:
        def random_element(self) -> Element: ...
        def tuple(self) -> tuple[Element, ...]: ...
        def list(self) -> list[Element]: ...
