# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KahlerAlgebras:
    def super_categories(self) -> _SageObject: ...
    class ParentMethods:
        def poincare_pairing(self, a: builtins.object, b: builtins.object) -> _SageObject: ...
        def lefschetz_element(self) -> _SageObject: ...
        def hodge_riemann_relations(self, k: builtins.int) -> _SageObject: ...
