# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LTrivialSemigroups:
    def extra_super_categories(self) -> _SageObject: ...
    def RTrivial_extra_super_categories(self) -> _SageObject: ...
    def Commutative_extra_super_categories(self) -> _SageObject: ...
