from sage.categories.category import Category
from sage.categories.category_types import Category_over_base_ring
from sage.structure.element import Element
from sage.structure.parent import Parent

class LambdaBracketAlgebras(Category_over_base_ring):
    def super_categories(self) -> list[Category]: ...
    def _repr_object_names(self) -> str: ...
    class SubcategoryMethods:
        def FinitelyGeneratedAsLambdaBracketAlgebra(self) -> Category: ...
        def FinitelyGenerated(self) -> Category: ...
    class ParentMethods:
        def ideal(self, *gens: object, **kwds: object) -> Parent: ...
    class ElementMethods:
        def bracket(self, rhs: Element) -> Element: ...
        def _bracket_(self, rhs: Element) -> Element: ...
        def nproduct(self, rhs: Element, n: int) -> Element: ...
        def _nproduct_(self, rhs: Element, n: int) -> Element: ...
        def T(self, n: int = 1) -> Element: ...
