# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LieAlgebrasWithBasis:
    def example(self, gens: builtins.object = ...) -> _SageObject: ...
    Graded: _SageObject
    class ParentMethods:
        def bracket_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def module(self) -> _SageObject: ...
        def from_vector(self, v: builtins.object, order: builtins.object = ..., coerce: builtins.bool = ...) -> _SageObject: ...
        def dimension(self) -> _SageObject: ...
        def pbw_basis(self, basis_key: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
        poincare_birkhoff_witt_basis: _SageObject
    class ElementMethods:
        def to_vector(self, order: builtins.object = ...) -> _SageObject: ...
        def lift(self) -> _SageObject: ...
