# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LoopCrystals:
    def super_categories(self) -> _SageObject: ...
    def example(self, n: builtins.int = ...) -> _SageObject: ...
    class ParentMethods:
        def weight_lattice_realization(self) -> _SageObject: ...
        def digraph(self, subset: builtins.object = ..., index_set: builtins.object = ...) -> _SageObject: ...

class RegularLoopCrystals:
    def super_categories(self) -> _SageObject: ...
    class ElementMethods:
        def classical_weight(self) -> _SageObject: ...

class KirillovReshetikhinCrystals:
    def super_categories(self) -> _SageObject: ...
    class ParentMethods:
        def r(self) -> _SageObject: ...
        def s(self) -> _SageObject: ...
        def classical_decomposition(self) -> _SageObject: ...
        def classically_highest_weight_vectors(self) -> _SageObject: ...
        def cardinality(self) -> _SageObject: ...
        def maximal_vector(self) -> _SageObject: ...
        def module_generator(self) -> _SageObject: ...
        def affinization(self) -> _SageObject: ...
        def R_matrix(self, K: builtins.int) -> _SageObject: ...
        def local_energy_function(self, B: builtins.object) -> _SageObject: ...
        def b_sharp(self) -> _SageObject: ...
        def is_perfect(self, ell: builtins.object = ...) -> builtins.bool: ...
        def level(self) -> _SageObject: ...
        def q_dimension(self, q: builtins.int = ..., prec: builtins.int = ..., use_product: builtins.bool = ...) -> _SageObject: ...
    class ElementMethods:
        def lusztig_involution(self) -> _SageObject: ...
        def energy_function(self) -> _SageObject: ...
    class TensorProducts:
        def extra_super_categories(self) -> _SageObject: ...
        class ParentMethods:
            def maximal_vector(self) -> _SageObject: ...
            def classically_highest_weight_vectors(self) -> _SageObject: ...
            def cardinality(self) -> _SageObject: ...
            def one_dimensional_configuration_sum(self, q: builtins.int = ..., group_components: builtins.bool = ...) -> _SageObject: ...
        class ElementMethods:
            def energy_function(self, algorithm: builtins.str = ...) -> _SageObject: ...
            def affine_grading(self) -> _SageObject: ...
            def e_string_to_ground_state(self) -> _SageObject: ...

class LocalEnergyFunction:
    def __init__(self, B: builtins.object, Bp: builtins.object, normalization: builtins.int = ...) -> None: ...
