class Magmas:
    class ElementMethods:
        ...
    class ParentMethods:
        ...
    class SubcategoryMethods:
        ...
    class Unital:
        class ElementMethods:
            ...
        class ParentMethods:
            ...
        class SubcategoryMethods:
            ...
    class Commutative:
        class ParentMethods:
            ...
