from sage.categories.category import Category
from sage.structure.element import Element
from sage.structure.parent import Parent

class MagmaticAlgebras:
    def __init__(self, base: Parent | Category, name: str | None = None) -> None: ...
    class ParentMethods:
        def algebra_generators(self) -> tuple[Element, ...]: ...
    class WithBasis:
        class ParentMethods:
            def algebra_generators(self) -> tuple[Element, ...]: ...
            def product_on_basis(self, left: object, right: object) -> Element: ...
            def product(self, left: Element, right: Element) -> Element: ...
        class FiniteDimensional:
            class ParentMethods:
                def to_finite_dimensional_algebra(self) -> Parent: ...
                def derivations_basis(self) -> tuple[Element, ...]: ...
