from .covariant_functorial_construction import RegressiveCovariantConstructionCategory
from .category_with_axiom import CategoryWithAxiom

class MetricSpacesCategory(RegressiveCovariantConstructionCategory): ...

class MetricSpaces(MetricSpacesCategory):
    class ElementMethods:
        ...
    class ParentMethods:
        ...
    class SubcategoryMethods:
        def Complete(self) -> CategoryWithAxiom: ...
    class Complete(CategoryWithAxiom):
        ...
