from collections.abc import Callable, Iterable, Iterator

from sage.categories.category import Category
from sage.categories.morphism import Morphism
from sage.structure.element import Element
from sage.structure.parent import Parent

class ModulesWithBasis:
    class ParentMethods:
        def basis(self) -> object | None: ...
        def module_morphism(self, *args: object, **kwargs: object) -> Morphism: ...
        def echelon_form(self, elements: object, **kwargs: object) -> tuple[Element, ...]: ...
        def submodule(self, generators: object, **kwargs: object) -> Parent: ...
        def quotient_module(self, submodule: object, check: bool = True, **kwds: object) -> Parent: ...
        def tensor(self, *parents: Parent) -> Parent: ...
        def intersection(self, submodule: object) -> Parent: ...
        def cardinality(self) -> int: ...
        def is_finite(self) -> bool: ...
        def monomial(self, index: object) -> Element: ...
        def sum_of_monomials(self, indices: Iterable[object]) -> Element: ...
        def monomial_or_zero_if_none(self, index: object | None) -> Element: ...
        def term(self, index: object, coeff: object) -> Element: ...
        def sum_of_terms(self, terms: Iterable[tuple[object, object]]) -> Element: ...
        def dimension(self) -> int: ...
        def rank(self) -> int: ...
        def random_element(self, *args: object, **kwargs: object) -> Element: ...
    class ElementMethods:
        def monomial_coefficients(self, copy: bool = True) -> dict[object, object]: ...
        def coefficient(self, index: object) -> object | None: ...
        def items(self) -> Iterator[tuple[object, object]]: ...
        def is_zero(self) -> bool: ...
        def length(self) -> int: ...
        def support(self) -> list[object]: ...
        def monomials(self) -> list[Element]: ...
        def terms(self) -> list[Element]: ...
        def coefficients(self) -> list[object]: ...
        def support_of_term(self) -> object | None: ...
        def leading_support(self, *args: object, **kwargs: object) -> object | None: ...
        def leading_item(self, *args: object, **kwargs: object) -> tuple[object, object]: ...
        def leading_monomial(self, *args: object, **kwargs: object) -> Element: ...
        def leading_coefficient(self, *args: object, **kwargs: object) -> object | None: ...
        def leading_term(self, *args: object, **kwargs: object) -> Element: ...
        def trailing_support(self, *args: object, **kwargs: object) -> object | None: ...
        def trailing_item(self, *args: object, **kwargs: object) -> tuple[object, object]: ...
        def trailing_monomial(self, *args: object, **kwargs: object) -> Element: ...
        def trailing_coefficient(self, *args: object, **kwargs: object) -> object | None: ...
        def trailing_term(self, *args: object, **kwargs: object) -> Element: ...
        def map_coefficients(self, f: Callable[[object], object], **kwargs: object) -> Element: ...
        def map_support(self, f: Callable[[object], object], **kwargs: object) -> Element: ...
        def map_support_skip_none(self, f: Callable[[object], object | None], **kwargs: object) -> Element: ...
        def map_item(self, f: Callable[[object, object], tuple[object, object]], **kwargs: object) -> Element: ...
        def tensor(self, *elements: Element) -> Element: ...
    class Homsets:
        class ParentMethods:
            ...
    class MorphismMethods:
        def on_basis(self) -> Callable[[object], Element]: ...
    class CartesianProducts:
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            ...
    class TensorProducts:
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            ...
        class ElementMethods:
            def apply_multilinear_morphism(self, f: Callable[..., object]) -> object | None: ...
    class DualObjects:
        def extra_super_categories(self) -> list[Category]: ...
