from collections.abc import Callable, Iterable

from sage.categories.category import Category
from sage.categories.category_types import Category_module
from sage.categories.morphism import Morphism, SetMorphism
from sage.categories.tensor import TensorProductFunctor
from sage.matrix.matrix2 import Matrix
from sage.structure.category_object import CategoryObject
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageCoercionAtom

class Modules(Category_module):
    def __init__(self, base_ring: Category | CategoryObject, dispatch: bool = True) -> None: ...
    class SubcategoryMethods:
        def base_ring(self) -> Parent: ...
        def TensorProducts(self) -> Category: ...
        def DualObjects(self) -> Category: ...
        def FiniteDimensional(self) -> Category: ...
        def FinitelyPresented(self) -> Category: ...
        def Filtered(self) -> Category: ...
        def Graded(self) -> Category: ...
        def Super(self) -> Category: ...
        def WithBasis(self) -> Category: ...
    class FiniteDimensional:
        def extra_super_categories(self) -> list[Category]: ...
        class TensorProducts:
            def extra_super_categories(self) -> list[Category]: ...
    class FinitelyPresented:
        def extra_super_categories(self) -> list[Category]: ...
    class ParentMethods:
        def linear_combination(
            self,
            iter_of_elements_coeff: Iterable[tuple[Element, Element | SageCoercionAtom]],
            factor_on_left: bool = True,
        ) -> Element: ...
        def tensor_square(self) -> Parent: ...
        def module_morphism(
            self,
            *,
            function: Callable[..., Element],
            category: Category | None = None,
            codomain: Parent,
            **keywords: bool | int | str | Matrix | Callable[..., Element] | Element | Category | Parent,
        ) -> SetMorphism: ...
        def quotient(
            self,
            submodule: Parent | Iterable[Element],
            check: bool = True,
            **kwds: bool | int | str | Parent | Element,
        ) -> Parent: ...
        def quotient_module(
            self,
            submodule: Parent | Iterable[Element],
            check: bool = True,
            **kwds: bool | int | str | Parent | Element,
        ) -> Parent: ...
    class ElementMethods:
        ...
    class Homsets:
        def extra_super_categories(self) -> list[Category]: ...
        def base_ring(self) -> Parent: ...
        class ParentMethods:
            def base_ring(self) -> Parent: ...
            def zero(self) -> Morphism: ...
        class Endset:
            def extra_super_categories(self) -> list[Category]: ...
    class CartesianProducts:
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            def __init_extra__(self) -> None: ...
        class ElementMethods:
            def _lmul_(self, x: Element | SageCoercionAtom) -> Element: ...
    class TensorProducts:
        def extra_super_categories(self) -> list[Category]: ...
        class ParentMethods:
            def construction(self) -> tuple[TensorProductFunctor, tuple[Parent, ...]]: ...
            def tensor_factors(self) -> tuple[Parent, ...]: ...
