from collections.abc import Hashable, Iterable
from typing import TypeAlias

from sage.structure.element import Element

_PosetElement: TypeAlias = Element | Hashable

class Posets:
    class ElementMethods:
        ...
    class ParentMethods:
        def le(self, x: _PosetElement, y: _PosetElement) -> bool: ...
        def lt(self, x: _PosetElement, y: _PosetElement) -> bool: ...
        def ge(self, x: _PosetElement, y: _PosetElement) -> bool: ...
        def gt(self, x: _PosetElement, y: _PosetElement) -> bool: ...
        def upper_covers(self, x: _PosetElement) -> list[_PosetElement]: ...
        def lower_covers(self, x: _PosetElement) -> list[_PosetElement]: ...
        def order_ideal(self, elements: Iterable[_PosetElement]) -> list[_PosetElement]: ...
        def order_filter(self, elements: Iterable[_PosetElement]) -> list[_PosetElement]: ...
        def directed_subset(self, elements: Iterable[_PosetElement], direction: str) -> list[_PosetElement]: ...
        def principal_order_ideal(self, x: _PosetElement) -> list[_PosetElement]: ...
        def principal_order_filter(self, x: _PosetElement) -> list[_PosetElement]: ...
        def order_ideal_toggle(self, I: Iterable[_PosetElement], v: _PosetElement) -> Iterable[_PosetElement]: ...
        def order_ideal_toggles(self, I: Iterable[_PosetElement], vs: Iterable[_PosetElement]) -> Iterable[_PosetElement]: ...
        def is_order_ideal(self, o: Iterable[_PosetElement]) -> bool: ...
        def is_order_filter(self, o: Iterable[_PosetElement]) -> bool: ...
        def is_chain_of_poset(self, o: Iterable[_PosetElement], ordered: bool = False) -> bool: ...
        def is_antichain_of_poset(self, o: Iterable[_PosetElement]) -> bool: ...
