from sage.categories.category import Category
from sage.categories.category_types import Category_over_base
from sage.categories.covariant_functorial_construction import RegressiveCovariantConstructionCategory
from sage.misc.bindable_class import BindableClass

class RealizationsCategory(RegressiveCovariantConstructionCategory): ...

def Realizations(self: object) -> Category: ...

class Category_realization_of_parent(Category_over_base, BindableClass):
    parent_with_realization: object
    def __init__(self, parent_with_realization: object) -> None: ...
    def _get_name(self) -> str: ...
    def _repr_object_names(self) -> str: ...
