from collections.abc import Iterable

from sage.categories.category import Category
from sage.categories.category_singleton import Category_singleton
from sage.categories.tensor import TensorProductsCategory
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.graphs.digraph import DiGraph
from sage.graphs.graph import Graph

class RegularCrystals(Category_singleton):
    def super_categories(self) -> list[Category]: ...
    def example(self, n: int = 3) -> Parent: ...
    def additional_structure(self) -> None: ...
    class MorphismMethods:
        def is_isomorphism(self) -> bool: ...
    class ParentMethods:
        def demazure_operator(self, element: Element, reduced_word: Iterable[int]) -> Element: ...
        def demazure_subcrystal(self, element: Element, reduced_word: Iterable[int], only_support: bool = True) -> Parent: ...
        def _test_stembridge_local_axioms(self, index_set: Iterable[int | str] | None = None, verbose: bool = False, complete: bool = False, **options: object) -> bool: ...
        def dual_equivalence_graph(self, X: Iterable[Element] | None = None, index_set: Iterable[int | str] | None = None, directed: bool = True) -> DiGraph: ...
    class ElementMethods: ...
    class TensorProducts(TensorProductsCategory):
        def extra_super_categories(self) -> list[Category]: ...
