from typing import Generic, TypeVar

from sage.categories.category import Category
from sage.modules.free_module import FreeModule_generic
from sage.rings.integer import Integer
from sage.structure.element import Element, RingElement
from sage.structure.parent import ElementConstructorInput, MembershipInput, Parent

from .category_with_axiom import CategoryWithAxiom

_E = TypeVar("_E", bound=RingElement, default=RingElement, covariant=True)

class Rings(Category):
    def __init__(self) -> None: ...
    class ElementMethods:
        ...
    class MorphismMethods:
        ...
    class ParentMethods(Parent[_E], Generic[_E]):
        def __call__(
            self,
            x: ElementConstructorInput = ...,
            *args: ElementConstructorInput,
            **kwds: ElementConstructorInput,
        ) -> _E: ...
        def __contains__(self, x: MembershipInput) -> bool: ...
        def __pow__(self, n: int | Integer) -> FreeModule_generic[_E]: ...
        def zero(self) -> _E: ...
        def one(self) -> _E: ...
        def gen(self, i: int = ...) -> Element: ...
        def random_element(self, *args: object, **kwds: object) -> Element: ...
        def characteristic(self) -> Integer: ...
        def is_field(self, proof: bool = ...) -> bool: ...
    class SubcategoryMethods:
        def Finite(self) -> CategoryWithAxiom: ...
        def Topological(self) -> CategoryWithAxiom: ...
    class Finite(CategoryWithAxiom):
        ...
    class Topological(CategoryWithAxiom):
        ...

Ring = Rings.ParentMethods
