from sage.categories.category import Category
from sage.categories.category_types import Category_ideal
from sage.rings.ring import Ring


class RingIdeals(Category_ideal):
    def __init__(self, R: Ring) -> None: ...
    def ring(self) -> Ring: ...
    def super_categories(self) -> list[Category]: ...
