from collections.abc import Sequence
from typing import Protocol

from .category_with_axiom import CategoryWithAxiom
from .finite_sets import FiniteSets
from .metric_spaces import MetricSpaces
from .topological_spaces import TopologicalSpaces
from .facade_sets import FacadeSets
from .enumerated_sets import EnumeratedSets
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageCoercionAtom, SageObject


class _SympySetLike(Protocol):
    @property
    def is_finite_set(self) -> bool: ...

    def __contains__(self, element: SageCoercionAtom) -> bool: ...


class EmptySetError(ValueError): ...

type _SetConstruction = tuple[SageObject, SageObject] | None

class Sets:
    class ElementMethods:
        ...
    class MorphismMethods:
        ...
    class ParentMethods:
        def __contains__(self, x: SageCoercionAtom) -> bool: ...
        def _element_constructor_(self, x: SageCoercionAtom) -> Element: ...
        def is_parent_of(self, element: SageCoercionAtom) -> bool: ...
        def an_element(self) -> Element: ...
        def _an_element_(self) -> Element: ...
        def some_elements(self) -> Sequence[Element]: ...
        def is_empty(self) -> bool: ...
        def construction(self) -> _SetConstruction: ...
        def _sympy_(self) -> _SympySetLike: ...
    class SubcategoryMethods:
        def Topological(self) -> TopologicalSpaces: ...
        def Metric(self) -> MetricSpaces: ...
        def Finite(self) -> FiniteSets: ...
        def Infinite(self) -> CategoryWithAxiom: ...
        def Enumerated(self) -> EnumeratedSets: ...
        def Facade(self) -> FacadeSets: ...
    class Finite(CategoryWithAxiom):
        ...
    class Topological(CategoryWithAxiom):
        ...
    class Metric(CategoryWithAxiom):
        def Complete(self) -> CategoryWithAxiom: ...
    class Enumerated(CategoryWithAxiom):
        ...
    class Facade(FacadeSets):
        ...
    class Infinite:
        class ParentMethods:
            ...
    class CartesianProducts:
        class ElementMethods:
            ...
        class ParentMethods:
            def is_finite(self) -> bool: ...
            def cardinality(self) -> int | Element: ...
            def random_element(self, *args: SageCoercionAtom) -> tuple[Element, ...]: ...
            def construction(self) -> tuple[SageObject, SageObject]: ...
            def _sympy_(self) -> _SympySetLike: ...
    class Subquotients:
        class ElementMethods:
            ...
        class ParentMethods:
            ...
    class Subobjects:
        class ParentMethods:
            ...
