from typing import TYPE_CHECKING
from sage.categories.category import Category
from sage.categories.category_types import Category_over_base_ring
from sage.categories.covariant_functorial_construction import CovariantConstructionCategory

class SuperModulesCategory(CovariantConstructionCategory, Category_over_base_ring):
    @classmethod
    def default_super_categories(cls, category: Category, *args: object) -> Category: ...
    def __init__(self, base_category: Category) -> None: ...
    def _repr_object_names(self) -> str: ...

class SuperModules(SuperModulesCategory):
    def super_categories(self) -> list[Category]: ...
    def extra_super_categories(self) -> list[Category]: ...
    class ParentMethods: ...
    class ElementMethods:
        def is_even_odd(self) -> int: ...
        def is_even(self) -> bool: ...
        def is_odd(self) -> bool: ...
