# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Parallelism:
    def __init__(self) -> None: ...
    def reset(self) -> _SageObject: ...
    def set(self, field: builtins.object = ..., nproc: builtins.object = ...) -> _SageObject: ...
    def get(self, field: builtins.object) -> _SageObject: ...
    def get_all(self) -> _SageObject: ...
    def set_default(self, nproc: builtins.object = ...) -> _SageObject: ...
    def get_default(self) -> _SageObject: ...
