import builtins
from typing import Self

class _SageObject: ...

def get_flag(self=..., subsystem: builtins.object = ...) -> _SageObject: ...

class WithProof:
    def __init__(self, subsystem: builtins.object, t: builtins.object) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: builtins.object) -> builtins.bool | None: ...
