# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Matrix:
    def str(self) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __getitem__(self, ij: builtins.object) -> _SageObject: ...
    def nrows(self) -> _SageObject: ...
    def ncols(self) -> _SageObject: ...
    def add_scalar(self, s: builtins.object) -> _SageObject: ...
    def charpoly(self, var: builtins.object = ...) -> _SageObject: ...
    def sage_matrix_over_ZZ(self, sparse: builtins.object = ...) -> _SageObject: ...

class MatrixFactory:
    def new_matrix(self, M: builtins.object) -> _SageObject: ...

def new_Matrix(M: builtins.object) -> _SageObject: ...
