from sage.modules.fg_pid.fgp_element import FGP_Element
from sage.modules.fg_pid.fgp_module import FGP_Module_class
from sage.rings.integer import Integer
from sage.rings.infinity import PlusInfinity
from sage.modules.free_module_element import FreeModuleElement

class AdditiveAbelianGroupElement(FGP_Element):
    def _hermite_lift(self) -> FreeModuleElement: ...
    def _repr_(self) -> str: ...

class AdditiveAbelianGroup_class(FGP_Module_class):
    def __init__(self, cover: object, relations: object) -> None: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def short_name(self) -> str: ...
    def _module_constructor(
        self, cover: object, relations: object, check: bool = True
    ) -> AdditiveAbelianGroup_class: ...
    def order(self) -> Integer | PlusInfinity: ...
    def exponent(self) -> Integer: ...

class AdditiveAbelianGroup_fixed_gens(AdditiveAbelianGroup_class): ...
