from collections.abc import Iterator
from sage.groups.additive_abelian.qmodnz_element import QmodnZ_Element
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.rings.rational import Rational

class QmodnZ(Parent, UniqueRepresentation):
    n: Rational
    def __init__(self, n: int | Rational = 1) -> None: ...
    def _repr_(self) -> str: ...
    def _coerce_map_from_(self, S: object) -> bool: ...
    def _element_constructor_(self, x: object) -> QmodnZ_Element: ...
    def _an_element_(self) -> QmodnZ_Element: ...
    def zero(self) -> QmodnZ_Element: ...
    def some_elements(self) -> list[QmodnZ_Element]: ...
    def random_element(self) -> QmodnZ_Element: ...
    def __iter__(self) -> Iterator[QmodnZ_Element]: ...
