# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def random_normal(mean: builtins.object, std: builtins.object, rstate: builtins.object) -> _SageObject: ...

class Distribution:
    def sample(self, n: builtins.object = ...) -> _SageObject: ...
    def prob(self, x: builtins.object) -> _SageObject: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class GaussianMixtureDistribution:
    def __init__(self, B: builtins.object, eps: builtins.object = ..., normalize: builtins.object = ...) -> None: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def is_fixed(self, i: builtins.object = ...) -> builtins.bool: ...
    def fix(self, i: builtins.object = ...) -> _SageObject: ...
    def unfix(self, i: builtins.object = ...) -> _SageObject: ...
    def sample(self, n: builtins.object = ...) -> _SageObject: ...
    def prob(self, x: builtins.object) -> _SageObject: ...
    def prob_m(self, x: builtins.object, m: builtins.object) -> _SageObject: ...
