# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class HMM_Util:
    def normalize_probability_TimeSeries(self, T: builtins.object, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def initial_probs_to_TimeSeries(self, pi: builtins.object, normalize: builtins.object) -> _SageObject: ...
    def state_matrix_to_TimeSeries(self, A: builtins.object, N: builtins.object, normalize: builtins.object) -> _SageObject: ...
