# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def frequency_table(string: builtins.object) -> _SageObject: ...

class Huffman:
    def __init__(self, source: builtins.object) -> None: ...
    def encode(self, string: builtins.object) -> _SageObject: ...
    def decode(self, string: builtins.object) -> _SageObject: ...
    def encoding_table(self) -> _SageObject: ...
    def tree(self) -> _SageObject: ...
