# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ProbabilityDistribution:
    def __init__(self) -> None: ...
    def get_random_element(self) -> _SageObject: ...
    def generate_histogram_data(self, num_samples: builtins.object = ..., bins: builtins.object = ...) -> _SageObject: ...
    def generate_histogram_plot(self, name: builtins.object, num_samples: builtins.object = ..., bins: builtins.object = ...) -> _SageObject: ...

class SphericalDistribution:
    def __init__(self, dimension: builtins.object = ..., rng: builtins.object = ..., seed: builtins.object = ...) -> None: ...
    def set_seed(self, seed: builtins.object) -> _SageObject: ...
    def set_random_number_generator(self, rng: builtins.object = ...) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def get_random_element(self) -> _SageObject: ...
    def reset_distribution(self) -> _SageObject: ...

class RealDistribution:
    def set_seed(self, seed: builtins.object) -> _SageObject: ...
    def set_random_number_generator(self, rng: builtins.object = ...) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def get_random_element(self) -> _SageObject: ...
    def set_distribution(self, name: builtins.object = ..., parameters: builtins.object = ...) -> _SageObject: ...
    def reset_distribution(self) -> _SageObject: ...
    def distribution_function(self, x: builtins.object) -> _SageObject: ...
    def cum_distribution_function(self, x: builtins.object) -> _SageObject: ...
    def cum_distribution_function_inv(self, x: builtins.object) -> _SageObject: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class GeneralDiscreteDistribution:
    def __init__(self, P: builtins.object, rng: builtins.object = ..., seed: builtins.object = ...) -> None: ...
    def set_seed(self, seed: builtins.object) -> _SageObject: ...
    def set_random_number_generator(self, rng: builtins.object = ...) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def get_random_element(self) -> _SageObject: ...
    def reset_distribution(self) -> _SageObject: ...
