# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class OrthogonalFunction:
    def __init__(self, name: builtins.str, nargs: builtins.int = ..., latex_name: builtins.str = ..., conversions: builtins.object = ...) -> None: ...
    def eval_formula(self, *args: builtins.object) -> _SageObject: ...
    def __call__(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class ChebyshevFunction:
    def __call__(self, n: builtins.int, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class Func_chebyshev_T:
    def __init__(self) -> None: ...
    def eval_formula(self, n: builtins.int, x: builtins.object) -> _SageObject: ...
    def eval_algebraic(self, n: builtins.int, x: builtins.object) -> _SageObject: ...

chebyshev_T: _SageObject
class Func_chebyshev_U:
    def __init__(self) -> None: ...
    def eval_formula(self, n: builtins.int, x: builtins.object) -> _SageObject: ...
    def eval_algebraic(self, n: builtins.int, x: builtins.object) -> _SageObject: ...

chebyshev_U: _SageObject
class Func_legendre_P:
    def __init__(self) -> None: ...

legendre_P: _SageObject
class Func_legendre_Q:
    def __init__(self) -> None: ...
    def eval_recursive(self, n: builtins.int, arg: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def eval_formula(self, n: builtins.int, arg: builtins.object, **kwds: builtins.object) -> _SageObject: ...

legendre_Q: _SageObject
class Func_assoc_legendre_P:
    def __init__(self) -> None: ...
    def eval_gen_poly(self, n: builtins.int, m: builtins.int, arg: builtins.object, **kwds: builtins.object) -> _SageObject: ...

gen_legendre_P: _SageObject
class Func_assoc_legendre_Q:
    def __init__(self) -> None: ...
    def eval_recursive(self, n: builtins.int, m: builtins.int, x: builtins.object, **kwds: builtins.object) -> _SageObject: ...

gen_legendre_Q: _SageObject
class Func_hermite:
    def __init__(self) -> None: ...

hermite: _SageObject
class Func_jacobi_P:
    def __init__(self) -> None: ...

jacobi_P: _SageObject
class Func_ultraspherical:
    def __init__(self) -> None: ...

ultraspherical: _SageObject
gegenbauer: _SageObject
class Func_laguerre:
    def __init__(self) -> None: ...

laguerre: _SageObject
class Func_gen_laguerre:
    def __init__(self) -> None: ...

gen_laguerre: _SageObject
class Func_krawtchouk:
    def __init__(self) -> None: ...
    def eval_formula(self, k: builtins.int, x: builtins.object, n: builtins.int, p: builtins.int) -> _SageObject: ...
    def eval_recursive(self, j: builtins.int, x: builtins.object, n: builtins.int, p: builtins.int, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

krawtchouk: _SageObject
class Func_meixner:
    def __init__(self) -> None: ...
    def eval_formula(self, n: builtins.int, x: builtins.object, b: builtins.object, c: builtins.object) -> _SageObject: ...
    def eval_recursive(self, n: builtins.int, x: builtins.object, b: builtins.object, c: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

meixner: _SageObject
class Func_hahn:
    def __init__(self) -> None: ...
    def eval_formula(self, k: builtins.int, x: builtins.object, a: builtins.object, b: builtins.object, n: builtins.int) -> _SageObject: ...
    def eval_recursive(self, k: builtins.int, x: builtins.object, a: builtins.object, b: builtins.object, n: builtins.int, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

hahn: _SageObject
