# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PiecewiseFunction:
    def __init__(self) -> None: ...
    def __call__(self, function_pieces: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    @staticmethod
    def in_operands(ex: builtins.object) -> _SageObject: ...
    @staticmethod
    def simplify(ex: builtins.object) -> _SageObject: ...
    class EvaluationMethods:
        def __pow__(self, parameters: builtins.object, variable: builtins.object, n: builtins.int) -> Self: ...
        def expression_at(self, parameters: builtins.object, variable: builtins.object, point: builtins.object) -> _SageObject: ...
        which_function: _SageObject
        def domains(self, parameters: builtins.object, variable: builtins.object) -> _SageObject: ...
        def domain(self, parameters: builtins.object, variable: builtins.object) -> _SageObject: ...
        def __len__(self, parameters: builtins.object, variable: builtins.object) -> builtins.int: ...
        def expressions(self, parameters: builtins.object, variable: builtins.object) -> _SageObject: ...
        def items(self, parameters: builtins.object, variable: builtins.object) -> _SageObject: ...
        def __call__(self, parameters: builtins.object, variable: builtins.object, value: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
        def restriction(self, parameters: builtins.object, variable: builtins.object, restricted_domain: builtins.object) -> _SageObject: ...
        def extension(self, parameters: builtins.object, variable: builtins.object, extension: builtins.object, extension_domain: builtins.object = ...) -> _SageObject: ...
        def unextend_zero(self, parameters: builtins.object, variable: builtins.object) -> _SageObject: ...
        def pieces(self, parameters: builtins.object, variable: builtins.object) -> _SageObject: ...
        def end_points(self, parameters: builtins.object, variable: builtins.object) -> builtins.list[_SageObject]: ...
        def piecewise_add(self, parameters: builtins.object, variable: builtins.object, other: builtins.object) -> _SageObject: ...
        def integral(self, parameters: builtins.object, variable: builtins.object, x: builtins.object = ..., a: builtins.object = ..., b: builtins.object = ..., definite: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...
        def critical_points(self, parameters: builtins.object, variable: builtins.object) -> _SageObject: ...
        def convolution(self, parameters: builtins.object, variable: builtins.object, other: builtins.object) -> _SageObject: ...
        def trapezoid(self, parameters: builtins.object, variable: builtins.object, N: builtins.int) -> _SageObject: ...
        def laplace(self, parameters: builtins.object, variable: builtins.object, x: builtins.str = ..., s: builtins.str = ...) -> _SageObject: ...
        def fourier_series_cosine_coefficient(self, parameters: builtins.object, variable: builtins.object, n: builtins.int, L: builtins.object = ...) -> _SageObject: ...
        def fourier_series_sine_coefficient(self, parameters: builtins.object, variable: builtins.object, n: builtins.int, L: builtins.object = ...) -> _SageObject: ...
        def fourier_series_partial_sum(self, parameters: builtins.object, variable: builtins.object, N: builtins.int, L: builtins.object = ...) -> _SageObject: ...

piecewise: _SageObject
