# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class HyperellipticCurve_padic_field:
    def __init__(self, projective_model: builtins.object, f: builtins.object, h: builtins.object, genus: builtins.object, names: builtins.list[_SageObject] = ...) -> None: ...
    def local_analytic_interpolation(self, P: builtins.int, Q: builtins.int) -> _SageObject: ...
    def is_in_weierstrass_disc(self, P: builtins.int) -> builtins.bool: ...
    def find_char_zero_weierstrass_point(self, Q: builtins.int) -> _SageObject: ...
    def residue_disc(self, P: builtins.int) -> _SageObject: ...
    def is_same_disc(self, P: builtins.int, Q: builtins.int) -> builtins.bool: ...
    def tiny_integrals(self, F: builtins.object, P: builtins.int, Q: builtins.int) -> _SageObject: ...
    def tiny_integrals_on_basis(self, P: builtins.int, Q: builtins.int) -> _SageObject: ...
    def teichmuller(self, P: builtins.int) -> _SageObject: ...
    def coleman_integrals_on_basis(self, P: builtins.int, Q: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...
    coleman_integrals_on_basis_hyperelliptic: _SageObject
    def coleman_integral(self, w: builtins.object, P: builtins.int, Q: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...
    def frobenius(self, P: builtins.int = ...) -> _SageObject: ...
    def newton_sqrt(self, f: builtins.object, x0: builtins.object, prec: builtins.int) -> _SageObject: ...
    def curve_over_ram_extn(self, deg: builtins.object) -> _SageObject: ...
    def get_boundary_point(self, curve_over_extn: builtins.object, P: builtins.int) -> _SageObject: ...
    def P_to_S(self, P: builtins.int, S: builtins.object) -> _SageObject: ...
    def coleman_integral_P_to_S(self, w: builtins.object, P: builtins.int, S: builtins.object) -> _SageObject: ...
    def S_to_Q(self, S: builtins.object, Q: builtins.int) -> _SageObject: ...
    def coleman_integral_S_to_Q(self, w: builtins.object, S: builtins.object, Q: builtins.int) -> _SageObject: ...
    def coleman_integral_from_weierstrass_via_boundary(self, w: builtins.object, P: builtins.int, Q: builtins.int, d: builtins.object) -> _SageObject: ...
