# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class HyperellipticJacobianHomset:
    def __init__(self, Y: builtins.object, X: builtins.object, **kwds: builtins.object) -> None: ...
    def curve(self) -> _SageObject: ...
    def extended_curve(self) -> _SageObject: ...
    def order(self) -> _SageObject: ...
    def cardinality(self, extension_degree: builtins.int = ...) -> _SageObject: ...
    def count_points(self, n: builtins.int = ...) -> _SageObject: ...
    def point_to_mumford_coordinates(self, P: builtins.int) -> _SageObject: ...
    def zero(self, check: builtins.bool = ...) -> _SageObject: ...
    def cantor_composition(self, u1: builtins.object, v1: builtins.object, u2: builtins.object, v2: builtins.object) -> _SageObject: ...
    def cantor_reduction(self, u0: builtins.object, v0: builtins.object) -> _SageObject: ...
    def lift_u(self, u: builtins.object, all: builtins.bool = ...) -> _SageObject: ...
    def random_element(self, fast: builtins.bool = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def points(self) -> _SageObject: ...
    rational_points: _SageObject
    def abelian_group(self) -> _SageObject: ...
