# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KummerSurface:
    def __init__(self, J: builtins.int) -> None: ...
    def __call__(self, P: builtins.int) -> _SageObject: ...
    def defining_equation(self) -> _SageObject: ...
    def jacobian(self) -> _SageObject: ...
