import builtins

class _SageObject: ...

def HyperellipticCurve_from_invariants(
    self,
    reduced: builtins.bool = ...,
    precision: builtins.int = ...,
    algorithm: builtins.str = ...,
) -> _SageObject: ...
def Mestre_conic(
    self, xyz: builtins.bool = ..., names: builtins.str = ...
) -> _SageObject: ...
