import builtins

class _SageObject: ...

class CombinatorialPolyhedron:
    def __cinit__(self) -> _SageObject: ...
    def __init__(
        self,
        data: builtins.object,
        Vrep: builtins.object = ...,
        facets: builtins.object = ...,
        unbounded: builtins.object = ...,
        far_face: builtins.object = ...,
    ) -> None: ...
    def f(v: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def Vrepresentation(self) -> _SageObject: ...
    def Hrepresentation(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def n_vertices(self) -> _SageObject: ...
    def vertices(self, names: builtins.object = ...) -> _SageObject: ...
    def n_facets(self) -> _SageObject: ...
    def facets(self, names: builtins.object = ...) -> _SageObject: ...
    def incidence_matrix(self) -> _SageObject: ...
    def edges(
        self, names: builtins.object = ..., algorithm: builtins.object = ...
    ) -> _SageObject: ...
    def vertex_graph(
        self, names: builtins.object = ..., algorithm: builtins.object = ...
    ) -> _SageObject: ...
    def vertex_adjacency_matrix(
        self, algorithm: builtins.object = ...
    ) -> _SageObject: ...
    def ridges(
        self,
        add_equations: builtins.object = ...,
        names: builtins.object = ...,
        algorithm: builtins.object = ...,
    ) -> _SageObject: ...
    def facet_adjacency_matrix(
        self, algorithm: builtins.object = ...
    ) -> _SageObject: ...
    def facet_graph(
        self, names: builtins.object = ..., algorithm: builtins.object = ...
    ) -> _SageObject: ...
    def vertex_facet_graph(self, names: builtins.object = ...) -> _SageObject: ...
    def f_vector(
        self,
        num_threads: builtins.object = ...,
        parallelization_depth: builtins.object = ...,
        algorithm: builtins.object = ...,
    ) -> _SageObject: ...
    def flag_f_vector(self, *args: builtins.object) -> _SageObject: ...
    def neighborliness(self) -> _SageObject: ...
    def is_neighborly(self, k: builtins.object = ...) -> builtins.bool: ...
    def is_simplex(self) -> builtins.bool: ...
    def is_simplicial(self) -> builtins.bool: ...
    def simpliciality(self) -> _SageObject: ...
    def is_simple(self) -> builtins.bool: ...
    def simplicity(self) -> _SageObject: ...
    def is_lawrence_polytope(self) -> builtins.bool: ...
    def is_pyramid(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def is_bipyramid(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def is_prism(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def join_of_Vrep(self, *indices: builtins.object) -> _SageObject: ...
    def meet_of_Hrep(self, *indices: builtins.object) -> _SageObject: ...
    def face_generator(
        self, dimension: builtins.object = ..., algorithm: builtins.object = ...
    ) -> _SageObject: ...
    def face_lattice(self) -> _SageObject: ...
    def hasse_diagram(self) -> _SageObject: ...
    def face_by_face_lattice_index(self, index: builtins.object) -> _SageObject: ...
    def a_maximal_chain(
        self, Vindex: builtins.object = ..., Hindex: builtins.object = ...
    ) -> _SageObject: ...
    def test_a_chain(b: builtins.object) -> _SageObject: ...
    def Vrep(self) -> _SageObject: ...
    def facet_names(self) -> _SageObject: ...
    def equations(self) -> _SageObject: ...
    def n_Vrepresentation(self) -> _SageObject: ...
    def n_Hrepresentation(self) -> _SageObject: ...
    def is_compact(self) -> builtins.bool: ...
    def is_bounded(self) -> builtins.bool: ...
    def bitrep_facets(self) -> _SageObject: ...
    def bitrep_Vrep(self) -> _SageObject: ...
    def far_face_tuple(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def dual(self) -> _SageObject: ...
    def pyramid(
        self, new_vertex: builtins.object = ..., new_facet: builtins.object = ...
    ) -> _SageObject: ...
    def choose_algorithm_to_compute_edges_or_ridges(
        self, edges_or_ridges: builtins.object
    ) -> _SageObject: ...
