from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class CombinatorialPolyhedron(SageObject):
    def _repr_(self) -> str: ...
    def _test_bitsets(self, tester: Element | int | str | bool | None, **options: Element | int | str | bool | None) -> Element: ...
    def Vrepresentation(self) -> Element: ...
    def Hrepresentation(self) -> Element: ...
    def dimension(self) -> int: ...
    def n_vertices(self) -> Element: ...
    def vertices(self, names: str) -> Element: ...
    def n_facets(self) -> Element: ...
    def facets(self, names: str) -> Element: ...
    def incidence_matrix(self) -> Element: ...
    def edges(self, names: str, algorithm: str) -> Element: ...
    def vertex_graph(self, names: str, algorithm: str) -> Element: ...
    def vertex_adjacency_matrix(self, algorithm: str) -> Element: ...
    def ridges(self, add_equations: Element | int | str | bool | None, names: str, algorithm: str) -> Element: ...
    def facet_adjacency_matrix(self, algorithm: str) -> Element: ...
    def facet_graph(self, names: str, algorithm: str) -> Element: ...
    def vertex_facet_graph(self, names: str) -> Element: ...
    def f_vector(self, num_threads: Element | int | str | bool | None, parallelization_depth: Element | int | str | bool | None, algorithm: str) -> Element: ...
    def flag_f_vector(self, *args: Element | int | str | bool | None) -> Element: ...
    def _flag_f_vector(self) -> Element: ...
    def neighborliness(self) -> Element: ...
    def is_neighborly(self, k: int) -> bool: ...
    def is_simplex(self) -> bool: ...
    def is_simplicial(self) -> bool: ...
    def simpliciality(self) -> Element: ...
    def is_simple(self) -> bool: ...
    def simplicity(self) -> Element: ...
    def is_lawrence_polytope(self) -> bool: ...
    def is_pyramid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def is_bipyramid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def is_prism(self, certificate: Element | int | str | bool | None) -> bool: ...
    def join_of_Vrep(self, *indices: Element | int | str | bool | None) -> Element: ...
    def meet_of_Hrep(self, *indices: Element | int | str | bool | None) -> Element: ...
    def face_generator(self, dimension: Element | int | str | bool | None, algorithm: str) -> Element: ...
    def face_lattice(self) -> Element: ...
    def hasse_diagram(self) -> Element: ...
    def _face_lattice_dimension(self, index: int) -> Element: ...
    def face_by_face_lattice_index(self, index: int) -> Element: ...
    def a_maximal_chain(self, Vindex: Element | int | str | bool | None, Hindex: Element | int | str | bool | None) -> Element: ...
    def _test_a_maximal_chain(self, tester: Element | int | str | bool | None, **options: Element | int | str | bool | None) -> Element: ...
    def is_compact(self) -> bool: ...
    def choose_algorithm_to_compute_edges_or_ridges(self, edges_or_ridges: Element | int | str | bool | None) -> Element: ...
    def _record_all_faces(self) -> Element: ...
