# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def Vrep_list_to_bit_rep(Vrep_list: builtins.object, output: builtins.object) -> _SageObject: ...

def incidences_to_bit_rep(incidences: builtins.object, output: builtins.object) -> _SageObject: ...

def incidence_matrix_to_bit_rep_of_facets(matrix: builtins.object) -> _SageObject: ...

def incidence_matrix_to_bit_rep_of_Vrep(matrix: builtins.object) -> _SageObject: ...

def facets_tuple_to_bit_rep_of_facets(facets_input: builtins.object, n_Vrep: builtins.object) -> _SageObject: ...

def facets_tuple_to_bit_rep_of_Vrep(facets_input: builtins.object, n_Vrep: builtins.object) -> _SageObject: ...

def bit_rep_to_Vrep_list(face: builtins.object, output: builtins.object) -> _SageObject: ...
