from sage.structure.element import Element

def incidence_matrix_to_bit_rep_of_facets(matrix: Element | int | str | bool | None) -> Element: ...
def incidence_matrix_to_bit_rep_of_Vrep(matrix: Element | int | str | bool | None) -> Element: ...
def facets_tuple_to_bit_rep_of_facets(facets_input: Element | int | str | bool | None, n_Vrep: Element | int | str | bool | None) -> Element: ...
def facets_tuple_to_bit_rep_of_Vrep(facets_input: Element | int | str | bool | None, n_Vrep: Element | int | str | bool | None) -> Element: ...
