# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ListOfFaces:
    def __cinit__(self, n_faces: builtins.object, n_atoms: builtins.object, n_coatoms: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __copy__(self) -> Self: ...
    def compute_dimension(self) -> _SageObject: ...
    def pyramid(self) -> _SageObject: ...
    def delete_atoms_unsafe(self, delete: builtins.object, face: builtins.object) -> _SageObject: ...
    def delete_faces_unsafe(self, delete: builtins.object, face: builtins.object) -> _SageObject: ...
    def get_not_inclusion_maximal_unsafe(self, not_inclusion_maximal: builtins.object) -> _SageObject: ...
    def get_faces_all_set_unsafe(self, all_set: builtins.object) -> _SageObject: ...
    def matrix(self) -> _SageObject: ...

def face_as_combinatorial_polyhedron(facets: builtins.object, Vrep: builtins.object, face: builtins.object, dual: builtins.object) -> _SageObject: ...
