# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PolyhedronFaceLattice:
    def __cinit__(self, C: builtins.object) -> _SageObject: ...
    def __init__(self, C: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def find_face(self, dimension: builtins.object, face: builtins.object) -> _SageObject: ...
    def get_face(self, dimension: builtins.object, index: builtins.object) -> _SageObject: ...
    def set_coatom_rep(self, dimension: builtins.object, index: builtins.object) -> _SageObject: ...
    def set_atom_rep(self, dimension: builtins.object, index: builtins.object) -> _SageObject: ...
    def incidence_init(self, dimension_one: builtins.object, dimension_two: builtins.object) -> _SageObject: ...
    def next_incidence(self, one: builtins.object, two: builtins.object) -> _SageObject: ...
    def next_incidence_loop(self, one: builtins.object, two: builtins.object) -> _SageObject: ...
    def next_trivial_incidence(self, one: builtins.object, two: builtins.object) -> _SageObject: ...
    def next_trivial_incidence2(self, one: builtins.object, two: builtins.object) -> _SageObject: ...
