# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def fmpz_mat_get_linbox(A: builtins.object, m: builtins.object) -> _SageObject: ...

def fmpz_mat_set_linbox(m: builtins.object, A: builtins.object) -> _SageObject: ...

def fmpz_poly_set_linbox(p: builtins.object, q: builtins.object) -> _SageObject: ...

def linbox_fmpz_mat_mul(C: builtins.object, A: builtins.object, B: builtins.object) -> _SageObject: ...

def linbox_fmpz_mat_charpoly(cp: builtins.object, A: builtins.object) -> _SageObject: ...

def linbox_fmpz_mat_minpoly(mp: builtins.object, A: builtins.object) -> _SageObject: ...

def linbox_fmpz_mat_rank(A: builtins.object) -> _SageObject: ...

def linbox_fmpz_mat_det(det: builtins.object, A: builtins.object) -> _SageObject: ...
