# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeGradedModuleElement:
    def dense_coefficient_list(self, order: builtins.object = ...) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def lift_to_free(self) -> _SageObject: ...
    def vector_presentation(self) -> _SageObject: ...
