import builtins

class _SageObject: ...

class FPModule:
    @staticmethod
    def __classcall__(
        cls: builtins.object,
        arg0: builtins.object,
        generator_degrees: builtins.object = ...,
        relations: builtins.tuple[_SageObject, ...] = ...,
        names: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(self, j: builtins.int, names: builtins.object) -> None: ...
    Element: _SageObject

    def defining_homomorphism(self) -> _SageObject: ...
    def change_ring(self, algebra: builtins.object) -> _SageObject: ...
    def monomial(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def connectivity(self) -> _SageObject: ...
    def is_trivial(self) -> bool: ...
    def has_relations(self) -> bool: ...
    def an_element(self, n: builtins.int = ...) -> _SageObject: ...
    def basis_elements(
        self, n: builtins.int, verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def element_from_coordinates(
        self, coordinates: builtins.object, n: builtins.int
    ) -> _SageObject: ...
    def vector_presentation(
        self, n: builtins.int, verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def generator_degrees(self) -> _SageObject: ...
    def generators(self) -> _SageObject: ...
    gens: _SageObject

    def generator(self, index: builtins.object) -> _SageObject: ...
    gen: _SageObject

    def relations(self) -> _SageObject: ...
    def relation(self, index: builtins.object) -> _SageObject: ...
    def minimal_presentation(
        self, top_dim: builtins.object = ..., verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def suspension(self, t: builtins.object) -> _SageObject: ...
    def submodule_inclusion(
        self, spanning_elements: builtins.object
    ) -> _SageObject: ...
    def resolution(
        self,
        k: builtins.int,
        top_dim: builtins.object = ...,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...
