import builtins
from typing import Self

class _SageObject: ...

class FPModuleMorphism:
    def __init__(
        self,
        parent: builtins.object,
        values: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def change_ring(self, algebra: builtins.object) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def values(self) -> _SageObject: ...
    def __add__(self, g: builtins.object) -> Self: ...
    def __neg__(self) -> Self: ...
    def __sub__(self, g: builtins.object) -> Self: ...
    def __mul__(self, g: builtins.object) -> Self: ...
    def is_zero(self) -> bool: ...
    def is_identity(self) -> bool: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def vector_presentation(self, n: builtins.int) -> _SageObject: ...
    def solve(self, x: builtins.object) -> _SageObject: ...
    def lift(self, f: builtins.object, verbose: builtins.bool = ...) -> _SageObject: ...
    def split(self, verbose: builtins.bool = ...) -> _SageObject: ...
    def homology(
        self,
        f: builtins.object,
        top_dim: builtins.object = ...,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...
    def suspension(self, t: builtins.object) -> _SageObject: ...
    def cokernel_projection(self) -> _SageObject: ...
    def kernel_inclusion(
        self, top_dim: builtins.object = ..., verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def image(
        self, top_dim: builtins.object = ..., verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def is_injective(
        self, top_dim: builtins.object = ..., verbose: builtins.bool = ...
    ) -> bool: ...
    def is_surjective(self) -> bool: ...
    def fp_module(self) -> _SageObject: ...
