# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def make_ZZ_p(x: builtins.object, ctx: builtins.object) -> _SageObject: ...

def make_ZZ_pX(x: builtins.object, ctx: builtins.object) -> _SageObject: ...

class ntl_ZZ_pX:
    def __init__(self, v: builtins.object = ..., modulus: builtins.object = ...) -> None: ...
    def __cinit__(self, v: builtins.object = ..., modulus: builtins.object = ...) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __copy__(self) -> Self: ...
    def get_modulus_context(self) -> _SageObject: ...
    def __setitem__(self, i: builtins.object, a: builtins.object) -> None: ...
    def setitem_from_int(self, i: builtins.object, value: builtins.object) -> _SageObject: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def getitem_as_int(self, i: builtins.object) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __sub__(self, other: builtins.object) -> Self: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __truediv__(self, other: builtins.object) -> Self: ...
    def __mod__(self, other: builtins.object) -> Self: ...
    def quo_rem(self, other: builtins.object) -> _SageObject: ...
    def square(self) -> _SageObject: ...
    def __pow__(self, n: builtins.object, modulus: builtins.object) -> Self: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def is_zero(self) -> builtins.bool: ...
    def is_one(self) -> builtins.bool: ...
    def is_monic(self) -> builtins.bool: ...
    def __neg__(self) -> Self: ...
    def left_shift(self, n: builtins.object) -> _SageObject: ...
    def right_shift(self, n: builtins.object) -> _SageObject: ...
    def gcd(self, other: builtins.object) -> _SageObject: ...
    def xgcd(self, other: builtins.object, plain: builtins.object = ...) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def leading_coefficient(self) -> _SageObject: ...
    def constant_term(self) -> _SageObject: ...
    def set_x(self) -> _SageObject: ...
    def is_x(self) -> builtins.bool: ...
    def convert_to_modulus(self, c: builtins.object) -> _SageObject: ...
    def derivative(self) -> _SageObject: ...
    def factor(self, verbose: builtins.object = ...) -> _SageObject: ...
    def linear_roots(self) -> _SageObject: ...
    def reverse(self, hi: builtins.object = ...) -> _SageObject: ...
    def truncate(self, m: builtins.object) -> _SageObject: ...
    def multiply_and_truncate(self, other: builtins.object, m: builtins.object) -> _SageObject: ...
    def square_and_truncate(self, m: builtins.object) -> _SageObject: ...
    def invert_and_truncate(self, m: builtins.object) -> _SageObject: ...
    def invmod(self, modulus: builtins.object) -> _SageObject: ...
    def invmod_newton(self, modulus: builtins.object) -> _SageObject: ...
    def multiply_mod(self, other: builtins.object, modulus: builtins.object) -> _SageObject: ...
    def trace_mod(self, modulus: builtins.object) -> _SageObject: ...
    def trace_list(self) -> _SageObject: ...
    def resultant(self, other: builtins.object) -> _SageObject: ...
    def norm_mod(self, modulus: builtins.object) -> _SageObject: ...
    def discriminant(self) -> _SageObject: ...
    def charpoly_mod(self, modulus: builtins.object) -> _SageObject: ...
    def minpoly_mod(self, modulus: builtins.object) -> _SageObject: ...
    def clear(self) -> _SageObject: ...
    def preallocate_space(self, n: builtins.object) -> _SageObject: ...
    def compose_mod(self, other: builtins.object, modulus: builtins.object) -> _SageObject: ...

class ntl_ZZ_pX_Modulus:
    def __cinit__(self, poly: builtins.object) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
