# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def make_ZZ(x: builtins.object) -> _SageObject: ...

def make_ZZ_sig_off(x: builtins.object) -> _SageObject: ...

def make_mat_ZZ(x: builtins.object) -> _SageObject: ...

def make_mat_ZZ_sig_off(x: builtins.object) -> _SageObject: ...

class ntl_mat_ZZ:
    def __init__(self, nrows: builtins.object = ..., ncols: builtins.object = ..., v: builtins.object = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __sub__(self, other: builtins.object) -> Self: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __pow__(self, e: builtins.object, ignored: builtins.object) -> Self: ...
    def nrows(self) -> _SageObject: ...
    def ncols(self) -> _SageObject: ...
    def __setitem__(self, ij: builtins.object, x: builtins.object) -> None: ...
    def __getitem__(self, ij: builtins.object) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def determinant(self, deterministic: builtins.object = ...) -> _SageObject: ...
    def HNF(self, D: builtins.object = ...) -> _SageObject: ...
    def charpoly(self) -> _SageObject: ...
    def BKZ_FP(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def BKZ_QP(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def BKZ_QP1(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def BKZ_XD(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def BKZ_RR(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_BKZ_FP(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_BKZ_QP(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_BKZ_QP1(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_BKZ_XD(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_BKZ_RR(self, U: builtins.object = ..., delta: builtins.object = ..., BlockSize: builtins.object = ..., prune: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def LLL(self, a: builtins.object = ..., b: builtins.object = ..., return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def LLL_FP(self, delta: builtins.object = ..., return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def LLL_QP(self, delta: builtins.object, return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def LLL_XD(self, delta: builtins.object, return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def LLL_RR(self, delta: builtins.object, return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_LLL_FP(self, delta: builtins.object, return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_LLL_QP(self, delta: builtins.object, return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_LLL_XD(self, delta: builtins.object, return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
    def G_LLL_RR(self, delta: builtins.object, return_U: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...
