# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

ZZ_sage: _SageObject
class ntl_zz_pX:
    def __init__(self, ls: builtins.object = ..., modulus: builtins.object = ...) -> None: ...
    def __cinit__(self, v: builtins.object = ..., modulus: builtins.object = ...) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __setitem__(self, i: builtins.object, val: builtins.object) -> None: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __sub__(self, other: builtins.object) -> Self: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __truediv__(self, other: builtins.object) -> Self: ...
    def __mod__(self, other: builtins.object) -> Self: ...
    def __pow__(self, n: builtins.object, ignored: builtins.object) -> Self: ...
    def quo_rem(self, right: builtins.object) -> _SageObject: ...
    def __floordiv__(self, right: builtins.object) -> Self: ...
    def __lshift__(self, n: builtins.object) -> Self: ...
    def __rshift__(self, n: builtins.object) -> Self: ...
    def diff(self) -> _SageObject: ...
    def reverse(self) -> _SageObject: ...
    def __neg__(self) -> Self: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def leading_coefficient(self) -> _SageObject: ...
    def constant_term(self) -> _SageObject: ...
    def square(self) -> _SageObject: ...
    def truncate(self, m: builtins.object) -> _SageObject: ...
    def multiply_and_truncate(self, other: builtins.object, m: builtins.object) -> _SageObject: ...
    def square_and_truncate(self, m: builtins.object) -> _SageObject: ...
    def invert_and_truncate(self, m: builtins.object) -> _SageObject: ...
    def is_zero(self) -> builtins.bool: ...
    def is_one(self) -> builtins.bool: ...
    def is_monic(self) -> builtins.bool: ...
    def set_x(self) -> _SageObject: ...
    def is_x(self) -> builtins.bool: ...
    def clear(self) -> _SageObject: ...
    def preallocate_space(self, n: builtins.object) -> _SageObject: ...

def make_zz_pX(L: builtins.object, context: builtins.object) -> _SageObject: ...
