# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

ZZ_sage: _SageObject
def ntl_ZZ_p_random_element(v: builtins.object) -> _SageObject: ...

class ntl_ZZ_p:
    def __init__(self, v: builtins.object = ..., modulus: builtins.object = ...) -> None: ...
    def __cinit__(self, v: builtins.object = ..., modulus: builtins.object = ...) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def modulus_context(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __invert__(self) -> Self: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __sub__(self, other: builtins.object) -> Self: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pow__(self, e: builtins.object, ignored: builtins.object) -> Self: ...
    def __int__(self) -> builtins.int: ...
    def get_as_int(self) -> _SageObject: ...
    def set_from_int(self, value: builtins.object) -> _SageObject: ...
    def lift(self) -> _SageObject: ...
    def modulus(self) -> _SageObject: ...
    def lift_centered(self) -> _SageObject: ...
