# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ntl_ZZ_pContext_class:
    def __init__(self, v: builtins.object) -> None: ...
    def __cinit__(self, v: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __hash__(self) -> builtins.int: ...
    def modulus(self) -> _SageObject: ...
    def restore(self) -> _SageObject: ...
    def restore_c(self) -> _SageObject: ...

class ntl_ZZ_pContext_factory:
    def __init__(self) -> None: ...
    def make_c(self, v: builtins.object) -> _SageObject: ...

ZZ_pContext_factory: _SageObject
def ntl_ZZ_pContext(v: builtins.object) -> _SageObject: ...
