from collections.abc import Callable, Iterator

from sage.databases.oeis import FancyTuple, OEISSequence
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject
from sage.structure.unique_representation import UniqueRepresentation

class FindStat(UniqueRepresentation, SageObject):
    def __init__(self) -> None: ...
    def browse(self) -> None: ...
    def set_user(self, name: str | None = ..., email: str | None = ...) -> None: ...
    def user_name(self) -> str: ...
    def user_email(self) -> str: ...
    def login(self) -> None: ...

def findstat(
    query: str | Callable[..., object] | None = ...,
    values: list[tuple[Element, Element]] | None = ...,
    distribution: dict[Element, int] | None = ...,
    domain: FindStatCollection | None = ...,
    depth: int = ...,
    max_values: int | None = ...,
) -> FindStatStatisticQuery | FindStatStatistics | FindStatStatistic | tuple[object, ...]: ...

def findmap(*args: object, **kwargs: object) -> FindStatMapQuery | FindStatMaps | FindStatMap: ...

class FindStatFunction(SageObject):
    def __init__(
        self, id: str, data: dict[str, object] | None = ..., function: Callable[..., object] | None = ...
    ) -> None: ...
    def __call__(self, elt: Element) -> Element: ...
    def reset(self) -> None: ...
    def id(self) -> int: ...
    def id_str(self) -> str: ...
    def domain(self) -> FindStatCollection: ...
    def description(self) -> str: ...
    def set_description(self, value: str) -> None: ...
    def name(self) -> str: ...
    def references(self) -> FancyTuple: ...
    def references_raw(self) -> list[object]: ...
    def set_references_raw(self, value: list[object]) -> None: ...
    def sage_code(self) -> str: ...
    def set_sage_code(self, value: str) -> None: ...

class FindStatCombinatorialStatistic(SageObject):
    def __init__(self) -> None: ...
    def first_terms(self) -> dict[Element, Element]: ...
    def first_terms_str(self, max_values: int = ...) -> str: ...
    def generating_functions(
        self, style: str = ..., max_values: int = ...
    ) -> dict[Element, Element] | list[Element]: ...
    def oeis_search(self, search_size: int = ..., verbose: bool = ...) -> OEISSequence: ...

class FindStatStatistic(Element, FindStatFunction, FindStatCombinatorialStatistic):
    @classmethod
    def __classcall_private__(cls, entry: str | FindStatStatistic) -> FindStatStatistic: ...
    def __init__(self, parent: FindStatStatistics, id: str) -> None: ...
    def __call__(self, elt: Element) -> Element: ...
    def __reduce__(self) -> tuple[type[FindStatStatistic], tuple[int]]: ...
    def set_first_terms(self, values: list[tuple[Element, Element]]) -> Element: ...
    def code(self) -> str: ...
    def set_code(self, value: str) -> None: ...
    def browse(self) -> None: ...
    def submit(self, max_values: int = ...) -> None: ...
    edit: Callable[[int], None]
    def __hash__(self) -> int: ...
    def info(self) -> None: ...

class FindStatStatistics(UniqueRepresentation, Parent):
    def __init__(self, domain: FindStatCollection | None = ...) -> None: ...
    def __iter__(self) -> Iterator[FindStatStatistic]: ...
    Element: type[FindStatStatistic]

class FindStatStatisticQuery(FindStatStatistic):
    def __init__(
        self,
        data: list[tuple[Element, Element]] | None = ...,
        values_of: Element | None = ...,
        distribution_of: Element | None = ...,
        domain: FindStatCollection | None = ...,
        known_terms: dict[Element, Element] | None = ...,
        function: Callable[..., object] | None = ...,
        depth: int = ...,
        debug: bool = ...,
    ) -> None: ...
    def first_terms(self, max_values: int = ...) -> dict[Element, Element]: ...
    def __getitem__(self, i: int) -> tuple[Element, Element]: ...
    def __len__(self) -> int: ...

class FindStatCompoundStatistic(Element, FindStatCombinatorialStatistic):
    def __init__(
        self, id: str, domain: FindStatCollection | None = ..., check: bool = ...
    ) -> None: ...
    def domain(self) -> FindStatCollection: ...
    def __call__(self, elt: Element) -> Element: ...
    def id_str(self) -> str: ...
    def statistic(self) -> FindStatStatistic: ...
    def compound_map(self) -> list[FindStatMap]: ...
    def browse(self) -> None: ...
    def info(self) -> None: ...

class FindStatMatchingStatistic(FindStatCompoundStatistic):
    def __init__(
        self,
        matching_statistic: FindStatStatistic,
        offset: int,
        quality: list[float],
        domain: FindStatCollection | None = ...,
    ) -> None: ...
    def offset(self) -> int: ...
    def quality(self) -> list[float]: ...
    def info(self) -> None: ...

class FindStatCombinatorialMap(SageObject): ...

class FindStatMap(Element, FindStatFunction, FindStatCombinatorialMap):
    @classmethod
    def __classcall_private__(cls, entry: str | FindStatMap) -> FindStatMap: ...
    def __init__(self, parent: FindStatMaps, id: str) -> None: ...
    def __reduce__(self) -> tuple[type[FindStatMap], tuple[int]]: ...
    def browse(self) -> None: ...
    def submit(self) -> None: ...
    edit: Callable[[], None]
    def __hash__(self) -> int: ...
    def codomain(self) -> FindStatCollection: ...
    def properties_raw(self) -> list[object]: ...
    def set_properties_raw(self, value: list[object]) -> None: ...
    def set_name(self, value: str) -> None: ...
    def info(self) -> None: ...

class FindStatMaps(UniqueRepresentation, Parent):
    def __init__(
        self, domain: FindStatCollection | None = ..., codomain: FindStatCollection | None = ...
    ) -> None: ...
    def __iter__(self) -> Iterator[FindStatMap]: ...
    Element: type[FindStatMap]

class FindStatMapQuery(FindStatMap):
    def __init__(
        self,
        data: list[tuple[Element, Element]] | None = ...,
        values_of: Element | None = ...,
        distribution_of: Element | None = ...,
        domain: FindStatCollection | None = ...,
        codomain: FindStatCollection | None = ...,
        known_terms: dict[Element, Element] | None = ...,
        function: Callable[..., object] | None = ...,
        depth: int = ...,
        debug: bool = ...,
    ) -> None: ...
    def __getitem__(self, i: int) -> tuple[Element, Element]: ...
    def __len__(self) -> int: ...

class FindStatCompoundMap(Element, FindStatCombinatorialMap):
    def __init__(
        self,
        id: str,
        domain: FindStatCollection | None = ...,
        codomain: FindStatCollection | None = ...,
        check: bool = ...,
    ) -> None: ...
    def domain(self) -> FindStatCollection: ...
    def codomain(self) -> FindStatCollection: ...
    def __call__(self, elt: Element) -> Element: ...
    def __getitem__(self, i: int) -> FindStatMap: ...
    def id_str(self) -> str: ...
    def maps(self) -> list[FindStatMap]: ...
    def __len__(self) -> int: ...
    def browse(self) -> None: ...
    def info(self) -> None: ...

class FindStatMatchingMap(FindStatCompoundMap):
    def __init__(
        self,
        matching_map: FindStatMap,
        quality: list[float],
        domain: FindStatCollection | None = ...,
        codomain: FindStatCollection | None = ...,
    ) -> None: ...
    def quality(self) -> list[float]: ...
    def info(self) -> None: ...

class FindStatCollection(Element):
    @classmethod
    def __classcall_private__(cls, entry: str | FindStatCollection) -> FindStatCollection: ...
    def __init__(
        self,
        parent: FindStatCollections,
        id: str,
        data: dict[str, object],
        sageconstructor_overridden: bool,
    ) -> None: ...
    def __reduce__(self) -> tuple[type[FindStatCollection], tuple[int]]: ...
    def __hash__(self) -> int: ...
    def is_supported(self) -> bool: ...
    def elements_on_level(self, level: int) -> list[Element]: ...
    def element_level(self, element: Element) -> int | None: ...
    def is_element(self, element: Element | str) -> bool: ...
    def levels_with_sizes(self) -> list[tuple[int, int]]: ...
    def in_range(self, element: Element) -> bool: ...
    def first_terms(
        self, function: Callable[[Element], Element], level: int | None = ...
    ) -> list[tuple[Element, Element]]: ...
    def id(self) -> int: ...
    def id_str(self) -> str: ...
    def browse(self) -> None: ...
    def to_string(self) -> Callable[[Element], str]: ...
    def from_string(self) -> Callable[[str], Element]: ...
    def name(self, style: str = ...) -> str: ...

class FindStatCollections(UniqueRepresentation, Parent):
    def __init__(self) -> None: ...
    def __iter__(self) -> Iterator[FindStatCollection]: ...
    Element: type[FindStatCollection]
