# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

columns_white_list: _SageObject
columns_black_list: _SageObject
class KnotInfoColumnTypes:
    OnlyKnots: _SageObject
    OnlyLinks: _SageObject
    KnotsAndLinks: _SageObject

class KnotInfoColumns:
    @property
    def types(self) -> _SageObject: ...
    def column_name(self) -> _SageObject: ...
    def column_type(self) -> _SageObject: ...
    def description_webpage(self, new: builtins.int = ..., autoraise: builtins.bool = ...) -> _SageObject: ...

class KnotInfoFilename:
    def url(self) -> _SageObject: ...
    def excel(self) -> _SageObject: ...
    def csv(self) -> _SageObject: ...
    def num_knots(self, version: builtins.object) -> _SageObject: ...
    def sobj_row(self) -> _SageObject: ...
    def sobj_column(self) -> _SageObject: ...
    def sobj_data(self, column: builtins.object) -> _SageObject: ...
    def description_url(self, column: builtins.object) -> _SageObject: ...
    def diagram_url(self, fname: builtins.object, single: builtins.bool = ...) -> _SageObject: ...
    knots: _SageObject
    links: _SageObject

class KnotInfoDataBase:
    filename: _SageObject
    def __init__(self, install: builtins.bool = ...) -> None: ...
    def create_filecache(self, force: builtins.bool = ...) -> _SageObject: ...
    def version(self) -> _SageObject: ...
    def demo_version(self) -> _SageObject: ...
    def knot_list(self) -> _SageObject: ...
    def link_list(self) -> _SageObject: ...
    def columns(self) -> _SageObject: ...
    def read_column_dict(self) -> _SageObject: ...
    def read_row_dict(self) -> _SageObject: ...
    def row_names(self) -> _SageObject: ...
    def read_num_knots(self) -> _SageObject: ...
    def read(self, column: builtins.object) -> _SageObject: ...

column_demo_sample: _SageObject
row_demo_sample: _SageObject
db: _SageObject
dc: _SageObject
data_demo_sample: _SageObject
