import builtins
from collections.abc import (
    Iterator as _Iterator,
)
from typing import Self

class _SageObject: ...

sqlite_keywords: _SageObject

def regexp(self, item: builtins.object) -> _SageObject: ...
def verify_type(self) -> _SageObject: ...
def verify_column(self) -> _SageObject: ...
def verify_operator(self) -> _SageObject: ...
def construct_skeleton(self) -> _SageObject: ...

p: _SageObject

class SQLQuery:
    def __init__(
        self, database: builtins.object, *args: builtins.object, **kwds: builtins.object
    ) -> None: ...
    def get_query_string(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def query_results(self) -> _SageObject: ...
    def show(self, **kwds: builtins.object) -> _SageObject: ...
    def __copy__(self) -> Self: ...
    def intersect(
        self,
        other: builtins.object,
        join_table: builtins.object = ...,
        join_dict: builtins.object = ...,
        in_place: builtins.bool = ...,
    ) -> _SageObject: ...
    def union(
        self,
        other: builtins.object,
        join_table: builtins.object = ...,
        join_dict: builtins.object = ...,
        in_place: builtins.bool = ...,
    ) -> _SageObject: ...

class SQLDatabase:
    ignore_warnings: bool

    def __init__(
        self,
        filename: builtins.object = ...,
        read_only: builtins.object = ...,
        skeleton: builtins.object = ...,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: builtins.object, exc: builtins.object, tb: builtins.object
    ) -> builtins.bool | None: ...
    def __copy__(self) -> Self: ...
    def save(self, filename: builtins.object) -> _SageObject: ...
    def get_skeleton(self, check: builtins.bool = ...) -> _SageObject: ...
    def query(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def show(
        self, table_name: builtins.str, **kwds: builtins.object
    ) -> _SageObject: ...
    def get_cursor(self, ignore_warning: builtins.object = ...) -> _SageObject: ...
    def get_connection(self, ignore_warning: builtins.object = ...) -> _SageObject: ...
    def create_table(
        self, table_name: builtins.str, table_skeleton: builtins.object
    ) -> _SageObject: ...
    def add_column(
        self,
        table_name: builtins.str,
        col_name: builtins.str,
        col_dict: builtins.object,
        default: builtins.str = ...,
    ) -> _SageObject: ...
    def drop_column(
        self, table_name: builtins.str, col_name: builtins.str
    ) -> _SageObject: ...
    def rename_table(
        self, table_name: builtins.str, new_name: builtins.str
    ) -> _SageObject: ...
    def drop_table(self, table_name: builtins.str) -> _SageObject: ...
    def drop_data_from_table(self, table_name: builtins.str) -> _SageObject: ...
    def make_index(
        self,
        col_name: builtins.str,
        table_name: builtins.str,
        unique: builtins.bool = ...,
    ) -> _SageObject: ...
    def drop_index(
        self, table_name: builtins.str, index_name: builtins.str
    ) -> _SageObject: ...
    def make_unique(
        self, table_name: builtins.str, col_name: builtins.str
    ) -> _SageObject: ...
    def drop_unique(
        self, table_name: builtins.str, col_name: builtins.str
    ) -> _SageObject: ...
    def make_primary_key(
        self, table_name: builtins.str, col_name: builtins.str
    ) -> _SageObject: ...
    def drop_primary_key(
        self, table_name: builtins.str, col_name: builtins.str
    ) -> _SageObject: ...
    def add_row(
        self,
        table_name: builtins.str,
        values: builtins.object,
        entry_order: builtins.object = ...,
    ) -> _SageObject: ...
    def delete_rows(self, query: builtins.object) -> _SageObject: ...
    def add_rows(
        self,
        table_name: builtins.str,
        rows: builtins.object,
        entry_order: builtins.object = ...,
    ) -> _SageObject: ...
    add_data: _SageObject

    def vacuum(self) -> _SageObject: ...
    def commit(self) -> _SageObject: ...
