import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class SteinWatkinsIsogenyClass:
    def __init__(self, conductor: builtins.object) -> None: ...
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SteinWatkinsAllData:
    def __init__(self, num: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...
    next: _SageObject

    def __getitem__(self, N: builtins.int) -> _SageObject: ...
    def iter_levels(self) -> _SageObject: ...

class SteinWatkinsPrimeData:
    def __init__(self, num: builtins.object) -> None: ...

def ecdb_num_curves(self=...) -> _SageObject: ...
