# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ProjectiveConic_rational_function_field:
    def __init__(self, A: builtins.object, f: builtins.object) -> None: ...
    def has_rational_point(self, point: builtins.bool = ..., algorithm: builtins.str = ..., read_cache: builtins.bool = ...) -> builtins.bool: ...
    def find_point(self, supports: builtins.object, roots: builtins.object, case: builtins.object, solution: builtins.int = ...) -> _SageObject: ...
