import builtins

from sage.structure.element import Element

class _SageObject: ...

class ProjectiveConic_field:
    def __init__(self, A: builtins.object, f: builtins.object) -> None: ...
    def base_extend(self, S: builtins.object) -> _SageObject: ...
    def cache_point(self, p: builtins.int) -> _SageObject: ...
    def coefficients(self) -> _SageObject: ...
    def derivative_matrix(self) -> _SageObject: ...
    def determinant(self) -> _SageObject: ...
    def diagonal_matrix(self) -> _SageObject: ...
    def diagonalization(self, names: builtins.object = ...) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def has_rational_point(
        self,
        point: builtins.bool = ...,
        algorithm: builtins.str = ...,
        read_cache: builtins.bool = ...,
    ) -> builtins.bool: ...
    def has_singular_point(self, point: builtins.bool = ...) -> builtins.bool: ...
    def hom(self, x: builtins.object, Y: builtins.object = ...) -> _SageObject: ...
    def is_diagonal(self) -> bool: ...
    def is_smooth(self) -> bool: ...
    def matrix(self) -> _SageObject: ...
    def parametrization(
        self, point: builtins.object = ..., morphism: builtins.bool = ...
    ) -> _SageObject: ...
    def point(self, v: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def random_rational_point(
        self, *args1: builtins.object, **args2: builtins.object
    ) -> _SageObject: ...
    def rational_point(
        self, algorithm: builtins.str = ..., read_cache: builtins.bool = ...
    ) -> _SageObject: ...
    def singular_point(self) -> _SageObject: ...
    def symmetric_matrix(self) -> _SageObject: ...
    def upper_triangular_matrix(self) -> _SageObject: ...
    def variable_names(self) -> _SageObject: ...
