# cypari2 2.2.4, cypari2/gen.pyx and the generated cypari2/auto_gen.pxi.
# Each signature is the one `inspect.signature` reports for the installed
# module. `Gen_base` holds the methods generated from PARI's function table;
# `Gen` holds the hand-written ones and the Python protocols.
from collections.abc import Iterator, Sequence
from typing import Protocol, SupportsIndex

# A value that converts to PARI through its `__pari__` method, as a SageMath
# element does.
class SupportsPari(Protocol):
    def __pari__(self) -> Gen: ...

# What `objtogen` in cypari2/convert.pyx converts to a PARI object: a `Gen`,
# a value with `__pari__`, a Python number, a GP expression as a string, and
# a sequence of these (a PARI vector).
type PariInput = Gen | SupportsPari | int | float | complex | str | Sequence[PariInput]

class Gen_base:
    def type(self) -> str: ...
    def mattranspose(self) -> Gen: ...
    def matsnf(self, flag: int = 0) -> Gen: ...
    def qfauto(self, fl: PariInput | None = None) -> Gen: ...
    def qfisom(self, H: PariInput, fl: PariInput | None = None, grp: PariInput | None = None) -> Gen: ...
    def qfminim(self, B: PariInput | None = None, m: PariInput | None = None, flag: int = 0, precision: int = 64) -> Gen: ...
    def qfrep(self, B: PariInput, flag: int = 0) -> Gen: ...
    def qfsolve(self) -> Gen: ...

class Gen(Gen_base):
    def __call__(self, *args: PariInput) -> Gen: ...
    def __getitem__(self, n: SupportsIndex | tuple[SupportsIndex, SupportsIndex]) -> Gen: ...
    def __iter__(self) -> Iterator[Gen]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __float__(self) -> float: ...
    def __neg__(self) -> Gen: ...
    def __add__(self, right: PariInput) -> Gen: ...
    def __radd__(self, left: PariInput) -> Gen: ...
    def __sub__(self, right: PariInput) -> Gen: ...
    def __rsub__(self, left: PariInput) -> Gen: ...
    def __mul__(self, right: PariInput) -> Gen: ...
    def __rmul__(self, left: PariInput) -> Gen: ...
    def __truediv__(self, right: PariInput) -> Gen: ...
    def __rtruediv__(self, left: PariInput) -> Gen: ...
    def __floordiv__(self, right: PariInput) -> Gen: ...
    def __mod__(self, right: PariInput) -> Gen: ...
    def __pow__(self, n: PariInput) -> Gen: ...
    def ncols(self) -> int: ...
    def nrows(self) -> int: ...
