# cypari2 2.2.4, cypari2/pari_instance.pyx and the generated
# cypari2/auto_instance.pxi. `Pari_auto` holds the PARI functions generated
# from PARI's function table; `Pari` holds the hand-written ones.
from cypari2.gen import Gen, PariInput

class Pari_auto:
    def coredisc(self, n: PariInput, flag: int = 0) -> Gen: ...
    def factor(self, x: PariInput, D: PariInput | None = None) -> Gen: ...
    def matdiagonal(self, x: PariInput) -> Gen: ...
    def partitions(self, k: PariInput, a: PariInput | None = None, n: PariInput | None = None) -> Gen: ...

class Pari(Pari_auto):
    def __init__(self, size: int = 8000000, sizemax: int = 0, maxprime: int = 500000) -> None: ...
    def __call__(self, s: PariInput) -> Gen: ...
    def matrix(self, m: int, n: int, entries: PariInput | None = None) -> Gen: ...
