from sage.categories.action import Action
from sage.rings.function_field.drinfeld_modules.drinfeld_module import DrinfeldModule
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import RingElement

class DrinfeldModuleAction(Action):
    def __init__(self, drinfeld_module: DrinfeldModule) -> None: ...
    def _act_(self, pol: Polynomial, x: RingElement) -> RingElement: ...
    def drinfeld_module(self) -> DrinfeldModule: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
