from sage.categories.action import Action
from sage.structure.element import Element
from sage.structure.parent import ElementConstructorInput

class DrinfeldModuleAction(Action):
    def __init__(self, drinfeld_module: ElementConstructorInput) -> None: ...
    def drinfeld_module(self) -> Element: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
