import builtins

class _SageObject: ...

def CarlitzModule(self, base: builtins.object = ...) -> _SageObject: ...
def carlitz_exponential(
    self, prec: builtins.int = ..., name: builtins.str = ...
) -> _SageObject: ...
def carlitz_logarithm(
    self, prec: builtins.int = ..., name: builtins.str = ...
) -> _SageObject: ...
def carlitz_factorial(self, n: builtins.int) -> _SageObject: ...

carlitz_series: _SageObject

def carlitz_bernoulli(self, n: builtins.int) -> _SageObject: ...
