from sage.categories.category import Category
from sage.categories.morphism import Morphism
from sage.rings.integer import Integer
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.unique_representation import UniqueRepresentation

class DrinfeldModule(Parent, UniqueRepresentation):
    @staticmethod
    def __classcall_private__(
        class_: type[DrinfeldModule],
        function_ring: Polynomial | MPolynomial,
        gen: Polynomial | MPolynomial,
        A_field: ElementConstructorInput = ...,
        name: str = ...,
    ) -> DrinfeldModule: ...
    def __init__(self, gen: Polynomial | MPolynomial, category: Category) -> None: ...
    def __call__(self, a: Element | ElementConstructorInput) -> Element: ...
    def __hash__(self) -> int: ...
    def action(self) -> Element: ...
    def basic_j_invariant_parameters(
        self, coeff_indices: int | Integer = ..., nonzero: int | Integer = ...
    ) -> Element: ...
    def basic_j_invariants(self, nonzero: ElementConstructorInput = ...) -> Element: ...
    def coefficient(self, n: int | Integer) -> Element: ...
    def coefficients(self, sparse: bool = ...) -> list[Element]: ...
    def change_A_field(self, A_field: ElementConstructorInput) -> Element: ...
    def gen(self) -> Element: ...
    def height(self) -> Element: ...
    def is_isomorphic(
        self,
        other: Element | ElementConstructorInput,
        absolutely: ElementConstructorInput = ...,
    ) -> bool: ...
    def is_finite(self) -> bool: ...
    def j_invariant(
        self, parameter: int | Integer = ..., check: bool = ...
    ) -> Element: ...
    def jk_invariants(self) -> Element: ...
    def morphism(self) -> Morphism: ...
    def rank(self) -> int | Integer: ...
    def velu(self, isog: Polynomial | MPolynomial) -> Element: ...
    def hom(
        self, x: Element | ElementConstructorInput, codomain: Parent = ...
    ) -> Morphism: ...
    def scalar_multiplication(
        self, x: Element | ElementConstructorInput
    ) -> Element: ...
    def frobenius_relative(self, n: int | Integer = ...) -> Element: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
