# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DrinfeldModule_finite:
    def __init__(self, gen: builtins.object, category: builtins.object) -> None: ...
    def frobenius_endomorphism(self) -> _SageObject: ...
    def frobenius_charpoly(self, var: builtins.str = ..., algorithm: builtins.str = ...) -> _SageObject: ...
    def frobenius_norm(self) -> _SageObject: ...
    def frobenius_trace(self, algorithm: builtins.str = ...) -> _SageObject: ...
    def invert(self, ore_pol: builtins.object) -> _SageObject: ...
    def is_isogenous(self, psi: builtins.object) -> builtins.bool: ...
    def is_supersingular(self) -> builtins.bool: ...
    def is_ordinary(self) -> builtins.bool: ...
