# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DrinfeldModuleMorphism:
    @staticmethod
    def __classcall_private__(cls: builtins.object, parent: builtins.object, x: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, ore_pol: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def is_zero(self) -> builtins.bool: ...
    def is_identity(self) -> builtins.bool: ...
    def is_isogeny(self) -> builtins.bool: ...
    def is_isomorphism(self) -> builtins.bool: ...
    def ore_polynomial(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def inverse(self) -> _SageObject: ...
    def __invert__(self) -> Self: ...
    def right_gcd(self, other: builtins.object) -> _SageObject: ...
    def left_lcm(self, other: builtins.object) -> _SageObject: ...
    def norm(self, ideal: builtins.bool = ...) -> _SageObject: ...
    def dual_isogeny(self) -> _SageObject: ...
    def characteristic_polynomial(self, var: builtins.str = ...) -> _SageObject: ...
    def charpoly(self, var: builtins.str = ...) -> _SageObject: ...
