# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def mpfr_from_mpfval(res: builtins.object, x: builtins.object) -> _SageObject: ...

def mpfr_to_mpfval(value: builtins.object) -> _SageObject: ...

def mpmath_to_sage(x: builtins.object, prec: builtins.object) -> _SageObject: ...

def sage_to_mpmath(x: builtins.object, prec: builtins.object) -> _SageObject: ...

def call(func: builtins.object, *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
