from sage.groups.abelian_gps.abelian_group import AbelianGroup_class

class GenericCellComplex: ...

class CubicalComplex(GenericCellComplex):
    def dimension(self) -> int: ...
    def euler_characteristic(self) -> int: ...
    def homology(self, deg: int | None = None) -> dict[int, AbelianGroup_class] | AbelianGroup_class: ...
