import builtins

class _SageObject: ...

class FilteredSimplicialComplex:
    def __init__(
        self, simplices: builtins.list[_SageObject] = ..., verbose: builtins.bool = ...
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def insert(
        self, vertex_list: builtins.object, filtration_value: builtins.object
    ) -> _SageObject: ...
    def filtration(
        self, s: builtins.object, filtration_value: builtins.object = ...
    ) -> _SageObject: ...
    def prune(self, threshold: builtins.object) -> _SageObject: ...
    def persistence_intervals(
        self,
        dimension: builtins.int,
        field: builtins.int = ...,
        strict: builtins.bool = ...,
        verbose: builtins.object = ...,
    ) -> _SageObject: ...
    def betti_number(
        self,
        k: builtins.int,
        a: builtins.object,
        b: builtins.object,
        field: builtins.int = ...,
        strict: builtins.bool = ...,
        verbose: builtins.object = ...,
    ) -> _SageObject: ...
