# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AbstractSimplex_class:
    def __init__(self, dim: builtins.object, degeneracies: builtins.tuple[_SageObject, ...] = ..., underlying: builtins.object = ..., name: builtins.str = ..., latex_name: builtins.str = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def nondegenerate(self) -> _SageObject: ...
    def degeneracies(self) -> _SageObject: ...
    def is_degenerate(self) -> builtins.bool: ...
    def is_nondegenerate(self) -> builtins.bool: ...
    def dimension(self) -> _SageObject: ...
    def apply_degeneracies(self, *args: builtins.object) -> _SageObject: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: builtins.object) -> Self: ...

class NonDegenerateSimplex:
    def __init__(self, dim: builtins.object, name: builtins.str = ..., latex_name: builtins.str = ...) -> None: ...

def AbstractSimplex(dim: builtins.object, degeneracies: builtins.tuple[_SageObject, ...] = ..., underlying: builtins.object = ..., name: builtins.str = ..., latex_name: builtins.str = ...) -> _SageObject: ...

class SimplicialSet_arbitrary:
    def faces(self, simplex: builtins.object) -> _SageObject: ...
    def face(self, simplex: builtins.object, i: builtins.int) -> _SageObject: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def alexander_whitney(self, simplex: builtins.object, dim_left: builtins.object) -> _SageObject: ...
    def nondegenerate_simplices(self, max_dim: builtins.object = ...) -> _SageObject: ...
    def cells(self, subcomplex: builtins.object = ..., max_dim: builtins.object = ...) -> _SageObject: ...
    def n_cells(self, n: builtins.int, subcomplex: builtins.object = ...) -> _SageObject: ...
    def all_n_simplices(self, n: builtins.int) -> _SageObject: ...
    def identity(self) -> _SageObject: ...
    def constant_map(self, codomain: builtins.object = ..., point: builtins.object = ...) -> _SageObject: ...
    def is_reduced(self) -> builtins.bool: ...
    def graph(self) -> _SageObject: ...
    def is_connected(self) -> builtins.bool: ...
    def subsimplicial_set(self, simplices: builtins.object) -> _SageObject: ...
    def chain_complex(self, dimensions: builtins.object = ..., base_ring: builtins.object = ..., augmented: builtins.bool = ..., cochain: builtins.bool = ..., verbose: builtins.bool = ..., subcomplex: builtins.object = ..., check: builtins.bool = ...) -> _SageObject: ...
    def homology(self, dim: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def cohomology(self, dim: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def betti(self, dim: builtins.object = ..., subcomplex: builtins.object = ...) -> _SageObject: ...
    def n_chains(self, n: builtins.int, base_ring: builtins.object = ..., cochains: builtins.bool = ...) -> _SageObject: ...
    def quotient(self, subcomplex: builtins.object, vertex_name: builtins.str = ...) -> _SageObject: ...
    def disjoint_union(self, *others: builtins.object) -> _SageObject: ...
    def coproduct(self, *others: builtins.object) -> _SageObject: ...
    def product(self, *others: builtins.object) -> _SageObject: ...
    cartesian_product: _SageObject
    def pushout(self, *maps: builtins.object) -> _SageObject: ...
    def pullback(self, *maps: builtins.object) -> _SageObject: ...
    def wedge(self, *others: builtins.object) -> _SageObject: ...
    def cone(self) -> _SageObject: ...
    def suspension(self, n: builtins.int = ...) -> _SageObject: ...
    def join(self, *others: builtins.object) -> _SageObject: ...
    def reduce(self) -> _SageObject: ...
    def rename_latex(self, s: builtins.object) -> _SageObject: ...

class SimplicialSet_finite:
    def __init__(self, data: builtins.object, base_point: builtins.object = ..., name: builtins.str = ..., check: builtins.bool = ..., category: builtins.object = ..., latex_name: builtins.str = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __copy__(self) -> Self: ...
    def face_data(self) -> _SageObject: ...
    def n_skeleton(self, n: builtins.int) -> _SageObject: ...
    def f_vector(self) -> _SageObject: ...
    def euler_characteristic(self) -> _SageObject: ...
    def chain_complex(self, dimensions: builtins.object = ..., base_ring: builtins.object = ..., augmented: builtins.bool = ..., cochain: builtins.bool = ..., verbose: builtins.bool = ..., subcomplex: builtins.object = ..., check: builtins.bool = ...) -> _SageObject: ...
    def algebraic_topological_model(self, base_ring: builtins.object = ...) -> _SageObject: ...

SimplicialSet: _SageObject
def standardize_degeneracies(*L: builtins.object) -> _SageObject: ...

def all_degeneracies(n: builtins.int, l: builtins.int = ...) -> _SageObject: ...

def standardize_face_maps(*L: builtins.object) -> _SageObject: ...

def face_degeneracies(m: builtins.int, I: builtins.int) -> _SageObject: ...

def shrink_simplicial_complex(K: builtins.int) -> _SageObject: ...
