import builtins
from collections.abc import (
    Hashable,
)

from sage.structure.element import Element

class _SageObject: ...

kenzo_path: _SageObject

class Nerve:
    def __init__(self, monoid: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def n_skeleton(self, n: builtins.int) -> _SageObject: ...

def Sphere(self) -> _SageObject: ...
def ClassifyingSpace(self) -> _SageObject: ...
def RealProjectiveSpace(self) -> _SageObject: ...
def KleinBottle(self) -> _SageObject: ...
def Torus(self) -> _SageObject: ...
def Simplex(self) -> _SageObject: ...
def Empty(self) -> _SageObject: ...
def Point(self) -> _SageObject: ...
def Horn(self, k: builtins.int) -> _SageObject: ...
def ComplexProjectiveSpace(self) -> _SageObject: ...
def simplicial_data_from_kenzo_output(self) -> dict[Hashable, Element]: ...
def HopfMap(self) -> _SageObject: ...
def PresentationComplex(self) -> _SageObject: ...
