import builtins

class _SageObject: ...

class SimplicialComplexMorphism:
    def __init__(
        self, f: builtins.object, X: builtins.object, Y: builtins.object
    ) -> None: ...
    def __eq__(self, x: object) -> bool: ...
    def __call__(
        self, x: builtins.object, orientation: builtins.bool = ...
    ) -> _SageObject: ...
    def associated_chain_complex_morphism(
        self,
        base_ring: builtins.object = ...,
        augmented: builtins.bool = ...,
        cochain: builtins.bool = ...,
    ) -> _SageObject: ...
    def image(self) -> _SageObject: ...
    def is_surjective(self) -> bool: ...
    def is_injective(self) -> bool: ...
    def is_identity(self) -> bool: ...
    def fiber_product(
        self, other: builtins.object, rename_vertices: builtins.bool = ...
    ) -> _SageObject: ...
    def mapping_torus(self) -> _SageObject: ...
    def induced_homology_morphism(
        self, base_ring: builtins.object = ..., cohomology: builtins.bool = ...
    ) -> _SageObject: ...
    def is_contiguous_to(self, other: builtins.object) -> builtins.bool: ...
