# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SimplicialComplexHomset:
    def __call__(self, f: builtins.object) -> _SageObject: ...
    def diagonal_morphism(self, rename_vertices: builtins.bool = ...) -> _SageObject: ...
    def identity(self) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
