# Generated from the pinned Sage 10.7 source tree.
from collections.abc import Iterable

from sage.libs.gap.context_managers import GlobalVariableContext
from sage.libs.gap.element import GapElement
from sage.rings.integer import Integer

class Gap:
    # libgap.pyx:479: ``None`` when GAP returns no value.
    def eval(self, gap_command: str) -> GapElement | None: ...
    def load_package(self, pkg: str) -> GapElement: ...
    def function_factory(self, function_name: str) -> GapElement: ...
    def set_global(self, variable: str, value: object) -> None: ...
    def unset_global(self, variable: str) -> None: ...
    def get_global(self, variable: str) -> GapElement: ...
    def global_context(self, variable: str, value: object) -> GlobalVariableContext: ...
    def set_seed(self, seed: int | Integer | None = None) -> int | Integer: ...
    def zero(self) -> GapElement: ...
    def one(self) -> GapElement: ...
    def __init__(self) -> None: ...
    def __dir__(self) -> Iterable[str]: ...
    def __getattr__(self, name: str) -> GapElement: ...
    # libgap.pyx:796: the object count, ``TotalMemoryAllocated()`` and the
    # ``GasmanStatistics()`` record, converted by ``.sage()``.
    def show(self) -> dict[str, int | Integer | dict[str, list[Integer]]]: ...
    def count_GAP_objects(self) -> int: ...
    def collect(self) -> None: ...

# libgap.pyx:871.
libgap: Gap
