import builtins

class _SageObject: ...

def hilbert_class_polynomial(self, algorithm: builtins.str = ...) -> _SageObject: ...
def is_HCP(self, check_monic_irreducible: builtins.bool = ...) -> builtins.bool: ...
def OrderClassNumber(self, h0: builtins.object, f: builtins.object) -> _SageObject: ...
def cm_j_invariants(self, proof: builtins.bool = ...) -> _SageObject: ...
def cm_j_invariants_and_orders(self, proof: builtins.bool = ...) -> _SageObject: ...
def cm_orders(self, proof: builtins.bool = ...) -> _SageObject: ...

watkins_table: _SageObject
klaise_table: _SageObject

def largest_fundamental_disc_with_class_number(self) -> _SageObject: ...
def largest_disc_with_class_number(self) -> _SageObject: ...

hDf_dict: _SageObject

def discriminants_with_bounded_class_number(
    self, B: builtins.object = ..., proof: builtins.bool = ...
) -> _SageObject: ...
def is_cm_j_invariant(
    self, algorithm: builtins.str = ..., method: builtins.object = ...
) -> builtins.bool: ...
