from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ring import Ring
from sage.schemes.elliptic_curves.ell_generic import EllipticCurve_generic
from sage.schemes.projective.projective_point import ProjectivePoint

class EllipticCurveFactory:
    def create_key_and_extra_args(
        self,
        x: object = ...,
        y: object = ...,
        j: object = ...,
        minimal_twist: bool = ...,
    ) -> tuple[tuple[object, ...], dict[str, object]]: ...
    def create_object(
        self, version: str, key: tuple[object, ...], **extra_args: object
    ) -> EllipticCurve_generic: ...

EllipticCurve: EllipticCurveFactory

def _parse_multivariate_defining_equation(self) -> list[object]: ...
def coefficients_from_Weierstrass_polynomial(
    self,
) -> tuple[object, object, object, object, object]: ...
def EllipticCurve_from_Weierstrass_polynomial(self) -> EllipticCurve_generic: ...
def EllipticCurve_from_c4c6(self, c6: object) -> EllipticCurve_generic: ...
def EllipticCurve_from_j(self, minimal_twist: bool = ...) -> EllipticCurve_generic: ...
def coefficients_from_j(
    self, minimal_twist: bool = ...
) -> tuple[object, object, object, object, object]: ...
def EllipticCurve_from_cubic(
    self, P: list[object] | tuple[object, ...] | None = ..., morphism: bool = ...
) -> EllipticCurve_generic | tuple[EllipticCurve_generic, object]: ...
def tangent_at_smooth_point(
    self, P: ProjectivePoint | list[object] | tuple[object, ...]
) -> Polynomial: ...
def chord_and_tangent(
    self, P: ProjectivePoint | list[object] | tuple[object, ...]
) -> ProjectivePoint: ...
def projective_point(self) -> ProjectivePoint: ...
def are_projectively_equivalent(self, Q: object, base_ring: Ring) -> bool: ...
def EllipticCurves_with_good_reduction_outside_S(
    self=..., proof: bool | None = ..., verbose: bool = ...
) -> list[EllipticCurve_generic]: ...
