from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import RingElement


from sage.schemes.curves.projective_curve import ProjectivePlaneCurve
from sage.schemes.elliptic_curves.ell_generic import EllipticCurve_generic
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.schemes.generic.algebraic_scheme import AlgebraicScheme
from sage.schemes.generic.scheme import Scheme
from sage.schemes.projective.projective_point import ProjectivePoint

class EllipticCurveFactory:
    def create_key_and_extra_args(
        self,
        x: object = ...,
        y: object = ...,
        j: object = ...,
        minimal_twist: bool = ...,
    ) -> tuple[tuple[object, ...], dict[str, object]]: ...
    def create_object(self, version: str, key: tuple[object, ...], **extra_args: object) -> EllipticCurve_generic: ...

EllipticCurve: EllipticCurveFactory

def _parse_multivariate_defining_equation(g: object) -> list[object]: ...
def coefficients_from_Weierstrass_polynomial(f: Polynomial) -> tuple[object, object, object, object, object]: ...
def EllipticCurve_from_Weierstrass_polynomial(f: Polynomial) -> EllipticCurve_generic: ...
def EllipticCurve_from_c4c6(c4: object, c6: object) -> EllipticCurve_generic: ...
def EllipticCurve_from_j(j: object, minimal_twist: bool = ...) -> EllipticCurve_generic: ...
def coefficients_from_j(j: object, minimal_twist: bool = ...) -> tuple[object, object, object, object, object]: ...
def EllipticCurve_from_cubic(F: Polynomial, P: list[object] | tuple[object, ...] | None = ..., morphism: bool = ...) -> EllipticCurve_generic | tuple[EllipticCurve_generic, object]: ...
def tangent_at_smooth_point(C: AlgebraicScheme, P: ProjectivePoint | list[object] | tuple[object, ...]) -> Polynomial: ...
def chord_and_tangent(F: Polynomial, P: ProjectivePoint | list[object] | tuple[object, ...]) -> ProjectivePoint: ...
def projective_point(p: object) -> ProjectivePoint: ...
def are_projectively_equivalent(P: object, Q: object, base_ring: Ring) -> bool: ...
def EllipticCurves_with_good_reduction_outside_S(S: list[object] = ..., proof: bool | None = ..., verbose: bool = ...) -> list[EllipticCurve_generic]: ...
