from typing import TYPE_CHECKING
from sage.rings.integer import Integer
from sage.schemes.elliptic_curves.ell_generic import EllipticCurve_generic
from sage.schemes.curves.projective_curve import ProjectivePlaneCurve_field

if TYPE_CHECKING:
    from sage.rings.ring import Ring
    from sage.rings.field import Field
    from sage.schemes.elliptic_curves.ell_curve_isogeny import EllipticCurveIsogeny

class EllipticCurve_field(EllipticCurve_generic, ProjectivePlaneCurve_field):
    def __init__(self, R: Field, data, category=None) -> None: ...
    def genus(self) -> Integer: ...
    def quadratic_twist(self, D=None) -> EllipticCurve_field: ...
    def two_torsion_rank(self) -> int: ...
    def quartic_twist(self, D) -> EllipticCurve_field: ...
    def sextic_twist(self, D) -> EllipticCurve_field: ...
    def is_quadratic_twist(self, other: EllipticCurve_field): ...
    def is_quartic_twist(self, other: EllipticCurve_field): ...
    def is_sextic_twist(self, other: EllipticCurve_field): ...
    def descend_to(self, K: Field, f=None) -> list: ...
    def division_field(self, n: Integer, names: str = ..., map: bool = ..., **kwds): ...
    def torsion_subgroup(self, n: Integer, *, extend: bool = ..., algorithm: str | None = ...): ...
    def torsion_gens(self, n: Integer, *args, **kwds): ...
