from typing import Self
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import RingElement, Element
from sage.schemes.elliptic_curves.ell_generic import EllipticCurve_generic
from sage.schemes.projective.projective_point import SchemeMorphism_point_projective_ring
from sage.schemes.projective.projective_homset import SchemeHomset_points_abelian_variety_field
from sage.libs.pari.gen import gen as pari_gen
from sage.plot.graphics import Graphics
from sage.rings.polynomial.polynomial_element import Polynomial
import typing

# We drop bases like AdditiveGroupElement, SchemeMorphism_point_abelian_variety_field, etc.
# Actually we can keep EllipticCurvePoint_field as inheriting from some common bases if needed, but drop it for simplicity.
class EllipticCurvePoint_field:
    def __init__(self, curve: EllipticCurve_generic, v: tuple[object, ...], check: bool = ...) -> None: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __getitem__(self, n: int) -> RingElement: ...
    def __iter__(self) -> typing.Iterator[RingElement]: ...
    def __tuple__(self) -> tuple[RingElement, ...]: ...
    def _richcmp_(self, other: object, op: int) -> bool: ...
    def __pari__(self) -> pari_gen: ...
    def order(self, algorithm: str | None = ...) -> Integer: ...
    def _compute_order(self, algorithm: str | None = ...) -> Integer: ...
    def __bool__(self) -> bool: ...
    def has_order(self, n: int | Integer) -> bool: ...
    def has_finite_order(self) -> bool: ...
    def has_infinite_order(self) -> bool: ...
    def plot(self) -> Graphics: ...
    def _add_(self, other: EllipticCurvePoint_field) -> EllipticCurvePoint_field: ...
    def _neg_(self) -> EllipticCurvePoint_field: ...
    def xy(self) -> tuple[RingElement, RingElement]: ...
    def x(self) -> RingElement: ...
    def y(self) -> RingElement: ...
    def is_divisible_by(self, m: int | Integer) -> bool: ...
    def division_points(self, m: int | Integer, poly_only: bool = ...) -> list[EllipticCurvePoint_field] | Polynomial: ...
    def divide(self, d: int | Integer) -> list[EllipticCurvePoint_field]: ...
    def _divide_out(self, p: int | Integer) -> EllipticCurvePoint_field: ...
    def set_order(self, value: Integer | float) -> None: ...
    def _line_(self, R: EllipticCurvePoint_field, Q: EllipticCurvePoint_field) -> RingElement: ...
    def _miller_(self, Q: EllipticCurvePoint_field, n: int | Integer) -> RingElement: ...
    def weil_pairing(self, Q: EllipticCurvePoint_field, n: int | Integer, algorithm: str | None = ...) -> RingElement: ...
    def tate_pairing(self, Q: EllipticCurvePoint_field, n: int | Integer, k: int | Integer, q: int | Integer = ...) -> RingElement: ...
    def ate_pairing(self, Q: EllipticCurvePoint_field, n: int | Integer, k: int | Integer, t: int | Integer, q: int | Integer = ...) -> RingElement: ...
    def point_of_jacobian_of_curve(self) -> Element: ...
