from typing import Self

from sage.matrix.matrix import Matrix
from sage.categories.map import Map
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.rings.integer import Integer
from sage.schemes.elliptic_curves.ell_field import EllipticCurve_field
from sage.schemes.elliptic_curves.ell_local_data import EllipticCurveLocalData
from sage.schemes.elliptic_curves.ell_point import EllipticCurvePoint_number_field


class EllipticCurve_number_field(EllipticCurve_field):
    def __init__(self, K: Ring, ainvs: tuple[RingElement, ...]) -> None: ...
    def base_extend(self, R: Ring | Map) -> Self: ...
    def simon_two_descent(
        self,
        verbose: int = ...,
        lim1: int = ...,
        lim3: int = ...,
        limtriv: int = ...,
        maxprob: int = ...,
        limbigprime: int = ...,
        known_points: list[EllipticCurvePoint_number_field] | None = ...,
    ) -> tuple[int, int, list[EllipticCurvePoint_number_field]]: ...
    def height_pairing_matrix(
        self,
        points: list[EllipticCurvePoint_number_field] | None = ...,
        precision: int | None = ...,
        normalised: bool = ...,
    ) -> Matrix: ...
    def regulator_of_points(
        self,
        points: list[EllipticCurvePoint_number_field] = ...,
        precision: int | None = ...,
        normalised: bool = ...,
    ) -> RingElement: ...
    def is_local_integral_model(self, *P: object) -> bool: ...
    def local_integral_model(self, *P: object) -> Self: ...
    def is_global_integral_model(self) -> bool: ...
    def global_integral_model(self) -> Self: ...
    def integral_model(self) -> Self: ...
    def _reduce_model(self) -> Self: ...
    def _scale_by_units(self) -> Self: ...
    def local_data(self, P: object | None = ..., proof: bool | None = ..., algorithm: str = ..., globally: bool = ...) -> EllipticCurveLocalData | list[EllipticCurveLocalData]: ...
    def _get_local_data(self, P: object | None = ..., proof: bool | None = ..., algorithm: str = ..., globally: bool = ...) -> EllipticCurveLocalData: ...
    def local_minimal_model(self, P: object, proof: bool | None = ..., algorithm: str = ...) -> Self: ...
    def has_good_reduction(self, P: object) -> bool: ...
    def has_bad_reduction(self, P: object) -> bool: ...
    def has_multiplicative_reduction(self, P: object) -> bool: ...
    def has_split_multiplicative_reduction(self, P: object) -> bool: ...
    def has_nonsplit_multiplicative_reduction(self, P: object) -> bool: ...
    def has_additive_reduction(self, P: object) -> bool: ...
    def tamagawa_number(self, P: object, proof: bool | None = ...) -> int: ...
    def tamagawa_numbers(self) -> list[int]: ...
    def tamagawa_exponent(self, P: object, proof: bool | None = ...) -> int: ...
