from typing import Self
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import RingElement


from sage.categories.category import Category
from sage.categories.map import Map
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.symbolic.expression import Expression
from sage.plot.graphics import Graphics
from sage.libs.pari.gen import gen as pari_gen

from ..curves.projective_curve import ProjectivePlaneCurve
from ..projective.projective_homset import SchemeHomset_points_abelian_variety_field
from ..projective.projective_morphism import SchemeMorphism_polynomial_projective_space
from ..projective.projective_point import SchemeMorphism_point_projective_ring
from .ell_curve_isogeny import EllipticCurveIsogeny
from .ell_point import EllipticCurvePoint_field
from .formal_group import EllipticCurveFormalGroup
from .weierstrass_morphism import WeierstrassIsomorphism

class EllipticCurve_generic(ProjectivePlaneCurve):
    def __init__(self, K: Ring, ainvs: tuple[object, ...], category: Category | None = ...) -> None: ...
    def assume_base_ring_is_field(self, flag: bool = ...) -> None: ...
    def _defining_params_(self) -> tuple[Ring, tuple[RingElement, RingElement, RingElement, RingElement, RingElement]]: ...
    def _equation_string(self) -> str: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _pari_init_(self) -> str: ...
    def _magma_init_(self, magma: object) -> str: ...
    def _symbolic_(self, SR: object) -> Expression: ...
    def __contains__(self, P: object) -> bool: ...
    def __call__(self, *args: object, **kwargs: object) -> EllipticCurvePoint_field: ...
    def _reduce_point(self, R: Ring, p: object) -> SchemeMorphism_point_projective_ring: ...
    def is_x_coord(self, x: object) -> bool: ...
    def lift_x(self, x: object, all: bool = ..., extend: bool = ...) -> EllipticCurvePoint_field | list[EllipticCurvePoint_field]: ...
    def _point_homset(self, *args: object, **kwargs: object) -> SchemeHomset_points_abelian_variety_field: ...
    def __getitem__(self, n: object) -> EllipticCurvePoint_field: ...
    def __is_over_RationalField(self) -> bool: ...
    def is_on_curve(self, x: object, y: object) -> bool: ...
    def is_exact(self) -> bool: ...
    def a_invariants(self) -> tuple[RingElement, RingElement, RingElement, RingElement, RingElement]: ...
    def a1(self) -> RingElement: ...
    def a2(self) -> RingElement: ...
    def a3(self) -> RingElement: ...
    def a4(self) -> RingElement: ...
    def a6(self) -> RingElement: ...
    def b_invariants(self) -> tuple[RingElement, RingElement, RingElement, RingElement]: ...
    def b2(self) -> RingElement: ...
    def b4(self) -> RingElement: ...
    def b6(self) -> RingElement: ...
    def b8(self) -> RingElement: ...
    def c_invariants(self) -> tuple[RingElement, RingElement]: ...
    def c4(self) -> RingElement: ...
    def c6(self) -> RingElement: ...
    def discriminant(self) -> RingElement: ...
    def j_invariant(self) -> RingElement: ...
    def base_extend(self, R: Ring | Map) -> Self: ...
    def change_ring(self, R: Ring | object) -> Self: ...
    def base_ring(self) -> Ring: ...
    def gens(self) -> tuple[EllipticCurvePoint_field, ...]: ...
    def gen(self, i: int) -> EllipticCurvePoint_field: ...
    def rst_transform(self, r: object, s: object, t: object) -> Self: ...
    def scale_curve(self, u: object) -> Self: ...
    def isomorphism(self, u: object, r: object = ..., s: object = ..., t: object = ...) -> WeierstrassIsomorphism: ...
    def division_polynomial_0(self, n: int, x: object = ...) -> Polynomial: ...
    def two_division_polynomial(self, x: object = ...) -> Polynomial: ...
    def division_polynomial(self, m: int, x: object = ..., two_torsion_multiplicity: int = ..., force_evaluate: bool = ...) -> Polynomial: ...
    def _multiple_x_numerator(self, n: int, x: object = ...) -> Polynomial: ...
    def _multiple_x_denominator(self, n: int, x: object = ...) -> Polynomial: ...
    def multiplication_by_m(self, m: int, x_only: bool = ...) -> tuple[Polynomial, ...] | SchemeMorphism_polynomial_projective_space: ...
    def scalar_multiplication(self, m: int) -> SchemeMorphism_polynomial_projective_space: ...
    def frobenius_isogeny(self, n: int = ...) -> EllipticCurveIsogeny: ...
    def identity_morphism(self) -> EllipticCurveIsogeny: ...
    def isomorphism_to(self, other: EllipticCurve_generic) -> WeierstrassIsomorphism: ...
    def automorphisms(self, field: Ring | None = ...) -> list[WeierstrassIsomorphism]: ...
    def isomorphisms(self, other: EllipticCurve_generic, field: Ring | None = ...) -> list[WeierstrassIsomorphism]: ...
    def is_isomorphic(self, other: EllipticCurve_generic, field: Ring | None = ...) -> bool: ...
    def change_weierstrass_model(self, *args: object, **kwargs: object) -> Self: ...
    def short_weierstrass_model(self, complete_cube: bool = ...) -> Self: ...
    def montgomery_model(self, twisted: bool = ..., morphism: bool = ...) -> Self | tuple[Self, WeierstrassIsomorphism]: ...
    def plot(self, xmin: object = ..., xmax: object = ..., components: str = ..., **kwargs: object) -> Graphics: ...
    def formal_group(self) -> EllipticCurveFormalGroup: ...
    def _p_primary_torsion_basis(self, p: int, m: int) -> tuple[EllipticCurvePoint_field, EllipticCurvePoint_field]: ...
    def hyperelliptic_polynomials(self) -> tuple[Polynomial, Polynomial]: ...
    def pari_curve(self) -> pari_gen: ...
    def __pari__(self) -> pari_gen: ...
    def is_smooth(self, point: RingElement | tuple[RingElement, ...] | None = None) -> bool: ...
