import builtins

class _SageObject: ...

class GaloisRepresentation:
    def __init__(self, E: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def elliptic_curve(self) -> _SageObject: ...
    def non_surjective(self, A: builtins.int = ...) -> _SageObject: ...
    def is_surjective(
        self, p: builtins.int, A: builtins.int = ...
    ) -> builtins.bool: ...
    def isogeny_bound(self, A: builtins.int = ...) -> _SageObject: ...
    def reducible_primes(self) -> _SageObject: ...

def Frobenius_filter(
    self, L: builtins.object, patience: builtins.int = ...
) -> _SageObject: ...
def deg_one_primes_iter(self, principal_only: builtins.bool = ...) -> _SageObject: ...
def Billerey_P_l(self, l: builtins.object) -> _SageObject: ...
def Billerey_B_l(self, l: builtins.object, B: builtins.int = ...) -> _SageObject: ...
def Billerey_R_q(self, q: builtins.int, B: builtins.int = ...) -> _SageObject: ...
def Billerey_B_bound(
    self,
    max_l: builtins.int = ...,
    num_l: builtins.int = ...,
    small_prime_bound: builtins.int = ...,
    debug: builtins.bool = ...,
) -> _SageObject: ...
def Billerey_R_bound(
    self,
    max_l: builtins.int = ...,
    num_l: builtins.int = ...,
    small_prime_bound: builtins.object = ...,
    debug: builtins.bool = ...,
) -> _SageObject: ...
def reducible_primes_Billerey(
    self,
    num_l: builtins.object = ...,
    max_l: builtins.object = ...,
    verbose: builtins.bool = ...,
) -> _SageObject: ...
def reducible_primes_naive(
    self,
    max_l: builtins.object = ...,
    num_P: builtins.object = ...,
    verbose: builtins.bool = ...,
) -> _SageObject: ...
