# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GaloisRepresentation:
    def __init__(self, E: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def elliptic_curve(self) -> _SageObject: ...
    def non_surjective(self, A: builtins.int = ...) -> _SageObject: ...
    def is_surjective(self, p: builtins.int, A: builtins.int = ...) -> builtins.bool: ...
    def isogeny_bound(self, A: builtins.int = ...) -> _SageObject: ...
    def reducible_primes(self) -> _SageObject: ...

def Frobenius_filter(E: builtins.object, L: builtins.object, patience: builtins.int = ...) -> _SageObject: ...

def deg_one_primes_iter(K: builtins.int, principal_only: builtins.bool = ...) -> _SageObject: ...

def Billerey_P_l(E: builtins.object, l: builtins.object) -> _SageObject: ...

def Billerey_B_l(E: builtins.object, l: builtins.object, B: builtins.int = ...) -> _SageObject: ...

def Billerey_R_q(E: builtins.object, q: builtins.int, B: builtins.int = ...) -> _SageObject: ...

def Billerey_B_bound(E: builtins.object, max_l: builtins.int = ..., num_l: builtins.int = ..., small_prime_bound: builtins.int = ..., debug: builtins.bool = ...) -> _SageObject: ...

def Billerey_R_bound(E: builtins.object, max_l: builtins.int = ..., num_l: builtins.int = ..., small_prime_bound: builtins.object = ..., debug: builtins.bool = ...) -> _SageObject: ...

def reducible_primes_Billerey(E: builtins.object, num_l: builtins.object = ..., max_l: builtins.object = ..., verbose: builtins.bool = ...) -> _SageObject: ...

def reducible_primes_naive(E: builtins.object, max_l: builtins.object = ..., num_P: builtins.object = ..., verbose: builtins.bool = ...) -> _SageObject: ...
