# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def heegner_points(N: builtins.int, D: builtins.object = ..., c: builtins.object = ...) -> _SageObject: ...

def heegner_point(N: builtins.int, D: builtins.object = ..., c: builtins.int = ...) -> _SageObject: ...

class RingClassField:
    def __init__(self, D: builtins.object, c: builtins.object, check: builtins.bool = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def conductor(self) -> _SageObject: ...
    def discriminant_of_K(self) -> _SageObject: ...
    def ramified_primes(self) -> builtins.list[_SageObject]: ...
    def degree_over_K(self) -> _SageObject: ...
    def degree_over_H(self) -> _SageObject: ...
    def absolute_degree(self) -> _SageObject: ...
    degree_over_Q: _SageObject
    def quadratic_field(self) -> _SageObject: ...
    def galois_group(self, base: builtins.object = ...) -> _SageObject: ...
    def is_subfield(self, M: builtins.int) -> builtins.bool: ...

class GaloisGroup:
    def __init__(self, field: builtins.object, base: builtins.object = ...) -> None: ...
    def __eq__(self, G: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def field(self) -> _SageObject: ...
    def base_field(self) -> _SageObject: ...
    def kolyvagin_generators(self) -> builtins.tuple[_SageObject, ...]: ...
    def lift_of_hilbert_class_field_galois_group(self) -> builtins.tuple[_SageObject, ...]: ...
    def is_kolyvagin(self) -> builtins.bool: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def cardinality(self) -> _SageObject: ...
    def complex_conjugation(self) -> _SageObject: ...

class GaloisAutomorphism:
    def __init__(self, parent: builtins.object) -> None: ...
    def parent(self) -> _SageObject: ...
    def domain(self) -> _SageObject: ...

class GaloisAutomorphismComplexConjugation:
    def __init__(self, parent: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, right: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __invert__(self) -> Self: ...
    def order(self) -> _SageObject: ...

class GaloisAutomorphismQuadraticForm:
    def __init__(self, parent: builtins.object, quadratic_form: builtins.object, alpha: builtins.object = ...) -> None: ...
    def order(self) -> _SageObject: ...
    def alpha(self) -> _SageObject: ...
    def p1_element(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.int) -> builtins.bool: ...
    def __mul__(self, right: builtins.object) -> Self: ...
    def quadratic_form(self) -> _SageObject: ...
    def ideal(self) -> _SageObject: ...

class HeegnerPoint:
    def __init__(self, N: builtins.int, D: builtins.object, c: builtins.object) -> None: ...
    def __richcmp__(self, other: builtins.object, op: builtins.int) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def level(self) -> _SageObject: ...
    def conductor(self) -> _SageObject: ...
    def discriminant(self) -> _SageObject: ...
    def quadratic_field(self) -> _SageObject: ...
    def quadratic_order(self) -> _SageObject: ...
    def ring_class_field(self) -> _SageObject: ...

class HeegnerPoints:
    def __init__(self, N: builtins.int) -> None: ...
    def level(self) -> _SageObject: ...

class HeegnerPoints_level:
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def reduce_mod(self, ell: builtins.object) -> _SageObject: ...
    def discriminants(self, n: builtins.int = ..., weak: builtins.bool = ...) -> builtins.list[_SageObject]: ...

class HeegnerPoints_level_disc:
    def __init__(self, N: builtins.int, D: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def discriminant(self) -> _SageObject: ...
    def quadratic_field(self) -> _SageObject: ...
    def kolyvagin_conductors(self, r: builtins.int = ..., n: builtins.int = ..., E: builtins.object = ..., m: builtins.int = ...) -> builtins.list[_SageObject]: ...

def is_kolyvagin_conductor(N: builtins.int, E: builtins.object, D: builtins.object, r: builtins.int, n: builtins.int, c: builtins.object) -> builtins.bool: ...

class HeegnerPoints_level_disc_cond:
    def __init__(self, N: builtins.int, D: builtins.object, c: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def conductor(self) -> _SageObject: ...
    def satisfies_kolyvagin_hypothesis(self) -> builtins.bool: ...
    def ring_class_field(self) -> _SageObject: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def betas(self) -> builtins.tuple[_SageObject, ...]: ...
    def points(self, beta: builtins.object = ...) -> builtins.tuple[_SageObject, ...]: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class HeegnerPointOnX0N:
    def __init__(self, N: builtins.int, D: builtins.object, c: builtins.object = ..., f: builtins.object = ..., check: builtins.bool = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.int) -> builtins.bool: ...
    def atkin_lehner_act(self, Q: builtins.int = ...) -> _SageObject: ...
    def quadratic_form(self) -> _SageObject: ...
    def reduced_quadratic_form(self) -> _SageObject: ...
    def tau(self) -> _SageObject: ...
    def map_to_curve(self, E: builtins.object) -> _SageObject: ...
    def galois_orbit_over_K(self) -> _SageObject: ...
    def plot(self, **kwds: builtins.object) -> _SageObject: ...

class HeegnerPointOnEllipticCurve:
    def __init__(self, E: builtins.object, x: builtins.object, check: builtins.bool = ...) -> None: ...
    def satisfies_kolyvagin_hypothesis(self, n: builtins.int = ...) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, right: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def heegner_point_on_X0N(self) -> _SageObject: ...
    def map_to_complex_numbers(self, prec: builtins.int = ...) -> _SageObject: ...
    def kolyvagin_point(self) -> _SageObject: ...
    def curve(self) -> _SageObject: ...
    def quadratic_form(self) -> _SageObject: ...
    def numerical_approx(self, prec: builtins.int = ..., algorithm: builtins.str = ...) -> _SageObject: ...
    def tau(self) -> _SageObject: ...
    def x_poly_exact(self, prec: builtins.int = ..., algorithm: builtins.str = ...) -> _SageObject: ...
    def point_exact(self, prec: builtins.int = ..., algorithm: builtins.str = ..., var: builtins.str = ..., optimize: builtins.bool = ...) -> _SageObject: ...
    def conjugates_over_K(self) -> _SageObject: ...
    def kolyvagin_cohomology_class(self, n: builtins.int = ...) -> _SageObject: ...

class KolyvaginPoint:
    def __init__(self, heegner_point: builtins.object) -> None: ...
    def satisfies_kolyvagin_hypothesis(self, n: builtins.int = ...) -> _SageObject: ...
    def curve(self) -> _SageObject: ...
    def heegner_point(self) -> _SageObject: ...
    def index(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def numerical_approx(self, prec: builtins.int = ...) -> _SageObject: ...
    def point_exact(self, prec: builtins.int = ...) -> _SageObject: ...
    def plot(self, prec: builtins.int = ..., *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def trace_to_real_numerical(self, prec: builtins.int = ...) -> _SageObject: ...
    def mod(self, p: builtins.int, prec: builtins.int = ...) -> _SageObject: ...
    def kolyvagin_cohomology_class(self, n: builtins.int = ...) -> _SageObject: ...

class KolyvaginCohomologyClass:
    def __init__(self, kolyvagin_point: builtins.object, n: builtins.int) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def n(self) -> _SageObject: ...
    def conductor(self) -> _SageObject: ...
    def kolyvagin_point(self) -> _SageObject: ...
    def heegner_point(self) -> _SageObject: ...

class KolyvaginCohomologyClassEn:
    ...

class HeegnerQuatAlg:
    def __init__(self, level: builtins.object, ell: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def level(self) -> _SageObject: ...
    def ell(self) -> _SageObject: ...
    def satisfies_heegner_hypothesis(self, D: builtins.object, c: builtins.object = ...) -> builtins.bool: ...
    def heegner_discriminants(self, n: builtins.int = ...) -> _SageObject: ...
    def heegner_conductors(self, D: builtins.object, n: builtins.int = ...) -> _SageObject: ...
    def optimal_embeddings(self, D: builtins.object, c: builtins.object, R: builtins.int) -> _SageObject: ...
    def brandt_module(self) -> _SageObject: ...
    def quaternion_algebra(self) -> _SageObject: ...
    def right_ideals(self) -> _SageObject: ...
    def left_orders(self) -> _SageObject: ...
    def heegner_divisor(self, D: builtins.object, c: builtins.object = ...) -> _SageObject: ...
    def modp_splitting_data(self, p: builtins.int) -> _SageObject: ...
    def modp_splitting_map(self, p: builtins.int) -> _SageObject: ...
    def cyclic_subideal_p1(self, I: builtins.int, c: builtins.object) -> _SageObject: ...
    def galois_group_over_hilbert_class_field(self, D: builtins.object, c: builtins.object) -> _SageObject: ...
    def galois_group_over_quadratic_field(self, D: builtins.object, c: builtins.object) -> _SageObject: ...
    def quadratic_field(self, D: builtins.object) -> _SageObject: ...
    def kolyvagin_cyclic_subideals(self, I: builtins.int, p: builtins.int, alpha_quaternion: builtins.object) -> _SageObject: ...
    def kolyvagin_generator(self, K: builtins.int, p: builtins.int) -> _SageObject: ...
    def kolyvagin_generators(self, K: builtins.int, c: builtins.object) -> _SageObject: ...
    def kolyvagin_sigma_operator(self, D: builtins.object, c: builtins.object, r: builtins.int, bound: builtins.object = ...) -> _SageObject: ...
    def modp_dual_elliptic_curve_factor(self, E: builtins.object, p: builtins.int, bound: builtins.int = ...) -> _SageObject: ...
    def rational_kolyvagin_divisor(self, D: builtins.object, c: builtins.object) -> _SageObject: ...
    def kolyvagin_point_on_curve(self, D: builtins.object, c: builtins.object, E: builtins.object, p: builtins.int, bound: builtins.int = ...) -> _SageObject: ...

def kolyvagin_reduction_data(E: builtins.object, q: builtins.int, first_only: builtins.bool = ...) -> _SageObject: ...

class HeegnerQuatAlgEmbedding:
    def __init__(self, D: builtins.object, c: builtins.object, R: builtins.int, beta: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def matrix(self) -> _SageObject: ...
    def domain(self) -> _SageObject: ...
    def domain_gen(self) -> _SageObject: ...
    def domain_conductor(self) -> _SageObject: ...
    def beta(self) -> _SageObject: ...
    def codomain(self) -> _SageObject: ...
    def conjugate(self) -> _SageObject: ...

def quadratic_order(D: builtins.object, c: builtins.object, names: builtins.str = ...) -> _SageObject: ...

def class_number(D: builtins.object) -> _SageObject: ...

def is_inert(D: builtins.object, p: builtins.int) -> builtins.bool: ...

def is_split(D: builtins.object, p: builtins.int) -> builtins.bool: ...

def is_ramified(D: builtins.object, p: builtins.int) -> builtins.bool: ...

def nearby_rational_poly(f: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def simplest_rational_poly(f: builtins.object, prec: builtins.int) -> _SageObject: ...

def satisfies_weak_heegner_hypothesis(N: builtins.int, D: builtins.object) -> _SageObject: ...

def make_monic(f: builtins.object) -> _SageObject: ...

def ell_heegner_point(self: builtins.object, D: builtins.object, c: builtins.object = ..., f: builtins.object = ..., check: builtins.bool = ...) -> _SageObject: ...

def kolyvagin_point(self: builtins.object, D: builtins.object, c: builtins.object = ..., check: builtins.bool = ...) -> _SageObject: ...

def ell_heegner_discriminants(self: builtins.object, bound: builtins.object) -> builtins.list[_SageObject]: ...

def ell_heegner_discriminants_list(self: builtins.object, n: builtins.int) -> builtins.list[_SageObject]: ...

def heegner_point_height(self: builtins.object, D: builtins.object, prec: builtins.int = ..., check_rank: builtins.bool = ...) -> _SageObject: ...

def heegner_index(self: builtins.object, D: builtins.object, min_p: builtins.int = ..., prec: builtins.int = ..., descent_second_limit: builtins.int = ..., verbose_mwrank: builtins.bool = ..., check_rank: builtins.bool = ...) -> _SageObject: ...

def heegner_index_bound(self: builtins.object, D: builtins.int = ..., prec: builtins.int = ..., max_height: builtins.object = ...) -> builtins.tuple[_SageObject, ...]: ...

def heegner_sha_an(self: builtins.object, D: builtins.object, prec: builtins.int = ...) -> _SageObject: ...

def satisfies_heegner_hypothesis(self: builtins.object, D: builtins.object) -> _SageObject: ...
