import builtins

from sage.interfaces.r import R
from sage.rings.generic import ProductTree

class _SageObject: ...

class FastEllipticPolynomial:
    hK: R
    hItree: ProductTree

    def __init__(
        self,
        E: builtins.object,
        n: builtins.int,
        P: builtins.int,
        Q: builtins.int = ...,
    ) -> None: ...
    def __call__(
        self, alpha: builtins.object, *, derivative: builtins.bool = ...
    ) -> _SageObject: ...

class EllipticCurveHom_velusqrt:
    def __init__(
        self,
        E: builtins.object,
        P: builtins.int,
        *,
        codomain: builtins.object = ...,
        model: builtins.object = ...,
        Q: builtins.int = ...,
    ) -> None: ...
    def kernel_polynomial(self) -> _SageObject: ...
    def as_EllipticCurveIsogeny(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def rational_maps(self) -> _SageObject: ...
    def x_rational_map(self) -> _SageObject: ...
    def scaling_factor(self) -> _SageObject: ...
    def inseparable_degree(self) -> _SageObject: ...
    def kernel_subgroup(self, *, extend: builtins.bool = ...) -> _SageObject: ...
