# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class EllipticCurveHom_composite:
    def __init__(self, E: builtins.object, kernel: builtins.object, codomain: builtins.object = ..., model: builtins.object = ..., velu_sqrt_bound: builtins.object = ...) -> None: ...
    @classmethod
    def from_factors(cls, maps: builtins.object, E: builtins.object = ..., strict: builtins.bool = ...) -> _SageObject: ...
    def factors(self) -> _SageObject: ...
    def rational_maps(self) -> _SageObject: ...
    def x_rational_map(self) -> _SageObject: ...
    def kernel_polynomial(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def formal(self, prec: builtins.int = ...) -> _SageObject: ...
    def scaling_factor(self) -> _SageObject: ...
    def inseparable_degree(self) -> _SageObject: ...
    def kernel_points(self) -> _SageObject: ...
    def inverse_image(self, Q: builtins.int, /, *, all: builtins.bool = ...) -> _SageObject: ...
    def push_subgroup(self, f: builtins.object) -> _SageObject: ...
