# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class EllipticCurveHom_sum:
    def __init__(self, phis: builtins.object, domain: builtins.object = ..., codomain: builtins.object = ...) -> None: ...
    def summands(self) -> _SageObject: ...
    def to_isogeny_chain(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def rational_maps(self) -> _SageObject: ...
    def x_rational_map(self) -> _SageObject: ...
    def kernel_polynomial(self) -> _SageObject: ...
    def scaling_factor(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def inseparable_degree(self) -> _SageObject: ...
