import builtins

class _SageObject: ...

def Fricke_polynomial(self) -> _SageObject: ...
def Fricke_module(self) -> _SageObject: ...
def Psi(self, use_stored: builtins.bool = ...) -> _SageObject: ...
def isogenies_prime_degree_genus_0(
    self, l: builtins.object = ..., minimal_models: builtins.bool = ...
) -> _SageObject: ...

sporadic_j: _SageObject

def isogenies_sporadic_Q(
    self, l: builtins.object = ..., minimal_models: builtins.bool = ...
) -> _SageObject: ...
def isogenies_2(self, minimal_models: builtins.bool = ...) -> _SageObject: ...
def isogenies_3(self, minimal_models: builtins.bool = ...) -> _SageObject: ...
def isogenies_5_0(self, minimal_models: builtins.bool = ...) -> _SageObject: ...
def isogenies_5_1728(self, minimal_models: builtins.bool = ...) -> _SageObject: ...
def isogenies_7_0(self, minimal_models: builtins.bool = ...) -> _SageObject: ...
def isogenies_7_1728(self, minimal_models: builtins.bool = ...) -> _SageObject: ...
def isogenies_13_0(self, minimal_models: builtins.bool = ...) -> _SageObject: ...
def isogenies_13_1728(self, minimal_models: builtins.bool = ...) -> _SageObject: ...

hyperelliptic_primes: _SageObject

def Psi2(self) -> _SageObject: ...
def isogenies_prime_degree_genus_plus_0(
    self, l: builtins.object = ..., minimal_models: builtins.bool = ...
) -> _SageObject: ...
def isogenies_prime_degree_genus_plus_0_j0(
    self, l: builtins.object, minimal_models: builtins.bool = ...
) -> _SageObject: ...
def isogenies_prime_degree_genus_plus_0_j1728(
    self, l: builtins.object, minimal_models: builtins.bool = ...
) -> _SageObject: ...
def is_kernel_polynomial(
    self, m: builtins.int, f: builtins.object
) -> builtins.bool: ...
def isogenies_prime_degree_general(
    self, l: builtins.object, minimal_models: builtins.bool = ...
) -> _SageObject: ...
def isogenies_prime_degree(
    self, l: builtins.object, minimal_models: builtins.bool = ...
) -> _SageObject: ...
