# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def Fricke_polynomial(l: builtins.object) -> _SageObject: ...

def Fricke_module(l: builtins.object) -> _SageObject: ...

def Psi(l: builtins.object, use_stored: builtins.bool = ...) -> _SageObject: ...

def isogenies_prime_degree_genus_0(E: builtins.object, l: builtins.object = ..., minimal_models: builtins.bool = ...) -> _SageObject: ...

sporadic_j: _SageObject
def isogenies_sporadic_Q(E: builtins.object, l: builtins.object = ..., minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_2(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_3(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_5_0(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_5_1728(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_7_0(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_7_1728(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_13_0(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_13_1728(E: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

hyperelliptic_primes: _SageObject
def Psi2(l: builtins.object) -> _SageObject: ...

def isogenies_prime_degree_genus_plus_0(E: builtins.object, l: builtins.object = ..., minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_prime_degree_genus_plus_0_j0(E: builtins.object, l: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_prime_degree_genus_plus_0_j1728(E: builtins.object, l: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def is_kernel_polynomial(E: builtins.object, m: builtins.int, f: builtins.object) -> builtins.bool: ...

def isogenies_prime_degree_general(E: builtins.object, l: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...

def isogenies_prime_degree(E: builtins.object, l: builtins.object, minimal_models: builtins.bool = ...) -> _SageObject: ...
