# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def c4c6_nonsingular(c4: builtins.object, c6: builtins.object) -> _SageObject: ...

def c4c6_model(c4: builtins.object, c6: builtins.object, assume_nonsingular: builtins.bool = ...) -> _SageObject: ...

def make_integral(a: builtins.object, P: builtins.int, e: builtins.object) -> _SageObject: ...

def sqrt_mod_4(x: builtins.object, P: builtins.int) -> _SageObject: ...

def check_b2_local(c4: builtins.object, c6: builtins.object, P: builtins.int, b2: builtins.object, debug: builtins.bool = ...) -> _SageObject: ...

def check_b2_global(c4: builtins.object, c6: builtins.object, b2: builtins.object, debug: builtins.bool = ...) -> _SageObject: ...

def check_Kraus_local_3(c4: builtins.object, c6: builtins.object, P: builtins.int, assume_nonsingular: builtins.bool = ..., debug: builtins.bool = ...) -> _SageObject: ...

def check_a1a3_local(c4: builtins.object, c6: builtins.object, P: builtins.int, a1: builtins.object, a3: builtins.object, debug: builtins.bool = ...) -> _SageObject: ...

def check_a1a3_global(c4: builtins.object, c6: builtins.object, a1: builtins.object, a3: builtins.object, debug: builtins.bool = ...) -> _SageObject: ...

def check_rst_global(c4: builtins.object, c6: builtins.object, r: builtins.int, s: builtins.object, t: builtins.object, debug: builtins.bool = ...) -> _SageObject: ...

def check_Kraus_local_2(c4: builtins.object, c6: builtins.object, P: builtins.int, a1: builtins.object = ..., assume_nonsingular: builtins.bool = ...) -> _SageObject: ...

def check_Kraus_local(c4: builtins.object, c6: builtins.object, P: builtins.int, assume_nonsingular: builtins.bool = ...) -> _SageObject: ...

def check_Kraus_global(c4: builtins.object, c6: builtins.object, assume_nonsingular: builtins.bool = ..., debug: builtins.bool = ...) -> _SageObject: ...

def semi_global_minimal_model(E: builtins.object, debug: builtins.bool = ...) -> _SageObject: ...
