from sage.schemes.elliptic_curves.ell_rational_field import EllipticCurve_rational_field
from sage.structure.sage_object import SageObject

class Lseries_ell(SageObject):
    def __init__(self, E: EllipticCurve_rational_field) -> None: ...
    def elliptic_curve(self) -> EllipticCurve_rational_field: ...
    def _repr_(self) -> str: ...
