# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

sqrt: _SageObject
def padic_lseries(self: builtins.object, p: builtins.int, normalize: builtins.bool = ..., implementation: builtins.str = ..., precision: builtins.int = ...) -> _SageObject: ...

def padic_regulator(self: builtins.object, p: builtins.int, prec: builtins.int = ..., height: builtins.object = ..., check_hypotheses: builtins.bool = ...) -> _SageObject: ...

def padic_height_pairing_matrix(self: builtins.object, p: builtins.int, prec: builtins.int = ..., height: builtins.object = ..., check_hypotheses: builtins.bool = ...) -> _SageObject: ...

def padic_height(self: builtins.object, p: builtins.int, prec: builtins.int = ..., sigma: builtins.object = ..., check_hypotheses: builtins.bool = ...) -> _SageObject: ...

def padic_height_via_multiply(self: builtins.object, p: builtins.int, prec: builtins.int = ..., E2: builtins.object = ..., check_hypotheses: builtins.bool = ...) -> _SageObject: ...

def padic_sigma(self: builtins.object, p: builtins.int, N: builtins.int = ..., E2: builtins.object = ..., check: builtins.bool = ..., check_hypotheses: builtins.bool = ...) -> _SageObject: ...

def padic_sigma_truncated(self: builtins.object, p: builtins.int, N: builtins.int = ..., lamb: builtins.int = ..., E2: builtins.object = ..., check_hypotheses: builtins.bool = ...) -> _SageObject: ...

def padic_E2(self: builtins.object, p: builtins.int, prec: builtins.int = ..., check: builtins.bool = ..., check_hypotheses: builtins.bool = ..., algorithm: builtins.str = ...) -> _SageObject: ...

def matrix_of_frobenius(self: builtins.object, p: builtins.int, prec: builtins.int = ..., check: builtins.bool = ..., check_hypotheses: builtins.bool = ..., algorithm: builtins.str = ...) -> _SageObject: ...
