import builtins
from typing import Self

class _SageObject: ...

class PeriodicRegion:
    def __init__(
        self,
        w1: builtins.object,
        w2: builtins.object,
        data: builtins.object,
        full: builtins.object = ...,
    ) -> None: ...
    def is_empty(self) -> builtins.bool: ...
    def ds(self) -> _SageObject: ...
    def verify(self, condition: builtins.object) -> _SageObject: ...
    def refine(
        self, condition: builtins.object = ..., times: builtins.object = ...
    ) -> _SageObject: ...
    def expand(self, corners: builtins.object = ...) -> _SageObject: ...
    def contract(self, corners: builtins.object = ...) -> _SageObject: ...
    def __contains__(self, z: object) -> bool: ...
    def __truediv__(self, n: builtins.object) -> Self: ...
    def __invert__(self) -> Self: ...
    def __and__(left: builtins.object, right: builtins.object) -> Self: ...
    def __xor__(left: builtins.object, right: builtins.object) -> Self: ...
    def __richcmp__(
        left: builtins.object, right: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def border(self, raw: builtins.object = ...) -> _SageObject: ...
    def innermost_point(self) -> _SageObject: ...
    def plot(self, **kwds: builtins.object) -> _SageObject: ...

def frame_data(data: builtins.object, full: builtins.object = ...) -> _SageObject: ...
def unframe_data(
    framed: builtins.object, full: builtins.object = ...
) -> _SageObject: ...
