# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def is_Q_curve(E: builtins.object, maxp: builtins.int = ..., certificate: builtins.bool = ..., verbose: builtins.bool = ...) -> builtins.bool: ...

def Step4Test(E: builtins.object, B: builtins.object, oldB: builtins.int = ..., verbose: builtins.bool = ...) -> _SageObject: ...

def conjugacy_test(jlist: builtins.object, verbose: builtins.bool = ...) -> _SageObject: ...
