import builtins

class _SageObject: ...

def is_Q_curve(
    self,
    maxp: builtins.int = ...,
    certificate: builtins.bool = ...,
    verbose: builtins.bool = ...,
) -> builtins.bool: ...
def Step4Test(
    self, B: builtins.object, oldB: builtins.int = ..., verbose: builtins.bool = ...
) -> _SageObject: ...
def conjugacy_test(self, verbose: builtins.bool = ...) -> _SageObject: ...
