import builtins

class _SageObject: ...

def reduce_mod_q(self, amodq: builtins.object) -> _SageObject: ...

class EllipticCurveSaturator:
    def __init__(self, E: builtins.object, verbose: builtins.bool = ...) -> None: ...
    def add_reductions(self, q: builtins.int) -> _SageObject: ...
    def full_p_saturation(
        self, Plist: builtins.object, p: builtins.int
    ) -> _SageObject: ...
    def p_saturation(
        self, Plist: builtins.object, p: builtins.int, sieve: builtins.bool = ...
    ) -> _SageObject: ...

def p_projections(
    self, Plist: builtins.object, p: builtins.int, debug: builtins.bool = ...
) -> _SageObject: ...
