# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def agcl_cmp(a: builtins.object, b: builtins.object) -> _SageObject: ...

def all_children_are_equivalent_trivial(PS: builtins.object, S: builtins.object) -> _SageObject: ...

def refine_and_return_invariant_trivial(PS: builtins.object, S: builtins.object, cells_to_refine_by: builtins.object, ctrb_len: builtins.object) -> _SageObject: ...

def compare_structures_trivial(gamma_1: builtins.object, gamma_2: builtins.object, S1: builtins.object, S2: builtins.object, degree: builtins.object) -> _SageObject: ...

def test_intersect_parabolic_with_alternating(n: builtins.object = ..., partition: builtins.object = ...) -> _SageObject: ...

def compare_perms(gamma_1: builtins.object, gamma_2: builtins.object, S1: builtins.object, S2: builtins.object, degree: builtins.object) -> _SageObject: ...

def coset_rep(perm: builtins.object = ..., gens: builtins.object = ...) -> _SageObject: ...

def allocate_agcl_output(n: builtins.object) -> _SageObject: ...

def deallocate_agcl_output(output: builtins.object) -> _SageObject: ...

def allocate_agcl_work_space(n: builtins.object) -> _SageObject: ...

def deallocate_agcl_work_space(work_space: builtins.object) -> _SageObject: ...
