# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def canonical_generator_next(can_gen_data: builtins.object, degree: builtins.object, mem_err: builtins.object) -> _SageObject: ...

def allocate_cgd(max_depth: builtins.object, degree: builtins.object) -> _SageObject: ...

def deallocate_cgd(cgd: builtins.object) -> _SageObject: ...

def start_canonical_generator(group: builtins.object, obj: builtins.object, degree: builtins.object, canonical_generator: builtins.object) -> _SageObject: ...
