# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def set_stab_py(generators: builtins.object, sett: builtins.object, relab: builtins.object = ...) -> _SageObject: ...

def set_stab(supergroup: builtins.object, sett: builtins.object, relab: builtins.object) -> _SageObject: ...

def sets_isom_py(generators: builtins.object, set1: builtins.object, set2: builtins.object) -> _SageObject: ...

def sets_isom(supergroup: builtins.object, set1: builtins.object, set2: builtins.object, isom: builtins.object) -> _SageObject: ...

def all_set_children_are_equivalent(PS: builtins.object, S: builtins.object) -> _SageObject: ...

def refine_set(PS: builtins.object, S: builtins.object, cells_to_refine_by: builtins.object, ctrb_len: builtins.object) -> _SageObject: ...

def compare_sets(gamma_1: builtins.object, gamma_2: builtins.object, S1: builtins.object, S2: builtins.object, degree: builtins.object) -> _SageObject: ...

def allocate_subset(n: builtins.object) -> _SageObject: ...

def free_subset(child: builtins.object) -> _SageObject: ...

def allocate_sgd(degree: builtins.object) -> _SageObject: ...

def deallocate_sgd(data: builtins.object) -> _SageObject: ...

def subset_generator_next(data: builtins.object, degree: builtins.object, mem_err: builtins.object) -> _SageObject: ...

def generate_child_subsets(S: builtins.object, group: builtins.object, child_iterator: builtins.object) -> _SageObject: ...

def apply_subset_aug(parent: builtins.object, aug: builtins.object, child: builtins.object, degree: builtins.object, mem_err: builtins.object) -> _SageObject: ...

def free_subset_aug(aug: builtins.object) -> _SageObject: ...

def canonical_set_parent(child: builtins.object, parent: builtins.object, permutation: builtins.object, degree: builtins.object, mem_err: builtins.object) -> _SageObject: ...

def allocate_subset_gen(degree: builtins.object, max_size: builtins.object) -> _SageObject: ...

def allocate_subset_gen_2(degree: builtins.object, max_size: builtins.object, it: builtins.object) -> _SageObject: ...

def free_subset_gen(subset_gen: builtins.object) -> _SageObject: ...

def setup_set_gen(subset_gen: builtins.object, degree: builtins.object, max_size: builtins.object) -> _SageObject: ...
