# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MatrixStruct:
    def __cinit__(self, matrix: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def display(self) -> _SageObject: ...
    def run(self, partition: builtins.object = ...) -> _SageObject: ...
    def automorphism_group(self) -> _SageObject: ...
    def canonical_relabeling(self) -> _SageObject: ...
    def is_isomorphic(self, other: builtins.object) -> builtins.bool: ...

def refine_matrix(PS: builtins.object, S: builtins.object, cells_to_refine_by: builtins.object, ctrb_len: builtins.object) -> _SageObject: ...

def compare_matrices(gamma_1: builtins.object, gamma_2: builtins.object, S1: builtins.object, S2: builtins.object, degree: builtins.object) -> _SageObject: ...

def all_matrix_children_are_equivalent(PS: builtins.object, S: builtins.object) -> _SageObject: ...

def random_tests(n: builtins.object = ..., nrows_max: builtins.object = ..., ncols_max: builtins.object = ..., nsymbols_max: builtins.object = ..., perms_per_matrix: builtins.object = ..., density_range: builtins.object = ...) -> _SageObject: ...
