import builtins

class _SageObject: ...

class JupyterNotebookCmd:
    @staticmethod
    def extend_parser(parser: builtins.object) -> _SageObject: ...
    def __init__(self, options: builtins.object) -> None: ...
    def run(self) -> int: ...
