[mypy]
strict = True
exclude = ^sage-src/build/

# Skip duplicate module conflicts inherent to Sage's structure
[[mypy-sage.libs.giac.*]]
ignore_errors = True
[[mypy-sage.interfaces.giac.*]]
ignore_errors = True
[[mypy-sage.libs.lcalc.*]]
ignore_errors = True
[[mypy-sage.lfunctions.lcalc.*]]
ignore_errors = True
[[mypy-sage.libs.mwrank.*]]
ignore_errors = True
[[mypy-sage.interfaces.mwrank.*]]
ignore_errors = True
[[mypy-sage.libs.pari.*]]
ignore_errors = True
[[mypy-sage.lfunctions.pari.*]]
ignore_errors = True
[[mypy-sage.libs.singular.*]]
ignore_errors = True
[[mypy-sage.interfaces.singular.*]]
ignore_errors = True
[[mypy-sage.manifolds.chart.*]]
ignore_errors = True
[[mypy-sage.manifolds.differentiable.chart.*]]
ignore_errors = True
[[mypy-sage.manifolds.family.*]]
ignore_errors = True
[[mypy-sage.combinat.family.*]]
ignore_errors = True
