import builtins

class _SageObject: ...

class AffineFactorizationCrystal:
    n: builtins.int

    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        w: builtins.object,
        n: builtins.int,
        x: builtins.object = ...,
        k: builtins.int = ...,
    ) -> _SageObject: ...
    def __init__(
        self, w: builtins.object, n: builtins.int, x: builtins.object = ...
    ) -> None: ...

    class Element:
        def e(self, i: builtins.int) -> _SageObject: ...
        def f(self, i: builtins.int) -> _SageObject: ...
        def bracketing(self, i: builtins.int) -> _SageObject: ...
        def to_tableau(self) -> _SageObject: ...

def affine_factorizations(
    self, l: builtins.object, weight: builtins.object = ...
) -> _SageObject: ...

class FactorizationToTableaux:
    def is_isomorphism(self) -> bool: ...
    is_embedding: _SageObject
    is_surjective: _SageObject
