from collections.abc import Iterable, Iterator, Sequence
from typing import Self

from sage.combinat.crystals.direct_sum import CrystalIndex
from sage.combinat.root_system.cartan_type import CartanType_abstract
from sage.combinat.root_system.weyl_group import WeylGroupElement
from sage.graphs.digraph import DiGraph
from sage.plot.graphics import Graphics
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.structure.element import Element
from sage.structure.element_wrapper import ElementWrapper
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

type CartanTypeInput = CartanType_abstract | Sequence[object] | str
type WeightCoordinates = Sequence[int | Integer]
type RootElement = Element
type WeightElement = Element
type RootHeightPair = tuple[RootElement, int | Integer]
type FoldedAlcoveData = tuple[RootsWithHeightElement, ...]
type InfinityAlcoveData = tuple[RootHeightPair, ...]

class CrystalOfAlcovePaths(
    UniqueRepresentation,
    Parent[CrystalOfAlcovePathsElement],
):
    Element: type[CrystalOfAlcovePathsElement]
    element_class: type[CrystalOfAlcovePathsElement]
    weight: WeightElement
    R: object
    module_generators: tuple[CrystalOfAlcovePathsElement, ...]

    @staticmethod
    def __classcall_private__(
        cls: type[CrystalOfAlcovePaths],
        starting_weight: WeightElement | CartanTypeInput,
        cartan_type: WeightCoordinates | bool | None = ...,
        highest_weight_crystal: bool | None = ...,
    ) -> CrystalOfAlcovePaths: ...
    def __init__(
        self,
        starting_weight: WeightElement,
        highest_weight_crystal: bool,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(
        self,
        data: FoldedAlcoveData
        | Sequence[int | Integer]
        | CrystalOfAlcovePathsElement,
    ) -> CrystalOfAlcovePathsElement: ...
    def vertices(self) -> list[list[int]]: ...
    def cartan_type(self) -> CartanType_abstract: ...
    def index_set(self) -> tuple[CrystalIndex, ...]: ...
    def weight_lattice_realization(self) -> Parent: ...
    def highest_weight_vector(self) -> CrystalOfAlcovePathsElement: ...

class CrystalOfAlcovePathsElement(ElementWrapper):
    value: FoldedAlcoveData

    def parent(self) -> CrystalOfAlcovePaths: ...
    def __iter__(self) -> Iterator[RootsWithHeightElement]: ...
    def is_admissible(self) -> bool: ...
    def _latex_(self) -> list[tuple[object, int | Integer]]: ...
    def integer_sequence(self) -> list[int]: ...
    def phi(self, i: CrystalIndex) -> Rational: ...
    def epsilon(self, i: CrystalIndex) -> int: ...
    def weight(self) -> WeightElement: ...
    def plot(self) -> Graphics: ...
    def _richcmp_(
        self,
        other: CrystalOfAlcovePathsElement,
        op: int,
    ) -> bool: ...
    def __hash__(self) -> int: ...
    def _folding_data(
        self,
        i: CrystalIndex,
    ) -> dict[RootElement | str, int]: ...
    def e(self, i: CrystalIndex) -> Self | None: ...
    def _gi(
        self,
        i: CrystalIndex,
    ) -> tuple[list[RootElement | str], list[int | Integer]]: ...
    def f(self, i: CrystalIndex) -> Self | None: ...
    @staticmethod
    def _sign(root: RootElement) -> int: ...
    def _eps(self, root: RootsWithHeightElement) -> int: ...
    def path(self) -> list[WeylGroupElement]: ...

class InfinityCrystalOfAlcovePaths(
    UniqueRepresentation,
    Parent[InfinityCrystalOfAlcovePaths.Element],
):
    module_generators: tuple[InfinityCrystalOfAlcovePaths.Element, ...]

    class Element(ElementWrapper):
        value: InfinityAlcoveData
        _shift: int | Integer

        def __init__(
            self,
            parent: InfinityCrystalOfAlcovePaths,
            elt: InfinityAlcoveData,
            shift: int | Integer,
        ) -> None: ...
        def parent(self) -> InfinityCrystalOfAlcovePaths: ...
        def e(self, i: CrystalIndex) -> Self | None: ...
        def f(self, i: CrystalIndex) -> Self: ...
        def epsilon(self, i: CrystalIndex) -> int: ...
        def phi(self, i: CrystalIndex) -> int | Integer: ...
        def weight(self) -> WeightElement: ...
        def projection(
            self,
            k: int | Integer | None = ...,
        ) -> CrystalOfAlcovePathsElement | None: ...

    Element: type[Element]
    element_class: type[Element]

    @staticmethod
    def __classcall_private__(
        cls: type[InfinityCrystalOfAlcovePaths],
        cartan_type: CartanTypeInput,
    ) -> InfinityCrystalOfAlcovePaths: ...
    def __init__(self, cartan_type: CartanType_abstract) -> None: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(
        self,
        elt: InfinityAlcoveData,
        shift: int | Integer = ...,
    ) -> Element: ...
    def highest_weight_vector(self) -> Element: ...
    def cartan_type(self) -> CartanType_abstract: ...
    def index_set(self) -> tuple[CrystalIndex, ...]: ...
    def weight_lattice_realization(self) -> Parent: ...
    def cardinality(self) -> PlusInfinity: ...

class RootsWithHeight(
    UniqueRepresentation,
    Parent[RootsWithHeightElement],
):
    Element: type[RootsWithHeightElement]
    element_class: type[RootsWithHeightElement]
    weight: WeightElement

    @staticmethod
    def __classcall_private__(
        cls: type[RootsWithHeight],
        starting_weight: WeightElement | CartanTypeInput,
        cartan_type: WeightCoordinates | None = ...,
    ) -> RootsWithHeight: ...
    def __init__(self, weight: WeightElement) -> None: ...
    def _repr_(self) -> str: ...
    def _max_height(self, root: RootElement) -> int | Integer: ...
    def word(self) -> list[CrystalIndex]: ...
    def lambda_chain(self) -> list[RootsWithHeightElement]: ...
    def _element_constructor_(
        self,
        root: RootElement | Iterable[int | Integer],
        height: int | Integer,
    ) -> RootsWithHeightElement: ...
    def _an_element_(self) -> RootsWithHeightElement: ...

class RootsWithHeightElement(Element):
    root: RootElement
    height: int | Integer

    def __init__(
        self,
        parent: RootsWithHeight,
        root: RootElement,
        height: int | Integer,
    ) -> None: ...
    def parent(self) -> RootsWithHeight: ...
    def _repr_(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def _richcmp_(
        self,
        other: RootsWithHeightElement,
        op: int,
    ) -> bool: ...

def compare_graphs(
    g1: DiGraph,
    g2: DiGraph,
    node1: object,
    node2: object,
) -> bool: ...
