import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.combinat.root_system.root_system import RootSystem

class _SageObject: ...

class CrystalOfAlcovePaths:
    R: RootSystem

    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        starting_weight: builtins.object,
        cartan_type: builtins.object = ...,
        highest_weight_crystal: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self, starting_weight: builtins.object, highest_weight_crystal: builtins.object
    ) -> None: ...
    def vertices(self) -> _SageObject: ...

class CrystalOfAlcovePathsElement:
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def is_admissible(self) -> bool: ...
    def integer_sequence(self) -> _SageObject: ...
    def phi(self, i: builtins.int) -> _SageObject: ...
    def epsilon(self, i: builtins.int) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def plot(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def e(self, i: builtins.int) -> _SageObject: ...
    def f(self, i: builtins.int) -> _SageObject: ...
    def path(self) -> _SageObject: ...

class InfinityCrystalOfAlcovePaths:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, cartan_type: builtins.object
    ) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...

    class Element:
        def __init__(
            self, parent: builtins.object, elt: builtins.object, shift: builtins.object
        ) -> None: ...
        def e(self, i: builtins.int) -> _SageObject: ...
        def f(self, i: builtins.int) -> _SageObject: ...
        def epsilon(self, i: builtins.int) -> _SageObject: ...
        def phi(self, i: builtins.int) -> _SageObject: ...
        def weight(self) -> _SageObject: ...
        def projection(self, k: builtins.int = ...) -> _SageObject: ...

class RootsWithHeight:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        starting_weight: builtins.object,
        cartan_type: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(self, weight: builtins.object) -> None: ...
    def word(self) -> _SageObject: ...
    def lambda_chain(self) -> _SageObject: ...

class RootsWithHeightElement:
    def __init__(
        self, parent: builtins.object, root: builtins.object, height: builtins.object
    ) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: object) -> bool: ...

def compare_graphs(
    self, g2: builtins.object, node1: builtins.object, node2: builtins.object
) -> _SageObject: ...
