# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DirectSumOfCrystals:
    @staticmethod
    def __classcall_private__(cls: builtins.object, crystals: builtins.object, facade: builtins.bool = ..., keepkey: builtins.bool = ..., category: builtins.object = ...) -> _SageObject: ...
    def __init__(self, crystals: builtins.object, facade: builtins.object, keepkey: builtins.object, category: builtins.object, **options: builtins.object) -> None: ...
    def weight_lattice_realization(self) -> _SageObject: ...
    class Element:
        def e(self, i: builtins.int) -> _SageObject: ...
        def f(self, i: builtins.int) -> _SageObject: ...
        def weight(self) -> _SageObject: ...
        def phi(self, i: builtins.int) -> _SageObject: ...
        def epsilon(self, i: builtins.int) -> _SageObject: ...
