# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class InfinityCrystalOfTableaux:
    @staticmethod
    def __classcall_private__(cls: builtins.object, cartan_type: builtins.object) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def module_generator(self) -> _SageObject: ...
    class Element:
        def phi(self, i: builtins.int) -> _SageObject: ...
        def weight(self) -> _SageObject: ...
        def reduced_form(self) -> _SageObject: ...
        def seg(self) -> _SageObject: ...
        def content(self) -> _SageObject: ...

class InfinityCrystalOfTableauxTypeD:
    @staticmethod
    def __classcall_private__(cls: builtins.object, cartan_type: builtins.object) -> _SageObject: ...
    def module_generator(self) -> _SageObject: ...
    class Element:
        ...

class DualInfinityQueerCrystalOfTableaux:
    @staticmethod
    def __classcall_private__(cls: builtins.object, cartan_type: builtins.object) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def module_generator(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    class Element:
        ...
