# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def KirillovReshetikhinCrystalFromLSPaths(cartan_type: builtins.object, r: builtins.int, s: builtins.int = ...) -> _SageObject: ...

def KirillovReshetikhinCrystal(cartan_type: builtins.object, r: builtins.int, s: builtins.object, model: builtins.str = ...) -> _SageObject: ...

def KashiwaraNakashimaTableaux(cartan_type: builtins.object, r: builtins.int, s: builtins.object) -> _SageObject: ...

class KirillovReshetikhinGenericCrystal:
    def __init__(self, cartan_type: builtins.object, r: builtins.int, s: builtins.object, dual: builtins.object = ...) -> None: ...
    def module_generator(self) -> _SageObject: ...
    def r(self) -> _SageObject: ...
    def s(self) -> _SageObject: ...
    def classically_highest_weight_vectors(self) -> _SageObject: ...
    def kirillov_reshetikhin_tableaux(self) -> _SageObject: ...

class KirillovReshetikhinGenericCrystalElement:
    def pp(self) -> _SageObject: ...
    def to_kirillov_reshetikhin_tableau(self) -> _SageObject: ...
    def to_tableau(self) -> _SageObject: ...
    def lusztig_involution(self) -> _SageObject: ...

class KirillovReshetikhinCrystalFromPromotion:
    def __init__(self, cartan_type: builtins.object, r: builtins.int, s: builtins.object) -> None: ...

class KirillovReshetikhinCrystalFromPromotionElement:
    ...

class KR_type_A:
    def classical_decomposition(self) -> _SageObject: ...
    def promotion(self) -> _SageObject: ...
    def promotion_inverse(self) -> _SageObject: ...
    def dynkin_diagram_automorphism(self, i: builtins.int) -> _SageObject: ...

class KR_type_vertical:
    def classical_decomposition(self) -> _SageObject: ...
    def promotion(self) -> _SageObject: ...
    def promotion_inverse(self) -> _SageObject: ...
    def dynkin_diagram_automorphism(self, i: builtins.int) -> _SageObject: ...
    def promotion_on_highest_weight_vector(self, b: builtins.object) -> _SageObject: ...
    def from_highest_weight_vector_to_pm_diagram(self, b: builtins.object) -> _SageObject: ...
    def from_pm_diagram_to_highest_weight_vector(self, pm: builtins.object) -> _SageObject: ...

class KR_type_E6:
    def classical_decomposition(self) -> _SageObject: ...
    def dynkin_diagram_automorphism(self, i: builtins.int) -> _SageObject: ...
    def affine_weight(self, b: builtins.object) -> _SageObject: ...
    def hw_auxiliary(self) -> _SageObject: ...
    def highest_weight_dict(self) -> _SageObject: ...
    def highest_weight_dict_inv(self) -> _SageObject: ...
    def automorphism_on_affine_weight(self, weight: builtins.object) -> _SageObject: ...
    def promotion_on_highest_weight_vectors(self) -> _SageObject: ...
    def promotion_on_highest_weight_vectors_function(self) -> _SageObject: ...
    def promotion(self) -> _SageObject: ...
    def promotion_inverse(self) -> _SageObject: ...

class KR_type_C:
    def classical_decomposition(self) -> _SageObject: ...
    def ambient_crystal(self) -> _SageObject: ...
    def ambient_dict_pm_diagrams(self) -> _SageObject: ...
    def ambient_highest_weight_dict(self) -> _SageObject: ...
    def highest_weight_dict(self) -> _SageObject: ...
    def to_ambient_crystal(self) -> _SageObject: ...
    def from_ambient_crystal(self) -> _SageObject: ...

class KR_type_CElement:
    def e0(self) -> _SageObject: ...
    def f0(self) -> _SageObject: ...
    def epsilon0(self) -> _SageObject: ...
    def phi0(self) -> _SageObject: ...

class KR_type_A2:
    def module_generator(self) -> _SageObject: ...
    def classical_decomposition(self) -> _SageObject: ...
    def ambient_crystal(self) -> _SageObject: ...
    def ambient_dict_pm_diagrams(self) -> _SageObject: ...
    def ambient_highest_weight_dict(self) -> _SageObject: ...
    def highest_weight_dict(self) -> _SageObject: ...
    def to_ambient_crystal(self) -> _SageObject: ...
    def from_ambient_crystal(self) -> _SageObject: ...

class KR_type_A2Element:
    def e0(self) -> _SageObject: ...
    def f0(self) -> _SageObject: ...
    def epsilon0(self) -> _SageObject: ...
    def phi0(self) -> _SageObject: ...

class KR_type_box:
    def __init__(self, cartan_type: builtins.object, r: builtins.int, s: builtins.object) -> None: ...
    def classical_decomposition(self) -> _SageObject: ...
    def ambient_crystal(self) -> _SageObject: ...
    def highest_weight_dict(self) -> _SageObject: ...
    def ambient_highest_weight_dict(self) -> _SageObject: ...
    def similarity_factor(self) -> _SageObject: ...
    def to_ambient_crystal(self) -> _SageObject: ...
    def from_ambient_crystal(self) -> _SageObject: ...

class KR_type_boxElement:
    def e0(self) -> _SageObject: ...
    def f0(self) -> _SageObject: ...
    def epsilon0(self) -> _SageObject: ...
    def phi0(self) -> _SageObject: ...

class KR_type_Bn:
    def classical_decomposition(self) -> _SageObject: ...
    def ambient_crystal(self) -> _SageObject: ...
    def highest_weight_dict(self) -> _SageObject: ...
    def ambient_highest_weight_dict(self) -> _SageObject: ...
    def similarity_factor(self) -> _SageObject: ...
    def to_ambient_crystal(self) -> _SageObject: ...
    def from_ambient_crystal(self) -> _SageObject: ...

class KR_type_BnElement:
    def e0(self) -> _SageObject: ...
    def f0(self) -> _SageObject: ...
    def epsilon0(self) -> _SageObject: ...
    def phi0(self) -> _SageObject: ...

class KR_type_Cn:
    def classical_decomposition(self) -> _SageObject: ...
    def from_highest_weight_vector_to_pm_diagram(self, b: builtins.object) -> _SageObject: ...
    def from_pm_diagram_to_highest_weight_vector(self, pm: builtins.object) -> _SageObject: ...

class KR_type_CnElement:
    def e0(self) -> _SageObject: ...
    def f0(self) -> _SageObject: ...
    def epsilon0(self) -> _SageObject: ...
    def phi0(self) -> _SageObject: ...

class KR_type_Dn_twisted:
    def classical_decomposition(self) -> _SageObject: ...
    def from_highest_weight_vector_to_pm_diagram(self, b: builtins.object) -> _SageObject: ...
    def from_pm_diagram_to_highest_weight_vector(self, pm: builtins.object) -> _SageObject: ...

class KR_type_Dn_twistedElement:
    def e0(self) -> _SageObject: ...
    def f0(self) -> _SageObject: ...
    def epsilon0(self) -> _SageObject: ...
    def phi0(self) -> _SageObject: ...

class KR_type_spin:
    def classical_decomposition(self) -> _SageObject: ...
    def dynkin_diagram_automorphism(self, i: builtins.int) -> _SageObject: ...
    def promotion_on_highest_weight_vectors(self) -> _SageObject: ...
    def promotion_on_highest_weight_vectors_inverse(self) -> _SageObject: ...
    def promotion(self) -> _SageObject: ...
    def promotion_inverse(self) -> _SageObject: ...

class KR_type_D_tri1:
    def __init__(self, ct: builtins.object, s: builtins.object) -> None: ...
    def classical_decomposition(self) -> _SageObject: ...
    def from_coordinates(self, coords: builtins.object) -> _SageObject: ...
    class Element:
        def coordinates(self) -> _SageObject: ...
        def e0(self) -> _SageObject: ...
        def f0(self) -> _SageObject: ...
        def epsilon0(self) -> _SageObject: ...
        def phi0(self) -> _SageObject: ...

class CrystalOfTableaux_E7:
    def module_generator(self, shape: builtins.object) -> _SageObject: ...

class KR_type_E7:
    def __init__(self, ct: builtins.object, r: builtins.int, s: builtins.object) -> None: ...
    def classical_decomposition(self) -> _SageObject: ...
    def A7_decomposition(self) -> _SageObject: ...
    def to_A7_crystal(self) -> _SageObject: ...
    def from_A7_crystal(self) -> _SageObject: ...
    class Element:
        def e0(self) -> _SageObject: ...
        def f0(self) -> _SageObject: ...

class PMDiagram:
    def __init__(self, pm_diagram: builtins.object, from_shapes: builtins.object = ...) -> None: ...
    def pp(self) -> _SageObject: ...
    def inner_shape(self) -> _SageObject: ...
    def outer_shape(self) -> _SageObject: ...
    def intermediate_shape(self) -> _SageObject: ...
    def heights_of_minus(self) -> builtins.list[_SageObject]: ...
    def heights_of_addable_plus(self) -> builtins.list[_SageObject]: ...
    def sigma(self) -> _SageObject: ...

def partitions_in_box(r: builtins.int, s: builtins.object) -> _SageObject: ...

def vertical_dominoes_removed(r: builtins.int, s: builtins.object) -> _SageObject: ...

def horizontal_dominoes_removed(r: builtins.int, s: builtins.object) -> _SageObject: ...

class AmbientRetractMap:
    def __init__(self, base: builtins.object, ambient: builtins.object, pdict_inv: builtins.object, index_set: builtins.object, similarity_factor_domain: builtins.object = ..., automorphism: builtins.object = ...) -> None: ...

class CrystalDiagramAutomorphism:
    def __init__(self, C: builtins.object, on_hw: builtins.object, index_set: builtins.object = ..., automorphism: builtins.object = ..., cache: builtins.bool = ...) -> None: ...
    def is_isomorphism(self) -> builtins.bool: ...
    is_surjective: _SageObject
    is_embedding: _SageObject
    is_strict: _SageObject
