# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KyotoPathModel:
    @staticmethod
    def __classcall_private__(cls: builtins.object, crystals: builtins.object, weight: builtins.object, P: builtins.int = ...) -> _SageObject: ...
    def __init__(self, crystals: builtins.object, weight: builtins.object, P: builtins.int) -> None: ...
    def finite_tensor_product(self, k: builtins.int) -> _SageObject: ...
    def weight_lattice_realization(self) -> _SageObject: ...
    class Element:
        def epsilon(self, i: builtins.int) -> _SageObject: ...
        def phi(self, i: builtins.int) -> _SageObject: ...
        def e(self, i: builtins.int) -> _SageObject: ...
        def f(self, i: builtins.int) -> _SageObject: ...
        def weight(self) -> _SageObject: ...
        def truncate(self, k: builtins.int = ...) -> _SageObject: ...
