import builtins

from sage.combinat.root_system.root_system import RootSystem

class _SageObject: ...

class CrystalOfLSPaths:
    R: RootSystem

    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        starting_weight: builtins.object,
        cartan_type: builtins.object = ...,
        starting_weight_parent: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self, starting_weight: builtins.object, starting_weight_parent: builtins.object
    ) -> None: ...
    def weight_lattice_realization(self) -> _SageObject: ...

    class Element:
        def endpoint(self) -> _SageObject: ...
        def compress(self) -> _SageObject: ...
        def split_step(
            self, which_step: builtins.object, r: builtins.int
        ) -> _SageObject: ...
        def reflect_step(
            self, which_step: builtins.object, i: builtins.int
        ) -> _SageObject: ...
        def epsilon(self, i: builtins.int) -> _SageObject: ...
        def phi(self, i: builtins.int) -> _SageObject: ...
        def e(
            self,
            i: builtins.int,
            power: builtins.int = ...,
            to_string_end: builtins.bool = ...,
            length_only: builtins.bool = ...,
        ) -> _SageObject: ...
        def dualize(self) -> _SageObject: ...
        def f(
            self,
            i: builtins.int,
            power: builtins.int = ...,
            to_string_end: builtins.bool = ...,
            length_only: builtins.bool = ...,
        ) -> _SageObject: ...
        def s(self, i: builtins.int) -> _SageObject: ...
        def weight(self) -> _SageObject: ...

class CrystalOfProjectedLevelZeroLSPaths:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, weight: builtins.object
    ) -> _SageObject: ...
    def maximal_vector(self) -> _SageObject: ...
    def classically_highest_weight_vectors(self) -> _SageObject: ...
    def one_dimensional_configuration_sum(
        self, q: builtins.int = ..., group_components: builtins.bool = ...
    ) -> _SageObject: ...
    def is_perfect(self, level: builtins.int = ...) -> bool: ...

    class Element:
        def scalar_factors(self) -> _SageObject: ...
        def weyl_group_representation(self) -> _SageObject: ...
        def energy_function(self) -> _SageObject: ...

class InfinityCrystalOfLSPaths:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, cartan_type: builtins.object
    ) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def module_generator(self) -> _SageObject: ...
    def weight_lattice_realization(self) -> _SageObject: ...

    class Element:
        def e(
            self,
            i: builtins.int,
            power: builtins.int = ...,
            length_only: builtins.bool = ...,
        ) -> _SageObject: ...
        def f(
            self,
            i: builtins.int,
            power: builtins.int = ...,
            length_only: builtins.bool = ...,
        ) -> _SageObject: ...
        def weight(self) -> _SageObject: ...
        def phi(self, i: builtins.int) -> _SageObject: ...

def positively_parallel_weights(self, w: builtins.object) -> _SageObject: ...
