# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PBWDatum:
    def __init__(self, parent: builtins.object, long_word: builtins.object, lusztig_datum: builtins.object) -> None: ...
    def __eq__(self, other_PBWDatum: builtins.object) -> builtins.bool: ...
    def is_equivalent_to(self, other_pbw_datum: builtins.object) -> builtins.bool: ...
    def convert_to_long_word_with_first_letter(self, i: builtins.object) -> _SageObject: ...
    def convert_to_new_long_word(self, new_long_word: builtins.object) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def star(self) -> _SageObject: ...

class PBWData:
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def convert_to_new_long_word(self, pbw_datum: builtins.object, new_long_word: builtins.object) -> _SageObject: ...

def compute_new_lusztig_datum(enhanced_braid_chain: builtins.object, initial_lusztig_datum: builtins.object) -> _SageObject: ...

def tropical_plucker_relation(a: builtins.object, lusztig_datum: builtins.object) -> _SageObject: ...

def enhance_braid_move_chain(braid_move_chain: builtins.object, cartan_type: builtins.object) -> _SageObject: ...
