import builtins

class _SageObject: ...

class PBWCrystalElement:
    def __init__(
        self,
        parent: builtins.object,
        lusztig_datum: builtins.object,
        long_word: builtins.object = ...,
    ) -> None: ...
    def lusztig_datum(self, word: builtins.object = ...) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def e(self, i: builtins.int) -> _SageObject: ...
    def f(self, i: builtins.int) -> _SageObject: ...
    def epsilon(self, i: builtins.int) -> _SageObject: ...
    def phi(self, i: builtins.int) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def star(self) -> _SageObject: ...

class PBWCrystal:
    @staticmethod
    def __classcall__(
        cls: builtins.object, cartan_type: builtins.object
    ) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def default_long_word(self) -> _SageObject: ...
    def set_default_long_word(self, word: builtins.object) -> _SageObject: ...
    Element: _SageObject
