from collections.abc import Iterator

from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.structure.element import Element

import sage.combinat.partition
import sage.combinat.crystals.letters
from sage.combinat.root_system.cartan_type import CartanType_abstract
class CrystalOfWords(UniqueRepresentation, Parent):
    def _element_constructor_(self, *crystalElements: Element) -> CrystalOfWordsElement: ...
    class Element: ...

class CrystalOfWordsElement(Element):
    def __getitem__(self, index: int) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...

class TensorProductOfCrystals(CrystalOfWords):
    module_generators: tuple[TensorProductOfCrystalsElement, ...] | TensorProductOfCrystals
    @staticmethod
    def __classcall_private__(cls: type[TensorProductOfCrystals], *crystals: Parent, **options: object) -> TensorProductOfCrystals: ...
    def cartan_type(self) -> CartanType_abstract: ...
    def highest_weight_vectors(self) -> list[TensorProductOfCrystalsElement]: ...
    def index_set(self) -> tuple[int, ...] | list[int]: ...

class TensorProductOfCrystalsElement(Element):
    def f(self, i: int) -> TensorProductOfCrystalsElement | None: ...
    def e(self, i: int) -> TensorProductOfCrystalsElement | None: ...
    def epsilon(self, i: int) -> int: ...
    def phi(self, i: int) -> int: ...
    def weight(self) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __getitem__(self, index: int) -> Element: ...
    def __len__(self) -> int: ...

class TensorProductOfCrystalsWithGenerators(TensorProductOfCrystals):
    ...

class FullTensorProductOfCrystals(TensorProductOfCrystals):
    def list(self) -> list[TensorProductOfCrystalsElement]: ...
    def cardinality(self) -> int: ...

class FullTensorProductOfRegularCrystals(FullTensorProductOfCrystals):
    ...

class TensorProductOfRegularCrystalsWithGenerators(TensorProductOfCrystalsWithGenerators):
    ...

class FullTensorProductOfSuperCrystals(FullTensorProductOfCrystals):
    ...

class QueerSuperCrystalsMixin:
    ...

class FullTensorProductOfQueerSuperCrystals(FullTensorProductOfCrystals, QueerSuperCrystalsMixin):
    ...

class CrystalOfTableaux(CrystalOfWords):
    @staticmethod
    def __classcall_private__(cls: type[CrystalOfTableaux], cartan_type: object, shape: object = ..., **kwds: object) -> CrystalOfTableaux: ...
    def cartan_type(self) -> CartanType_abstract: ...
    def highest_weight_vectors(self) -> list[CrystalOfTableauxElement]: ...
    def shape(self) -> sage.combinat.partition.Partition: ...
    def index_set(self) -> tuple[int, ...] | list[int]: ...

class CrystalOfTableauxElement(Element):
    def f(self, i: int) -> CrystalOfTableauxElement | None: ...
    def e(self, i: int) -> CrystalOfTableauxElement | None: ...
    def epsilon(self, i: int) -> int: ...
    def phi(self, i: int) -> int: ...
    def weight(self) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...

class CrystalOfQueerTableaux(CrystalOfWords, QueerSuperCrystalsMixin):
    ...
