from collections.abc import Iterator

from sage.modules.free_module_element import FreeModuleElement
from sage.rings.finite_rings.element_base import Cache_base, FinitePolyExtElement
from sage.rings.finite_rings.finite_field_givaro import FiniteField_givaro
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element, RingElement

class FiniteField_givaroElement(FinitePolyExtElement):
    def __init__(self, parent: FiniteField_givaro) -> None: ...
    def _repr_(self) -> str: ...
    def _element(self) -> Element: ...
    def __bool__(self) -> bool: ...
    def is_one(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def is_square(self) -> bool: ...
    def sqrt(self, extend: bool = False, all: bool = False) -> FiniteField_givaroElement | list[FinitePolyExtElement] | None: ...
    def _add_(self, right: FiniteField_givaroElement) -> FiniteField_givaroElement: ...
    def _mul_(self, right: FiniteField_givaroElement) -> FiniteField_givaroElement: ...
    def _div_(self, right: FiniteField_givaroElement) -> FiniteField_givaroElement: ...
    def _sub_(self, right: FiniteField_givaroElement) -> FiniteField_givaroElement: ...
    def __neg__(self) -> FiniteField_givaroElement: ...
    def __invert__(self) -> FiniteField_givaroElement: ...
    def __pow__(self, exp: int, other: object) -> FiniteField_givaroElement: ...
    def _richcmp_(self, right: object, op: int) -> bool: ...
    def __int__(self) -> int: ...
    def _integer_representation(self) -> int: ...
    def _integer_(self, ZZ: object = None) -> Integer: ...
    def _log_to_int(self) -> int: ...
    def log(self, base: object, order: object = None, *, check: bool = False) -> Integer: ...
    def _int_repr(self) -> int: ...
    def _log_repr(self) -> int: ...
    def _poly_repr(self) -> str: ...
    def polynomial(self, name: str | None = None) -> Polynomial: ...
    def _magma_init_(self, magma: object) -> str: ...
    def multiplicative_order(self) -> int: ...
    def __copy__(self) -> FiniteField_givaroElement: ...
    def __deepcopy__(self, memo: object) -> FiniteField_givaroElement: ...
    def _gap_init_(self) -> str: ...
    def __hash__(self) -> int: ...
    def _vector_(self, reverse: bool = False) -> FreeModuleElement[RingElement]: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...

class Cache_givaro(Cache_base):
    def __init__(self, parent: object, p: int, k: int, modulus: object, repr: str = 'poly', cache: bool = False) -> None: ...
    def characteristic(self) -> int: ...
    def order(self) -> int: ...
    def order_c(self) -> int: ...
    def exponent(self) -> int: ...
    def random_element(self, *args: object, **kwds: object) -> FiniteField_givaroElement: ...
    def element_from_data(self, e: FiniteField_givaroElement | int | str | None) -> FiniteField_givaroElement: ...
    def gen(self) -> FiniteField_givaroElement: ...
    def log_to_int(self, n: int) -> int: ...
    def int_to_log(self, n: int) -> int: ...
    def fetch_int(self, number: int) -> FiniteField_givaroElement: ...
    def _element_repr(self, e: FiniteField_givaroElement) -> str: ...
    def _element_log_repr(self, e: FiniteField_givaroElement) -> str: ...
    def _element_int_repr(self, e: FiniteField_givaroElement) -> str: ...
    def _element_poly_repr(self, e: FiniteField_givaroElement, varname: str | None = None) -> str: ...
    def a_times_b_plus_c(self, a: FiniteField_givaroElement, b: FiniteField_givaroElement, c: FiniteField_givaroElement) -> FiniteField_givaroElement: ...
    def a_times_b_minus_c(self, a: FiniteField_givaroElement, b: FiniteField_givaroElement, c: FiniteField_givaroElement) -> FiniteField_givaroElement: ...
    def c_minus_a_times_b(self, a: FiniteField_givaroElement, b: FiniteField_givaroElement, c: FiniteField_givaroElement) -> FiniteField_givaroElement: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...

class FiniteField_givaro_iterator(Iterator[FiniteField_givaroElement]):
    def __init__(self, cache: Cache_givaro) -> None: ...
    def __next__(self) -> FiniteField_givaroElement: ...
    def __iter__(self) -> FiniteField_givaro_iterator: ...
