# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FiniteFieldElement_pari_ffelt:
    def __init__(self, parent: builtins.object, x: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def construct(self, g: builtins.object) -> _SageObject: ...
    def construct_from(self, x: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: builtins.object) -> Self: ...
    def is_zero(self) -> builtins.bool: ...
    def is_one(self) -> builtins.bool: ...
    def is_unit(self) -> builtins.bool: ...
    def __pos__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __pow__(self, exp: builtins.object, other: builtins.object) -> Self: ...
    def pth_power(self, k: builtins.object = ...) -> _SageObject: ...
    def polynomial(self, name: builtins.object = ...) -> _SageObject: ...
    def minpoly(self, var: builtins.object = ...) -> _SageObject: ...
    def charpoly(self, var: builtins.object = ...) -> _SageObject: ...
    def is_square(self) -> builtins.bool: ...
    def sqrt(self, extend: builtins.object = ..., all: builtins.object = ...) -> _SageObject: ...
    def log(self, base: builtins.object, order: builtins.object = ..., check: builtins.object = ...) -> _SageObject: ...
    def multiplicative_order(self) -> _SageObject: ...
    def lift(self) -> _SageObject: ...
    def __int__(self) -> builtins.int: ...
    def __float__(self) -> builtins.float: ...
    def __pari__(self, var: builtins.object = ...) -> _SageObject: ...

def unpickle_FiniteFieldElement_pari_ffelt(parent: builtins.object, elem: builtins.object) -> _SageObject: ...
