from collections.abc import Iterator

from sage.categories.map import Map
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.commutative_ring_element import CommutativeRingElement
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ring import Field
from sage.structure.element import Element, RingElement
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject

class gen: ...

type _ElementList = list[Element]
type _PolyExtList = list[FinitePolyExtElement]

class FiniteRingElement(CommutativeRingElement):
    def _nth_root_common(
        self, n: int, all: bool, algorithm: str | None, cunningham: bool
    ) -> FiniteRingElement | _ElementList | None: ...
    def to_bytes(self, byteorder: str = "big") -> bytes: ...
    def canonical_associate(self) -> FiniteRingElement: ...
    def minpoly_over(self, F: Field, var: str = "x") -> Polynomial: ...

class FinitePolyExtElement(FiniteRingElement):
    def _im_gens_(
        self,
        codomain: Parent,
        im_gens: tuple[Element, ...],
        base_map: Map | None = None,
    ) -> Element: ...
    def minpoly(self, var: str = "x", algorithm: str = "pari") -> Polynomial: ...
    def minimal_polynomial(self, var: str = "x") -> Polynomial: ...
    def __getitem__(self, n: int) -> Element: ...
    def list(self) -> _ElementList: ...
    def __iter__(self) -> Iterator[Element]: ...
    def _vector_(self, reverse: bool = False) -> FreeModuleElement[RingElement]: ...
    def matrix(self, reverse: bool = False) -> Matrix: ...
    def _latex_(self) -> str: ...
    def __pari__(self, var: str | None = None) -> gen: ...
    def _pari_init_(self, var: str | None = None) -> str: ...
    def charpoly(self, var: str = "x", algorithm: str = "pari") -> Polynomial: ...
    def norm(self) -> Element: ...
    def trace(self) -> Element: ...
    def multiplicative_order(self) -> int: ...
    def additive_order(self) -> Integer: ...
    def is_square(self) -> bool: ...
    def square_root(
        self, extend: bool = False, all: bool = False
    ) -> FinitePolyExtElement | _PolyExtList | None: ...
    def sqrt(
        self, extend: bool = False, all: bool = False
    ) -> FinitePolyExtElement | _PolyExtList | None: ...
    def nth_root(
        self,
        n: int,
        extend: bool = False,
        all: bool = False,
        algorithm: str | None = None,
        cunningham: bool = False,
    ) -> FinitePolyExtElement | _PolyExtList | None: ...
    def pth_power(self, k: int = 1) -> FinitePolyExtElement: ...
    def pth_root(self, k: int = 1) -> FinitePolyExtElement: ...
    def conjugate(self) -> FinitePolyExtElement: ...
    def to_integer(self, reverse: bool = False) -> Integer: ...
    def to_bytes(self, byteorder: str = "big") -> bytes: ...

class Cache_base(SageObject):
    def fetch_int(self, number: int) -> FinitePolyExtElement: ...
