from collections.abc import Callable
from typing import Self

from sage.interfaces.expect import Expect
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.finite_rings.element_base import Cache_base, FinitePolyExtElement
from sage.rings.finite_rings.finite_field_ntl_gf2e import FiniteField_ntl_gf2e
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.integer import Integer
from sage.rings.integer_ring import IntegerRing_class
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element


class gen: ...


class Cache_ntl_gf2e(Cache_base[IntegerMod_abstract]):
    def __init__(
        self,
        parent: FiniteField_ntl_gf2e,
        k: int | Integer,
        modulus: Polynomial,
    ) -> None: ...
    def _doctest_for_5340(self) -> None: ...
    def order(self) -> Integer: ...
    def degree(self) -> Integer: ...
    def import_data(self, e: FiniteField_ntl_gf2eElement) -> None: ...
    def fetch_int(self, number: int | Integer) -> FiniteField_ntl_gf2eElement: ...
    def polynomial(self) -> Polynomial: ...


class FiniteField_ntl_gf2eElement(
    FinitePolyExtElement[IntegerMod_abstract],
):
    def __init__(
        self,
        parent: FiniteField_ntl_gf2e | None = ...,
    ) -> None: ...
    def __bool__(self) -> bool: ...
    def is_one(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def is_square(self) -> bool: ...
    def sqrt(
        self,
        extend: bool = ...,
        all: bool = ...,
    ) -> Self | list[Self] | None: ...
    def _add_(self, right: FiniteField_ntl_gf2eElement) -> Self: ...
    def _mul_(self, right: FiniteField_ntl_gf2eElement) -> Self: ...
    def _div_(self, other: FiniteField_ntl_gf2eElement) -> Self: ...
    def _sub_(self, right: FiniteField_ntl_gf2eElement) -> Self: ...
    def __neg__(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def _richcmp_(
        self,
        right: FiniteField_ntl_gf2eElement,
        op: int,
    ) -> bool: ...
    def _integer_(
        self,
        ZZ: IntegerRing_class | None = ...,
    ) -> Integer: ...
    def __int__(self) -> int: ...
    def _integer_representation(self) -> int: ...
    def polynomial(self, name: str | None = ...) -> Polynomial: ...
    def charpoly(
        self,
        var: str = ...,
        algorithm: str = ...,
    ) -> Polynomial: ...
    def minpoly(
        self,
        var: str = ...,
        algorithm: str = ...,
    ) -> Polynomial: ...
    def norm(self) -> IntegerMod_abstract: ...
    def trace(self) -> IntegerMod_abstract: ...
    def weight(self) -> int: ...
    def _magma_init_(self, magma: Expect) -> str: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[int, Element]) -> Self: ...
    def _gap_init_(self) -> str: ...
    def __hash__(self) -> int: ...
    def _vector_(
        self,
        reverse: bool = ...,
    ) -> FreeModuleElement[IntegerMod_abstract]: ...
    def __reduce__(
        self,
    ) -> tuple[
        Callable[..., FiniteField_ntl_gf2eElement],
        tuple[FiniteField_ntl_gf2e, str],
    ]: ...
    def log(
        self,
        base: Element,
        order: Integer | None = ...,
        *,
        check: bool = ...,
    ) -> Integer: ...


def unpickleFiniteField_ntl_gf2eElement(
    parent: FiniteField_ntl_gf2e,
    elem: str,
) -> FiniteField_ntl_gf2eElement: ...
