import builtins

class _SageObject: ...

def late_import(self) -> _SageObject: ...

class FiniteField_ntl_gf2e:
    def __init__(
        self,
        q: builtins.int,
        names: builtins.str = ...,
        modulus: builtins.object = ...,
        repr: builtins.str = ...,
    ) -> None: ...
    def characteristic(self) -> _SageObject: ...
    def order(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def prime_subfield(self) -> _SageObject: ...
    def from_integer(self, number: builtins.object) -> _SageObject: ...
