from sage.rings.finite_rings.element_ntl_gf2e import FiniteField_ntl_gf2eElement
from sage.rings.finite_rings.finite_field_base import FiniteField
from sage.rings.finite_rings.finite_field_prime_modn import FiniteField_prime_modn
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial

class gen: ...

class FiniteField_ntl_gf2e(FiniteField):
    def __init__(self, q: int | Integer, names: str = 'a', modulus: Polynomial | None = None, repr: str = 'poly') -> None: ...
    def characteristic(self) -> Integer: ...
    def order(self) -> Integer: ...
    def degree(self) -> Integer: ...
    def _element_constructor_(self, e: FiniteField_ntl_gf2eElement | int | Integer | str | Polynomial | None) -> FiniteField_ntl_gf2eElement: ...
    def gen(self, n: int = 0) -> FiniteField_ntl_gf2eElement: ...
    def prime_subfield(self) -> FiniteField_prime_modn: ...
    def from_integer(self, number: int, reverse: bool = False) -> FiniteField_ntl_gf2eElement: ...
    def _pari_modulus(self) -> Polynomial: ...

def late_import() -> None: ...
