# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FiniteField_pari_ffelt:
    def __init__(self, p: builtins.int, modulus: builtins.object, name: builtins.str = ...) -> None: ...
    Element: _SageObject
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
