# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FiniteFieldHomset:
    def __call__(self, im_gens: builtins.object, base_map: builtins.object = ..., check: builtins.bool = ...) -> _SageObject: ...
    def is_aut(self) -> builtins.bool: ...
    def order(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def list(self) -> _SageObject: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def index(self, item: builtins.object) -> _SageObject: ...
