from collections.abc import Callable
from typing import Self

from sage.categories.map import Map
from sage.interfaces.expect import Expect
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.finite_rings.element_base import FiniteRingElement
from sage.rings.finite_rings.integer_mod_ring import IntegerModRing_generic
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.integer_ring import IntegerRing_class
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.structure.element import Element
from sage.structure.parent import Parent


class gen: ...
class SageInputBuilder: ...


class NativeIntStruct:
    def __init__(self, m: int | Integer) -> None: ...
    def __reduce__(self) -> tuple[type[NativeIntStruct], tuple[int]]: ...
    def precompute_table(self, parent: IntegerModRing_generic) -> None: ...


class IntegerMod_abstract(FiniteRingElement):
    def __init__(
        self,
        parent: IntegerModRing_generic,
        value: Element | int | Integer | None = ...,
    ) -> None: ...
    def parent(self) -> IntegerModRing_generic: ...
    def __abs__(self) -> Self: ...
    def __reduce__(self) -> tuple[Callable[..., Self], tuple[IntegerModRing_generic, Integer]]: ...
    def _im_gens_(
        self,
        codomain: Parent,
        im_gens: tuple[Element, ...],
        base_map: Map | None = ...,
    ) -> Element: ...
    def __mod__(self, modulus: Element | int | Integer) -> Self: ...
    def is_nilpotent(self) -> bool: ...
    def _pari_init_(self) -> str: ...
    def __pari__(self) -> gen: ...
    def _gap_init_(self) -> str: ...
    def _magma_init_(self, magma: Expect) -> str: ...
    def _fricas_init_(self) -> str: ...
    def _sage_input_(
        self,
        sib: SageInputBuilder,
        coerced: bool,
    ) -> Element: ...
    def log(
        self,
        b: IntegerMod_abstract | None = ...,
        order: Integer | None = ...,
        check: bool = ...,
    ) -> Integer: ...
    def generalised_log(self) -> list[tuple[Integer, Integer]]: ...
    def modulus(self) -> Integer: ...
    def charpoly(self, var: str = ...) -> Polynomial: ...
    def minpoly(self, var: str = ...) -> Polynomial: ...
    def minimal_polynomial(self, var: str = ...) -> Polynomial: ...
    def polynomial(self, var: str = ...) -> Polynomial: ...
    def norm(self) -> Self: ...
    def trace(self) -> Self: ...
    def lift(self) -> Integer: ...
    def lift_centered(self) -> Integer: ...
    def is_one(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def divides(self, other: IntegerMod_abstract) -> bool: ...
    def is_square(self) -> bool: ...
    def sqrt(
        self,
        extend: bool = ...,
        all: bool = ...,
    ) -> Self | list[Self] | None: ...
    def nth_root(
        self,
        n: int | Integer,
        extend: bool = ...,
        all: bool = ...,
        algorithm: str | None = ...,
        cunningham: bool = ...,
    ) -> Self | list[Self] | None: ...
    def _nth_root_naive(self, n: int | Integer) -> Self: ...
    def _balanced_abs(self) -> Integer: ...
    def rational_reconstruction(self) -> Rational: ...
    def crt(self, other: IntegerMod_abstract) -> Self: ...
    def additive_order(self) -> Integer: ...
    def is_primitive_root(self) -> bool: ...
    def multiplicative_order(self) -> Integer: ...
    def valuation(self, p: int | Integer) -> int | PlusInfinity: ...
    def _floordiv_(self, right: IntegerMod_abstract) -> Self: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _integer_(
        self,
        ZZ: IntegerRing_class | None = ...,
    ) -> Integer: ...
    def _rational_(self) -> Rational: ...
    def _vector_(self) -> FreeModuleElement[Self]: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __float__(self) -> float: ...
    def __hash__(self) -> int: ...


class IntegerMod_gmp(IntegerMod_abstract):
    def __lshift__(self, k: int | Integer) -> Self: ...
    def __rshift__(self, k: int | Integer) -> Self: ...
    def _richcmp_(self, right: IntegerMod_gmp, op: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def _crt(self, other: IntegerMod_gmp) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[int, Element]) -> Self: ...
    def _add_(self, right: IntegerMod_gmp) -> Self: ...
    def _sub_(self, right: IntegerMod_gmp) -> Self: ...
    def _neg_(self) -> Self: ...
    def _mul_(self, right: IntegerMod_gmp) -> Self: ...
    def _div_(self, right: IntegerMod_gmp) -> Self: ...
    def __pow__(
        self,
        exp: int | Integer,
        modulus: Element | None = ...,
    ) -> Self: ...
    def __invert__(self) -> Self: ...
    def gcd(self, other: IntegerMod_gmp) -> Self: ...


class IntegerMod_int(IntegerMod_abstract):
    def _richcmp_(self, right: IntegerMod_int, op: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def _crt(self, other: IntegerMod_int) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[int, Element]) -> Self: ...
    def _add_(self, right: IntegerMod_int) -> Self: ...
    def _sub_(self, right: IntegerMod_int) -> Self: ...
    def _neg_(self) -> Self: ...
    def _mul_(self, right: IntegerMod_int) -> Self: ...
    def _div_(self, right: IntegerMod_int) -> Self: ...
    def __pow__(
        self,
        exp: int | Integer,
        modulus: Element | None = ...,
    ) -> Self: ...
    def __invert__(self) -> Self: ...
    def gcd(self, other: IntegerMod_int) -> Self: ...


class IntegerMod_int64(IntegerMod_abstract):
    def _richcmp_(self, right: IntegerMod_int64, op: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[int, Element]) -> Self: ...
    def _add_(self, right: IntegerMod_int64) -> Self: ...
    def _sub_(self, right: IntegerMod_int64) -> Self: ...
    def _neg_(self) -> Self: ...
    def _mul_(self, right: IntegerMod_int64) -> Self: ...
    def _div_(self, right: IntegerMod_int64) -> Self: ...
    def __pow__(
        self,
        exp: int | Integer,
        modulus: Element | None = ...,
    ) -> Self: ...
    def __invert__(self) -> Self: ...


def Mod(
    x: Element | int | Integer,
    m: int | Integer,
) -> IntegerMod_abstract: ...
