from collections.abc import Iterator
from typing import Literal, overload

import sage.rings.abc
from sage.categories.category import Category
from sage.categories.map import Map
from sage.categories.rings import Rings
from sage.groups.abelian_gps.values import AbelianGroupWithValues_class
from sage.interfaces.expect import Expect
from sage.rings.finite_rings.element_base import FiniteRingElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.quotient_ring import QuotientRing_generic
from sage.structure.element import Element
from sage.structure.factorization import Factorization
from sage.structure.factory import (
    FactoryArgument,
    FactoryCacheKey,
    FactoryExtraArgs,
    FactoryVersion,
    UniqueFactory,
)
from sage.structure.parent import Parent

class IntegerModFactory(UniqueFactory):
    def get_object(self, version: FactoryVersion, key: FactoryCacheKey, extra_args: FactoryExtraArgs) -> IntegerModRing_generic: ...
    def create_key_and_extra_args(self, *args: FactoryArgument, **kwds: FactoryArgument) -> tuple[FactoryCacheKey, FactoryExtraArgs]: ...
    def create_object(self, version: FactoryVersion, key: FactoryCacheKey, **kwds: FactoryArgument) -> IntegerModRing_generic: ...

def _unit_gens_primepowercase(p: int | Integer, r: int | Integer) -> list[tuple[IntegerMod_abstract, Integer]]: ...
def crt(v: list[IntegerMod_abstract]) -> IntegerMod_abstract: ...

class IntegerModRing_generic(QuotientRing_generic, sage.rings.abc.IntegerModRing, Rings.ParentMethods[IntegerMod_abstract]):
    def __init__(self, order: int | Integer, cache: bool | None = ..., category: Category | None = ...) -> None: ...
    def _macaulay2_init_(self, macaulay2: Expect | None = ...) -> str: ...
    def _fricas_init_(self) -> str: ...
    def krull_dimension(self) -> int: ...
    def is_prime_field(self) -> bool: ...
    def _precompute_table(self) -> None: ...
    def list_of_elements_of_multiplicative_group(self) -> list[IntegerMod_abstract]: ...
    def multiplicative_subgroups(self) -> tuple[tuple[IntegerMod_abstract, ...], ...]: ...
    def is_integral_domain(self, proof: bool | None = ...) -> bool: ...
    def is_unique_factorization_domain(self, proof: bool | None = ...) -> bool: ...
    def is_field(self, proof: bool | None = ...) -> bool: ...
    def field(self) -> sage.rings.abc.Ring: ...
    def _pseudo_fraction_field(self) -> sage.rings.abc.Ring: ...
    def multiplicative_group_is_cyclic(self) -> bool: ...
    def multiplicative_generator(self) -> FiniteRingElement: ...
    def quadratic_nonresidue(self) -> IntegerMod_abstract: ...
    def square_roots_of_one(self) -> tuple[IntegerMod_abstract, ...]: ...
    def factored_order(self) -> Factorization: ...
    def factored_unit_order(self) -> Factorization: ...
    def characteristic(self) -> Integer: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def modulus(self) -> Integer | Polynomial: ...
    def order(self) -> Integer: ...
    def zero(self) -> IntegerMod_abstract: ...
    def one(self) -> IntegerMod_abstract: ...
    def cardinality(self) -> Integer: ...
    def _pari_order(self) -> Integer: ...
    def _element_constructor_(self, x: IntegerMod_abstract | int | Integer | None) -> IntegerMod_abstract: ...
    def __iter__(self) -> Iterator[IntegerMod_abstract]: ...
    def _coerce_map_from_(self, S: Parent) -> bool | Map | None: ...
    def _convert_map_from_(self, other: Parent) -> bool | Map | None: ...
    def __richcmp__(self, other: Parent, op: int) -> bool: ...
    def unit_gens(self, **kwds: object) -> tuple[IntegerMod_abstract, ...]: ...
    def unit_group_exponent(self) -> Integer: ...
    def unit_group_order(self) -> Integer: ...
    def unit_group(self, algorithm: str = ...) -> AbelianGroupWithValues_class: ...
    def random_element(self, *args: object, **kwds: object) -> Element: ...
    def _lift_residue_field_root(self, p: int | Integer, e: int | Integer, f: Polynomial, fprime: Polynomial, root: IntegerMod_abstract) -> tuple[IntegerMod_abstract, ...]: ...

    @overload
    def _roots_univariate_polynomial(self, f: Polynomial, ring: sage.rings.abc.Ring | None = ..., multiplicities: Literal[True] = ..., algorithm: str | None = ...) -> list[tuple[FiniteRingElement, int]]: ...
    @overload
    def _roots_univariate_polynomial(self, f: Polynomial, ring: sage.rings.abc.Ring | None = ..., multiplicities: Literal[False] = ..., algorithm: str | None = ...) -> list[FiniteRingElement]: ...
    @overload
    def _roots_univariate_polynomial(self, f: Polynomial, ring: sage.rings.abc.Ring | None = ..., multiplicities: bool = ..., algorithm: str | None = ...) -> list[FiniteRingElement] | list[tuple[FiniteRingElement, int]]: ...

    def _gap_init_(self) -> str: ...
    def _magma_init_(self, magma: Expect) -> str: ...
    def degree(self) -> Integer: ...

def IntegerModRing(order: int | Integer = ...) -> IntegerModRing_generic: ...

Integers = IntegerModRing
