from sage.categories.map import Map
from sage.categories.morphism import Morphism
from sage.interfaces.expect import Expect
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.finite_rings.element_base import FiniteRingElement
from sage.rings.finite_rings.integer_mod_ring import IntegerModRing_generic
from sage.rings.integer import Integer
from sage.rings.integer_ring import IntegerRing_class
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.structure.element import Element, RingElement
from sage.structure.parent import Parent

class gen: ...
class SageInputBuilder: ...

type _ModList = list[IntegerMod_abstract]

class NativeIntStruct:
    def __init__(self, m: int) -> None: ...
    def __reduce__(self) -> tuple[type[NativeIntStruct], tuple[int]]: ...
    def precompute_table(self, parent: IntegerModRing_generic) -> None: ...

class IntegerMod_abstract(FiniteRingElement):
    def __init__(self, parent: Parent, value: Element | None = None) -> None: ...
    def __abs__(self) -> IntegerMod_abstract: ...
    def __reduce__(self) -> tuple[type[IntegerMod_abstract], tuple[Integer]]: ...
    def _im_gens_(
        self,
        codomain: Parent,
        im_gens: tuple[Element, ...],
        base_map: Map | None = None,
    ) -> Element: ...
    def __mod__(self, modulus: Element) -> IntegerMod_abstract: ...
    def is_nilpotent(self) -> bool: ...
    def _pari_init_(self) -> str: ...
    def __pari__(self) -> gen: ...
    def _gap_init_(self) -> str: ...
    def _magma_init_(self, magma: Expect) -> str: ...
    def _fricas_init_(self) -> str: ...
    def _sage_input_(self, sib: SageInputBuilder, coerced: bool) -> Element: ...
    def log(
        self,
        b: Element | None = None,
        order: Integer | None = None,
        check: bool = False,
    ) -> Integer: ...
    def generalised_log(self) -> list[tuple[Integer, Integer]]: ...
    def modulus(self) -> Integer: ...
    def charpoly(self, var: str = "x") -> Polynomial: ...
    def minpoly(self, var: str = "x") -> Polynomial: ...
    def minimal_polynomial(self, var: str = "x") -> Polynomial: ...
    def polynomial(self, var: str = "x") -> Polynomial: ...
    def norm(self) -> IntegerMod_abstract: ...
    def trace(self) -> IntegerMod_abstract: ...
    def lift_centered(self) -> Integer: ...
    def is_one(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def divides(self, other: IntegerMod_abstract) -> bool: ...
    def is_square(self) -> bool: ...
    def sqrt(
        self, extend: bool = True, all: bool = False
    ) -> IntegerMod_abstract | _ModList | None: ...
    def nth_root(
        self,
        n: int,
        extend: bool = False,
        all: bool = False,
        algorithm: str | None = None,
        cunningham: bool = False,
    ) -> IntegerMod_abstract | _ModList | None: ...
    def _nth_root_naive(self, n: int) -> IntegerMod_abstract: ...
    def _balanced_abs(self) -> Integer: ...
    def rational_reconstruction(self) -> Rational: ...
    def crt(self, other: IntegerMod_abstract) -> IntegerMod_abstract: ...
    def additive_order(self) -> Integer: ...
    def is_primitive_root(self) -> bool: ...
    def multiplicative_order(self) -> int: ...
    def valuation(self, p: Integer) -> int: ...
    def _floordiv_(self, right: IntegerMod_abstract) -> IntegerMod_abstract: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _integer_(self, ZZ: IntegerRing_class | None = None) -> Integer: ...
    def _rational_(self) -> Rational: ...
    def _vector_(self) -> FreeModuleElement[RingElement]: ...

class IntegerMod_gmp(IntegerMod_abstract):
    def __lshift__(self, k: int) -> IntegerMod_gmp: ...
    def __rshift__(self, k: int) -> IntegerMod_gmp: ...
    def _richcmp_(self, right: IntegerMod_gmp, op: int) -> bool: ...
    def is_one(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def _crt(self, other: IntegerMod_gmp) -> IntegerMod_gmp: ...
    def __copy__(self) -> IntegerMod_gmp: ...
    def __deepcopy__(self, memo: dict[int, Element]) -> IntegerMod_gmp: ...
    def _add_(self, right: IntegerMod_gmp) -> IntegerMod_gmp: ...
    def _sub_(self, right: IntegerMod_gmp) -> IntegerMod_gmp: ...
    def _neg_(self) -> IntegerMod_gmp: ...
    def _mul_(self, right: IntegerMod_gmp) -> IntegerMod_gmp: ...
    def _div_(self, right: IntegerMod_gmp) -> IntegerMod_gmp: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __pow__(self, exp: int, m: Element) -> IntegerMod_gmp: ...
    def __invert__(self) -> IntegerMod_gmp: ...
    def lift(self) -> Integer: ...
    def __float__(self) -> float: ...
    def __hash__(self) -> int: ...
    def gcd(self, other: IntegerMod_gmp) -> IntegerMod_gmp: ...

class IntegerMod_int(IntegerMod_abstract):
    def _richcmp_(self, right: IntegerMod_int, op: int) -> bool: ...
    def is_one(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def _crt(self, other: IntegerMod_int) -> IntegerMod_int: ...
    def __copy__(self) -> IntegerMod_int: ...
    def __deepcopy__(self, memo: dict[int, Element]) -> IntegerMod_int: ...
    def _add_(self, right: IntegerMod_int) -> IntegerMod_int: ...
    def _sub_(self, right: IntegerMod_int) -> IntegerMod_int: ...
    def _neg_(self) -> IntegerMod_int: ...
    def _mul_(self, right: IntegerMod_int) -> IntegerMod_int: ...
    def _div_(self, right: IntegerMod_int) -> IntegerMod_int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lshift__(self, k: int) -> IntegerMod_int: ...
    def __rshift__(self, k: int) -> IntegerMod_int: ...
    def __pow__(self, exp: int, m: Element) -> IntegerMod_int: ...
    def __invert__(self) -> IntegerMod_int: ...
    def lift(self) -> Integer: ...
    def __float__(self) -> float: ...
    def __hash__(self) -> int: ...
    def sqrt(
        self, extend: bool = True, all: bool = False
    ) -> IntegerMod_int | _ModList | None: ...
    def _balanced_abs(self) -> Integer: ...
    def gcd(self, other: IntegerMod_int) -> IntegerMod_int: ...

class IntegerMod_int64(IntegerMod_abstract):
    def _richcmp_(self, right: IntegerMod_int64, op: int) -> bool: ...
    def is_one(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def _crt(self, other: IntegerMod_int64) -> IntegerMod_int64: ...
    def __copy__(self) -> IntegerMod_int64: ...
    def __deepcopy__(self, memo: dict[int, Element]) -> IntegerMod_int64: ...
    def _add_(self, right: IntegerMod_int64) -> IntegerMod_int64: ...
    def _sub_(self, right: IntegerMod_int64) -> IntegerMod_int64: ...
    def _neg_(self) -> IntegerMod_int64: ...
    def _mul_(self, right: IntegerMod_int64) -> IntegerMod_int64: ...
    def _div_(self, right: IntegerMod_int64) -> IntegerMod_int64: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lshift__(self, k: int) -> IntegerMod_int64: ...
    def __rshift__(self, k: int) -> IntegerMod_int64: ...
    def __pow__(self, exp: int, m: Element) -> IntegerMod_int64: ...
    def __invert__(self) -> IntegerMod_int64: ...
    def lift(self) -> Integer: ...
    def __float__(self) -> float: ...
    def __hash__(self) -> int: ...
    def _balanced_abs(self) -> Integer: ...
    def gcd(self, other: IntegerMod_int64) -> IntegerMod_int64: ...

class IntegerMod_hom(Morphism):
    def __init__(self, parent: Parent) -> None: ...
    def _call_(self, x: Element) -> Element: ...

class IntegerMod_to_IntegerMod(IntegerMod_hom):
    def __init__(self, R: Parent, S: Parent) -> None: ...
    def _call_(self, x: Element) -> Element: ...
    def _repr_type(self) -> str: ...
    def is_surjective(self) -> bool: ...
    def is_injective(self) -> bool: ...

class Integer_to_IntegerMod(IntegerMod_hom):
    def __init__(self, R: Parent) -> None: ...
    def _call_(self, x: Element) -> Element: ...
    def _repr_type(self) -> str: ...
    def section(self) -> IntegerMod_to_Integer: ...
    def is_surjective(self) -> bool: ...
    def is_injective(self) -> bool: ...

class IntegerMod_to_Integer(Map):
    def __init__(self, R: Parent) -> None: ...
    def _call_(self, x: Element) -> Element: ...
    def _repr_type(self) -> str: ...

class Int_to_IntegerMod(IntegerMod_hom):
    def __init__(self, R: Parent) -> None: ...
    def _call_(self, x: Element) -> Element: ...
    def _repr_type(self) -> str: ...

def Mod(
    n: int | Integer, m: int | Integer, parent: Parent | None = None
) -> IntegerMod_abstract: ...
def IntegerMod(parent: Parent, value: Element) -> IntegerMod_abstract: ...
def square_root_mod_prime_power(
    a: IntegerMod_abstract, p: Integer, e: int
) -> IntegerMod_abstract: ...
def square_root_mod_prime(
    a: IntegerMod_abstract, p: Integer | None = None
) -> IntegerMod_abstract: ...
def lucas_q1(mm: Integer, P: IntegerMod_abstract) -> list[IntegerMod_abstract]: ...
def lucas(
    k: int, P: Integer, Q: Integer | int = 1, n: Integer | None = None
) -> list[Integer]: ...
