# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ResidueFieldFactory:
    def create_key_and_extra_args(self, p: builtins.object, names: builtins.object = ..., check: builtins.object = ..., implementation: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def create_object(self, version: builtins.object, key: builtins.object, **kwds: builtins.object) -> _SageObject: ...

ResidueField: _SageObject
class ResidueField_generic:
    def __init__(self, p: builtins.object) -> None: ...
    def construction(self) -> _SageObject: ...
    def ideal(self) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def reduction_map(self) -> _SageObject: ...
    def lift_map(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...

class ReductionMap:
    def __init__(self, K: builtins.object, F: builtins.object, to_vs: builtins.object, to_order: builtins.object, PB: builtins.object, PBinv: builtins.object) -> None: ...
    def section(self) -> _SageObject: ...

class ResidueFieldHomomorphism_global:
    def __init__(self, K: builtins.object, F: builtins.object, to_vs: builtins.object, to_order: builtins.object, PB: builtins.object, PBinv: builtins.object) -> None: ...
    def section(self) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...

class LiftingMap:
    def __init__(self, reduction: builtins.object, to_order: builtins.object, PB: builtins.object) -> None: ...

class ResidueFiniteField_prime_modn:
    def __init__(self, p: builtins.object, name: builtins.object, intp: builtins.object, to_vs: builtins.object, to_order: builtins.object, PB: builtins.object) -> None: ...
