from collections.abc import Iterator

from sage.structure.element import Element

def midpoint(pointa: Element | int | str | bool | None, pointb: Element | int | str | bool | None, w: Element) -> Element: ...
def cut_edge_by_bisection(pointa: Element | int | str | bool | None, pointb: Element | int | str | bool | None, condition: Element | int | str | bool | None, eps: Element | int | str | bool | None, N: Element | int | str | bool | None) -> Element: ...

class IndexFaceSet(PrimitiveObject):
    def _clean_point_list(self) -> Element: ...
    def _separate_creases(self, threshold: Element | int | str | bool | None) -> Element: ...
    def _mem_stats(self) -> Element: ...
    def is_enclosed(self) -> bool: ...
    def index_faces(self) -> Element: ...
    def has_local_colors(self) -> bool: ...
    def index_faces_with_colors(self) -> Element: ...
    def faces(self) -> Element: ...
    def face_list(self, render_params: Element | int | str | bool | None) -> Element: ...
    def edges(self) -> Element: ...
    def edge_list(self) -> Element: ...
    def vertices(self) -> Element: ...
    def vertex_list(self) -> Element: ...
    def x3d_geometry(self) -> Element: ...
    def bounding_box(self) -> Element: ...
    def partition(self, f: Element) -> Element: ...
    def add_condition(self, condition: Element | int | str | bool | None, N: Element | int | str | bool | None, eps: Element | int | str | bool | None) -> Element: ...
    def tachyon_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def json_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def threejs_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def obj_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def jmol_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def stl_binary_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def dual(self, **kwds: Element | int | str | bool | None) -> Element: ...
    def stickers(self, colors: Element | int | str | bool | None, width: Element | int | str | bool | None, hover: Element | int | str | bool | None) -> Element: ...
    def sticker(self, face_list: Element | int | str | bool | None, width: Element | int | str | bool | None, hover: Element | int | str | bool | None, **kwds: Element | int | str | bool | None) -> Element: ...

class FaceIter:
    def __iter__(self) -> Iterator[Element]: ...

class EdgeIter:
    def __iter__(self) -> Iterator[Element]: ...

class VertexIter:
    def __iter__(self) -> Iterator[Element]: ...

class PrimitiveObject: ...
