# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def format_tachyon_texture(rgb: builtins.object) -> _SageObject: ...

def format_tachyon_triangle(P: builtins.object, Q: builtins.object, R: builtins.object) -> _SageObject: ...

def format_json_vertex(P: builtins.object) -> _SageObject: ...

def format_json_face(face: builtins.object) -> _SageObject: ...

def format_obj_vertex(P: builtins.object) -> _SageObject: ...

def format_obj_face(face: builtins.object, off: builtins.object) -> _SageObject: ...

def format_obj_face_back(face: builtins.object, off: builtins.object) -> _SageObject: ...

def format_pmesh_vertex(P: builtins.object) -> _SageObject: ...

def format_pmesh_face(face: builtins.object, has_color: builtins.object) -> _SageObject: ...

def midpoint(pointa: builtins.object, pointb: builtins.object, w: builtins.object) -> _SageObject: ...

def cut_edge_by_bisection(pointa: builtins.object, pointb: builtins.object, condition: builtins.object, eps: builtins.object = ..., N: builtins.object = ...) -> _SageObject: ...

class IndexFaceSet:
    def realloc(self, vcount: builtins.object, fcount: builtins.object, icount: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def is_enclosed(self) -> builtins.bool: ...
    def index_faces(self) -> _SageObject: ...
    def has_local_colors(self) -> builtins.bool: ...
    def index_faces_with_colors(self) -> _SageObject: ...
    def faces(self) -> _SageObject: ...
    def face_list(self, render_params: builtins.object = ...) -> _SageObject: ...
    def edges(self) -> _SageObject: ...
    def edge_list(self) -> _SageObject: ...
    def vertices(self) -> _SageObject: ...
    def vertex_list(self) -> _SageObject: ...
    def x3d_geometry(self) -> _SageObject: ...
    def bounding_box(self) -> _SageObject: ...
    def partition(self, f: builtins.object) -> _SageObject: ...
    def add_condition(self, condition: builtins.object, N: builtins.object = ..., eps: builtins.object = ...) -> _SageObject: ...
    def condi(x: builtins.object, y: builtins.object, z: builtins.object) -> _SageObject: ...
    def cut(a: builtins.object, b: builtins.object, c: builtins.object) -> _SageObject: ...
    def iter_split_faces(self) -> _SageObject: ...
    def tachyon_repr(self, render_params: builtins.object) -> _SageObject: ...
    def json_repr(self, render_params: builtins.object) -> _SageObject: ...
    def threejs_repr(self, render_params: builtins.object) -> _SageObject: ...
    def obj_repr(self, render_params: builtins.object) -> _SageObject: ...
    def jmol_repr(self, render_params: builtins.object) -> _SageObject: ...
    def stl_binary_repr(self, render_params: builtins.object) -> _SageObject: ...
    def chopped_faces_iter(self) -> _SageObject: ...
    def dual(self, **kwds: builtins.object) -> _SageObject: ...
    def stickers(self, colors: builtins.object, width: builtins.object, hover: builtins.object) -> _SageObject: ...
    def sticker(self, face_list: builtins.object, width: builtins.object, hover: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class FaceIter:
    def __init__(self, face_set: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...

class EdgeIter:
    def __init__(self, face_set: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...

class VertexIter:
    def __init__(self, face_set: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...

def sticker(face: builtins.object, width: builtins.object, hover: builtins.object) -> _SageObject: ...
