# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def list_plot3d(v: builtins.object, interpolation_type: builtins.str = ..., point_list: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...

def list_plot3d_matrix(m: builtins.int, **kwds: builtins.object) -> _SageObject: ...

def list_plot3d_array_of_arrays(v: builtins.object, interpolation_type: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def list_plot3d_tuples(v: builtins.object, interpolation_type: builtins.object, **kwds: builtins.object) -> _SageObject: ...
