from sage.structure.element import Element

def list_plot3d(v: Element, interpolation_type: Element | int | str | bool | None, point_list: Element | int | str | bool | None) -> list[Element]: ...
def list_plot3d_matrix(m: int) -> list[Element]: ...
def list_plot3d_array_of_arrays(v: Element, interpolation_type: Element | int | str | bool | None) -> list[Element]: ...
def list_plot3d_tuples(v: Element, interpolation_type: Element | int | str | bool | None) -> list[Element]: ...
