from sage.structure.element import Element

class ParametricSurface(IndexFaceSet):
    def default_render_params(self) -> Element: ...
    def x3d_geometry(self) -> Element: ...
    def tachyon_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def obj_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def jmol_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def json_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def threejs_repr(self, render_params: Element | int | str | bool | None) -> Element: ...
    def is_enclosed(self) -> bool: ...
    def dual(self) -> Element: ...
    def bounding_box(self) -> Element: ...
    def triangulate(self, render_params: Element | int | str | bool | None) -> Element: ...
    def get_grid(self, ds: Element | int | str | bool | None) -> Element: ...
    def eval(self, u: Element | int | str | bool | None, v: Element) -> Element: ...
    def plot(self) -> Element: ...

class MoebiusStrip(ParametricSurface):
    ...

class IndexFaceSet: ...
