from sage.structure.element import Element

def plot_vector_field3d(functions: Element | int | str | bool | None, xrange: Element | int | str | bool | None, yrange: Element | int | str | bool | None, zrange: Element | int | str | bool | None, plot_points: Element | int | str | bool | None, colors: Element | int | str | bool | None, center_arrows: Element | int | str | bool | None) -> Element: ...
