from sage.structure.element import Element

def plot3d(f: Element, urange: Element | int | str | bool | None, vrange: Element | int | str | bool | None, adaptive: Element | int | str | bool | None, transformation: Element | int | str | bool | None) -> Element: ...
def plot3d_adaptive(f: Element, x_range: Element | int | str | bool | None, y_range: Element | int | str | bool | None, color: Element | int | str | bool | None, grad_f: Element | int | str | bool | None, max_bend: Element | int | str | bool | None, max_depth: Element | int | str | bool | None, initial_depth: Element | int | str | bool | None, num_colors: Element | int | str | bool | None) -> Element: ...
def spherical_plot3d(f: Element, urange: Element | int | str | bool | None, vrange: Element | int | str | bool | None) -> Element: ...
def cylindrical_plot3d(f: Element, urange: Element | int | str | bool | None, vrange: Element | int | str | bool | None) -> Element: ...
def axes(scale: Element | int | str | bool | None, radius: Element | int | str | bool | None) -> Element: ...

class _Coordinates:
    def _name(self) -> Element: ...
    def transform(self) -> Element: ...
    def to_cartesian(self, func: Element | int | str | bool | None, params: Element | int | str | bool | None) -> Element: ...

class _ArbitraryCoordinates(_Coordinates):
    ...

class Spherical(_Coordinates):
    ...

class SphericalElevation(_Coordinates):
    ...

class Cylindrical(_Coordinates):
    ...

class TrivialTriangleFactory:
    def triangle(self, a: Element, b: Element, c: Element, color: Element | int | str | bool | None) -> Element: ...
    def smooth_triangle(self, a: Element, b: Element, c: Element, da: Element | int | str | bool | None, db: Element | int | str | bool | None, dc: Element | int | str | bool | None, color: Element | int | str | bool | None) -> Element: ...
