# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

TACHYON_PIXEL: _SageObject
def line3d(points: builtins.object, thickness: builtins.int = ..., radius: builtins.object = ..., arrow_head: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...

def bezier3d(path: builtins.object, **options: builtins.object) -> _SageObject: ...

def polygon3d(points: builtins.object, **options: builtins.object) -> _SageObject: ...

def polygons3d(faces: builtins.object, points: builtins.object, **options: builtins.object) -> _SageObject: ...

def frame3d(lower_left: builtins.object, upper_right: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def frame_labels(lower_left: builtins.object, upper_right: builtins.object, label_lower_left: builtins.object, label_upper_right: builtins.object, eps: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...

def ruler(start: builtins.int, end: builtins.object, ticks: builtins.int = ..., sub_ticks: builtins.int = ..., absolute: builtins.bool = ..., snap: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...

def ruler_frame(lower_left: builtins.object, upper_right: builtins.object, ticks: builtins.int = ..., sub_ticks: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...

def sphere(center: builtins.tuple[_SageObject, ...] = ..., size: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...

def text3d(txt: builtins.object, x_y_z: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class Point:
    def __init__(self, center: builtins.object, size: builtins.int = ..., **kwds: builtins.object) -> None: ...
    def bounding_box(self) -> _SageObject: ...
    def tachyon_repr(self, render_params: builtins.object) -> _SageObject: ...
    def obj_repr(self, render_params: builtins.object) -> _SageObject: ...
    def jmol_repr(self, render_params: builtins.object) -> _SageObject: ...
    def threejs_repr(self, render_params: builtins.object) -> _SageObject: ...
    def stl_binary_repr(self, render_params: builtins.object) -> _SageObject: ...

class Line:
    def __init__(self, points: builtins.object, thickness: builtins.int = ..., corner_cutoff: builtins.float = ..., arrow_head: builtins.bool = ..., **kwds: builtins.object) -> None: ...
    def bounding_box(self) -> _SageObject: ...
    def tachyon_repr(self, render_params: builtins.object) -> _SageObject: ...
    def obj_repr(self, render_params: builtins.object) -> _SageObject: ...
    def jmol_repr(self, render_params: builtins.object) -> _SageObject: ...
    def corners(self, corner_cutoff: builtins.object = ..., max_len: builtins.object = ...) -> _SageObject: ...
    def threejs_repr(self, render_params: builtins.object) -> _SageObject: ...
    def stl_binary_repr(self, render_params: builtins.object) -> _SageObject: ...

def point3d(v: builtins.object, size: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...
