# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Tachyon:
    def __init__(self, xres: builtins.int = ..., yres: builtins.int = ..., zoom: builtins.float = ..., antialiasing: builtins.bool = ..., aspectratio: builtins.float = ..., raydepth: builtins.int = ..., camera_position: builtins.object = ..., camera_center: builtins.object = ..., updir: builtins.list[_SageObject] = ..., look_at: builtins.list[_SageObject] = ..., viewdir: builtins.object = ..., projection: builtins.str = ..., focallength: builtins.str = ..., aperture: builtins.str = ..., frustum: builtins.str = ...) -> None: ...
    def save_image(self, filename: builtins.object = ..., *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def save(self, filename: builtins.str = ..., verbose: builtins.object = ..., extra_opts: builtins.str = ...) -> _SageObject: ...
    def show(self, **kwds: builtins.object) -> _SageObject: ...
    def str(self) -> _SageObject: ...
    def light(self, center: builtins.object, radius: builtins.object, color: builtins.object) -> _SageObject: ...
    def texfunc(self, type: builtins.int = ..., center: builtins.tuple[_SageObject, ...] = ..., rotate: builtins.tuple[_SageObject, ...] = ..., scale: builtins.tuple[_SageObject, ...] = ..., imagefile: builtins.str = ...) -> _SageObject: ...
    def texture(self, name: builtins.str, ambient: builtins.float = ..., diffuse: builtins.float = ..., specular: builtins.float = ..., opacity: builtins.float = ..., color: builtins.tuple[_SageObject, ...] = ..., texfunc: builtins.int = ..., phong: builtins.int = ..., phongsize: builtins.float = ..., phongtype: builtins.str = ..., imagefile: builtins.str = ...) -> _SageObject: ...
    def texture_recolor(self, name: builtins.str, colors: builtins.object) -> _SageObject: ...
    def sphere(self, center: builtins.object, radius: builtins.object, texture: builtins.object) -> _SageObject: ...
    def ring(self, center: builtins.object, normal: builtins.object, inner: builtins.object, outer: builtins.object, texture: builtins.object) -> _SageObject: ...
    def cylinder(self, center: builtins.object, axis: builtins.object, radius: builtins.object, texture: builtins.object) -> _SageObject: ...
    def plane(self, center: builtins.object, normal: builtins.object, texture: builtins.object) -> _SageObject: ...
    def axis_aligned_box(self, min_p: builtins.object, max_p: builtins.object, texture: builtins.object) -> _SageObject: ...
    def fcylinder(self, base: builtins.object, apex: builtins.object, radius: builtins.object, texture: builtins.object) -> _SageObject: ...
    def triangle(self, vertex_1: builtins.object, vertex_2: builtins.object, vertex_3: builtins.object, texture: builtins.object) -> _SageObject: ...
    def smooth_triangle(self, vertex_1: builtins.object, vertex_2: builtins.object, vertex_3: builtins.object, normal_1: builtins.object, normal_2: builtins.object, normal_3: builtins.object, texture: builtins.object) -> _SageObject: ...
    def fractal_landscape(self, res: builtins.object, scale: builtins.object, center: builtins.object, texture: builtins.object) -> _SageObject: ...
    def plot(self, f: builtins.object, xmin_xmax: builtins.object, ymin_ymax: builtins.object, texture: builtins.object, grad_f: builtins.object = ..., max_bend: builtins.float = ..., max_depth: builtins.int = ..., initial_depth: builtins.int = ..., num_colors: builtins.object = ...) -> _SageObject: ...
    def parametric_plot(self, f: builtins.object, t_0: builtins.object, t_f: builtins.object, tex: builtins.object, r: builtins.float = ..., cylinders: builtins.bool = ..., min_depth: builtins.int = ..., max_depth: builtins.int = ..., e_rel: builtins.float = ..., e_abs: builtins.float = ...) -> _SageObject: ...

class Light:
    def __init__(self, center: builtins.object, radius: builtins.object, color: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class Texfunc:
    def __init__(self, ttype: builtins.int = ..., center: builtins.tuple[_SageObject, ...] = ..., rotate: builtins.tuple[_SageObject, ...] = ..., scale: builtins.tuple[_SageObject, ...] = ..., imagefile: builtins.str = ...) -> None: ...
    def str(self) -> _SageObject: ...

class Texture:
    def __init__(self, name: builtins.str, ambient: builtins.float = ..., diffuse: builtins.float = ..., specular: builtins.float = ..., opacity: builtins.float = ..., color: builtins.tuple[_SageObject, ...] = ..., texfunc: builtins.int = ..., phong: builtins.int = ..., phongsize: builtins.int = ..., phongtype: builtins.str = ..., imagefile: builtins.str = ...) -> None: ...
    def recolor(self, name: builtins.str, color: builtins.object) -> _SageObject: ...
    def str(self) -> _SageObject: ...

class Sphere:
    def __init__(self, center: builtins.object, radius: builtins.object, texture: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class Ring:
    def __init__(self, center: builtins.object, normal: builtins.object, inner: builtins.object, outer: builtins.object, texture: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class FractalLandscape:
    def __init__(self, res: builtins.object, scale: builtins.object, center: builtins.object, texture: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class Cylinder:
    def __init__(self, center: builtins.object, axis: builtins.object, radius: builtins.object, texture: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class Plane:
    def __init__(self, center: builtins.object, normal: builtins.object, texture: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class FCylinder:
    def __init__(self, base: builtins.object, apex: builtins.object, radius: builtins.object, texture: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class Axis_aligned_box:
    def __init__(self, min_p: builtins.object, max_p: builtins.object, texture: builtins.object) -> None: ...
    def str(self) -> _SageObject: ...

class TachyonTriangle:
    def str(self) -> _SageObject: ...

class TachyonSmoothTriangle:
    def str(self) -> _SageObject: ...

class TachyonTriangleFactory:
    def __init__(self, tach: builtins.object, tex: builtins.object) -> None: ...
    def triangle(self, a: builtins.object, b: builtins.object, c: builtins.object, color: builtins.object = ...) -> _SageObject: ...
    def smooth_triangle(self, a: builtins.object, b: builtins.object, c: builtins.object, da: builtins.object, db: builtins.object, dc: builtins.object, color: builtins.object = ...) -> _SageObject: ...
    def get_colors(self, list: builtins.object) -> _SageObject: ...

class ParametricPlot:
    def str(self) -> _SageObject: ...
    def __init__(self, f: builtins.object, t_0: builtins.object, t_f: builtins.object, tex: builtins.object, r: builtins.float = ..., cylinders: builtins.bool = ..., min_depth: builtins.int = ..., max_depth: builtins.int = ..., e_rel: builtins.float = ..., e_abs: builtins.float = ...) -> None: ...
    def tol(self, est: builtins.object, val: builtins.object) -> _SageObject: ...

def tostr(s: builtins.object, length: builtins.int = ..., out_type: builtins.object = ...) -> _SageObject: ...
