from sage.structure.element import Element
from sage.structure.sage_object import SageObject

def parse_color(info: Element | int | str | bool | None, base: Element | int | str | bool | None) -> Element: ...

class Texture(WithEqualityById, SageObject):
    def _repr_(self) -> str: ...
    def hex_rgb(self) -> str: ...
    def tachyon_str(self) -> str: ...
    def x3d_str(self) -> str: ...
    def mtl_str(self) -> str: ...
    def jmol_str(self, obj: Element | int | str | bool | None) -> str: ...

class WithEqualityById: ...
