# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

pi: _SageObject
class Transformation:
    def __init__(self, scale: builtins.object = ...) -> None: ...
    def get_matrix(self) -> _SageObject: ...
    def is_skew(self, eps: builtins.object = ...) -> builtins.bool: ...
    def is_uniform(self, eps: builtins.object = ...) -> builtins.bool: ...
    def is_uniform_on(self, basis: builtins.object, eps: builtins.object = ...) -> builtins.bool: ...
    def transform_point(self, x: builtins.object) -> _SageObject: ...
    def transform_vector(self, v: builtins.object) -> _SageObject: ...
    def transform_bounding_box(self, box: builtins.object) -> _SageObject: ...
    def transform_point_c(self, res: builtins.object, P: builtins.object) -> _SageObject: ...
    def transform_vector_c(self, res: builtins.object, P: builtins.object) -> _SageObject: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __invert__(self) -> Self: ...
    def __call__(self, p: builtins.object) -> _SageObject: ...
    def max_scale(self) -> _SageObject: ...
    def avg_scale(self) -> _SageObject: ...

def rotate_arbitrary(v: builtins.object, theta: builtins.object) -> _SageObject: ...
