from sage.structure.element import Element

def crossunit(u: Element | int | str | bool | None, v: Element) -> Element: ...

type _BuiltinStr = str
class Triangle:
    def str(self) -> Element: ...
    def set_color(self, color: Element | int | _BuiltinStr | bool | None) -> Element: ...
    def get_vertices(self) -> Element: ...

class SmoothTriangle(Triangle):
    def get_normals(self) -> Element: ...

class TriangleFactory:
    def triangle(self, a: Element, b: Element, c: Element, color: Element | int | str | bool | None) -> Element: ...
    def smooth_triangle(self, a: Element, b: Element, c: Element, da: Element | int | str | bool | None, db: Element | int | str | bool | None, dc: Element | int | str | bool | None, color: Element | int | str | bool | None) -> Element: ...
    def get_colors(self, list: Element | int | str | bool | None) -> Element: ...

class TrianglePlot:
    def plot_block(self, min_x: Element | int | _BuiltinStr | bool | None, mid_x: Element | int | _BuiltinStr | bool | None, max_x: Element | int | _BuiltinStr | bool | None, min_y: Element | int | _BuiltinStr | bool | None, mid_y: Element | int | _BuiltinStr | bool | None, max_y: Element | int | _BuiltinStr | bool | None, sw_z: Element | int | _BuiltinStr | bool | None, nw_z: Element | int | _BuiltinStr | bool | None, se_z: Element | int | _BuiltinStr | bool | None, ne_z: Element | int | _BuiltinStr | bool | None, mid_z: Element | int | _BuiltinStr | bool | None, depth: Element | int | _BuiltinStr | bool | None) -> Element: ...
    def interface(self, n: int, p: int, p_c: Element | int | _BuiltinStr | bool | None, q: int, q_c: Element | int | _BuiltinStr | bool | None) -> Element: ...
    def triangulate(self, p: int, c: Element) -> Element: ...
    def extrema(self, list: Element | int | _BuiltinStr | bool | None) -> Element: ...

class PlotBlock:
    ...
