from sage.combinat.free_module import CombinatorialFreeModule
from sage.combinat.root_system.root_system import RootSystem
from sage.rings.ring import Ring
from sage.rings.ring_element import RingElement
from sage.rings.integer import Integer
from sage.combinat.root_system.cartan_type import CartanType_abstract
from sage.categories.morphism import Morphism

class AmbientSpace(CombinatorialFreeModule):
    def __init__(self, root_system: RootSystem, base_ring: Ring, index_set: tuple[Integer, ...] | None = ...) -> None: ...
    def dimension(self) -> Integer: ...
    @classmethod
    def smallest_base_ring(cls, cartan_type: CartanType_abstract | None = ...) -> Ring: ...
    def __call__(self, v: object) -> CombinatorialFreeModule.Element: ...
    def __getitem__(self, i: Integer | slice) -> CombinatorialFreeModule.Element: ...
    def coroot_lattice(self) -> CombinatorialFreeModule: ...
    def simple_coroot(self, i: Integer) -> CombinatorialFreeModule.Element: ...
    def reflection(self, root: CombinatorialFreeModule.Element, coroot: CombinatorialFreeModule.Element | None = ...) -> CombinatorialFreeModule.Element: ...
    def fundamental_weight(self, i: Integer) -> CombinatorialFreeModule.Element: ...
    def from_vector_notation(self, weight: tuple[Integer, ...], style: str = ...) -> CombinatorialFreeModule.Element: ...
    def to_ambient_space_morphism(self) -> Morphism: ...

class AmbientSpaceElement(CombinatorialFreeModule.Element):
    def inner_product(self, lambdacheck: CombinatorialFreeModule.Element) -> RingElement: ...
    def associated_coroot(self) -> CombinatorialFreeModule.Element: ...
    def is_positive_root(self) -> bool: ...
    def coerce_to_sl(self) -> CombinatorialFreeModule.Element: ...
    def coerce_to_e7(self) -> CombinatorialFreeModule.Element: ...
    def coerce_to_e6(self) -> CombinatorialFreeModule.Element: ...
    def to_ambient(self) -> CombinatorialFreeModule.Element: ...
