# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BraidMoveCalculator:
    def __init__(self, coxeter_group: builtins.object) -> None: ...
    def put_in_front(self, k: builtins.int, input_word: builtins.object) -> _SageObject: ...
    def chain_of_reduced_words(self, start_word: builtins.object, end_word: builtins.object) -> _SageObject: ...
