# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def BraidOrbit(word: builtins.object, rels: builtins.object) -> _SageObject: ...

def is_fully_commutative(word: builtins.object, rels: builtins.object) -> builtins.bool: ...

def pattern_match(L: builtins.object, i: builtins.object, X: builtins.object, l: builtins.object) -> _SageObject: ...
