# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CoxeterType:
    @staticmethod
    def __classcall_private__(cls: builtins.object, *x: builtins.object) -> _SageObject: ...
    @classmethod
    def samples(self, finite: builtins.object = ..., affine: builtins.object = ..., crystallographic: builtins.object = ...) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def coxeter_graph(self) -> _SageObject: ...
    def is_finite(self) -> builtins.bool: ...
    def is_affine(self) -> builtins.bool: ...
    def is_crystallographic(self) -> builtins.bool: ...
    def is_simply_laced(self) -> builtins.bool: ...
    def bilinear_form(self, R: builtins.int = ...) -> _SageObject: ...

class CoxeterTypeFromCartanType:
    @staticmethod
    def __classcall_private__(cls: builtins.object, cartan_type: builtins.object) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def coxeter_graph(self) -> _SageObject: ...
    def cartan_type(self) -> _SageObject: ...
    def type(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def is_finite(self) -> builtins.bool: ...
    def is_affine(self) -> builtins.bool: ...
    def is_crystallographic(self) -> builtins.bool: ...
    def is_simply_laced(self) -> builtins.bool: ...
    def is_reducible(self) -> builtins.bool: ...
    def is_irreducible(self) -> builtins.bool: ...
    def component_types(self) -> _SageObject: ...
    def relabel(self, relabelling: builtins.object) -> _SageObject: ...
