import builtins

class _SageObject: ...

class CoxeterType:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, *x: builtins.object
    ) -> _SageObject: ...
    @classmethod
    def samples(
        cls,
        finite: builtins.object = ...,
        affine: builtins.object = ...,
        crystallographic: builtins.object = ...,
    ) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def coxeter_graph(self) -> _SageObject: ...
    def is_finite(self) -> bool: ...
    def is_affine(self) -> bool: ...
    def is_crystallographic(self) -> bool: ...
    def is_simply_laced(self) -> bool: ...
    def bilinear_form(self, R: builtins.int = ...) -> _SageObject: ...

class CoxeterTypeFromCartanType:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, cartan_type: builtins.object
    ) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def coxeter_graph(self) -> _SageObject: ...
    def cartan_type(self) -> _SageObject: ...
    def type(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def is_finite(self) -> bool: ...
    def is_affine(self) -> bool: ...
    def is_crystallographic(self) -> bool: ...
    def is_simply_laced(self) -> bool: ...
    def is_reducible(self) -> bool: ...
    def is_irreducible(self) -> bool: ...
    def component_types(self) -> _SageObject: ...
    def relabel(self, relabelling: builtins.object) -> _SageObject: ...
