import builtins

class _SageObject: ...

def DynkinDiagram(
    self, *args: builtins.object, **kwds: builtins.object
) -> _SageObject: ...

class DynkinDiagram_class:
    def __init__(
        self,
        t: builtins.object = ...,
        index_set: builtins.object = ...,
        odd_isotropic_roots: builtins.list[_SageObject] = ...,
        **options: builtins.object,
    ) -> None: ...
    def add_edge(
        self, i: builtins.int, j: builtins.int, label: builtins.int = ...
    ) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    @staticmethod
    def an_instance() -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def cartan_type(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def dynkin_diagram(self) -> _SageObject: ...
    def cartan_matrix(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def relabel(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def subtype(self, index_set: builtins.object) -> _SageObject: ...
    def is_finite(self) -> bool: ...
    def is_affine(self) -> bool: ...
    def is_irreducible(self) -> bool: ...
    def is_crystallographic(self) -> bool: ...
    def symmetrizer(self) -> _SageObject: ...
    def odd_isotropic_roots(self) -> _SageObject: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def column(self, j: builtins.int) -> _SageObject: ...
    def row(self, i: builtins.int) -> _SageObject: ...
    def coxeter_diagram(self) -> _SageObject: ...

def precheck(
    self,
    letter: builtins.object = ...,
    length: builtins.int = ...,
    affine: builtins.object = ...,
    n_ge: builtins.object = ...,
    n: builtins.int = ...,
) -> _SageObject: ...
