# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class NonSymmetricMacdonaldPolynomials:
    @staticmethod
    def __classcall__(cls: builtins.object, KL: builtins.object, q: builtins.str = ..., q1: builtins.str = ..., q2: builtins.str = ..., normalized: builtins.bool = ...) -> _SageObject: ...
    def __init__(self, KL: builtins.object, q: builtins.int, q1: builtins.object, q2: builtins.object, normalized: builtins.object) -> None: ...
    def cartan_type(self) -> _SageObject: ...
    def L(self) -> _SageObject: ...
    def L_check(self) -> _SageObject: ...
    def L_prime(self) -> _SageObject: ...
    def L0(self) -> _SageObject: ...
    def KL0(self) -> _SageObject: ...
    def Q_to_Qcheck(self) -> _SageObject: ...
    def Y(self) -> _SageObject: ...
    def affine_lift(self, mu: builtins.object) -> _SageObject: ...
    def twist(self, mu: builtins.object, i: builtins.int) -> _SageObject: ...
    def affine_retract(self, mu: builtins.object) -> _SageObject: ...
    def __getitem__(self, mu: builtins.object) -> _SageObject: ...
    def rho_prime(self) -> _SageObject: ...
    def eigenvalue_experimental(self, mu: builtins.object, l: builtins.object) -> _SageObject: ...
    def seed(self, mu: builtins.object) -> _SageObject: ...
    def symmetric_macdonald_polynomial(self, mu: builtins.object) -> _SageObject: ...
