import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class PieriFactors:
    def __contains__(self, w: object) -> bool: ...
    def elements(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def generating_series(self, weight: builtins.object = ...) -> _SageObject: ...
    def default_weight(self) -> _SageObject: ...
    def max_length(self) -> _SageObject: ...

class PieriFactors_finite_type:
    def maximal_elements(self) -> _SageObject: ...

class PieriFactors_affine_type:
    def maximal_elements(self) -> _SageObject: ...

class PieriFactors_type_A:
    def __init__(self, W: builtins.object) -> None: ...
    def maximal_elements_combinatorial(self) -> _SageObject: ...
    def stanley_symm_poly_weight(self, w: builtins.object) -> _SageObject: ...

class PieriFactors_type_B:
    def __init__(self, W: builtins.object) -> None: ...
    def maximal_elements_combinatorial(self) -> _SageObject: ...
    def stanley_symm_poly_weight(self, w: builtins.object) -> _SageObject: ...

class PieriFactors_type_A_affine:
    @staticmethod
    def __classcall__(
        cls: builtins.object,
        W: builtins.object,
        min_length: builtins.int = ...,
        max_length: builtins.object = ...,
        min_support: builtins.object = ...,
        max_support: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        W: builtins.object,
        min_length: builtins.object,
        max_length: builtins.object,
        min_support: builtins.object,
        max_support: builtins.object,
    ) -> None: ...
    def subset(self, length: builtins.int) -> _SageObject: ...
    def maximal_elements_combinatorial(self) -> _SageObject: ...
    def __contains__(self, w: object) -> bool: ...
    def __getitem__(self, support: builtins.object) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def generating_series(self, weight: builtins.object = ...) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def stanley_symm_poly_weight(self, w: builtins.object) -> _SageObject: ...

class PieriFactors_type_C_affine:
    def __init__(self, W: builtins.object) -> None: ...
    def maximal_elements_combinatorial(self) -> _SageObject: ...
    def stanley_symm_poly_weight(self, w: builtins.object) -> _SageObject: ...

class PieriFactors_type_B_affine:
    def __init__(self, W: builtins.object) -> None: ...
    def maximal_elements_combinatorial(self) -> _SageObject: ...
    def stanley_symm_poly_weight(self, w: builtins.object) -> _SageObject: ...

class PieriFactors_type_D_affine:
    def __init__(self, W: builtins.object) -> None: ...
    def maximal_elements_combinatorial(self) -> _SageObject: ...
    def stanley_symm_poly_weight(self, w: builtins.object) -> _SageObject: ...
