# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Iterator:
    def noncom_letters(self) -> _SageObject: ...
    def succ(self, u: builtins.object, first: builtins.object) -> _SageObject: ...
    def succ_words(self, u: builtins.object, word: builtins.object, first: builtins.object) -> _SageObject: ...
    def test(self, u: builtins.object, si: builtins.object, i: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def iter_depth(self) -> _SageObject: ...
    def iter_words_depth(self) -> _SageObject: ...
    def iter_breadth(self) -> _SageObject: ...
    def iter_words_breadth(self) -> _SageObject: ...
    def iter_parabolic(self) -> _SageObject: ...

def iterator_tracking_words(W: builtins.object) -> _SageObject: ...

def has_left_descent(w: builtins.object, i: builtins.object, N: builtins.object) -> builtins.bool: ...

def first_descent(w: builtins.object, n: builtins.object, N: builtins.object, left: builtins.object) -> _SageObject: ...

def parabolic_recursive(x: builtins.object, v: builtins.object, f: builtins.object) -> _SageObject: ...

def parabolic_iteration_application(W: builtins.object, f: builtins.object) -> _SageObject: ...

def reduced_word_c(W: builtins.object, w: builtins.object) -> _SageObject: ...
