import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

def ReflectionGroup(
    self, *args: builtins.object, **kwds: builtins.object
) -> _SageObject: ...
def is_chevie_available(self) -> builtins.bool: ...

class RealReflectionGroup:
    def __init__(
        self,
        W_types: builtins.object,
        index_set: builtins.object = ...,
        hyperplane_index_set: builtins.object = ...,
        reflection_index_set: builtins.object = ...,
    ) -> None: ...
    def iteration(
        self, algorithm: builtins.str = ..., tracking_words: builtins.bool = ...
    ) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def bipartite_index_set(self) -> _SageObject: ...
    def cartan_type(self) -> _SageObject: ...
    def positive_roots(self) -> _SageObject: ...
    def almost_positive_roots(self) -> _SageObject: ...
    def root_to_reflection(self, root: builtins.object) -> _SageObject: ...
    def reflection_to_positive_root(self, r: builtins.int) -> _SageObject: ...
    def fundamental_weights(self) -> _SageObject: ...
    def fundamental_weight(self, i: builtins.int) -> _SageObject: ...
    def coxeter_diagram(self) -> _SageObject: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def right_coset_representatives(self, J: builtins.int) -> _SageObject: ...
    def simple_root_index(self, i: builtins.int) -> _SageObject: ...
    def bruhat_cone(
        self,
        x: builtins.object,
        y: builtins.object,
        side: builtins.str = ...,
        backend: builtins.str = ...,
    ) -> _SageObject: ...

    class Element:
        def right_coset_representatives(self) -> _SageObject: ...
        def left_coset_representatives(self) -> _SageObject: ...

class IrreducibleRealReflectionGroup:
    class Element: ...
