from sage.structure.sage_object import SageObject
from sage.structure.unique_representation import UniqueRepresentation
from sage.combinat.root_system.cartan_type import CartanType_abstract
from sage.combinat.root_system.ambient_space import AmbientSpace
from sage.combinat.root_system.root_lattice_realizations import RootLatticeRealizations
from sage.combinat.root_system.weight_lattice_realizations import WeightLatticeRealizations
from sage.rings.ring import Ring
from sage.rings.integer import Integer

class RootSystem(UniqueRepresentation, SageObject):
    def cartan_type(self) -> CartanType_abstract: ...
    def rank(self) -> Integer: ...
    def ambient_space(self, base_ring: Ring | None = ...) -> AmbientSpace | None: ...
    def root_lattice(self) -> RootLatticeRealizations.ParentMethods: ...
    def weight_lattice(self, extended: bool = ...) -> WeightLatticeRealizations.ParentMethods: ...
    def coroot_lattice(self) -> RootLatticeRealizations.ParentMethods: ...
