import builtins

from sage.structure.element import Element

class _SageObject: ...

class CartanType:
    affine: bool

    def __init__(self, types: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def component_types(self) -> _SageObject: ...
    def type(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def cartan_matrix(self, subdivide: builtins.bool = ...) -> _SageObject: ...
    def dynkin_diagram(self) -> _SageObject: ...
    def ascii_art(
        self, label: builtins.str = ..., node: builtins.object = ...
    ) -> _SageObject: ...
    def is_finite(self) -> builtins.bool: ...
    def is_irreducible(self) -> builtins.bool: ...
    def dual(self) -> _SageObject: ...
    def is_affine(self) -> bool: ...
    def coxeter_diagram(self) -> _SageObject: ...

class AmbientSpace:
    def cartan_type(self) -> _SageObject: ...
    def component_types(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def ambient_spaces(self) -> _SageObject: ...
    def inject_weights(self, i: builtins.int, v: builtins.object) -> _SageObject: ...
    def simple_root(self, i: builtins.int) -> _SageObject: ...
    def simple_coroot(self, i: builtins.int) -> _SageObject: ...
    def positive_roots(self) -> list[Element]: ...
    def negative_roots(self) -> list[Element]: ...
    def fundamental_weights(self) -> _SageObject: ...
