# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AmbientSpace:
    def __init__(self, root_system: builtins.object, base_ring: builtins.object) -> None: ...
    def dimension(self) -> _SageObject: ...
    def root(self, i: builtins.int, j: builtins.int = ..., k: builtins.int = ..., l: builtins.object = ..., p1: builtins.int = ..., p2: builtins.int = ..., p3: builtins.int = ..., p4: builtins.int = ...) -> _SageObject: ...
    def simple_root(self, i: builtins.int) -> _SageObject: ...
    def negative_roots(self) -> _SageObject: ...
    def positive_roots(self) -> _SageObject: ...
    def fundamental_weights(self) -> _SageObject: ...

class CartanType:
    def __init__(self) -> None: ...
    AmbientSpace: _SageObject
    def coxeter_number(self) -> _SageObject: ...
    def dual_coxeter_number(self) -> _SageObject: ...
    def dynkin_diagram(self) -> _SageObject: ...
    def ascii_art(self, label: builtins.str = ..., node: builtins.object = ...) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
