# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AmbientSpace:
    @classmethod
    def smallest_base_ring(cls, cartan_type: builtins.object) -> _SageObject: ...
    def __init__(self, root_system: builtins.object, base_ring: builtins.object) -> None: ...
    def is_extended(self) -> builtins.bool: ...
    def fundamental_weight(self, i: builtins.int) -> _SageObject: ...
    def simple_root(self, i: builtins.int) -> _SageObject: ...
    def simple_coroot(self, i: builtins.int) -> _SageObject: ...
    def coroot_lattice(self) -> _SageObject: ...
    class Element:
        def inner_product(self, other: builtins.object) -> _SageObject: ...
        scalar: _SageObject
        def associated_coroot(self) -> _SageObject: ...
