import builtins

class _SageObject: ...

class CartanType:
    def __init__(self, type: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def ascii_art(
        self, label: builtins.str = ..., node: builtins.object = ...
    ) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def dual(self) -> _SageObject: ...
    def dynkin_diagram(self) -> _SageObject: ...

class AmbientSpace:
    def dimension(self) -> _SageObject: ...
    def simple_root(self, i: builtins.int) -> _SageObject: ...
    def fundamental_weights(self) -> _SageObject: ...

class CartanType_finite:
    AmbientSpace: _SageObject

class CartanType_affine:
    def classical(self) -> _SageObject: ...
    def basic_untwisted(self) -> _SageObject: ...
    def special_node(self) -> _SageObject: ...
