from typing import TYPE_CHECKING

from sage.categories.category_with_axiom import CategoryWithAxiom_over_base_ring

if TYPE_CHECKING:
    from sage.structure.element import Element
    from sage.categories.category import Category
    from sage.sets.family import Family
    from sage.modules.free_module_morphism import FreeModuleMorphism


class WeightLatticeRealizations(CategoryWithAxiom_over_base_ring):
    def super_categories(self) -> list[Category]: ...

    class ParentMethods:
        def is_extended(self) -> bool: ...
        def __init_extra__(self) -> None: ...
        def _test_weight_lattice_realization(self, **options: object) -> None: ...
        def fundamental_weights(self) -> Family: ...
        def simple_root(self, i: object) -> Element: ...
        def rho(self) -> Element: ...
        def reduced_word_of_alcove_morphism(self, f: object) -> list[object]: ...
        def dynkin_diagram_automorphism_of_alcove_morphism(
            self, f: object
        ) -> dict[object, object]: ...
