from sage.combinat.free_module import CombinatorialFreeModule
from sage.combinat.root_system.root_system import RootSystem
from sage.categories.morphism import Morphism
from sage.rings.ring_element import RingElement
from sage.sets.family import AbstractFamily
from sage.structure.element import Element


class WeightSpace(CombinatorialFreeModule):
    root_system: RootSystem
    _extended: bool

    @staticmethod
    def __classcall_private__(
        cls: type[WeightSpace], root_system: RootSystem, base_ring: object, extended: bool = ...
    ) -> WeightSpace: ...
    def __init__(self, root_system: RootSystem, base_ring: object, extended: bool) -> None: ...
    def is_extended(self) -> bool: ...
    def _repr_(self) -> str: ...
    def _name_string(
        self, capitalize: bool = ..., base_ring: bool = ..., type: bool = ...
    ) -> str: ...
    def fundamental_weight(self, i: object | str) -> Element: ...
    def basis_extension(self) -> AbstractFamily: ...
    def simple_root(self, j: object) -> Element: ...
    def _repr_term(self, m: object) -> str: ...
    def _latex_term(self, m: object) -> str: ...
    def _to_classical_on_basis(self, i: object | str) -> Element: ...
    def to_ambient_space_morphism(self) -> Morphism: ...


class WeightSpaceElement(CombinatorialFreeModule.Element):
    def scalar(self, lambdacheck: Element) -> RingElement: ...
    def is_dominant(self) -> bool: ...
    def is_dominant_weight(self) -> bool: ...
    def to_ambient(self) -> CombinatorialFreeModule.Element: ...
    def to_weight_space(self) -> Element: ...
