from collections.abc import Iterator
from sage.groups.matrix_gps.finitely_generated_gap import FinitelyGeneratedMatrixGroup_gap
from sage.groups.matrix_gps.group_element_gap import MatrixGroupElement_gap
from sage.groups.perm_gps.permgroup import PermutationGroup_generic
from sage.structure.unique_representation import UniqueRepresentation
from sage.sets.family import AbstractFamily as Family

from sage.combinat.root_system.cartan_type import CartanType_abstract
from sage.combinat.root_system.root_lattice_realizations import RootLatticeRealizations
from sage.matrix.matrix import Matrix
from sage.structure.element import Element
from sage.rings.integer import Integer
def WeylGroup(
    x: object,
    prefix: str | None = None,
    implementation: str = "matrix",
) -> WeylGroup_gens | WeylGroup_permutation: ...


class WeylGroup_gens(UniqueRepresentation, FinitelyGeneratedMatrixGroup_gap):
    def __init__(self, domain: RootLatticeRealizations, prefix: str | None) -> None: ...
    def __hash__(self) -> int: ...
    def cartan_type(self) -> CartanType_abstract: ...
    def index_set(self) -> tuple[object, ...]: ...
    def morphism_matrix(self, f: object) -> Matrix: ...
    def from_morphism(self, f: object) -> WeylGroupElement: ...
    def simple_reflections(self) -> Family: ...
    def reflections(self) -> Family: ...
    def _repr_(self) -> str: ...
    def character_table(self) -> str: ...
    def one(self) -> WeylGroupElement: ...
    unit: WeylGroupElement
    def domain(self) -> RootLatticeRealizations: ...
    def simple_reflection(self, i: object) -> WeylGroupElement: ...
    def long_element_hardcoded(self) -> WeylGroupElement: ...
    def classical(self) -> ClassicalWeylSubgroup: ...
    Element: type[WeylGroupElement]


class ClassicalWeylSubgroup(WeylGroup_gens):
    def cartan_type(self) -> CartanType_abstract: ...
    def simple_reflections(self) -> Family: ...
    def weyl_group(self, prefix: str = "hereditary") -> WeylGroup_gens: ...
    def _test_is_finite(self, **options: object) -> None: ...


class WeylGroupElement(MatrixGroupElement_gap):
    def __init__(self, parent: WeylGroup_gens, g: object, check: bool = False) -> None: ...
    def __hash__(self) -> int: ...
    def to_matrix(self) -> Matrix: ...
    def domain(self) -> RootLatticeRealizations: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def _richcmp_(self, other: WeylGroupElement, op: object) -> bool: ...
    def action(self, v: Element) -> Element: ...
    def has_descent(self, i: object, positive: bool = False, side: str = "right") -> bool: ...
    def has_left_descent(self, i: object) -> bool: ...
    def has_right_descent(self, i: object) -> bool: ...
    def apply_simple_reflection(self, i: object, side: str = "right") -> WeylGroupElement: ...
    def to_permutation(self) -> tuple[int, ...]: ...
    def to_permutation_string(self) -> str: ...


class WeylGroup_permutation(UniqueRepresentation, PermutationGroup_generic):
    def __init__(self, cartan_type: CartanType_abstract, prefix: str | None) -> None: ...
    def iteration(self, algorithm: str = "breadth", tracking_words: bool = True) -> Iterator[WeylGroupElement]: ...
    def __iter__(self) -> Iterator[WeylGroupElement]: ...
    def _coerce_map_from_(self, P: object) -> bool: ...
    def rank(self) -> Integer: ...
    def simple_reflection(self, i: object) -> WeylGroupElement: ...
    def simple_roots(self) -> Family: ...
    independent_roots: Family
    def index_set(self) -> tuple[object, ...]: ...
    def reflection_index_set(self) -> tuple[int, ...]: ...
    def cartan_type(self) -> CartanType_abstract: ...
    def roots(self) -> tuple[object, ...]: ...
    def positive_roots(self) -> tuple[object, ...]: ...
