from sage.homology.chain_complex import ChainComplex_class
from sage.homology.chain_homotopy import ChainContraction
from sage.rings.ring import Field

def algebraic_topological_model(
    K: object, base_ring: Field | None = ...
) -> tuple[ChainContraction, ChainComplex_class]: ...

def algebraic_topological_model_delta_complex(
    K: object, base_ring: Field | None = ...
) -> tuple[ChainContraction, ChainComplex_class]: ...
