# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CellComplexReference:
    def __init__(self, cell_complex: builtins.object, degree: builtins.int, cells: builtins.object = ...) -> None: ...
    def cell_complex(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...

class Chains:
    def __init__(self, cell_complex: builtins.object, degree: builtins.int, cells: builtins.object = ..., base_ring: builtins.object = ...) -> None: ...
    def dual(self) -> _SageObject: ...
    def chain_complex(self) -> _SageObject: ...
    class Element:
        def to_complex(self) -> _SageObject: ...
        def boundary(self) -> _SageObject: ...
        def is_cycle(self) -> builtins.bool: ...
        def is_boundary(self) -> builtins.bool: ...

class Cochains:
    def __init__(self, cell_complex: builtins.object, degree: builtins.int, cells: builtins.object = ..., base_ring: builtins.object = ...) -> None: ...
    def dual(self) -> _SageObject: ...
    def cochain_complex(self) -> _SageObject: ...
    class Element:
        def to_complex(self) -> _SageObject: ...
        def coboundary(self) -> _SageObject: ...
        def is_cocycle(self) -> builtins.bool: ...
        def is_coboundary(self) -> builtins.bool: ...
        def eval(self, other: builtins.object) -> _SageObject: ...
        def cup_product(self, cochain: builtins.object) -> _SageObject: ...
