import builtins
from typing import Self

class _SageObject: ...

class ChainComplexMorphism:
    def __init__(
        self,
        matrices: builtins.object,
        C: builtins.object,
        D: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def in_degree(self, n: builtins.int) -> _SageObject: ...
    def to_matrix(self, deg: builtins.object = ...) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def __neg__(self) -> Self: ...
    def __add__(self, x: builtins.object) -> Self: ...
    def __mul__(self, x: builtins.object) -> Self: ...
    def __rmul__(self, x: builtins.object) -> Self: ...
    def __sub__(self, x: builtins.object) -> Self: ...
    def __eq__(self, x: object) -> bool: ...
    def is_identity(self) -> bool: ...
    def is_surjective(self) -> bool: ...
    def is_injective(self) -> bool: ...
    def __hash__(self) -> int: ...
