# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def ChainComplex(data: builtins.object = ..., base_ring: builtins.object = ..., grading_group: builtins.object = ..., degree_of_differential: builtins.int = ..., degree: builtins.int = ..., check: builtins.bool = ...) -> _SageObject: ...

class Chain_class:
    def __init__(self, parent: builtins.object, vectors: builtins.object, check: builtins.bool = ...) -> None: ...
    def vector(self, degree: builtins.int) -> _SageObject: ...
    def is_cycle(self) -> builtins.bool: ...
    def is_boundary(self) -> builtins.bool: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...

class ChainComplex_class:
    def __init__(self, grading_group: builtins.object, degree_of_differential: builtins.object, base_ring: builtins.object, differentials: builtins.object) -> None: ...
    Element: _SageObject
    def random_element(self) -> _SageObject: ...
    def rank(self, degree: builtins.int, ring: builtins.object = ...) -> _SageObject: ...
    def grading_group(self) -> _SageObject: ...
    def nonzero_degrees(self) -> _SageObject: ...
    def ordered_degrees(self, start: builtins.int = ..., exclude_first: builtins.bool = ...) -> _SageObject: ...
    def degree_of_differential(self) -> _SageObject: ...
    def differential(self, dim: builtins.object = ...) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def free_module_rank(self, degree: builtins.int) -> _SageObject: ...
    def free_module(self, degree: builtins.int = ...) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def homology(self, deg: builtins.object = ..., base_ring: builtins.object = ..., generators: builtins.bool = ..., verbose: builtins.bool = ..., algorithm: builtins.str = ...) -> _SageObject: ...
    def betti(self, deg: builtins.object = ..., base_ring: builtins.object = ...) -> _SageObject: ...
    def torsion_list(self, max_prime: builtins.object, min_prime: builtins.int = ...) -> _SageObject: ...
    def shift(self, n: builtins.int = ...) -> _SageObject: ...
    def cartesian_product(self, *factors: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def tensor(self, *factors: builtins.object, **kwds: builtins.object) -> _SageObject: ...
