from sage.categories.morphism import Morphism
from sage.misc.classcall_metaclass import ClasscallMetaclass
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject

class FreeResolution(SageObject, metaclass=ClasscallMetaclass):
    def __init__(self, module: object, name: str = "S", **kwds: object) -> None: ...
    def differential(self, i: int) -> Morphism: ...
    def target(self) -> Parent: ...

class FiniteFreeResolution(FreeResolution): ...

class FiniteFreeResolution_free_module(FiniteFreeResolution):
    def __init__(self, module: object, *args: object, **kwds: object) -> None: ...
