# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class HochschildComplex:
    def __init__(self, A: builtins.object, M: builtins.int) -> None: ...
    def algebra(self) -> _SageObject: ...
    def coefficients(self) -> _SageObject: ...
    def module(self, d: builtins.object) -> _SageObject: ...
    def trivial_module(self) -> _SageObject: ...
    def boundary(self, d: builtins.object) -> _SageObject: ...
    differential: _SageObject
    def coboundary(self, d: builtins.object) -> _SageObject: ...
    def homology(self, d: builtins.object) -> _SageObject: ...
    def cohomology(self, d: builtins.object) -> _SageObject: ...
    class Element:
        def __init__(self, parent: builtins.object, vectors: builtins.object) -> None: ...
        def vector(self, degree: builtins.int) -> _SageObject: ...
