# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class InducedHomologyMorphism:
    def __init__(self, map: builtins.object, base_ring: builtins.object = ..., cohomology: builtins.bool = ...) -> None: ...
    def base_ring(self) -> _SageObject: ...
    def to_matrix(self, deg: builtins.object = ...) -> _SageObject: ...
    def __call__(self, elt: builtins.object) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def is_identity(self) -> builtins.bool: ...
    def is_surjective(self) -> builtins.bool: ...
    def is_injective(self) -> builtins.bool: ...
