import builtins

class _SageObject: ...

class HomologyVectorSpaceWithBasis:
    def __init__(
        self,
        base_ring: builtins.object,
        cell_complex: builtins.object,
        cohomology: builtins.bool = ...,
        category: builtins.object = ...,
    ) -> None: ...
    def basis(self, d: builtins.object = ...) -> _SageObject: ...
    def degree_on_basis(self, i: builtins.int) -> _SageObject: ...
    def contraction(self) -> _SageObject: ...
    def complex(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...

    class Element:
        def to_cycle(self) -> _SageObject: ...
        def eval(self, other: builtins.object) -> _SageObject: ...

class HomologyVectorSpaceWithBasis_mod2:
    def __init__(
        self,
        base_ring: builtins.object,
        cell_complex: builtins.object,
        category: builtins.object = ...,
    ) -> None: ...

    class Element: ...

class CohomologyRing:
    def __init__(
        self,
        base_ring: builtins.object,
        cell_complex: builtins.object,
        category: builtins.object = ...,
    ) -> None: ...
    def one(self) -> _SageObject: ...
    def product_on_basis(
        self, li: builtins.object, ri: builtins.object
    ) -> _SageObject: ...

    class Element:
        def cup_product(self, other: builtins.object) -> _SageObject: ...

class CohomologyRing_mod2:
    def __init__(
        self, base_ring: builtins.object, cell_complex: builtins.object
    ) -> None: ...

    class Element:
        def Sq(self, i: builtins.int) -> _SageObject: ...

    def steenrod_module_map(
        self,
        deg_domain: builtins.object,
        deg_codomain: builtins.object,
        side: builtins.str = ...,
    ) -> _SageObject: ...

def sum_indices(
    self, i_k_plus_one: builtins.object, S_k_plus_one: builtins.object
) -> _SageObject: ...
def is_GF2(self) -> bool: ...
