# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DrinfeldModularForms:
    Element: _SageObject
    @staticmethod
    def __classcall_private__(cls: builtins.object, base_ring: builtins.object, rank: builtins.int = ..., group: builtins.object = ..., has_type: builtins.bool = ..., names: builtins.object = ...) -> _SageObject: ...
    def __init__(self, base_ring: builtins.object, rank: builtins.int, group: builtins.object, has_type: builtins.object, names: builtins.object) -> None: ...
    def coefficient_form(self, i: builtins.int, a: builtins.object = ...) -> _SageObject: ...
    def coefficient_forms(self, a: builtins.object = ...) -> _SageObject: ...
    def gen(self, n: builtins.int) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def ngens(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def basis_of_weight(self, k: builtins.int) -> _SageObject: ...
    basis: _SageObject
    def polynomial_ring(self) -> _SageObject: ...
