# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AffineCurve:
    def __init__(self, A: builtins.object, X: builtins.object) -> None: ...
    def projective_closure(self, i: builtins.int = ..., PP: builtins.object = ...) -> _SageObject: ...

class AffinePlaneCurve:
    def __init__(self, A: builtins.object, f: builtins.object) -> None: ...
    def divisor_of_function(self, r: builtins.int) -> builtins.list[_SageObject]: ...
    def local_coordinates(self, pt: builtins.object, n: builtins.int) -> _SageObject: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def is_transverse(self, C: builtins.object, P: builtins.int) -> builtins.bool: ...
    def multiplicity(self, P: builtins.int) -> _SageObject: ...
    def tangents(self, P: builtins.int, factor: builtins.bool = ...) -> builtins.list[_SageObject]: ...
    def is_ordinary_singularity(self, P: builtins.int) -> builtins.bool: ...
    def rational_parameterization(self) -> _SageObject: ...

class AffineCurve_field:
    def __init__(self, A: builtins.object, X: builtins.object) -> None: ...
    def projection(self, indices: builtins.object, AS: builtins.object = ...) -> _SageObject: ...
    def plane_projection(self, AP: builtins.object = ...) -> _SageObject: ...
    def blowup(self, P: builtins.int = ...) -> _SageObject: ...
    def resolution_of_singularities(self, extend: builtins.bool = ...) -> _SageObject: ...
    def tangent_line(self, p: builtins.int) -> _SageObject: ...

class AffinePlaneCurve_field:
    def has_vertical_asymptote(self) -> builtins.bool: ...
    def is_vertical_line(self) -> builtins.bool: ...
    def fundamental_group(self, simplified: builtins.bool = ..., puiseux: builtins.bool = ...) -> _SageObject: ...
    def braid_monodromy(self) -> _SageObject: ...
    def riemann_surface(self, **kwargs: builtins.object) -> _SageObject: ...

class AffinePlaneCurve_finite_field:
    def riemann_roch_basis(self, D: builtins.object) -> builtins.list[_SageObject]: ...
    def rational_points(self, algorithm: builtins.str = ...) -> builtins.list[_SageObject]: ...

class IntegralAffineCurve:
    def function_field(self) -> _SageObject: ...
    def __call__(self, *args: builtins.object) -> _SageObject: ...
    def function(self, f: builtins.object) -> _SageObject: ...
    def coordinate_functions(self) -> _SageObject: ...
    def pull_from_function_field(self, f: builtins.object) -> _SageObject: ...
    def singular_closed_points(self) -> _SageObject: ...
    def place_to_closed_point(self, place: builtins.object) -> _SageObject: ...
    def places_at_infinity(self) -> builtins.list[_SageObject]: ...
    def places_on(self, point: builtins.object) -> builtins.list[_SageObject]: ...
    def parametric_representation(self, place: builtins.object, name: builtins.str = ...) -> _SageObject: ...

class IntegralAffineCurve_finite_field:
    def places(self, degree: builtins.int = ...) -> _SageObject: ...
    def closed_points(self, degree: builtins.int = ...) -> builtins.list[_SageObject]: ...

class IntegralAffinePlaneCurve:
    ...

class IntegralAffinePlaneCurve_finite_field:
    ...
