import builtins
from collections.abc import (
    Hashable,
)

from sage.structure.element import Element

class _SageObject: ...

class PlaneCurveArrangementElement:
    def __init__(
        self,
        parent: builtins.object,
        curves: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __hash__(self) -> int: ...
    def ncurves(self) -> int: ...
    def curves(self) -> tuple[Element, ...]: ...
    def union(self, other: builtins.object) -> _SageObject: ...
    add_curves: _SageObject

    def deletion(self, curves: builtins.object) -> _SageObject: ...
    def change_ring(self, base_ring: builtins.object) -> _SageObject: ...
    def coordinate_ring(self) -> _SageObject: ...
    def defining_polynomials(self) -> tuple[Element, ...]: ...
    def defining_polynomial(self, simplified: builtins.bool = ...) -> _SageObject: ...
    def have_common_factors(self) -> bool: ...
    def reduce(
        self, clean: builtins.bool = ..., verbose: builtins.bool = ...
    ) -> _SageObject: ...

class AffinePlaneCurveArrangementElement:
    def __init__(
        self,
        parent: builtins.object,
        curves: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def fundamental_group(
        self,
        simplified: builtins.bool = ...,
        vertical: builtins.bool = ...,
        projective: builtins.bool = ...,
    ) -> _SageObject: ...
    def meridians(
        self, simplified: builtins.bool = ..., vertical: builtins.bool = ...
    ) -> dict[Hashable, Element]: ...
    def braid_monodromy(self, vertical: builtins.bool = ...) -> _SageObject: ...
    def strands(self) -> _SageObject: ...
    def vertical_strands(self) -> _SageObject: ...
    def vertical_lines_in_braid_monodromy(self) -> _SageObject: ...

class ProjectivePlaneCurveArrangementElement:
    def __init__(
        self,
        parent: builtins.object,
        curves: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def fundamental_group(self, simplified: builtins.bool = ...) -> _SageObject: ...
    def meridians(self, simplified: builtins.bool = ...) -> dict[Hashable, Element]: ...

class PlaneCurveArrangements:
    Element: _SageObject

    @staticmethod
    def __classcall__(
        cls: builtins.object,
        base: builtins.object,
        names: builtins.tuple[_SageObject, ...] = ...,
    ) -> _SageObject: ...
    def __init__(
        self, base_ring: builtins.object, names: builtins.tuple[_SageObject, ...] = ...
    ) -> None: ...
    def coordinate_ring(self) -> _SageObject: ...
    def change_ring(self, base_ring: builtins.object) -> _SageObject: ...
    def ambient_space(self) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...

class AffinePlaneCurveArrangements:
    Element: _SageObject

    def ambient_space(self) -> _SageObject: ...

class ProjectivePlaneCurveArrangements:
    Element: _SageObject

    def ambient_space(self) -> _SageObject: ...
