import builtins

class _SageObject: ...

class ProjectiveCurvePoint_field:
    def is_singular(self) -> bool: ...

class ProjectivePlaneCurvePoint_field:
    def multiplicity(self) -> _SageObject: ...
    def tangents(self) -> _SageObject: ...
    def is_ordinary_singularity(self) -> bool: ...
    def is_transverse(self, D: builtins.object) -> bool: ...

class ProjectivePlaneCurvePoint_finite_field: ...

class IntegralProjectiveCurvePoint:
    def closed_point(self) -> _SageObject: ...
    def places(self) -> _SageObject: ...
    def place(self) -> _SageObject: ...

class IntegralProjectiveCurvePoint_finite_field: ...
class IntegralProjectivePlaneCurvePoint: ...
class IntegralProjectivePlaneCurvePoint_finite_field: ...

class AffineCurvePoint_field:
    def is_singular(self) -> bool: ...

class AffinePlaneCurvePoint_field:
    def multiplicity(self) -> _SageObject: ...
    def tangents(self) -> _SageObject: ...
    def is_ordinary_singularity(self) -> bool: ...
    def is_transverse(self, D: builtins.object) -> bool: ...

class AffinePlaneCurvePoint_finite_field: ...

class IntegralAffineCurvePoint:
    def closed_point(self) -> _SageObject: ...
    def places(self) -> _SageObject: ...
    def place(self) -> _SageObject: ...

class IntegralAffineCurvePoint_finite_field: ...
class IntegralAffinePlaneCurvePoint: ...
class IntegralAffinePlaneCurvePoint_finite_field: ...
