# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class WeightedProjectiveCurve:
    def __init__(self, A: builtins.object, X: builtins.object, *kwargs: builtins.object) -> None: ...
    def projective_curve(self) -> _SageObject: ...
    def affine_patch(self, i: builtins.int, AA: builtins.object = ...) -> _SageObject: ...
    def riemann_surface(self, **kwargs: builtins.object) -> _SageObject: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
