# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def n_k_params(C: builtins.object, n_k: builtins.object) -> _SageObject: ...

def roth_ruckenstein_root_finder(p: builtins.int, maxd: builtins.object = ..., precision: builtins.int = ...) -> _SageObject: ...

def alekhnovich_root_finder(p: builtins.int, maxd: builtins.object = ..., precision: builtins.int = ...) -> _SageObject: ...

class GRSGuruswamiSudanDecoder:
    @staticmethod
    def parameters_given_tau(tau: builtins.object, C: builtins.object = ..., n_k: builtins.object = ...) -> _SageObject: ...
    @staticmethod
    def guruswami_sudan_decoding_radius(C: builtins.object = ..., n_k: builtins.object = ..., l: builtins.object = ..., s: builtins.object = ...) -> _SageObject: ...
    @staticmethod
    def gs_satisfactory(tau: builtins.object, s: builtins.object, l: builtins.object, C: builtins.object = ..., n_k: builtins.object = ...) -> _SageObject: ...
    def __init__(self, code: builtins.object, tau: builtins.object = ..., parameters: builtins.object = ..., interpolation_alg: builtins.object = ..., root_finder: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def interpolation_algorithm(self) -> _SageObject: ...
    def rootfinding_algorithm(self) -> _SageObject: ...
    def parameters(self) -> _SageObject: ...
    def multiplicity(self) -> _SageObject: ...
    def list_size(self) -> _SageObject: ...
    def decode_to_message(self, r: builtins.int) -> _SageObject: ...
    def decode_to_code(self, r: builtins.int) -> _SageObject: ...
    def decoding_radius(self) -> _SageObject: ...
