import builtins

class _SageObject: ...

def gs_interpolation_linalg(
    self, tau: builtins.object, parameters: builtins.object, wy: builtins.object
) -> _SageObject: ...
def lee_osullivan_module(
    self, parameters: builtins.object, wy: builtins.object
) -> _SageObject: ...
def gs_interpolation_lee_osullivan(
    self, tau: builtins.object, parameters: builtins.object, wy: builtins.object
) -> _SageObject: ...
