# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def polynomial_to_list(p: builtins.int, len: builtins.object) -> _SageObject: ...

def johnson_radius(n: builtins.int, d: builtins.object) -> _SageObject: ...

def ligt(x: builtins.object) -> _SageObject: ...

def gilt(x: builtins.object) -> _SageObject: ...

def solve_degree2_to_integer_range(a: builtins.object, b: builtins.object, c: builtins.object) -> _SageObject: ...
