from collections.abc import Callable

from sage.structure.sage_object import SageObject

class CalculusMethod(SageObject):
    def __init__(self, current: str | None = None, base_field_type: str = "real") -> None: ...
    def set(self, method: str) -> None: ...
    def current(self) -> str: ...
    def reset(self) -> None: ...
    def simplify(self, expression: str, method: str | None = None) -> str: ...
    def simplify_function(self, method: str | None = None) -> Callable[[str], str]: ...
    def set_simplify_function(
        self, simplifying_func: Callable[[str], str], method: str | None = None
    ) -> None: ...
