import builtins

class _SageObject: ...

def Minkowski(self=..., names: builtins.object = ...) -> _SageObject: ...
def Kerr(
    self=...,
    a: builtins.int = ...,
    coordinates: builtins.str = ...,
    names: builtins.object = ...,
) -> _SageObject: ...
def Torus(
    self=..., r: builtins.int = ..., names: builtins.object = ...
) -> _SageObject: ...
def RealProjectiveSpace(self=...) -> _SageObject: ...
