# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def Minkowski(positive_spacelike: builtins.bool = ..., names: builtins.object = ...) -> _SageObject: ...

def Kerr(m: builtins.int = ..., a: builtins.int = ..., coordinates: builtins.str = ..., names: builtins.object = ...) -> _SageObject: ...

def Torus(R: builtins.int = ..., r: builtins.int = ..., names: builtins.object = ...) -> _SageObject: ...

def RealProjectiveSpace(dim: builtins.int = ...) -> _SageObject: ...
