from collections.abc import Sequence

from sage.structure.element import AlgebraElement, Expression, ModuleElementWithMutability
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject

class ChartFunction(AlgebraElement, ModuleElementWithMutability):
    def __call__(self, *coords: Expression | complex) -> Expression: ...
    def display(self) -> str: ...
    def expr(self, method: str | None = None) -> Expression: ...

class ChartFunctionRing(Parent):
    Element = ChartFunction
    element_class: type[ChartFunction]
    def zero(self) -> ChartFunction: ...
    def one(self) -> ChartFunction: ...

class MultiCoordFunction(SageObject):
    def __init__(self, chart: SageObject, expressions: Sequence[Expression | complex | str]) -> None: ...
    def __call__(self, *coords: Expression | complex) -> tuple[Expression, ...]: ...
    def display(self) -> str: ...
