# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LocalCoFrame:
    def __init__(self, frame: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ...) -> None: ...
    def at(self, point: builtins.object) -> _SageObject: ...
    def set_name(self, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., index_position: builtins.str = ..., include_domain: builtins.bool = ...) -> _SageObject: ...

class LocalFrame:
    @staticmethod
    def __classcall_private__(cls: builtins.object, section_module: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., symbol_dual: builtins.object = ..., latex_symbol_dual: builtins.object = ...) -> _SageObject: ...
    def __init__(self, section_module: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., symbol_dual: builtins.object = ..., latex_symbol_dual: builtins.object = ...) -> None: ...
    def domain(self) -> _SageObject: ...
    def base_space(self) -> _SageObject: ...
    def vector_bundle(self) -> _SageObject: ...
    def coframe(self) -> _SageObject: ...
    def new_frame(self, change_of_frame: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., symbol_dual: builtins.object = ..., latex_symbol_dual: builtins.object = ...) -> _SageObject: ...
    def restrict(self, subdomain: builtins.object) -> _SageObject: ...
    def at(self, point: builtins.object) -> _SageObject: ...
    def set_name(self, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., index_position: builtins.str = ..., include_domain: builtins.bool = ...) -> _SageObject: ...

class TrivializationCoFrame:
    def __init__(self, triv_frame: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ...) -> None: ...

class TrivializationFrame:
    def __init__(self, trivialization: builtins.object) -> None: ...
    def trivialization(self) -> _SageObject: ...
