from typing import TYPE_CHECKING, Optional, overload
from sage.rings.cc import CC
from sage.rings.real_mpfr import RR

from sage.manifolds.chart import Chart
from sage.manifolds.scalarfield import ScalarField

class TopologicalManifold:
    _dim: int
    def __init__(
        self,
        n: int,
        name: str,
        field: object,
        structure: object,
        base_manifold: TopologicalManifold | None = None,
        latex_name: str | None = None,
        start_index: int = 0,
        category: object = None,
        unique_tag: str | None = None,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def _an_element_(self) -> object: ...
    def __contains__(self, point: object) -> bool: ...
    def open_subset(
        self,
        name: str,
        latex_name: str | None = None,
        coord_def: dict[Chart, object] = ...,
        supersets: object = None,
    ) -> TopologicalManifold: ...
    def _init_open_subset(self, resu: TopologicalManifold, coord_def: dict[Chart, object]) -> None: ...
    def get_chart(self, coordinates: str, domain: str | None = None) -> Chart: ...
    def dimension(self) -> int: ...
    def dim(self) -> int: ...
    def base_field(self) -> object: ...
    def base_field_type(self) -> str: ...
    def start_index(self) -> int: ...
    def irange(self, start: int | None = None, end: int | None = None) -> object: ...
    def index_generator(self, nb_indices: int) -> object: ...
    def atlas(self) -> list[Chart]: ...
    def top_charts(self) -> list[Chart]: ...
    def default_chart(self) -> Chart: ...
    def set_default_chart(self, chart: Chart) -> None: ...
    def coord_change(self, chart1: Chart, chart2: Chart) -> object: ...
    def coord_changes(self) -> dict[object, object]: ...
    def is_manifestly_coordinate_domain(self) -> bool: ...
    def chart(
        self,
        coordinates: str = "",
        names: object = None,
        calc_method: str | None = None,
        coord_restrictions: object = None,
    ) -> Chart: ...
    def is_open(self) -> bool: ...
    def set_orientation(self, orientation: object) -> None: ...
    def orientation(self) -> list[Chart]: ...
    def has_orientation(self) -> bool: ...
    def _get_min_covering(self, object_list: list[object]) -> object: ...
    def vector_bundle(
        self, rank: int, name: str, field: str = "real", latex_name: str | None = None
    ) -> object: ...
    def scalar_field_algebra(self) -> object: ...
    def scalar_field(
        self,
        coord_expression: object = None,
        chart: Chart | None = None,
        name: str | None = None,
        latex_name: str | None = None,
    ) -> ScalarField: ...
    def constant_scalar_field(self, value: object, name: str | None = None, latex_name: str | None = None) -> ScalarField: ...
    def zero_scalar_field(self) -> ScalarField: ...
    def one_scalar_field(self) -> ScalarField: ...
