# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def grad(scalar: builtins.object) -> _SageObject: ...

def div(tensor: builtins.object) -> _SageObject: ...

def curl(vector: builtins.object) -> _SageObject: ...

def laplacian(field: builtins.object) -> _SageObject: ...

def dalembertian(field: builtins.object) -> _SageObject: ...
