from typing import Protocol

from sage.structure.parent import Parent

class _SubsetPoint(Protocol):
    def parent(self) -> Parent: ...

class ManifoldSubset(Parent):
    def _an_element_(self) -> _SubsetPoint: ...
    def __contains__(self, point: _SubsetPoint) -> bool: ...
    def is_open(self) -> bool: ...
