# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class TopologicalSubmanifold:
    def __init__(self, n: builtins.int, name: builtins.str, field: builtins.object, structure: builtins.object, ambient: builtins.object = ..., base_manifold: builtins.object = ..., latex_name: builtins.str = ..., start_index: builtins.int = ..., category: builtins.object = ..., unique_tag: builtins.object = ...) -> None: ...
    def open_subset(self, name: builtins.str, latex_name: builtins.str = ..., coord_def: builtins.dict[_SageObject, _SageObject] = ..., supersets: builtins.object = ...) -> _SageObject: ...
    def set_immersion(self, phi: builtins.object, inverse: builtins.object = ..., var: builtins.object = ..., t_inverse: builtins.object = ...) -> _SageObject: ...
    def declare_embedding(self) -> _SageObject: ...
    def set_embedding(self, phi: builtins.object, inverse: builtins.object = ..., var: builtins.object = ..., t_inverse: builtins.object = ...) -> _SageObject: ...
    def adapted_chart(self, postscript: builtins.object = ..., latex_postscript: builtins.object = ...) -> _SageObject: ...
    def plot(self, param: builtins.object, u: builtins.object, v: builtins.object, chart1: builtins.object = ..., chart2: builtins.object = ..., **kwargs: builtins.object) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def immersion(self) -> _SageObject: ...
    def embedding(self) -> _SageObject: ...
    def as_subset(self) -> _SageObject: ...
