# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Trivialization:
    def __init__(self, vector_bundle: builtins.object, name: builtins.str, domain: builtins.object, latex_name: builtins.str = ...) -> None: ...
    def base_space(self) -> _SageObject: ...
    def transition_map(self, other: builtins.object, transf: builtins.object, compute_inverse: builtins.bool = ...) -> _SageObject: ...
    def vector_bundle(self) -> _SageObject: ...
    def domain(self) -> _SageObject: ...
    def frame(self) -> _SageObject: ...
    def coframe(self) -> _SageObject: ...

class TransitionMap:
    def __init__(self, triv1: builtins.object, triv2: builtins.object, transf: builtins.object, compute_inverse: builtins.bool = ...) -> None: ...
    def automorphism(self) -> _SageObject: ...
    def inverse(self) -> _SageObject: ...
    def det(self) -> _SageObject: ...
    def matrix(self) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
