import builtins
from collections.abc import (
    Iterator as _Iterator,
)
from typing import Self

class _SageObject: ...

class CoxeterGroup:
    @staticmethod
    def __classcall__(
        cls: builtins.object,
        cartan_type: builtins.object,
        *args: builtins.object,
        **options: builtins.object,
    ) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cartan_type(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def bruhat_interval(
        self, u: builtins.object, v: builtins.object
    ) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def simple_reflections(self) -> _SageObject: ...
    gens: _SageObject

    def from_reduced_word(self, w: builtins.object) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def is_finite(self) -> bool: ...
    def length(self, x: builtins.object) -> _SageObject: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def root_system(self) -> _SageObject: ...
    def kazhdan_lusztig_polynomial(
        self,
        u: builtins.object,
        v: builtins.object,
        constant_term_one: builtins.bool = ...,
    ) -> _SageObject: ...
    def parabolic_kazhdan_lusztig_polynomial(
        self,
        u: builtins.object,
        v: builtins.object,
        J: builtins.int,
        constant_term_one: builtins.bool = ...,
    ) -> _SageObject: ...

    class Element:
        wrapped_class: _SageObject

        def __init__(self, parent: builtins.object, x: builtins.object) -> None: ...
        def __iter__(self) -> _Iterator[_SageObject]: ...
        def coatoms(self) -> builtins.list[_SageObject]: ...
        def reduced_word(self) -> builtins.list[_SageObject]: ...
        def __invert__(self) -> Self: ...
        inverse: _SageObject

        def __getitem__(self, i: builtins.int) -> _SageObject: ...
        def __len__(self) -> builtins.int: ...
        length: _SageObject

        def bruhat_le(self, v: builtins.object) -> builtins.bool: ...
        def poincare_polynomial(self) -> _SageObject: ...
        def has_right_descent(self, i: builtins.int) -> builtins.bool: ...
        def has_left_descent(self, i: builtins.int) -> builtins.bool: ...
        def action(self, v: builtins.object) -> _SageObject: ...
        def action_on_rational_function(self, f: builtins.object) -> _SageObject: ...
