# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class String:
    def __init__(self, s: builtins.object = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...

class Type:
    def __init__(self, s: builtins.object) -> None: ...
    def name(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...

class CoxGroup:
    def __cinit__(self, cartan_type: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __dealloc__(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def bruhat_interval(self, w: builtins.object, v: builtins.object) -> _SageObject: ...
    def orderings(self) -> _SageObject: ...
    def type(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def order(self) -> _SageObject: ...
    def is_finite(self) -> builtins.bool: ...
    def full_context(self) -> _SageObject: ...
    def long_element(self) -> _SageObject: ...
    def __call__(self, w: builtins.object) -> _SageObject: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def coxeter_graph(self) -> _SageObject: ...

class CoxGroupElement:
    def __init__(self, group: builtins.object, w: builtins.object, normal_form: builtins.object = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __invert__(self) -> Self: ...
    def parent_group(self) -> _SageObject: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
    def left_descents(self) -> _SageObject: ...
    def right_descents(self) -> _SageObject: ...
    def bruhat_le(self, w: builtins.object) -> _SageObject: ...
    def is_two_sided_descent(self, s: builtins.object) -> builtins.bool: ...
    def coatoms(self) -> _SageObject: ...
    def normal_form(self) -> _SageObject: ...
    def reduced(self) -> _SageObject: ...
    def __mul__(self, y: builtins.object) -> Self: ...
    def poincare_polynomial(self) -> _SageObject: ...
    def kazhdan_lusztig_polynomial(self, v: builtins.object) -> _SageObject: ...
    def mu_coefficient(self, v: builtins.object) -> _SageObject: ...

def LFlags_to_list(parent: builtins.object, f: builtins.object) -> _SageObject: ...

class CoxGroupIterator:
    def __init__(self, group: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...

CoxGroup_cache: _SageObject
def get_CoxGroup(cartan_type: builtins.object) -> _SageObject: ...
