# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def sage_vector_to_poly(v: builtins.object, r: builtins.object) -> _SageObject: ...

class RingWrap:
    def __dealloc__(self) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def var_names(self) -> _SageObject: ...
    def npars(self) -> _SageObject: ...
    def ordering_string(self) -> _SageObject: ...
    def par_names(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def is_commutative(self) -> builtins.bool: ...

class Resolution:
    def __init__(self, base_ring: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...

def new_leftv(data: builtins.object, res_type: builtins.object) -> _SageObject: ...

def free_leftv(args: builtins.object, r: builtins.object = ...) -> _SageObject: ...

def is_sage_wrapper_for_singular_ring(ring: builtins.object) -> builtins.bool: ...

def new_sage_polynomial(ring: builtins.object, p: builtins.object) -> _SageObject: ...

def is_singular_poly_wrapper(p: builtins.object) -> builtins.bool: ...

def all_singular_poly_wrapper(s: builtins.object) -> _SageObject: ...

def access_singular_poly(p: builtins.object) -> _SageObject: ...

def access_singular_ring(r: builtins.object) -> _SageObject: ...

def copy_sage_polynomial_into_singular_poly(p: builtins.object) -> _SageObject: ...

def all_vectors(s: builtins.object) -> _SageObject: ...

class Converter:
    def __init__(self, args: builtins.object, ring: builtins.object, attributes: builtins.object = ...) -> None: ...
    def ring(self) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def pop_front(self) -> _SageObject: ...
    def to_sage_matrix(self, mat: builtins.object) -> _SageObject: ...
    def to_sage_vector_destructive(self, p: builtins.object, free_module: builtins.object = ...) -> _SageObject: ...
    def to_sage_module_element_sequence_destructive(self, i: builtins.object) -> _SageObject: ...
    def to_sage_integer_matrix(self, mat: builtins.object) -> _SageObject: ...
    def append_polynomial(self, p: builtins.object) -> _SageObject: ...
    def append_ideal(self, i: builtins.object) -> _SageObject: ...
    def append_module(self, m: builtins.object) -> _SageObject: ...
    def append_number(self, n: builtins.object) -> _SageObject: ...
    def append_ring(self, r: builtins.object) -> _SageObject: ...
    def append_matrix(self, mat: builtins.object) -> _SageObject: ...
    def append_int(self, n: builtins.object) -> _SageObject: ...
    def append_list(self, l: builtins.object) -> _SageObject: ...
    def append_intvec(self, a: builtins.object) -> _SageObject: ...
    def append_vector(self, v: builtins.object) -> _SageObject: ...
    def append_resolution(self, resolution: builtins.object) -> _SageObject: ...
    def append_intmat(self, a: builtins.object) -> _SageObject: ...
    def append_str(self, n: builtins.object) -> _SageObject: ...
    def to_python(self, to_convert: builtins.object) -> _SageObject: ...

class BaseCallHandler:
    def handle_call(self, argument_list: builtins.object, _ring: builtins.object = ...) -> _SageObject: ...
    def free_res(self) -> _SageObject: ...

class LibraryCallHandler:
    def __init__(self) -> None: ...
    def handle_call(self, argument_list: builtins.object, _ring: builtins.object = ...) -> _SageObject: ...
    def free_res(self) -> _SageObject: ...

arity_dict: _SageObject
class KernelCallHandler:
    def __init__(self, cmd_n: builtins.object, arity: builtins.object) -> None: ...
    def handle_call(self, argument_list: builtins.object, _ring: builtins.object = ...) -> _SageObject: ...
    def free_res(self) -> _SageObject: ...

class SingularFunction:
    def __init__(self, name: builtins.object) -> None: ...
    def get_call_handler(self) -> _SageObject: ...
    def function_exists(self) -> _SageObject: ...
    def __call__(self, *args: builtins.object, ring: builtins.object = ..., interruptible: builtins.object = ..., attributes: builtins.object = ...) -> _SageObject: ...

def call_function(self: builtins.object, args: builtins.object, R: builtins.object, signal_handler: builtins.object = ..., attributes: builtins.object = ...) -> _SageObject: ...

class SingularLibraryFunction:
    def __init__(self, name: builtins.object) -> None: ...
    def get_call_handler(self) -> _SageObject: ...
    def function_exists(self) -> _SageObject: ...

class SingularKernelFunction:
    def __init__(self, name: builtins.object) -> None: ...
    def get_call_handler(self) -> _SageObject: ...
    def function_exists(self) -> _SageObject: ...

def singular_function(name: builtins.object) -> _SageObject: ...

def lib(name: builtins.object) -> _SageObject: ...

def get_printlevel() -> _SageObject: ...

def set_printlevel(l: builtins.object) -> _SageObject: ...

def list_of_functions(packages: builtins.object = ...) -> _SageObject: ...

def new_RingWrap(r: builtins.object) -> _SageObject: ...
