# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GroebnerStrategy:
    def __cinit__(self, L: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def ideal(self) -> _SageObject: ...
    def ring(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def normal_form(self, p: builtins.object) -> _SageObject: ...

class NCGroebnerStrategy:
    def __init__(self, L: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def ideal(self) -> _SageObject: ...
    def ring(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def normal_form(self, p: builtins.object) -> _SageObject: ...

def unpickle_NCGroebnerStrategy0(I: builtins.object) -> _SageObject: ...

def unpickle_GroebnerStrategy0(I: builtins.object) -> _SageObject: ...
