# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LibSingularOptions_abstract:
    def __init__(self, **kwds: builtins.object) -> None: ...
    def __getitem__(self, name: builtins.object) -> _SageObject: ...
    def __setitem__(self, name: builtins.object, value: builtins.object) -> None: ...
    def __int__(self) -> builtins.int: ...
    def save(self) -> _SageObject: ...
    def load(self, value: builtins.object = ...) -> _SageObject: ...

class LibSingularOptions:
    def __init__(self, **kwds: builtins.object) -> None: ...
    def reset_default(self) -> _SageObject: ...

class LibSingularVerboseOptions:
    def __init__(self, **kwds: builtins.object) -> None: ...
    def reset_default(self) -> _SageObject: ...

class LibSingularOptionsContext:
    def __init__(self, opt: builtins.object, **kwds: builtins.object) -> None: ...
    def __enter__(self) -> Self: ...
    def __call__(self, **kwds: builtins.object) -> _SageObject: ...
    def __exit__(self, typ: builtins.object, value: builtins.object, tb: builtins.object) -> builtins.bool | None: ...

opt: _SageObject
opt_verb: _SageObject
opt_ctx: _SageObject
opt_verb_ctx: _SageObject
