# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def si2sa_QQ(n: builtins.object, nn: builtins.object, _ring: builtins.object) -> _SageObject: ...

def si2sa_ZZ(n: builtins.object, _ring: builtins.object) -> _SageObject: ...

def si2sa_GFqGivaro(n: builtins.object, _ring: builtins.object, cache: builtins.object) -> _SageObject: ...

def si2sa_GFqNTLGF2E(n: builtins.object, _ring: builtins.object, cache: builtins.object) -> _SageObject: ...

def si2sa_GFq_generic(n: builtins.object, _ring: builtins.object, base: builtins.object) -> _SageObject: ...

def si2sa_transext_QQ(n: builtins.object, _ring: builtins.object, base: builtins.object) -> _SageObject: ...

def si2sa_transext_FF(n: builtins.object, _ring: builtins.object, base: builtins.object) -> _SageObject: ...

def si2sa_NF(n: builtins.object, _ring: builtins.object, base: builtins.object) -> _SageObject: ...

def si2sa_ZZmod(n: builtins.object, _ring: builtins.object, base: builtins.object) -> _SageObject: ...

def singular_monomial_exponents(p: builtins.object, r: builtins.object) -> _SageObject: ...

def si2sa_resolution(res: builtins.object) -> _SageObject: ...

def si2sa_resolution_graded(res: builtins.object, degrees: builtins.object) -> _SageObject: ...

def sa2si_QQ(r: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_GFqGivaro(quo: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_GFqNTLGF2E(elem: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_GFq_generic(elem: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_transext_QQ(elem: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_transext_FF(elem: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_NF(elem: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_ZZ(d: builtins.object, _ring: builtins.object) -> _SageObject: ...

def sa2si_ZZmod(d: builtins.object, _ring: builtins.object) -> _SageObject: ...

def si2sa(n: builtins.object, _ring: builtins.object, base: builtins.object) -> _SageObject: ...

def sa2si(elem: builtins.object, _ring: builtins.object) -> _SageObject: ...

def si2sa_intvec(v: builtins.object) -> _SageObject: ...

def si2sa_bigintvec(v: builtins.object) -> _SageObject: ...

def overflow_check(e: builtins.object, _ring: builtins.object) -> _SageObject: ...

def init_libsingular() -> _SageObject: ...

saved_PATH: _SageObject
def libsingular_error_callback(s: builtins.object) -> _SageObject: ...

def start_catch_error() -> _SageObject: ...

def check_error() -> _SageObject: ...

def get_resource(id: builtins.object) -> _SageObject: ...
