import builtins

from sage.structure.element import Element

class _SageObject: ...

def ToricDivisor(
    self,
    arg: builtins.object = ...,
    ring: builtins.object = ...,
    check: builtins.bool = ...,
    reduce: builtins.bool = ...,
) -> _SageObject: ...

class ToricDivisor_generic:
    def __init__(
        self,
        v: builtins.object,
        parent: builtins.object,
        check: builtins.bool = ...,
        reduce: builtins.bool = ...,
    ) -> None: ...
    def coefficient(self, x: builtins.object) -> _SageObject: ...
    def function_value(self, point: builtins.object) -> _SageObject: ...
    def m(self, cone: builtins.object) -> _SageObject: ...
    def is_Weil(self) -> bool: ...
    def is_QQ_Weil(self) -> bool: ...
    def is_Cartier(self) -> bool: ...
    def is_QQ_Cartier(self) -> bool: ...
    def is_integral(self) -> bool: ...
    def move_away_from(self, cone: builtins.object) -> _SageObject: ...
    def cohomology_class(self) -> _SageObject: ...
    def Chern_character(self) -> _SageObject: ...
    ch: _SageObject

    def divisor_class(self) -> _SageObject: ...
    def Chow_cycle(self, ring: builtins.object = ...) -> _SageObject: ...
    def is_ample(self) -> bool: ...
    def is_nef(self) -> bool: ...
    def polyhedron(self) -> _SageObject: ...
    def sections(self) -> _SageObject: ...
    def sections_monomials(self) -> _SageObject: ...
    def monomial(self, point: builtins.object) -> _SageObject: ...
    def Kodaira_map(self, names: builtins.str = ...) -> _SageObject: ...
    def cohomology(
        self,
        weight: builtins.object = ...,
        deg: builtins.object = ...,
        dim: builtins.bool = ...,
    ) -> _SageObject: ...
    def cohomology_support(self) -> _SageObject: ...

class ToricDivisorGroup:
    def __init__(
        self, toric_variety: builtins.object, base_ring: builtins.object
    ) -> None: ...
    def ngens(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def base_extend(self, R: builtins.int) -> _SageObject: ...
    Element: _SageObject

class ToricRationalDivisorClassGroup:
    def __init__(self, toric_variety: builtins.object) -> None: ...
    Element: _SageObject

class ToricRationalDivisorClassGroup_basis_lattice:
    def __init__(self, group: builtins.object) -> None: ...
    Element: _SageObject
