# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ToricIdeal:
    def __init__(self, A: builtins.object, names: builtins.str = ..., base_ring: builtins.object = ..., polynomial_ring: builtins.object = ..., algorithm: builtins.str = ...) -> None: ...
    def A(self) -> _SageObject: ...
    def ker(self) -> _SageObject: ...
    def nvariables(self) -> _SageObject: ...
