# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class InfinitePointEnumerator:
    def __init__(self, fan: builtins.object, ring: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class NaiveFinitePointEnumerator:
    def __init__(self, fan: builtins.object, ring: builtins.object) -> None: ...
    def rays(self) -> _SageObject: ...
    def units(self) -> _SageObject: ...
    def roots(self, n: builtins.int) -> _SageObject: ...
    def rescalings(self) -> _SageObject: ...
    def orbit(self, point: builtins.object) -> _SageObject: ...
    def cone_iter(self) -> _SageObject: ...
    def coordinate_iter(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class FiniteFieldPointEnumerator:
    def multiplicative_generator(self) -> _SageObject: ...
    def multiplicative_group_order(self) -> _SageObject: ...
    def root_generator(self, n: builtins.int) -> _SageObject: ...
    def log(self, z: builtins.object) -> _SageObject: ...
    def exp(self, powers: builtins.object) -> _SageObject: ...
    def rescaling_log_generators(self) -> _SageObject: ...
    def cone_points_iter(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...

class NaiveSubschemePointEnumerator:
    def __init__(self, polynomials: builtins.object, ambient: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class FiniteFieldSubschemePointEnumerator:
    def inhomogeneous_equations(self, ring: builtins.object, nonzero_coordinates: builtins.object, cokernel: builtins.object) -> _SageObject: ...
    def solutions_serial(self, inhomogeneous_equations: builtins.object, log_range: builtins.object) -> _SageObject: ...
    def solutions(self, inhomogeneous_equations: builtins.object, log_range: builtins.object) -> _SageObject: ...
    def homogeneous_coordinates(self, log_t: builtins.object, nonzero_coordinates: builtins.object, cokernel: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...
