import builtins

from sage.structure.element import Element

class _SageObject: ...

DEFAULT_PREFIX: _SageObject

def ToricVariety(
    self,
    coordinate_names: builtins.object = ...,
    names: builtins.object = ...,
    coordinate_indices: builtins.object = ...,
    base_ring: builtins.object = ...,
    base_field: builtins.object = ...,
) -> _SageObject: ...
def AffineToricVariety(
    self, *args: builtins.object, **kwds: builtins.object
) -> _SageObject: ...

class ToricVariety_field:
    def __init__(
        self,
        fan: builtins.object,
        coordinate_names: builtins.object,
        coordinate_indices: builtins.object,
        base_field: builtins.object,
    ) -> None: ...
    def __eq__(self, right: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def affine_patch(self, i: builtins.int) -> _SageObject: ...
    def change_ring(self, F: builtins.object) -> _SageObject: ...
    def coordinate_ring(self) -> _SageObject: ...
    def embedding_morphism(self) -> _SageObject: ...
    def fan(
        self, dim: builtins.object = ..., codim: builtins.object = ...
    ) -> _SageObject: ...
    def inject_coefficients(
        self, scope: builtins.object = ..., verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def dimension_singularities(self) -> _SageObject: ...
    def is_homogeneous(self, polynomial: builtins.object) -> bool: ...
    def is_isomorphic(self, another: builtins.object) -> bool: ...
    def is_affine(self) -> bool: ...
    def is_complete(self) -> bool: ...
    def is_orbifold(self) -> bool: ...
    def is_smooth(self) -> bool: ...
    def Kaehler_cone(self) -> _SageObject: ...
    def Mori_cone(self) -> _SageObject: ...
    def plot(self, **options: builtins.object) -> _SageObject: ...
    def rational_class_group(self) -> _SageObject: ...
    def Chow_group(self, base_ring: builtins.object = ...) -> _SageObject: ...
    def cartesian_product(
        self,
        other: builtins.object,
        coordinate_names: builtins.object = ...,
        coordinate_indices: builtins.object = ...,
    ) -> _SageObject: ...
    def resolve(self, **kwds: builtins.object) -> _SageObject: ...
    def resolve_to_orbifold(self, **kwds: builtins.object) -> _SageObject: ...
    def subscheme(self, polynomials: builtins.object) -> _SageObject: ...
    def Stanley_Reisner_ideal(self) -> _SageObject: ...
    def linear_equivalence_ideal(self) -> _SageObject: ...
    def cohomology_ring(self) -> _SageObject: ...
    def cohomology_basis(self, d: builtins.object = ...) -> _SageObject: ...
    def volume_class(self) -> _SageObject: ...
    def integrate(self, cohomology_class: builtins.object) -> _SageObject: ...
    @property
    def sheaves(self) -> _SageObject: ...
    def Chern_class(self, deg: builtins.object = ...) -> _SageObject: ...
    def Chern_character(self, deg: builtins.object = ...) -> _SageObject: ...
    def Todd_class(self, deg: builtins.object = ...) -> _SageObject: ...
    c: _SageObject
    ch: _SageObject
    Td: _SageObject

    def Euler_number(self) -> _SageObject: ...
    chi: _SageObject

    def K(self) -> _SageObject: ...
    def divisor(
        self,
        arg: builtins.object,
        base_ring: builtins.object = ...,
        check: builtins.bool = ...,
        reduce: builtins.bool = ...,
    ) -> _SageObject: ...
    def divisor_group(self, base_ring: builtins.object = ...) -> _SageObject: ...
    def toric_divisor_group(self, base_ring: builtins.object = ...) -> _SageObject: ...
    def Spec(
        self, cone: builtins.object = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def affine_algebraic_patch(
        self, cone: builtins.object = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def orbit_closure(self, cone: builtins.object) -> _SageObject: ...
    def count_points(self) -> _SageObject: ...
    def Demazure_roots(self) -> _SageObject: ...
    def Aut_dimension(self) -> _SageObject: ...

def normalize_names(
    self=...,
    ngens: builtins.object = ...,
    prefix: builtins.str = ...,
    indices: builtins.object = ...,
    return_prefix: builtins.bool = ...,
) -> _SageObject: ...

class CohomologyRing:
    def __init__(self, variety: builtins.object) -> None: ...
    def __call__(
        self, x: builtins.object, coerce: builtins.bool = ...
    ) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...

class CohomologyClass:
    def __init__(
        self, cohomology_ring: builtins.object, representative: builtins.object
    ) -> None: ...
    def deg(self) -> _SageObject: ...
    def part_of_degree(self, d: builtins.object) -> _SageObject: ...
    def exp(self) -> _SageObject: ...
