# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def WeierstrassMap(polynomial: builtins.object, variables: builtins.object = ...) -> _SageObject: ...

def WeierstrassMap_P2(polynomial: builtins.object, variables: builtins.object = ...) -> _SageObject: ...

def WeierstrassMap_P1xP1(polynomial: builtins.object, variables: builtins.object = ...) -> _SageObject: ...

def WeierstrassMap_P2_112(polynomial: builtins.object, variables: builtins.object = ...) -> _SageObject: ...
