import builtins

class _SageObject: ...

def Gamma_constructor(self) -> _SageObject: ...

class Gamma_class:
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def index(self) -> _SageObject: ...
    def ncusps(self) -> _SageObject: ...
    def nirregcusps(self) -> _SageObject: ...
    def reduce_cusp(self, c: builtins.object) -> _SageObject: ...
    def are_equivalent(
        self, x: builtins.object, y: builtins.object, trans: builtins.bool = ...
    ) -> _SageObject: ...
    def nu3(self) -> _SageObject: ...
    def image_mod_n(self) -> _SageObject: ...
