from collections.abc import Iterator
from sage.modular.arithgroup.arithgroup_generic import ArithmeticSubgroup
from sage.modular.arithgroup.arithgroup_element import ArithmeticSubgroupElement
from sage.modular.arithgroup.congroup_gammaH import GammaH_class

class Gamma0_class:
    def __init__(self, level: int) -> None: ...
    def __reduce__(self) -> tuple[object, ...]: ...
    def divisor_subgroups(self) -> list[Gamma0_class]: ...
    def is_even(self) -> bool: ...
    def is_subgroup(self, right: ArithmeticSubgroup) -> bool: ...
    def coset_reps(self) -> Iterator[ArithmeticSubgroupElement]: ...
    def generators(self, algorithm: str = 'farey') -> list[ArithmeticSubgroupElement]: ...
    def gamma_h_subgroups(self) -> list[GammaH_class]: ...
    def ncusps(self) -> int: ...
    def nu2(self) -> int: ...
    def nu3(self) -> int: ...
    def index(self) -> int: ...
    def dimension_new_cusp_forms(self, k: int = 2, p: int = 0) -> int: ...

def Gamma0_constructor(N: int) -> Gamma0_class: ...
