# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def Gamma_constructor(N: builtins.int) -> _SageObject: ...

class Gamma_class:
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def index(self) -> _SageObject: ...
    def ncusps(self) -> _SageObject: ...
    def nirregcusps(self) -> _SageObject: ...
    def reduce_cusp(self, c: builtins.object) -> _SageObject: ...
    def are_equivalent(self, x: builtins.object, y: builtins.object, trans: builtins.bool = ...) -> _SageObject: ...
    def nu3(self) -> _SageObject: ...
    def image_mod_n(self) -> _SageObject: ...
