from collections.abc import Iterator

from sage.groups.group import Group
from sage.matrix.matrix import Matrix
from sage.modular.arithgroup.arithgroup_element import ArithmeticSubgroupElement
from sage.modular.arithgroup.arithgroup_generic import ArithmeticSubgroup
from sage.modular.arithgroup.congroup_generic import CongruenceSubgroupBase
from sage.modular.cusps import Cusp
from sage.modular.dirichlet import DirichletCharacter
from sage.structure.element import Element

class GammaH_class(CongruenceSubgroupBase):
    def __init__(
        self, level: int, H: list[int], Hlist: list[int] | None = None
    ) -> None: ...
    def restrict(self, M: int) -> GammaH_class: ...
    def extend(self, M: int) -> GammaH_class: ...
    def divisor_subgroups(self) -> list[Element]: ...
    def to_even_subgroup(self) -> GammaH_class: ...
    def is_even(self) -> bool: ...
    def generators(
        self, algorithm: str = "farey"
    ) -> list[ArithmeticSubgroupElement]: ...
    def reduce_cusp(self, c: object) -> Cusp: ...
    def gamma0_coset_reps(self) -> list[Element]: ...
    def coset_reps(self, G: ArithmeticSubgroup | None = ...) -> Iterator[Element]: ...
    def is_subgroup(self, other: ArithmeticSubgroup) -> bool: ...
    def index(self) -> int: ...
    def nu2(self) -> int: ...
    def nu3(self) -> int: ...
    def ncusps(self) -> int: ...
    def nregcusps(self) -> int: ...
    def nirregcusps(self) -> int: ...
    def dimension_cusp_forms(self, k: int = 2) -> int: ...
    def dimension_new_cusp_forms(
        self, k: int = 2, p: int = 0, **kwargs: object
    ) -> int: ...
    def image_mod_n(self) -> Group: ...
    def atkin_lehner_matrix(self, Q: int) -> Matrix: ...
    def characters_mod_H(
        self, sign: int | None = None, galois_orbits: bool = False
    ) -> list[DirichletCharacter]: ...

def GammaH_constructor(self, H: int | list[int]) -> CongruenceSubgroupBase: ...
def _normalize_H(self, level: int) -> list[Element]: ...
def _list_subgroup(self, gens: list[int]) -> list[Element]: ...
def _GammaH_coset_helper(self, H: list[int]) -> list[Element]: ...
def mumu(self) -> int: ...
