import builtins

from sage.structure.element import Element

class _SageObject: ...

class PathAlgebra:
    Element: _SageObject

    def __init__(
        self, k: builtins.int, P: builtins.int, order: builtins.str = ...
    ) -> None: ...
    def order_string(self) -> str: ...
    def gens(self) -> tuple[Element, ...]: ...
    def arrows(self) -> _SageObject: ...
    def idempotents(self) -> _SageObject: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def quiver(self) -> _SageObject: ...
    def semigroup(self) -> _SageObject: ...
    def degree_on_basis(self, x: builtins.object) -> _SageObject: ...
    def sum(self, iter_of_elements: builtins.object) -> _SageObject: ...
    def linear_combination(
        self,
        iter_of_elements_coeff: builtins.object,
        factor_on_left: builtins.bool = ...,
    ) -> _SageObject: ...
    def homogeneous_component(self, n: builtins.int) -> _SageObject: ...
    def homogeneous_components(self) -> _SageObject: ...
