import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class AuslanderReitenQuiver:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, quiver: builtins.object
    ) -> _SageObject: ...
    def __init__(self, quiver: builtins.object) -> None: ...

    class options:
        NAME: _SageObject
        module: _SageObject
        latex: _SageObject

    def quiver(self) -> _SageObject: ...
    def projectives(self) -> _SageObject: ...
    def simples(self) -> _SageObject: ...
    def injectives(self) -> _SageObject: ...
    def digraph_preprojectives(
        self, max_depth: builtins.object, with_translations: builtins.bool = ...
    ) -> _SageObject: ...
    def digraph_postinjectives(
        self, max_depth: builtins.object, with_translations: builtins.bool = ...
    ) -> _SageObject: ...
    def digraph(self, with_translations: builtins.bool = ...) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def dimension_vectors_of_level(self, k: builtins.int) -> _SageObject: ...

    class Element:
        def __init__(
            self,
            parent: builtins.object,
            vertex: builtins.object,
            level: builtins.object,
        ) -> None: ...
        def __hash__(self) -> builtins.int: ...
        def vertex(self) -> _SageObject: ...
        def level(self) -> _SageObject: ...
        def translation(self) -> _SageObject: ...
        def inverse_translation(self) -> _SageObject: ...
        def dimension_vector(self) -> _SageObject: ...

def detect_dynkin_quiver(self) -> _SageObject: ...
