# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class QuiverHomSpace:
    Element: _SageObject
    def __init__(self, domain: builtins.object, codomain: builtins.object, category: builtins.object = ...) -> None: ...
    def zero(self) -> _SageObject: ...
    def __call__(self, *data: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def natural_map(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def quiver(self) -> _SageObject: ...
    def domain(self) -> _SageObject: ...
    def codomain(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def coordinates(self, hom: builtins.object) -> _SageObject: ...
    def left_module(self, basis: builtins.bool = ...) -> _SageObject: ...
