# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class QuiverRepHom:
    def __init__(self, domain: builtins.object, codomain: builtins.object, data: builtins.dict[_SageObject, _SageObject] = ...) -> None: ...
    def __add__(left: builtins.object, right: builtins.object) -> Self: ...
    def __iadd__(self, other: builtins.object) -> Self: ...
    def __sub__(left: builtins.object, right: builtins.object) -> Self: ...
    def __isub__(self, other: builtins.object) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __bool__(self) -> builtins.bool: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def domain(self) -> _SageObject: ...
    def codomain(self) -> _SageObject: ...
    def get_matrix(self, vertex: builtins.object) -> _SageObject: ...
    def get_map(self, vertex: builtins.object) -> _SageObject: ...
    def quiver(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def is_injective(self) -> builtins.bool: ...
    def is_surjective(self) -> builtins.bool: ...
    def is_isomorphism(self) -> builtins.bool: ...
    def is_zero(self) -> builtins.bool: ...
    def is_endomorphism(self) -> builtins.bool: ...
    def rank(self) -> _SageObject: ...
    def kernel(self) -> _SageObject: ...
    def image(self) -> _SageObject: ...
    def cokernel(self) -> _SageObject: ...
    def linear_dual(self) -> _SageObject: ...
    def algebraic_dual(self) -> _SageObject: ...
    def direct_sum(self, maps: builtins.object, return_maps: builtins.bool = ..., pinch: builtins.object = ...) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def scalar_mult(self, scalar: builtins.object) -> _SageObject: ...
    def iscalar_mult(self, scalar: builtins.object) -> _SageObject: ...
