from sage.quadratic_forms.quadratic_form import QuadraticForm

def BezoutianQuadraticForm(f: object, g: object) -> QuadraticForm: ...
def HyperbolicPlane_quadratic_form(R: object, r: int = 1) -> QuadraticForm: ...
