from typing import overload, Literal
from sage.matrix.matrix import Matrix

@overload
def is_triangular_number(n: int, return_value: Literal[True]) -> tuple[bool, object]: ...
@overload
def is_triangular_number(n: int, return_value: Literal[False] = False) -> bool: ...

@overload
def extend_to_primitive(A_input: list[object]) -> list[object]: ...
@overload
def extend_to_primitive(A_input: Matrix) -> Matrix: ...

def least_quadratic_nonresidue(p: int) -> int: ...
