from sage.matrix.matrix import Matrix
from sage.modules.free_module_element import FreeModuleElement

def qfsolve(G: Matrix) -> object | int | Matrix: ...
def qfparam(G: Matrix, sol: tuple[object, ...]) -> FreeModuleElement: ...
def solve(self: object, c: int = 0) -> FreeModuleElement: ...
