import builtins

class _SageObject: ...

def find_primitive_p_divisible_vector__random(self, p: builtins.int) -> _SageObject: ...
def find_primitive_p_divisible_vector__next(
    self, p: builtins.int, v: builtins.object = ...
) -> _SageObject: ...
def find_p_neighbor_from_vec(
    self, p: builtins.int, y: builtins.object, return_matrix: builtins.bool = ...
) -> _SageObject: ...
def neighbor_iteration(
    self,
    p: builtins.int,
    mass: builtins.object = ...,
    max_classes: builtins.object = ...,
    algorithm: builtins.str = ...,
    max_neighbors: builtins.int = ...,
    verbose: builtins.bool = ...,
) -> _SageObject: ...
def orbits_lines_mod_p(self, p: builtins.int) -> _SageObject: ...
