from sage.matrix.matrix import Matrix
from sage.quadratic_forms.quadratic_form import QuadraticForm

def _rational_diagonal_form_and_transformation(
    self,
) -> tuple[QuadraticForm, Matrix]: ...
def anisotropic_primes(self) -> list[int]: ...
def compute_definiteness(self) -> str: ...
def compute_definiteness_string_by_determinants(
    self, *args: object, **kwargs: object
) -> str: ...
def hasse_invariant(self, prime: int) -> int: ...
def hasse_invariant__OMeara(self, prime: int) -> int: ...
def is_anisotropic(self, *args: object, **kwargs: object) -> bool: ...
def is_definite(self) -> bool: ...
def is_hyperbolic(self) -> bool: ...
def is_indefinite(self) -> bool: ...
def is_isotropic(self, *args: object, **kwargs: object) -> bool: ...
def is_negative_definite(self) -> bool: ...
def is_positive_definite(self) -> bool: ...
def rational_diagonal_form(self) -> QuadraticForm: ...
def signature(self) -> tuple[int, int]: ...
def signature_vector(self) -> tuple[int, int, int]: ...
