from collections.abc import Iterator, Sequence
from typing import Self, TypeVar
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_homspace import FreeModuleHomspace
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_double import RealDoubleElement
from sage.rings.complex_double import ComplexDoubleElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

import builtins

class _SageObject: ...

def disc(self: builtins.object) -> ElementConstructorInput: ...
def content(self: builtins.object) -> ElementConstructorInput: ...
def adjoint(self: builtins.object) -> ElementConstructorInput: ...
def antiadjoint(self: builtins.object) -> ElementConstructorInput: ...
def is_adjoint(self: builtins.object) -> builtins.bool: ...
def reciprocal(self: builtins.object) -> ElementConstructorInput: ...
def omega(self: builtins.object) -> ElementConstructorInput: ...
def delta(self: builtins.object) -> ElementConstructorInput: ...
def level__Tornaria(self: builtins.object) -> ElementConstructorInput: ...
def discrec(self: builtins.object) -> ElementConstructorInput: ...
def hasse_conductor(self: builtins.object) -> ElementConstructorInput: ...
def clifford_invariant(
    self: builtins.object, p: builtins.int
) -> ElementConstructorInput: ...
def clifford_conductor(self: builtins.object) -> ElementConstructorInput: ...
def basiclemma(self: builtins.object, M: builtins.int) -> ElementConstructorInput: ...
def basiclemmavec(
    self: builtins.object, M: builtins.int
) -> ElementConstructorInput: ...
def xi(self: builtins.object, p: builtins.int) -> ElementConstructorInput: ...
def xi_rec(self: builtins.object, p: builtins.int) -> ElementConstructorInput: ...
def lll(self: builtins.object) -> ElementConstructorInput: ...
def representation_number_list(
    self: builtins.object, B: builtins.object
) -> ElementConstructorInput: ...
def representation_vector_list(
    self: builtins.object, B: builtins.object, maxvectors: builtins.object = ...
) -> ElementConstructorInput: ...
def is_zero(
    self: builtins.object, v: builtins.object, p: builtins.int = ...
) -> builtins.bool: ...
def is_zero_nonsingular(
    self: builtins.object, v: builtins.object, p: builtins.int = ...
) -> builtins.bool: ...
def is_zero_singular(
    self: builtins.object, v: builtins.object, p: builtins.int = ...
) -> builtins.bool: ...
