def _rational_diagonal_form_and_transformation(self: object) -> tuple[object, object]: ...
def anisotropic_primes(self: object) -> list[int]: ...
def compute_definiteness(self: object) -> str: ...
def compute_definiteness_string_by_determinants(self: object, *args: object, **kwargs: object) -> str: ...
def hasse_invariant(self: object, prime: int) -> int: ...
def hasse_invariant__OMeara(self: object, prime: int) -> int: ...
def is_anisotropic(self: object, *args: object, **kwargs: object) -> bool: ...
def is_definite(self: object) -> bool: ...
def is_hyperbolic(self: object) -> bool: ...
def is_indefinite(self: object) -> bool: ...
def is_isotropic(self: object, *args: object, **kwargs: object) -> bool: ...
def is_negative_definite(self: object) -> bool: ...
def is_positive_definite(self: object) -> bool: ...
def rational_diagonal_form(self: object) -> object: ...
def signature(self: object) -> tuple[int, int]: ...
def signature_vector(self: object) -> object: ...
