def local_representation_conditions(self: object, *args: object, **kwargs: object) -> dict[object, object]: ...
def is_locally_universal_at_prime(self: object, prime: int) -> bool: ...
def is_locally_universal_at_all_primes(self: object) -> bool: ...
def is_locally_universal_at_all_places(self: object) -> bool: ...
def is_locally_represented_number_at_place(self: object, *args: object, **kwargs: object) -> bool: ...
def is_locally_represented_number(self: object, *args: object, **kwargs: object) -> bool: ...
