# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def find_primitive_p_divisible_vector__random(self: builtins.object, p: builtins.int) -> _SageObject: ...

def find_primitive_p_divisible_vector__next(self: builtins.object, p: builtins.int, v: builtins.object = ...) -> _SageObject: ...

def find_p_neighbor_from_vec(self: builtins.object, p: builtins.int, y: builtins.object, return_matrix: builtins.bool = ...) -> _SageObject: ...

def neighbor_iteration(seeds: builtins.object, p: builtins.int, mass: builtins.object = ..., max_classes: builtins.object = ..., algorithm: builtins.str = ..., max_neighbors: builtins.int = ..., verbose: builtins.bool = ...) -> _SageObject: ...

def orbits_lines_mod_p(self: builtins.object, p: builtins.int) -> _SageObject: ...
