from collections.abc import Iterator, Sequence
from typing import Self, TypeVar
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_homspace import FreeModuleHomspace
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_double import RealDoubleElement
from sage.rings.complex_double import ComplexDoubleElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

from sage.groups.matrix_gps.finitely_generated_gap import (
    FinitelyGeneratedMatrixGroup_gap,
)
from sage.matrix.matrix import Matrix
from sage.rings.polynomial.multi_polynomial import MPolynomial

class Vector: ...
class CommutativeRing: ...
class PermutationGroup: ...

def quadratic_form_from_invariants(
    F: ElementConstructorInput,
    rk: int,
    det: ElementConstructorInput,
    P: ElementConstructorInput,
    sminus: int,
) -> QuadraticForm: ...
def DiagonalQuadraticForm(R: Ring, diag: ElementConstructorInput) -> QuadraticForm: ...

class QuadraticForm:
    def __init__(
        self,
        R: Ring,
        n: int | Integer = None,
        entries: FreeModuleElement[_Scalar] | Sequence[_Scalar] = None,
        unsafe_initialization: bool = False,
        number_of_automorphisms: ElementConstructorInput = None,
        determinant: ElementConstructorInput = None,
    ) -> None: ...
    def list_external_initializations(self) -> list[str]: ...
    def _pari_init_(self) -> str: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __getitem__(
        self, ij: ElementConstructorInput
    ) -> FreeModuleElement[_Scalar] | _Scalar: ...
    def __setitem__(
        self, ij: ElementConstructorInput, coeff: ElementConstructorInput
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, right: ElementConstructorInput) -> bool: ...
    def __add__(self, right: QuadraticForm) -> QuadraticForm: ...
    def sum_by_coefficients_with(self, right: QuadraticForm) -> QuadraticForm: ...
    @overload
    def __call__(
        self, v: FreeModuleElement[_Scalar] | Sequence[_Scalar]
    ) -> QuadraticForm: ...
    @overload
    def __call__(
        self, v: FreeModuleElement[_Scalar] | Sequence[_Scalar]
    ) -> ElementConstructorInput: ...
    def _is_even_symmetric_matrix_(
        self, A: Matrix[_Scalar], R: Ring = None
    ) -> bool: ...
    def matrix(self) -> Matrix[_Scalar]: ...
    def Hessian_matrix(self) -> Matrix[_Scalar]: ...
    def Gram_matrix_rational(self) -> Matrix[_Scalar]: ...
    def Gram_matrix(self) -> Matrix[_Scalar]: ...
    def has_integral_Gram_matrix(self) -> bool: ...
    def gcd(self) -> ElementConstructorInput: ...
    def polynomial(self, names: str = "x") -> MPolynomial: ...
    @staticmethod
    def from_polynomial(poly: ElementConstructorInput) -> QuadraticForm: ...
    def is_primitive(self) -> bool: ...
    def primitive(self) -> QuadraticForm: ...
    def adjoint_primitive(self) -> QuadraticForm: ...
    def dim(self) -> int: ...
    def base_ring(self) -> CommutativeRing: ...
    def coefficients(self) -> tuple[_Scalar, ...]: ...
    def det(self) -> _Scalar: ...
    def Gram_det(self) -> ElementConstructorInput: ...
    def change_ring(self, R: Ring) -> QuadraticForm: ...
    def level(self) -> ElementConstructorInput: ...
    def bilinear_map(
        self,
        v: FreeModuleElement[_Scalar] | Sequence[_Scalar],
        w: FreeModuleElement[_Scalar] | Sequence[_Scalar],
    ) -> ElementConstructorInput: ...
    def find_entry_with_minimal_scale_at_prime(
        self, prime: int
    ) -> ElementConstructorInput: ...
    def local_normal_form(
        self,
        prime: int,
        *args: ElementConstructorInput,
        **kwargs: ElementConstructorInput,
    ) -> QuadraticForm: ...
    def jordan_blocks_by_scale_and_unimodular(
        self, prime: int
    ) -> ElementConstructorInput: ...
    def jordan_blocks_in_unimodular_list_by_scale_power(
        self, prime: int, *args: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def count_congruence_solutions(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def count_congruence_solutions__bad_type(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def count_congruence_solutions__bad_type_I(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def count_congruence_solutions__bad_type_II(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def count_congruence_solutions__good_type(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def count_congruence_solutions__zero_type(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def count_congruence_solutions_as_vector(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> Vector: ...
    def count_modp_solutions__by_Gauss_sum(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def local_bad_density_congruence(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_badI_density_congruence(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_badII_density_congruence(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_density_congruence(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_good_density_congruence(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_good_density_congruence_even(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_good_density_congruence_odd(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_primitive_density_congruence(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_zero_density_congruence(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def _rational_diagonal_form_and_transformation(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def anisotropic_primes(self) -> list[int]: ...
    def compute_definiteness(self) -> str: ...
    def compute_definiteness_string_by_determinants(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> str: ...
    def hasse_invariant(self, prime: int) -> int: ...
    def hasse_invariant__OMeara(self, prime: int) -> int: ...
    def is_anisotropic(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> bool: ...
    def is_definite(self) -> bool: ...
    def is_hyperbolic(self) -> bool: ...
    def is_indefinite(self) -> bool: ...
    def is_isotropic(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> bool: ...
    def is_negative_definite(self) -> bool: ...
    def is_positive_definite(self) -> bool: ...
    def rational_diagonal_form(self) -> QuadraticForm: ...
    def signature(self) -> tuple[int, int]: ...
    def signature_vector(self) -> tuple[int, int, int]: ...
    def add_symmetric(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def divide_variable(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def elementary_substitution(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def extract_variables(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def multiply_variable(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def scale_by_factor(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def swap_variables(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def local_density(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def local_primitive_density(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def adjoint(self) -> QuadraticForm: ...
    def antiadjoint(self) -> QuadraticForm: ...
    def basiclemma(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def basiclemmavec(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> Vector: ...
    def clifford_conductor(self) -> int: ...
    def clifford_invariant(self, prime: int) -> int: ...
    def content(self) -> ElementConstructorInput: ...
    def delta(self) -> ElementConstructorInput: ...
    def disc(self) -> ElementConstructorInput: ...
    def discrec(self) -> ElementConstructorInput: ...
    def hasse_conductor(self) -> int: ...
    def is_adjoint(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_zero_nonsingular(self) -> bool: ...
    def is_zero_singular(self) -> bool: ...
    def level__Tornaria(self) -> int: ...
    def lll(self) -> QuadraticForm: ...
    def omega(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def reciprocal(self) -> QuadraticForm: ...
    def representation_number_list(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> list[int]: ...
    def representation_vector_list(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> list[Vector]: ...
    def xi(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def xi_rec(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def theta_by_cholesky(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> MPolynomial: ...
    def theta_by_pari(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> MPolynomial: ...
    def theta_series(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> MPolynomial: ...
    def theta_series_degree_2(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> MPolynomial: ...
    def siegel_product(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def find_p_neighbor_from_vec(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def find_primitive_p_divisible_vector__next(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> Vector: ...
    def find_primitive_p_divisible_vector__random(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> Vector: ...
    def neighbor_iteration(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> list[QuadraticForm]: ...
    def orbits_lines_mod_p(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def minkowski_reduction(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def minkowski_reduction_for_4vars__SP(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def reduced_binary_form(self) -> QuadraticForm: ...
    def reduced_binary_form1(self) -> QuadraticForm: ...
    def reduced_ternary_form__Dickson(self) -> QuadraticForm: ...
    def global_genus_symbol(self) -> ElementConstructorInput: ...
    def local_genus_symbol(self, prime: int) -> ElementConstructorInput: ...
    def CS_genus_symbol_list(self) -> ElementConstructorInput: ...
    def shimura_mass__maximal(self) -> ElementConstructorInput: ...
    def GHY_mass__maximal(self) -> ElementConstructorInput: ...
    def mass__by_Siegel_densities(self) -> ElementConstructorInput: ...
    def Pall_mass_density_at_odd_prime(self, prime: int) -> ElementConstructorInput: ...
    def Watson_mass_at_2(self) -> ElementConstructorInput: ...
    def Kitaoka_mass_at_2(self) -> ElementConstructorInput: ...
    def mass_at_two_by_counting_mod_power(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def parity(self) -> int: ...
    def is_even(self) -> bool: ...
    def is_odd(self) -> bool: ...
    def conway_species_list_at_odd_prime(
        self, prime: int
    ) -> ElementConstructorInput: ...
    def conway_species_list_at_2(self) -> ElementConstructorInput: ...
    def conway_octane_of_this_unimodular_Jordan_block_at_2(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def conway_diagonal_factor(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def conway_cross_product_doubled_power(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> int: ...
    def conway_type_factor(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def conway_p_mass(self, prime: int) -> ElementConstructorInput: ...
    def conway_standard_p_mass(self, prime: int) -> ElementConstructorInput: ...
    def conway_standard_mass(self) -> ElementConstructorInput: ...
    def conway_mass(self) -> ElementConstructorInput: ...
    def local_representation_conditions(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def is_locally_universal_at_prime(self, prime: int) -> bool: ...
    def is_locally_universal_at_all_primes(self) -> bool: ...
    def is_locally_universal_at_all_places(self) -> bool: ...
    def is_locally_represented_number_at_place(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> bool: ...
    def is_locally_represented_number(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> bool: ...
    def cholesky_decomposition(self) -> ElementConstructorInput: ...
    def complementary_subform_to_vector(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> QuadraticForm: ...
    def split_local_cover(self) -> QuadraticForm: ...
    def vectors_by_length(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def basis_of_short_vectors(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> list[Vector]: ...
    def short_vector_list_up_to_length(
        self, len_bound: int | Integer, up_to_sign_flag: bool = ...
    ) -> ElementConstructorInput: ...
    def short_primitive_vector_list_up_to_length(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> list[tuple[Vector, int]]: ...
    def _compute_automorphisms(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> ElementConstructorInput: ...
    def automorphism_group(self) -> FinitelyGeneratedMatrixGroup_gap: ...
    def automorphisms(self) -> ElementConstructorInput: ...
    def number_of_automorphisms(self) -> int: ...
    def set_number_of_automorphisms(self, n: int) -> None: ...
    def has_equivalent_Jordan_decomposition_at_prime(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> bool: ...
    @overload
    def is_globally_equivalent_to(
        self, other: QuadraticForm, return_matrix: Literal[False] = ...
    ) -> bool: ...
    @overload
    def is_globally_equivalent_to(
        self, other: QuadraticForm, return_matrix: Literal[True]
    ) -> bool: ...
    def is_locally_equivalent_to(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> bool: ...
    def is_rationally_isometric(self, other: QuadraticForm) -> bool: ...
    def solve(
        self, *args: ElementConstructorInput, **kwargs: ElementConstructorInput
    ) -> Vector: ...
    def genera(self) -> ElementConstructorInput: ...
