from typing import overload
from sage.matrix.matrix import Matrix

# Forward references for types without stubs
class Vector: ...
class CommutativeRing: ...
class PermutationGroup: ...

def quadratic_form_from_invariants(F: object, rk: int, det: object, P: list[object], sminus: int) -> QuadraticForm: ...
def DiagonalQuadraticForm(R: object, diag: list[object]) -> QuadraticForm: ...

class QuadraticForm:
    def __init__(
        self,
        R: object,
        n: object = None,
        entries: object = None,
        unsafe_initialization: bool = False,
        number_of_automorphisms: object = None,
        determinant: object = None,
    ) -> None: ...

    def list_external_initializations(self) -> list[str]: ...
    def __pari__(self) -> object: ...
    def _pari_init_(self) -> str: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __getitem__(self, ij: tuple[object, object]) -> object: ...
    def __setitem__(self, ij: tuple[object, object], coeff: object) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, right: object) -> bool: ...
    def __add__(self, right: QuadraticForm) -> QuadraticForm: ...
    def sum_by_coefficients_with(self, right: QuadraticForm) -> QuadraticForm: ...
    @overload
    def __call__(self, v: Matrix) -> QuadraticForm: ...
    @overload
    def __call__(self, v: Vector | list[object] | tuple[object, ...]) -> object: ...

    def _is_even_symmetric_matrix_(self, A: Matrix, R: object | None = None) -> bool: ...
    def matrix(self) -> Matrix: ...
    def Hessian_matrix(self) -> Matrix: ...
    def Gram_matrix_rational(self) -> object: ...
    def Gram_matrix(self) -> Matrix: ...
    def has_integral_Gram_matrix(self) -> bool: ...
    def gcd(self) -> object: ...
    def polynomial(self, names: str = 'x') -> object: ...
    @staticmethod
    def from_polynomial(poly: object) -> QuadraticForm: ...

    def is_primitive(self) -> bool: ...
    def primitive(self) -> QuadraticForm: ...
    def adjoint_primitive(self) -> QuadraticForm: ...

    def dim(self) -> int: ...
    def base_ring(self) -> object: ...
    def coefficients(self) -> list[object]: ...
    def det(self) -> object: ...
    def Gram_det(self) -> object: ...
    def change_ring(self, R: object) -> QuadraticForm: ...
    def level(self) -> object: ...
    def level_ideal(self) -> object: ...
    def bilinear_map(self, v: object, w: object) -> object: ...

    # Methods from imported modules (defined via from/lazy_import)
    # From quadratic_form__local_normal_form
    def find_entry_with_minimal_scale_at_prime(self, prime: int) -> object: ...
    def local_normal_form(self, prime: int, *args: object, **kwargs: object) -> object: ...
    def jordan_blocks_by_scale_and_unimodular(self, prime: int) -> object: ...
    def jordan_blocks_in_unimodular_list_by_scale_power(self, prime: int, *args: object) -> object: ...

    # From quadratic_form__count_local_2
    def count_congruence_solutions(self, *args: object, **kwargs: object) -> int: ...
    def count_congruence_solutions__bad_type(self, *args: object, **kwargs: object) -> int: ...
    def count_congruence_solutions__bad_type_I(self, *args: object, **kwargs: object) -> int: ...
    def count_congruence_solutions__bad_type_II(self, *args: object, **kwargs: object) -> int: ...
    def count_congruence_solutions__good_type(self, *args: object, **kwargs: object) -> int: ...
    def count_congruence_solutions__zero_type(self, *args: object, **kwargs: object) -> int: ...
    def count_congruence_solutions_as_vector(self, *args: object, **kwargs: object) -> Vector: ...

    # From quadratic_form__local_density_congruence
    def count_modp_solutions__by_Gauss_sum(self, *args: object, **kwargs: object) -> int: ...
    def local_bad_density_congruence(self, *args: object, **kwargs: object) -> object: ...
    def local_badI_density_congruence(self, *args: object, **kwargs: object) -> object: ...
    def local_badII_density_congruence(self, *args: object, **kwargs: object) -> object: ...
    def local_density_congruence(self, *args: object, **kwargs: object) -> object: ...
    def local_good_density_congruence(self, *args: object, **kwargs: object) -> object: ...
    def local_good_density_congruence_even(self, *args: object, **kwargs: object) -> object: ...
    def local_good_density_congruence_odd(self, *args: object, **kwargs: object) -> object: ...
    def local_primitive_density_congruence(self, *args: object, **kwargs: object) -> object: ...
    def local_zero_density_congruence(self, *args: object, **kwargs: object) -> object: ...

    # From quadratic_form__local_field_invariants
    def _rational_diagonal_form_and_transformation(self, *args: object, **kwargs: object) -> object: ...
    def anisotropic_primes(self) -> list[int]: ...
    def compute_definiteness(self) -> str: ...
    def compute_definiteness_string_by_determinants(self, *args: object, **kwargs: object) -> str: ...
    def hasse_invariant(self, prime: int) -> int: ...
    def hasse_invariant__OMeara(self, prime: int) -> int: ...
    def is_anisotropic(self, *args: object, **kwargs: object) -> bool: ...
    def is_definite(self) -> bool: ...
    def is_hyperbolic(self) -> bool: ...
    def is_indefinite(self) -> bool: ...
    def is_isotropic(self, *args: object, **kwargs: object) -> bool: ...
    def is_negative_definite(self) -> bool: ...
    def is_positive_definite(self) -> bool: ...
    def rational_diagonal_form(self) -> QuadraticForm: ...
    def signature(self) -> tuple[int, int]: ...
    def signature_vector(self) -> Vector: ...

    # From quadratic_form__variable_substitutions
    def add_symmetric(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def divide_variable(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def elementary_substitution(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def extract_variables(self, *args: object, **kwargs: object) -> object: ...
    def multiply_variable(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def scale_by_factor(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def swap_variables(self, *args: object, **kwargs: object) -> QuadraticForm: ...

    # From quadratic_form__local_density_interfaces (lazy_import)
    def local_density(self, *args: object, **kwargs: object) -> object: ...
    def local_primitive_density(self, *args: object, **kwargs: object) -> object: ...

    # From quadratic_form__ternary_Tornaria
    def adjoint(self) -> QuadraticForm: ...
    def antiadjoint(self) -> QuadraticForm: ...
    def basiclemma(self, *args: object, **kwargs: object) -> object: ...
    def basiclemmavec(self, *args: object, **kwargs: object) -> object: ...
    def clifford_conductor(self) -> int: ...
    def clifford_invariant(self, prime: int) -> int: ...
    def content(self) -> object: ...
    def delta(self) -> object: ...
    def disc(self) -> object: ...
    def discrec(self) -> object: ...
    def hasse_conductor(self) -> int: ...
    def is_adjoint(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_zero_nonsingular(self) -> bool: ...
    def is_zero_singular(self) -> bool: ...
    def level__Tornaria(self) -> int: ...
    def lll(self) -> QuadraticForm: ...
    def omega(self, *args: object, **kwargs: object) -> object: ...
    def reciprocal(self) -> QuadraticForm: ...
    def representation_number_list(self, *args: object, **kwargs: object) -> list[int]: ...
    def representation_vector_list(self, *args: object, **kwargs: object) -> list[Vector]: ...
    def xi(self, *args: object, **kwargs: object) -> object: ...
    def xi_rec(self, *args: object, **kwargs: object) -> object: ...

    # From quadratic_form__theta
    def theta_by_cholesky(self, *args: object, **kwargs: object) -> object: ...
    def theta_by_pari(self, *args: object, **kwargs: object) -> object: ...
    def theta_series(self, *args: object, **kwargs: object) -> object: ...
    def theta_series_degree_2(self, *args: object, **kwargs: object) -> object: ...

    # From quadratic_form__siegel_product (lazy_import)
    def siegel_product(self, *args: object, **kwargs: object) -> object: ...

    # From quadratic_form__neighbors
    def find_p_neighbor_from_vec(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def find_primitive_p_divisible_vector__next(self, *args: object, **kwargs: object) -> Vector: ...
    def find_primitive_p_divisible_vector__random(self, *args: object, **kwargs: object) -> Vector: ...
    def neighbor_iteration(self, *args: object, **kwargs: object) -> object: ...
    def orbits_lines_mod_p(self, *args: object, **kwargs: object) -> list[object]: ...

    # From quadratic_form__reduction_theory
    def minkowski_reduction(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def minkowski_reduction_for_4vars__SP(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def reduced_binary_form(self) -> QuadraticForm: ...
    def reduced_binary_form1(self) -> QuadraticForm: ...
    def reduced_ternary_form__Dickson(self) -> QuadraticForm: ...

    # From quadratic_form__genus (lazy_import)
    def global_genus_symbol(self) -> object: ...
    def local_genus_symbol(self, prime: int) -> object: ...
    def CS_genus_symbol_list(self) -> list[object]: ...

    # From quadratic_form__mass (lazy_import)
    def shimura_mass__maximal(self) -> object: ...
    def GHY_mass__maximal(self) -> object: ...

    # From quadratic_form__mass__Siegel_densities (lazy_import)
    def mass__by_Siegel_densities(self) -> object: ...
    def Pall_mass_density_at_odd_prime(self, prime: int) -> object: ...
    def Watson_mass_at_2(self) -> object: ...
    def Kitaoka_mass_at_2(self) -> object: ...
    def mass_at_two_by_counting_mod_power(self, *args: object, **kwargs: object) -> object: ...

    # From quadratic_form__mass__Conway_Sloane_masses (lazy_import)
    def parity(self) -> int: ...
    def is_even(self) -> bool: ...
    def is_odd(self) -> bool: ...
    def conway_species_list_at_odd_prime(self, prime: int) -> list[object]: ...
    def conway_species_list_at_2(self) -> list[object]: ...
    def conway_octane_of_this_unimodular_Jordan_block_at_2(self, *args: object, **kwargs: object) -> int: ...
    def conway_diagonal_factor(self, *args: object, **kwargs: object) -> object: ...
    def conway_cross_product_doubled_power(self, *args: object, **kwargs: object) -> int: ...
    def conway_type_factor(self, *args: object, **kwargs: object) -> object: ...
    def conway_p_mass(self, prime: int) -> object: ...
    def conway_standard_p_mass(self, prime: int) -> object: ...
    def conway_standard_mass(self) -> object: ...
    def conway_mass(self) -> object: ...

    # From quadratic_form__local_representation_conditions (lazy_import)
    def local_representation_conditions(self, *args: object, **kwargs: object) -> object: ...
    def is_locally_universal_at_prime(self, prime: int) -> bool: ...
    def is_locally_universal_at_all_primes(self) -> bool: ...
    def is_locally_universal_at_all_places(self) -> bool: ...
    def is_locally_represented_number_at_place(self, *args: object, **kwargs: object) -> bool: ...
    def is_locally_represented_number(self, *args: object, **kwargs: object) -> bool: ...

    # From quadratic_form__split_local_covering
    def cholesky_decomposition(self) -> object: ...
    def complementary_subform_to_vector(self, *args: object, **kwargs: object) -> QuadraticForm: ...
    def split_local_cover(self) -> QuadraticForm: ...
    def vectors_by_length(self, *args: object, **kwargs: object) -> dict[object, list[Vector]]: ...

    # From quadratic_form__automorphisms (lazy_import)
    def basis_of_short_vectors(self, *args: object, **kwargs: object) -> list[Vector]: ...
    def short_vector_list_up_to_length(self, *args: object, **kwargs: object) -> list[tuple[Vector, int]]: ...
    def short_primitive_vector_list_up_to_length(self, *args: object, **kwargs: object) -> list[tuple[Vector, int]]: ...
    def _compute_automorphisms(self, *args: object, **kwargs: object) -> object: ...
    def automorphism_group(self) -> object: ...
    def automorphisms(self) -> list[Matrix]: ...
    def number_of_automorphisms(self) -> int: ...
    def set_number_of_automorphisms(self, n: int) -> None: ...

    # From quadratic_form__equivalence_testing
    def has_equivalent_Jordan_decomposition_at_prime(self, *args: object, **kwargs: object) -> bool: ...
    def is_globally_equivalent_to(self, *args: object, **kwargs: object) -> bool: ...
    def is_locally_equivalent_to(self, *args: object, **kwargs: object) -> bool: ...
    def is_rationally_isometric(self, *args: object, **kwargs: object) -> bool: ...

    # From qfsolve (lazy_import)
    def solve(self, *args: object, **kwargs: object) -> object: ...

    # From genera.genus (lazy_import)
    def genera(self) -> object: ...
