import builtins

class _SageObject: ...

def parity(self, allow_rescaling_flag: builtins.bool = ...) -> _SageObject: ...
def is_even(self, allow_rescaling_flag: builtins.bool = ...) -> bool: ...
def is_odd(self, allow_rescaling_flag: builtins.bool = ...) -> bool: ...
def conway_species_list_at_odd_prime(self, p: builtins.int) -> _SageObject: ...
def conway_species_list_at_2(self) -> _SageObject: ...
def conway_octane_of_this_unimodular_Jordan_block_at_2(self) -> _SageObject: ...
def conway_diagonal_factor(self, p: builtins.int) -> _SageObject: ...
def conway_cross_product_doubled_power(self, p: builtins.int) -> _SageObject: ...
def conway_type_factor(self) -> _SageObject: ...
def conway_p_mass(self, p: builtins.int) -> _SageObject: ...
def conway_standard_p_mass(self, p: builtins.int) -> _SageObject: ...
def conway_standard_mass(self) -> _SageObject: ...
def conway_mass(self) -> _SageObject: ...
