import builtins

class _SageObject: ...

def gamma__exact(self) -> _SageObject: ...
def zeta__exact(self) -> _SageObject: ...
def QuadraticBernoulliNumber(self, d: builtins.object) -> _SageObject: ...
def quadratic_L_function__exact(self, d: builtins.object) -> _SageObject: ...
def quadratic_L_function__numerical(
    self, d: builtins.object, num_terms: builtins.int = ...
) -> _SageObject: ...
