# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def gamma__exact(n: builtins.int) -> _SageObject: ...

def zeta__exact(n: builtins.int) -> _SageObject: ...

def QuadraticBernoulliNumber(k: builtins.int, d: builtins.object) -> _SageObject: ...

def quadratic_L_function__exact(n: builtins.int, d: builtins.object) -> _SageObject: ...

def quadratic_L_function__numerical(n: builtins.int, d: builtins.object, num_terms: builtins.int = ...) -> _SageObject: ...
