# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def red_mfact(a: builtins.object, b: builtins.object) -> _SageObject: ...

def primitivize(v0: builtins.object, v1: builtins.object, v2: builtins.object, p: builtins.object) -> _SageObject: ...

def evaluate(a: builtins.object, b: builtins.object, c: builtins.object, r: builtins.object, s: builtins.object, t: builtins.object, v: builtins.object) -> _SageObject: ...

def pseudorandom_primitive_zero_mod_p(a: builtins.object, b: builtins.object, c: builtins.object, r: builtins.object, s: builtins.object, t: builtins.object, p: builtins.object) -> _SageObject: ...

def extend(v: builtins.object) -> _SageObject: ...
