import builtins

class _SageObject: ...

class CryptoMiniSat:
    def __init__(
        self,
        verbosity: builtins.int = ...,
        confl_limit: builtins.object = ...,
        threads: builtins.object = ...,
    ) -> None: ...
    def var(self, decision: builtins.object = ...) -> int: ...
    def nvars(self) -> int: ...
    def add_clause(self, lits: builtins.object) -> None: ...
    def add_xor_clause(
        self, lits: builtins.object, rhs: builtins.bool = ...
    ) -> None: ...
    def __call__(self, assumptions: builtins.object = ...) -> tuple | bool: ...
    def clauses(self, filename: builtins.object = ...) -> _SageObject: ...
