from sage.interfaces.interface import Interface

class Expect(Interface):
    def eval(self, x: str, **kwds: object) -> str: ...
    def quit(self) -> None: ...
    def read(self, filename: str) -> None: ...

class ExpectElement: ...
class ExpectFunction: ...
class FunctionElement: ...
