# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

FRICAS_SINGLE_LINE_START: _SageObject
FRICAS_MULTI_LINE_START: _SageObject
FRICAS_LINE_LENGTH: _SageObject
FRICAS_WHAT_OPERATIONS_STRING: _SageObject
FRICAS_ERROR_IN_LIBRARY_CODE: _SageObject
FRICAS_SYSTEM_ERROR: _SageObject
FRICAS_INIT_CODE: _SageObject
FRICAS_HELPER_CODE: _SageObject
FRICAS_LINENUMBER_OFF_CODE: _SageObject
FRICAS_FIRST_PROMPT: _SageObject
FRICAS_LINENUMBER_OFF_PROMPT: _SageObject
class FriCAS:
    def __init__(self, name: builtins.str = ..., command: builtins.object = ..., script_subdirectory: builtins.object = ..., logfile: builtins.object = ..., server: builtins.object = ..., server_tmpdir: builtins.object = ...) -> None: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def get_string(self, var: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def eval(self, code: builtins.object, strip: builtins.bool = ..., synchronize: builtins.bool = ..., locals: builtins.object = ..., allow_use_file: builtins.bool = ..., split_lines: builtins.str = ..., reformat: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...
    def console(self) -> _SageObject: ...

class FriCASElement:
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def __int__(self) -> builtins.int: ...
    def bool(self) -> _SageObject: ...
    def __bool__(self) -> builtins.bool: ...
    def __float__(self) -> builtins.float: ...
    def gen(self, n: builtins.int) -> _SageObject: ...

class FriCASFunctionElement:
    def __init__(self, object: builtins.object, name: builtins.str) -> None: ...

class FriCASExpectFunction:
    def __init__(self, parent: builtins.object, name: builtins.str) -> None: ...

fricas: _SageObject
def reduce_load_fricas() -> _SageObject: ...

def fricas_console() -> _SageObject: ...
