# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Frobby:
    def __call__(self, action: builtins.object, input: builtins.object = ..., options: builtins.list[_SageObject] = ..., verbose: builtins.bool = ...) -> _SageObject: ...
    def alexander_dual(self, monomial_ideal: builtins.object) -> _SageObject: ...
    def hilbert(self, monomial_ideal: builtins.object) -> _SageObject: ...
    def associated_primes(self, monomial_ideal: builtins.object) -> _SageObject: ...
    def dimension(self, monomial_ideal: builtins.object) -> _SageObject: ...
    def irreducible_decomposition(self, monomial_ideal: builtins.object) -> _SageObject: ...

frobby: _SageObject
