import builtins

class _SageObject: ...

WORKSPACE: _SageObject
first_try: _SageObject

def gap_command(self=..., local: builtins.bool = ...) -> _SageObject: ...

class Gap_generic:
    def interrupt(
        self,
        tries: builtins.object = ...,
        timeout: builtins.int = ...,
        quit_on_fail: builtins.bool = ...,
    ) -> _SageObject: ...
    def load_package(
        self, pkg: builtins.object, verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def eval(
        self,
        x: builtins.object,
        newlines: builtins.bool = ...,
        strip: builtins.bool = ...,
        split_lines: builtins.bool = ...,
        **kwds: builtins.object,
    ) -> _SageObject: ...
    def unbind(self, var: builtins.object) -> _SageObject: ...
    def version(self) -> _SageObject: ...
    def function_call(
        self,
        function: builtins.object,
        args: builtins.object = ...,
        kwds: builtins.object = ...,
    ) -> _SageObject: ...
    def get_record_element(
        self, record: builtins.object, name: builtins.str
    ) -> _SageObject: ...

class GapElement_generic:
    def __bool__(self) -> builtins.bool: ...
    def __len__(self) -> builtins.int: ...
    def is_string(self) -> builtins.bool: ...

class Gap:
    def __init__(
        self,
        max_workspace_size: builtins.object = ...,
        maxread: builtins.object = ...,
        script_subdirectory: builtins.object = ...,
        use_workspace_cache: builtins.bool = ...,
        server: builtins.object = ...,
        server_tmpdir: builtins.object = ...,
        logfile: builtins.object = ...,
        seed: builtins.object = ...,
        env: builtins.dict[_SageObject, _SageObject] = ...,
    ) -> None: ...
    def set_seed(self, seed: builtins.object = ...) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def cputime(self, t: builtins.object = ...) -> _SageObject: ...
    def save_workspace(self) -> _SageObject: ...
    def help(self, s: builtins.object, pager: builtins.bool = ...) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(
        self, var: builtins.object, use_file: builtins.bool = ...
    ) -> _SageObject: ...
    def console(self) -> _SageObject: ...

def gap_reset_workspace(self=..., verbose: builtins.bool = ...) -> _SageObject: ...

class GapElement:
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def str(self, use_file: builtins.bool = ...) -> _SageObject: ...

class GapFunctionElement: ...
class GapFunction: ...

def gfq_gap_to_sage(self, F: builtins.object) -> _SageObject: ...
def intmod_gap_to_sage(self) -> _SageObject: ...

gap: _SageObject

def reduce_load_GAP(self) -> _SageObject: ...
def gap_console(self) -> _SageObject: ...
