import builtins

class _SageObject: ...

def gap_workspace_file(
    self=..., name: builtins.str = ..., dir: builtins.object = ...
) -> _SageObject: ...
def prepare_workspace_dir(self=...) -> _SageObject: ...
