# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

COMMANDS_CACHE: _SageObject
class Giac:
    def __init__(self, maxread: builtins.object = ..., script_subdirectory: builtins.object = ..., server: builtins.object = ..., server_tmpdir: builtins.object = ..., logfile: builtins.object = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def expect(self) -> _SageObject: ...
    def console(self) -> _SageObject: ...
    def completions(self, s: builtins.object) -> _SageObject: ...
    def cputime(self, t: builtins.object = ...) -> _SageObject: ...
    def eval(self, code: builtins.object, strip: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def help(self, string: builtins.object) -> _SageObject: ...
    def clear(self, var: builtins.object) -> _SageObject: ...
    def version(self) -> _SageObject: ...

class GiacFunction:
    ...

class GiacFunctionElement:
    ...

class GiacElement:
    def __float__(self) -> builtins.float: ...
    def unapply(self, var: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __del__(self) -> _SageObject: ...
    def integral(self, var: builtins.str = ..., min: builtins.object = ..., max: builtins.object = ...) -> _SageObject: ...
    integrate: _SageObject
    def sum(self, var: builtins.object, min: builtins.object = ..., max: builtins.object = ...) -> _SageObject: ...

giac: _SageObject
def reduce_load_Giac() -> _SageObject: ...

def giac_console() -> _SageObject: ...
