from sage.structure.parent import Parent
from sage.structure.parent_base import ParentWithBase

class Interface(ParentWithBase):
    def __init__(self, name: str | Parent) -> None: ...
    def eval(self, x: str, **kwds: object) -> str: ...
