import builtins
from typing import Self

class _SageObject: ...

class Kash:
    def __init__(
        self,
        max_workspace_size: builtins.object = ...,
        maxread: builtins.object = ...,
        script_subdirectory: builtins.object = ...,
        restart_on_ctrlc: builtins.bool = ...,
        logfile: builtins.object = ...,
        server: builtins.object = ...,
        server_tmpdir: builtins.object = ...,
    ) -> None: ...
    def clear(self, var: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def eval(
        self,
        x: builtins.object,
        newlines: builtins.bool = ...,
        strip: builtins.bool = ...,
        **kwds: builtins.object,
    ) -> _SageObject: ...
    def help(self, name: builtins.str = ...) -> _SageObject: ...
    def help_search(self, name: builtins.str) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def function_call(
        self,
        function: builtins.object,
        args: builtins.object = ...,
        kwds: builtins.object = ...,
    ) -> _SageObject: ...
    def console(self) -> _SageObject: ...
    def version(self) -> _SageObject: ...

class KashElement:
    def __mod__(self, other: builtins.object) -> Self: ...
    def __len__(self) -> builtins.int: ...
    def __bool__(self) -> builtins.bool: ...

class KashDocumentation: ...

kash: _SageObject

def reduce_load_Kash(self) -> _SageObject: ...
def kash_console(self) -> _SageObject: ...
def kash_version(self) -> _SageObject: ...
