# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

COMMANDS_CACHE: _SageObject
class Maple:
    def __init__(self, maxread: builtins.object = ..., script_subdirectory: builtins.object = ..., server: builtins.object = ..., server_tmpdir: builtins.object = ..., logfile: builtins.object = ..., ulimit: builtins.object = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def expect(self) -> _SageObject: ...
    def console(self) -> _SageObject: ...
    def completions(self, s: builtins.object) -> builtins.list[_SageObject]: ...
    def cputime(self, t: builtins.object = ...) -> builtins.float: ...
    def set(self, var: builtins.object, value: builtins.object) -> None: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def source(self, s: builtins.object) -> _SageObject: ...
    def help(self, string: builtins.object) -> _SageObject: ...
    def with_package(self, package: builtins.object) -> None: ...
    load: _SageObject
    def clear(self, var: builtins.object) -> None: ...

class MapleFunction:
    ...

class MapleFunctionElement:
    ...

class MapleElement:
    def __float__(self) -> builtins.float: ...
    def __hash__(self) -> builtins.int: ...
    def op(self, i: builtins.int = ...) -> _SageObject: ...

maple: _SageObject
def reduce_load_Maple() -> _SageObject: ...

def maple_console() -> _SageObject: ...
