# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Mathics:
    def __init__(self, maxread: builtins.object = ..., logfile: builtins.object = ..., init_list_length: builtins.int = ..., seed: builtins.object = ...) -> None: ...
    def eval(self, code: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def chdir(self, dir: builtins.object) -> _SageObject: ...
    def console(self) -> _SageObject: ...
    def help(self, cmd: builtins.object, long: builtins.bool = ...) -> _SageObject: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...

class MathicsElement:
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...
    def __float__(self, precision: builtins.int = ...) -> builtins.float: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __len__(self) -> builtins.int: ...
    def save_image(self, filename: builtins.object, ImageSize: builtins.int = ...) -> _SageObject: ...
    def show(self, ImageSize: builtins.int = ...) -> _SageObject: ...
    def __bool__(self) -> builtins.bool: ...
    def n(self, *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...

mathics: _SageObject
def reduce_load(X: builtins.object) -> _SageObject: ...

def mathics_console() -> _SageObject: ...
