import builtins

class _SageObject: ...

instances: _SageObject

def Mwrank(
    self=..., server: builtins.object = ..., server_tmpdir: builtins.object = ...
) -> _SageObject: ...

AINVS_LIST_RE: _SageObject
AINVS_PLAIN_RE: _SageObject

def validate_mwrank_input(self) -> _SageObject: ...

class Mwrank_class:
    def __init__(
        self,
        options: builtins.str = ...,
        server: builtins.object = ...,
        server_tmpdir: builtins.object = ...,
    ) -> None: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __call__(self, cmd: builtins.object) -> _SageObject: ...
    def eval(self, s: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def console(self) -> _SageObject: ...

mwrank: _SageObject

def mwrank_console(self) -> _SageObject: ...
