import builtins

class _SageObject: ...

def get_solution_dicts(
    self, input_ring: builtins.object, get_failures: builtins.bool = ...
) -> _SageObject: ...
def get_classified_solution_dicts(
    self, input_ring: builtins.object, get_failures: builtins.bool = ...
) -> _SageObject: ...
def get_variable_list(self) -> _SageObject: ...

class PHC_Object:
    def __init__(
        self, output_file_contents: builtins.object, input_ring: builtins.object
    ) -> None: ...
    def save_as_start(
        self, start_filename: builtins.object = ..., sol_filter: builtins.str = ...
    ) -> _SageObject: ...
    def classified_solution_dicts(self) -> _SageObject: ...
    def solution_dicts(self, get_failures: builtins.bool = ...) -> _SageObject: ...
    def solutions(self, get_failures: builtins.bool = ...) -> _SageObject: ...
    def variable_list(self) -> _SageObject: ...

class PHC:
    def path_track(
        self,
        start_sys: builtins.object,
        end_sys: builtins.object,
        input_ring: builtins.object,
        c_skew: builtins.float = ...,
        saved_start: builtins.object = ...,
    ) -> _SageObject: ...
    def plot_paths_2d(
        self,
        start_sys: builtins.object,
        end_sys: builtins.object,
        input_ring: builtins.object,
        c_skew: builtins.float = ...,
        endpoints: builtins.bool = ...,
        saved_start: builtins.object = ...,
        rand_colors: builtins.bool = ...,
    ) -> _SageObject: ...
    def mixed_volume(
        self, polys: builtins.object, verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def start_from(
        self,
        start_filename_or_string: builtins.object,
        polys: builtins.object,
        input_ring: builtins.object,
        path_track_file: builtins.object = ...,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...
    def blackbox(
        self,
        polys: builtins.object,
        input_ring: builtins.object,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...

phc: _SageObject
