# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PolymakeError(Exception):
    ...

def polymake_console(command: builtins.str = ...) -> _SageObject: ...

class PolymakeAbstract:
    def __init__(self, seed: builtins.object = ...) -> None: ...
    def version(self) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def function_call(self, function: builtins.object, args: builtins.object = ..., kwds: builtins.object = ...) -> _SageObject: ...
    def console(self) -> _SageObject: ...
    def clear(self, var: builtins.object) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(self, cmd: builtins.object) -> _SageObject: ...
    def help(self, topic: builtins.object, pager: builtins.bool = ...) -> _SageObject: ...
    def application(self, app: builtins.object) -> _SageObject: ...
    def new_object(self, name: builtins.str, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class PolymakeElement:
    def __bool__(self) -> builtins.bool: ...
    def known_properties(self) -> _SageObject: ...
    def typename(self) -> _SageObject: ...
    def full_typename(self) -> _SageObject: ...
    def qualified_typename(self) -> _SageObject: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...
    def get_member_function(self, attrname: builtins.object) -> _SageObject: ...
    def get_member(self, attrname: builtins.object) -> _SageObject: ...
    def __getitem__(self, key: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
    def typeof(self) -> _SageObject: ...

class PolymakeFunctionElement:
    def __init__(self, obj: builtins.object, name: builtins.str, memberfunction: builtins.bool = ...) -> None: ...
    def __call__(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class PolymakeJuPyMake:
    def __init__(self, seed: builtins.object = ..., verbose: builtins.bool = ...) -> None: ...
    def is_running(self) -> builtins.bool: ...
    def eval(self, code: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def reduce_load_Polymake() -> _SageObject: ...

Polymake: _SageObject
polymake: _SageObject
polymake_jupymake: _SageObject
