# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ContainChildren:
    def __init__(self, exitcode: builtins.object = ..., exceptcode: builtins.object = ..., silent: builtins.object = ...) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *exc: builtins.object) -> builtins.bool | None: ...

def terminate(sp: builtins.object, interval: builtins.object = ..., signals: builtins.object = ...) -> _SageObject: ...
