# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def sage_spawned_process_file() -> builtins.str: ...

def register_spawned_process(pid: builtins.int, cmd: builtins.str = ...) -> None: ...

expect_objects: _SageObject
def expect_quitall(verbose: builtins.bool = ...) -> None: ...

def kill_spawned_jobs(verbose: builtins.bool = ...) -> _SageObject: ...

def is_running(pid: builtins.int) -> builtins.bool: ...

def invalidate_all() -> None: ...
