# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

rpy2_feature: _SageObject
COMMANDS_CACHE: _SageObject
RRepositoryURL: _SageObject
RFilteredPackages: _SageObject
RBaseCommands: _SageObject
class R:
    def __init__(self, maxread: builtins.object = ..., logfile: builtins.object = ..., init_list_length: builtins.int = ..., seed: builtins.object = ...) -> None: ...
    def set_seed(self, seed: builtins.object = ...) -> _SageObject: ...
    def png(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def convert_r_list(self, l: builtins.object) -> _SageObject: ...
    def install_packages(self, package_name: builtins.str) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...
    def read(self, filename: builtins.object) -> _SageObject: ...
    def source(self, s: builtins.object) -> _SageObject: ...
    def version(self) -> _SageObject: ...
    def library(self, library_name: builtins.str) -> _SageObject: ...
    require: _SageObject
    def available_packages(self) -> _SageObject: ...
    def help(self, command: builtins.object) -> _SageObject: ...
    def console(self) -> _SageObject: ...
    def function_call(self, function: builtins.object, args: builtins.object = ..., kwds: builtins.object = ...) -> _SageObject: ...
    def call(self, function_name: builtins.str, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def na(self) -> _SageObject: ...
    def completions(self, s: builtins.object) -> _SageObject: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def eval(self, code: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def __getitem__(self, s: builtins.object) -> _SageObject: ...
    def chdir(self, dir: builtins.object) -> _SageObject: ...

class RElement:
    def tilde(self, x: builtins.object) -> _SageObject: ...
    stat_model: _SageObject
    def is_string(self) -> builtins.bool: ...
    def __len__(self) -> builtins.int: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def __bool__(self) -> builtins.bool: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def dot_product(self, other: builtins.object) -> _SageObject: ...

class RFunctionElement:
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __call__(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class RFunction:
    def __init__(self, parent: builtins.object, name: builtins.str, r_name: builtins.str = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

r: _SageObject
def reduce_load_R() -> _SageObject: ...

def r_console() -> _SageObject: ...

def r_version() -> _SageObject: ...

class HelpExpression:
    ...
