# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AlgorithmExt:
    ALG_SIMPLIFY: _SageObject
    ALG_WIRTINGER: _SageObject
    ALG_USE_EXTERIOR: _SageObject

class Regina:
    def __init__(self) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def eval(self, code: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def help(self, cmd: builtins.object, long: builtins.bool = ...) -> _SageObject: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...

class ReginaElement:
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...
    def __bool__(self) -> builtins.bool: ...
    def __deepcopy__(self, memo: builtins.object = ...) -> Self: ...

class ReginaFunctionElement:
    def __call__(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class ReginaFunction:
    def __call__(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

regina: _SageObject
