import builtins

class _SageObject: ...

class Sage:
    def __init__(
        self,
        logfile: builtins.object = ...,
        preparse: builtins.bool = ...,
        init_code: builtins.object = ...,
        server: builtins.object = ...,
        server_tmpdir: builtins.object = ...,
        remote_cleaner: builtins.bool = ...,
        **kwds: builtins.object,
    ) -> None: ...
    def cputime(self, t: builtins.object = ...) -> _SageObject: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def preparse(self, x: builtins.object) -> _SageObject: ...
    def eval(
        self, line: builtins.object, strip: builtins.bool = ..., **kwds: builtins.object
    ) -> _SageObject: ...
    def set(self, var: builtins.object, value: builtins.object) -> _SageObject: ...
    def get(self, var: builtins.object) -> _SageObject: ...
    def clear(self, var: builtins.object) -> _SageObject: ...
    def console(self) -> _SageObject: ...
    def version(self) -> _SageObject: ...
    def new(self, x: builtins.object) -> _SageObject: ...

class SageElement:
    def __getattr__(self, attrname: builtins.object) -> _SageObject: ...

class SageFunction:
    def __call__(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...

sage0: _SageObject

def reduce_load_Sage(self) -> _SageObject: ...
def reduce_load_element(self) -> _SageObject: ...
def sage0_console(self) -> _SageObject: ...
def sage0_version(self) -> _SageObject: ...
