# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SageSpawn:
    def __init__(self, *args: builtins.object, **kwds: builtins.object) -> None: ...
    def expect_peek(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def expect_upto(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class SagePtyProcess:
    def close(self, force: builtins.object = ...) -> _SageObject: ...
    def terminate_async(self, interval: builtins.object = ...) -> _SageObject: ...
