# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SageSet:
    def __new__(cls, sage_set: builtins.object) -> Self: ...
    @property
    def is_empty(self) -> builtins.bool: ...
    @property
    def is_finite_set(self) -> builtins.bool: ...
    @property
    def is_iterable(self) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
