# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class UndefSageHelper:
    def __get__(self, ins: builtins.object, typ: builtins.object) -> _SageObject: ...

def sympy_init() -> _SageObject: ...

def check_expression(expr: builtins.object, var_symbols: builtins.object, only_from_sympy: builtins.bool = ...) -> _SageObject: ...

def check_all() -> _SageObject: ...

def sympy_set_to_list(set: builtins.object, vars: builtins.object) -> _SageObject: ...
