import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class SageSet:
    def __new__(cls, sage_set: builtins.object) -> SageSet: ...
    @property
    def is_empty(self) -> builtins.bool: ...
    @property
    def is_finite_set(self) -> builtins.bool: ...
    @property
    def is_iterable(self) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
