# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def bell_number(n: builtins.object) -> _SageObject: ...

def bernoulli_number(n: builtins.object) -> _SageObject: ...

def euler_number(n: builtins.object) -> _SageObject: ...

def stirling_number_1(n: builtins.object, k: builtins.object) -> _SageObject: ...

def stirling_number_2(n: builtins.object, k: builtins.object) -> _SageObject: ...

def number_of_partitions(n: builtins.object) -> _SageObject: ...

def dedekind_sum(p: builtins.object, q: builtins.object) -> _SageObject: ...

def harmonic_number(n: builtins.object) -> _SageObject: ...
