from sage.structure.sage_object import SageObject

class FormattedExpansion(SageObject):
    _txt: str | None
    _latex: str | None
    def __init__(self, txt: str | None = None, latex: str | None = None) -> None: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
