from typing import overload

from sage.matrix.matrix2 import Matrix
from sage.rings.integer import Integer
from sage.structure.element import Element, Expression, MultiplicativeGroupElement
from sage.tensor.modules.comp import Components
from sage.tensor.modules.finite_rank_free_module import FiniteRankFreeModule
from sage.tensor.modules.free_module_alt_form import FreeModuleAltForm
from sage.tensor.modules.free_module_basis import FreeModuleBasis
from sage.tensor.modules.free_module_element import FiniteRankFreeModuleElement
from sage.tensor.modules.free_module_tensor import FreeModuleTensor
from sage.manifolds.differentiable.metric import PseudoRiemannianMetric
from sage.manifolds.differentiable.poisson_tensor import PoissonTensorField
from sage.manifolds.differentiable.symplectic_form import SymplecticForm

type _Scalar = Element | Expression | Integer | int
type _FormatSpec = int | Integer
type _ComponentSet = Components[_Scalar, _Scalar, _FormatSpec]

class FreeModuleAutomorphism(FreeModuleTensor, MultiplicativeGroupElement):
    inverse: FreeModuleAutomorphism
    charpoly: Element
    determinant: Element
    minpoly: Element

    def __init__(
        self,
        fmodule: FiniteRankFreeModule,
        name: str | None = ...,
        latex_name: str | None = ...,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def _new_instance(self) -> FreeModuleAutomorphism: ...
    def _del_derived(self) -> None: ...
    def set_comp(self, basis: FreeModuleBasis | None = ...) -> _ComponentSet: ...
    def add_comp(self, basis: FreeModuleBasis | None = ...) -> _ComponentSet: ...
    @overload
    def __call__(self, vector: FiniteRankFreeModuleElement) -> FiniteRankFreeModuleElement: ...
    @overload
    def __call__(self, linform: FreeModuleAltForm, vector: FiniteRankFreeModuleElement) -> Element | int: ...
    @overload
    def __call__(self, *args: FreeModuleTensor) -> _Scalar: ...
    def __invert__(self) -> FreeModuleAutomorphism: ...
    def _mul_(self, other: FreeModuleAutomorphism) -> FreeModuleAutomorphism: ...
    @overload
    def __mul__(self, other: FreeModuleAutomorphism) -> FreeModuleAutomorphism: ...
    @overload
    def __mul__(self, other: FreeModuleTensor | _Scalar) -> FreeModuleTensor: ...
    def matrix(self, basis1: FreeModuleBasis | None = ..., basis2: FreeModuleBasis | None = ...) -> Matrix: ...
    def _some_matrix(self) -> Matrix: ...
    def characteristic_polynomial(self, var: str = ...) -> Element: ...
    def det(self) -> Element: ...
    def fcp(self, var: str = ...) -> Element: ...
    def minimal_polynomial(self, var: str = ...) -> Element: ...
    @overload
    def trace(self) -> Element: ...
    @overload
    def trace(
        self,
        pos1: int = ...,
        pos2: int = ...,
        using: PseudoRiemannianMetric | SymplecticForm | PoissonTensorField | None = ...,
    ) -> FreeModuleTensor | _Scalar: ...
