# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Basis_abstract:
    def __init__(self, fmodule: builtins.object, symbol: builtins.object, latex_symbol: builtins.object, indices: builtins.object, latex_indices: builtins.object) -> None: ...
    def keys(self) -> _SageObject: ...
    def values(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
    def cardinality(self) -> _SageObject: ...
    def __getitem__(self, index: builtins.object) -> _SageObject: ...
    def free_module(self) -> _SageObject: ...
    def set_name(self, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., index_position: builtins.str = ...) -> _SageObject: ...

class FreeModuleCoBasis:
    def __init__(self, basis: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ...) -> None: ...

class FreeModuleBasis:
    @staticmethod
    def __classcall_private__(cls: builtins.object, fmodule: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., symbol_dual: builtins.object = ..., latex_symbol_dual: builtins.object = ...) -> _SageObject: ...
    def __init__(self, fmodule: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., symbol_dual: builtins.object = ..., latex_symbol_dual: builtins.object = ...) -> None: ...
    def module(self) -> _SageObject: ...
    def dual_basis(self) -> _SageObject: ...
    def new_basis(self, change_of_basis: builtins.object, symbol: builtins.object, latex_symbol: builtins.object = ..., indices: builtins.object = ..., latex_indices: builtins.object = ..., symbol_dual: builtins.object = ..., latex_symbol_dual: builtins.object = ...) -> _SageObject: ...
