from collections.abc import Sequence
from typing import Protocol, TypeAlias

from sage.categories.morphism import Morphism
from sage.matrix.matrix2 import Matrix
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.tensor.modules.finite_rank_free_module import FiniteRankFreeModule
from sage.tensor.modules.format_utilities import FormattedExpansion
from sage.tensor.modules.free_module_basis import FreeModuleBasis
from sage.tensor.modules.free_module_element import FiniteRankFreeModuleElement

type _MatrixLike = Matrix | Sequence[Sequence[Element | int]] | int
_Name: TypeAlias = str | None

class _FreeModuleHomsetLike(Protocol):
    def domain(self) -> FiniteRankFreeModule: ...
    def codomain(self) -> FiniteRankFreeModule: ...
    def base_ring(self) -> Parent: ...

class FiniteRankFreeModuleMorphism(Morphism):
    def __init__(
        self,
        parent: _FreeModuleHomsetLike,
        matrix_rep: _MatrixLike,
        bases: tuple[FreeModuleBasis, FreeModuleBasis] | Sequence[FreeModuleBasis] | None = ...,
        name: _Name = ...,
        latex_name: _Name = ...,
        is_identity: bool = ...,
    ) -> None: ...
    def _latex_(self) -> str: ...
    def _add_(self, other: FiniteRankFreeModuleMorphism) -> FiniteRankFreeModuleMorphism: ...
    def _sub_(self, other: FiniteRankFreeModuleMorphism) -> FiniteRankFreeModuleMorphism: ...
    def _lmul_(self, scalar: Element | int) -> FiniteRankFreeModuleMorphism: ...
    def _call_(self, element: FiniteRankFreeModuleElement) -> FiniteRankFreeModuleElement: ...
    def is_injective(self) -> bool: ...
    def is_surjective(self) -> bool: ...
    def is_identity(self) -> bool: ...
    def _modules_and_bases(
        self,
        basis1: FreeModuleBasis | None = ...,
        basis2: FreeModuleBasis | None = ...,
    ) -> tuple[FiniteRankFreeModule, FiniteRankFreeModule, FreeModuleBasis, FreeModuleBasis]: ...
    def matrix(self, basis1: FreeModuleBasis | None = ..., basis2: FreeModuleBasis | None = ...) -> Matrix: ...
    def _common_bases(
        self,
        other: FiniteRankFreeModuleMorphism,
    ) -> tuple[FreeModuleBasis, FreeModuleBasis] | None: ...
    def display(
        self,
        basis1: FreeModuleBasis | None = ...,
        basis2: FreeModuleBasis | None = ...,
    ) -> FormattedExpansion: ...

class FiniteRankFreeModuleEndomorphism(FiniteRankFreeModuleMorphism):
    charpoly: Element
    determinant: Element
    minpoly: Element

    def __init__(
        self,
        parent: _FreeModuleHomsetLike,
        matrix_rep: _MatrixLike,
        bases: tuple[FreeModuleBasis, FreeModuleBasis] | Sequence[FreeModuleBasis] | None = ...,
        name: _Name = ...,
        latex_name: _Name = ...,
        is_identity: bool = ...,
    ) -> None: ...
    def _some_matrix(self) -> Matrix: ...
    def characteristic_polynomial(self, var: str = ...) -> Element: ...
    def det(self) -> Element: ...
    def fcp(self, var: str = ...) -> Element: ...
    def minimal_polynomial(self, var: str = ...) -> Element: ...
    def trace(self) -> Element: ...
