from collections.abc import Sequence
from typing import Protocol, Self, TypeAlias, overload

from sage.matrix.matrix2 import Matrix
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

_TensorType: TypeAlias = tuple[int, int]
_IndexPermutation: TypeAlias = Sequence[int]
_Scalar: TypeAlias = int | Integer | Element
_ComponentValue: TypeAlias = _Scalar | Matrix | list[_Scalar] | list[list[_Scalar]]
_TensorAccess: TypeAlias = str | int | slice | tuple[int | slice | SageObject, ...]


class _IndexedTensor(Protocol):
    _tensor_type: _TensorType
    _name: str | None

    def tensor_type(self) -> _TensorType: ...
    def tensor_rank(self) -> int: ...
    def symmetrize(self, *pos: int) -> Self: ...
    def antisymmetrize(self, *pos: int) -> Self: ...
    def trace(self, pos1: int, pos2: int) -> Self | _Scalar: ...
    def contract(self, *args: int | _IndexedTensor) -> _IndexedTensor | _Scalar: ...
    def comp(self, basis: SageObject) -> SageObject: ...
    def __mul__(self, other: _IndexedTensor) -> _IndexedTensor | _Scalar: ...
    def __rmul__(self, other: _Scalar) -> Self: ...
    def __add__(self, other: _IndexedTensor) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __getitem__(self, args: _TensorAccess) -> _ComponentValue: ...
    def __setitem__(self, args: _TensorAccess, value: _ComponentValue) -> None: ...


class TensorWithIndices(SageObject):
    _tensor: _IndexedTensor | _Scalar
    _changed: bool
    _con: str
    _cov: str

    @staticmethod
    def _parse_indices(
        indices: str,
        tensor_type: _TensorType | None = None,
        allow_contraction: bool = True,
        allow_symmetries: bool = True,
    ) -> tuple[str, str]: ...
    def __init__(self, tensor: _IndexedTensor, indices: str) -> None: ...
    def _repr_(self) -> str: ...
    def update(self) -> TensorWithIndices | _IndexedTensor | _Scalar: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __mul__(self, other: TensorWithIndices) -> _IndexedTensor | _Scalar: ...
    def __rmul__(self, other: _Scalar) -> TensorWithIndices: ...
    def __add__(self, other: TensorWithIndices) -> TensorWithIndices: ...
    def __sub__(self, other: TensorWithIndices) -> TensorWithIndices: ...
    @overload
    def __getitem__(self, args: str) -> TensorWithIndices: ...
    @overload
    def __getitem__(self, args: int | slice | tuple[int | slice | SageObject, ...]) -> _ComponentValue: ...
    @overload
    def __setitem__(self, args: str, value: TensorWithIndices) -> None: ...
    @overload
    def __setitem__(self, args: int | slice | tuple[int | slice | SageObject, ...], value: _ComponentValue) -> None: ...
    def permute_indices(self, permutation: _IndexPermutation) -> TensorWithIndices: ...
    def __pos__(self) -> TensorWithIndices: ...
    def __neg__(self) -> TensorWithIndices: ...
