# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AutomaticSemigroup:
    @staticmethod
    def __classcall_private__(cls: builtins.object, generators: builtins.object, ambient: builtins.object = ..., one: builtins.object = ..., mul: builtins.object = ..., category: builtins.object = ...) -> _SageObject: ...
    def __init__(self, generators: builtins.object, ambient: builtins.object, one: builtins.object, mul: builtins.object, category: builtins.object) -> None: ...
    def repr_element_method(self, style: builtins.str = ...) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def retract(self, ambient_element: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def semigroup_generators(self) -> _SageObject: ...
    gens: _SageObject
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def product(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def from_reduced_word(self, l: builtins.object) -> _SageObject: ...
    def construct(self, up_to: builtins.object = ..., n: builtins.int = ...) -> _SageObject: ...
    class Element:
        def __init__(self, ambient_element: builtins.object, parent: builtins.object) -> None: ...
        def reduced_word(self) -> _SageObject: ...
        def lift(self) -> _SageObject: ...
        def transition(self, i: builtins.int) -> _SageObject: ...
        def __copy__(self, memo: builtins.object = ...) -> Self: ...

class AutomaticMonoid:
    def one(self) -> _SageObject: ...
    semigroup_generators: _SageObject
    def monoid_generators(self) -> _SageObject: ...
    gens: _SageObject
