# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeAbelianMonoidElement:
    def __cinit__(self, parent: builtins.object = ..., x: builtins.object = ...) -> _SageObject: ...
    def __init__(self, parent: builtins.object, x: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def __copy__(self) -> Self: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __mul__(self, y: builtins.object) -> Self: ...
    def __pow__(self, n: builtins.object, modulus: builtins.object) -> Self: ...
    def __hash__(self) -> builtins.int: ...
    def list(self) -> _SageObject: ...
