import builtins
from collections.abc import (
    Iterator as _Iterator,
)
from typing import Self

from sage.structure.element import Element

class _SageObject: ...

class FreeMonoidElement:
    def __init__(
        self, F: builtins.object, x: builtins.object, check: builtins.bool = ...
    ) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __call__(self, *x: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def __invert__(self) -> Self: ...
    def __len__(self) -> int: ...
    def to_word(self, alph: builtins.object = ...) -> _SageObject: ...
    def to_list(self, indices: builtins.bool = ...) -> list[Element]: ...
