# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeAbelianMonoidFactory:
    def create_key(self, n: builtins.int, names: builtins.object) -> _SageObject: ...
    def create_object(self, version: builtins.object, key: builtins.object) -> _SageObject: ...

FreeAbelianMonoid_factory: _SageObject
def FreeAbelianMonoid(index_set: builtins.object = ..., names: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...

class FreeAbelianMonoid_class:
    Element: _SageObject
    def __init__(self, n: builtins.int, names: builtins.object) -> None: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def gen(self, i: builtins.int = ...) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def ngens(self) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
