import builtins

class _SageObject: ...

class FreeMonoid:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        index_set: builtins.object = ...,
        names: builtins.object = ...,
        commutative: builtins.bool = ...,
        **kwds: builtins.object,
    ) -> _SageObject: ...
    Element: _SageObject

    def __init__(self, n: builtins.int, names: builtins.object = ...) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def gen(self, i: builtins.int = ...) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
