# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class StringMonoid_class:
    def __init__(self, n: builtins.int, alphabet: builtins.tuple[_SageObject, ...] = ...) -> None: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def alphabet(self) -> builtins.tuple[_SageObject, ...]: ...
    def one(self) -> _SageObject: ...
    def gen(self, i: builtins.int = ...) -> _SageObject: ...

class BinaryStringMonoid:
    def __init__(self) -> None: ...
    def __call__(self, x: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def encoding(self, S: builtins.object, padic: builtins.bool = ...) -> _SageObject: ...

BinaryStrings: _SageObject
class OctalStringMonoid:
    def __init__(self) -> None: ...
    def __call__(self, x: builtins.object, check: builtins.bool = ...) -> _SageObject: ...

OctalStrings: _SageObject
class HexadecimalStringMonoid:
    def __init__(self) -> None: ...
    def __call__(self, x: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def encoding(self, S: builtins.object, padic: builtins.bool = ...) -> _SageObject: ...

HexadecimalStrings: _SageObject
class Radix64StringMonoid:
    def __init__(self) -> None: ...
    def __call__(self, x: builtins.object, check: builtins.bool = ...) -> _SageObject: ...

Radix64Strings: _SageObject
class AlphabeticStringMonoid:
    def __init__(self) -> None: ...
    def __call__(self, x: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def characteristic_frequency(self, table_name: builtins.str = ...) -> _SageObject: ...
    def encoding(self, S: builtins.object) -> _SageObject: ...

AlphabeticStrings: _SageObject
