import builtins

from sage.structure.element import Element

class _SageObject: ...

class TraceMonoidElement:
    def lex_normal_form(self) -> _SageObject: ...
    def foata_normal_form(self) -> tuple[Element, ...]: ...
    def dependence_graph(self) -> _SageObject: ...
    def hasse_diagram(self, algorithm: builtins.str = ...) -> _SageObject: ...
    def min_hasse_diagram(self) -> _SageObject: ...
    def naive_hasse_diagram(self) -> _SageObject: ...
    def alphabet(self) -> _SageObject: ...
    def projection(self, letters: builtins.object) -> _SageObject: ...
    def multiplicative_order(self) -> _SageObject: ...

class TraceMonoid:
    Element: _SageObject

    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        M: builtins.int = ...,
        I: builtins.int = ...,
        names: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self, M: builtins.int, I: builtins.int, names: builtins.object
    ) -> None: ...
    def ngens(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def gen(self, i: builtins.int = ...) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def independence(self) -> _SageObject: ...
    def dependence(self) -> _SageObject: ...
    def dependence_graph(self) -> _SageObject: ...
    def independence_graph(self) -> _SageObject: ...
    def dependence_polynomial(self, t: builtins.object = ...) -> _SageObject: ...
    def number_of_words(self, length: builtins.int) -> _SageObject: ...
    def words(self, length: builtins.int) -> _SageObject: ...
