# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LabelledBranching:
    def __cinit__(self, n: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def add_gen(self, gen: builtins.object) -> _SageObject: ...
    def has_empty_intersection(self, part: builtins.object) -> builtins.bool: ...
    def small_generating_set(self) -> _SageObject: ...
    def get_order(self) -> _SageObject: ...

class PartitionRefinement_generic:
    def __cinit__(self, n: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def get_canonical_form(self) -> _SageObject: ...
    def get_transporter(self) -> _SageObject: ...
    def get_autom_gens(self) -> _SageObject: ...
    def get_autom_order_permutation(self) -> _SageObject: ...
    def len(self) -> _SageObject: ...
