# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def view_list(L: builtins.object) -> _SageObject: ...

def picture_set(A: builtins.object, L: builtins.object) -> builtins.set[_SageObject]: ...

class Minimog:
    def __init__(self, type: builtins.str = ...) -> None: ...
    def print_kitten(self) -> _SageObject: ...
    def find_hexad0(self, pts: builtins.object) -> _SageObject: ...
    def find_hexad1(self, pts: builtins.object) -> _SageObject: ...
    def find_hexad2(self, pts: builtins.object, x0: builtins.object) -> _SageObject: ...
    def find_hexad3(self, pts: builtins.object, x0: builtins.object, x1: builtins.object) -> _SageObject: ...
    def find_hexad(self, pts: builtins.object) -> _SageObject: ...
    def blackjack_move(self, L0: builtins.object) -> _SageObject: ...
