import builtins

class _SageObject: ...

class BasesOfQSymOrNCSF:
    def super_categories(self) -> _SageObject: ...

    class ParentMethods:
        def __getitem__(
            self, c: builtins.object, *rest: builtins.object
        ) -> _SageObject: ...
        def one_basis(self) -> _SageObject: ...
        def sum_of_finer_compositions(
            self, composition: builtins.object
        ) -> _SageObject: ...
        def sum_of_fatter_compositions(
            self, composition: builtins.object
        ) -> _SageObject: ...
        def alternating_sum_of_compositions(self, n: builtins.int) -> _SageObject: ...
        def alternating_sum_of_finer_compositions(
            self, composition: builtins.object, conjugate: builtins.bool = ...
        ) -> _SageObject: ...
        def alternating_sum_of_fatter_compositions(
            self, composition: builtins.object
        ) -> _SageObject: ...
        def sum_of_partition_rearrangements(
            self, par: builtins.object
        ) -> _SageObject: ...
        def degree_on_basis(self, I: builtins.int) -> _SageObject: ...
        def skew(
            self, x: builtins.object, y: builtins.object, side: builtins.str = ...
        ) -> _SageObject: ...
        def duality_pairing(
            self, x: builtins.object, y: builtins.object
        ) -> _SageObject: ...
        def duality_pairing_by_coercion(
            self, x: builtins.object, y: builtins.object
        ) -> _SageObject: ...
        def duality_pairing_matrix(
            self, basis: builtins.object, degree: builtins.int
        ) -> _SageObject: ...
        def counit_on_basis(self, I: builtins.int) -> _SageObject: ...
        def degree_negation(self, element: builtins.object) -> _SageObject: ...

    class ElementMethods:
        def degree_negation(self) -> _SageObject: ...
        def duality_pairing(self, y: builtins.object) -> _SageObject: ...
        def skew_by(
            self, y: builtins.object, side: builtins.str = ...
        ) -> _SageObject: ...
        def degree(self) -> _SageObject: ...

class AlgebraMorphism:
    def __init__(
        self,
        domain: builtins.object,
        on_generators: builtins.object,
        position: builtins.int = ...,
        codomain: builtins.object = ...,
        category: builtins.object = ...,
        anti: builtins.bool = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class GradedModulesWithInternalProduct:
    def super_categories(self) -> _SageObject: ...

    class ParentMethods:
        def internal_product_on_basis(
            self, I: builtins.int, J: builtins.int
        ) -> _SageObject: ...
        def internal_product(self) -> _SageObject: ...
        itensor: _SageObject
        kronecker_product: _SageObject

    class ElementMethods:
        def internal_product(self, other: builtins.object) -> _SageObject: ...
        itensor: _SageObject
        kronecker_product: _SageObject

    class Realizations:
        class ParentMethods:
            def internal_product_by_coercion(
                self, left: builtins.object, right: builtins.object
            ) -> _SageObject: ...
