# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GenericSDPBackend:
    def base_ring(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def add_variable(self, obj: builtins.object = ..., name: builtins.object = ...) -> _SageObject: ...
    def add_variables(self, n: builtins.object, names: builtins.object = ...) -> _SageObject: ...
    def set_sense(self, sense: builtins.object) -> _SageObject: ...
    def objective_coefficient(self, variable: builtins.object, coeff: builtins.object = ...) -> _SageObject: ...
    def set_objective(self, coeff: builtins.object, d: builtins.object = ...) -> _SageObject: ...
    def add_linear_constraint(self, coefficients: builtins.object, name: builtins.object = ...) -> _SageObject: ...
    def add_linear_constraints(self, number: builtins.object, names: builtins.object = ...) -> _SageObject: ...
    def solve(self) -> _SageObject: ...
    def get_objective_value(self) -> _SageObject: ...
    def get_variable_value(self, variable: builtins.object) -> _SageObject: ...
    def ncols(self) -> _SageObject: ...
    def nrows(self) -> _SageObject: ...
    def is_maximization(self) -> builtins.bool: ...
    def problem_name(self, name: builtins.object = ...) -> _SageObject: ...
    def row(self, i: builtins.object) -> _SageObject: ...
    def row_name(self, index: builtins.object) -> _SageObject: ...
    def col_name(self, index: builtins.object) -> _SageObject: ...
    def dual_variable(self, i: builtins.object, sparse: builtins.object = ...) -> _SageObject: ...
    def slack(self, i: builtins.object, sparse: builtins.object = ...) -> _SageObject: ...
    def solver_parameter(self, name: builtins.object, value: builtins.object = ...) -> _SageObject: ...

default_solver: _SageObject
def default_sdp_solver(solver: builtins.object = ...) -> _SageObject: ...

def get_solver(solver: builtins.object = ..., base_ring: builtins.object = ...) -> _SageObject: ...
