# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GLPKExactBackend:
    def __cinit__(self, maximization: builtins.object = ...) -> _SageObject: ...
    def add_variable(self, lower_bound: builtins.object = ..., upper_bound: builtins.object = ..., binary: builtins.object = ..., continuous: builtins.object = ..., integer: builtins.object = ..., obj: builtins.object = ..., name: builtins.object = ...) -> _SageObject: ...
    def add_variables(self, number: builtins.object, lower_bound: builtins.object = ..., upper_bound: builtins.object = ..., binary: builtins.object = ..., continuous: builtins.object = ..., integer: builtins.object = ..., obj: builtins.object = ..., names: builtins.object = ...) -> _SageObject: ...
    def set_variable_type(self, variable: builtins.object, vtype: builtins.object) -> _SageObject: ...
