from collections.abc import Iterator, Sequence
from typing import Self

from sage.structure.sage_object import SageObject

type Breakpoint = int | tuple[int, Sequence[int]]

class CharacterArt(SageObject):
    def __init__(
        self,
        lines: Sequence[str] = ...,
        breakpoints: Sequence[Breakpoint] = ...,
        baseline: int | None = ...,
    ) -> None: ...
    @classmethod
    def empty(cls) -> Self: ...
    def __getitem__(self, key: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def _repr_(self) -> str: ...
    def __format__(self, fmt: str) -> str: ...
    def get_baseline(self) -> int: ...
    def _isatty(self) -> bool: ...
    def _terminal_width(self) -> int: ...
    def _splitting_points(self, size: int, offset: int = ...) -> Iterator[int]: ...
    def _split_repr_(self, size: int) -> str: ...
    def split(self, pos: int) -> tuple[Self, Self]: ...
    @staticmethod
    def _compute_new_baseline(obj1: CharacterArt, obj2: CharacterArt) -> int: ...
    @staticmethod
    def _compute_new_h(obj1: CharacterArt, obj2: CharacterArt) -> int: ...
    def width(self) -> int: ...
    def __len__(self) -> int: ...
    def height(self) -> int: ...
    def __add__(self, Nelt: Self) -> Self: ...
    def __mul__(self, Nelt: Self) -> Self: ...

def _shifted_breakpoints(breakpoints: Sequence[Breakpoint], offset: int) -> Iterator[Breakpoint]: ...
