# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CharacterArtFactory:
    def __init__(self, art_type: builtins.object, string_type: builtins.object, magic_method_name: builtins.str, parenthesis: builtins.object, square_bracet: builtins.object, curly_brace: builtins.object) -> None: ...
    def build(self, obj: builtins.object, baseline: builtins.object = ...) -> _SageObject: ...
    def build_empty(self) -> _SageObject: ...
    def build_from_magic_method(self, obj: builtins.object, baseline: builtins.object = ...) -> _SageObject: ...
    def build_from_string(self, obj: builtins.object, baseline: builtins.int = ...) -> _SageObject: ...
    def build_container(self, content: builtins.object, left_border: builtins.object, right_border: builtins.object, baseline: builtins.int = ...) -> _SageObject: ...
    def build_set(self, s: builtins.object, baseline: builtins.int = ...) -> _SageObject: ...
    def build_dict(self, d: builtins.object, baseline: builtins.int = ...) -> _SageObject: ...
    def build_list(self, l: builtins.object, baseline: builtins.int = ...) -> _SageObject: ...
    def build_tuple(self, t: builtins.object, baseline: builtins.int = ...) -> _SageObject: ...
    def concatenate(self, iterable: builtins.object, separator: builtins.object, empty: builtins.object = ..., baseline: builtins.int = ..., nested: builtins.bool = ...) -> _SageObject: ...
    def parse_keywords(self, kwds: builtins.object) -> _SageObject: ...
