# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def bitset_chars(s: builtins.object, bits: builtins.object, zero: builtins.object = ..., one: builtins.object = ...) -> _SageObject: ...

def bitset_from_char(bits: builtins.object, s: builtins.object, zero: builtins.object = ..., one: builtins.object = ...) -> _SageObject: ...

def bitset_from_str(bits: builtins.object, s: builtins.object, zero: builtins.object = ..., one: builtins.object = ...) -> _SageObject: ...

def bitset_string(bits: builtins.object) -> _SageObject: ...

def bitset_bytes(bits: builtins.object) -> _SageObject: ...

def bitset_list(bits: builtins.object) -> _SageObject: ...

def bitset_pickle(bs: builtins.object) -> _SageObject: ...

def bitset_unpickle(bs: builtins.object, input: builtins.object) -> _SageObject: ...
