from collections.abc import Iterator
from typing import Self

class FrozenBitset:
    def __init__(self, iter: object | None = None, capacity: int | None = None) -> None: ...
    def __getstate__(self) -> tuple[object, ...]: ...
    def __setstate__(self, state: tuple[object, ...]) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
    def __reversed__(self) -> Iterator[int]: ...
    def _larger_capacity_(self, capacity: int) -> FrozenBitset: ...
    def capacity(self) -> int: ...
    def __hash__(self) -> int: ...
    def isempty(self) -> bool: ...
    def __richcmp__(self, other: FrozenBitset, op: int) -> bool: ...
    def issubset(self, other: FrozenBitset) -> bool: ...
    def issuperset(self, other: FrozenBitset) -> bool: ...
    def isdisjoint(self, other: FrozenBitset) -> bool: ...
    def __contains__(self, n: int) -> bool: ...
    def __len__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    def _union(self, other: FrozenBitset) -> FrozenBitset: ...
    def union(self, other: FrozenBitset) -> FrozenBitset: ...
    def __or__(self, other: FrozenBitset) -> FrozenBitset: ...
    def intersection(self, other: FrozenBitset) -> FrozenBitset: ...
    def __and__(self, other: FrozenBitset) -> FrozenBitset: ...
    def difference(self, other: FrozenBitset) -> FrozenBitset: ...
    def __sub__(self, other: FrozenBitset) -> FrozenBitset: ...
    def symmetric_difference(self, other: FrozenBitset) -> FrozenBitset: ...
    def __xor__(self, other: FrozenBitset) -> FrozenBitset: ...
    def complement(self) -> FrozenBitset: ...
    def __invert__(self) -> FrozenBitset: ...
    def __copy__(self) -> FrozenBitset: ...

class Bitset(FrozenBitset):
    def __copy__(self) -> Bitset: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: FrozenBitset, op: int) -> bool: ...
    def update(self, other: FrozenBitset) -> None: ...
    def __ior__(self, other: FrozenBitset) -> Self: ...
    def intersection_update(self, other: FrozenBitset) -> None: ...
    def __iand__(self, other: FrozenBitset) -> Self: ...
    def difference_update(self, other: FrozenBitset) -> None: ...
    def __isub__(self, other: FrozenBitset) -> Self: ...
    def symmetric_difference_update(self, other: FrozenBitset) -> None: ...
    def __ixor__(self, other: FrozenBitset) -> Self: ...
    def add(self, n: int) -> None: ...
    def remove(self, n: int) -> None: ...
    def discard(self, n: int) -> None: ...
    def pop(self) -> int: ...
    def clear(self) -> None: ...

def test_bitset(py_a: str, py_b: str, n: int) -> None: ...
def test_bitset_set_first_n(py_a: str, n: int) -> None: ...
def test_bitset_remove(py_a: str, n: int) -> None: ...
def test_bitset_pop(py_a: str) -> None: ...
def test_bitset_unpickle(data: tuple[object, ...]) -> None: ...
def test_bitset_copy_flex(py_a: str) -> None: ...