from collections.abc import Iterable

def iaxpy(a: object, X: dict[object, object], Y: dict[object, object], remove_zeros: bool = True, factor_on_left: bool = True) -> int: ...
def axpy(a: object, X: dict[object, object], Y: dict[object, object], factor_on_left: bool = True) -> dict[object, object]: ...
def negate(D: dict[object, object]) -> dict[object, object]: ...
def scal(a: object, D: dict[object, object], factor_on_left: bool = True) -> dict[object, object]: ...
def add(D: dict[object, object], D2: dict[object, object]) -> dict[object, object]: ...
def sum(dict_iter: Iterable[dict[object, object]]) -> dict[object, object]: ...
def linear_combination(dict_factor_iter: Iterable[tuple[dict[object, object], object]], factor_on_left: bool = True) -> dict[object, object]: ...
def sum_of_monomials(monomials: Iterable[object], scalar: object) -> dict[object, object]: ...
def sum_of_terms(index_coeff_pairs: Iterable[tuple[object, object]]) -> dict[object, object]: ...
def convert_remove_zeroes(D: dict[object, object], R: object) -> dict[object, object]: ...
