from sage.rings.integer import Integer

class ListOfPairs:
    def __getitem__(self, index: int) -> tuple[Integer, Integer]: ...
    def __setitem__(self, index: int, value: tuple[int, int] | list[int]) -> None: ...
