# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PairingHeap_class:
    def __bool__(self) -> builtins.bool: ...
    def empty(self) -> _SageObject: ...
    def full(self) -> _SageObject: ...
    def capacity(self) -> _SageObject: ...
    def size(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def top(self) -> _SageObject: ...
    def top_value(self) -> _SageObject: ...
    def pop(self) -> _SageObject: ...

class PairingHeap_of_n_integers:
    def __init__(self, n: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def push(self, item: builtins.object, value: builtins.object) -> _SageObject: ...
    def top(self) -> _SageObject: ...
    def top_item(self) -> _SageObject: ...
    def pop(self) -> _SageObject: ...
    def decrease(self, item: builtins.object, new_value: builtins.object) -> _SageObject: ...
    def __contains__(self, item: builtins.object) -> builtins.bool: ...
    def value(self, item: builtins.object) -> _SageObject: ...

class PairingHeap_of_n_hashables:
    def __init__(self, n: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def push(self, item: builtins.object, value: builtins.object) -> _SageObject: ...
    def top(self) -> _SageObject: ...
    def top_item(self) -> _SageObject: ...
    def pop(self) -> _SageObject: ...
    def decrease(self, item: builtins.object, new_value: builtins.object) -> _SageObject: ...
    def __contains__(self, item: builtins.object) -> builtins.bool: ...
    def value(self, item: builtins.object) -> _SageObject: ...
