# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SemimonomialTransformationGroup:
    Element: _SageObject
    def __init__(self, R: builtins.int, len: builtins.object) -> None: ...
    def base_ring(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def __contains__(self, item: builtins.object) -> builtins.bool: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def order(self) -> _SageObject: ...

class SemimonomialActionVec:
    def __init__(self, G: builtins.object, V: builtins.object, check: builtins.bool = ...) -> None: ...

class SemimonomialActionMat:
    def __init__(self, G: builtins.object, M: builtins.int, check: builtins.bool = ...) -> None: ...
