import builtins

from sage.rings.integer import Integer
from sage.structure.element import Element

class _SageObject: ...

class SemimonomialTransformationGroup:
    Element: _SageObject

    def __init__(self, R: builtins.int, len: builtins.object) -> None: ...
    def base_ring(self) -> _SageObject: ...
    def degree(self) -> Integer: ...
    def __contains__(self, item: object) -> bool: ...
    def gens(self) -> tuple[Element, ...]: ...
    def order(self) -> Integer: ...

class SemimonomialActionVec:
    def __init__(
        self, G: builtins.object, V: builtins.object, check: builtins.bool = ...
    ) -> None: ...

class SemimonomialActionMat:
    def __init__(
        self, G: builtins.object, M: builtins.int, check: builtins.bool = ...
    ) -> None: ...
