# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

x: _SageObject
def library_interact(decorator_target: builtins.object = ..., **widgets: builtins.object) -> _SageObject: ...

def html(obj: builtins.object) -> _SageObject: ...

def demo(n: builtins.int, m: builtins.int) -> _SageObject: ...

def taylor_polynomial(title: builtins.object, f: builtins.object, order: builtins.int) -> _SageObject: ...

def definite_integral(title: builtins.object, f: builtins.object, g: builtins.object, interval: builtins.object, x_range: builtins.object, selection: builtins.object) -> _SageObject: ...

def function_derivative(title: builtins.object, function: builtins.object, x_range: builtins.object, y_range: builtins.object) -> _SageObject: ...

def difference_quotient(title: builtins.object, f: builtins.object, interval: builtins.object, a: builtins.object, x0: builtins.object) -> _SageObject: ...

def quadratic_equation(A: builtins.object, B: builtins.object, C: builtins.object) -> _SageObject: ...

def trigonometric_properties_triangle(a0: builtins.object, a1: builtins.object, a2: builtins.object) -> _SageObject: ...

def unit_circle(function: builtins.object, x: builtins.object) -> _SageObject: ...

def special_points(title: builtins.object, a0: builtins.object, a1: builtins.object, a2: builtins.object, show_median: builtins.object, show_pb: builtins.object, show_alt: builtins.object, show_ab: builtins.object, show_incircle: builtins.object, show_euler: builtins.object) -> _SageObject: ...

def coin(n: builtins.int, interval: builtins.object) -> _SageObject: ...

def bisection_method(title: builtins.object, f: builtins.object, interval: builtins.object, d: builtins.object, maxn: builtins.object) -> _SageObject: ...

def secant_method(title: builtins.object, f: builtins.object, interval: builtins.object, d: builtins.object, maxn: builtins.object) -> _SageObject: ...

def newton_method(title: builtins.object, f: builtins.object, c: builtins.object, d: builtins.object, maxn: builtins.object, interval: builtins.object, list_steps: builtins.object) -> _SageObject: ...

def trapezoid_integration(title: builtins.object, f: builtins.object, n: builtins.int, interval_input: builtins.object, interval_s: builtins.object, interval_g: builtins.object, output_form: builtins.object) -> _SageObject: ...

def simpson_integration(title: builtins.object, f: builtins.object, n: builtins.int, interval_input: builtins.object, interval_s: builtins.object, interval_g: builtins.object, output_form: builtins.object) -> _SageObject: ...

def riemann_sum(title: builtins.object, f: builtins.object, n: builtins.int, hr1: builtins.object, interval_input: builtins.object, interval_s: builtins.object, interval_g: builtins.object, hr2: builtins.object, list_table: builtins.object, auto_update: builtins.bool = ...) -> _SageObject: ...

def function_tool(f: builtins.object, g: builtins.object, xrange: builtins.object, yrange: builtins.object, a: builtins.object, action: builtins.object, do_plot: builtins.object) -> _SageObject: ...

def julia(expo: builtins.object, c_real: builtins.object, c_imag: builtins.object, iterations: builtins.object, zoom_x: builtins.object, zoom_y: builtins.object, plot_points: builtins.object, dpi: builtins.object) -> _SageObject: ...

def mandelbrot(expo: builtins.object, iterations: builtins.object, zoom_x: builtins.object, zoom_y: builtins.object, plot_points: builtins.object, dpi: builtins.object) -> _SageObject: ...

def cellular_automaton(N: builtins.int, rule_number: builtins.object, size: builtins.int) -> _SageObject: ...

def polar_prime_spiral(interval: builtins.object, show_factors: builtins.object, highlight_primes: builtins.object, show_curves: builtins.object, n: builtins.int, dpi: builtins.object) -> _SageObject: ...
