from sage.structure.unique_representation import UniqueRepresentation
from sage.rings.integer import Integer
from sage.rings.infinity import PlusInfinity
from sage.groups.group import AbelianGroup as AbelianGroupBase
from sage.groups.abelian_gps.abelian_group_element import AbelianGroupElement
from sage.groups.abelian_gps.dual_abelian_group import DualAbelianGroup_class

class AbelianGroup_class(UniqueRepresentation, AbelianGroupBase):
    def is_isomorphic(self, right: object) -> bool: ...
    def is_subgroup(self, right: object) -> bool: ...
    def __le__(self, right: object) -> bool: ...
    def __ge__(self, right: object) -> bool: ...
    def __lt__(self, right: object) -> bool: ...
    def __gt__(self, right: object) -> bool: ...
    def is_trivial(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def dual_group(self, names: str = 'X', base_ring: object = None) -> DualAbelianGroup_class: ...
    def elementary_divisors(self) -> tuple[Integer, ...]: ...
    def exponent(self) -> Integer: ...
    def identity(self) -> AbelianGroupElement: ...
    def _group_notation(self, eldv: object) -> str: ...
    def _latex_(self) -> str: ...
    def _gap_init_(self) -> str: ...
    def gen(self, i: int = 0) -> AbelianGroupElement: ...
    def gens(self) -> tuple[AbelianGroupElement, ...]: ...
    def gens_orders(self) -> tuple[Integer, ...]: ...
    def invariants(self) -> tuple[Integer, ...]: ...
    def ngens(self) -> int: ...
    def order(self) -> Integer | PlusInfinity: ...
    def is_abelian(self) -> bool: ...
    def is_cyclic(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def subgroups(self) -> list[AbelianGroup_class]: ...

