from collections.abc import Iterator
from sage.structure.unique_representation import UniqueRepresentation
from sage.groups.group import AbelianGroup as AbelianGroupBase
from sage.rings.integer import Integer
from sage.rings.infinity import PlusInfinity
from sage.rings.ring import Ring
from sage.groups.abelian_gps.dual_abelian_group_element import DualAbelianGroupElement
from sage.groups.abelian_gps.abelian_group import AbelianGroup_class

class DualAbelianGroup_class(UniqueRepresentation, AbelianGroupBase):
    def group(self) -> AbelianGroup_class: ...
    def base_ring(self) -> Ring: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def random_element(self) -> DualAbelianGroupElement: ...
    def gen(self, i: int = 0) -> DualAbelianGroupElement: ...
    def gens(self) -> tuple[DualAbelianGroupElement, ...]: ...
    def ngens(self) -> int: ...
    def gens_orders(self) -> tuple[Integer, ...]: ...
    def invariants(self) -> tuple[Integer, ...]: ...
    def __contains__(self, X: object) -> bool: ...
    def order(self) -> Integer | PlusInfinity: ...
    def is_commutative(self) -> bool: ...
    def is_abelian(self) -> bool: ...
    def list(self) -> tuple[DualAbelianGroupElement, ...]: ...
    def __iter__(self) -> Iterator[DualAbelianGroupElement]: ...
