# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AbelianGroupElementBase:
    def __init__(self, parent: builtins.object, exponents: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def exponents(self) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def order(self) -> _SageObject: ...
    multiplicative_order: _SageObject
    def __pow__(self, n: builtins.int) -> Self: ...
    def __invert__(self) -> Self: ...
    def is_trivial(self) -> builtins.bool: ...
