from collections.abc import Callable
from typing import Self

from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.padics.padic_generic_element import pAdicGenericElement
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.rings.valuation.valuation import DiscretePseudoValuation
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.structure.unique_representation import UniqueRepresentation

DEFAULT_THRESHOLD_DELETION: pAdicGenericElement
STARTING_ADDITIONAL_PREC: pAdicGenericElement

class pRational(SageObject):
    def __init__(
        self,
        p: int | Integer,
        x: pAdicGenericElement | ElementConstructorInput,
        exponent: int | Integer | Rational = ...,
        valuation: DiscretePseudoValuation = ...,
    ) -> None: ...
    def reduce(self, prec: int | Integer) -> pAdicGenericElement: ...
    def reduce_relative(self, prec: int | Integer) -> pAdicGenericElement: ...
    def normalize(self) -> Self: ...
    def valuation(self) -> Integer | PlusInfinity: ...
    def is_p_power(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def __add__(self, other: pAdicGenericElement | ElementConstructorInput) -> Self: ...
    def __sub__(self, other: pAdicGenericElement | ElementConstructorInput) -> Self: ...
    def __neg__(self) -> Self: ...
    def __mul__(self, other: pAdicGenericElement | ElementConstructorInput) -> Self: ...
    def __truediv__(
        self, other: pAdicGenericElement | ElementConstructorInput
    ) -> Self: ...
    def __lshift__(self, n: int | Integer) -> pAdicGenericElement: ...
    def __rshift__(self, n: int | Integer) -> pAdicGenericElement: ...
    def unit_part(self) -> pAdicGenericElement: ...
    def xgcd(
        self, other: pAdicGenericElement | ElementConstructorInput
    ) -> pAdicGenericElement: ...
    def value(self) -> Integer | PlusInfinity: ...
    def list(self, prec: int | Integer) -> list[pAdicGenericElement]: ...

class DifferentialPrecisionGeneric(SageObject):
    def __init__(self, p: int | Integer, label: ElementConstructorInput) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def threshold_deletion(self, threshold: int | Integer = ...) -> Self: ...
    def prime(self) -> Self: ...
    def ambient_dimension(self) -> int | Integer: ...
    def dimension(self) -> int | Integer: ...
    def del_elements(self, threshold: int | Integer = ...) -> Self: ...
    def precision_lattice(self, elements: ElementConstructorInput = ...) -> Self: ...
    def diffused_digits(self, elements: ElementConstructorInput = ...) -> Self: ...
    def tracked_elements(
        self, values: ElementConstructorInput = ..., dead: ElementConstructorInput = ...
    ) -> Self: ...
    def history_enable(self) -> Self: ...
    def history_disable(self) -> Self: ...
    def history_clear(self) -> Self: ...
    def history(
        self,
        compact: ElementConstructorInput = ...,
        separate_reduce: ElementConstructorInput = ...,
        timings: ElementConstructorInput = ...,
        output_type: ElementConstructorInput = ...,
    ) -> Self: ...
    def timings(self, action: ElementConstructorInput = ...) -> Self: ...
    def _repr_(self) -> str: ...

class PrecisionLattice(UniqueRepresentation, DifferentialPrecisionGeneric):
    def __init__(self, p: int | Integer, label: ElementConstructorInput) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def dimension(self) -> int | Integer: ...
    def reduce(
        self, index: int | Integer = ..., partial: int | Integer = ...
    ) -> pAdicGenericElement: ...
    def del_elements(self, threshold: int | Integer = ...) -> pAdicGenericElement: ...
    def precision_lattice(
        self, elements: int | Integer = ...
    ) -> pAdicGenericElement: ...

class PrecisionModule(UniqueRepresentation, DifferentialPrecisionGeneric):
    def __init__(self, p: int | Integer, label: Ring, prec: int | Integer) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def internal_prec(self) -> pAdicGenericElement: ...
    def dimension(self) -> int | Integer: ...
    def is_lattice(self) -> bool: ...
    def del_elements(self, threshold: int | Integer = ...) -> pAdicGenericElement: ...
    def precision_lattice(
        self, elements: ElementConstructorInput = ...
    ) -> pAdicGenericElement: ...

class pAdicLatticeElementWeakProxy(pAdicGenericElement):
    def __init__(
        self,
        element: pAdicLatticeElementWeakProxy | ElementConstructorInput,
        callback: ElementConstructorInput = ...,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __call__(self) -> Self: ...

def list_of_padics(elements: ElementConstructorInput) -> pAdicGenericElement: ...
