# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

DEFAULT_THRESHOLD_DELETION: _SageObject
STARTING_ADDITIONAL_PREC: _SageObject
class pRational:
    def __init__(self, p: builtins.int, x: builtins.object, exponent: builtins.int = ..., valuation: builtins.object = ...) -> None: ...
    def reduce(self, prec: builtins.int) -> _SageObject: ...
    def reduce_relative(self, prec: builtins.int) -> _SageObject: ...
    def normalize(self) -> _SageObject: ...
    def valuation(self) -> _SageObject: ...
    def is_p_power(self) -> builtins.bool: ...
    def is_zero(self) -> builtins.bool: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __sub__(self, other: builtins.object) -> Self: ...
    def __neg__(self) -> Self: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __truediv__(self, other: builtins.object) -> Self: ...
    def __lshift__(self, n: builtins.int) -> Self: ...
    def __rshift__(self, n: builtins.int) -> Self: ...
    def unit_part(self) -> _SageObject: ...
    def xgcd(self, other: builtins.object) -> _SageObject: ...
    def value(self) -> _SageObject: ...
    def list(self, prec: builtins.int) -> _SageObject: ...

class DifferentialPrecisionGeneric:
    def __init__(self, p: builtins.int, label: builtins.str) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def threshold_deletion(self, threshold: builtins.object = ...) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def ambient_dimension(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def del_elements(self, threshold: builtins.object = ...) -> _SageObject: ...
    def precision_lattice(self, elements: builtins.object = ...) -> _SageObject: ...
    def diffused_digits(self, elements: builtins.object = ...) -> _SageObject: ...
    def tracked_elements(self, values: builtins.bool = ..., dead: builtins.bool = ...) -> _SageObject: ...
    def history_enable(self) -> _SageObject: ...
    def history_disable(self) -> _SageObject: ...
    def history_clear(self) -> _SageObject: ...
    def history(self, compact: builtins.bool = ..., separate_reduce: builtins.bool = ..., timings: builtins.bool = ..., output_type: builtins.str = ...) -> _SageObject: ...
    def timings(self, action: builtins.object = ...) -> _SageObject: ...

class PrecisionLattice:
    def __init__(self, p: builtins.int, label: builtins.str) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def dimension(self) -> _SageObject: ...
    def reduce(self, index: builtins.int = ..., partial: builtins.bool = ...) -> _SageObject: ...
    def del_elements(self, threshold: builtins.object = ...) -> _SageObject: ...
    def precision_lattice(self, elements: builtins.object = ...) -> _SageObject: ...

class PrecisionModule:
    def __init__(self, p: builtins.int, label: builtins.str, prec: builtins.int) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def internal_prec(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def is_lattice(self) -> builtins.bool: ...
    def del_elements(self, threshold: builtins.object = ...) -> _SageObject: ...
    def precision_lattice(self, elements: builtins.object = ...) -> _SageObject: ...

class pAdicLatticeElementWeakProxy:
    def __init__(self, element: builtins.object, callback: builtins.object = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self) -> _SageObject: ...

def list_of_padics(elements: builtins.object) -> _SageObject: ...
