# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

python_min: _SageObject
python_max: _SageObject
def gauss_sum(a: builtins.object, p: builtins.int, f: builtins.object, prec: builtins.int = ..., factored: builtins.bool = ..., algorithm: builtins.str = ..., parent: builtins.object = ...) -> _SageObject: ...

def min(*L: builtins.object) -> _SageObject: ...

def max(*L: builtins.object) -> _SageObject: ...

def precprint(prec_type: builtins.object, prec_cap: builtins.object, p: builtins.int) -> _SageObject: ...

def trim_zeros(L: builtins.object) -> _SageObject: ...
