# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FrobeniusEndomorphism_padics:
    def __init__(self, domain: builtins.object, n: builtins.object = ...) -> None: ...
    def order(self) -> _SageObject: ...
    def power(self) -> _SageObject: ...
    def __pow__(self, n: builtins.object, modulus: builtins.object) -> Self: ...
    def is_injective(self) -> builtins.bool: ...
    def is_surjective(self) -> builtins.bool: ...
    def is_identity(self) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
