from typing import Self

from sage.all import i
from sage.arith.misc import gcd
from sage.calculus.predefined import s
from sage.categories.category import Category
from sage.categories.morphism import Morphism
from sage.functions.transcendental import zeta
from sage.interfaces.r import R
from sage.rings.finite_rings.finite_field_constructor import GF
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.order import FunctionFieldOrder
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.infinity import MinusInfinity, PlusInfinity
from sage.rings.integer import Integer
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.number_field.order import Order as NumberFieldOrder
from sage.rings.padics.local_generic import LocalGeneric
from sage.rings.padics.morphism import FrobeniusEndomorphism_padics
from sage.rings.padics.padic_generic_element import pAdicGenericElement
from sage.rings.padics.padic_printing import pAdicPrinter
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.ring import Field, Ring
from sage.structure.element import Element
from sage.structure.parent import ElementConstructorInput, Parent

class pAdicGeneric(LocalGeneric):
    def prime(self) -> Integer: ...
    def precision_cap(self) -> Integer: ...
    def is_capped_relative(self) -> bool: ...
    def is_capped_absolute(self) -> bool: ...
    def an_element(self) -> Integer: ...
    def some_elements(self) -> list[Integer]: ...
    def random_element(self) -> Element: ...
    def characteristic(self) -> int: ...
    def __init__(
        self,
        base: Ring,
        p: int | Integer | FunctionFieldPlace | NumberFieldIdeal,
        prec: int | Integer | None,
        print_mode: Ring,
        names: str | tuple[str, ...] | None,
        element_class: Ring,
        category: Category | None = ...,
    ) -> None: ...
    def ngens(self) -> int: ...
    def gens(self) -> tuple: ...
    def __richcmp__(
        self,
        other: pAdicGenericElement | ElementConstructorInput,
        op: ElementConstructorInput,
    ) -> pAdicGenericElement: ...
    def print_mode(self) -> str: ...
    def uniformizer_pow(self, n: int | Integer) -> pAdicGenericElement: ...
    def residue_characteristic(self) -> Integer: ...
    def residue_class_field(self) -> GF: ...
    def residue_field(self) -> Field | tuple[Field, Morphism, Morphism]: ...
    def residue_ring(self, n: int | Integer) -> Ring: ...
    def residue_system(self) -> list[pAdicGenericElement]: ...
    def fraction_field(
        self, print_mode: Polynomial | MPolynomial | None = ...
    ) -> pAdicGenericElement | Self: ...
    def integer_ring(
        self, print_mode: int | Integer | None = ...
    ) -> pAdicGenericElement | Self: ...
    def teichmuller(
        self,
        x: pAdicGenericElement | ElementConstructorInput,
        prec: int | Integer | None = ...,
    ) -> pAdicGenericElement: ...
    def teichmuller_system(self) -> list[pAdicGenericElement]: ...
    def extension(
        self,
        modulus: Polynomial | MPolynomial,
        prec: int | Integer | None = ...,
        names: str | tuple[str, ...] | None = ...,
        print_mode: ElementConstructorInput | None = ...,
        implementation: str | None = ...,
        **kwds: ElementConstructorInput,
    ) -> FunctionField | NumberField_generic | tuple[Parent, Morphism, Morphism]: ...
    def frobenius_endomorphism(
        self, n: int | Integer = ...
    ) -> FrobeniusEndomorphism_padics: ...
    def valuation(self) -> Integer | Rational | PlusInfinity | MinusInfinity: ...
    def primitive_root_of_unity(
        self,
        n: int | Integer | None = ...,
        order: NumberFieldOrder | FunctionFieldOrder = ...,
    ) -> pAdicGenericElement | tuple[pAdicGenericElement, gcd | Integer | s]: ...
    def roots_of_unity(self, n: int | Integer | None = ...) -> list[zeta | i]: ...

class ResidueReductionMap(Morphism):
    def is_surjective(self) -> bool: ...
    def is_injective(self) -> bool: ...
    def _call_(
        self, x: pAdicGenericElement | ElementConstructorInput
    ) -> pAdicGenericElement: ...
    def section(self) -> Morphism: ...
    def _richcmp_(
        self, other: pAdicGenericElement | ElementConstructorInput, op: Ring
    ) -> bool: ...

class ResidueLiftingMap(Morphism):
    def _call_(self, x: pAdicGenericElement | ElementConstructorInput) -> R: ...
    def _richcmp_(
        self, other: pAdicGenericElement | ElementConstructorInput, op: Ring
    ) -> bool: ...

def local_print_mode(
    obj: ElementConstructorInput,
    print_options: ElementConstructorInput,
    pos: ElementConstructorInput | None = ...,
    ram_name: str | None = ...,
) -> pAdicPrinter: ...
