from collections.abc import Callable, Iterator
from typing import Self

from sage.categories.morphism import Morphism
from sage.rings.function_field.function_field import FunctionField
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.morphism import RingHomomorphism, RingMap
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.padics.padic_generic import pAdicGeneric
from sage.rings.padics.padic_generic_element import pAdicGenericElement
from sage.rings.padics.pow_computer import PowComputer_base
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.ring import Field, Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject

class CAElement:
    def __copy__(self) -> Self: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def _neg_(self) -> Self: ...
    def _add_(self, _right: ElementConstructorInput) -> Self: ...
    def _sub_(self, _right: ElementConstructorInput) -> Self: ...
    def __invert__(self) -> Self: ...
    def _mul_(self, _right: ElementConstructorInput) -> Self: ...
    def _div_(self, right: CAElement | ElementConstructorInput) -> Self: ...
    def _quo_rem(self, _right: ElementConstructorInput) -> tuple[Self, Self]: ...
    def __pow__(
        self, _right: ElementConstructorInput, dummy: ElementConstructorInput
    ) -> Self: ...
    def add_bigoh(self, absprec: int | Integer | None) -> Self: ...
    def is_zero(self, absprec: int | Integer | None = ...) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_equal_to(
        self, _right: ElementConstructorInput, absprec: int | Integer | None = ...
    ) -> bool: ...
    def _cache_key(self) -> tuple[ElementConstructorInput, ...]: ...
    def _teichmuller_set_unsafe(self) -> None: ...
    def _polynomial_list(self, pad: ElementConstructorInput = ...) -> list[Integer]: ...
    def polynomial(self, var: str = ...) -> Polynomial: ...
    def precision_absolute(self) -> Integer | PlusInfinity: ...
    def precision_relative(self) -> Integer | PlusInfinity: ...
    def unit_part(self) -> Self: ...
    def val_unit(self) -> tuple[Integer | PlusInfinity, Self]: ...
    def __hash__(self) -> int: ...

class expansion_mode: ...

class PowComputer_(PowComputer_base):
    def __init__(
        self,
        prime: int | Integer,
        cache_limit: ElementConstructorInput,
        prec_cap: ElementConstructorInput,
        ram_prec_cap: ElementConstructorInput,
        in_field: ElementConstructorInput,
    ) -> None: ...

class pAdicCappedAbsoluteElement(CAElement):
    def lift(self) -> pAdicCappedAbsoluteElement: ...
    def lift_c(self) -> Self: ...
    def __pari__(self) -> Self: ...
    def residue(
        self,
        absprec: int | Integer = ...,
        field: pAdicGeneric = ...,
        check_prec: ElementConstructorInput = ...,
    ) -> Self: ...
    def multiplicative_order(self) -> Self: ...
    def _exp_binary_splitting(self, aprec: ElementConstructorInput) -> Self: ...
    def _exp_newton(
        self,
        aprec: ElementConstructorInput,
        log_algorithm: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def _integer_(
        self, Z: pAdicCappedAbsoluteElement | ElementConstructorInput | None = ...
    ) -> Integer | None: ...
    def _log_binary_splitting(
        self, aprec: ElementConstructorInput, mina: ElementConstructorInput = ...
    ) -> Self: ...

def make_pAdicCappedAbsoluteElement(
    parent: pAdicGeneric,
    x: pAdicGenericElement | ElementConstructorInput,
    absprec: int | Integer,
) -> pAdicGenericElement: ...

class pAdicTemplateElement(pAdicGenericElement):
    def __init__(
        self,
        parent: Parent,
        x: pAdicTemplateElement | ElementConstructorInput,
        absprec: int | Integer | None = ...,
        relprec: int | Integer | None = ...,
    ) -> None: ...
    def __lshift__(self, shift: ElementConstructorInput) -> Self: ...
    def __rshift__(self, shift: ElementConstructorInput) -> Self: ...
    def lift_to_precision(self, absprec: int | Integer | None = ...) -> Self: ...
    def expansion(
        self,
        n: int | Integer | None = ...,
        lift_mode: ElementConstructorInput = ...,
        start_val: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def teichmuller_expansion(self, n: int | Integer | None = ...) -> Self: ...
    def _ext_p_list(self, pos: ElementConstructorInput) -> Self: ...
    def unit_part(self) -> Self: ...
    def _prime_pow(self) -> Self: ...
    def residue(
        self,
        absprec: int | Integer | None = ...,
        field: pAdicGeneric | None = ...,
        check_prec: ElementConstructorInput = ...,
    ) -> Self: ...

class ExpansionIter(SageObject):
    def __cinit__(
        self, elt: pAdicTemplateElement, prec: int, mode: expansion_mode
    ) -> pAdicGenericElement: ...
    def __iter__(self) -> Iterator[pAdicGenericElement]: ...
    def __len__(self) -> int | Integer: ...
    def __next__(self) -> pAdicGenericElement: ...

class ExpansionIterable(SageObject):
    def __cinit__(
        self, elt: pAdicTemplateElement, prec: int, val_shift: int, mode: expansion_mode
    ) -> pAdicGenericElement: ...
    def __iter__(self) -> Iterator[pAdicGenericElement]: ...
    def __len__(self) -> int | Integer: ...
    def __getitem__(self, n: int | Integer) -> pAdicGenericElement: ...

class pAdicCoercion_ZZ_CA(RingHomomorphism):
    def __init__(self, R: Ring) -> None: ...
    def _call_(
        self, x: pAdicGenericElement | ElementConstructorInput
    ) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        x: pAdicGenericElement | ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...
    def section(self) -> Morphism: ...

class pAdicConvert_CA_ZZ(RingMap):
    def __init__(self, R: Ring) -> None: ...
    def _call_(self, _x: ElementConstructorInput) -> pAdicGenericElement: ...

class pAdicConvert_QQ_CA(Morphism):
    def __init__(self, R: Ring) -> None: ...
    def _call_(
        self, x: pAdicGenericElement | ElementConstructorInput
    ) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        x: pAdicGenericElement | ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...

class pAdicCoercion_CA_frac_field(RingHomomorphism):
    def __init__(
        self, R: Ring, K: NumberField_generic | FunctionField | Field
    ) -> None: ...
    def _call_(self, _x: ElementConstructorInput) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        _x: ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...
    def section(self) -> Morphism: ...
    def is_injective(self) -> bool: ...
    def is_surjective(self) -> bool: ...

class pAdicConvert_CA_frac_field(Morphism):
    def __init__(
        self, K: NumberField_generic | FunctionField | Field, R: Ring
    ) -> None: ...
    def _call_(self, _x: ElementConstructorInput) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        _x: ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...

def unpickle_cae_v2[CAElementT: CAElement](
    cls: type[CAElementT],
    parent: Parent,
    value: RingElement | int | Integer | Rational,
    absprec: int | Integer | None,
) -> CAElementT: ...
