from collections.abc import Callable
from typing import Self

from sage.rings.integer import Integer
from sage.rings.padics.padic_generic import pAdicGeneric
from sage.rings.padics.padic_generic_element import pAdicGenericElement
from sage.rings.padics.padic_ZZ_pX_element import pAdicZZpXElement
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput

class pAdicZZpXCAElement(pAdicZZpXElement):
    def __init__(
        self,
        parent: pAdicGeneric,
        x: pAdicZZpXCAElement | ElementConstructorInput,
        absprec: int | Integer = ...,
        relprec: int | Integer = ...,
        empty: ElementConstructorInput = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def __invert__(self) -> Self: ...
    def to_fraction_field(self) -> Self: ...
    def __lshift__(self, shift: ElementConstructorInput) -> Self: ...
    def __rshift__(self, shift: ElementConstructorInput) -> Self: ...
    def __pow__(self, _right: ElementConstructorInput, m: int | Integer) -> Self: ...
    def __copy__(self) -> Self: ...
    def is_zero(self, absprec: int | Integer = ...) -> bool: ...
    def polynomial(self, var: ElementConstructorInput = ...) -> Polynomial: ...
    def is_equal_to(
        self,
        right: pAdicZZpXCAElement | ElementConstructorInput,
        absprec: int | Integer = ...,
    ) -> bool: ...
    def lift_to_precision(self, absprec: int | Integer = ...) -> int | Integer: ...
    def expansion(
        self, n: int | Integer = ..., lift_mode: ElementConstructorInput = ...
    ) -> Self: ...
    def matrix_mod_pn(self) -> Self: ...
    def teichmuller_expansion(self, n: int | Integer = ...) -> Self: ...
    def precision_absolute(self) -> int | Integer: ...
    def precision_relative(self) -> int | Integer: ...
    def valuation_c(self) -> Self: ...
    def unit_part(self) -> Self: ...
    def ext_p_list(self, pos: ElementConstructorInput) -> Self: ...
    def _add_(self, _right: ElementConstructorInput) -> Self: ...
    def _div_(self, right: pAdicZZpXCAElement | ElementConstructorInput) -> Self: ...
    def _integer_(
        self, Z: pAdicZZpXCAElement | ElementConstructorInput | None = ...
    ) -> Integer | None: ...
    def _mul_(self, _right: ElementConstructorInput) -> Self: ...
    def _neg_(self) -> Self: ...
    def _ntl_rep(self) -> Self: ...
    def _ntl_rep_abs(self) -> Self: ...
    def _polynomial_list(self, pad: ElementConstructorInput = ...) -> Self: ...
    def _sub_(self, _right: ElementConstructorInput) -> Self: ...
    def _teichmuller_set_unsafe(self) -> Self: ...

def make_ZZpXCAElement(
    parent: pAdicGeneric,
    value: RingElement | int | Integer | Rational,
    absprec: int | Integer,
    version: int | tuple[int, ...],
) -> pAdicGenericElement: ...
