from collections.abc import Callable
from types import TracebackType
from typing import Self

from sage.rings.integer import Integer
from sage.rings.padics.padic_generic_element import pAdicGenericElement
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import Element, RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject

def pAdicPrinter(
    ring: Ring, options: ElementConstructorInput = ...
) -> pAdicGenericElement: ...

class pAdicPrinterDefaults(SageObject):
    def __init__(
        self,
        mode: str = ...,
        pos: ElementConstructorInput = ...,
        max_ram_terms: ElementConstructorInput = ...,
        max_unram_terms: ElementConstructorInput = ...,
        max_terse_terms: ElementConstructorInput = ...,
        sep: ElementConstructorInput = ...,
        alphabet: ElementConstructorInput = ...,
    ) -> None: ...
    def mode(self, mode: str = ...) -> pAdicGenericElement: ...
    def allow_negatives(
        self, neg: ElementConstructorInput = ...
    ) -> pAdicGenericElement: ...
    def max_series_terms(
        self, max: ElementConstructorInput = ...
    ) -> pAdicGenericElement: ...
    def max_unram_terms(
        self, max: ElementConstructorInput = ...
    ) -> pAdicGenericElement: ...
    def max_poly_terms(
        self, max: ElementConstructorInput = ...
    ) -> pAdicGenericElement: ...
    def sep(self, sep: ElementConstructorInput = ...) -> pAdicGenericElement: ...
    def alphabet(
        self, alphabet: ElementConstructorInput = ...
    ) -> pAdicGenericElement: ...

class pAdicPrinter_class(SageObject):
    def __init__(
        self,
        ring: Ring,
        mode: str,
        pos: ElementConstructorInput,
        ram_name: str,
        unram_name: str,
        var_name: str,
        max_ram_terms: ElementConstructorInput,
        max_unram_terms: ElementConstructorInput,
        max_terse_terms: ElementConstructorInput,
        sep: ElementConstructorInput,
        alphabet: ElementConstructorInput,
        show_prec: ElementConstructorInput,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def __richcmp__(
        self,
        other: pAdicGenericElement | ElementConstructorInput,
        op: ElementConstructorInput,
    ) -> pAdicGenericElement: ...
    def __enter__(self) -> pAdicGenericElement: ...
    def dict(self) -> dict[Element, pAdicGenericElement]: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def base_p_list(
        self,
        value: RingElement | int | Integer | Rational,
        pos: ElementConstructorInput,
    ) -> pAdicGenericElement: ...
    def repr_gen(
        self,
        elt: pAdicGenericElement | ElementConstructorInput,
        do_latex: ElementConstructorInput,
        pos: ElementConstructorInput = ...,
        mode: str = ...,
        ram_name: str = ...,
    ) -> pAdicGenericElement: ...
    def _repr_(self) -> str: ...
    def richcmp_modes(self, other: pAdicPrinter_class, op: int) -> bool: ...
    def _alphabet(self) -> pAdicGenericElement: ...
    def _base_p_list(
        self,
        value: RingElement | int | Integer | Rational,
        pos: ElementConstructorInput,
    ) -> pAdicGenericElement: ...
    def _max_ram_terms(self) -> pAdicGenericElement: ...
    def _max_terse_terms(self) -> pAdicGenericElement: ...
    def _max_unram_terms(self) -> pAdicGenericElement: ...
    def _pos(self) -> pAdicGenericElement: ...
    def _print_mode(self) -> pAdicGenericElement: ...
    def _ram_name(self) -> pAdicGenericElement: ...
    def _ring(self) -> pAdicGenericElement: ...
    def _sep(self) -> pAdicGenericElement: ...
    def _show_prec(self) -> pAdicGenericElement: ...
    def _uniformizer_name(self) -> pAdicGenericElement: ...
