# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class pAdicRingCappedRelative:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...

class pAdicRingCappedAbsolute:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...

class pAdicRingFloatingPoint:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...

class pAdicRingFixedMod:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...

class pAdicFieldCappedRelative:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...
    def random_element(self, algorithm: builtins.str = ...) -> _SageObject: ...

class pAdicFieldFloatingPoint:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...

class pAdicRingLattice:
    def __init__(self, p: builtins.int, prec: builtins.int, subtype: builtins.object, print_mode: builtins.object, names: builtins.object, label: builtins.str = ..., category: builtins.object = ...) -> None: ...
    def random_element(self, prec: builtins.int = ...) -> _SageObject: ...

class pAdicFieldLattice:
    def __init__(self, p: builtins.int, prec: builtins.int, subtype: builtins.object, print_mode: builtins.object, names: builtins.object, label: builtins.str = ..., category: builtins.object = ...) -> None: ...
    def random_element(self, prec: builtins.int = ..., integral: builtins.bool = ...) -> _SageObject: ...

class pAdicRingRelaxed:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...

class pAdicFieldRelaxed:
    def __init__(self, p: builtins.int, prec: builtins.int, print_mode: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...
