# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def pAdicPrinter(ring: builtins.object, options: builtins.object = ...) -> _SageObject: ...

class pAdicPrinterDefaults:
    def __init__(self, mode: builtins.object = ..., pos: builtins.object = ..., max_ram_terms: builtins.object = ..., max_unram_terms: builtins.object = ..., max_terse_terms: builtins.object = ..., sep: builtins.object = ..., alphabet: builtins.object = ...) -> None: ...
    def mode(self, mode: builtins.object = ...) -> _SageObject: ...
    def allow_negatives(self, neg: builtins.object = ...) -> _SageObject: ...
    def max_series_terms(self, max: builtins.object = ...) -> _SageObject: ...
    def max_unram_terms(self, max: builtins.object = ...) -> _SageObject: ...
    def max_poly_terms(self, max: builtins.object = ...) -> _SageObject: ...
    def sep(self, sep: builtins.object = ...) -> _SageObject: ...
    def alphabet(self, alphabet: builtins.object = ...) -> _SageObject: ...

class pAdicPrinter_class:
    def __init__(self, ring: builtins.object, mode: builtins.object, pos: builtins.object, ram_name: builtins.object, unram_name: builtins.object, var_name: builtins.object, max_ram_terms: builtins.object, max_unram_terms: builtins.object, max_terse_terms: builtins.object, sep: builtins.object, alphabet: builtins.object, show_prec: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __enter__(self) -> Self: ...
    def dict(self) -> _SageObject: ...
    def __exit__(self, type: builtins.object, value: builtins.object, traceback: builtins.object) -> builtins.bool | None: ...
    def base_p_list(self, value: builtins.object, pos: builtins.object) -> _SageObject: ...
    def repr_gen(self, elt: builtins.object, do_latex: builtins.object, pos: builtins.object = ..., mode: builtins.object = ..., ram_name: builtins.object = ...) -> _SageObject: ...
