from collections.abc import Callable, Iterator
from typing import Self

from sage.rings.infinity import MinusInfinity, PlusInfinity
from sage.rings.integer import Integer
from sage.rings.padics.padic_generic import pAdicGeneric
from sage.rings.padics.padic_generic_element import pAdicGenericElement
from sage.rings.rational import Rational
from sage.rings.real_mpfr import RealNumber
from sage.rings.valuation.valuation import DiscretePseudoValuation
from sage.structure.element import Element, RingElement
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject

class expansion_mode: ...

class RelaxedElement(pAdicGenericElement):
    def __init__(self, parent: Parent) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def digit(self, i: int | Integer) -> Self: ...
    def expansion(
        self,
        n: int | Integer | None = ...,
        lift_mode: ElementConstructorInput = ...,
        start_val: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def __getitem__(self, n: int | Integer) -> RelaxedElement: ...
    def slice(
        self,
        start: int | Integer | None = ...,
        stop: int | Integer | None = ...,
        bound: int | Integer | Rational | RealNumber = ...,
    ) -> Self: ...
    def _repr_(self) -> str: ...
    def is_equal_at_precision(
        self,
        right: RelaxedElement | ElementConstructorInput,
        prec: int | Integer | None,
    ) -> bool: ...
    def is_equal_to(
        self,
        right: RelaxedElement,
        prec: int | Integer | None = ...,
        secure: ElementConstructorInput | None = ...,
    ) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_exact(self) -> bool: ...
    def precision_absolute(self) -> Integer | PlusInfinity: ...
    def precision_relative(self) -> Integer | PlusInfinity: ...
    def precision_current(self) -> Self: ...
    def at_precision_absolute(
        self,
        prec: int | Integer | None = ...,
        permissive: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def add_bigoh(self, absprec: int | Integer | None) -> Self: ...
    def at_precision_relative(
        self,
        prec: int | Integer | None = ...,
        halt: ElementConstructorInput = ...,
        permissive: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def lift_to_precision(self, absprec: int | Integer | None = ...) -> Self: ...
    def valuation(
        self,
        halt: ElementConstructorInput = ...,
        secure: ElementConstructorInput | None = ...,
    ) -> Integer | Rational | PlusInfinity | MinusInfinity: ...
    def unit_part(self, halt: ElementConstructorInput = ...) -> Self: ...
    def val_unit(
        self, halt: ElementConstructorInput = ...
    ) -> tuple[Integer | PlusInfinity, Self]: ...
    def residue(
        self,
        absprec: int | Integer | None = ...,
        field: pAdicGeneric = ...,
        check_prec: ElementConstructorInput = ...,
    ) -> Self: ...
    def lift(self, absprec: int | Integer | None = ...) -> RelaxedElement: ...
    def __rshift__(self, s: RelaxedElement | ElementConstructorInput) -> Self: ...
    def __lshift__(self, s: RelaxedElement | ElementConstructorInput) -> Self: ...
    def _add_(self, other: RelaxedElement | ElementConstructorInput) -> Self: ...
    def _sub_(self, other: RelaxedElement | ElementConstructorInput) -> Self: ...
    def _neg_(self) -> Self: ...
    def _mul_(self, other: RelaxedElement | ElementConstructorInput) -> Self: ...
    def _div_(self, other: RelaxedElement | ElementConstructorInput) -> Self: ...
    def __invert__(self) -> Self: ...
    def inverse_of_unit(self) -> Self: ...
    def sqrt(self) -> Self | list[Self] | Element: ...
    def _test_pickling(self, **options: ElementConstructorInput) -> Self: ...
    def _test_nonzero_equal(self, **options: ElementConstructorInput) -> Self: ...

class RelaxedElement_abandon(RelaxedElement):
    def __init__(self) -> None: ...

class RelaxedElementWithDigits(RelaxedElement):
    def __cinit__(self) -> Self: ...

class RelaxedElement_zero(RelaxedElement):
    def __init__(self, parent: Parent) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_one(RelaxedElementWithDigits):
    def __init__(self, parent: Parent) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_bound(RelaxedElement):
    def __init__(
        self,
        parent: Parent,
        x: RelaxedElement,
        precbound: ElementConstructorInput | None = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_value(RelaxedElementWithDigits):
    def __init__(
        self,
        parent: Parent,
        value: RingElement | int | Integer | Rational,
        shift: int = ...,
        precbound: ElementConstructorInput | None = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_random(RelaxedElementWithDigits):
    def __init__(
        self,
        parent: Parent,
        valuation: DiscretePseudoValuation,
        precbound: ElementConstructorInput | None = ...,
        seed: ElementConstructorInput | None = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_slice(RelaxedElement):
    def __init__(
        self, parent: Parent, x: RelaxedElement, start: int, stop: int, shift: int
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_add(RelaxedElementWithDigits):
    def __init__(
        self, parent: Parent, x: RelaxedElement, y: RelaxedElement
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_sub(RelaxedElementWithDigits):
    def __init__(
        self, parent: Parent, x: RelaxedElement, y: RelaxedElement
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_mul(RelaxedElementWithDigits):
    def __cinit__(self) -> Self: ...
    def __init__(
        self, parent: Parent, x: RelaxedElement, y: RelaxedElement
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_muldigit(RelaxedElementWithDigits):
    def __init__(
        self, parent: Parent, x: RelaxedElement_div, y: RelaxedElement
    ) -> None: ...

class RelaxedElement_div(RelaxedElementWithDigits):
    def __cinit__(self) -> Self: ...
    def __init__(
        self,
        parent: Parent,
        num: RelaxedElement,
        denom: RelaxedElement,
        minval: int = ...,
        precbound: ElementConstructorInput | None = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_sqrt(RelaxedElementWithDigits):
    def __init__(self, parent: Parent, x: RelaxedElement) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_teichmuller(RelaxedElementWithDigits):
    def __init__(self, parent: Parent, xbar: ElementConstructorInput) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...

class RelaxedElement_unknown(RelaxedElementWithDigits):
    def __init__(
        self,
        parent: Parent,
        valuation: int,
        digits: ElementConstructorInput | None = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def set(self, definition: RelaxedElement) -> Self: ...

class RelaxedElement_zeroone(RelaxedElementWithDigits):
    def __init__(self, parent: Parent, valuation: int) -> None: ...

class ExpansionIter(SageObject):
    def __cinit__(self) -> pAdicGenericElement: ...
    def __init__(
        self, elt: RelaxedElement, mode: expansion_mode, start: int, stop: int
    ) -> None: ...
    def __len__(self) -> int | Integer: ...
    def __iter__(self) -> Iterator[pAdicGenericElement]: ...
    def __next__(self) -> pAdicGenericElement: ...

def unpickle_unknown(
    uid: ElementConstructorInput,
    cls: type[Parent] | None,
    parent: Parent,
    valuation: DiscretePseudoValuation,
    digits: ElementConstructorInput,
    definition: ElementConstructorInput,
) -> pAdicGenericElement: ...
