# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def check_ordp(a: builtins.object) -> _SageObject: ...

class pAdicZZpXCRElement:
    def __init__(self, parent: builtins.object, x: builtins.object, absprec: builtins.object = ..., relprec: builtins.object = ..., empty: builtins.object = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __invert__(self) -> Self: ...
    def __lshift__(self, shift: builtins.object) -> Self: ...
    def __rshift__(self, shift: builtins.object) -> Self: ...
    def __pow__(self, _right: builtins.object, m: builtins.object) -> Self: ...
    def __copy__(self) -> Self: ...
    def is_zero(self, absprec: builtins.object = ...) -> builtins.bool: ...
    def polynomial(self, var: builtins.object = ...) -> _SageObject: ...
    def is_equal_to(self, right: builtins.object, absprec: builtins.object = ...) -> builtins.bool: ...
    def lift_to_precision(self, absprec: builtins.object = ...) -> _SageObject: ...
    def expansion(self, n: builtins.object = ..., lift_mode: builtins.object = ...) -> _SageObject: ...
    def matrix_mod_pn(self) -> _SageObject: ...
    def teichmuller_expansion(self, n: builtins.object = ...) -> _SageObject: ...
    def precision_absolute(self) -> _SageObject: ...
    def precision_relative(self) -> _SageObject: ...
    def valuation_c(self) -> _SageObject: ...
    def unit_part(self) -> _SageObject: ...
    def ext_p_list(self, pos: builtins.object) -> _SageObject: ...

def make_ZZpXCRElement(parent: builtins.object, unit: builtins.object, ordp: builtins.object, relprec: builtins.object, version: builtins.object) -> _SageObject: ...
