from typing import Self

from sage.rings.number_field.number_field_element import NumberFieldElement
from sage.rings.padics.padic_ext_element import pAdicExtElement
from sage.rings.rational import Rational
from sage.structure.parent import ElementConstructorInput, Parent

class pAdicZZpXElement(pAdicExtElement):
    def valuation(self) -> int: ...
    def precision_absolute(self) -> int: ...
    def precision_relative(self) -> int: ...
    def is_zero(self) -> bool: ...
    def lift_to_precision(self, absprec: int | None = None) -> pAdicZZpXElement: ...
    def __init__(self, parent: Parent) -> None: ...
    def norm(
        self, base: ElementConstructorInput | None = ...
    ) -> NumberFieldElement | Rational: ...
    def trace(
        self, base: ElementConstructorInput | None = ...
    ) -> NumberFieldElement | Rational: ...
    def _prime_pow(self) -> Self: ...
    def _rational_(self) -> Rational: ...
