from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class PowComputer_class(SageObject):
    def __init__(self, prime: Integer, cache_limit: int, prec_cap: int, ram_prec_cap: int, in_field: bool, poly: Polynomial | None = None, shift_seed: Element | None = None) -> None: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def pow_Integer_Integer(self, n: int) -> Integer: ...
    def _pow_mpz_t_tmp_demo(self, m: int, n: int) -> list[Integer]: ...
    def _pow_mpz_t_tmp_test(self, n: int) -> Integer: ...
    def _pow_mpz_t_top_test(self) -> Integer: ...
    def _repr_(self) -> str: ...
    def _prime(self) -> Integer: ...
    def _in_field(self) -> bool: ...
    def _cache_limit(self) -> int: ...
    def _prec_cap(self) -> int: ...
    def _top_power(self) -> Integer: ...
    def __call__(self, n: int) -> Integer: ...

class PowComputer_base(PowComputer_class):
    def __init__(self, prime: Integer, cache_limit: int, prec_cap: int, ram_prec_cap: int, in_field: bool, poly: Polynomial | None = None, shift_seed: Element | None = None) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
