# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PowComputer_flint:
    def __cinit__(self, prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, poly: builtins.object = ..., shift_seed: builtins.object = ...) -> _SageObject: ...
    def __init__(self, prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, poly: builtins.object = ..., shift_seed: builtins.object = ...) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def pow_fmpz_t_tmp(self, n: builtins.object) -> _SageObject: ...
    def pow_mpz_t_tmp(self, n: builtins.object) -> _SageObject: ...
    def pow_mpz_t_top(self) -> _SageObject: ...
    def capdiv(self, n: builtins.object) -> _SageObject: ...
    def polynomial(self, n: builtins.object = ..., var: builtins.object = ...) -> _SageObject: ...

class PowComputer_flint_1step:
    def __cinit__(self, prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, _poly: builtins.object) -> _SageObject: ...
    def __init__(self, prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, _poly: builtins.object, shift_seed: builtins.object = ...) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def get_modulus(self, k: builtins.object) -> _SageObject: ...
    def get_modulus_capdiv(self, k: builtins.object) -> _SageObject: ...
    def polynomial(self, _n: builtins.object = ..., var: builtins.object = ...) -> _SageObject: ...

class PowComputer_flint_unram:
    def __cinit__(self, prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, _poly: builtins.object, shift_seed: builtins.object = ...) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __init__(self, prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, poly: builtins.object = ...) -> None: ...

class PowComputer_flint_eis:
    def __init__(self, prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, poly: builtins.object = ...) -> None: ...

def PowComputer_flint_maker(prime: builtins.object, cache_limit: builtins.object, prec_cap: builtins.object, ram_prec_cap: builtins.object, in_field: builtins.object, poly: builtins.object, prec_type: builtins.object) -> _SageObject: ...

class of:
    ...
