from collections.abc import Callable, Iterator
from typing import Self

from sage.categories.morphism import Morphism
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.morphism import RingHomomorphism, RingMap
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.padics.padic_generic import pAdicGeneric
from sage.rings.padics.padic_generic_element import pAdicGenericElement
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ring import Field, Ring
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject

class expansion_mode: ...

class RelativeRamifiedFloatingPointElement(FPElement):
    def _poly_rep(self) -> Self: ...

class pAdicTemplateElement(pAdicGenericElement):
    def __init__(
        self,
        parent: Parent,
        x: pAdicTemplateElement | ElementConstructorInput,
        absprec: int | Integer | None = ...,
        relprec: int | Integer | None = ...,
    ) -> None: ...
    def __lshift__(self, shift: ElementConstructorInput) -> Self: ...
    def __rshift__(self, shift: ElementConstructorInput) -> Self: ...
    def lift_to_precision(self, absprec: int | Integer | None = ...) -> Self: ...
    def expansion(
        self,
        n: int | Integer | None = ...,
        lift_mode: ElementConstructorInput = ...,
        start_val: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def teichmuller_expansion(self, n: int | Integer | None = ...) -> Self: ...
    def _ext_p_list(self, pos: ElementConstructorInput) -> Self: ...
    def unit_part(self) -> Self: ...
    def _prime_pow(self) -> Self: ...
    def residue(
        self,
        absprec: int | Integer | None = ...,
        field: pAdicGeneric | None = ...,
        check_prec: ElementConstructorInput = ...,
    ) -> Self: ...

class ExpansionIter(SageObject):
    def __cinit__(
        self, elt: pAdicTemplateElement, prec: int, mode: expansion_mode
    ) -> pAdicGenericElement: ...
    def __iter__(self) -> Iterator[pAdicGenericElement]: ...
    def __len__(self) -> int | Integer: ...
    def __next__(self) -> pAdicGenericElement: ...

class ExpansionIterable(SageObject):
    def __cinit__(
        self, elt: pAdicTemplateElement, prec: int, val_shift: int, mode: expansion_mode
    ) -> pAdicGenericElement: ...
    def __iter__(self) -> Iterator[pAdicGenericElement]: ...
    def __len__(self) -> int | Integer: ...
    def __getitem__(self, n: int | Integer) -> pAdicGenericElement: ...

class FPElement(pAdicTemplateElement):
    def __copy__(self) -> Self: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def _neg_(self) -> Self: ...
    def _add_(self, _right: ElementConstructorInput) -> Self: ...
    def _sub_(self, _right: ElementConstructorInput) -> Self: ...
    def __invert__(self) -> Self: ...
    def _mul_(self, _right: ElementConstructorInput) -> Self: ...
    def _div_(self, _right: ElementConstructorInput) -> Self: ...
    def _quo_rem(self, _right: ElementConstructorInput) -> tuple[Self, Self]: ...
    def __pow__(
        self, _right: ElementConstructorInput, dummy: ElementConstructorInput
    ) -> Self: ...
    def _repr_(
        self, mode: str | None = ..., do_latex: ElementConstructorInput = ...
    ) -> str: ...
    def add_bigoh(self, absprec: int | Integer | None) -> Self: ...
    def is_zero(self, absprec: int | Integer | None = ...) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_equal_to(
        self, _right: ElementConstructorInput, absprec: int | Integer | None = ...
    ) -> bool: ...
    def _teichmuller_set_unsafe(self) -> None: ...
    def _polynomial_list(self, pad: ElementConstructorInput = ...) -> list[Integer]: ...
    def polynomial(self, var: str = ...) -> Polynomial: ...
    def precision_absolute(self) -> Integer | PlusInfinity: ...
    def precision_relative(self) -> Integer | PlusInfinity: ...
    def unit_part(self) -> Self: ...
    def val_unit(
        self, p: int | Integer | FunctionFieldPlace | NumberFieldIdeal | None = ...
    ) -> tuple[Integer | PlusInfinity, Self]: ...
    def __hash__(self) -> int: ...

class pAdicCoercion_ZZ_FP(RingHomomorphism):
    def __init__(self, R: Ring) -> None: ...
    def _call_(
        self, x: pAdicGenericElement | ElementConstructorInput
    ) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        x: pAdicGenericElement | ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...
    def section(self) -> Morphism: ...

class pAdicConvert_FP_ZZ(RingMap):
    def __init__(self, R: Ring) -> None: ...
    def _call_(self, _x: ElementConstructorInput) -> pAdicGenericElement: ...

class pAdicCoercion_QQ_FP(RingHomomorphism):
    def __init__(self, R: Ring) -> None: ...
    def _call_(
        self, x: pAdicGenericElement | ElementConstructorInput
    ) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        x: pAdicGenericElement | ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...
    def section(self) -> Morphism: ...

class pAdicConvert_FP_QQ(RingMap):
    def __init__(self, R: Ring) -> None: ...
    def _call_(self, _x: ElementConstructorInput) -> pAdicGenericElement: ...

class pAdicConvert_QQ_FP(Morphism):
    def __init__(self, R: Ring) -> None: ...
    def _call_(
        self, x: pAdicGenericElement | ElementConstructorInput
    ) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        x: pAdicGenericElement | ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...

class pAdicCoercion_FP_frac_field(RingHomomorphism):
    def __init__(
        self, R: Ring, K: NumberField_generic | FunctionField | Field
    ) -> None: ...
    def _call_(self, _x: ElementConstructorInput) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        _x: ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...
    def section(self) -> Morphism: ...

class pAdicConvert_FP_frac_field(Morphism):
    def __init__(
        self, K: NumberField_generic | FunctionField | Field, R: Ring
    ) -> None: ...
    def _call_(self, _x: ElementConstructorInput) -> pAdicGenericElement: ...
    def _call_with_args(
        self,
        _x: ElementConstructorInput,
        args: ElementConstructorInput = ...,
        kwds: ElementConstructorInput = ...,
    ) -> pAdicGenericElement: ...

def unpickle_fpe_v2[FPElementT: FPElement](
    cls: type[FPElementT],
    parent: Parent,
    unit: ElementConstructorInput,
    ordp: ElementConstructorInput,
) -> FPElementT: ...
