# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class pAdicRelativeBaseringInjection:
    def __init__(self, R: builtins.int, S: builtins.object) -> None: ...
    def section(self) -> _SageObject: ...

class pAdicRelativeBaseringSection:
    def __init__(self, S: builtins.object, R: builtins.int) -> None: ...

class RelativeRamifiedExtensionRingFixedMod:
    def __init__(self, exact_modulus: builtins.object, approx_modulus: builtins.object, prec: builtins.int, print_mode: builtins.object, shift_seed: builtins.object, names: builtins.object, implementation: builtins.str) -> None: ...

class RelativeRamifiedExtensionRingCappedAbsolute:
    def __init__(self, exact_modulus: builtins.object, approx_modulus: builtins.object, prec: builtins.int, print_mode: builtins.object, shift_seed: builtins.object, names: builtins.object, implementation: builtins.str) -> None: ...

class RelativeRamifiedExtensionRingCappedRelative:
    def __init__(self, exact_modulus: builtins.object, approx_modulus: builtins.object, prec: builtins.int, print_mode: builtins.object, shift_seed: builtins.object, names: builtins.object, implementation: builtins.str) -> None: ...

class RelativeRamifiedExtensionFieldCappedRelative:
    def __init__(self, exact_modulus: builtins.object, approx_modulus: builtins.object, prec: builtins.int, print_mode: builtins.object, shift_seed: builtins.object, names: builtins.object, implementation: builtins.str) -> None: ...

class RelativeRamifiedExtensionRingFloatingPoint:
    def __init__(self, exact_modulus: builtins.object, approx_modulus: builtins.object, prec: builtins.int, print_mode: builtins.object, shift_seed: builtins.object, names: builtins.object, implementation: builtins.str) -> None: ...

class RelativeRamifiedExtensionFieldFloatingPoint:
    def __init__(self, exact_modulus: builtins.object, approx_modulus: builtins.object, prec: builtins.int, print_mode: builtins.object, shift_seed: builtins.object, names: builtins.object, implementation: builtins.str) -> None: ...
