
from collections.abc import Sequence
from typing import TypeAlias

from sage.rings.finite_rings.finite_field_base import FiniteField
from sage.rings.padics.padic_extension_generic import pAdicExtensionGeneric
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element

PrintModeValue: TypeAlias = str | bool | int | Sequence[str] | None

class UnramifiedExtensionGeneric(pAdicExtensionGeneric):
    def __init__(
        self,
        poly: Polynomial,
        prec: int,
        print_mode: dict[str, PrintModeValue],
        names: tuple[str, str, str, str],
        element_class: type[Element],
    ) -> None: ...
    def _extension_type(self) -> str: ...
    def absolute_f(self) -> int: ...
    def residue_class_field(self) -> FiniteField: ...
    def residue_ring(self, n: int) -> FiniteField: ...
    def discriminant(self, K: pAdicExtensionGeneric | None = ...) -> int: ...
    def is_galois(self, K: pAdicExtensionGeneric | None = ...) -> bool: ...
    def gen(self, n: int = ...) -> Element: ...
    def _frob_gen(self, arithmetic: bool = ...) -> Element: ...
    def uniformizer_pow(self, n: int) -> Element: ...
    def uniformizer(self) -> Element: ...
    def _uniformizer_print(self) -> str: ...
    def _unram_print(self) -> str: ...
    def has_pth_root(self) -> bool: ...
    def has_root_of_unity(self, n: int) -> bool: ...
