import builtins
from collections.abc import (
    Iterator,
)

from sage.structure.element import Element

class _SageObject: ...

def fast_char_p_power(self, n: builtins.int, p: builtins.int = ...) -> _SageObject: ...

class WittVectorRing:
    def __classcall_private__(
        self,
        coefficient_ring: builtins.object,
        prec: builtins.int = ...,
        p: builtins.int = ...,
        algorithm: builtins.str = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        coefficient_ring: builtins.object,
        prec: builtins.int,
        prime: builtins.object,
        algorithm: builtins.str,
    ) -> None: ...
    def __iter__(self) -> Iterator: ...
    def cardinality(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def coefficient_ring(self) -> _SageObject: ...
    def frobenius_morphism(self, truncate: builtins.bool = ...) -> _SageObject: ...
    def frobenius_polynomials(
        self, variables: builtins.object = ...
    ) -> _SageObject: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def is_exact(self) -> bool: ...
    def is_field(self, proof: builtins.bool = ...) -> builtins.bool: ...
    def is_finite(self) -> bool: ...
    def is_integral_domain(self, proof: builtins.bool = ...) -> builtins.bool: ...
    def is_integrally_closed(self) -> builtins.bool: ...
    def is_prime_field(self) -> builtins.bool: ...
    def ngens(self) -> int: ...
    def precision(self) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def prod_polynomials(self, variables: builtins.object = ...) -> _SageObject: ...
    def random_element(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def sum_polynomials(self, variables: builtins.object = ...) -> _SageObject: ...
    def teichmuller_lift(self, x: builtins.object) -> _SageObject: ...
    def verschiebung(self, extend: builtins.bool = ...) -> _SageObject: ...

class WittVectorRing_finotti:
    Element: _SageObject

    def __init__(
        self,
        coefficient_ring: builtins.object,
        prec: builtins.int,
        prime: builtins.object,
    ) -> None: ...

class WittVectorRing_phantom:
    Element: _SageObject

    def __init__(
        self,
        coefficient_ring: builtins.object,
        prec: builtins.int,
        prime: builtins.object,
    ) -> None: ...

class WittVectorRing_pinvertible:
    Element: _SageObject

    def __init__(
        self,
        coefficient_ring: builtins.object,
        prec: builtins.int,
        prime: builtins.object,
    ) -> None: ...

class WittVectorRing_standard:
    Element: _SageObject

    def __init__(
        self,
        coefficient_ring: builtins.object,
        prec: builtins.int,
        prime: builtins.object,
    ) -> None: ...

class WittVectorFrobeniusMorphism:
    def __init__(
        self, domain: builtins.object, truncate: builtins.bool = ...
    ) -> None: ...

class WittVectorVerschiebung:
    def __init__(
        self, domain: builtins.object, extend: builtins.bool = ...
    ) -> None: ...
