# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class WittVector:
    def __init__(self, parent: builtins.object, vec: builtins.object = ...) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __invert__(self) -> Self: ...
    def __len__(self) -> builtins.int: ...
    def additive_order(self) -> _SageObject: ...
    def coordinates(self) -> _SageObject: ...
    def is_unit(self) -> builtins.bool: ...

class WittVector_phantom:
    def __init__(self, parent: builtins.object, vec: builtins.object = ..., phantom: builtins.object = ...) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def coordinates(self) -> _SageObject: ...
    def phantom(self, lift: builtins.bool = ...) -> _SageObject: ...

class WittVector_finotti:
    ...

class WittVector_pinvertible:
    ...

class WittVector_standard:
    ...
