# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

INNER_HTML_TEMPLATE: _SageObject
IFRAME_TEMPLATE: _SageObject
OUTER_HTML_TEMPLATE: _SageObject
class JSMolHtml:
    def __init__(self, jmol: builtins.object, path_to_jsmol: builtins.object = ..., width: builtins.str = ..., height: builtins.str = ...) -> None: ...
    def script(self) -> _SageObject: ...
    def js_script(self) -> _SageObject: ...
    def inner_html(self) -> _SageObject: ...
    def iframe(self) -> _SageObject: ...
    def outer_html(self) -> _SageObject: ...
