from typing import Literal, overload

from cypari2.gen import Gen
from sage.matrix.matrix_integer_dense import Matrix_integer_dense
from sage.misc.fast_methods import Singleton
from sage.modular.arithgroup.congroup_gammaH import GammaH_class
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.structure.element import Element as SageElement
from sage.structure.element import InfinityElement
from sage.structure.parent import Parent

type _CuspScalar = Integer | Rational | InfinityElement | Gen | int | str
type _CuspPair = tuple[_CuspScalar, _CuspScalar] | list[_CuspScalar]
type _CuspInput = _CuspScalar | _CuspPair | Cusp

class Cusp(SageElement):

    def __init__(
        self,
        a: _CuspInput,
        b: _CuspScalar | None = None,
        parent: Parent | None = None,
        check: bool = True,
    ) -> None: ...

    def __hash__(self) -> int: ...

    def _richcmp_(self, other: Cusp, op: int) -> bool: ...

    def is_infinity(self) -> bool: ...

    def numerator(self) -> Integer: ...

    def denominator(self) -> Integer: ...

    def _rational_(self) -> Rational: ...

    def _integer_(self, ZZ: Parent | None = None) -> Integer: ...

    def _repr_(self) -> str: ...

    def _latex_(self) -> str: ...

    def __neg__(self) -> Cusp: ...

    @overload
    def is_gamma0_equiv(self, other: _CuspInput, N: int | Integer, transformation: Literal[False] | None = None) -> bool: ...
    @overload
    def is_gamma0_equiv(self, other: _CuspInput, N: int | Integer, transformation: Literal[True, "corner"]) -> tuple[bool, Integer | None]: ...
    @overload
    def is_gamma0_equiv(self, other: _CuspInput, N: int | Integer, transformation: Literal["matrix"]) -> tuple[bool, Matrix_integer_dense | None]: ...

    def is_gamma1_equiv(self, other: _CuspInput, N: int | Integer) -> tuple[bool, int]: ...

    def is_gamma_h_equiv(self, other: Cusp, G: GammaH_class) -> tuple[bool, int]: ...

    def _acted_upon_(self, g: Matrix_integer_dense, self_on_left: bool) -> Cusp | None: ...

    def apply(self, g: tuple[Integer | int, Integer | int, Integer | int, Integer | int] | list[Integer | int]) -> Cusp: ...

    def galois_action(self, t: int | Integer, N: int | Integer) -> Cusp: ...

    def __pari__(self) -> Gen: ...

class Cusps_class(Singleton, Parent):

    Element: type[Cusp]

    def __init__(self) -> None: ...

    def _repr_(self) -> str: ...

    def _latex_(self) -> str: ...

    @overload
    def __call__(self, x: _CuspInput) -> Cusp: ...
    @overload
    def __call__(self, *args: object, **kwds: object) -> SageElement: ...

    def _coerce_map_from_(self, R: Parent) -> bool: ...

    def _element_constructor_(self, x: _CuspInput) -> Cusp: ...

Cusps: Cusps_class
