# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def eisen(p: builtins.int) -> _SageObject: ...

def CO_delta(r: builtins.int, p: builtins.int, N: builtins.int, eps: builtins.object) -> _SageObject: ...

def CO_nu(r: builtins.int, p: builtins.int, N: builtins.int, eps: builtins.object) -> _SageObject: ...

def CohenOesterle(eps: builtins.object, k: builtins.int) -> _SageObject: ...

def dimension_new_cusp_forms(X: builtins.object, k: builtins.int = ..., p: builtins.int = ...) -> _SageObject: ...

def dimension_cusp_forms(X: builtins.object, k: builtins.int = ...) -> _SageObject: ...

def dimension_eis(X: builtins.object, k: builtins.int = ...) -> _SageObject: ...

def dimension_modular_forms(X: builtins.object, k: builtins.int = ...) -> _SageObject: ...

def sturm_bound(level: builtins.object, weight: builtins.int = ...) -> _SageObject: ...
