# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def characteristic_polynomial_from_traces(traces: builtins.object, d: builtins.object, q: builtins.int, i: builtins.int, sign: builtins.object, deg: builtins.object = ..., use_fe: builtins.bool = ...) -> _SageObject: ...

def enumerate_hypergeometric_data(d: builtins.object, weight: builtins.object = ...) -> _SageObject: ...

def possible_hypergeometric_data(d: builtins.object, weight: builtins.object = ...) -> builtins.list[_SageObject]: ...

def cyclotomic_to_alpha(cyclo: builtins.object) -> builtins.list[_SageObject]: ...

def alpha_to_cyclotomic(alpha: builtins.object) -> builtins.list[_SageObject]: ...

def capital_M(n: builtins.int) -> _SageObject: ...

def cyclotomic_to_gamma(cyclo_up: builtins.object, cyclo_down: builtins.object) -> builtins.dict[_SageObject, _SageObject]: ...

def gamma_list_to_cyclotomic(galist: builtins.object) -> _SageObject: ...

class HypergeometricData:
    def __init__(self, cyclotomic: builtins.object = ..., alpha_beta: builtins.object = ..., gamma_list: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def cyclotomic_data(self) -> builtins.tuple[_SageObject, ...]: ...
    def alpha_beta(self) -> builtins.tuple[_SageObject, ...]: ...
    def alpha(self) -> builtins.list[_SageObject]: ...
    def beta(self) -> builtins.list[_SageObject]: ...
    def defining_polynomials(self) -> builtins.tuple[_SageObject, ...]: ...
    def gamma_array(self) -> builtins.dict[_SageObject, _SageObject]: ...
    def gamma_list(self) -> builtins.list[_SageObject]: ...
    def wild_primes(self) -> builtins.list[_SageObject]: ...
    def zigzag(self, x: builtins.object, flip_beta: builtins.bool = ...) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def hodge_numbers(self) -> builtins.list[_SageObject]: ...
    def hodge_polynomial(self) -> _SageObject: ...
    def hodge_function(self, x: builtins.object) -> _SageObject: ...
    def hodge_polygon_vertices(self) -> builtins.list[_SageObject]: ...
    def E_polynomial(self, vars: builtins.object = ...) -> _SageObject: ...
    def M_value(self) -> _SageObject: ...
    def is_primitive(self) -> builtins.bool: ...
    def primitive_index(self) -> _SageObject: ...
    def has_symmetry_at_one(self) -> builtins.bool: ...
    def lfunction(self, t: builtins.object, prec: builtins.int = ...) -> _SageObject: ...
    def canonical_scheme(self, t: builtins.object = ...) -> _SageObject: ...
    def lattice_polytope(self) -> _SageObject: ...
    def twist(self) -> _SageObject: ...
    def swap_alpha_beta(self) -> _SageObject: ...
    def primitive_data(self) -> _SageObject: ...
    def gauss_table(self, p: builtins.int, f: builtins.object, prec: builtins.int) -> _SageObject: ...
    def gauss_table_full(self) -> _SageObject: ...
    def padic_H_value(self, p: builtins.int, f: builtins.object, t: builtins.object, prec: builtins.int = ..., cache_p: builtins.bool = ...) -> _SageObject: ...
    trace: _SageObject
    def H_value(self, p: builtins.int, f: builtins.object, t: builtins.object, ring: builtins.object = ...) -> _SageObject: ...
    def sign(self, t: builtins.object, p: builtins.int) -> _SageObject: ...
    def euler_factor_tame_contribution(self, t: builtins.object, p: builtins.int, mo: builtins.object, deg: builtins.object = ...) -> _SageObject: ...
    def euler_factor(self, t: builtins.object, p: builtins.int, deg: builtins.object = ..., cache_p: builtins.bool = ...) -> _SageObject: ...
