# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DynamicalSystem_Berkovich:
    @staticmethod
    def __classcall_private__(cls: builtins.object, dynamical_system: builtins.object, domain: builtins.object = ..., ideal: builtins.object = ...) -> _SageObject: ...
    def __init__(self, dynamical_system: builtins.object, domain: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __neq__(self, other: builtins.object) -> _SageObject: ...
    def domain(self) -> _SageObject: ...
    def as_scheme_dynamical_system(self) -> _SageObject: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def defining_polynomials(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...

class DynamicalSystem_Berkovich_projective:
    @staticmethod
    def __classcall_private__(cls: builtins.object, dynamical_system: builtins.object, domain: builtins.object = ...) -> _SageObject: ...
    def __init__(self, dynamical_system: builtins.object, domain: builtins.object = ...) -> None: ...
    def scale_by(self, t: builtins.object) -> _SageObject: ...
    def normalize_coordinates(self) -> _SageObject: ...
    def conjugate(self, M: builtins.int, adjugate: builtins.bool = ..., new_ideal: builtins.object = ...) -> _SageObject: ...
    def resultant(self, normalize: builtins.bool = ...) -> _SageObject: ...
    def dehomogenize(self, n: builtins.int) -> _SageObject: ...
    def __call__(self, x: builtins.object, type_3_pole_check: builtins.bool = ...) -> _SageObject: ...

class DynamicalSystem_Berkovich_affine:
    @staticmethod
    def __classcall_private__(cls: builtins.object, dynamical_system: builtins.object, domain: builtins.object = ...) -> _SageObject: ...
    def __init__(self, dynamical_system: builtins.object, domain: builtins.object) -> None: ...
    def homogenize(self, n: builtins.int) -> _SageObject: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
