# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DynamicalSemigroup:
    @staticmethod
    def __classcall_private__(cls: builtins.object, ds_data: builtins.object) -> _SageObject: ...
    def __init__(self, systems: builtins.object) -> None: ...
    def __call__(self, input: builtins.object) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def change_ring(self, new_ring: builtins.object) -> _SageObject: ...
    def domain(self) -> _SageObject: ...
    def codomain(self) -> _SageObject: ...
    def defining_polynomials(self) -> _SageObject: ...
    def defining_systems(self) -> _SageObject: ...
    def nth_iterate(self, p: builtins.int, n: builtins.int) -> _SageObject: ...
    def orbit(self, p: builtins.int, n: builtins.int) -> _SageObject: ...
    def specialization(self, assignments: builtins.object) -> _SageObject: ...
    def __mul__(self, other_dynamical_semigroup: builtins.object) -> Self: ...
    def __pow__(self, n: builtins.int) -> Self: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...

class DynamicalSemigroup_projective:
    @staticmethod
    def __classcall_private__(cls: builtins.object, ds_data: builtins.object) -> _SageObject: ...
    def dehomogenize(self, n: builtins.int) -> _SageObject: ...

class DynamicalSemigroup_projective_field:
    ...

class DynamicalSemigroup_projective_finite_field:
    ...

class DynamicalSemigroup_affine:
    @staticmethod
    def __classcall_private__(cls: builtins.object, ds_data: builtins.object) -> _SageObject: ...
    def homogenize(self, n: builtins.int) -> _SageObject: ...

class DynamicalSemigroup_affine_field:
    ...

class DynamicalSemigroup_affine_finite_field:
    ...
