# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def automorphism_group_QQ_fixedpoints(rational_function: builtins.object, return_functions: builtins.bool = ..., iso_type: builtins.bool = ...) -> _SageObject: ...

def height_bound(polynomial: builtins.object) -> _SageObject: ...

def PGL_repn(rational_function: builtins.object) -> _SageObject: ...

def PGL_order(A: builtins.object) -> _SageObject: ...

def CRT_helper(automorphisms: builtins.object, moduli: builtins.object) -> _SageObject: ...

def CRT_automorphisms(automorphisms: builtins.object, order_elts: builtins.object, degree: builtins.int, moduli: builtins.object) -> _SageObject: ...

def valid_automorphisms(automorphisms_CRT: builtins.object, rational_function: builtins.object, ht_bound: builtins.object, M: builtins.int, return_functions: builtins.bool = ...) -> _SageObject: ...

def remove_redundant_automorphisms(automorphisms: builtins.object, order_elts: builtins.object, moduli: builtins.object, integral_autos: builtins.object) -> _SageObject: ...

def automorphism_group_QQ_CRT(rational_function: builtins.object, prime_lower_bound: builtins.int = ..., return_functions: builtins.bool = ..., iso_type: builtins.bool = ...) -> _SageObject: ...

def automorphism_group_FF(rational_function: builtins.object, absolute: builtins.bool = ..., iso_type: builtins.bool = ..., return_functions: builtins.bool = ...) -> _SageObject: ...

def field_descent(sigma: builtins.object, y: builtins.object) -> _SageObject: ...

def rational_function_coefficient_descent(rational_function: builtins.object, sigma: builtins.object, poly_ring: builtins.object) -> _SageObject: ...

def rational_function_coerce(rational_function: builtins.object, sigma: builtins.object, S_polys: builtins.object) -> _SageObject: ...

def rational_function_reduce(rational_function: builtins.object) -> _SageObject: ...

def three_stable_points(rational_function: builtins.object, invariant_list: builtins.object) -> _SageObject: ...

def automorphism_group_FF_alg2(rational_function: builtins.object) -> _SageObject: ...

def order_p_automorphisms(rational_function: builtins.object, pre_image: builtins.object) -> _SageObject: ...

def automorphisms_fixing_pair(rational_function: builtins.object, pair: builtins.object, quad: builtins.object) -> _SageObject: ...

def automorphism_group_FF_alg3(rational_function: builtins.object) -> _SageObject: ...

def which_group(list_of_elements: builtins.object) -> _SageObject: ...

def conjugating_set_initializer(f: builtins.object, g: builtins.object) -> _SageObject: ...

def greedy_independence_check(P: builtins.int, repeated_mult: builtins.object, point_to_mult: builtins.object) -> _SageObject: ...

def conjugating_set_helper(f: builtins.object, g: builtins.object, num_cpus: builtins.object, source: builtins.object, possible_targets: builtins.object) -> _SageObject: ...

def is_conjugate_helper(f: builtins.object, g: builtins.object, num_cpus: builtins.object, source: builtins.object, possible_targets: builtins.object) -> builtins.bool: ...
