from sage.categories.category import Category
from sage.rings.ring import Ring
from sage.rings.integer import Integer
from sage.schemes.generic.morphism import SchemeMorphism
from sage.schemes.projective.projective_space import ProjectiveSpace_ring
from sage.structure.element import Element
from sage.schemes.projective.projective_morphism import SchemeMorphism_polynomial_projective_space
from sage.dynamics.arithmetic_dynamics.generic_ds import DynamicalSystem

class DynamicalSystem_projective(SchemeMorphism_polynomial_projective_space, DynamicalSystem):
    def __init__(self, polys: list[Element] | tuple[Element, ...], domain: ProjectiveSpace_ring) -> None: ...
    def dehomogenize(self, n: tuple[int, int] | int) -> SchemeMorphism: ...
    def dynatomic_polynomial(self, period: list[int] | tuple[int, ...] | int) -> Element: ...
    def nth_iterate_map(self, n: int, normalize: bool = ...) -> SchemeMorphism: ...
    def nth_iterate(self, P: Element, n: int, **kwds: object) -> Element: ...
    def arakelov_zhang_pairing(self, g: SchemeMorphism, **kwds: object) -> Element: ...
    def degree_sequence(self, iterates: int = ...) -> list[int]: ...
    def dynamical_degree(self, N: int = ..., prec: int = ...) -> Element: ...
    def orbit(self, P: Element, N: int | list[int] | tuple[int, int], **kwds: object) -> list[Element]: ...
    def resultant(self, normalize: bool = ...) -> Element: ...
    def primes_of_bad_reduction(self, check: bool = ...) -> list[Element]: ...
    def conjugate(self, M: Element, adjugate: bool = ..., normalize: bool = ...) -> SchemeMorphism: ...
    def green_function(self, P: Element, v: Element, **kwds: object) -> Element: ...
    def canonical_height(self, P: Element, **kwds: object) -> Element: ...
    def height_difference_bound(self, prec: int = ...) -> Element: ...
    def multiplier(self, P: Element, n: int, check: bool = ...) -> Element: ...
    def nth_preimage_tree(self, Q: Element, n: int, **kwds: object) -> Element: ...
    def possible_periods(self, return_points: bool = ..., **kwds: object) -> list[int] | list[tuple[int, Element]]: ...
    def is_PGL_minimal(self, prime_list: list[Element] | None = ...) -> bool: ...
    def minimal_model(self, return_transformation: bool = ..., prime_list: list[Element] | None = ..., algorithm: str = ..., check_primes: bool = ...) -> SchemeMorphism | tuple[SchemeMorphism, Element]: ...
    def all_minimal_models(self, return_transformation: bool = ..., prime_list: list[Element] | None = ..., algorithm: str = ..., check_minimal: bool = ...) -> list[SchemeMorphism] | list[tuple[SchemeMorphism, Element]]: ...
    def affine_preperiodic_model(self, m: int, n: int, return_conjugation: bool = ...) -> SchemeMorphism | tuple[SchemeMorphism, Element]: ...
    def automorphism_group(self, **kwds: object) -> Element | list[Element] | list[tuple[SchemeMorphism, Element]]: ...
    def critical_subscheme(self) -> SchemeMorphism: ...
    def critical_points(self, R: Ring | None = ...) -> list[Element]: ...
    def ramification_type(self, R: Ring | None = ..., stable: bool = ...) -> list[list[int]]: ...
    def is_postcritically_finite(self, err: float = ..., use_algebraic_closure: bool = ..., **kwds: object) -> bool: ...
    def is_dynamical_belyi_map(self) -> bool: ...
    def critical_point_portrait(self, check: bool = ..., use_algebraic_closure: bool = ...) -> Element: ...
    def critical_height(self, **kwds: object) -> Element: ...
    def preperiodic_points(self, m: int, n: int, **kwds: object) -> list[Element]: ...
    def periodic_points(self, n: int, minimal: bool = ..., formal: bool = ..., R: Ring | None = ..., algorithm: str = ..., return_scheme: bool = ...) -> list[Element] | SchemeMorphism: ...
    def multiplier_spectra(self, n: int, formal: bool = ..., type: str = ..., use_algebraic_closure: bool = ..., check: bool = ...) -> list[Element]: ...
    def sigma_invariants(self, n: int, formal: bool = ..., embedding: Element | None = ..., type: str = ..., return_polynomial: bool = ..., chow: bool = ..., deform: bool = ..., check: bool = ...) -> list[Element] | Element: ...
    def reduced_form(self, **kwds: object) -> SchemeMorphism | tuple[SchemeMorphism, Element]: ...
    def postcritical_set(self, check: bool = ...) -> list[Element]: ...
    def is_chebyshev(self) -> bool: ...
    def is_Lattes(self) -> bool: ...
    def Lattes_to_curve(self, return_conjugation: bool = ..., check_lattes: bool = ...) -> SchemeMorphism | tuple[SchemeMorphism, Element]: ...

from sage.schemes.projective.projective_morphism import SchemeMorphism_polynomial_projective_space_field, SchemeMorphism_polynomial_projective_space_finite_field
from sage.graphs.digraph import DiGraph

class DynamicalSystem_projective_field(DynamicalSystem_projective, SchemeMorphism_polynomial_projective_space_field):
    def lift_to_rational_periodic(self, points_modp: list[Element], B: int | None = ...) -> list[Element]: ...
    def all_periodic_points(self, **kwds: object) -> list[Element]: ...
    def all_rational_preimages(self, points: list[Element] | tuple[Element, ...]) -> list[Element]: ...
    def all_preperiodic_points(self, **kwds: object) -> list[Element]: ...
    def rational_preperiodic_graph(self, **kwds: object) -> DiGraph: ...
    def connected_rational_component(self, P: Element, n: int | None = ...) -> DiGraph: ...
    def conjugating_set(self, other: SchemeMorphism, R: Ring | None = ..., num_cpus: int | None = ...) -> list[SchemeMorphism] | list[Element]: ...
    def is_conjugate(self, other: SchemeMorphism, R: Ring | None = ..., num_cpus: int | None = ...) -> bool | tuple[bool, SchemeMorphism]: ...
    def is_polynomial(self) -> bool: ...
    def normal_form(self, return_conjugation: bool = ...) -> SchemeMorphism | tuple[SchemeMorphism, SchemeMorphism]: ...
    def potential_good_reduction(self, prime: Element, return_conjugation: bool = ...) -> bool | tuple[bool, SchemeMorphism]: ...
    def reduce_base_field(self) -> SchemeMorphism: ...
    def is_newton(self, return_conjugation: bool = ...) -> bool | tuple[bool, SchemeMorphism]: ...

class DynamicalSystem_projective_finite_field(DynamicalSystem_projective_field, SchemeMorphism_polynomial_projective_space_finite_field):
    def is_postcritically_finite(self, err: float = ..., use_algebraic_closure: bool = ..., **kwds: object) -> bool: ...
    def orbit_structure(self, P: Element) -> list[int] | tuple[int, int]: ...
    def cyclegraph(self) -> DiGraph: ...
    def possible_periods(self, return_points: bool = ..., **kwds: object) -> list[int] | list[tuple[int, Element]]: ...
    def automorphism_group(self, **kwds: object) -> Element | list[Element] | list[tuple[SchemeMorphism, Element]]: ...
    def all_periodic_points(self, **kwds: object) -> list[Element]: ...
