import builtins

class _SageObject: ...

def WehlerK3Surface(self) -> _SageObject: ...
def random_WehlerK3Surface(self) -> _SageObject: ...

class WehlerK3Surface_ring:
    Q: CR
    L: CR

    def __init__(self, polys: builtins.object) -> None: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    def Gpoly(self, component: builtins.object, k: builtins.int) -> _SageObject: ...
    def Hpoly(
        self, component: builtins.object, i: builtins.int, j: builtins.int
    ) -> _SageObject: ...
    def Lxa(self, a: builtins.object) -> _SageObject: ...
    def Qxa(self, a: builtins.object) -> _SageObject: ...
    def Sxa(self, a: builtins.object) -> _SageObject: ...
    def Lyb(self, b: builtins.object) -> _SageObject: ...
    def Qyb(self, b: builtins.object) -> _SageObject: ...
    def Syb(self, b: builtins.object) -> _SageObject: ...
    def Ramification_poly(self, i: builtins.int) -> _SageObject: ...
    def is_degenerate(self) -> bool: ...
    def degenerate_fibers(self) -> _SageObject: ...
    def degenerate_primes(self, check: builtins.bool = ...) -> _SageObject: ...
    def is_smooth(self) -> bool: ...
    def sigmaX(self, P: builtins.int, **kwds: builtins.object) -> _SageObject: ...
    def sigmaY(self, P: builtins.int, **kwds: builtins.object) -> _SageObject: ...
    def phi(self, a: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def psi(self, a: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def lambda_plus(
        self,
        P: builtins.int,
        v: builtins.object,
        N: builtins.int,
        m: builtins.int,
        n: builtins.int,
        prec: builtins.int = ...,
    ) -> _SageObject: ...
    def lambda_minus(
        self,
        P: builtins.int,
        v: builtins.object,
        N: builtins.int,
        m: builtins.int,
        n: builtins.int,
        prec: builtins.int = ...,
    ) -> _SageObject: ...
    def canonical_height_plus(
        self,
        P: builtins.int,
        N: builtins.int,
        badprimes: builtins.object = ...,
        prec: builtins.int = ...,
    ) -> _SageObject: ...
    def canonical_height_minus(
        self,
        P: builtins.int,
        N: builtins.int,
        badprimes: builtins.object = ...,
        prec: builtins.int = ...,
    ) -> _SageObject: ...
    def canonical_height(
        self,
        P: builtins.int,
        N: builtins.int,
        badprimes: builtins.object = ...,
        prec: builtins.int = ...,
    ) -> _SageObject: ...
    def fiber(self, p: builtins.int, component: builtins.object) -> _SageObject: ...
    def nth_iterate_phi(
        self, P: builtins.int, n: builtins.int, **kwds: builtins.object
    ) -> _SageObject: ...
    def nth_iterate_psi(
        self, P: builtins.int, n: builtins.int, **kwds: builtins.object
    ) -> _SageObject: ...
    def orbit_phi(
        self, P: builtins.int, N: builtins.int, **kwds: builtins.object
    ) -> _SageObject: ...
    def orbit_psi(
        self, P: builtins.int, N: builtins.int, **kwds: builtins.object
    ) -> _SageObject: ...
    def is_isomorphic(self, right: builtins.object) -> bool: ...
    def is_symmetric_orbit(self, orbit: builtins.object) -> bool: ...

class WehlerK3Surface_field: ...

class WehlerK3Surface_finite_field:
    def cardinality(self) -> _SageObject: ...
