from sage.structure.element import Element

class ACEQuantumOnsagerAlgebra(CombinatorialFreeModule):
    def _monomial_key(self, x: Element) -> Element: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _repr_term(self, m: int) -> str: ...
    def _latex_term(self, m: int) -> str: ...
    def algebra_generators(self) -> Element: ...
    def q(self) -> Element: ...
    def one_basis(self) -> Element: ...
    def _an_element_(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...
    def degree_on_basis(self, m: int) -> int: ...
    def quantum_onsager_pbw_generator(self, i: int) -> Element: ...
    def product_on_basis(self, lhs: Element | int | str | bool | None, rhs: Element | int | str | bool | None) -> Element: ...
    def _sigma_on_basis(self, x: Element) -> Element: ...
    def _dagger_on_basis(self, x: Element) -> Element: ...
    def sigma(self) -> Element: ...
    def dagger(self) -> Element: ...

class CombinatorialFreeModule: ...
