from sage.structure.element import Element
from sage.structure.parent import Parent

class FockSpaceOptions(GlobalOptions):
    ...

class FockSpace(Parent, UniqueRepresentation):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def q(self) -> Element: ...
    def multicharge(self) -> Element: ...
    def a_realization(self) -> Element: ...
    def inject_shorthands(self, verbose: bool) -> Element: ...
    def highest_weight_vector(self) -> Element: ...
    def __getitem__(self, i: int) -> Element: ...

class FockSpaceBases(Category_realization_of_parent):
    def super_categories(self) -> Element: ...

class FockSpaceTruncated(FockSpace):
    ...

class Category_realization_of_parent: ...

class GlobalOptions: ...

class UniqueRepresentation: ...
