from typing import Self

from sage.interfaces.expect import ExpectElement
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.parent import Parent


def projection_lower_half(Q: Element | int | str | bool | None) -> Element: ...

class QuaGroupModuleElement(Element):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __hash__(self) -> int: ...
    def _richcmp_(self, other: Element, op: Element | int | str | bool | None) -> bool: ...
    def _libgap_(self) -> ExpectElement: ...
    def _add_(self, other: Element) -> Self: ...
    def _sub_(self, other: Element) -> Self: ...
    def _acted_upon_(self, scalar: Element | int | str | bool | None, self_on_left: Element | int | str | bool | None) -> Element: ...
    def e_tilde(self, i: int) -> Element: ...
    def f_tilde(self, i: int) -> Element: ...

class QuantumGroup(UniqueRepresentation, Parent):
    def _libgap_(self) -> ExpectElement: ...
    def cartan_type(self) -> Element: ...
    def _element_constructor_(self, elt: Element) -> Element: ...
    def one(self) -> Element: ...
    def zero(self) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def E(self) -> Element: ...
    def E_simple(self) -> Element: ...
    def F(self) -> Element: ...
    def F_simple(self) -> Element: ...
    def K(self) -> Element: ...
    def K_inverse(self) -> Element: ...
    def algebra_generators(self) -> Element: ...
    def _an_element_(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...
    def q(self) -> Element: ...
    def _Hom_(self, Y: Element | int | str | bool | None, category: Element | int | str | bool | None) -> Element: ...
    def highest_weight_module(self, weight: Element | int | str | bool | None) -> Element: ...
    def lower_half(self) -> Element: ...
    def coproduct(self, elt: Element, n: int) -> Element: ...
    def antipode(self, elt: Element) -> Element: ...
    def counit(self, elt: Element) -> Element: ...

class QuantumGroupMorphism(Morphism):
    def _call_(self, val: Element | int | str | bool | None) -> Element: ...
    def im_gens(self) -> Element: ...
    def _repr_defn(self) -> str: ...

class QuantumGroupHomset(HomsetWithBase):
    ...

class QuaGroupRepresentationElement(QuaGroupModuleElement):
    def _et(self, i: int) -> Element: ...
    def _ft(self, i: int) -> Element: ...
    def monomial_coefficients(self, copy: Element | int | str | bool | None) -> Element: ...
    def _vector_(self, R: Ring, order: Element | int | str | bool | None, sparse: Element | int | str | bool | None) -> Element: ...

class CrystalGraphVertex(Element):
    def __hash__(self) -> int: ...

class QuantumGroupModule(Parent, UniqueRepresentation):
    def _libgap_(self) -> ExpectElement: ...
    def basis(self) -> Element: ...
    def crystal_basis(self) -> Element: ...
    def R_matrix(self) -> Element: ...
    def crystal_graph(self) -> Element: ...

class HighestWeightModule(QuantumGroupModule):
    def highest_weight_vector(self) -> Element: ...
    def tensor(self) -> Element: ...

class TensorProductOfHighestWeightModules(QuantumGroupModule):
    def _highest_weights_and_vectors(self) -> Element: ...
    def highest_weight_vectors(self) -> Element: ...
    def highest_weight_decomposition(self) -> Element: ...
    def tensor_factors(self) -> Element: ...

class HighestWeightSubmodule(QuantumGroupModule):
    def _ambient_basis_map(self) -> Element: ...
    def ambient(self) -> Element: ...
    def lift(self) -> Element: ...
    def retract(self, elt: Element) -> Element: ...

class LowerHalfQuantumGroup(Parent, UniqueRepresentation):
    def _construct_monomial(self, k: int) -> Element: ...
    def _construct_canonical_basis_elts(self, k: int) -> Element: ...
    def canonical_basis_elements(self) -> Element: ...

class HomsetWithBase: ...

class Morphism: ...

class UniqueRepresentation: ...
