# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class QuantumGroupRepresentation:
    @staticmethod
    def __classcall__(cls: builtins.object, R: builtins.int, C: builtins.object, q: builtins.int = ...) -> _SageObject: ...
    def __init__(self, R: builtins.int, C: builtins.object, q: builtins.int) -> None: ...
    def cartan_type(self) -> _SageObject: ...
    def K_on_basis(self, i: builtins.int, b: builtins.object, power: builtins.int = ...) -> _SageObject: ...

class CyclicRepresentation:
    def module_generator(self) -> _SageObject: ...

class AdjointRepresentation:
    def __init__(self, R: builtins.int, C: builtins.object, q: builtins.int) -> None: ...
    def e_on_basis(self, i: builtins.int, b: builtins.object) -> _SageObject: ...
    def f_on_basis(self, i: builtins.int, b: builtins.object) -> _SageObject: ...

class MinusculeRepresentation:
    def e_on_basis(self, i: builtins.int, b: builtins.object) -> _SageObject: ...
    def f_on_basis(self, i: builtins.int, b: builtins.object) -> _SageObject: ...
