from collections.abc import Iterable, Iterator, Mapping
from typing import Generic, TypeVar

from sage.modules.free_module import FreeModule_generic, FreeModule_submodule, VectorSpace
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.structure.element import FieldElement
from sage.structure.parent import Parent

_Scalar = TypeVar("_Scalar", bound=FieldElement, default=FieldElement)


def FilteredVectorSpace(
    base_ring: Parent[_Scalar],
    dimension: int | Integer,
    filtration: Mapping[int | Integer, Iterable[FreeModuleElement[_Scalar]]] | None = ...,
) -> FilteredVectorSpace_class[_Scalar]: ...


class FilteredVectorSpace_class(Generic[_Scalar]):
    def __init__(
        self,
        vector_space: VectorSpace[_Scalar],
        filtration: Mapping[int | Integer, FreeModule_submodule[_Scalar]],
    ) -> None: ...
    def base_ring(self) -> Parent[_Scalar]: ...
    def vector_space(self) -> VectorSpace[_Scalar]: ...
    def dimension(self) -> int: ...
    rank = dimension
    def filtration(self) -> dict[Integer, FreeModule_submodule[_Scalar]]: ...
    def __getitem__(self, degree: int | Integer) -> FreeModule_submodule[_Scalar]: ...
    def support(self) -> tuple[Integer, ...]: ...
    def graded_piece(self, degree: int | Integer) -> FreeModule_generic[_Scalar]: ...
    def graded_dimension(self, degree: int | Integer) -> int: ...
    def associated_graded(self) -> dict[Integer, FreeModule_generic[_Scalar]]: ...
    def shift(self, degree: int | Integer) -> FilteredVectorSpace_class[_Scalar]: ...
    def dual(self) -> FilteredVectorSpace_class[_Scalar]: ...
    def direct_sum(
        self,
        other: FilteredVectorSpace_class[_Scalar],
    ) -> FilteredVectorSpace_class[_Scalar]: ...
    def tensor_product(
        self,
        other: FilteredVectorSpace_class[_Scalar],
    ) -> FilteredVectorSpace_class[_Scalar]: ...
    def symmetric_power(self, degree: int) -> FilteredVectorSpace_class[_Scalar]: ...
    def exterior_power(self, degree: int) -> FilteredVectorSpace_class[_Scalar]: ...
