import builtins
from collections.abc import Callable, Iterable

from sage.matrix.matrix import Matrix
from sage.plot.graphics import Graphics
from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.structure.element import Vector, Element

class FreeModuleElement(Vector):
    def __init__(self) -> None: ...
    def monomial_coefficients(self, copy: bool = ...) -> dict[int, Element]: ...
    def __pari__(self) -> Element: ...
    def numpy(self, dtype: type | None = ...) -> Element: ...
    def __hash__(self) -> int: ...
    def numerical_approx(self, prec: int | None = ..., digits: int | None = ..., algorithm: str | None = ...) -> FreeModuleElement: ...
    def row(self) -> Matrix: ...
    def column(self) -> Matrix: ...
    def __copy__(self) -> FreeModuleElement: ...
    def subs(self, in_dict: dict[object, object] | None = ..., **kwds: object) -> FreeModuleElement: ...
    def change_ring(self, R: Ring) -> FreeModuleElement: ...
    def coordinate_ring(self) -> Ring: ...
    def additive_order(self) -> Integer | float: ...
    def items(self) -> list[tuple[int, Element]]: ...
    def __abs__(self) -> Element: ...
    def norm(self, p: Integer | float = ...) -> Element | float: ...
    def __getitem__(self, i: int) -> Element: ...
    def get_unsafe(self, i: int) -> Element: ...
    def get(self, i: int) -> Element: ...
    def __setitem__(self, i: int, value: Element) -> None: ...
    def set(self, i: int, value: Element) -> None: ...
    def __invert__(self) -> FreeModuleElement: ...
    def __len__(self) -> int: ...
    def __mod__(self, p: Element) -> FreeModuleElement: ...
    def Mod(self, p: Element) -> FreeModuleElement: ...
    def list(self, copy: bool = ...) -> builtins.list[Element]: ...
    def list_from_positions(self, positions: Iterable[int]) -> builtins.list[Element]: ...
    def lift(self) -> FreeModuleElement: ...
    def lift_centered(self) -> FreeModuleElement: ...
    def __pos__(self) -> FreeModuleElement: ...
    def __pow__(self, n: int) -> FreeModuleElement: ...
    def degree(self) -> int: ...
    def denominator(self) -> Element: ...
    def dict(self, copy: bool = ...) -> dict[int, Element]: ...
    def plot(self, plot_type: str | None = ..., start: FreeModuleElement | None = ..., **kwds: object) -> Graphics: ...
    def plot_step(self, xmin: float = ..., xmax: float = ..., eps: float | None = ..., res: int | None = ..., **kwds: object) -> Graphics: ...
    def dot_product(self, right: FreeModuleElement) -> Element: ...
    def cross_product(self, right: FreeModuleElement) -> FreeModuleElement: ...
    def cross_product_matrix(self) -> Matrix: ...
    def pairwise_product(self, right: FreeModuleElement) -> FreeModuleElement: ...
    def div(self, variables: Iterable[object] | None = ...) -> Element: ...
    def curl(self, variables: Iterable[object] | None = ...) -> FreeModuleElement: ...
    def element(self) -> FreeModuleElement: ...
    def monic(self) -> FreeModuleElement: ...
    def normalized(self, p: Integer | float = ...) -> FreeModuleElement: ...
    def conjugate(self) -> FreeModuleElement: ...
    def inner_product(self, right: FreeModuleElement) -> Element: ...
    def outer_product(self, right: FreeModuleElement) -> Matrix: ...
    def hermitian_inner_product(self, right: FreeModuleElement) -> Element: ...
    def is_dense(self) -> bool: ...
    def is_sparse(self) -> bool: ...
    def is_vector(self) -> bool: ...
    def nonzero_positions(self) -> builtins.list[int]: ...
    def support(self) -> builtins.list[int]: ...
    def dense_vector(self) -> FreeModuleElement: ...
    def sparse_vector(self) -> FreeModuleElement: ...
    def apply_map(self, phi: Callable[[Element], Element], R: Ring | None = ..., sparse: bool | None = ...) -> FreeModuleElement: ...
    def derivative(self, *args: object) -> FreeModuleElement: ...
    def integral(self, *args: object, **kwds: object) -> FreeModuleElement: ...
    def nintegral(self, *args: object, **kwds: object) -> tuple[tuple[float, ...], float, int, str]: ...
    def concatenate(self, other: FreeModuleElement, *, ring: Ring | None = ...) -> FreeModuleElement: ...
    def compositional_inverse(self, allow_multivalued_inverse: bool = ..., **kwargs: object) -> FreeModuleElement: ...
    def function(self, *args: object) -> Callable[..., Element]: ...
