# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeModuleHomspace:
    def __call__(self, A: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def zero(self, side: builtins.str = ...) -> _SageObject: ...
    def basis(self, side: builtins.str = ...) -> _SageObject: ...
    def identity(self, side: builtins.str = ...) -> _SageObject: ...
