from collections.abc import Iterable, Iterator
from typing import TYPE_CHECKING

from sage.modules.module import Module
from sage.structure.parent import Parent

if TYPE_CHECKING:
    from sage.categories.family import Family
    from sage.matrix.matrix import Matrix
    from sage.modules.free_module_element import FreeModuleElement
    from sage.modules.module_morphism import ModuleMorphism
    from sage.rings.integer import Integer
    from sage.rings.ring import Field, Ring
    from sage.structure.element import Element

class FreeModule_generic(Module):
    def __init__(self, base: Ring, rank: int, sparse: bool = ...) -> None: ...
    def construction(self) -> tuple[object, object]: ...
    def dense_module(self) -> FreeModule_generic: ...
    def sparse_module(self) -> FreeModule_generic: ...
    def is_submodule(self, other: FreeModule_generic) -> bool: ...
    def __iter__(self) -> Iterator[FreeModuleElement]: ...
    def cardinality(self) -> Integer | float: ...
    def basis(self) -> Family: ...
    def gens(self) -> tuple[FreeModuleElement, ...]: ...
    def basis_matrix(self) -> Matrix: ...
    def echelonized_basis_matrix(self) -> Matrix: ...
    def matrix(self) -> Matrix: ...
    def direct_sum(self, other: FreeModule_generic) -> FreeModule_generic: ...
    def coordinates(self, v: FreeModuleElement) -> list[Element]: ...
    def coordinate_vector(self, v: FreeModuleElement) -> FreeModuleElement: ...
    def coordinate_module(self) -> FreeModule_generic: ...
    def dimension(self) -> int: ...
    def codimension(self) -> int: ...
    def discriminant(self) -> Element: ...
    def base_field(self) -> Field: ...
    def coordinate_ring(self) -> Ring: ...
    def free_module(self) -> FreeModule_generic: ...
    def gen(self, i: int) -> FreeModuleElement: ...
    def gram_matrix(self) -> Matrix: ...
    def has_user_basis(self) -> bool: ...
    def hom(self, im_gens: Iterable[FreeModuleElement] | ModuleMorphism, codomain: FreeModule_generic | None = ...) -> ModuleMorphism: ...
    def pseudoHom(self, im_gens: Iterable[FreeModuleElement] | ModuleMorphism, codomain: FreeModule_generic | None = ...) -> ModuleMorphism: ...
    def pseudohom(self, im_gens: Iterable[FreeModuleElement] | ModuleMorphism, codomain: FreeModule_generic | None = ...) -> ModuleMorphism: ...
    def inner_product_matrix(self) -> Matrix: ...
    def is_ambient(self) -> bool: ...
    def is_dense(self) -> bool: ...
    def is_full(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def ngens(self) -> int: ...
    def nonembedded_free_module(self) -> FreeModule_generic: ...
    def random_element(self, *args: object, **kwds: object) -> FreeModuleElement: ...
    def rank(self) -> int: ...
    def uses_ambient_inner_product(self) -> bool: ...
    def are_linearly_dependent(self, vecs: Iterable[FreeModuleElement]) -> bool: ...
    def scale(self) -> Element: ...
    def relations(self) -> FreeModule_generic: ...
