from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from typing import Generic, Literal, NoReturn, Self, TypeVar, overload

import numpy as np
from numpy.typing import DTypeLike, NDArray
from sympy.matrices.matrixbase import MatrixBase

from sage.interfaces.expect import Expect, ExpectElement
from sage.libs.pari.gen import gen
from sage.matrix.matrix import Matrix
from sage.misc.sage_input import SageInputBuilder, SageInputExpression
from sage.plot.graphics import Graphics
from sage.plot.plot3d.base import Graphics3d
from sage.rings.infinity import AnInfinity, PlusInfinity
from sage.rings.integer import Integer
from sage.structure.element import Element, RingElement, Vector
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sequence import Sequence_generic

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)
_NewScalar = TypeVar("_NewScalar", bound=RingElement)
_OtherScalar = TypeVar("_OtherScalar", bound=RingElement)

type VectorEntries = (
    Iterable[ElementConstructorInput]
    | Mapping[int | Integer, ElementConstructorInput]
)
type VectorPlotType = Literal["arrow", "point", "step"]
type NumericalIntegralData = (
    list[tuple[RingElement, ...]]
    | dict[int, tuple[RingElement, ...]]
)


@overload
def vector(
    arg0: FreeModuleElement[_Scalar],
    arg1: None = ...,
    arg2: None = ...,
    sparse: bool | None = ...,
    immutable: bool = ...,
) -> FreeModuleElement[_Scalar]: ...
@overload
def vector(
    arg0: Parent[_Scalar],
    arg1: VectorEntries | FreeModuleElement[_Scalar],
    arg2: None = ...,
    sparse: bool | None = ...,
    immutable: bool = ...,
) -> FreeModuleElement[_Scalar]: ...
@overload
def vector(
    arg0: VectorEntries | FreeModuleElement[RingElement],
    arg1: Parent[_Scalar],
    arg2: None = ...,
    sparse: bool | None = ...,
    immutable: bool = ...,
) -> FreeModuleElement[_Scalar]: ...
@overload
def vector(
    arg0: Parent[_Scalar],
    arg1: int | Integer,
    arg2: VectorEntries | FreeModuleElement[_Scalar] | None = ...,
    sparse: bool | None = ...,
    immutable: bool = ...,
) -> FreeModuleElement[_Scalar]: ...
@overload
def vector(
    arg0: VectorEntries,
    arg1: None = ...,
    arg2: None = ...,
    sparse: bool | None = ...,
    immutable: bool = ...,
) -> FreeModuleElement[RingElement]: ...

free_module_element = vector

@overload
def prepare(
    v: VectorEntries,
    R: Parent[_Scalar],
    degree: int | Integer | None = ...,
) -> tuple[Sequence_generic, Parent[_Scalar]]: ...
@overload
def prepare(
    v: VectorEntries,
    R: None,
    degree: int | Integer | None = ...,
) -> tuple[Sequence_generic, Parent[RingElement]]: ...

@overload
def zero_vector(
    arg0: int | Integer,
    arg1: None = ...,
) -> FreeModuleElement[Integer]: ...
@overload
def zero_vector(
    arg0: Parent[_Scalar],
    arg1: int | Integer,
) -> FreeModuleElement[_Scalar]: ...

@overload
def random_vector(
    ring: int | Integer,
    degree: int | Integer | None = ...,
    *args: object,
    **kwds: object,
) -> FreeModuleElement[Integer]: ...
@overload
def random_vector(
    ring: Parent[_Scalar],
    degree: int | Integer,
    *args: object,
    **kwds: object,
) -> FreeModuleElement[_Scalar]: ...


def make_FreeModuleElement_generic_dense(
    parent: FreeModule_generic[_Scalar],
    entries: Sequence[ElementConstructorInput],
    degree: int | Integer,
) -> FreeModuleElement_generic_dense[_Scalar]: ...

def make_FreeModuleElement_generic_dense_v1(
    parent: FreeModule_generic[_Scalar],
    entries: Sequence[ElementConstructorInput],
    degree: int | Integer,
    immutable: bool,
) -> FreeModuleElement_generic_dense[_Scalar]: ...

def make_FreeModuleElement_generic_sparse(
    parent: FreeModule_generic[_Scalar],
    entries: Mapping[int | Integer, ElementConstructorInput],
    degree: int | Integer,
) -> FreeModuleElement_generic_sparse[_Scalar]: ...

def make_FreeModuleElement_generic_sparse_v1(
    parent: FreeModule_generic[_Scalar],
    entries: Mapping[int | Integer, ElementConstructorInput],
    degree: int | Integer,
    immutable: bool,
) -> FreeModuleElement_generic_sparse[_Scalar]: ...


class FreeModuleElement(Vector[_Scalar], Generic[_Scalar]):
    def __init__(self, parent: Parent[Self]) -> None: ...
    def parent(self) -> FreeModule_generic[_Scalar]: ...
    def base_ring(self) -> Parent[_Scalar]: ...
    def monomial_coefficients(self, copy: bool = ...) -> dict[int, _Scalar]: ...
    def _giac_init_(self) -> list[_Scalar]: ...
    def __pari__(self) -> gen: ...
    def _pari_init_(self) -> str: ...
    def _magma_init_(self, magma: Expect) -> str: ...
    def numpy(self, dtype: DTypeLike | None = ...) -> NDArray[np.generic]: ...
    def __hash__(self) -> int: ...
    @overload
    def _vector_(self, R: None = ...) -> Self: ...
    @overload
    def _vector_(self, R: Parent[_NewScalar]) -> FreeModuleElement[_NewScalar]: ...
    def _sage_input_(
        self,
        sib: SageInputBuilder,
        coerce: bool,
    ) -> SageInputExpression: ...
    def numerical_approx(
        self,
        prec: int | Integer | None = ...,
        digits: int | Integer | None = ...,
        algorithm: str | None = ...,
    ) -> FreeModuleElement[RingElement]: ...
    def row(self) -> Matrix[_Scalar]: ...
    def column(self) -> Matrix[_Scalar]: ...
    def __copy__(self) -> Self: ...
    def subs(
        self,
        in_dict: Mapping[RingElement, ElementConstructorInput] | None = ...,
        **kwds: ElementConstructorInput,
    ) -> Self: ...
    def change_ring(self, R: Parent[_NewScalar]) -> FreeModuleElement[_NewScalar]: ...
    def coordinate_ring(self) -> Parent[RingElement]: ...
    def additive_order(self) -> Integer | AnInfinity: ...
    def items(self) -> Iterator[tuple[int, _Scalar]]: ...
    iteritems = items
    def __abs__(self) -> RingElement: ...
    def norm(
        self,
        p: int | Integer | float | RingElement | PlusInfinity = ...,
    ) -> RingElement: ...
    def _richcmp_(self, right: FreeModuleElement[_Scalar], op: int) -> bool: ...
    @overload
    def __getitem__(self, i: int | Integer) -> _Scalar: ...
    @overload
    def __getitem__(self, i: slice) -> FreeModuleElement[_Scalar]: ...
    def get(self, i: int | Integer) -> _Scalar: ...
    def __setitem__(
        self,
        i: int | Integer | slice,
        value: ElementConstructorInput | Sequence[ElementConstructorInput],
    ) -> None: ...
    def set(self, i: int | Integer, value: ElementConstructorInput) -> None: ...
    def __invert__(self) -> NoReturn: ...
    def __len__(self) -> int: ...
    def __mod__(self, p: ElementConstructorInput) -> Self: ...
    def Mod(self, p: ElementConstructorInput) -> FreeModuleElement[RingElement]: ...
    def list(self, copy: bool = ...) -> list[_Scalar]: ...
    def list_from_positions(
        self,
        positions: Iterable[int | Integer],
    ) -> list[_Scalar]: ...
    def lift(self) -> FreeModuleElement[RingElement]: ...
    def lift_centered(self) -> FreeModuleElement[RingElement]: ...
    def __pos__(self) -> Self: ...
    def __pow__(self, n: int | Integer, dummy: None = ...) -> NoReturn: ...
    def _repr_(self) -> str: ...
    def _maple_init_(self) -> str: ...
    def degree(self) -> int: ...
    def denominator(self) -> Integer: ...
    def dict(self, copy: bool = ...) -> dict[int, _Scalar]: ...
    def plot(
        self,
        plot_type: VectorPlotType | None = ...,
        start: Sequence[ElementConstructorInput] | None = ...,
        **kwds: object,
    ) -> Graphics | Graphics3d: ...
    def plot_step(
        self,
        xmin: RingElement | int | float = ...,
        xmax: RingElement | int | float = ...,
        eps: RingElement | int | float | None = ...,
        res: int | Integer | None = ...,
        connect: bool = ...,
        **kwds: object,
    ) -> Graphics: ...
    def _dot_product_coerce_(
        self,
        right: FreeModuleElement[_OtherScalar],
    ) -> RingElement: ...
    @overload
    def dot_product(self, right: FreeModuleElement[_Scalar]) -> _Scalar: ...
    @overload
    def dot_product(self, right: FreeModuleElement[_OtherScalar]) -> RingElement: ...
    def cross_product(
        self,
        right: FreeModuleElement[_OtherScalar],
    ) -> FreeModuleElement[RingElement]: ...
    def pairwise_product(
        self,
        right: FreeModuleElement[_OtherScalar],
    ) -> FreeModuleElement[RingElement]: ...
    def _variables(self) -> list[RingElement]: ...
    def div(
        self,
        variables: Sequence[RingElement] | None = ...,
    ) -> RingElement: ...
    def curl(
        self,
        variables: Sequence[RingElement] | None = ...,
    ) -> RingElement | FreeModuleElement[RingElement]: ...
    def element(self) -> Self: ...
    def monic(self) -> FreeModuleElement[RingElement]: ...
    def normalized(
        self,
        p: int | Integer | float | RingElement | PlusInfinity = ...,
    ) -> FreeModuleElement[RingElement]: ...
    def conjugate(self) -> FreeModuleElement[RingElement]: ...
    def inner_product(
        self,
        right: FreeModuleElement[_OtherScalar],
    ) -> RingElement: ...
    def outer_product(
        self,
        right: FreeModuleElement[_OtherScalar],
    ) -> Matrix[RingElement]: ...
    def is_dense(self) -> bool: ...
    def is_sparse(self) -> bool: ...
    def is_vector(self) -> Literal[True]: ...
    def _macaulay2_(self, macaulay2: Expect | None = ...) -> ExpectElement: ...
    def _mathematica_init_(self) -> str: ...
    def _sympy_(self) -> MatrixBase: ...
    def nonzero_positions(self) -> list[int]: ...
    def support(self) -> list[int]: ...
    def hamming_weight(self) -> int: ...
    def _latex_(self) -> str: ...
    def dense_vector(self) -> FreeModuleElement[_Scalar]: ...
    def sparse_vector(self) -> FreeModuleElement[_Scalar]: ...
    @overload
    def apply_map(
        self,
        phi: Callable[[_Scalar], _NewScalar],
        R: Parent[_NewScalar],
        sparse: bool | None = ...,
    ) -> FreeModuleElement[_NewScalar]: ...
    @overload
    def apply_map(
        self,
        phi: Callable[[_Scalar], RingElement],
        R: None = ...,
        sparse: bool | None = ...,
    ) -> FreeModuleElement[RingElement]: ...
    def _derivative(
        self,
        var: RingElement | None = ...,
    ) -> FreeModuleElement[RingElement]: ...
    def derivative(self, *args: object) -> FreeModuleElement[RingElement]: ...
    diff = derivative
    def integral(
        self,
        *args: object,
        **kwds: object,
    ) -> FreeModuleElement[RingElement]: ...
    integrate = integral
    def nintegral(
        self,
        *args: object,
        **kwds: object,
    ) -> tuple[FreeModuleElement[RingElement], NumericalIntegralData]: ...
    nintegrate = nintegral
    @overload
    def concatenate(
        self,
        other: Iterable[ElementConstructorInput],
        *,
        ring: Parent[_NewScalar],
    ) -> FreeModuleElement[_NewScalar]: ...
    @overload
    def concatenate(
        self,
        other: Iterable[ElementConstructorInput],
        *,
        ring: None = ...,
    ) -> FreeModuleElement[RingElement]: ...
    def compositional_inverse(
        self,
        allow_multivalued_inverse: bool = ...,
        **kwargs: object,
    ) -> FreeModuleElement[RingElement]: ...
    def __neg__(self) -> Self: ...
    def __add__(self, right: FreeModuleElement[_Scalar]) -> Self: ...
    def __sub__(self, right: FreeModuleElement[_Scalar]) -> Self: ...
    @overload
    def __mul__(self, right: FreeModuleElement[_Scalar]) -> _Scalar: ...
    @overload
    def __mul__(self, right: Matrix[_Scalar]) -> Self: ...
    @overload
    def __mul__(self, right: _Scalar | int | Integer) -> Self: ...
    def __rmul__(self, left: _Scalar | int | Integer) -> Self: ...


class FreeModuleElement_generic_dense(FreeModuleElement[_Scalar], Generic[_Scalar]):
    def __init__(
        self,
        parent: FreeModule_generic[_Scalar],
        entries: Sequence[ElementConstructorInput] = ...,
        coerce: bool = ...,
        copy: bool = ...,
    ) -> None: ...
    def __copy__(self) -> Self: ...
    def _add_(self, right: Self) -> Self: ...
    def _sub_(self, right: Self) -> Self: ...
    def _rmul_(self, left: Element) -> Self: ...
    def _lmul_(self, right: Element) -> Self: ...
    def _pairwise_product_(self, right: Vector[_Scalar]) -> Self: ...
    def __reduce__(
        self,
    ) -> tuple[
        Callable[..., FreeModuleElement_generic_dense[_Scalar]],
        tuple[FreeModule_generic[_Scalar], list[_Scalar], int, bool],
    ]: ...
    def list(self, copy: bool = ...) -> list[_Scalar]: ...
    def __call__(
        self,
        *args: object,
        **kwargs: object,
    ) -> FreeModuleElement[RingElement]: ...
    def function(self, *args: RingElement) -> FreeModuleElement[RingElement]: ...


class FreeModuleElement_generic_sparse(FreeModuleElement[_Scalar], Generic[_Scalar]):
    def __init__(
        self,
        parent: FreeModule_generic[_Scalar],
        entries: Mapping[int | Integer, ElementConstructorInput]
        | Sequence[ElementConstructorInput] = ...,
        coerce: bool = ...,
        copy: bool = ...,
    ) -> None: ...
    def __copy__(self) -> Self: ...
    def _add_(self, right: Self) -> Self: ...
    def _sub_(self, right: Self) -> Self: ...
    def _lmul_(self, right: Element) -> Self: ...
    def _rmul_(self, left: Element) -> Self: ...
    def _dot_product_coerce_(
        self,
        right: FreeModuleElement[_OtherScalar],
    ) -> RingElement: ...
    def _pairwise_product_(self, right: Vector[_Scalar]) -> Self: ...
    def _richcmp_(self, right: Self, op: int) -> bool: ...
    def items(self) -> Iterator[tuple[int, _Scalar]]: ...
    iteritems = items
    def __reduce__(
        self,
    ) -> tuple[
        Callable[..., FreeModuleElement_generic_sparse[_Scalar]],
        tuple[FreeModule_generic[_Scalar], dict[int, _Scalar], int, bool],
    ]: ...
    @overload
    def __getitem__(self, i: int | Integer) -> _Scalar: ...
    @overload
    def __getitem__(self, i: slice) -> FreeModuleElement[_Scalar]: ...
    def denominator(self) -> Integer: ...
    def dict(self, copy: bool = ...) -> dict[int, _Scalar]: ...
    def list(self, copy: bool = ...) -> list[_Scalar]: ...
    def nonzero_positions(self) -> list[int]: ...
    def hamming_weight(self) -> int: ...


from sage.modules.free_module import FreeModule_generic
