from collections.abc import Callable, Iterable
from typing import Generic, TypeVar, overload

from sage.categories.rings import Rings
from sage.matrix.matrix import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.plot.graphics import Graphics
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import Element, RingElement, Vector

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

class FreeModuleElement(Vector[_Scalar], Generic[_Scalar]):
    def __init__(self) -> None: ...
    def monomial_coefficients(self, copy: bool = ...) -> dict[int, Element]: ...
    def __pari__(self) -> Element: ...
    def numpy(self, dtype: type | None = ...) -> Element: ...
    def __hash__(self) -> int: ...
    def numerical_approx(
        self,
        prec: int | None = ...,
        digits: int | None = ...,
        algorithm: str | None = ...,
    ) -> FreeModuleElement: ...
    def row(self) -> Matrix: ...
    def column(self) -> Matrix: ...
    def __copy__(self) -> FreeModuleElement: ...
    def subs(
        self, in_dict: dict[object, object] | None = ..., **kwds: object
    ) -> FreeModuleElement: ...
    def change_ring(self, R: Ring) -> FreeModuleElement: ...
    def coordinate_ring(self) -> Ring: ...
    def additive_order(self) -> Integer | float: ...
    def items(self) -> list[tuple[int, Element]]: ...
    def __abs__(self) -> Element: ...
    def parent(self) -> FreeModule_generic[RingElement]: ...
    def __neg__(self) -> FreeModuleElement[RingElement]: ...
    def __add__(self, other: Vector[_Scalar]) -> FreeModuleElement[_Scalar]: ...
    def __sub__(self, other: Vector[_Scalar]) -> FreeModuleElement[_Scalar]: ...
    @overload
    def __mul__(self, other: Matrix[_Scalar]) -> FreeModuleElement[_Scalar]: ...
    @overload
    def __mul__(self, other: Vector[_Scalar]) -> _Scalar: ...
    @overload
    def __mul__(self, other: int | _Scalar) -> FreeModuleElement[_Scalar]: ...
    def __rmul__(self, other: int | _Scalar) -> FreeModuleElement[_Scalar]: ...
    def __floordiv__(self, other: int | _Scalar) -> FreeModuleElement[_Scalar]: ...
    def norm(self, p: Integer | float = ...) -> RingElement | float: ...
    def __getitem__(self, i: int) -> Element: ...
    def get_unsafe(self, i: int) -> Element: ...
    def get(self, i: int) -> Element: ...
    def __setitem__(self, i: int, value: Element) -> None: ...
    def set(self, i: int, value: Element) -> None: ...
    def __invert__(self) -> FreeModuleElement: ...
    def __len__(self) -> int: ...
    def __mod__(self, p: Element) -> FreeModuleElement: ...
    def Mod(self, p: Element) -> FreeModuleElement: ...
    def list(self, copy: bool = ...) -> list[Element]: ...
    def list_from_positions(self, positions: Iterable[int]) -> list[Element]: ...
    def lift(self) -> FreeModuleElement: ...
    def lift_centered(self) -> FreeModuleElement: ...
    def __pos__(self) -> FreeModuleElement: ...
    def __pow__(self, n: int) -> FreeModuleElement: ...
    def degree(self) -> int: ...
    def denominator(self) -> Element: ...
    def dict(self, copy: bool = ...) -> dict[int, Element]: ...
    def plot(
        self,
        plot_type: str | None = ...,
        start: FreeModuleElement | None = ...,
        **kwds: object,
    ) -> Graphics: ...
    def plot_step(
        self,
        xmin: float = ...,
        xmax: float = ...,
        eps: float | None = ...,
        res: int | None = ...,
        **kwds: object,
    ) -> Graphics: ...
    def dot_product(self, right: FreeModuleElement) -> Element: ...
    def cross_product(self, right: FreeModuleElement) -> FreeModuleElement: ...
    def cross_product_matrix(self) -> Matrix: ...
    def pairwise_product(self, right: FreeModuleElement) -> FreeModuleElement: ...
    def div(self, variables: Iterable[object] | None = ...) -> Element: ...
    def curl(self, variables: Iterable[object] | None = ...) -> FreeModuleElement: ...
    def element(self) -> FreeModuleElement: ...
    def monic(self) -> FreeModuleElement: ...
    def normalized(self, p: Integer | float = ...) -> FreeModuleElement: ...
    def conjugate(self) -> FreeModuleElement: ...
    def inner_product(self, right: FreeModuleElement) -> Element: ...
    def outer_product(self, right: FreeModuleElement) -> Matrix: ...
    def hermitian_inner_product(self, right: FreeModuleElement) -> Element: ...
    def is_dense(self) -> bool: ...
    def is_sparse(self) -> bool: ...
    def is_vector(self) -> bool: ...
    def nonzero_positions(self) -> list[int]: ...
    def support(self) -> list[int]: ...
    def dense_vector(self) -> FreeModuleElement: ...
    def sparse_vector(self) -> FreeModuleElement: ...
    def apply_map(
        self,
        phi: Callable[[Element], Element],
        R: Ring | None = ...,
        sparse: bool | None = ...,
    ) -> FreeModuleElement: ...
    def derivative(self, *args: object) -> FreeModuleElement: ...
    def integral(self, *args: object, **kwds: object) -> FreeModuleElement: ...
    def nintegral(
        self, *args: object, **kwds: object
    ) -> tuple[tuple[float, ...], float, int, str]: ...
    def concatenate(
        self, other: FreeModuleElement, *, ring: Ring | None = ...
    ) -> FreeModuleElement: ...
    def compositional_inverse(
        self, allow_multivalued_inverse: bool = ..., **kwargs: object
    ) -> FreeModuleElement: ...
    def function(self, *args: object) -> Callable[..., Element]: ...

@overload
def vector(
    entries: Iterable[int | Integer | Rational],
    *,
    sparse: bool | None = ...,
    immutable: bool = ...,
) -> FreeModuleElement[Integer | Rational]: ...
@overload
def vector(
    base_ring: Rings.ParentMethods[_Scalar],
    entries: Iterable[int | _Scalar],
    *,
    sparse: bool | None = ...,
    immutable: bool = ...,
) -> FreeModuleElement[_Scalar]: ...
