from collections.abc import Iterable
from typing import Self

from sage.matrix.matrix_integer_dense import Matrix_integer_dense
from sage.modules.free_module import FreeModule_ambient, FreeModule_submodule
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer


class FreeModule_ambient_integer(FreeModule_ambient[Integer]):
    def basis_matrix(self) -> Matrix_integer_dense: ...
    def span(
        self,
        gens: Iterable[FreeModuleElement[Integer]],
        check: bool = ...,
        already_echelonized: bool = ...,
    ) -> FreeModule_submodule_integer: ...
    submodule = span
    def dual_module(self) -> Self: ...


class FreeModule_submodule_integer(FreeModule_submodule[Integer]):
    def basis_matrix(self) -> Matrix_integer_dense: ...
    def echelonized_basis_matrix(self) -> Matrix_integer_dense: ...
    def saturation(self, p: int | Integer = ...) -> Self: ...
    def index_in_saturation(self) -> Integer: ...
    def is_primitive(self) -> bool: ...
    def quotient(self, submodule: FreeModule_submodule_integer) -> object: ...
