from typing import Literal, Self

from sage.categories.homset import Homset
from sage.categories.morphism import Morphism
from sage.matrix.matrix import Matrix
from sage.structure.parent import Parent


class MatrixMorphism_abstract(Morphism):
    def __init__(
        self,
        parent: Homset[Parent, Parent],
        side: Literal["left", "right"] = "left",
    ) -> None: ...
    def matrix(self) -> Matrix: ...
    def side(self) -> Literal["left", "right"]: ...
    def side_switch(self) -> Self: ...
    def inverse(self) -> Self: ...
    def rank(self) -> int: ...
    def nullity(self) -> int: ...
    def is_injective(self) -> bool: ...
    def is_surjective(self) -> bool: ...
    def is_bijective(self) -> bool: ...
    def is_identity(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_equal_function(self, other: MatrixMorphism_abstract) -> bool: ...
    def restrict_domain(self, sub: Parent) -> Self: ...
    def restrict_codomain(self, sub: Parent) -> Self: ...
    def restrict(self, sub: Parent) -> Self: ...


class MatrixMorphism(MatrixMorphism_abstract):
    def __init__(
        self,
        parent: Homset[Parent, Parent],
        A: Matrix | MatrixMorphism_abstract,
        copy_matrix: bool = True,
        side: Literal["left", "right"] = "left",
    ) -> None: ...
    def matrix(self, side: Literal["left", "right"] | None = None) -> Matrix: ...
