import builtins

class _SageObject: ...

class QuotientModuleFunctor:
    rank: _SageObject

    def __init__(self, relations: builtins.object) -> None: ...
    def relations(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def merge(self, other: builtins.object) -> _SageObject: ...
