from collections.abc import Iterator, Sequence
from typing import Self, TypeVar
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_homspace import FreeModuleHomspace
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_double import RealDoubleElement
from sage.rings.complex_double import ComplexDoubleElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

import builtins

class _SageObject: ...

def MultiFilteredVectorSpace(
    arg: builtins.object, base_ring: builtins.object = ..., check: builtins.bool = ...
) -> ElementConstructorInput: ...

class MultiFilteredVectorSpace_class:
    def __init__(
        self,
        base_ring: builtins.object,
        dim: builtins.object,
        filtrations: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def index_set(self) -> FreeModule_generic: ...
    def change_ring(self, base_ring: builtins.object) -> FreeModule_generic: ...
    def ambient_vector_space(self) -> FreeModule_generic: ...
    def is_constant(self) -> builtins.bool: ...
    def is_exhaustive(self) -> builtins.bool: ...
    def is_separating(self) -> builtins.bool: ...
    def support(self) -> FreeModule_generic: ...
    def min_degree(self) -> FreeModule_generic: ...
    def max_degree(self) -> FreeModule_generic: ...
    def get_filtration(self, key: builtins.object) -> FreeModule_generic: ...
    def get_degree(
        self, key: builtins.object, deg: builtins.object
    ) -> FreeModule_generic: ...
    def graded(
        self, key: builtins.object, deg: builtins.object
    ) -> FreeModule_generic: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def direct_sum(self, other: builtins.object) -> FreeModule_generic: ...
    def tensor_product(self, other: builtins.object) -> FreeModule_generic: ...
    def exterior_power(self, n: builtins.int) -> FreeModule_generic: ...
    wedge: _SageObject

    def symmetric_power(self, n: builtins.int) -> FreeModule_generic: ...
    def dual(self) -> FreeModule_generic: ...
    def shift(self, deg: builtins.object) -> FreeModule_generic: ...
    def random_deformation(
        self, epsilon: builtins.object = ...
    ) -> FreeModule_generic: ...
