import builtins

from sage.structure.element import Element

class _SageObject: ...
class ScalarAction: ...
class OreAction: ...

def normalize_names(self, rank: builtins.int) -> _SageObject: ...

class OreModule:
    Element: _SageObject

    def __classcall_private__(
        self,
        mat: builtins.object,
        twist: builtins.object,
        denominator: builtins.object = ...,
        names: builtins.object = ...,
        category: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        mat: builtins.object,
        ore: builtins.object,
        denominator: builtins.object,
        names: builtins.object,
        category: builtins.object,
    ) -> None: ...
    def is_zero(self) -> bool: ...
    def rename_basis(
        self, names: builtins.object, coerce: builtins.bool = ...
    ) -> _SageObject: ...
    def pseudohom(self) -> _SageObject: ...
    def ore_ring(
        self, names: builtins.str = ..., action: builtins.bool = ...
    ) -> _SageObject: ...
    def twisting_morphism(self) -> _SageObject: ...
    def twisting_derivation(self) -> _SageObject: ...
    def matrix(self) -> _SageObject: ...
    def over_fraction_field(self) -> _SageObject: ...
    def basis(self) -> list[Element]: ...
    def gens(self) -> list[Element]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def random_element(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def module(self) -> _SageObject: ...
    def hom(
        self, im_gens: builtins.object, codomain: builtins.object = ...
    ) -> _SageObject: ...
    def multiplication_map(self, P: builtins.int) -> _SageObject: ...
    def identity_morphism(self) -> _SageObject: ...
    def span(
        self,
        gens: builtins.object,
        saturate: builtins.bool = ...,
        names: builtins.object = ...,
        check: builtins.bool = ...,
    ) -> _SageObject: ...
    submodule: _SageObject

    def quotient(
        self,
        sub: builtins.object,
        remove_torsion: builtins.bool = ...,
        names: builtins.object = ...,
        check: builtins.bool = ...,
    ) -> _SageObject: ...
    quo: _SageObject

    def ambient_modules(self) -> list[Element]: ...
    def is_submodule(self, other: builtins.object) -> bool: ...
    def fitting_index(self, other: builtins.object = ...) -> _SageObject: ...
    def covers(self) -> list[Element]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class OreSubmodule:
    def __classcall_private__(
        self,
        ambient: builtins.object,
        gens: builtins.object,
        saturate: builtins.object,
        names: builtins.object,
    ) -> _SageObject: ...
    def __init__(
        self,
        ambient: builtins.object,
        submodule: builtins.object,
        names: builtins.object,
    ) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def ambient_module(self) -> _SageObject: ...
    def ambient_modules(self) -> list[Element]: ...
    def over_fraction_field(self) -> _SageObject: ...
    def saturate(
        self, names: builtins.object = ..., coerce: builtins.bool = ...
    ) -> _SageObject: ...
    def rename_basis(
        self, names: builtins.object, coerce: builtins.bool = ...
    ) -> _SageObject: ...
    def injection_morphism(self) -> _SageObject: ...
    def morphism_restriction(self, f: builtins.object) -> _SageObject: ...
    def morphism_corestriction(self, f: builtins.object) -> _SageObject: ...

class OreQuotientModule:
    def __classcall_private__(
        self,
        cover: builtins.object,
        gens: builtins.object,
        remove_torsion: builtins.object,
        names: builtins.object,
    ) -> _SageObject: ...
    def __init__(
        self, cover: builtins.object, submodule: builtins.object, names: builtins.object
    ) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def over_fraction_field(self) -> _SageObject: ...
    def cover(self) -> _SageObject: ...
    def covers(self) -> list[Element]: ...
    def relations(self, names: builtins.object = ...) -> _SageObject: ...
    def rename_basis(
        self, names: builtins.object, coerce: builtins.bool = ...
    ) -> _SageObject: ...
    def projection_morphism(self) -> _SageObject: ...
    def morphism_quotient(self, f: builtins.object) -> _SageObject: ...
    def morphism_modulo(self, f: builtins.object) -> _SageObject: ...
