import builtins

class _SageObject: ...

class OreModuleMorphism:
    def __init__(
        self,
        parent: builtins.object,
        im_gens: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def matrix(self) -> _SageObject: ...
    def is_zero(self) -> bool: ...
    def is_identity(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def is_injective(self) -> bool: ...
    def is_surjective(self) -> bool: ...
    def is_bijective(self) -> bool: ...
    def is_isomorphism(self) -> bool: ...
    def inverse(self) -> _SageObject: ...
    def kernel(self, names: builtins.object = ...) -> _SageObject: ...
    def image(
        self, saturate: builtins.bool = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def cokernel(
        self, remove_torsion: builtins.bool = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def coimage(self, names: builtins.object = ...) -> _SageObject: ...
    def determinant(self) -> _SageObject: ...
    det: _SageObject

    def characteristic_polynomial(self, var: builtins.str = ...) -> _SageObject: ...
    charpoly: _SageObject

class OreModuleRetraction: ...
class OreModuleSection: ...
