# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class OreModule_homspace:
    Element: _SageObject
    def __init__(self, domain: builtins.object, codomain: builtins.object, category: builtins.object = ...) -> None: ...
    def matrix_space(self) -> _SageObject: ...
    def identity(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
