# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class QuotientModule_free_ambient:
    def __init__(self, module: builtins.object, sub: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def gen(self, i: builtins.int = ...) -> _SageObject: ...
    def ambient_module(self) -> _SageObject: ...
    def cover(self) -> _SageObject: ...
    V: _SageObject
    def relations(self) -> _SageObject: ...
    W: _SageObject
    def free_cover(self) -> _SageObject: ...
    def free_relations(self) -> _SageObject: ...

class FreeModule_ambient_field_quotient:
    def __init__(self, domain: builtins.object, sub: builtins.object, quotient_matrix: builtins.object, lift_matrix: builtins.object, inner_product_matrix: builtins.object = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def quotient_map(self) -> _SageObject: ...
    def lift_map(self) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def cover(self) -> _SageObject: ...
    V: _SageObject
    def relations(self) -> _SageObject: ...
    W: _SageObject
