from collections.abc import Iterable
from typing import Generic, Self, TypeVar

from sage.matrix.matrix import Matrix
from sage.modules.free_module import FreeModule_ambient, FreeModule_generic, FreeModule_submodule
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.structure.element import RingElement

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)


class Submodule(FreeModule_submodule[_Scalar], Generic[_Scalar]):
    def ambient_module(self) -> FreeModule_ambient[_Scalar]: ...
    def basis_matrix(self) -> Matrix[_Scalar]: ...
    def echelonized_basis_matrix(self) -> Matrix[_Scalar]: ...
    def gens(self) -> tuple[FreeModuleElement[_Scalar], ...]: ...
    def intersection(self, other: FreeModule_generic[_Scalar]) -> Self: ...
    def sum(self, other: FreeModule_generic[_Scalar]) -> Self: ...
    def saturation(self) -> Self: ...
    def index_in(self, other: FreeModule_generic[_Scalar]) -> Integer: ...
    def quotient(self, submodule: FreeModule_generic[_Scalar]) -> object: ...


def span(
    ambient: FreeModule_ambient[_Scalar],
    generators: Iterable[FreeModuleElement[_Scalar]],
    check: bool = ...,
    already_echelonized: bool = ...,
) -> Submodule[_Scalar]: ...
