# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Submodule_free_ambient:
    def __init__(self, ambient: builtins.object, gens: builtins.object, check: builtins.bool = ..., already_echelonized: builtins.bool = ...) -> None: ...
    def matrix(self) -> _SageObject: ...
    generators_matrix: _SageObject
    def relations(self) -> _SageObject: ...
    def gens(self) -> builtins.list[_SageObject]: ...
    def gen(self, i: builtins.int = ...) -> _SageObject: ...
    def ambient_module(self) -> _SageObject: ...
