from collections.abc import Sequence
from typing import Self

from sage.matrix.matrix_integer_dense import Matrix_integer_dense
from sage.modules.free_module_element import FreeModuleElement_generic_dense
from sage.rings.integer import Integer
from sage.structure.parent import ElementConstructorInput


class Vector_integer_dense(FreeModuleElement_generic_dense[Integer]):
    def __init__(
        self,
        parent: object,
        entries: Sequence[int | Integer | ElementConstructorInput] = ...,
        coerce: bool = ...,
        copy: bool = ...,
    ) -> None: ...
    def __copy__(self) -> Self: ...
    def list(self, copy: bool = ...) -> list[Integer]: ...
    def denominator(self) -> Integer: ...
    def dot_product(self, right: Vector_integer_dense) -> Integer: ...
    inner_product = dot_product
    def pairwise_product(self, right: Vector_integer_dense) -> Self: ...
    def norm(self, p: int | float | None = ...) -> object: ...
    def row(self) -> Matrix_integer_dense: ...
    def column(self) -> Matrix_integer_dense: ...
    def gcd(self) -> Integer: ...
    content = gcd
