# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def allocate_c_vector_modint(v: builtins.object, num_nonzero: builtins.object) -> _SageObject: ...

def clear_c_vector_modint(v: builtins.object) -> _SageObject: ...

def binary_search0_modn(v: builtins.object, n: builtins.object, x: builtins.object) -> _SageObject: ...

def binary_search_modn(v: builtins.object, n: builtins.object, x: builtins.object, ins: builtins.object) -> _SageObject: ...

def get_entry(v: builtins.object, n: builtins.object) -> _SageObject: ...

def is_entry_zero_unsafe(v: builtins.object, n: builtins.object) -> builtins.bool: ...

def to_list(v: builtins.object) -> _SageObject: ...

def set_entry(v: builtins.object, n: builtins.object, x: builtins.object) -> _SageObject: ...

def scale_c_vector_modint(v: builtins.object, scalar: builtins.object) -> _SageObject: ...
