from typing import Generic, Self, TypeVar

from sage.matrix.matrix import Matrix
from sage.modules.free_module import FreeModule_submodule, VectorSpace
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_morphism import FreeModuleMorphism
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import FieldElement

_Scalar = TypeVar("_Scalar", bound=FieldElement, default=FieldElement)


class VectorSpaceMorphism(
    FreeModuleMorphism[_Scalar],
    Generic[_Scalar],
):
    def domain(self) -> VectorSpace[_Scalar]: ...
    def codomain(self) -> VectorSpace[_Scalar]: ...
    def matrix(self, side: str | None = ...) -> Matrix[_Scalar]: ...
    def kernel(self) -> FreeModule_submodule[_Scalar]: ...
    def image(self) -> FreeModule_submodule[_Scalar]: ...
    range = image
    def rank(self) -> int: ...
    def nullity(self) -> int: ...
    def characteristic_polynomial(self, var: str = ...) -> Polynomial: ...
    charpoly = characteristic_polynomial
    def minimal_polynomial(self, var: str = ...) -> Polynomial: ...
    minpoly = minimal_polynomial
    def eigenvalues(self) -> list[_Scalar]: ...
    def eigenvectors(self) -> list[tuple[_Scalar, list[FreeModuleElement[_Scalar]], int]]: ...
    def is_diagonalizable(self) -> bool: ...
    def inverse(self) -> Self: ...
    __invert__ = inverse
