class AttrCallObject:
    name: str
    args: tuple[object, ...]
    kwds: dict[str, object]

    def __init__(self, name: str, args: tuple[object, ...], kwds: dict[str, object]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def attrcall(name: str, *args: object, **kwds: object) -> AttrCallObject: ...
