from sage.misc.nested_class import NestedClassMetaclass

class ClasscallMetaclass(NestedClassMetaclass):
    def __cinit__(self, *args: object, **opts: object) -> None: ...
    def _set_classcall(cls: type, function: object) -> None: ...
    def __call__(cls: type, *args: object, **kwds: object) -> object: ...
    def __get__(cls: type, instance: object | None, owner: type) -> object: ...
    def __contains__(cls: type, x: object) -> bool: ...

def typecall(cls: type, *args: object, **kwds: object) -> object: ...
def timeCall(T: type, n: int, *args: object) -> None: ...
