var_name: str

def variable_names(self, name: str | None = ...) -> tuple[str, ...]: ...
def latex_variable_names(self, name: str | None = ...) -> tuple[str, ...]: ...
def set_default_variable_name(self, separator: str = ...) -> None: ...

series_prec: int

def series_precision(self) -> int: ...
def set_series_precision(self) -> None: ...
