import builtins

class _SageObject: ...

def runsnake(self) -> _SageObject: ...
def import_statement_string(
    self, names: builtins.object, lazy: builtins.object
) -> _SageObject: ...
def load_submodules(
    self=..., exclude_pattern: builtins.object = ...
) -> _SageObject: ...
def find_objects_from_name(
    self, module_name: builtins.str = ..., include_lazy_imports: builtins.bool = ...
) -> _SageObject: ...
def import_statements(
    self, *objects: builtins.object, **kwds: builtins.object
) -> _SageObject: ...
