from sage.misc.classcall_metaclass import ClasscallMetaclass

class WithEqualityById:
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...

class FastHashable_class:
    h: int
    def __init__(self, h: int) -> None: ...
    def __hash__(self) -> int: ...

class Singleton(WithEqualityById, metaclass=ClasscallMetaclass):
    @staticmethod
    def __classcall__(cls: type) -> Singleton: ...
    def __copy__(self) -> Singleton: ...
    def __reduce__(self) -> tuple[type, tuple[()]]: ...
