import types
from collections.abc import Callable
from typing import TypeVar

_R = TypeVar("_R")

def code_ctor(*args: object) -> types.CodeType: ...
def reduce_code(co: types.CodeType) -> tuple[Callable[..., types.CodeType], tuple[object, ...]]: ...
def pickle_function(func: Callable[..., object]) -> bytes: ...
def unpickle_function(pickled: bytes) -> Callable[..., object]: ...
def call_pickled_function(
    fpargs: tuple[bytes, tuple[tuple[object, ...], dict[str, object]]],
) -> tuple[tuple[tuple[object, ...], dict[str, object]], _R]: ...
def pickleMethod(
    method: types.MethodType,
) -> tuple[Callable[..., object], tuple[str, object | None, type]]: ...
def unpickleMethod(
    im_name: str,
    __self__: object | None,
    im_class: type,
) -> types.MethodType | Callable[..., object]: ...
def pickleModule(module: types.ModuleType) -> tuple[Callable[[str], types.ModuleType], tuple[str]]: ...
def unpickleModule(name: str) -> types.ModuleType: ...
