
def additive_order(self) -> object | None: ...
def base_ring(self) -> object | None: ...
def base_field(self) -> object | None: ...
def basis(self) -> object | None: ...
def category(self) -> object | None: ...
def characteristic_polynomial(self, var: str = ...) -> object | None: ...

charpoly = characteristic_polynomial

def coerce(self, x: object) -> object | None: ...
def cyclotomic_polynomial(self, var: str = ...) -> object | None: ...
def decomposition(self) -> object | None: ...
def denominator(self) -> object | None: ...
def det(self) -> object | None: ...
def dimension(self) -> object | None: ...

dim = dimension

def discriminant(self) -> object | None: ...

disc = discriminant

def eta(self) -> object | None: ...
def fcp(self, var: str = ...) -> object | None: ...
def gen(self) -> object | None: ...
def gens(self) -> object | None: ...
def hecke_operator(self, n: int) -> object | None: ...
def image(self) -> object | None: ...
def symbolic_sum(self, *args: object, **kwds: object) -> object | None: ...
def symbolic_prod(self, *args: object, **kwds: object) -> object | None: ...
def integral(self, *args: object, **kwds: object) -> object | None: ...

integrate = integral

def integral_closure(self) -> object | None: ...
def interval(self, b: int) -> list[int]: ...
def xinterval(self, b: int) -> range: ...
def is_even(self) -> bool: ...
def is_odd(self) -> bool: ...
def kernel(self) -> object | None: ...
def krull_dimension(self) -> object | None: ...
def lift(self) -> object | None: ...
def log(self, *args: object, **kwds: object) -> object | None: ...
def minimal_polynomial(self, var: str = ...) -> object | None: ...

minpoly = minimal_polynomial

def multiplicative_order(self) -> object | None: ...
def ngens(self) -> int: ...
def norm(self) -> object | None: ...
def numerator(self) -> object | None: ...
def numerical_approx(
    self, prec: int | None = ..., digits: int | None = ..., algorithm: str | None = ...
) -> object | None: ...

n = numerical_approx
N = numerical_approx

def objgens(self) -> tuple[object, object]: ...
def objgen(self) -> tuple[object, object]: ...
def order(self) -> object | None: ...
def rank(self) -> object | None: ...
def regulator(self) -> object | None: ...
def round(self, ndigits: int = ...) -> object | None: ...
def quotient(self, y: object, *args: object, **kwds: object) -> object | None: ...

quo = quotient

def isqrt(self) -> object | None: ...
def squarefree_part(self) -> object | None: ...
def sqrt(self, *args: object, **kwds: object) -> object | None: ...
def transpose(self) -> object | None: ...
