from collections.abc import Callable

class func_persist:
    def __init__(self, f: Callable[..., object], dir: str = ...) -> None: ...
    def __call__(self, *args: object, **kwds: object) -> object | None: ...
