from sage.structure.sage_object import SageObject

class HtmlFragment(str, SageObject):
    def _rich_repr_(self, display_manager: object, **kwds: object) -> SageObject: ...

def math_parse(s: str) -> HtmlFragment: ...

class MathJaxExpr:
    def __init__(self, y: object) -> None: ...
    def __add__(self, y: str) -> MathJaxExpr: ...
    def __radd__(self, y: str) -> MathJaxExpr: ...

class MathJax:
    def __call__(self, x: object, combine_all: bool = ...) -> MathJaxExpr: ...
    def eval(
        self,
        x: object,
        globals: dict[str, object] | None = ...,
        locals: dict[str, object] | None = ...,
        mode: str = ...,
        combine_all: bool = ...,
    ) -> MathJaxExpr: ...

class HTMLFragmentFactory(SageObject):
    def _repr_(self) -> str: ...
    def __call__(self, obj: object, concatenate: bool = ..., strict: bool = ...) -> HtmlFragment: ...
    def eval(self, s: str, locals: dict[str, object] | None = ...) -> HtmlFragment: ...
    def iframe(self, url: str, height: int = ..., width: int = ...) -> HtmlFragment: ...

html: HTMLFragmentFactory

def pretty_print_default(enable: bool = ...) -> None: ...
