# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class InlineFortran:
    def __init__(self, globals: builtins.object = ...) -> None: ...
    def __call__(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def eval(self, x: builtins.object, globals: builtins.object = ..., locals: builtins.object = ...) -> _SageObject: ...
    def add_library(self, s: builtins.object) -> _SageObject: ...
    def add_library_path(self, s: builtins.object) -> _SageObject: ...

fortran: _SageObject
