from sage.structure.sage_object import SageObject
from typing import Self

def list_function(x: list[object]) -> str: ...
def tuple_function(x: tuple[object, ...], combine_all: bool = False) -> str: ...
def bool_function(x: bool) -> str: ...
def builtin_constant_function(x: object) -> str: ...
def None_function(x: None) -> str: ...
def str_function(x: str) -> str: ...
def dict_function(x: dict[object, object]) -> str: ...
def float_function(x: float) -> str: ...

class LatexExpr(str):
    def __new__(cls, s: str) -> Self: ...
    def _repr_mimebundle_(self, **kwargs: object) -> dict[str, str]: ...

def has_latex_attr(x: object) -> bool: ...
def default_engine() -> str: ...

class _Latex_prefs_object(SageObject):
    def __init__(self) -> None: ...
    def _reset(self) -> None: ...

def latex_extra_preamble() -> str: ...

class LatexCall:
    def __init__(self, *args: object) -> None: ...
    def __call__(self, x: object) -> str: ...
    def eval(self, x: object, mode: str = 'display', **kwds: object) -> str: ...

class Latex(LatexCall):
    def __init__(self, *args: object) -> None: ...
    def __call__(self, x: object) -> str: ...

class LatexExamples:
    def __init__(self, x: object) -> None: ...
