from sage.structure.sage_object import SageObject

class Standalone(SageObject):
    def __init__(
        self,
        content: str,
        document_class_options: list[str] | None = ...,
        standalone_config: list[str] | None = ...,
        usepackage: list[str] | None = ...,
        macros: list[str] | None = ...,
        use_sage_preamble: bool = ...,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def content(self) -> str: ...
    def add_document_class_option(self, option: str) -> None: ...
    def add_standalone_config(self, config: str) -> None: ...
    def add_usepackage(self, package: str) -> None: ...
    def add_macro(self, macro: str) -> None: ...
    def pdf(self, filename: str | None = ..., view: bool = ..., program: str | None = ...) -> str | None: ...
    def dvi(self, filename: str | None = ..., view: bool = ..., program: str = ...) -> str | None: ...
    def png(self, filename: str | None = ..., density: int = ..., view: bool = ...) -> str | None: ...
    def svg(self, filename: str | None = ..., view: bool = ..., program: str = ...) -> str | None: ...
    def eps(self, filename: str | None = ..., view: bool = ..., program: str = ...) -> str | None: ...
    def tex(self, filename: str | None = ..., content_only: bool = ..., include_header: bool | None = ...) -> str: ...
    def save(self, filename: str | None = ..., compress: bool = ..., **kwds: object) -> None: ...

class TikzPicture(Standalone):
    def __init__(
        self,
        content: str,
        standalone_config: list[str] | None = ...,
        usepackage: list[str] | None = ...,
        usetikzlibrary: list[str] | None = ...,
        macros: list[str] | None = ...,
        use_sage_preamble: bool = ...,
    ) -> None: ...
    def add_usetikzlibrary(self, library: str) -> None: ...
    @classmethod
    def from_dot_string(cls, dotdata: str, prog: str = ...) -> TikzPicture: ...
    @classmethod
    def from_graph(cls, graph: object, merge_multiedges: bool = ..., **kwds: object) -> TikzPicture: ...
    @classmethod
    def from_graph_with_pos(cls, graph: object, scale: float = ..., merge_multiedges: bool = ..., **kwds: object) -> TikzPicture: ...
    @classmethod
    def from_poset(cls, poset: object, **kwds: object) -> TikzPicture: ...
    def tikz_picture_code(self) -> str: ...
