def produce_latex_macro(self, *sample_args: object) -> str: ...
def convert_latex_macro_to_mathjax(
    self,
) -> tuple[str, str] | tuple[str, list[str | int]]: ...
def sage_latex_macros(self) -> list[str]: ...
def sage_mathjax_macros(self) -> dict[str, str | list[str | int]]: ...
