from collections.abc import Callable
from typing import Self, overload

class _lazy_attribute[Owner, Value]:
    f: Callable[[Owner], Value]
    __name__: str
    __doc__: str | None
    __module__: str
    def __init__(self, f: Callable[[Owner], Value]) -> None: ...
    def _sage_src_lines_(self) -> tuple[list[str], int]: ...
    @overload
    def __get__(self, instance: None, owner: type[Owner] | None = None) -> Self: ...
    @overload
    def __get__(self, instance: Owner, owner: type[Owner] | None = None) -> Value: ...

class lazy_attribute[Owner, Value](_lazy_attribute[Owner, Value]):
    def __init__(self, f: Callable[[Owner], Value]) -> None: ...

class lazy_class_attribute[Owner, Value](_lazy_attribute[Owner, Value]):
    @overload
    def __get__(self, instance: None, owner: type[Owner] | None = None) -> Value: ...
    @overload
    def __get__(self, instance: Owner, owner: type[Owner] | None = None) -> Value: ...
