from collections.abc import Callable, Iterable, Iterator
from contextlib import AbstractContextManager
from typing import TypeVar

_T = TypeVar("_T")
LOCAL_IDENTIFIER: str

def try_read(
    self, splitlines: bool = ...
) -> str | bytes | list[str] | list[bytes] | None: ...
def exactly_one_is_true(self) -> bool: ...
def strunc(self, n: int = ...) -> str: ...
def newton_method_sizes(self) -> list[int]: ...
def compose(self, g: Callable[[object], object]) -> Callable[[object], object]: ...
def nest(self, n: int, x: object) -> object | None: ...
def is_iterator(self) -> bool: ...
def random_sublist(self, s: float) -> list[_T]: ...
def is_sublist(self, Y: Iterable[_T]) -> bool: ...
def some_tuples(
    self, repeat: int | None, bound: int, max_samples: int | None = ...
) -> Iterator[_T | tuple[_T, ...]] | list[_T | tuple[_T, ...]]: ...
def exists(self, P: Callable[[_T], bool]) -> tuple[bool, _T | None]: ...
def forall(self, P: Callable[[_T], bool]) -> tuple[bool, _T | None]: ...
def word_wrap(self, ncols: int = ...) -> str: ...
def pad_zeros(self, size: int = ...) -> str: ...
def is_in_string(self, pos: int) -> bool: ...
def get_main_globals(self) -> dict[str, object]: ...
def inject_variable(self, value: object, warn: bool = ...) -> None: ...
def inject_variable_test(self, value: object, depth: int) -> None: ...
def run_once(self) -> Callable[..., object]: ...
def increase_recursion_limit(self) -> AbstractContextManager[None]: ...

set_trace: Callable[[], None]
