class MultiplexFunction:
    multiplexer: Multiplex
    name: str
    def __init__(self, multiplexer: Multiplex, name: str) -> None: ...
    def __call__(self, *args: object, **kwds: object) -> tuple[object, ...] | None: ...

class Multiplex:
    children: list[object]
    def __init__(self, *args: object) -> None: ...
    def __getattr__(self, name: str) -> MultiplexFunction: ...
