import pkgutil
from collections.abc import Callable, Iterator

def is_package_or_sage_namespace_package_dir(self) -> bool: ...
def cython_namespace_package_support(self) -> None: ...
def walk_packages(
    self=..., prefix: str = ..., onerror: Callable[[str], None] | None = ...
) -> Iterator[pkgutil.ModuleInfo]: ...
