from collections.abc import Callable, Mapping

type ParseResult = (
    int
    | float
    | str
    | bool
    | list[ParseResult]
    | tuple[ParseResult, ...]
)

function_map: dict[str, Callable[..., ParseResult]]

def foo(
    *args: object,
    **kwds: object,
) -> tuple[tuple[object, ...], dict[str, object]]: ...
def token_to_str(token: int) -> str: ...

class Tokenizer:
    def __init__(self, s: str) -> None: ...
    def test(self) -> None: ...
    def reset(self, pos: int = 0) -> None: ...
    def next(self) -> int: ...
    def last(self) -> int: ...
    def peek(self) -> int: ...
    def backtrack(self) -> bool: ...
    def last_token_string(self) -> str: ...

class Parser:
    def __init__(
        self,
        make_int: Callable[[str], ParseResult] = ...,
        make_float: Callable[[str], ParseResult] = ...,
        make_var: Callable[[str], ParseResult] | Mapping[str, ParseResult] = ...,
        make_function: Callable[[str], ParseResult] | Mapping[str, ParseResult] = ...,
        implicit_multiplication: bool = True,
    ) -> None: ...
    def _variable_constructor(self) -> Callable[[str], ParseResult] | LookupNameMaker: ...
    def _callable_constructor(self) -> Callable[[str], ParseResult] | LookupNameMaker: ...
    def parse(self, s: str, accept_eqn: bool = True) -> ParseResult: ...
    def parse_expression(self, s: str) -> ParseResult: ...
    def parse_sequence(self, s: str) -> ParseResult: ...
    def p_matrix(self, tokens: Tokenizer) -> ParseResult: ...
    def p_sequence(self, tokens: Tokenizer) -> ParseResult: ...
    def p_list(self, tokens: Tokenizer) -> ParseResult: ...
    def p_tuple(self, tokens: Tokenizer) -> ParseResult: ...
    def p_eqn(self, tokens: Tokenizer) -> ParseResult: ...
    def p_expr(self, tokens: Tokenizer) -> ParseResult: ...
    def p_term(self, tokens: Tokenizer) -> ParseResult: ...
    def p_factor(self, tokens: Tokenizer) -> ParseResult: ...
    def p_power(self, tokens: Tokenizer) -> ParseResult: ...
    def p_atom(self, tokens: Tokenizer) -> ParseResult: ...
    def p_args(
        self,
        tokens: Tokenizer,
    ) -> tuple[list[ParseResult], dict[str, ParseResult]]: ...
    def p_arg(
        self,
        tokens: Tokenizer,
    ) -> ParseResult | tuple[str, ParseResult]: ...

class LookupNameMaker:
    def __init__(
        self,
        names: Mapping[str, ParseResult],
        fallback: Callable[[str], ParseResult] | None = None,
    ) -> None: ...
    def set_names(self, new_names: Mapping[str, ParseResult]) -> None: ...
    def __call__(self, name: str) -> ParseResult: ...
