already_pickled: dict[int, bool]
already_unpickled: dict[int, object]

def load(*filename: str, compress: bool = True, verbose: bool = True, **kwargs: object) -> object: ...
def _base_save(obj: object, filename: str, compress: bool = True) -> None: ...
def save(obj: object, filename: str, compress: bool = True, **kwargs: object) -> None: ...
def _base_dumps(obj: object, compress: bool = True) -> bytes: ...
def dumps(obj: object, compress: bool = True) -> bytes: ...
def register_unpickle_override(
    module: str,
    name: str,
    callable: object,
    call_name: str | None = None
) -> None: ...
def unpickle_global(module: str, name: str) -> object: ...
def loads(s: bytes, compress: bool = True, **kwargs: object) -> object: ...
def picklejar(obj: object, dir: str | None = None) -> None: ...
def unpickle_all(target: str, debug: bool = False, run_test_suite: bool = False) -> None: ...
def make_None(*args: object, **kwds: object) -> None: ...
def load_sage_object(cls: type, dic: dict[str, object]) -> object: ...
def load_sage_element(cls: type, parent: object, dic_pic: dict[str, object]) -> object: ...
def db(name: str) -> object: ...
def db_save(x: object, name: str | None = None) -> None: ...
