class Profiler:
    def __init__(self, systems: list[object] = ..., verbose: bool = ...) -> None: ...
    def clear(self) -> None: ...
    def __call__(self, message: str | None = ...) -> None: ...
    def print_last(self) -> str: ...
