from typing import Self

def sage_input(x: object, preparse: bool = True, verify: bool = False, allow_locals: bool = False) -> str: ...

class SageInputBuilder:
    def __init__(self) -> None: ...
    def call_method(self, name: str, *args: object, **kwargs: object) -> SageInputExpression: ...

class SageInputExpression: ...

class SIE_literal(SageInputExpression):
    def __init__(self, value: object) -> None: ...

class SIE_literal_stringrep(SIE_literal):
    def __init__(self, value: str, stringrep: str) -> None: ...

class SIE_call(SageInputExpression):
    def __init__(self, function: SageInputExpression, *args: object, **kwargs: object) -> None: ...

class SIE_subscript(SageInputExpression):
    def __init__(self, obj: SageInputExpression, key: SageInputExpression) -> None: ...

class SIE_getattr(SageInputExpression):
    def __init__(self, obj: SageInputExpression, name: str) -> None: ...

class SIE_tuple(SageInputExpression):
    def __init__(self, *args: object) -> None: ...

class SIE_dict(SageInputExpression):
    def __init__(self, **kwargs: object) -> None: ...

class SIE_binary(SageInputExpression):
    def __init__(self, left: SageInputExpression, op: str, right: SageInputExpression) -> None: ...

class SIE_unary(SageInputExpression):
    def __init__(self, op: str, arg: SageInputExpression) -> None: ...

class SIE_gens_constructor(SageInputExpression):
    def __init__(self, parent: SageInputExpression, names: object) -> None: ...

class SIE_gen(SageInputExpression):
    def __init__(self, parent: SageInputExpression, index: int) -> None: ...

class SIE_import_name(SageInputExpression):
    def __init__(self, module: str, name: str) -> None: ...

class SIE_assign(SageInputExpression):
    def __init__(self, name: str, value: SageInputExpression) -> None: ...

class SageInputFormatter:
    def __init__(self, builder: SageInputBuilder | None = None) -> None: ...
    def format(self, x: object) -> SageInputExpression: ...

def verify_same(a: object, b: object) -> None: ...
def verify_si_answer(x: object, answer: str, preparse: bool) -> None: ...

class SageInputAnswer(tuple):
    def __new__(cls, answer: str, preparse: bool) -> Self: ...
