import unittest

class TestSuite:
    def __init__(self, instance: object) -> None: ...
    def run(
        self,
        category: object = ...,
        skip: list[str] = ...,
        catch: bool = ...,
        raise_on_failure: bool = ...,
        **options: object,
    ) -> None: ...

class TestSuiteFailure(AssertionError): ...

def instance_tester(instance: object, tester: object = ..., **options: object) -> InstanceTester: ...

class InstanceTester(unittest.TestCase):
    def __init__(
        self,
        instance: object,
        elements: object = ...,
        verbose: bool = ...,
        prefix: str = ...,
        max_runs: int = ...,
        **options: object,
    ) -> None: ...
    def runTest(self) -> None: ...
    def info(self, message: str, newline: bool = ...) -> None: ...
    def some_elements(self, S: object = ..., repeat: int | None = ...) -> list[object]: ...

class PythonObjectWithTests:
    def __init__(self, instance: object) -> None: ...
    def _test_pickling(self, **options: object) -> None: ...
    def _test_new(self, **options: object) -> None: ...
