class _Transform:
    default_priority: int

    def apply(self) -> None: ...

def process_docstring_aliases(
    self, what: str, name: str, obj: object, options: object, docstringlines: list[str]
) -> None: ...
def process_directives(
    self, what: str, name: str, obj: object, options: object, docstringlines: list[str]
) -> None: ...
def process_docstring_cython(
    self, what: str, name: str, obj: object, options: object, docstringlines: list[str]
) -> None: ...
def process_docstring_module_title(
    self, what: str, name: str, obj: object, options: object, docstringlines: list[str]
) -> None: ...
def process_dollars(
    self, what: str, name: str, obj: object, options: object, docstringlines: list[str]
) -> None: ...
def process_inherited(
    self, what: str, name: str, obj: object, options: object, docstringlines: list[str]
) -> None: ...
def skip_TESTS_block(
    self, what: str, name: str, obj: object, options: object, docstringlines: list[str]
) -> None: ...

class SagemathTransform(_Transform):
    default_priority: int

    def apply(self) -> None: ...

def setup(self) -> None: ...
