def init(state: dict[str, object] | None = ...) -> None: ...
def show_identifiers(hidden: bool = ...) -> list[str]: ...
def save_session(name: str = ..., verbose: bool = ...) -> None: ...
def load_session(name: str = ..., verbose: bool = ...) -> None: ...
