from sage.structure.sage_object import SageObject

class table(SageObject):
    def __init__(
        self,
        rows: list[object] | None = ...,
        columns: list[object] | None = ...,
        header_row: bool | list[object] = ...,
        header_column: bool | list[object] = ...,
        frame: bool = ...,
        align: str = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def options(self, **kwds: object) -> dict[str, object]: ...
    def transpose(self) -> table: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _html_(self) -> str: ...
