LEVEL: int
verbose_files: list[str]

def verbose(
    self="", t: int = 0, level: int = 1, caller_name: str | None = None
) -> float: ...
def set_verbose(self, files: str | list[str] = "all") -> None: ...
def set_verbose_files(self) -> None: ...
def get_verbose_files(self) -> list[str]: ...
def unset_verbose_files(self) -> None: ...
def get_verbose(self) -> int: ...
