from sage.structure.sage_object import SageObject

def default_viewer(self=...) -> str: ...

class Viewer(SageObject):
    def browser(self, app: str | None = ...) -> str | None: ...
    def dvi_viewer(self, app: str | None = ...) -> str | None: ...
    def pdf_viewer(self, app: str | None = ...) -> str | None: ...
    def png_viewer(self, app: str | None = ...) -> str | None: ...
    def __call__(self, x: str | None = ...) -> str | None: ...

viewer: Viewer

def browser(self) -> str: ...
def dvi_viewer(self) -> str: ...
def pdf_viewer(self) -> str: ...
def png_viewer(self) -> str: ...
