from collections.abc import ItemsView, Iterator, KeysView, ValuesView
from typing import TypeVar

_K = TypeVar("_K")
_V = TypeVar("_V")

class WeakValueDictEraser:
    def __init__(self, D: WeakValueDictionary[_K, _V]) -> None: ...
    def __call__(self, r: object) -> None: ...

class WeakValueDictionary(dict[_K, _V]):
    def __cinit__(self) -> None: ...
    def __init__(self, data: object = ()) -> None: ...
    def __copy__(self) -> WeakValueDictionary[_K, _V]: ...
    def __deepcopy__(self, memo: dict[int, object]) -> WeakValueDictionary[_K, _V]: ...
    def setdefault(self, k: _K, default: _V | None = None) -> _V: ...
    def __setitem__(self, k: _K, v: _V) -> None: ...
    def pop(self, k: _K) -> _V: ...
    def popitem(self) -> tuple[_K, _V]: ...
    def get(self, k: _K, d: _V | None = None) -> _V: ...
    def __getitem__(self, k: _K) -> _V: ...
    def __contains__(self, k: _K) -> bool: ...
    def __iter__(self) -> Iterator[_K]: ...
    def keys(self) -> KeysView[_K]: ...
    def values(self) -> ValuesView[_V]: ...
    def values_list(self) -> list[_V]: ...
    def items(self) -> ItemsView[tuple[_K, _V]]: ...
    def items_list(self) -> list[tuple[_K, _V]]: ...

class CachedWeakValueDictionary(WeakValueDictionary[_K, _V]):
    def __cinit__(self) -> None: ...
    def __init__(self, data: object = (), cache: int = 16) -> None: ...
