from .number_field_base import NumberField
from .number_field_ideal import NumberFieldIdeal

class ClassGroup:
    def gens_ideals(self) -> list[NumberFieldIdeal]: ...
    def number_field(self) -> NumberField: ...
