from sage.rings.integer import Integer
from sage.rings.number_field.number_field import NumberField_generic

class GaloisGroupElement: ...

class GaloisGroup_v2:
    def order(self, algorithm: str | None = ..., recompute: bool = ...) -> Integer: ...
    def gens(self) -> tuple[GaloisGroupElement, ...]: ...
    def fixed_field(self, name: str | None = ..., polred: bool | None = ..., threshold: int | None = ...) -> NumberField_generic: ...
