from collections.abc import Callable, Sequence
from typing import Self

from sage.calculus.predefined import K, k
from sage.categories.map import Map
from sage.categories.morphism import Morphism
from sage.data_structures.blas_dict import sum
from sage.databases.sql_db import p
from sage.env import join
from sage.groups.generic import discrete_log
from sage.groups.group import AbelianGroup
from sage.libs.ntl.ntl_ZZX import ZZ
from sage.matrix.matrix0 import Matrix
from sage.misc.functional import gens, multiplicative_order, quotient
from sage.misc.misc_c import prod
from sage.misc.mrange import xmrange_iter
from sage.modules.free_module import FreeModule_generic
from sage.rings.finite_rings.finite_field_base import FiniteField
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.ideal import FunctionFieldIdeal
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.ideal import Ideal_fractional, Ideal_generic
from sage.rings.infinity import MinusInfinity, PlusInfinity
from sage.rings.integer import Integer
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.number_field.number_field_element import NumberFieldElement
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.ring import Field, Ring
from sage.schemes.elliptic_curves.sha_tate import valuation
from sage.sets.family import Family
from sage.structure.element import (
    Element,
    ModuleElement,
    MultiplicativeGroupElement,
    Vector,
)
from sage.structure.factorization import Factorization
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.richcmp import richcmp

class NumberFieldIdeal(Ideal_generic):
    def norm(self) -> Integer: ...
    def absolute_norm(self) -> Integer: ...
    def is_prime(self) -> bool: ...
    def is_principal(self, proof: bool | None = ...) -> bool: ...
    def gens(self) -> tuple[NumberFieldElement, ...]: ...
    def ramification_index(self) -> int: ...
    def residue_field(self, names: str | None = ...) -> FiniteField: ...
    def residue_class_degree(self) -> int: ...
    def __init__(
        self,
        field: NumberField_generic,
        gens: Sequence[ElementConstructorInput],
        coerce: ElementConstructorInput = ...,
    ) -> None: ...
    def __hash__(self) -> Self: ...
    def _latex_(self) -> str: ...
    def _richcmp_(
        self,
        other: NumberFieldElement | ElementConstructorInput,
        op: ElementConstructorInput,
    ) -> richcmp | NumberFieldElement: ...
    def coordinates(self, x: NumberFieldElement | ElementConstructorInput) -> Self: ...
    def _repr_(self) -> str: ...
    def __pari__(self) -> Self: ...
    def pari_hnf(self) -> Self: ...
    def basis(self) -> Family[Element]: ...
    def free_module(
        self,
    ) -> FreeModule_generic | tuple[FreeModule_generic, Morphism, Morphism]: ...
    def reduce_equiv(self) -> NumberFieldIdeal | FunctionFieldIdeal: ...
    def gens_reduced(self, proof: bool | None = ...) -> gens: ...
    def gens_two(self) -> tuple: ...
    def integral_basis(self) -> Self: ...
    def integral_split(self) -> tuple[Self | prod, prod]: ...
    def intersection(
        self, other: NumberFieldElement | ElementConstructorInput
    ) -> NumberFieldIdeal | FunctionFieldIdeal: ...
    def is_integral(self) -> bool: ...
    def is_maximal(self) -> bool: ...
    def pari_prime(self) -> Vector: ...
    def ideal_class_log(self, proof: bool | None = ...) -> NumberFieldElement: ...
    def S_ideal_class_log(self, S: Ring | Parent) -> list[Self]: ...
    def is_zero(self) -> bool: ...
    def relative_norm(self) -> NumberFieldElement: ...
    def absolute_ramification_index(self) -> Integer: ...
    def relative_ramification_index(self) -> Integer: ...
    def number_field(self) -> NumberField_generic: ...
    def smallest_integer(self) -> ZZ: ...
    def valuation(
        self, p: int | Integer | FunctionFieldPlace | NumberFieldIdeal
    ) -> Integer | Rational | PlusInfinity | MinusInfinity: ...
    def decomposition_group(self) -> Self: ...
    def ramification_group(self, v: ElementConstructorInput) -> Self: ...
    def inertia_group(self) -> Self: ...
    def random_element(
        self, *args: ElementConstructorInput, **kwds: ElementConstructorInput
    ) -> Self: ...
    def artin_symbol(self) -> Self: ...
    def residue_symbol(
        self, e: int | Integer | Rational, m: int | Integer, check: bool = ...
    ) -> Self | multiplicative_order | int | Integer | discrete_log: ...
    def _magma_init_(self, magma: ElementConstructorInput) -> join: ...
    def _pari_init_(self) -> str: ...

class NumberFieldFractionalIdeal(
    MultiplicativeGroupElement, Ideal_fractional, NumberFieldIdeal
):

    def __init__(
        self,
        field: NumberField_generic,
        gens: Sequence[ElementConstructorInput],
        coerce: ElementConstructorInput = ...,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def divides(self, other: NumberFieldElement | ElementConstructorInput) -> bool: ...
    def factor(self) -> Factorization: ...
    def prime_factors(self) -> list[NumberFieldIdeal]: ...
    def __invert__(self) -> NumberFieldIdeal | FunctionFieldIdeal: ...
    def is_maximal(self) -> bool: ...
    def is_trivial(self, proof: bool | None = ...) -> bool: ...
    def ramification_index(self) -> Integer: ...
    def reduce(
        self, f: Polynomial | MPolynomial | Map | Callable[..., Element]
    ) -> sum: ...
    def residues(self) -> xmrange_iter: ...
    def invertible_residues(self, reduce: bool = ...) -> Self: ...
    def invertible_residues_mod(
        self, subgp_gens: int | Integer = ..., reduce: bool = ...
    ) -> xmrange_iter: ...
    def denominator(self) -> Integer: ...
    def numerator(self) -> Integer | NumberFieldElement: ...
    def is_coprime(
        self, other: NumberFieldElement | ElementConstructorInput
    ) -> bool: ...
    def idealcoprime(self, J: int | Integer) -> k: ...
    def small_residue(
        self, f: Polynomial | MPolynomial | Map | Callable[..., Element]
    ) -> k: ...
    def idealstar(self, flag: int | Integer = ...) -> AbelianGroup: ...
    def ideallog(
        self,
        x: NumberFieldElement | ElementConstructorInput,
        gens: Sequence[ElementConstructorInput] | None = ...,
        check: bool = ...,
    ) -> list[Element] | list[ZZ]: ...
    def element_1_mod(
        self, other: NumberFieldElement | ElementConstructorInput
    ) -> K: ...
    def euler_phi(self) -> prod: ...
    def prime_to_S_part(self, S: Ring | Parent) -> Self | p | valuation: ...
    def is_S_unit(self, S: Ring | Parent) -> bool: ...
    def is_S_integral(self, S: Ring | Parent) -> bool: ...
    def prime_to_idealM_part(
        self, M: Matrix | ModuleElement | int | Integer
    ) -> Self | NumberFieldIdeal | FunctionFieldIdeal: ...
    def residue_field(
        self, names: str | tuple[str, ...] | None = ...
    ) -> Field | tuple[Field, Morphism, Morphism]: ...
    def residue_class_degree(self) -> Integer: ...
    def ray_class_number(self) -> ZZ: ...

def basis_to_module(
    B: NumberFieldElement | ElementConstructorInput,
    K: NumberField_generic | FunctionField | Field,
) -> NumberFieldElement: ...

class QuotientMap(Morphism):
    def __init__(
        self,
        K: NumberField_generic | FunctionField | Field,
        M_OK_change: ElementConstructorInput,
        Q: Polynomial | MPolynomial,
        I: NumberFieldIdeal | FunctionFieldIdeal,
    ) -> None: ...
    def __call__(
        self, x: NumberFieldElement | ElementConstructorInput
    ) -> NumberFieldElement: ...

class LiftMap(Morphism):
    def __init__(
        self,
        OK: ElementConstructorInput,
        M_OK_map: ElementConstructorInput,
        Q: ElementConstructorInput,
        I: NumberFieldIdeal | FunctionFieldIdeal,
    ) -> None: ...
    def __call__(
        self, x: NumberFieldElement | ElementConstructorInput
    ) -> NumberFieldElement: ...

def quotient_char_p(
    I: NumberFieldIdeal | FunctionFieldIdeal,
    p: int | Integer | FunctionFieldPlace | NumberFieldIdeal,
) -> tuple[quotient, QuotientMap, LiftMap]: ...
