from typing import TYPE_CHECKING, overload, Literal
from sage.rings.integer import Integer
from sage.rings.rational import Rational

from sage.rings.number_field.number_field_element import NumberFieldElement_absolute
from sage.rings.number_field.number_field import NumberField
class NumberFieldElement_quadratic(NumberFieldElement_absolute):
    

    def __init__(self, parent: NumberField, f) -> None: ...

    def parts(self) -> tuple[Rational, Rational]: ...

    def sign(self) -> int: ...

    def continued_fraction_list(self) -> tuple[tuple[int, ...], tuple[int, ...]]: ...

    def continued_fraction(self): ...

    def _add_(self, other): ...

    def _sub_(self, other): ...

    def __neg__(self): ...

    def _mul_(self, other): ...

    def _real_mpfi_(self, R): ...

    def _complex_mpfi_(self, R): ...

    def _arb_(self, R): ...

    def _acb_(self, R): ...

    def _maxima_init_(self, I=None) -> str: ...

    def _fricas_init_(self) -> str: ...

    def _sympy_(self): ...

    def _polymake_init_(self) -> str: ...

    def _copy_for_parent(self, parent: NumberField): ...

    def __copy__(self): ...

    def __deepcopy__(self, memo): ...

    def __reduce__(self): ...

class NumberFieldElement_quadratic_sqrt(NumberFieldElement_quadratic):
    ...

class OrderElement_quadratic(NumberFieldElement_quadratic):
    ...
