# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class NumberFieldEmbedding:
    def __init__(self, K: builtins.object, R: builtins.object, gen_embedding: builtins.object) -> None: ...
    def gen_image(self) -> _SageObject: ...

class EmbeddedNumberFieldMorphism:
    def __init__(self, K: builtins.object, L: builtins.object, ambient_field: builtins.object = ...) -> None: ...
    def section(self) -> _SageObject: ...

class EmbeddedNumberFieldConversion:
    def __init__(self, K: builtins.object, L: builtins.object, ambient_field: builtins.object = ...) -> None: ...

def matching_root(poly: builtins.object, target: builtins.object, ambient_field: builtins.object = ..., margin: builtins.object = ..., max_prec: builtins.object = ...) -> _SageObject: ...

def closest(target: builtins.object, values: builtins.object, margin: builtins.object = ...) -> _SageObject: ...

def root_from_approx(f: builtins.object, a: builtins.object) -> _SageObject: ...

def create_embedding_from_approx(K: builtins.object, gen_image: builtins.object) -> _SageObject: ...

class CyclotomicFieldEmbedding:
    def __init__(self, K: builtins.object, L: builtins.object) -> None: ...
    def section(self) -> _SageObject: ...

class CyclotomicFieldConversion:
    def __init__(self, K: builtins.object, L: builtins.object) -> None: ...
