
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.number_field.unit_group import UnitGroup
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.number_field.order import Order as NumberFieldOrder

from typing import overload

from sage.rings.abc import Field, Order as AbstractOrder
from sage.rings.morphism import RingHomomorphism
from sage.rings.number_field.class_group import ClassGroup
from sage.rings.number_field.galois_group import GaloisGroup_v2
from sage.rings.number_field.number_field_base import NumberField
from sage.rings.number_field.number_field_element import NumberFieldElement
from sage.rings.number_field.order import Order
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational_field import RationalField

class NumberField_generic(NumberField):
    def construction(self) -> tuple[type, tuple[Polynomial]]: ...
    def structure(self) -> tuple[Polynomial, RingHomomorphism, RingHomomorphism]: ...
    def completion(self, p: Integer | tuple[Integer, ...], prec: int, extras: dict[str, str] = ...) -> Field: ...
    def primitive_element(self) -> NumberFieldElement: ...
    def random_element(self, num_bound: int | None = ..., den_bound: int | None = ..., integral_coefficients: bool = ..., distribution: str | None = ...) -> NumberFieldElement: ...
    def subfield(self, alpha: NumberFieldElement, name: str | None = ..., names: str | tuple[str, ...] | None = ...) -> tuple[NumberField_generic, RingHomomorphism]: ...
    def change_generator(self, alpha: NumberFieldElement, name: str | None = ..., names: str | tuple[str, ...] | None = ...) -> NumberField_generic: ...
    def subfield_from_elements(self, alpha: list[NumberFieldElement], name: str | None = ..., polred: bool = ..., threshold: float | None = ...) -> tuple[NumberField_generic, RingHomomorphism]: ...
    def is_absolute(self) -> bool: ...
    def gen(self, n: int = ...) -> NumberFieldElement: ...
    def signature(self) -> tuple[int, int]: ...
    def is_relative(self) -> bool: ...
    def quadratic_defect(self, a: NumberFieldElement, p: Integer, check: bool = ...) -> Integer | None: ...
    def absolute_field(self, names: str | tuple[str, ...]) -> tuple[NumberField_generic, RingHomomorphism, RingHomomorphism]: ...
    def is_isomorphic(self, other: NumberField_generic, isomorphism_maps: bool = ...) -> bool | tuple[bool, RingHomomorphism]: ...
    def is_totally_real(self) -> bool: ...
    def is_totally_imaginary(self) -> bool: ...
    def is_CM(self) -> bool: ...
    def complex_conjugation(self) -> RingHomomorphism: ...
    def maximal_totally_real_subfield(self) -> tuple[NumberField_generic, RingHomomorphism]: ...
    def complex_embeddings(self, prec: int = ...) -> list[RingHomomorphism]: ...
    def real_embeddings(self, prec: int = ...) -> list[RingHomomorphism]: ...
    def specified_complex_embedding(self) -> RingHomomorphism | None: ...
    def gen_embedding(self) -> RingHomomorphism | None: ...
    def algebraic_closure(self) -> Field: ...
    def conductor(self, check_abelian: bool = ...) -> Integer: ...
    def dirichlet_group(self) -> list[NumberFieldElement]: ...
    def ideal(self, *gens: object, **kwds: object) -> NumberFieldIdeal: ...
    def idealchinese(self, ideals: list[AbstractOrder], residues: list[NumberFieldElement]) -> NumberFieldElement: ...
    def fractional_ideal(self, *gens: NumberFieldElement, **kwds: str) -> AbstractOrder: ...
    def ideals_of_bdd_norm(self, bound: Integer | int) -> list[AbstractOrder]: ...
    def primes_above(self, x: Integer | int, degree: int | None = ...) -> list[AbstractOrder]: ...
    def prime_above(self, x: Integer | int, degree: int | None = ...) -> AbstractOrder: ...
    def primes_of_bounded_norm(self, B: Integer | int) -> list[AbstractOrder]: ...
    def primes_of_bounded_norm_iter(self, B: Integer | int) -> AbstractOrder: ...
    def primes_of_degree_one_iter(self, num_integer_primes: int = ..., max_iterations: int = ...) -> AbstractOrder: ...
    def primes_of_degree_one_list(self, n: int, num_integer_primes: int = ..., max_iterations: int = ...) -> list[AbstractOrder]: ...
    def completely_split_primes(self, B: Integer | int = ...) -> list[AbstractOrder]: ...
    def pari_polynomial(self, name: str = ...) -> str: ...
    def pari_nf(self, important: bool = ...) -> str: ...
    def pari_zk(self) -> str: ...
    def pari_bnf(self, proof: bool | None = ..., units: bool = ...) -> str: ...
    def pari_rnfnorm_data(self, L: NumberField_generic, proof: bool = ...) -> str: ...
    def characteristic(self) -> int: ...
    def class_group(self, proof: bool | None = ..., names: str = ...) -> ClassGroup: ...
    def class_number(self, proof: bool = ...) -> Integer: ...
    def S_class_group(self, S: list[AbstractOrder], proof: bool | None = ..., names: str = ...) -> ClassGroup: ...
    def S_units(self, S: list[AbstractOrder], proof: bool = ...) -> list[NumberFieldElement]: ...
    def selmer_generators(self, S: tuple[AbstractOrder, ...], m: int, proof: bool = ..., orders: bool = ...) -> list[NumberFieldElement]: ...
    def selmer_group_iterator(self, S: tuple[AbstractOrder, ...], m: int, proof: bool = ...) -> NumberFieldElement: ...
    def selmer_space(self, S: tuple[AbstractOrder, ...], p: int, proof: bool | None = ...) -> list[NumberFieldElement]: ...
    def composite_fields(self, other: NumberField_generic, names: str | tuple[str, ...] | None = ..., both_maps: bool = ..., preserve_embedding: bool = ...) -> list[NumberField_generic]: ...
    def absolute_degree(self) -> int: ...
    def absolute_discriminant(self) -> Integer: ...
    def degree(self) -> int: ...
    def different(self) -> AbstractOrder: ...
    def discriminant(self, v: object = ...) -> Integer: ...
    def disc(self, v: Integer | int | None = ...) -> Integer: ...
    def trace_dual_basis(self, b: list[NumberFieldElement]) -> list[NumberFieldElement]: ...
    def elements_of_norm(self, n: Integer | int, proof: bool | None = ...) -> list[NumberFieldElement]: ...
    def extension(self, poly: Polynomial | NumberFieldElement, name: str | None = ..., names: str | tuple[str, ...] | None = ..., latex_name: str | None = ..., latex_names: str | tuple[str, ...] | None = ..., *args: str, **kwds: str) -> NumberField_generic: ...
    def factor(self, n: Integer | int) -> list[tuple[AbstractOrder, int]]: ...
    def prime_factors(self, x: Integer | int) -> list[AbstractOrder]: ...
    def decomposition_type(self, p: Integer | int) -> list[tuple[int, int]]: ...
    def is_field(self, proof: bool = ...) -> bool: ...
    def is_galois(self) -> bool: ...
    def is_abelian(self) -> bool: ...
    def galois_group(self, algorithm: str = ..., names: str = ..., gc_numbering: bool = ...) -> GaloisGroup_v2: ...
    def power_basis(self) -> list[NumberFieldElement]: ...
    def integral_basis(self, v: list[Integer | int] | None = ...) -> list[NumberFieldElement]: ...
    def reduced_basis(self, prec: int | None = ...) -> list[NumberFieldElement]: ...
    def reduced_gram_matrix(self, prec: int | None = ...) -> list[list[float]]: ...
    def narrow_class_group(self, proof: bool | None = ...) -> ClassGroup: ...
    def ngens(self) -> int: ...
    def order(self) -> Order: ...
    def absolute_polynomial_ntl(self) -> Polynomial: ...
    def polynomial_ntl(self) -> Polynomial: ...
    def polynomial(self) -> Polynomial: ...
    def defining_polynomial(self) -> Polynomial: ...
    def polynomial_ring(self) -> Field: ...
    def polynomial_quotient_ring(self) -> Field: ...
    def regulator(self, proof: bool | None = ...) -> float: ...
    def residue_field(self, prime: AbstractOrder, names: str | None = ..., check: bool = ...) -> Field: ...
    def trace_pairing(self, v: list[NumberFieldElement]) -> list[list[NumberFieldElement]]: ...
    def uniformizer(self, P: AbstractOrder, others: str = ...) -> NumberFieldElement: ...
    def units(self, proof: bool | None = ...) -> list[NumberFieldElement]: ...
    def unit_group(self, proof: bool = ...) -> UnitGroup: ...
    def S_unit_group(self, proof: bool | None = ..., S: list[AbstractOrder] | None = ...) -> ClassGroup: ...
    def S_unit_solutions(self, S: list[AbstractOrder] = ..., prec: int = ..., include_exponents: bool = ..., include_bound: bool = ..., proof: bool | None = ...) -> list[tuple[NumberFieldElement, NumberFieldElement]]: ...
    def zeta(self, n: int = ..., all: bool = ...) -> NumberFieldElement | list[NumberFieldElement]: ...
    def zeta_order(self) -> int: ...
    def primitive_root_of_unity(self) -> NumberFieldElement: ...
    def roots_of_unity(self) -> list[NumberFieldElement]: ...
    def zeta_coefficients(self, n: int) -> list[Integer]: ...
    def solve_CRT(self, reslist: list[NumberFieldElement], Ilist: list[AbstractOrder], check: bool = ...) -> NumberFieldElement: ...
    def valuation(self, prime: AbstractOrder) -> int: ...
    def some_elements(self) -> list[NumberFieldElement]: ...
    def lmfdb_page(self) -> str: ...
    def maximal_order(self, v: Integer | int | list[Integer | int] | None = ..., assume_maximal: bool | str | None = ...) -> Order: ...
    def embeddings(self, K: Field) -> list[RingHomomorphism]: ...
    def minkowski_bound(self) -> Rational: ...
    def gens(self) -> tuple[NumberFieldElement, ...]: ...
    def base_ring(self) -> RationalField | Field: ...
    def ring_of_integers(self, *args: object, **kwds: object) -> NumberFieldOrder: ...
