from typing import TYPE_CHECKING
from sage.rings.number_field.number_field import NumberField_generic

if TYPE_CHECKING:
    from sage.rings.number_field.number_field_base import NumberField
    from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
    from sage.rings.polynomial.polynomial_element import Polynomial
    from sage.structure.sequence import Sequence

class NumberField_relative(NumberField_generic):
    def __init__(
        self,
        base: NumberField,
        polynomial: Polynomial,
        name: str,
        latex_name: str | None = ...,
        names: tuple[str, ...] | None = ...,
        check: bool = ...,
        embedding=None,
        structure=None,
    ) -> None: ...
    def change_names(self, names: tuple[str, ...] | str) -> NumberField_relative: ...
    def subfields(self, degree: int = ..., name: str | None = ...) -> Sequence: ...
    def is_absolute(self) -> bool: ...
    def gens(self) -> tuple: ...
    def _first_ngens(self, n: int) -> tuple: ...
    def ngens(self) -> int: ...
    def gen(self, n: int = ...) -> NumberField_generic: ...
    def galois_closure(self, names: str | None = ...) -> NumberField_generic: ...
    def composite_fields(
        self,
        other: NumberField_generic,
        names: str | None = ...,
        both_maps: bool = ...,
        preserve_embedding: bool = ...,
    ) -> list: ...
    def absolute_degree(self) -> int: ...
    def relative_degree(self) -> int: ...
    def degree(self) -> int: ...
    def _maximal_order(self, v: tuple = ..., assume_maximal: str = ...): ...
    def _repr_(self) -> str: ...
    def _Hom_(self, codomain: NumberField_generic, category=None): ...
    def _latex_(self) -> str: ...
    def _coerce_from_other_number_field(self, x): ...
    def _convert_non_number_field_element(self, x): ...
    def _coerce_map_from_(self, R): ...
    def _element_constructor_(self, x, check: bool = ...): ...
    def _fractional_ideal_class_(self): ...
    def is_galois(self) -> bool: ...
    def is_galois_relative(self) -> bool: ...
    def is_galois_absolute(self) -> bool: ...
    def is_isomorphic_relative(self, other: NumberField_relative, base_isom=None) -> bool: ...
    def is_CM_extension(self) -> bool: ...
    def free_module(self, base=None, basis=None, map: bool = ...): ...
    def relative_vector_space(self, base=None, *args, **kwds): ...
    def absolute_vector_space(self, base=None, *args, **kwds): ...
    def vector_space(self, *args, **kwds): ...
    def absolute_base_field(self) -> tuple: ...
    def _pari_rnfeq(self): ...
    def _pari_nfzk(self): ...
    def _pari_relative_structure(self) -> tuple: ...
    def _gen_relative(self) -> NumberField_generic: ...
    def pari_rnf(self): ...
