from collections.abc import Callable, Sequence
from typing import Self

from sage.categories.map import Map
from sage.categories.morphism import Morphism
from sage.libs.pari.gen import gen
from sage.matrix.matrix0 import Matrix
from sage.rings.complex_mpfr import ComplexNumber
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.ideal import FunctionFieldIdeal
from sage.rings.function_field.order import FunctionFieldOrder
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.infinity import MinusInfinity, PlusInfinity
from sage.rings.integer import Integer
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.number_field.number_field_element_base import NumberFieldElement_base
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.number_field.order import Order as NumberFieldOrder
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_mpfr import RealNumber
from sage.rings.ring import Field, Ring
from sage.rings.valuation.valuation import DiscretePseudoValuation
from sage.structure.element import Element, RingElement, Vector
from sage.structure.factorization import Factorization
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject

class NumberFieldElement(NumberFieldElement_base):
    def __bool__(self) -> bool: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: ElementConstructorInput) -> Self: ...
    def __getitem__(self, n: int | Integer) -> NumberFieldElement: ...
    def __hash__(self) -> int: ...
    def __init__(
        self, parent: Parent, f: Polynomial | MPolynomial | Map | Callable[..., Element]
    ) -> None: ...
    def __invert__(self) -> Self: ...
    def __pow__(
        self,
        exp: ElementConstructorInput,
        dummy: ElementConstructorInput,
    ) -> Self: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def abs(
        self, prec: int | Integer | None = ..., i: int | Integer | None = ...
    ) -> Self: ...
    def abs_non_arch(
        self,
        P: NumberFieldIdeal | FunctionFieldPlace | Polynomial | DiscretePseudoValuation,
        prec: int | Integer | None = ...,
    ) -> Self: ...
    def absolute_different(self) -> NumberFieldElement: ...
    def absolute_norm(self) -> Rational | Integer: ...
    def additive_order(self) -> Integer | PlusInfinity: ...
    def ceil(self) -> Integer: ...
    def charpoly(self, var: str = ...) -> Polynomial: ...
    def complex_embedding(
        self, prec: int | Integer | None = ..., i: int | Integer = ...
    ) -> ComplexNumber: ...
    def complex_embeddings(
        self, prec: int | Integer | None = ...
    ) -> list[ComplexNumber]: ...
    def conjugate(self) -> Self: ...
    def coordinates_in_terms_of_powers(self) -> Vector: ...
    def denominator(self) -> Integer: ...
    def denominator_ideal(self) -> NumberFieldIdeal: ...
    def descend_mod_power(
        self,
        K: NumberField_generic | FunctionField | Field = ...,
        d: ElementConstructorInput = ...,
    ) -> Self: ...
    def different(
        self, K: NumberField_generic | FunctionField | Field | None = ...
    ) -> NumberFieldElement: ...
    def factor(self) -> Factorization: ...
    def floor(self) -> Integer: ...
    def galois_conjugates(
        self, K: NumberField_generic | FunctionField | Field
    ) -> list[NumberFieldElement]: ...
    def gcd(self, other: NumberFieldElement | ElementConstructorInput) -> Self: ...
    def global_height(self, prec: int | Integer | None = ...) -> RealNumber: ...
    def global_height_arch(self, prec: int | Integer | None = ...) -> RealNumber: ...
    def global_height_non_arch(
        self, prec: int | Integer | None = ...
    ) -> RealNumber | Rational: ...
    def inverse_mod(self, I: NumberFieldIdeal | FunctionFieldIdeal) -> Self: ...
    def is_integer(self) -> bool: ...
    def is_integral(self) -> bool: ...
    def is_norm(
        self,
        L: NumberField_generic | FunctionField | Field,
        element: bool = ...,
        proof: bool = ...,
    ) -> bool: ...
    def is_nth_power(self, n: int | Integer) -> bool: ...
    def is_padic_square(
        self,
        P: NumberFieldIdeal | FunctionFieldPlace | Polynomial | DiscretePseudoValuation,
        check: bool = ...,
    ) -> bool: ...
    def is_prime(self) -> bool: ...
    def is_square(self, root: bool = ...) -> bool | tuple[bool, Self]: ...
    def is_totally_positive(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def list(self) -> list[Self]: ...
    def local_height(
        self,
        P: NumberFieldIdeal | FunctionFieldPlace | Polynomial | DiscretePseudoValuation,
        prec: int | Integer | None = ...,
        weighted: ElementConstructorInput = ...,
    ) -> RealNumber | Rational: ...
    def local_height_arch(
        self,
        i: int | Integer,
        prec: int | Integer | None = ...,
        weighted: ElementConstructorInput = ...,
    ) -> RealNumber: ...
    def matrix(self, base: ElementConstructorInput | None = ...) -> Matrix: ...
    def minpoly(self, var: str = ...) -> Polynomial: ...
    def multiplicative_order(self) -> Integer | PlusInfinity: ...
    def norm(
        self, K: NumberField_generic | FunctionField | Field | None = ...
    ) -> NumberFieldElement | Rational: ...
    def nth_root(self, n: int | Integer, all: bool = ...) -> Self | list[Self]: ...
    def numerator_ideal(self) -> NumberFieldIdeal: ...
    def polynomial(self, var: str = ...) -> Polynomial: ...
    def relative_norm(self) -> NumberFieldElement: ...
    def residue_symbol(
        self,
        P: NumberFieldIdeal | FunctionFieldPlace | Polynomial | DiscretePseudoValuation,
        m: int | Integer,
        check: bool = ...,
    ) -> Integer: ...
    def round(self) -> Integer: ...
    def sign(self) -> int: ...
    def sqrt(
        self, all: bool = ..., extend: bool = ...
    ) -> Self | list[Self] | Element: ...
    def support(self) -> list[Element]: ...
    def trace(
        self, K: NumberField_generic | FunctionField | Field | None = ...
    ) -> NumberFieldElement | Rational: ...
    def valuation(
        self,
        P: NumberFieldIdeal | FunctionFieldPlace | Polynomial | DiscretePseudoValuation,
    ) -> Integer | Rational | PlusInfinity | MinusInfinity: ...
    def vector(self) -> Vector: ...
    def __abs__(self) -> RealNumber: ...
    def __complex__(self) -> complex: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __pari__(self, name: str | None = ...) -> gen: ...
    def _acb_(self, R: Ring) -> Self: ...
    def _add_(self, right: NumberFieldElement | ElementConstructorInput) -> Self: ...
    def _algebraic_(self, parent: Parent) -> Element: ...
    def _coefficients(self) -> tuple[RingElement, ...]: ...
    def _complex_double_(self, CDF: ElementConstructorInput) -> Self: ...
    def _copy_for_parent(self, parent: Parent) -> Self: ...
    def _div_(self, other: NumberFieldElement | ElementConstructorInput) -> Self: ...
    def _gap_init_(self) -> str: ...
    def _im_gens_(
        self,
        codomain: Parent,
        im_gens: Sequence[ElementConstructorInput],
        base_map: Map | Morphism | None = ...,
    ) -> Self: ...
    def _integer_(
        self, Z: NumberFieldElement | ElementConstructorInput | None = ...
    ) -> Integer | None: ...
    def _libgap_(self) -> Self: ...
    def _lift_cyclotomic_element(
        self, new_parent: ElementConstructorInput, check: bool = ..., rel: int = ...
    ) -> Self: ...
    def _matrix_over_base(
        self, L: NumberField_generic | FunctionField | Field
    ) -> Matrix: ...
    def _matrix_over_base_morphism(self, phi: Map | Morphism) -> Morphism: ...
    def _mpfr_(self, R: Ring) -> Self: ...
    def _mul_(self, right: NumberFieldElement | ElementConstructorInput) -> Self: ...
    def _neg_(self) -> Self: ...
    def _number_field(self) -> NumberField_generic: ...
    def _pari_init_(self, name: str | None = ...) -> str: ...
    def _pari_polynomial(self, name: str | None = ...) -> gen: ...
    def _random_element(
        self,
        num_bound: ElementConstructorInput | None = ...,
        den_bound: ElementConstructorInput | None = ...,
        distribution: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def _rational_(self) -> Rational: ...
    def _richcmp_(
        self,
        right: NumberFieldElement | ElementConstructorInput,
        op: int,
    ) -> bool: ...
    def _rnfisnorm(
        self,
        L: NumberField_generic | FunctionField | Field,
        proof: bool = ...,
        extra_primes: ElementConstructorInput = ...,
    ) -> tuple[bool, NumberFieldElement]: ...
    def _set_multiplicative_order(self, n: int | Integer) -> None: ...
    def _sub_(self, right: NumberFieldElement | ElementConstructorInput) -> Self: ...
    def _symbolic_(self, SR: ElementConstructorInput) -> Element: ...

class NumberFieldElement_absolute(NumberFieldElement):
    def absolute_charpoly(self, var: str = ...) -> Polynomial: ...
    def absolute_minpoly(self, var: str = ...) -> Polynomial: ...
    def charpoly(self, var: str = ...) -> Polynomial: ...
    def minpoly(self, var: str = ...) -> Polynomial: ...
    def list(self) -> list[Rational]: ...
    def lift(self) -> Polynomial: ...
    def is_real_positive(self) -> bool: ...
    def _magma_init_(self, magma: ElementConstructorInput) -> str: ...

class CoordinateFunction(SageObject):
    def __call__(
        self, x: NumberFieldElement | ElementConstructorInput
    ) -> NumberFieldElement: ...
    def __eq__(self, other: object) -> bool: ...
    def __init__(
        self,
        alpha: NumberFieldElement,
        W: ElementConstructorInput,
        to_V: ElementConstructorInput,
    ) -> None: ...
    def __ne__(self, other: object) -> bool: ...
    def alpha(self) -> NumberFieldElement: ...

class NumberFieldElement_relative(NumberFieldElement):
    def __getitem__(self, n: int | Integer) -> NumberFieldElement: ...
    def __init__(
        self, parent: Parent, f: Polynomial | MPolynomial | Map | Callable[..., Element]
    ) -> None: ...
    def _latex_(self) -> str: ...
    def _magma_init_(self, magma: ElementConstructorInput) -> str: ...
    def _repr_(self) -> str: ...
    def absolute_charpoly(
        self, var: str = ..., algorithm: str | None = ...
    ) -> Self: ...
    def absolute_minpoly(self, var: str = ..., algorithm: str | None = ...) -> Self: ...
    def charpoly(self, var: str = ...) -> Polynomial: ...
    def lift(self, var: str = ...) -> NumberFieldElement: ...
    def list(self) -> list[Self]: ...
    def valuation(
        self,
        P: NumberFieldIdeal | FunctionFieldPlace | Polynomial | DiscretePseudoValuation,
    ) -> Integer | Rational | PlusInfinity | MinusInfinity: ...

class OrderElement_absolute(NumberFieldElement_absolute):
    def __init__(
        self,
        order: NumberFieldOrder | FunctionFieldOrder,
        f: Polynomial | MPolynomial | Map | Callable[..., Element],
    ) -> None: ...
    def __invert__(self) -> Self: ...
    def canonical_associate(self) -> Self: ...
    def inverse_mod(self, I: NumberFieldIdeal | FunctionFieldIdeal) -> Self: ...

class OrderElement_relative(NumberFieldElement_relative):
    def __init__(
        self,
        order: NumberFieldOrder | FunctionFieldOrder,
        f: Polynomial | MPolynomial | Map | Callable[..., Element],
    ) -> None: ...
    def __invert__(self) -> Self: ...
    def absolute_charpoly(self, var: str = ...) -> Self: ...
    def absolute_minpoly(self, var: str = ...) -> Self: ...
    def canonical_associate(self) -> Self: ...
    def charpoly(self, var: str = ...) -> Polynomial: ...
    def inverse_mod(self, I: NumberFieldIdeal | FunctionFieldIdeal) -> Self: ...
    def minpoly(self, var: str = ...) -> Polynomial: ...
