from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational

class NumberFieldElement: ...

class NumberFieldElement_absolute(NumberFieldElement):
    def absolute_charpoly(self, var: str = ...) -> Polynomial: ...
    def absolute_minpoly(self, var: str = ...) -> Polynomial: ...
    def charpoly(self, var: str = ...) -> Polynomial: ...
    def minpoly(self, var: str = ...) -> Polynomial: ...
    def list(self) -> list[Rational]: ...
    def lift(self) -> Polynomial: ...
    def is_real_positive(self) -> bool: ...
