from collections.abc import Callable
from typing import Protocol, Self

from sage.categories.map import Map
from sage.categories.morphism import Morphism
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.ideal import FunctionFieldIdeal
from sage.rings.function_field.order import FunctionFieldOrder
from sage.rings.integer import Integer
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.number_field.number_field_element import (
    NumberFieldElement,
    NumberFieldElement_absolute,
)
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.number_field.order import Order as NumberFieldOrder
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_mpfr import RealNumber
from sage.rings.ring import Field
from sage.structure.element import Element, RingElement
from sage.structure.parent import ElementConstructorInput, Parent

class _ContinuedFractionPeriodic(Protocol): ...
class _RealIntervalElement(Protocol): ...
class _ComplexIntervalElement(Protocol): ...
class _RealBall(Protocol): ...
class _ComplexBall(Protocol): ...
class _SympyExpression(Protocol): ...
class _QuadraticConversionParent(Protocol): ...

class NumberFieldElement_quadratic(NumberFieldElement_absolute):
    def __init__(
        self,
        parent: NumberField_generic,
        f: Self
        | Rational
        | Integer
        | tuple[Rational, Rational]
        | tuple[Integer, Integer, Integer],
    ) -> None: ...
    def parts(self) -> tuple[Rational, Rational]: ...
    def sign(self) -> int: ...
    def continued_fraction_list(self) -> tuple[tuple[int, ...], tuple[int, ...]]: ...
    def continued_fraction(self) -> _ContinuedFractionPeriodic: ...
    def _add_(self, other: Self) -> Self: ...
    def _sub_(self, other: Self) -> Self: ...
    def __neg__(self) -> Self: ...
    def _mul_(self, other: Self) -> Self: ...
    def _real_mpfi_(self, R: _QuadraticConversionParent) -> _RealIntervalElement: ...
    def _complex_mpfi_(
        self, R: _QuadraticConversionParent
    ) -> _ComplexIntervalElement: ...
    def _arb_(self, R: _QuadraticConversionParent) -> _RealBall: ...
    def _acb_(self, R: _QuadraticConversionParent) -> _ComplexBall: ...
    def _maxima_init_(self, I: str | None = None) -> str: ...
    def _fricas_init_(self) -> str: ...
    def _sympy_(self) -> _SympyExpression: ...
    def _polymake_init_(self) -> str: ...
    def _copy_for_parent(self, parent: NumberField_generic) -> Self: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[int, Self]) -> Self: ...
    def __reduce__(
        self,
    ) -> tuple[
        Callable[[NumberField_generic, type[Self], Integer, Integer, Integer], Self],
        tuple[NumberField_generic, type[Self], Integer, Integer, Integer],
    ]: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __invert__(self) -> Self: ...
    def ceil(self) -> Integer: ...
    def charpoly(self, var: str = ..., algorithm: str | None = ...) -> Polynomial: ...
    def denominator(self) -> Integer: ...
    def floor(self) -> Integer: ...
    def imag(self) -> NumberFieldElement | RealNumber: ...
    def is_integer(self) -> bool: ...
    def is_integral(self) -> bool: ...
    def minpoly(self, var: str = ..., algorithm: str | None = ...) -> Polynomial: ...
    def norm(
        self, K: NumberField_generic | FunctionField | Field | None = ...
    ) -> NumberFieldElement | Rational: ...
    def numerator(self) -> Integer | NumberFieldElement: ...
    def real(self) -> NumberFieldElement | RealNumber: ...
    def round(self) -> Integer: ...
    def trace(self) -> NumberFieldElement | Rational: ...
    def __abs__(self) -> RealNumber: ...
    def _coefficients(self) -> tuple[RingElement, ...]: ...
    def _integer_(
        self, Z: NumberFieldElement | ElementConstructorInput | None = ...
    ) -> Integer | None: ...
    def _lift_cyclotomic_element(
        self, new_parent: ElementConstructorInput, check: bool = ..., rel: int = ...
    ) -> Self: ...
    def _lmul_(self, _c: Element) -> Self: ...
    def _rational_(self) -> Rational: ...
    def _richcmp_(
        self,
        _right: ElementConstructorInput,
        op: int,
    ) -> bool: ...
    def _rmul_(self, _c: Element) -> Self: ...
    def galois_conjugate(self) -> Self: ...

class NumberFieldElement_quadratic_sqrt(NumberFieldElement_quadratic):
    def __getitem__(self, n: int | Integer) -> NumberFieldElement: ...
    def denominator(self) -> Integer: ...
    def _coefficients(self) -> tuple[RingElement, ...]: ...

class OrderElement_quadratic(NumberFieldElement_quadratic):
    def __init__(
        self,
        order: NumberFieldOrder | FunctionFieldOrder,
        f: Polynomial | MPolynomial | Map | Callable[..., Element],
    ) -> None: ...
    def __invert__(self) -> Self: ...
    def charpoly(self, var: str = ..., algorithm: str | None = ...) -> Polynomial: ...
    def denominator(self) -> Integer: ...
    def inverse_mod(self, I: NumberFieldIdeal | FunctionFieldIdeal) -> Self: ...
    def minpoly(self, var: str = ..., algorithm: str | None = ...) -> Polynomial: ...
    def norm(self) -> NumberFieldElement | Rational: ...
    def trace(self) -> NumberFieldElement | Rational: ...
    def _coefficients(self) -> tuple[RingElement, ...]: ...
    def _lmul_(self, _c: Element) -> Self: ...
    def _rmul_(self, _c: Element) -> Self: ...

class NumberFieldElement_gaussian(NumberFieldElement_quadratic_sqrt):
    def log(
        self, *args: ElementConstructorInput, **kwds: ElementConstructorInput
    ) -> Self: ...
    def _algebraic_(self, parent: Parent) -> Element: ...
    def _symbolic_(self, SR: ElementConstructorInput) -> Element: ...
    def imag_part(self) -> Self: ...
    def real_part(self) -> Self: ...

class Q_to_quadratic_field_element(Morphism):
    def __init__(self, K: NumberField_generic | FunctionField | Field) -> None: ...
    def _call_(self, x: NumberFieldElement | ElementConstructorInput) -> Element: ...
    def _repr_type(self) -> str: ...

class Z_to_quadratic_field_element(Morphism):
    def __init__(self, K: NumberField_generic | FunctionField | Field) -> None: ...
    def _call_(self, x: NumberFieldElement | ElementConstructorInput) -> Element: ...
    def _repr_type(self) -> str: ...
