from sage.categories.morphism import Morphism
from sage.matrix.matrix0 import Matrix
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.real_mpfr import RealNumber
from sage.structure.element import Element
from sage.structure.parent import Parent

def column_Log(SUK: Parent, iota: Morphism, U: Element, prec: int = 106) -> list[RealNumber]: ...
def c3_func(SUK: Parent, prec: int = 106) -> RealNumber: ...
def c4_func(SUK: Parent, v: Morphism, A: Matrix, prec: int = 106) -> RealNumber: ...
def beta_k(betas_and_ns: list[tuple[RealNumber, int]]) -> list[RealNumber]: ...
def mus(SUK: Parent, v: Morphism) -> list[Element]: ...
def possible_mu0s(SUK: Parent, v: Morphism) -> list[Element]: ...
def Yu_a1_kappa1_c1(p: int, dK: int, ep: RealNumber) -> tuple[RealNumber, ...]: ...
def Yu_condition_115(K: NumberField_generic, v: Morphism) -> bool: ...
def Yu_modified_height(mu: Element, n: int, v: Morphism, prec: int = 106) -> RealNumber: ...
def Omega_prime(dK: int, v: Morphism, mu_list: list[Element], prec: int = 106) -> RealNumber: ...
def Yu_C1_star(n: int, v: Morphism, prec: int = 106) -> RealNumber: ...
def Yu_bound(SUK: Parent, v: Morphism, prec: int = 106) -> RealNumber: ...
def K0_func(SUK: Parent, A: Matrix, prec: int = 106) -> RealNumber: ...
def c11_func(SUK: Parent, v: Morphism, A: Matrix, prec: int = 106) -> RealNumber: ...
def c13_func(SUK: Parent, v: Morphism, prec: int = 106) -> RealNumber: ...
def K1_func(SUK: Parent, v: Morphism, A: Matrix, prec: int = 106) -> RealNumber: ...
def minimal_vector(A: Matrix, y: Element, prec: int = 106) -> RealNumber: ...
def reduction_step_complex_case(place: Morphism, B0: RealNumber, list_of_gens: list[Element], torsion_gen: Element, c13: RealNumber) -> RealNumber: ...
def cx_LLL_bound(SUK: Parent, A: Matrix, prec: int = 106) -> RealNumber: ...
def log_p(a: Element, prime: int, prec: int) -> RealNumber: ...
def log_p_series_part(a: Element, prime: int, prec: int) -> RealNumber: ...
def defining_polynomial_for_Kp(prime: int, prec: int = 106) -> list[Polynomial]: ...
def embedding_to_Kp(a: Element, prime: int, prec: int) -> Element: ...
def p_adic_LLL_bound_one_prime(prime: int, B0: RealNumber, M: Matrix, M_logp: Matrix, m0: int, c3: RealNumber, prec: int = 106) -> RealNumber: ...
def p_adic_LLL_bound(SUK: Parent, A: Matrix, prec: int = 106) -> RealNumber: ...
def split_primes_large_lcm(SUK: Parent, bound: RealNumber) -> list[int]: ...
def sieve_ordering(SUK: Parent, q: int) -> list[int]: ...
def clean_rfv_dict(rfv_dictionary: dict[int, tuple[int, ...]]) -> None: ...
def construct_rfv_to_ev(rfv_dictionary: dict[int, tuple[int, ...]], q: int, d: int, verbose: bool = False) -> dict[int, tuple[int, ...]]: ...
def construct_comp_exp_vec(rfv_to_ev_dict: dict[int, tuple[int, ...]], q: int) -> dict[int, tuple[int, ...]]: ...
def drop_vector(ev: Element, p: int, q: int, complement_ev_dict: dict[int, tuple[int, ...]]) -> bool: ...
def construct_complement_dictionaries(split_primes_list: list[int], SUK: Parent, verbose: bool = False) -> tuple[dict[int, tuple[int, ...]], dict[int, tuple[int, ...]]]: ...
def compatible_vectors_check(a0: Element, a1: Element, g: int, l: int) -> bool: ...
def compatible_vectors(a: Element, m0: int, m1: int, g: int) -> bool: ...
def compatible_systems(split_prime_list: list[int], complement_exp_vec_dict: dict[int, tuple[int, ...]]) -> list[tuple[int, ...]]: ...
def compatible_system_lift(compatible_system: tuple[int, ...], split_primes_list: list[int]) -> list[tuple[int, ...]]: ...
def solutions_from_systems(SUK: Parent, bound: RealNumber, cs_list: list[tuple[int, ...]], split_primes_list: list[int]) -> list[Element]: ...
def clean_sfs(sfs_list: list[Element]) -> list[Element]: ...
def sieve_below_bound(K: NumberField_generic, S: list[Element], bound: int = 10, bump: int = 10, **kwds: int | bool) -> list[Element]: ...
def solve_S_unit_equation(K: NumberField_generic, S: list[Element], prec: int = 106, include_exponents: bool = True, include_bound: bool = False, proof: bool | None = None, verbose: bool = False) -> list[Element] | tuple[list[Element], RealNumber]: ...
def eq_up_to_order(A: Element, B: Element) -> bool: ...
