from .number_field_base import NumberField
from .number_field_element import NumberFieldElement
from .number_field_ideal import NumberFieldIdeal

class UnitGroup:
    def rank(self) -> int: ...
    def fundamental_units(self) -> list[NumberFieldElement]: ...
    def roots_of_unity(self) -> list[NumberFieldElement]: ...
    def torsion_generator(self) -> NumberFieldElement: ...
    def zeta_order(self) -> int: ...
    def zeta(self, n: int = ..., all: bool = ...) -> NumberFieldElement | list[NumberFieldElement]: ...
    def number_field(self) -> NumberField: ...
    def primes(self) -> list[NumberFieldIdeal]: ...
    def log(self, u: NumberFieldElement) -> tuple[int, ...]: ...
    def exp(self, exponents: tuple[int, ...] | list[int]) -> NumberFieldElement: ...
