from sage.categories.map import Map
from sage.rings.function_field.derivations import FunctionFieldDerivation
from sage.rings.function_field.element import FunctionFieldElement
from sage.rings.function_field.function_field import FunctionField
from sage.schemes.elliptic_curves.ell_modular_symbols import zero
from sage.structure.parent import ElementConstructorInput

class FunctionFieldDerivation_separable(FunctionFieldDerivation):
    def __init__(self, parent: FunctionField, d: ElementConstructorInput) -> None: ...
    def _call_(
        self, x: FunctionFieldElement | ElementConstructorInput
    ) -> FunctionFieldElement | zero: ...

class FunctionFieldDerivation_inseparable(FunctionFieldDerivation):
    def __init__(
        self, parent: FunctionField, u: ElementConstructorInput = ...
    ) -> None: ...
    def _call_(
        self, x: FunctionFieldElement | ElementConstructorInput
    ) -> FunctionFieldElement | zero: ...

class FunctionFieldHigherDerivation(Map):
    def __init__(self, field: FunctionField) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class RationalFunctionFieldHigherDerivation_global(FunctionFieldHigherDerivation):
    def __init__(self, field: FunctionField) -> None: ...

class FunctionFieldHigherDerivation_global(FunctionFieldHigherDerivation):
    def __init__(self, field: FunctionField) -> None: ...

class FunctionFieldHigherDerivation_char_zero(FunctionFieldHigherDerivation):
    def __init__(self, field: FunctionField) -> None: ...
