from sage.rings.derivation import RingDerivationWithoutTwist
from sage.rings.function_field.function_field import FunctionField

class FunctionFieldDerivation(RingDerivationWithoutTwist):
    def __init__(self, parent: FunctionField) -> None: ...
    def is_injective(self) -> bool: ...
