import builtins

class _SageObject: ...

class FunctionFieldDerivation_separable:
    def __init__(self, parent: builtins.object, d: builtins.object) -> None: ...

class FunctionFieldDerivation_inseparable:
    def __init__(self, parent: builtins.object, u: builtins.object = ...) -> None: ...

class FunctionFieldHigherDerivation:
    def __init__(self, field: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class RationalFunctionFieldHigherDerivation_global:
    def __init__(self, field: builtins.object) -> None: ...

class FunctionFieldHigherDerivation_global:
    def __init__(self, field: builtins.object) -> None: ...

class FunctionFieldHigherDerivation_char_zero:
    def __init__(self, field: builtins.object) -> None: ...
