from typing import Self

from sage.categories.morphism import SetMorphism
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.structure.element import Element, ModuleElement
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.richcmp import richcmp
from sage.structure.unique_representation import UniqueRepresentation

def divisor(field: FunctionField, data: FunctionField) -> FunctionFieldDivisor: ...
def prime_divisor(
    field: FunctionField, place: FunctionFieldPlace, m: int | Integer = ...
) -> FunctionFieldDivisor: ...

class FunctionFieldDivisor(ModuleElement):
    def __init__(
        self, parent: FunctionField, data: ElementConstructorInput
    ) -> None: ...
    def __hash__(self) -> int: ...
    def dict(self) -> dict[Element, FunctionFieldDivisor]: ...
    def list(self) -> list[FunctionFieldDivisor]: ...
    def support(self) -> list[FunctionFieldDivisor]: ...
    def multiplicity(self, place: FunctionFieldPlace) -> Self: ...
    valuation: Integer

    def is_effective(self) -> bool: ...
    def is_prime(self) -> bool: ...
    def place(self) -> FunctionFieldPlace: ...
    def numerator(self) -> Self: ...
    def denominator(self) -> Self: ...
    def degree(self) -> int | Integer: ...
    def dimension(self) -> int | Integer: ...
    def basis_function_space(self) -> Self: ...
    def function_space(self) -> Self: ...
    def basis_differential_space(self) -> Self: ...
    def differential_space(self) -> Self: ...
    def _repr_(self, split: bool = ...) -> str: ...
    def _latex_(self) -> str: ...
    def _richcmp_(
        self,
        other: FunctionFieldDivisor | ElementConstructorInput,
        op: ElementConstructorInput,
    ) -> richcmp: ...

class DivisorGroup(UniqueRepresentation, Parent):
    def __init__(self, field: FunctionField) -> None: ...
    def function_field(self) -> Self: ...
    def effective_divisors(
        self,
        of_degree: int | Integer = ...,
        max_degree: int | Integer = ...,
        avoid: int | Integer = ...,
    ) -> Self: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(
        self, x: DivisorGroup | ElementConstructorInput
    ) -> FunctionField: ...
    def _coerce_map_from_(self, S: Ring | Parent) -> SetMorphism: ...
    def _an_element_(self) -> FunctionFieldDivisor: ...
