# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def divisor(field: builtins.object, data: builtins.object) -> _SageObject: ...

def prime_divisor(field: builtins.object, place: builtins.object, m: builtins.int = ...) -> _SageObject: ...

class FunctionFieldDivisor:
    def __init__(self, parent: DivisorGroup, data: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def dict(self) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def support(self) -> _SageObject: ...
    def multiplicity(self, place: builtins.object) -> _SageObject: ...
    valuation: _SageObject
    def is_effective(self) -> builtins.bool: ...
    def is_prime(self) -> builtins.bool: ...
    def place(self) -> _SageObject: ...
    def numerator(self) -> _SageObject: ...
    def denominator(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def basis_function_space(self) -> _SageObject: ...
    def function_space(self) -> _SageObject: ...
    def basis_differential_space(self) -> _SageObject: ...
    def differential_space(self) -> _SageObject: ...

class DivisorGroup:
    Element: _SageObject
    def __init__(self, field: builtins.object) -> None: ...
    def function_field(self) -> _SageObject: ...
    def effective_divisors(self, of_degree: builtins.object = ..., max_degree: builtins.object = ..., avoid: builtins.object = ...) -> _Iterable[FunctionFieldDivisor]: ...
