from sage.categories.morphism import Morphism
from sage.rings.function_field.divisor import FunctionFieldDivisor
from sage.rings.function_field.element import FunctionFieldElement
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.integer import Integer
from sage.rings.ring_extension import RingExtension_generic
from sage.structure.parent import ElementConstructorInput

class FunctionFieldExtension(RingExtension_generic): ...

class ConstantFieldExtension(FunctionFieldExtension):
    def __init__(self, F: FunctionField, k_ext: ElementConstructorInput) -> None: ...
    def top(self) -> FunctionFieldElement: ...
    def defining_morphism(self) -> Morphism: ...
    def conorm_place(
        self, p: int | Integer | FunctionFieldPlace
    ) -> FunctionFieldElement: ...
    def conorm_divisor(self, d: FunctionField) -> FunctionFieldDivisor: ...
