# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FunctionField_polymod:
    Element: _SageObject
    def __init__(self, polynomial: builtins.object, names: builtins.object, category: builtins.object = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def monic_integral_model(self, names: builtins.object = ...) -> _SageObject: ...
    def constant_field(self) -> _SageObject: ...
    def constant_base_field(self) -> _SageObject: ...
    def degree(self, base: builtins.object = ...) -> _SageObject: ...
    def base_field(self) -> _SageObject: ...
    def random_element(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def polynomial(self) -> _SageObject: ...
    def is_separable(self, base: builtins.object = ...) -> builtins.bool: ...
    def polynomial_ring(self) -> _SageObject: ...
    def free_module(self, base: builtins.object = ..., basis: builtins.object = ..., map: builtins.bool = ...) -> _SageObject: ...
    def maximal_order(self) -> _SageObject: ...
    def maximal_order_infinite(self) -> _SageObject: ...
    def different(self) -> _SageObject: ...
    def equation_order(self) -> _SageObject: ...
    def hom(self, im_gens: builtins.object, base_morphism: builtins.object = ...) -> _SageObject: ...
    def genus(self) -> _SageObject: ...
    def simple_model(self, name: builtins.str = ...) -> _SageObject: ...
    def primitive_element(self) -> _SageObject: ...
    def separable_model(self, names: builtins.object = ...) -> _SageObject: ...
    def change_variable_name(self, name: builtins.str) -> _SageObject: ...

class FunctionField_simple:
    def places_above(self, p: builtins.int) -> _SageObject: ...
    def constant_field(self) -> _SageObject: ...
    def exact_constant_field(self, name: builtins.str = ...) -> _SageObject: ...
    def genus(self) -> _SageObject: ...
    def residue_field(self, place: builtins.object, name: builtins.str = ...) -> _SageObject: ...
    def places_infinite(self, degree: builtins.int = ...) -> _SageObject: ...
    def get_infinite_place(self, degree: builtins.int = ...) -> _SageObject: ...

class FunctionField_char_zero:
    def higher_derivation(self) -> _SageObject: ...

class FunctionField_global:
    def __init__(self, polynomial: builtins.object, names: builtins.object) -> None: ...
    def maximal_order(self) -> _SageObject: ...
    def higher_derivation(self) -> _SageObject: ...
    def places(self, degree: builtins.int = ...) -> _SageObject: ...
    def gaps(self) -> _SageObject: ...
    def weierstrass_places(self) -> _SageObject: ...
    def L_polynomial(self, name: builtins.str = ...) -> _SageObject: ...
    def number_of_rational_places(self, r: builtins.int = ...) -> _SageObject: ...

class FunctionField_integral:
    def equation_order(self) -> _SageObject: ...
    def primitive_integal_element_infinite(self) -> _SageObject: ...
    def equation_order_infinite(self) -> _SageObject: ...

class FunctionField_char_zero_integral:
    ...

class FunctionField_global_integral:
    ...
