from collections.abc import Callable, Sequence
from typing import Self

from sage.categories.category import Category
from sage.categories.map import Map
from sage.categories.morphism import Morphism
from sage.modules.free_module import FreeModule_generic
from sage.rings.function_field.derivations import FunctionFieldDerivation
from sage.rings.function_field.element import FunctionFieldElement
from sage.rings.function_field.element_rational import FunctionFieldElement_rational
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.ideal import FunctionFieldIdeal
from sage.rings.function_field.order import FunctionFieldOrder
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.integer import Integer
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ring import Field
from sage.structure.parent import ElementConstructorInput, Parent

class RationalFunctionField(FunctionField):
    def __init__(
        self,
        constant_field: FunctionField,
        names: str | tuple[str, ...],
        category: Category = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[Callable[..., Self], tuple[ElementConstructorInput, ...]]: ...
    def __hash__(self) -> int: ...
    def polynomial_ring(self, var: Polynomial | MPolynomial = ...) -> Parent: ...
    def free_module(
        self, base: FunctionField = ..., basis: FunctionField = ..., map: bool = ...
    ) -> FreeModule_generic | tuple[FreeModule_generic, Morphism, Morphism]: ...
    def random_element(
        self, *args: ElementConstructorInput, **kwds: ElementConstructorInput
    ) -> FunctionFieldElement: ...
    def degree(self, base: FunctionField = ...) -> int | Integer: ...
    def gen(self, n: int | Integer = ...) -> FunctionFieldElement: ...
    def ngens(self) -> int | Integer: ...
    def base_field(self) -> FunctionField: ...
    def hom(
        self,
        im_gens: Sequence[ElementConstructorInput],
        base_morphism: Map | Morphism = ...,
    ) -> Morphism: ...
    def field(self) -> FunctionField: ...
    def maximal_order(self) -> FunctionFieldOrder: ...
    equation_order: FunctionFieldOrder

    def maximal_order_infinite(self) -> FunctionFieldOrder: ...
    equation_order_infinite: FunctionFieldOrder

    def constant_base_field(self) -> FunctionField: ...
    constant_field: FunctionField

    def different(self) -> FunctionFieldIdeal: ...
    def genus(self) -> int | Integer: ...
    def change_variable_name(self, name: str) -> Self: ...
    def residue_field(
        self, place: FunctionFieldPlace, name: str = ...
    ) -> Field | tuple[Field, Morphism, Morphism]: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(
        self, x: FunctionFieldElement | ElementConstructorInput
    ) -> FunctionFieldElement_rational: ...

class RationalFunctionField_char_zero(RationalFunctionField):
    def higher_derivation(self) -> FunctionFieldDerivation: ...

class RationalFunctionField_global(RationalFunctionField):
    def places(self, degree: int | Integer = ...) -> list[FunctionFieldPlace]: ...
    def place_infinite(self) -> FunctionFieldElement: ...
    def get_finite_place(self, degree: int | Integer) -> FunctionFieldElement: ...
    def get_infinite_place(self, degree: int | Integer = ...) -> FunctionFieldPlace: ...
    def higher_derivation(self) -> FunctionFieldDerivation: ...
