import builtins
from typing import Literal

from sage.rings.function_field.element_rational import FunctionFieldElement_rational
from sage.rings.function_field.place_rational import FunctionFieldPlace_rational
from sage.rings.integer import Integer

class _SageObject: ...

class RationalFunctionField:
    Element: _SageObject

    def __init__(
        self,
        constant_field: builtins.object,
        names: builtins.object,
        category: builtins.object = ...,
    ) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __hash__(self) -> int: ...
    def polynomial_ring(self, var: builtins.str = ...) -> _SageObject: ...
    def free_module(
        self,
        base: builtins.object = ...,
        basis: builtins.object = ...,
        map: builtins.bool = ...,
    ) -> _SageObject: ...
    def random_element(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> FunctionFieldElement_rational: ...
    def degree(self, base: builtins.object = ...) -> Integer: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def ngens(self) -> Literal[1]: ...
    def base_field(self) -> _SageObject: ...
    def hom(
        self, im_gens: builtins.object, base_morphism: builtins.object = ...
    ) -> _SageObject: ...
    def field(self) -> _SageObject: ...
    def maximal_order(self) -> _SageObject: ...
    equation_order: _SageObject

    def maximal_order_infinite(self) -> _SageObject: ...
    equation_order_infinite: _SageObject

    def constant_base_field(self) -> _SageObject: ...
    constant_field: _SageObject

    def different(self) -> _SageObject: ...
    def genus(self) -> Integer: ...
    def change_variable_name(self, name: builtins.str) -> _SageObject: ...
    def residue_field(
        self, place: builtins.object, name: builtins.str = ...
    ) -> _SageObject: ...

class RationalFunctionField_char_zero:
    def higher_derivation(self) -> _SageObject: ...

class RationalFunctionField_global:
    def places(self, degree: builtins.int = ...) -> _SageObject: ...
    def place_infinite(self) -> _SageObject: ...
    def get_finite_place(
        self, degree: builtins.int
    ) -> FunctionFieldPlace_rational | None: ...
    def get_infinite_place(
        self, degree: builtins.int = ...
    ) -> FunctionFieldPlace_rational | None: ...
    def higher_derivation(self) -> _SageObject: ...
