import builtins
from typing import Self

from sage.structure.element import Element

class _SageObject: ...

class FunctionFieldIdeal:
    def __init__(self, ring: builtins.object) -> None: ...
    def gens_reduced(self) -> _SageObject: ...
    def ring(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def place(self) -> _SageObject: ...
    def factor(self) -> _SageObject: ...
    def divisor(self) -> _SageObject: ...
    def divisor_of_zeros(self) -> _SageObject: ...
    def divisor_of_poles(self) -> _SageObject: ...

class FunctionFieldIdeal_module:
    def __init__(self, ring: builtins.object, module: builtins.object) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __hash__(self) -> int: ...
    def module(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def intersection(self, other: builtins.object) -> _SageObject: ...
    def __invert__(self) -> Self: ...

class FunctionFieldIdealInfinite: ...

class FunctionFieldIdealInfinite_module:
    def __init__(self, ring: builtins.object, module: builtins.object) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def module(self) -> _SageObject: ...

class IdealMonoid:
    def __init__(self, R: builtins.int) -> None: ...
    def ring(self) -> _SageObject: ...
