from typing import Self

from sage.rings.function_field.divisor import FunctionFieldDivisor
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.ideal import Ideal_generic
from sage.rings.integer import Integer
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.factorization import Factorization
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.richcmp import richcmp
from sage.structure.unique_representation import UniqueRepresentation

class FunctionFieldIdeal(Element):
    def __init__(self, ring: Ring) -> None: ...
    def gens_reduced(self) -> Self: ...
    def ring(self) -> Ring: ...
    def base_ring(self) -> Ring: ...
    def place(self) -> FunctionFieldPlace: ...
    def factor(self) -> Factorization: ...
    def divisor(self) -> FunctionFieldDivisor: ...
    def divisor_of_zeros(self) -> Self: ...
    def divisor_of_poles(self) -> Self: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...

class FunctionFieldIdeal_module(FunctionFieldIdeal, Ideal_generic):
    def __init__(self, ring: Ring, module: ElementConstructorInput) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __hash__(self) -> int: ...
    def module(self) -> Self: ...
    def gens(self) -> tuple[FunctionFieldIdeal_module, ...]: ...
    def gen(self, i: int | Integer) -> FunctionFieldIdeal_module: ...
    def ngens(self) -> int | Integer: ...
    def intersection(
        self, other: FunctionFieldIdeal_module | ElementConstructorInput
    ) -> Self: ...
    def __invert__(self) -> Self: ...
    def _richcmp_(
        self,
        other: FunctionFieldIdeal_module | ElementConstructorInput,
        op: ElementConstructorInput,
    ) -> richcmp: ...

class FunctionFieldIdealInfinite(FunctionFieldIdeal): ...

class FunctionFieldIdealInfinite_module(FunctionFieldIdealInfinite, Ideal_generic):
    def __init__(self, ring: Ring, module: ElementConstructorInput) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def module(self) -> Self: ...

class IdealMonoid(UniqueRepresentation, Parent):
    def __init__(self, R: Ring) -> None: ...
    def ring(self) -> Ring: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(
        self, x: IdealMonoid | ElementConstructorInput
    ) -> NumberFieldIdeal | FunctionFieldIdeal: ...
    def _coerce_map_from_(self, x: IdealMonoid | ElementConstructorInput) -> bool: ...
    def _an_element_(self) -> Self: ...
