import builtins

from sage.rings.function_field.divisor import FunctionFieldDivisor
from sage.rings.function_field.function_field import FunctionField

class _SageObject: ...

class JacobianPoint_base:
    def addflip(self, other: builtins.object) -> _SageObject: ...
    def divisor(self) -> FunctionFieldDivisor: ...

class JacobianPoint_finite_field_base:
    def additive_order(self) -> _SageObject: ...
    def frobenius(self) -> _SageObject: ...

class JacobianGroupFunctor:
    rank: _SageObject

    def __init__(self, base_field: builtins.object, field: builtins.object) -> None: ...
    def merge(self, other: builtins.object) -> _SageObject: ...

class JacobianGroup_base:
    def __init__(
        self,
        parent: builtins.object,
        function_field: builtins.object,
        base_div: builtins.object,
    ) -> None: ...
    def construction(self) -> _SageObject: ...
    def parent(self) -> _SageObject: ...
    def function_field(self) -> FunctionField: ...
    def base_divisor(self) -> FunctionFieldDivisor: ...

class JacobianGroup_finite_field_base:
    def order(self, algorithm: builtins.str = ...) -> _SageObject: ...
    def get_points(self, n: builtins.int) -> list[JacobianPoint_finite_field_base]: ...
    def some_elements(self) -> list[JacobianPoint_finite_field_base]: ...

class Jacobian_base:
    def __init__(
        self,
        function_field: builtins.object,
        base_div: builtins.object,
        **kwds: builtins.object,
    ) -> None: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def curve(self) -> _SageObject: ...
    def base_curve(self) -> _SageObject: ...
    def facade_for(self) -> _SageObject: ...
    def base_divisor(self) -> FunctionFieldDivisor: ...
    def group(self, k_ext: builtins.object = ...) -> _SageObject: ...
    def set_base_place(self, place: builtins.object) -> None: ...
