# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class JacobianPoint:
    def __init__(self, parent: JacobianGroup, finite_ideal: builtins.object, infinite_ideal: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def additive_order(self) -> _SageObject: ...
    def effective_part(self) -> _SageObject: ...
    def divisor(self) -> _SageObject: ...

class JacobianPoint_finite_field:
    ...

class JacobianGroup:
    Element: _SageObject
    def __init__(self, parent: builtins.object, function_field: builtins.object, base_div: builtins.object) -> None: ...
    def point(self, divisor: builtins.object) -> _SageObject: ...
    def zero(self) -> JacobianPoint: ...

class JacobianGroup_finite_field:
    Element: _SageObject
    def __iter__(self) -> _Iterator[JacobianPoint_finite_field]: ...

class Jacobian:
    def __init__(self, function_field: builtins.object, base_div: builtins.object, cache_infinite_ideals: builtins.bool = ..., **kwds: builtins.object) -> None: ...
    def group(self, k_ext: builtins.object = ...) -> _SageObject: ...
