from collections.abc import Callable

from sage.calculus.predefined import F
from sage.categories.map import Map
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element

class FunctionFieldMaximalOrder: ...
class FunctionFieldMaximalOrderInfinite: ...

from collections.abc import Sequence

from sage.categories.category import Category
from sage.rings.function_field.element import FunctionFieldElement
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.ideal import FunctionFieldIdeal
from sage.rings.integer import Integer
from sage.sets.family import Family
from sage.structure.parent import ElementConstructorInput

class FunctionFieldMaximalOrder_rational(FunctionFieldMaximalOrder):
    def __init__(self, field: FunctionField) -> None: ...
    def ideal_with_gens_over_base(
        self, gens: Sequence[ElementConstructorInput]
    ) -> FunctionFieldElement: ...
    def basis(self) -> Family[FunctionFieldElement]: ...
    def gen(self, n: int | Integer = ...) -> FunctionFieldElement: ...
    def ngens(self) -> int | Integer: ...
    def ideal(self, *gens: ElementConstructorInput) -> FunctionFieldIdeal: ...
    def _element_constructor_(
        self, f: Polynomial | MPolynomial | Map | Callable[..., Element]
    ) -> F: ...

class FunctionFieldMaximalOrderInfinite_rational(FunctionFieldMaximalOrderInfinite):
    def __init__(self, field: FunctionField, category: Category = ...) -> None: ...
    def basis(self) -> Family[FunctionFieldElement]: ...
    def prime_ideal(self) -> FunctionFieldElement: ...
    def ideal(self, *gens: ElementConstructorInput) -> FunctionFieldIdeal: ...
    def _element_constructor_(
        self, f: Polynomial | MPolynomial | Map | Callable[..., Element]
    ) -> F: ...
