from typing import Self

from sage.categories.morphism import Morphism
from sage.rings.function_field.place import FunctionFieldPlace
from sage.rings.integer import Integer
from sage.rings.ring import Field

class FunctionFieldPlace_polymod(FunctionFieldPlace):
    def place_below(self) -> Self: ...
    def relative_degree(self) -> int | Integer: ...
    def degree(self) -> int | Integer: ...
    def is_infinite_place(self) -> bool: ...
    def local_uniformizer(self) -> Self: ...
    def gaps(self) -> list[Integer]: ...
    def residue_field(
        self, name: str = ...
    ) -> Field | tuple[Field, Morphism, Morphism]: ...
    def valuation_ring(self) -> Self: ...
