# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FunctionFieldPlace_polymod:
    def place_below(self) -> _SageObject: ...
    def relative_degree(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def is_infinite_place(self) -> builtins.bool: ...
    def local_uniformizer(self) -> _SageObject: ...
    def gaps(self) -> _SageObject: ...
    def residue_field(self, name: builtins.str = ...) -> _SageObject: ...
    def valuation_ring(self) -> _SageObject: ...
