import builtins

from sage.rings.function_field.divisor import FunctionFieldDivisor
from sage.rings.function_field.function_field import FunctionField
from sage.rings.function_field.ideal import FunctionFieldIdeal

class _SageObject: ...

class FunctionFieldPlace:
    def __init__(self, parent: builtins.object, prime: builtins.object) -> None: ...
    def __hash__(self) -> int: ...
    def __radd__(self, other: builtins.object) -> FunctionFieldDivisor: ...
    def function_field(self) -> FunctionField: ...
    def prime_ideal(self) -> FunctionFieldIdeal: ...
    def divisor(self, multiplicity: builtins.int = ...) -> _SageObject: ...

class PlaceSet:
    Element: _SageObject

    def __init__(self, field: builtins.object) -> None: ...
    def function_field(self) -> FunctionField: ...
