# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Point:
    def __init__(self, point_configuration: builtins.object, i: builtins.object, projective: builtins.object, affine: builtins.object, reduced: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def point_configuration(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
    def index(self) -> _SageObject: ...
    def projective(self) -> _SageObject: ...
    def affine(self) -> _SageObject: ...
    def reduced_affine(self) -> _SageObject: ...
    def reduced_projective(self) -> _SageObject: ...
    def reduced_affine_vector(self) -> _SageObject: ...
    def reduced_projective_vector(self) -> _SageObject: ...

class PointConfiguration_base:
    def __init__(self, points: builtins.object, defined_affine: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def reduced_affine_vector_space(self) -> _SageObject: ...
    def reduced_projective_vector_space(self) -> _SageObject: ...
    def ambient_dim(self) -> _SageObject: ...
    def dim(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def is_affine(self) -> builtins.bool: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def n_points(self) -> _SageObject: ...
    def points(self) -> _SageObject: ...
    def point(self, i: builtins.object) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def simplex_to_int(self, simplex: builtins.object) -> _SageObject: ...
    def int_to_simplex(self, s: builtins.object) -> _SageObject: ...

class ConnectedTriangulationsIterator:
    def __cinit__(self) -> _SageObject: ...
    def __init__(self, point_configuration: builtins.object, seed: builtins.object = ..., star: builtins.object = ..., fine: builtins.object = ...) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...
