from collections.abc import Iterator

from sage.structure.element import Element

def triangulation_render_2d(triangulation: Element | int | str | bool | None) -> Element: ...
def triangulation_render_3d(triangulation: Element | int | str | bool | None) -> Element: ...

class Triangulation(Element):
    def point_configuration(self) -> Element: ...
    def _richcmp_(self, other: Element, op: Element | int | str | bool | None) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __getitem__(self, i: int) -> Element: ...
    def __len__(self) -> int: ...
    def _repr_(self) -> str: ...
    def plot(self) -> Element: ...
    def gkz_phi(self) -> Element: ...
    def enumerate_simplices(self) -> Element: ...
    def fan(self, origin: Element | int | str | bool | None) -> Element: ...
    def simplicial_complex(self) -> Element: ...
    def _boundary_simplex_dictionary(self) -> Element: ...
    def boundary(self) -> Element: ...
    def boundary_simplicial_complex(self) -> Element: ...
    def interior_facets(self) -> Element: ...
    def polyhedral_complex(self) -> Element: ...
    def boundary_polyhedral_complex(self) -> Element: ...
    def normal_cone(self) -> Element: ...
    def adjacency_graph(self) -> Element: ...
