from collections.abc import Iterator

from sage.structure.element import Element

class PointConfiguration(UniqueRepresentation, PointConfiguration_base):
    def _have_TOPCOM(self) -> Element: ...
    def set_engine(self, engine: Element | int | str | bool | None) -> Element: ...
    def star_center(self) -> Element: ...
    def an_element(self) -> Element: ...
    def _element_constructor_(self, e: Element) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...
    def _repr_(self) -> str: ...
    def _TOPCOM_points(self) -> Element: ...
    def _TOPCOM_exec(self, executable: Element | int | str | bool | None, input_string: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _TOPCOM_communicate(self, executable: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _TOPCOM_triangulations(self, verbose: bool) -> Element: ...
    def _TOPCOM_triangulate(self, verbose: bool) -> Element: ...
    def restrict_to_regular_triangulations(self, regular: Element | int | str | bool | None) -> Element: ...
    def restrict_to_connected_triangulations(self, connected: Element | int | str | bool | None) -> Element: ...
    def restrict_to_fine_triangulations(self, fine: Element | int | str | bool | None) -> Element: ...
    def restrict_to_star_triangulations(self, star: Element | int | str | bool | None) -> Element: ...
    def triangulations(self, verbose: bool) -> Element: ...
    def triangulations_list(self, verbose: bool) -> Element: ...
    def triangulate(self, verbose: bool) -> Element: ...
    def convex_hull(self) -> Element: ...
    def restricted_automorphism_group(self) -> Element: ...
    def face_codimension(self, point: Element | int | str | bool | None) -> Element: ...
    def face_interior(self, dim: Element | int | str | bool | None, codim: Element | int | str | bool | None) -> Element: ...
    def exclude_points(self, point_idx_list: Element | int | str | bool | None) -> Element: ...
    def volume(self, simplex: Element | int | str | bool | None) -> Element: ...
    def secondary_polytope(self) -> Element: ...
    def circuits_support(self) -> Element: ...
    def circuits(self) -> Element: ...
    def positive_circuits(self) -> Element: ...
    def bistellar_flips(self) -> Element: ...
    def lexicographic_triangulation(self) -> Element: ...
    def distance_affine(self, x: Element, y: Element) -> Element: ...
    def distance_FS(self, x: Element, y: Element) -> Element: ...
    def distance(self, x: Element, y: Element) -> Element: ...
    def farthest_point(self, points: Element | int | str | bool | None, among: Element | int | str | bool | None) -> Element: ...
    def contained_simplex(self, large: Element | int | str | bool | None, initial_point: Element | int | str | bool | None, point_order: Element | int | str | bool | None) -> Element: ...
    def placing_triangulation(self, point_order: Element | int | str | bool | None) -> Element: ...
    def Gale_transform(self, points: Element | int | str | bool | None, homogenize: Element | int | str | bool | None) -> Element: ...
    def deformation_cone(self, collection: Element | int | str | bool | None) -> Element: ...
    def plot(self) -> Element: ...

class PointConfiguration_base: ...

class UniqueRepresentation: ...
