# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BGGDualModule:
    def __init__(self, module: builtins.object) -> None: ...
    def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
    def highest_weight(self) -> _SageObject: ...
    def highest_weight_vector(self) -> _SageObject: ...
    def lie_algebra(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    class Element:
        ...

class SimpleModuleIndices:
    @staticmethod
    def __classcall__(cls: builtins.object, simple: builtins.object, prefix: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...
    def __init__(self, simple: builtins.object, prefix: builtins.str, category: builtins.object = ..., **kwds: builtins.object) -> None: ...
    def weight_space_basis(self, mu: builtins.object) -> _SageObject: ...
    def __contains__(self, m: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...

class SimpleModule:
    @staticmethod
    def __classcall_private__(cls: builtins.object, g: builtins.object, weight: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def __init__(self, g: builtins.object, weight: builtins.object, prefix: builtins.str = ..., basis_key: builtins.object = ..., **kwds: builtins.object) -> None: ...
    def ambient(self) -> _SageObject: ...
    def lift(self) -> _SageObject: ...
    def retract(self, x: builtins.object) -> _SageObject: ...
    def dual(self) -> Self: ...
    def highest_weight(self) -> _SageObject: ...
    def highest_weight_vector(self) -> _SageObject: ...
    def lie_algebra(self) -> _SageObject: ...
    def pbw_basis(self) -> _SageObject: ...
    def homogeneous_component_basis(self, mu: builtins.object) -> _SageObject: ...
    weight_space_basis: _SageObject
    class Element:
        ...

class FiniteDimensionalSimpleModule:
    def bgg_resolution(self) -> _SageObject: ...
