import builtins

class _SageObject: ...

class BGGResolution:
    def __init__(self, L: builtins.object) -> None: ...
    def simple_module(self) -> _SageObject: ...
    def module_order(self, i: builtins.int) -> _SageObject: ...

def build_differentials(self) -> _SageObject: ...
