# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CenterIndices:
    @staticmethod
    def __classcall__(cls: builtins.object, center: builtins.object) -> _SageObject: ...
    def __init__(self, center: builtins.object, indices: builtins.object = ...) -> None: ...
    def lift_on_basis(self, m: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def some_elements(self) -> _SageObject: ...
    def degree(self, m: builtins.int) -> _SageObject: ...

class SimpleLieCenterIndices:
    def __init__(self, center: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class CenterUEA:
    def __init__(self, g: builtins.object, UEA: builtins.object) -> None: ...
    def algebra_generators(self) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def product_on_basis(self, left: builtins.object, right: builtins.object) -> _SageObject: ...
    def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
    def lift(self) -> _SageObject: ...
    def retract(self, elt: builtins.object) -> _SageObject: ...
