import builtins

class _SageObject: ...

def three_dimensional(
    self,
    a: builtins.object,
    b: builtins.object,
    c: builtins.object,
    d: builtins.object,
    names: builtins.list[_SageObject] = ...,
) -> _SageObject: ...
def cross_product(self, names: builtins.list[_SageObject] = ...) -> _SageObject: ...
def three_dimensional_by_rank(
    self,
    n: builtins.int,
    a: builtins.object = ...,
    names: builtins.list[_SageObject] = ...,
) -> _SageObject: ...
def affine_transformations_line(
    self, names: builtins.list[_SageObject] = ..., representation: builtins.str = ...
) -> _SageObject: ...
def abelian(
    self, names: builtins.object = ..., index_set: builtins.object = ...
) -> _SageObject: ...
def Heisenberg(
    self, n: builtins.int, representation: builtins.str = ...
) -> _SageObject: ...
def regular_vector_fields(self) -> _SageObject: ...

witt: _SageObject

def pwitt(self, p: builtins.int) -> _SageObject: ...
def upper_triangular_matrices(self, n: builtins.int) -> _SageObject: ...
def strictly_upper_triangular_matrices(self, n: builtins.int) -> _SageObject: ...
def sl(self, n: builtins.int, representation: builtins.str = ...) -> _SageObject: ...
def su(self, n: builtins.int, representation: builtins.str = ...) -> _SageObject: ...
def so(self, n: builtins.int, representation: builtins.str = ...) -> _SageObject: ...
def sp(self, n: builtins.int, representation: builtins.str = ...) -> _SageObject: ...
