import builtins

from sage.structure.element import Element

class _SageObject: ...

class FreeLieBasis_abstract:
    def __init__(self, lie: builtins.object, basis_name: builtins.str) -> None: ...
    def monomial(self, x: builtins.object) -> _SageObject: ...
    def is_abelian(self) -> bool: ...
    def basis(self) -> _SageObject: ...
    def degree_on_basis(self, x: builtins.object) -> _SageObject: ...
    def graded_dimension(self, k: builtins.int) -> _SageObject: ...
    def graded_basis(self, k: builtins.int) -> _SageObject: ...
    Element: _SageObject

class FreeLieAlgebra:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        R: builtins.int,
        names: builtins.object = ...,
        index_set: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self, R: builtins.int, names: builtins.object, index_set: builtins.object
    ) -> None: ...
    def lie_algebra_generators(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def a_realization(self) -> _SageObject: ...

    class Hall:
        def __init__(self, lie: builtins.object) -> None: ...
        def graded_basis(self, k: builtins.int) -> _SageObject: ...

    class Lyndon:
        def __init__(self, lie: builtins.object) -> None: ...
        def graded_basis(self, k: builtins.int) -> _SageObject: ...
        def pbw_basis(self, **kwds: builtins.object) -> _SageObject: ...
        poincare_birkhoff_witt_basis: _SageObject

class FreeLieAlgebraBases:
    def __init__(self, base: builtins.object) -> None: ...
    def super_categories(self) -> _SageObject: ...

def is_lyndon(self) -> bool: ...
