from sage.structure.element import Element
from sage.structure.parent import Parent

def is_lyndon(w: Element) -> bool: ...

class FreeLieBasis_abstract(FinitelyGeneratedLieAlgebra, IndexedGenerators, BindableClass):
    def _repr_(self) -> str: ...
    def _repr_term(self, x: Element) -> str: ...
    def _latex_term(self, x: Element) -> str: ...
    def _ascii_art_term(self, x: Element) -> Element: ...
    def _unicode_art_term(self, x: Element) -> Element: ...
    def _element_constructor_(self, x: Element) -> Element: ...
    def monomial(self, x: Element) -> Element: ...
    def _construct_UEA(self) -> Element: ...
    def is_abelian(self) -> bool: ...
    def basis(self) -> Element: ...
    def degree_on_basis(self, x: Element) -> int: ...
    def graded_dimension(self, k: int) -> Element: ...
    def graded_basis(self, k: int) -> Element: ...
    def _rewrite_bracket(self, l: Element | int | str | bool | None, r: int) -> Element: ...

class FreeLieAlgebra(Parent, UniqueRepresentation):
    def lie_algebra_generators(self) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: int) -> Element: ...
    def a_realization(self) -> Element: ...

class FreeLieAlgebraBases(Category_realization_of_parent):
    def super_categories(self) -> Element: ...

class BindableClass: ...

class Category_realization_of_parent: ...

class FinitelyGeneratedLieAlgebra: ...

class IndexedGenerators: ...

class UniqueRepresentation: ...
