import builtins

from sage.structure.element import Element

class _SageObject: ...

class HeisenbergAlgebra_abstract:
    def __init__(self, I: builtins.int) -> None: ...
    def p(self, i: builtins.int) -> _SageObject: ...
    def q(self, i: builtins.int) -> _SageObject: ...
    def z(self) -> _SageObject: ...
    def bracket_on_basis(
        self, x: builtins.object, y: builtins.object
    ) -> _SageObject: ...
    def step(self) -> _SageObject: ...

    class Element: ...

class HeisenbergAlgebra_fd:
    def __init__(self, n: builtins.int) -> None: ...
    def n(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def lie_algebra_generators(self) -> _SageObject: ...
    def basis(self) -> _SageObject: ...

class HeisenbergAlgebra:
    def __init__(self, R: builtins.int, n: builtins.int) -> None: ...

class InfiniteHeisenbergAlgebra:
    def __init__(self, R: builtins.int) -> None: ...
    def lie_algebra_generators(self) -> _SageObject: ...
    def basis(self) -> _SageObject: ...

class HeisenbergAlgebra_matrix:
    def __init__(self, R: builtins.int, n: builtins.int) -> None: ...
    def p(self, i: builtins.int) -> _SageObject: ...
    def q(self, i: builtins.int) -> _SageObject: ...
    def z(self) -> _SageObject: ...
    def step(self) -> _SageObject: ...

    class Element:
        def monomial_coefficients(self, copy: builtins.bool = ...) -> _SageObject: ...
