from sage.matrix.matrix import Matrix
from sage.rings.ring import Ring

class LieAlgebra_generic:
    def base_ring(self) -> Ring: ...
    def rank(self) -> int: ...
    def killing_form_matrix(self) -> Matrix: ...
    def is_abelian(self) -> bool: ...
    def is_semisimple(self) -> bool: ...
    def is_solvable(self) -> bool: ...
