# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LieAlgebraElement:
    def __mul__(left: builtins.object, right: builtins.object) -> Self: ...
    def base_map(x: builtins.object) -> _SageObject: ...
    def lift(self) -> _SageObject: ...

class LieAlgebraElementWrapper:
    def __bool__(self) -> builtins.bool: ...
    def __mul__(left: builtins.object, right: builtins.object) -> Self: ...
    def __truediv__(self, x: builtins.object) -> Self: ...
    def __neg__(self) -> Self: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class LieAlgebraMatrixWrapper:
    def __init__(self, parent: builtins.object, value: builtins.object) -> None: ...

class LieSubalgebraElementWrapper:
    def __init__(self, parent: builtins.object, value: builtins.object) -> None: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def monomial_coefficients(self, copy: builtins.object = ...) -> _SageObject: ...

class StructureCoefficientsElement:
    def bracket(self, right: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def to_vector(self, sparse: builtins.object = ..., order: builtins.object = ...) -> _SageObject: ...
    def lift(self) -> _SageObject: ...
    def monomial_coefficients(self, copy: builtins.object = ...) -> _SageObject: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...

class UntwistedAffineLieAlgebraElement:
    def __init__(self, parent: builtins.object, t_dict: builtins.object, c_coeff: builtins.object, d_coeff: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def t_dict(self) -> _SageObject: ...
    def c_coefficient(self) -> _SageObject: ...
    def d_coefficient(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __bool__(self) -> builtins.bool: ...
    def monomial_coefficients(self, copy: builtins.object = ...) -> _SageObject: ...
    def bracket(self, right: builtins.object) -> _SageObject: ...
    def canonical_derivation(self) -> _SageObject: ...

class FreeLieAlgebraElement:
    def lift(self) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def k(x: builtins.object) -> _SageObject: ...

class LieObject:
    def to_word(self) -> _SageObject: ...

class LieGenerator:
    def __init__(self, name: builtins.object, index: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def to_word(self) -> _SageObject: ...
    def lift(self, UEA_gens_dict: builtins.object) -> _SageObject: ...

class LieBracket:
    def __init__(self, l: builtins.object, r: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def lift(self, UEA_gens_dict: builtins.object) -> _SageObject: ...
    def to_word(self) -> _SageObject: ...

class GradedLieBracket:
    def __init__(self, l: builtins.object, r: builtins.object, grade: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...

class LyndonBracket:
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
