# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LieAlgebraHomomorphism_im_gens:
    def __init__(self, parent: builtins.object, im_gens: builtins.object, base_map: builtins.object = ..., check: builtins.bool = ...) -> None: ...
    def im_gens(self) -> _SageObject: ...
    def base_map(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...

class LieAlgebraHomset:
    def __init__(self, X: builtins.object, Y: builtins.object, category: builtins.object = ..., base: builtins.object = ..., check: builtins.bool = ...) -> None: ...
    def __call__(self, im_gens: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def zero(self) -> _SageObject: ...

class LieAlgebraMorphism_from_generators:
    def __init__(self, on_generators: builtins.object, domain: builtins.object = ..., codomain: builtins.object = ..., check: builtins.bool = ..., base_map: builtins.object = ..., category: builtins.object = ...) -> None: ...
