from sage.structure.element import Element

class NilpotentLieAlgebra_dense(LieAlgebraWithStructureCoefficients):
    def _repr_(self) -> str: ...

class FreeNilpotentLieAlgebra(NilpotentLieAlgebra_dense):
    def _repr_generator(self, w: Element, use_latex: Element | int | str | bool | None) -> str: ...
    def _latex_term(self, w: Element) -> str: ...
    def degree_on_basis(self, w: Element) -> int: ...

class LieAlgebraWithStructureCoefficients: ...
