# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class OnsagerAlgebra:
    def __init__(self, R: builtins.int) -> None: ...
    def basis(self) -> _SageObject: ...
    def lie_algebra_generators(self) -> _SageObject: ...
    def bracket_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def quantum_group(self, q: builtins.int = ..., c: builtins.object = ...) -> _SageObject: ...
    def alternating_central_extension(self) -> _SageObject: ...
    Element: _SageObject

class QuantumOnsagerAlgebra:
    def __init__(self, g: builtins.object, q: builtins.int, c: builtins.object) -> None: ...
    def lie_algebra(self) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    gens: _SageObject
    def q(self) -> _SageObject: ...
    def c(self) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
    def product_on_basis(self, lhs: builtins.object, rhs: builtins.object) -> _SageObject: ...

class OnsagerAlgebraACE:
    def __init__(self, R: builtins.int) -> None: ...
    def basis(self) -> _SageObject: ...
    def lie_algebra_generators(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def bracket_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def projection(self) -> _SageObject: ...
    Element: _SageObject
