from sage.rings.ring import Ring
from sage.structure.element import Element

class OnsagerAlgebra(LieAlgebraWithGenerators, IndexedGenerators):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _repr_generator(self, m: int) -> str: ...
    def _latex_generator(self, m: int) -> str: ...
    def basis(self) -> Element: ...
    def lie_algebra_generators(self) -> Element: ...
    def bracket_on_basis(self, x: Element, y: Element) -> Element: ...
    def _an_element_(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...
    def quantum_group(self, q: int, c: Element) -> Element: ...
    def alternating_central_extension(self) -> Element: ...

class QuantumOnsagerAlgebra(CombinatorialFreeModule):
    def _basis_key(self, k: int) -> Element: ...
    def _monoid_key(self, x: Element) -> Element: ...
    def _monomial_key(self, x: Element) -> Element: ...
    def _repr_term(self, m: int) -> str: ...
    def _latex_term(self, m: int) -> str: ...
    def lie_algebra(self) -> Element: ...
    def algebra_generators(self) -> Element: ...
    def q(self) -> Element: ...
    def c(self) -> Element: ...
    def one_basis(self) -> Element: ...
    def degree_on_basis(self, m: int) -> int: ...
    def product_on_basis(self, lhs: Element | int | str | bool | None, rhs: Element | int | str | bool | None) -> Element: ...

class OnsagerAlgebraACE(InfinitelyGeneratedLieAlgebra, IndexedGenerators):
    def _coerce_map_from_(self, R: Ring) -> Element: ...
    def _from_onsager_on_basis(self, x: Element) -> Element: ...
    def projection(self) -> Element: ...
    def _projection_on_basis(self, x: Element) -> Element: ...

class CombinatorialFreeModule: ...

class IndexedGenerators: ...

class InfinitelyGeneratedLieAlgebra: ...

class LieAlgebraWithGenerators: ...
