# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LieQuotient_finite_dimensional_with_basis:
    @staticmethod
    def __classcall_private__(cls: builtins.object, ambient: builtins.object, I: builtins.int, names: builtins.object = ..., index_set: builtins.object = ..., index_set_mapping: builtins.object = ..., category: builtins.object = ...) -> _SageObject: ...
    def __init__(self, L: builtins.object, I: builtins.int, names: builtins.object, index_set: builtins.object, index_set_mapping: builtins.object, category: builtins.object = ...) -> None: ...
    def ambient(self) -> _SageObject: ...
    def lift(self, X: builtins.object) -> _SageObject: ...
    def retract(self, X: builtins.object) -> _SageObject: ...
    def defining_ideal(self) -> _SageObject: ...
    def from_vector(self, v: builtins.object, order: builtins.object = ..., coerce: builtins.bool = ...) -> _SageObject: ...
