# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Representation_abstract:
    def __init__(self, lie_algebra: builtins.object) -> None: ...
    def lie_algebra(self) -> _SageObject: ...
    def side(self) -> _SageObject: ...
    def representation_matrix(self, elt: builtins.object) -> _SageObject: ...

class RepresentationByMorphism:
    @staticmethod
    def __classcall_private__(cls: builtins.object, lie_algebra: builtins.object, f: builtins.object = ..., index_set: builtins.object = ..., on_basis: builtins.bool = ..., **kwargs: builtins.object) -> _SageObject: ...
    def __init__(self, lie_algebra: builtins.object, f: builtins.object, index_set: builtins.object, on_basis: builtins.object, category: builtins.object, **kwargs: builtins.object) -> None: ...
    class Element:
        ...

class TrivialRepresentation:
    def __init__(self, lie_algebra: builtins.object, **kwargs: builtins.object) -> None: ...
    class Element:
        ...

class FaithfulRepresentationNilpotentPBW:
    def __init__(self, L: builtins.object, minimal: builtins.bool = ...) -> None: ...
    class Element:
        ...

class FaithfulRepresentationPBWPosChar:
    def __init__(self, L: builtins.object) -> None: ...
    def p_exponents(self) -> _SageObject: ...
    def groebner_basis(self) -> _SageObject: ...
    class Element:
        ...
