# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LieSubalgebra_finite_dimensional_with_basis:
    @staticmethod
    def __classcall_private__(cls: builtins.object, ambient: builtins.object, gens: builtins.object, ideal_of: builtins.object = ..., order: builtins.object = ..., category: builtins.object = ...) -> _SageObject: ...
    def __init__(self, ambient: builtins.object, gens: builtins.object, ideal_of: builtins.object, order: builtins.object = ..., category: builtins.object = ...) -> None: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def __getitem__(self, x: builtins.object) -> _SageObject: ...
    def indices(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def lift(self, X: builtins.object) -> _SageObject: ...
    def retract(self, X: builtins.object) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def lie_algebra_generators(self) -> _SageObject: ...
    def basis(self) -> _SageObject: ...
    def leading_monomials(self) -> _SageObject: ...
    def from_vector(self, v: builtins.object, order: builtins.object = ..., coerce: builtins.bool = ...) -> _SageObject: ...
    def basis_matrix(self) -> _SageObject: ...
    def module(self, sparse: builtins.bool = ...) -> _SageObject: ...
    def is_ideal(self, A: builtins.object) -> builtins.bool: ...
    class Element:
        def adjoint_matrix(self, sparse: builtins.bool = ...) -> _SageObject: ...
