from sage.structure.element import Element

class SymplecticDerivationLieAlgebra(InfinitelyGeneratedLieAlgebra, IndexedGenerators):
    def _basis_key(self, x: Element) -> Element: ...
    def _repr_term(self, m: int) -> str: ...
    def _latex_term(self, m: int) -> str: ...
    def _unicode_art_term(self, m: int) -> Element: ...
    def _repr_(self) -> str: ...
    def degree_on_basis(self, x: Element) -> int: ...
    def bracket_on_basis(self, x: Element, y: Element) -> Element: ...
    def _an_element_(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...

class IndexedGenerators: ...

class InfinitelyGeneratedLieAlgebra: ...
