from typing import Self

from sage.rings.ring import Ring
from sage.structure.element import Element

class ModulePrinting:
    def _repr_generator(self, m: int) -> str: ...
    def _latex_generator(self, m: int) -> str: ...

class VermaModule(ModulePrinting, CombinatorialFreeModule):
    def _triangular_key(self, x: Element) -> Element: ...
    def _monoid_key(self, x: Element) -> Element: ...
    def _monomial_key(self, x: Element) -> Element: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def lie_algebra(self) -> Element: ...
    def pbw_basis(self) -> Element: ...
    def highest_weight_vector(self) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def highest_weight(self) -> Element: ...
    def dual(self) -> Element: ...
    def degree_on_basis(self, m: int) -> int: ...
    def _coerce_map_from_(self, R: Ring) -> Element: ...
    def _element_constructor_(self, x: Element) -> Element: ...
    def contravariant_form(self, x: Element, y: Element) -> Element: ...
    def _dominant_data(self) -> Element: ...
    def is_singular(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def is_projective(self) -> bool: ...
    def homogeneous_component_basis(self, d: int) -> Element: ...
    def _homogeneous_component_f(self, d: int) -> Element: ...
    def _Hom_(self, Y: Element | int | str | bool | None, category: Element | int | str | bool | None) -> Element: ...

class VermaModuleMorphism(Morphism):
    def _repr_type(self) -> str: ...
    def _repr_defn(self) -> str: ...
    def _richcmp_(self, other: Element, op: Element | int | str | bool | None) -> Element: ...
    def _call_(self, x: Element) -> Element: ...
    def _on_basis(self, m: int) -> Element: ...
    def _add_(self, other: Element) -> Self: ...
    def _sub_(self, other: Element) -> Self: ...
    def _acted_upon_(self, other: Element, self_on_left: Element | int | str | bool | None) -> Element: ...
    def _composition_(self, right: Element | int | str | bool | None, homset: Element | int | str | bool | None) -> Element: ...
    def is_injective(self) -> bool: ...
    def is_surjective(self) -> bool: ...
    def image(self) -> Element: ...

class VermaModuleHomset(Homset):
    def _an_element_(self) -> Element: ...
    def highest_weight_image(self) -> Element: ...
    def singular_vector(self) -> Element: ...
    def natural_map(self) -> Element: ...
    def zero(self) -> Element: ...
    def dimension(self) -> int: ...
    def basis(self) -> Element: ...

class CombinatorialFreeModule: ...

class Homset: ...

class Morphism: ...
