import builtins

from sage.structure.element import Element

class _SageObject: ...

class ModulePrinting:
    def __init__(self, vector_name: builtins.str = ...) -> None: ...

class VermaModule:
    def __init__(
        self,
        g: builtins.object,
        weight: builtins.object,
        basis_key: builtins.object = ...,
        prefix: builtins.str = ...,
        **kwds: builtins.object,
    ) -> None: ...
    def lie_algebra(self) -> _SageObject: ...
    def pbw_basis(self) -> _SageObject: ...
    poincare_birkhoff_witt_basis: _SageObject

    def highest_weight_vector(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def highest_weight(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
    def contravariant_form(
        self, x: builtins.object, y: builtins.object
    ) -> _SageObject: ...
    def is_singular(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def is_projective(self) -> bool: ...
    def homogeneous_component_basis(self, d: builtins.object) -> _SageObject: ...
    weight_space_basis: _SageObject

    class Element: ...

class VermaModuleMorphism:
    def __init__(self, parent: builtins.object, scalar: builtins.object) -> None: ...
    def is_injective(self) -> bool: ...
    def is_surjective(self) -> bool: ...
    def image(self) -> _SageObject: ...

class VermaModuleHomset:
    def __call__(
        self, x: builtins.object, **options: builtins.object
    ) -> _SageObject: ...
    def highest_weight_image(self) -> _SageObject: ...
    def singular_vector(self) -> _SageObject: ...
    def natural_map(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def basis(self) -> _SageObject: ...
    Element: _SageObject
