import builtins

class _SageObject: ...

def lift_to_gamma1(self, m: builtins.int, n: builtins.int) -> _SageObject: ...
def lift_matrix_to_sl2z(self, N: builtins.int) -> _SageObject: ...
def lift_gen_to_gamma1(self, n: builtins.int) -> _SageObject: ...
def lift_uniformiser_odd(self, u: builtins.object, n: builtins.int) -> _SageObject: ...
def lift_ramified(
    self, p: builtins.int, u: builtins.object, n: builtins.int
) -> _SageObject: ...
def lift_for_SL(self, N: builtins.int = ...) -> _SageObject: ...
