# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def LocalComponent(f: builtins.object, p: builtins.int, twist_factor: builtins.object = ...) -> _SageObject: ...

class LocalComponentBase:
    def __init__(self, newform: builtins.object, prime: builtins.object, twist_factor: builtins.object) -> None: ...
    def species(self) -> _SageObject: ...
    def check_tempered(self) -> _SageObject: ...
    def newform(self) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def conductor(self) -> _SageObject: ...
    def coefficient_field(self) -> _SageObject: ...
    def twist_factor(self) -> _SageObject: ...
    def central_character(self) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...

class PrimitiveLocalComponent:
    def is_primitive(self) -> builtins.bool: ...
    def minimal_twist(self) -> Self: ...

class PrincipalSeries:
    def species(self) -> _SageObject: ...
    def check_tempered(self) -> _SageObject: ...
    def characters(self) -> _SageObject: ...

class UnramifiedPrincipalSeries:
    def satake_polynomial(self) -> _SageObject: ...
    def characters(self) -> _SageObject: ...

class PrimitivePrincipalSeries:
    def characters(self) -> _SageObject: ...

class PrimitiveSpecial:
    def species(self) -> _SageObject: ...
    def characters(self) -> _SageObject: ...
    def check_tempered(self) -> _SageObject: ...

class PrimitiveSupercuspidal:
    def species(self) -> _SageObject: ...
    def type_space(self) -> _SageObject: ...
    def characters(self) -> _SageObject: ...
    def check_tempered(self) -> _SageObject: ...

class ImprimitiveLocalComponent:
    def __init__(self, newform: builtins.object, prime: builtins.object, twist_factor: builtins.object, min_twist: builtins.object, chi: builtins.object) -> None: ...
    def is_primitive(self) -> builtins.bool: ...
    def minimal_twist(self) -> _SageObject: ...
    def twisting_character(self) -> _SageObject: ...
    def species(self) -> _SageObject: ...
    def characters(self) -> _SageObject: ...
    def check_tempered(self) -> _SageObject: ...
