# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeKnotInfoMonoidElement:
    def as_knot(self) -> _SageObject: ...
    def to_knotinfo(self) -> _SageObject: ...

class FreeKnotInfoMonoid:
    Element: _SageObject
    @staticmethod
    def __classcall_private__(cls: builtins.object, max_crossing_number: builtins.int = ..., prefix: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...
    def __init__(self, max_crossing_number: builtins.object, category: builtins.object = ..., prefix: builtins.str = ..., **kwds: builtins.object) -> None: ...
    def from_knot(self, knot: builtins.object, unique: builtins.bool = ...) -> _SageObject: ...
    def inject_variables(self, select: builtins.object = ..., verbose: builtins.bool = ...) -> _SageObject: ...
