# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def eval_knotinfo(string: builtins.object, locals: builtins.dict[_SageObject, _SageObject] = ..., to_tuple: builtins.bool = ...) -> _SageObject: ...

def knotinfo_int(string: builtins.object) -> _SageObject: ...

def knotinfo_bool(string: builtins.object) -> _SageObject: ...

class SymmetryMutant:
    itself: _SageObject
    reverse: _SageObject
    concordance_inverse: _SageObject
    mirror_image: _SageObject
    mixed: _SageObject
    unknown: _SageObject
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def rev(self) -> _SageObject: ...
    def mir(self) -> _SageObject: ...
    def matches(self, link: builtins.object) -> _SageObject: ...
    def is_minimal(self, link: builtins.object) -> builtins.bool: ...

class KnotInfoBase:
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    @property
    def items(self) -> _SageObject: ...
    def __getitem__(self, item: builtins.object) -> _SageObject: ...
    def pd_notation(self, original: builtins.bool = ...) -> _SageObject: ...
    def dt_notation(self, original: builtins.bool = ...) -> _SageObject: ...
    def gauss_notation(self, original: builtins.bool = ...) -> _SageObject: ...
    def braid_notation(self, original: builtins.bool = ...) -> _SageObject: ...
    def braid_index(self) -> _SageObject: ...
    def braid_length(self) -> _SageObject: ...
    def braid(self) -> _SageObject: ...
    def num_components(self) -> _SageObject: ...
    def crossing_number(self) -> _SageObject: ...
    def determinant(self) -> _SageObject: ...
    def three_genus(self) -> _SageObject: ...
    def signature(self) -> _SageObject: ...
    def is_knot(self) -> builtins.bool: ...
    def name_unoriented(self) -> _SageObject: ...
    def symmetry_type(self) -> _SageObject: ...
    def is_reversible(self) -> builtins.bool: ...
    def is_amphicheiral(self, positive: builtins.bool = ...) -> builtins.bool: ...
    def is_hyperbolic(self) -> builtins.bool: ...
    def is_alternating(self) -> builtins.bool: ...
    def is_almost_alternating(self) -> builtins.bool: ...
    def is_quasi_alternating(self) -> builtins.bool: ...
    def is_adequate(self) -> builtins.bool: ...
    def is_positive(self) -> builtins.bool: ...
    def is_quasipositive(self) -> builtins.bool: ...
    def is_strongly_quasipositive(self) -> builtins.bool: ...
    def is_positive_braid(self) -> builtins.bool: ...
    def is_fibered(self) -> builtins.bool: ...
    def is_oriented(self) -> builtins.bool: ...
    def cosmetic_crossing_conjecture_verified(self) -> _SageObject: ...
    def homfly_polynomial(self, var1: builtins.str = ..., var2: builtins.str = ..., original: builtins.bool = ...) -> _SageObject: ...
    def kauffman_polynomial(self, var1: builtins.str = ..., var2: builtins.str = ..., original: builtins.bool = ...) -> _SageObject: ...
    def jones_polynomial(self, variab: builtins.object = ..., skein_normalization: builtins.bool = ..., puiseux: builtins.bool = ..., original: builtins.bool = ..., use_sqrt: builtins.bool = ...) -> _SageObject: ...
    def alexander_polynomial(self, var: builtins.str = ..., original: builtins.bool = ..., laurent_poly: builtins.bool = ...) -> _SageObject: ...
    def conway_polynomial(self, var: builtins.str = ..., original: builtins.bool = ...) -> _SageObject: ...
    def khovanov_polynomial(self, var1: builtins.str = ..., var2: builtins.str = ..., torsion: builtins.str = ..., ring: builtins.object = ..., original: builtins.bool = ..., reduced: builtins.bool = ..., odd: builtins.bool = ..., base_ring: builtins.object = ...) -> _SageObject: ...
    def link(self, use_item: builtins.object = ..., snappy: builtins.bool = ...) -> _SageObject: ...
    def is_unique(self) -> builtins.bool: ...
    def is_recoverable(self, unique: builtins.bool = ...) -> builtins.bool: ...
    def inject(self, verbose: builtins.bool = ...) -> _SageObject: ...
    def series(self, oriented: builtins.bool = ...) -> _SageObject: ...
    def diagram(self, single: builtins.bool = ..., new: builtins.int = ..., autoraise: builtins.bool = ...) -> _SageObject: ...
    def knot_atlas_webpage(self, new: builtins.int = ..., autoraise: builtins.bool = ...) -> _SageObject: ...
    def knotilus_webpage(self, new: builtins.int = ..., autoraise: builtins.bool = ...) -> _SageObject: ...

class KnotInfoSeries:
    def __init__(self, crossing_number: builtins.object, is_knot: builtins.object, is_alternating: builtins.object, name_unoriented: builtins.object = ...) -> None: ...
    def list(self, oriented: builtins.bool = ..., comp: builtins.object = ..., det: builtins.object = ..., homfly: builtins.object = ...) -> _SageObject: ...
    def lower_list(self, oriented: builtins.bool = ..., comp: builtins.object = ..., det: builtins.object = ..., homfly: builtins.object = ...) -> _SageObject: ...
    def __getitem__(self, item: builtins.object) -> _SageObject: ...
    def __call__(self, item: builtins.object) -> _SageObject: ...
    def is_recoverable(self, unique: builtins.bool = ..., max_samples: builtins.int = ...) -> builtins.bool: ...
    def inject(self, verbose: builtins.bool = ...) -> _SageObject: ...

KnotInfo: _SageObject
