# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Link:
    def __init__(self, data: builtins.object) -> None: ...
    def arcs(self, presentation: builtins.str = ...) -> _SageObject: ...
    def fundamental_group(self, presentation: builtins.str = ..., algorithm: builtins.str = ...) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def braid(self, remove_loops: builtins.bool = ...) -> _SageObject: ...
    def khovanov_homology(self, ring: builtins.object = ..., height: builtins.object = ..., degree: builtins.int = ..., implementation: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...
    def oriented_gauss_code(self) -> _SageObject: ...
    def pd_code(self) -> _SageObject: ...
    def gauss_code(self) -> _SageObject: ...
    def dowker_notation(self) -> _SageObject: ...
    def seifert_matrix(self) -> _SageObject: ...
    def number_of_components(self) -> _SageObject: ...
    def is_knot(self) -> builtins.bool: ...
    def genus(self) -> _SageObject: ...
    def signature(self) -> _SageObject: ...
    def omega_signature(self, omega: builtins.object) -> _SageObject: ...
    def alexander_polynomial(self, var: builtins.str = ...) -> _SageObject: ...
    def conway_polynomial(self) -> _SageObject: ...
    def khovanov_polynomial(self, var1: builtins.str = ..., var2: builtins.str = ..., torsion: builtins.str = ..., ring: builtins.object = ..., base_ring: builtins.object = ..., implementation: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...
    def determinant(self) -> _SageObject: ...
    def is_alternating(self) -> builtins.bool: ...
    def orientation(self) -> _SageObject: ...
    def seifert_circles(self) -> _SageObject: ...
    def regions(self) -> _SageObject: ...
    def remove_loops(self) -> _SageObject: ...
    def mirror_image(self) -> _SageObject: ...
    def reverse(self) -> _SageObject: ...
    def writhe(self) -> _SageObject: ...
    def jones_polynomial(self, variab: builtins.object = ..., skein_normalization: builtins.bool = ..., algorithm: builtins.str = ...) -> _SageObject: ...
    def homfly_polynomial(self, var1: builtins.object = ..., var2: builtins.object = ..., normalization: builtins.str = ..., algorithm: builtins.str = ...) -> _SageObject: ...
    def links_gould_polynomial(self, varnames: builtins.str = ...) -> _SageObject: ...
    def is_colorable(self, n: builtins.int = ...) -> builtins.bool: ...
    def colorings(self, n: builtins.int = ...) -> _SageObject: ...
    def coloring_maps(self, n: builtins.int = ..., finitely_presented: builtins.bool = ...) -> _SageObject: ...
    def plot(self, gap: builtins.float = ..., component_gap: builtins.float = ..., solver: builtins.object = ..., color: builtins.str = ..., **kwargs: builtins.object) -> _SageObject: ...
    def get_knotinfo(self, mirror_version: builtins.bool = ..., unique: builtins.bool = ...) -> _SageObject: ...
    def is_isotopic(self, other: builtins.object) -> builtins.bool: ...
    def simplify(self, exhaustive: builtins.bool = ..., height: builtins.int = ..., threads: builtins.int = ...) -> _SageObject: ...
