import builtins
from collections.abc import (
    Iterator,
)

class _SageObject: ...

def OverconvergentModularForms(
    self,
    weight: builtins.object,
    radius: builtins.object,
    base_ring: builtins.object = ...,
    prec: builtins.int = ...,
    char: builtins.object = ...,
) -> _SageObject: ...

class OverconvergentModularFormsSpace:
    def __init__(
        self,
        prime: builtins.object,
        weight: builtins.object,
        radius: builtins.object,
        base_ring: builtins.object,
        prec: builtins.int,
        char: builtins.object,
    ) -> None: ...
    def is_exact(self) -> bool: ...
    def change_ring(self, ring: builtins.object) -> _SageObject: ...
    def base_extend(self, ring: builtins.object) -> _SageObject: ...
    def character(self) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def normalising_factor(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def radius(self) -> _SageObject: ...
    def gens(self) -> Iterator: ...
    def prec(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def coordinate_vector(self, x: builtins.object) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def hecke_operator(self, f: builtins.object, m: builtins.int) -> _SageObject: ...
    def hecke_matrix(
        self,
        m: builtins.int,
        n: builtins.int,
        use_recurrence: builtins.bool = ...,
        exact_arith: builtins.bool = ...,
        side: builtins.str = ...,
    ) -> _SageObject: ...
    def slopes(
        self, n: builtins.int, use_recurrence: builtins.bool = ...
    ) -> _SageObject: ...
    def eigenfunctions(
        self,
        n: builtins.int,
        F: builtins.object = ...,
        exact_arith: builtins.bool = ...,
    ) -> _SageObject: ...
    def recurrence_matrix(self, use_smithline: builtins.bool = ...) -> _SageObject: ...
    def cps_u(
        self, n: builtins.int, use_recurrence: builtins.bool = ...
    ) -> _SageObject: ...

class OverconvergentModularFormElement:
    def __init__(
        self,
        parent: builtins.object,
        gexp: builtins.object = ...,
        qexp: builtins.object = ...,
    ) -> None: ...
    def prec(self) -> _SageObject: ...
    def is_eigenform(self) -> bool: ...
    def slope(self) -> _SageObject: ...
    def eigenvalue(self) -> _SageObject: ...
    def q_expansion(self, prec: builtins.int = ...) -> _SageObject: ...
    def gexp(self) -> _SageObject: ...
    def coordinates(self, prec: builtins.int = ...) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def is_integral(self) -> bool: ...
    def r_ord(self, r: builtins.int) -> _SageObject: ...
    def valuation(self) -> _SageObject: ...
    def governing_term(self, r: builtins.int) -> _SageObject: ...
    def valuation_plot(self, rmax: builtins.object = ...) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def additive_order(self) -> _SageObject: ...
    def base_extend(self, R: builtins.int) -> _SageObject: ...
    def __pari__(self) -> _SageObject: ...
