# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def compute_G(p: builtins.int, F: builtins.object) -> _SageObject: ...

def low_weight_bases(N: builtins.int, p: builtins.int, m: builtins.int, NN: builtins.object, weightbound: builtins.object) -> _SageObject: ...

def random_low_weight_bases(N: builtins.int, p: builtins.int, m: builtins.int, NN: builtins.object, weightbound: builtins.object) -> _SageObject: ...

def low_weight_generators(N: builtins.int, p: builtins.int, m: builtins.int, NN: builtins.object) -> _SageObject: ...

def random_solution(B: builtins.object, K: builtins.int) -> _SageObject: ...

def ech_form(A: builtins.object, p: builtins.int) -> _SageObject: ...

def random_new_basis_modp(N: builtins.int, p: builtins.int, k: builtins.int, LWBModp: builtins.object, TotalBasisModp: builtins.object, elldash: builtins.object, bound: builtins.object) -> _SageObject: ...

def complementary_spaces_modp(N: builtins.int, p: builtins.int, k0: builtins.object, n: builtins.int, elldash: builtins.object, LWBModp: builtins.object, bound: builtins.object) -> _SageObject: ...

def complementary_spaces(N: builtins.int, p: builtins.int, k0: builtins.object, n: builtins.int, mdash: builtins.object, elldashp: builtins.object, elldash: builtins.object, modformsring: builtins.object, bound: builtins.object) -> _SageObject: ...

def higher_level_katz_exp(p: builtins.int, N: builtins.int, k0: builtins.object, m: builtins.int, mdash: builtins.object, elldash: builtins.object, elldashp: builtins.object, modformsring: builtins.object, bound: builtins.object) -> _SageObject: ...

def compute_elldash(p: builtins.int, N: builtins.int, k0: builtins.object, n: builtins.int) -> _SageObject: ...

def hecke_series_degree_bound(p: builtins.int, N: builtins.int, k: builtins.int, m: builtins.int) -> _SageObject: ...

def higher_level_UpGj(p: builtins.int, N: builtins.int, klist: builtins.object, m: builtins.int, modformsring: builtins.object, bound: builtins.object, extra_data: builtins.bool = ...) -> _SageObject: ...

def compute_Wi(k: builtins.int, p: builtins.int, h: builtins.object, hj: builtins.object, E4: builtins.object, E6: builtins.object) -> _SageObject: ...

def katz_expansions(k0: builtins.object, p: builtins.int, ellp: builtins.object, mdash: builtins.object, n: builtins.int) -> _SageObject: ...

def level1_UpGj(p: builtins.int, klist: builtins.object, m: builtins.int, extra_data: builtins.bool = ...) -> _SageObject: ...

def is_valid_weight_list(klist: builtins.object, p: builtins.int) -> None: ...

def hecke_series(p: builtins.int, N: builtins.int, klist: builtins.object, m: builtins.int, modformsring: builtins.bool = ..., weightbound: builtins.int = ...) -> _SageObject: ...
