import builtins

class _SageObject: ...

def WeightSpace_constructor(self, base_ring: builtins.object = ...) -> _SageObject: ...

class WeightSpace_class:
    def __init__(self, p: builtins.int, base_ring: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def zero(self) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def base_extend(self, R: builtins.int) -> _SageObject: ...

class WeightCharacter:
    def __init__(self, parent: builtins.object) -> None: ...
    def base_extend(self, R: builtins.int) -> _SageObject: ...
    def is_even(self) -> bool: ...
    def pAdicEisensteinSeries(
        self, ring: builtins.object, prec: builtins.int = ...
    ) -> _SageObject: ...
    def values_on_gens(self) -> _SageObject: ...
    def is_trivial(self) -> bool: ...
    def Lvalue(self) -> _SageObject: ...
    def one_over_Lvalue(self) -> _SageObject: ...

class AlgebraicWeight:
    def __init__(
        self, parent: builtins.object, k: builtins.int, chi: builtins.object = ...
    ) -> None: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def k(self) -> _SageObject: ...
    def chi(self) -> _SageObject: ...
    def __hash__(self) -> int: ...
    def teichmuller_type(self) -> _SageObject: ...
    def Lvalue(self) -> _SageObject: ...

class ArbitraryWeight:
    def __init__(
        self, parent: builtins.object, w: builtins.object, t: builtins.object
    ) -> None: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def teichmuller_type(self) -> _SageObject: ...
