# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LimitValuationFactory:
    def create_key(self, base_valuation: builtins.object, G: builtins.object) -> _SageObject: ...
    def create_object(self, version: builtins.object, key: builtins.object) -> _SageObject: ...

LimitValuation: _SageObject
class LimitValuation_generic:
    def __init__(self, parent: builtins.object, approximation: builtins.object) -> None: ...
    def reduce(self, f: builtins.object, check: builtins.bool = ...) -> _SageObject: ...

class MacLaneLimitValuation:
    def __init__(self, parent: builtins.object, approximation: builtins.object, G: builtins.object) -> None: ...
    def extensions(self, ring: builtins.object) -> _SageObject: ...
    def lift(self, F: builtins.object) -> _SageObject: ...
    def uniformizer(self) -> _SageObject: ...
    def residue_ring(self) -> _SageObject: ...
    def restriction(self, ring: builtins.object) -> _SageObject: ...
    def value_semigroup(self) -> _SageObject: ...
    def element_with_valuation(self, s: builtins.object) -> _SageObject: ...
    def simplify(self, f: builtins.object, error: builtins.object = ..., force: builtins.bool = ...) -> _SageObject: ...
    def lower_bound(self, f: builtins.object) -> _SageObject: ...
    def upper_bound(self, f: builtins.object) -> _SageObject: ...
    def is_negative_pseudo_valuation(self) -> builtins.bool: ...
