# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MappedValuation_base:
    def __init__(self, parent: builtins.object, base_valuation: builtins.object) -> None: ...
    def residue_ring(self) -> _SageObject: ...
    def uniformizer(self) -> _SageObject: ...
    def reduce(self, f: builtins.object) -> _SageObject: ...
    def lift(self, F: builtins.object) -> _SageObject: ...
    def simplify(self, x: builtins.object, error: builtins.object = ..., force: builtins.bool = ...) -> _SageObject: ...
    def element_with_valuation(self, s: builtins.object) -> _SageObject: ...

class FiniteExtensionFromInfiniteValuation:
    def __init__(self, parent: builtins.object, base_valuation: builtins.object) -> None: ...
    def restriction(self, ring: builtins.object) -> _SageObject: ...
    def simplify(self, x: builtins.object, error: builtins.object = ..., force: builtins.bool = ...) -> _SageObject: ...
    def lower_bound(self, x: builtins.object) -> _SageObject: ...
    def upper_bound(self, x: builtins.object) -> _SageObject: ...

class FiniteExtensionFromLimitValuation:
    def __init__(self, parent: builtins.object, approximant: builtins.object, G: builtins.object, approximants: builtins.object) -> None: ...
