from typing import Never

from sage.rings.infinity import PlusInfinity
from sage.rings.rational import Rational
from sage.rings.valuation.valuation import (
    DiscretePseudoValuation,
    DiscreteValuation,
    InfiniteDiscretePseudoValuation,
)
from sage.rings.valuation.valuation_space import DiscretePseudoValuationSpace
from sage.rings.valuation.value_group import DiscreteValueGroup
from sage.structure.element import RingElement
from sage.structure.factory import FactoryArgument, FactoryVersion, UniqueFactory
from sage.structure.parent import ElementConstructorInput, Parent

type RingParent = Parent[RingElement]

class TrivialValuationFactory(UniqueFactory):
    def __init__(
        self,
        clazz: type[DiscretePseudoValuation],
        parent: type[DiscretePseudoValuationSpace],
        name: str,
    ) -> None: ...
    def __call__(self, domain: RingParent) -> DiscretePseudoValuation: ...
    def create_key(self, domain: RingParent) -> tuple[RingParent]: ...
    def create_object(
        self,
        version: FactoryVersion,
        key: tuple[RingParent],
        **extra_args: FactoryArgument,
    ) -> DiscretePseudoValuation: ...

class TrivialDiscretePseudoValuation_base(DiscretePseudoValuation):
    def uniformizer(self) -> Never: ...
    def is_trivial(self) -> bool: ...
    def is_negative_pseudo_valuation(self) -> bool: ...

class TrivialDiscretePseudoValuation(
    TrivialDiscretePseudoValuation_base,
    InfiniteDiscretePseudoValuation,
):
    def __init__(self, parent: DiscretePseudoValuationSpace) -> None: ...
    def _call_(self, x: RingElement) -> PlusInfinity: ...
    def _repr_(self) -> str: ...
    def value_group(self) -> Never: ...
    def residue_ring(self) -> RingParent: ...
    def reduce(self, x: ElementConstructorInput) -> RingElement: ...
    def lift(self, X: ElementConstructorInput) -> RingElement: ...
    def _ge_(self, other: DiscretePseudoValuation) -> bool: ...

class TrivialDiscreteValuation(
    TrivialDiscretePseudoValuation_base,
    DiscreteValuation,
):
    def __init__(self, parent: DiscretePseudoValuationSpace) -> None: ...
    def _call_(self, x: RingElement) -> Rational | PlusInfinity: ...
    def _repr_(self) -> str: ...
    def value_group(self) -> DiscreteValueGroup: ...
    def residue_ring(self) -> RingParent: ...
    def reduce(self, x: ElementConstructorInput) -> RingElement: ...
    def lift(self, X: ElementConstructorInput) -> RingElement: ...
    def extensions(self, ring: RingParent) -> list[DiscretePseudoValuation]: ...
    def _ge_(self, other: DiscretePseudoValuation) -> bool: ...

TrivialValuation: TrivialValuationFactory
TrivialPseudoValuation: TrivialValuationFactory
