from sage.categories.morphism import Morphism
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import InfinityElement, RingElement
from sage.structure.factorization import Factorization

class DiscretePseudoValuation(Morphism):
    def __init__(self, parent: Morphism) -> None: ...
    def is_equivalent(self, f: RingElement | int, g: RingElement | int) -> bool: ...
    def __hash__(self) -> int: ...
    def _hash_(self) -> int: ...
    def _richcmp_(self, other: DiscretePseudoValuation, op: int) -> bool: ...
    def _eq_(self, other: DiscretePseudoValuation) -> bool: ...
    def _le_(self, other: DiscretePseudoValuation) -> bool: ...
    def _ge_(self, other: DiscretePseudoValuation) -> bool: ...

class InfiniteDiscretePseudoValuation(DiscretePseudoValuation):
    def is_discrete_valuation(self) -> bool: ...

class NegativeInfiniteDiscretePseudoValuation(InfiniteDiscretePseudoValuation):
    def is_negative_pseudo_valuation(self) -> bool: ...

class DiscreteValuation(DiscretePseudoValuation):
    def is_discrete_valuation(self) -> bool: ...
    def mac_lane_approximants(self, G: Polynomial, assume_squarefree: bool = ..., require_final_EF: bool = ..., required_precision: int | Integer | InfinityElement = ..., require_incomparability: bool = ..., require_maximal_degree: bool = ..., algorithm: str = ...) -> list[DiscreteValuation]: ...
    def mac_lane_approximant(self, G: Polynomial, valuation: DiscreteValuation, approximants: list[DiscreteValuation] | None = None) -> DiscreteValuation: ...
    def montes_factorization(self, G: Polynomial, assume_squarefree: bool = ..., required_precision: int | Integer | InfinityElement | None = None) -> Factorization: ...
    def _ge_(self, other: DiscretePseudoValuation) -> bool: ...

class MacLaneApproximantNode:
    valuation: DiscreteValuation
    parent: MacLaneApproximantNode | None
    ef: bool
    principal_part_bound: int | None
    coefficients: list[RingElement] | None
    valuations: list[RingElement | Integer | InfinityElement] | None
    forced_leaf: bool
    def __init__(self, valuation: DiscreteValuation, parent: MacLaneApproximantNode | None, ef: bool, principal_part_bound: int | None, coefficients: list[RingElement] | None, valuations: list[RingElement | Integer | InfinityElement] | None) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
