import builtins

class _SageObject: ...

class DiscretePseudoValuationSpace:
    def __init__(self, domain: builtins.object) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...

    class ElementMethods:
        def is_discrete_pseudo_valuation(self) -> builtins.bool: ...
        def is_discrete_valuation(self) -> builtins.bool: ...
        def is_negative_pseudo_valuation(self) -> builtins.bool: ...
        def is_trivial(self) -> builtins.bool: ...
        def uniformizer(self) -> _SageObject: ...
        def value_group(self) -> _SageObject: ...
        def value_semigroup(self) -> _SageObject: ...
        def element_with_valuation(self, s: builtins.object) -> _SageObject: ...
        def residue_ring(self) -> _SageObject: ...
        def residue_field(self) -> _SageObject: ...
        def reduce(self, x: builtins.object) -> _SageObject: ...
        def lift(self, X: builtins.object) -> _SageObject: ...
        def extension(self, ring: builtins.object) -> _SageObject: ...
        def extensions(self, ring: builtins.object) -> _SageObject: ...
        def restriction(self, ring: builtins.object) -> _SageObject: ...
        def change_domain(self, ring: builtins.object) -> _SageObject: ...
        def scale(self, scalar: builtins.object) -> _SageObject: ...
        def separating_element(self, others: builtins.object) -> _SageObject: ...
        def shift(self, x: builtins.object, s: builtins.object) -> _SageObject: ...
        def simplify(
            self,
            x: builtins.object,
            error: builtins.object = ...,
            force: builtins.bool = ...,
        ) -> _SageObject: ...
        def lower_bound(self, x: builtins.object) -> _SageObject: ...
        def upper_bound(self, x: builtins.object) -> _SageObject: ...
        def inverse(
            self, x: builtins.object, precision: builtins.int
        ) -> _SageObject: ...

class ScaleAction: ...
