from collections.abc import Callable, Iterable

from sage.categories.action import Action
from sage.categories.homset import Homset
from sage.rings.infinity import MinusInfinity, PlusInfinity
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.valuation.valuation import DiscretePseudoValuation
from sage.rings.valuation.value_group import (
    DiscreteValuationCodomain,
    DiscreteValueGroup,
    DiscreteValueSemigroup,
    ValuationValue,
)
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject
from sage.structure.unique_representation import UniqueRepresentation

type ValuationScalar = int | Integer | Rational | PlusInfinity | MinusInfinity
type RingParent = Parent[RingElement]
type ValuationOperation = Callable[
    [ElementConstructorInput, ElementConstructorInput], ElementConstructorInput
]

class DiscretePseudoValuationSpace(
    UniqueRepresentation,
    Homset[DiscretePseudoValuation, RingElement, ValuationValue],
):
    def __init__(self, domain: RingParent) -> None: ...
    def _get_action_(
        self,
        S: Parent,
        op: ValuationOperation,
        self_on_left: bool,
    ) -> ScaleAction | None: ...
    def _an_element_(self) -> DiscretePseudoValuation: ...
    def _repr_(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def __call__(self, x: DiscretePseudoValuation) -> DiscretePseudoValuation: ...
    def _element_constructor_(
        self,
        x: DiscretePseudoValuation,
    ) -> DiscretePseudoValuation: ...
    def codomain(self) -> DiscreteValuationCodomain: ...
    def domain(self) -> RingParent: ...

    class ElementMethods(SageObject):
        def is_discrete_pseudo_valuation(self) -> bool: ...
        def is_discrete_valuation(self) -> bool: ...
        def is_negative_pseudo_valuation(self) -> bool: ...
        def is_trivial(self) -> bool: ...
        def uniformizer(self) -> RingElement: ...
        def value_group(self) -> DiscreteValueGroup: ...
        def value_semigroup(self) -> DiscreteValueSemigroup: ...
        def element_with_valuation(self, s: ValuationScalar) -> RingElement: ...
        def residue_ring(self) -> RingParent: ...
        def residue_field(self) -> RingParent: ...
        def reduce(self, x: ElementConstructorInput) -> RingElement: ...
        def lift(self, X: ElementConstructorInput) -> RingElement: ...
        def extension(self, ring: RingParent) -> DiscretePseudoValuation: ...
        def extensions(self, ring: RingParent) -> list[DiscretePseudoValuation]: ...
        def restriction(self, ring: RingParent) -> DiscretePseudoValuation: ...
        def change_domain(self, ring: RingParent) -> DiscretePseudoValuation: ...
        def scale(self, scalar: ValuationScalar) -> DiscretePseudoValuation: ...
        def separating_element(
            self,
            others: Iterable[DiscretePseudoValuation],
        ) -> RingElement: ...
        def _strictly_separating_element(
            self,
            other: DiscretePseudoValuation,
        ) -> RingElement: ...
        def _weakly_separating_element(
            self,
            other: DiscretePseudoValuation,
        ) -> RingElement: ...
        def shift(
            self, x: ElementConstructorInput, s: ValuationScalar
        ) -> RingElement: ...
        def simplify(
            self,
            x: ElementConstructorInput,
            error: ValuationScalar | None = ...,
            force: bool = ...,
        ) -> RingElement: ...
        def lower_bound(self, x: ElementConstructorInput) -> ValuationValue: ...
        def upper_bound(self, x: ElementConstructorInput) -> ValuationValue: ...
        def inverse(
            self,
            x: ElementConstructorInput,
            precision: ValuationScalar,
        ) -> RingElement: ...
        def _relative_size(self, x: ElementConstructorInput) -> float: ...

class ScaleAction(Action):
    def _act_(
        self,
        s: ValuationScalar,
        v: DiscretePseudoValuation,
    ) -> DiscretePseudoValuation: ...
