import builtins
from typing import Self

from sage.structure.element import Element

class _SageObject: ...

class DiscreteValuationCodomain:
    def __init__(self) -> None: ...

class DiscreteValueGroup:
    @staticmethod
    def __classcall__(
        cls: builtins.object, generator: builtins.object
    ) -> _SageObject: ...
    def __init__(self, generator: builtins.object) -> None: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def index(self, other: builtins.object) -> _SageObject: ...
    def numerator(self) -> _SageObject: ...
    def denominator(self) -> _SageObject: ...
    def gen(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def is_trivial(self) -> builtins.bool: ...

class DiscreteValueSemigroup:
    @staticmethod
    def __classcall__(
        cls: builtins.object, generators: builtins.object
    ) -> _SageObject: ...
    def __init__(self, generators: builtins.object) -> None: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def gens(self) -> tuple[Element, ...]: ...
    def some_elements(self) -> _SageObject: ...
    def is_trivial(self) -> builtins.bool: ...
    def is_group(self) -> builtins.bool: ...
