# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DiscreteValuationCodomain:
    def __init__(self) -> None: ...

class DiscreteValueGroup:
    @staticmethod
    def __classcall__(cls: builtins.object, generator: builtins.object) -> _SageObject: ...
    def __init__(self, generator: builtins.object) -> None: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def index(self, other: builtins.object) -> _SageObject: ...
    def numerator(self) -> _SageObject: ...
    def denominator(self) -> _SageObject: ...
    def gen(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def is_trivial(self) -> builtins.bool: ...

class DiscreteValueSemigroup:
    @staticmethod
    def __classcall__(cls: builtins.object, generators: builtins.object) -> _SageObject: ...
    def __init__(self, generators: builtins.object) -> None: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def some_elements(self) -> _SageObject: ...
    def is_trivial(self) -> builtins.bool: ...
    def is_group(self) -> builtins.bool: ...
