# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AskeyWilsonAlgebra:
    @staticmethod
    def __classcall_private__(cls: builtins.object, R: builtins.int, q: builtins.int = ...) -> _SageObject: ...
    def __init__(self, R: builtins.int, q: builtins.int) -> None: ...
    def algebra_generators(self) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def one_basis(self) -> _SageObject: ...
    def q(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def casimir_element(self) -> _SageObject: ...
    def product_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def permutation_automorphism(self) -> _SageObject: ...
    rho: _SageObject
    def reflection_automorphism(self) -> _SageObject: ...
    sigma: _SageObject
    def loop_representation(self) -> _SageObject: ...
    pi: _SageObject

class AlgebraMorphism:
    def __init__(self, domain: builtins.object, on_generators: builtins.object, position: builtins.int = ..., codomain: builtins.object = ..., category: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
