from sage.structure.element import Element

class AskeyWilsonAlgebra(CombinatorialFreeModule):
    def _repr_term(self, t: Element | int | str | bool | None) -> str: ...
    def _latex_term(self, t: Element | int | str | bool | None) -> str: ...
    def _repr_(self) -> str: ...
    def algebra_generators(self) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def one_basis(self) -> Element: ...
    def q(self) -> Element: ...
    def _an_element_(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...
    def casimir_element(self) -> Element: ...
    def product_on_basis(self, x: Element, y: Element) -> Element: ...
    def permutation_automorphism(self) -> Element: ...
    def reflection_automorphism(self) -> Element: ...
    def loop_representation(self) -> Element: ...

class AlgebraMorphism(ModuleMorphismByLinearity):
    def _on_basis(self, c: Element) -> Element: ...
    def _composition_(self, right: Element | int | str | bool | None, homset: Element | int | str | bool | None) -> Element: ...

class CombinatorialFreeModule: ...

class ModuleMorphismByLinearity: ...
