# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AssociatedGradedAlgebra:
    def __init__(self, A: builtins.object, category: builtins.object = ...) -> None: ...
    def gen(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    def degree_on_basis(self, x: builtins.object) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def product_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
