from sage.structure.element import Element

type _BuiltinList[_T] = list[_T]
class CliffordAlgebraElement(IndexedFreeModuleElement):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def list(self) -> _BuiltinList[Element]: ...
    def support(self) -> Element: ...
    def reflection(self) -> Element: ...
    def transpose(self) -> Element: ...
    def conjugate(self) -> Element: ...

class ExteriorAlgebraElement(CliffordAlgebraElement):
    def reduce(self, I: Element | int | str | bool | None, left: Element | int | str | bool | None) -> Element: ...
    def interior_product(self, x: Element) -> Element: ...
    def hodge_dual(self) -> Element: ...
    def constant_coefficient(self) -> Element: ...
    def scalar(self, other: Element) -> Element: ...

class CohomologyRAAGElement(CliffordAlgebraElement):
    ...

class IndexedFreeModuleElement: ...
