from typing import Self

from sage.data_structures.bitset import FrozenBitset
from sage.modules.with_basis.indexed_element import IndexedFreeModuleElement
from sage.rings.ideal import Ideal_generic
from sage.structure.element import Element

type CliffordTermList = list[tuple[FrozenBitset, Element]]
type CliffordSupport = list[FrozenBitset]

class CliffordAlgebraElement(IndexedFreeModuleElement):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _mul_(self, other: Self) -> Self: ...
    def _mul_self_term(self, supp: FrozenBitset, coeff: Element) -> Self: ...
    def _mul_term_self(self, supp: FrozenBitset, coeff: Element) -> Self: ...
    def list(self) -> CliffordTermList: ...
    def support(self) -> CliffordSupport: ...
    def reflection(self) -> CliffordAlgebraElement: ...
    degree_negation = reflection

    def transpose(self) -> CliffordAlgebraElement: ...
    def conjugate(self) -> CliffordAlgebraElement: ...
    clifford_conjugate = conjugate

class ExteriorAlgebraElement(CliffordAlgebraElement):
    def _mul_(self, other: Self) -> Self: ...
    def _mul_self_term(self, supp: FrozenBitset, coeff: Element) -> Self: ...
    def _mul_term_self(self, supp: FrozenBitset, coeff: Element) -> Self: ...
    def reduce(self, I: Ideal_generic, left: bool = True) -> Self: ...
    def interior_product(self, x: ExteriorAlgebraElement) -> Self: ...
    antiderivation = interior_product

    def hodge_dual(self) -> ExteriorAlgebraElement: ...
    def constant_coefficient(self) -> Element: ...
    def scalar(self, other: ExteriorAlgebraElement) -> Element: ...

class CohomologyRAAGElement(CliffordAlgebraElement):
    def _mul_(self, other: Self) -> Self: ...
import builtins
