from typing import Self

from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject

class ClusterAlgebraElement(ElementWrapper):
    def _add_(self, other: Element) -> Self: ...
    def _neg_(self) -> Self: ...
    def _div_(self, other: Element) -> Self: ...
    def d_vector(self) -> tuple[Element, ...]: ...
    def _repr_(self) -> str: ...

class PrincipalClusterAlgebraElement(ClusterAlgebraElement):
    def g_vector(self) -> Element: ...
    def F_polynomial(self) -> Element: ...
    def is_homogeneous(self) -> bool: ...
    def homogeneous_components(self) -> dict[Element, Element]: ...
    def theta_basis_decomposition(self) -> Element: ...

class ClusterAlgebraSeed(SageObject):
    def __hash__(self) -> int: ...
    def depth(self) -> int: ...
    def path_from_initial_seed(self) -> list[Element]: ...
    def b_matrix(self) -> Element: ...
    def c_matrix(self) -> Element: ...
    def c_vector(self, j: int) -> tuple[Element, ...]: ...
    def c_vectors(self) -> list[tuple[Element, ...]]: ...
    def g_matrix(self) -> Element: ...
    def g_vectors(self) -> list[tuple[Element, ...]]: ...
    def F_polynomials(self) -> list[Element]: ...
    def cluster_variable(self, j: int) -> Element: ...
    def cluster_variables(self) -> list[Element]: ...
    def mutate(self, direction: Element | int | str | bool | None) -> Element: ...
    def _mutated_F(self, k: int, old_g_vector: Element | int | str | bool | None) -> Element: ...

class ClusterAlgebra(Parent, UniqueRepresentation):
    def _an_element_(self) -> Element: ...
    def _coerce_map_from_(self, other: Element) -> Element: ...
    def coxeter_element(self) -> Element: ...
    def is_acyclic(self) -> bool: ...
    def rank(self) -> int: ...
    def current_seed(self) -> Element: ...
    def set_current_seed(self, seed: Element | int | str | bool | None) -> Element: ...
    def reset_current_seed(self) -> Element: ...
    def clear_computed_data(self) -> Element: ...
    def contains_seed(self, seed: Element | int | str | bool | None) -> bool: ...
    def initial_seed(self) -> Element: ...
    def euler_matrix(self) -> Element: ...
    def d_vector_to_g_vector(self, d: int) -> tuple[Element, ...]: ...
    def g_vector_to_d_vector(self, g: Element) -> tuple[Element, ...]: ...
    def g_vectors_so_far(self) -> list[Element]: ...
    def cluster_variables_so_far(self) -> list[Element]: ...
    def F_polynomials_so_far(self) -> list[Element]: ...
    def find_g_vector(self, g_vector: Element | int | str | bool | None, depth: Element | int | str | bool | None) -> Element: ...
    def ambient(self) -> Element: ...
    def scalars(self) -> Element: ...
    def lift(self, x: Element) -> Element: ...
    def retract(self, x: Element) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def coefficient(self, j: int) -> Element: ...
    def coefficients(self) -> tuple[Element, ...]: ...
    def coefficient_names(self) -> tuple[Element, ...]: ...
    def initial_cluster_variable(self, j: int) -> Element: ...
    def initial_cluster_variables(self) -> tuple[Element, ...]: ...
    def initial_cluster_variable_names(self) -> tuple[Element, ...]: ...
    def seeds(self) -> Element: ...
    def reset_exploring_iterator(self, mutating_F: Element | int | str | bool | None) -> Element: ...
    def explore_to_depth(self, depth: Element | int | str | bool | None) -> Element: ...
    def cluster_fan(self, depth: Element | int | str | bool | None) -> Element: ...
    def mutate_initial(self, direction: Element | int | str | bool | None) -> Element: ...
    def greedy_element(self, d_vector: Element | int | str | bool | None) -> Element: ...
    def theta_basis_element(self, g_vector: Element | int | str | bool | None) -> Element: ...
    def theta_basis_F_polynomial(self, g_vector: Element | int | str | bool | None) -> Element: ...
    def _greedy_coefficient(self, d_vector: Element | int | str | bool | None, p: int, q: int) -> Element: ...
    def upper_cluster_algebra(self) -> Element: ...
    def upper_bound(self) -> Element: ...
    def lower_bound(self) -> Element: ...

class ElementWrapper: ...

class UniqueRepresentation: ...
