import builtins
from collections.abc import (
    Hashable,
)
from typing import Self

from sage.structure.element import Element

class _SageObject: ...

class ClusterAlgebraElement:
    def d_vector(self) -> tuple[Element, ...]: ...

class PrincipalClusterAlgebraElement:
    def g_vector(self) -> _SageObject: ...
    def F_polynomial(self) -> _SageObject: ...
    def is_homogeneous(self) -> bool: ...
    def homogeneous_components(self) -> dict[Hashable, Element]: ...
    def theta_basis_decomposition(self) -> _SageObject: ...

class ClusterAlgebraSeed:
    def __init__(
        self,
        B: builtins.object,
        C: builtins.object,
        G: builtins.object,
        parent: builtins.object,
        **kwargs: builtins.object,
    ) -> None: ...
    def __copy__(self) -> Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __contains__(self, element: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def parent(self) -> _SageObject: ...
    def depth(self) -> int: ...
    def path_from_initial_seed(self) -> list[Element]: ...
    def b_matrix(self) -> _SageObject: ...
    def c_matrix(self) -> _SageObject: ...
    def c_vector(self, j: builtins.int) -> tuple[Element, ...]: ...
    def c_vectors(self) -> list[tuple]: ...
    def g_matrix(self) -> _SageObject: ...
    def g_vector(self, j: builtins.int) -> tuple[Element, ...]: ...
    def g_vectors(self) -> list[tuple]: ...
    def F_polynomial(self, j: builtins.int) -> _SageObject: ...
    def F_polynomials(self) -> list[Element]: ...
    def cluster_variable(self, j: builtins.int) -> _SageObject: ...
    def cluster_variables(self) -> list[Element]: ...
    def mutate(
        self, direction: builtins.object, **kwargs: builtins.object
    ) -> _SageObject: ...

class ClusterAlgebra:
    @staticmethod
    def __classcall__(
        self: builtins.object, data: builtins.object, **kwargs: builtins.object
    ) -> _SageObject: ...
    def __init__(self, B: builtins.object, **kwargs: builtins.object) -> None: ...
    def coxeter_element(self) -> _SageObject: ...
    def is_acyclic(self) -> bool: ...
    def rank(self) -> _SageObject: ...
    def current_seed(self) -> _SageObject: ...
    def set_current_seed(self, seed: builtins.object) -> _SageObject: ...
    def reset_current_seed(self) -> _SageObject: ...
    def clear_computed_data(self) -> _SageObject: ...
    def contains_seed(self, seed: builtins.object) -> bool: ...
    def initial_seed(self) -> _SageObject: ...
    def b_matrix(self) -> _SageObject: ...
    def euler_matrix(self) -> _SageObject: ...
    def d_vector_to_g_vector(self, d: builtins.object) -> tuple[Element, ...]: ...
    def g_vector_to_d_vector(self, g: builtins.object) -> tuple[Element, ...]: ...
    def g_vectors(self, mutating_F: builtins.bool = ...) -> _SageObject: ...
    def cluster_variables(self) -> _SageObject: ...
    def F_polynomials(self) -> _SageObject: ...
    def g_vectors_so_far(self) -> list[Element]: ...
    def cluster_variables_so_far(self) -> list[Element]: ...
    def F_polynomials_so_far(self) -> list[Element]: ...
    def cluster_variable(self, g_vector: builtins.object) -> _SageObject: ...
    def F_polynomial(self, g_vector: builtins.object) -> _SageObject: ...
    def find_g_vector(
        self, g_vector: builtins.object, depth: builtins.object = ...
    ) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def scalars(self) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def retract(self, x: builtins.object) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def coefficient(self, j: builtins.int) -> _SageObject: ...
    def coefficients(self) -> tuple[Element, ...]: ...
    def coefficient_names(self) -> tuple[Element, ...]: ...
    def initial_cluster_variable(self, j: builtins.int) -> _SageObject: ...
    def initial_cluster_variables(self) -> tuple[Element, ...]: ...
    def initial_cluster_variable_names(self) -> tuple[Element, ...]: ...
    def seeds(self, **kwargs: builtins.object) -> _SageObject: ...
    def reset_exploring_iterator(
        self, mutating_F: builtins.bool = ...
    ) -> _SageObject: ...
    def explore_to_depth(self, depth: builtins.object) -> _SageObject: ...
    def cluster_fan(self, depth: builtins.object = ...) -> _SageObject: ...
    def mutate_initial(
        self, direction: builtins.object, **kwargs: builtins.object
    ) -> _SageObject: ...
    def greedy_element(self, d_vector: builtins.object) -> _SageObject: ...
    def theta_basis_element(self, g_vector: builtins.object) -> _SageObject: ...
    def theta_basis_F_polynomial(self, g_vector: builtins.object) -> _SageObject: ...
    def upper_cluster_algebra(self) -> _SageObject: ...
    def upper_bound(self) -> _SageObject: ...
    def lower_bound(self) -> _SageObject: ...
