from collections.abc import Set as AbstractSet

from sage.algebras.clifford_algebra_element import CliffordAlgebraElement
from sage.data_structures.bitset import FrozenBitset
from sage.rings.ideal import Ideal_generic
from sage.rings.integer import Integer
from sage.structure.element import Element

class GBElement:
    def __init__(
        self, x: CliffordAlgebraElement, ls: FrozenBitset, n: Integer
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: GBElement, op: int) -> bool: ...

class GroebnerStrategy:
    def __init__(self, I: Ideal_generic) -> None: ...
    def leading_support(self, f: CliffordAlgebraElement) -> FrozenBitset: ...
    def partial_S_poly_left(self, f: GBElement, g: GBElement) -> GBElement: ...
    def partial_S_poly_right(self, f: GBElement, g: GBElement) -> GBElement: ...
    def build_elt(self, f: CliffordAlgebraElement) -> GBElement: ...
    def prod_GB_term(self, f: GBElement, t: FrozenBitset) -> GBElement: ...
    def prod_term_GB(self, t: FrozenBitset, f: GBElement) -> GBElement: ...
    def build_S_poly(self, f: GBElement, g: GBElement) -> bool: ...
    def preprocessing(
        self, P: list[tuple[GBElement, GBElement]], G: list[GBElement]
    ) -> AbstractSet[GBElement]: ...
    def reduction(
        self, P: list[tuple[GBElement, GBElement]], G: list[GBElement]
    ) -> list[GBElement]: ...
    def compute_groebner(self, reduced: bool = True) -> None: ...
    def reduced_gb(self, G: list[GBElement]) -> int: ...
    def reduce_computed_gb(self) -> None: ...
    def reduce(self, f: CliffordAlgebraElement) -> CliffordAlgebraElement: ...
    def reduce_single(
        self, f: CliffordAlgebraElement, g: CliffordAlgebraElement
    ) -> bool: ...
    def bitset_to_int(self, X: FrozenBitset) -> Integer: ...
    def int_to_bitset(self, n: int | Integer) -> FrozenBitset: ...
    def sorted_monomials(self, as_dict: bool = False) -> list[FrozenBitset]: ...
    def monomial_to_int(self) -> dict[Element, Integer]: ...

class GroebnerStrategyNegLex(GroebnerStrategy):
    def bitset_to_int(self, X: FrozenBitset) -> Integer: ...
    def int_to_bitset(self, n: int | Integer) -> FrozenBitset: ...

class GroebnerStrategyDegRevLex(GroebnerStrategy):
    def bitset_to_int(self, X: FrozenBitset) -> Integer: ...
    def int_to_bitset(self, n: int | Integer) -> FrozenBitset: ...

class GroebnerStrategyDegLex(GroebnerStrategy):
    def bitset_to_int(self, X: FrozenBitset) -> Integer: ...
    def int_to_bitset(self, n: int | Integer) -> FrozenBitset: ...
