from sage.structure.element import Element

class FiniteGCAlgebra(CombinatorialFreeModule):
    def _valid_index(self, w: Element) -> bool: ...
    def _repr_(self) -> str: ...
    def ngens(self) -> int: ...
    def product_on_basis(self, w1: Element | int | str | bool | None, w2: Element | int | str | bool | None) -> Element: ...
    def degree_on_basis(self, i: int) -> int: ...
    def _repr_term(self, w: Element) -> str: ...
    def _latex_term(self, w: Element) -> str: ...
    def algebra_generators(self) -> Element: ...
    def one_basis(self) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: int) -> Element: ...
    def maximal_degree(self) -> Element: ...

class CombinatorialFreeModule: ...
