# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FiniteGCAlgebra:
    @staticmethod
    def __classcall_private__(cls: builtins.object, base: builtins.object, names: builtins.object = ..., degrees: builtins.object = ..., max_degree: builtins.object = ..., category: builtins.object = ..., **kwargs: builtins.object) -> _SageObject: ...
    def __init__(self, base: builtins.object, names: builtins.object, degrees: builtins.object, max_degree: builtins.object, category: builtins.object = ..., **kwargs: builtins.object) -> None: ...
    def ngens(self) -> _SageObject: ...
    def product_on_basis(self, w1: builtins.object, w2: builtins.object) -> _SageObject: ...
    def degree_on_basis(self, i: builtins.int) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def maximal_degree(self) -> _SageObject: ...
    max_degree: _SageObject
