# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeZinbielAlgebra:
    @staticmethod
    def __classcall_private__(cls: builtins.object, R: builtins.int, n: builtins.int = ..., names: builtins.object = ..., prefix: builtins.str = ..., side: builtins.object = ...) -> _SageObject: ...
    def __init__(self, R: builtins.int, n: builtins.int, names: builtins.object, prefix: builtins.str, side: builtins.object) -> None: ...
    def side(self) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def degree_on_basis(self, t: builtins.object) -> _SageObject: ...
    def product_on_basis_left(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def product_on_basis_right(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def coproduct_on_basis(self, w: builtins.object) -> _SageObject: ...
    def counit(self, S: builtins.object) -> _SageObject: ...
    def construction(self) -> _SageObject: ...

class ZinbielFunctor:
    rank: _SageObject
    def __init__(self, variables: builtins.object, side: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def merge(self, other: builtins.object) -> _SageObject: ...
