# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def transpose_cmp(x: builtins.object, y: builtins.object) -> _SageObject: ...

class HallAlgebra:
    def __init__(self, base_ring: builtins.object, q: builtins.int, prefix: builtins.str = ...) -> None: ...
    def one_basis(self) -> _SageObject: ...
    def product_on_basis(self, mu: builtins.object, la: builtins.object) -> _SageObject: ...
    def coproduct_on_basis(self, la: builtins.object) -> _SageObject: ...
    def antipode_on_basis(self, la: builtins.object) -> _SageObject: ...
    def counit(self, x: builtins.object) -> _SageObject: ...
    def monomial_basis(self) -> _SageObject: ...
    def __getitem__(self, la: builtins.object) -> _SageObject: ...
    class Element:
        def scalar(self, y: builtins.object) -> _SageObject: ...

class HallAlgebraMonomials:
    def __init__(self, base_ring: builtins.object, q: builtins.int, prefix: builtins.str = ...) -> None: ...
    def one_basis(self) -> _SageObject: ...
    def product_on_basis(self, a: builtins.object, b: builtins.object) -> _SageObject: ...
    def coproduct_on_basis(self, a: builtins.object) -> _SageObject: ...
    def antipode_on_basis(self, a: builtins.object) -> _SageObject: ...
    def counit(self, x: builtins.object) -> _SageObject: ...
    def __getitem__(self, a: builtins.object) -> _SageObject: ...
    class Element:
        def scalar(self, y: builtins.object) -> _SageObject: ...
