from sage.structure.element import Element

def transpose_cmp(x: Element, y: Element) -> Element: ...

class HallAlgebra(CombinatorialFreeModule):
    def _repr_(self) -> str: ...
    def one_basis(self) -> Element: ...
    def product_on_basis(self, mu: Element | int | str | bool | None, la: Element | int | str | bool | None) -> Element: ...
    def coproduct_on_basis(self, la: Element | int | str | bool | None) -> Element: ...
    def antipode_on_basis(self, la: Element | int | str | bool | None) -> Element: ...
    def counit(self, x: Element) -> Element: ...
    def monomial_basis(self) -> Element: ...
    def __getitem__(self, la: Element | int | str | bool | None) -> Element: ...

class HallAlgebraMonomials(CombinatorialFreeModule):
    def _to_natural_on_basis(self, a: Element) -> Element: ...

class CombinatorialFreeModule: ...
