from sage.combinat.root_system.cartan_type import CartanType_abstract
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.combinat.root_system.weyl_group import WeylGroup
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

class IwahoriHeckeAlgebra(Parent, UniqueRepresentation):
    def cartan_type(self) -> CartanType_abstract: ...
    def base_ring(self) -> Ring: ...
    def T(self) -> list[Element]: ...
    def q1(self) -> Element: ...
    def q2(self) -> Element: ...
    def coxeter_group(self) -> WeylGroup: ...
    def is_generic(self) -> bool: ...
