# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class NilCoxeterAlgebra:
    def __init__(self, W: builtins.object, base_ring: builtins.object = ..., prefix: builtins.str = ...) -> None: ...
    def homogeneous_generator_noncommutative_variables(self, r: builtins.int) -> _SageObject: ...
    def homogeneous_noncommutative_variables(self, la: builtins.object) -> _SageObject: ...
    def k_schur_noncommutative_variables(self, la: builtins.object) -> _SageObject: ...
