# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Octonion_generic:
    def __init__(self, parent: builtins.object, v: builtins.object) -> None: ...
    def __getitem__(self, m: builtins.object) -> _SageObject: ...
    def __bool__(self) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __hash__(self) -> builtins.int: ...
    def __neg__(self) -> Self: ...
    def is_unit(self) -> builtins.bool: ...
    def __invert__(self) -> Self: ...
    def conjugate(self) -> _SageObject: ...
    def quadratic_form(self) -> _SageObject: ...
    def norm(self) -> _SageObject: ...
    def abs(self) -> _SageObject: ...
    def real_part(self) -> _SageObject: ...
    def imag_part(self) -> _SageObject: ...
    def monomial_coefficients(self, copy: builtins.object = ...) -> _SageObject: ...

class Octonion:
    def quadratic_form(self) -> _SageObject: ...
    def norm(self) -> _SageObject: ...

class OctonionAlgebra:
    @staticmethod
    def __classcall_private__(cls: builtins.object, R: builtins.object, a: builtins.object = ..., b: builtins.object = ..., c: builtins.object = ..., names: builtins.object = ...) -> _SageObject: ...
    def __init__(self, R: builtins.object, a: builtins.object, b: builtins.object, c: builtins.object, names: builtins.object) -> None: ...
    def some_elements(self) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def gens(self) -> _SageObject: ...
    def basis(self) -> _SageObject: ...
