from sage.structure.element import Element

class qCommutingPolynomials_generic(CombinatorialFreeModule):
    def _term_key(self) -> Element: ...
    def gen(self, i: int) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def algebra_generators(self) -> Element: ...
    def degree_on_basis(self, m: int) -> int: ...
    def dimension(self) -> int: ...
    def q(self) -> Element: ...

class qCommutingPolynomials(qCommutingPolynomials_generic):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def one_basis(self) -> Element: ...
    def product_on_basis(self, x: Element, y: Element) -> Element: ...

class qCommutingLaurentPolynomials(qCommutingPolynomials_generic):
    def _repr_term(self, m: int) -> str: ...
    def _latex_term(self, m: int) -> str: ...

class CombinatorialFreeModule: ...
