import builtins
from typing import Self

from sage.structure.element import Element

class _SageObject: ...

class qCommutingPolynomials_generic:
    @staticmethod
    def __classcall__(
        cls: builtins.object,
        q: builtins.int,
        n: builtins.int = ...,
        B: builtins.object = ...,
        base_ring: builtins.object = ...,
        names: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        q: builtins.int,
        B: builtins.object,
        indices: builtins.object,
        names: builtins.object,
    ) -> None: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def algebra_generators(self) -> _SageObject: ...
    def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def q(self) -> _SageObject: ...

class qCommutingPolynomials:
    def __init__(
        self, q: builtins.int, B: builtins.object, names: builtins.object
    ) -> None: ...
    def one_basis(self) -> _SageObject: ...
    def product_on_basis(
        self, x: builtins.object, y: builtins.object
    ) -> _SageObject: ...

class qCommutingLaurentPolynomials:
    def __init__(
        self, q: builtins.int, B: builtins.object, names: builtins.object
    ) -> None: ...
    def one_basis(self) -> _SageObject: ...
    def product_on_basis(
        self, x: builtins.object, y: builtins.object
    ) -> _SageObject: ...

    class Element:
        def __invert__(self) -> Self: ...
