from typing import Self

from sage.combinat.free_module import CombinatorialFreeModule
from sage.combinat.root_system.cartan_type import CartanType_abstract
from sage.monoids.indexed_free_monoid import IndexedFreeAbelianMonoidElement
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.ring import CommutativeRing
from sage.sets.family import AbstractFamily
from sage.structure.element import Element
from sage.typeset.ascii_art import AsciiArt
from sage.typeset.unicode_art import UnicodeArt

type QSystemBasisKey = tuple[int | Integer, int | Integer]
type QSystemMonoidElement = IndexedFreeAbelianMonoidElement[QSystemBasisKey]


def is_tamely_laced(ct: object) -> bool: ...

class QSystem(CombinatorialFreeModule):
    @classmethod
    def __classcall__(
        cls: type[Self],
        *args: object,
        **options: object,
    ) -> Self: ...
    def __init__(
        self,
        base_ring: CommutativeRing,
        cartan_type: CartanType_abstract,
        level: int | Integer | None,
        twisted: bool,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def _repr_term(self, t: QSystemMonoidElement) -> str: ...
    def _latex_term(self, t: QSystemMonoidElement) -> str: ...
    def _ascii_art_term(self, t: QSystemMonoidElement) -> AsciiArt: ...
    def _unicode_art_term(self, t: QSystemMonoidElement) -> UnicodeArt: ...
    def cartan_type(self) -> CartanType_abstract: ...
    def index_set(self) -> tuple[object, ...]: ...
    def level(self) -> int | Integer | None: ...
    def one_basis(self) -> QSystemMonoidElement: ...
    def algebra_generators(self) -> AbstractFamily[object, Element]: ...
    def gens(self) -> tuple[Element, ...]: ...
    def dimension(self) -> PlusInfinity: ...
    def Q(self, a: int | Integer, m: int | Integer) -> Element: ...
    def _Q_poly(self, a: int | Integer, m: int | Integer) -> Element: ...

    class Element(CombinatorialFreeModule.Element):
        def _mul_(self, x: Self) -> Self: ...
