import builtins

from sage.structure.element import Element

class _SageObject: ...

class QSystem:
    @staticmethod
    def __classcall__(
        cls: builtins.object,
        base_ring: builtins.object,
        cartan_type: builtins.object,
        level: builtins.object = ...,
        twisted: builtins.bool = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        base_ring: builtins.object,
        cartan_type: builtins.object,
        level: builtins.object,
        twisted: builtins.object,
    ) -> None: ...
    def cartan_type(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def level(self) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def dimension(self) -> _SageObject: ...
    def Q(self, a: builtins.object, m: builtins.int) -> _SageObject: ...

    class Element: ...

def is_tamely_laced(self) -> bool: ...
