from sage.structure.element import Element

class QuantumOscillatorAlgebra(CombinatorialFreeModule):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def q(self) -> Element: ...
    def algebra_generators(self) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def one_basis(self) -> tuple[Element, ...]: ...
    def some_elements(self) -> tuple[Element, ...]: ...
    def fock_space_representation(self) -> Element: ...
    def _repr_term(self, m: int) -> str: ...
    def _latex_term(self, m: int) -> str: ...
    def product_on_basis(self, ml: Element | int | str | bool | None, mr: Element | int | str | bool | None) -> Element: ...

class FockSpaceRepresentation(CombinatorialFreeModule):
    def _test_representation(self) -> Element: ...
    def vacuum(self) -> Element: ...

class CombinatorialFreeModule: ...
