# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class QuantumMatrixCoordinateAlgebra_abstract:
    @staticmethod
    def __classcall__(cls: builtins.object, q: builtins.int = ..., bar: builtins.object = ..., R: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...
    def __init__(self, gp_indices: builtins.object, n: builtins.int, q: builtins.int, bar: builtins.object, R: builtins.int, category: builtins.object, indices_key: builtins.object = ...) -> None: ...
    def n(self) -> _SageObject: ...
    def q(self) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def quantum_determinant(self) -> _SageObject: ...
    def product_on_basis(self, a: builtins.object, b: builtins.object) -> _SageObject: ...
    def counit_on_basis(self, x: builtins.object) -> _SageObject: ...
    class Element:
        def bar(self) -> _SageObject: ...

class QuantumMatrixCoordinateAlgebra:
    @staticmethod
    def __classcall_private__(cls: builtins.object, m: builtins.int, n: builtins.int = ..., q: builtins.int = ..., bar: builtins.object = ..., R: builtins.int = ...) -> _SageObject: ...
    def __init__(self, m: builtins.int, n: builtins.int, q: builtins.int, bar: builtins.object, R: builtins.int) -> None: ...
    def m(self) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    def coproduct_on_basis(self, x: builtins.object) -> _SageObject: ...

class QuantumGL:
    @staticmethod
    def __classcall_private__(cls: builtins.object, n: builtins.int, q: builtins.int = ..., bar: builtins.object = ..., R: builtins.int = ...) -> _SageObject: ...
    def __init__(self, n: builtins.int, q: builtins.int, bar: builtins.object, R: builtins.int) -> None: ...
    def algebra_generators(self) -> _SageObject: ...
    def product_on_basis(self, a: builtins.object, b: builtins.object) -> _SageObject: ...
    def antipode_on_basis(self, x: builtins.object) -> _SageObject: ...
    def coproduct_on_basis(self, x: builtins.object) -> _SageObject: ...
