import builtins

class _SageObject: ...

def unpickle_QuaternionAlgebraElement_generic_v0(
    self, *args: builtins.object
) -> _SageObject: ...
def unpickle_QuaternionAlgebraElement_rational_field_v0(
    self, *args: builtins.object
) -> _SageObject: ...
def unpickle_QuaternionAlgebraElement_number_field_v0(
    self, *args: builtins.object
) -> _SageObject: ...
