from sage.structure.element import Element

class RationalCherednikAlgebra(CombinatorialFreeModule):
    def _genkey(self, t: Element | int | str | bool | None) -> Element: ...
    def _reflections(self) -> dict[Element, Element]: ...
    def _repr_(self) -> str: ...
    def _repr_term(self, t: Element | int | str | bool | None) -> str: ...
    def algebra_generators(self) -> Element: ...
    def one_basis(self) -> Element: ...
    def product_on_basis(self, left: Element | int | str | bool | None, right: Element | int | str | bool | None) -> Element: ...
    def _product_coroot_root(self, i: int, j: int) -> Element: ...
    def degree_on_basis(self, m: int) -> int: ...
    def trivial_idempotent(self) -> Element: ...
    def deformed_euler(self) -> Element: ...
    def _an_element_(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...

class CombinatorialFreeModule: ...
