from sage.structure.element import Element

def schur_representative_indices(n: int, r: int) -> Element: ...
def schur_representative_from_index(i0: Element | int | str | bool | None, i1: Element | int | str | bool | None) -> Element: ...
def GL_irreducible_character(n: int, mu: Element | int | str | bool | None, KK: Element | int | str | bool | None) -> Element: ...

class SchurAlgebra(CombinatorialFreeModule):
    def _repr_(self) -> str: ...
    def one(self) -> Element: ...
    def product_on_basis(self, e_ij: Element | int | str | bool | None, e_kl: Element | int | str | bool | None) -> Element: ...
    def dimension(self) -> int: ...

class SchurTensorModule(CombinatorialFreeModule_Tensor):
    def construction(self) -> Element: ...
    def _monomial_product(self, xi: Element | int | str | bool | None, v: Element) -> Element: ...

class CombinatorialFreeModule: ...

class CombinatorialFreeModule_Tensor: ...
