# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def schur_representative_indices(n: builtins.int, r: builtins.int) -> _SageObject: ...

def schur_representative_from_index(i0: builtins.object, i1: builtins.object) -> _SageObject: ...

class SchurAlgebra:
    def __init__(self, R: builtins.int, n: builtins.int, r: builtins.int) -> None: ...
    def one(self) -> _SageObject: ...
    def product_on_basis(self, e_ij: builtins.object, e_kl: builtins.object) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...

class SchurTensorModule:
    def __init__(self, R: builtins.int, n: builtins.int, r: builtins.int) -> None: ...
    def construction(self) -> _SageObject: ...
    class Element:
        ...

def GL_irreducible_character(n: builtins.int, mu: builtins.object, KK: builtins.object) -> _SageObject: ...
