from collections.abc import Iterator
from typing import Self

from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.parent import Parent

def repr_from_monomials(monomials: Element | int | str | bool | None, term_repr: Element | int | str | bool | None, use_latex: Element | int | str | bool | None) -> str: ...
def repr_factored(w: Element, latex_output: Element | int | str | bool | None) -> str: ...

type _BuiltinList[_T] = list[_T]
class DifferentialWeylAlgebraElement(IndexedFreeModuleElement):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _mul_(self, other: Element) -> Self: ...
    def _rmul_(self, other: Element) -> Element: ...
    def _lmul_(self, other: Element) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...
    def list(self) -> _BuiltinList[Element]: ...
    def factor_differentials(self) -> dict[Element, Element]: ...
    def diff(self, p: int) -> Element: ...

class DifferentialWeylAlgebra(UniqueRepresentation, Parent):
    def _element_constructor_(self, x: Element) -> Element: ...
    def _coerce_map_from_(self, R: Ring) -> Element: ...
    def degree_on_basis(self, i: int) -> int: ...
    def polynomial_ring(self) -> Element: ...
    def basis(self) -> Element: ...
    def algebra_generators(self) -> Element: ...
    def variables(self) -> Element: ...
    def differentials(self) -> Element: ...
    def gen(self, i: int) -> Element: ...
    def ngens(self) -> int: ...
    def one(self) -> Element: ...
    def zero(self) -> Element: ...
    def diff_action(self) -> Element: ...

class DifferentialWeylAlgebraAction(Action):
    def _act_(self, g: Element, x: Element) -> Element: ...

class InfGenDifferentialWeylAlgebraElement(IndexedFreeModuleElement):
    def __iter__(self) -> Iterator[Element]: ...

class InfGenDifferentialWeylAlgebra(UniqueRepresentation, Parent):
    def polynomial_gens(self) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...
    def differential(self, i: int) -> Element: ...
    def one_basis(self) -> Element: ...

class Action: ...

class IndexedFreeModuleElement: ...

class UniqueRepresentation: ...
