from sage.rings.ring import Ring
from sage.structure.element import Element

class Yangian(CombinatorialFreeModule):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _term_key(self) -> Element: ...
    def _repr_term(self, m: int) -> str: ...
    def _latex_term(self, m: int) -> str: ...
    def _element_constructor_(self, x: Element) -> Element: ...
    def gen(self, r: int, i: int, j: int) -> Element: ...
    def algebra_generators(self) -> Element: ...
    def one_basis(self) -> Element: ...
    def degree_on_basis(self, m: int) -> int: ...
    def graded_algebra(self) -> Element: ...
    def dimension(self) -> int: ...
    def product_on_basis(self, x: Element, y: Element) -> Element: ...
    def product_on_gens(self, a: Element, b: Element) -> Element: ...
    def coproduct_on_basis(self, m: int) -> Element: ...
    def counit_on_basis(self, m: int) -> Element: ...

class YangianLevel(Yangian):
    def _coerce_map_from_(self, R: Ring) -> Element: ...
    def level(self) -> Element: ...
    def defining_polynomial(self, i: int, j: int, u: Element | int | str | bool | None) -> Element: ...
    def quantum_determinant(self, u: Element | int | str | bool | None) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...

class GradedYangianBase(AssociatedGradedAlgebra):
    ...

class GradedYangianNatural(GradedYangianBase):
    ...

class GradedYangianLoop(GradedYangianBase):
    def antipode_on_basis(self, m: int) -> Element: ...

class AssociatedGradedAlgebra: ...

class CombinatorialFreeModule: ...
