from sage.structure.element import Element

class YokonumaHeckeAlgebra(CombinatorialFreeModule):
    def cartan_type(self) -> Element: ...
    def index_set(self) -> Element: ...
    def q(self) -> Element: ...
    def g(self, i: int) -> Element: ...
    def gens(self) -> tuple[Element, ...]: ...

class YokonumaHeckeAlgebraGL(YokonumaHeckeAlgebra):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _repr_term(self, m: int) -> str: ...
    def _latex_term(self, m: int) -> str: ...
    def algebra_generators(self) -> Element: ...
    def one_basis(self) -> Element: ...
    def e(self, i: int) -> Element: ...
    def t(self, i: int) -> Element: ...
    def product_on_basis(self, m1: Element | int | str | bool | None, m2: Element | int | str | bool | None) -> Element: ...
    def _product_by_basis_gen(self, m: int, i: int) -> Element: ...
    def inverse_g(self, i: int) -> Element: ...

class YokonumaHeckeAlgebraWeyl(YokonumaHeckeAlgebra):
    def h(self, i: int) -> Element: ...

class CombinatorialFreeModule: ...
