# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KRTToRCBijectionTypeE67:
    def next_state(self, val: builtins.object) -> _SageObject: ...

class RCToKRTBijectionTypeE67:
    def next_state(self, r: builtins.int) -> _SageObject: ...

def endpoint6(r: builtins.int) -> _SageObject: ...

def endpoint7(r: builtins.int) -> _SageObject: ...
