# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KirillovReshetikhinTableaux:
    @staticmethod
    def __classcall_private__(cls: builtins.object, cartan_type: builtins.object, r: builtins.int, s: builtins.object) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object, r: builtins.int, s: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def module_generator(self, i: builtins.int = ..., **options: builtins.object) -> _SageObject: ...
    def from_kirillov_reshetikhin_crystal(self, krc: builtins.object) -> _SageObject: ...
    def r(self) -> _SageObject: ...
    def s(self) -> _SageObject: ...
    def kirillov_reshetikhin_crystal(self) -> _SageObject: ...
    def classical_decomposition(self) -> _SageObject: ...
    def tensor(self, *crystals: builtins.object, **options: builtins.object) -> _SageObject: ...

class KRTableauxRectangle:
    def from_kirillov_reshetikhin_crystal(self, krc: builtins.object) -> _SageObject: ...

class KRTableauxTypeVertical:
    def from_kirillov_reshetikhin_crystal(self, krc: builtins.object) -> _SageObject: ...

class KRTableauxTypeHorizonal:
    def from_kirillov_reshetikhin_crystal(self, krc: builtins.object) -> _SageObject: ...

class KRTableauxTypeBox:
    ...

class KRTableauxSpin:
    ...

class KRTableauxBn:
    def from_kirillov_reshetikhin_crystal(self, krc: builtins.object) -> _SageObject: ...

class KirillovReshetikhinTableauxElement:
    def __init__(self, parent: builtins.object, list: builtins.object, **options: builtins.object) -> None: ...
    def to_kirillov_reshetikhin_crystal(self) -> _SageObject: ...
    def to_array(self, rows: builtins.bool = ...) -> _SageObject: ...
    def to_tableau(self) -> _SageObject: ...
    def pp(self) -> _SageObject: ...
    def to_classical_highest_weight(self, index_set: builtins.object = ...) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def classical_weight(self) -> _SageObject: ...
    def e(self, i: builtins.int) -> _SageObject: ...
    def f(self, i: builtins.int) -> _SageObject: ...
    def epsilon(self, i: builtins.int) -> _SageObject: ...
    def phi(self, i: builtins.int) -> _SageObject: ...
    def left_split(self) -> _SageObject: ...
    def right_split(self) -> _SageObject: ...

class KRTableauxSpinElement:
    def e(self, i: builtins.int) -> _SageObject: ...
    def f(self, i: builtins.int) -> _SageObject: ...
    def epsilon(self, i: builtins.int) -> _SageObject: ...
    def phi(self, i: builtins.int) -> _SageObject: ...
    def to_array(self, rows: builtins.bool = ...) -> _SageObject: ...
    def left_split(self) -> _SageObject: ...
    def classical_weight(self) -> _SageObject: ...

class KRTableauxDTwistedSpin:
    Element: _SageObject

class KRTableauxTypeFromRCElement:
    def e(self, i: builtins.int) -> _SageObject: ...
    def f(self, i: builtins.int) -> _SageObject: ...
    def epsilon(self, i: builtins.int) -> _SageObject: ...
    def phi(self, i: builtins.int) -> _SageObject: ...

class KRTableauxTypeFromRC:
    def __init__(self, cartan_type: builtins.object, r: builtins.int, s: builtins.object) -> None: ...
    def module_generators(self) -> _SageObject: ...
    Element: _SageObject
