# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class InfinityCrystalOfRiggedConfigurations:
    @staticmethod
    def __classcall_private__(cls: builtins.object, cartan_type: builtins.object) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object) -> None: ...
    options: _SageObject
    def weight_lattice_realization(self) -> _SageObject: ...
    class Element:
        def weight(self) -> _SageObject: ...

class InfinityCrystalOfNonSimplyLacedRC:
    def __init__(self, vct: builtins.object) -> None: ...
    def virtual(self) -> _SageObject: ...
    def to_virtual(self, rc: builtins.object) -> _SageObject: ...
    def from_virtual(self, vrc: builtins.object) -> _SageObject: ...
    class Element:
        def weight(self) -> _SageObject: ...
