# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class RiggedConfigurationElement:
    def __init__(self, parent: builtins.object, rigged_partitions: builtins.list[_SageObject] = ..., **options: builtins.object) -> None: ...
    def check(self) -> _SageObject: ...
    def nu(self) -> _SageObject: ...
    def e(self, a: builtins.object) -> _SageObject: ...
    def f(self, a: builtins.object) -> _SageObject: ...
    def epsilon(self, a: builtins.object) -> _SageObject: ...
    def phi(self, a: builtins.object) -> _SageObject: ...
    def vacancy_number(self, a: builtins.object, i: builtins.int) -> _SageObject: ...
    def partition_rigging_lists(self) -> _SageObject: ...

class RCNonSimplyLacedElement:
    def to_virtual_configuration(self) -> _SageObject: ...
    def e(self, a: builtins.object) -> _SageObject: ...
    def f(self, a: builtins.object) -> _SageObject: ...

class RCHighestWeightElement:
    def check(self) -> _SageObject: ...
    def f(self, a: builtins.object) -> _SageObject: ...
    def weight(self) -> _SageObject: ...

class RCHWNonSimplyLacedElement:
    def check(self) -> _SageObject: ...
    def f(self, a: builtins.object) -> _SageObject: ...
    def weight(self) -> _SageObject: ...

class KRRiggedConfigurationElement:
    def __init__(self, parent: builtins.object, rigged_partitions: builtins.list[_SageObject] = ..., **options: builtins.object) -> None: ...
    def check(self) -> _SageObject: ...
    def e(self, a: builtins.object) -> _SageObject: ...
    def f(self, a: builtins.object) -> _SageObject: ...
    def epsilon(self, a: builtins.object) -> _SageObject: ...
    def phi(self, a: builtins.object) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def classical_weight(self) -> _SageObject: ...
    def to_tensor_product_of_kirillov_reshetikhin_tableaux(self, display_steps: builtins.bool = ..., build_graph: builtins.bool = ...) -> _SageObject: ...
    def to_tensor_product_of_kirillov_reshetikhin_crystals(self, display_steps: builtins.bool = ..., build_graph: builtins.bool = ...) -> _SageObject: ...
    def left_split(self) -> _SageObject: ...
    def right_split(self) -> _SageObject: ...
    def left_box(self, return_b: builtins.bool = ...) -> _SageObject: ...
    delta: _SageObject
    def left_column_box(self) -> _SageObject: ...
    def right_column_box(self) -> _SageObject: ...
    def complement_rigging(self, reverse_factors: builtins.bool = ...) -> _SageObject: ...

class KRRCSimplyLacedElement:
    def cocharge(self) -> _SageObject: ...
    cc: _SageObject
    def charge(self) -> _SageObject: ...

class KRRCNonSimplyLacedElement:
    def e(self, a: builtins.object) -> _SageObject: ...
    def f(self, a: builtins.object) -> _SageObject: ...
    def cocharge(self) -> _SageObject: ...
    cc: _SageObject

class KRRCTypeA2DualElement:
    def epsilon(self, a: builtins.object) -> _SageObject: ...
    def phi(self, a: builtins.object) -> _SageObject: ...
    def cocharge(self) -> _SageObject: ...
    cc: _SageObject
