# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class TensorProductOfKirillovReshetikhinTableauxElement:
    def __init__(self, parent: builtins.object, list: builtins.list[_SageObject] = ..., **options: builtins.object) -> None: ...
    def pp(self) -> _SageObject: ...
    def classical_weight(self) -> _SageObject: ...
    def lusztig_involution(self) -> _SageObject: ...
    def left_split(self) -> _SageObject: ...
    def right_split(self) -> _SageObject: ...
    def to_rigged_configuration(self, display_steps: builtins.bool = ...) -> _SageObject: ...
    def to_tensor_product_of_kirillov_reshetikhin_crystals(self) -> _SageObject: ...
