import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.combinat.crystals.letters import CrystalOfLetters

class _SageObject: ...

class HighestWeightTensorKRT:
    def __init__(self, tp_krt: builtins.object) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...

class TensorProductOfKirillovReshetikhinTableaux:
    module_generators: HighestWeightTensorKRT
    letters: CrystalOfLetters

    @staticmethod
    def __classcall_private__(
        cls: builtins.object, cartan_type: builtins.object, B: builtins.object
    ) -> _SageObject: ...
    def __init__(self, cartan_type: builtins.object, B: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def rigged_configurations(self) -> _SageObject: ...
    def tensor_product_of_kirillov_reshetikhin_crystals(self) -> _SageObject: ...
    def tensor(
        self, *crystals: builtins.object, **options: builtins.object
    ) -> _SageObject: ...
