import builtins

from sage.structure.element import Element

class _SageObject: ...

class ArtinGroupElement:
    def exponent_sum(self) -> _SageObject: ...
    def coxeter_group_element(self, W: builtins.object = ...) -> _SageObject: ...
    def burau_matrix(self, var: builtins.str = ...) -> _SageObject: ...

class FiniteTypeArtinGroupElement:
    def __hash__(self) -> builtins.int: ...
    def left_normal_form(self) -> _SageObject: ...

class ArtinGroup:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        coxeter_data: builtins.object,
        names: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self, coxeter_matrix: builtins.object, names: builtins.object
    ) -> None: ...
    def cardinality(self) -> _SageObject: ...
    order: _SageObject

    def as_permutation_group(self) -> _SageObject: ...
    def coxeter_type(self) -> _SageObject: ...
    def coxeter_matrix(self) -> _SageObject: ...
    def coxeter_group(self) -> _SageObject: ...
    def index_set(self) -> _SageObject: ...
    def some_elements(self) -> list[Element]: ...
    Element: _SageObject

class FiniteTypeArtinGroup:
    def delta(self) -> _SageObject: ...
    Element: _SageObject
