# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CactusGroup:
    def __init__(self, n: builtins.int) -> None: ...
    def right_angled_coxeter_group(self) -> _SageObject: ...
    def n(self) -> _SageObject: ...
    def group_generators(self) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def gen(self, i: builtins.int, j: builtins.int = ...) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def random_element(self, max_length: builtins.int = ...) -> _SageObject: ...
    def bilinear_form(self, t: builtins.object = ...) -> _SageObject: ...
    def geometric_representation_generators(self, t: builtins.object = ...) -> _SageObject: ...
    class Element:
        def __init__(self, parent: builtins.object, data: builtins.object) -> None: ...
        def __hash__(self) -> builtins.int: ...
        def __invert__(self) -> Self: ...
        def to_permutation(self) -> _SageObject: ...
        to_matrix: _SageObject

class PureCactusGroup:
    def __init__(self, n: builtins.int) -> None: ...
    def n(self) -> _SageObject: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
