from sage.groups.free_group import FreeGroup, FreeGroupElement
from sage.libs.gap.element import GapElement
from sage.rings.integer import Integer
from typing import Any

class GroupMorphismWithGensImages:
    def _repr_defn(self) -> str: ...

class FinitelyPresentedGroupElement:
    def __init__(self, parent: FinitelyPresentedGroup, x: FreeGroupElement, check: bool = True) -> None: ...
    def __reduce__(self) -> tuple: ...
    def _repr_(self) -> str: ...
    def Tietze(self) -> tuple[int, ...]: ...
    def __hash__(self) -> int: ...
    def __call__(self, *values: object, **kwds: object) -> object: ...

class RewritingSystem:
    def __init__(self, G: FinitelyPresentedGroup) -> None: ...
    def free_group(self) -> FreeGroup: ...
    def finitely_presented_group(self) -> FinitelyPresentedGroup: ...
    def reduce(self, element: FreeGroupElement) -> FinitelyPresentedGroupElement: ...
    def gap(self) -> GapElement: ...
    def rules(self) -> dict[Any, Any]: ...
    def is_confluent(self) -> bool: ...
    def make_confluent(self) -> None: ...

class FinitelyPresentedGroup:
    Element: type[FinitelyPresentedGroupElement]
    def __init__(self, free_group: FreeGroup, relations: tuple[FreeGroupElement, ...], category: object = None, libgap_fpgroup: object = None) -> None: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _regina_(self, regina: object) -> object: ...
    def free_group(self) -> FreeGroup: ...
    def relations(self) -> tuple[FreeGroupElement, ...]: ...
    def _perm_isomorphism(self) -> GapElement | None: ...
    def cardinality(self, limit: int = 4096000) -> Integer: ...
    def order(self, limit: int = 4096000) -> Integer: ...
    def as_permutation_group(self, limit: int = 4096000) -> object: ...
    def direct_product(self, H: FinitelyPresentedGroup, reduced: bool = False, new_names: bool = True) -> FinitelyPresentedGroup: ...
    def semidirect_product(self, H: FinitelyPresentedGroup, hom: object, check: bool = True, reduced: bool = False) -> FinitelyPresentedGroup: ...
    def _element_constructor_(self, *args: object, **kwds: object) -> FinitelyPresentedGroupElement: ...
    def abelian_invariants(self) -> tuple[Integer, ...]: ...
    def abelianization_map(self) -> object: ...
    def abelianization_to_algebra(self, ring: object = None) -> object: ...
    def simplification_isomorphism(self) -> object: ...
    def simplified(self) -> FinitelyPresentedGroup: ...
    def sorted_presentation(self) -> FinitelyPresentedGroup: ...
    def epimorphisms(self, H: object) -> object: ...
