# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def CyclicPresentation(n: builtins.int) -> _SageObject: ...

def FinitelyGeneratedAbelianPresentation(int_list: builtins.object) -> _SageObject: ...

def FinitelyGeneratedHeisenbergPresentation(n: builtins.int = ..., p: builtins.int = ...) -> _SageObject: ...

def DihedralPresentation(n: builtins.int) -> _SageObject: ...

def DiCyclicPresentation(n: builtins.int) -> _SageObject: ...

def SymmetricPresentation(n: builtins.int) -> _SageObject: ...

def QuaternionPresentation() -> _SageObject: ...

def AlternatingPresentation(n: builtins.int) -> _SageObject: ...

def KleinFourPresentation() -> _SageObject: ...

def BinaryDihedralPresentation(n: builtins.int) -> _SageObject: ...

def CactusPresentation(n: builtins.int) -> _SageObject: ...
