from collections.abc import Iterator
from sage.groups.abelian_gps.abelian_aut import (
    AbelianGroupAutomorphism,
    AbelianGroupAutomorphismGroup_subgroup,
)
from sage.rings.integer import Integer
type FqfMembershipInput = FqfIsometry | AbelianGroupAutomorphism

class FqfIsometry(AbelianGroupAutomorphism):
    def parent(self, x: None = None) -> FqfOrthogonalGroup: ...

class FqfOrthogonalGroup(AbelianGroupAutomorphismGroup_subgroup):
    def gens(self) -> tuple[FqfIsometry, ...]: ...
    def ngens(self) -> int: ...
    def order(self) -> Integer: ...
    def is_finite(self) -> bool: ...
    def __iter__(self) -> Iterator[FqfIsometry]: ...
    def __contains__(self, x: FqfMembershipInput) -> bool: ...
