from sage.groups.group import Group
from sage.structure.element import Element

class FreeGroupElement(Element): ...

class FreeGroup_class(Group):
    def rank(self) -> int: ...
    def generators(self) -> tuple[FreeGroupElement, ...]: ...
    def is_abelian(self) -> bool: ...

