import builtins

class _SageObject: ...

class GaloisGroup_perm:
    def transitive_number(
        self, algorithm: builtins.str = ..., recompute: builtins.bool = ...
    ) -> _SageObject: ...
    def __init__(
        self,
        field: builtins.object,
        algorithm: builtins.str = ...,
        names: builtins.object = ...,
        gc_numbering: builtins.bool = ...,
    ) -> None: ...
    def ngens(self) -> int: ...

class GaloisSubgroup_perm: ...
