# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GroupSemidirectProductElement:
    def __invert__(self) -> Self: ...
    def to_opposite(self) -> _SageObject: ...

class GroupSemidirectProduct:
    def __init__(self, G: builtins.object, H: builtins.object, twist: builtins.object = ..., act_to_right: builtins.bool = ..., prefix0: builtins.object = ..., prefix1: builtins.object = ..., print_tuple: builtins.bool = ..., category: builtins.object = ...) -> None: ...
    def act_to_right(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def group_generators(self) -> _SageObject: ...
    def product(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def opposite_semidirect_product(self) -> _SageObject: ...
    def construction(self) -> _SageObject: ...
