# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class IndexedGroup:
    def order(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def group_generators(self) -> _SageObject: ...
    gens: _SageObject

class IndexedFreeGroup:
    def __init__(self, indices: builtins.object, prefix: builtins.str, category: builtins.object = ..., **kwds: builtins.object) -> None: ...
    def one(self) -> _SageObject: ...
    def gen(self, x: builtins.object) -> _SageObject: ...
    class Element:
        def __len__(self) -> builtins.int: ...
        length: _SageObject
        def __invert__(self) -> Self: ...
        def to_word_list(self) -> builtins.list[builtins.tuple[_SageObject, ...]]: ...

class IndexedFreeAbelianGroup:
    def __init__(self, indices: builtins.object, prefix: builtins.str, category: builtins.object = ..., **kwds: builtins.object) -> None: ...
    def one(self) -> _SageObject: ...
    def gen(self, x: builtins.object) -> _SageObject: ...
    class Element:
        def __invert__(self) -> Self: ...
        def __floordiv__(self, a: builtins.object) -> Self: ...
        def __pow__(self, n: builtins.int) -> Self: ...
