# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KernelSubgroup:
    def __init__(self, morphism: builtins.object) -> None: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def defining_morphism(self) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def retract(self, x: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    class Element:
        def __invert__(self) -> Self: ...
