from cypari2.gen import Gen
from sage.groups.perm_gps.permgroup_named import TransitiveGroup
from sage.rings.integer import Integer

class PariGroup:
    def __init__(self, x: Gen, degree: int | Integer) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __pari__(self) -> Gen: ...
    def degree(self) -> int | Integer: ...
    def signature(self) -> Integer: ...
    def transitive_number(self) -> Integer: ...
    def label(self) -> str: ...
    def order(self) -> Integer: ...
    def cardinality(self) -> Integer: ...
    def permutation_group(self) -> TransitiveGroup: ...
    def _permgroup_(self) -> TransitiveGroup: ...
