import builtins

class _SageObject: ...

class PariGroup:
    def __init__(self, x: builtins.object, degree: builtins.int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __pari__(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def signature(self) -> _SageObject: ...
    def transitive_number(self) -> _SageObject: ...
    def label(self) -> _SageObject: ...
    def order(self) -> _SageObject: ...
    cardinality: _SageObject

    def permutation_group(self) -> _SageObject: ...
