import builtins
from typing import Self

from sage.structure.element import Element

class _SageObject: ...

class RightAngledArtinGroup:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, G: builtins.object, names: builtins.object = ...
    ) -> _SageObject: ...
    def __init__(self, G: builtins.object, names: builtins.object) -> None: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def ngens(self) -> _SageObject: ...
    def graph(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    one_element: _SageObject

    def cohomology(self, F: builtins.object = ...) -> _SageObject: ...

    class Element:
        def __init__(self, parent: builtins.object, lst: builtins.object) -> None: ...
        def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
        def __pow__(self, n: builtins.int) -> Self: ...
        def __invert__(self) -> Self: ...

class CohomologyRAAG:
    def __init__(self, R: builtins.int, A: builtins.object) -> None: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def ngens(self) -> _SageObject: ...
    def degree_on_basis(self, I: builtins.int) -> _SageObject: ...

    class Element: ...
