from sage.structure.element import Element

class SandpileExamples:
    def Complete(self, n: int) -> Element: ...
    def Cycle(self, n: int) -> Element: ...
    def Diamond(self) -> Element: ...
    def Fan(self, n: int, deg_three_verts: Element | int | str | bool | None) -> Element: ...
    def Grid(self, m: int, n: int) -> Element: ...
    def House(self) -> Element: ...
    def Wheel(self, n: int) -> Element: ...
