from sage.rings.integer import Integer
from sage.structure.element import Element

def sandlib(selector: Element | int | str | bool | None) -> Element: ...
def triangle_sandpile(n: int) -> Element: ...
def aztec_sandpile(n: int) -> Element: ...
def glue_graphs(g: Element, h: Element, glue_g: Element | int | str | bool | None, glue_h: Element | int | str | bool | None) -> Element: ...
def firing_graph(S: Element | int | str | bool | None, eff: Element | int | str | bool | None) -> Element: ...
def parallel_firing_graph(S: Element | int | str | bool | None, eff: Element | int | str | bool | None) -> Element: ...
def admissible_partitions(S: Element | int | str | bool | None, k: int) -> Element: ...
def partition_sandpile(S: Element | int | str | bool | None, p: int) -> Sandpile: ...
def min_cycles(G: Element | int | str | bool | None, v: Element) -> list[Element]: ...
def wilmes_algorithm(M: Element | int | str | bool | None) -> Element: ...

class Sandpile(DiGraph):
    def version(self) -> Element: ...
    def help(self) -> Element: ...
    def _repr_(self) -> str: ...
    def show(self) -> Element: ...
    def show3d(self) -> Element: ...
    def dict(self) -> Element: ...
    def sink(self) -> Element: ...
    def laplacian(self) -> Element: ...
    def reduced_laplacian(self) -> Element: ...
    def group_order(self) -> Element: ...
    def _set_max_stable(self) -> Element: ...
    def max_stable(self) -> Element: ...
    def _set_max_stable_div(self) -> Element: ...
    def max_stable_div(self) -> Element: ...
    def _set_out_degrees(self) -> Element: ...
    def out_degree(self, v: Element) -> Element: ...
    def _set_in_degrees(self) -> Element: ...
    def in_degree(self, v: Element) -> Element: ...
    def _set_burning_config(self) -> Element: ...
    def burning_config(self) -> Element: ...
    def burning_script(self) -> Element: ...
    def nonsink_vertices(self) -> Element: ...
    def all_k_config(self, k: int) -> Element: ...
    def zero_config(self) -> Element: ...
    def _set_identity(self) -> Element: ...
    def identity(self, verbose: bool) -> Element: ...
    def _set_recurrents(self) -> Element: ...
    def recurrents(self, verbose: bool) -> Element: ...
    def _set_superstables(self) -> Element: ...
    def superstables(self, verbose: bool) -> Element: ...
    def _set_group_gens(self) -> Element: ...
    def group_gens(self, verbose: bool) -> list[Element]: ...
    def genus(self) -> Element: ...
    def is_undirected(self) -> bool: ...
    def _set_min_recurrents(self) -> Element: ...
    def min_recurrents(self, verbose: bool) -> Element: ...
    def max_superstables(self, verbose: bool) -> Element: ...
    def tutte_polynomial(self) -> Element: ...
    def _set_avalanche_polynomial(self) -> Element: ...
    def avalanche_polynomial(self, multivariable: Element | int | str | bool | None) -> Element: ...
    def nonspecial_divisors(self, verbose: bool) -> list[Element]: ...
    def canonical_divisor(self) -> Element: ...
    def _set_invariant_factors(self) -> Element: ...
    def invariant_factors(self) -> Element: ...
    def _set_hilbert_function(self) -> Element: ...
    def h_vector(self) -> Element: ...
    def hilbert_function(self) -> Element: ...
    def postulation(self) -> Element: ...
    def _set_smith_form(self) -> Element: ...
    def smith_form(self) -> list[Element]: ...
    def reorder_vertices(self) -> Element: ...
    def _set_jacobian_representatives(self) -> Element: ...
    def jacobian_representatives(self, verbose: bool) -> Element: ...
    def picard_representatives(self, d: int, verbose: bool) -> Element: ...
    def stable_configs(self, smax: Element | int | str | bool | None) -> Element: ...
    def markov_chain(self, state: Element | int | str | bool | None, distrib: Element | int | str | bool | None) -> Element: ...
    def _set_stationary_density(self) -> Element: ...
    def stationary_density(self) -> Element: ...
    def all_k_div(self, k: int) -> Element: ...
    def zero_div(self) -> Element: ...
    def _set_betti_complexes(self) -> Element: ...
    def betti_complexes(self) -> Element: ...
    def _set_ring(self) -> Element: ...
    def _set_ideal(self) -> Element: ...
    def unsaturated_ideal(self) -> Element: ...
    def ideal(self, gens: Element | int | str | bool | None) -> Element: ...
    def ring(self) -> Element: ...
    def _set_resolution(self) -> Element: ...
    def resolution(self, verbose: bool) -> Element: ...
    def _set_groebner(self) -> Element: ...
    def groebner(self) -> Element: ...
    def betti(self, verbose: bool) -> Element: ...
    def solve(self) -> Element: ...
    def _set_points(self) -> None: ...
    def points(self) -> list[Element]: ...
    def symmetric_recurrents(self, orbits: Element | int | str | bool | None) -> Element: ...

class SandpileConfig(dict[Element, Element]):
    def _set_deg(self) -> None: ...
    def deg(self) -> Element: ...
    def sandpile(self) -> Element: ...
    def dualize(self) -> Element: ...
    def fire_vertex(self, v: Element) -> Element: ...
    def fire_script(self, sigma: Element | int | str | bool | None) -> Element: ...
    def unstable(self) -> list[Element]: ...
    def fire_unstable(self) -> Element: ...
    def _set_stabilize(self) -> Element: ...
    def stabilize(self, with_firing_vector: Element | int | str | bool | None) -> Element: ...
    def support(self) -> list[Element]: ...
    def add_random(self, distrib: Element | int | str | bool | None) -> Element: ...
    def order(self) -> Integer: ...
    def is_stable(self) -> bool: ...
    def _set_equivalent_recurrent(self) -> None: ...
    def equivalent_recurrent(self, with_firing_vector: Element | int | str | bool | None) -> Element: ...
    def _set_is_recurrent(self) -> None: ...
    def is_recurrent(self) -> bool: ...
    def _set_equivalent_superstable(self) -> None: ...
    def equivalent_superstable(self, with_firing_vector: Element | int | str | bool | None) -> Element: ...
    def _set_is_superstable(self) -> None: ...
    def is_superstable(self) -> bool: ...
    def is_symmetric(self, orbits: Element | int | str | bool | None) -> bool: ...
    def burst_size(self, v: Element) -> Element: ...

class SandpileDivisor(dict[Element, Element]):
    def _set_q_reduced(self) -> None: ...
    def q_reduced(self, verbose: bool) -> Element: ...
    def is_q_reduced(self) -> bool: ...
    def is_linearly_equivalent(self, D: Element | int | str | bool | None, with_firing_vector: Element | int | str | bool | None) -> bool: ...
    def simulate_threshold(self, distrib: Element | int | str | bool | None) -> Element: ...
    def _set_linear_system(self) -> None: ...
    def _set_polytope(self) -> None: ...
    def polytope(self) -> Polyhedron: ...
    def _set_polytope_integer_pts(self) -> None: ...
    def polytope_integer_pts(self) -> tuple[Element, ...]: ...
    def _set_effective_div(self) -> None: ...
    def effective_div(self, verbose: bool, with_firing_vectors: Element | int | str | bool | None) -> list[Element]: ...
    def _set_rank(self, set_witness: Element | int | str | bool | None) -> None: ...
    def rank(self, with_witness: Element | int | str | bool | None) -> int: ...
    def _set_r_of_D(self, verbose: bool) -> Element: ...
    def weierstrass_rank_seq(self, v: Element) -> Element: ...
    def weierstrass_gap_seq(self, v: Element, weight: Element | int | str | bool | None) -> Element: ...
    def is_weierstrass_pt(self, v: Element) -> bool: ...
    def _set_weierstrass_pts(self) -> Element: ...
    def weierstrass_pts(self, with_rank_seq: Element | int | str | bool | None) -> Element: ...
    def weierstrass_div(self, verbose: bool) -> Element: ...
    def _set_Dcomplex(self) -> Element: ...
    def Dcomplex(self) -> Element: ...
    def _set_life(self) -> Element: ...
    def is_alive(self, cycle: Element | int | str | bool | None) -> bool: ...

class DiGraph: ...

class Polyhedron: ...
