# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def animate(frames: builtins.object, **kwds: builtins.object) -> _SageObject: ...

class Animation:
    def __init__(self, v: builtins.object = ..., **kwds: builtins.object) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __len__(self) -> builtins.int: ...
    def make_image(self, frame: builtins.object, filename: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def png(self, dir: builtins.object = ...) -> _SageObject: ...
    def graphics_array(self, ncols: builtins.int = ...) -> _SageObject: ...
    def gif(self, delay: builtins.int = ..., savefile: builtins.object = ..., iterations: builtins.int = ..., show_path: builtins.bool = ..., use_ffmpeg: builtins.bool = ...) -> _SageObject: ...
    def show(self, delay: builtins.object = ..., iterations: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def ffmpeg(self, savefile: builtins.object = ..., show_path: builtins.bool = ..., output_format: builtins.object = ..., ffmpeg_options: builtins.str = ..., delay: builtins.object = ..., iterations: builtins.int = ..., pix_fmt: builtins.str = ...) -> _SageObject: ...
    def apng(self, savefile: builtins.object = ..., show_path: builtins.bool = ..., delay: builtins.int = ..., iterations: builtins.int = ...) -> _SageObject: ...
    def save(self, filename: builtins.object = ..., show_path: builtins.bool = ..., use_ffmpeg: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...
    def interactive(self, **kwds: builtins.object) -> _SageObject: ...

class APngAssembler:
    magic: _SageObject
    mustmatch: _SageObject
    def __init__(self, out: builtins.object, num_frames: builtins.object, num_plays: builtins.int = ..., delay: builtins.int = ..., delay_denominator: builtins.int = ...) -> None: ...
    def add_frame(self, pngfile: builtins.object, delay: builtins.object = ..., delay_denominator: builtins.object = ...) -> _SageObject: ...
    def set_default(self, pngfile: builtins.object) -> _SageObject: ...
