import builtins

class _SageObject: ...

class BarChart:
    def __init__(
        self, ind: builtins.object, datalist: builtins.object, options: builtins.object
    ) -> None: ...
    def get_minmax_data(self) -> _SageObject: ...

def bar_chart(self, **options: builtins.object) -> _SageObject: ...
