# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BezierPath:
    def __init__(self, path: builtins.object, options: builtins.object) -> None: ...
    def plot3d(self, z: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...
    def get_minmax_data(self) -> _SageObject: ...

def bezier_path(path: builtins.object, **options: builtins.object) -> _SageObject: ...
