import builtins

class _SageObject: ...

class BezierPath:
    def __init__(self, path: builtins.object, options: builtins.object) -> None: ...
    def plot3d(self, z: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...
    def get_minmax_data(self) -> _SageObject: ...

def bezier_path(self, **options: builtins.object) -> _SageObject: ...
