from collections.abc import Iterator

from sage.structure.element import Element

def mod_one(x: Element) -> Element: ...
def html_to_float(c: Element) -> Element: ...
def rgbcolor(c: Element, space: Element | int | str | bool | None) -> Element: ...
def hue(h: Element, s: int, v: Element) -> Element: ...
def float_to_html(r: int, g: Element, b: Element) -> Element: ...
def float_to_integer(r: int, g: Element, b: Element) -> Element: ...
def rainbow(n: int, format: Element | int | str | bool | None) -> Element: ...
def get_cmap(cmap: Element | int | str | bool | None) -> Element: ...
def check_color_data(cfcm: Element | int | str | bool | None) -> Element: ...

class Color:
    def __hash__(self) -> int: ...
    def blend(self, color: Element | int | str | bool | None, fraction: Element | int | str | bool | None) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __getitem__(self, i: int) -> Element: ...
    def rgb(self) -> Element: ...
    def hls(self) -> Element: ...
    def hsl(self) -> Element: ...
    def hsv(self) -> Element: ...
    def html_color(self) -> Element: ...
    def lighter(self, fraction: Element | int | str | bool | None) -> Element: ...
    def darker(self, fraction: Element | int | str | bool | None) -> Element: ...

class ColorsDict(dict[Element, Element]):
    ...

class Colormaps(MutableMapping):
    def load_maps(self) -> Element: ...

class MutableMapping: ...
