# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

DEFAULT_LOGARITHMIC_CONTOUR_BASE: _SageObject
DEFAULT_LINEAR_CONTOUR_BASE: _SageObject
def new_CDF_element(x: builtins.object, y: builtins.object) -> _SageObject: ...

def mag_to_lightness(r: builtins.object, rate: builtins.object = ...) -> _SageObject: ...

def cyclic_logarithmic_mag_to_lightness(r: builtins.object, base: builtins.object = ...) -> _SageObject: ...

def cyclic_linear_mag_to_lightness(r: builtins.object, base: builtins.object = ...) -> _SageObject: ...

def add_lightness_smoothing_to_rgb(rgb: builtins.object, delta: builtins.object) -> _SageObject: ...

def add_contours_to_rgb(rgb: builtins.object, delta: builtins.object, dark_rate: builtins.object = ...) -> _SageObject: ...

class ComplexPlot:
    def __init__(self, rgb_data: builtins.object, x_range: builtins.object, y_range: builtins.object, options: builtins.object) -> None: ...
    def get_minmax_data(self) -> _SageObject: ...

def rgb_to_hls(rgb: builtins.object) -> _SageObject: ...

def hls_to_rgb(hls: builtins.object) -> _SageObject: ...
