from sage.structure.element import Element

def disk(point: Element | int | str | bool | None, radius: Element | int | str | bool | None, angle: Element | int | str | bool | None) -> Element: ...

class Disk(GraphicPrimitive):
    def get_minmax_data(self) -> Element: ...
    def _allowed_options(self) -> Element: ...
    def _repr_(self) -> str: ...
    def _render_on_subplot(self, subplot: Element | int | str | bool | None) -> Element: ...
    def plot3d(self, z: Element) -> Element: ...

class GraphicPrimitive: ...
