from sage.structure.element import Element

def ellipse(center: Element | int | str | bool | None, r1: Element | int | str | bool | None, r2: Element | int | str | bool | None, angle: Element | int | str | bool | None) -> Element: ...

class Ellipse(GraphicPrimitive):
    def get_minmax_data(self) -> Element: ...
    def _allowed_options(self) -> Element: ...
    def _repr_(self) -> str: ...
    def _render_on_subplot(self, subplot: Element | int | str | bool | None) -> Element: ...
    def plot3d(self) -> Element: ...

class GraphicPrimitive: ...
