# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Ellipse:
    def __init__(self, x: builtins.object, y: builtins.object, r1: builtins.object, r2: builtins.object, angle: builtins.object, options: builtins.object) -> None: ...
    def get_minmax_data(self) -> _SageObject: ...
    def plot3d(self) -> _SageObject: ...

def ellipse(center: builtins.object, r1: builtins.object, r2: builtins.object, angle: builtins.int = ..., **options: builtins.object) -> _SageObject: ...
