from sage.structure.element import Element

def histogram(datalist: Element | int | str | bool | None) -> Element: ...

class Histogram(GraphicPrimitive):
    def get_minmax_data(self) -> Element: ...
    def _allowed_options(self) -> Element: ...
    def _repr_(self) -> str: ...
    def _render_on_subplot(self, subplot: Element | int | str | bool | None) -> Element: ...

class GraphicPrimitive: ...
