from sage.structure.element import Element

def hyperbolic_polygon(pts: Element | int | str | bool | None, model: Element | int | str | bool | None, resolution: Element | int | str | bool | None) -> Element: ...
def hyperbolic_triangle(a: Element, b: Element, c: Element, model: Element | int | str | bool | None) -> Element: ...

class HyperbolicPolygon(HyperbolicArcCore):
    def _repr_(self) -> str: ...

class HyperbolicArcCore: ...
