from sage.structure.element import Element

def hyperbolic_regular_polygon(sides: Element | int | str | bool | None, i_angle: Element | int | str | bool | None, center: Element | int | str | bool | None) -> Element: ...

class HyperbolicRegularPolygon(HyperbolicPolygon):
    def _repr_(self) -> str: ...
    def _i_rotation(self, z: Element, alpha: Element | int | str | bool | None) -> Element: ...

class HyperbolicPolygon: ...
