from sage.structure.element import Element

def setup_for_eval_on_grid(funcs: Element | int | str | bool | None, ranges: Element | int | str | bool | None, plot_points: Element | int | str | bool | None, return_vars: Element | int | str | bool | None, imaginary_tolerance: Element | int | str | bool | None) -> Element: ...
def unify_arguments(funcs: Element | int | str | bool | None) -> Element: ...
def get_matplotlib_linestyle(linestyle: Element | int | str | bool | None, return_type: Element | int | str | bool | None) -> Element: ...

class FastCallablePlotWrapper(FastCallableFloatWrapper):
    ...

class FastCallableFloatWrapper: ...
