# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MultiGraphics:
    def __init__(self, graphics_list: builtins.object) -> None: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __setitem__(self, i: builtins.int, g: builtins.object) -> None: ...
    def __len__(self) -> builtins.int: ...
    def matplotlib(self, figure: builtins.object = ..., figsize: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def save(self, filename: builtins.object, figsize: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def save_image(self, filename: builtins.object = ..., *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def show(self, **kwds: builtins.object) -> _SageObject: ...
    def plot(self) -> _SageObject: ...
    def inset(self, graphics: builtins.object, pos: builtins.object = ..., fontsize: builtins.object = ...) -> _SageObject: ...
    def position(self, index: builtins.object) -> _SageObject: ...
    def append(self, graphics: builtins.object, pos: builtins.object = ...) -> _SageObject: ...

class GraphicsArray:
    def __init__(self, array: builtins.object) -> None: ...
    def nrows(self) -> _SageObject: ...
    def ncols(self) -> _SageObject: ...
    def append(self, g: builtins.object) -> _SageObject: ...
    def position(self, index: builtins.object) -> _SageObject: ...
