from typing import Self

from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class MultiGraphics(WithEqualityById, SageObject):
    def _repr_(self) -> str: ...
    def _rich_repr_(self, display_manager: Element | int | str | bool | None) -> Element: ...
    def __getitem__(self, i: int) -> Element: ...
    def __len__(self) -> int: ...
    def matplotlib(self, figure: Element | int | str | bool | None, figsize: Element | int | str | bool | None) -> Element: ...
    def save_image(self, filename: Element | int | str | bool | None) -> Element: ...
    def _latex_(self) -> str: ...
    def show(self) -> Element: ...
    def plot(self) -> Element: ...
    def inset(self, graphics: Element | int | str | bool | None, pos: Element | int | str | bool | None, fontsize: Element | int | str | bool | None) -> Element: ...
    def _add_subplot(self, figure: Element | int | str | bool | None, index: int) -> Self: ...
    def position(self, index: int) -> Element: ...
    def append(self, graphics: Element | int | str | bool | None, pos: Element | int | str | bool | None) -> Element: ...

class GraphicsArray(MultiGraphics):
    def nrows(self) -> Element: ...
    def ncols(self) -> Element: ...

class WithEqualityById: ...
