from sage.structure.element import Element

def SelectiveFormatter(formatter: Element | int | str | bool | None, skip_values: Element | int | str | bool | None) -> Element: ...
def xydata_from_point_list(points: Element | int | str | bool | None) -> Element: ...
def plot(funcs: Element | int | str | bool | None) -> Element: ...
def parametric_plot(funcs: Element | int | str | bool | None) -> Element: ...
def polar_plot(funcs: Element | int | str | bool | None) -> Element: ...
def list_plot(data: Element | int | str | bool | None, plotjoined: Element | int | str | bool | None) -> list[Element]: ...
def plot_loglog(funcs: Element | int | str | bool | None) -> Element: ...
def plot_semilogx(funcs: Element | int | str | bool | None) -> Element: ...
def plot_semilogy(funcs: Element | int | str | bool | None) -> Element: ...
def list_plot_loglog(data: Element | int | str | bool | None, plotjoined: Element | int | str | bool | None) -> list[Element]: ...
def list_plot_semilogx(data: Element | int | str | bool | None, plotjoined: Element | int | str | bool | None) -> list[Element]: ...
def list_plot_semilogy(data: Element | int | str | bool | None, plotjoined: Element | int | str | bool | None) -> list[Element]: ...
def to_float_list(v: Element) -> Element: ...
def reshape(v: Element, n: int, m: int) -> Element: ...
def graphics_array(array: Element | int | str | bool | None, nrows: Element | int | str | bool | None, ncols: Element | int | str | bool | None) -> Element: ...
def multi_graphics(graphics_list: Element | int | str | bool | None) -> Element: ...
def minmax_data(xdata: Element | int | str | bool | None, ydata: Element | int | str | bool | None, dict: Element | int | str | bool | None) -> tuple[Element, ...] | dict[Element, Element]: ...
def adaptive_refinement(f: Element, p1: Element | int | str | bool | None, p2: Element | int | str | bool | None, adaptive_tolerance: Element | int | str | bool | None, adaptive_recursion: Element | int | str | bool | None, level: Element | int | str | bool | None) -> Element: ...
def generate_plot_points(f: Element, xrange: Element | int | str | bool | None, plot_points: Element | int | str | bool | None, adaptive_tolerance: Element | int | str | bool | None, adaptive_recursion: Element | int | str | bool | None, randomize: Element | int | str | bool | None, initial_points: Element | int | str | bool | None) -> Element: ...
