import builtins

class _SageObject: ...

class Point:
    def __init__(
        self, xdata: builtins.object, ydata: builtins.object, options: builtins.object
    ) -> None: ...
    def plot3d(self, z: builtins.int = ..., **kwds: builtins.object) -> _SageObject: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...

def point(self, **kwds: builtins.object) -> _SageObject: ...
def point2d(self, **options: builtins.object) -> _SageObject: ...

points: _SageObject
