from sage.structure.element import Element

def polygon(points: Element | int | str | bool | None) -> Element: ...
def polygon2d(points: Element | int | str | bool | None) -> Element: ...

class Polygon(GraphicPrimitive_xydata):
    def _repr_(self) -> str: ...
    def __getitem__(self, i: int) -> Element: ...
    def __len__(self) -> int: ...
    def _allowed_options(self) -> Element: ...
    def _plot3d_options(self, options: Element | int | str | bool | None) -> Element: ...
    def plot3d(self, z: Element) -> Element: ...
    def _render_on_subplot(self, subplot: Element | int | str | bool | None) -> Element: ...

class GraphicPrimitive_xydata: ...
