# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GraphicPrimitive:
    def __init__(self, options: builtins.object) -> None: ...
    def plot3d(self, **kwds: builtins.object) -> _SageObject: ...
    def set_zorder(self, zorder: builtins.object) -> _SageObject: ...
    def set_options(self, new_options: builtins.object) -> _SageObject: ...
    def options(self) -> _SageObject: ...

class GraphicPrimitive_xydata:
    def get_minmax_data(self) -> _SageObject: ...
