# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class StreamlinePlot:
    def __init__(self, xpos_array: builtins.object, ypos_array: builtins.object, xvec_array: builtins.object, yvec_array: builtins.object, options: builtins.object) -> None: ...
    def get_minmax_data(self) -> _SageObject: ...

def streamline_plot(f_g: builtins.object, xrange: builtins.object, yrange: builtins.object, **options: builtins.object) -> _SageObject: ...
