# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Text:
    def __init__(self, string: builtins.object, point: builtins.object, options: builtins.object) -> None: ...
    def get_minmax_data(self) -> _SageObject: ...
    def plot3d(self, **kwds: builtins.object) -> _SageObject: ...

def text(string: builtins.object, xy: builtins.object, **options: builtins.object) -> _SageObject: ...
