import builtins
from collections.abc import (
    Hashable,
)

from sage.structure.element import Element

class _SageObject: ...

def lrcoef_unsafe(
    self, inner1: builtins.object, inner2: builtins.object
) -> _SageObject: ...
def lrcoef(self, inner1: builtins.object, inner2: builtins.object) -> _SageObject: ...
def mult(
    self,
    part2: builtins.object,
    maxrows: builtins.object = ...,
    level: builtins.object = ...,
    quantum: builtins.object = ...,
) -> dict[Hashable, Element]: ...
def skew(
    self, inner: builtins.object, maxrows: builtins.object = ...
) -> dict[Hashable, Element]: ...
def coprod(self, all: builtins.int = ...) -> dict[Hashable, Element]: ...
def mult_schubert(
    self, w2: builtins.object, rank: builtins.int = ...
) -> dict[Hashable, Element]: ...
def lrskew(
    self,
    inner: builtins.object,
    weight: builtins.object = ...,
    maxrows: builtins.object = ...,
) -> _SageObject: ...
