import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.structure.element import Element

class _SageObject: ...

M2ZSpace: _SageObject

def M2Z(self) -> _SageObject: ...

Id: _SageObject
sig: _SageObject
tau: _SageObject
minone_inf_path: _SageObject
t00: _SageObject
t10: _SageObject
t01: _SageObject
t11: _SageObject

class PollackStevensModularDomain:
    def __init__(
        self,
        N: builtins.int,
        reps: builtins.object,
        indices: builtins.object,
        rels: builtins.object,
        equiv_ind: builtins.object,
    ) -> None: ...
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def level(self) -> _SageObject: ...
    def indices(self, n: builtins.int = ...) -> _SageObject: ...
    def reps(self, n: builtins.int = ...) -> _SageObject: ...
    def relations(self, A: builtins.object = ...) -> _SageObject: ...
    def equivalent_index(self, A: builtins.object) -> _SageObject: ...
    def equivalent_rep(self, A: builtins.object) -> _SageObject: ...
    def P1(self) -> _SageObject: ...

class ManinRelations:
    def __init__(self, N: builtins.int) -> None: ...
    def indices_with_two_torsion(self) -> _SageObject: ...
    def reps_with_two_torsion(self) -> _SageObject: ...
    def two_torsion_matrix(self, A: builtins.object) -> _SageObject: ...
    def indices_with_three_torsion(self) -> _SageObject: ...
    def reps_with_three_torsion(self) -> _SageObject: ...
    def three_torsion_matrix(self, A: builtins.object) -> _SageObject: ...
    def form_list_of_cusps(self) -> _SageObject: ...
    def is_unimodular_path(self, r1: builtins.object, r2: builtins.object) -> bool: ...
    def unimod_to_matrices(
        self, r1: builtins.object, r2: builtins.object
    ) -> _SageObject: ...
    def fd_boundary(self, C: builtins.object) -> _SageObject: ...
    def prep_hecke_on_gen(
        self, l: builtins.object, gen: builtins.object, modulus: builtins.object = ...
    ) -> _SageObject: ...
    def prep_hecke_on_gen_list(
        self, l: builtins.object, gen: builtins.object, modulus: builtins.object = ...
    ) -> _SageObject: ...

def basic_hecke_matrix(self, l: builtins.object) -> _SageObject: ...
