# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

minusproj: _SageObject
class PSModSymAction:
    def __init__(self, actor: builtins.object, MSspace: builtins.object) -> None: ...

class PSModularSymbolElement:
    def __init__(self, map_data: builtins.object, parent: builtins.object, construct: builtins.bool = ...) -> None: ...
    def dict(self) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def values(self) -> _SageObject: ...
    def plus_part(self) -> _SageObject: ...
    def minus_part(self) -> _SageObject: ...
    def hecke(self, ell: builtins.object, algorithm: builtins.str = ...) -> _SageObject: ...
    def valuation(self, p: builtins.int = ...) -> _SageObject: ...
    def diagonal_valuation(self, p: builtins.int) -> _SageObject: ...
    def is_Tq_eigensymbol(self, q: builtins.int, p: builtins.int = ..., M: builtins.int = ...) -> builtins.bool: ...
    def Tq_eigenvalue(self, q: builtins.int, p: builtins.int = ..., M: builtins.int = ..., check: builtins.bool = ...) -> _SageObject: ...
    def is_ordinary(self, p: builtins.int = ..., P: builtins.int = ...) -> builtins.bool: ...
    def evaluate_twisted(self, a: builtins.object, chi: builtins.object) -> _SageObject: ...

class PSModularSymbolElement_symk:
    def p_stabilize(self, p: builtins.int = ..., M: builtins.int = ..., alpha: builtins.object = ..., ap: builtins.object = ..., new_base_ring: builtins.object = ..., ordinary: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...
    def completions(self, p: builtins.int, M: builtins.int) -> _SageObject: ...
    def lift(self, p: builtins.int = ..., M: builtins.int = ..., alpha: builtins.object = ..., new_base_ring: builtins.object = ..., algorithm: builtins.str = ..., eigensymbol: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...
    def p_stabilize_and_lift(self, p: builtins.int, M: builtins.int, alpha: builtins.object = ..., ap: builtins.object = ..., new_base_ring: builtins.object = ..., ordinary: builtins.bool = ..., algorithm: builtins.str = ..., eigensymbol: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

class PSModularSymbolElement_dist:
    def reduce_precision(self, M: builtins.int) -> _SageObject: ...
    def precision_relative(self) -> _SageObject: ...
    def specialize(self, new_base_ring: builtins.object = ...) -> _SageObject: ...
    def padic_lseries(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
