import builtins

class _SageObject: ...

class pAdicLseries:
    def __init__(
        self,
        symb: builtins.object,
        gamma: builtins.object = ...,
        quadratic_twist: builtins.int = ...,
        precision: builtins.int = ...,
    ) -> None: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def symbol(self) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def quadratic_twist(self) -> _SageObject: ...
    def series(self, prec: builtins.int = ...) -> _SageObject: ...
    def interpolation_factor(
        self, ap: builtins.object, chip: builtins.int = ..., psi: builtins.object = ...
    ) -> _SageObject: ...

def log_gamma_binomial(
    self, gamma: builtins.object, n: builtins.int, M: builtins.int
) -> _SageObject: ...
