import builtins

class _SageObject: ...

class PollackStevensModularSymbols_factory:
    def create_key(
        self,
        group: builtins.object,
        weight: builtins.object = ...,
        sign: builtins.int = ...,
        base_ring: builtins.object = ...,
        p: builtins.int = ...,
        prec_cap: builtins.object = ...,
        coefficients: builtins.object = ...,
    ) -> _SageObject: ...
    def create_object(
        self, version: builtins.object, key: builtins.object
    ) -> _SageObject: ...

PollackStevensModularSymbols: _SageObject

class PollackStevensModularSymbolspace:
    def __init__(
        self,
        group: builtins.object,
        coefficients: builtins.object,
        sign: builtins.int = ...,
    ) -> None: ...
    def source(self) -> _SageObject: ...
    def coefficient_module(self) -> _SageObject: ...
    def group(self) -> _SageObject: ...
    def sign(self) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def ncoset_reps(self) -> _SageObject: ...
    def level(self) -> _SageObject: ...
    def precision_cap(self) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def prime(self) -> _SageObject: ...
    def change_ring(self, new_base_ring: builtins.object) -> _SageObject: ...
    def random_element(self, M: builtins.int = ...) -> _SageObject: ...

def cusps_from_mat(self) -> _SageObject: ...
def ps_modsym_from_elliptic_curve(
    self, sign: builtins.int = ..., implementation: builtins.str = ...
) -> _SageObject: ...
def ps_modsym_from_simple_modsym_space(
    self, name: builtins.str = ...
) -> _SageObject: ...
