# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def conjugatingbraid(braid1: builtins.object, braid2: builtins.object) -> _SageObject: ...

def leftnormalform(braid: builtins.object) -> _SageObject: ...

def rightnormalform(braid: builtins.object) -> _SageObject: ...

def greatestcommondivisor(braid1: builtins.object, braid2: builtins.object) -> _SageObject: ...

def leastcommonmultiple(braid1: builtins.object, braid2: builtins.object) -> _SageObject: ...

def centralizer(braid: builtins.object) -> _SageObject: ...

def supersummitset(braid: builtins.object) -> _SageObject: ...

def ultrasummitset(braid: builtins.object) -> _SageObject: ...

def thurston_type(braid: builtins.object) -> _SageObject: ...

def rigidity(braid: builtins.object) -> _SageObject: ...

def sliding_circuits(braid: builtins.object) -> _SageObject: ...

def send_to_sss(braid: builtins.object) -> _SageObject: ...

def send_to_uss(braid: builtins.object) -> _SageObject: ...

def send_to_sc(braid: builtins.object) -> _SageObject: ...

def trajectory(braid: builtins.object) -> _SageObject: ...

def cyclic_slidings(braid: builtins.object) -> _SageObject: ...
