# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def rawMatrix(Field: builtins.object, entries: builtins.object) -> _SageObject: ...

def sage_meataxe_error_handler(err: builtins.object) -> _SageObject: ...

def meataxe_init() -> _SageObject: ...
