# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def contpath_mp(deg: builtins.object, values: builtins.object, y0r: builtins.object, y0i: builtins.object, prec: builtins.object) -> _SageObject: ...

def contpath_mp_comps(deg: builtins.object, values: builtins.object, y0r: builtins.object, y0i: builtins.object, prec: builtins.object, otherdegs: builtins.object, othercoefs: builtins.object) -> _SageObject: ...

def contpath(deg: builtins.object, values: builtins.object, y0r: builtins.object, y0i: builtins.object) -> _SageObject: ...

def contpath_comps(deg: builtins.object, values: builtins.object, y0r: builtins.object, y0i: builtins.object, otherdegrees: builtins.object, othercoefs: builtins.object) -> _SageObject: ...
