# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CycleSpeciesStructure:
    def canonical_label(self) -> _SageObject: ...
    def permutation_group_element(self) -> _SageObject: ...
    def transport(self, perm: builtins.object) -> _SageObject: ...
    def automorphism_group(self) -> _SageObject: ...

class CycleSpecies:
    @staticmethod
    def __classcall__(cls: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def __init__(self, min: builtins.object = ..., max: builtins.object = ..., weight: builtins.object = ...) -> None: ...

CycleSpecies_class: _SageObject
