# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SumSpeciesStructure:
    ...

class SumSpecies:
    def __init__(self, F: builtins.object, G: builtins.object, min: builtins.object = ..., max: builtins.object = ..., weight: builtins.object = ...) -> None: ...
    def left_summand(self) -> _SageObject: ...
    def right_summand(self) -> _SageObject: ...
    def weight_ring(self) -> _SageObject: ...

SumSpecies_class: _SageObject
