from sage.structure.sage_object import SageObject


class AbstractTree(SageObject): ...

class AbstractClonableTree(AbstractTree): ...

class AbstractLabelledTree(AbstractTree): ...

class AbstractLabelledClonableTree(AbstractLabelledTree, AbstractClonableTree): ...
