# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BaxterPermutations:
    @staticmethod
    def __classcall_private__(classe: builtins.object, n: builtins.int = ...) -> _SageObject: ...

class BaxterPermutations_size:
    def __init__(self, n: builtins.int) -> None: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...
    def lattice(self) -> _SageObject: ...

class BaxterPermutations_all:
    def __init__(self, n: builtins.int = ...) -> None: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def to_pair_of_twin_binary_trees(self, p: builtins.int) -> builtins.tuple[_SageObject, ...]: ...
