# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BinaryRecurrenceSequence:
    def __init__(self, b: builtins.object, c: builtins.object, u0: builtins.int = ..., u1: builtins.int = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self, n: builtins.int, modulus: builtins.int = ...) -> _SageObject: ...
    def is_degenerate(self) -> builtins.bool: ...
    def is_geometric(self) -> builtins.bool: ...
    def is_quasigeometric(self) -> builtins.bool: ...
    def is_arithmetic(self) -> builtins.bool: ...
    def period(self, m: builtins.int, *, eventual: builtins.bool = ...) -> _SageObject: ...
    def pthpowers(self, p: builtins.int, Bound: builtins.object) -> _SageObject: ...
