import builtins

class _SageObject: ...

class BinaryRecurrenceSequence:
    u1: builtins.int
    u0: builtins.int

    def __init__(
        self,
        b: builtins.object,
        c: builtins.object,
        u0: builtins.int = ...,
        u1: builtins.int = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __call__(self, n: builtins.int, modulus: builtins.int = ...) -> _SageObject: ...
    def is_degenerate(self) -> bool: ...
    def is_geometric(self) -> bool: ...
    def is_quasigeometric(self) -> bool: ...
    def is_arithmetic(self) -> bool: ...
    def period(
        self, m: builtins.int, *, eventual: builtins.bool = ...
    ) -> _SageObject: ...
    def pthpowers(self, p: builtins.int, Bound: builtins.object) -> _SageObject: ...
