# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def bell_number(n: builtins.int, algorithm: builtins.str = ..., **options: builtins.object) -> _SageObject: ...

def catalan_number(n: builtins.int) -> _SageObject: ...

def narayana_number(n: builtins.int, k: builtins.int) -> _SageObject: ...

def euler_number(n: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def eulerian_number(n: builtins.int, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def eulerian_polynomial(n: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def fibonacci(n: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def lucas_number1(n: builtins.int, P: builtins.int, Q: builtins.int) -> _SageObject: ...

def lucas_number2(n: builtins.int, P: builtins.int, Q: builtins.int) -> _SageObject: ...

def stirling_number1(n: builtins.int, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def stirling_number2(n: builtins.int, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def lah_number(n: builtins.int, k: builtins.int) -> _SageObject: ...

def polygonal_number(s: builtins.object, n: builtins.int) -> _SageObject: ...

class CombinatorialObject:
    def __init__(self, l: builtins.object, copy: builtins.bool = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __hash__(self) -> builtins.int: ...
    def __bool__(self) -> builtins.bool: ...
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __contains__(self, item: builtins.object) -> builtins.bool: ...
    def index(self, key: builtins.object) -> _SageObject: ...

class CombinatorialElement:
    def __init__(self, parent: builtins.object, *args: builtins.object, **kwds: builtins.object) -> None: ...

def tuples(S: builtins.object, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def number_of_tuples(S: builtins.object, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def unordered_tuples(S: builtins.object, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def number_of_unordered_tuples(S: builtins.object, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...

def unshuffle_iterator(a: builtins.object, one: builtins.int = ...) -> _Iterator[_SageObject]: ...

def bell_polynomial(n: builtins.int, k: builtins.int = ..., ordinary: builtins.bool = ...) -> _SageObject: ...

def fibonacci_sequence(start: builtins.int, stop: builtins.int = ..., algorithm: builtins.str = ...) -> _Iterator[_SageObject]: ...

def fibonacci_xrange(start: builtins.int, stop: builtins.int = ..., algorithm: builtins.str = ...) -> _Iterator[_SageObject]: ...

def bernoulli_polynomial(x: builtins.object, n: builtins.int) -> _SageObject: ...
