from collections.abc import Iterable, Iterator
from typing import TypeVar

from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject

_T = TypeVar("_T")

class CombinatorialObject(SageObject, Iterable[_T]):
    def __init__(self, l: Iterable[_T], copy: bool = ...) -> None: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | slice) -> _T | list[_T]: ...
    def __contains__(self, item: _T) -> bool: ...
    def list(self) -> list[_T]: ...

class CombinatorialElement(CombinatorialObject[_T], Element):
    def __init__(self, parent: Parent, lst: Iterable[_T]) -> None: ...
