import builtins
from collections.abc import (
    Iterator,
)
from collections.abc import (
    Iterator as _Iterator,
)
from typing import Self

from sage.rings.integer import Integer

class _SageObject: ...

def bell_number(
    self, algorithm: builtins.str = ..., **options: builtins.object
) -> Integer: ...
def catalan_number(self) -> _SageObject: ...
def narayana_number(self, k: builtins.int) -> Integer: ...
def euler_number(self, algorithm: builtins.str = ...) -> Integer: ...
def eulerian_number(
    self, k: builtins.int, algorithm: builtins.str = ...
) -> Integer: ...
def eulerian_polynomial(self, algorithm: builtins.str = ...) -> _SageObject: ...
def fibonacci(self, algorithm: builtins.str = ...) -> Integer: ...
def lucas_number1(self, P: builtins.int, Q: builtins.int) -> _SageObject: ...
def lucas_number2(self, P: builtins.int, Q: builtins.int) -> _SageObject: ...
def stirling_number1(
    self, k: builtins.int, algorithm: builtins.str = ...
) -> Integer: ...
def stirling_number2(
    self, k: builtins.int, algorithm: builtins.str = ...
) -> Integer: ...
def lah_number(self, k: builtins.int) -> Integer: ...
def polygonal_number(self, n: builtins.int) -> _SageObject: ...

class CombinatorialObject:
    def __init__(self, l: builtins.object, copy: builtins.bool = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __hash__(self) -> builtins.int: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> Integer: ...
    def __getitem__(self, key: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __contains__(self, item: object) -> bool: ...
    def index(self, key: builtins.object) -> _SageObject: ...

class CombinatorialElement:
    def __init__(
        self, parent: builtins.object, *args: builtins.object, **kwds: builtins.object
    ) -> None: ...

def tuples(self, k: builtins.int, algorithm: builtins.str = ...) -> _SageObject: ...
def number_of_tuples(
    self, k: builtins.int, algorithm: builtins.str = ...
) -> Integer: ...
def unordered_tuples(
    self, k: builtins.int, algorithm: builtins.str = ...
) -> _SageObject: ...
def number_of_unordered_tuples(
    self, k: builtins.int, algorithm: builtins.str = ...
) -> Integer: ...
def unshuffle_iterator(self, one: builtins.int = ...) -> Iterator: ...
def bell_polynomial(
    self, k: builtins.int = ..., ordinary: builtins.bool = ...
) -> _SageObject: ...
def fibonacci_sequence(
    self, stop: builtins.int = ..., algorithm: builtins.str = ...
) -> Iterator: ...
def fibonacci_xrange(
    self, stop: builtins.int = ..., algorithm: builtins.str = ...
) -> Iterator: ...
def bernoulli_polynomial(self, n: builtins.int) -> _SageObject: ...
