import builtins
from typing import Self

class _SageObject: ...

def combinatorial_map_trivial(
    self=..., order: builtins.object = ..., name: builtins.str = ...
) -> _SageObject: ...
def combinatorial_map_wrapper(
    self=..., order: builtins.object = ..., name: builtins.str = ...
) -> _SageObject: ...

combinatorial_map: _SageObject

class CombinatorialMap:
    def __init__(
        self, f: builtins.object, order: builtins.object = ..., name: builtins.str = ...
    ) -> None: ...
    def __get__(self, inst: builtins.object, cls: builtins.object = ...) -> Self: ...
    def __call__(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def unbounded_map(self) -> _SageObject: ...
    def order(self) -> _SageObject: ...
    def name(self) -> _SageObject: ...

def combinatorial_maps_in_class(self) -> _SageObject: ...
