
from sage.structure.element import Element
from sage.combinat.partition import Partition
from sage.combinat.root_system.weyl_group import WeylGroupElement

class Core(Element):
    def k(self) -> int: ...
    def to_partition(self) -> Partition: ...
    def to_bounded_partition(self) -> Partition: ...
    def size(self) -> int: ...
    def length(self) -> int: ...
    def to_grassmannian(self) -> WeylGroupElement: ...
    def affine_symmetric_group_simple_action(self, i: int) -> Core: ...
    def affine_symmetric_group_action(self, w: WeylGroupElement | list[int] | tuple[int, ...], transposition: bool = ...) -> Core: ...
    def weak_le(self, other: Core | list[int] | tuple[int, ...]) -> bool: ...
    def weak_covers(self) -> list[Core]: ...
    def strong_le(self, other: Core | list[int] | tuple[int, ...]) -> bool: ...
    def contains(self, other: Core | list[int] | tuple[int, ...]) -> bool: ...
    def strong_covers(self) -> list[Core]: ...
    def strong_down_list(self) -> list[Core]: ...
    def k_boundary(self) -> Partition: ...
    def weak_order_le(self, other: Core) -> bool: ...
