# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def CyclicSievingPolynomial(L: builtins.object, cyc_act: builtins.object = ..., order: builtins.object = ..., get_order: builtins.bool = ...) -> _SageObject: ...

def CyclicSievingCheck(L: builtins.object, cyc_act: builtins.object, f: builtins.object, order: builtins.object = ...) -> builtins.bool: ...

def orbit_decomposition(L: builtins.object, cyc_act: builtins.object) -> builtins.list[builtins.list[_SageObject]]: ...
