import builtins

class _SageObject: ...

def CyclicSievingPolynomial(
    self,
    cyc_act: builtins.object = ...,
    order: builtins.object = ...,
    get_order: builtins.bool = ...,
) -> _SageObject: ...
def CyclicSievingCheck(
    self, cyc_act: builtins.object, f: builtins.object, order: builtins.object = ...
) -> bool: ...
def orbit_decomposition(self, cyc_act: builtins.object) -> list[list]: ...
