import builtins

class _SageObject: ...

def debruijn_sequence(k: builtins.object, n: builtins.object) -> _SageObject: ...
def gen(
    t: builtins.object, p: builtins.object, k: builtins.object, n: builtins.object
) -> _SageObject: ...
def is_debruijn_sequence(
    seq: builtins.object, k: builtins.object, n: builtins.object
) -> builtins.bool: ...

class DeBruijnSequences:
    def __init__(self, k: builtins.object, n: builtins.object) -> None: ...
    def __contains__(self, seq: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
