import builtins

from sage.categories.realizations import Realizations

class _SageObject: ...

class DescentAlgebra:
    def __init__(self, R: builtins.int, n: builtins.int) -> None: ...
    def a_realization(self) -> _SageObject: ...

    class D:
        def __init__(
            self, alg: builtins.object, prefix: builtins.str = ...
        ) -> None: ...
        def product_on_basis(
            self, S: builtins.object, T: builtins.object
        ) -> _SageObject: ...
        def one_basis(self) -> builtins.tuple[_SageObject, ...]: ...
        def to_B_basis(self, S: builtins.object) -> _SageObject: ...
        def to_symmetric_group_algebra_on_basis(
            self, S: builtins.object
        ) -> _SageObject: ...
        def __getitem__(self, S: builtins.object) -> _SageObject: ...

    standard: _SageObject

    class B:
        def __init__(
            self, alg: builtins.object, prefix: builtins.str = ...
        ) -> None: ...
        def product_on_basis(self, p: builtins.int, q: builtins.int) -> _SageObject: ...
        def one_basis(self) -> _SageObject: ...
        def to_I_basis(self, p: builtins.int) -> _SageObject: ...
        def to_D_basis(self, p: builtins.int) -> _SageObject: ...
        def to_nsym(self, p: builtins.int) -> _SageObject: ...

    subset: _SageObject

    class I:
        def __init__(
            self, alg: builtins.object, prefix: builtins.str = ...
        ) -> None: ...
        def product_on_basis(self, p: builtins.int, q: builtins.int) -> _SageObject: ...
        def one(self) -> _SageObject: ...
        def one_basis(self) -> _SageObject: ...
        def to_B_basis(self, p: builtins.int) -> _SageObject: ...
        def idempotent(self, la: builtins.object) -> _SageObject: ...

    idempotent: _SageObject

class DescentAlgebraBases:
    def __init__(self, base: builtins.object) -> None: ...
    def super_categories(self) -> list[Realizations]: ...

    class ParentMethods:
        def __getitem__(self, p: builtins.int) -> _SageObject: ...
        def to_symmetric_group_algebra(self) -> _SageObject: ...
        def to_symmetric_group_algebra_on_basis(
            self, S: builtins.object
        ) -> _SageObject: ...

    class ElementMethods:
        def to_symmetric_group_algebra(self) -> _SageObject: ...
