from collections.abc import Callable, Iterator
from typing import Self

from sage.categories.category import Category
from sage.combinat.free_module import CombinatorialFreeModule
from sage.combinat.permutation import Permutation
from sage.combinat.posets.posets import FinitePoset
from sage.combinat.set_partition import AbstractSetPartition, SetPartition
from sage.graphs.graph import Graph
from sage.groups.perm_gps.permgroup_named import SymmetricGroup
from sage.matrix.matrix0 import Matrix
from sage.modules.with_basis.morphism import ModuleMorphism
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.global_options import GlobalOptions
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.typeset.ascii_art import AsciiArt

def partition_diagrams(k: int | Rational) -> Iterator[SetPartition | list[list[int]]]: ...

def brauer_diagrams(k: int | Rational) -> Iterator[list[tuple[int, int]]]: ...

def temperley_lieb_diagrams(k: int | Rational) -> Iterator[list[tuple[int, int]]]: ...

def planar_diagrams(k: int | Rational) -> Iterator[SetPartition | list[list[int]]]: ...

def planar_partitions_rec(X: list[list[int]]) -> Iterator[list[list[int]]]: ...

def ideal_diagrams(k: int | Rational) -> Iterator[SetPartition | list[list[int]]]: ...

class AbstractPartitionDiagram(AbstractSetPartition):
    def __init__(
        self, parent: AbstractPartitionDiagrams, d: AbstractSetPartition | list[list[int]], check: bool = ...
    ) -> None: ...
    def check(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def base_diagram(self) -> AbstractSetPartition: ...
    diagram: Callable[[], AbstractSetPartition]
    def set_partition(self) -> SetPartition: ...
    def compose(self, other: AbstractPartitionDiagram, check: bool = ...) -> Self: ...
    def propagating_number(self) -> int: ...
    def count_blocks_of_size(self, n: int) -> int: ...
    def order(self) -> int | Rational: ...
    def is_planar(self) -> bool: ...
    def dual(self) -> Self: ...

class IdealDiagram(AbstractPartitionDiagram):
    @staticmethod
    def __classcall_private__(
        cls: type[IdealDiagram], diag: AbstractSetPartition | list[list[int]]
    ) -> IdealDiagram: ...
    def check(self) -> None: ...

class PlanarDiagram(AbstractPartitionDiagram):
    @staticmethod
    def __classcall_private__(
        cls: type[PlanarDiagram], diag: AbstractSetPartition | list[list[int]]
    ) -> PlanarDiagram: ...
    def check(self) -> None: ...

class TemperleyLiebDiagram(AbstractPartitionDiagram):
    @staticmethod
    def __classcall_private__(
        cls: type[TemperleyLiebDiagram], diag: AbstractSetPartition | list[list[int]]
    ) -> TemperleyLiebDiagram: ...
    def check(self) -> None: ...

class PartitionDiagram(AbstractPartitionDiagram):
    @staticmethod
    def __classcall_private__(
        cls: type[PartitionDiagram], diag: AbstractSetPartition | list[list[int]]
    ) -> PartitionDiagram: ...

class BrauerDiagram(AbstractPartitionDiagram):
    @staticmethod
    def __classcall_private__(
        cls: type[BrauerDiagram], diag: AbstractSetPartition | list[list[int]]
    ) -> BrauerDiagram: ...
    def check(self) -> None: ...
    class options:
        NAME: str
        module: str
        option_class: type
        display: str
    def involution_permutation_triple(
        self, curt: bool = ...
    ) -> tuple[list[tuple[int, ...]], list[tuple[int, ...]], list[int] | list[tuple[int, int]]]: ...
    def bijection_on_free_nodes(
        self, two_line: bool = ...
    ) -> list[tuple[int, int]] | tuple[list[int], list[int]]: ...
    def perm(self) -> list[int]: ...
    def is_elementary_symmetric(self) -> bool: ...

class AbstractPartitionDiagrams(Parent, UniqueRepresentation):
    Element: type[AbstractPartitionDiagram]
    def __init__(self, order: int | Rational, category: Category | None = ...) -> None: ...
    def __iter__(self) -> Iterator[AbstractPartitionDiagram]: ...
    def __contains__(self, obj: object) -> bool: ...

class PartitionDiagrams(AbstractPartitionDiagrams):
    Element: type[PartitionDiagram]
    def cardinality(self) -> int: ...

class BrauerDiagrams(AbstractPartitionDiagrams):
    Element: type[BrauerDiagram]
    options: GlobalOptions
    def __contains__(self, obj: object) -> bool: ...
    def cardinality(self) -> int: ...
    def symmetric_diagrams(
        self, l: int | None = ..., perm: Permutation | None = ...
    ) -> list[BrauerDiagram]: ...
    def from_involution_permutation_triple(
        self, D1_D2_pi: tuple[list[list[int]], list[list[int]], Permutation]
    ) -> BrauerDiagram: ...

class TemperleyLiebDiagrams(AbstractPartitionDiagrams):
    Element: type[TemperleyLiebDiagram]
    def cardinality(self) -> int: ...
    def __contains__(self, obj: object) -> bool: ...

class PlanarDiagrams(AbstractPartitionDiagrams):
    Element: type[PlanarDiagram]
    def cardinality(self) -> int: ...
    def __contains__(self, obj: object) -> bool: ...

class IdealDiagrams(AbstractPartitionDiagrams):
    Element: type[IdealDiagram]
    def __contains__(self, obj: object) -> bool: ...

class DiagramAlgebra(CombinatorialFreeModule):
    def __init__(
        self,
        k: int | Rational,
        q: Element | int,
        base_ring: Ring,
        prefix: str,
        diagrams: AbstractPartitionDiagrams,
        category: Category | None = ...,
    ) -> None: ...
    def __getitem__(self, d: AbstractSetPartition) -> Element: ...
    def order(self) -> int | Rational: ...
    def set_partitions(self) -> Iterator[AbstractSetPartition]: ...
    class Element(CombinatorialFreeModule.Element):
        def diagram(self) -> AbstractSetPartition: ...
        def diagrams(self) -> list[AbstractSetPartition]: ...

class UnitDiagramMixin:
    def one_basis(self) -> AbstractSetPartition: ...

class DiagramBasis(DiagramAlgebra):
    def product_on_basis(self, d1: AbstractSetPartition, d2: AbstractSetPartition) -> Element: ...

class PartitionAlgebra(DiagramBasis, UnitDiagramMixin):
    @staticmethod
    def __classcall_private__(
        cls: type[PartitionAlgebra],
        k: int | Rational,
        q: Element | int,
        base_ring: Ring | None = ...,
        prefix: str = ...,
    ) -> PartitionAlgebra: ...
    def __init__(
        self, k: int | Rational, q: Element | int, base_ring: Ring, prefix: str
    ) -> None: ...
    def orbit_basis(self) -> OrbitBasis: ...
    def a(self, i: int) -> Element: ...
    generator_a: Callable[[int], Element]
    def e(self, i: int) -> Element: ...
    generator_e: Callable[[int], Element]
    def s(self, i: int) -> Element: ...
    generator_s: Callable[[int], Element]
    def sigma(self, i: int) -> Element: ...
    def jucys_murphy_element(self, i: int) -> Element: ...
    L: Callable[[int], Element]
    def potts_representation(self, y: Element | None = ...) -> PottsRepresentation: ...
    class Element(DiagramBasis.Element):
        def to_orbit_basis(self) -> OrbitBasis.Element: ...
        def dual(self) -> Self: ...

class OrbitBasis(DiagramAlgebra):
    @staticmethod
    def __classcall_private__(cls: type[OrbitBasis], *args: object) -> OrbitBasis: ...
    def __init__(self, alg: PartitionAlgebra) -> None: ...
    def one(self) -> Element: ...
    def diagram_basis(self) -> PartitionAlgebra: ...
    def product_on_basis(self, d1: AbstractSetPartition, d2: AbstractSetPartition) -> Element: ...
    class Element(DiagramBasis.Element):
        def to_diagram_basis(self) -> DiagramAlgebra.Element: ...

class SubPartitionAlgebra(DiagramBasis):
    def __init__(
        self,
        k: int | Rational,
        q: Element | int,
        base_ring: Ring,
        prefix: str,
        diagrams: AbstractPartitionDiagrams,
        category: Category | None = ...,
    ) -> None: ...
    def ambient(self) -> PartitionAlgebra: ...
    def lift(self) -> ModuleMorphism: ...
    def retract(self, x: PartitionAlgebra.Element) -> Element: ...
    class Element(DiagramBasis.Element):
        def to_orbit_basis(self) -> OrbitBasis.Element: ...

class BrauerAlgebra(SubPartitionAlgebra, UnitDiagramMixin):
    @staticmethod
    def __classcall_private__(
        cls: type[BrauerAlgebra],
        k: int | Rational,
        q: Element | int,
        base_ring: Ring | None = ...,
        prefix: str = ...,
    ) -> BrauerAlgebra: ...
    def __init__(
        self, k: int | Rational, q: Element | int, base_ring: Ring, prefix: str
    ) -> None: ...
    options: GlobalOptions
    def jucys_murphy(self, j: int) -> Element: ...

class HalfTemperleyLiebDiagrams(UniqueRepresentation, Parent):
    def __init__(self, order: int | Rational, defects: int) -> None: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __contains__(self, obj: object) -> bool: ...
    def cardinality(self) -> int: ...
    class Element(AbstractPartitionDiagram):
        def defects(self) -> int: ...
        def check(self) -> None: ...

class TemperleyLiebAlgebra(SubPartitionAlgebra, UnitDiagramMixin):
    @staticmethod
    def __classcall_private__(
        cls: type[TemperleyLiebAlgebra],
        k: int | Rational,
        q: Element | int,
        base_ring: Ring | None = ...,
        prefix: str = ...,
    ) -> TemperleyLiebAlgebra: ...
    def __init__(
        self, k: int | Rational, q: Element | int, base_ring: Ring, prefix: str
    ) -> None: ...
    def cell_poset(self) -> FinitePoset: ...
    def cell_module_indices(self, la: int) -> HalfTemperleyLiebDiagrams: ...
    def cellular_involution(self, x: Element) -> Element: ...

class PlanarAlgebra(SubPartitionAlgebra, UnitDiagramMixin):
    @staticmethod
    def __classcall_private__(
        cls: type[PlanarAlgebra],
        k: int | Rational,
        q: Element | int,
        base_ring: Ring | None = ...,
        prefix: str = ...,
    ) -> PlanarAlgebra: ...
    def __init__(
        self, k: int | Rational, q: Element | int, base_ring: Ring, prefix: str
    ) -> None: ...

class PropagatingIdeal(SubPartitionAlgebra):
    @staticmethod
    def __classcall_private__(
        cls: type[PropagatingIdeal],
        k: int | Rational,
        q: Element | int,
        base_ring: Ring | None = ...,
        prefix: str = ...,
    ) -> PropagatingIdeal: ...
    def __init__(
        self, k: int | Rational, q: Element | int, base_ring: Ring, prefix: str
    ) -> None: ...
    class Element(SubPartitionAlgebra.Element):
        def __pow__(self, n: int) -> Self: ...

def TL_diagram_ascii_art(
    diagram: TemperleyLiebDiagram, use_unicode: bool = ..., blobs: list[int] = ...
) -> AsciiArt: ...

def diagram_latex(
    diagram: AbstractPartitionDiagram,
    fill: bool = ...,
    edge_options: dict[str, object] | None = ...,
    edge_additions: dict[str, object] | None = ...,
) -> str: ...

class PottsRepresentation(CombinatorialFreeModule):
    def __init__(self, PA: PartitionAlgebra, y: Element | None) -> None: ...
    def __getitem__(self, ind: tuple[int, ...]) -> Element: ...
    def partition_algebra(self) -> PartitionAlgebra: ...
    def number_of_factors(self) -> int: ...
    def number_of_colors(self) -> int: ...
    def magnetic_field_direction(self) -> Element | None: ...
    def symmetric_group(self) -> SymmetricGroup: ...
    def representation_matrix(self, elt: Permutation) -> Matrix: ...
    class Element(CombinatorialFreeModule.Element): ...

def is_planar(sp: AbstractSetPartition) -> bool: ...

def to_graph(sp: AbstractSetPartition) -> Graph: ...

def pair_to_graph(sp1: AbstractSetPartition, sp2: AbstractSetPartition) -> Graph: ...

def propagating_number(sp: AbstractSetPartition) -> int: ...

def to_set_partition(l: list[list[int]], k: int | Rational | None = ...) -> SetPartition | list[object]: ...

def to_Brauer_partition(l: list[list[int]], k: int | Rational | None = ...) -> SetPartition | list[object]: ...

def identity_set_partition(k: int | Rational) -> list[list[int]]: ...
