from typing import overload
from collections.abc import Iterator

from sage.structure.unique_representation import UniqueRepresentation
from sage.structure.parent import Parent
from sage.combinat.composition import Composition
from sage.combinat.tableau import Tableau
from sage.combinat.combinat import CombinatorialElement

class BinaryTree: ...
class TamariIntervalPoset: ...
class Graphics: ...

class DyckWord(CombinatorialElement):
    def __classcall_private__(cls, dw: object, noncrossing_partition: object = ..., area_sequence: object = ..., heights_sequence: object = ..., catalan_code: object = ...) -> DyckWord: ...
    def __init__(self, parent: object, l: object, latex_options: object = ...) -> None: ...
    def set_latex_options(self, D: dict[str, object] | None = ...) -> None: ...
    def latex_options(self) -> dict[str, object]: ...
    def to_path_string(self, unicode: bool = ...) -> str: ...
    def pretty_print(self, type: str = ..., labelling: tuple[int, ...] | list[int] | None = ..., underpath: bool = ...) -> None: ...
    def plot(self, **kwds: object) -> Graphics: ...
    def length(self) -> int: ...
    def number_of_open_symbols(self) -> int: ...
    def number_of_close_symbols(self) -> int: ...
    def is_complete(self) -> bool: ...
    def height(self) -> int: ...
    def heights(self) -> tuple[int, ...]: ...
    def associated_parenthesis(self, pos: int) -> int | None: ...
    def ascent_prime_decomposition(self) -> list[DyckWord]: ...
    def catalan_factorization(self) -> list[DyckWord]: ...
    def number_of_initial_rises(self) -> int: ...
    def peaks(self) -> list[int]: ...
    def number_of_peaks(self) -> int: ...
    def valleys(self) -> list[int]: ...
    def number_of_valleys(self) -> int: ...
    def position_of_first_return(self) -> int | None: ...
    def positions_of_double_rises(self) -> list[int]: ...
    def number_of_double_rises(self) -> int: ...
    def returns_to_zero(self) -> list[int]: ...
    def touch_points(self) -> list[int]: ...
    def touch_composition(self) -> Composition: ...
    def number_of_touch_points(self) -> int: ...
    def rise_composition(self) -> Composition: ...
    def to_standard_tableau(self) -> Tableau: ...
    def to_tamari_sorting_tuple(self) -> tuple[int, ...]: ...
    def to_binary_tree(self, usemap: str = ...) -> BinaryTree: ...
    def to_binary_tree_tamari(self) -> BinaryTree: ...
    def tamari_interval(self, other: DyckWord) -> TamariIntervalPoset: ...
    def to_area_sequence(self) -> list[int]: ...
    def area(self) -> int: ...
    def bounce(self) -> int: ...
    def reading_word(self) -> tuple[int, ...]: ...

class DyckWords(UniqueRepresentation, Parent):
    def __classcall_private__(cls, k1: int | None = ..., k2: int | None = ..., complete: bool = ...) -> Parent: ...
    def __contains__(self, x: object) -> bool: ...
    def from_heights(self, heights: list[int] | tuple[int, ...]) -> DyckWord: ...
    def min_from_heights(self, heights: list[int] | tuple[int, ...]) -> DyckWord: ...
