import builtins
from collections.abc import (
    Iterator as _Iterator,
)
from typing import Self

from sage.combinat.words.morphism import WordMorphism
from sage.structure.element import Element

class _SageObject: ...

cm: _SageObject

class Face:
    def __init__(
        self, v: builtins.object, t: builtins.object, color: builtins.object = ...
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def vector(self) -> _SageObject: ...
    def type(self) -> _SageObject: ...
    def color(self, color: builtins.object = ...) -> _SageObject: ...

class Patch:
    def __init__(
        self, faces: builtins.object, face_contour: builtins.object = ...
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __sub__(self, other: builtins.object) -> Self: ...
    def union(self, other: builtins.object) -> Patch: ...
    def difference(self, other: builtins.object) -> Patch: ...
    def dimension(self) -> int | None: ...
    def faces_of_vector(self, v: builtins.object) -> list[Face]: ...
    def faces_of_type(self, t: builtins.object) -> list[Face]: ...
    def faces_of_color(self, color: builtins.object) -> list[Face]: ...
    def translate(self, v: builtins.object) -> Patch: ...
    def occurrences_of(self, other: builtins.object) -> list[Element]: ...
    def repaint(self, cmap: builtins.str = ...) -> None: ...
    def plot(
        self, projmat: builtins.object = ..., opacity: builtins.float = ...
    ) -> Graphics: ...
    def plot3d(self) -> _SageObject: ...
    def plot_tikz(
        self,
        projmat: builtins.object = ...,
        print_tikz_env: builtins.bool = ...,
        edgecolor: builtins.str = ...,
        scale: builtins.float = ...,
        drawzero: builtins.bool = ...,
        extra_code_before: builtins.str = ...,
        extra_code_after: builtins.str = ...,
    ) -> str: ...

class E1Star:
    def __init__(self, sigma: builtins.object, method: builtins.str = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __call__(
        self, patch: builtins.object, iterations: builtins.int = ...
    ) -> Patch: ...
    def __mul__(self, other: builtins.object) -> E1Star: ...
    def matrix(self) -> _SageObject: ...
    def inverse_matrix(self) -> _SageObject: ...
    def sigma(self) -> WordMorphism: ...
