import builtins

from sage.combinat.finite_state_machine import Automaton, Transducer

class _SageObject: ...

class AutomatonGenerators:
    def AnyLetter(self, input_alphabet: builtins.object) -> Automaton: ...
    def AnyWord(self, input_alphabet: builtins.object) -> Automaton: ...
    def EmptyWord(self, input_alphabet: builtins.object = ...) -> Automaton: ...
    def Word(
        self, word: builtins.object, input_alphabet: builtins.object = ...
    ) -> Automaton: ...
    def ContainsWord(
        self, word: builtins.object, input_alphabet: builtins.object
    ) -> Automaton: ...

class TransducerGenerators:
    def Identity(self, input_alphabet: builtins.object) -> Transducer: ...
    def CountSubblockOccurrences(
        self, block: builtins.object, input_alphabet: builtins.object
    ) -> Transducer: ...
    def Wait(
        self, input_alphabet: builtins.object, threshold: builtins.int = ...
    ) -> Transducer: ...
    def map(
        self, f: builtins.object, input_alphabet: builtins.object
    ) -> Transducer: ...
    def operator(
        self,
        operator: builtins.object,
        input_alphabet: builtins.object,
        number_of_operands: builtins.int = ...,
    ) -> Transducer: ...
    def all(
        self, input_alphabet: builtins.object, number_of_operands: builtins.int = ...
    ) -> Transducer: ...
    def any(
        self, input_alphabet: builtins.object, number_of_operands: builtins.int = ...
    ) -> Transducer: ...
    def add(
        self, input_alphabet: builtins.object, number_of_operands: builtins.int = ...
    ) -> Transducer: ...
    def sub(self, input_alphabet: builtins.object) -> Transducer: ...
    def weight(
        self, input_alphabet: builtins.object, zero: builtins.int = ...
    ) -> Transducer: ...
    def abs(self, input_alphabet: builtins.object) -> Transducer: ...
    def GrayCode(self) -> Transducer: ...
    RecursionRule: _SageObject

    def Recursion(
        self,
        recursions: builtins.object,
        base: builtins.object,
        function: builtins.object = ...,
        var: builtins.object = ...,
        input_alphabet: builtins.object = ...,
        word_function: builtins.object = ...,
        is_zero: builtins.object = ...,
        output_rings: builtins.list[_SageObject] = ...,
    ) -> Transducer: ...

automata: _SageObject
transducers: _SageObject
