import builtins
from typing import Self

from sage.structure.element import Element

class _SageObject: ...

class FreePreLieAlgebra:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, R: builtins.int, names: builtins.object = ...
    ) -> _SageObject: ...
    def __init__(self, R: builtins.int, names: builtins.object = ...) -> None: ...
    def variable_names(self) -> _SageObject: ...
    def gen(self, i: builtins.int) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    def gens(self) -> tuple[Element, ...]: ...
    def degree_on_basis(self, t: builtins.object) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def product_on_basis(
        self, x: builtins.object, y: builtins.object
    ) -> _SageObject: ...
    pre_Lie_product_on_basis: _SageObject

    def pre_Lie_product(self) -> _SageObject: ...
    def bracket_on_basis(
        self, x: builtins.object, y: builtins.object
    ) -> _SageObject: ...
    def nap_product_on_basis(
        self, x: builtins.object, y: builtins.object
    ) -> _SageObject: ...
    def nap_product(self) -> _SageObject: ...
    def corolla(
        self, x: builtins.object, y: builtins.object, n: builtins.int, N: builtins.int
    ) -> _SageObject: ...
    def group_product(
        self,
        x: builtins.object,
        y: builtins.object,
        n: builtins.int,
        N: builtins.int = ...,
    ) -> _SageObject: ...
    def construction(self) -> _SageObject: ...

    class Element:
        def lift(self) -> _SageObject: ...
        def valuation(self) -> _SageObject: ...

class PreLieFunctor:
    rank: _SageObject

    def __init__(self, vars: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def merge(self, other: builtins.object) -> _SageObject: ...

def tree_from_sortkey(self, labels: builtins.bool = ...) -> _SageObject: ...
def corolla_gen(
    self, list_ty: builtins.object, labels: builtins.bool = ...
) -> _SageObject: ...
