from collections.abc import Iterable, Callable

from sage.modules.module import Module
from sage.structure.indexed_generators import IndexedGenerators
from sage.structure.unique_representation import UniqueRepresentation
from sage.rings.ring import CommutativeRing, CommutativeRingElement
from sage.sets.family import Family
from sage.rings.infinity import PlusInfinity
import builtins

class CombinatorialFreeModule(UniqueRepresentation, Module, IndexedGenerators):
    class Element: ...
    def base_ring(self) -> CommutativeRing: ...
    def basis(self) -> Family: ...
    def an_element(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...
    def ngens(self) -> int: ...
    def gen(self, i: int) -> Element: ...
    
    # Existing methods
    def element_class(self) -> type: ...
    def construction(self) -> tuple[builtins.object, CommutativeRing] | None: ...
    def change_ring(self, R: CommutativeRing) -> CombinatorialFreeModule: ...
    def dimension(self) -> int | PlusInfinity: ...
    def is_exact(self) -> bool: ...
    def set_order(self, order: builtins.object) -> None: ...
    def get_order(self) -> list[builtins.object]: ...
    def get_order_key(self) -> Callable[[builtins.object], builtins.object]: ...
    def from_vector(self, vector: builtins.object, order: builtins.object = ..., coerce: bool = ...) -> Element: ...
    def sum(self, iter_of_elements: Iterable[Element]) -> Element: ...
    def linear_combination(self, iter_of_elements_coeff: Iterable[tuple[Element, CommutativeRingElement]], factor_on_left: bool = ...) -> Element: ...
    def term(self, index: builtins.object, coeff: CommutativeRingElement = ...) -> Element: ...
    def monomial(self, index: builtins.object) -> Element: ...
    def sum_of_terms(self, terms: Iterable[tuple[builtins.object, CommutativeRingElement]], distinct: bool = ...) -> Element: ...
    def zero(self) -> Element: ...
