import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

R: _SageObject
L: _SageObject
U: _SageObject
D: _SageObject
FPL_edges: _SageObject
FPL_turns: _SageObject

class FullyPackedLoop:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, generator: builtins.object
    ) -> _SageObject: ...
    def __init__(self, parent: builtins.object, generator: builtins.object) -> None: ...
    def to_alternating_sign_matrix(self) -> _SageObject: ...
    def plot(self, **options: builtins.object) -> _SageObject: ...
    def gyration(self) -> _SageObject: ...
    def link_pattern(self) -> _SageObject: ...
    def six_vertex_model(self) -> _SageObject: ...

class FullyPackedLoops:
    def __init__(self, n: builtins.int) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __contains__(self, fpl: object) -> bool: ...
    Element: _SageObject

    def size(self) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
