from collections.abc import Iterable, Iterator, Sequence
from typing import Self

from sage.combinat.tableau import SemistandardTableau
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.structure.element import RingElement
from sage.structure.list_clone import ClonableArray
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

type GelfandTsetlinRow = list[int | Integer]
type GelfandTsetlinData = Iterable[Iterable[int | Integer]]

class GelfandTsetlinPattern(
    ClonableArray[GelfandTsetlinRow],
):
    @staticmethod
    def __classcall_private__(
        cls: type[GelfandTsetlinPattern],
        gt: GelfandTsetlinData,
    ) -> GelfandTsetlinPattern: ...
    def parent(self) -> GelfandTsetlinPatterns: ...
    def check(self) -> None: ...
    def _hash_(self) -> int: ...
    def _repr_diagram(self) -> str: ...
    def pp(self) -> None: ...
    def _latex_(self) -> str: ...
    def to_tableau(self) -> SemistandardTableau: ...
    def boxed_entries(self) -> tuple[tuple[int, int], ...]: ...
    def circled_entries(self) -> tuple[tuple[int, int], ...]: ...
    def special_entries(self) -> tuple[tuple[int, int], ...]: ...
    def number_of_boxes(self) -> int: ...
    def number_of_circles(self) -> int: ...
    def number_of_special_entries(self) -> int: ...
    def is_strict(self) -> bool: ...
    def row_sums(self) -> list[int | Integer]: ...
    def weight(self) -> tuple[int | Integer, ...]: ...
    def Tokuyama_coefficient(
        self,
        name: str = ...,
    ) -> RingElement: ...
    def bender_knuth_involution(
        self,
        i: int | Integer,
    ) -> GelfandTsetlinPattern: ...

class GelfandTsetlinPatterns(
    UniqueRepresentation,
    Parent[GelfandTsetlinPattern],
):
    Element: type[GelfandTsetlinPattern]
    element_class: type[GelfandTsetlinPattern]

    @staticmethod
    def __classcall_private__(
        cls: type[GelfandTsetlinPatterns],
        n: int | Integer | None = ...,
        k: int | Integer | None = ...,
        strict: bool = ...,
        top_row: Sequence[int | Integer] | None = ...,
    ) -> GelfandTsetlinPatterns | GelfandTsetlinPatternsTopRow: ...
    def __init__(
        self,
        n: int | Integer | None,
        k: int | Integer | None,
        strict: bool,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def __contains__(self, gt: object) -> bool: ...
    def _element_constructor_(
        self,
        gt: GelfandTsetlinData | GelfandTsetlinPattern,
    ) -> GelfandTsetlinPattern: ...
    def _coerce_map_from_(self, S: object) -> bool | None: ...
    def __iter__(self) -> Iterator[GelfandTsetlinPattern]: ...
    def random_element(self) -> GelfandTsetlinPattern: ...

class GelfandTsetlinPatternsTopRow(GelfandTsetlinPatterns):
    def __init__(
        self,
        top_row: Sequence[int | Integer],
        strict: bool,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def __contains__(self, gt: object) -> bool: ...
    def __iter__(self) -> Iterator[GelfandTsetlinPattern]: ...
    def random_element(self) -> GelfandTsetlinPattern: ...
