# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def GraphPaths(g: builtins.object, source: builtins.object = ..., target: builtins.object = ...) -> _SageObject: ...

class GraphPaths_common:
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def outgoing_edges(self, v: builtins.object) -> _SageObject: ...
    def incoming_edges(self, v: builtins.object) -> _SageObject: ...
    def outgoing_paths(self, v: builtins.object) -> _SageObject: ...
    def incoming_paths(self, v: builtins.object) -> _SageObject: ...
    def paths_from_source_to_target(self, source: builtins.object, target: builtins.object) -> _SageObject: ...
    def paths(self) -> _SageObject: ...

class GraphPaths_all:
    def __init__(self, g: builtins.object) -> None: ...
    def list(self) -> _SageObject: ...

class GraphPaths_t:
    def __init__(self, g: builtins.object, target: builtins.object) -> None: ...
    def list(self) -> _SageObject: ...

class GraphPaths_s:
    def __init__(self, g: builtins.object, source: builtins.object) -> None: ...
    def list(self) -> _SageObject: ...

class GraphPaths_st:
    def __init__(self, g: builtins.object, source: builtins.object, target: builtins.object) -> None: ...
    def list(self) -> _SageObject: ...
