# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class IntegerMatrices:
    @staticmethod
    def __classcall__(cls: builtins.object, row_sums: builtins.object, column_sums: builtins.object) -> _SageObject: ...
    def __init__(self, row_sums: builtins.object, column_sums: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def cardinality(self) -> _SageObject: ...
    def row_sums(self) -> _SageObject: ...
    def column_sums(self) -> _SageObject: ...
    def to_composition(self, x: builtins.object) -> _SageObject: ...

def integer_matrices_generator(row_sums: builtins.object, column_sums: builtins.object) -> _SageObject: ...
