# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class TamariIntervalPoset:
    @staticmethod
    def __classcall_private__(cls: builtins.object, *args: builtins.object, **opts: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, size: builtins.int, relations: builtins.object = ..., check: builtins.bool = ...) -> None: ...
    def set_latex_options(self, D: builtins.object) -> _SageObject: ...
    def latex_options(self) -> builtins.dict[_SageObject, _SageObject]: ...
    def plot(self, **kwds: builtins.object) -> _SageObject: ...
    def poset(self) -> _SageObject: ...
    def factor(self) -> builtins.list[TamariIntervalPoset]: ...
    def __hash__(self) -> builtins.int: ...
    def increasing_cover_relations(self) -> builtins.list[builtins.tuple[builtins.int, builtins.int]]: ...
    def increasing_roots(self) -> builtins.list[builtins.int]: ...
    def increasing_children(self, v: builtins.object) -> builtins.list[builtins.int]: ...
    def increasing_parent(self, v: builtins.object) -> builtins.int | None: ...
    def decreasing_cover_relations(self) -> builtins.list[builtins.tuple[builtins.int, builtins.int]]: ...
    def decreasing_roots(self) -> builtins.list[builtins.int]: ...
    def decreasing_children(self, v: builtins.object) -> builtins.list[builtins.int]: ...
    def decreasing_parent(self, v: builtins.object) -> builtins.int | None: ...
    def le(self, e1: builtins.object, e2: builtins.object) -> builtins.bool: ...
    def lt(self, e1: builtins.object, e2: builtins.object) -> builtins.bool: ...
    def ge(self, e1: builtins.object, e2: builtins.object) -> builtins.bool: ...
    def gt(self, e1: builtins.object, e2: builtins.object) -> builtins.bool: ...
    def size(self) -> _SageObject: ...
    def cubical_coordinates(self) -> _SageObject: ...
    def complement(self) -> _SageObject: ...
    def left_branch_involution(self) -> _SageObject: ...
    def rise_contact_involution(self) -> _SageObject: ...
    def insertion(self, i: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[builtins.int]: ...
    def contains_interval(self, other: builtins.object) -> builtins.bool: ...
    def lower_contains_interval(self, other: builtins.object) -> builtins.bool: ...
    def upper_contains_interval(self, other: builtins.object) -> builtins.bool: ...
    def is_linear_extension(self, perm: builtins.object) -> builtins.bool: ...
    def contains_binary_tree(self, binary_tree: builtins.object) -> builtins.bool: ...
    def contains_dyck_word(self, dyck_word: builtins.object) -> builtins.bool: ...
    def intersection(self, other: builtins.object) -> _SageObject: ...
    def initial_forest(self) -> _SageObject: ...
    def final_forest(self) -> _SageObject: ...
    def is_initial_interval(self) -> builtins.bool: ...
    def is_final_interval(self) -> builtins.bool: ...
    def lower_binary_tree(self) -> _SageObject: ...
    def lower_dyck_word(self) -> _SageObject: ...
    def upper_binary_tree(self) -> _SageObject: ...
    def upper_dyck_word(self) -> _SageObject: ...
    def blossoming_tree(self) -> _SageObject: ...
    def subposet(self, start: builtins.int, end: builtins.object) -> _SageObject: ...
    sub_poset: _SageObject
    def min_linear_extension(self) -> _SageObject: ...
    def max_linear_extension(self) -> _SageObject: ...
    def linear_extensions(self) -> _SageObject: ...
    def lower_contained_intervals(self) -> _SageObject: ...
    def interval_cardinality(self) -> _SageObject: ...
    def binary_trees(self) -> _Iterator[_SageObject]: ...
    def dyck_words(self) -> _Iterator[_SageObject]: ...
    def maximal_chain_tamari_intervals(self) -> _SageObject: ...
    def maximal_chain_binary_trees(self) -> _Iterator[_SageObject]: ...
    def maximal_chain_dyck_words(self) -> _Iterator[_SageObject]: ...
    def tamari_inversions(self) -> builtins.list[builtins.tuple[builtins.int, builtins.int]]: ...
    def tamari_inversions_iter(self) -> _Iterator[builtins.tuple[builtins.int, builtins.int]]: ...
    def number_of_tamari_inversions(self) -> _SageObject: ...
    def number_of_new_components(self) -> _SageObject: ...
    def new_decomposition(self) -> _SageObject: ...
    def decomposition_to_triple(self) -> _SageObject: ...
    def grafting_tree(self) -> _SageObject: ...
    def is_new(self) -> builtins.bool: ...
    def is_simple(self) -> builtins.bool: ...
    def is_synchronized(self) -> builtins.bool: ...
    def is_modern(self) -> builtins.bool: ...
    def is_infinitely_modern(self) -> builtins.bool: ...
    def is_exceptional(self) -> builtins.bool: ...
    def is_dexter(self) -> builtins.bool: ...
    def is_indecomposable(self) -> builtins.bool: ...
    def is_connected(self) -> builtins.bool: ...

class TamariIntervalPosets:
    @staticmethod
    def __classcall_private__(cls: builtins.object, n: builtins.int = ...) -> _SageObject: ...
    class options:
        NAME: _SageObject
        module: _SageObject
        latex_tikz_scale: _SageObject
        latex_line_width_scalar: _SageObject
        latex_color_decreasing: _SageObject
        latex_color_increasing: _SageObject
        latex_hspace: _SageObject
        latex_vspace: _SageObject
    @staticmethod
    def check_poset(poset: builtins.object) -> builtins.bool: ...
    @staticmethod
    def final_forest(element: builtins.object) -> _SageObject: ...
    @staticmethod
    def initial_forest(element: builtins.object) -> _SageObject: ...
    @staticmethod
    def from_binary_trees(tree1: builtins.object, tree2: builtins.object) -> _SageObject: ...
    @staticmethod
    def from_dyck_words(dw1: builtins.object, dw2: builtins.object) -> _SageObject: ...
    @staticmethod
    def from_blossoming_tree(B: builtins.object) -> _SageObject: ...
    @staticmethod
    def recomposition_from_triple(left: builtins.object, right: builtins.object, r: builtins.int) -> _SageObject: ...
    @staticmethod
    def from_grafting_tree(tree: builtins.object) -> _SageObject: ...
    @staticmethod
    def from_minimal_schnyder_wood(graph: builtins.object) -> _SageObject: ...
    def __call__(self, *args: builtins.object, **keywords: builtins.object) -> _SageObject: ...
    def le(self, el1: builtins.object, el2: builtins.object) -> builtins.bool: ...

class TamariIntervalPosets_all:
    def __init__(self) -> None: ...
    def one(self) -> _SageObject: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    Element: _SageObject

TIP: _SageObject
class TamariIntervalPosets_size:
    def __init__(self, size: builtins.int) -> None: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def random_element(self) -> _SageObject: ...
    def element_class(self) -> _SageObject: ...
