import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class IntegerMatrices:
    @staticmethod
    def __classcall__(
        cls: builtins.object, row_sums: builtins.object, column_sums: builtins.object
    ) -> _SageObject: ...
    def __init__(
        self, row_sums: builtins.object, column_sums: builtins.object
    ) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def row_sums(self) -> _SageObject: ...
    def column_sums(self) -> _SageObject: ...
    def to_composition(self, x: builtins.object) -> _SageObject: ...

def integer_matrices_generator(self, column_sums: builtins.object) -> _SageObject: ...
