import builtins
from collections.abc import (
    Hashable,
    Iterator,
)

from sage.combinat.binary_tree import LabelledBinaryTree
from sage.combinat.permutation import Permutation
from sage.combinat.posets.posets import FinitePoset
from sage.combinat.tamari_blossoming_tree import TamariBlossomingTree
from sage.rings.integer import Integer
from sage.structure.element import Element

class _SageObject: ...

class TamariIntervalPoset:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, *args: builtins.object, **opts: builtins.object
    ) -> TIP: ...
    def __init__(
        self,
        parent: builtins.object,
        size: builtins.int,
        relations: builtins.object = ...,
        check: builtins.bool = ...,
    ) -> None: ...
    def set_latex_options(self, D: builtins.object) -> _SageObject: ...
    def latex_options(self) -> dict[Hashable, Element]: ...
    def plot(self, **kwds: builtins.object) -> _SageObject: ...
    def poset(self) -> FinitePoset: ...
    def factor(self) -> list[TamariIntervalPoset]: ...
    def __hash__(self) -> builtins.int: ...
    def increasing_cover_relations(self) -> list[tuple[int, int]]: ...
    def increasing_roots(self) -> list[int]: ...
    def increasing_children(self, v: builtins.object) -> list[int]: ...
    def increasing_parent(self, v: builtins.object) -> int | None: ...
    def decreasing_cover_relations(self) -> list[tuple[int, int]]: ...
    def decreasing_roots(self) -> list[int]: ...
    def decreasing_children(self, v: builtins.object) -> list[int]: ...
    def decreasing_parent(self, v: builtins.object) -> int | None: ...
    def le(self, e1: builtins.object, e2: builtins.object) -> bool: ...
    def lt(self, e1: builtins.object, e2: builtins.object) -> bool: ...
    def ge(self, e1: builtins.object, e2: builtins.object) -> bool: ...
    def gt(self, e1: builtins.object, e2: builtins.object) -> bool: ...
    def size(self) -> Integer: ...
    def cubical_coordinates(self) -> tuple[int, ...]: ...
    def complement(self) -> TIP: ...
    def left_branch_involution(self) -> TIP: ...
    def rise_contact_involution(self) -> TIP: ...
    def insertion(self, i: builtins.int) -> TIP: ...
    def __iter__(self) -> Iterator[int]: ...
    def contains_interval(self, other: builtins.object) -> bool: ...
    def lower_contains_interval(self, other: builtins.object) -> bool: ...
    def upper_contains_interval(self, other: builtins.object) -> bool: ...
    def is_linear_extension(self, perm: builtins.object) -> bool: ...
    def contains_binary_tree(self, binary_tree: builtins.object) -> bool: ...
    def contains_dyck_word(self, dyck_word: builtins.object) -> bool: ...
    def intersection(self, other: builtins.object) -> TIP: ...
    def initial_forest(self) -> TIP: ...
    def final_forest(self) -> TIP: ...
    def is_initial_interval(self) -> bool: ...
    def is_final_interval(self) -> bool: ...
    def lower_binary_tree(self) -> _SageObject: ...
    def lower_dyck_word(self) -> _SageObject: ...
    def upper_binary_tree(self) -> _SageObject: ...
    def upper_dyck_word(self) -> _SageObject: ...
    def blossoming_tree(self) -> TamariBlossomingTree: ...
    def subposet(self, start: builtins.int, end: builtins.object) -> TIP: ...
    sub_poset: _SageObject

    def min_linear_extension(self) -> Permutation: ...
    def max_linear_extension(self) -> Permutation: ...
    def linear_extensions(self) -> Iterator[Permutation]: ...
    def lower_contained_intervals(self) -> Iterator[TIP]: ...
    def interval_cardinality(self) -> Integer: ...
    def binary_trees(self) -> Iterator: ...
    def dyck_words(self) -> Iterator: ...
    def maximal_chain_tamari_intervals(self) -> Iterator[TIP]: ...
    def maximal_chain_binary_trees(self) -> Iterator: ...
    def maximal_chain_dyck_words(self) -> Iterator: ...
    def tamari_inversions(self) -> list[tuple[int, int]]: ...
    def tamari_inversions_iter(self) -> Iterator[tuple[int, int]]: ...
    def number_of_tamari_inversions(self) -> Integer: ...
    def number_of_new_components(self) -> Integer: ...
    def new_decomposition(self) -> list[TIP]: ...
    def decomposition_to_triple(self) -> tuple[TIP, TIP, int] | None: ...
    def grafting_tree(self) -> LabelledBinaryTree: ...
    def is_new(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def is_synchronized(self) -> bool: ...
    def is_modern(self) -> bool: ...
    def is_infinitely_modern(self) -> bool: ...
    def is_exceptional(self) -> bool: ...
    def is_dexter(self) -> bool: ...
    def is_indecomposable(self) -> bool: ...
    def is_connected(self) -> bool: ...

class TamariIntervalPosets:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, n: builtins.int = ...
    ) -> _SageObject: ...

    class options:
        NAME: _SageObject
        module: _SageObject
        latex_tikz_scale: _SageObject
        latex_line_width_scalar: _SageObject
        latex_color_decreasing: _SageObject
        latex_color_increasing: _SageObject
        latex_hspace: _SageObject
        latex_vspace: _SageObject

    @staticmethod
    def check_poset(poset: builtins.object) -> bool: ...
    @staticmethod
    def final_forest(element: builtins.object) -> TIP: ...
    @staticmethod
    def initial_forest(element: builtins.object) -> TIP: ...
    @staticmethod
    def from_binary_trees(tree1: builtins.object, tree2: builtins.object) -> TIP: ...
    @staticmethod
    def from_dyck_words(dw1: builtins.object, dw2: builtins.object) -> TIP: ...
    @staticmethod
    def from_blossoming_tree(B: builtins.object) -> TIP: ...
    @staticmethod
    def recomposition_from_triple(
        left: builtins.object, right: builtins.object, r: builtins.int
    ) -> TIP: ...
    @staticmethod
    def from_grafting_tree(tree: builtins.object) -> TIP: ...
    @staticmethod
    def from_minimal_schnyder_wood(graph: builtins.object) -> TIP: ...
    def __call__(
        self, *args: builtins.object, **keywords: builtins.object
    ) -> _SageObject: ...
    def le(self, el1: builtins.object, el2: builtins.object) -> bool: ...

class TamariIntervalPosets_all:
    def __init__(self) -> None: ...
    def one(self) -> TIP: ...
    def __contains__(self, x: object) -> bool: ...
    Element: _SageObject

TIP: _SageObject

class TamariIntervalPosets_size:
    def __init__(self, size: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> Integer: ...
    def __iter__(self) -> Iterator[TIP]: ...
    def random_element(self) -> TIP: ...
    def element_class(self) -> _SageObject: ...
