from collections.abc import Callable, Iterator
from typing import Self

from sage.combinat.binary_tree import BinaryTree, LabelledBinaryTree
from sage.combinat.dyck_word import DyckWord
from sage.combinat.permutation import Permutation
from sage.combinat.posets.posets import FinitePoset
from sage.combinat.tamari_blossoming_tree import TamariBlossomingTree
from sage.graphs.graph import Graph
from sage.plot.graphics import Graphics
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

class TamariIntervalPoset(Element):
    @classmethod
    def __classcall_private__(cls, *args: object, **opts: object) -> TamariIntervalPoset: ...
    def __init__(
        self,
        parent: TamariIntervalPosets,
        size: int,
        relations: list[tuple[int, int]] | None = ...,
        check: bool = ...,
    ) -> None: ...
    def set_latex_options(self, D: dict[str, object]) -> None: ...
    def latex_options(self) -> dict[str, object]: ...
    def plot(self, **kwds: object) -> Graphics: ...
    def poset(self) -> FinitePoset: ...
    def factor(self) -> list[TamariIntervalPoset]: ...
    def __hash__(self) -> int: ...
    def increasing_cover_relations(self) -> list[tuple[int, int]]: ...
    def increasing_roots(self) -> list[int]: ...
    def increasing_children(self, v: int) -> list[int]: ...
    def increasing_parent(self, v: int) -> int | None: ...
    def decreasing_cover_relations(self) -> list[tuple[int, int]]: ...
    def decreasing_roots(self) -> list[int]: ...
    def decreasing_children(self, v: int) -> list[int]: ...
    def decreasing_parent(self, v: int) -> int | None: ...
    def le(self, e1: int, e2: int) -> bool: ...
    def lt(self, e1: int, e2: int) -> bool: ...
    def ge(self, e1: int, e2: int) -> bool: ...
    def gt(self, e1: int, e2: int) -> bool: ...
    def size(self) -> int: ...
    def cubical_coordinates(self) -> tuple[int, ...]: ...
    def complement(self) -> Self: ...
    def left_branch_involution(self) -> Self: ...
    def rise_contact_involution(self) -> Self: ...
    def insertion(self, i: int) -> Self: ...
    def __iter__(self) -> Iterator[int]: ...
    def contains_interval(self, other: TamariIntervalPoset) -> bool: ...
    def lower_contains_interval(self, other: TamariIntervalPoset) -> bool: ...
    def upper_contains_interval(self, other: TamariIntervalPoset) -> bool: ...
    def is_linear_extension(self, perm: Permutation) -> bool: ...
    def contains_binary_tree(self, binary_tree: BinaryTree) -> bool: ...
    def contains_dyck_word(self, dyck_word: DyckWord) -> bool: ...
    def intersection(self, other: TamariIntervalPoset) -> Self: ...
    def initial_forest(self) -> Self: ...
    def final_forest(self) -> Self: ...
    def is_initial_interval(self) -> bool: ...
    def is_final_interval(self) -> bool: ...
    def lower_binary_tree(self) -> BinaryTree: ...
    def lower_dyck_word(self) -> DyckWord: ...
    def upper_binary_tree(self) -> BinaryTree: ...
    def upper_dyck_word(self) -> DyckWord: ...
    def blossoming_tree(self) -> TamariBlossomingTree: ...
    def subposet(self, start: int, end: int) -> Self: ...
    sub_poset: Callable[[int, int], TamariIntervalPoset]
    def min_linear_extension(self) -> Permutation: ...
    def max_linear_extension(self) -> Permutation: ...
    def linear_extensions(self) -> Iterator[Permutation]: ...
    def lower_contained_intervals(self) -> Iterator[TamariIntervalPoset]: ...
    def interval_cardinality(self) -> int: ...
    def binary_trees(self) -> Iterator[BinaryTree]: ...
    def dyck_words(self) -> Iterator[DyckWord]: ...
    def maximal_chain_tamari_intervals(self) -> Iterator[TamariIntervalPoset]: ...
    def maximal_chain_binary_trees(self) -> Iterator[BinaryTree]: ...
    def maximal_chain_dyck_words(self) -> Iterator[DyckWord]: ...
    def tamari_inversions(self) -> list[tuple[int, int]]: ...
    def tamari_inversions_iter(self) -> Iterator[tuple[int, int]]: ...
    def number_of_tamari_inversions(self) -> int: ...
    def number_of_new_components(self) -> int: ...
    def new_decomposition(self) -> list[TamariIntervalPoset] | BinaryTree: ...
    def decomposition_to_triple(self) -> tuple[TamariIntervalPoset, TamariIntervalPoset, int] | None: ...
    def grafting_tree(self) -> LabelledBinaryTree: ...
    def is_new(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def is_synchronized(self) -> bool: ...
    def is_modern(self) -> bool: ...
    def is_infinitely_modern(self) -> bool: ...
    def is_exceptional(self) -> bool: ...
    def is_dexter(self) -> bool: ...
    def is_indecomposable(self) -> bool: ...
    def is_connected(self) -> bool: ...

class TamariIntervalPosets(UniqueRepresentation, Parent):
    @classmethod
    def __classcall_private__(
        cls, n: int | None = ...
    ) -> TamariIntervalPosets_size | TamariIntervalPosets_all: ...
    class options:
        NAME: str
        module: str
        latex_tikz_scale: float
        latex_line_width_scalar: float
        latex_color_decreasing: str
        latex_color_increasing: str
        latex_hspace: float
        latex_vspace: float
    @staticmethod
    def check_poset(poset: FinitePoset) -> bool: ...
    @staticmethod
    def final_forest(
        element: TamariIntervalPoset | FinitePoset
    ) -> TamariIntervalPoset | tuple[list[int], list[tuple[int, int]], int]: ...
    @staticmethod
    def initial_forest(
        element: TamariIntervalPoset | FinitePoset
    ) -> TamariIntervalPoset | tuple[list[int], list[tuple[int, int]], int]: ...
    @staticmethod
    def from_binary_trees(tree1: BinaryTree, tree2: BinaryTree) -> TamariIntervalPoset: ...
    @staticmethod
    def from_dyck_words(dw1: DyckWord, dw2: DyckWord) -> TamariIntervalPoset: ...
    @staticmethod
    def from_blossoming_tree(B: TamariBlossomingTree) -> TamariIntervalPoset: ...
    @staticmethod
    def recomposition_from_triple(
        left: TamariIntervalPoset, right: TamariIntervalPoset, r: int
    ) -> TamariIntervalPoset: ...
    @staticmethod
    def from_grafting_tree(tree: LabelledBinaryTree) -> TamariIntervalPoset: ...
    @staticmethod
    def from_minimal_schnyder_wood(graph: Graph) -> TamariIntervalPoset: ...
    def __call__(self, *args: object, **keywords: object) -> Element: ...
    def le(self, el1: TamariIntervalPoset, el2: TamariIntervalPoset) -> bool: ...

class TamariIntervalPosets_all(TamariIntervalPosets):
    def __init__(self) -> None: ...
    def one(self) -> TamariIntervalPoset: ...
    def __contains__(self, x: object) -> bool: ...
    Element: type[TamariIntervalPoset]

TIP: type[TamariIntervalPosets]

class TamariIntervalPosets_size(TamariIntervalPosets):
    def __init__(self, size: int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> int: ...
    def __iter__(self) -> Iterator[TamariIntervalPoset]: ...
    def random_element(self) -> TamariIntervalPoset: ...
    element_class: type[TamariIntervalPoset]
