from collections.abc import Iterator
from typing import Self

from sage.combinat.partition import Partition
from sage.combinat.permutation import Permutation
from sage.structure.global_options import GlobalOptions
from sage.structure.list_clone import ClonableList
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

def WeakTableau(
    t: list[list[int]] | WeakTableau_core | WeakTableau_bounded | WeakTableau_factorized_permutation,
    k: int,
    inner_shape: list[int] = ...,
    representation: str = ...,
) -> WeakTableau_core | WeakTableau_bounded | WeakTableau_factorized_permutation: ...

def WeakTableaux(
    k: int,
    shape: list[int] | tuple[list[int], list[int]],
    weight: list[int] | tuple[int, ...],
    representation: str = ...,
) -> WeakTableaux_core | WeakTableaux_bounded | WeakTableaux_factorized_permutation: ...

class WeakTableau_abstract(ClonableList[list[int]]):
    def shape(self) -> Partition | tuple[Partition, Partition]: ...
    def weight(self) -> tuple[int, ...]: ...
    def size(self) -> int: ...
    def intermediate_shapes(self) -> list[Partition]: ...
    def pp(self) -> None: ...
    def __hash__(self) -> int: ...
    def representation(
        self, representation: str = ...
    ) -> WeakTableau_core | WeakTableau_bounded | WeakTableau_factorized_permutation: ...

class WeakTableaux_abstract(UniqueRepresentation, Parent):
    def shape(self) -> Partition | tuple[Partition, Partition]: ...
    def size(self) -> int: ...
    def representation(
        self, representation: str = ...
    ) -> WeakTableaux_core | WeakTableaux_bounded | WeakTableaux_factorized_permutation: ...

class WeakTableau_core(WeakTableau_abstract):
    @staticmethod
    def __classcall_private__(
        cls: type[WeakTableau_core], t: list[list[int]] | WeakTableau_core, k: int
    ) -> WeakTableau_core: ...
    def __init__(self, parent: WeakTableaux_core, t: list[list[int]]) -> None: ...
    def shape_core(self) -> Partition: ...
    def shape_bounded(self) -> Partition | tuple[Partition, Partition]: ...
    def check(self) -> None: ...
    def to_bounded_tableau(self) -> WeakTableau_bounded: ...
    def to_factorized_permutation_tableau(self) -> WeakTableau_factorized_permutation: ...
    def residues_of_entries(self, v: int) -> list[int]: ...
    def dictionary_of_coordinates_at_residues(self, v: int) -> dict[int, list[tuple[int, int]]]: ...
    def list_of_standard_cells(self) -> list[tuple[int, int]]: ...
    def k_charge(self, algorithm: str = ...) -> int: ...
    def k_charge_I(self) -> int: ...
    def k_charge_J(self) -> int: ...

class WeakTableaux_core(WeakTableaux_abstract):
    @staticmethod
    def __classcall_private__(
        cls: type[WeakTableaux_core],
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...],
    ) -> WeakTableaux_core: ...
    def __init__(
        self,
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...],
    ) -> None: ...
    def __iter__(self) -> Iterator[WeakTableau_core]: ...
    def diag(self, c: tuple[int, int], ha: tuple[int, int]) -> tuple[int, int]: ...
    def circular_distance(self, cr: int, r: int) -> int: ...
    Element: type[WeakTableau_core]

class WeakTableau_bounded(WeakTableau_abstract):
    @staticmethod
    def __classcall_private__(
        cls: type[WeakTableau_bounded], t: list[list[int]] | WeakTableau_bounded, k: int
    ) -> WeakTableau_bounded: ...
    def __init__(self, parent: WeakTableaux_bounded, t: list[list[int]]) -> None: ...
    def shape_core(self) -> Partition | tuple[Partition, Partition]: ...
    def shape_bounded(self) -> Partition | tuple[Partition, Partition]: ...
    def check(self) -> None: ...
    def to_core_tableau(self) -> WeakTableau_core: ...
    @classmethod
    def from_core_tableau(cls, t: WeakTableau_core, k: int) -> Self: ...
    def k_charge(self, algorithm: str = ...) -> int: ...

class WeakTableaux_bounded(WeakTableaux_abstract):
    @staticmethod
    def __classcall_private__(
        cls: type[WeakTableaux_bounded],
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...],
    ) -> WeakTableaux_bounded: ...
    def __init__(
        self,
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...],
    ) -> None: ...
    def __iter__(self) -> Iterator[WeakTableau_bounded]: ...
    Element: type[WeakTableau_bounded]

class WeakTableau_factorized_permutation(WeakTableau_abstract):
    @staticmethod
    def straighten_input(t: list[list[int]], k: int) -> tuple[list[int], ...]: ...
    @staticmethod
    def __classcall_private__(
        cls: type[WeakTableau_factorized_permutation],
        t: list[list[int]] | WeakTableau_factorized_permutation,
        k: int,
        inner_shape: list[int] = ...,
    ) -> WeakTableau_factorized_permutation: ...
    def __init__(self, parent: WeakTableaux_factorized_permutation, t: list[list[int]]) -> None: ...
    def shape_core(self) -> Partition: ...
    def shape_bounded(self) -> Partition | tuple[Partition, Partition]: ...
    def check(self) -> None: ...
    def to_core_tableau(self) -> WeakTableau_core: ...
    @classmethod
    def from_core_tableau(cls, t: WeakTableau_core, k: int) -> Self: ...
    def k_charge(self, algorithm: str = ...) -> int: ...

class WeakTableaux_factorized_permutation(WeakTableaux_abstract):
    @staticmethod
    def __classcall_private__(
        cls: type[WeakTableaux_factorized_permutation],
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...],
    ) -> WeakTableaux_factorized_permutation: ...
    def __init__(
        self,
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...],
    ) -> None: ...
    def __iter__(self) -> Iterator[WeakTableau_factorized_permutation]: ...
    Element: type[WeakTableau_factorized_permutation]

class StrongTableau(ClonableList[list[int]]):
    def __init__(self, parent: StrongTableaux, T: list[list[int]]) -> None: ...
    @staticmethod
    def __classcall_private__(
        cls: type[StrongTableau],
        T: list[list[int]] | StrongTableau,
        k: int,
        weight: tuple[int, ...] | None = ...,
    ) -> StrongTableau: ...
    def check(self) -> None: ...
    def __hash__(self) -> int: ...
    def is_column_strict_with_weight(self, mu: tuple[int, ...]) -> bool: ...
    def cell_of_marked_head(self, v: int) -> tuple[int, int]: ...
    def content_of_marked_head(self, v: int) -> int: ...
    def cells_of_marked_ribbon(self, v: int) -> list[tuple[int, int]]: ...
    def cell_of_highest_head(self, v: int) -> tuple[int, int]: ...
    def content_of_highest_head(self, v: int) -> int: ...
    def cells_head_dictionary(self) -> dict[int, list[tuple[int, int]]]: ...
    def cells_of_heads(self, v: int) -> list[tuple[int, int]]: ...
    def contents_of_heads(self, v: int) -> list[int]: ...
    def entries_by_content(self, diag: int) -> list[int]: ...
    def entries_by_content_standard(self, diag: int) -> list[int]: ...
    def ribbons_above_marked(self, v: int) -> int: ...
    def height_of_ribbon(self, v: int) -> int: ...
    def number_of_connected_components(self, v: int) -> int: ...
    def intermediate_shapes(self) -> list[Partition]: ...
    def pp(self) -> None: ...
    def outer_shape(self) -> Partition: ...
    def inner_shape(self) -> Partition: ...
    def shape(self) -> Partition | tuple[Partition, Partition]: ...
    def weight(self) -> tuple[int, ...]: ...
    def size(self) -> int: ...
    def to_list(self) -> list[list[int]]: ...
    def to_unmarked_list(self) -> list[list[int]]: ...
    def to_standard_list(self) -> list[list[int]]: ...
    def to_standard_tableau(self) -> StrongTableau: ...
    def to_unmarked_standard_list(self) -> list[list[int]]: ...
    def restrict(self, r: int) -> StrongTableau: ...
    def set_weight(self, mu: tuple[int, ...]) -> StrongTableau: ...
    def left_action(self, tij: Permutation) -> StrongTableau: ...
    def follows_tableau(self) -> list[StrongTableau]: ...
    def spin_of_ribbon(self, v: int) -> int: ...
    def spin(self) -> int: ...
    def to_transposition_sequence(self) -> list[list[int]]: ...

class StrongTableaux(UniqueRepresentation, Parent):
    def __init__(
        self,
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...],
    ) -> None: ...
    @staticmethod
    def __classcall_private__(
        cls: type[StrongTableaux],
        k: int,
        shape: list[int] | tuple[list[int], list[int]],
        weight: list[int] | tuple[int, ...] | None = ...,
    ) -> StrongTableaux: ...
    options: GlobalOptions
    def outer_shape(self) -> Partition: ...
    def inner_shape(self) -> Partition: ...
    def shape(self) -> Partition | tuple[Partition, Partition]: ...
    def __iter__(self) -> Iterator[StrongTableau]: ...
    @classmethod
    def standard_unmarked_iterator(
        cls,
        k: int,
        size: int,
        outer_shape: Partition | None = ...,
        inner_shape: list[int] = ...,
    ) -> Iterator[list[list[int]]]: ...
    @classmethod
    def marked_given_unmarked_and_weight_iterator(
        cls, unmarkedT: list[list[int]], k: int, weight: tuple[int, ...]
    ) -> Iterator[StrongTableau]: ...
    @classmethod
    def add_marking(
        cls, unmarkedT: list[list[int]], marking: list[int], k: int, weight: tuple[int, ...]
    ) -> StrongTableau: ...
    @classmethod
    def follows_tableau_unsigned_standard(cls, Tlist: list[list[int]], k: int) -> list[list[list[int]]]: ...
    @classmethod
    def standard_marked_iterator(
        cls,
        k: int,
        size: int,
        outer_shape: Partition | None = ...,
        inner_shape: list[int] = ...,
    ) -> Iterator[StrongTableau]: ...
    @classmethod
    def cells_head_dictionary(cls, T: StrongTableau) -> dict[int, list[tuple[int, int]]]: ...
    @classmethod
    def marked_CST_to_transposition_sequence(
        self, T: StrongTableau, k: int
    ) -> list[list[int]]: ...
    @classmethod
    def transpositions_to_standard_strong(
        self, transeq: list[list[int]], k: int, emptyTableau: list[list[int]] = ...
    ) -> StrongTableau: ...
    Element: type[StrongTableau]

def nabs(v: int) -> int: ...

def intermediate_shapes(t: WeakTableau_abstract | list[list[int]]) -> list[Partition]: ...
