# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KazhdanLusztigPolynomial:
    def __init__(self, W: builtins.object, q: builtins.int, trace: builtins.bool = ...) -> None: ...
    def R(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def R_tilde(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def P(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
