# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LittlewoodRichardsonTableau:
    @staticmethod
    def __classcall_private__(cls: builtins.object, t: builtins.object, weight: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, t: builtins.object) -> None: ...
    def check(self) -> _SageObject: ...

class LittlewoodRichardsonTableaux:
    @staticmethod
    def __classcall_private__(cls: builtins.object, shape: builtins.object, weight: builtins.object) -> _SageObject: ...
    def __init__(self, shape: builtins.object, weight: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    Element: _SageObject

def is_littlewood_richardson(t: builtins.object, heights: builtins.object) -> builtins.bool: ...
