# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DoublyLinkedList:
    def __init__(self, l: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def hide(self, i: builtins.int) -> _SageObject: ...
    def unhide(self, i: builtins.int) -> _SageObject: ...
    def head(self) -> _SageObject: ...
    def next(self, j: builtins.int) -> _SageObject: ...
    def prev(self, j: builtins.int) -> _SageObject: ...

def umbral_operation(poly: builtins.object) -> _SageObject: ...

class IterableFunctionCall:
    def __init__(self, f: builtins.object, *args: builtins.object, **kwargs: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def check_integer_list_constraints(l: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
