import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.rings.integer import Integer

class _SageObject: ...

def NonDecreasingParkingFunctions(self=...) -> _SageObject: ...
def is_a(self, n: builtins.int = ...) -> bool: ...

class NonDecreasingParkingFunction:
    def __init__(self, lst: builtins.object) -> None: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def __call__(self, n: builtins.int) -> _SageObject: ...
    def to_dyck_word(self) -> _SageObject: ...
    def __len__(self) -> int: ...
    grade: _SageObject

    def __hash__(self) -> int: ...
    @classmethod
    def from_dyck_word(cls, dw: builtins.object) -> NonDecreasingParkingFunction: ...

class NonDecreasingParkingFunctions_all:
    def __init__(self) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def graded_component(self, n: builtins.int) -> _SageObject: ...

class NonDecreasingParkingFunctions_n:
    n: builtins.int

    def __init__(self, n: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> Integer: ...
    def random_element(self) -> NonDecreasingParkingFunction: ...
    def one(self) -> NonDecreasingParkingFunction: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    Element: _SageObject
