import builtins
from collections.abc import (
    Hashable,
)
from collections.abc import (
    Iterator as _Iterator,
)

from sage.structure.element import Element

class _SageObject: ...

ndw_open_symbol: _SageObject
ndw_close_symbol: _SageObject

def update_ndw_symbols(self, cs: builtins.object) -> _SageObject: ...
def replace_dyck_char(self) -> _SageObject: ...
def replace_dyck_symbol(
    self, open_char: builtins.str = ..., close_char: builtins.str = ...
) -> str: ...

class NuDyckWord:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        dw: builtins.object = ...,
        nu: builtins.object = ...,
        **kwargs: builtins.object,
    ) -> _SageObject: ...
    def __init__(
        self,
        parent: builtins.object,
        dw: builtins.object,
        latex_options: builtins.object = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __neq__(self, other: builtins.object) -> _SageObject: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> int: ...
    def set_latex_options(self, D: builtins.object) -> _SageObject: ...
    def latex_options(self) -> dict[Hashable, Element]: ...
    def pretty_print(
        self, style: builtins.str = ..., labelling: builtins.object = ...
    ) -> _SageObject: ...
    pp: _SageObject

    def plot(self, **kwds: builtins.object) -> _SageObject: ...
    def path(self) -> _SageObject: ...
    def height(self) -> _SageObject: ...
    def width(self) -> _SageObject: ...
    def length(self) -> _SageObject: ...
    def points(self) -> _SageObject: ...
    def heights(self) -> _SageObject: ...
    def widths(self) -> _SageObject: ...
    def horizontal_distance(self) -> _SageObject: ...
    def can_mutate(self, i: builtins.int) -> bool | int: ...
    def mutate(self, i: builtins.int) -> NuDyckWord | None: ...

class NuDyckWords:
    Element: _SageObject

    def __init__(self, nu: builtins.tuple[_SageObject, ...] = ...) -> None: ...

    class options:
        NAME: _SageObject
        module: _SageObject
        display: _SageObject
        ascii_art: _SageObject
        diagram_style: _SageObject
        latex_tikz_scale: _SageObject
        latex_line_width_scalar: _SageObject
        latex_color: _SageObject
        latex_show_points: _SageObject
        latex_points_color: _SageObject
        latex_show_grid: _SageObject
        latex_show_nu: _SageObject
        latex_nu_options: _SageObject

    def __contains__(self, x: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __neq__(self, other: builtins.object) -> _SageObject: ...
    def __iter__(
        self,
        N: builtins.list[_SageObject] = ...,
        D: builtins.list[_SageObject] = ...,
        i: builtins.int = ...,
        X: builtins.object = ...,
    ) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...

def to_word_path(self) -> _SageObject: ...
def path_weakly_above_other(self, other: builtins.object) -> bool: ...
