from typing import overload
from collections.abc import Iterator

from sage.combinat.combinat import CombinatorialElement
from sage.combinat.dyck_word import DyckWord
from sage.combinat.binary_tree import BinaryTree

class ParallelogramPolyomino: ...
class Graph: ...
class Poset: ...
class Graphics: ...

class OrderedTree(CombinatorialElement):
    def __classcall_private__(cls, t: object = ..., check: bool = ...) -> OrderedTree: ...
    def __init__(self, parent: object, t: object, check: bool = ...) -> None: ...
    def is_empty(self) -> bool: ...
    def to_binary_tree_left_branch(self) -> BinaryTree: ...
    def to_parallelogram_polyomino(self, bijection: str = ...) -> ParallelogramPolyomino: ...
    def to_binary_tree_right_branch(self) -> BinaryTree: ...
    def to_dyck_word(self) -> DyckWord: ...
    def to_undirected_graph(self) -> Graph: ...
    def to_poset(self, root_to_leaf: bool = ...) -> Poset: ...
    def left_right_symmetry(self) -> OrderedTree: ...
    def plot(self, **kwds: object) -> Graphics: ...
    def sort_key(self) -> tuple[int, ...]: ...
    def normalize(self, inplace: bool = ...) -> OrderedTree | None: ...
