import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class SetPartitionsXkElement:
    def check(self) -> _SageObject: ...

def SetPartitionsAk(self) -> _SageObject: ...

class SetPartitionsAk_k:
    k: builtins.int

    def __init__(self, k: builtins.int) -> None: ...
    Element: _SageObject

class SetPartitionsAkhalf_k:
    k: builtins.int

    def __init__(self, k: builtins.int) -> None: ...
    Element: _SageObject

    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def SetPartitionsSk(self) -> _SageObject: ...

class SetPartitionsSk_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SetPartitionsSkhalf_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def SetPartitionsIk(self) -> _SageObject: ...

class SetPartitionsIk_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SetPartitionsIkhalf_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def SetPartitionsBk(self) -> _SageObject: ...

class SetPartitionsBk_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SetPartitionsBkhalf_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def SetPartitionsPk(self) -> _SageObject: ...

class SetPartitionsPk_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SetPartitionsPkhalf_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def SetPartitionsTk(self) -> _SageObject: ...

class SetPartitionsTk_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SetPartitionsTkhalf_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def SetPartitionsRk(self) -> _SageObject: ...

class SetPartitionsRk_k:
    k: builtins.int

    def __init__(self, k: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SetPartitionsRkhalf_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def SetPartitionsPRk(self) -> _SageObject: ...

class SetPartitionsPRk_k:
    k: builtins.int

    def __init__(self, k: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SetPartitionsPRkhalf_k:
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class PartitionAlgebra_generic:
    n: builtins.int
    k: builtins.int

    def __init__(
        self,
        R: builtins.int,
        cclass: builtins.object,
        n: builtins.int,
        k: builtins.int,
        name: builtins.str = ...,
        prefix: builtins.str = ...,
    ) -> None: ...
    def one_basis(self) -> _SageObject: ...
    def product_on_basis(
        self, left: builtins.object, right: builtins.object
    ) -> _SageObject: ...

class PartitionAlgebraElement_generic: ...
class PartitionAlgebraElement_ak: ...

class PartitionAlgebra_ak:
    def __init__(
        self,
        R: builtins.int,
        k: builtins.int,
        n: builtins.int,
        name: builtins.str = ...,
    ) -> None: ...

class PartitionAlgebraElement_bk: ...

class PartitionAlgebra_bk:
    def __init__(
        self,
        R: builtins.int,
        k: builtins.int,
        n: builtins.int,
        name: builtins.str = ...,
    ) -> None: ...

class PartitionAlgebraElement_sk: ...

class PartitionAlgebra_sk:
    def __init__(
        self,
        R: builtins.int,
        k: builtins.int,
        n: builtins.int,
        name: builtins.str = ...,
    ) -> None: ...

class PartitionAlgebraElement_pk: ...

class PartitionAlgebra_pk:
    def __init__(
        self,
        R: builtins.int,
        k: builtins.int,
        n: builtins.int,
        name: builtins.str = ...,
    ) -> None: ...

class PartitionAlgebraElement_tk: ...

class PartitionAlgebra_tk:
    def __init__(
        self,
        R: builtins.int,
        k: builtins.int,
        n: builtins.int,
        name: builtins.str = ...,
    ) -> None: ...

class PartitionAlgebraElement_rk: ...

class PartitionAlgebra_rk:
    def __init__(
        self,
        R: builtins.int,
        k: builtins.int,
        n: builtins.int,
        name: builtins.str = ...,
    ) -> None: ...

class PartitionAlgebraElement_prk: ...

class PartitionAlgebra_prk:
    def __init__(
        self,
        R: builtins.int,
        k: builtins.int,
        n: builtins.int,
        name: builtins.str = ...,
    ) -> None: ...

def is_planar(self) -> builtins.bool: ...
def to_graph(self) -> _SageObject: ...
def pair_to_graph(self, sp2: builtins.object) -> _SageObject: ...
def propagating_number(self) -> _SageObject: ...
def to_set_partition(self, k: builtins.int = ...) -> _SageObject: ...
def identity(self) -> _SageObject: ...
def set_partition_composition(self, sp2: builtins.object) -> _SageObject: ...
