# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ShiftingSequenceSpace:
    def __init__(self) -> None: ...
    def __contains__(self, seq: builtins.object) -> builtins.bool: ...
    def check(self, seq: builtins.object) -> _SageObject: ...

class ShiftingOperatorAlgebra:
    def __init__(self, base_ring: builtins.object = ..., prefix: builtins.str = ...) -> None: ...
    def __getitem__(self, seq: builtins.object) -> _SageObject: ...
    def product_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def one_basis(self) -> _SageObject: ...
    def build_and_register_conversion(self, support_map: builtins.object, codomain: builtins.object) -> _SageObject: ...
    def ij(self, i: builtins.int, j: builtins.int) -> _SageObject: ...
    class Element:
        def __call__(self, operand: builtins.object) -> _SageObject: ...
