from typing import TYPE_CHECKING, overload
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.structure.list_clone import ClonableList
from sage.rings.integer import Integer
from sage.combinat.partition import Partition
from sage.combinat.tableau import Tableau

if TYPE_CHECKING:
    from collections.abc import Iterator

class PartitionTuple(Element):
    def level(self) -> int: ...
    def __len__(self) -> int: ...
    def _repr_(self, compact: bool | None = ...) -> str: ...
    def _latex_(self) -> str: ...
    def components(self) -> list[Partition]: ...
    def diagram(self) -> str: ...
    def pp(self) -> None: ...
    def size(self) -> int: ...
    def row_standard_tableaux(self) -> list[Tableau]: ...
    def standard_tableaux(self) -> list[Tableau]: ...
    def up(self) -> list[PartitionTuple]: ...
    def up_list(self) -> list[PartitionTuple]: ...
    def down(self) -> list[PartitionTuple]: ...
    def down_list(self) -> list[PartitionTuple]: ...
    def cells(self) -> list[tuple[int, int, int]]: ...
    def content(self, k: int, r: int, c: int, multicharge: object) -> int | tuple[int, ...]: ...
    def content_tableau(self, multicharge: object) -> Tableau: ...
    def conjugate(self) -> PartitionTuple: ...
    def dominates(self, mu: PartitionTuple) -> bool: ...
    def initial_tableau(self) -> Tableau: ...
    def initial_column_tableau(self) -> Tableau: ...
    def garnir_tableau(self, *cell: int) -> Tableau: ...
    def top_garnir_tableau(self, e: int, cell: tuple[int, int, int]) -> Tableau: ...
    def arm_length(self, k: int, r: int, c: int) -> int: ...
    def leg_length(self, k: int, r: int, c: int) -> int: ...
    def contains(self, mu: PartitionTuple) -> bool: ...
    def hook_length(self, k: int, r: int, c: int) -> int: ...
    def to_exp(self, k: int = ...) -> list[int]: ...
    def removable_cells(self) -> list[tuple[int, int, int]]: ...
    def addable_cells(self) -> list[tuple[int, int, int]]: ...
    def add_cell(self, k: int, r: int, c: int) -> PartitionTuple | None: ...
    def remove_cell(self, k: int, r: int, c: int) -> PartitionTuple | None: ...
    def to_list(self) -> list[list[int]]: ...
    def young_subgroup(self) -> list[PartitionTuple]: ...
    def young_subgroup_generators(self) -> list[object]: ...
    def degree(self, e: int) -> int: ...
    def prime_degree(self, p: int) -> int: ...
    def block(self, e: int, multicharge: object) -> Partition: ...
    def defect(self, e: int, multicharge: object) -> int: ...

class PartitionTuples(UniqueRepresentation, Parent):
    def _element_constructor_(self, mu: object) -> PartitionTuple: ...
    def __contains__(self, mu: object) -> bool: ...
    def __getitem__(self, r: int) -> PartitionTuple: ...
    def level(self) -> int | None: ...
    def size(self) -> int | None: ...
    def _an_element_(self) -> PartitionTuple: ...

class PartitionTuples_all(PartitionTuples):
    def _repr_(self) -> str: ...
    def __iter__(self) -> Iterator[PartitionTuple]: ...
    def _an_element_(self) -> PartitionTuple: ...

class PartitionTuples_level(PartitionTuples):
    def _repr_(self) -> str: ...
    def __contains__(self, mu: object) -> bool: ...
    def __iter__(self) -> Iterator[PartitionTuple]: ...
    def _an_element_(self) -> PartitionTuple: ...

class PartitionTuples_size(PartitionTuples):
    def _repr_(self) -> str: ...
    def __contains__(self, mu: object) -> bool: ...
    def __iter__(self) -> Iterator[PartitionTuple]: ...
    def _an_element_(self) -> PartitionTuple: ...

class PartitionTuples_level_size(PartitionTuples):
    def _repr_(self) -> str: ...
    def __contains__(self, mu: object) -> bool: ...
    def __iter__(self) -> Iterator[PartitionTuple]: ...
    def _an_element_(self) -> PartitionTuple: ...

class RegularPartitionTuples(PartitionTuples):
    pass

class RegularPartitionTuples_all(RegularPartitionTuples):
    pass

class RegularPartitionTuples_level(RegularPartitionTuples):
    pass

class RegularPartitionTuples_size(RegularPartitionTuples):
    pass

class RegularPartitionTuples_level_size(RegularPartitionTuples):
    pass
