import collections.abc
from collections.abc import Iterator

import sage.combinat.alternating_sign_matrix
import sage.combinat.binary_tree
import sage.combinat.composition
import sage.combinat.diagram
import sage.combinat.ordered_tree
import sage.combinat.partition
import sage.combinat.posets.posets
import sage.combinat.words.word
import sage.graphs.digraph
import sage.groups.perm_gps.permgroup_element
import sage.matrix.matrix
import sage.matrix.matrix_space
import sage.rings.ideal
import sage.rings.polynomial.polynomial_element
from sage.combinat.composition import Composition
from sage.combinat.tableau import Tableau
from sage.graphs.digraph import DiGraph
from sage.rings.integer import Integer
from sage.structure.element import Element

class Permutation(Element):
    def size(self) -> Integer: ...
    def order(self) -> Integer: ...
    def cycle_string(self, singletons: bool = ...) -> str: ...
    def prev(self) -> Permutation | None: ...
    def to_tableau_by_shape(self, shape: object) -> Tableau: ...
    def to_cycles(
        self, singletons: bool = ..., use_min: bool = ...
    ) -> list[Element]: ...
    def to_permutation_group_element(
        self,
    ) -> sage.groups.perm_gps.permgroup_element.PermutationGroupElement: ...
    def signature(self) -> Integer: ...
    def is_even(self) -> bool: ...
    def to_matrix(self) -> sage.matrix.matrix.Matrix: ...
    def to_alternating_sign_matrix(
        self,
    ) -> sage.combinat.alternating_sign_matrix.AlternatingSignMatrix: ...
    def left_action_product(self, lp: Permutation) -> Permutation: ...
    def right_action_product(self, rp: Permutation) -> Permutation: ...
    def rank(self) -> Integer: ...
    def to_inversion_vector(self) -> list[Integer]: ...
    def inversions(self) -> list[Element]: ...
    def stack_sort(self) -> Permutation: ...
    def to_digraph(self) -> DiGraph: ...
    def show(self, representation: str = ..., orientation: str = ...) -> None: ...
    def number_of_inversions(self) -> Integer: ...
    def noninversions(self, k: int | None = ...) -> list[list]: ...
    def number_of_noninversions(self, k: int | None = ...) -> Integer: ...
    def length(self) -> Integer: ...
    def absolute_length(self) -> Integer: ...
    def inverse(self) -> Permutation: ...
    def ishift(self, i: int) -> Permutation: ...
    def iswitch(self, i: int) -> Permutation: ...
    def runs(self, as_tuple: bool = ...) -> list | tuple: ...
    def decreasing_runs(self, as_tuple: bool = ...) -> list | tuple: ...
    def longest_increasing_subsequence_length(self) -> Integer: ...
    def longest_increasing_subsequences(self) -> list[Element]: ...
    def number_of_longest_increasing_subsequences(self) -> int: ...
    def cycle_type(self) -> sage.combinat.partition.Partition: ...
    def forget_cycles(self) -> Permutation: ...
    def foata_bijection(self) -> Permutation: ...
    def foata_bijection_inverse(self) -> Permutation: ...
    def fundamental_transformation(self) -> Permutation: ...
    def fundamental_transformation_inverse(self) -> Permutation: ...
    def destandardize(
        self, weight: list[int], ordered_alphabet: list[int] | None = ...
    ) -> sage.combinat.words.word.Word_class: ...
    def to_lehmer_code(self) -> list[Element]: ...
    def to_lehmer_cocode(self) -> list[int]: ...
    def reduced_word(self) -> list[int]: ...
    def reduced_words_iterator(self) -> Iterator[Element]: ...
    def reduced_words(self) -> list[Element]: ...
    def reduced_word_lexmin(self) -> list[int]: ...
    def number_of_reduced_words(self) -> int: ...
    def rothe_diagram(self) -> sage.combinat.diagram.NorthwestDiagram: ...
    def rank_matrix(self) -> sage.matrix.matrix.Matrix: ...
    def schubert_determinant_ideal(self) -> sage.rings.ideal.Ideal_generic: ...
    def fixed_points(self) -> list[int]: ...
    def number_of_fixed_points(self) -> int: ...
    def is_derangement(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def recoils(self) -> list[int]: ...
    def number_of_recoils(self) -> Integer: ...
    def recoils_composition(self) -> Composition: ...
    def descents(
        self,
        final_descent: bool = ...,
        side: str = ...,
        positive: bool = ...,
        from_zero: bool = ...,
        index_set: tuple[int, ...] | None = ...,
    ) -> list[int]: ...
    def idescents(
        self, final_descent: bool = ..., from_zero: bool = ...
    ) -> list[int]: ...
    def idescents_signature(self, final_descent: bool = ...) -> list[int]: ...
    def number_of_descents(self, final_descent: bool = ...) -> int: ...
    def number_of_idescents(self, final_descent: bool = ...) -> int: ...
    def descents_composition(self) -> Composition: ...
    def descent_polynomial(
        self,
    ) -> sage.rings.polynomial.polynomial_element.Polynomial: ...
    def major_index(self, final_descent: bool = ...) -> Integer: ...
    def multi_major_index(self, composition: object) -> int: ...
    def imajor_index(self, final_descent: bool = ...) -> Integer: ...
    def to_major_code(self, final_descent: bool = ...) -> list[int]: ...
    def peaks(self) -> list[int]: ...
    def number_of_peaks(self) -> int: ...
    def saliances(self) -> list[int]: ...
    def number_of_saliances(self) -> int: ...
    def bruhat_lequal(self, p2: Permutation) -> bool: ...
    def weak_excedences(self) -> list[Element]: ...
    def bruhat_inversions(self) -> list[Element]: ...
    def bruhat_inversions_iterator(
        self,
    ) -> collections.abc.Iterator[tuple[int, int]]: ...
    def bruhat_succ(self) -> list[Element]: ...
    def bruhat_succ_iterator(
        self,
    ) -> collections.abc.Iterator[sage.combinat.permutation.Permutation]: ...
    def bruhat_pred(self) -> list[Element]: ...
    def bruhat_pred_iterator(
        self,
    ) -> collections.abc.Iterator[sage.combinat.permutation.Permutation]: ...
    def bruhat_smaller(self) -> list[Permutation]: ...
    def bruhat_greater(self) -> list[Permutation]: ...
    def permutohedron_lequal(self, p2: Permutation, side: str = ...) -> bool: ...
    def permutohedron_succ(self, side: str = ...) -> list[Permutation]: ...
    def permutohedron_pred(self, side: str = ...) -> list[Element]: ...
    def permutohedron_smaller(self, side: str = ...) -> list[Element]: ...
    def permutohedron_greater(self, side: str = ...) -> list[Element]: ...
    def right_permutohedron_interval_iterator(
        self, other: Permutation
    ) -> collections.abc.Iterator[sage.combinat.permutation.Permutation]: ...
    def right_permutohedron_interval(self, other: Permutation) -> list[Permutation]: ...
    def permutohedron_join(
        self, other: Permutation, side: str = ...
    ) -> Permutation: ...
    def permutohedron_meet(
        self, other: Permutation, side: str = ...
    ) -> Permutation: ...
    def has_pattern(self, patt: object) -> bool: ...
    def avoids(self, patt: object) -> bool: ...
    def pattern_positions(self, patt: object) -> list[Element]: ...
    def simion_schmidt(self, avoid: object) -> Permutation: ...
    def reverse(self) -> Permutation: ...
    def complement(self) -> Permutation: ...
    def permutation_poset(self) -> sage.combinat.posets.posets.FinitePoset: ...
    def dict(self) -> dict[int, int]: ...
    def action(self, a: object) -> sage.combinat.words.word.Word_class: ...
    def robinson_schensted(self) -> tuple[Tableau, Tableau]: ...
    def left_tableau(self) -> Tableau: ...
    def right_tableau(self) -> Tableau: ...
    def increasing_tree(
        self, compare: object = ...
    ) -> sage.combinat.ordered_tree.OrderedTree: ...
    def increasing_tree_shape(
        self, compare: object = ...
    ) -> sage.combinat.ordered_tree.OrderedTree: ...
    def binary_search_tree(
        self, left_to_right: bool = ...
    ) -> sage.combinat.binary_tree.BinaryTree: ...
    def binary_search_tree_shape(
        self, left_to_right: bool = ...
    ) -> sage.combinat.binary_tree.BinaryTree: ...
    def sylvester_class(self, left_to_right: bool = ...) -> list[Permutation]: ...
    def RS_partition(self) -> sage.combinat.partition.Partition: ...
    def remove_extra_fixed_points(self) -> Permutation: ...
    def retract_plain(self, m: int) -> Permutation: ...
    def retract_direct_product(self, m: int) -> Permutation: ...
    def retract_okounkov_vershik(self, m: int) -> Permutation: ...
    def hyperoctahedral_double_coset_type(
        self,
    ) -> sage.combinat.partition.Partition: ...
    def shifted_concatenation(
        self, other: Permutation, side: str = ...
    ) -> Permutation: ...
    def shifted_shuffle(self, other: Permutation) -> list[Permutation]: ...
    def nth_roots(self, n: int) -> list[Permutation]: ...
    def has_nth_root(self, n: int) -> bool: ...
    def number_of_nth_roots(self, n: int) -> Integer: ...
