from typing import TYPE_CHECKING, NewType, Any
from sage.structure.list_clone import ClonableArray
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.rings.integer import Integer
from sage.combinat.tableau import Tableau

from collections.abc import Iterator
PP = NewType('PP', PlanePartition)

class PlanePartition(ClonableArray):
    

    def __init__(self, parent: Parent, pp: list[int] | tuple[int, ...], check: bool = ...) -> None: ...
    def check(self) -> None: ...
    def _repr_(self) -> str: ...
    def to_tableau(self) -> Tableau: ...
    def z_tableau(self, tableau: bool = ...) -> Tableau | list[int]: ...
    def y_tableau(self, tableau: bool = ...) -> Tableau | list[int]: ...
    def x_tableau(self, tableau: bool = ...) -> Tableau | list[int]: ...
    def cells(self) -> list[tuple[int, int, int]]: ...
    def number_of_boxes(self) -> Integer: ...
    def _repr_diagram(self, show_box: bool = ..., use_unicode: bool = ...) -> str: ...
    def _ascii_art_(self) -> None: ...
    def _unicode_art_(self) -> None: ...
    def pp(self, show_box: bool = ...) -> None: ...
    def _repr_svg_(self) -> str: ...
    def _latex_(
        self, show_box: bool = ..., colors: list[str] | None = None
    ) -> str: ...
    def plot(self, show_box: bool = ..., colors: list[str] | None = None) -> Any: ...
    def contains(self, PP: PlanePartition | list[int]) -> bool: ...
    def plot3d(self, colors: list[str] | None = None) -> Any: ...
    def complement(self, tableau_only: bool = ...) -> PP | list[int]: ...
    def transpose(self, tableau_only: bool = ...) -> PP | list[int]: ...
    def is_SPP(self) -> bool: ...
    def is_CSPP(self) -> bool: ...
    def is_TSPP(self) -> bool: ...
    def is_SCPP(self) -> bool: ...
    def is_TCPP(self) -> bool: ...
    def is_SSCPP(self) -> bool: ...
    def is_CSTCPP(self) -> bool: ...
    def is_CSSCPP(self) -> bool: ...
    def is_TSSCPP(self) -> bool: ...
    def to_order_ideal(self) -> None: ...
    def maximal_boxes(self) -> list[int]: ...
    def cyclically_rotate(self, preserve_parent: bool = ...) -> PP: ...
    def bounding_box(self) -> tuple[int, int, int]: ...

class PlanePartitions(UniqueRepresentation, Parent):
    

    def __init__(
        self, box_size: tuple[int, int, int] | None = None, symmetry: str | None = None, category: Any = None
    ) -> None: ...
    def __contains__(self, pp: PlanePartition | list[int] | tuple[int, ...]) -> bool: ...
    def box(self) -> tuple[int, int, int] | None: ...
    def symmetry(self) -> str | None: ...
    def element_class(self, *args: Any, **kwargs: Any) -> PlanePartition: ...

class PlanePartitions_all(PlanePartitions):
    

    def __init__(self) -> None: ...
    def _repr_(self) -> str: ...
    def an_element(self) -> PlanePartition: ...

class PlanePartitions_box(PlanePartitions):
    

    def __init__(self, box_size: tuple[int, int, int]) -> None: ...
    def _repr_(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def to_poset(self) -> Any: ...
    def from_order_ideal(self, I: list[int]) -> PP: ...
    def from_antichain(self, A: list[int]) -> PP: ...
    def __iter__(self) -> Iterator[PlanePartition]: ...
    def cardinality(self) -> Integer: ...
    def random_element(self) -> PP: ...

class PlanePartitions_n(PlanePartitions):
    

    def __init__(self, n: int) -> None: ...
    def _repr_(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> Iterator[PlanePartition]: ...
    def cardinality(self) -> Integer: ...

class PlanePartitions_SPP(PlanePartitions):
    ...

class PlanePartitions_CSPP(PlanePartitions):
    ...

class PlanePartitions_TSPP(PlanePartitions):
    ...

class PlanePartitions_SCPP(PlanePartitions):
    ...

class PlanePartitions_TCPP(PlanePartitions):
    ...

class PlanePartitions_SSCPP(PlanePartitions):
    ...

class PlanePartitions_CSTCPP(PlanePartitions):
    ...

class PlanePartitions_CSSCPP(PlanePartitions):
    ...

class PlanePartitions_TSSCPP(PlanePartitions):
    ...
