import builtins

class _SageObject: ...

def q_int(self, q: builtins.int = ...) -> _SageObject: ...
def q_factorial(self, q: builtins.int = ...) -> _SageObject: ...
def q_binomial(
    self, k: builtins.int, q: builtins.int = ..., algorithm: builtins.str = ...
) -> _SageObject: ...
def gaussian_binomial(
    self, k: builtins.int, q: builtins.int = ..., algorithm: builtins.str = ...
) -> _SageObject: ...
def q_multinomial(
    self, q: builtins.int = ..., binomial_algorithm: builtins.str = ...
) -> _SageObject: ...

gaussian_multinomial: _SageObject

def q_catalan_number(
    self, q: builtins.int = ..., m: builtins.int = ...
) -> _SageObject: ...
def qt_catalan_number(self) -> _SageObject: ...
def q_pochhammer(self, a: builtins.object, q: builtins.int = ...) -> _SageObject: ...
def q_jordan(self, q: builtins.int = ...) -> _SageObject: ...
def q_subgroups_of_abelian_group(
    self, mu: builtins.object, q: builtins.int = ..., algorithm: builtins.str = ...
) -> _SageObject: ...
def q_stirling_number1(self, k: builtins.int, q: builtins.int = ...) -> _SageObject: ...
def q_stirling_number2(self, k: builtins.int, q: builtins.int = ...) -> _SageObject: ...
def number_of_irreducible_polynomials(
    self, q: builtins.int = ..., m: builtins.int = ...
) -> _SageObject: ...
