import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.structure.element import Element

class _SageObject: ...

class PrefixClosedSet:
    def __init__(self, words: builtins.object) -> None: ...
    @classmethod
    def create_by_alphabet(cls, alphabet: builtins.object) -> _SageObject: ...
    def add(self, w: builtins.object, check: builtins.bool = ...) -> None: ...
    def iterate_possible_additions(self) -> _SageObject: ...
    def prefix_set(self) -> list[Element]: ...

def minimize_result(self) -> _SageObject: ...

class RecognizableSeries:
    def __init__(
        self,
        parent: builtins.object,
        mu: builtins.object,
        left: builtins.object,
        right: builtins.object,
    ) -> None: ...
    @property
    def mu(self) -> _SageObject: ...
    @property
    def left(self) -> _SageObject: ...
    @property
    def right(self) -> _SageObject: ...
    def linear_representation(self) -> tuple[Element, ...]: ...
    def coefficient_of_word(
        self,
        w: builtins.object,
        multiply_left: builtins.bool = ...,
        multiply_right: builtins.bool = ...,
    ) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def is_trivial_zero(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def transposed(self) -> _SageObject: ...
    def minimized(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def hadamard_product(self, other: builtins.object) -> _SageObject: ...

class RecognizableSeriesSpace:
    Element: _SageObject

    @staticmethod
    def __classcall__(
        cls: builtins.object, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    @classmethod
    def __normalize__(
        cls,
        coefficient_ring: builtins.object = ...,
        alphabet: builtins.object = ...,
        indices: builtins.object = ...,
        category: builtins.object = ...,
        minimize_results: builtins.bool = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        coefficient_ring: builtins.object,
        indices: builtins.object,
        category: builtins.object,
        minimize_results: builtins.object,
    ) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def alphabet(self) -> _SageObject: ...
    def indices(self) -> _SageObject: ...
    def coefficient_ring(self) -> _SageObject: ...
    @property
    def minimize_results(self) -> _SageObject: ...
    def some_elements(self, **kwds: builtins.object) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def one_hadamard(self) -> _SageObject: ...
