from typing import TYPE_CHECKING
from sage.combinat.skew_tableau import SkewTableau
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.rings.integer import Integer
from sage.combinat.combinat import CombinatorialElement

if TYPE_CHECKING:
    from collections.abc import Iterator

class RibbonTableau(SkewTableau):
    """A ribbon tableau."""

    def __init__(self, parent, rt: list | tuple) -> None: ...
    def length(self) -> int: ...
    def to_word(self): ...

class RibbonTableaux(UniqueRepresentation, Parent):
    """Ribbon tableaux."""

    def __init__(self) -> None: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(self, rt: list | tuple) -> RibbonTableau: ...
    def from_expr(self, l: list) -> RibbonTableau: ...
    Element: type[RibbonTableau]

class RibbonTableaux_shape_weight_length(RibbonTableaux):
    """Ribbon tableaux of a given shape, weight, and length."""

    def __init__(self, shape, weight: tuple, length: int) -> None: ...
    def __iter__(self) -> 'Iterator[RibbonTableau]': ...
    def _repr_(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> Integer: ...

def insertion_tableau(skp, perm: list, evaluation: int, tableau: list, length: int) -> list: ...

def count_rec(nexts: list, current: list, part, weight: list, length: int) -> list[int]: ...

def list_rec(nexts: list, current: list, part, weight: list, length: int) -> list: ...

def spin_rec(t, nexts: list, current: list, part, weight: list, length: int) -> list: ...

def spin_polynomial_square(part, weight: list, length: int): ...

def spin_polynomial(part, weight: list, length: int): ...

def cospin_polynomial(part, weight: list, length: int): ...

def graph_implementation_rec(skp, weight: list, length: int, function): ...

class MultiSkewTableau(CombinatorialElement):
    """A multi skew tableau which is a tuple of skew tableaux."""

    def __init__(self, x: list) -> None: ...
    def size(self) -> int: ...
    def weight(self) -> list[int]: ...
    def shape(self) -> list: ...
    def inversion_pairs(self) -> list: ...
    def inversions(self) -> int: ...
    def _inversion_pairs_from_position(self, k: int, ij: tuple[int, int]) -> list: ...

class MultiSkewTableaux(UniqueRepresentation, Parent):
    """Multi skew tableaux."""

    def __init__(self, category=None) -> None: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(self, rt: list) -> MultiSkewTableau: ...
    Element: type[MultiSkewTableau]

class SemistandardMultiSkewTableaux(MultiSkewTableaux):
    """Semistandard multi skew tableaux."""

    def __init__(self, shape: tuple, weight) -> None: ...
    def _repr_(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> 'Iterator[MultiSkewTableau]': ...
