from collections.abc import Callable, Iterable, Iterator, Sequence

from sage.rings.integer import Integer
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

def number_of_rooted_trees(n: int | Integer) -> Integer: ...

class RootedTree:
    @staticmethod
    def __classcall_private__(
        cls: type[RootedTree],
        *args: object,
        **opts: object,
    ) -> RootedTree: ...
    def __init__(
        self,
        parent: Parent | None = ...,
        children: Iterable[object] = ...,
        check: bool = ...,
    ) -> None: ...
    def __iter__(self) -> Iterator[RootedTree]: ...
    def __len__(self) -> int: ...
    def sort_key(self) -> tuple[int, ...]: ...
    def __hash__(self) -> int: ...
    def normalize(self) -> None: ...
    def is_empty(self) -> bool: ...
    def number_of_nodes(self) -> int: ...
    def paths(self) -> Iterable[tuple[int, ...]]: ...
    def graft_list(self, other: RootedTree) -> list[RootedTree]: ...
    def graft_on_root(self, other: RootedTree) -> RootedTree: ...
    def single_graft(
        self,
        x: RootedTree,
        grafting_function: Sequence[tuple[int, ...]],
        path_prefix: tuple[int, ...] = ...,
    ) -> RootedTree: ...

class LabelledRootedTree(RootedTree):
    @staticmethod
    def __classcall_private__(
        cls: type[LabelledRootedTree],
        *args: object,
        **opts: object,
    ) -> LabelledRootedTree: ...
    def __init__(
        self,
        parent: Parent | None = ...,
        children: Iterable[object] = ...,
        label: object = ...,
        check: bool = ...,
    ) -> None: ...
    def __iter__(self) -> Iterator[LabelledRootedTree]: ...
    def label(self) -> object: ...
    def sort_key(self) -> tuple[object, ...]: ...
    def graft_list(
        self,
        other: RootedTree,
    ) -> list[LabelledRootedTree]: ...
    def graft_on_root(
        self,
        other: RootedTree,
    ) -> LabelledRootedTree: ...
    def single_graft(
        self,
        x: RootedTree,
        grafting_function: Sequence[tuple[int, ...]],
        path_prefix: tuple[int, ...] = ...,
    ) -> LabelledRootedTree: ...

class RootedTrees(UniqueRepresentation, Parent):
    @staticmethod
    def __classcall_private__(
        cls: type[RootedTrees],
        n: int | Integer | None = ...,
    ) -> RootedTrees_all | RootedTrees_size: ...

class RootedTrees_all(Parent):
    Element: type[RootedTree]
    element_class: type[RootedTree]
    def __init__(self) -> None: ...
    def __call__(
        self,
        children: Iterable[object] = ...,
        check: bool = ...,
    ) -> RootedTree: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> Iterator[RootedTree]: ...
    def unlabelled_trees(self) -> RootedTrees_all: ...
    def labelled_trees(self) -> LabelledRootedTrees_all: ...
    def leaf(self) -> RootedTree: ...

class RootedTrees_size(Parent):
    Element: type[RootedTree]
    element_class: type[RootedTree]
    def __init__(self, n: int | Integer) -> None: ...
    def __call__(
        self,
        children: Iterable[object] = ...,
        check: bool = ...,
    ) -> RootedTree: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> Iterator[RootedTree]: ...
    def check_element(
        self,
        el: object,
        check: bool = ...,
    ) -> None: ...
    def cardinality(self) -> Integer: ...

class LabelledRootedTrees(UniqueRepresentation, Parent):
    @staticmethod
    def __classcall_private__(
        cls: type[LabelledRootedTrees],
        n: int | Integer | None = ...,
    ) -> LabelledRootedTrees_all: ...

class LabelledRootedTrees_all(Parent):
    Element: type[LabelledRootedTree]
    element_class: type[LabelledRootedTree]
    def __init__(self, category: object = ...) -> None: ...
    def __call__(
        self,
        children: Iterable[object] = ...,
        label: object = ...,
        check: bool = ...,
    ) -> LabelledRootedTree: ...
    def __iter__(self) -> Iterator[LabelledRootedTree]: ...
    def unlabelled_trees(self) -> RootedTrees_all: ...
    def labelled_trees(self) -> LabelledRootedTrees_all: ...
