import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

def number_of_rooted_trees(self) -> _SageObject: ...

class RootedTree:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, *args: builtins.object, **opts: builtins.object
    ) -> _SageObject: ...
    def __init__(
        self,
        parent: builtins.object = ...,
        children: builtins.list[_SageObject] = ...,
        check: builtins.bool = ...,
    ) -> None: ...
    def sort_key(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def normalize(self) -> _SageObject: ...
    def is_empty(self) -> bool: ...
    def graft_list(self, other: builtins.object) -> _SageObject: ...
    def graft_on_root(self, other: builtins.object) -> _SageObject: ...
    def single_graft(
        self,
        x: builtins.object,
        grafting_function: builtins.object,
        path_prefix: builtins.tuple[_SageObject, ...] = ...,
    ) -> _SageObject: ...

class RootedTrees:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, n: builtins.int = ...
    ) -> _SageObject: ...

class RootedTrees_all:
    def __init__(self) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def unlabelled_trees(self) -> _SageObject: ...
    def labelled_trees(self) -> _SageObject: ...
    def leaf(self) -> _SageObject: ...
    Element: _SageObject

class RootedTrees_size:
    def __init__(self, n: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def check_element(
        self, el: builtins.object, check: builtins.bool = ...
    ) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def element_class(self) -> _SageObject: ...

class LabelledRootedTree:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, *args: builtins.object, **opts: builtins.object
    ) -> _SageObject: ...
    def sort_key(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...

class LabelledRootedTrees:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, n: builtins.int = ...
    ) -> _SageObject: ...

class LabelledRootedTrees_all:
    def __init__(self, category: builtins.object = ...) -> None: ...
    def unlabelled_trees(self) -> _SageObject: ...
    def labelled_trees(self) -> _SageObject: ...
    Element: _SageObject
