from collections.abc import Iterable, Iterator

from sage.combinat.partition import Partition
from sage.combinat.permutation import Permutation
from sage.plot.graphics import Graphics
from sage.structure.parent import Parent
from sage.combinat.core import AbstractSetPartition

class SetPartition(AbstractSetPartition):
    @classmethod
    def __classcall_private__(cls, parts: Iterable[Iterable[object]], check: bool = ...) -> SetPartition: ...
    def __init__(self, parent: Parent, s: Iterable[Iterable[object]], check: bool = ...) -> None: ...
    def check(self) -> None: ...
    def set_latex_options(self, **kwargs: object) -> None: ...
    def latex_options(self) -> dict[str, object]: ...
    def _latex_(self) -> str: ...
    def pipe(self, other: SetPartition) -> SetPartition: ...
    def shape(self) -> Partition: ...
    def to_permutation(self) -> Permutation: ...
    def to_restricted_growth_word(self, bijection: str = ...) -> tuple[int, ...] | list[int]: ...
    def to_restricted_growth_word_blocks(self) -> tuple[int, ...] | list[int]: ...
    def to_restricted_growth_word_intertwining(self) -> tuple[int, ...]: ...
    def openers(self) -> list[int]: ...
    def closers(self) -> list[int]: ...
    def to_rook_placement(self, bijection: str = ...) -> list[tuple[int, int]]: ...
    def to_rook_placement_gamma(self) -> list[tuple[int, int]]: ...
    def to_rook_placement_rho(self) -> list[tuple[int, int]]: ...
    def to_rook_placement_psi(self) -> list[tuple[int, int]]: ...
    def apply_permutation(self, p: Permutation) -> SetPartition: ...
    def crossings_iterator(self) -> Iterator[tuple[tuple[int, int], tuple[int, int]]]: ...
    def crossings(self) -> list[tuple[tuple[int, int], tuple[int, int]]]: ...
    def number_of_crossings(self) -> int: ...
    def is_noncrossing(self) -> bool: ...
    def nestings_iterator(self) -> Iterator[tuple[tuple[int, int], tuple[int, int]]]: ...
    def nestings(self) -> list[tuple[tuple[int, int], tuple[int, int]]]: ...
    def number_of_nestings(self) -> int: ...
    def is_nonnesting(self) -> bool: ...
    def is_atomic(self) -> bool: ...
    def standardization(self) -> SetPartition: ...
    def restriction(self, I: Iterable[object]) -> SetPartition: ...
    def ordered_set_partition_action(self, s: Iterable[Iterable[int]]) -> SetPartition: ...
    def refinements(self) -> list[SetPartition]: ...
    def strict_coarsenings(self) -> list[SetPartition]: ...
    def arcs(self) -> list[tuple[int, int]]: ...
    def plot(self, angle: float | None = ..., color: str = ..., base_set_dict: dict[object, object] | None = ...) -> Graphics: ...

    # Aliases
    cardinality = AbstractSetPartition.__len__
    size = AbstractSetPartition.base_set_cardinality
    shape_partition = shape
    to_partition = shape

    # Extra explicitly requested methods
    def number_of_blocks(self) -> int: ...
    def base_set(self) -> frozenset[object]: ...
    def base_set_cardinality(self) -> int: ...
    def blocks(self) -> list[frozenset[object]]: ...
    def coarsenings(self) -> list[SetPartition]: ...

