from collections.abc import Hashable, Iterable, Iterator, Sequence
from typing import Protocol, TypeAlias, overload

from sage.combinat.partition import Partition
from sage.combinat.permutation import Permutation
from sage.plot.graphics import Graphics
from sage.rings.integer import Integer
from sage.sets.set import Set_object
from sage.structure.parent import Parent

class AbstractSetPartition(Protocol):
    def __len__(self) -> int: ...
    def base_set_cardinality(self) -> int: ...

class _SetPartitionElement(Protocol):
    def __eq__(self, other: object) -> bool: ...

_SetPartitionElementInput: TypeAlias = Hashable | _SetPartitionElement

class SetPartition(AbstractSetPartition):
    @staticmethod
    def __classcall_private__(
        cls: type[SetPartition],
        parts: Iterable[Iterable[_SetPartitionElementInput]],
        check: bool = ...,
    ) -> SetPartition: ...
    @overload
    def __init__(
        self,
        parent: Parent,
        s: Iterable[Iterable[_SetPartitionElementInput]],
        check: bool = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        parts: Iterable[Iterable[_SetPartitionElementInput]],
        check: bool = ...,
    ) -> None: ...
    def check(self) -> None: ...
    def set_latex_options(self, **kwargs: float | bool | str | None) -> None: ...
    def latex_options(self) -> dict[str, float | bool | str | None]: ...
    def _latex_(self) -> str: ...
    def pipe(self, other: SetPartition) -> SetPartition: ...
    def shape(self) -> Partition: ...
    def to_permutation(self) -> Permutation: ...
    def to_restricted_growth_word(self, bijection: str = ...) -> tuple[int, ...] | list[int]: ...
    def to_restricted_growth_word_blocks(self) -> tuple[int, ...] | list[int]: ...
    def to_restricted_growth_word_intertwining(self) -> tuple[int, ...]: ...
    def openers(self) -> list[int]: ...
    def closers(self) -> list[int]: ...
    def to_rook_placement(self, bijection: str = ...) -> list[tuple[int, int]]: ...
    def to_rook_placement_gamma(self) -> list[tuple[int, int]]: ...
    def to_rook_placement_rho(self) -> list[tuple[int, int]]: ...
    def to_rook_placement_psi(self) -> list[tuple[int, int]]: ...
    def apply_permutation(self, p: Permutation) -> SetPartition: ...
    def crossings_iterator(self) -> Iterator[tuple[tuple[int, int], tuple[int, int]]]: ...
    def crossings(self) -> list[tuple[tuple[int, int], tuple[int, int]]]: ...
    def number_of_crossings(self) -> int: ...
    def is_noncrossing(self) -> bool: ...
    def nestings_iterator(self) -> Iterator[tuple[tuple[int, int], tuple[int, int]]]: ...
    def nestings(self) -> list[tuple[tuple[int, int], tuple[int, int]]]: ...
    def number_of_nestings(self) -> int: ...
    def is_nonnesting(self) -> bool: ...
    def is_atomic(self) -> bool: ...
    def standardization(self) -> SetPartition: ...
    def restriction(self, I: Iterable[_SetPartitionElementInput]) -> SetPartition: ...
    def ordered_set_partition_action(self, s: Iterable[Iterable[int]]) -> SetPartition: ...
    def refinements(self) -> list[SetPartition]: ...
    def strict_coarsenings(self) -> list[SetPartition]: ...
    def arcs(self) -> list[tuple[int, int]]: ...
    def plot(
        self,
        angle: float | None = ...,
        color: str = ...,
        base_set_dict: dict[_SetPartitionElementInput, float] | None = ...,
    ) -> Graphics: ...

    # Aliases
    cardinality = AbstractSetPartition.__len__
    size = AbstractSetPartition.base_set_cardinality
    shape_partition = shape
    to_partition = shape

    # Extra explicitly requested methods
    def number_of_blocks(self) -> int: ...
    def base_set(self) -> Set_object: ...
    def base_set_cardinality(self) -> int: ...
    def blocks(self) -> list[frozenset[_SetPartitionElementInput]]: ...
    def coarsenings(self) -> list[SetPartition]: ...

class SetPartitions(Parent):
    Element: type[SetPartition]

    @staticmethod
    def __classcall_private__(
        cls: type[SetPartitions],
        s: Iterable[_SetPartitionElementInput] | int | Integer | None = ...,
        part: int | Iterable[int] | Partition | None = ...,
    ) -> SetPartitions: ...
    def __init__(
        self,
        s: Iterable[_SetPartitionElementInput] | int | Integer | None = ...,
        part: int | Integer | Iterable[int | Integer] | Partition | None = ...,
    ) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def _element_constructor__(
        self, s: Iterable[Iterable[_SetPartitionElementInput]] | SetPartition, check: bool = ...
    ) -> SetPartition: ...
    def from_restricted_growth_word(
        self, w: Sequence[int | Integer], bijection: str = ...
    ) -> SetPartition: ...
    def from_restricted_growth_word_blocks(
        self, w: Sequence[int | Integer]
    ) -> SetPartition: ...
    def from_restricted_growth_word_intertwining(
        self, w: Sequence[int | Integer]
    ) -> SetPartition: ...
    def from_rook_placement(
        self,
        rooks: Iterable[tuple[int | Integer, int | Integer]],
        bijection: str = ...,
        n: int | Integer | None = ...,
    ) -> SetPartition: ...
    def from_arcs(
        self, arcs: Iterable[tuple[int | Integer, int | Integer]], n: int | Integer
    ) -> SetPartition: ...
    def from_rook_placement_gamma(
        self, rooks: Iterable[tuple[int | Integer, int | Integer]], n: int | Integer
    ) -> SetPartition: ...
    def from_rook_placement_rho(
        self, rooks: Iterable[tuple[int | Integer, int | Integer]], n: int | Integer
    ) -> SetPartition: ...
    def from_rook_placement_psi(
        self, rooks: Iterable[tuple[int | Integer, int | Integer]], n: int | Integer
    ) -> SetPartition: ...
    def is_less_than(self, s: SetPartition, t: SetPartition) -> bool: ...
