# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ShardPosetElement:
    def __new__(cls, p: builtins.int) -> Self: ...
    def __init__(self, p: builtins.int) -> None: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...

def shard_preorder_graph(runs: builtins.object) -> _SageObject: ...

def shard_poset(n: builtins.int) -> _SageObject: ...
