from collections.abc import Iterator

from sage.combinat.partition import Partition
from sage.combinat.permutation import Permutation
from sage.combinat.skew_partition import SkewPartition
from sage.combinat.tableau import SemistandardTableau, StandardTableau, Tableau
from sage.combinat.words.word import Word_class
from sage.structure.list_clone import ClonableList
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from typing import overload

class SkewTableau(ClonableList[tuple[int | None, ...]]):
    def check(self) -> None: ...
    def outer_shape(self) -> Partition: ...
    def inner_shape(self) -> Partition: ...
    def shape(self) -> SkewPartition: ...
    def outer_size(self) -> int: ...
    def inner_size(self) -> int: ...
    def size(self) -> int: ...
    def conjugate(self) -> SkewTableau: ...
    def to_word_by_row(self) -> Word_class: ...
    def to_word_by_column(self) -> Word_class: ...
    def to_word(self) -> Word_class: ...
    def to_permutation(self) -> Permutation: ...
    def weight(self) -> list[int]: ...
    def evaluation(self) -> list[int]: ...
    def is_standard(self) -> bool: ...
    def is_semistandard(self) -> bool: ...
    def to_tableau(self) -> Tableau: ...
    def pp(self) -> None: ...
    def to_list(self) -> list[list[int | None]]: ...
    def to_chain(self, max_entry: int | None = ...) -> list[Partition]: ...
    def slide(self, corner: tuple[int, int] | None = ..., return_vacated: bool = ...) -> SkewTableau | tuple[SkewTableau, tuple[int, int]]: ...
    def backward_slide(self, corner: tuple[int, int] | None = ...) -> SkewTableau: ...
    def reverse_slide(self, corner: tuple[int, int] | None = ...) -> SkewTableau: ...
    def rectify(self, algorithm: str | None = ...) -> Tableau | StandardTableau | SemistandardTableau: ...
    def add_entry(self, cell: tuple[int, int], m: int) -> SkewTableau: ...
    def anti_restrict(self, n: int) -> SkewTableau: ...
    def restriction_outer_shape(self, n: int) -> Partition: ...

class SkewTableaux(UniqueRepresentation, Parent):
    Element: type[SkewTableau]
    def _element_constructor_(self, st: object) -> SkewTableau: ...
    def __contains__(self, x: object) -> bool: ...
    def from_expr(self, expr: list[object]) -> SkewTableau: ...
    def from_chain(self, chain: list[Partition]) -> SkewTableau: ...
    def from_shape_and_word(self, shape: SkewPartition, word: list[int]) -> SkewTableau: ...

class StandardSkewTableaux(SkewTableaux):
    @staticmethod
    def __classcall_private__(cls: type[StandardSkewTableaux], skp: object = ...) -> StandardSkewTableaux_all | StandardSkewTableaux_size | StandardSkewTableaux_shape: ...
    def __contains__(self, x: object) -> bool: ...

class StandardSkewTableaux_all(StandardSkewTableaux):
    def _repr_(self) -> str: ...
    def __iter__(self) -> Iterator[SkewTableau]: ...

class StandardSkewTableaux_size(StandardSkewTableaux):
    def _repr_(self) -> str: ...
    def cardinality(self) -> int: ...

class StandardSkewTableaux_shape(StandardSkewTableaux):
    def _repr_(self) -> str: ...
    def cardinality(self) -> int: ...

class SemistandardSkewTableaux(SkewTableaux):
    @staticmethod
    def __classcall_private__(cls: type[SemistandardSkewTableaux], skp: object = ..., max_entry: int | None = ...) -> SemistandardSkewTableaux_all | SemistandardSkewTableaux_size | SemistandardSkewTableaux_shape: ...
    def __contains__(self, x: object) -> bool: ...

class SemistandardSkewTableaux_all(SemistandardSkewTableaux):
    def _repr_(self) -> str: ...
    def __iter__(self) -> Iterator[SkewTableau]: ...

class SemistandardSkewTableaux_size(SemistandardSkewTableaux):
    def _repr_(self) -> str: ...

class SemistandardSkewTableaux_shape(SemistandardSkewTableaux):
    def _repr_(self) -> str: ...
    def cardinality(self) -> int: ...
