# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SloaneSequence:
    def __init__(self, offset: builtins.int = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self, n: builtins.int) -> _SageObject: ...
    def list(self, n: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...

class A000001:
    def __init__(self) -> None: ...

class A000027:
    def __init__(self) -> None: ...
    link: _SageObject

class A000004:
    def __init__(self) -> None: ...

class A000005:
    def __init__(self) -> None: ...

class A000008:
    def __init__(self) -> None: ...

class A000009:
    def __init__(self) -> None: ...
    def cf(self) -> _SageObject: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A000796:
    def __init__(self) -> None: ...
    def pi(self) -> _SageObject: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A003418:
    def __init__(self) -> None: ...

class A007318:
    def __init__(self) -> None: ...
    keyword: _SageObject

class A008275:
    def __init__(self) -> None: ...
    keyword: _SageObject
    def s(self, n: builtins.int, k: builtins.int) -> _SageObject: ...

class A008277:
    def __init__(self) -> None: ...
    keyword: _SageObject
    def s2(self, n: builtins.int, k: builtins.int) -> _SageObject: ...

class A049310:
    def __init__(self) -> None: ...
    keyword: _SageObject

class A000010:
    def __init__(self) -> None: ...

class A000007:
    def __init__(self) -> None: ...

class A005843:
    def __init__(self) -> None: ...

class A000035:
    def __init__(self) -> None: ...

class A000169:
    def __init__(self) -> None: ...

class A000272:
    def __init__(self) -> None: ...

class A000312:
    def __init__(self) -> None: ...

class A001477:
    def __init__(self) -> None: ...

class A004526:
    def __init__(self) -> None: ...

class A000326:
    def __init__(self) -> None: ...

class A002378:
    def __init__(self) -> None: ...

class A002620:
    def __init__(self) -> None: ...

class A005408:
    def __init__(self) -> None: ...

class A000012:
    def __init__(self) -> None: ...

class A000120:
    def __init__(self) -> None: ...
    def f(self, n: builtins.int) -> _SageObject: ...

class A010060:
    def __init__(self) -> None: ...

class A000069:
    def __init__(self) -> None: ...

class A001969:
    def __init__(self) -> None: ...

class A000290:
    def __init__(self) -> None: ...

class A000225:
    def __init__(self) -> None: ...

class A000015:
    def __init__(self) -> None: ...

class A000016:
    def __init__(self) -> None: ...

class A000032:
    def __init__(self) -> None: ...

class A004086:
    def __init__(self) -> None: ...

class A002113:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A000030:
    def __init__(self) -> None: ...

class A000040:
    def __init__(self) -> None: ...

class A002808:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A018252:
    def __init__(self) -> None: ...

class A000043:
    def __init__(self) -> None: ...

class A000668:
    def __init__(self) -> None: ...

class A000396:
    def __init__(self) -> None: ...

class A005100:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A005101:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A002110:
    def __init__(self) -> None: ...

class A000720:
    def __init__(self) -> None: ...

class A064553:
    def __init__(self) -> None: ...

class A001055:
    def __init__(self) -> None: ...
    def nwf(self, n: builtins.int, m: builtins.int) -> _SageObject: ...

class A006530:
    def __init__(self) -> None: ...

class A000961:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A005117:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A020639:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A000041:
    def __init__(self) -> None: ...

class A000045:
    def __init__(self) -> None: ...
    def fib(self) -> _SageObject: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A000108:
    def __init__(self) -> None: ...

class A001006:
    def __init__(self) -> None: ...

class A000079:
    def __init__(self) -> None: ...

class A000578:
    def __init__(self) -> None: ...

class A000244:
    def __init__(self) -> None: ...

class A000302:
    def __init__(self) -> None: ...

class A000583:
    def __init__(self) -> None: ...

class A000142:
    def __init__(self) -> None: ...

class A000085:
    def __init__(self) -> None: ...

class A001189:
    def __init__(self) -> None: ...

class A000670:
    def __init__(self) -> None: ...

class A006318:
    def __init__(self) -> None: ...

class A000165:
    def __init__(self) -> None: ...

class A001147:
    def __init__(self) -> None: ...

class A006882:
    def __init__(self) -> None: ...
    def df(self) -> _SageObject: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A000984:
    def __init__(self) -> None: ...

class A001405:
    def __init__(self) -> None: ...

class A000292:
    def __init__(self) -> None: ...

class A000330:
    def __init__(self) -> None: ...

class ExtremesOfPermanentsSequence:
    def gen(self, a0: builtins.object, a1: builtins.object, d: builtins.object) -> _SageObject: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A000153:
    def __init__(self) -> None: ...

class A000255:
    def __init__(self) -> None: ...

class A000261:
    def __init__(self) -> None: ...

class A001909:
    def __init__(self) -> None: ...

class A001910:
    def __init__(self) -> None: ...

class ExtremesOfPermanentsSequence2:
    def gen(self, a0: builtins.object, a1: builtins.object, d: builtins.object) -> _SageObject: ...

class A090010:
    def __init__(self) -> None: ...

class A055790:
    def __init__(self) -> None: ...

class A090012:
    def __init__(self) -> None: ...

class A090013:
    def __init__(self) -> None: ...

class A090014:
    def __init__(self) -> None: ...

class A090015:
    def __init__(self) -> None: ...

class A090016:
    def __init__(self) -> None: ...

class A000166:
    def __init__(self) -> None: ...

class A000203:
    def __init__(self) -> None: ...

class A001157:
    def __init__(self) -> None: ...

class A008683:
    def __init__(self) -> None: ...

class A000204:
    def __init__(self) -> None: ...

class A000217:
    def __init__(self) -> None: ...

class A000124:
    def __init__(self) -> None: ...

class A002275:
    def __init__(self) -> None: ...

def recur_gen2b(a0: builtins.object, a1: builtins.object, a2: builtins.object, a3: builtins.object, b: builtins.object) -> _SageObject: ...

class RecurrenceSequence:
    def list(self, n: builtins.int) -> _SageObject: ...

class A001110:
    def __init__(self) -> None: ...
    link: _SageObject
    def g(self, k: builtins.int) -> _SageObject: ...

class A051959:
    def __init__(self) -> None: ...
    def g(self, k: builtins.int) -> _SageObject: ...

class A001221:
    def __init__(self) -> None: ...

class A001222:
    def __init__(self) -> None: ...

class A046660:
    ...

class A001227:
    def __init__(self) -> None: ...

class A001358:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A001694:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...
    def is_powerful(self, n: builtins.int) -> builtins.bool: ...

class A001836:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

def recur_gen2(a0: builtins.object, a1: builtins.object, a2: builtins.object, a3: builtins.object) -> _SageObject: ...

class RecurrenceSequence2:
    def list(self, n: builtins.int) -> _SageObject: ...

class A001906:
    def __init__(self) -> None: ...

class A001333:
    def __init__(self) -> None: ...

class A001045:
    def __init__(self) -> None: ...

class A000129:
    def __init__(self) -> None: ...

class A001109:
    def __init__(self) -> None: ...

class A015521:
    def __init__(self) -> None: ...

class A015523:
    def __init__(self) -> None: ...

class A015530:
    def __init__(self) -> None: ...

class A015531:
    def __init__(self) -> None: ...

class A015551:
    def __init__(self) -> None: ...

class A082411:
    def __init__(self) -> None: ...

class A083103:
    def __init__(self) -> None: ...

class A083104:
    def __init__(self) -> None: ...

class A083105:
    def __init__(self) -> None: ...

class A083216:
    def __init__(self) -> None: ...

class A061084:
    def __init__(self) -> None: ...
    keyword: _SageObject

def recur_gen3(a0: builtins.object, a1: builtins.object, a2: builtins.object, a3: builtins.object, a4: builtins.object, a5: builtins.object) -> _SageObject: ...

class A000213:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

class A000073:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...

def perm_mh(m: builtins.int, h: builtins.object) -> _SageObject: ...

class A079922:
    ...

class A079923:
    ...

class A109814:
    def __init__(self) -> None: ...

class A111774:
    def __init__(self) -> None: ...
    def list(self, n: builtins.int) -> _SageObject: ...
    def is_number_of_the_third_kind(self, n: builtins.int) -> builtins.bool: ...

class A111775:
    def __init__(self) -> None: ...

class A111787:
    def __init__(self) -> None: ...

class ExponentialNumbers:
    def __init__(self, a: builtins.object) -> None: ...

class A000110:
    def __init__(self) -> None: ...

class A000587:
    def __init__(self) -> None: ...

class A000100:
    def __init__(self) -> None: ...

class Sloane:
    def __dir__(self) -> _Iterable[builtins.str]: ...
    def __getattribute__(self, name: builtins.str) -> _SageObject: ...

sloane: _SageObject
