# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PairwiseCompatibleSubsets:
    def __init__(self, ambient: builtins.object, predicate: builtins.object, maximal: builtins.bool = ..., element_class: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __contains__(self, subset: builtins.object) -> builtins.bool: ...
    def post_process(self, subset_rest: builtins.object) -> _SageObject: ...
    def children(self, subset_rest: builtins.object) -> builtins.list[_SageObject]: ...
