import builtins

from sage.structure.element import Element

class _SageObject: ...

class PairwiseCompatibleSubsets:
    def __init__(
        self,
        ambient: builtins.object,
        predicate: builtins.object,
        maximal: builtins.bool = ...,
        element_class: builtins.object = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __contains__(self, subset: object) -> bool: ...
    def post_process(self, subset_rest: builtins.object) -> _SageObject: ...
    def children(self, subset_rest: builtins.object) -> list[Element]: ...
