import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.structure.element import Element

class _SageObject: ...

class SubwordComplexFacet:
    def __init__(
        self,
        parent: builtins.object,
        positions: builtins.object,
        facet_test: builtins.bool = ...,
    ) -> None: ...
    def extended_root_configuration(self) -> _SageObject: ...
    def root_configuration(self) -> _SageObject: ...
    def kappa_preimage(self) -> list[Element]: ...
    def is_vertex(self) -> bool: ...
    def root_cone(self) -> _SageObject: ...
    def upper_root_configuration(self) -> _SageObject: ...
    def extended_weight_configuration(
        self, coefficients: builtins.object = ...
    ) -> _SageObject: ...
    def weight_configuration(self) -> _SageObject: ...
    def weight_cone(self) -> _SageObject: ...
    def brick_vector(self, coefficients: builtins.object = ...) -> _SageObject: ...
    def flip(
        self, i: builtins.int, return_position: builtins.bool = ...
    ) -> _SageObject: ...
    def plot(
        self,
        list_colors: builtins.object = ...,
        labels: builtins.list[_SageObject] = ...,
        thickness: builtins.int = ...,
        fontsize: builtins.int = ...,
        shift: builtins.tuple[_SageObject, ...] = ...,
        compact: builtins.bool = ...,
        roots: builtins.bool = ...,
        **args: builtins.object,
    ) -> _SageObject: ...
    def show(self, *kwds: builtins.object, **args: builtins.object) -> _SageObject: ...

class SubwordComplex:
    @staticmethod
    def __classcall__(
        cls: builtins.object,
        Q: builtins.int,
        w: builtins.object,
        algorithm: builtins.str = ...,
    ) -> _SageObject: ...
    def __init__(
        self, Q: builtins.int, w: builtins.object, algorithm: builtins.str = ...
    ) -> None: ...
    def __call__(
        self, F: builtins.object, facet_test: builtins.bool = ...
    ) -> _SageObject: ...
    Element: _SageObject

    def __contains__(self, F: object) -> bool: ...
    def group(self) -> _SageObject: ...
    def cartan_type(self) -> _SageObject: ...
    def word(self) -> _SageObject: ...
    def pi(self) -> _SageObject: ...
    def facets(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def greedy_facet(self, side: builtins.str = ...) -> _SageObject: ...
    def is_sphere(self) -> bool: ...
    def is_ball(self) -> bool: ...
    def is_pure(self) -> bool: ...
    def dimension(self) -> _SageObject: ...
    def is_root_independent(self) -> bool: ...
    def is_double_root_free(self) -> bool: ...
    def kappa_preimages(self) -> _SageObject: ...
    def brick_fan(self) -> _SageObject: ...
    def brick_vectors(self, coefficients: builtins.object = ...) -> _SageObject: ...
    def minkowski_summand(self, i: builtins.int) -> _SageObject: ...
    def brick_polytope(self, coefficients: builtins.object = ...) -> _SageObject: ...
    def barycenter(self) -> _SageObject: ...
    def cover_relations(self, label: builtins.bool = ...) -> _SageObject: ...
    def increasing_flip_graph(self, label: builtins.bool = ...) -> _SageObject: ...
    def interval(self, I: builtins.int, J: builtins.int) -> set[Element]: ...
    def increasing_flip_poset(self) -> _SageObject: ...
