import builtins
from collections.abc import (
    Iterator,
)

from sage.rings.integer import Integer

class _SageObject: ...

def Subwords(
    self, k: builtins.int = ..., element_constructor: builtins.object = ...
) -> _SageObject: ...

class Subwords_w:
    def __init__(
        self, w: builtins.object, element_constructor: builtins.object
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __contains__(self, w: object) -> bool: ...
    def cardinality(self) -> Integer: ...
    def first(self) -> _SageObject: ...
    def last(self) -> _SageObject: ...
    def random_element(self) -> _SageObject: ...
    def __iter__(self) -> Iterator: ...

class Subwords_wk:
    def __init__(
        self, w: builtins.object, k: builtins.int, element_constructor: builtins.object
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __contains__(self, w: object) -> bool: ...
    def cardinality(self) -> Integer: ...
    def first(self) -> _SageObject: ...
    def last(self) -> _SageObject: ...
    def random_element(self) -> _SageObject: ...
    def __iter__(self) -> Iterator: ...

def smallest_positions(
    self, subword: builtins.object, pos: builtins.int = ...
) -> list | bool: ...
