import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.combinat.composition import Composition
from sage.combinat.partition import Partition
from sage.rings.integer import Integer
from sage.structure.element import Element

class _SageObject: ...

class SuperPartition:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, lst: builtins.object
    ) -> _SageObject: ...
    def __init__(
        self,
        parent: builtins.object,
        lst: builtins.object,
        check: builtins.bool = ...,
        immutable: builtins.bool = ...,
    ) -> None: ...
    def check(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> bool: ...
    def to_list(self) -> list[Element]: ...
    def to_composition(self) -> Composition: ...
    def to_partition(self) -> Partition: ...
    def antisymmetric_part(self) -> list[Element]: ...
    a_part: _SageObject

    def symmetric_part(self) -> list[Element]: ...
    s_part: _SageObject

    def bosonic_degree(self) -> int: ...
    degree: _SageObject

    def fermionic_degree(self) -> int: ...
    fermionic_sector: _SageObject

    def bi_degree(self) -> tuple[Element, ...]: ...
    def length(self) -> int: ...
    def bosonic_length(self) -> int: ...
    def shape_circled_diagram(self) -> Partition: ...
    @staticmethod
    def from_circled_diagram(
        shape: builtins.object, corners: builtins.object
    ) -> SuperPartition: ...
    def to_circled_diagram(self) -> list[Element]: ...
    def conjugate(self) -> SuperPartition: ...
    def zee(self) -> Integer: ...
    def sign(self) -> int: ...
    def dominates(self, other: builtins.object) -> bool: ...
    def add_horizontal_border_strip_star(self, h: builtins.object) -> list[Element]: ...
    def add_horizontal_border_strip_star_bar(
        self, h: builtins.object
    ) -> list[Element]: ...

class SuperPartitions:
    @staticmethod
    def __classcall_private__(
        self: builtins.object,
        n: builtins.int = ...,
        m: builtins.int = ...,
        **kwargs: builtins.object,
    ) -> _SageObject: ...
    def __init__(self, is_infinite: builtins.bool = ...) -> None: ...
    Element: _SageObject

    class options:
        NAME: _SageObject
        module: _SageObject
        display: _SageObject

    def __contains__(self, x: object) -> bool: ...

class SuperPartitions_n_m:
    m: builtins.int
    n: builtins.int

    def __init__(self, n: builtins.int, m: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SuperPartitions_n:
    n: builtins.int

    def __init__(self, n: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SuperPartitions_all:
    def __init__(self) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
