import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.rings.integer import Integer

class _SageObject: ...

class SemistandardSuperTableau:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, t: builtins.object
    ) -> _SageObject: ...
    def __init__(
        self,
        parent: builtins.object,
        t: builtins.object,
        check: builtins.bool = ...,
        preprocessed: builtins.bool = ...,
    ) -> None: ...
    def check(self) -> _SageObject: ...

class StandardSuperTableau:
    @staticmethod
    def __classcall_private__(
        self: builtins.object, t: builtins.object
    ) -> _SageObject: ...
    def check(self) -> _SageObject: ...
    def is_standard(self) -> bool: ...

class SemistandardSuperTableaux:
    @staticmethod
    def __classcall_private__(cls: builtins.object) -> _SageObject: ...
    Element: _SageObject

    def __contains__(self, x: object) -> bool: ...

class SemistandardSuperTableaux_all:
    def __init__(self) -> None: ...

class StandardSuperTableaux:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, n: builtins.int = ...
    ) -> _SageObject: ...
    Element: _SageObject

    def __contains__(self, x: object) -> bool: ...

class StandardSuperTableaux_all:
    def __init__(self) -> None: ...

class StandardSuperTableaux_size:
    size: Integer

    def __init__(self, n: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...

class StandardSuperTableaux_shape:
    shape: builtins.int

    def __init__(self, p: builtins.int) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
