# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SuperPartition:
    @staticmethod
    def __classcall_private__(cls: builtins.object, lst: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, lst: builtins.object, check: builtins.bool = ..., immutable: builtins.bool = ...) -> None: ...
    def check(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> builtins.bool: ...
    def to_list(self) -> builtins.list[_SageObject]: ...
    def to_composition(self) -> _SageObject: ...
    def to_partition(self) -> _SageObject: ...
    def antisymmetric_part(self) -> builtins.list[_SageObject]: ...
    a_part: _SageObject
    def symmetric_part(self) -> builtins.list[_SageObject]: ...
    s_part: _SageObject
    def bosonic_degree(self) -> builtins.int: ...
    degree: _SageObject
    def fermionic_degree(self) -> builtins.int: ...
    fermionic_sector: _SageObject
    def bi_degree(self) -> builtins.tuple[_SageObject, ...]: ...
    def length(self) -> builtins.int: ...
    def bosonic_length(self) -> builtins.int: ...
    def shape_circled_diagram(self) -> _SageObject: ...
    @staticmethod
    def from_circled_diagram(shape: builtins.object, corners: builtins.object) -> SuperPartition: ...
    def to_circled_diagram(self) -> builtins.list[_SageObject]: ...
    def conjugate(self) -> SuperPartition: ...
    def zee(self) -> _SageObject: ...
    def sign(self) -> builtins.int: ...
    def dominates(self, other: builtins.object) -> builtins.bool: ...
    def add_horizontal_border_strip_star(self, h: builtins.object) -> builtins.list[_SageObject]: ...
    def add_horizontal_border_strip_star_bar(self, h: builtins.object) -> builtins.list[_SageObject]: ...

class SuperPartitions:
    @staticmethod
    def __classcall_private__(self: builtins.object, n: builtins.int = ..., m: builtins.int = ..., **kwargs: builtins.object) -> _SageObject: ...
    def __init__(self, is_infinite: builtins.bool = ...) -> None: ...
    Element: _SageObject
    class options:
        NAME: _SageObject
        module: _SageObject
        display: _SageObject
    def __contains__(self, x: builtins.object) -> builtins.bool: ...

class SuperPartitions_n_m:
    def __init__(self, n: builtins.int, m: builtins.int) -> None: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SuperPartitions_n:
    def __init__(self, n: builtins.int) -> None: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class SuperPartitions_all:
    def __init__(self) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
