# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class TableauTuple:
    Element: _SageObject
    @staticmethod
    def __classcall_private__(self: builtins.object, t: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, t: builtins.object, check: builtins.bool = ...) -> None: ...
    def components(self) -> _SageObject: ...
    def to_list(self) -> _SageObject: ...
    def __call__(self, *cell: builtins.object) -> _SageObject: ...
    def level(self) -> _SageObject: ...
    def shape(self) -> _SageObject: ...
    def size(self) -> _SageObject: ...
    def conjugate(self) -> _SageObject: ...
    def pp(self) -> _SageObject: ...
    def to_word_by_row(self) -> _SageObject: ...
    to_word: _SageObject
    def to_word_by_column(self) -> _SageObject: ...
    def to_permutation(self) -> _SageObject: ...
    def entries(self) -> _SageObject: ...
    def entry(self, l: builtins.object, r: builtins.int, c: builtins.object) -> _SageObject: ...
    def is_row_strict(self) -> builtins.bool: ...
    def first_row_descent(self) -> _SageObject: ...
    def is_column_strict(self) -> builtins.bool: ...
    def first_column_descent(self) -> _SageObject: ...
    def is_standard(self) -> builtins.bool: ...
    def reduced_row_word(self) -> _SageObject: ...
    def reduced_column_word(self) -> _SageObject: ...
    def cells_containing(self, m: builtins.int) -> _SageObject: ...
    def up(self, n: builtins.int = ...) -> _SageObject: ...
    def row_stabilizer(self) -> _SageObject: ...
    def column_stabilizer(self) -> _SageObject: ...
    def charge(self) -> _SageObject: ...
    def cocharge(self) -> _SageObject: ...
    def add_entry(self, cell: builtins.object, m: builtins.int) -> _SageObject: ...
    def restrict(self, m: builtins.int = ...) -> _SageObject: ...
    def symmetric_group_action_on_entries(self, w: builtins.object) -> _SageObject: ...
    def content(self, k: builtins.int, multicharge: builtins.object) -> _SageObject: ...
    def residue(self, k: builtins.int, e: builtins.object, multicharge: builtins.object) -> _SageObject: ...

class RowStandardTableauTuple:
    @staticmethod
    def __classcall_private__(self: builtins.object, t: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, t: builtins.object, check: builtins.bool = ...) -> None: ...
    def inverse(self, k: builtins.int) -> _SageObject: ...
    def residue_sequence(self, e: builtins.object, multicharge: builtins.object) -> _SageObject: ...
    def degree(self, e: builtins.object, multicharge: builtins.object) -> _SageObject: ...
    def codegree(self, e: builtins.object, multicharge: builtins.object) -> _SageObject: ...

class StandardTableauTuple:
    @staticmethod
    def __classcall_private__(self: builtins.object, t: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, t: builtins.object, check: builtins.bool = ...) -> None: ...
    def dominates(self, t: builtins.object) -> _SageObject: ...
    def to_chain(self) -> _SageObject: ...
    def restrict(self, m: builtins.int = ...) -> _SageObject: ...

class TableauTuples:
    Element: _SageObject
    level_one_parent_class: _SageObject
    options: _SageObject
    @staticmethod
    def __classcall_private__(cls: builtins.object, level: builtins.object = ..., size: builtins.int = ...) -> _SageObject: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def level(self) -> _SageObject: ...
    def size(self) -> _SageObject: ...
    def list(self) -> _SageObject: ...

class TableauTuples_all:
    def __init__(self) -> None: ...
    def an_element(self) -> _SageObject: ...

class TableauTuples_level:
    def __init__(self, level: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def an_element(self) -> _SageObject: ...

class TableauTuples_size:
    def __init__(self, size: builtins.int) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def an_element(self) -> _SageObject: ...

class TableauTuples_level_size:
    def __init__(self, level: builtins.object, size: builtins.int) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def an_element(self) -> _SageObject: ...

class RowStandardTableauTuples:
    Element: _SageObject
    level_one_parent_class: _SageObject
    @staticmethod
    def __classcall_private__(cls: builtins.object, *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def __getitem__(self, r: builtins.int) -> _SageObject: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def shape(self) -> _SageObject: ...

class RowStandardTableauTuples_all:
    def __init__(self) -> None: ...
    def an_element(self) -> _SageObject: ...

class RowStandardTableauTuples_level:
    def __init__(self, level: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def an_element(self) -> _SageObject: ...

class RowStandardTableauTuples_size:
    def __init__(self, size: builtins.int) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def an_element(self) -> _SageObject: ...

class RowStandardTableauTuples_level_size:
    def __init__(self, level: builtins.object, size: builtins.int) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def an_element(self) -> _SageObject: ...

class RowStandardTableauTuples_shape:
    def __init__(self, shape: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...

class RowStandardTableauTuples_residue:
    def __init__(self, residue: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def quantum_characteristic(self) -> _SageObject: ...
    def multicharge(self) -> _SageObject: ...
    def level(self) -> _SageObject: ...
    def size(self) -> _SageObject: ...
    def residue_sequence(self) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...

class RowStandardTableauTuples_residue_shape:
    def __init__(self, residue: builtins.object, shape: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class StandardTableauTuples:
    Element: _SageObject
    level_one_parent_class: _SageObject
    @staticmethod
    def __classcall_private__(cls: builtins.object, *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def __getitem__(self, r: builtins.int) -> _SageObject: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def shape(self) -> _SageObject: ...

class StandardTableauTuples_all:
    def __init__(self) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class StandardTableauTuples_level:
    def __init__(self, level: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def an_element(self) -> _SageObject: ...

class StandardTableauTuples_size:
    def __init__(self, size: builtins.int) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def an_element(self) -> _SageObject: ...

class StandardTableauTuples_level_size:
    def __init__(self, level: builtins.object, size: builtins.int) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def an_element(self) -> _SageObject: ...

class StandardTableauTuples_shape:
    def __init__(self, shape: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def last(self) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    def random_element(self) -> _SageObject: ...

class StandardTableaux_residue:
    def __init__(self, residue: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class StandardTableaux_residue_shape:
    def __init__(self, residue: builtins.object, shape: builtins.object) -> None: ...
    def __contains__(self, t: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def an_element(self) -> _SageObject: ...
