# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class TamariBlossomingTree:
    @staticmethod
    def __classcall_private__(cls: builtins.object, tree: builtins.object) -> _SageObject: ...
    def __init__(self, parent: builtins.object, tree: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def size(self) -> _SageObject: ...
    def to_plane_tree(self) -> _SageObject: ...
    def to_tamari(self) -> _SageObject: ...
    @staticmethod
    def from_tamari(ltree: builtins.object, htree: builtins.object) -> TamariBlossomingTree: ...
    def to_TIP(self) -> _SageObject: ...
    @staticmethod
    def from_TIP(tip: builtins.object) -> TamariBlossomingTree: ...
    @staticmethod
    def binary_tree_plot(btree: builtins.object) -> _SageObject: ...
    def tamari_dual(self) -> Self: ...
    def plot_meandric(self, semicircle: builtins.bool = ..., arrow: builtins.bool = ...) -> _SageObject: ...
    @staticmethod
    def from_plane_tree(tree: builtins.object) -> TamariBlossomingTree: ...
    def reflection(self) -> Self: ...
    def plot_blossoming(self, aspect: builtins.float = ..., layout: builtins.str = ...) -> _SageObject: ...
    @staticmethod
    def binary_tree_smooth_drawing(btree: builtins.object, color: builtins.str = ...) -> _SageObject: ...
    def smooth_drawing(self) -> _SageObject: ...
    def is_synchronized(self) -> builtins.bool: ...
    def is_modern(self) -> builtins.bool: ...

class TamariBlossomingTrees:
    def __classcall_private__(cls: builtins.object, size: builtins.int = ...) -> _SageObject: ...

class TamariBlossomingTrees_all:
    Element: _SageObject
    def __init__(self) -> None: ...
    def __contains__(self, elem: builtins.object) -> builtins.bool: ...

class TamariBlossomingTrees_size:
    def __init__(self, size: builtins.int) -> None: ...
    def element_class(self) -> _SageObject: ...
    def __contains__(self, elem: builtins.object) -> builtins.bool: ...
    def cardinality(self) -> _SageObject: ...
    def random_element(self) -> TamariBlossomingTree: ...
    def __iter__(self) -> _Iterator[TamariBlossomingTree]: ...
    def random_synchronized_element(self) -> TamariBlossomingTree: ...
    def random_modern_element(self) -> TamariBlossomingTree: ...

class SynchronizedBlossomingTreeFactory:
    def __init__(self, size: builtins.int) -> None: ...
    def random_element(self) -> TamariBlossomingTree: ...

class ModernBlossomingTreeFactory:
    def __init__(self, size: builtins.int) -> None: ...
    def random_element(self) -> TamariBlossomingTree: ...
