import builtins

class _SageObject: ...

def paths_in_triangle(
    self, j: builtins.int, a: builtins.object, b: builtins.object
) -> list[tuple[int, ...]]: ...
def swap(self, i: builtins.int, m: builtins.int = ...) -> tuple[int, ...]: ...
def GeneralizedTamariLattice(
    self, b: builtins.object, m: builtins.int = ...
) -> _SageObject: ...
def TamariLattice(self, m: builtins.int = ...) -> _SageObject: ...
def swap_dexter(self, i: builtins.int) -> list[tuple[int, ...]]: ...
def DexterSemilattice(self) -> _SageObject: ...
