import builtins
from collections.abc import (
    Iterator,
)
from typing import Self

from sage.combinat.binary_tree import BinaryTree
from sage.combinat.interval_posets import TamariIntervalPoset
from sage.combinat.ordered_tree import OrderedTree
from sage.plot.graphics import Graphics
from sage.rings.integer import Integer

class _SageObject: ...

class TamariBlossomingTree:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object, tree: builtins.object
    ) -> _SageObject: ...
    def __init__(self, parent: builtins.object, tree: builtins.object) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def size(self) -> Integer: ...
    def to_plane_tree(self) -> OrderedTree: ...
    def to_tamari(self) -> tuple[BinaryTree, BinaryTree]: ...
    @staticmethod
    def from_tamari(ltree: builtins.object, htree: builtins.object) -> Self: ...
    def to_TIP(self) -> TamariIntervalPoset: ...
    @staticmethod
    def from_TIP(tip: builtins.object) -> Self: ...
    @staticmethod
    def binary_tree_plot(btree: builtins.object) -> Graphics: ...
    def tamari_dual(self) -> Self: ...
    def plot_meandric(
        self, semicircle: builtins.bool = ..., arrow: builtins.bool = ...
    ) -> Graphics: ...
    @staticmethod
    def from_plane_tree(tree: builtins.object) -> Self: ...
    def reflection(self) -> Self: ...
    def plot_blossoming(
        self, aspect: builtins.float = ..., layout: builtins.str = ...
    ) -> Graphics: ...
    @staticmethod
    def binary_tree_smooth_drawing(
        btree: builtins.object, color: builtins.str = ...
    ) -> Graphics: ...
    def smooth_drawing(self) -> Graphics: ...
    def is_synchronized(self) -> bool: ...
    def is_modern(self) -> bool: ...

class TamariBlossomingTrees:
    def __classcall_private__(self, size: builtins.int = ...) -> _SageObject: ...

class TamariBlossomingTrees_all:
    Element: _SageObject

    def __init__(self) -> None: ...
    def __contains__(self, elem: object) -> bool: ...

class TamariBlossomingTrees_size:
    def __init__(self, size: builtins.int) -> None: ...
    def element_class(self) -> _SageObject: ...
    def __contains__(self, elem: object) -> bool: ...
    def cardinality(self) -> Integer: ...
    def random_element(self) -> TamariBlossomingTree: ...
    def __iter__(self) -> Iterator[TamariBlossomingTree]: ...
    def random_synchronized_element(self) -> TamariBlossomingTree: ...
    def random_modern_element(self) -> TamariBlossomingTree: ...

class SynchronizedBlossomingTreeFactory:
    def __init__(self, size: builtins.int) -> None: ...
    def random_element(self) -> TamariBlossomingTree: ...

class ModernBlossomingTreeFactory:
    def __init__(self, size: builtins.int) -> None: ...
    def random_element(self) -> TamariBlossomingTree: ...
