import builtins
from collections.abc import (
    Iterator as _Iterator,
)
from typing import Self

class _SageObject: ...

def ncube_isometry_group(
    self, orientation_preserving: builtins.bool = ...
) -> _SageObject: ...
def ncube_isometry_group_cosets(
    self, orientation_preserving: builtins.bool = ...
) -> _SageObject: ...

class Polyomino:
    def __init__(
        self,
        coords: builtins.object,
        color: builtins.str = ...,
        dimension: builtins.int = ...,
    ) -> None: ...
    def color(self, color: builtins.object = ...) -> _SageObject: ...
    def frozenset(self) -> _SageObject: ...
    def sorted_list(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def bounding_box(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def intersection(self, other: builtins.object) -> _SageObject: ...
    def __sub__(self, v: builtins.object) -> Self: ...
    def __add__(self, v: builtins.object) -> Self: ...
    def __rmul__(self, m: builtins.int) -> Self: ...
    def canonical(self) -> _SageObject: ...
    def canonical_isometric_copies(
        self,
        orientation_preserving: builtins.bool = ...,
        mod_box_isometries: builtins.bool = ...,
    ) -> _SageObject: ...
    def translated_copies(self, box: builtins.object) -> _SageObject: ...
    def translated_copies_intersection(self, box: builtins.object) -> _SageObject: ...
    def isometric_copies(
        self,
        box: builtins.object,
        orientation_preserving: builtins.bool = ...,
        mod_box_isometries: builtins.bool = ...,
    ) -> _SageObject: ...
    def isometric_copies_intersection(
        self, box: builtins.object, orientation_preserving: builtins.bool = ...
    ) -> _SageObject: ...
    def neighbor_edges(self) -> _SageObject: ...
    def center(self) -> _SageObject: ...
    def boundary(self) -> _SageObject: ...
    def show3d(self, size: builtins.int = ...) -> _SageObject: ...
    def show2d(
        self,
        size: builtins.float = ...,
        color: builtins.str = ...,
        thickness: builtins.int = ...,
    ) -> _SageObject: ...
    def self_surrounding(
        self,
        radius: builtins.object,
        remove_incomplete_copies: builtins.bool = ...,
        ncpus: builtins.object = ...,
    ) -> _SageObject: ...

class TilingSolver:
    def __init__(
        self,
        pieces: builtins.object,
        box: builtins.object,
        rotation: builtins.bool = ...,
        reflection: builtins.bool = ...,
        reusable: builtins.bool = ...,
        outside: builtins.bool = ...,
    ) -> None: ...
    def is_suitable(self) -> bool: ...
    def pieces(self) -> _SageObject: ...
    def space(self) -> _SageObject: ...
    def coord_to_int_dict(self) -> _SageObject: ...
    def int_to_coord_dict(self) -> _SageObject: ...
    def rows_for_piece(
        self, i: builtins.int, mod_box_isometries: builtins.bool = ...
    ) -> _SageObject: ...
    def rows(self) -> _SageObject: ...
    def nrows_per_piece(self) -> _SageObject: ...
    def starting_rows(self) -> _SageObject: ...
    def row_to_polyomino(self, row_number: builtins.object) -> _SageObject: ...
    def dlx_solver(self) -> _SageObject: ...
    def solve(self, partial: builtins.object = ...) -> _SageObject: ...
    def number_of_solutions(self) -> _SageObject: ...
    def animate(
        self,
        partial: builtins.object = ...,
        stop: builtins.int = ...,
        size: builtins.float = ...,
        axes: builtins.bool = ...,
    ) -> _SageObject: ...
