# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Triangle:
    def __init__(self, poly: builtins.object, variables: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self, *args: builtins.object) -> _SageObject: ...
    def __getitem__(self, *args: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def matrix(self) -> _SageObject: ...
    def polynomial(self) -> _SageObject: ...
    def truncate(self, d: builtins.object) -> _SageObject: ...
    def factor(self) -> builtins.list[_SageObject]: ...

class M_triangle:
    def dual(self) -> M_triangle: ...
    def transmute(self) -> M_triangle: ...
    def h(self) -> H_triangle: ...
    def f(self) -> F_triangle: ...

class H_triangle:
    def transpose(self) -> H_triangle: ...
    def m(self) -> M_triangle: ...
    def f(self) -> F_triangle: ...
    def gamma(self) -> Gamma_triangle: ...
    def vector(self) -> _SageObject: ...

class F_triangle:
    def h(self) -> H_triangle: ...
    def m(self) -> M_triangle: ...
    def parabolic(self) -> F_triangle: ...
    def vector(self) -> _SageObject: ...

class Gamma_triangle:
    def h(self) -> H_triangle: ...
    def vector(self) -> _SageObject: ...
