import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class Tuples:
    k: builtins.int

    @staticmethod
    def __classcall_private__(
        cls: builtins.object, S: builtins.object, k: builtins.int
    ) -> _SageObject: ...
    def __init__(self, S: builtins.object, k: builtins.int) -> None: ...
    def unrank(self, i: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...

Tuples_sk: _SageObject

class UnorderedTuples:
    k: builtins.int

    @staticmethod
    def __classcall_private__(
        cls: builtins.object, S: builtins.object, k: builtins.int
    ) -> _SageObject: ...
    def __init__(self, S: builtins.object, k: builtins.int) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def cardinality(self) -> _SageObject: ...

UnorderedTuples_sk: _SageObject
