# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def YangBaxterGraph(partition: builtins.object = ..., root: builtins.object = ..., operators: builtins.object = ...) -> _SageObject: ...

class YangBaxterGraph_generic:
    def __init__(self, root: builtins.object, operators: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __len__(self) -> builtins.int: ...
    def __copy__(self) -> Self: ...
    def root(self) -> _SageObject: ...
    def successors(self, v: builtins.object) -> builtins.list[_SageObject]: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def vertices(self, sort: builtins.bool = ...) -> builtins.list[_SageObject]: ...
    def edges(self) -> _SageObject: ...
    def vertex_relabelling_dict(self, v: builtins.object, relabel_operator: builtins.object) -> builtins.dict[_SageObject, _SageObject]: ...
    def relabel_vertices(self, v: builtins.object, relabel_operator: builtins.object, inplace: builtins.bool = ...) -> _SageObject: ...
    def relabel_edges(self, edge_dict: builtins.object, inplace: builtins.bool = ...) -> _SageObject: ...

class YangBaxterGraph_partition:
    def __init__(self, partition: builtins.object) -> None: ...
    def __copy__(self) -> Self: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def vertex_relabelling_dict(self, v: builtins.object) -> builtins.dict[_SageObject, _SageObject]: ...
    def relabel_vertices(self, v: builtins.object, inplace: builtins.bool = ...) -> _SageObject: ...

class SwapOperator:
    def __init__(self, i: builtins.int) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self, u: builtins.object) -> _SageObject: ...
    def position(self) -> _SageObject: ...

class SwapIncreasingOperator:
    def __call__(self, u: builtins.object) -> _SageObject: ...
