from sage.structure.element import Element

class CGraph:
    def check_vertex(self, n: int) -> Element: ...
    def add_vertex(self, k: int) -> Element: ...
    def add_vertices(self, verts: Element | int | str | bool | None) -> Element: ...
    def del_vertex(self, v: Element) -> Element: ...
    def realloc(self, total: Element | int | str | bool | None) -> Element: ...
    def add_arc(self, u: Element | int | str | bool | None, v: Element) -> Element: ...
    def del_all_arcs(self, u: Element | int | str | bool | None, v: Element) -> Element: ...
    def del_arc_label(self, u: Element | int | str | bool | None, v: Element, l: Element | int | str | bool | None) -> Element: ...

class CGraphBackend(GenericGraphBackend):
    def c_graph(self) -> Element: ...
    def loops(self, new: Element | int | str | bool | None) -> Element: ...
    def n_edges(self, directed: Element | int | str | bool | None) -> Element: ...
    def n_vertices(self) -> Element: ...
    def has_vertex(self, v: Element) -> bool: ...
    def add_vertex(self, name: str) -> Element: ...
    def add_vertices(self, vertices: Element | int | str | bool | None) -> Element: ...
    def del_vertex(self, v: Element) -> Element: ...
    def del_vertices(self, vertices: Element | int | str | bool | None) -> Element: ...
    def iterator_verts(self, verts: Element | int | str | bool | None) -> Element: ...
    def relabel(self, perm: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def degree(self, v: Element, directed: Element | int | str | bool | None) -> int: ...
    def out_degree(self, v: Element) -> Element: ...
    def in_degree(self, v: Element) -> Element: ...
    def iterator_nbrs(self, v: Element) -> Element: ...
    def iterator_in_nbrs(self, v: Element) -> Element: ...
    def iterator_out_nbrs(self, v: Element) -> Element: ...
    def add_edges(self, edges: Element | int | str | bool | None, directed: Element | int | str | bool | None, remove_loops: Element | int | str | bool | None) -> Element: ...
    def add_edge(self, u: Element | int | str | bool | None, v: Element, l: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def del_edges(self, edges: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def del_edge(self, u: Element | int | str | bool | None, v: Element, l: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def iterator_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None) -> Element: ...
    def iterator_unsorted_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None) -> Element: ...
    def iterator_out_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None) -> Element: ...
    def iterator_in_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None) -> Element: ...
    def _iterator_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None, modus: Element | int | str | bool | None) -> Element: ...
    def is_subgraph(self, other: Element, vertices: Element | int | str | bool | None, ignore_labels: Element | int | str | bool | None) -> bool: ...
    def subgraph_given_vertices(self, other: Element, vertices: Element | int | str | bool | None) -> Element: ...
    def shortest_path_special(self, x: Element, y: Element, exclude_vertices: Element | int | str | bool | None, exclude_edges: Element | int | str | bool | None, distance_flag: Element | int | str | bool | None) -> Element: ...
    def shortest_path(self, x: Element, y: Element, distance_flag: Element | int | str | bool | None) -> Element: ...
    def is_connected(self, forbidden_vertices: Element | int | str | bool | None) -> bool: ...
    def is_strongly_connected(self) -> bool: ...
    def strongly_connected_component_containing_vertex(self, v: Element) -> Element: ...
    def is_directed_acyclic(self, certificate: Element | int | str | bool | None) -> bool: ...

class Search_iterator:
    ...

class GenericGraphBackend: ...
