# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CGraph:
    def has_vertex(self, n: builtins.object) -> builtins.bool: ...
    def check_vertex(self, n: builtins.object) -> _SageObject: ...
    def add_vertex_unsafe(self, k: builtins.object) -> _SageObject: ...
    def add_vertex(self, k: builtins.object = ...) -> _SageObject: ...
    def add_vertices(self, verts: builtins.object) -> _SageObject: ...
    def del_vertex_unsafe(self, v: builtins.object) -> _SageObject: ...
    def del_vertex(self, v: builtins.object) -> _SageObject: ...
    def current_allocation(self) -> _SageObject: ...
    def verts(self) -> _SageObject: ...
    def realloc(self, total: builtins.object) -> _SageObject: ...
    def del_arc_unsafe(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def add_arc(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def has_arc(self, u: builtins.object, v: builtins.object) -> builtins.bool: ...
    def del_all_arcs(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def add_arc_label_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> _SageObject: ...
    def has_arc_label_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> builtins.bool: ...
    def del_arc_label_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> _SageObject: ...
    def arc_label_unsafe(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def all_arcs_unsafe(self, u: builtins.object, v: builtins.object, arc_labels: builtins.object, size: builtins.object) -> _SageObject: ...
    def arc_label(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def all_arcs(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def del_arc_label(self, u: builtins.object, v: builtins.object, l: builtins.object) -> _SageObject: ...
    def has_arc_label(self, u: builtins.object, v: builtins.object, l: builtins.object) -> builtins.bool: ...
    def out_neighbors_unsafe(self, u: builtins.object, neighbors: builtins.object, size: builtins.object) -> _SageObject: ...
    def in_neighbors_unsafe(self, u: builtins.object, neighbors: builtins.object, size: builtins.object) -> _SageObject: ...
    def next_out_neighbor_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> _SageObject: ...
    def next_in_neighbor_unsafe(self, v: builtins.object, u: builtins.object, l: builtins.object) -> _SageObject: ...
    def adjacency_sequence_out(self, n: builtins.object, vertices: builtins.object, v: builtins.object, sequence: builtins.object) -> _SageObject: ...
    def adjacency_sequence_in(self, n: builtins.object, vertices: builtins.object, v: builtins.object, sequence: builtins.object) -> _SageObject: ...
    def out_neighbors(self, u: builtins.object) -> _SageObject: ...
    def in_neighbors(self, v: builtins.object) -> _SageObject: ...

class CGraphBackend:
    def cg(self) -> _SageObject: ...
    def c_graph(self) -> _SageObject: ...
    def loops(self, new: builtins.object = ...) -> _SageObject: ...
    def n_edges(self, directed: builtins.object) -> _SageObject: ...
    def n_vertices(self) -> _SageObject: ...
    def get_vertex(self, u: builtins.object) -> _SageObject: ...
    def get_vertex_checked(self, u: builtins.object) -> _SageObject: ...
    def vertex_label(self, u_int: builtins.object) -> _SageObject: ...
    def check_labelled_vertex(self, u: builtins.object, reverse: builtins.object) -> _SageObject: ...
    def has_vertex(self, v: builtins.object) -> builtins.bool: ...
    def add_vertex(self, name: builtins.object) -> _SageObject: ...
    def add_vertices(self, vertices: builtins.object) -> _SageObject: ...
    def del_vertex(self, v: builtins.object) -> _SageObject: ...
    def del_vertices(self, vertices: builtins.object) -> _SageObject: ...
    def iterator_verts(self, verts: builtins.object = ...) -> _SageObject: ...
    def relabel(self, perm: builtins.object, directed: builtins.object) -> _SageObject: ...
    def degree(self, v: builtins.object, directed: builtins.object) -> _SageObject: ...
    def out_degree(self, v: builtins.object) -> _SageObject: ...
    def in_degree(self, v: builtins.object) -> _SageObject: ...
    def iterator_nbrs(self, v: builtins.object) -> _SageObject: ...
    def iterator_in_nbrs(self, v: builtins.object) -> _SageObject: ...
    def iterator_out_nbrs(self, v: builtins.object) -> _SageObject: ...
    def new_edge_label(self, l: builtins.object) -> _SageObject: ...
    def add_edges(self, edges: builtins.object, directed: builtins.object, remove_loops: builtins.object = ...) -> _SageObject: ...
    def add_edge(self, u: builtins.object, v: builtins.object, l: builtins.object, directed: builtins.object) -> _SageObject: ...
    def del_edges(self, edges: builtins.object, directed: builtins.object) -> _SageObject: ...
    def del_edge(self, u: builtins.object, v: builtins.object, l: builtins.object, directed: builtins.object) -> _SageObject: ...
    def free_edge_label(self, l_int: builtins.object) -> _SageObject: ...
    def iterator_edges(self, vertices: builtins.object, labels: builtins.object) -> _SageObject: ...
    def iterator_unsorted_edges(self, vertices: builtins.object, labels: builtins.object) -> _SageObject: ...
    def iterator_out_edges(self, vertices: builtins.object, labels: builtins.object) -> _SageObject: ...
    def iterator_in_edges(self, vertices: builtins.object, labels: builtins.object) -> _SageObject: ...
    def is_subgraph(self, other: builtins.object, vertices: builtins.object, ignore_labels: builtins.object = ...) -> builtins.bool: ...
    def subgraph_given_vertices(self, other: builtins.object, vertices: builtins.object) -> _SageObject: ...
    def shortest_path_special(self, x: builtins.object, y: builtins.object, exclude_vertices: builtins.object = ..., exclude_edges: builtins.object = ..., distance_flag: builtins.object = ...) -> _SageObject: ...
    def shortest_path(self, x: builtins.object, y: builtins.object, distance_flag: builtins.object = ...) -> _SageObject: ...
    def weight_function(e: builtins.object) -> _SageObject: ...
    def is_connected(self, forbidden_vertices: builtins.object = ...) -> builtins.bool: ...
    def is_strongly_connected(self) -> builtins.bool: ...
    def strongly_connected_component_containing_vertex(self, v: builtins.object) -> _SageObject: ...
    def is_directed_acyclic(self, certificate: builtins.object = ...) -> builtins.bool: ...

class Search_iterator:
    def __dealloc__(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def next_breadth_first_search(self) -> _SageObject: ...
    def next_depth_first_search(self) -> _SageObject: ...
    def __next__(self) -> _SageObject: ...
