from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class GenericGraphBackend(SageObject):
    def add_edge(self, u: Element | int | str | bool | None, v: Element, l: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def add_edges(self, edges: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def add_vertex(self, name: str) -> Element: ...
    def add_vertices(self, vertices: Element | int | str | bool | None) -> Element: ...
    def degree(self, v: Element, directed: Element | int | str | bool | None) -> int: ...
    def in_degree(self, v: Element) -> Element: ...
    def out_degree(self, v: Element) -> Element: ...
    def del_edge(self, u: Element | int | str | bool | None, v: Element, l: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def del_vertex(self, v: Element) -> Element: ...
    def del_vertices(self, vertices: Element | int | str | bool | None) -> Element: ...
    def get_edge_label(self, u: Element | int | str | bool | None, v: Element) -> Element: ...
    def has_edge(self, u: Element | int | str | bool | None, v: Element, l: Element | int | str | bool | None) -> bool: ...
    def has_vertex(self, v: Element) -> bool: ...
    def iterator_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None) -> Element: ...
    def iterator_in_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None) -> Element: ...
    def iterator_out_edges(self, vertices: Element | int | str | bool | None, labels: Element | int | str | bool | None) -> Element: ...
    def iterator_nbrs(self, v: Element) -> Element: ...
    def iterator_in_nbrs(self, v: Element) -> Element: ...
    def iterator_out_nbrs(self, v: Element) -> Element: ...
    def iterator_verts(self, verts: Element | int | str | bool | None) -> Element: ...
    def loops(self, new: Element | int | str | bool | None) -> Element: ...
    def multiple_edges(self, new: Element | int | str | bool | None) -> Element: ...
    def name(self, new: Element | int | str | bool | None) -> str: ...
    def n_edges(self, directed: Element | int | str | bool | None) -> Element: ...
    def n_vertices(self) -> Element: ...
    def relabel(self, perm: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def set_edge_label(self, u: Element | int | str | bool | None, v: Element, l: Element | int | str | bool | None, directed: Element | int | str | bool | None) -> Element: ...
    def unpickle_graph_backend(self, directed: Element | int | str | bool | None, vertices: Element | int | str | bool | None, edges: Element | int | str | bool | None, kwds: Element | int | str | bool | None) -> Element: ...
