# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def compare(a: builtins.object, b: builtins.object) -> _SageObject: ...

class SparseGraph:
    def __dealloc__(self) -> _SageObject: ...
    def realloc(self, total: builtins.object) -> _SageObject: ...
    def is_directed(self) -> builtins.bool: ...
    def del_arc_unsafe(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def next_out_neighbor_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> _SageObject: ...
    def next_neighbor_BTNode_unsafe(self, vertices: builtins.object, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def out_degree(self, u: builtins.object) -> _SageObject: ...
    def next_in_neighbor_unsafe(self, v: builtins.object, u: builtins.object, l: builtins.object) -> _SageObject: ...
    def out_neighbors_unsafe(self, u: builtins.object, neighbors: builtins.object, size: builtins.object) -> _SageObject: ...
    def in_neighbors_unsafe(self, u: builtins.object, neighbors: builtins.object, size: builtins.object) -> _SageObject: ...
    def in_degree(self, v: builtins.object) -> _SageObject: ...
    def add_arc_label_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> _SageObject: ...
    def add_arc_label(self, u: builtins.object, v: builtins.object, l: builtins.object = ...) -> _SageObject: ...
    def arc_label_unsafe(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def all_arcs_unsafe(self, u: builtins.object, v: builtins.object, arc_labels: builtins.object, size: builtins.object) -> _SageObject: ...
    def arc_labels_unsafe(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def del_arc_label_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> _SageObject: ...
    def has_arc_label_unsafe(self, u: builtins.object, v: builtins.object, l: builtins.object) -> builtins.bool: ...

class SparseGraphBackend:
    def __init__(self, n: builtins.object, directed: builtins.object = ...) -> None: ...
    def new_edge_label(self, l: builtins.object) -> _SageObject: ...
    def free_edge_label(self, l_int: builtins.object) -> _SageObject: ...
    def get_edge_label(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def has_edge(self, u: builtins.object, v: builtins.object, l: builtins.object) -> builtins.bool: ...
    def multiple_edges(self, new: builtins.object) -> _SageObject: ...
    def set_edge_label(self, u: builtins.object, v: builtins.object, l: builtins.object, directed: builtins.object) -> _SageObject: ...
