import builtins

class _SageObject: ...

def pari_to_cdf(g: builtins.object) -> _SageObject: ...
def new_gen_from_complex_double_element(self) -> _SageObject: ...
def complex_double_element_eta(self, flag: builtins.object) -> _SageObject: ...
def complex_double_element_agm(self, right: builtins.object) -> _SageObject: ...
def complex_double_element_dilog(self) -> _SageObject: ...
def complex_double_element_gamma(self) -> _SageObject: ...
def complex_double_element_gamma_inc(self, t: builtins.object) -> _SageObject: ...
def complex_double_element_zeta(self) -> _SageObject: ...
