# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def pari_to_cdf(g: builtins.object) -> _SageObject: ...

def new_gen_from_complex_double_element(self: builtins.object) -> _SageObject: ...

def complex_double_element_eta(self: builtins.object, flag: builtins.object) -> _SageObject: ...

def complex_double_element_agm(self: builtins.object, right: builtins.object) -> _SageObject: ...

def complex_double_element_dilog(self: builtins.object) -> _SageObject: ...

def complex_double_element_gamma(self: builtins.object) -> _SageObject: ...

def complex_double_element_gamma_inc(self: builtins.object, t: builtins.object) -> _SageObject: ...

def complex_double_element_zeta(self: builtins.object) -> _SageObject: ...
