from typing import Self

from sage.modular.modform_hecketriangle.abstract_ring import FormsRing_abstract
from sage.modular.modform_hecketriangle.element import FormsElement
from sage.modular.modform_hecketriangle.hecke_triangle_group_element import (
    HeckeTriangleGroupElement,
)
from sage.modular.modform_hecketriangle.hecke_triangle_groups import HeckeTriangleGroup
from sage.modular.modform_hecketriangle.subspace import SubSpaceForms
from sage.modules.free_module import FreeModule_generic
from sage.rings.infinity import PlusInfinity
from sage.rings.laurent_series_ring_element import LaurentSeries
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import Element as SageElement
from sage.structure.element import Vector

class FormsSpace_abstract(FormsRing_abstract):
    Element: type[FormsElement]
    def __init__(
        self,
        group: HeckeTriangleGroup,
        base_ring: Ring,
        k: Rational | int,
        ep: HeckeTriangleGroupElement | int | None,
        n: int | None,
    ) -> None: ...
    def one(self) -> FormsElement: ...
    def is_ambient(self) -> bool: ...
    def ambient_space(self) -> Self: ...
    def module(self) -> FreeModule_generic: ...
    def ambient_module(self) -> FreeModule_generic: ...
    def subspace(self, basis: list[FormsElement]) -> SubSpaceForms: ...
    def change_ring(self, new_base_ring: Ring) -> Self: ...
    def construction(self) -> tuple[object, ...]: ...
    def weight(self) -> Rational | int: ...
    def ep(self) -> HeckeTriangleGroupElement | int | None: ...
    def contains_coeff_ring(self) -> bool: ...
    def element_from_coordinates(self, vec: Vector) -> FormsElement: ...
    def element_from_ambient_coordinates(self, vec: Vector) -> FormsElement: ...
    def homogeneous_part(self, k: Rational | int, ep: HeckeTriangleGroupElement | int | None) -> Self: ...
    def weight_parameters(self) -> tuple[Rational, Rational]: ...
    def aut_factor(self, gamma: HeckeTriangleGroupElement, t: SageElement) -> SageElement: ...
    def F_simple(self, order_1: SageElement | int = ...) -> FormsElement: ...
    def Faber_pol(
        self, m: int, order_1: SageElement | int = ..., fix_d: bool = ..., d_num_prec: int | None = ...
    ) -> Polynomial: ...
    def faber_pol(
        self, m: int, order_1: SageElement | int = ..., fix_d: bool = ..., d_num_prec: int | None = ...
    ) -> Polynomial: ...
    def F_basis_pol(self, m: int, order_1: SageElement | int = ...) -> SageElement: ...
    def F_basis(self, m: int, order_1: SageElement | int = ...) -> FormsElement: ...
    def quasi_part_gens(
        self,
        r: int | None = ...,
        min_exp: int = ...,
        max_exp: int = ...,
        order_1: SageElement | int = ...,
    ) -> tuple[FormsElement, ...]: ...
    def quasi_part_dimension(
        self,
        r: int | None = ...,
        min_exp: int = ...,
        max_exp: int = ...,
        order_1: SageElement | int = ...,
    ) -> int: ...
    def construct_form(
        self,
        laurent_series: LaurentSeries,
        order_1: SageElement | int = ...,
        check: bool = ...,
        rationalize: bool = ...,
    ) -> FormsElement: ...
    def required_laurent_prec(self, min_exp: int = ..., order_1: SageElement | int = ...) -> int: ...
    def construct_quasi_form(
        self,
        laurent_series: LaurentSeries,
        order_1: SageElement | int = ...,
        check: bool = ...,
        rationalize: bool = ...,
    ) -> FormsElement: ...
    def q_basis(
        self, m: int | None = ..., min_exp: int = ..., order_1: SageElement | int = ...
    ) -> tuple[FormsElement, ...]: ...
    def rationalize_series(
        self,
        laurent_series: LaurentSeries,
        coeff_bound: float = ...,
        denom_factor: SageElement | int = ...,
    ) -> LaurentSeries: ...
    def dimension(self) -> int | PlusInfinity: ...
    def rank(self) -> int | PlusInfinity: ...
    def degree(self) -> int | PlusInfinity: ...
    def coordinate_vector(self, v: FormsElement) -> Vector: ...
    def ambient_coordinate_vector(self, v: FormsElement) -> Vector: ...
    def gens(self) -> tuple[FormsElement, ...]: ...
    def gen(self, k: int = ...) -> FormsElement: ...
