# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FormsElement:
    def __init__(self, parent: builtins.object, rat: builtins.object) -> None: ...
    def coordinate_vector(self) -> _SageObject: ...
    def ambient_coordinate_vector(self) -> _SageObject: ...
    def lseries(self, num_prec: builtins.object = ..., max_imaginary_part: builtins.int = ..., max_asymp_coeffs: builtins.int = ...) -> _SageObject: ...
