# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def ConstantFormsSpaceFunctor(group: builtins.object) -> _SageObject: ...

class FormsSubSpaceFunctor:
    rank: _SageObject
    def __init__(self, ambient_space_functor: builtins.object, generators: builtins.object) -> None: ...
    def __call__(self, R: builtins.int) -> _SageObject: ...
    def merge(self, other: builtins.object) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...

class FormsSpaceFunctor:
    AT: _SageObject
    rank: _SageObject
    def __init__(self, analytic_type: builtins.object, group: builtins.object, k: builtins.int, ep: builtins.object) -> None: ...
    def __call__(self, R: builtins.int) -> _SageObject: ...
    def merge(self, other: builtins.object) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...

class FormsRingFunctor:
    AT: _SageObject
    rank: _SageObject
    def __init__(self, analytic_type: builtins.object, group: builtins.object, red_hom: builtins.object) -> None: ...
    def __call__(self, R: builtins.int) -> _SageObject: ...
    def merge(self, other: builtins.object) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...

class BaseFacade:
    def __init__(self, ring: builtins.object) -> None: ...
