# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MFSeriesConstructor:
    @staticmethod
    def __classcall__(cls: builtins.object, group: builtins.object = ..., prec: builtins.int = ...) -> _SageObject: ...
    def __init__(self, group: builtins.object, prec: builtins.int) -> None: ...
    def group(self) -> _SageObject: ...
    def hecke_n(self) -> _SageObject: ...
    def prec(self) -> _SageObject: ...
    def J_inv_ZZ(self) -> _SageObject: ...
    def f_rho_ZZ(self) -> _SageObject: ...
    def f_i_ZZ(self) -> _SageObject: ...
    def f_inf_ZZ(self) -> _SageObject: ...
    def G_inv_ZZ(self) -> _SageObject: ...
    def E4_ZZ(self) -> _SageObject: ...
    def E6_ZZ(self) -> _SageObject: ...
    def Delta_ZZ(self) -> _SageObject: ...
    def E2_ZZ(self) -> _SageObject: ...
    def EisensteinSeries_ZZ(self, k: builtins.int) -> _SageObject: ...
