# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CharacteristicCohomologyClassRingElement:
    def __init__(self, parent: builtins.object, x: builtins.object, name: builtins.str = ..., latex_name: builtins.str = ...) -> None: ...
    def get_form(self, nab: builtins.object) -> _SageObject: ...
    def representative(self, nab: builtins.object = ...) -> _SageObject: ...
    def set_name(self, name: builtins.str = ..., latex_name: builtins.str = ...) -> _SageObject: ...

class CharacteristicCohomologyClassRing:
    Element: _SageObject
    def __init__(self, base: builtins.object, vbundle: builtins.object) -> None: ...

def multiplicative_sequence(q: builtins.int, n: builtins.int = ...) -> _SageObject: ...

def additive_sequence(q: builtins.int, k: builtins.int, n: builtins.int = ...) -> _SageObject: ...

def fast_wedge_power(form: builtins.object, n: builtins.int) -> _SageObject: ...

class Algorithm_generic:
    def get(self, nab: builtins.object) -> _SageObject: ...
    def get_local(self, cmat: builtins.object) -> _SageObject: ...
    def get_gen_pow(self, nab: builtins.object, i: builtins.int, n: builtins.int) -> _SageObject: ...

class ChernAlgorithm:
    def get_local(self, cmat: builtins.object) -> _SageObject: ...

class PontryaginAlgorithm:
    def get_local(self, cmat: builtins.object) -> _SageObject: ...

class EulerAlgorithm:
    def get(self, nab: builtins.object) -> _SageObject: ...
    def get_local(self, cmat: builtins.object) -> _SageObject: ...

class PontryaginEulerAlgorithm:
    def get(self, nab: builtins.object) -> _SageObject: ...
    def get_local(self, cmat: builtins.object) -> _SageObject: ...
    def get_gen_pow(self, nab: builtins.object, i: builtins.int, n: builtins.int) -> _SageObject: ...
