# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DiffChart:
    def __init__(self, domain: builtins.object, coordinates: builtins.object, calc_method: builtins.object = ..., periods: builtins.object = ..., coord_restrictions: builtins.object = ...) -> None: ...
    def transition_map(self, other: builtins.object, transformations: builtins.object, intersection_name: builtins.str = ..., restrictions1: builtins.object = ..., restrictions2: builtins.object = ...) -> _SageObject: ...
    def frame(self) -> _SageObject: ...
    def coframe(self) -> _SageObject: ...
    def restrict(self, subset: builtins.object, restrictions: builtins.object = ...) -> _SageObject: ...
    def symbolic_velocities(self, left: builtins.str = ..., right: builtins.object = ...) -> _SageObject: ...

class RealDiffChart:
    def __init__(self, domain: builtins.object, coordinates: builtins.object, calc_method: builtins.object = ..., bounds: builtins.object = ..., periods: builtins.object = ..., coord_restrictions: builtins.object = ...) -> None: ...
    def restrict(self, subset: builtins.object, restrictions: builtins.object = ...) -> _SageObject: ...

class DiffCoordChange:
    def __init__(self, chart1: builtins.object, chart2: builtins.object, *transformations: builtins.object) -> None: ...
    def jacobian(self) -> _SageObject: ...
    def jacobian_det(self) -> _SageObject: ...
