# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DifferentiableCurve:
    def __init__(self, parent: builtins.object, coord_expression: builtins.object = ..., name: builtins.str = ..., latex_name: builtins.str = ..., is_isomorphism: builtins.bool = ..., is_identity: builtins.bool = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def coord_expr(self, chart: builtins.object = ...) -> _SageObject: ...
    def __call__(self, t: builtins.object, simplify: builtins.bool = ...) -> _SageObject: ...
    def tangent_vector_field(self, name: builtins.str = ..., latex_name: builtins.str = ...) -> _SageObject: ...
    def plot(self, chart: builtins.object = ..., ambient_coords: builtins.object = ..., mapping: builtins.object = ..., prange: builtins.object = ..., include_end_point: builtins.tuple[_SageObject, ...] = ..., end_point_offset: builtins.tuple[_SageObject, ...] = ..., parameters: builtins.object = ..., color: builtins.str = ..., style: builtins.str = ..., label_axes: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...
