# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MixedFormAlgebra:
    Element: _SageObject
    def __init__(self, vector_field_module: builtins.object) -> None: ...
    def zero(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def vector_field_module(self) -> _SageObject: ...
    def differential(self, degree: builtins.int = ...) -> _SageObject: ...
    def cohomology(self, *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    homology: _SageObject
    def irange(self, start: builtins.int = ...) -> _SageObject: ...
    def lift_from_homology(self, x: builtins.object) -> _SageObject: ...
