from collections.abc import Iterable, Sequence
from typing import Literal, Protocol, TypeAlias, overload

from sage.manifolds.manifold import TopologicalManifold
from sage.manifolds.scalarfield import ScalarField
from sage.rings.integer import Integer
from sage.structure.element import Element as SageElement
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.tensor.modules.reflexive_module import ReflexiveModule_abstract, ReflexiveModule_base

from sage.manifolds.differentiable.vectorfield import VectorField, VectorFieldParal

_Name: TypeAlias = str | None
_TensorType: TypeAlias = tuple[int, int]
_IndexBlock: TypeAlias = Iterable[int]
_Symmetry: TypeAlias = _IndexBlock | Iterable[_IndexBlock] | None
_Signature: TypeAlias = int | Integer | tuple[int | Integer, int | Integer] | tuple[int | Integer, int | Integer, int | Integer]

class _DiffMapLike(Protocol):
    _codomain: TopologicalManifold
    def restrict(self, subdomain: TopologicalManifold) -> _DiffMapLike: ...

class _AutomorphismField(Protocol):
    def set_immutable(self) -> None: ...

class _AutomorphismFieldGroup(Protocol):
    def element_class(self, module: VectorFieldModule, name: _Name = ..., latex_name: _Name = ...) -> _AutomorphismField: ...
    def one(self) -> _AutomorphismField: ...

class _TensorFieldModule(ReflexiveModule_abstract): ...
class _TensorField(Protocol): ...
class _DiffFormModule(ReflexiveModule_abstract): ...
class _DiffForm(Protocol): ...
class _MultivectorModule(ReflexiveModule_abstract): ...
class _MultivectorField(Protocol): ...
class _Metric(Protocol): ...
class _SymplecticForm(Protocol): ...
class _PoissonTensorField(Protocol): ...

class VectorFieldModule(UniqueRepresentation, ReflexiveModule_base):
    Element: type[VectorField]
    def __init__(self, domain: TopologicalManifold, dest_map: _DiffMapLike | None = None) -> None: ...
    def domain(self) -> TopologicalManifold: ...
    def ambient_domain(self) -> TopologicalManifold: ...
    def destination_map(self) -> _DiffMapLike: ...
    def tensor_module(
        self,
        k: int,
        l: int,
        *,
        sym: _Symmetry = ...,
        antisym: _Symmetry = ...,
    ) -> ReflexiveModule_abstract: ...
    def exterior_power(self, p: int) -> Parent | VectorFieldModule | _MultivectorModule: ...
    def dual_exterior_power(self, p: int) -> Parent | _DiffFormModule: ...
    def dual(self) -> _DiffFormModule: ...
    def general_linear_group(self) -> _AutomorphismFieldGroup: ...
    def tensor(self, *args: ReflexiveModule_abstract, **kwds: str | _Symmetry) -> ReflexiveModule_abstract: ...
    def alternating_contravariant_tensor(
        self, degree: int, name: _Name = ..., latex_name: _Name = ...
    ) -> ScalarField | VectorField | _MultivectorField: ...
    @overload
    def alternating_form(self, degree: Literal[0], name: _Name = ..., latex_name: _Name = ...) -> ScalarField: ...
    @overload
    def alternating_form(self, degree: int, name: _Name = ..., latex_name: _Name = ...) -> _DiffForm: ...
    def linear_form(self, name: _Name = ..., latex_name: _Name = ...) -> _DiffForm: ...
    def automorphism(self, name: _Name = ..., latex_name: _Name = ...) -> _AutomorphismField: ...
    def identity_map(self) -> _AutomorphismField: ...
    def zero(self) -> VectorField: ...
    def metric(self, name: str, signature: _Signature | None = ..., latex_name: _Name = ...) -> _Metric: ...
    def symplectic_form(self, name: _Name = ..., latex_name: _Name = ...) -> _SymplecticForm: ...
    def poisson_tensor(self, name: _Name = ..., latex_name: _Name = ...) -> _PoissonTensorField: ...

class _FreeModuleBasis(Protocol): ...

class VectorFieldFreeModule(VectorFieldModule):
    Element: type[VectorFieldParal]
    def __init__(self, domain: TopologicalManifold, dest_map: _DiffMapLike | None = None) -> None: ...
    def domain(self) -> TopologicalManifold: ...
    def ambient_domain(self) -> TopologicalManifold: ...
    def destination_map(self) -> _DiffMapLike: ...
    def tensor_module(
        self,
        k: int,
        l: int,
        *,
        sym: _Symmetry = ...,
        antisym: _Symmetry = ...,
    ) -> ReflexiveModule_abstract: ...
    def exterior_power(self, p: int) -> Parent | VectorFieldFreeModule | _MultivectorModule: ...
    def dual_exterior_power(self, p: int) -> Parent | _DiffFormModule: ...
    def general_linear_group(self) -> _AutomorphismFieldGroup: ...
    def basis(
        self,
        symbol: str | Sequence[str],
        latex_symbol: str | Sequence[str] | None = ...,
        from_frame: Parent | None = ...,
        dest_map: _DiffMapLike | None = ...,
    ) -> _FreeModuleBasis: ...
    def tensor_from_comp(
        self,
        tensor_type: _TensorType,
        comp: SageElement,
        name: _Name = ...,
        latex_name: _Name = ...,
    ) -> VectorFieldParal | _TensorField | _DiffForm: ...
    def sym_bilinear_form(self, name: _Name = ..., latex_name: _Name = ...) -> _TensorField: ...
    def metric(self, name: str, signature: _Signature | None = ..., latex_name: _Name = ...) -> _Metric: ...
    def symplectic_form(self, name: _Name = ..., latex_name: _Name = ...) -> _SymplecticForm: ...
    def poisson_tensor(self, name: _Name = ..., latex_name: _Name = ...) -> _PoissonTensorField: ...
