import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class PRESENT:
    keySchedule: builtins.int

    def __init__(
        self,
        keySchedule: builtins.int = ...,
        rounds: builtins.object = ...,
        doFinalRound: builtins.bool = ...,
    ) -> None: ...
    def __call__(
        self,
        block: builtins.object,
        key: builtins.object,
        algorithm: builtins.str = ...,
    ) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def encrypt(
        self, plaintext: builtins.object, key: builtins.object
    ) -> _SageObject: ...
    def decrypt(
        self, ciphertext: builtins.object, key: builtins.object
    ) -> _SageObject: ...
    def round(
        self,
        state: builtins.object,
        round_counter: builtins.object,
        round_key: builtins.object,
        inverse: builtins.bool = ...,
    ) -> _SageObject: ...
    def sbox_layer(
        self, state: builtins.object, inverse: builtins.bool = ...
    ) -> _SageObject: ...
    def linear_layer(
        self, state: builtins.object, inverse: builtins.bool = ...
    ) -> _SageObject: ...

class PRESENT_KS:
    def __init__(
        self,
        keysize: builtins.int = ...,
        rounds: builtins.int = ...,
        master_key: builtins.object = ...,
    ) -> None: ...
    def __call__(self, K: builtins.int) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, r: builtins.int) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

def convert_to_vector(self, L: builtins.object) -> _SageObject: ...
