from sage.structure.element import Element

def width_of_cut_decomposition(G: Element | int | str | bool | None, L: Element | int | str | bool | None) -> Element: ...
def cutwidth_dyn(G: Element | int | str | bool | None, lower_bound: Element | int | str | bool | None) -> Element: ...
