# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FastDigraph:
    def __cinit__(self, D: builtins.object, vertex_list: builtins.object = ...) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def print_adjacency_matrix(self) -> _SageObject: ...

def compute_out_neighborhood_cardinality(g: builtins.object, S: builtins.object) -> _SageObject: ...

def popcount32(i: builtins.object) -> _SageObject: ...

def test_popcount() -> _SageObject: ...

def slow_popcount32(i: builtins.object) -> _SageObject: ...
