from sage.structure.element import Element

def is_cartesian_product(g: Element, certificate: Element | int | str | bool | None, relabeling: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> bool: ...
def r(x: Element, y: Element) -> Element: ...
def rooted_product(G: Element | int | str | bool | None, H: Element | int | str | bool | None, root: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def edges() -> Element: ...
