from sage.structure.element import Element

def rank_decomposition(G: Element | int | str | bool | None, verbose: bool, immutable: Element | int | str | bool | None) -> int: ...
def mkgraph(num_vertices: Element | int | str | bool | None) -> Element: ...
