from sage.structure.element import Element
from sage.structure.sage_object import SageObject

def slice_decomposition(G: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...

class SliceDecomposition(SageObject):
    def lexBFS_order(self) -> Element: ...
    def xslice_data(self, v: Element) -> Element: ...
    def slice(self, v: Element) -> Element: ...
    def xslice_sequence(self, v: Element) -> Element: ...
    def lexicographic_label(self, v: Element) -> Element: ...
    def active_edges(self, v: Element) -> Element: ...
    def _slice(self, idx: Element | int | str | bool | None) -> Element: ...
    def _xslice_sequence(self, idx: Element | int | str | bool | None) -> Element: ...
    def _xslice_lex_label(self, idx: Element | int | str | bool | None) -> Element: ...
    def _xslice_active_edges(self, idx: Element | int | str | bool | None) -> Element: ...
    def underlying_graph(self) -> Element: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
