# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def make_tdlib_graph(G: builtins.object, vertex_to_int: builtins.object, V: builtins.object, E: builtins.object) -> _SageObject: ...

def make_sage_decomp(G: builtins.object, V: builtins.object, E: builtins.object, int_to_vertex: builtins.object) -> _SageObject: ...

def treedecomposition_exact(G: builtins.object, lb: builtins.object = ...) -> _SageObject: ...

def get_width(T: builtins.object) -> _SageObject: ...
