from sage.structure.element import Element

def treedecomposition_exact(G: Element | int | str | bool | None, lb: Element | int | str | bool | None) -> Element: ...
def get_width(T: Element | int | str | bool | None) -> Element: ...
