from sage.modules.free_module import FreeModule_generic
from sage.structure.parent import Parent
from sage.structure.sequence import Sequence_generic

class ModularAbelianVariety_abstract(Parent):
    def __init__(
        self,
        groups: object,
        base_field: object,
        is_simple: bool | None = None,
        newform_level: int | None = None,
        isogeny_number: int | None = None,
        number: int | None = None,
        check: bool = True,
    ) -> None: ...
    def groups(self) -> tuple[object, ...]: ...
    def is_J0(self) -> bool: ...
    def is_J1(self) -> bool: ...
    def lattice(self) -> FreeModule_generic: ...
    def free_module(self) -> FreeModule_generic: ...
    def vector_space(self) -> Parent: ...
    def base_field(self) -> Parent: ...
    def base_extend(self, K: object) -> ModularAbelianVariety_abstract: ...
    def __contains__(self, x: object) -> bool: ...
    def label(self) -> str: ...
    def newform(self, names: str | None = None) -> Parent: ...
    def newform_decomposition(self, names: str | None = None) -> Sequence_generic: ...
    def newform_label(self) -> str: ...
    def elliptic_curve(self) -> Parent: ...
    def modular_kernel(self) -> Parent: ...
    def modular_degree(self) -> int: ...
    def intersection(self, other: ModularAbelianVariety_abstract) -> ModularAbelianVariety_abstract: ...
    def direct_product(self, other: ModularAbelianVariety_abstract) -> ModularAbelianVariety_abstract: ...
    def quotient(
        self,
        other: ModularAbelianVariety_abstract,
        **kwds: object,
    ) -> ModularAbelianVariety_abstract: ...
    def degeneracy_map(self, M_ls: list[object], t_ls: list[int]) -> Parent: ...
    def projection(
        self,
        A: ModularAbelianVariety_abstract,
        check: bool = True,
    ) -> Parent: ...
    def project_to_factor(self, n: int) -> ModularAbelianVariety_abstract: ...
    def is_subvariety_of_ambient_jacobian(self) -> bool: ...
    def ambient_variety(self) -> ModularAbelianVariety_abstract: ...
    def ambient_morphism(self) -> Parent: ...
    def is_ambient(self) -> bool: ...
    def dimension(self) -> int: ...
    def conductor(self) -> int: ...
    def rank(self) -> int: ...
    def degree(self) -> int: ...
    def endomorphism_ring(self, category: object | None = None) -> Parent: ...
    def sturm_bound(self) -> int: ...
    def is_hecke_stable(self) -> bool: ...
    def is_subvariety(self, other: ModularAbelianVariety_abstract) -> bool: ...
    def change_ring(self, R: object) -> ModularAbelianVariety_abstract: ...
    def level(self) -> int: ...
