# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def ModAbVar_ambient_jacobian(group: builtins.object) -> _SageObject: ...

class ModAbVar_ambient_jacobian_class:
    def __init__(self, group: builtins.object) -> None: ...
    def ambient_variety(self) -> _SageObject: ...
    def group(self) -> _SageObject: ...
    def groups(self) -> builtins.tuple[_SageObject, ...]: ...
    def degeneracy_map(self, level: builtins.object, t: builtins.int = ..., check: builtins.bool = ...) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def decomposition(self, simple: builtins.bool = ..., bound: builtins.object = ...) -> builtins.list[_SageObject]: ...
    def newform_decomposition(self, names: builtins.object = ...) -> builtins.list[_SageObject]: ...
