import builtins

class _SageObject: ...

def J0(self) -> _SageObject: ...
def J1(self) -> _SageObject: ...
def JH(self, H: builtins.object) -> _SageObject: ...
def AbelianVariety(self) -> _SageObject: ...
