import builtins

class _SageObject: ...
class CuspidalSubgroup_generic: ...

class CuspidalSubgroup:
    def lattice(self) -> _SageObject: ...

class RationalCuspSubgroup:
    def lattice(self) -> _SageObject: ...

class RationalCuspidalSubgroup:
    def lattice(self) -> _SageObject: ...

def is_rational_cusp_gamma0(self, N: builtins.int, data: builtins.object) -> bool: ...
