# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Homology:
    def hecke_polynomial(self, n: builtins.int, var: builtins.str = ...) -> _SageObject: ...

class Homology_abvar:
    def __init__(self, abvar: builtins.object, base: builtins.object) -> None: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def gen(self, n: builtins.int) -> _SageObject: ...
    def abelian_variety(self) -> _SageObject: ...
    def ambient_hecke_module(self) -> _SageObject: ...
    def free_module(self) -> _SageObject: ...
    def hecke_bound(self) -> _SageObject: ...
    def hecke_matrix(self, n: builtins.int) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def submodule(self, U: builtins.object, check: builtins.bool = ...) -> _SageObject: ...

class IntegralHomology:
    def __init__(self, abvar: builtins.object) -> None: ...
    def hecke_matrix(self, n: builtins.int) -> _SageObject: ...
    def hecke_polynomial(self, n: builtins.int, var: builtins.str = ...) -> _SageObject: ...

class RationalHomology:
    def __init__(self, abvar: builtins.object) -> None: ...
    def hecke_matrix(self, n: builtins.int) -> _SageObject: ...
    def hecke_polynomial(self, n: builtins.int, var: builtins.str = ...) -> _SageObject: ...

class Homology_over_base:
    def __init__(self, abvar: builtins.object, base_ring: builtins.object) -> None: ...
    def hecke_matrix(self, n: builtins.int) -> _SageObject: ...

class Homology_submodule:
    def __init__(self, ambient: builtins.object, submodule: builtins.object) -> None: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def ambient_hecke_module(self) -> _SageObject: ...
    def free_module(self) -> _SageObject: ...
    def hecke_bound(self) -> _SageObject: ...
    def hecke_matrix(self, n: builtins.int) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
