# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class RationalTorsionSubgroup:
    def __init__(self, abvar: builtins.object) -> None: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def order(self, proof: builtins.bool = ...) -> _SageObject: ...
    def lattice(self) -> _SageObject: ...
    def possible_orders(self, proof: builtins.bool = ...) -> _SageObject: ...
    def divisor_of_order(self) -> _SageObject: ...
    def multiple_of_order(self, maxp: builtins.object = ..., proof: builtins.bool = ...) -> _SageObject: ...
    def multiple_of_order_using_frobp(self, maxp: builtins.object = ...) -> _SageObject: ...

class QQbarTorsionSubgroup:
    Element: _SageObject
    def __init__(self, abvar: builtins.object) -> None: ...
    def field_of_definition(self) -> _SageObject: ...
    def abelian_variety(self) -> _SageObject: ...
