# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class TorsionPoint:
    def __init__(self, parent: builtins.object, element: builtins.object, check: builtins.bool = ...) -> None: ...
    def element(self) -> _SageObject: ...
    def additive_order(self) -> _SageObject: ...
