from sage.rings.ring import Field, Ring

class NumberField_quadratic(Field): ...
class NumberField_cyclotomic(Field): ...
class UniversalCyclotomicField(Field): ...
class AlgebraicField_common(Field): ...
class AlgebraicField(AlgebraicField_common): ...
class AlgebraicRealField(AlgebraicField_common): ...
class RealField(Field): ...
class RealBallField(Field): ...
class RealIntervalField(Field): ...
class RealDoubleField(Field): ...
class ComplexField(Field): ...
class ComplexBallField(Field): ...
class ComplexIntervalField(Field): ...
class ComplexDoubleField(Field): ...
class IntegerModRing: ...
class Order: ...
class pAdicRing(Ring): ...
class pAdicField(Field): ...
