from .ring import CommutativeRing as CommutativeRing, Field as Field
from .integer import Integer
from .real_double import RealDoubleField_class
from .real_mpfr import RealField_class
from .real_mpfi import RealIntervalField as RealIntervalField_class

__all__ = (
    "AlgebraicField",
    "AlgebraicField_common",
    "AlgebraicRealField",
    "CommutativeRing",
    "ComplexBallField",
    "ComplexDoubleField",
    "ComplexField",
    "ComplexIntervalField",
    "Field",
    "IntegerModRing",
    "NumberField_cyclotomic",
    "NumberField_quadratic",
    "Order",
    "RealBallField",
    "RealDoubleField",
    "RealField",
    "RealIntervalField",
    "UniversalCyclotomicField",
    "pAdicField",
    "pAdicRing",
)

class RealField(Field):
    def to_prec(self, prec: int | Integer) -> RealField_class: ...
class NumberField_quadratic(Field): ...
class NumberField_cyclotomic(Field): ...
class UniversalCyclotomicField(Field): ...
class AlgebraicField_common(Field): ...
class AlgebraicField(AlgebraicField_common): ...
class AlgebraicRealField(AlgebraicField_common): ...
class RealBallField(Field): ...
class RealIntervalField(Field):
    def to_prec(self, prec: int | Integer) -> RealIntervalField_class: ...
class RealDoubleField(Field):
    def to_prec(self, prec: int | Integer) -> RealDoubleField_class | RealField_class: ...
class ComplexField(Field): ...
class ComplexBallField(Field): ...
class ComplexIntervalField(Field): ...
class ComplexDoubleField(Field): ...
class IntegerModRing: ...
class pAdicRing(CommutativeRing): ...
class pAdicField(Field): ...
class Order: ...
