# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AlgebraicClosureFiniteFieldElement:
    def __init__(self, parent: builtins.object, value: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __pow__(self, exp: builtins.object) -> Self: ...
    def change_level(self, n: builtins.int) -> _SageObject: ...
    def minpoly(self) -> _SageObject: ...
    minimal_polynomial: _SageObject
    def is_square(self) -> builtins.bool: ...
    def sqrt(self, all: builtins.bool = ...) -> _SageObject: ...
    def nth_root(self, n: builtins.int) -> _SageObject: ...
    def multiplicative_order(self) -> _SageObject: ...
    def pth_power(self, k: builtins.int = ...) -> _SageObject: ...
    def pth_root(self, k: builtins.int = ...) -> _SageObject: ...
    def as_finite_field_element(self, minimal: builtins.bool = ...) -> _SageObject: ...

class AlgebraicClosureFiniteField_generic:
    def __init__(self, base_ring: builtins.object, name: builtins.str, category: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def characteristic(self) -> _SageObject: ...
    Element: _SageObject
    def subfield(self, n: builtins.int) -> _SageObject: ...
    def inclusion(self, m: builtins.int, n: builtins.int) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def gen(self, n: builtins.int) -> _SageObject: ...
    def gens(self) -> _SageObject: ...
    def algebraic_closure(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...

class AlgebraicClosureFiniteField_pseudo_conway:
    def __init__(self, base_ring: builtins.object, name: builtins.str, category: builtins.object = ..., lattice: builtins.object = ..., use_database: builtins.bool = ...) -> None: ...

def AlgebraicClosureFiniteField(base_ring: builtins.object, name: builtins.str, category: builtins.object = ..., implementation: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...
