from collections.abc import Sequence
from typing import overload

from sage.categories.category import Category
from sage.rings.fraction_field import FractionField_generic
from sage.rings.fraction_field_element import FractionFieldElement
from sage.rings.laurent_series_ring_element import LaurentSeries
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.polynomial.polynomial_ring import PolynomialRing_generic
from sage.rings.ring import CommutativeRing
from sage.structure.element import FieldElement, RingElement
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.unique_representation import UniqueRepresentation
from sage.symbolic.expression import Expression

def CFiniteSequences(
    base_ring: CommutativeRing | PolynomialRing_generic,
    names: str | tuple[str, ...] | None = ...,
    category: Category | None = ...,
) -> CFiniteSequences_generic: ...

class CFiniteSequence(FieldElement):
    @staticmethod
    def __classcall_private__(
        class_: type[CFiniteSequence],
        ogf: ElementConstructorInput,
    ) -> CFiniteSequence: ...
    def __init__(
        self,
        parent: CFiniteSequences_generic,
        ogf: FractionFieldElement,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def __hash__(self) -> int: ...
    def _add_(self, other: CFiniteSequence) -> CFiniteSequence: ...
    def _sub_(self, other: CFiniteSequence) -> CFiniteSequence: ...
    def _mul_(self, other: CFiniteSequence) -> CFiniteSequence: ...
    def _div_(self, other: CFiniteSequence) -> CFiniteSequence: ...
    def coefficients(self) -> list[RingElement]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @overload
    def __getitem__(self, key: int) -> RingElement: ...
    @overload
    def __getitem__(self, key: slice) -> list[RingElement]: ...
    def ogf(self) -> FractionFieldElement: ...
    def numerator(self) -> Polynomial: ...
    def denominator(self) -> Polynomial: ...
    def recurrence_repr(self) -> str: ...
    def series(self, n: int) -> LaurentSeries: ...
    def closed_form(self, n: str = ...) -> Expression: ...

class CFiniteSequences_generic(
    Parent[CFiniteSequence],
    UniqueRepresentation,
):
    Element: type[CFiniteSequence]
    def __init__(
        self,
        polynomial_ring: PolynomialRing_generic,
        category: Category,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(
        self,
        ogf: ElementConstructorInput,
    ) -> CFiniteSequence: ...
    def ngens(self) -> int: ...
    def gen(self, i: int = ...) -> CFiniteSequence: ...
    def gens(self) -> tuple[CFiniteSequence]: ...
    def an_element(self) -> CFiniteSequence: ...
    def __contains__(self, x: object) -> bool: ...
    def fraction_field(self) -> FractionField_generic: ...
    def polynomial_ring(self) -> PolynomialRing_generic: ...
    def _coerce_map_from_(self, S: Parent) -> bool: ...
    def from_recurrence(
        self,
        coefficients: Sequence[RingElement],
        values: Sequence[RingElement],
    ) -> CFiniteSequence: ...
    def guess(
        self,
        sequence: Sequence[RingElement],
        algorithm: str = ...,
    ) -> CFiniteSequence: ...
