from sage.plot.plot import GraphicObject
from __future__ import annotations
from builtins import str as String
from sage.rings.integer import Integer
from sage.rings.real_mpfr import RealField_class, RealNumber
from sage.rings.abc import ComplexField
from sage.structure.element import Element
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.qqbar import AlgebraicField

class ComplexField_class(ComplexField):
    def __init__(self, prec: int = ...) -> None: ...
    def is_exact(self) -> bool: ...
    def prec(self) -> Integer: ...
    def to_prec(self, prec: int) -> ComplexField_class: ...
    def __eq__(self, other: object) -> bool: ...
    def __call__(self, x: object = ..., im: object = ...) -> ComplexNumber: ...
    def characteristic(self) -> Integer: ...
    def gen(self, n: int = ...) -> ComplexNumber: ...
    def construction(self) -> tuple[object, object]: ...
    def random_element(self, *args: object, **kwds: object) -> ComplexNumber: ...
    def pi(self) -> ComplexNumber: ...
    def ngens(self) -> int: ...
    def zeta(self, n: int = ...) -> ComplexNumber: ...
    def scientific_notation(self, status: bool | None = ...) -> bool: ...
    def algebraic_closure(self) -> AlgebraicField: ...

class ComplexNumber(Element):
    def __init__(self, parent: ComplexField_class, x: object = ..., y: object = ...) -> None: ...
    def str(self, **kwds: object) -> String: ...
    def norm(self) -> RealNumber: ...
    def prec(self) -> Integer: ...
    def real(self) -> RealNumber: ...
    def imag(self) -> RealNumber: ...
    def multiplicative_order(self) -> Integer: ...
    def plot(self, **kwds: object) -> GraphicObject: ...
    def arccos(self) -> ComplexNumber: ...
    def arccosh(self) -> ComplexNumber: ...
    def arcsin(self) -> ComplexNumber: ...
    def arcsinh(self) -> ComplexNumber: ...
    def arctan(self) -> ComplexNumber: ...
    def arctanh(self) -> ComplexNumber: ...
    def coth(self) -> ComplexNumber: ...
    def arccoth(self) -> ComplexNumber: ...
    def csc(self) -> ComplexNumber: ...
    def csch(self) -> ComplexNumber: ...
    def arccsch(self) -> ComplexNumber: ...
    def sec(self) -> ComplexNumber: ...
    def sech(self) -> ComplexNumber: ...
    def arcsech(self) -> ComplexNumber: ...
    def cot(self) -> ComplexNumber: ...
    def cos(self) -> ComplexNumber: ...
    def cosh(self) -> ComplexNumber: ...
    def eta(self) -> ComplexNumber: ...
    def sin(self) -> ComplexNumber: ...
    def sinh(self) -> ComplexNumber: ...
    def tan(self) -> ComplexNumber: ...
    def tanh(self) -> ComplexNumber: ...
    def agm(self, right: ComplexNumber) -> ComplexNumber: ...
    def argument(self) -> RealNumber: ...
    def arg(self) -> RealNumber: ...
    def conjugate(self) -> ComplexNumber: ...
    def dilog(self) -> ComplexNumber: ...
    def exp(self) -> ComplexNumber: ...
    def gamma(self) -> ComplexNumber: ...
    def gamma_inc(self, t: ComplexNumber) -> ComplexNumber: ...
    def log(self, base: object = ...) -> ComplexNumber: ...
    def additive_order(self) -> Integer: ...
    def sqrt(self, extend: bool = ..., all: bool = ...) -> ComplexNumber: ...
    def nth_root(self, n: int, extend: bool = ..., all: bool = ...) -> ComplexNumber: ...
    def is_square(self) -> bool: ...
    def is_real(self) -> bool: ...
    def is_imaginary(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def is_positive_infinity(self) -> bool: ...
    def is_negative_infinity(self) -> bool: ...
    def is_infinity(self) -> bool: ...
    def is_NaN(self) -> bool: ...
    def zeta(self) -> ComplexNumber: ...
    def algebraic_dependency(self, n: int, **kwds: object) -> Polynomial: ...
