from typing import Literal, Self, overload
from sage.rings.ring import Field
from sage.rings.real_mpfr import RealField_class, RealNumber
from sage.rings.integer import Integer
from sage.structure.element import FieldElement
from sage.categories.map import Map
from sage.libs.pari.gen import gen
from sage.rings.polynomial.polynomial_element import Polynomial

_str = str

class gmpy2:
    class mpc: ...

def late_import() -> None: ...
def split_complex_string(string: _str, base: int = ...) -> tuple[_str | None, _str | None]: ...
def MPComplexField(prec: int = ..., rnd: _str = ..., names: object = ...) -> MPComplexField_class: ...
def __create__MPComplexField_version0(prec: int, rnd: _str) -> MPComplexField_class: ...
def __create__MPComplexNumber_version0(parent: MPComplexField_class, s: object, base: int = ...) -> MPComplexNumber: ...

class MPComplexField_class(Field):
    _prec: int
    def __init__(self, prec: int = ..., rnd: _str = ...) -> None: ...
    def _repr_(self) -> _str: ...
    def _latex_(self) -> _str: ...
    def __call__(self, x: object = ..., im: object = ..., *args: object, **kwds: object) -> MPComplexNumber: ...
    def _element_constructor_(self, z: object) -> MPComplexNumber: ...
    def _coerce_map_from_(self, S: object) -> Map | bool | None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def __richcmp__(left: object, right: object, op: int) -> bool: ...
    def gen(self, n: int = ...) -> MPComplexNumber: ...
    def ngens(self) -> int: ...
    def _an_element_(self) -> MPComplexNumber: ...
    def random_element(self, min: object = ..., max: object = ...) -> MPComplexNumber: ...
    def is_exact(self) -> Literal[False]: ...
    def characteristic(self) -> Integer: ...
    def name(self) -> _str: ...
    def __hash__(self) -> int: ...
    def prec(self) -> int: ...
    def rounding_mode(self) -> _str: ...
    def rounding_mode_real(self) -> _str: ...
    def rounding_mode_imag(self) -> _str: ...
    def _real_field(self) -> RealField_class: ...
    def _imag_field(self) -> RealField_class: ...

class MPComplexNumber(FieldElement):
    def __init__(self, parent: MPComplexField_class, x: object, y: object = ..., base: int = ...) -> None: ...
    def _set(self, z: object, y: object = ..., base: int = ...) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def _repr_(self) -> _str: ...
    def _latex_(self) -> _str: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, i: int) -> RealNumber: ...
    def prec(self) -> int: ...
    def real(self) -> RealNumber: ...
    def imag(self) -> RealNumber: ...
    def str(self, base: int = ..., **kwds: object) -> _str: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: object) -> Self: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __pari__(self) -> gen: ...
    def __mpc__(self) -> gmpy2.mpc: ...
    def _richcmp_(self, other: object, op: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_square(self) -> bool: ...
    def is_real(self) -> bool: ...
    def is_imaginary(self) -> bool: ...
    def algebraic_dependency(self, n: int, **kwds: object) -> Polynomial: ...
    def _add_(self, right: object) -> MPComplexNumber: ...
    def _sub_(self, right: object) -> MPComplexNumber: ...
    def _mul_(self, right: object) -> MPComplexNumber: ...
    def _div_(self, right: object) -> MPComplexNumber: ...
    def _neg_(self) -> MPComplexNumber: ...
    def __invert__(self) -> MPComplexNumber: ...
    def __neg__(self) -> MPComplexNumber: ...
    def __abs__(self) -> RealNumber: ...
    def norm(self) -> RealNumber: ...
    def __pow__(self, right: object, modulus: object) -> MPComplexNumber: ...
    def cos(self) -> MPComplexNumber: ...
    def sin(self) -> MPComplexNumber: ...
    def tan(self) -> MPComplexNumber: ...
    def cosh(self) -> MPComplexNumber: ...
    def sinh(self) -> MPComplexNumber: ...
    def tanh(self) -> MPComplexNumber: ...
    def arccos(self) -> MPComplexNumber: ...
    def arcsin(self) -> MPComplexNumber: ...
    def arctan(self) -> MPComplexNumber: ...
    def arccosh(self) -> MPComplexNumber: ...
    def arcsinh(self) -> MPComplexNumber: ...
    def arctanh(self) -> MPComplexNumber: ...
    def coth(self) -> MPComplexNumber: ...
    def arccoth(self) -> MPComplexNumber: ...
    def csc(self) -> MPComplexNumber: ...
    def csch(self) -> MPComplexNumber: ...
    def arccsch(self) -> MPComplexNumber: ...
    def sec(self) -> MPComplexNumber: ...
    def sech(self) -> MPComplexNumber: ...
    def arcsech(self) -> MPComplexNumber: ...
    def cot(self) -> MPComplexNumber: ...
    def argument(self) -> RealNumber: ...
    def conjugate(self) -> MPComplexNumber: ...
    def sqr(self) -> MPComplexNumber: ...
    def sqrt(self) -> MPComplexNumber: ...
    def exp(self) -> MPComplexNumber: ...
    def log(self) -> MPComplexNumber: ...
    def __lshift__(self, n: int) -> MPComplexNumber: ...
    def __rshift__(self, n: int) -> MPComplexNumber: ...
    @overload
    def nth_root(self, n: int, all: Literal[False] = ...) -> MPComplexNumber: ...
    @overload
    def nth_root(self, n: int, all: Literal[True]) -> list[MPComplexNumber]: ...
    @overload
    def nth_root(self, n: int, all: bool) -> MPComplexNumber | list[MPComplexNumber]: ...
    def dilog(self) -> MPComplexNumber: ...
    def eta(self, omit_frac: bool = ...) -> MPComplexNumber: ...
    def gamma(self) -> MPComplexNumber: ...
    def gamma_inc(self, t: object) -> MPComplexNumber: ...
    def zeta(self) -> MPComplexNumber: ...
    def agm(self, right: object, algorithm: _str = ...) -> MPComplexNumber: ...
