from typing import TYPE_CHECKING, Any

from sage.rings.integer import Integer
from sage.rings.real_double import RealDoubleElement
from sage.structure.parent import Parent

class ComplexDoubleField_class(Parent):
    def __init__(self) -> None: ...
    def __reduce__(self) -> tuple[type[ComplexDoubleField_class], None]: ...
    def is_exact(self) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def __hash__(self) -> int: ...
    def characteristic(self) -> Integer: ...
    def random_element(self, xmin: float = -1, xmax: float = 1, ymin: float = -1, ymax: float = 1) -> ComplexDoubleElement: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __call__(self, x: Any = None, im: Any = None) -> ComplexDoubleElement: ...
    def _element_constructor_(self, x: Any) -> ComplexDoubleElement: ...
    def _coerce_map_from_(self, S: Parent) -> Any | None: ...
    def _magma_init_(self, magma: Any) -> str: ...
    def _fricas_init_(self) -> str: ...
    def prec(self) -> int: ...
    def precision(self) -> int: ...
    def to_prec(self, prec: int) -> ComplexDoubleField_class: ...
    def gen(self, n: int = 0) -> ComplexDoubleElement: ...
    def ngens(self) -> int: ...
    def algebraic_closure(self) -> ComplexDoubleField_class: ...
    def real_double_field(self) -> Any: ...
    def pi(self) -> ComplexDoubleElement: ...
    def construction(self) -> tuple[Any, tuple[()]]: ...
    def zeta(self, n: int = 2) -> ComplexDoubleElement: ...
    def _factor_univariate_polynomial(self, f: Any) -> Any: ...

class ComplexDoubleElement:
    def __init__(self, real: Any, imag: Any) -> None: ...
    def __reduce__(self) -> tuple[type[ComplexDoubleElement], None]: ...
    def __hash__(self) -> int: ...
    def _richcmp_(self, right: object, op: int) -> bool: ...
    def __getitem__(self, n: int) -> RealDoubleElement: ...
    def _magma_init_(self, magma: Any) -> str: ...
    def prec(self) -> int: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def _interface_init_(self, I: Any = None) -> str: ...
    def _mathematica_init__(self) -> Any: ...
    def _maxima_init_(self, I: Any = None) -> str: ...
    def _sympy_(self) -> Any: ...
    def _repr_(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def _latex_(self) -> str: ...
    def __pari__(self) -> Any: ...
    def __mpc__(self) -> Any: ...
    def _add_(self, right: ComplexDoubleElement) -> ComplexDoubleElement: ...
    def _sub_(self, right: ComplexDoubleElement) -> ComplexDoubleElement: ...
    def _mul_(self, right: ComplexDoubleElement) -> ComplexDoubleElement: ...
    def _div_(self, right: ComplexDoubleElement) -> ComplexDoubleElement: ...
    def __invert__(self) -> ComplexDoubleElement: ...
    def _neg_(self) -> ComplexDoubleElement: ...
    def conjugate(self) -> ComplexDoubleElement: ...
    def conj(self) -> ComplexDoubleElement: ...
    def arg(self) -> RealDoubleElement: ...
    def __abs__(self) -> RealDoubleElement: ...
    def abs(self) -> RealDoubleElement: ...
    def argument(self) -> RealDoubleElement: ...
    def abs2(self) -> RealDoubleElement: ...
    def norm(self) -> RealDoubleElement: ...
    def logabs(self) -> RealDoubleElement: ...
    def real(self) -> RealDoubleElement: ...
    def real_part(self) -> RealDoubleElement: ...
    def imag(self) -> RealDoubleElement: ...
    def imag_part(self) -> RealDoubleElement: ...
    def sqrt(self, all: bool = False) -> ComplexDoubleElement: ...
    def nth_root(self, n: int, all: bool = False) -> ComplexDoubleElement: ...
    def is_square(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def is_positive_infinity(self) -> bool: ...
    def is_negative_infinity(self) -> bool: ...
    def is_infinity(self) -> bool: ...
    def is_NaN(self) -> bool: ...
    def _pow_(self, other: Any) -> ComplexDoubleElement: ...
    def exp(self) -> ComplexDoubleElement: ...
    def log(self, base: Any = None) -> ComplexDoubleElement: ...
    def log10(self) -> ComplexDoubleElement: ...
    def log_b(self, b: Any) -> ComplexDoubleElement: ...
    def sin(self) -> ComplexDoubleElement: ...
    def cos(self) -> ComplexDoubleElement: ...
    def tan(self) -> ComplexDoubleElement: ...
    def sec(self) -> ComplexDoubleElement: ...
    def csc(self) -> ComplexDoubleElement: ...
    def cot(self) -> ComplexDoubleElement: ...
    def arcsin(self) -> ComplexDoubleElement: ...
    def arccos(self) -> ComplexDoubleElement: ...
    def arctan(self) -> ComplexDoubleElement: ...
    def arccsc(self) -> ComplexDoubleElement: ...
    def arccot(self) -> ComplexDoubleElement: ...
    def arcsec(self) -> ComplexDoubleElement: ...
    def sinh(self) -> ComplexDoubleElement: ...
    def cosh(self) -> ComplexDoubleElement: ...
    def tanh(self) -> ComplexDoubleElement: ...
    def sech(self) -> ComplexDoubleElement: ...
    def csch(self) -> ComplexDoubleElement: ...
    def coth(self) -> ComplexDoubleElement: ...
    def arcsinh(self) -> ComplexDoubleElement: ...
    def arccosh(self) -> ComplexDoubleElement: ...
    def arctanh(self) -> ComplexDoubleElement: ...
    def arcsech(self) -> ComplexDoubleElement: ...
    def arccsch(self) -> ComplexDoubleElement: ...
    def arccoth(self) -> ComplexDoubleElement: ...
    def eta(self, omit_frac: int = 0) -> ComplexDoubleElement: ...

class FloatToCDF:
    def __init__(self, R: Parent) -> None: ...
    def _call_(self, x: Any) -> ComplexDoubleElement: ...
    def _repr_type(self) -> str: ...

class ComplexToCDF:
    def __init__(self, S: Parent) -> None: ...
    def _call_(self, x: Any) -> ComplexDoubleElement: ...
    def _repr_type(self) -> str: ...

def ComplexDoubleField() -> ComplexDoubleField_class: ...
