from typing import Literal, Self, overload
from sage.rings.integer import Integer
from sage.rings.real_mpfi import RealIntervalFieldElement
from sage.structure.element import FieldElement
from sage.rings.complex_mpfr import ComplexNumber
from sage.plot.plot import GraphicObject
import sage.misc.sage_input

_str = str

class ComplexIntervalFieldElement(FieldElement):
    def __init__(self, parent: object, real: object, imag: object = ..., base: int = ...) -> None: ...
    def _repr_(self) -> _str: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, i: int) -> RealIntervalFieldElement: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def str(self, base: int = ..., style: _str | None = ...) -> _str: ...
    def _mpfr_(self, parent: object) -> FieldElement: ...
    def plot(self, pointsize: float = ..., **kwds: object) -> GraphicObject: ...
    def _latex_(self) -> _str: ...
    def bisection(self) -> tuple[ComplexIntervalFieldElement, ComplexIntervalFieldElement]: ...
    def is_exact(self) -> Literal[False]: ...
    def endpoints(self) -> tuple[ComplexIntervalFieldElement, ComplexIntervalFieldElement, ComplexIntervalFieldElement, ComplexIntervalFieldElement]: ...
    def edges(self) -> tuple[ComplexIntervalFieldElement, ComplexIntervalFieldElement, ComplexIntervalFieldElement, ComplexIntervalFieldElement]: ...
    def diameter(self) -> RealIntervalFieldElement: ...
    def overlaps(self, other: ComplexIntervalFieldElement) -> bool: ...
    def intersection(self, other: ComplexIntervalFieldElement) -> ComplexIntervalFieldElement: ...
    def union(self, other: ComplexIntervalFieldElement) -> ComplexIntervalFieldElement: ...
    def magnitude(self) -> RealIntervalFieldElement: ...
    def mignitude(self) -> RealIntervalFieldElement: ...
    def center(self) -> ComplexNumber: ...
    def __contains__(self, other: object) -> bool: ...
    def contains_zero(self) -> bool: ...
    def _add_(self, right: object) -> ComplexIntervalFieldElement: ...
    def _sub_(self, right: object) -> ComplexIntervalFieldElement: ...
    def _mul_(self, right: object) -> ComplexIntervalFieldElement: ...
    def norm(self) -> RealIntervalFieldElement: ...
    def _div_(self, right: object) -> ComplexIntervalFieldElement: ...
    def __pow__(self, right: object, modulus: object) -> ComplexIntervalFieldElement: ...
    def _magma_init_(self, magma: object) -> _str: ...
    def _interface_init_(self, I: object = ...) -> _str: ...
    def _sage_input_(self, sib: object, coerce: bool) -> sage.misc.sage_input.SageInputExpression: ...
    def prec(self) -> Integer: ...
    def real(self) -> RealIntervalFieldElement: ...
    def imag(self) -> RealIntervalFieldElement: ...
    def __neg__(self) -> ComplexIntervalFieldElement: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> RealIntervalFieldElement: ...
    def __invert__(self) -> ComplexIntervalFieldElement: ...
    def _complex_mpfr_field_(self, field: object) -> ComplexNumber: ...
    def __int__(self) -> int: ...
    def _integer_(self, _: object) -> Integer: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __bool__(self) -> bool: ...
    def _richcmp_(left: object, right: object, op: int) -> bool: ...
    def lexico_cmp(left: object, right: object) -> int: ...
    def multiplicative_order(self) -> Integer: ...
    def argument(self) -> RealIntervalFieldElement: ...
    def arg(self) -> RealIntervalFieldElement: ...
    def crosses_log_branch_cut(self) -> bool: ...
    def conjugate(self) -> ComplexIntervalFieldElement: ...
    def exp(self) -> ComplexIntervalFieldElement: ...
    def log(self, base: object = ...) -> ComplexIntervalFieldElement: ...
    @overload
    def sqrt(self, all: Literal[False] = ..., **kwds: object) -> ComplexIntervalFieldElement: ...
    @overload
    def sqrt(self, all: Literal[True], **kwds: object) -> list[ComplexIntervalFieldElement]: ...
    @overload
    def sqrt(self, all: bool, **kwds: object) -> ComplexIntervalFieldElement | list[ComplexIntervalFieldElement]: ...
    def is_square(self) -> bool: ...
    def is_NaN(self) -> bool: ...
    def cos(self) -> ComplexIntervalFieldElement: ...
    def sin(self) -> ComplexIntervalFieldElement: ...
    def tan(self) -> ComplexIntervalFieldElement: ...
    def cosh(self) -> ComplexIntervalFieldElement: ...
    def sinh(self) -> ComplexIntervalFieldElement: ...
    def tanh(self) -> ComplexIntervalFieldElement: ...
    def zeta(self, a: object = ...) -> ComplexIntervalFieldElement: ...

def make_ComplexIntervalFieldElement0(fld: object, re: object, im: object) -> ComplexIntervalFieldElement: ...
def create_ComplexIntervalFieldElement(s_real: object, s_imag: object = ..., pad: int = ..., min_prec: int = ...) -> ComplexIntervalFieldElement: ...
