from typing import Self

from sage.categories.morphism import Morphism
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element, FieldElement
from sage.structure.factorization import Factorization
from sage.structure.parent import Parent

type CoercionSlot = Parent | int
type CoercionSlots = dict[str, CoercionSlot]

def is_FpTElement(x: Element) -> bool: ...

class FpTElement(FieldElement):
    _numer: Polynomial
    _denom: Polynomial
    initialized: bool
    p: int

    def __init__(
        self, parent: FpT, numer: Polynomial | Element | int,
        denom: Polynomial | Element | int = 1, coerce: bool = True,
        reduce: bool = True,
    ) -> None: ...

    def _new_c(self) -> FpTElement: ...
    def _copy_c(self) -> FpTElement: ...
    def numer(self) -> Polynomial: ...
    def numerator(self) -> Polynomial: ...
    def denom(self) -> Polynomial: ...
    def denominator(self) -> Polynomial: ...
    def __call__(self, *args: Element, **kwds: Element) -> FpTElement: ...
    def subs(
        self, in_dict: dict[Element, Element] | None = None,
        *args: Element, **kwds: Element,
    ) -> FpTElement: ...
    def valuation(self, v: Element) -> int: ...
    def factor(self) -> Factorization: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _richcmp_(self, other: FpTElement, op: int) -> bool: ...
    def __hash__(self) -> int: ...
    def __neg__(self) -> FpTElement: ...
    def __invert__(self) -> FpTElement: ...
    def _add_(self, other: FpTElement) -> FpTElement: ...
    def _sub_(self, other: FpTElement) -> FpTElement: ...
    def _mul_(self, other: FpTElement) -> FpTElement: ...
    def _div_(self, other: FpTElement) -> FpTElement: ...
    def next(self) -> FpTElement: ...
    def _sqrt_or_None(self) -> FpTElement | None: ...
    def is_square(self) -> bool: ...
    def sqrt(
        self, extend: bool = True, all: bool = False
    ) -> FpTElement | list[FpTElement]: ...
    def __pow__(self, e: int, modulus: None = None) -> FpTElement: ...

class FpT(Parent):
    INTEGER_LIMIT: int

    def __init__(self, R: Parent, names: str | None = None) -> None: ...

    def __iter__(self) -> FpT_iter: ...
    def iter(
        self, bound: int | None = None, start: FpTElement | None = None
    ) -> FpT_iter: ...

class FpT_iter:
    parent: FpT
    degree: int
    cur: FpTElement

    def __init__(
        self, parent: FpT, degree: int | None = None,
        start: FpTElement | None = None,
    ) -> None: ...
    def __cinit__(
        self, parent: FpT, degree: int | None = None,
        start: FpTElement | None = None,
    ) -> None: ...

    def __dealloc__(self) -> None: ...
    def __iter__(self) -> FpT_iter: ...
    def __next__(self) -> FpTElement: ...

class Polyring_FpT_coerce(Morphism):
    p: int

    def __init__(self, R: Parent) -> None: ...

    def _extra_slots(self) -> CoercionSlots: ...
    def _update_slots(self, _slots: CoercionSlots) -> None: ...
    def _call_(self, x: Polynomial) -> FpTElement: ...
    def _call_with_args(
        self, x: Polynomial, args: tuple[Element, ...] = (),
        kwds: dict[str, Element] = {},
    ) -> FpTElement: ...
    def section(self) -> FpT_Polyring_section: ...

class FpT_Polyring_section(Morphism):
    p: int

    def __init__(self, f: Polyring_FpT_coerce) -> None: ...
    def _extra_slots(self) -> CoercionSlots: ...
    def _update_slots(self, _slots: CoercionSlots) -> None: ...
    def _call_(self, x: FpTElement) -> Polynomial: ...

class Fp_FpT_coerce(Morphism):
    p: int

    def __init__(self, R: Parent) -> None: ...

    def _extra_slots(self) -> CoercionSlots: ...
    def _update_slots(self, _slots: CoercionSlots) -> None: ...
    def _call_(self, x: Element) -> FpTElement: ...
    def _call_with_args(
        self, x: Element, args: tuple[Element, ...] = (),
        kwds: dict[str, Element] = {},
    ) -> FpTElement: ...
    def section(self) -> FpT_Fp_section: ...

class FpT_Fp_section(Morphism):
    p: int

    def __init__(self, f: Fp_FpT_coerce) -> None: ...
    def _extra_slots(self) -> CoercionSlots: ...
    def _update_slots(self, _slots: CoercionSlots) -> None: ...
    def _call_(self, x: FpTElement) -> Element: ...

class ZZ_FpT_coerce(Morphism):
    p: int

    def __init__(self, R: Parent) -> None: ...

    def _extra_slots(self) -> CoercionSlots: ...
    def _update_slots(self, _slots: CoercionSlots) -> None: ...
    def _call_(self, x: int) -> FpTElement: ...
    def _call_with_args(
        self, x: int, args: tuple[Element, ...] = (),
        kwds: dict[str, Element] = {},
    ) -> FpTElement: ...
    def section(self) -> Morphism: ...

def unpickle_FpT_element(
    K: FpT, numer: Polynomial, denom: Polynomial
) -> FpTElement: ...
