from collections.abc import Callable, Iterator

from sage.categories.category import Category
from sage.categories.map import Section
from sage.rings.function_field.function_field import FunctionField
from sage.structure.coerce_maps import DefaultConvertMap_unique
from sage.structure.element import Element
from sage.structure.parent import Parent

class FractionField_generic(Parent):
    def __init__(self, R: Parent, element_class: type = ..., category: Category | None = ...) -> None: ...
    def __reduce__(self) -> tuple[Callable[..., Parent], tuple[Parent]]: ...
    def is_field(self, proof: bool = ...) -> bool: ...
    def is_finite(self) -> bool: ...
    def base_ring(self) -> Parent: ...
    def characteristic(self) -> int: ...
    def ring(self) -> Parent: ...
    def is_exact(self) -> bool: ...
    def construction(self) -> tuple[Callable[..., Parent], Parent] | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def ngens(self) -> int: ...
    def gen(self, i: int = ...) -> Element: ...
    def random_element(self, *args: object, **kwds: object) -> Element: ...
    def some_elements(self) -> Iterator[Element] | list[Element]: ...

class FractionField_1poly_field(FractionField_generic):
    def __init__(self, R: Parent, element_class: type = ...) -> None: ...
    def ring_of_integers(self) -> Parent: ...
    def maximal_order(self) -> Parent: ...
    def class_number(self) -> int: ...
    def function_field(self) -> FunctionField: ...

class FractionFieldEmbedding(DefaultConvertMap_unique):
    def is_surjective(self) -> bool: ...
    def is_injective(self) -> bool: ...
    def section(self) -> FractionFieldEmbeddingSection: ...

class FractionFieldEmbeddingSection(Section): ...
