from typing import Generic, Literal, TypeVar, overload

from sage.structure.element import FieldElement, RingElement
from sage.structure.parent import Parent

_BaseElement = TypeVar("_BaseElement", bound=RingElement, default=RingElement)

def is_FractionFieldElement(x: FieldElement) -> bool: ...

class FractionFieldElement(FieldElement, Generic[_BaseElement]):
    _numerator: _BaseElement
    _denominator: _BaseElement
    _is_reduced: bool

    def __init__(
        self,
        parent: Parent,
        numerator: _BaseElement,
        denominator: _BaseElement | int = ...,
        coerce: bool = ...,
        reduce: bool = ...,
    ) -> None: ...
    def reduce(self) -> FractionFieldElement[RingElement] | None: ...
    def __call__(
        self, *x: object, **kwds: object
    ) -> FractionFieldElement[RingElement]: ...
    def subs(
        self, in_dict: dict[object, object] | None = None, *args: object, **kwds: object
    ) -> FractionFieldElement[RingElement]: ...
    def specialization(
        self, D: object = None, phi: object = None
    ) -> FractionFieldElement[RingElement]: ...
    def __copy__(self) -> FractionFieldElement[RingElement]: ...
    def numerator(self) -> RingElement: ...
    def denominator(self) -> RingElement: ...
    @overload
    def is_square(self, root: Literal[False] = ...) -> bool: ...
    @overload
    def is_square(
        self, root: Literal[True]
    ) -> tuple[bool, FractionFieldElement[RingElement]]: ...
    def nth_root(self, n: int) -> FractionFieldElement[RingElement]: ...
    def __hash__(self) -> int: ...
    def _is_atomic(self) -> bool: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _add_(
        self, right: FractionFieldElement[_BaseElement]
    ) -> FractionFieldElement[_BaseElement]: ...
    def _mul_(
        self, right: FractionFieldElement[_BaseElement]
    ) -> FractionFieldElement[_BaseElement]: ...
    def _div_(
        self, right: FractionFieldElement[_BaseElement]
    ) -> FractionFieldElement[_BaseElement]: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __pow__(
        self, right: int, modulus: None = ...
    ) -> FractionFieldElement[RingElement]: ...
    def __neg__(self) -> FractionFieldElement[RingElement]: ...
    def __abs__(self) -> FractionFieldElement[RingElement]: ...
    def __invert__(self) -> FractionFieldElement[RingElement]: ...
    def _richcmp_(self, other: FractionFieldElement[_BaseElement], op: int) -> bool: ...
    def valuation(self, v: RingElement | None = ...) -> int: ...
    def __bool__(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_one(self) -> bool: ...

class FractionFieldElement_1poly_field(FractionFieldElement[_BaseElement]):
    def __init__(
        self,
        parent: Parent,
        numerator: _BaseElement,
        denominator: _BaseElement | int = ...,
        coerce: bool = ...,
        reduce: bool = ...,
    ) -> None: ...
    def normalize_leading_coefficients(self) -> None: ...
    def is_integral(self) -> bool: ...
    def support(self) -> list[RingElement]: ...

def make_element(
    parent: Parent, numerator: _BaseElement, denominator: _BaseElement
) -> FractionFieldElement[_BaseElement]: ...
