from sage.categories.homset import HomsetWithBase
from sage.rings.morphism import RingHomomorphism
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import Parent

class RingHomset_generic(HomsetWithBase[RingHomomorphism, RingElement, RingElement]):
    def __init__(self, R: Ring, S: Ring, category: object = None) -> None: ...
    def has_coerce_map_from(self, x: object) -> bool: ...
    def _element_constructor_(self, x: object, check: bool = True, base_map: object = None) -> RingHomomorphism: ...
    def natural_map(self) -> RingHomomorphism: ...
    def zero(self) -> RingHomomorphism: ...

class RingHomset_quo_ring(RingHomset_generic):
    def _element_constructor_(self, x: object, check: bool = True, base_map: object = None) -> RingHomomorphism: ...
