from sage.rings.ideal import Ideal_generic
from sage.rings.ring import Ring
from sage.structure.parent import Parent

class IdealMonoid_c(Parent):
    def __init__(self, R: Ring) -> None: ...
    def ring(self) -> Ring: ...
    def _element_constructor_(self, x: object) -> Ideal_generic: ...
    def _coerce_map_from_(self, x: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
