from typing import Literal, NoReturn as _NoReturn, overload
from sage.rings.ring import CommutativeRing
from sage.structure.element import InfinityElement as InfinityElement

class InfinityRing_class(CommutativeRing):
    def __init__(self) -> None: ...
    def fraction_field(self) -> _NoReturn: ...
    def ngens(self) -> int: ...
    @overload
    def gen(self, n: Literal[0] = 0) -> PlusInfinity: ...
    @overload
    def gen(self, n: Literal[1]) -> MinusInfinity: ...
    @overload
    def gen(self, n: int) -> PlusInfinity | MinusInfinity: ...
    def gens(self) -> tuple[PlusInfinity, MinusInfinity]: ...
    def is_zero(self) -> bool: ...
    def is_commutative(self) -> bool: ...

class MinusInfinity(InfinityElement):
    def __init__(self, parent: InfinityRing_class = ...) -> None: ...
    def __neg__(self) -> PlusInfinity: ...
    def sqrt(self) -> _NoReturn: ...

class PlusInfinity(InfinityElement):
    def __init__(self, parent: InfinityRing_class = ...) -> None: ...
    def __neg__(self) -> MinusInfinity: ...
    def sqrt(self) -> PlusInfinity: ...

InfinityRing: InfinityRing_class
infinity: PlusInfinity
Infinity: PlusInfinity
minus_infinity: MinusInfinity
