from __future__ import annotations
from typing import NoReturn as _NoReturn
from sage.rings.ring import CommutativeRing
from sage.structure.element import Element
from sage.rings.fraction_field import FractionField_generic

class InfinityRing_class(CommutativeRing):
    def __init__(self) -> None: ...
    def fraction_field(self) -> InfinityRing_class: ...
    def ngens(self) -> int: ...
    def gen(self, n: int = ...) -> PlusInfinity: ...
    def gens(self) -> tuple[PlusInfinity]: ...
    def is_zero(self) -> bool: ...
    def is_commutative(self) -> bool: ...

class MinusInfinity(Element):
    def __init__(self, parent: InfinityRing_class = ...) -> None: ...
    def sqrt(self) -> _NoReturn: ...

class PlusInfinity(Element):
    def __init__(self, parent: InfinityRing_class = ...) -> None: ...
    def sqrt(self) -> PlusInfinity: ...
