from sage.rings.integer import Integer
from sage.rings.ring import CommutativeRing, Ring
from sage.rings.infinity import PlusInfinity as Infinity
from sage.structure.parent import Parent
from sage.categories.morphism import Morphism
from sage.rings.polynomial.polynomial_element import Polynomial

class IntegerRing_class(CommutativeRing):
    def characteristic(self) -> int: ...
    def order(self) -> Infinity: ...
    def is_field(self, proof: bool = ...) -> bool: ...
    def is_finite(self) -> bool: ...
    def random_element(self, x: int | None = None, y: int | None = None) -> Integer: ...
    def _coerce_map_from_(self, S: Parent) -> Morphism | None: ...
    def extension(self, poly: Polynomial, names: str) -> Ring: ...
    def zeta(self, n: int = 2) -> Integer: ...
    def some_elements(self) -> tuple[Integer, ...]: ...
