from collections.abc import Iterable, Iterator
from typing import Literal, overload

from sage.categories.rings import Rings
from sage.modules.free_module import FreeModule_generic
from sage.rings.finite_rings.integer_mod_ring import IntegerModRing_generic
from sage.rings.ideal import Ideal_pid
from sage.rings.integer import Integer
from sage.rings.rational_field import RationalField
from sage.rings.ring import PrincipalIdealDomain, Ring
from sage.rings.infinity import PlusInfinity as Infinity
from sage.structure.parent import ElementConstructorInput, MembershipInput, Parent
from sage.categories.morphism import Morphism
from sage.rings.polynomial.polynomial_element import Polynomial

class IntegerRing_class(PrincipalIdealDomain, Rings.ParentMethods[Integer]):
    def __init__(self) -> None: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def fraction_field(self) -> RationalField: ...
    def characteristic(self) -> Integer: ...
    def order(self) -> Infinity: ...
    def is_field(self, proof: bool = ...) -> bool: ...
    def is_finite(self) -> bool: ...
    def random_element(
        self,
        x: int | Integer | None = None,
        y: int | Integer | None = None,
        distribution: str | None = None,
    ) -> Integer: ...
    def prod(self, values: Iterable[ElementConstructorInput]) -> Integer: ...
    def sum(self, values: Iterable[ElementConstructorInput]) -> Integer: ...
    def zero(self) -> Integer: ...
    def one(self) -> Integer: ...
    def __iter__(self) -> Iterator[Integer]: ...
    def __contains__(self, x: MembershipInput) -> bool: ...
    def __rmul__(self, other: int | Integer) -> Ideal_pid[Integer]: ...
    def __pow__(self, n: int | Integer) -> FreeModule_generic[Integer]: ...
    def ideal(
        self,
        *args: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> Ideal_pid[Integer]: ...
    def quotient(
        self,
        I: Ideal_pid[Integer],
        names: str | tuple[str, ...] | None = ...,
        **kwds: ElementConstructorInput,
    ) -> IntegerModRing_generic: ...
    def _coerce_map_from_(self, S: Parent) -> Morphism | None: ...
    def extension(self, poly: Polynomial, names: str) -> Ring: ...
    def zeta(self, n: int = 2) -> Integer: ...
    def some_elements(self) -> tuple[Integer, ...]: ...
    def degree(self) -> int: ...
    def absolute_degree(self) -> int: ...
    def krull_dimension(self) -> int: ...
    def completion(
        self,
        p: int | Integer | Infinity,
        prec: int,
        extras: dict[str, str] | None = ...,
    ) -> Parent: ...
    def residue_field(
        self,
        prime: int | Integer,
        check: bool = ...,
        names: str | None = ...,
    ) -> Parent: ...
    @overload
    def range(self, end: int) -> Iterator[Integer]: ...
    @overload
    def range(self, start: int, end: int) -> Iterator[Integer]: ...
    @overload
    def range(self, start: int, end: int, step: int) -> Iterator[Integer]: ...
    def _an_element_(self) -> Integer: ...
    def discriminant(self) -> Integer: ...
    def roots_of_unity(self) -> list[Integer]: ...
    def _pseudo_fraction_field(self) -> RationalField: ...
    def is_noetherian(self) -> bool: ...
    def is_integrally_closed(self) -> bool: ...
    def is_unique_factorization_domain(self, proof: bool = ...) -> bool: ...
    def is_dedekind_domain(self) -> bool: ...
    def gens(self) -> tuple[Integer]: ...
    def gen(self, n: int = ...) -> Integer: ...
    def ngens(self) -> int: ...
    def parameter(self) -> Integer: ...
    def _gap_init_(self) -> str: ...
    def _fricas_init_(self) -> str: ...
    def _polymake_init_(self) -> str: ...
    def from_bytes(
        self, input_bytes: bytes, byteorder: str = ..., is_signed: bool = ...
    ) -> Integer: ...

ZZ: IntegerRing_class
Z: IntegerRing_class

def IntegerRing() -> IntegerRing_class: ...
def is_IntegerRing(x: Parent) -> bool: ...
def crt_basis(X: list[Integer]) -> list[Integer]: ...
