from collections.abc import Callable, Iterator

from sage.rings.laurent_series_ring import LaurentSeriesRing
from sage.rings.polynomial.laurent_polynomial import LaurentPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.power_series_ring_element import PowerSeries
from sage.rings.ring import Ring
from sage.structure.element import AlgebraElement, Element
from sage.structure.parent import Parent

type ElementList[E] = list[E]

class LaurentSeries(AlgebraElement):
    def __init__(self, parent: LaurentSeriesRing, f: PowerSeries | Polynomial, n: int = 0) -> None: ...
    def __hash__(self) -> int: ...
    def change_ring(self, R: Parent) -> LaurentSeries: ...
    def is_unit(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_monomial(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def verschiebung(self, n: int) -> LaurentSeries: ...
    V = verschiebung
    def __getitem__(self, i: int | slice) -> Element | LaurentSeries: ...
    def __iter__(self) -> Iterator[Element]: ...
    def list(self) -> ElementList[Element]: ...
    def coefficients(self) -> ElementList[Element]: ...
    def residue(self) -> Element: ...
    def exponents(self) -> ElementList[int]: ...
    def lift_to_precision(self, absprec: int | None = ...) -> LaurentSeries: ...
    def add_bigoh(self, prec: int) -> LaurentSeries: ...
    def O(self, prec: int) -> LaurentSeries: ...
    def degree(self) -> int: ...
    def __neg__(self) -> LaurentSeries: ...
    def shift(self, k: int) -> LaurentSeries: ...
    def __lshift__(self, k: int) -> LaurentSeries: ...
    def __rshift__(self, k: int) -> LaurentSeries: ...
    def truncate(self, n: int) -> LaurentSeries: ...
    def truncate_laurentseries(self, n: int) -> LaurentSeries: ...
    def truncate_neg(self, n: int) -> LaurentSeries: ...
    def common_prec(self, other: LaurentSeries) -> int: ...
    def common_valuation(self, other: LaurentSeries) -> int: ...
    def valuation(self) -> int: ...
    def variable(self) -> str: ...
    def prec(self) -> int: ...
    def precision_absolute(self) -> int: ...
    def precision_relative(self) -> int: ...
    def __copy__(self) -> LaurentSeries: ...
    def reverse(self, precision: int | None = ...) -> LaurentSeries: ...
    def derivative(self, *args: Element) -> LaurentSeries: ...
    def integral(self) -> LaurentSeries: ...
    def nth_root(self, n: int, prec: int | None = ...) -> LaurentSeries: ...
    def inverse(self) -> LaurentSeries: ...
    def laurent_polynomial(self) -> LaurentPolynomial: ...
    def valuation_zero_part(self) -> PowerSeries: ...
    def revert(self, precision: int | None = None) -> LaurentSeries: ...
    def is_square(self, root: bool = False) -> bool: ...
    def power_series(self) -> PowerSeries: ...
    def __call__(self, *x: object, **kwds: object) -> Element: ...
    def map_coefficients(self, f: Callable[[Element], Element], new_base_ring: Ring | None = None) -> LaurentSeries: ...
