from sage.rings.laurent_series_ring_element import LaurentSeries
from sage.rings.ring import Ring

class LaurentSeriesRing_generic:
    def gen(self, n: int = ...) -> LaurentSeries: ...
    def default_prec(self) -> int: ...
    def base_ring(self) -> Ring: ...

class LaurentSeriesRing(LaurentSeriesRing_generic):
    ...
