from sage.rings.fraction_field import FractionField_generic
from sage.rings.ring import Ring
from sage.structure.element import Element, IntegralDomainElement
from sage.structure.factorization import Factorization
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

def normalize_extra_units(
    self, add_units: list[Element] | tuple[Element, ...], warning: bool = True
) -> list[Element]: ...

class LocalizationElement(IntegralDomainElement):
    def __init__(self, parent: Localization, x: object) -> None: ...
    def factor(self, proof: bool | None = None) -> Factorization: ...
    def numerator(self) -> Element: ...
    def denominator(self) -> Element: ...
    def is_unit(self) -> bool: ...
    def inverse_of_unit(self) -> LocalizationElement: ...
    def __hash__(self) -> int: ...

class Localization(Parent, UniqueRepresentation):
    def __init__(
        self,
        base_ring: Ring,
        extra_units: object,
        names: object = None,
        normalize: bool = True,
        category: object = None,
        warning: bool = True,
    ) -> None: ...
    def ngens(self) -> int: ...
    def gen(self, i: int) -> LocalizationElement: ...
    def gens(self) -> tuple[Element, ...]: ...
    def fraction_field(self) -> FractionField_generic: ...
    def characteristic(self) -> int: ...
    def krull_dimension(self) -> int: ...
    def is_field(self, proof: bool = True) -> bool: ...
