# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MPowerSeriesRing_generic:
    Element: _SageObject
    @staticmethod
    def __classcall__(cls: builtins.object, base_ring: builtins.object, num_gens: builtins.object, name_list: builtins.object, order: builtins.str = ..., default_prec: builtins.int = ..., sparse: builtins.bool = ...) -> _SageObject: ...
    def __init__(self, base_ring: builtins.object, num_gens: builtins.object, name_list: builtins.object, order: builtins.str = ..., default_prec: builtins.int = ..., sparse: builtins.bool = ...) -> None: ...
    def is_noetherian(self, proof: builtins.bool = ...) -> builtins.bool: ...
    def term_order(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def construction(self) -> _SageObject: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    def remove_var(self, *var: builtins.object) -> _SageObject: ...
    def laurent_series_ring(self) -> _SageObject: ...
    def is_sparse(self) -> builtins.bool: ...
    def is_dense(self) -> builtins.bool: ...
    def gen(self, n: builtins.int = ...) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def prec_ideal(self) -> _SageObject: ...
    def bigoh(self, prec: builtins.int) -> _SageObject: ...
    def O(self, prec: builtins.int) -> _SageObject: ...

def unpickle_multi_power_series_ring_v0(base_ring: builtins.object, num_gens: builtins.object, names: builtins.object, order: builtins.object, default_prec: builtins.object, sparse: builtins.bool) -> _SageObject: ...
