from sage.rings.ideal import Ideal_generic
from sage.rings.ideal_monoid import IdealMonoid_c
from sage.rings.ring import Ring

class IdealMonoid_nc(IdealMonoid_c):
    def __init__(self, R: Ring) -> None: ...
    def _element_constructor_(self, x: object) -> Ideal_nc: ...

class Ideal_nc(Ideal_generic):
    def __init__(self, ring: Ring, gens: list[object] | tuple[object, ...], coerce: bool = True, side: str = "twosided") -> None: ...
    def __eq__(self, right: object) -> bool: ...
    def __ne__(self, right: object) -> bool: ...
    def __hash__(self) -> int: ...
    def side(self) -> str: ...
    def __mul__(self, other: Ideal_nc | Ideal_generic) -> Ideal_nc: ...
