from sage.structure.element import Element
from sage.rings.laurent_series_ring_element import LaurentSeries

from sage.rings.infinity import PlusInfinity, MinusInfinity
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.power_series_ring import PowerSeriesRing_generic as PowerSeriesRing
from sage.rings.ring import Ring
from typing import List  # noqa: UP035
from sage.categories.morphism import Morphism

class PowerSeries(Element):
    def __init__(self, parent: PowerSeriesRing, prec: int, is_gen: bool = False) -> None: ...
    def parent(self) -> PowerSeriesRing: ...
    def base_ring(self) -> Ring: ...
    def degree(self) -> int: ...
    def polynomial(self) -> Polynomial: ...
    def truncate(self, prec: int) -> PowerSeries: ...
    def derivative(self, *args: object) -> PowerSeries: ...
    def integral(self) -> PowerSeries: ...
    def sqrt(self, prec: int | None = None, extend: bool = False, all: bool = False, name: str | None = None) -> PowerSeries: ...
    def is_unit(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def prec(self) -> int: ...
    
    # Enumerated methods from Phase 1
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, ...]: ...
    def is_sparse(self) -> bool: ...
    def is_dense(self) -> bool: ...
    def is_gen(self) -> bool: ...
    def base_extend(self, R: Ring) -> PowerSeries: ...
    def change_ring(self, R: Ring) -> PowerSeries: ...
    def __call__(self, x: object) -> Element: ...
    def coefficients(self) -> List[object]: ...    # noqa: UP006, UP035
    def exponents(self) -> List[int]: ...    # noqa: UP006, UP035
    def list(self) -> List[object]: ...    # noqa: UP006, UP035
    def lift_to_precision(self, absprec: int | None = None) -> PowerSeries: ...
    def __copy__(self) -> PowerSeries: ...
    def padded_list(self, n: int | None = None) -> List[object]: ...    # noqa: UP006, UP035
    def precision_absolute(self) -> int: ...
    def precision_relative(self) -> int: ...
    def add_bigoh(self, prec: int) -> PowerSeries: ...
    def __getitem__(self, n: int) -> Element: ...
    def common_prec(self, f: PowerSeries) -> int: ...
    def __bool__(self) -> bool: ...
    def inverse(self) -> PowerSeries: ...
    def valuation_zero_part(self) -> PowerSeries: ...
    def __mod__(self, other: object) -> PowerSeries: ...
    def __pow__(self, r: int, dummy: object = None) -> PowerSeries: ...
    def shift(self, n: int) -> PowerSeries: ...
    def __lshift__(self, n: int) -> PowerSeries: ...
    def __rshift__(self, n: int) -> PowerSeries: ...
    def is_monomial(self) -> bool: ...
    def map_coefficients(self, f: Morphism, new_base_ring: Ring | None = None) -> PowerSeries: ...
    def jacobi_continued_fraction(self) -> tuple[tuple[Element, Element], ...]: ...
    def super_delta_fraction(self, delta: int) -> List[tuple[Element, int, Polynomial]]: ...  # noqa: UP006, UP035
    def stieltjes_continued_fraction(self) -> List[Element]: ...  # noqa: UP006, UP035
    def is_square(self) -> bool: ...
    def square_root(self) -> PowerSeries: ...
    def nth_root(self, n: int, prec: int | None = None) -> PowerSeries: ...
    def cos(self, prec: int | PlusInfinity = ...) -> PowerSeries: ...
    def sin(self, prec: int | PlusInfinity = ...) -> PowerSeries: ...
    def tan(self, prec: int | PlusInfinity = ...) -> PowerSeries: ...
    def sinh(self, prec: int | PlusInfinity = ...) -> PowerSeries: ...
    def cosh(self, prec: int | PlusInfinity = ...) -> PowerSeries: ...
    def tanh(self, prec: int | PlusInfinity = ...) -> PowerSeries: ...
    def O(self, prec: int) -> PowerSeries: ...
    def solve_linear_de(self, prec: int | PlusInfinity = ..., b: PowerSeries | None = None, f0: object | None = None) -> PowerSeries: ...
    def exp(self, prec: int | None = None) -> PowerSeries: ...
    def log(self, prec: int | None = None) -> PowerSeries: ...
    def V(self, n: int) -> PowerSeries: ...
    def valuation(self) -> int: ...
    def variable(self) -> str: ...
    def __setitem__(self, n: int, value: object) -> None: ...
    def laurent_series(self) -> LaurentSeries: ...
    def egf_to_ogf(self) -> PowerSeries: ...
    def ogf_to_egf(self) -> PowerSeries: ...
