from sage.rings.infinity import PlusInfinity
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.power_series_ring import PowerSeriesRing_generic
from sage.rings.power_series_ring_element import PowerSeries
from sage.structure.element import Element

type ElementList[E] = list[E]

class PowerSeries_pari(PowerSeries):
    def __init__(
        self,
        parent: PowerSeriesRing_generic | PowerSeriesRing,
        f: object | int = 0,
        prec: int | PlusInfinity | bool = ...,
        check: object = None,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def polynomial(self) -> Polynomial: ...
    def valuation(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __call__(self, *x: object, **kwds: object) -> Element: ...
    def __getitem__(self, n: int) -> Element: ...
    def list(self) -> ElementList[Element]: ...
    def padded_list(self, n: int | None = None) -> ElementList[Element]: ...
    def monomial_coefficients(self, copy: object = None) -> dict[int, Element]: ...
    def integral(self, var: object = None) -> PowerSeries_pari: ...
    def revert(self, precision: int | None = None) -> PowerSeries_pari: ...
    def reverse(self, precision: int | None = None) -> PowerSeries_pari: ...
