import builtins

from sage.rings.infinity import PlusInfinity
from sage.rings.laurent_series_ring_element import LaurentSeries
from sage.rings.power_series_ring_element import PowerSeries
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import AlgebraElement, Element

class PuiseuxSeries(AlgebraElement):
    def __call__(self, x: Element | float) -> Element: ...
    def laurent_part(self) -> LaurentSeries: ...
    def ramification_index(self) -> int: ...
    def valuation(self) -> Rational | PlusInfinity: ...
    def add_bigoh(self, prec: int | Rational | PlusInfinity) -> PuiseuxSeries: ...
    def change_ring(self, R: Ring) -> PuiseuxSeries: ...
    def is_unit(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_monomial(self) -> bool: ...
    def list(self) -> builtins.list[Element]: ...
    def coefficients(self) -> builtins.list[Element]: ...
    def exponents(self) -> builtins.list[Rational]: ...
    def degree(self) -> Rational: ...
    def shift(self, r: int | Rational) -> PuiseuxSeries: ...
    def truncate(self, r: int | Rational) -> PuiseuxSeries: ...
    def prec(self) -> Rational | PlusInfinity: ...
    precision_absolute = prec
    def precision_relative(self) -> Rational | int: ...
    def common_prec(self, p: PuiseuxSeries) -> Rational | PlusInfinity: ...
    def variable(self) -> str: ...
    def laurent_series(self) -> LaurentSeries: ...
    def power_series(self) -> PowerSeries: ...
    def inverse(self) -> PuiseuxSeries: ...
