from sage.rings.laurent_series_ring_element import LaurentSeries
from sage.rings.power_series_ring_element import PowerSeries
from sage.rings.puiseux_series_ring import PuiseuxSeriesRing
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import AlgebraElement, Element

type ElementList[E] = list[E]

class PuiseuxSeries(AlgebraElement):
    def __init__(self, parent: PuiseuxSeriesRing, f: LaurentSeries, e: int = 1) -> None: ...
    def __call__(self, x: Element) -> Element: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, r: int) -> Element: ...
    def laurent_part(self) -> LaurentSeries: ...
    def ramification_index(self) -> int: ...
    def valuation(self) -> Rational: ...
    def add_bigoh(self, prec: object) -> PuiseuxSeries: ...
    def change_ring(self, R: Ring) -> PuiseuxSeries: ...
    def is_unit(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_monomial(self) -> bool: ...
    def list(self) -> ElementList[Element]: ...
    def coefficients(self) -> ElementList[Element]: ...
    def exponents(self) -> ElementList[Rational]: ...
    def degree(self) -> Rational: ...
    def shift(self, r: int | Rational) -> PuiseuxSeries: ...
    def truncate(self, r: int | Rational) -> PuiseuxSeries: ...
    def prec(self) -> Rational: ...
    def precision_relative(self) -> Rational: ...
    def common_prec(self, p: PuiseuxSeries) -> Rational: ...
    def variable(self) -> str: ...
    def laurent_series(self) -> LaurentSeries: ...
    def power_series(self) -> PowerSeries: ...
    def inverse(self) -> PuiseuxSeries: ...
