from __future__ import annotations
from sage.rings.integer import Integer
from sage.rings.ring import Field
from sage.structure.element import Element
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.complex_mpfr import ComplexNumber
from sage.rings.real_mpfr import RealNumber
from sage.rings.rational import Rational

class AlgebraicRealField(Field):
    def __init__(self) -> None: ...
    def completion(self, p: object, prec: object = ..., extras: object = ...) -> Field: ...
    def algebraic_closure(self) -> AlgebraicField: ...
    def gens(self) -> tuple[()]: ...
    def gen(self, n: int = ...) -> Integer: ... # It fails with ValueError("QQbar has no generators")
    def ngens(self) -> int: ...
    def zeta(self, n: int = ...) -> AlgebraicNumber: ...
    def polynomial_root(self, p: Polynomial, root: object = ...) -> AlgebraicNumber: ...
    def random_element(self, *args: object, **kwds: object) -> AlgebraicNumber: ...

class AlgebraicField(Field):
    def __init__(self) -> None: ...
    def completion(self, p: object, prec: object = ..., extras: object = ...) -> Field: ...
    def algebraic_closure(self) -> AlgebraicField: ...
    def construction(self) -> tuple[object, object]: ...
    def gens(self) -> tuple[()]: ...
    def gen(self, n: int = ...) -> Integer: ... # Fails with ValueError
    def ngens(self) -> int: ...
    def zeta(self, n: int = ...) -> AlgebraicNumber: ...
    def polynomial_root(self, p: Polynomial, root: object = ...) -> AlgebraicNumber: ...
    def random_element(self, *args: object, **kwds: object) -> AlgebraicNumber: ...

class AlgebraicNumber(Element):
    def __init__(self, parent: AlgebraicField | AlgebraicRealField, value: object) -> None: ...
    def real(self) -> AlgebraicNumber: ...
    def imag(self) -> AlgebraicNumber: ...
    def conjugate(self) -> AlgebraicNumber: ...
    def norm(self) -> Rational: ...
    def interval_exact(self) -> AlgebraicNumber: ...
    def complex_number(self, **kwds: object) -> ComplexNumber: ...
    def complex_exact(self) -> AlgebraicNumber: ...
    def multiplicative_order(self) -> Integer: ...
    def rational_argument(self) -> Rational: ...
    def minpoly(self) -> Polynomial: ...
