from collections.abc import Callable
from typing import Literal, Self, overload

import sage.rings.abc
from sage.categories.action import Action
from sage.categories.pushout import AlgebraicClosureFunctor
from sage.libs.pari.gen import gen
from sage.misc.fast_methods import Singleton
from sage.rings.complex_interval import ComplexIntervalFieldElement
from sage.rings.complex_interval_field import ComplexIntervalField_class
from sage.rings.complex_mpfr import ComplexNumber
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.morphism import RingHomomorphism
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.number_field.number_field_element import NumberFieldElement
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.rational_field import RationalField
from sage.rings.real_mpfi import RealIntervalField, RealIntervalFieldElement
from sage.rings.real_mpfr import RealNumber
from sage.rings.ring import Field
from sage.structure.element import Element, FieldElement
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

type _Interval = RealIntervalFieldElement | ComplexIntervalFieldElement
type _IntervalField = RealIntervalField | ComplexIntervalField_class

def number_field_elements_from_algebraics(
    self,
    minimal: bool = False,
    same_field: bool = False,
    embedded: bool = False,
    name: str = "a",
    prec: int = 53,
) -> tuple[NumberField_generic, list[NumberFieldElement], RingHomomorphism]: ...

class AlgebraicField_common(sage.rings.abc.AlgebraicField_common):
    def default_interval_prec(self) -> int: ...
    def characteristic(self) -> Integer: ...
    def order(self) -> PlusInfinity: ...
    def common_polynomial(self, poly: Polynomial) -> AlgebraicPolynomialTracker: ...

class AlgebraicRealField(
    Singleton, AlgebraicField_common, sage.rings.abc.AlgebraicRealField
):
    def __init__(self) -> None: ...
    def completion(self, p: object, prec: object, extras: object = ...) -> Field: ...
    def algebraic_closure(self) -> AlgebraicField: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, n: int = ...) -> Integer: ...
    def ngens(self) -> int: ...
    def zeta(self, n: int = 2) -> AlgebraicNumber: ...
    def polynomial_root(
        self, poly: Polynomial, interval: _Interval, multiplicity: int = 1
    ) -> AlgebraicNumber: ...
    def random_element(self, *args: object, **kwds: object) -> AlgebraicNumber: ...

class AlgebraicField(Singleton, AlgebraicField_common, sage.rings.abc.AlgebraicField):
    def __init__(self) -> None: ...
    def completion(self, p: object, prec: object, extras: object = ...) -> Field: ...
    def algebraic_closure(self) -> AlgebraicField: ...
    def construction(self) -> tuple[AlgebraicClosureFunctor, RationalField]: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, n: int = ...) -> Integer: ...
    def ngens(self) -> int: ...
    def zeta(self, n: int = 2) -> AlgebraicNumber: ...
    def polynomial_root(
        self, poly: Polynomial, interval: _Interval, multiplicity: int = 1
    ) -> AlgebraicNumber: ...
    def random_element(self, *args: object, **kwds: object) -> AlgebraicNumber: ...
    @staticmethod
    def mk_algebraic(x: object) -> AlgebraicNumber: ...

class AlgebraicGeneratorRelation(SageObject):
    parent: AlgebraicGenerator
    child2_poly: Polynomial
    child2: AlgebraicGenerator
    child1_poly: Polynomial
    child1: AlgebraicGenerator

    def __init__(
        self,
        child1: AlgebraicGenerator,
        child1_poly: Polynomial,
        child2: AlgebraicGenerator,
        child2_poly: Polynomial,
        parent: AlgebraicGenerator,
    ) -> None: ...

class AlgebraicGenerator(SageObject):
    def __init__(self, field: Field, root: ANDescr) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def is_complex(self) -> bool: ...
    def root_as_algebraic(self) -> AlgebraicNumber: ...
    def is_trivial(self) -> bool: ...
    def field(self) -> Field: ...
    def pari_field(self) -> gen: ...
    def conjugate(self) -> AlgebraicGenerator: ...
    def union(
        self, other: AlgebraicGenerator, name: str = "a"
    ) -> AlgebraicGenerator: ...
    def super_poly(
        self, super: AlgebraicGenerator, checked: object = None
    ) -> NumberFieldElement | None: ...
    def __call__(self, elt: object) -> NumberFieldElement: ...

class ANDescr(SageObject):
    def is_simple(self) -> bool: ...
    def neg(self, n: AlgebraicNumber) -> ANDescr: ...
    def invert(self, n: AlgebraicNumber) -> ANDescr: ...
    def abs(self, n: AlgebraicNumber) -> ANDescr: ...
    def real(self, n: AlgebraicNumber) -> ANDescr: ...
    def imag(self, n: AlgebraicNumber) -> ANDescr: ...
    def conjugate(self, n: AlgebraicNumber) -> ANDescr: ...
    def norm(self, n: AlgebraicNumber) -> ANDescr: ...

class AlgebraicNumber_base(FieldElement):
    def __init__(
        self, parent: AlgebraicField | AlgebraicRealField, x: object
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def is_square(self) -> bool: ...
    def is_integer(self) -> bool: ...
    @overload
    def sqrt(self, all: Literal[False] = ..., extend: bool = ...) -> Self: ...
    @overload
    def sqrt(self, all: Literal[True], extend: bool = ...) -> list[Self]: ...
    @overload
    def nth_root(self, n: int, all: Literal[False] = ...) -> Self: ...
    @overload
    def nth_root(self, n: int, all: Literal[True]) -> list[Self]: ...
    def as_number_field_element(
        self, minimal: bool = False, embedded: bool = False, prec: int = 53
    ) -> tuple[NumberField_generic, NumberFieldElement, RingHomomorphism]: ...
    def is_integral(self) -> bool: ...
    def exactify(self) -> ANDescr: ...
    def simplify(self) -> None: ...
    def minpoly(self) -> Polynomial: ...
    def degree(self) -> int: ...
    def interval_fast(self, field: _IntervalField) -> _Interval: ...
    def interval_diameter(self, diam: RealNumber) -> _Interval: ...
    def interval(
        self, field: _IntervalField | sage.rings.abc.RealBallField
    ) -> _Interval: ...
    def radical_expression(self) -> Expression: ...

class AlgebraicNumber(AlgebraicNumber_base):
    def __init__(self, x: object | AlgebraicField | AlgebraicRealField) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def real(self) -> AlgebraicReal: ...
    def imag(self) -> AlgebraicReal: ...
    def conjugate(self) -> AlgebraicNumber: ...
    def norm(self) -> AlgebraicReal: ...
    def interval_exact(
        self, field: ComplexIntervalField_class
    ) -> ComplexIntervalFieldElement: ...
    def complex_number(
        self, field: ComplexIntervalField_class
    ) -> ComplexIntervalFieldElement: ...
    def complex_exact(
        self, field: ComplexIntervalField_class
    ) -> ComplexIntervalFieldElement: ...
    def multiplicative_order(self) -> Integer | PlusInfinity: ...
    def rational_argument(self) -> Rational: ...

class AlgebraicReal(AlgebraicNumber_base):
    def __init__(self, x: object | AlgebraicField | AlgebraicRealField) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def round(self) -> Integer: ...
    def trunc(self) -> Integer: ...
    def real(self) -> AlgebraicReal: ...
    def imag(self) -> AlgebraicReal: ...
    def conjugate(self) -> AlgebraicReal: ...
    def multiplicative_order(self) -> Integer | PlusInfinity: ...
    def sign(self) -> Integer: ...
    def interval_exact(self, field: RealIntervalField) -> RealIntervalFieldElement: ...
    def real_number(self, field: RealIntervalField) -> RealNumber: ...
    def real_exact(self, field: RealIntervalField) -> RealNumber: ...

class AlgebraicNumberPowQQAction(Action):
    def __init__(self) -> None: ...

class ANRational(ANDescr):
    def __init__(self, x: Rational) -> None: ...
    def handle_sage_input(
        self, sib: object, coerce: bool, is_qqbar: bool
    ) -> tuple[object, bool]: ...
    def generator(self) -> AlgebraicGenerator: ...
    def is_complex(self) -> bool: ...
    def exactify(self) -> ANRational: ...
    def is_simple(self) -> bool: ...
    def minpoly(self) -> Polynomial: ...
    def neg(self, n: AlgebraicNumber) -> ANRational: ...
    def invert(self, n: AlgebraicNumber) -> ANRational: ...
    def abs(self, n: AlgebraicNumber) -> ANRational: ...
    def rational_argument(self, n: AlgebraicNumber) -> Rational: ...
    def angle(self) -> Rational: ...
    def scale(self) -> Rational: ...

class AlgebraicPolynomialTracker(SageObject):
    def __init__(self, poly: Polynomial) -> None: ...
    def poly(self) -> Polynomial: ...
    def is_complex(self) -> bool: ...
    def complex_roots(self, prec: int, multiplicity: int) -> list[ComplexNumber]: ...
    def exactify(self) -> None: ...
    def factors(self) -> list[Polynomial]: ...
    def generator(self) -> AlgebraicGenerator: ...

class ANRoot(ANDescr):
    def __init__(
        self, poly: Polynomial, interval: _Interval, multiplicity: int = 1
    ) -> None: ...
    def handle_sage_input(
        self, sib: object, coerce: bool, is_qqbar: bool
    ) -> tuple[object, bool]: ...
    def is_complex(self) -> bool: ...
    def conjugate(self, n: AlgebraicNumber) -> ANUnaryExpr: ...
    def refine_interval(self, interval: _Interval, prec: int) -> _Interval: ...
    def exactify(self) -> ANExtensionElement: ...

class ANExtensionElement(ANDescr):
    def __init__(
        self, generator: AlgebraicGenerator, value: NumberFieldElement
    ) -> None: ...
    def handle_sage_input(
        self, sib: object, coerce: bool, is_qqbar: bool
    ) -> tuple[object, bool]: ...
    def is_complex(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def generator(self) -> AlgebraicGenerator: ...
    def exactify(self) -> ANExtensionElement: ...
    def field_element_value(self) -> NumberFieldElement: ...
    def minpoly(self) -> Polynomial: ...
    def simplify(self, n: AlgebraicNumber_base) -> ANDescr: ...
    def neg(self, n: AlgebraicNumber) -> ANExtensionElement: ...
    def invert(self, n: AlgebraicNumber) -> ANExtensionElement: ...
    def conjugate(self, n: AlgebraicNumber) -> ANExtensionElement: ...
    def norm(self, n: AlgebraicNumber) -> ANUnaryExpr: ...
    def abs(self, n: AlgebraicNumber) -> ANDescr: ...
    def rational_argument(self, n: AlgebraicNumber) -> Rational: ...

class ANUnaryExpr(ANDescr):
    def __init__(self, arg: ANDescr, op: str) -> None: ...
    def handle_sage_input(
        self, sib: object, coerce: bool, is_qqbar: bool
    ) -> tuple[object, bool]: ...
    def is_complex(self) -> bool: ...
    def exactify(self) -> ANDescr: ...

class ANBinaryExpr(ANDescr):
    def __init__(
        self, left: ANDescr, right: ANDescr, op: Callable[[object, object], object]
    ) -> None: ...
    def handle_sage_input(
        self, sib: object, coerce: bool, is_qqbar: bool
    ) -> tuple[object, bool]: ...
    def is_complex(self) -> bool: ...
    def exactify(self) -> ANDescr: ...

AA: AlgebraicRealField
QQbar: AlgebraicField
