from sage.rings.integer import Integer
from sage.structure.element import FieldElement

class Rational(FieldElement):
    def numerator(self) -> Integer: ...
    def denominator(self) -> Integer: ...
    def is_integral(self) -> bool: ...
    def continued_fraction_list(self) -> list[Integer]: ...
    def height(self) -> Integer: ...
