from typing import overload

from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.structure.element import FieldElement
from sage.structure.parent import ElementConstructorInput, MembershipInput
from sage.symbolic.expression import Expression

type _List[T] = list[T]
type _Text = str

class Rational(FieldElement):
    def __init__(self, x: ElementConstructorInput = ...) -> None: ...
    def __add__(self, other: int | Integer | Rational) -> Rational: ...
    def __radd__(self, other: int | Integer) -> Rational: ...
    def __sub__(self, other: int | Integer | Rational) -> Rational: ...
    def __rsub__(self, other: int | Integer) -> Rational: ...
    @overload
    def __mul__(self, other: int | Integer | Rational) -> Rational: ...
    @overload
    def __mul__(self, other: FreeModuleElement[Integer | Rational]) -> FreeModuleElement[Integer | Rational]: ...
    def __rmul__(self, other: int | Integer) -> Rational: ...
    def __truediv__(self, other: int | Integer | Rational) -> Rational: ...
    def __rtruediv__(self, other: int | Integer) -> Rational: ...
    def __mod__(self, other: int | Integer | Rational) -> Rational: ...
    def __pow__(self, n: int | Integer | Rational) -> Rational | Expression: ...
    def numerator(self) -> Integer: ...
    def denominator(self) -> Integer: ...
    def is_integral(self) -> bool: ...
    def continued_fraction_list(self, type: str = ...) -> list[Integer]: ...
    def height(self) -> Integer: ...
    def __index__(self) -> int: ...
    def list(self) -> _List[Rational]: ...
    def __copy__(self) -> Rational: ...
    def _latex_(self) -> str: ...
    def _mathml_(self) -> str: ...
    def is_square(self) -> bool: ...
    def is_perfect_power(self, expected_value: bool = ...) -> bool: ...
    def period(self) -> Integer: ...
    def nth_root(self, n: int) -> Rational: ...
    def is_nth_power(self, n: int) -> bool: ...
    def str(self, base: int = ...) -> _Text: ...
    def __float__(self) -> float: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, n: int) -> Rational: ...
    def __invert__(self) -> Rational: ...
    def __pos__(self) -> Rational: ...
    def __neg__(self) -> Rational: ...
    def __bool__(self) -> bool: ...
    def __abs__(self) -> Rational: ...
    def abs(self) -> Rational: ...
    def __lt__(self, other: MembershipInput) -> bool: ...
    def __le__(self, other: MembershipInput) -> bool: ...
    def __gt__(self, other: MembershipInput) -> bool: ...
    def __ge__(self, other: MembershipInput) -> bool: ...
    def sign(self) -> Integer: ...
    def mod_ui(self, n: int) -> Integer: ...
    def norm(self) -> Rational: ...
    def relative_norm(self) -> Rational: ...
    def absolute_norm(self) -> Rational: ...
    def trace(self) -> Rational: ...
    def numer(self) -> Integer: ...
    def __int__(self) -> int: ...
    def denom(self) -> Integer: ...
    def as_integer_ratio(self) -> tuple[Integer, Integer]: ...
    def support(self) -> list[Integer]: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def trunc(self) -> Integer: ...
    def round(self, mode: str = ...) -> Integer: ...
    def sqrt(self) -> Rational | Expression: ...
    def valuation(self, p: int | Integer) -> Integer: ...
    def real(self) -> Rational: ...
    def imag(self) -> Rational: ...
    def is_one(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def is_rational(self) -> bool: ...
    def conjugate(self) -> Rational: ...

def integer_rational_power(a: Integer, b: Rational) -> Integer | None: ...
def make_rational(s: str) -> Rational: ...
