from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from sage.rings.integer import Integer
    from sage.rings.rational import Rational

# from sage.rings.integer import Integer
# from sage.rings.rational import Rational
from collections.abc import Iterator

class RationalField:
    def __init__(self) -> None: ...
    def _repr_(self) -> str: ...
    def discriminant(self) -> Integer: ...
    def class_number(self) -> Integer: ...
    def signature(self) -> tuple[Integer, Integer]: ...
    def embeddings(self, K: object) -> list[object]: ...
    def _coerce_map_from_(self, S: object) -> bool | None: ...
    def is_field(self, proof: bool = ...) -> bool: ...
    def characteristic(self) -> Integer: ...
    def gen(self, n: int = ...) -> Rational: ...
    def gens(self) -> tuple[Rational]: ...
    def ngens(self) -> Integer: ...
    def zeta(self, n: int = ...) -> Rational: ...
    def random_element(self, num_bound: int | None = ..., den_bound: int | None = ..., *args: object, **kwds: object) -> Rational: ...
    def some_elements(self) -> Iterator[Rational]: ...
    def _an_element_(self) -> Rational: ...
