from collections.abc import Callable, Iterator, Sequence
from typing import Literal, Self, overload

from sage.categories.map import Map
from sage.categories.pushout import ConstructionFunctor
from sage.categories.sets_cat import _SympySetLike
from sage.groups.additive_abelian.qmodnz import QmodnZ
from sage.interfaces.expect import Expect
from sage.misc.sage_input import SageInputBuilder, SageInputExpression
from sage.rings.infinity import PlusInfinity
from sage.rings.ideal import Ideal_generic
from sage.rings.integer import Integer
from sage.rings.integer_ring import IntegerRing_class
from sage.rings.number_field.number_field import NumberField_generic
from sage.rings.number_field.number_field_element import NumberFieldElement
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.qqbar import AlgebraicField
from sage.rings.rational import Rational
from sage.rings.ring import Field
from sage.rings.valuation.valuation import DiscreteValuation
from sage.structure.factorization import Factorization
from sage.structure.parent import Parent
from sage.structure.sequence import Sequence_generic


class RationalField(Field):
    def __new__(cls) -> Self: ...
    def __init__(self) -> None: ...
    def __reduce__(self) -> tuple[type[RationalField], tuple[()]]: ...
    def _repr_(self) -> str: ...
    def _repr_option(self, key: str) -> bool: ...
    def _latex_(self) -> str: ...
    def __len__(self) -> int: ...
    def construction(self) -> tuple[ConstructionFunctor, IntegerRing_class]: ...
    def completion(
        self, p: int | Integer | PlusInfinity, prec: int, extras: dict[str, str] = ...
    ) -> Field: ...
    def _coerce_map_from_(self, S: Parent | type[int]) -> Map | None: ...
    def _is_valid_homomorphism_(
        self, codomain: Parent, im_gens: Sequence[Rational | int | Integer], base_map: Map | None = ...
    ) -> bool: ...
    def __iter__(self) -> Iterator[Rational]: ...
    def __truediv__(self, I: Parent | Ideal_generic) -> Parent | QmodnZ: ...
    def range_by_height(self, start: int, end: int | None = ...) -> Iterator[Rational]: ...
    def primes_of_bounded_norm_iter(self, B: Integer | int) -> Iterator[Integer]: ...
    def discriminant(self) -> Integer: ...
    def absolute_discriminant(self) -> Integer: ...
    def relative_discriminant(self) -> Integer: ...
    def class_number(self) -> Integer: ...
    def signature(self) -> tuple[Integer, Integer]: ...
    def embeddings(self, K: Field) -> Sequence_generic: ...
    def automorphisms(self) -> Sequence_generic: ...
    def places(self, all_complex: bool = ..., prec: int | PlusInfinity | None = ...) -> list[Map]: ...
    def complex_embedding(self, prec: int = 53) -> Map: ...
    def residue_field(self, p: int | Integer, check: bool = ...) -> Field: ...
    def hilbert_symbol_negative_at_S(
        self,
        S: list[Integer | int],
        b: int | Integer | Rational,
        check: bool = ...,
    ) -> Rational: ...
    def number_field(self) -> RationalField: ...
    def is_field(self, proof: bool = ...) -> bool: ...
    def is_absolute(self) -> bool: ...
    def is_prime_field(self) -> bool: ...
    def characteristic(self) -> Integer: ...
    def gen(self, n: int = ...) -> Rational: ...
    def gens(self) -> tuple[Rational]: ...
    def ngens(self) -> Integer: ...
    def degree(self) -> Integer: ...
    def absolute_degree(self) -> Integer: ...
    def maximal_order(self) -> IntegerRing_class: ...
    def power_basis(self) -> list[Rational]: ...
    def extension(
        self,
        poly: Polynomial | NumberFieldElement,
        name: str | None = ...,
        names: str | tuple[str, ...] | None = ...,
        latex_name: str | None = ...,
        latex_names: str | tuple[str, ...] | None = ...,
        *args: str,
        **kwds: str,
    ) -> NumberField_generic: ...
    def algebraic_closure(self) -> AlgebraicField: ...
    def order(self) -> PlusInfinity: ...
    def polynomial(self) -> Polynomial: ...
    def _an_element_(self) -> Rational: ...
    def _sage_input_(self, sib: SageInputBuilder, coerced: bool) -> SageInputExpression: ...
    def some_elements(self) -> Iterator[Rational]: ...
    def random_element(
        self,
        num_bound: int | None = ...,
        den_bound: int | None = ...,
        distribution: str | None = ...,
        *args: int,
        **kwds: str | int | bool,
    ) -> Rational: ...
    def zeta(self, n: int = ...) -> Rational: ...
    defining_polynomial = polynomial
    absolute_polynomial = polynomial
    def _gap_init_(self) -> str: ...
    def _magma_init_(self, magma: Expect) -> str: ...
    def _macaulay2_init_(self, macaulay2: Expect | None = None) -> str: ...
    def _fricas_init_(self) -> str: ...
    _axiom_init_ = _fricas_init_
    def _polymake_init_(self) -> str: ...
    def _sympy_(self) -> _SympySetLike: ...
    def _factor_univariate_polynomial(self, f: Polynomial) -> Factorization: ...
    @overload
    def selmer_generators(
        self,
        S: Sequence[Integer | int],
        m: int,
        proof: bool = ...,
        orders: Literal[False] = ...,
    ) -> list[Integer | int]: ...
    @overload
    def selmer_generators(
        self,
        S: Sequence[Integer | int],
        m: int,
        proof: bool = ...,
        orders: Literal[True] = ...,
    ) -> tuple[list[Integer | int], list[Integer]]: ...
    def selmer_group_iterator(
        self,
        S: Sequence[Integer | int],
        m: int,
        proof: bool = ...,
    ) -> Iterator[Rational]: ...
    def selmer_space(
        self,
        S: Sequence[Integer | int],
        p: int,
        proof: bool | None = ...,
    ) -> tuple[
        Parent,
        list[Rational],
        Callable[[Sequence[int]], Rational],
        Callable[[Rational], Sequence[int]],
    ]: ...
    def quadratic_defect(
        self,
        a: int | Integer | Rational,
        p: Integer | Ideal_generic,
        check: bool = ...,
    ) -> Integer | PlusInfinity: ...
    def valuation(self, p: Integer | Parent) -> DiscreteValuation: ...


QQ: RationalField
Q: RationalField
