from __future__ import annotations
from builtins import str as String
from sage.rings.integer import Integer
from sage.rings.abc import RealField
from sage.structure.element import Element
from sage.rings.rational import Rational
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.complex_mpfr import ComplexField_class
from sage.rings.qqbar import AlgebraicRealField

class RealField_class(RealField):
    def __init__(self, prec: int = ..., sci_not: int = ..., rnd: String = ...) -> None: ...
    def construction(self) -> tuple[object, object]: ...
    def gen(self, n: int = ...) -> RealNumber: ...
    def complex_field(self) -> ComplexField_class: ...
    def algebraic_closure(self) -> AlgebraicRealField: ...
    def ngens(self) -> int: ...
    def gens(self) -> tuple[RealNumber, ...]: ...
    def characteristic(self) -> Integer: ...
    def name(self) -> String: ...
    def precision(self) -> Integer: ...
    def to_prec(self, prec: int) -> RealField_class: ...
    def pi(self) -> RealNumber: ...
    def euler_constant(self) -> RealNumber: ...
    def catalan_constant(self) -> RealNumber: ...
    def log2(self) -> RealNumber: ...
    def random_element(self, *args: object, **kwargs: object) -> RealNumber: ...
    def factorial(self, n: int) -> RealNumber: ...
    def rounding_mode(self) -> String: ...
    def scientific_notation(self, status: bool | None = ...) -> bool: ...
    def zeta(self, n: int = ...) -> RealNumber: ...
    def prec(self) -> Integer: ...
    def is_exact(self) -> bool: ...
    def e(self) -> RealNumber: ...
    def an_element(self) -> RealNumber: ...
    def some_elements(self) -> list[RealNumber]: ...

class RealNumber(Element):
    def __init__(self, parent: RealField_class, x: object = ..., base: int = ...) -> None: ...
    def real(self) -> RealNumber: ...
    def imag(self) -> RealNumber: ...
    def str(self, base: int = ..., no_sci: int = ..., truncate: bool = ..., **kwds: object) -> String: ...
    def hex(self) -> String: ...
    def integer_part(self) -> Integer: ...
    def fp_rank(self) -> int: ...
    def fp_rank_delta(self, other: RealNumber) -> int: ...
    def multiplicative_order(self) -> Integer: ...
    def sign(self) -> int: ...
    def precision(self) -> Integer: ...
    def conjugate(self) -> RealNumber: ...
    def ulp(self) -> RealNumber: ...
    def epsilon(self) -> RealNumber: ...
    def round(self, mode: String | None = ...) -> Integer: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def trunc(self) -> Integer: ...
    def frac(self) -> RealNumber: ...
    def nexttoward(self, other: RealNumber) -> RealNumber: ...
    def nextabove(self) -> RealNumber: ...
    def nextbelow(self) -> RealNumber: ...
    def sign_mantissa_exponent(self) -> tuple[int, Integer, Integer]: ...
    def exact_rational(self) -> Rational: ...
    def as_integer_ratio(self) -> tuple[Integer, Integer]: ...
    def simplest_rational(self) -> Rational: ...
    def nearby_rational(self, max_error: object = ..., max_denominator: object = ...) -> Rational: ...
    def is_NaN(self) -> bool: ...
    def is_positive_infinity(self) -> bool: ...
    def is_negative_infinity(self) -> bool: ...
    def is_infinity(self) -> bool: ...
    def is_unit(self) -> bool: ...
    def is_real(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def sqrt(self, extend: bool = ..., all: bool = ...) -> RealNumber: ...
    def is_square(self) -> bool: ...
    def cube_root(self) -> RealNumber: ...
    def log(self, base: object = ...) -> RealNumber: ...
    def log2(self) -> RealNumber: ...
    def log10(self) -> RealNumber: ...
    def log1p(self) -> RealNumber: ...
    def exp(self) -> RealNumber: ...
    def exp2(self) -> RealNumber: ...
    def exp10(self) -> RealNumber: ...
    def expm1(self) -> RealNumber: ...
    def eint(self) -> RealNumber: ...
    def cos(self) -> RealNumber: ...
    def sin(self) -> RealNumber: ...
    def tan(self) -> RealNumber: ...
    def sincos(self) -> tuple[RealNumber, RealNumber]: ...
    def arccos(self) -> RealNumber: ...
    def arcsin(self) -> RealNumber: ...
    def arctan(self) -> RealNumber: ...
    def cosh(self) -> RealNumber: ...
    def sinh(self) -> RealNumber: ...
    def tanh(self) -> RealNumber: ...
    def coth(self) -> RealNumber: ...
    def arccoth(self) -> RealNumber: ...
    def cot(self) -> RealNumber: ...
    def csch(self) -> RealNumber: ...
    def arccsch(self) -> RealNumber: ...
    def csc(self) -> RealNumber: ...
    def sech(self) -> RealNumber: ...
    def arcsech(self) -> RealNumber: ...
    def sec(self) -> RealNumber: ...
    def arccosh(self) -> RealNumber: ...
    def arcsinh(self) -> RealNumber: ...
    def arctanh(self) -> RealNumber: ...
    def agm(self, right: RealNumber) -> RealNumber: ...
    def erf(self) -> RealNumber: ...
    def erfc(self) -> RealNumber: ...
    def j0(self) -> RealNumber: ...
    def j1(self) -> RealNumber: ...
    def jn(self, n: int) -> RealNumber: ...
    def y0(self) -> RealNumber: ...
    def y1(self) -> RealNumber: ...
    def yn(self, n: int) -> RealNumber: ...
    def gamma(self) -> RealNumber: ...
    def log_gamma(self) -> RealNumber: ...
    def zeta(self) -> RealNumber: ...
    def algebraic_dependency(self, n: int, **kwds: object) -> Polynomial: ...
    def nth_root(self, n: int, extend: bool = ..., all: bool = ...) -> RealNumber: ...
