from typing import overload
from sage.rings.ring import Field
from sage.structure.element import FieldElement, Element
from sage.categories.morphism import Morphism
from sage.rings.continued_fraction import ContinuedFraction_base

RLF: RealLazyField_class
CLF: ComplexLazyField_class

def RealLazyField() -> RealLazyField_class: ...
def ComplexLazyField() -> ComplexLazyField_class: ...
def make_element(parent: LazyField, *args: object) -> LazyFieldElement: ...

class LazyField(Field):
    def __init__(self, base: object = ..., names: object = ..., normalize: bool = ..., category: object = ...) -> None: ...
    def __getattr__(self, name: str) -> LazyConstant: ...
    def interval_field(self, prec: int | None = ...) -> Field: ...

class RealLazyField_class(LazyField):
    def interval_field(self, prec: int | None = ...) -> Field: ...
    def construction(self) -> tuple[object, object]: ...
    def _latex_(self) -> str: ...
    def gen(self, i: int = ...) -> LazyFieldElement: ...
    def _repr_(self) -> str: ...
    def __hash__(self) -> int: ...

class ComplexLazyField_class(LazyField):
    def __init__(self) -> None: ...
    def interval_field(self, prec: int | None = ...) -> Field: ...
    def gen(self, i: int = ...) -> LazyFieldElement: ...
    def construction(self) -> tuple[object, object]: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def __hash__(self) -> int: ...

class LazyFieldElement(FieldElement):
    def depth(self) -> int: ...
    def approx(self) -> Element: ...
    def _real_double_(self, R: object) -> Element: ...
    def _complex_double_(self, R: object) -> Element: ...
    def _generic_(self, R: object) -> Element: ...
    def _real_mpfi_(self, R: object) -> Element: ...
    def _complex_mpfi_(self, R: object) -> Element: ...
    def _mpfr_(self, R: object) -> Element: ...
    def _complex_mpfr_field_(self, R: object) -> Element: ...
    def eval(self, R: object) -> Element: ...
    def continued_fraction(self) -> ContinuedFraction_base: ...
    def __hash__(self) -> int: ...
    def _add_(self, other: LazyFieldElement) -> LazyFieldElement: ...
    def _sub_(self, other: LazyFieldElement) -> LazyFieldElement: ...
    def _mul_(self, other: LazyFieldElement) -> LazyFieldElement: ...
    def _div_(self, other: LazyFieldElement) -> LazyFieldElement: ...
    def __pow__(self, other: LazyFieldElement, dummy: object) -> LazyFieldElement: ...
    def __neg__(self) -> LazyFieldElement: ...
    def __invert__(self) -> LazyFieldElement: ...
    def _richcmp_(self, other: object, op: int) -> bool: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __dir__(self) -> list[str]: ...
    def __getattribute__(self, name: str) -> Element: ...

class LazyWrapper(LazyFieldElement):
    def __init__(self, parent: LazyField, value: object, check: bool = ...) -> None: ...
    def __neg__(self) -> LazyWrapper: ...
    def __invert__(self) -> LazyWrapper: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def eval(self, R: object) -> Element: ...
    def continued_fraction(self) -> ContinuedFraction_base: ...

class LazyBinop(LazyFieldElement):
    def __init__(self, parent: LazyField, left: object, right: object, op: object) -> None: ...
    def depth(self) -> int: ...
    def eval(self, R: object) -> Element: ...
    def __float__(self) -> float: ...
    def __hash__(self) -> int: ...

class LazyUnop(LazyFieldElement):
    def __init__(self, parent: LazyField, arg: object, op: object) -> None: ...
    def depth(self) -> int: ...
    def eval(self, R: object) -> Element: ...
    def __hash__(self) -> int: ...
    def __float__(self) -> float: ...

class LazyNamedUnop(LazyUnop):
    def __init__(self, parent: LazyField, arg: object, op: str, extra_args: tuple[object, ...] | None = ...) -> None: ...
    def eval(self, R: object) -> Element: ...
    def approx(self) -> Element: ...
    def __hash__(self) -> int: ...
    def __float__(self) -> float: ...
    def __call__(self, *args: object) -> LazyNamedUnop: ...

class LazyConstant(LazyFieldElement):
    def __init__(self, parent: LazyField, name: str, extra_args: tuple[object, ...] | None = ...) -> None: ...
    def eval(self, R: object) -> Element: ...
    def __call__(self, *args: object) -> LazyConstant: ...
    def __hash__(self) -> int: ...
    def __float__(self) -> float: ...

class LazyAlgebraic(LazyFieldElement):
    def __init__(self, parent: LazyField, poly: object, approx: object, prec: int = ...) -> None: ...
    def eval(self, R: object) -> Element: ...
    def __float__(self) -> float: ...

class LazyWrapperMorphism(Morphism):
    def __init__(self, domain: object, codomain: LazyField) -> None: ...
    def _call_(self, x: object) -> LazyWrapper: ...
