from collections.abc import Sequence
from typing import NoReturn

from sage.categories.morphism import Morphism
from sage.rings.integer import Integer
from sage.rings.infinity import PlusInfinity
from sage.rings.real_mpfr import RealField_class
from sage.rings.complex_double import ComplexDoubleElement, ComplexDoubleField_class
from sage.rings.complex_mpfr import ComplexField_class, ComplexNumber
from sage.misc.sage_input import SageInputBuilder, SageInputExpression
from sage.structure.factorization import Factorization
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.rings.polynomial.polynomial_element import Polynomial

class gen: ...

class RealDoubleField_class:
    def __init__(self) -> None: ...
    def __reduce__(self) -> tuple[type[RealDoubleField_class], tuple[()]]: ...
    def is_exact(self) -> bool: ...
    def _latex_(self) -> str: ...
    def _sage_input_(self, sib: SageInputBuilder, coerced: bool) -> SageInputExpression: ...
    def _repr_option(self, key: str) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def construction(self) -> tuple[object, object]: ...
    def complex_field(self) -> ComplexDoubleField_class: ...
    def algebraic_closure(self) -> ComplexDoubleField_class: ...
    def _coerce_map_from_(self, S: object) -> Morphism | None: ...
    def _magma_init_(self, magma: object) -> str: ...
    def _fricas_init_(self) -> str: ...
    def _polymake_init_(self) -> str: ...
    def precision(self) -> int: ...
    def prec(self) -> int: ...
    def to_prec(self, prec: int) -> RealDoubleField_class | RealField_class: ...
    def gen(self, n: int = 0) -> RealDoubleElement: ...
    def ngens(self) -> int: ...
    def characteristic(self) -> Integer: ...
    def random_element(self, min: float = -1, max: float = 1) -> RealDoubleElement: ...
    def name(self) -> str: ...
    def __hash__(self) -> int: ...
    def pi(self) -> RealDoubleElement: ...
    def euler_constant(self) -> RealDoubleElement: ...
    def log2(self) -> RealDoubleElement: ...
    def factorial(self, n: int) -> RealDoubleElement: ...
    def zeta(self, n: int = 2) -> RealDoubleElement: ...
    def NaN(self) -> RealDoubleElement: ...
    def nan(self) -> RealDoubleElement: ...
    def _factor_univariate_polynomial(self, f: object) -> Factorization: ...

class RealDoubleElement:
    def __init__(self, x: object) -> None: ...
    def __reduce__(self) -> tuple[type[RealDoubleElement], tuple[float]]: ...
    def prec(self) -> int: ...
    def ulp(self) -> RealDoubleElement: ...
    def real(self) -> RealDoubleElement: ...
    def imag(self) -> RealDoubleElement: ...
    def __complex__(self) -> complex: ...
    def _integer_(self, ZZ: object | None = None) -> Integer: ...
    def __mpfr__(self) -> float: ...
    def _interface_init_(self, I: object | None = None) -> str: ...
    def _mathematica_init__(self) -> str: ...
    def _sage_input_(
        self, sib: SageInputBuilder, coerced: bool
    ) -> SageInputExpression: ...
    def _repr_(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def _latex_(self) -> str: ...
    def __hash__(self) -> int: ...
    def _im_gens_(
        self, codomain: Parent, im_gens: Sequence[Element], base_map: Morphism | None = None
    ) -> RealDoubleElement: ...
    def str(self) -> str: ...
    def __copy__(self) -> RealDoubleElement: ...
    def __deepcopy__(self, memo: dict[object, object]) -> RealDoubleElement: ...
    def integer_part(self) -> Integer: ...
    def sign_mantissa_exponent(self) -> tuple[int, Integer, Integer]: ...
    def as_integer_ratio(self) -> tuple[Integer, Integer]: ...
    def __invert__(self) -> RealDoubleElement: ...
    def _add_(self, right: RealDoubleElement) -> RealDoubleElement: ...
    def _sub_(self, right: RealDoubleElement) -> RealDoubleElement: ...
    def _mul_(self, right: RealDoubleElement) -> RealDoubleElement: ...
    def _div_(self, right: RealDoubleElement) -> RealDoubleElement: ...
    def __neg__(self) -> RealDoubleElement: ...
    def conjugate(self) -> RealDoubleElement: ...
    def __abs__(self) -> RealDoubleElement: ...
    def abs(self) -> RealDoubleElement: ...
    def __lshift__(self, y: int) -> NoReturn: ...
    def __rshift__(self, y: int) -> NoReturn: ...
    def multiplicative_order(self) -> int | PlusInfinity: ...
    def sign(self) -> int: ...
    def round(self) -> Integer: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def ceiling(self) -> Integer: ...
    def trunc(self) -> Integer: ...
    def frac(self) -> RealDoubleElement: ...
    def __float__(self) -> float: ...
    def _rpy_(self) -> float: ...
    def __int__(self) -> int: ...
    def _complex_mpfr_field_(self, CC: ComplexField_class) -> ComplexNumber: ...
    def _complex_double_(self, CDF: ComplexDoubleField_class) -> ComplexDoubleElement: ...
    def __pari__(self) -> gen: ...
    def is_NaN(self) -> bool: ...
    def is_positive_infinity(self) -> bool: ...
    def is_negative_infinity(self) -> bool: ...
    def is_infinity(self) -> bool: ...
    def _richcmp_(self, right: RealDoubleElement, op: int) -> bool: ...
    def NaN(self) -> RealDoubleElement: ...
    def nan(self) -> RealDoubleElement: ...
    def sqrt(
        self, extend: bool = True, all: bool = False
    ) -> RealDoubleElement | list[RealDoubleElement] | list[ComplexDoubleElement]: ...
    def is_square(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def cube_root(self) -> RealDoubleElement: ...
    def agm(self, other: RealDoubleElement | float) -> RealDoubleElement: ...
    def algebraic_dependency(self, n: int) -> Polynomial: ...
    def algdep(self, n: int) -> Polynomial: ...

class RealDoubleField_class_Instance(RealDoubleField_class): ...

class ToRDF:
    def __init__(self, R: object) -> None: ...
    def _call_(self, x: object) -> RealDoubleElement: ...
    def _repr_type(self) -> str: ...

def RealDoubleField() -> RealDoubleField_class: ...
