from collections.abc import Iterator
from typing import NoReturn

from sage.categories.category import Category
from sage.rings.ideal import Ideal_generic as Ideal
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.number_field.number_field_element import NumberFieldElement
from sage.rings.number_field.number_field_ideal import NumberFieldIdeal
from sage.rings.number_field.order import Order as NumberFieldOrder
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.category_object import NameSpec
from sage.structure.parent import Parent
from sage.structure.element import Element

class Ring(Parent):
    def __init__(
        self,
        base: Parent | object,
        names: NameSpec = None,
        normalize: bool = True,
        category: Category | None = None,
    ) -> None: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __len__(self) -> int: ...
    def __xor__(self, n: object) -> NoReturn: ...
    def base_extend(self, X: Parent) -> Parent: ...
    def category(self) -> Category: ...
    def __mul__(self, x: object) -> Ideal: ...
    def zero(self) -> Element: ...
    def one(self) -> Element: ...
    def order(self) -> int | PlusInfinity | NumberFieldOrder: ...
    
    def characteristic(self) -> int | Integer: ...
    def is_commutative(self) -> bool: ...
    def is_field(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_integral_domain(self) -> bool: ...
    def is_noetherian(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def base_ring(self) -> Ring: ...
    def fraction_field(self) -> Field: ...
    def ideal(self, *args: object, **kwds: object) -> Ideal | NumberFieldIdeal: ...
    def quotient(self, I: object, names: object = None) -> Ring: ...

class CommutativeRing(Ring):
    def __init__(self, *args: object, **kwds: object) -> None: ...
    def krull_dimension(self) -> int: ...

class IntegralDomain(Ring):
    def __init__(self, *args: object, **kwds: object) -> None: ...

class NoetherianRing(Ring):
    def __init__(self, *args: object, **kwds: object) -> None: ...

class DedekindDomain(Ring):
    def __init__(self, *args: object, **kwds: object) -> None: ...

class PrincipalIdealDomain(Ring):
    def __init__(self, *args: object, **kwds: object) -> None: ...

def _is_Field(x: object) -> bool: ...

class Field(CommutativeRing):
    def algebraic_closure(self) -> Field: ...
    def extension(
        self,
        poly: Polynomial | NumberFieldElement,
        name: str | None = ...,
        names: str | tuple[str, ...] | None = ...,
        latex_name: str | None = ...,
        latex_names: str | tuple[str, ...] | None = ...,
        *args: str,
        **kwds: str,
    ) -> Field: ...

class Algebra(Ring):
    def __init__(
        self, base_ring: Parent | object, *args: object, **kwds: object
    ) -> None: ...

class CommutativeAlgebra(Ring):
    def __init__(
        self, base_ring: Parent | object, *args: object, **kwds: object
    ) -> None: ...
