from collections.abc import Hashable, Iterable, Iterator
from typing import Self

from sage.combinat.free_module import CombinatorialFreeModule
from sage.misc.fast_methods import WithEqualityById
from sage.monoids.indexed_free_monoid import (
    IndexedFreeAbelianMonoid,
    IndexedFreeAbelianMonoidElement,
)
from sage.rings.ring import Ring
from sage.sets.family import AbstractFamily
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

class AtomicSpeciesElement(WithEqualityById, Element):
    def __init__(
        self,
        parent: AtomicSpecies | Parent[Self],
        dis: object,
        domain_partition: object,
    ) -> None: ...
    def grade(self) -> int: ...
    def structures(self, *labels: object) -> Iterator[object]: ...
    def __call__(self, *args: object) -> PolynomialSpeciesElement: ...

class AtomicSpecies(UniqueRepresentation, Parent):
    def __init__(self, names: str | tuple[str, ...]) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def grading_set(self) -> Parent: ...
    def subset(self, size: int) -> AtomicSpecies: ...
    def graded_component(self, mc: object) -> Element: ...

class MolecularSpecies(IndexedFreeAbelianMonoid):
    def __init__(self, names: str | tuple[str, ...]) -> None: ...
    def grading_set(self) -> Parent: ...
    def subset(self, size: int) -> MolecularSpecies: ...
    def graded_component(self, mc: object) -> Element: ...

class PolynomialSpeciesElement(CombinatorialFreeModule.Element):
    def is_constant(self) -> bool: ...
    def is_virtual(self) -> bool: ...
    def is_molecular(self) -> bool: ...
    def is_atomic(self) -> bool: ...
    def tilde(self) -> PolynomialSpeciesElement: ...
    def hadamard_product(
        self, other: PolynomialSpeciesElement
    ) -> PolynomialSpeciesElement: ...
    def __call__(self, *args: object) -> Element: ...
    def factor(self) -> Iterator[Element]: ...
    def structures(self, *labels: object) -> Iterator[object]: ...

class PolynomialSpecies(CombinatorialFreeModule):
    def __init__(
        self,
        base_ring: Ring | CommutativeRing,
        names: str | tuple[str, ...] | Iterable[Hashable] | AbstractFamily | None,
    ) -> None: ...
    def change_ring(self, R: Ring) -> PolynomialSpecies: ...
    def degree_on_basis(self, m: object) -> int: ...
    def one_basis(self) -> IndexedFreeAbelianMonoidElement: ...
    def product_on_basis(
        self, H: IndexedFreeAbelianMonoidElement, K: IndexedFreeAbelianMonoidElement
    ) -> IndexedFreeAbelianMonoidElement: ...
