from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject

class Word_class(SageObject):
    def parent(self) -> Parent: ...
    def length(self) -> int: ...
    def is_primitive(self) -> bool: ...
    def primitive(self) -> Word_class: ...
    def conjugate(self, pos: int) -> Word_class: ...
    def reversal(self) -> Word_class: ...
    def has_period(self, p: int) -> bool: ...
