from collections.abc import Hashable, Iterable, Iterator, Mapping, Sequence
from typing import Generic, TypeVar, overload

from sage.combinat.words.abstract_word import Word_class
from sage.rings.integer import Integer

_Letter = TypeVar("_Letter", bound=Hashable, default=Hashable)


class FiniteWord_class(
    Word_class,
    Generic[_Letter],
):
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_Letter]: ...
    @overload
    def __getitem__(self, key: int | Integer) -> _Letter: ...
    @overload
    def __getitem__(self, key: slice) -> FiniteWord_class[_Letter]: ...
    def concatenate(
        self,
        other: FiniteWord_class[_Letter],
    ) -> FiniteWord_class[_Letter]: ...
    __mul__ = concatenate
    __add__ = concatenate
    def reversal(self) -> FiniteWord_class[_Letter]: ...
    def shuffle(
        self,
        other: FiniteWord_class[_Letter],
        overlap: int | Integer = ...,
    ) -> Iterable[FiniteWord_class[_Letter]]: ...
    def lex_less(self, other: FiniteWord_class[_Letter]) -> bool: ...
    def is_empty(self) -> bool: ...
    def number_of_factors(
        self,
        n: int | Integer | None = ...,
    ) -> Integer | dict[int, Integer]: ...
    def lempel_ziv_complexity(self) -> int: ...
    def is_lyndon(self) -> bool: ...
    def lyndon_factorization(
        self,
    ) -> tuple[FiniteWord_class[_Letter], ...]: ...
    def degree(
        self,
        weights: Sequence[int | Integer]
        | Mapping[_Letter, int | Integer]
        | None = ...,
    ) -> int | Integer: ...
    def deg_lex_less(
        self,
        other: FiniteWord_class[_Letter],
        weights: Sequence[int | Integer]
        | Mapping[_Letter, int | Integer]
        | None = ...,
    ) -> bool: ...
    def inv_lex_less(self, other: FiniteWord_class[_Letter]) -> bool: ...
    def rev_lex_less(self, other: FiniteWord_class[_Letter]) -> bool: ...
    def evaluation_dict(self) -> dict[_Letter, int]: ...
    def evaluation(self) -> list[int]: ...
    def length(self) -> int: ...
    def longest_common_prefix(
        self,
        other: FiniteWord_class[_Letter],
    ) -> FiniteWord_class[_Letter]: ...
    def is_prefix(self, other: FiniteWord_class[_Letter]) -> bool: ...
    def is_suffix(self, other: FiniteWord_class[_Letter]) -> bool: ...
    def factors(
        self,
        n: int | Integer | None = ...,
    ) -> Iterable[FiniteWord_class[_Letter]]: ...
