# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def get_cycles(f: builtins.object, domain: builtins.object) -> _SageObject: ...

class PeriodicPointIterator:
    def __init__(self, m: builtins.int, cycle: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def get_iterator(self, i: builtins.int) -> _SageObject: ...

class WordMorphism:
    def __init__(self, data: builtins.object, domain: builtins.object = ..., codomain: builtins.object = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __call__(self, w: builtins.object, order: builtins.int = ...) -> _SageObject: ...
    def latex_layout(self, layout: builtins.object = ...) -> _SageObject: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __pow__(self, exp: builtins.object) -> Self: ...
    def extend_by(self, other: builtins.object) -> _SageObject: ...
    def restrict_domain(self, alphabet: builtins.object) -> _SageObject: ...
    def incidence_matrix(self) -> _SageObject: ...
    def domain(self) -> _SageObject: ...
    def codomain(self) -> _SageObject: ...
    def is_endomorphism(self) -> builtins.bool: ...
    def is_self_composable(self) -> builtins.bool: ...
    def image(self, letter: builtins.object) -> _SageObject: ...
    def images(self) -> builtins.list[_SageObject]: ...
    def reversal(self) -> _SageObject: ...
    def is_empty(self) -> builtins.bool: ...
    def is_erasing(self) -> builtins.bool: ...
    def is_identity(self) -> builtins.bool: ...
    def partition_of_domain_alphabet(self) -> _SageObject: ...
    def is_involution(self) -> builtins.bool: ...
    def pisot_eigenvector_right(self) -> _SageObject: ...
    def pisot_eigenvector_left(self) -> _SageObject: ...
    def is_primitive(self) -> builtins.bool: ...
    def is_prolongable(self, letter: builtins.object) -> builtins.bool: ...
    def is_uniform(self, k: builtins.int = ...) -> builtins.bool: ...
    def fixed_point(self, letter: builtins.object) -> _SageObject: ...
    def fixed_points(self) -> _SageObject: ...
    def periodic_point(self, letter: builtins.object) -> _SageObject: ...
    def periodic_points(self) -> _SageObject: ...
    def language(self, n: builtins.int, u: builtins.object = ...) -> _SageObject: ...
    def conjugate(self, pos: builtins.object) -> _SageObject: ...
    def has_left_conjugate(self) -> builtins.bool: ...
    def has_right_conjugate(self) -> builtins.bool: ...
    def list_of_conjugates(self) -> _SageObject: ...
    def is_in_classP(self, f: builtins.object = ...) -> builtins.bool: ...
    def has_conjugate_in_classP(self, f: builtins.object = ...) -> builtins.bool: ...
    def dual_map(self, k: builtins.int = ...) -> _SageObject: ...
    def rauzy_fractal_projection(self, eig: builtins.object = ..., prec: builtins.int = ...) -> _SageObject: ...
    def rauzy_fractal_points(self, n: builtins.int = ..., exchange: builtins.bool = ..., eig: builtins.object = ..., translate: builtins.object = ..., prec: builtins.int = ...) -> _SageObject: ...
    def rauzy_fractal_plot(self, n: builtins.int = ..., exchange: builtins.bool = ..., eig: builtins.object = ..., translate: builtins.object = ..., prec: builtins.int = ..., colormap: builtins.str = ..., opacity: builtins.object = ..., plot_origin: builtins.object = ..., plot_basis: builtins.bool = ..., point_size: builtins.object = ...) -> _SageObject: ...
    def is_growing(self, letter: builtins.object = ...) -> builtins.bool: ...
    def growing_letters(self) -> _SageObject: ...
    def immortal_letters(self) -> _SageObject: ...
    def letter_growth_types(self) -> _SageObject: ...
    def abelian_rotation_subspace(self) -> _SageObject: ...
    def is_injective(self) -> builtins.bool: ...
    def is_pushy(self, w: builtins.object = ...) -> builtins.bool: ...
    def is_unboundedly_repetitive(self, w: builtins.object = ...) -> builtins.bool: ...
    def is_repetitive(self, w: builtins.object = ...) -> builtins.bool: ...
    def infinite_repetitions_primitive_roots(self, w: builtins.object = ..., allow_growing: builtins.object = ...) -> _SageObject: ...
    def simplify_alphabet_size(self, Z: builtins.object = ...) -> _SageObject: ...
    def simplify_until_injective(self) -> _SageObject: ...
