import builtins
from collections.abc import (
    Iterator as _Iterator,
)

class _SageObject: ...

class ShuffleProduct_w1w2:
    def __init__(
        self, w1: builtins.object, w2: builtins.object, check: builtins.bool = ...
    ) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class ShuffleProduct_shifted:
    def __init__(
        self, w1: builtins.object, w2: builtins.object, check: builtins.bool = ...
    ) -> None: ...
