import builtins
from collections.abc import (
    Iterator as _Iterator,
)
from typing import Self

class _SageObject: ...

class WordDatatype:
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __hash__(self) -> builtins.int: ...

class WordDatatype_list:
    def __init__(
        self, parent: builtins.object = ..., data: builtins.object = ...
    ) -> None: ...
    def __contains__(self, a: object) -> bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def length(self) -> _SageObject: ...
    def __getitem__(self, key: builtins.object) -> _SageObject: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def number_of_letter_occurrences(self, a: builtins.object) -> _SageObject: ...

class WordDatatype_str:
    def __init__(
        self, parent: builtins.object = ..., data: builtins.object = ...
    ) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def __contains__(self, a: object) -> bool: ...
    def find(
        self,
        sub: builtins.object,
        start: builtins.object = ...,
        end: builtins.object = ...,
    ) -> _SageObject: ...
    def rfind(
        self,
        sub: builtins.object,
        start: builtins.object = ...,
        end: builtins.object = ...,
    ) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def length(self) -> _SageObject: ...
    def __getitem__(self, key: builtins.object) -> _SageObject: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def number_of_letter_occurrences(self, letter: builtins.object) -> _SageObject: ...
    def split(
        self, sep: builtins.object = ..., maxsplit: builtins.object = ...
    ) -> _SageObject: ...
    def partition(self, sep: builtins.object) -> _SageObject: ...
    def is_suffix(self, other: builtins.object) -> builtins.bool: ...
    def has_suffix(self, other: builtins.object) -> builtins.bool: ...
    def is_prefix(self, other: builtins.object) -> builtins.bool: ...
    def has_prefix(self, other: builtins.object) -> builtins.bool: ...

class WordDatatype_tuple:
    def __init__(
        self, parent: builtins.object = ..., data: builtins.object = ...
    ) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def length(self) -> _SageObject: ...
    def __contains__(self, a: object) -> bool: ...
    def __getitem__(self, key: builtins.object) -> _SageObject: ...
    def __mul__(self, other: builtins.object) -> Self: ...
