from sage.structure.sage_object import SageObject
from typing import overload, TYPE_CHECKING
if TYPE_CHECKING:
    import sage.structure.parent
    import collections.abc








class Word_class(SageObject):
    def parent(self) -> 'sage.structure.parent.Parent': ...
    def string_rep(self) -> str: ...
    def length(self) -> int | object: ...
    def is_finite(self) -> bool: ...
    def longest_common_prefix(self, other: object, length: int | None = ...) -> 'sage.combinat.words.word.Word_class': ...
    def longest_periodic_prefix(self, period: int = ...) -> 'sage.combinat.words.word.Word_class': ...
    def is_empty(self) -> bool: ...
    def to_integer_word(self) -> 'sage.combinat.words.word.Word_class': ...
    def lex_less(self, other: object) -> bool: ...
    def lex_greater(self, other: object) -> bool: ...
    def apply_morphism(self, morphism: object) -> 'sage.combinat.words.word.Word_class': ...
    def delta(self) -> 'sage.combinat.words.word.Word_class': ...
    def iterated_right_palindromic_closure(self, f: object, algorithm: str = ...) -> 'sage.combinat.words.word.Word_class': ...
    def prefixes_iterator(self, max_length: int | None = ...) -> 'collections.abc.Iterator'['sage.combinat.words.word.Word_class']: ...
    def palindrome_prefixes_iterator(self, max_length: int | None = ...) -> 'collections.abc.Iterator'['sage.combinat.words.word.Word_class']: ...
    def partial_sums(self, start: int | None = ..., mod: int | None = ...) -> 'sage.combinat.words.word.Word_class': ...
    def finite_differences(self, mod: int | None = ...) -> 'sage.combinat.words.word.Word_class': ...
    def sum_digits(self, base: int = ..., mod: int | None = ...) -> 'sage.combinat.words.word.Word_class': ...
    def first_occurrence(self, other: object, start: int = ...) -> int | None: ...
    def factor_occurrences_iterator(self, fact: object) -> 'collections.abc.Iterator'[int]: ...
    def return_words_iterator(self, fact: object) -> 'collections.abc.Iterator'['sage.combinat.words.word.Word_class']: ...
    def complete_return_words_iterator(self, fact: object) -> 'collections.abc.Iterator'['sage.combinat.words.word.Word_class']: ...
