# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def chain_poly(positions: builtins.object) -> _SageObject: ...

def moebius_matrix_fast(positions: builtins.object) -> _SageObject: ...

def coxeter_matrix_fast(positions: builtins.object) -> _SageObject: ...
