import builtins

class _SageObject: ...

coxeter_matrix_fast: _SageObject
moebius_matrix_fast: _SageObject

class IncreasingChains:
    def __contains__(self, tup: object) -> bool: ...
    def post_process(self, chain: builtins.object) -> _SageObject: ...
    def children(self, chain: builtins.object) -> _SageObject: ...
