from typing import overload, TYPE_CHECKING, Callable
from sage.graphs.digraph import DiGraph
from sage.rings.integer import Integer

if TYPE_CHECKING:
    from collections.abc import Iterator

class LatticeError(ValueError):
    fail: str
    x: object
    y: object
    def __init__(self, fail: str, x: object, y: object) -> None: ...
    def __str__(self) -> str: ...

class HasseDiagram(DiGraph):
    def _repr_(self) -> str: ...
    def linear_extension(self) -> list[int]: ...
    def linear_extensions(self) -> Iterator[list[int]]: ...
    def greedy_linear_extensions_iterator(self) -> Iterator[list[int]]: ...
    def supergreedy_linear_extensions_iterator(self) -> Iterator[list[int]]: ...
    def is_linear_extension(self, lin_ext: object = ...) -> bool: ...
    def cover_relations_iterator(self) -> Iterator[tuple[int, int]]: ...
    def cover_relations(self) -> list[tuple[int, int]]: ...
    def is_lequal(self, i: object, j: object) -> bool: ...
    def is_less_than(self, x: object, y: object) -> bool: ...
    def is_gequal(self, x: object, y: object) -> bool: ...
    def is_greater_than(self, x: object, y: object) -> bool: ...
    def minimal_elements(self) -> list[int]: ...
    def maximal_elements(self) -> list[int]: ...
    def bottom(self) -> int | None: ...
    def has_bottom(self) -> bool: ...
    def top(self) -> int | None: ...
    def has_top(self) -> bool: ...
    def is_bounded(self) -> bool: ...
    def is_chain(self) -> bool: ...
    def is_antichain_of_poset(self, elms: object) -> bool: ...
    def dual(self) -> HasseDiagram: ...
    def _precompute_intervals(self) -> None: ...
    def interval(self, x: object, y: object) -> list[int]: ...
    def interval_iterator(self, x: int, y: int) -> Iterator[int]: ...
    def open_interval(self, x: int, y: int) -> list[int]: ...
    def rank_function(self) -> Callable[[int], int] | None: ...
    def rank(self, element: object = ...) -> int: ...
    def is_ranked(self) -> bool: ...
    def covers(self, x: object, y: object) -> bool: ...
    def upper_covers_iterator(self, element: object) -> Iterator[int]: ...
    def lower_covers_iterator(self, element: object) -> Iterator[int]: ...
    def cardinality(self) -> int: ...
    def moebius_function(self, i: object, j: object) -> int: ...
    def bottom_moebius_function(self, j: object) -> int: ...
    def moebius_function_matrix(self, algorithm: str = ...): ...
    def _moebius_function_from_matrix(self, i: object, j: object) -> int: ...
    def coxeter_transformation(self, algorithm: str = ...): ...
    def order_filter(self, elements: object) -> list[int]: ...
    def principal_order_filter(self, i: object) -> list[int]: ...
    def order_ideal(self, elements: object) -> list[int]: ...
    def order_ideal_cardinality(self, elements: object) -> Integer: ...
    def principal_order_ideal(self, i: object) -> list[int]: ...
    def lequal_matrix(self, boolean: bool = ...): ...
    def prime_elements(self) -> tuple[list[int], list[int]]: ...
    def meet_matrix(self): ...
    def is_meet_semilattice(self) -> bool: ...
    def join_matrix(self): ...
    def is_join_semilattice(self) -> bool: ...
    def find_nonsemidistributive_elements(self, meet_or_join: str) -> tuple[int, int, int, int] | None: ...
    def vertical_decomposition(self, return_list: bool = ...) -> int | list[int] | None: ...
    def is_complemented(self) -> int | None: ...
    def pseudocomplement(self, element: object) -> int | None: ...
    def orthocomplementations_iterator(self) -> Iterator[list[int]]: ...
