
from sage.combinat.posets.lattices import FiniteLatticePoset
from sage.topology.simplicial_complex import SimplicialComplex

class _SageObject: ...

def hochschild_lattice(self) -> FiniteLatticePoset: ...
def hochschild_fan(self) -> _SageObject: ...
def hochschild_simplicial_complex(self) -> SimplicialComplex: ...
