# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class IncidenceAlgebra:
    def __init__(self, R: builtins.int, P: builtins.int, prefix: builtins.str = ...) -> None: ...
    def reduced_subalgebra(self, prefix: builtins.str = ...) -> _SageObject: ...
    def poset(self) -> _SageObject: ...
    def some_elements(self) -> builtins.list[_SageObject]: ...
    def product_on_basis(self, A: builtins.object, B: builtins.object) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    delta: _SageObject
    def zeta(self) -> _SageObject: ...
    def moebius(self) -> _SageObject: ...
    def __getitem__(self, A: builtins.object) -> _SageObject: ...
    class Element:
        def __call__(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def to_matrix(self) -> _SageObject: ...
        def is_unit(self) -> builtins.bool: ...
        def __invert__(self) -> Self: ...

class ReducedIncidenceAlgebra:
    def __init__(self, I: builtins.int, prefix: builtins.str = ...) -> None: ...
    def poset(self) -> _SageObject: ...
    def some_elements(self) -> builtins.list[_SageObject]: ...
    def one_basis(self) -> _SageObject: ...
    def delta(self) -> _SageObject: ...
    def zeta(self) -> _SageObject: ...
    def moebius(self) -> _SageObject: ...
    def lift(self) -> _SageObject: ...
    def __getitem__(self, A: builtins.object) -> _SageObject: ...
    class Element:
        def __call__(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def to_matrix(self) -> _SageObject: ...
        def is_unit(self) -> builtins.bool: ...
        def __invert__(self) -> Self: ...
        def lift(self) -> _SageObject: ...
