from sage.structure.list_clone import ClonableArray
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

class LinearExtensionOfPoset(ClonableArray[object]): ...

class LinearExtensionsOfPoset(UniqueRepresentation, Parent): ...

class LinearExtensionsOfPosetWithHooks(LinearExtensionsOfPoset): ...

class LinearExtensionsOfForest(LinearExtensionsOfPoset): ...

class LinearExtensionsOfMobile(LinearExtensionsOfPoset): ...
