# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BasisAbstract:
    def __getitem__(self, x: builtins.object) -> _SageObject: ...

class MoebiusAlgebra:
    def __init__(self, R: builtins.int, L: builtins.object) -> None: ...
    def a_realization(self) -> _SageObject: ...
    def lattice(self) -> _SageObject: ...
    class E:
        def __init__(self, M: builtins.int, prefix: builtins.str = ...) -> None: ...
        def product_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def one(self) -> _SageObject: ...
    natural: _SageObject
    class I:
        def __init__(self, M: builtins.int, prefix: builtins.str = ...) -> None: ...
        def product_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def one(self) -> _SageObject: ...
        def __getitem__(self, x: builtins.object) -> _SageObject: ...
    idempotent: _SageObject

class QuantumMoebiusAlgebra:
    def __init__(self, L: builtins.object, q: builtins.int = ...) -> None: ...
    def a_realization(self) -> _SageObject: ...
    def lattice(self) -> _SageObject: ...
    class E:
        def __init__(self, M: builtins.int, prefix: builtins.str = ...) -> None: ...
        def product_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def one(self) -> _SageObject: ...
    natural: _SageObject
    class C:
        def __init__(self, M: builtins.int, prefix: builtins.str = ...) -> None: ...
    characteristic_basis: _SageObject
    class KL:
        def __init__(self, M: builtins.int, prefix: builtins.str = ...) -> None: ...
    kazhdan_lusztig: _SageObject

class MoebiusAlgebraBases:
    def super_categories(self) -> _SageObject: ...
    class ParentMethods:
        def product_on_basis(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def one(self) -> _SageObject: ...
    class ElementMethods:
        ...
