from sage.structure.unique_representation import UniqueRepresentation
from sage.structure.parent import Parent
from sage.rings.integer import Integer
from sage.combinat.posets.linear_extensions import LinearExtensionsOfPoset
class FinitePoset(UniqueRepresentation, Parent):
    def cardinality(self) -> Integer: ...
    def linear_extensions(self, facade: bool = ...) -> LinearExtensionsOfPoset: ...
    def moebius_function(self, x: object, y: object) -> Integer: ...
    def rank(self, element: object | None = ...) -> Integer | None: ...
    def is_graded(self) -> bool: ...
    def maximal_chains(self, partial: list[object] | None = ...) -> list[list[object]]: ...
