from collections.abc import (
    Iterator,
)

from sage.combinat.posets.lattices import LatticePoset
from sage.geometry.fan import Fan
from sage.geometry.polyhedron.constructor import Polyhedron

class _SageObject: ...

B: _SageObject
N: _SageObject
BB: _SageObject

def sashes(self) -> Iterator[tuple[str, ...]]: ...
def cover_relations(self) -> Iterator[tuple[str, ...]]: ...
def lattice_of_sashes(self) -> LatticePoset: ...
def pellytope_fan(self) -> Fan: ...
def pellytope(self) -> Polyhedron: ...
