import builtins

from sage.structure.element import Matrix

class _SageObject: ...

class RijndaelGF:
    state_vrs: Matrix

    def __init__(
        self,
        Nb: builtins.object,
        Nk: builtins.object,
        state_chr: builtins.str = ...,
        key_chr: builtins.str = ...,
    ) -> None: ...
    def __call__(
        self,
        text: builtins.object,
        key: builtins.object,
        algorithm: builtins.str = ...,
        format: builtins.str = ...,
    ) -> _SageObject: ...
    def block_length(self) -> _SageObject: ...
    def key_length(self) -> _SageObject: ...
    def number_rounds(self) -> _SageObject: ...
    def encrypt(
        self, plain: builtins.object, key: builtins.object, format: builtins.str = ...
    ) -> _SageObject: ...
    def decrypt(
        self,
        ciphertext: builtins.object,
        key: builtins.object,
        format: builtins.str = ...,
    ) -> _SageObject: ...
    def expand_key(self, key: builtins.object) -> _SageObject: ...
    def expand_key_poly(
        self, row: builtins.object, col: builtins.object, round: builtins.object
    ) -> _SageObject: ...
    def apply_poly(
        self,
        state: builtins.object,
        poly_constr: builtins.object,
        algorithm: builtins.str = ...,
        keys: builtins.object = ...,
        poly_constr_attr: builtins.object = ...,
    ) -> _SageObject: ...
    def compose(
        self,
        f: builtins.object,
        g: builtins.object,
        algorithm: builtins.str = ...,
        f_attr: builtins.object = ...,
        g_attr: builtins.object = ...,
    ) -> _SageObject: ...
    def add_round_key_poly_constr(self) -> _SageObject: ...
    def add_round_key(
        self, state: builtins.object, round_key: builtins.object
    ) -> _SageObject: ...
    def sub_bytes_poly_constr(self) -> _SageObject: ...
    def sub_bytes(
        self, state: builtins.object, algorithm: builtins.str = ...
    ) -> _SageObject: ...
    def mix_columns_poly_constr(self) -> _SageObject: ...
    def mix_columns(
        self, state: builtins.object, algorithm: builtins.str = ...
    ) -> _SageObject: ...
    def shift_rows_poly_constr(self) -> _SageObject: ...
    def shift_rows(
        self, state: builtins.object, algorithm: builtins.str = ...
    ) -> _SageObject: ...

    class Round_Component_Poly_Constr:
        def __init__(
            self,
            polynomial_constr: builtins.object,
            rgf: builtins.object,
            round_component_name: builtins.str = ...,
        ) -> None: ...
        def __call__(
            self,
            row: builtins.object,
            col: builtins.object,
            algorithm: builtins.str = ...,
            **kwargs: builtins.object,
        ) -> _SageObject: ...
