import builtins

class _SageObject: ...

def eval_dist_at_powseries(self, f: builtins.object) -> _SageObject: ...

class BruhatTitsHarmonicCocycleElement:
    def __init__(self, _parent: builtins.object, vec: builtins.object) -> None: ...
    def monomial_coefficients(self, copy: builtins.bool = ...) -> _SageObject: ...
    def print_values(self) -> _SageObject: ...
    def valuation(self) -> _SageObject: ...
    def evaluate(self, e1: builtins.object) -> _SageObject: ...
    def riemann_sum(
        self,
        f: builtins.object,
        center: builtins.int = ...,
        level: builtins.int = ...,
        E: builtins.object = ...,
    ) -> _SageObject: ...
    def modular_form(
        self, z: builtins.object = ..., level: builtins.int = ...
    ) -> _SageObject: ...
    def derivative(
        self,
        z: builtins.object = ...,
        level: builtins.int = ...,
        order: builtins.int = ...,
    ) -> _SageObject: ...

class BruhatTitsHarmonicCocycles:
    Element: _SageObject

    @staticmethod
    def __classcall__(
        cls: builtins.object,
        X: builtins.object,
        k: builtins.int,
        prec: builtins.int = ...,
        basis_matrix: builtins.object = ...,
        base_field: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        X: builtins.object,
        k: builtins.int,
        prec: builtins.int = ...,
        basis_matrix: builtins.object = ...,
        base_field: builtins.object = ...,
    ) -> None: ...
    def monomial_coefficients(self) -> _SageObject: ...
    def base_extend(self, base_ring: builtins.object) -> _SageObject: ...
    def change_ring(self, new_base_ring: builtins.object) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def submodule(
        self, v: builtins.object, check: builtins.bool = ...
    ) -> _SageObject: ...
    def is_simple(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def free_module(self) -> _SageObject: ...
    def character(self) -> _SageObject: ...
    def embed_quaternion(
        self, g: builtins.object, scale: builtins.int = ..., exact: builtins.bool = ...
    ) -> _SageObject: ...
    def basis_matrix(self) -> _SageObject: ...

class pAdicAutomorphicFormElement:
    def __init__(self, parent: builtins.object, vec: builtins.object) -> None: ...
    def __bool__(self) -> builtins.bool: ...
    def __getitem__(self, e1: builtins.object) -> _SageObject: ...
    def evaluate(self, e1: builtins.object) -> _SageObject: ...
    def valuation(self) -> _SageObject: ...
    def integrate(
        self,
        f: builtins.object,
        center: builtins.int = ...,
        level: builtins.int = ...,
        method: builtins.str = ...,
    ) -> _SageObject: ...
    def modular_form(
        self,
        z: builtins.object = ...,
        level: builtins.int = ...,
        method: builtins.str = ...,
    ) -> _SageObject: ...
    def derivative(
        self,
        z: builtins.object = ...,
        level: builtins.int = ...,
        method: builtins.str = ...,
        order: builtins.int = ...,
    ) -> _SageObject: ...
    def coleman(
        self,
        t1: builtins.object,
        t2: builtins.object,
        E: builtins.object = ...,
        method: builtins.str = ...,
        mult: builtins.bool = ...,
    ) -> _SageObject: ...

class pAdicAutomorphicForms:
    Element: _SageObject

    @staticmethod
    def __classcall__(
        cls: builtins.object,
        domain: builtins.object,
        U: builtins.object,
        prec: builtins.int = ...,
        t: builtins.object = ...,
        R: builtins.int = ...,
        overconvergent: builtins.bool = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        domain: builtins.object,
        U: builtins.object,
        prec: builtins.int = ...,
        t: builtins.object = ...,
        R: builtins.int = ...,
        overconvergent: builtins.bool = ...,
    ) -> None: ...
    def prime(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def precision_cap(self) -> _SageObject: ...
    def lift(self, f: builtins.object) -> _SageObject: ...
