# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeAlgebra:
    def __init__(self, R: builtins.int, alphabet: builtins.tuple[_SageObject, ...] = ...) -> None: ...
    def one_basis(self) -> _SageObject: ...
    def product_on_basis(self, w1: builtins.object, w2: builtins.object) -> _SageObject: ...
    def algebra_generators(self) -> _SageObject: ...

Example: _SageObject
