# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FreeCommutativeAdditiveSemigroup:
    def __init__(self, alphabet: builtins.tuple[_SageObject, ...] = ...) -> None: ...
    def summation(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def additive_semigroup_generators(self) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    class Element:
        def __init__(self, parent: builtins.object, iterable: builtins.object) -> None: ...
        def __hash__(self) -> builtins.int: ...

Example: _SageObject
