import builtins
from collections.abc import (
    Iterator as _Iterator,
)

from sage.structure.element import Element

class _SageObject: ...

class AbelianLieAlgebra:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        R: builtins.int,
        n: builtins.int = ...,
        M: builtins.int = ...,
        ambient: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        R: builtins.int,
        n: builtins.int = ...,
        M: builtins.int = ...,
        ambient: builtins.object = ...,
    ) -> None: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def universal_enveloping_algebra(self) -> _SageObject: ...
    def zero(self) -> _SageObject: ...
    def basis_matrix(self) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def subalgebra(self, gens: builtins.object) -> _SageObject: ...
    ideal: _SageObject

    def is_ideal(self, A: builtins.object) -> builtins.bool: ...
    def basis(self) -> _SageObject: ...
    lie_algebra_generators: _SageObject

    def gens(self) -> tuple[Element, ...]: ...
    def module(self) -> _SageObject: ...
    def from_vector(
        self, v: builtins.object, order: builtins.object = ...
    ) -> _SageObject: ...
    def leading_monomials(self) -> _SageObject: ...

    class Element:
        def __init__(self, parent: builtins.object, value: builtins.object) -> None: ...
        def __iter__(self) -> _Iterator[_SageObject]: ...
        def __getitem__(self, i: builtins.int) -> _SageObject: ...
        def lift(self) -> _SageObject: ...
        def to_vector(
            self, order: builtins.object = ..., sparse: builtins.bool = ...
        ) -> _SageObject: ...
        def monomial_coefficients(self, copy: builtins.bool = ...) -> _SageObject: ...

Example: _SageObject
