# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Example:
    def __init__(self) -> None: ...
    def __contains__(self, o: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...

class IsomorphicObjectOfFiniteEnumeratedSet:
    def __init__(self, ambient: builtins.object = ...) -> None: ...
    def ambient(self) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def retract(self, x: builtins.object) -> _SageObject: ...
    def __contains__(self, x: builtins.object) -> builtins.bool: ...
