import builtins

from sage.rings.integer import Integer

class _SageObject: ...

class DihedralGroup:
    n: builtins.int

    def __init__(self, n: builtins.int = ...) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def one(self) -> _SageObject: ...
    def index_set(self) -> tuple[int, int]: ...
    def degrees(self) -> tuple[Integer, Integer]: ...
    def coxeter_matrix(self) -> _SageObject: ...

    class Element:
        wrapped_class: _SageObject

        def has_right_descent(
            self,
            i: builtins.int,
            positive: builtins.bool = ...,
            side: builtins.str = ...,
        ) -> builtins.bool: ...
        def apply_simple_reflection_right(self, i: builtins.int) -> _SageObject: ...

Example: _SageObject
