# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class NonNegativeIntegers:
    def __init__(self) -> None: ...
    def __contains__(self, elt: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __call__(self, elt: builtins.object) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    def next(self, o: builtins.object) -> _SageObject: ...
    Element: _SageObject

Example: _SageObject
