# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LieAlgebraFromAssociative:
    @staticmethod
    def __classcall_private__(cls: builtins.object, gens: builtins.object) -> _SageObject: ...
    def __init__(self, gens: builtins.object) -> None: ...
    def zero(self) -> _SageObject: ...
    def lie_algebra_generators(self) -> _SageObject: ...
    class Element:
        def __eq__(self, rhs: builtins.object) -> builtins.bool: ...
        def __ne__(self, rhs: builtins.object) -> builtins.bool: ...
        def __hash__(self) -> builtins.int: ...
        def __bool__(self) -> builtins.bool: ...
        def __truediv__(self, x: builtins.object, self_on_left: builtins.bool = ...) -> Self: ...
        def __neg__(self) -> Self: ...
        def __getitem__(self, i: builtins.int) -> _SageObject: ...

Example: _SageObject
