# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LeftZeroSemigroup:
    def __init__(self) -> None: ...
    def product(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    def some_elements(self) -> builtins.list[_SageObject]: ...
    class Element:
        def is_idempotent(self) -> builtins.bool: ...

class FreeSemigroup:
    def __init__(self, alphabet: builtins.tuple[_SageObject, ...] = ...) -> None: ...
    def product(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def semigroup_generators(self) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    class Element:
        wrapped_class: _SageObject

class QuotientOfLeftZeroSemigroup:
    def __init__(self, category: builtins.object = ...) -> None: ...
    def ambient(self) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def the_answer(self) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    def some_elements(self) -> builtins.list[_SageObject]: ...
    def retract(self, x: builtins.object) -> _SageObject: ...
    class Element:
        ...

class IncompleteSubquotientSemigroup:
    def __init__(self, category: builtins.object = ...) -> None: ...
    def ambient(self) -> _SageObject: ...
    class Element:
        ...
