# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PrimeNumbers:
    def __init__(self) -> None: ...
    def an_element(self) -> _SageObject: ...
    def __contains__(self, p: builtins.object) -> builtins.bool: ...
    element_class: _SageObject

class PrimeNumbers_Abstract:
    def __init__(self) -> None: ...
    def an_element(self) -> _SageObject: ...
    def next(self, i: builtins.int) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    class Element:
        def is_prime(self) -> builtins.bool: ...
        def next(self) -> _SageObject: ...

class PrimeNumbers_Inherits:
    def __init__(self) -> None: ...
    def __contains__(self, p: builtins.object) -> builtins.bool: ...
    class Element:
        def __init__(self, parent: builtins.object, p: builtins.int) -> None: ...

class PrimeNumbers_Wrapper:
    def __init__(self) -> None: ...
    def __contains__(self, p: builtins.object) -> builtins.bool: ...
    class Element:
        ...

class PrimeNumbers_Facade:
    def __init__(self) -> None: ...
    def __contains__(self, p: builtins.object) -> builtins.bool: ...
    element_class: _SageObject
