# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SubsetAlgebra:
    def __init__(self, R: builtins.int, S: builtins.object) -> None: ...
    def a_realization(self) -> _SageObject: ...
    def base_set(self) -> _SageObject: ...
    def indices(self) -> _SageObject: ...
    def indices_key(self, x: builtins.object) -> _SageObject: ...
    def supsets(self, set: builtins.object) -> _SageObject: ...
    class Bases:
        def super_categories(self) -> _SageObject: ...
        class ParentMethods:
            def from_set(self, *args: builtins.object) -> _SageObject: ...
            def __getitem__(self, s: builtins.object) -> _SageObject: ...
            def one(self) -> _SageObject: ...
    class Fundamental:
        def __init__(self, A: builtins.object) -> None: ...
        def product_on_basis(self, left: builtins.object, right: builtins.object) -> _SageObject: ...
        def one_basis(self) -> _SageObject: ...
        one: _SageObject
    F: _SageObject
    class In:
        def __init__(self, A: builtins.object) -> None: ...
    class Out:
        def __init__(self, A: builtins.object) -> None: ...
