from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class HyperbolicGeodesic(SageObject):
    def _cached_geodesic(self) -> Element: ...
    def _complete(self) -> Element: ...
    def _repr_(self) -> str: ...
    def start(self) -> Element: ...
    def end(self) -> Element: ...
    def endpoints(self) -> Element: ...
    def model(self) -> Element: ...
    def to_model(self, model: Element | int | str | bool | None) -> Element: ...
    def graphics_options(self) -> Element: ...
    def update_graphics(self, update: Element | int | str | bool | None) -> Element: ...
    def is_complete(self) -> bool: ...
    def is_asymptotically_parallel(self, other: Element) -> bool: ...
    def is_ultra_parallel(self, other: Element) -> bool: ...
    def is_parallel(self, other: Element) -> bool: ...
    def ideal_endpoints(self) -> Element: ...
    def complete(self) -> Element: ...
    def reflection_involution(self) -> Element: ...
    def common_perpendicula(self, other: Element) -> Element: ...
    def intersection(self, other: Element) -> Element: ...
    def perpendicular_bisector(self) -> Element: ...
    def midpoint(self) -> Element: ...
    def dist(self, other: Element) -> Element: ...
    def angle(self, other: Element) -> Element: ...
    def length(self) -> Element: ...

class HyperbolicGeodesicUHP(HyperbolicGeodesic):
    def plot(self, boundary: Element | int | str | bool | None) -> Element: ...
    def common_perpendicular(self, other: Element) -> Element: ...
    def _get_B(self) -> Element: ...
    def _to_std_geod(self, p: int) -> Element: ...
    def _crossratio_matrix(self, p1: Element | int | str | bool | None, p2: Element | int | str | bool | None) -> Element: ...

class HyperbolicGeodesicPD(HyperbolicGeodesic):
    ...

class HyperbolicGeodesicKM(HyperbolicGeodesic):
    ...

class HyperbolicGeodesicHM(HyperbolicGeodesic):
    def _plot_vertices(self, points: Element | int | str | bool | None) -> Element: ...
