import builtins
from typing import Self

class _SageObject: ...

class HyperbolicIsometry:
    def __init__(
        self, model: builtins.object, A: builtins.object, check: builtins.bool = ...
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def __pow__(self, n: builtins.int) -> Self: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def matrix(self) -> _SageObject: ...
    def __invert__(self) -> Self: ...
    def is_identity(self) -> builtins.bool: ...
    def model(self) -> _SageObject: ...
    def to_model(self, other: builtins.object) -> _SageObject: ...
    def preserves_orientation(self) -> _SageObject: ...
    def classification(self) -> _SageObject: ...
    def translation_length(self) -> _SageObject: ...
    def axis(self) -> _SageObject: ...
    def fixed_point_set(self) -> _SageObject: ...
    def fixed_geodesic(self) -> _SageObject: ...
    def repelling_fixed_point(self) -> _SageObject: ...
    def attracting_fixed_point(self) -> _SageObject: ...

class HyperbolicIsometryUHP:
    def preserves_orientation(self) -> _SageObject: ...
    def classification(self) -> _SageObject: ...
    def translation_length(self) -> _SageObject: ...
    def fixed_point_set(self) -> _SageObject: ...
    def repelling_fixed_point(self) -> _SageObject: ...
    def attracting_fixed_point(self) -> _SageObject: ...

class HyperbolicIsometryPD:
    def __mul__(self, other: builtins.object) -> Self: ...
    def __pow__(self, n: builtins.int) -> Self: ...
    def preserves_orientation(self) -> _SageObject: ...

class HyperbolicIsometryKM: ...

def moebius_transform(self, z: builtins.object) -> _SageObject: ...
