# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class HyperbolicPoint:
    def __init__(self, model: builtins.object, coordinates: builtins.object, is_boundary: builtins.object, check: builtins.bool = ..., **graphics_options: builtins.object) -> None: ...
    def __rmul__(self, other: builtins.object) -> Self: ...
    def coordinates(self) -> _SageObject: ...
    def model(self) -> _SageObject: ...
    def to_model(self, model: builtins.object) -> _SageObject: ...
    def is_boundary(self) -> builtins.bool: ...
    def update_graphics(self, update: builtins.bool = ..., **options: builtins.object) -> _SageObject: ...
    def graphics_options(self) -> _SageObject: ...
    def symmetry_involution(self) -> _SageObject: ...
    def show(self, boundary: builtins.bool = ..., **options: builtins.object) -> _SageObject: ...

class HyperbolicPointUHP:
    def symmetry_involution(self) -> _SageObject: ...
    def show(self, boundary: builtins.bool = ..., **options: builtins.object) -> _SageObject: ...
