from sage.structure.element import Element
from sage.structure.parent import Parent

class HyperbolicModel(Parent, UniqueRepresentation, BindableClass):
    def _repr_(self) -> str: ...
    def _element_constructor_(self, x: Element, is_boundary: Element | int | str | bool | None) -> Element: ...
    def name(self) -> str: ...
    def short_name(self) -> str: ...
    def is_bounded(self) -> bool: ...
    def is_conformal(self) -> bool: ...
    def is_isometry_group_projective(self) -> bool: ...
    def point_in_model(self, p: int) -> Element: ...
    def point_test(self, p: int) -> Element: ...
    def boundary_point_in_model(self, p: int) -> Element: ...
    def bdry_point_test(self, p: int) -> Element: ...
    def isometry_in_model(self, A: Element | int | str | bool | None) -> Element: ...
    def isometry_test(self, A: Element | int | str | bool | None) -> Element: ...
    def get_point(self, coordinates: Element | int | str | bool | None, is_boundary: Element | int | str | bool | None) -> Element: ...
    def get_geodesic(self, start: Element | int | str | bool | None, end: Element | int | str | bool | None) -> Element: ...
    def get_isometry(self, A: Element | int | str | bool | None) -> Element: ...
    def random_element(self) -> Element: ...
    def random_point(self) -> Element: ...
    def random_geodesic(self) -> Element: ...
    def random_isometry(self, preserve_orientation: Element | int | str | bool | None) -> Element: ...
    def dist(self, a: Element, b: Element) -> Element: ...
    def _dist_points(self, p1: Element | int | str | bool | None, p2: Element | int | str | bool | None) -> Element: ...
    def _dist_geod_point(self, start: Element | int | str | bool | None, end: Element | int | str | bool | None, p: int) -> Element: ...
    def isometry_from_fixed_points(self, repel: Element | int | str | bool | None, attract: Element | int | str | bool | None) -> Element: ...

class HyperbolicModelUHP(HyperbolicModel):
    def _coerce_map_from_(self, X: Element | int | str | bool | None) -> Element: ...
    def get_background_graphic(self) -> Element: ...
    def _moebius_sending(self, w: Element) -> Element: ...

class HyperbolicModelPD(HyperbolicModel):
    ...

class HyperbolicModelKM(HyperbolicModel):
    ...

class HyperbolicModelHM(HyperbolicModel):
    ...

class BindableClass: ...

class UniqueRepresentation: ...
