# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def WeightedProjectiveSpace(weights: builtins.object, R: builtins.int = ..., names: builtins.object = ...) -> _SageObject: ...

class WeightedProjectiveSpace_ring:
    @staticmethod
    def __classcall__(cls: builtins.object, weights: builtins.object, R: builtins.int = ..., names: builtins.object = ...) -> _SageObject: ...
    def __init__(self, weights: builtins.object, R: builtins.int = ..., names: builtins.object = ...) -> None: ...
    def weights(self) -> _SageObject: ...
    def ngens(self) -> _SageObject: ...
    def coordinate_ring(self) -> _SageObject: ...
    def point(self, v: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    def subscheme(self, *_: builtins.object, **__: builtins.object) -> _SageObject: ...
    def curve(self, F: builtins.object) -> _SageObject: ...
