# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def walsh_hadamard(f: builtins.object, ldn: builtins.object) -> _SageObject: ...

def yellow_code(a: builtins.object) -> _SageObject: ...

def reed_muller(f: builtins.object, ldn: builtins.object) -> _SageObject: ...

class BooleanFunction:
    def __cinit__(self, x: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __invert__(self) -> Self: ...
    def __add__(self, other: builtins.object) -> Self: ...
    def __mul__(self, other: builtins.object) -> Self: ...
    def __or__(self, other: builtins.object) -> Self: ...
    def algebraic_normal_form(self) -> _SageObject: ...
    def nvariables(self) -> _SageObject: ...
    def truth_table(self, format: builtins.object = ...) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def walsh_hadamard_transform(self) -> _SageObject: ...
    def absolute_walsh_spectrum(self) -> _SageObject: ...
    def is_balanced(self) -> builtins.bool: ...
    def is_symmetric(self) -> builtins.bool: ...
    def nonlinearity(self) -> _SageObject: ...
    def is_bent(self) -> builtins.bool: ...
    def correlation_immunity(self) -> _SageObject: ...
    def resiliency_order(self) -> _SageObject: ...
    def autocorrelation(self) -> _SageObject: ...
    def absolute_autocorrelation(self) -> _SageObject: ...
    def absolute_indicator(self) -> _SageObject: ...
    def sum_of_square_indicator(self) -> _SageObject: ...
    def annihilator(self, d: builtins.object, dim: builtins.object = ...) -> _SageObject: ...
    def algebraic_immunity(self, annihilator: builtins.object = ...) -> _SageObject: ...
    def algebraic_degree(self) -> _SageObject: ...
    def is_plateaued(self) -> builtins.bool: ...
    def is_linear_structure(self, val: builtins.object) -> builtins.bool: ...
    def has_linear_structure(self) -> builtins.bool: ...
    def linear_structures(self) -> _SageObject: ...
    def derivative(self, u: builtins.object) -> _SageObject: ...
    def __setitem__(self, i: builtins.object, y: builtins.object) -> None: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...

def unpickle_BooleanFunction(bool_list: builtins.object) -> _SageObject: ...

class BooleanFunctionIterator:
    def __init__(self, f: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...

def random_boolean_function(n: builtins.object) -> _SageObject: ...
