# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Cipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...
    def __eq__(self, right: builtins.object) -> builtins.bool: ...
    def key(self) -> _SageObject: ...
    def domain(self) -> _SageObject: ...
    def codomain(self) -> _SageObject: ...

class SymmetricKeyCipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...

class PublicKeyCipher:
    def __init__(self, parent: builtins.object, key: builtins.object, public: builtins.bool = ...) -> None: ...
