import builtins

class _SageObject: ...

class AffineCipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __call__(self, M: builtins.int) -> _SageObject: ...

class HillCipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...
    def __eq__(self, right: object) -> bool: ...
    def __call__(self, M: builtins.int) -> _SageObject: ...
    def inverse(self) -> _SageObject: ...

class ShiftCipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __call__(self, M: builtins.int) -> _SageObject: ...

class SubstitutionCipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...
    def __eq__(self, right: object) -> bool: ...
    def __call__(self, M: builtins.int) -> _SageObject: ...
    def inverse(self) -> _SageObject: ...

class TranspositionCipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...
    def __call__(self, M: builtins.int, mode: builtins.str = ...) -> _SageObject: ...
    def inverse(self) -> _SageObject: ...

class VigenereCipher:
    def __init__(self, parent: builtins.object, key: builtins.object) -> None: ...
    def __call__(self, M: builtins.int, mode: builtins.str = ...) -> _SageObject: ...
    def inverse(self) -> _SageObject: ...
