# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class UniformSampler:
    def __init__(self, lower_bound: builtins.object, upper_bound: builtins.object) -> None: ...
    def __call__(self) -> _SageObject: ...

class UniformPolynomialSampler:
    def __init__(self, P: builtins.int, n: builtins.int, lower_bound: builtins.object, upper_bound: builtins.object) -> None: ...
    def __call__(self) -> _SageObject: ...

class LWE:
    def __init__(self, n: builtins.int, q: builtins.int, D: builtins.object, secret_dist: builtins.str = ..., m: builtins.int = ...) -> None: ...
    def __call__(self) -> _SageObject: ...

class Regev:
    def __init__(self, n: builtins.int, secret_dist: builtins.str = ..., m: builtins.int = ...) -> None: ...

class LindnerPeikert:
    def __init__(self, n: builtins.int, delta: builtins.float = ..., m: builtins.int = ...) -> None: ...

class UniformNoiseLWE:
    def __init__(self, n: builtins.int, instance: builtins.str = ..., m: builtins.int = ...) -> None: ...

class RingLWE:
    def __init__(self, N: builtins.int, q: builtins.int, D: builtins.object, poly: builtins.object = ..., secret_dist: builtins.str = ..., m: builtins.int = ...) -> None: ...
    def __call__(self) -> _SageObject: ...

class RingLindnerPeikert:
    def __init__(self, N: builtins.int, delta: builtins.float = ..., m: builtins.int = ...) -> None: ...

class RingLWEConverter:
    def __init__(self, ringlwe: builtins.object) -> None: ...
    def __call__(self) -> _SageObject: ...

def samples(m: builtins.int, n: builtins.int, lwe: builtins.object, seed: builtins.object = ..., balanced: builtins.bool = ..., **kwds: builtins.object) -> _SageObject: ...

def balance_sample(s: builtins.object, q: builtins.int = ...) -> _SageObject: ...
