import builtins

class _SageObject: ...

def bracken_leander(self) -> _SageObject: ...
def carlet_tang_tang_liao(
    self, c: builtins.object = ..., bf: builtins.object = ...
) -> _SageObject: ...
def gold(self, i: builtins.int) -> _SageObject: ...
def kasami(self, i: builtins.int) -> _SageObject: ...
def niho(self) -> _SageObject: ...
def welch(self) -> _SageObject: ...
def monomial_function(self, e: builtins.object) -> _SageObject: ...
def inversion(self) -> _SageObject: ...
def chi(self) -> _SageObject: ...

DryGASCON256: _SageObject
AES: _SageObject
FlexAEAD: _SageObject
Anubis: _SageObject
ARIA_s2: _SageObject
BelT: _SageObject
Camellia: _SageObject
CMEA: _SageObject
Chiasmus: _SageObject
CLEFIA_S0: _SageObject
CLEFIA_S1: _SageObject
Crypton_0_5: _SageObject
Crypton_1_0_S0: _SageObject
Crypton_1_0_S1: _SageObject
Crypton_1_0_S2: _SageObject
Crypton_1_0_S3: _SageObject
CS_cipher: _SageObject
CSA: _SageObject
CSS: _SageObject
DBlock: _SageObject
E2: _SageObject
Enocoro: _SageObject
Fantomas: _SageObject
FLY: _SageObject
Fox: _SageObject
Iceberg: _SageObject
Iraqi: _SageObject
iScream: _SageObject
Kalyna_pi0: _SageObject
Kalyna_pi1: _SageObject
Kalyna_pi2: _SageObject
Kalyna_pi3: _SageObject
Khazad: _SageObject
Kuznyechik: _SageObject
Kuznechik: _SageObject
Streebog: _SageObject
Stribog: _SageObject
Lilliput_AE: _SageObject
MD2: _SageObject
newDES: _SageObject
Picaro: _SageObject
Safer: _SageObject
Scream: _SageObject
SEED_S0: _SageObject
SEED_S1: _SageObject
SKINNY_8: _SageObject
ForkSkinny_8: _SageObject
Remus_8: _SageObject
Romulus: _SageObject
Skipjack: _SageObject
SNOW_3G_sq: _SageObject
SMS4: _SageObject
Turing: _SageObject
Twofish_p0: _SageObject
Twofish_p1: _SageObject
Whirlpool: _SageObject
Zorro: _SageObject
ZUC_S0: _SageObject
ZUC_S1: _SageObject
WAGE: _SageObject
Fides_6: _SageObject
APN_6: _SageObject
SC2000_6: _SageObject
Ascon: _SageObject
ISAP: _SageObject
DryGASCON128: _SageObject
Fides_5: _SageObject
SC2000_5: _SageObject
Shamash: _SageObject
SYCON: _SageObject
Elephant: _SageObject
KNOT: _SageObject
Pyjamask_4: _SageObject
SATURNIN_0: _SageObject
SATURNIN_1: _SageObject
Spook: _SageObject
Clyde: _SageObject
Shadow: _SageObject
TRIFLE: _SageObject
Yarara: _SageObject
Coral: _SageObject
DES_S1_1: _SageObject
DES_S1_2: _SageObject
DES_S1_3: _SageObject
DES_S1_4: _SageObject
DES_S2_1: _SageObject
DES_S2_2: _SageObject
DES_S2_3: _SageObject
DES_S2_4: _SageObject
DES_S3_1: _SageObject
DES_S3_2: _SageObject
DES_S3_3: _SageObject
DES_S3_4: _SageObject
DES_S4_1: _SageObject
DES_S4_2: _SageObject
DES_S4_3: _SageObject
DES_S4_4: _SageObject
DES_S5_1: _SageObject
DES_S5_2: _SageObject
DES_S5_3: _SageObject
DES_S5_4: _SageObject
DES_S6_1: _SageObject
DES_S6_2: _SageObject
DES_S6_3: _SageObject
DES_S6_4: _SageObject
DES_S7_1: _SageObject
DES_S7_2: _SageObject
DES_S7_3: _SageObject
DES_S7_4: _SageObject
DES_S8_1: _SageObject
DES_S8_2: _SageObject
DES_S8_3: _SageObject
DES_S8_4: _SageObject
Lucifer_S0: _SageObject
Lucifer_S1: _SageObject
GOST_1: _SageObject
GOST_2: _SageObject
GOST_3: _SageObject
GOST_4: _SageObject
GOST_5: _SageObject
GOST_6: _SageObject
GOST_7: _SageObject
GOST_8: _SageObject
GOST2_1: _SageObject
GOST2_2: _SageObject
Magma_1: _SageObject
Magma_2: _SageObject
Magma_3: _SageObject
Magma_4: _SageObject
Magma_5: _SageObject
Magma_6: _SageObject
Magma_7: _SageObject
Magma_8: _SageObject
GOST_IETF_1: _SageObject
GOST_IETF_2: _SageObject
GOST_IETF_3: _SageObject
GOST_IETF_4: _SageObject
GOST_IETF_5: _SageObject
GOST_IETF_6: _SageObject
GOST_IETF_7: _SageObject
GOST_IETF_8: _SageObject
Hummingbird_2_S1: _SageObject
Hummingbird_2_S2: _SageObject
Hummingbird_2_S3: _SageObject
Hummingbird_2_S4: _SageObject
LBlock_0: _SageObject
LBlock_1: _SageObject
LBlock_2: _SageObject
LBlock_3: _SageObject
LBlock_4: _SageObject
LBlock_5: _SageObject
LBlock_6: _SageObject
LBlock_7: _SageObject
LBlock_8: _SageObject
LBlock_9: _SageObject
SERPENT_S0: _SageObject
SERPENT_S1: _SageObject
SERPENT_S2: _SageObject
SERPENT_S3: _SageObject
SERPENT_S4: _SageObject
SERPENT_S5: _SageObject
SERPENT_S6: _SageObject
SERPENT_S7: _SageObject
KLEIN: _SageObject
MIBS: _SageObject
Midori_Sb0: _SageObject
MANTIS: _SageObject
WARP: _SageObject
CRAFT: _SageObject
Midori_Sb1: _SageObject
Noekeon: _SageObject
Piccolo: _SageObject
Panda: _SageObject
PRESENT: _SageObject
CiliPadi: _SageObject
PHOTON: _SageObject
ORANGE: _SageObject
GIFT: _SageObject
HYENA: _SageObject
Fountain_1: _SageObject
TGIF: _SageObject
Fountain_2: _SageObject
Fountain_3: _SageObject
Fountain_4: _SageObject
Pride: _SageObject
PRINCE: _SageObject
Prost: _SageObject
Qarma_sigma0: _SageObject
Qarma_sigma1: _SageObject
Qameleon: _SageObject
Qarma_sigma2: _SageObject
REC_0: _SageObject
Rectangle: _SageObject
SC2000_4: _SageObject
SKINNY_4: _SageObject
ForkSkinny_4: _SageObject
Remus_4: _SageObject
TWINE: _SageObject
Luffa_v1: _SageObject
Luffa: _SageObject
BLAKE_1: _SageObject
BLAKE_2: _SageObject
BLAKE_3: _SageObject
BLAKE_4: _SageObject
BLAKE_5: _SageObject
BLAKE_6: _SageObject
BLAKE_7: _SageObject
BLAKE_8: _SageObject
BLAKE_9: _SageObject
JH_S0: _SageObject
JH_S1: _SageObject
SMASH_256_S1: _SageObject
SMASH_256_S2: _SageObject
SMASH_256_S3: _SageObject
Anubis_S0: _SageObject
Anubis_S1: _SageObject
CLEFIA_SS0: _SageObject
CLEFIA_SS1: _SageObject
CLEFIA_SS2: _SageObject
CLEFIA_SS3: _SageObject
Enocoro_S4: _SageObject
Iceberg_S0: _SageObject
Iceberg_S1: _SageObject
Khazad_P: _SageObject
Khazad_Q: _SageObject
Whirlpool_E: _SageObject
Whirlpool_R: _SageObject
CS_cipher_F: _SageObject
CS_cipher_G: _SageObject
Fox_S1: _SageObject
Fox_S2: _SageObject
Fox_S3: _SageObject
Twofish_Q0_T0: _SageObject
Twofish_Q0_T1: _SageObject
Twofish_Q0_T2: _SageObject
Twofish_Q0_T3: _SageObject
Twofish_Q1_T0: _SageObject
Twofish_Q1_T1: _SageObject
Twofish_Q1_T2: _SageObject
Twofish_Q1_T3: _SageObject
Kuznyechik_nu0: _SageObject
Kuznyechik_nu1: _SageObject
Kuznyechik_sigma: _SageObject
Kuznyechik_phi: _SageObject
Optimal_S0: _SageObject
Optimal_S1: _SageObject
Optimal_S2: _SageObject
Optimal_S3: _SageObject
Optimal_S4: _SageObject
Optimal_S5: _SageObject
Optimal_S6: _SageObject
Optimal_S7: _SageObject
Optimal_S8: _SageObject
Optimal_S9: _SageObject
Optimal_S10: _SageObject
Optimal_S11: _SageObject
Optimal_S12: _SageObject
Optimal_S13: _SageObject
Optimal_S14: _SageObject
Optimal_S15: _SageObject
Serpent_type_S0: _SageObject
Serpent_type_S1: _SageObject
Serpent_type_S2: _SageObject
Serpent_type_S3: _SageObject
Serpent_type_S4: _SageObject
Serpent_type_S5: _SageObject
Serpent_type_S6: _SageObject
Serpent_type_S7: _SageObject
Serpent_type_S8: _SageObject
Serpent_type_S9: _SageObject
Serpent_type_S10: _SageObject
Serpent_type_S11: _SageObject
Serpent_type_S12: _SageObject
Serpent_type_S13: _SageObject
Serpent_type_S14: _SageObject
Serpent_type_S15: _SageObject
Serpent_type_S16: _SageObject
Serpent_type_S17: _SageObject
Serpent_type_S18: _SageObject
Serpent_type_S19: _SageObject
Golden_S0: _SageObject
Golden_S1: _SageObject
Golden_S2: _SageObject
Golden_S3: _SageObject
UDCIKMP11: _SageObject
SEA: _SageObject
PRINTcipher: _SageObject
Pyjamask_3: _SageObject
affine_equiv_classes: _SageObject
sboxes: _SageObject
