# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

IntegerModRing: _SageObject
class LFSRCryptosystem:
    def __init__(self, field: builtins.object = ...) -> None: ...
    def __eq__(self, right: builtins.object) -> builtins.bool: ...
    def __call__(self, key: builtins.object) -> _SageObject: ...
    def encoding(self, M: builtins.int) -> _SageObject: ...

class ShrinkingGeneratorCryptosystem:
    def __init__(self, field: builtins.object = ...) -> None: ...
    def __call__(self, key: builtins.object) -> _SageObject: ...
    def encoding(self, M: builtins.int) -> _SageObject: ...

def blum_blum_shub(length: builtins.int, seed: builtins.object = ..., p: builtins.int = ..., q: builtins.int = ..., lbound: builtins.object = ..., ubound: builtins.object = ..., ntries: builtins.int = ...) -> _SageObject: ...
