import builtins

class _SageObject: ...

def ascii_integer(self) -> _SageObject: ...
def ascii_to_bin(self) -> _SageObject: ...
def bin_to_ascii(self) -> _SageObject: ...
def has_blum_prime(self, ubound: builtins.object) -> bool: ...
def is_blum_prime(self) -> builtins.bool: ...
def least_significant_bits(self, k: builtins.int) -> _SageObject: ...
def random_blum_prime(
    self, ubound: builtins.object, ntries: builtins.int = ...
) -> _SageObject: ...
