# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

SAGE_EXTENSION: _SageObject
class SageIpythonConfiguration:
    def colors(self) -> _SageObject: ...
    def simple_prompt(self) -> _SageObject: ...
    def term_title(self) -> _SageObject: ...
    def default(self) -> _SageObject: ...
    def copy(self) -> _SageObject: ...

sage_ipython_config: _SageObject
