# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def preparser(on: builtins.bool = ...) -> _SageObject: ...

class SageShellOverride:
    def show_usage(self) -> _SageObject: ...
    def system_raw(self, cmd: builtins.object) -> _SageObject: ...

class SageNotebookInteractiveShell:
    def init_display_formatter(self) -> _SageObject: ...

class SageTerminalInteractiveShell:
    def init_display_formatter(self) -> _SageObject: ...
    def prompt_for_code(self) -> _SageObject: ...

class SageTestShell:
    def init_display_formatter(self) -> _SageObject: ...
    def quit(self) -> _SageObject: ...
    def run_cell(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def SagePreparseTransformer(lines: builtins.object) -> _SageObject: ...

SagePromptTransformer: _SageObject
class logstr:
    ...

class InterfaceShellTransformer:
    priority: _SageObject
    def __init__(self, *args: builtins.object, **kwds: builtins.object) -> None: ...
    def preparse_imports_from_sage(self, line: builtins.object) -> _SageObject: ...
    def transform(self, line: builtins.object, continue_prompt: builtins.object) -> _SageObject: ...

def interface_shell_embed(interface: builtins.object) -> _SageObject: ...

def get_test_shell() -> _SageObject: ...

class SageCrashHandler:
    def __init__(self, app: builtins.object) -> None: ...

class SageTerminalApp:
    name: _SageObject
    crash_handler_class: _SageObject
    test_shell: _SageObject
    shell_class: _SageObject
    def load_config_file(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def init_shell(self) -> _SageObject: ...
