# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SageMagics:
    def crun(self, s: builtins.object) -> _SageObject: ...
    def runfile(self, s: builtins.object) -> _SageObject: ...
    def attach(self, s: builtins.object) -> _SageObject: ...
    def iload(self, args: builtins.object) -> _SageObject: ...
    def display(self, args: builtins.object) -> _SageObject: ...
    def cython(self, line: builtins.object, cell: builtins.object) -> _SageObject: ...
    def fortran(self, line: builtins.object, cell: builtins.object) -> _SageObject: ...

class SageCustomizations:
    def __init__(self, shell: builtins.object = ...) -> None: ...
    def register_interface_magics(self) -> _SageObject: ...
    @staticmethod
    def all_globals() -> _SageObject: ...
    def init_environment(self) -> _SageObject: ...
    def run_init(self) -> _SageObject: ...
    def init_inspector(self) -> _SageObject: ...
    def init_line_transforms(self) -> _SageObject: ...

class SageJupyterCustomizations:
    @staticmethod
    def all_globals() -> _SageObject: ...

def load_ipython_extension(ip: builtins.object) -> _SageObject: ...
