# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SagePrompts:
    def in_prompt_tokens(self, cli: builtins.object = ...) -> _SageObject: ...
    def continuation_prompt_tokens(self, cli: builtins.object = ..., width: builtins.object = ...) -> _SageObject: ...
    def rewrite_prompt_tokens(self) -> _SageObject: ...
    def out_prompt_tokens(self) -> _SageObject: ...

class InterfacePrompts:
    def __init__(self, interface_name: builtins.str) -> None: ...
    def in_prompt_tokens(self, cli: builtins.object = ...) -> _SageObject: ...
    def continuation_prompt_tokens(self, cli: builtins.object = ..., width: builtins.object = ...) -> _SageObject: ...
    def rewrite_prompt_tokens(self) -> _SageObject: ...
    def out_prompt_tokens(self) -> _SageObject: ...

class DebugPrompts:
    def in_prompt_tokens(self, cli: builtins.object = ...) -> _SageObject: ...
    def continuation_prompt_tokens(self, cli: builtins.object = ..., width: builtins.object = ...) -> _SageObject: ...
    def rewrite_prompt_tokens(self) -> _SageObject: ...
    def out_prompt_tokens(self) -> _SageObject: ...
