import builtins

class _SageObject: ...

user_globals: _SageObject

def get_globals(self) -> _SageObject: ...
def set_globals(self) -> None: ...
def initialize_globals(self, g: builtins.object = ...) -> _SageObject: ...
def get_global(self) -> _SageObject: ...
def set_global(self, value: builtins.object) -> _SageObject: ...
