# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

user_globals: _SageObject
def get_globals() -> _SageObject: ...

def set_globals(g: builtins.dict[_SageObject, _SageObject]) -> None: ...

def initialize_globals(all: builtins.object, g: builtins.object = ...) -> _SageObject: ...

def get_global(name: builtins.str) -> _SageObject: ...

def set_global(name: builtins.str, value: builtins.object) -> _SageObject: ...
