from collections.abc import Iterator

from sage.combinat.cluster_algebra_quiver.quiver import ClusterQuiver
from sage.combinat.cluster_algebra_quiver.quiver_mutation_type import (
    QuiverMutationType_abstract,
)
from sage.graphs.digraph import DiGraph
from sage.matrix.matrix0 import Matrix
from sage.plot.graphics import Graphics
from sage.rings.fraction_field import FractionField_generic
from sage.rings.fraction_field_element import FractionFieldElement
from sage.rings.quotient_ring import QuotientRing_generic
from sage.rings.ring import Field
from sage.structure.element import Element, Vector
from sage.structure.sage_object import SageObject

class ClusterSeed(SageObject):
    def __init__(
        self,
        data: Matrix | ClusterQuiver | list[object] | dict[object, object] | None,
        frozen: list[int] | None = ...,
        is_principal: bool = ...,
        user_labels: list[object] | None = ...,
        user_labels_prefix: str = ...,
    ) -> None: ...
    def use_c_vectors(self, use: bool = ..., bot_is_c: bool = ..., force: bool = ...) -> None: ...
    def use_g_vectors(self, use: bool = ..., force: bool = ...) -> None: ...
    def use_d_vectors(self, use: bool = ..., force: bool = ...) -> None: ...
    def use_fpolys(
        self,
        use: bool = ...,
        user_labels: list[object] | None = ...,
        user_labels_prefix: str | None = ...,
    ) -> None: ...
    def track_mutations(self, use: bool = ...) -> None: ...
    def set_c_matrix(self, data: Matrix) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def plot(
        self,
        circular: bool = ...,
        mark: int | None = ...,
        save_pos: bool = ...,
        force_c: bool = ...,
        with_greens: bool = ...,
        add_labels: bool = ...,
    ) -> Graphics: ...
    def show(
        self,
        fig_size: float = ...,
        circular: bool = ...,
        mark: int | None = ...,
        save_pos: bool = ...,
        force_c: bool = ...,
        with_greens: bool = ...,
        add_labels: bool = ...,
    ) -> None: ...
    def interact(self, fig_size: float = ..., circular: bool = ...) -> None: ...
    def save_image(
        self, filename: str, circular: bool = ..., mark: int | None = ..., save_pos: bool = ...
    ) -> None: ...
    def b_matrix(self) -> Matrix: ...
    def ground_field(self) -> Field: ...
    def x(self, k: int) -> ClusterVariable: ...
    def y(self, k: int) -> ClusterVariable: ...
    def n(self) -> int: ...
    def m(self) -> int: ...
    def free_vertices(self) -> list[int]: ...
    def frozen_vertices(self) -> list[int]: ...
    def mutations(self) -> list[int]: ...
    def cluster_variable(self, k: int) -> ClusterVariable: ...
    def cluster(self) -> list[ClusterVariable]: ...
    def f_polynomial(self, k: int) -> Element: ...
    def f_polynomials(self) -> list[Element]: ...
    def g_vector(self, k: int) -> tuple[int, ...]: ...
    def g_matrix(self, show_warnings: bool = ...) -> Matrix: ...
    def c_vector(self, k: int) -> tuple[int, ...]: ...
    def c_matrix(self, show_warnings: bool = ...) -> Matrix: ...
    def d_vector(self, k: int) -> Vector: ...
    def d_matrix(self, show_warnings: bool = ...) -> Matrix: ...
    def coefficient(self, k: int) -> ClusterVariable: ...
    def coefficients(self) -> list[ClusterVariable]: ...
    def quiver(self) -> ClusterQuiver: ...
    def is_acyclic(self) -> bool: ...
    def is_bipartite(self, return_bipartition: bool = ...) -> bool: ...
    def green_vertices(self) -> list[int]: ...
    def first_green_vertex(self) -> int | None: ...
    def red_vertices(self) -> list[int]: ...
    def first_red_vertex(self) -> int | None: ...
    def urban_renewals(self, return_first: bool = ...) -> list[int] | int | None: ...
    def first_urban_renewal(self) -> int | None: ...
    def highest_degree_denominator(self, filter: list[ClusterVariable] | None = ...) -> int | None: ...
    def smallest_c_vector(self) -> int | None: ...
    def most_decreased_edge_after_mutation(self) -> int | None: ...
    def most_decreased_denominator_after_mutation(self) -> int | None: ...
    def mutate(
        self,
        sequence: int | list[int] | str | ClusterSeed,
        inplace: bool = ...,
        input_type: str | None = ...,
    ) -> ClusterSeed: ...
    def cluster_index(self, cluster_str: ClusterVariable) -> int | None: ...
    def mutation_sequence(
        self,
        sequence: int | list[int] | str,
        show_sequence: bool = ...,
        fig_size: float = ...,
        return_output: str = ...,
    ) -> list[ClusterSeed] | list[Matrix] | ClusterVariable: ...
    def mutation_analysis(
        self, options: list[str] = ..., filter: list[ClusterVariable] | None = ...
    ) -> dict[str, object]: ...
    def exchangeable_part(self) -> ClusterSeed: ...
    def universal_extension(self) -> ClusterSeed: ...
    def principal_extension(self) -> ClusterSeed: ...
    def reorient(self, data: int | list[int] | tuple[int, int]) -> None: ...
    def set_cluster(self, cluster: ClusterVariable | list[ClusterVariable], force: bool = ...) -> None: ...
    def reset_cluster(self) -> None: ...
    def reset_coefficients(self) -> None: ...
    def mutation_class_iter(
        self,
        depth: int = ...,
        show_depth: bool = ...,
        return_paths: bool = ...,
        up_to_equivalence: bool = ...,
        only_sink_source: bool = ...,
    ) -> Iterator[ClusterSeed] | Iterator[tuple[ClusterSeed, list[int]]]: ...
    def mutation_class(
        self,
        depth: int = ...,
        show_depth: bool = ...,
        return_paths: bool = ...,
        up_to_equivalence: bool = ...,
        only_sink_source: bool = ...,
    ) -> list[ClusterSeed] | list[tuple[ClusterSeed, list[int]]]: ...
    def cluster_class_iter(
        self, depth: int = ..., show_depth: bool = ..., up_to_equivalence: bool = ...
    ) -> Iterator[ClusterVariable]: ...
    def cluster_class(
        self, depth: int = ..., show_depth: bool = ..., up_to_equivalence: bool = ...
    ) -> list[ClusterVariable]: ...
    def b_matrix_class_iter(
        self, depth: int = ..., up_to_equivalence: bool = ...
    ) -> Iterator[Matrix]: ...
    def b_matrix_class(self, depth: int = ..., up_to_equivalence: bool = ...) -> list[Matrix]: ...
    def variable_class_iter(
        self, depth: int = ..., ignore_bipartite_belt: bool = ...
    ) -> Iterator[ClusterVariable]: ...
    def variable_class(
        self, depth: int = ..., ignore_bipartite_belt: bool = ...
    ) -> list[ClusterVariable]: ...
    def is_finite(self) -> bool: ...
    def is_mutation_finite(
        self, nr_of_checks: int | None = ..., return_path: bool = ...
    ) -> bool | tuple[bool, list[int]]: ...
    def mutation_type(self) -> QuiverMutationType_abstract: ...
    def greedy(
        self, a1: ClusterVariable, a2: ClusterVariable, algorithm: str = ...
    ) -> list[ClusterVariable]: ...
    def oriented_exchange_graph(self) -> DiGraph: ...
    def find_upper_bound(self, verbose: bool = ...) -> QuotientRing_generic: ...
    def get_upper_cluster_algebra_element(self, a: Vector) -> Element: ...
    def LLM_gen_set(self, size_limit: int = ...) -> list[Vector]: ...

def coeff_recurs(
    p: int, q: int, a1: Element, a2: Element, b: Element, c: Element
) -> int: ...

def PathSubset(n: int, m: int) -> set[tuple[int, ...]]: ...

def SetToPath(T: set[int]) -> list[int]: ...

def is_LeeLiZel_allowable(
    T: set[tuple[int, ...]], n: int, m: int, b: int, c: int
) -> bool: ...

def get_green_vertices(C: Matrix) -> list[int]: ...

def get_red_vertices(C: Matrix) -> list[int]: ...

class ClusterVariable(FractionFieldElement):
    def __init__(
        self,
        parent: FractionField_generic,
        numerator: Element,
        denominator: Element,
        coerce: bool = ...,
        reduce: bool = ...,
        mutation_type: QuiverMutationType_abstract | None = ...,
        variable_type: str | None = ...,
        xdim: int = ...,
    ) -> None: ...
    def almost_positive_root(self) -> Vector: ...
