# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ClusterSeed:
    def __init__(self, data: builtins.object, frozen: builtins.object = ..., is_principal: builtins.bool = ..., user_labels: builtins.object = ..., user_labels_prefix: builtins.str = ...) -> None: ...
    def use_c_vectors(self, use: builtins.bool = ..., bot_is_c: builtins.bool = ..., force: builtins.bool = ...) -> _SageObject: ...
    def use_g_vectors(self, use: builtins.bool = ..., force: builtins.bool = ...) -> _SageObject: ...
    def use_d_vectors(self, use: builtins.bool = ..., force: builtins.bool = ...) -> _SageObject: ...
    def use_fpolys(self, use: builtins.bool = ..., user_labels: builtins.object = ..., user_labels_prefix: builtins.object = ...) -> _SageObject: ...
    def track_mutations(self, use: builtins.bool = ...) -> _SageObject: ...
    def set_c_matrix(self, data: builtins.object) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def plot(self, circular: builtins.bool = ..., mark: builtins.object = ..., save_pos: builtins.bool = ..., force_c: builtins.bool = ..., with_greens: builtins.bool = ..., add_labels: builtins.bool = ...) -> _SageObject: ...
    def show(self, fig_size: builtins.int = ..., circular: builtins.bool = ..., mark: builtins.object = ..., save_pos: builtins.bool = ..., force_c: builtins.bool = ..., with_greens: builtins.bool = ..., add_labels: builtins.bool = ...) -> _SageObject: ...
    def interact(self, fig_size: builtins.int = ..., circular: builtins.bool = ...) -> _SageObject: ...
    def save_image(self, filename: builtins.object, circular: builtins.bool = ..., mark: builtins.object = ..., save_pos: builtins.bool = ...) -> _SageObject: ...
    def b_matrix(self) -> _SageObject: ...
    def ground_field(self) -> _SageObject: ...
    def x(self, k: builtins.int) -> _SageObject: ...
    def y(self, k: builtins.int) -> _SageObject: ...
    def n(self) -> _SageObject: ...
    def m(self) -> _SageObject: ...
    def free_vertices(self) -> _SageObject: ...
    def frozen_vertices(self) -> _SageObject: ...
    def mutations(self) -> _SageObject: ...
    def cluster_variable(self, k: builtins.int) -> _SageObject: ...
    def cluster(self) -> _SageObject: ...
    def f_polynomial(self, k: builtins.int) -> _SageObject: ...
    def f_polynomials(self) -> _SageObject: ...
    def g_vector(self, k: builtins.int) -> _SageObject: ...
    def g_matrix(self, show_warnings: builtins.bool = ...) -> _SageObject: ...
    def c_vector(self, k: builtins.int) -> _SageObject: ...
    def c_matrix(self, show_warnings: builtins.bool = ...) -> _SageObject: ...
    def d_vector(self, k: builtins.int) -> _SageObject: ...
    def d_matrix(self, show_warnings: builtins.bool = ...) -> _SageObject: ...
    def coefficient(self, k: builtins.int) -> _SageObject: ...
    def coefficients(self) -> _SageObject: ...
    def quiver(self) -> _SageObject: ...
    def is_acyclic(self) -> builtins.bool: ...
    def is_bipartite(self, return_bipartition: builtins.bool = ...) -> builtins.bool: ...
    def green_vertices(self) -> _SageObject: ...
    def first_green_vertex(self) -> _SageObject: ...
    def red_vertices(self) -> _SageObject: ...
    def first_red_vertex(self) -> _SageObject: ...
    def urban_renewals(self, return_first: builtins.bool = ...) -> _SageObject: ...
    def first_urban_renewal(self) -> _SageObject: ...
    def highest_degree_denominator(self, filter: builtins.object = ...) -> _SageObject: ...
    def smallest_c_vector(self) -> _SageObject: ...
    def most_decreased_edge_after_mutation(self) -> _SageObject: ...
    def most_decreased_denominator_after_mutation(self) -> _SageObject: ...
    def mutate(self, sequence: builtins.object, inplace: builtins.bool = ..., input_type: builtins.object = ...) -> _SageObject: ...
    def cluster_index(self, cluster_str: builtins.object) -> _SageObject: ...
    def mutation_sequence(self, sequence: builtins.object, show_sequence: builtins.bool = ..., fig_size: builtins.float = ..., return_output: builtins.str = ...) -> _SageObject: ...
    def mutation_analysis(self, options: builtins.list[_SageObject] = ..., filter: builtins.object = ...) -> _SageObject: ...
    def exchangeable_part(self) -> _SageObject: ...
    def universal_extension(self) -> _SageObject: ...
    def principal_extension(self) -> _SageObject: ...
    def reorient(self, data: builtins.object) -> _SageObject: ...
    def set_cluster(self, cluster: builtins.object, force: builtins.bool = ...) -> _SageObject: ...
    def reset_cluster(self) -> _SageObject: ...
    def reset_coefficients(self) -> _SageObject: ...
    def mutation_class_iter(self, depth: builtins.object = ..., show_depth: builtins.bool = ..., return_paths: builtins.bool = ..., up_to_equivalence: builtins.bool = ..., only_sink_source: builtins.bool = ...) -> _SageObject: ...
    def mutation_class(self, depth: builtins.object = ..., show_depth: builtins.bool = ..., return_paths: builtins.bool = ..., up_to_equivalence: builtins.bool = ..., only_sink_source: builtins.bool = ...) -> _SageObject: ...
    def cluster_class_iter(self, depth: builtins.object = ..., show_depth: builtins.bool = ..., up_to_equivalence: builtins.bool = ...) -> _SageObject: ...
    def cluster_class(self, depth: builtins.object = ..., show_depth: builtins.bool = ..., up_to_equivalence: builtins.bool = ...) -> _SageObject: ...
    def b_matrix_class_iter(self, depth: builtins.object = ..., up_to_equivalence: builtins.bool = ...) -> _SageObject: ...
    def b_matrix_class(self, depth: builtins.object = ..., up_to_equivalence: builtins.bool = ...) -> _SageObject: ...
    def variable_class_iter(self, depth: builtins.object = ..., ignore_bipartite_belt: builtins.bool = ...) -> _SageObject: ...
    def variable_class(self, depth: builtins.object = ..., ignore_bipartite_belt: builtins.bool = ...) -> _SageObject: ...
    def is_finite(self) -> builtins.bool: ...
    def is_mutation_finite(self, nr_of_checks: builtins.object = ..., return_path: builtins.bool = ...) -> builtins.bool: ...
    def mutation_type(self) -> _SageObject: ...
    def greedy(self, a1: builtins.object, a2: builtins.object, algorithm: builtins.str = ...) -> _SageObject: ...
    def oriented_exchange_graph(self) -> _SageObject: ...
    def find_upper_bound(self, verbose: builtins.bool = ...) -> _SageObject: ...
    def get_upper_cluster_algebra_element(self, a: builtins.object) -> _SageObject: ...
    def LLM_gen_set(self, size_limit: builtins.object = ...) -> _SageObject: ...

def coeff_recurs(p: builtins.int, q: builtins.int, a1: builtins.object, a2: builtins.object, b: builtins.object, c: builtins.object) -> _SageObject: ...

def PathSubset(n: builtins.int, m: builtins.int) -> _SageObject: ...

def SetToPath(T: builtins.object) -> _SageObject: ...

def is_LeeLiZel_allowable(T: builtins.object, n: builtins.int, m: builtins.int, b: builtins.object, c: builtins.object) -> builtins.bool: ...

def get_green_vertices(C: builtins.object) -> builtins.list[builtins.int]: ...

def get_red_vertices(C: builtins.object) -> builtins.list[builtins.int]: ...

class ClusterVariable:
    def __init__(self, parent: builtins.object, numerator: builtins.object, denominator: builtins.object, coerce: builtins.bool = ..., reduce: builtins.bool = ..., mutation_type: builtins.object = ..., variable_type: builtins.object = ..., xdim: builtins.int = ...) -> None: ...
    def almost_positive_root(self) -> _SageObject: ...
