import builtins

class _SageObject: ...

class QuiverMutationTypeFactory:
    def __call__(self, *args: builtins.object) -> _SageObject: ...
    def samples(
        self,
        finite: builtins.object = ...,
        affine: builtins.object = ...,
        elliptic: builtins.object = ...,
        mutation_finite: builtins.object = ...,
    ) -> _SageObject: ...

QuiverMutationType: _SageObject

class QuiverMutationType_abstract:
    def plot(
        self, circular: builtins.bool = ..., directed: builtins.bool = ...
    ) -> _SageObject: ...
    def show(
        self, circular: builtins.bool = ..., directed: builtins.bool = ...
    ) -> _SageObject: ...
    def letter(self) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def b_matrix(self) -> _SageObject: ...
    def standard_quiver(self) -> _SageObject: ...
    def cartan_matrix(self) -> _SageObject: ...
    def is_irreducible(self) -> bool: ...
    def is_mutation_finite(self) -> bool: ...
    def is_simply_laced(self) -> bool: ...
    def is_skew_symmetric(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_affine(self) -> bool: ...
    def is_elliptic(self) -> bool: ...
    def properties(self) -> None: ...

class QuiverMutationType_Irreducible:
    def __init__(
        self, letter: builtins.object, rank: builtins.int, twist: builtins.object = ...
    ) -> None: ...
    def irreducible_components(self) -> _SageObject: ...
    def class_size(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...

class QuiverMutationType_Reducible:
    def __init__(self, *args: builtins.object) -> None: ...
    def irreducible_components(self) -> _SageObject: ...
    def class_size(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...

def save_quiver_data(
    self,
    up_to: builtins.bool = ...,
    types: builtins.str = ...,
    verbose: builtins.bool = ...,
) -> _SageObject: ...
