import builtins

class _SageObject: ...

class FSymBasis_abstract:
    def __init__(self, alg: builtins.object, graded: builtins.bool = ...) -> None: ...
    def some_elements(self) -> _SageObject: ...

class FSymBases:
    def super_categories(self) -> _SageObject: ...

    class ParentMethods:
        def __getitem__(self, key: builtins.object) -> _SageObject: ...
        def basis(self, degree: builtins.int = ...) -> _SageObject: ...
        def one_basis(self) -> _SageObject: ...
        def duality_pairing(
            self, x: builtins.object, y: builtins.object
        ) -> _SageObject: ...
        def duality_pairing_matrix(
            self, basis: builtins.object, degree: builtins.int
        ) -> _SageObject: ...
        def degree_on_basis(self, t: builtins.object) -> _SageObject: ...

    class ElementMethods:
        def duality_pairing(self, other: builtins.object) -> _SageObject: ...

class FreeSymmetricFunctions:
    def __init__(self, base_ring: builtins.object) -> None: ...
    def a_realization(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...

    class Fundamental:
        def dual_basis(self) -> _SageObject: ...
        def product_on_basis(
            self, t1: builtins.object, t2: builtins.object
        ) -> _SageObject: ...
        def coproduct_on_basis(self, t: builtins.object) -> _SageObject: ...

        class Element:
            def to_fqsym(self) -> _SageObject: ...
            def to_symmetric_function(self) -> _SageObject: ...

    G: _SageObject

class FreeSymmetricFunctions_Dual:
    def __init__(self, base_ring: builtins.object) -> None: ...
    def a_realization(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...

    class FundamentalDual:
        def dual_basis(self) -> _SageObject: ...
        def product_on_basis(
            self, t1: builtins.object, t2: builtins.object
        ) -> _SageObject: ...
        def coproduct_on_basis(self, t: builtins.object) -> _SageObject: ...

        class Element:
            def to_quasisymmetric_function(self) -> _SageObject: ...

    F: _SageObject

def standardize(self) -> _SageObject: ...
def ascent_set(self) -> _SageObject: ...
def descent_set(self) -> _SageObject: ...
def descent_composition(self) -> _SageObject: ...
