from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer

class FGP_Element:
    def __init__(self, parent: object, x: FreeModuleElement, check: bool = ...) -> None: ...
    def lift(self) -> FreeModuleElement: ...
    def __neg__(self) -> FGP_Element: ...
    def _add_(self, other: FGP_Element) -> FGP_Element: ...
    def _sub_(self, other: FGP_Element) -> FGP_Element: ...
    def _mul_(self, other: object) -> FGP_Element: ...
    def _rmul_(self, other: object) -> FGP_Element: ...
    def __richcmp__(self, other: FGP_Element, op: int) -> bool: ...
    def __reduce__(self) -> tuple[object, ...]: ...
    def additive_order(self) -> Integer: ...
    def _repr_(self) -> str: ...
