from collections.abc import Iterable
from sage.modules.free_module import FreeModule_generic
from sage.modules.fg_pid.fgp_element import FGP_Element
from sage.modules.fg_pid.fgp_morphism import FGP_Morphism
from sage.structure.element import Element
from sage.rings.commutative_ring import CommutativeRing

class FGP_Module_class:
    element_class: type[FGP_Element]

    def __init__(self, V: FreeModule_generic, W: FreeModule_generic, check: bool = ...) -> None: ...
    def _module_constructor(
        self,
        V: FreeModule_generic,
        W: FreeModule_generic,
        check: bool = ...,
    ) -> FGP_Module_class: ...
    def V(self) -> FreeModule_generic: ...
    def W(self) -> FreeModule_generic: ...
    def base_ring(self) -> CommutativeRing: ...
    def ngens(self) -> int: ...
    def gens(self) -> tuple[FGP_Element, ...]: ...
    def gen(self, i: int) -> FGP_Element: ...
    def invariants(self) -> tuple[int, ...]: ...
    def rank(self) -> int: ...
    def linear_combination_of_smith_form_gens(self, coeffs: Iterable[Element]) -> FGP_Element: ...
    def hom(self, im_gens: Iterable[FGP_Element]) -> FGP_Morphism: ...
    def optimized(self) -> tuple[FGP_Module_class, FGP_Morphism]: ...
    def __truediv__(self, other: FGP_Module_class) -> FGP_Module_class: ...
    def __add__(self, other: FGP_Module_class) -> FGP_Module_class: ...
    def __mul__(self, other: Element) -> FGP_Module_class: ...
    def __rmul__(self, other: Element) -> FGP_Module_class: ...

def FGP_Module(
    V: FreeModule_generic,
    W: FreeModule_generic,
    check: bool = ...,
) -> FGP_Module_class: ...
