from typing import Generic, TypeVar

from sage.categories.morphism import Morphism
from sage.modules.fg_pid.fgp_element import FGP_Element
from sage.modules.fg_pid.fgp_module import FGP_Module_class
from sage.structure.element import RingElement

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

class FGP_Morphism(Morphism[FGP_Element, FGP_Element], Generic[_Scalar]):
    def __init__(self, parent: object, phi: object, check: bool = ...) -> None: ...
    def im_gens(self) -> tuple[FGP_Element, ...]: ...
    def image(self) -> FGP_Module_class[_Scalar]: ...
    def kernel(self) -> FGP_Module_class[_Scalar]: ...
    def inverse_image(
        self,
        submodule: FGP_Module_class[_Scalar],
    ) -> FGP_Module_class[_Scalar]: ...
    def lift(self, x: FGP_Element) -> FGP_Element: ...
    def __call__(self, x: FGP_Element) -> FGP_Element: ...
    def __richcmp__(self, other: FGP_Morphism, op: int) -> bool: ...
    def _repr_(self) -> str: ...

class FGP_Homset_class:
    def __init__(self, X: FGP_Module_class, Y: FGP_Module_class, category: object = ...) -> None: ...
    def __call__(self, x: object, check: bool = ...) -> FGP_Morphism: ...
