from typing import Generic, Self, TypeVar, overload

from sage.modules.free_module_element import FreeModuleElement
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.structure.element import ModuleElement, RingElement
from sage.structure.parent import Parent

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)
_NewScalar = TypeVar("_NewScalar", bound=RingElement)

class FGP_Element(ModuleElement, Generic[_Scalar]):
    def __init__(
        self,
        parent: FGP_Module_class[_Scalar],
        x: FreeModuleElement[_Scalar],
        check: bool = ...,
    ) -> None: ...
    def parent(self) -> FGP_Module_class[_Scalar]: ...
    def lift(self) -> FreeModuleElement[_Scalar]: ...
    def __neg__(self) -> Self: ...
    def _add_(self, other: FGP_Element[_Scalar]) -> Self: ...
    def _sub_(self, other: FGP_Element[_Scalar]) -> Self: ...
    def _rmul_(self, c: _Scalar) -> Self: ...
    def _lmul_(self, s: _Scalar) -> Self: ...
    def _repr_(self) -> str: ...
    @overload
    def __getitem__(self, key: int | Integer) -> _Scalar: ...
    @overload
    def __getitem__(self, key: slice) -> FreeModuleElement[_Scalar]: ...
    def vector(self) -> FreeModuleElement[_Scalar]: ...
    def __hash__(self) -> int: ...
    def _vector_(
        self,
        base_ring: Parent[_NewScalar] | None = ...,
    ) -> FreeModuleElement[_Scalar] | FreeModuleElement[_NewScalar]: ...
    def _richcmp_(self, other: FGP_Element[_Scalar], op: int) -> bool: ...
    def additive_order(self) -> Integer | PlusInfinity: ...
    order = additive_order

from sage.modules.fg_pid.fgp_module import FGP_Module_class
