from typing import Generic, Self, TypeVar

from sage.modules.free_module_element import FreeModuleElement
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.structure.element import ModuleElement, RingElement

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)


class FGP_Element(ModuleElement, Generic[_Scalar]):
    def parent(self) -> FGP_Module_class[_Scalar]: ...
    def lift(self) -> FreeModuleElement[_Scalar]: ...
    def vector(self) -> FreeModuleElement[_Scalar]: ...
    def additive_order(self) -> Integer | PlusInfinity: ...
    order = additive_order
    def is_zero(self) -> bool: ...
    def __neg__(self) -> Self: ...
    def __add__(self, other: FGP_Element[_Scalar]) -> Self: ...
    def __sub__(self, other: FGP_Element[_Scalar]) -> Self: ...
    def __rmul__(self, scalar: _Scalar | int | Integer) -> Self: ...


from sage.modules.fg_pid.fgp_module import FGP_Module_class
