from sage.matrix.matrix0 import Matrix
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

def transvectant(f: AlgebraicForm, g: AlgebraicForm, h: int = 1, scale: str = "default") -> AlgebraicForm: ...

class FormsBase(SageObject):
    def __init__(self, n: int, homogeneous: bool, ring: Ring, variables: tuple[Element, ...]) -> None: ...
    def ring(self) -> Ring: ...
    def variables(self) -> tuple[Element, ...]: ...
    def is_homogeneous(self) -> bool: ...

class AlgebraicForm(FormsBase):
    def __init__(self, n: int, d: int, polynomial: Polynomial, *args: object, **kwds: object) -> None: ...
    def form(self) -> Polynomial: ...
    def homogenized(self, var: str = "h") -> AlgebraicForm: ...
    def coefficients(self) -> tuple[Element, ...]: ...
    def transformed(self, g: object) -> AlgebraicForm: ...

class QuadraticForm(AlgebraicForm):
    def __init__(self, n: int, d: int, polynomial: Polynomial, *args: object) -> None: ...
    @classmethod
    def from_invariants(cls, discriminant: Element, x: object, z: object, *args: object, **kwargs: object) -> QuadraticForm: ...
    def monomials(self) -> tuple[Polynomial, ...]: ...
    def coeffs(self) -> tuple[Element, ...]: ...
    def scaled_coeffs(self) -> tuple[Element, ...]: ...
    def matrix(self) -> Matrix: ...
    def discriminant(self) -> Element: ...
    def invariants(self, type: str = "discriminant") -> tuple[Element, ...]: ...
    def dual(self) -> QuadraticForm: ...
    def as_QuadraticForm(self) -> QuadraticForm: ...

class BinaryQuartic(AlgebraicForm):
    def __init__(self, n: int, d: int, polynomial: Polynomial, *args: object) -> None: ...
    def monomials(self) -> tuple[Polynomial, ...]: ...
    def coeffs(self) -> tuple[Element, ...]: ...
    def scaled_coeffs(self) -> tuple[Element, ...]: ...
    def EisensteinD(self) -> Element: ...
    def EisensteinE(self) -> Element: ...
    def g_covariant(self) -> BinaryQuartic: ...
    def h_covariant(self) -> BinaryQuartic: ...

class BinaryQuintic(AlgebraicForm):
    def __init__(self, n: int, d: int, polynomial: Polynomial, *args: object) -> None: ...
    @classmethod
    def from_invariants(cls, invariants: tuple[Element, ...], x: object, z: object, *args: object, **kwargs: object) -> BinaryQuintic: ...
    def monomials(self) -> tuple[Polynomial, ...]: ...
    def coeffs(self) -> tuple[Element, ...]: ...
    def scaled_coeffs(self) -> tuple[Element, ...]: ...
    def H_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def i_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def T_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def j_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def tau_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def theta_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def alpha_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def beta_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def gamma_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def delta_covariant(self, as_form: bool = False) -> BinaryQuintic | Polynomial: ...
    def A_invariant(self) -> Element: ...
    def B_invariant(self) -> Element: ...
    def C_invariant(self) -> Element: ...
    def R_invariant(self) -> Element: ...
    def invariants(self, type: str = "clebsch") -> tuple[Element, ...]: ...
    def clebsch_invariants(self, as_tuple: bool = False) -> tuple[Element, ...] | Element: ...
    def arithmetic_invariants(self) -> tuple[Element, ...]: ...
    def canonical_form(self, reduce_gcd: bool = False) -> BinaryQuintic: ...

class TernaryQuadratic(QuadraticForm):
    def __init__(self, n: int, d: int, polynomial: Polynomial, *args: object) -> None: ...
    def monomials(self) -> tuple[Polynomial, ...]: ...
    def coeffs(self) -> tuple[Element, ...]: ...
    def scaled_coeffs(self) -> tuple[Element, ...]: ...
    def covariant_conic(self, other: TernaryQuadratic) -> QuadraticForm: ...

class TernaryCubic(AlgebraicForm):
    def __init__(self, n: int, d: int, polynomial: Polynomial, *args: object) -> None: ...
    def monomials(self) -> tuple[Polynomial, ...]: ...
    def coeffs(self) -> tuple[Element, ...]: ...
    def scaled_coeffs(self) -> tuple[Element, ...]: ...
    def S_invariant(self) -> Element: ...
    def T_invariant(self) -> Element: ...
    def polar_conic(self) -> QuadraticForm: ...
    def Hessian(self) -> TernaryCubic: ...
    def Theta_covariant(self) -> TernaryCubic: ...
    def J_covariant(self) -> TernaryCubic: ...
    def syzygy(self, U: Element, S: Element, T: Element, H: TernaryCubic, Theta: TernaryCubic, J: TernaryCubic) -> Polynomial: ...

class SeveralAlgebraicForms(FormsBase):
    def __init__(self, forms: list[AlgebraicForm] | tuple[AlgebraicForm, ...]) -> None: ...
    def n_forms(self) -> int: ...
    def get_form(self, i: int) -> AlgebraicForm: ...
    def homogenized(self, var: str = "h") -> SeveralAlgebraicForms: ...

class TwoAlgebraicForms(SeveralAlgebraicForms):
    def first(self) -> AlgebraicForm: ...
    def second(self) -> AlgebraicForm: ...

class TwoTernaryQuadratics(TwoAlgebraicForms):
    def Delta_invariant(self) -> Element: ...
    def Delta_prime_invariant(self) -> Element: ...
    def Theta_invariant(self) -> Element: ...
    def Theta_prime_invariant(self) -> Element: ...
    def F_covariant(self) -> TernaryQuadratic: ...
    def J_covariant(self) -> TernaryQuadratic: ...
    def syzygy(self, Delta: Element, Theta: Element, Theta_prime: Element, Delta_prime: Element, S: Polynomial, T: Polynomial) -> Polynomial: ...

class TwoQuaternaryQuadratics(TwoAlgebraicForms):
    def Delta_invariant(self) -> Element: ...
    def Delta_prime_invariant(self) -> Element: ...
    def Theta_invariant(self) -> Element: ...
    def Theta_prime_invariant(self) -> Element: ...
    def Phi_invariant(self) -> Element: ...
    def T_covariant(self) -> QuadraticForm: ...
    def T_prime_covariant(self) -> QuadraticForm: ...
    def J_covariant(self) -> QuadraticForm: ...
    def syzygy(self, Delta: Element, Theta: Element, Phi: Element, Theta_prime: Element, Delta_prime: Element, S: Polynomial, T: Polynomial) -> Polynomial: ...

class InvariantTheoryFactory:
    def quadratic_form(self, polynomial: Polynomial, *args: object) -> QuadraticForm: ...
    def inhomogeneous_quadratic_form(self, polynomial: Polynomial, *args: object) -> QuadraticForm: ...
    def binary_quadratic(self, quadratic: Polynomial, *args: object) -> QuadraticForm: ...
    def quaternary_quadratic(self, quadratic: Polynomial, *args: object) -> QuadraticForm: ...
    def binary_quartic(self, quartic: Polynomial, *args: object, **kwds: object) -> BinaryQuartic: ...
    def binary_quintic(self, quintic: Polynomial, *args: object, **kwds: object) -> BinaryQuintic: ...
    def binary_form_from_invariants(self, degree: int, invariants: tuple[Element, ...], variables: object = None, as_form: bool = ...) -> BinaryQuintic | Polynomial: ...
    def ternary_quadratic(self, quadratic: Polynomial, *args: object, **kwds: object) -> TernaryQuadratic: ...
    def ternary_cubic(self, cubic: Polynomial, *args: object, **kwds: object) -> TernaryCubic: ...
    def ternary_biquadratic(self, quadratic1: Polynomial, quadratic2: Polynomial, *args: object, **kwds: object) -> TwoTernaryQuadratics: ...
    def quaternary_biquadratic(self, quadratic1: Polynomial, quadratic2: Polynomial, *args: object, **kwds: object) -> TwoQuaternaryQuadratics: ...
