from sage.rings.ring import Ring
from sage.structure.element import Element

def binary_quadratic_coefficients_from_invariants(discriminant: Element, invariant_choice: str = "default") -> tuple[Element, ...]: ...
def binary_cubic_coefficients_from_invariants(discriminant: Element, invariant_choice: str = "default") -> tuple[Element, ...]: ...
def binary_quintic_coefficients_from_invariants(invariants: tuple[Element, ...], K: Ring | None = None, invariant_choice: str = "default", scaling: str = "normalized") -> tuple[Element, ...]: ...
