from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sage.matrix.matrix_dense import Matrix
    from sage.rings.ring import CommutativeRing
    from sage.categories.category import Category
    from .module import HeckeModule_free_module

class AmbientHeckeModule(HeckeModule_free_module):
    """An ambient Hecke module."""

    def __init__(
        self,
        base_ring: CommutativeRing,
        rank: int,
        level: int,
        weight: int,
        category: Category | None = None,
    ) -> None: ...
    def __add__(self, other: HeckeModule_free_module) -> AmbientHeckeModule: ...
    def rank(self) -> int: ...
    def complement(self) -> HeckeModule_free_module: ...
    def decomposition_matrix(self) -> Matrix: ...
    def decomposition_matrix_inverse(self) -> Matrix: ...
    def degeneracy_map(self, codomain, t: int = 1): ...
    def dual_free_module(self): ...
    def fcp(self, n: int, var: str = 'x'): ...
    def free_module(self): ...
    def hecke_bound(self) -> int: ...
    def hecke_module_of_level(self, level: int): ...
    def hecke_images(self, i: int, v: list) -> Matrix: ...
    def intersection(self, other: HeckeModule_free_module) -> HeckeModule_free_module: ...
    def is_ambient(self) -> bool: ...
    def is_full_hecke_module(self, compute: bool = True) -> bool: ...
    def is_new(self, p: int | None = None) -> bool: ...
    def is_old(self, p: int | None = None) -> bool: ...
    def is_submodule(self, V: HeckeModule_free_module) -> bool: ...
    def linear_combination_of_basis(self, v): ...
    def new_submodule(self, p: int | None = None) -> HeckeModule_free_module: ...
    def nonembedded_free_module(self): ...
    def old_submodule(self, p: int | None = None) -> HeckeModule_free_module: ...
    def submodule(self, M, Mdual=None, check: bool = True) -> HeckeModule_free_module: ...
    def _submodule_class(self): ...
    def submodule_from_nonembedded_module(
        self, V, Vdual=None, check: bool = True
    ) -> HeckeModule_free_module: ...
    def submodule_generated_by_images(self, M) -> HeckeModule_free_module: ...
    def _degeneracy_raising_matrix(self, codomain): ...
    def _degeneracy_lowering_matrix(self, codomain, t: int): ...
    def _hecke_image_of_ith_basis_element(self, n: int, i: int): ...
    def _set_dual_free_module(self, V) -> None: ...
    def ambient_hecke_module(self) -> AmbientHeckeModule: ...
