
from typing import overload

from sage.matrix.matrix import Matrix
from sage.modular.hecke.element import HeckeModuleElement
from sage.modular.hecke.morphism import HeckeModuleMorphism_matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.structure.element import Element
from .module import HeckeModule_free_module
from .ambient_module import AmbientHeckeModule

class HeckeSubmodule(HeckeModule_free_module):
    def __init__(
        self,
        ambient: AmbientHeckeModule,
        submodule: FreeModule_generic,
        dual_free_module: FreeModule_generic | None = None,
        check: bool = True,
    ) -> None: ...
    def __add__(self, other: HeckeModule_free_module) -> HeckeSubmodule: ...
    def __richcmp__(self, other: HeckeSubmodule, op: int) -> bool: ...
    def _element_constructor_(self, x: HeckeModuleElement | FreeModuleElement, check: bool = True) -> HeckeModuleElement: ...
    def ambient_hecke_module(self) -> AmbientHeckeModule: ...
    def ambient(self) -> AmbientHeckeModule: ...
    def complement(self, bound: int | None = None) -> HeckeSubmodule: ...
    def degeneracy_map(self, level: int, t: int = 1) -> HeckeModuleMorphism_matrix: ...
    def dual_free_module(
        self, bound: int | None = None, anemic: bool = True, use_star: bool = True
    ) -> FreeModule_generic: ...
    def free_module(self) -> FreeModule_generic: ...
    def module(self) -> FreeModule_generic: ...
    def intersection(self, other: HeckeModule_free_module) -> HeckeSubmodule: ...
    def is_ambient(self) -> bool: ...
    def is_new(self, p: int | None = None) -> bool: ...
    def is_old(self, p: int | None = None) -> bool: ...
    @overload
    def is_submodule(self, V: HeckeModule_free_module) -> bool: ...
    @overload
    def is_submodule(self, other: object) -> bool: ...
    def linear_combination_of_basis(self, v: list[Element] | FreeModuleElement) -> HeckeModuleElement: ...
    def new_submodule(self, p: int | None = None) -> HeckeSubmodule: ...
    def nonembedded_free_module(self) -> FreeModule_generic: ...
    def old_submodule(self, p: int | None = None) -> HeckeSubmodule: ...
    def rank(self) -> Integer: ...
    @overload
    def submodule(self, M: FreeModule_generic | list[HeckeModuleElement], Mdual: FreeModule_generic | None = None, check: bool = True) -> HeckeSubmodule: ...
    @overload
    def submodule(self, X: object) -> HeckeSubmodule: ...
    def submodule_from_nonembedded_module(
        self, V: FreeModule_generic, Vdual: FreeModule_generic | None = None, check: bool = True
    ) -> HeckeSubmodule: ...
    def hecke_bound(self) -> int: ...
    def _compute_dual_hecke_matrix(self, n: int) -> Matrix: ...
    def _compute_hecke_matrix(self, n: int) -> Matrix: ...
    def _compute_diamond_matrix(self, d: int) -> Matrix: ...
    def _compute_atkin_lehner_matrix(self, d: int) -> Matrix: ...
    def _set_dual_free_module(self, V: FreeModule_generic) -> None: ...
