from collections.abc import Iterable, Sequence
from typing import Generic, Self, TypeVar

from sage.categories.category import Category
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

type NameSpec = str | Sequence[str] | None

def normalize_names(ngens: int | Integer, names: NameSpec) -> tuple[str, ...]: ...
def certify_names(names: NameSpec) -> bool: ...

_ElementT = TypeVar("_ElementT", bound=Element, default=Element)

class CategoryObject(SageObject, Generic[_ElementT]):
    def __init__(
        self,
        category: Category | Sequence[Category] | None = ...,
        base: CategoryObject[Element] | None = ...,
    ) -> None: ...
    def _is_category_initialized(self) -> bool: ...
    def category(self) -> Category: ...
    def categories(self) -> list[Category]: ...
    def _init_category_(self, category: Category | Sequence[Category]) -> None: ...
    def _refine_category_(self, category: Category | Sequence[Category]) -> None: ...
    def base(self) -> CategoryObject[Element] | None: ...
    def base_ring(self) -> CategoryObject[Element] | None: ...
    def variable_names(self) -> tuple[str, ...]: ...
    def variable_name(self) -> str: ...
    def gens_dict(self, *, copy: bool = ...) -> dict[str, _ElementT]: ...
    def gens_dict_recursive(self) -> dict[str, Element]: ...
    def ngens(self) -> int | Integer: ...
    def gen(self, n: int | Integer = ...) -> _ElementT: ...
    def gens(self) -> tuple[_ElementT, ...]: ...
    def objgens(self) -> tuple[Self, tuple[_ElementT, ...]]: ...
    def objgen(self) -> tuple[Self, _ElementT]: ...
    def _first_ngens(self, n: int | Integer) -> tuple[_ElementT, ...]: ...
    def _defining_names(self) -> Iterable[_ElementT]: ...
    def latex_variable_names(self) -> tuple[str, ...]: ...
    def latex_name(self) -> str: ...
