from collections.abc import Iterator

class MonoDictEraser:
    def __init__(self, D: object) -> None: ...
    def __call__(self, r: object) -> None: ...

class TripleDictEraser:
    def __init__(self, D: object) -> None: ...
    def __call__(self, r: object) -> None: ...

class MonoDict[K, V]:
    def __init__(self, data: dict[K, V] | None = None, *, weak_values: bool = False) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, k: K) -> bool: ...
    def __getitem__(self, k: K) -> V: ...
    def __setitem__(self, k: K, value: V) -> None: ...
    def __delitem__(self, k: K) -> None: ...
    def items(self) -> Iterator[tuple[K, V]]: ...
    def copy(self) -> dict[K, V]: ...
    def __reduce__(self) -> tuple[type[MonoDict[K, V]], tuple[dict[K, V]]]: ...

class TripleDict[K1, K2, K3, V]:
    def __init__(self, data: dict[tuple[K1, K2, K3], V] | None = None, *, weak_values: bool = False) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, k: tuple[K1, K2, K3]) -> bool: ...
    def __getitem__(self, k: tuple[K1, K2, K3]) -> V: ...
    def __setitem__(self, k: tuple[K1, K2, K3], value: V) -> None: ...
    def __delitem__(self, k: tuple[K1, K2, K3]) -> None: ...
    def items(self) -> Iterator[tuple[tuple[K1, K2, K3], V]]: ...
    def copy(self) -> dict[tuple[K1, K2, K3], V]: ...
    def __reduce__(self) -> tuple[type[TripleDict[K1, K2, K3, V]], tuple[dict[tuple[K1, K2, K3], V]]]: ...
