from typing import TypeVar

from sage.structure.parent import ElementConstructorInput
from sage.structure.parent import Parent

_T = TypeVar("_T")

class GenericAction:
    def __init__(self, G: Parent, S: object, is_left: bool, check: bool = True) -> None: ...
    def codomain(self) -> Parent: ...

class ActOnAction(GenericAction):
    def _act_(self, g: object, x: object) -> Parent: ...

class ActedUponAction(GenericAction):
    def _act_(self, g: object, x: object) -> Parent: ...

class ModuleAction:
    def __init__(self, G: Parent, M: Parent, is_left: bool) -> None: ...
    def _repr_name_(self) -> str: ...
    def codomain(self) -> Parent: ...
    def domain(self) -> Parent: ...
    def __invert__(self) -> ModuleAction: ...

class LeftModuleAction(ModuleAction):
    def _act_(self, g: ElementConstructorInput, a: ElementConstructorInput) -> ElementConstructorInput: ...

class RightModuleAction(ModuleAction):
    def _act_(self, g: ElementConstructorInput, a: ElementConstructorInput) -> ElementConstructorInput: ...

class IntegerAction:
    ...

class IntegerMulAction(IntegerAction):
    def _act_(self, nn: int, a: _T) -> _T: ...
    def _repr_name_(self) -> str: ...

class IntegerPowAction(IntegerAction):
    def _act_(self, n: int, a: _T) -> _T: ...
    def _repr_name_(self) -> str: ...

def detect_element_action(X: Parent, Y: object, X_on_left: bool, X_el: object | None = None, Y_el: object | None = None) -> GenericAction | None: ...
def fast_mul(a: _T, n: int) -> _T: ...
def fast_mul_long(a: _T, s: int) -> _T: ...
