from sage.structure.map import Map
from sage.structure.parent import Parent
from sage.structure.element import Element

class DefaultConvertMap_unique(Map):
    def __init__(self, domain: object, codomain: object, category: object | None = ...) -> None: ...
    def domain(self) -> Parent: ...
    def codomain(self) -> Parent: ...
    def _repr_type(self) -> str: ...
    def _call_(self, x: object) -> Element: ...
    def _call_with_args(self, x: object, args: tuple[object, ...] = ..., kwds: dict[str, object] = ...) -> Element: ...
