from collections.abc import Iterator

class MonoDict:
    def __init__(self, data: object | None = None, *, weak_values: bool = False) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, k: object) -> bool: ...
    def __getitem__(self, k: object) -> object: ...
    def __setitem__(self, k: object, value: object) -> None: ...
    def __delitem__(self, k: object) -> None: ...
    def items(self) -> Iterator[tuple[object, object]]: ...
    def copy(self) -> MonoDict: ...
    def __reduce__(self) -> tuple[object, ...]: ...

class TripleDict:
    def __init__(self, data: object | None = None, *, weak_values: bool = False) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, k: object) -> bool: ...
    def __getitem__(self, k: tuple[object, object, object]) -> object: ...
    def __setitem__(self, k: tuple[object, object, object], value: object) -> None: ...
    def __delitem__(self, k: tuple[object, object, object]) -> None: ...
    def items(self) -> Iterator[tuple[tuple[object, object, object], object]]: ...
    def copy(self) -> TripleDict: ...
    def __reduce__(self) -> tuple[object, ...]: ...
