from typing import Protocol

from sage.structure.parent import Parent

class Element(Protocol):
    def parent(self, x: None = None) -> Parent: ...

class ModuleElement(Element, Protocol):
    ...

class ModuleElementWithMutability(ModuleElement, Protocol):
    ...

class MonoidElement(Element, Protocol):
    ...

class MultiplicativeGroupElement(MonoidElement, Protocol):
    ...

class AdditiveGroupElement(ModuleElement, Protocol):
    ...

class RingElement(ModuleElement, Protocol):
    ...

class AlgebraElement(RingElement, Protocol):
    ...

class CommutativeRingElement(RingElement, Protocol):
    ...

class CommutativeAlgebraElement(CommutativeRingElement, Protocol):
    ...

class Expression(CommutativeRingElement, Protocol):
    ...

class FieldElement(CommutativeRingElement, Protocol):
    ...

class InfinityElement(RingElement, Protocol):
    ...

class Matrix(ModuleElement, Protocol):
    ...

def parent(x: object) -> Parent: ...
