from collections.abc import Iterator
from typing import Protocol, Self, TypeVar, overload

from sage.categories.rings import Rings
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.structure.coerce import CoercionModel
from sage.structure.element_wrapper import ElementWrapper as ElementWrapper
from sage.structure.parent import ElementConstructorInput, MembershipInput, Parent

coercion_model: CoercionModel

class Element(Protocol):
    def __init__(self: Self, parent: Parent[Self]) -> None: ...
    def _set_parent(self, parent: Parent) -> None: ...
    def parent(self: Self) -> Parent[Self]: ...
    def base_ring(self) -> Rings.ParentMethods[RingElement]: ...
    def __dir__(self) -> list[str]: ...
    def _repr_(self) -> str: ...
    def __copy__(self) -> Element: ...
    def __pos__(self) -> Element: ...
    def _coeff_repr(self, no_space: bool = ...) -> str: ...
    def _latex_coeff_repr(self) -> str: ...
    def _is_atomic(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def __neg__(self) -> Element: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def _cache_key(self) -> tuple[Parent, str]: ...

class ModuleElement(Element, Protocol):
    def order(self) -> Integer: ...
    def additive_order(self) -> Integer: ...

class ModuleElementWithMutability(ModuleElement, Protocol):
    def __init__(self, parent: Parent, is_immutable: bool = ...) -> None: ...
    def set_immutable(self) -> None: ...
    def is_mutable(self) -> bool: ...
    def is_immutable(self) -> bool: ...

class MonoidElement(Element, Protocol):
    def __bool__(self) -> bool: ...

class MultiplicativeGroupElement(MonoidElement, Protocol): ...
class AdditiveGroupElement(ModuleElement, Protocol): ...

class RingElement(ModuleElement, Protocol):
    def __neg__(self) -> RingElement: ...
    def is_unit(self) -> bool: ...
    def __mul__(self, other: ElementConstructorInput) -> Element: ...
    def __rmul__(self, other: ElementConstructorInput) -> Element: ...
    def __abs__(self) -> Self: ...
    def __lt__(self, other: MembershipInput) -> bool: ...
    def __le__(self, other: MembershipInput) -> bool: ...
    def __gt__(self, other: MembershipInput) -> bool: ...
    def __ge__(self, other: MembershipInput) -> bool: ...
    def is_one(self) -> bool: ...
    def is_nilpotent(self) -> bool: ...
    def is_prime(self) -> bool: ...

class AlgebraElement(RingElement, Protocol): ...
class CommutativeRingElement(RingElement, Protocol): ...
class CommutativeAlgebraElement(CommutativeRingElement, Protocol): ...
class Expression(CommutativeRingElement, Protocol): ...

class IntegralDomainElement(CommutativeRingElement, Protocol):
    def is_nilpotent(self) -> bool: ...

class DedekindDomainElement(IntegralDomainElement, Protocol): ...
class PrincipalIdealDomainElement(DedekindDomainElement, Protocol): ...
class EuclideanDomainElement(PrincipalIdealDomainElement, Protocol): ...

class FieldElement(CommutativeRingElement, Protocol):
    def is_unit(self) -> bool: ...
    def divides(self, other: FieldElement) -> bool: ...

class InfinityElement(RingElement, Protocol): ...

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)
type _List[T] = list[T]

class Vector(ModuleElement, Protocol[_Scalar]):
    def __iter__(self) -> Iterator[_Scalar]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int | Integer) -> _Scalar: ...
    def __neg__(self) -> Vector[_Scalar]: ...
    def __add__(self, other: Vector[_Scalar]) -> Vector[_Scalar]: ...
    def __sub__(self, other: Vector[_Scalar]) -> Vector[_Scalar]: ...
    @overload
    def __mul__(self, other: Matrix[_Scalar]) -> Vector[_Scalar]: ...
    @overload
    def __mul__(self, other: Vector[_Scalar]) -> _Scalar: ...
    @overload
    def __mul__(self, other: int | _Scalar) -> Vector[_Scalar]: ...
    def __rmul__(self, other: int | _Scalar) -> Vector[_Scalar]: ...
    def set_immutable(self) -> None: ...
    def __setitem__(self, i: int | Integer, value: ElementConstructorInput) -> None: ...
    def list(self) -> _List[_Scalar]: ...
    def denominator(self) -> Integer: ...

class Matrix(ModuleElement, Protocol[_Scalar]):
    # element.pyx:3615,3947 owns multiplication and division only. Matrix
    # indexing, dimensions and inversion belong to the matrix0/1/2 layers.
    @overload
    def __mul__(self, other: Matrix[_Scalar]) -> Matrix[_Scalar]: ...
    @overload
    def __mul__(self, other: Vector[_Scalar]) -> Vector[_Scalar]: ...
    @overload
    def __mul__(self, other: int | _Scalar) -> Matrix[_Scalar]: ...
    # Cython exposes the reflected slot from element.pyx's same __mul__ body.
    @overload
    def __rmul__(self, other: Matrix[_Scalar]) -> Matrix[_Scalar]: ...
    @overload
    def __rmul__(self, other: Vector[_Scalar]) -> Vector[_Scalar]: ...
    @overload
    def __rmul__(self, other: int | _Scalar) -> Matrix[_Scalar]: ...
    @overload
    def __truediv__(
        self: Matrix[Integer],
        other: int | Integer,
    ) -> Matrix[Rational]: ...
    @overload
    def __truediv__(
        self,
        other: int | _Scalar | Matrix[_Scalar],
    ) -> Matrix[RingElement]: ...
    def __rtruediv__(self, other: Matrix[_Scalar]) -> Matrix[RingElement]: ...

def parent(x: object) -> Parent: ...
def get_coercion_model() -> CoercionModel: ...
