from collections.abc import Iterator

from sage.structure.element import Element
from sage.structure.parent import Parent

class FormalSum(Element):
    def __init__(self, x: object, parent: Parent | None = None, check: bool = True, reduce: bool = True) -> None: ...
    def __iter__(self) -> Iterator[tuple[object, object]]: ...
    def __getitem__(self, n: int) -> tuple[object, object]: ...
    def __len__(self) -> int: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _richcmp_(self, other: FormalSum, op: int) -> bool: ...
    def _neg_(self) -> FormalSum: ...
    def _add_(self, other: FormalSum) -> FormalSum: ...
    def _lmul_(self, s: object) -> FormalSum: ...
    def _rmul_(self, s: object) -> FormalSum: ...
    def __bool__(self) -> bool: ...
    def reduce(self) -> None: ...

class FormalSums(Parent):
    Element: type[FormalSum]
    def __init__(self, base_ring: Parent) -> None: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(self, x: object, check: bool = True, reduce: bool = True) -> FormalSum: ...
    def _coerce_map_from_(self, X: object) -> bool: ...
    def base_extend(self, R: Parent) -> FormalSums | None: ...
    def _get_action_(self, other: object, op: object, self_is_left: bool) -> None: ...
    def _an_element_(self, check: bool = False, reduce: bool = False) -> FormalSum: ...

formal_sums: FormalSums
