# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class IncreasingArraysPy:
    class Element:
        def check(self) -> _SageObject: ...

def add1_internal(bla: builtins.object) -> _SageObject: ...

def add1_immutable(bla: builtins.object) -> _SageObject: ...

def add1_mutable(bla: builtins.object) -> _SageObject: ...

def add1_with(bla: builtins.object) -> _SageObject: ...
