from collections.abc import Callable
from typing import ParamSpec, TypeVar

_P = ParamSpec("_P")
_R = TypeVar("_R")
_StateValue = TypeVar("_StateValue")
type MutabilityState[_StateValue] = dict[str, bool | _StateValue]

class Mutability[StateValue]:
    def __init__(self, is_immutable: bool = False) -> None: ...
    def _require_mutable(self) -> None: ...
    def _require_immutable(self) -> None: ...
    def set_immutable(self) -> None: ...
    def is_immutable(self) -> bool: ...
    def is_mutable(self) -> bool: ...
    def __getstate__(self) -> MutabilityState[Mutability]: ...
    def __setstate__(self, state: MutabilityState[_StateValue]) -> None: ...

def require_mutable(f: Callable[_P, _R]) -> Callable[_P, _R]: ...
def require_immutable(f: Callable[_P, _R]) -> Callable[_P, _R]: ...
