from sage.structure.parent import Parent

class ParentWithBase(Parent):
    def __init__(self, base: Parent, *args: object, **kwds: object) -> None: ...
    def base_extend(self, X: Parent) -> Parent: ...

def check_old_coerce(p: Parent) -> None: ...
