from typing import Any

from .category_object import CategoryObject

class Parent(CategoryObject):
    def __init__(self: Any, category: Any = ...) -> None: ...
    def Hom(self: Any, *args: Any, **kwargs: Any) -> Any: ...
    def _refine_category_(self, category: Any) -> None: ...
    def _test_not_implemented_methods(self) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def structure_morphism(self) -> Any: ...
    def saturation(self, *args: Any, **kwargs: Any) -> Any: ...
    def zero(self) -> Any: ...
    def base_ring(self) -> Any: ...
    def quotient_module(self, *args: Any, **kwargs: Any) -> Any: ...
    def direct_sum(self, *args: Any, **kwargs: Any) -> Any: ...
    def algebra(self, *args: Any, **kwargs: Any) -> Any: ...
