from collections.abc import Iterable
from typing import SupportsIndex, TypeAlias, overload

from sage.structure.sage_object import SageObject
from sage.structure.parent import Parent
from sage.categories.category import Category

_SequenceElement: TypeAlias = SageObject | int | float | complex | str | bool

def Sequence(
    x: Iterable[_SequenceElement],
    universe: Parent | Category | None = None,
    check: bool = True,
    immutable: bool = False,
    cr: bool = False,
    cr_str: bool | None = None,
    use_sage_types: bool = False,
) -> Sequence_generic: ...

class Sequence_generic(SageObject, list[_SequenceElement]):
    def __init__(
        self,
        x: Iterable[_SequenceElement],
        universe: Parent | Category | None = None,
        check: bool = True,
        immutable: bool = False,
        cr: bool = False,
        cr_str: bool | None = None,
        use_sage_types: bool = False,
    ) -> None: ...
    def reverse(self) -> None: ...
    @overload
    def __setitem__(self, n: SupportsIndex, value: _SequenceElement) -> None: ...
    @overload
    def __setitem__(self, n: slice, value: Iterable[_SequenceElement]) -> None: ...
    @overload
    def __getitem__(self, n: SupportsIndex) -> _SequenceElement: ...
    @overload
    def __getitem__(self, n: slice) -> Sequence_generic: ...
    def __getslice__(self, i: int, j: int) -> Sequence_generic: ...
    def __setslice__(self, i: int, j: int, value: Iterable[_SequenceElement]) -> None: ...
    def append(self, x: _SequenceElement) -> None: ...
    def extend(self, iterable: Iterable[_SequenceElement]) -> None: ...
    def insert(self, index: SupportsIndex, value: _SequenceElement) -> None: ...
    def pop(self, index: SupportsIndex = -1) -> _SequenceElement: ...
    def remove(self, value: _SequenceElement) -> None: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def universe(self) -> Parent | Category: ...
    def _require_mutable(self) -> None: ...
    def set_immutable(self) -> None: ...
    def is_immutable(self) -> bool: ...
    def is_mutable(self) -> bool: ...
    def __reduce__(
        self,
    ) -> tuple[
        type[Sequence_generic],
        tuple[list[_SequenceElement], Parent | Category, bool, bool, bool | None],
    ]: ...
    def __copy__(self) -> Sequence_generic: ...
    def __getattr__(self, name: str) -> Parent | Category | bool | None: ...

seq = Sequence
