from typing import TypeVar, SupportsIndex, Iterator, overload
from collections.abc import Callable, Iterable, MutableSequence
from sage.structure.sage_object import SageObject
from sage.structure.parent import Parent
from sage.categories.category import Category

_T = TypeVar("_T")

def Sequence(
    x: list[_T] | tuple[_T, ...] | _T,
    universe: Parent | Category | None = None,
    check: bool = True,
    immutable: bool = False,
    cr: bool = False,
    cr_str: bool | None = None,
    use_sage_types: bool = False,
) -> Sequence_generic: ...

class Sequence_generic(SageObject, MutableSequence[_T]):
    def __init__(
        self,
        x: list[_T] | tuple[_T, ...] | _T,
        universe: Parent | Category | None = None,
        check: bool = True,
        immutable: bool = False,
        cr: bool = False,
        cr_str: bool | None = None,
        use_sage_types: bool = False,
    ) -> None: ...
    def reverse(self) -> None: ...
    def __setitem__(self, n: SupportsIndex | slice, value: _T) -> None: ...
    @overload
    def __getitem__(self, n: SupportsIndex) -> _T: ...
    @overload
    def __getitem__(self, n: slice) -> Sequence_generic: ...
    def __getslice__(self, i: int, j: int) -> Sequence_generic: ...
    def __setslice__(self, i: int, j: int, value: Iterable[_T]) -> None: ...
    def append(self, x: _T) -> None: ...
    def extend(self, iterable: Iterable[_T]) -> None: ...
    def insert(self, index: SupportsIndex, object: _T) -> None: ...
    def pop(self, index: SupportsIndex = -1) -> _T: ...
    def remove(self, value: _T) -> None: ...
    def sort(self, key: Callable[[_T], object] | None = None, reverse: bool = False) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __hash__(self) -> int: ...  # type: ignore[override]
    def _repr_(self) -> str: ...
    def _repr_pretty_(self, p: object, cycle: bool) -> None: ...
    def _latex_(self) -> str: ...
    def universe(self) -> Parent | Category: ...
    def _require_mutable(self) -> None: ...
    def set_immutable(self) -> None: ...
    def is_immutable(self) -> bool: ...
    def is_mutable(self) -> bool: ...
    def __reduce__(self) -> tuple[type, tuple[list[_T], Parent | Category, bool, bool, bool]]: ...
    def __copy__(self) -> Sequence_generic: ...
    def __getattr__(self, name: str) -> object: ...

seq = Sequence
