from collections.abc import Callable

from sage.categories.category import Category
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject
from sage.structure.unique_representation import UniqueRepresentation
from typing import TypeAlias

SetFactoryConstraints: TypeAlias = tuple[int | None, ...]
ElementConstructorAttributes: TypeAlias = dict[str, Parent | str | type[Element]]

class SetFactory(UniqueRepresentation, SageObject):
    def __call__(self, *constraints: int | None, **consdict: int | None) -> Parent: ...
    def add_constraints(
        self, cons: SetFactoryConstraints, *args: object, **opts: int | None
    ) -> SetFactoryConstraints: ...

class SetFactoryPolicy(UniqueRepresentation, SageObject):
    def __init__(self, factory: SetFactory) -> None: ...
    def factory(self) -> SetFactory: ...
    def self_element_constructor_attributes(
        self, element_class: type[Element]
    ) -> ElementConstructorAttributes: ...
    def facade_element_constructor_attributes(
        self, parent: Parent
    ) -> ElementConstructorAttributes: ...
    def element_constructor_attributes(
        self, constraints: SetFactoryConstraints
    ) -> ElementConstructorAttributes: ...

class SelfParentPolicy(SetFactoryPolicy):
    def __init__(self, factory: SetFactory, element_class: type[Element]) -> None: ...
    def element_constructor_attributes(
        self, constraints: SetFactoryConstraints
    ) -> ElementConstructorAttributes: ...
    def _repr_(self) -> str: ...

class TopMostParentPolicy(SetFactoryPolicy):
    def __init__(
        self,
        factory: SetFactory,
        top_constraints: SetFactoryConstraints,
        element_class: type[Element],
    ) -> None: ...
    def element_constructor_attributes(
        self, constraints: SetFactoryConstraints
    ) -> ElementConstructorAttributes: ...
    def _repr_(self) -> str: ...

class FacadeParentPolicy(SetFactoryPolicy):
    def __init__(self, factory: SetFactory, parent: Parent) -> None: ...
    def element_constructor_attributes(
        self, constraints: SetFactoryConstraints
    ) -> ElementConstructorAttributes: ...
    def _repr_(self) -> str: ...

class BareFunctionPolicy(SetFactoryPolicy):
    def __init__(self, factory: SetFactory, constructor: Callable[..., Element]) -> None: ...
    def element_constructor_attributes(
        self, constraints: SetFactoryConstraints
    ) -> ElementConstructorAttributes: ...
    def _repr_(self) -> str: ...

class ParentWithSetFactory(Parent):
    def __init__(
        self,
        constraints: SetFactoryConstraints,
        policy: SetFactoryPolicy,
        category: Category | None = None,
    ) -> None: ...
    def constraints(self) -> SetFactoryConstraints: ...
    def policy(self) -> SetFactoryPolicy: ...
    def facade_policy(self) -> SetFactoryPolicy: ...
    def factory(self) -> SetFactory: ...
    def subset(self, *args: int | None, **options: int | None) -> ParentWithSetFactory: ...
    def _test_subset(self, **options: bool) -> None: ...
    def check_element(self, x: Element, check: bool) -> None: ...
    def __contains__(self, x: Element | SageObject) -> bool: ...
    def __call__(self, *args: object, **keywords: object) -> Element: ...
    def _element_constructor_(self, *args: object, **keywords: object) -> Element: ...
