from collections.abc import Iterator, MappingView, Sequence, Set as AbstractSet
from typing import overload

class SupportView(MappingView, Sequence[object], AbstractSet[object]):
    def __init__(self, mapping: object, *, zero: object = None) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> object: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[object, ...]: ...
    def __iter__(self) -> Iterator[object]: ...
    def __contains__(self, key: object) -> bool: ...
