from collections.abc import Iterator, MappingView
from typing import Generic, TypeVar, overload

_T = TypeVar("_T")

class SupportView(MappingView, Generic[_T]):
    def __init__(self, mapping: object, *, zero: object = None) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> _T: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[_T, ...]: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __contains__(self, key: object) -> bool: ...
