from sage.misc.fast_methods import WithEqualityById

class WithPicklingByInitArgs:
    def __classcall__(cls, *args: object, **options: object) -> WithPicklingByInitArgs: ...
    def __reduce__(self) -> tuple[object, ...]: ...
    def __copy__(self) -> WithPicklingByInitArgs: ...
    def __deepcopy__(self, memo: dict[int, object]) -> WithPicklingByInitArgs: ...
    def __getstate__(self) -> dict[str, object] | None: ...
    def __setstate__(self, d: dict[str, object]) -> None: ...

def unreduce(cls: type, args: tuple[object, ...], keywords: dict[str, object]) -> UniqueRepresentation: ...

class CachedRepresentation(WithPicklingByInitArgs):
    def __classcall__(cls, *args: object, **options: object) -> CachedRepresentation: ...
    @classmethod
    def _clear_cache_(cls) -> None: ...

class UniqueRepresentation(WithEqualityById, CachedRepresentation):
    @classmethod
    def _reduction(cls) -> tuple[type, tuple[object, ...], dict[str, object]] | tuple[type, tuple[object, ...]]: ...
    def __reduce__(self) -> tuple[type, tuple[object, ...]]: ...
    def __copy__(self) -> UniqueRepresentation: ...
