# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

pi: _SageObject
named_colors: _SageObject
def xproj(x: builtins.object, y: builtins.object, z: builtins.object, r: builtins.int) -> _SageObject: ...

def yproj(x: builtins.object, y: builtins.object, z: builtins.object, r: builtins.int) -> _SageObject: ...

def rotation_list(tilt: builtins.object, turn: builtins.object) -> _SageObject: ...

def polygon_plot3d(points: builtins.object, tilt: builtins.int = ..., turn: builtins.int = ..., **kwargs: builtins.object) -> _SageObject: ...

def inv_list(lst: builtins.object) -> _SageObject: ...

face_polys: _SageObject
def create_poly(face: builtins.object, color: builtins.object) -> _SageObject: ...

singmaster_indices: _SageObject
def index2singmaster(facet: builtins.object) -> _SageObject: ...

def color_of_square(facet: builtins.object, colors: builtins.list[_SageObject] = ...) -> _SageObject: ...

cubie_center_list: _SageObject
def cubie_centers(label: builtins.str) -> _SageObject: ...

def cubie_colors(label: builtins.str, state0: builtins.object) -> _SageObject: ...

def plot3d_cubie(cnt: builtins.object, clrs: builtins.object) -> _SageObject: ...

class CubeGroup:
    def __init__(self) -> None: ...
    def gen_names(self) -> _SageObject: ...
    def B(self) -> _SageObject: ...
    def D(self) -> _SageObject: ...
    def F(self) -> _SageObject: ...
    def L(self) -> _SageObject: ...
    def R(self) -> _SageObject: ...
    def U(self) -> _SageObject: ...
    def parse(self, mv: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def facets(self, g: builtins.object = ...) -> _SageObject: ...
    def faces(self, mv: builtins.object) -> _SageObject: ...
    def move(self, mv: builtins.object) -> _SageObject: ...
    def display2d(self, mv: builtins.object) -> _SageObject: ...
    def repr2d(self, mv: builtins.object) -> _SageObject: ...
    def plot_cube(self, mv: builtins.object, title: builtins.bool = ..., colors: builtins.list[_SageObject] = ...) -> _SageObject: ...
    def plot3d_cube(self, mv: builtins.object, title: builtins.bool = ...) -> _SageObject: ...
    def legal(self, state: builtins.object, mode: builtins.str = ...) -> _SageObject: ...
    def solve(self, state: builtins.object, algorithm: builtins.str = ...) -> _SageObject: ...

def cubie_faces() -> _SageObject: ...

cubie_face_list: _SageObject
rand_colors: _SageObject
class RubiksCube:
    def __init__(self, state: builtins.object = ..., history: builtins.list[_SageObject] = ..., colors: builtins.list[_SageObject] = ...) -> None: ...
    def move(self, g: builtins.object) -> _SageObject: ...
    def undo(self) -> _SageObject: ...
    def facets(self) -> _SageObject: ...
    def plot(self) -> _SageObject: ...
    def show(self) -> _SageObject: ...
    def cubie(self, size: builtins.int, gap: builtins.object, x: builtins.object, y: builtins.object, z: builtins.object, colors: builtins.object, stickers: builtins.bool = ...) -> _SageObject: ...
    def plot3d(self, stickers: builtins.bool = ...) -> _SageObject: ...
    def show3d(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def solve(self, algorithm: builtins.str = ..., timeout: builtins.int = ...) -> _SageObject: ...
    def scramble(self, moves: builtins.int = ...) -> _SageObject: ...
