_BuiltinList = list
from collections.abc import Iterator
from typing import Literal, TypeVar, overload

from sage.categories.groups import Groups
from sage.groups.conjugacy_classes import ConjugacyClassGAP
from sage.groups.finitely_presented import FinitelyPresentedGroup
from sage.groups.perm_gps.permgroup_element import PermutationGroupElement
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.parent import ElementConstructorInput

_Point = TypeVar("_Point")
type _List[T] = list[T]

class PermutationGroup_generic(Groups.ParentMethods[PermutationGroupElement]):
    def order(self) -> Integer: ...
    def degree(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def is_cyclic(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def is_solvable(self) -> bool: ...
    def is_trivial(self) -> bool: ...
    def is_transitive(self, domain: _BuiltinList[int] | None = ...) -> bool: ...
    def generators(self) -> tuple[PermutationGroupElement, ...]: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: int = ...) -> PermutationGroupElement: ...
    def ngens(self) -> int: ...
    def identity(self) -> PermutationGroupElement: ...
    def random_element(self) -> PermutationGroupElement: ...
    def subgroup(
        self, gens: _BuiltinList[PermutationGroupElement]
    ) -> PermutationGroup_generic: ...
    def center(self) -> PermutationGroup_generic: ...
    def derived_subgroup(self) -> PermutationGroup_generic: ...
    def normalizer(self, g: PermutationGroup_generic) -> PermutationGroup_generic: ...
    def centralizer(
        self, g: PermutationGroupElement | PermutationGroup_generic
    ) -> PermutationGroup_generic: ...
    def orbits(self) -> _BuiltinList[_BuiltinList[int]]: ...
    def conjugacy_classes(self) -> _BuiltinList[ConjugacyClassGAP]: ...
    def character_table(self) -> _BuiltinList[_BuiltinList[Integer | bool | int]]: ...
    def sylow_subgroup(self, p: int) -> PermutationGroup_generic: ...
    def is_isomorphic(self, right: PermutationGroup_generic) -> bool: ...
    def as_finitely_presented_group(
        self, reduced: bool = ...
    ) -> FinitelyPresentedGroup: ...
    def list(self) -> _BuiltinList[PermutationGroupElement]: ...
    def __iter__(self) -> Iterator[PermutationGroupElement]: ...
    def structure_description(self) -> str: ...
    @overload
    def orbit(
        self, point: tuple[_Point, ...], action: Literal["OnSets"]
    ) -> _List[tuple[_Point, ...]]: ...
    @overload
    def orbit(self, point: int, action: str = ...) -> _BuiltinList[int]: ...
    @overload
    def direct_product(
        self, other: PermutationGroup_generic, maps: Literal[False]
    ) -> PermutationGroup_generic: ...
    @overload
    def direct_product(
        self, other: PermutationGroup_generic, maps: Literal[True] = ...
    ) -> tuple[PermutationGroup_generic, ...]: ...

type PermutationGroupGeneratorInput = (
    PermutationGroupElement | list[int] | tuple[int, ...] | ElementConstructorInput
)

def PermutationGroup(
    self=..., *args: ElementConstructorInput, **kwds: ElementConstructorInput
) -> PermutationGroup_generic: ...
