from sage.rings.integer import Integer
from sage.groups.perm_gps.permgroup_element import PermutationGroupElement
from sage.groups.conjugacy_classes import ConjugacyClassGAP

class PermutationGroup_generic:
    def order(self) -> Integer: ...
    def degree(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def is_cyclic(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def is_solvable(self) -> bool: ...
    def is_trivial(self) -> bool: ...
    def is_transitive(self, domain: list[int] | None = ...) -> bool: ...
    def generators(self) -> tuple[PermutationGroupElement, ...]: ...
    def gens(self) -> tuple[PermutationGroupElement, ...]: ...
    def gen(self, i: int = ...) -> PermutationGroupElement: ...
    def ngens(self) -> int: ...
    def identity(self) -> PermutationGroupElement: ...
    def random_element(self) -> PermutationGroupElement: ...
    def subgroup(self, gens: list[PermutationGroupElement]) -> PermutationGroup_generic: ...
    def center(self) -> PermutationGroup_generic: ...
    def derived_subgroup(self) -> PermutationGroup_generic: ...
    def normalizer(self, g: PermutationGroup_generic) -> PermutationGroup_generic: ...
    def centralizer(self, g: PermutationGroupElement | PermutationGroup_generic) -> PermutationGroup_generic: ...
    def orbits(self) -> list[list[int]]: ...
    def orbit(self, point: int, action: str = ...) -> list[int]: ...
    def conjugacy_classes(self) -> list[ConjugacyClassGAP]: ...
    def character_table(self) -> list[list[Integer | bool | int]]: ...
    def sylow_subgroup(self, p: int) -> PermutationGroup_generic: ...
    def is_isomorphic(self, right: PermutationGroup_generic) -> bool: ...
