import builtins
from typing import Self

class _SageObject: ...

latex_operators: _SageObject

class BooleanFormula:
    def __init__(
        self, exp: builtins.object, tree: builtins.object, vo: builtins.object
    ) -> None: ...
    def polish_notation(self) -> _SageObject: ...
    def tree(self) -> _SageObject: ...
    def full_tree(self) -> _SageObject: ...
    def __or__(self, other: builtins.object) -> Self: ...
    def __and__(self, other: builtins.object) -> Self: ...
    def __xor__(self, other: builtins.object) -> Self: ...
    def __pow__(self, other: builtins.object) -> Self: ...
    def __invert__(self) -> Self: ...
    def ifthen(self, other: builtins.object) -> _SageObject: ...
    def iff(self, other: builtins.object) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def truthtable(
        self, start: builtins.int = ..., end: builtins.object = ...
    ) -> _SageObject: ...
    def evaluate(self, var_values: builtins.object) -> _SageObject: ...
    def is_satisfiable(self) -> bool: ...
    def is_tautology(self) -> bool: ...
    def is_contradiction(self) -> bool: ...
    def is_consequence(self, *hypotheses: builtins.object) -> bool: ...
    def implies(self, other: builtins.object) -> _SageObject: ...
    def equivalent(self, other: builtins.object) -> _SageObject: ...
    def convert_cnf_table(self) -> _SageObject: ...
    convert_cnf: _SageObject

    def convert_cnf_recur(self) -> _SageObject: ...
    def satformat(self) -> _SageObject: ...
    def convert_opt(self, tree: builtins.object) -> _SageObject: ...
    def add_statement(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def get_bit(self, x: builtins.object, c: builtins.object) -> _SageObject: ...
    def reduce_op(self, tree: builtins.object) -> _SageObject: ...
    def dist_not(self, tree: builtins.object) -> _SageObject: ...
    def dist_ors(self, tree: builtins.object) -> _SageObject: ...
    def to_infix(self, tree: builtins.object) -> _SageObject: ...
    def convert_expression(self) -> _SageObject: ...
    def get_next_op(self, str: builtins.object) -> _SageObject: ...
    def length(self) -> _SageObject: ...

is_consequence: _SageObject
