# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def eval_formula(tree: builtins.object, vdict: builtins.object) -> _SageObject: ...

def eval_f(tree: builtins.object) -> _SageObject: ...

def eval_op(op: builtins.object, lv: builtins.object, rv: builtins.object) -> _SageObject: ...
