# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def parse(s: builtins.object) -> _SageObject: ...

def polish_parse(s: builtins.object) -> _SageObject: ...

def get_trees(*statements: builtins.object) -> _SageObject: ...

def recover_formula(prefix_tree: builtins.object) -> _SageObject: ...

def recover_formula_internal(prefix_tree: builtins.object) -> _SageObject: ...

def prefix_to_infix(prefix_tree: builtins.object) -> _SageObject: ...

def to_infix_internal(prefix_tree: builtins.object) -> _SageObject: ...

def tokenize(s: builtins.object) -> _SageObject: ...

def tree_parse(toks: builtins.object, polish: builtins.bool = ...) -> _SageObject: ...

def parse_ltor(toks: builtins.object, n: builtins.int = ..., polish: builtins.bool = ...) -> _SageObject: ...

def apply_func(tree: builtins.object, func: builtins.object) -> _SageObject: ...
