import builtins

class _SageObject: ...

def parse(self) -> _SageObject: ...
def polish_parse(self) -> _SageObject: ...
def get_trees(self, *statements: builtins.object) -> _SageObject: ...
def recover_formula(self) -> _SageObject: ...
def recover_formula_internal(self) -> _SageObject: ...
def prefix_to_infix(self) -> _SageObject: ...
def to_infix_internal(self) -> _SageObject: ...
def tokenize(self) -> _SageObject: ...
def tree_parse(self, polish: builtins.bool = ...) -> _SageObject: ...
def parse_ltor(
    self, n: builtins.int = ..., polish: builtins.bool = ...
) -> _SageObject: ...
def apply_func(self, func: builtins.object) -> _SageObject: ...
