from sage.logic.boolformula import BooleanFormula
from sage.logic.logicparser import BooleanParseTree


def formula(s: str) -> BooleanFormula: ...
def get_formulas(
    *statements: str | BooleanParseTree,
) -> list[BooleanFormula]: ...
def consistent(*formulas: BooleanFormula) -> bool: ...
