# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

max_print: _SageObject
class IntList:
    def __cinit__(self) -> _SageObject: ...
    def __init__(self, values: builtins.object) -> None: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __setitem__(self, i: builtins.object, x: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def list(self) -> _SageObject: ...
    def sum(self) -> _SageObject: ...
    def prod(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def __add__(left: builtins.object, right: builtins.object) -> Self: ...
    def min(self, index: builtins.object = ...) -> _SageObject: ...
    def max(self, index: builtins.object = ...) -> _SageObject: ...
    def time_series(self) -> _SageObject: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def plot_histogram(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def new_int_list(length: builtins.object) -> _SageObject: ...

def unpickle_intlist_v1(v: builtins.object, n: builtins.object) -> _SageObject: ...
