# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

max_print: _SageObject
digits: _SageObject
class TimeSeries:
    def __cinit__(self) -> _SageObject: ...
    def __init__(self, values: builtins.object, initialize: builtins.object = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def vector(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __setitem__(self, i: builtins.object, x: builtins.object) -> None: ...
    def __copy__(self) -> Self: ...
    def __add__(left: builtins.object, right: builtins.object) -> Self: ...
    def __mul__(left: builtins.object, right: builtins.object) -> Self: ...
    def autoregressive_fit(self, M: builtins.object) -> _SageObject: ...
    def autoregressive_forecast(self, filter: builtins.object) -> _SageObject: ...
    def reversed(self) -> _SageObject: ...
    def extend(self, right: builtins.object) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def log(self) -> _SageObject: ...
    def exp(self) -> _SageObject: ...
    def abs(self) -> _SageObject: ...
    def diffs(self, k: builtins.object = ...) -> _SageObject: ...
    def scale_time(self, k: builtins.object) -> _SageObject: ...
    def rescale(self, s: builtins.object) -> _SageObject: ...
    def scale(self, s: builtins.object) -> _SageObject: ...
    def add_scalar(self, s: builtins.object) -> _SageObject: ...
    def add_entries(self, t: builtins.object) -> _SageObject: ...
    def show(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def plot(self, plot_points: builtins.object = ..., points: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def simple_moving_average(self, k: builtins.object) -> _SageObject: ...
    def exponential_moving_average(self, alpha: builtins.object) -> _SageObject: ...
    def sums(self, s: builtins.object = ...) -> _SageObject: ...
    def sum(self) -> _SageObject: ...
    def prod(self) -> _SageObject: ...
    def mean(self) -> _SageObject: ...
    def pow(self, k: builtins.object) -> _SageObject: ...
    def moment(self, k: builtins.object) -> _SageObject: ...
    def central_moment(self, k: builtins.object) -> _SageObject: ...
    def covariance(self, other: builtins.object) -> _SageObject: ...
    def autocovariance(self, k: builtins.object = ...) -> _SageObject: ...
    def correlation(self, other: builtins.object) -> _SageObject: ...
    def autocorrelation(self, k: builtins.object = ...) -> _SageObject: ...
    def variance(self, bias: builtins.object = ...) -> _SageObject: ...
    def standard_deviation(self, bias: builtins.object = ...) -> _SageObject: ...
    def range_statistic(self, b: builtins.object = ...) -> _SageObject: ...
    def hurst_exponent(self) -> _SageObject: ...
    def min(self, index: builtins.object = ...) -> _SageObject: ...
    def max(self, index: builtins.object = ...) -> _SageObject: ...
    def clip_remove(self, min: builtins.object = ..., max: builtins.object = ...) -> _SageObject: ...
    def histogram(self, bins: builtins.object = ..., normalize: builtins.object = ...) -> _SageObject: ...
    def plot_histogram(self, bins: builtins.object = ..., normalize: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def plot_candlestick(self, bins: builtins.object = ...) -> _SageObject: ...
    def numpy(self, copy: builtins.object = ...) -> _SageObject: ...
    def randomize(self, distribution: builtins.object = ..., loc: builtins.object = ..., scale: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def fft(self, overwrite: builtins.object = ...) -> _SageObject: ...
    def ifft(self, overwrite: builtins.object = ...) -> _SageObject: ...

def new_time_series(length: builtins.object) -> _SageObject: ...

def unpickle_time_series_v1(v: builtins.object, n: builtins.object) -> _SageObject: ...

def autoregressive_fit(acvs: builtins.object) -> _SageObject: ...
