from sage.rings.polynomial.pbori.pbori import BooleanPolynomial

def easy_linear_polynomials(self) -> list[BooleanPolynomial]: ...
def easy_linear_polynomials_via_interpolation(self) -> list[BooleanPolynomial]: ...
