from sage.rings.polynomial.pbori.pbori import BooleanPolynomial

def easy_linear_polynomials(p: BooleanPolynomial) -> list[BooleanPolynomial]: ...
def easy_linear_polynomials_via_interpolation(p: BooleanPolynomial) -> list[BooleanPolynomial]: ...
