from sage.rings.polynomial.pbori.pbori import BooleanMonomial, BooleanPolynomialRing

def _fglm(
    self, from_ring: BooleanPolynomialRing, to_ring: BooleanPolynomialRing
) -> list[object]: ...
def fglm(
    self, from_ring: BooleanPolynomialRing, to_ring: BooleanPolynomialRing
) -> list[object]: ...
def vars_real_divisors(self, monomial_set: object) -> list[BooleanMonomial]: ...
def m_k_plus_one(self, variables: object) -> list[BooleanMonomial]: ...
