from collections.abc import Callable

from sage.rings.polynomial.pbori.pbori import BooleanPolynomial
from sage.structure.element import Element

class HeuristicalFunction:
    def __call__(self, *args: object, **kwds: object) -> Element: ...
    def __init__(self, f: Callable[..., object], heuristic_function: Callable[..., object]) -> None: ...

def get_options_from_function(f: object) -> dict[str, object]: ...
def filter_oldstyle_options(**options: object) -> dict[str, object]: ...
def filter_newstyle_options(func: object, **options: object) -> dict[str, object]: ...
def want_interpolation_gb(G: object) -> bool: ...
def ll_is_good(I: object) -> bool: ...
def ll_heuristic(d: int) -> bool: ...
def change_order_heuristic(d: int) -> bool: ...
def interpolation_gb_heuristic(d: int) -> bool: ...
def linear_algebra_heuristic(d: int) -> bool: ...
def trivial_heuristic(d: int) -> bool: ...
def with_heuristic(heuristic_function: Callable[..., object]) -> Callable[..., object]: ...
def clean_polys_pre(I: object) -> list[object]: ...
def gb_with_pre_post_option(option: str, pre: object = None, post: object = None) -> Callable[..., object]: ...
def redsb_post(I: object, state: object) -> list[object]: ...
def minsb_post(I: object, state: object) -> list[object]: ...
def invert_all(I: object) -> list[object]: ...
def invert_all_pre(I: object) -> list[object]: ...
def invert_all_post(I: object, state: object) -> list[object]: ...
def llfirst_pre(I: object, prot: bool) -> list[object]: ...
def ll_constants_pre(I: object) -> list[object]: ...
def variety_size_from_gb(I: object) -> int: ...
def other_ordering_pre(I: object, option_set: object, kwds: object) -> list[object]: ...
def llfirstonthefly_pre(I: object, prot: bool) -> list[object]: ...
def gauss_on_linear_pre(I: object, prot: bool) -> list[object]: ...
def easy_linear_polynomials_pre(I: object) -> list[object]: ...
def llfirst_post(I: object, state: object, prot: bool, kwds: object) -> list[object]: ...
def ll_constants_post(I: object, state: object) -> list[object]: ...
def result_to_list_post(I: object, state: object) -> list[object]: ...
def fix_deg_bound_post(I: object, state: object) -> list[object]: ...
def incremental_pre(I: object, prot: bool, kwds: object) -> list[object]: ...
def eliminate_identical_variables_pre(I: object, prot: bool) -> list[object]: ...
def groebner_basis(I: object, heuristic: bool = True, unique_ideal_generator: bool = False, **kwds: object) -> list[object]: ...
def build_groebner_basis_doc_string() -> str: ...
