from collections.abc import Callable

from sage.structure.element import Element

class HeuristicalFunction:
    def __call__(self, *args: object, **kwds: object) -> Element: ...
    def __init__(
        self, f: Callable[..., object], heuristic_function: Callable[..., object]
    ) -> None: ...

def get_options_from_function(self) -> dict[str, object]: ...
def filter_oldstyle_options(self, **options: object) -> dict[str, object]: ...
def filter_newstyle_options(self, **options: object) -> dict[str, object]: ...
def want_interpolation_gb(self) -> bool: ...
def ll_is_good(self) -> bool: ...
def ll_heuristic(self) -> bool: ...
def change_order_heuristic(self) -> bool: ...
def interpolation_gb_heuristic(self) -> bool: ...
def linear_algebra_heuristic(self) -> bool: ...
def trivial_heuristic(self) -> bool: ...
def with_heuristic(self) -> Callable[..., object]: ...
def clean_polys_pre(self) -> list[object]: ...
def gb_with_pre_post_option(
    self, pre: object = None, post: object = None
) -> Callable[..., object]: ...
def redsb_post(self, state: object) -> list[object]: ...
def minsb_post(self, state: object) -> list[object]: ...
def invert_all(self) -> list[object]: ...
def invert_all_pre(self) -> list[object]: ...
def invert_all_post(self, state: object) -> list[object]: ...
def llfirst_pre(self, prot: bool) -> list[object]: ...
def ll_constants_pre(self) -> list[object]: ...
def variety_size_from_gb(self) -> int: ...
def other_ordering_pre(self, option_set: object, kwds: object) -> list[object]: ...
def llfirstonthefly_pre(self, prot: bool) -> list[object]: ...
def gauss_on_linear_pre(self, prot: bool) -> list[object]: ...
def easy_linear_polynomials_pre(self) -> list[object]: ...
def llfirst_post(self, state: object, prot: bool, kwds: object) -> list[object]: ...
def ll_constants_post(self, state: object) -> list[object]: ...
def result_to_list_post(self, state: object) -> list[object]: ...
def fix_deg_bound_post(self, state: object) -> list[object]: ...
def incremental_pre(self, prot: bool, kwds: object) -> list[object]: ...
def eliminate_identical_variables_pre(self, prot: bool) -> list[object]: ...
def groebner_basis(
    self, heuristic: bool = True, unique_ideal_generator: bool = False, **kwds: object
) -> list[object]: ...
def build_groebner_basis_doc_string(self) -> str: ...
