from sage.rings.polynomial.pbori.pbori import BooleanMonomial, BooleanPolynomial

def add_up_poly_list(self, init: object) -> BooleanPolynomial: ...
def bench_interpolate(self, nvariables: int, points: object) -> None: ...
def nf_lex_points(self, p: object) -> list[BooleanPolynomial]: ...
def gen_random_o_z(self, points_p: object) -> list[object]: ...
def variety_lex_leading_terms(self, variables: object) -> list[BooleanMonomial]: ...
def lex_groebner_basis_points(self, variables: object) -> list[BooleanPolynomial]: ...
def lex_groebner_basis_for_polynomial_via_variety(self) -> list[BooleanPolynomial]: ...
