from sage.rings.polynomial.pbori.pbori import BooleanMonomial, BooleanPolynomial

def add_up_poly_list(l: object, init: object) -> BooleanPolynomial: ...
def bench_interpolate(degree: int, nvariables: int, points: object) -> None: ...
def nf_lex_points(f: object, p: object) -> list[BooleanPolynomial]: ...
def gen_random_o_z(points: object, points_p: object) -> list[object]: ...
def variety_lex_leading_terms(points: object, variables: object) -> list[BooleanMonomial]: ...
def lex_groebner_basis_points(points: object, variables: object) -> list[BooleanPolynomial]: ...
def lex_groebner_basis_for_polynomial_via_variety(p: object) -> list[BooleanPolynomial]: ...
