from sage.rings.polynomial.pbori.pbori import BooleanPolynomial, ReductionStrategy

class GeneratorLimitExceeded(Exception):
    def __init__(self, strat: ReductionStrategy) -> None: ...

def pkey(p: object) -> tuple[object, ...]: ...
def build_and_print_matrices(v: object, strat: object) -> None: ...
def multiply_polynomials(l: object, ring: object) -> BooleanPolynomial: ...
def build_and_print_matrices_deg_colored(v: object, strat: object) -> None: ...
def high_probability_polynomials_trick(p: object, strat: object) -> list[BooleanPolynomial]: ...
def symmGB_F2_python(G: object, deg_bound: int = ..., over_deg_bound: int = 0, **kwds: object) -> list[BooleanPolynomial]: ...
def GPS(G: object, vars_start: int, vars_end: int) -> list[BooleanPolynomial]: ...
def GPS_with_proof_path(G: object, proof_path: object, deg_bound: int, over_deg_bound: int) -> list[BooleanPolynomial]: ...
def GPS_with_suggestions(G: object, deg_bound: int, over_deg_bound: int, opt_lazy: bool = True, **kwds: object) -> list[BooleanPolynomial]: ...
def GPS_with_non_binary_proof_path(G: object, proof_path: object, deg_bound: int, over_deg_bound: int) -> list[BooleanPolynomial]: ...
def symmGB_F2_C(G: object, opt_exchange: bool = True, **kwds: object) -> list[BooleanPolynomial]: ...
def normal_form(poly: BooleanPolynomial, ideal: object, reduced: bool = True) -> BooleanPolynomial: ...
def _test() -> None: ...
