from sage.rings.polynomial.pbori.pbori import BooleanMonomial, BooleSet

def used_vars(self, bound: int | None = None) -> list[BooleanMonomial]: ...
def used_vars_set(self, bound: int | None = None) -> BooleSet: ...
