from sage.rings.polynomial.pbori.pbori import BooleanMonomial, BooleSet

def used_vars(l: object, bound: int | None = None) -> list[BooleanMonomial]: ...
def used_vars_set(l: object, bound: int | None = None) -> BooleSet: ...
