# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def TangentBundle(X: builtins.object) -> _SageObject: ...

def CotangentBundle(X: builtins.object) -> _SageObject: ...

def TrivialBundle(X: builtins.object, rank: builtins.int = ...) -> _SageObject: ...

def LineBundle(X: builtins.object, D: builtins.object) -> _SageObject: ...

class SheafLibrary:
    def __init__(self, toric_variety: builtins.object) -> None: ...
    def trivial_bundle(self, rank: builtins.int = ...) -> _SageObject: ...
    def line_bundle(self, divisor: builtins.object) -> _SageObject: ...
    def tangent_bundle(self) -> _SageObject: ...
    def cotangent_bundle(self) -> _SageObject: ...
    def Klyachko(self, multi_filtration: builtins.object) -> _SageObject: ...
    def divisor(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
