import builtins

class _SageObject: ...

def normalise_hadamard(self, skew: builtins.bool = ...) -> _SageObject: ...
def hadamard_matrix_paleyI(self, normalize: builtins.bool = ...) -> _SageObject: ...
def symmetric_conference_matrix_paley(self) -> _SageObject: ...
def hadamard_matrix_paleyII(self) -> _SageObject: ...
def hadamard_matrix_from_symmetric_conference_matrix(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def hadamard_matrix_miyamoto_construction(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def hadamard_matrix_williamson_type(
    self,
    b: builtins.object,
    c: builtins.object,
    d: builtins.object,
    check: builtins.bool = ...,
) -> _SageObject: ...
def williamson_type_quadruples_smallcases(
    self, existence: builtins.bool = ...
) -> _SageObject: ...
def williamson_hadamard_matrix_smallcases(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def hadamard_matrix_156(self) -> _SageObject: ...
def construction_four_symbol_delta_code_I(
    self, Y: builtins.object, Z: builtins.object, W: builtins.object
) -> _SageObject: ...
def construction_four_symbol_delta_code_II(
    self, Y: builtins.object, Z: builtins.object, W: builtins.object
) -> _SageObject: ...
def four_symbol_delta_code_smallcases(
    self, existence: builtins.bool = ...
) -> _SageObject: ...
def hadamard_matrix_from_sds(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def hadamard_matrix_cooper_wallis_construction(
    self,
    x2: builtins.object,
    x3: builtins.object,
    x4: builtins.object,
    A: builtins.object,
    B: builtins.object,
    C: builtins.object,
    D: builtins.object,
    check: builtins.bool = ...,
) -> _SageObject: ...
def hadamard_matrix_cooper_wallis_smallcases(
    self, check: builtins.bool = ..., existence: builtins.bool = ...
) -> _SageObject: ...
def hadamard_matrix_turyn_type(
    self,
    b: builtins.object,
    c: builtins.object,
    d: builtins.object,
    e1: builtins.object,
    e2: builtins.object,
    e3: builtins.object,
    e4: builtins.object,
    check: builtins.bool = ...,
) -> _SageObject: ...
def turyn_type_hadamard_matrix_smallcases(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def hadamard_matrix_spence_construction(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def is_hadamard_matrix(
    self,
    normalized: builtins.bool = ...,
    skew: builtins.bool = ...,
    verbose: builtins.bool = ...,
) -> builtins.bool: ...
def is_skew_hadamard_matrix(
    self, normalized: builtins.bool = ..., verbose: builtins.bool = ...
) -> builtins.bool: ...
def hadamard_matrix(
    self,
    existence: builtins.bool = ...,
    check: builtins.bool = ...,
    construction_name: builtins.bool = ...,
) -> _SageObject: ...
def hadamard_matrix_www(self, comments: builtins.bool = ...) -> _SageObject: ...
def regular_symmetric_hadamard_matrix_with_constant_diagonal(
    self, e: builtins.object, existence: builtins.bool = ...
) -> _SageObject: ...
def RSHCD_324(self) -> _SageObject: ...
def rshcd_from_close_prime_powers(self) -> _SageObject: ...
def williamson_goethals_seidel_skew_hadamard_matrix(
    self,
    b: builtins.object,
    c: builtins.object,
    d: builtins.object,
    check: builtins.bool = ...,
) -> _SageObject: ...
def skew_hadamard_matrix_spence_construction(
    self, check: builtins.bool = ...
) -> _SageObject: ...
def skew_hadamard_matrix_spence_1975(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def GS_skew_hadamard_smallcases(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def skew_hadamard_matrix_from_orthogonal_design(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def skew_hadamard_matrix_from_complementary_difference_sets(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def skew_hadamard_matrix_whiteman_construction(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def skew_hadamard_matrix_from_good_matrices(
    self,
    b: builtins.object,
    c: builtins.object,
    d: builtins.object,
    check: builtins.bool = ...,
) -> _SageObject: ...
def skew_hadamard_matrix_from_good_matrices_smallcases(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def skew_hadamard_matrix(
    self,
    existence: builtins.bool = ...,
    skew_normalize: builtins.bool = ...,
    check: builtins.bool = ...,
    construction_name: builtins.bool = ...,
) -> _SageObject: ...
def symmetric_conference_matrix(
    self, check: builtins.bool = ..., existence: builtins.bool = ...
) -> _SageObject: ...
def szekeres_difference_set_pair(self, check: builtins.bool = ...) -> _SageObject: ...
def typeI_matrix_difference_set(self, A: builtins.object) -> _SageObject: ...
def rshcd_from_prime_power_and_conference_matrix(self) -> _SageObject: ...
def are_amicable_hadamard_matrices(
    self, N: builtins.int, verbose: builtins.bool = ...
) -> _SageObject: ...
def amicable_hadamard_matrices_wallis(
    self, check: builtins.bool = ...
) -> _SageObject: ...
def amicable_hadamard_matrices(
    self, existence: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
