from collections.abc import Iterator
from typing import Self

from sage.combinat.permutation import Permutation
from sage.groups.group import Group
from sage.groups.perm_gps.permgroup import PermutationGroup_generic
from sage.matrix.matrix0 import Matrix
from sage.structure.element import Vector

type _BuiltinList[_T] = list[_T]

class LatinSquare:
    def __init__(self, *args: int | Matrix | list[list[int]]) -> None: ...
    def dumps(self) -> bytes: ...
    def __getitem__(self, rc: tuple[int, int]) -> int: ...
    def __setitem__(self, rc: tuple[int, int], val: int) -> None: ...
    def set_immutable(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __copy__(self) -> Self: ...
    def clear_cells(self) -> None: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def row(self, x: int) -> Vector: ...
    def column(self, x: int) -> Vector: ...
    def list(self) -> _BuiltinList[_BuiltinList[int]]: ...
    def n_filled_cells(self) -> int: ...
    def actual_row_col_sym_sizes(self) -> tuple[int, int, int]: ...
    def is_empty_column(self, c: int) -> bool: ...
    def is_empty_row(self, r: int) -> bool: ...
    def n_distinct_symbols(self) -> int: ...
    def apply_isotopism(
        self,
        row_perm: Permutation | _BuiltinList[int],
        col_perm: Permutation | _BuiltinList[int],
        sym_perm: Permutation | _BuiltinList[int],
    ) -> Self: ...
    def filled_cells_map(self) -> dict[tuple[int, int, int], int]: ...
    def top_left_empty_cell(self) -> _BuiltinList[int] | None: ...
    def is_partial_latin_square(self) -> bool: ...
    def is_latin_square(self) -> bool: ...
    def permissable_values(self, r: int, c: int) -> _BuiltinList[int]: ...
    def random_empty_cell(self) -> _BuiltinList[int] | None: ...
    def is_uniquely_completable(self) -> bool: ...
    def is_completable(self) -> bool: ...
    def gcs(self) -> Self: ...
    def dlxcpp_has_unique_completion(self) -> bool: ...
    def vals_in_row(self, r: int) -> _BuiltinList[int]: ...
    def vals_in_col(self, c: int) -> _BuiltinList[int]: ...
    def latex(self) -> str: ...
    def disjoint_mate_dlxcpp_rows_and_map(
        self, allow_subtrade: bool
    ) -> tuple[_BuiltinList[_BuiltinList[int]], dict[object, object]]: ...
    def find_disjoint_mates(
        self, nr_to_find: int | None = ..., allow_subtrade: bool = ...
    ) -> Iterator[LatinSquare]: ...
    def contained_in(self, Q: LatinSquare) -> bool: ...

def genus(T1: LatinSquare, T2: LatinSquare) -> int: ...

def tau123(
    T1: LatinSquare, T2: LatinSquare
) -> tuple[dict[object, object], Permutation, Permutation, Permutation]: ...

def isotopism(p: Permutation | list[int] | tuple[int, ...]) -> Permutation: ...

def cells_map_as_square(cells_map: dict[object, object], n: int) -> LatinSquare: ...

def beta1(rce: tuple[int, int, int], T1: LatinSquare, T2: LatinSquare) -> tuple[int, int, int]: ...

def beta2(rce: tuple[int, int, int], T1: LatinSquare, T2: LatinSquare) -> tuple[int, int, int]: ...

def beta3(rce: tuple[int, int, int], T1: LatinSquare, T2: LatinSquare) -> tuple[int, int, int]: ...

def tau1(T1: LatinSquare, T2: LatinSquare, cells_map: dict[object, object]) -> Permutation: ...

def tau2(T1: LatinSquare, T2: LatinSquare, cells_map: dict[object, object]) -> Permutation: ...

def tau3(T1: LatinSquare, T2: LatinSquare, cells_map: dict[object, object]) -> Permutation: ...

def back_circulant(n: int) -> LatinSquare: ...

def forward_circulant(n: int) -> LatinSquare: ...

def direct_product(
    L1: LatinSquare, L2: LatinSquare, L3: LatinSquare, L4: LatinSquare
) -> LatinSquare: ...

def elementary_abelian_2group(s: int) -> LatinSquare: ...

def coin() -> bool: ...

def next_conjugate(L: LatinSquare) -> LatinSquare: ...

def row_containing_sym(L: LatinSquare, c: int, x: int) -> int: ...

def column_containing_sym(L: LatinSquare, r: int, x: int) -> int: ...

def LatinSquare_generator(
    L_start: LatinSquare, check_assertions: bool = ...
) -> Iterator[LatinSquare]: ...

def group_to_LatinSquare(G: Group) -> Matrix: ...

def alternating_group_bitrade_generators(
    m: int,
) -> tuple[Permutation, Permutation, Permutation, PermutationGroup_generic]: ...

def pq_group_bitrade_generators(
    p: int, q: int
) -> tuple[Permutation, Permutation, Permutation, PermutationGroup_generic]: ...

def p3_group_bitrade_generators(
    p: int,
) -> tuple[Permutation, Permutation, Permutation, PermutationGroup_generic]: ...

def check_bitrade_generators(
    a: Permutation, b: Permutation, c: Permutation
) -> bool: ...

def is_bitrade(T1: LatinSquare, T2: LatinSquare) -> bool: ...

def is_primary_bitrade(
    a: Permutation, b: Permutation, c: Permutation, G: PermutationGroup_generic
) -> bool: ...

def tau_to_bitrade(
    t1: Permutation, t2: Permutation, t3: Permutation
) -> tuple[LatinSquare, LatinSquare]: ...

def bitrade_from_group(
    a: Permutation, b: Permutation, c: Permutation, G: PermutationGroup_generic
) -> tuple[LatinSquare, LatinSquare]: ...

def is_disjoint(T1: LatinSquare, T2: LatinSquare) -> bool: ...

def is_same_shape(T1: LatinSquare, T2: LatinSquare) -> bool: ...

def is_row_and_col_balanced(T1: LatinSquare, T2: LatinSquare) -> bool: ...

def dlxcpp_rows_and_map(P: LatinSquare) -> tuple[list[list[int]], dict[object, object]]: ...

def dlxcpp_find_completions(
    P: LatinSquare, nr_to_find: int | None = ...
) -> list[LatinSquare]: ...

def bitrade(T1: LatinSquare, T2: LatinSquare) -> tuple[LatinSquare, LatinSquare]: ...
