# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BackendIPython:
    def install(self, **kwds: builtins.object) -> _SageObject: ...
    def set_underscore_variable(self, obj: builtins.object) -> _SageObject: ...
    def display_immediately(self, plain_text: builtins.object, rich_output: builtins.object) -> _SageObject: ...

class BackendIPythonCommandline:
    def default_preferences(self) -> _SageObject: ...
    def supported_output(self) -> _SageObject: ...
    def displayhook(self, plain_text: builtins.object, rich_output: builtins.object) -> _SageObject: ...
    def display_immediately(self, plain_text: builtins.object, rich_output: builtins.object) -> _SageObject: ...
    def launch_viewer(self, image_file: builtins.object, plain_text: builtins.object) -> _SageObject: ...
    def launch_jmol(self, output_jmol: builtins.object, plain_text: builtins.object) -> _SageObject: ...
    def is_in_terminal(self) -> builtins.bool: ...
    def threejs_offline_scripts(self) -> _SageObject: ...

IFRAME_TEMPLATE: _SageObject
class BackendIPythonNotebook:
    def supported_output(self) -> _SageObject: ...
    def displayhook(self, plain_text: builtins.object, rich_output: builtins.object) -> _SageObject: ...
    def threejs_offline_scripts(self) -> _SageObject: ...
