# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class OutputImagePng:
    def __init__(self, png: builtins.object) -> None: ...
    @classmethod
    def example(cls) -> _SageObject: ...

class OutputImageGif:
    def __init__(self, gif: builtins.object) -> None: ...
    @classmethod
    def example(cls) -> _SageObject: ...
    def html_fragment(self) -> _SageObject: ...

class OutputImageJpg:
    def __init__(self, jpg: builtins.object) -> None: ...
    @classmethod
    def example(cls) -> _SageObject: ...

class OutputImageSvg:
    def __init__(self, svg: builtins.object) -> None: ...
    @classmethod
    def example(cls) -> _SageObject: ...

class OutputImagePdf:
    def __init__(self, pdf: builtins.object) -> None: ...
    @classmethod
    def example(cls) -> _SageObject: ...

class OutputImageDvi:
    def __init__(self, dvi: builtins.object) -> None: ...
    @classmethod
    def example(cls) -> _SageObject: ...
