# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Property:
    def __init__(self, name: builtins.str, allowed_values: builtins.object, doc: builtins.object = ...) -> None: ...
    def getter(self, prefs: builtins.object) -> _SageObject: ...
    def setter(self, prefs: builtins.object, value: builtins.object) -> _SageObject: ...
    def deleter(self, prefs: builtins.object) -> _SageObject: ...

class PreferencesABC:
    def __init__(self, *args: builtins.object, **kwds: builtins.object) -> None: ...
    def available_options(self) -> _SageObject: ...

class DisplayPreferences:
    ...
