# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

Infinity: _SageObject
MInfinity: _SageObject
class IntegerListsBackend:
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __getstate__(self) -> _SageObject: ...
    def __setstate__(self, state: builtins.object) -> _SageObject: ...

class Envelope:
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def limit_start(self) -> _SageObject: ...
    def limit(self) -> _SageObject: ...
    def __call__(self, k: builtins.object) -> _SageObject: ...
    def adapt(self, m: builtins.object, j: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
