from ..generic.morphism import SchemeMorphism_polynomial


class SchemeMorphism_polynomial_projective_space(SchemeMorphism_polynomial): ...

class SchemeMorphism_polynomial_projective_space_field(SchemeMorphism_polynomial_projective_space): ...

class SchemeMorphism_polynomial_projective_space_finite_field(SchemeMorphism_polynomial_projective_space_field): ...

class SchemeMorphism_polynomial_projective_subscheme_field(SchemeMorphism_polynomial_projective_space_field): ...
