from sage.rings.ring import CommutativeRing
from sage.rings.polynomial.multi_polynomial_ring_base import MPolynomialRing_base
from sage.schemes.generic.morphism import SchemeMorphism_point

class ProjectiveSpace_abstract:
    def dimension(self) -> int: ...
    def base_ring(self) -> CommutativeRing: ...
    def coordinate_ring(self) -> MPolynomialRing_base: ...
    def point(self, v: list[object]) -> SchemeMorphism_point: ...
