from collections.abc import Iterator

from sage.categories.groups import Groups
from sage.groups.matrix_gps.group_element import MatrixGroupElement_gap
from sage.groups.matrix_gps.matrix_group_gap import MatrixGroup_gap
from sage.groups.perm_gps.permgroup import PermutationGroup_generic
from sage.rings.integer import Integer
from sage.structure.parent import MembershipInput

class FinitelyGeneratedMatrixGroup_gap(
    MatrixGroup_gap,
    Groups.ParentMethods[MatrixGroupElement_gap],
):
    def as_permutation_group(self, algorithm: str | None = ..., seed: int | None = ...) -> PermutationGroup_generic: ...
    def order(self) -> Integer: ...
    def gens(self) -> tuple[MatrixGroupElement_gap, ...]: ...
    def ngens(self) -> int: ...
    def is_finite(self) -> bool: ...
    def structure_description(self) -> str: ...
    def conjugacy_classes_representatives(self) -> tuple[MatrixGroupElement_gap, ...]: ...
    def list(self) -> list[MatrixGroupElement_gap]: ...
    def __iter__(self) -> Iterator[MatrixGroupElement_gap]: ...
    def __contains__(self, x: MembershipInput) -> bool: ...
