# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class HeisenbergGroup:
    @staticmethod
    def __classcall_private__(cls: builtins.object, n: builtins.int = ..., R: builtins.int = ...) -> _SageObject: ...
    def __init__(self, n: builtins.int = ..., R: builtins.int = ...) -> None: ...
    def order(self) -> _SageObject: ...
    cardinality: _SageObject
    def center(self) -> _SageObject: ...
