from sage.matrix.matrix import Matrix
from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.rings.infinity import PlusInfinity
from sage.groups.matrix_gps.named_group import NamedMatrixGroup_generic

def GL(n: int, R: Ring | int, var: str = ...) -> LinearMatrixGroup_generic: ...
def SL(n: int, R: Ring | int, var: str = ...) -> LinearMatrixGroup_generic: ...

class LinearMatrixGroup_generic(NamedMatrixGroup_generic):
    def _check_matrix(self, x: Matrix, *args: object) -> None: ...
    def order(self) -> Integer | PlusInfinity: ...
    def base_ring(self) -> Ring: ...
    def degree(self) -> int: ...
    def random_element(self) -> Matrix: ...
    def gens(self) -> tuple[Matrix, ...]: ...
    cardinality = order
