# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Polyhedron_normaliz:
    def __init__(self, parent: builtins.object, Vrep: builtins.object, Hrep: builtins.object, normaliz_cone: builtins.object = ..., normaliz_data: builtins.object = ..., internal_base_ring: builtins.object = ..., **kwds: builtins.object) -> None: ...
    def __copy__(self) -> Self: ...
    def __getstate__(self) -> _SageObject: ...
    def __setstate__(self, state: builtins.object) -> _SageObject: ...
    def integral_hull(self) -> _SageObject: ...

class Polyhedron_QQ_normaliz:
    def ehrhart_series(self, variable: builtins.str = ...) -> _SageObject: ...
    def hilbert_series(self, grading: builtins.object, variable: builtins.str = ...) -> _SageObject: ...
    def integral_points(self, threshold: builtins.int = ...) -> builtins.tuple[_SageObject, ...]: ...
    def integral_points_generators(self) -> _SageObject: ...

class Polyhedron_ZZ_normaliz:
    ...
