from sage.structure.element import Element

class Polyhedron_cdd(Polyhedron_base):
    def _init_from_Vrepresentation(self, vertices: Element | int | str | bool | None, rays: Element | int | str | bool | None, lines: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _init_from_Hrepresentation(self, ieqs: Element | int | str | bool | None, eqns: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _run_cdd(self, cdd_input_string: Element | int | str | bool | None, cmdline_arg: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _parse_block(self, cddout: Element | int | str | bool | None, header: Element | int | str | bool | None, parser: Element | int | str | bool | None) -> Element: ...
    def _init_from_cdd_output(self, cddout: Element | int | str | bool | None) -> Element: ...

class Polyhedron_QQ_cdd(Polyhedron_cdd, Polyhedron_QQ):
    ...

class Polyhedron_QQ: ...

class Polyhedron_base: ...
