from sage.structure.element import Element
from sage.structure.parent import Parent

class Polyhedron_polymake(Polyhedron_base):
    def _is_zero(self, x: Element) -> Element: ...
    def _is_nonneg(self, x: Element) -> Element: ...
    def _is_positive(self, x: Element) -> Element: ...
    def _init_from_polymake_polytope(self, polymake_polytope: Element | int | str | bool | None) -> Element: ...
    def _init_from_Vrepresentation(self, vertices: Element | int | str | bool | None, rays: Element | int | str | bool | None, lines: Element | int | str | bool | None, minimize: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _polymake_Vrepresentation_data(self, vertices: Element | int | str | bool | None, rays: Element | int | str | bool | None, lines: Element | int | str | bool | None, minimal: Element | int | str | bool | None) -> Element: ...
    def _init_from_Hrepresentation(self, ieqs: Element | int | str | bool | None, eqns: Element | int | str | bool | None, minimize: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _polymake_Hrepresentation_data(self, ieqs: Element | int | str | bool | None, eqns: Element | int | str | bool | None, minimal: Element | int | str | bool | None) -> Element: ...
    def _init_from_Vrepresentation_and_Hrepresentation(self, Vrep: Element | int | str | bool | None, Hrep: Element | int | str | bool | None) -> Element: ...
    def _polymake_polytope_from_Vrepresentation_and_Hrepresentation(self, Vrep: Element | int | str | bool | None, Hrep: Element | int | str | bool | None) -> Element: ...
    def _init_Vrepresentation_from_polymake(self) -> Element: ...
    def _init_Hrepresentation_from_polymake(self) -> Element: ...
    def _from_polymake_polytope(self, parent: Parent, polymake_polytope: Element | int | str | bool | None) -> Element: ...
    def _polymake_(self, polymake: Element | int | str | bool | None) -> Element: ...
    def _test_polymake_pickling(self, tester: Element | int | str | bool | None, other: Element) -> Element: ...

class Polyhedron_QQ_polymake(Polyhedron_polymake, Polyhedron_QQ):
    ...

class Polyhedron_ZZ_polymake(Polyhedron_polymake, Polyhedron_ZZ):
    ...

class Polyhedron_QQ: ...

class Polyhedron_ZZ: ...

class Polyhedron_base: ...
