from sage.structure.element import Element

class Polyhedron_base3(Polyhedron_base2):
    def _init_empty_polyhedron(self) -> Element: ...
    def slack_matrix(self) -> Element: ...
    def incidence_matrix(self) -> Element: ...
    def combinatorial_polyhedron(self) -> Element: ...
    def _test_combinatorial_polyhedron(self, tester: Element | int | str | bool | None) -> Element: ...
    def face_generator(self, face_dimension: Element | int | str | bool | None, algorithm: str) -> Element: ...
    def faces(self, face_dimension: Element | int | str | bool | None) -> Element: ...
    def facets(self) -> Element: ...
    def f_vector(self, num_threads: Element | int | str | bool | None, parallelization_depth: Element | int | str | bool | None, algorithm: str) -> Element: ...
    def bounded_edges(self) -> Element: ...
    def vertex_adjacency_matrix(self, algorithm: str) -> Element: ...
    def facet_adjacency_matrix(self, algorithm: str) -> Element: ...
    def a_maximal_chain(self) -> Element: ...
    def is_simplex(self) -> bool: ...
    def simplicity(self) -> Element: ...
    def is_simple(self) -> bool: ...
    def simpliciality(self) -> Element: ...
    def is_simplicial(self) -> bool: ...
    def is_pyramid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def is_bipyramid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def is_prism(self, certificate: Element | int | str | bool | None) -> bool: ...
    def is_lawrence_polytope(self) -> bool: ...
    def neighborliness(self) -> Element: ...
    def is_neighborly(self, k: int) -> bool: ...
    def join_of_Vrep(self) -> Element: ...
    def meet_of_Hrep(self) -> Element: ...
    def _test_combinatorial_face_as_combinatorial_polyhedron(self, tester: Element | int | str | bool | None) -> Element: ...

class Polyhedron_base2: ...
