from sage.structure.element import Element

class Polyhedron_base1(Polyhedron_base0, ConvexSet_closed):
    def __hash__(self) -> int: ...
    def _repr_(self) -> str: ...
    def _richcmp_(self, other: Element, op: Element | int | str | bool | None) -> Element: ...
    def _is_subpolyhedron(self, other: Element) -> Element: ...
    def is_empty(self) -> bool: ...
    def is_universe(self) -> bool: ...
    def dim(self) -> int: ...
    def Vrepresentation_space(self) -> Element: ...
    def Hrepresentation_space(self) -> Element: ...
    def ambient_vector_space(self, base_field: Element | int | str | bool | None) -> Element: ...
    def ambient_dim(self) -> Element: ...
    def an_affine_basis(self) -> Element: ...
    def a_maximal_chain(self) -> Element: ...
    def representative_point(self) -> Element: ...
    def _some_elements_(self) -> Element: ...
    def contains(self, point: Element | int | str | bool | None) -> bool: ...
    def interior(self) -> Element: ...
    def interior_contains(self, point: Element | int | str | bool | None) -> Element: ...
    def is_relatively_open(self) -> bool: ...
    def relative_interior(self) -> Element: ...
    def relative_interior_contains(self, point: Element | int | str | bool | None) -> Element: ...

class ConvexSet_closed: ...

class Polyhedron_base0: ...
