from sage.structure.element import Element

class Polyhedron_QQ(Polyhedron_base):
    def _is_zero(self, x: Element) -> Element: ...
    def _is_nonneg(self, x: Element) -> Element: ...
    def _is_positive(self, x: Element) -> Element: ...
    def integral_points_count(self, verbose: bool, use_Hrepresentation: Element | int | str | bool | None, explicit_enumeration_threshold: Element | int | str | bool | None, preprocess: Element | int | str | bool | None) -> Element: ...
    def ehrhart_polynomial(self, engine: Element | int | str | bool | None, variable: str, verbose: bool, dual: Element | int | str | bool | None, irrational_primal: Element | int | str | bool | None, irrational_all_primal: Element | int | str | bool | None, maxdet: Element | int | str | bool | None, no_decomposition: Element | int | str | bool | None, compute_vertex_cones: Element | int | str | bool | None, smith_form: Element | int | str | bool | None, dualization: Element | int | str | bool | None, triangulation: Element | int | str | bool | None, triangulation_max_height: Element | int | str | bool | None) -> Element: ...
    def ehrhart_quasipolynomial(self, variable: str, engine: Element | int | str | bool | None, verbose: bool, dual: Element | int | str | bool | None, irrational_primal: Element | int | str | bool | None, irrational_all_primal: Element | int | str | bool | None, maxdet: Element | int | str | bool | None, no_decomposition: Element | int | str | bool | None, compute_vertex_cones: Element | int | str | bool | None, smith_form: Element | int | str | bool | None, dualization: Element | int | str | bool | None, triangulation: Element | int | str | bool | None, triangulation_max_height: Element | int | str | bool | None) -> Element: ...
    def _ehrhart_quasipolynomial_normaliz(self, variable: str) -> Element: ...
    def _ehrhart_polynomial_latte(self, verbose: bool, dual: Element | int | str | bool | None, irrational_primal: Element | int | str | bool | None, irrational_all_primal: Element | int | str | bool | None, maxdet: Element | int | str | bool | None, no_decomposition: Element | int | str | bool | None, compute_vertex_cones: Element | int | str | bool | None, smith_form: Element | int | str | bool | None, dualization: Element | int | str | bool | None, triangulation: Element | int | str | bool | None, triangulation_max_height: Element | int | str | bool | None) -> Element: ...
    def fixed_subpolytope(self, vertex_permutation: Element | int | str | bool | None) -> Element: ...
    def fixed_subpolytopes(self, conj_class_reps: Element | int | str | bool | None) -> Element: ...
    def Hstar_function(self, acting_group: Element | int | str | bool | None, output: Element | int | str | bool | None) -> Element: ...
    def _Hstar_function_normaliz(self, acting_group: Element | int | str | bool | None, output: Element | int | str | bool | None) -> Element: ...
    def is_effective(self, Hstar: Element | int | str | bool | None, Hstar_as_lin_comb: Element | int | str | bool | None) -> bool: ...
    def _is_effective_normaliz(self, Hstar: Element | int | str | bool | None, Hstar_as_lin_comb: Element | int | str | bool | None) -> Element: ...

class Polyhedron_base: ...
