# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Polyhedron_ZZ:
    def __getattribute__(self, name: builtins.str) -> _SageObject: ...
    def __dir__(self) -> _Iterable[builtins.str]: ...
    def is_lattice_polytope(self) -> builtins.bool: ...
    def ehrhart_polynomial(self, engine: builtins.object = ..., variable: builtins.str = ..., verbose: builtins.bool = ..., dual: builtins.object = ..., irrational_primal: builtins.object = ..., irrational_all_primal: builtins.object = ..., maxdet: builtins.object = ..., no_decomposition: builtins.object = ..., compute_vertex_cones: builtins.object = ..., smith_form: builtins.object = ..., dualization: builtins.object = ..., triangulation: builtins.object = ..., triangulation_max_height: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def polar(self) -> _SageObject: ...
    def is_reflexive(self) -> builtins.bool: ...
    def is_terminal(self) -> builtins.bool: ...
    def has_IP_property(self) -> builtins.bool: ...
    def fibration_generator(self, dim: builtins.object) -> _SageObject: ...
    def find_translation(self, translated_polyhedron: builtins.object) -> _SageObject: ...
    def minkowski_decompositions(self) -> builtins.tuple[_SageObject, ...]: ...
    def normal_form(self, algorithm: builtins.str = ..., permutation: builtins.bool = ...) -> _SageObject: ...
