from sage.structure.element import Element

class Polyhedron_base5(Polyhedron_base4):
    def polar(self, in_affine_span: Element | int | str | bool | None) -> Element: ...
    def pyramid(self) -> Element: ...
    def _test_pyramid(self, tester: Element | int | str | bool | None) -> Element: ...
    def bipyramid(self) -> Element: ...
    def _test_bipyramid(self, tester: Element | int | str | bool | None) -> Element: ...
    def prism(self) -> Element: ...
    def _test_prism(self, tester: Element | int | str | bool | None) -> Element: ...
    def truncation(self, cut_frac: Element | int | str | bool | None) -> Element: ...
    def lawrence_polytope(self) -> Element: ...
    def deformation_cone(self) -> Element: ...
    def minkowski_sum(self, other: Element) -> Element: ...
    def minkowski_difference(self, other: Element) -> Element: ...
    def product(self, other: Element) -> Element: ...
    def _test_product(self, tester: Element | int | str | bool | None) -> Element: ...
    def join(self, other: Element) -> Element: ...
    def subdirect_sum(self, other: Element) -> Element: ...
    def direct_sum(self, other: Element) -> Element: ...
    def convex_hull(self, other: Element) -> Element: ...
    def intersection(self, other: Element) -> Element: ...
    def _acted_upon_(self, actor: Element | int | str | bool | None, self_on_left: Element | int | str | bool | None) -> Element: ...
    def translation(self, displacement: Element | int | str | bool | None) -> Element: ...
    def _translation_double_description(self, displacement: Element | int | str | bool | None) -> Element: ...
    def dilation(self, scalar: Element | int | str | bool | None) -> Element: ...
    def _test_dilation(self, tester: Element | int | str | bool | None) -> Element: ...
    def linear_transformation(self, linear_transf: Element | int | str | bool | None, new_base_ring: Element | int | str | bool | None) -> Element: ...
    def _test_linear_transformation(self, tester: Element | int | str | bool | None) -> Element: ...
    def face_truncation(self, face: Element | int | str | bool | None, linear_coefficients: Element | int | str | bool | None, cut_frac: Element | int | str | bool | None) -> Element: ...
    def stack(self, face: Element | int | str | bool | None, position: Element | int | str | bool | None) -> Element: ...
    def wedge(self, face: Element | int | str | bool | None, width: Element | int | str | bool | None) -> Element: ...
    def face_split(self, face: Element | int | str | bool | None) -> Element: ...
    def lawrence_extension(self, v: Element) -> Element: ...
    def _test_lawrence(self, tester: Element | int | str | bool | None) -> Element: ...
    def one_point_suspension(self, vertex: Element | int | str | bool | None) -> Element: ...

class Polyhedron_base4: ...
