from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class Polyhedron_base0(Element, SageObject):
    def _init_from_Vrepresentation(self, vertices: Element | int | str | bool | None, rays: Element | int | str | bool | None, lines: Element | int | str | bool | None) -> Element: ...
    def _init_from_Hrepresentation(self, ieqs: Element | int | str | bool | None, eqns: Element | int | str | bool | None) -> Element: ...
    def _init_empty_polyhedron(self) -> Element: ...
    def _delete(self) -> Element: ...
    def _sage_input_(self, sib: Element | int | str | bool | None, coerced: Element | int | str | bool | None) -> Element: ...
    def base_extend(self, base_ring: Ring, backend: Element | int | str | bool | None) -> Element: ...
    def change_ring(self, base_ring: Ring, backend: Element | int | str | bool | None) -> Element: ...
    def is_mutable(self) -> bool: ...
    def is_immutable(self) -> bool: ...
    def n_equations(self) -> Element: ...
    def n_inequalities(self) -> Element: ...
    def n_vertices(self) -> Element: ...
    def n_rays(self) -> int: ...
    def n_lines(self) -> int: ...
    def is_compact(self) -> bool: ...
    def Hrepresentation(self, index: int) -> Element: ...
    def Hrepresentation_str(self, separator: Element | int | str | bool | None, latex: Element | int | str | bool | None, style: Element | int | str | bool | None, align: Element | int | str | bool | None) -> Element: ...
    def Hrep_generator(self) -> Element: ...
    def n_Hrepresentation(self) -> Element: ...
    def Vrepresentation(self, index: int) -> Element: ...
    def n_Vrepresentation(self) -> Element: ...
    def Vrep_generator(self) -> Element: ...
    def inequality_generator(self) -> Element: ...
    def inequalities(self) -> Element: ...
    def inequalities_list(self) -> Element: ...
    def equation_generator(self) -> Element: ...
    def equations(self) -> Element: ...
    def equations_list(self) -> Element: ...
    def vertices_list(self) -> Element: ...
    def vertex_generator(self) -> Element: ...
    def vertices(self) -> Element: ...
    def vertices_matrix(self, base_ring: Ring) -> Element: ...
    def ray_generator(self) -> Element: ...
    def rays(self) -> Element: ...
    def rays_list(self) -> Element: ...
    def line_generator(self) -> Element: ...
    def lines(self) -> Element: ...
    def lines_list(self) -> Element: ...
    def backend(self) -> Element: ...
    def cdd_Hrepresentation(self) -> Element: ...
    def write_cdd_Hrepresentation(self, filename: Element | int | str | bool | None) -> Element: ...
    def cdd_Vrepresentation(self) -> Element: ...
    def write_cdd_Vrepresentation(self, filename: Element | int | str | bool | None) -> Element: ...
