from sage.structure.element import Element

class Polyhedron_base_number_field(Polyhedron_base):
    def _compute_data_lists_and_internal_base_ring(self, data_lists: Element | int | str | bool | None, convert_QQ: Element | int | str | bool | None, convert_NF: Element | int | str | bool | None) -> Element: ...

class Polyhedron_base: ...
