from sage.structure.element import Element

class Polyhedron_base2(Polyhedron_base1):
    def is_lattice_polytope(self) -> bool: ...
    def lattice_polytope(self, envelope: Element | int | str | bool | None) -> Element: ...
    def _integral_points_PALP(self) -> Element: ...
    def h_star_vector(self) -> Element: ...
    def _h_star_vector_normaliz(self) -> Element: ...
    def integral_points_count(self) -> Element: ...
    def integral_points(self, threshold: Element | int | str | bool | None) -> Element: ...
    def get_integral_point(self, index: int) -> Element: ...
    def random_integral_point(self) -> Element: ...
    def generating_function_of_integral_points(self) -> Element: ...

class Polyhedron_base1: ...
