# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LatticePolytopeError(Exception):
    ...

class LatticePolytopesNotIsomorphicError(Exception):
    ...

class LatticePolytopeNoEmbeddingError(Exception):
    ...

class LatticeEuclideanGroupElement:
    def __init__(self, A: builtins.object, b: builtins.object) -> None: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def domain_dim(self) -> _SageObject: ...
    def codomain_dim(self) -> _SageObject: ...
