from collections.abc import Iterator

from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class PALPreader(SageObject):
    def _palp_Popen(self) -> Element: ...
    def _read_vertices(self, stdout: Element | int | str | bool | None, rows: Element | int | str | bool | None, cols: Element | int | str | bool | None) -> Element: ...
    def _read_vertices_transposed(self, stdout: Element | int | str | bool | None, rows: Element | int | str | bool | None, cols: Element | int | str | bool | None) -> Element: ...
    def _iterate_list(self, start: Element | int | str | bool | None, stop: Element | int | str | bool | None, step: Element | int | str | bool | None) -> Element: ...
    def _iterate_Polyhedron(self, start: Element | int | str | bool | None, stop: Element | int | str | bool | None, step: Element | int | str | bool | None) -> Element: ...
    def _iterate_PPL(self, start: Element | int | str | bool | None, stop: Element | int | str | bool | None, step: Element | int | str | bool | None) -> Element: ...
    def _iterate_PointCollection(self, start: Element | int | str | bool | None, stop: Element | int | str | bool | None, step: Element | int | str | bool | None) -> Element: ...
    def _iterate(self, output: Element | int | str | bool | None) -> Element: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __getitem__(self, item: Element | int | str | bool | None) -> Element: ...

class Reflexive4dHodge(PALPreader):
    ...
