from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.parent import Parent

def Polyhedra(ambient_space_or_base_ring: Element | int | str | bool | None, ambient_dim: Element | int | str | bool | None, backend: Element | int | str | bool | None) -> Element: ...
def does_backend_handle_base_ring(base_ring: Ring, backend: Element | int | str | bool | None) -> Element: ...

type _BuiltinList[_T] = list[_T]
class Polyhedra_base(UniqueRepresentation, Parent):
    def list(self) -> _BuiltinList[Element]: ...
    def recycle(self, polyhedron: Element | int | str | bool | None) -> Element: ...
    def ambient_dim(self) -> Element: ...
    def backend(self) -> Element: ...
    def an_element(self) -> Element: ...
    def some_elements(self) -> _BuiltinList[Element]: ...
    def zero(self) -> Element: ...
    def empty(self) -> Element: ...
    def universe(self) -> Element: ...
    def Vrepresentation_space(self) -> Element: ...
    def Hrepresentation_space(self) -> Element: ...
    def _repr_base_ring(self) -> str: ...
    def _repr_ambient_module(self) -> str: ...
    def _repr_(self) -> str: ...
    def _element_constructor_(self) -> Element: ...
    def _element_constructor_polyhedron(self, polyhedron: Element | int | str | bool | None) -> Element: ...
    def base_extend(self, base_ring: Ring, backend: Element | int | str | bool | None, ambient_dim: Element | int | str | bool | None) -> Element: ...
    def change_ring(self, base_ring: Ring, backend: Element | int | str | bool | None, ambient_dim: Element | int | str | bool | None) -> Element: ...
    def _coerce_base_ring(self, other: Element) -> Element: ...
    def _coerce_map_from_(self, X: Element | int | str | bool | None) -> Element: ...
    def _get_action_(self, other: Element, op: Element | int | str | bool | None, self_is_left: Element | int | str | bool | None) -> Element: ...
    def _make_Inequality(self, polyhedron: Element | int | str | bool | None, data: Element | int | str | bool | None) -> Element: ...
    def _make_Equation(self, polyhedron: Element | int | str | bool | None, data: Element | int | str | bool | None) -> Element: ...
    def _make_Vertex(self, polyhedron: Element | int | str | bool | None, data: Element | int | str | bool | None) -> Element: ...
    def _make_Ray(self, polyhedron: Element | int | str | bool | None, data: Element | int | str | bool | None) -> Element: ...
    def _make_Line(self, polyhedron: Element | int | str | bool | None, data: Element | int | str | bool | None) -> Element: ...

class Polyhedra_ZZ_ppl(Polyhedra_base):
    ...

class Polyhedra_ZZ_normaliz(Polyhedra_base):
    ...

class Polyhedra_QQ_ppl(Polyhedra_base):
    ...

class Polyhedra_QQ_normaliz(Polyhedra_base):
    ...

class Polyhedra_QQ_cdd(Polyhedra_base):
    ...

class Polyhedra_RDF_cdd(Polyhedra_base):
    ...

class Polyhedra_normaliz(Polyhedra_base):
    ...

class Polyhedra_polymake(Polyhedra_base):
    ...

class Polyhedra_field(Polyhedra_base):
    ...

class Polyhedra_number_field(Polyhedra_base):
    ...

class UniqueRepresentation: ...
