from sage.rings.integer import Integer
from sage.structure.element import Element

def polar_P2_polytope() -> Element: ...
def polar_P1xP1_polytope() -> Element: ...
def polar_P2_112_polytope() -> Element: ...
def subpolygons_of_polar_P2() -> Element: ...
def subpolygons_of_polar_P2_112() -> Element: ...
def subpolygons_of_polar_P1xP1() -> Element: ...
def sub_reflexive_polygons() -> Element: ...

class LatticePolygon_PPL_class(LatticePolytope_PPL_class):
    def ordered_vertices(self) -> Integer: ...
    def _find_isomorphism_degenerate(self, polytope: Element | int | str | bool | None) -> Element: ...
    def _find_cyclic_isomorphism_matching_edge(self, polytope: Element | int | str | bool | None, polytope_origin: Element | int | str | bool | None, p_ray_left: Element | int | str | bool | None, p_ray_right: Element | int | str | bool | None) -> Element: ...
    def find_isomorphism(self, polytope: Element | int | str | bool | None) -> Element: ...
    def is_isomorphic(self, polytope: Element | int | str | bool | None) -> bool: ...
    def sub_polytopes(self) -> Element: ...
    def plot(self) -> Element: ...

class LatticePolytope_PPL_class: ...
