import builtins

class _SageObject: ...

class LatticePolygon_PPL_class:
    def ordered_vertices(self) -> _SageObject: ...
    def find_isomorphism(self, polytope: builtins.object) -> _SageObject: ...
    def is_isomorphic(self, polytope: builtins.object) -> builtins.bool: ...
    def sub_polytopes(self) -> _SageObject: ...
    def plot(self) -> _SageObject: ...

def polar_P2_polytope(self) -> _SageObject: ...
def polar_P1xP1_polytope(self) -> _SageObject: ...
def polar_P2_112_polytope(self) -> _SageObject: ...
def subpolygons_of_polar_P2(self) -> _SageObject: ...
def subpolygons_of_polar_P2_112(self) -> _SageObject: ...
def subpolygons_of_polar_P1xP1(self) -> _SageObject: ...
def sub_reflexive_polygons(self) -> _SageObject: ...
