# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def LatticePolytope_PPL(*args: builtins.object) -> _SageObject: ...

class LatticePolytope_PPL_class:
    def is_bounded(self) -> builtins.bool: ...
    def n_vertices(self) -> _SageObject: ...
    def is_simplex(self) -> builtins.bool: ...
    def bounding_box(self) -> _SageObject: ...
    def n_integral_points(self) -> _SageObject: ...
    def integral_points(self) -> _SageObject: ...
    def integral_points_not_interior_to_facets(self) -> _SageObject: ...
    def vertices(self) -> _SageObject: ...
    def vertices_saturating(self, constraint: builtins.object) -> _SageObject: ...
    def is_full_dimensional(self) -> builtins.bool: ...
    def fibration_generator(self, dim: builtins.object) -> _SageObject: ...
    def pointsets_mod_automorphism(self, pointsets: builtins.object) -> _SageObject: ...
    def ambient_space(self) -> _SageObject: ...
    def contains(self, point_coordinates: builtins.object) -> _SageObject: ...
    def contains_origin(self) -> _SageObject: ...
    def affine_space(self) -> _SageObject: ...
    def affine_lattice_polytope(self) -> _SageObject: ...
    def base_projection(self, fiber: builtins.object) -> _SageObject: ...
    def base_projection_matrix(self, fiber: builtins.object) -> _SageObject: ...
    def base_rays(self, fiber: builtins.object, points: builtins.object) -> _SageObject: ...
    def has_IP_property(self) -> builtins.bool: ...
    def restricted_automorphism_group(self, vertex_labels: builtins.object = ...) -> _SageObject: ...
    def lattice_automorphism_group(self, points: builtins.object = ..., point_labels: builtins.object = ...) -> _SageObject: ...
    def sub_polytope_generator(self) -> _SageObject: ...
    def embed_in_reflexive_polytope(self, output: builtins.str = ...) -> _SageObject: ...
