import builtins

class _SageObject: ...

def CompleteMatchings(self) -> _SageObject: ...
def matchingsset(self) -> _SageObject: ...
def dcrossing(self) -> _SageObject: ...
def setp_to_edges(self) -> _SageObject: ...
def dcrossvec_setp(self) -> _SageObject: ...
def dcrossvec_cm(self) -> _SageObject: ...
def tablecolumn(self, k: builtins.int) -> _SageObject: ...
