# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class stl_int_vector:
    def __cinit__(self) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def sum(self) -> _SageObject: ...
    def __richcmp__(left: builtins.object, right: builtins.object, op: builtins.object) -> _SageObject: ...
