# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def BullGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def ButterflyGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def CircularLadderGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def ClawGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def CycleGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def CompleteGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def CorrelationGraph(seqs: builtins.object, alpha: builtins.object, include_anticorrelation: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def CompleteBipartiteGraph(p: builtins.int, q: builtins.int, set_position: builtins.bool = ..., immutable: builtins.bool = ..., name: builtins.str = ...) -> _SageObject: ...

def CompleteMultipartiteGraph(L: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def DiamondGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def GemGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def ForkGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def DartGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def EmptyGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def ToroidalGrid2dGraph(p: builtins.int, q: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def Toroidal6RegularGrid2dGraph(p: builtins.int, q: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def Grid2dGraph(p: builtins.int, q: builtins.int, set_positions: builtins.bool = ..., immutable: builtins.bool = ..., name: builtins.str = ...) -> _SageObject: ...

def GridGraph(dim_list: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def HouseGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def HouseXGraph(immutable: builtins.bool = ...) -> _SageObject: ...

def LadderGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def MoebiusLadderGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def PathGraph(n: builtins.int, pos: builtins.object = ..., immutable: builtins.bool = ..., name: builtins.str = ...) -> _SageObject: ...

def StarGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...
