from sage.structure.element import Element

def BullGraph(immutable: Element | int | str | bool | None) -> Element: ...
def ButterflyGraph(immutable: Element | int | str | bool | None) -> Element: ...
def CircularLadderGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def ClawGraph(immutable: Element | int | str | bool | None) -> Element: ...
def CycleGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def CompleteGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def CorrelationGraph(seqs: Element | int | str | bool | None, alpha: Element | int | str | bool | None, include_anticorrelation: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def CompleteBipartiteGraph(p: int, q: int, set_position: Element | int | str | bool | None, immutable: Element | int | str | bool | None, name: str) -> Element: ...
def CompleteMultipartiteGraph(L: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def DiamondGraph(immutable: Element | int | str | bool | None) -> Element: ...
def GemGraph(immutable: Element | int | str | bool | None) -> Element: ...
def ForkGraph(immutable: Element | int | str | bool | None) -> Element: ...
def DartGraph(immutable: Element | int | str | bool | None) -> Element: ...
def EmptyGraph(immutable: Element | int | str | bool | None) -> Element: ...
def ToroidalGrid2dGraph(p: int, q: int, immutable: Element | int | str | bool | None) -> Element: ...
def Toroidal6RegularGrid2dGraph(p: int, q: int, immutable: Element | int | str | bool | None) -> Element: ...
def Grid2dGraph(p: int, q: int, set_positions: Element | int | str | bool | None, immutable: Element | int | str | bool | None, name: str) -> Element: ...
def GridGraph(dim_list: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def HouseGraph(immutable: Element | int | str | bool | None) -> Element: ...
def HouseXGraph(immutable: Element | int | str | bool | None) -> Element: ...
def LadderGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def MoebiusLadderGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def PathGraph(n: int, pos: Element | int | str | bool | None, immutable: Element | int | str | bool | None, name: str) -> Element: ...
def StarGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
