import builtins

class _SageObject: ...

def SymplecticPolarGraph(
    self, q: builtins.int, algorithm: builtins.str = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def AffineOrthogonalPolarGraph(
    self, q: builtins.int, sign: builtins.str = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def OrthogonalPolarGraph(
    self, q: builtins.int, sign: builtins.str = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def NonisotropicOrthogonalPolarGraph(
    self,
    q: builtins.int,
    sign: builtins.str = ...,
    perp: builtins.object = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def UnitaryPolarGraph(
    self, q: builtins.int, algorithm: builtins.str = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def NonisotropicUnitaryPolarGraph(
    self, q: builtins.int, immutable: builtins.bool = ...
) -> _SageObject: ...
def UnitaryDualPolarGraph(
    self, q: builtins.int, immutable: builtins.bool = ...
) -> _SageObject: ...
def SymplecticDualPolarGraph(
    self, q: builtins.int, immutable: builtins.bool = ...
) -> _SageObject: ...
def TaylorTwographDescendantSRG(
    self, clique_partition: builtins.bool = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def TaylorTwographSRG(self, immutable: builtins.bool = ...) -> _SageObject: ...
def AhrensSzekeresGeneralizedQuadrangleGraph(
    self, dual: builtins.bool = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def T2starGeneralizedQuadrangleGraph(
    self,
    dual: builtins.bool = ...,
    hyperoval: builtins.object = ...,
    field: builtins.object = ...,
    check_hyperoval: builtins.bool = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def HaemersGraph(
    self,
    hyperoval: builtins.object = ...,
    hyperoval_matching: builtins.object = ...,
    field: builtins.object = ...,
    check_hyperoval: builtins.bool = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def CossidentePenttilaGraph(self, immutable: builtins.bool = ...) -> _SageObject: ...
def Nowhere0WordsTwoWeightCodeGraph(
    self,
    hyperoval: builtins.object = ...,
    field: builtins.object = ...,
    check_hyperoval: builtins.bool = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def OrthogonalDualPolarGraph(
    self, d: builtins.object, q: builtins.int, immutable: builtins.bool = ...
) -> _SageObject: ...
