from sage.structure.element import Element

def DegreeSequence(deg_sequence: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def DegreeSequenceBipartite(s1: Element | int | str | bool | None, s2: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def DegreeSequenceConfigurationModel(deg_sequence: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def DegreeSequenceTree(deg_sequence: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def DegreeSequenceExpected(deg_sequence: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
