from sage.structure.element import Element

def cocliques_HoffmannSingleton(immutable: Element | int | str | bool | None) -> Element: ...
def locally_GQ42_distance_transitive_graph(immutable: Element | int | str | bool | None) -> Element: ...
def ConwaySmith_for_3S7(immutable: Element | int | str | bool | None) -> Element: ...
def has_edge(u: Element | int | str | bool | None, v: Element) -> bool: ...
def graph_3O73(immutable: Element | int | str | bool | None) -> Element: ...
def FosterGraph3S6(immutable: Element | int | str | bool | None) -> Element: ...
def J2Graph(immutable: Element | int | str | bool | None) -> Element: ...
def IvanovIvanovFaradjevGraph(immutable: Element | int | str | bool | None) -> Element: ...
def LargeWittGraph(immutable: Element | int | str | bool | None) -> Element: ...
def TruncatedWittGraph(immutable: Element | int | str | bool | None) -> Element: ...
def DoublyTruncatedWittGraph(immutable: Element | int | str | bool | None) -> Element: ...
def distance_3_doubly_truncated_Golay_code_graph(immutable: Element | int | str | bool | None) -> Element: ...
def shortened_00_11_binary_Golay_code_graph(immutable: Element | int | str | bool | None) -> Element: ...
def shortened_000_111_extended_binary_Golay_code_graph(immutable: Element | int | str | bool | None) -> Element: ...
def vanLintSchrijverGraph(immutable: Element | int | str | bool | None) -> Element: ...
def LeonardGraph(immutable: Element | int | str | bool | None) -> Element: ...
def UstimenkoGraph(m: int, q: int, immutable: Element | int | str | bool | None) -> Element: ...
def BilinearFormsGraph(d: int, e: Element, q: int, immutable: Element | int | str | bool | None) -> Element: ...
def AlternatingFormsGraph(n: int, q: int, immutable: Element | int | str | bool | None) -> Element: ...
def HermitianFormsGraph(n: int, r: int, immutable: Element | int | str | bool | None) -> Element: ...
def build_mat(v: Element, w: Element) -> Element: ...
def DoubleOddGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def HalfCube(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def DoubleGrassmannGraph(q: int, e: Element, immutable: Element | int | str | bool | None) -> Element: ...
def is_from_GQ_spread(arr: Element | int | str | bool | None) -> bool: ...
def graph_from_GQ_spread(s: int, t: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def GeneralisedDodecagonGraph(s: int, t: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def GeneralisedOctagonGraph(s: int, t: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def GeneralisedHexagonGraph(s: int, t: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def is_classical_parameters_graph(array: Element | int | str | bool | None) -> bool: ...
def integral_log(x: Element, b: Element) -> Element: ...
def check_parameters(d: int, b: Element, alpha: Element | int | str | bool | None, beta: Element | int | str | bool | None, arr: Element | int | str | bool | None) -> Element: ...
def b_(i: int) -> Element: ...
def c_(i: int) -> Element: ...
def a_(i: int) -> Element: ...
def is_pseudo_partition_graph(arr: Element | int | str | bool | None) -> bool: ...
def pseudo_partition_graph(m: int, a: Element, immutable: Element | int | str | bool | None) -> Element: ...
def is_near_polygon(array: Element | int | str | bool | None) -> bool: ...
def near_polygon_graph(family: Element | int | str | bool | None, params: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def distance_regular_graph(arr: Element | int | str | bool | None, existence: Element | int | str | bool | None, check: bool) -> Element: ...
def result(G: Element | int | str | bool | None) -> Element: ...
def is_iterable(obj: Element | int | str | bool | None) -> bool: ...
