from sage.structure.element import Element

def JohnsonGraph(n: int, k: int, immutable: Element | int | str | bool | None) -> Element: ...
def KneserGraph(n: int, k: int, immutable: Element | int | str | bool | None, name: str) -> Element: ...
def FurerGadget(k: int, prefix: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def CaiFurerImmermanGraph(G: Element | int | str | bool | None, twisted: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def EgawaGraph(p: int, s: int, immutable: Element | int | str | bool | None) -> Element: ...
def HammingGraph(n: int, q: int, X: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def BarbellGraph(n1: Element | int | str | bool | None, n2: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def LollipopGraph(n1: Element | int | str | bool | None, n2: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def TadpoleGraph(n1: Element | int | str | bool | None, n2: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def AztecDiamondGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def DipoleGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def BubbleSortGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def chang_graphs(immutable: Element | int | str | bool | None) -> Element: ...
def CirculantGraph(n: int, adjacency: Element | int | str | bool | None, immutable: Element | int | str | bool | None, name: str) -> Element: ...
def CubeGraph(n: int, embedding: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def GoethalsSeidelGraph(k: int, r: int, immutable: Element | int | str | bool | None) -> Element: ...
def DorogovtsevGoltsevMendesGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def FoldedCubeGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def FriendshipGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def FuzzyBallGraph(partition: Element | int | str | bool | None, q: int, immutable: Element | int | str | bool | None) -> Element: ...
def GeneralizedPetersenGraph(n: int, k: int, immutable: Element | int | str | bool | None, name: str) -> Element: ...
def IGraph(n: int, j: int, k: int, immutable: Element | int | str | bool | None) -> Element: ...
def DoubleGeneralizedPetersenGraph(n: int, k: int, immutable: Element | int | str | bool | None) -> Element: ...
def RoseWindowGraph(n: int, a: Element, r: int, immutable: Element | int | str | bool | None) -> Element: ...
def TabacjnGraph(n: int, a: Element, b: Element, r: int, immutable: Element | int | str | bool | None) -> Element: ...
def HararyGraph(k: int, n: int, immutable: Element | int | str | bool | None) -> Element: ...
def HyperStarGraph(n: int, k: int, immutable: Element | int | str | bool | None) -> Element: ...
def LCFGraph(n: int, shift_list: Element | int | str | bool | None, repeats: Element | int | str | bool | None, immutable: Element | int | str | bool | None, name: str) -> Element: ...
def MycielskiGraph(k: int, relabel: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def MycielskiStep(g: Element, immutable: Element | int | str | bool | None) -> Element: ...
def NKStarGraph(n: int, k: int, immutable: Element | int | str | bool | None) -> Element: ...
def NStarGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def OddGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def PaleyGraph(q: int, immutable: Element | int | str | bool | None) -> Element: ...
def PasechnikGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def SquaredSkewHadamardMatrixGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def SwitchedSquaredSkewHadamardMatrixGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def HanoiTowerGraph(pegs: Element | int | str | bool | None, disks: Element | int | str | bool | None, labels: Element | int | str | bool | None, positions: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def line_graph_forbidden_subgraphs(immutable: Element | int | str | bool | None) -> Element: ...
def petersen_family(generate: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def p2_forbidden_minors(immutable: Element | int | str | bool | None) -> Element: ...
def SierpinskiGasketGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def GeneralizedSierpinskiGraph(G: Element | int | str | bool | None, k: int, stretch: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def WheelGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def WindmillGraph(k: int, n: int, immutable: Element | int | str | bool | None) -> Element: ...
def RingedTree(k: int, vertex_labels: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def MathonPseudocyclicMergingGraph(M: Element | int | str | bool | None, t: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def MathonPseudocyclicStronglyRegularGraph(t: Element | int | str | bool | None, G: Element | int | str | bool | None, L: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def TuranGraph(n: int, r: int, immutable: Element | int | str | bool | None) -> Element: ...
def MuzychukS6Graph(n: int, d: int, Phi: Element | int | str | bool | None, Sigma: Element | int | str | bool | None, verbose: bool, immutable: Element | int | str | bool | None) -> Element: ...
def CubeConnectedCycle(d: int, immutable: Element | int | str | bool | None) -> Element: ...
def StaircaseGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def BiwheelGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
def TruncatedBiwheelGraph(n: int, immutable: Element | int | str | bool | None) -> Element: ...
