# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def JohnsonGraph(n: builtins.int, k: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def KneserGraph(n: builtins.int, k: builtins.int, immutable: builtins.bool = ..., name: builtins.str = ...) -> _SageObject: ...

def FurerGadget(k: builtins.int, prefix: builtins.str = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def CaiFurerImmermanGraph(G: builtins.object, twisted: builtins.bool = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def EgawaGraph(p: builtins.int, s: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def HammingGraph(n: builtins.int, q: builtins.int, X: builtins.object = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def BarbellGraph(n1: builtins.object, n2: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def LollipopGraph(n1: builtins.object, n2: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def TadpoleGraph(n1: builtins.object, n2: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def AztecDiamondGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def DipoleGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def BubbleSortGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def chang_graphs(immutable: builtins.bool = ...) -> _SageObject: ...

def CirculantGraph(n: builtins.int, adjacency: builtins.object, immutable: builtins.bool = ..., name: builtins.str = ...) -> _SageObject: ...

def CubeGraph(n: builtins.int, embedding: builtins.int = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def GoethalsSeidelGraph(k: builtins.int, r: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def DorogovtsevGoltsevMendesGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def FoldedCubeGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def FriendshipGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def FuzzyBallGraph(partition: builtins.object, q: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def GeneralizedPetersenGraph(n: builtins.int, k: builtins.int, immutable: builtins.bool = ..., name: builtins.str = ...) -> _SageObject: ...

def IGraph(n: builtins.int, j: builtins.int, k: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def DoubleGeneralizedPetersenGraph(n: builtins.int, k: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def RoseWindowGraph(n: builtins.int, a: builtins.object, r: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def TabacjnGraph(n: builtins.int, a: builtins.object, b: builtins.object, r: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def HararyGraph(k: builtins.int, n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def HyperStarGraph(n: builtins.int, k: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def LCFGraph(n: builtins.int, shift_list: builtins.object, repeats: builtins.object, immutable: builtins.bool = ..., name: builtins.str = ...) -> _SageObject: ...

def MycielskiGraph(k: builtins.int = ..., relabel: builtins.bool = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def MycielskiStep(g: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def NKStarGraph(n: builtins.int, k: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def NStarGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def OddGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def PaleyGraph(q: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def PasechnikGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def SquaredSkewHadamardMatrixGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def SwitchedSquaredSkewHadamardMatrixGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def HanoiTowerGraph(pegs: builtins.object, disks: builtins.object, labels: builtins.bool = ..., positions: builtins.bool = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def line_graph_forbidden_subgraphs(immutable: builtins.bool = ...) -> _SageObject: ...

def petersen_family(generate: builtins.bool = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def p2_forbidden_minors(immutable: builtins.bool = ...) -> _SageObject: ...

def SierpinskiGasketGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def GeneralizedSierpinskiGraph(G: builtins.object, k: builtins.int, stretch: builtins.object = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def WheelGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def WindmillGraph(k: builtins.int, n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def RingedTree(k: builtins.int, vertex_labels: builtins.bool = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def MathonPseudocyclicMergingGraph(M: builtins.int, t: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def MathonPseudocyclicStronglyRegularGraph(t: builtins.object, G: builtins.object = ..., L: builtins.object = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def TuranGraph(n: builtins.int, r: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def MuzychukS6Graph(n: builtins.int, d: builtins.object, Phi: builtins.str = ..., Sigma: builtins.str = ..., verbose: builtins.bool = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def CubeConnectedCycle(d: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def StaircaseGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def BiwheelGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...

def TruncatedBiwheelGraph(n: builtins.int, immutable: builtins.bool = ...) -> _SageObject: ...
