import builtins

class _SageObject: ...

class LUWGraphDescriptor:
    name: builtins.str

    def __init__(
        self,
        ring: builtins.object,
        equations: builtins.object,
        name: builtins.str,
        point_coordinate_sets: builtins.object,
        line_coordinate_sets: builtins.object,
    ) -> None: ...
    def dimension(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def point_first_coordinates(self) -> _SageObject: ...
    def line_first_coordinates(self) -> _SageObject: ...
    def point_count(self) -> _SageObject: ...
    def line_count(self) -> _SageObject: ...
    def order(self) -> _SageObject: ...
    def size(self) -> _SageObject: ...
    def adjacency_matrix(self, vertices: builtins.object = ...) -> _SageObject: ...
    def equations(self) -> _SageObject: ...
    def graph(self, immutable: builtins.bool = ...) -> _SageObject: ...
    def ball(
        self,
        start_vertex: builtins.object,
        depth: builtins.object,
        immutable: builtins.bool = ...,
    ) -> _SageObject: ...
    def neighbors(self, vertex: builtins.object) -> _SageObject: ...
    def lift(
        self, new_functions: builtins.object, name: builtins.str = ...
    ) -> _SageObject: ...
    def project_down(
        self, x: builtins.object, name: builtins.str = ...
    ) -> _SageObject: ...

def define_luw_graph(
    self,
    equations: builtins.object,
    name: builtins.str = ...,
    A: builtins.object = ...,
    B: builtins.object = ...,
    point_coordinate_sets: builtins.object = ...,
    line_coordinate_sets: builtins.object = ...,
) -> _SageObject: ...
def LUWGraph(
    self,
    equations: builtins.object,
    name: builtins.str = ...,
    A: builtins.object = ...,
    B: builtins.object = ...,
    point_coordinate_sets: builtins.object = ...,
    line_coordinate_sets: builtins.object = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def Akq(
    self,
    q: builtins.int,
    A: builtins.object = ...,
    B: builtins.object = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def Dkq(
    self,
    q: builtins.int,
    A: builtins.object = ...,
    B: builtins.object = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def WengerGraph(
    self,
    q: builtins.int,
    A: builtins.object = ...,
    B: builtins.object = ...,
    immutable: builtins.bool = ...,
) -> _SageObject: ...
def define_Akq(
    self, q: builtins.int, A: builtins.object = ..., B: builtins.object = ...
) -> _SageObject: ...
def define_Dkq(
    self, q: builtins.int, A: builtins.object = ..., B: builtins.object = ...
) -> _SageObject: ...
def define_WengerGraph(
    self, q: builtins.int, A: builtins.object = ..., B: builtins.object = ...
) -> _SageObject: ...
