from sage.structure.element import Element

def RandomGNP(n: int, p: int, seed: Element | int | str | bool | None, fast: Element | int | str | bool | None, algorithm: str, immutable: Element | int | str | bool | None) -> Element: ...
def RandomBarabasiAlbert(n: int, m: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomBipartite(n1: Element | int | str | bool | None, n2: Element | int | str | bool | None, p: int, set_position: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomRegularBipartite(n1: Element | int | str | bool | None, n2: Element | int | str | bool | None, d1: Element | int | str | bool | None, set_position: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomBlockGraph(m: int, k: int, kmax: Element | int | str | bool | None, incidence_structure: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomBoundedToleranceGraph(n: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomGNM(n: int, m: int, dense: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomNewmanWattsStrogatz(n: int, k: int, p: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomHolmeKim(n: int, m: int, p: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomIntervalGraph(n: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomProperIntervalGraph(n: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def growing_subtrees(T: Element | int | str | bool | None, k: int) -> Element: ...
def connecting_nodes(T: Element | int | str | bool | None, l: Element | int | str | bool | None) -> Element: ...
def pruned_tree(T: Element | int | str | bool | None, f: Element, s: int) -> Element: ...
def RandomChordalGraph(n: int, algorithm: str, k: int, l: Element | int | str | bool | None, f: Element, s: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomKTree(n: int, k: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomPartialKTree(n: int, k: int, x: Element, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomRegular(d: int, n: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomShell(constructor: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomToleranceGraph(n: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomTriangulation(n: int, set_position: Element | int | str | bool | None, k: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def blossoming_contour(t: Element | int | str | bool | None, shift: Element | int | str | bool | None, seed: Element | int | str | bool | None) -> Element: ...
def RandomBicubicPlanar(n: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def RandomUnitDiskGraph(n: int, radius: Element | int | str | bool | None, side: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
