import builtins

class _SageObject: ...

def AfricaMap(
    self=..., year: builtins.int = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def EuropeMap(
    self=..., year: builtins.int = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def USAMap(self=..., immutable: builtins.bool = ...) -> _SageObject: ...
def WorldMap(self=...) -> _SageObject: ...
