# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CNFEncoder:
    def __init__(self, solver: builtins.object, ring: builtins.object, max_vars_sparse: builtins.int = ..., use_xor_clauses: builtins.object = ..., cutting_number: builtins.int = ..., random_seed: builtins.int = ...) -> None: ...
    def var(self, m: builtins.int = ..., decision: builtins.object = ...) -> _SageObject: ...
    @property
    def phi(self) -> _SageObject: ...
    def zero_blocks(self, f: builtins.object) -> _SageObject: ...
    def clauses_sparse(self, f: builtins.object) -> _SageObject: ...
    def clauses_dense(self, f: builtins.object) -> _SageObject: ...
    def monomial(self, m: builtins.int) -> _SageObject: ...
    def permutations(length: builtins.int, equal_zero: builtins.object) -> _SageObject: ...
    def split_xor(self, monomial_list: builtins.object, equal_zero: builtins.object) -> _SageObject: ...
    def clauses(self, f: builtins.object) -> _SageObject: ...
    def __call__(self, F: builtins.object) -> _SageObject: ...
    def to_polynomial(self, c: builtins.object) -> _SageObject: ...
