from collections.abc import Hashable, Iterator

from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.structure.element import Element
from sage.structure.factorization import Factorization

def factor(self, *args: object, **kwargs: object) -> Factorization: ...
def prime_range(start: int, stop: int | None = None) -> list[Integer]: ...
def next_prime(self, proof: bool | None = ...) -> Integer: ...
def previous_prime(self) -> Integer: ...
def gcd(self, b: int | Integer = ...) -> Integer: ...
def lcm(a: Integer, b: Integer) -> Integer: ...
def moebius(n: Integer) -> int: ...
def sigma(n: Integer, k: int = 1) -> Integer: ...
def euler_phi(n: Integer) -> Integer: ...
def is_prime(self) -> bool: ...
def prime_pi(n: Integer) -> Integer: ...
def bernoulli(self, algorithm: str = ..., num_threads: int = ...) -> Rational: ...
def factorial(self, algorithm: str = ...) -> Integer: ...
def binomial(self, m: int | Integer) -> int | Integer: ...
def prime_powers(self, stop: int | None = ...) -> list[Integer]: ...
def primes_first_n(self, leave_pari: bool = ...) -> list[Integer]: ...
def eratosthenes(self) -> list[Integer]: ...
def primes(
    self=..., stop: int | None = ..., proof: bool | None = ...
) -> Iterator[Integer]: ...
def random_prime(self, proof: bool | None = ..., lbound: int = ...) -> Integer: ...
def rational_reconstruction(self, m: int, algorithm: str = ...) -> Rational: ...
def mqrr_rational_reconstruction(
    self, m: int, T: int
) -> tuple[Integer, Integer] | None: ...
def trial_division(self, bound: int | None = ...) -> Integer: ...
def carmichael_lambda(self) -> Integer: ...
def binomial_coefficients(self) -> dict[Hashable, Element]: ...
def multinomial_coefficients(self, n: int) -> dict[tuple[int, ...], int]: ...
def kronecker_symbol(self, y: int) -> Integer: ...
def legendre_symbol(self, p: int) -> Integer: ...
def jacobi_symbol(self, b: int) -> Integer: ...
def primitive_root(self, check: bool = ...) -> Integer: ...
def nth_prime(self) -> Integer: ...
def quadratic_residues(self) -> list[Integer]: ...
def number_of_divisors(self) -> Integer: ...
def hilbert_symbol(self, b: int, p: int, algorithm: str = ...) -> Integer: ...
def hilbert_conductor(self, b: int) -> Integer: ...
def hilbert_conductor_inverse(self) -> tuple[Integer, Integer]: ...
def two_squares(self) -> tuple[Integer, Integer]: ...
def three_squares(self) -> tuple[Integer, Integer, Integer]: ...
def four_squares(self) -> tuple[Integer, Integer, Integer, Integer]: ...
def sum_of_k_squares(self, n: int) -> tuple[Integer, ...]: ...
def subfactorial(self) -> Integer: ...
def is_power_of_two(self) -> bool: ...
def fundamental_discriminant(self) -> Integer: ...
def dedekind_sum(self, q: int, algorithm: str = ...) -> Rational: ...
def dedekind_psi(self) -> Integer: ...
