from collections.abc import Iterator
from typing import Self, overload
from sage.rings.integer import Integer

MAX_MODULUS: int

class MultiModularBasis_base:
    def __init__(self, val: object, l_bound: int = ..., u_bound: int = ...) -> None: ...
    def extend_with_primes(self, plist: object, partial_products: object = ..., check: bool = ...) -> int: ...
    def crt(self, b: object) -> Integer: ...
    def precomputation_list(self) -> list[Integer]: ...
    def partial_product(self, n: int) -> Integer: ...
    def prod(self) -> Integer | int: ...
    def list(self) -> list[Integer]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Integer]: ...
    @overload
    def __getitem__(self, ix: int) -> int: ...
    @overload
    def __getitem__(self, ix: slice) -> Self: ...

class MultiModularBasis(MultiModularBasis_base): ...

class MutableMultiModularBasis(MultiModularBasis):
    def next_prime(self) -> int: ...
    def replace_prime(self, ix: int) -> int: ...
