from collections.abc import Callable, Sequence
from sage.matrix.matrix_dense import Matrix_dense
from sage.modular.hecke.module import HeckeModule_free_module
from sage.modular.modsym.space import ModularSymbolsSpace
from sage.modular.modsym.subspace import ModularSymbolsSubspace
from sage.categories.category import Category
from sage.rings.commutative_ring import CommutativeRing
from sage.rings.integer import Integer
from sage.structure.factorization import Factorization
from typing import Protocol

from sage.modular.arithgroup.congruence_subgroup import CongruenceSubgroup
from sage.modular.dirichlet import DirichletCharacter
from sage.modules.free_module import FreeModule_generic as FreeModule
from sage.modular.modsym.element import ModularSymbolsElement
from sage.modular.hecke.morphism import HeckeModuleMorphism_matrix
from sage.modular.cusps import Cusp
from sage.modules.free_module_element import FreeModuleElement
from sage.modular.modsym.boundary import BoundarySpace as BoundarySpace_wtk_g0
from sage.modular.hecke.morphism import HeckeModuleMorphism

class HeckeModule(HeckeModule_free_module): ...
class ManinSymbolList_gamma0(Protocol): ...
class P1List(Protocol): ...

class ModularSymbolsAmbient(ModularSymbolsSpace, HeckeModule):


    def __init__(
        self,
        group: CongruenceSubgroup,
        weight: Integer,
        sign: Integer,
        base_ring: CommutativeRing,
        character: DirichletCharacter | None = None,
        custom_init: Callable[[], None] | None = None,
        category: Category | None = None,
    ) -> None: ...
    def new_submodule(self, p: Integer | None = None) -> ModularSymbolsSubspace: ...
    def manin_symbols(self) -> ManinSymbolList_gamma0: ...
    def manin_generators(self) -> list[int]: ...
    def manin_basis(self) -> list[int]: ...
    def p1list(self) -> P1List: ...
    def compute_presentation(self) -> None: ...
    def manin_gens_to_basis(self) -> Matrix_dense: ...
    def _element_constructor_(self, x: FreeModuleElement | ModularSymbolsElement | list[int | Cusp] | tuple[int, ...] | int, computed_with_hecke: bool = False) -> ModularSymbolsElement: ...
    def manin_symbol(self, x: Sequence[int | Cusp], check: bool = True) -> ModularSymbolsElement: ...
    def modular_symbol(self, x: Sequence[int | Cusp], check: bool = True) -> ModularSymbolsElement: ...
    def modular_symbol_sum(self, x: Sequence[int | Cusp], check: bool = True) -> ModularSymbolsElement: ...
    def _compute_hecke_matrix_prime(self, p: int, rows: list[int] | None = None) -> Matrix_dense: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def boundary_map(self) -> HeckeModuleMorphism_matrix: ...
    def cusps(self) -> list[Cusp]: ...
    def boundary_space(self) -> BoundarySpace_wtk_g0: ...
    def cuspidal_submodule(self) -> ModularSymbolsSubspace: ...
    def rank(self) -> Integer: ...
    def eisenstein_submodule(self) -> ModularSymbolsSubspace: ...
    def element(self, x: ModularSymbolsElement | tuple[int, ...]) -> ModularSymbolsElement: ...
    def dual_star_involution_matrix(self) -> Matrix_dense: ...
    def factorization(self) -> Factorization: ...
    factor = factorization
    def is_cuspidal(self) -> bool: ...
    def is_eisenstein(self) -> bool: ...
    def manin_symbols_basis(self) -> list[int]: ...
    def modular_symbols_of_level(self, G: CongruenceSubgroup | int | Integer) -> ModularSymbolsAmbient: ...
    def modular_symbols_of_sign(self) -> ModularSymbolsAmbient: ...
    def modular_symbols_of_weight(self, k: int | Integer) -> ModularSymbolsAmbient: ...
    def star_involution(self) -> HeckeModuleMorphism: ...
    def twisted_winding_element(self, i: int | Integer, eps: DirichletCharacter) -> ModularSymbolsElement: ...
    def integral_structure(self, algorithm: str = "default") -> FreeModule: ...
    def compact_newform_eigenvalues(self, v: list[int], names: str = "alpha") -> list[Integer]: ...

class ModularSymbolsAmbient_wtk_g0(ModularSymbolsAmbient):


    def __init__(
        self,
        N: int,
        k: int,
        sign: int,
        F: CommutativeRing,
        custom_init: Callable[[], None] | None = None,
        category: Category | None = None,
    ) -> None: ...
    def _dimension_formula(self) -> int | None: ...
    def _repr_(self) -> str: ...
    def _cuspidal_submodule_dimension_formula(self) -> int: ...
    def _degeneracy_raising_matrix_1(self, M: ModularSymbolsAmbient) -> Matrix_dense: ...
    def _cuspidal_new_submodule_dimension_formula(self) -> int: ...
    def boundary_space(self) -> BoundarySpace_wtk_g0: ...
    def manin_symbols(self) -> ManinSymbolList_gamma0: ...
    def _hecke_images(self, i: int, v: list[int]) -> Matrix_dense: ...

class ModularSymbolsAmbient_wt2_g0(ModularSymbolsAmbient_wtk_g0):


    def __init__(
        self,
        N: int,
        sign: int,
        F: CommutativeRing,
        custom_init: Callable[[], None] | None = None,
        category: Category | None = None,
    ) -> None: ...
    def _dimension_formula(self) -> int | None: ...
    def _cuspidal_submodule_dimension_formula(self) -> int: ...

class ModularSymbolsAmbient_wtk_g1(ModularSymbolsAmbient):
    ...


class ModularSymbolsAmbient_wtk_gamma_h(ModularSymbolsAmbient):
    ...


class ModularSymbolsAmbient_wtk_eps(ModularSymbolsAmbient):
    ...
