# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Apply:
    def __cinit__(self) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...

def apply_to_monomial(i: builtins.object, j: builtins.object, a: builtins.object, b: builtins.object, c: builtins.object, d: builtins.object) -> _SageObject: ...
