from sage.modular.arithgroup.congroup_generic import CongruenceSubgroup
from sage.modular.dirichlet import DirichletCharacter
from sage.modular.hecke.module import HeckeModule_generic
from sage.modules.free_module import FreeModule_generic
from sage.rings.integer import Integer
from sage.rings.ring import CommutativeRing

class BoundarySpace(HeckeModule_generic):
    def __init__(
        self,
        group: CongruenceSubgroup = ...,
        weight: int | Integer = ...,
        sign: int | Integer = ...,
        base_ring: CommutativeRing = ...,
        character: DirichletCharacter | None = ...,
    ) -> None: ...
    def is_ambient(self) -> bool: ...
    def group(self) -> CongruenceSubgroup: ...
    def weight(self) -> Integer: ...
    def character(self) -> DirichletCharacter | None: ...
    def sign(self) -> Integer: ...
    def free_module(self) -> FreeModule_generic: ...
    def rank(self) -> Integer: ...
