from typing import TYPE_CHECKING

from sage.modular.hecke.module import HeckeModuleElement
from sage.structure.formal_sum import FormalSum

if TYPE_CHECKING:
    from sage.modular.modsym.space import ModularSymbolsSpace
    from sage.modules.free_module_element import FreeModuleElement

def set_modsym_print_mode(mode: str = "manin") -> None:
    """
    Set the mode for printing of modular symbols elements.
    """
    ...

class ModularSymbolsElement(HeckeModuleElement):
    """
    An element of a space of modular symbols.
    """

    def __init__(
        self,
        parent: ModularSymbolsSpace,
        x: FreeModuleElement,
        check: bool = True,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _add_(self, right: ModularSymbolsElement) -> ModularSymbolsElement: ...
    def _rmul_(self, other) -> ModularSymbolsElement: ...
    def _lmul_(self, left) -> ModularSymbolsElement: ...
    def _neg_(self) -> ModularSymbolsElement: ...
    def _sub_(self, other: ModularSymbolsElement) -> ModularSymbolsElement: ...
    def list(self) -> list: ...
    def manin_symbol_rep(self) -> FormalSum: ...
    def modular_symbol_rep(self) -> FormalSum: ...
