import builtins

class _SageObject: ...

def P1NFList_clear_level_cache(self) -> _SageObject: ...

class MSymbol:
    def __init__(
        self,
        N: builtins.int,
        c: builtins.object,
        d: builtins.object = ...,
        check: builtins.bool = ...,
    ) -> None: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def N(self) -> _SageObject: ...
    def tuple(self) -> _SageObject: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    c: _SageObject
    d: _SageObject

    def lift_to_sl2_Ok(self) -> _SageObject: ...
    def normalize(self, with_scalar: builtins.bool = ...) -> _SageObject: ...

class P1NFList:
    def __init__(self, N: builtins.int) -> None: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def __getitem__(self, n: builtins.int) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def list(self) -> _SageObject: ...
    def normalize(
        self,
        c: builtins.object,
        d: builtins.object = ...,
        with_scalar: builtins.bool = ...,
    ) -> _SageObject: ...
    def N(self) -> _SageObject: ...
    def index(
        self,
        c: builtins.object,
        d: builtins.object = ...,
        with_scalar: builtins.bool = ...,
    ) -> _SageObject: ...
    def index_of_normalized_pair(
        self, c: builtins.object, d: builtins.object = ...
    ) -> _SageObject: ...
    def lift_to_sl2_Ok(self, i: builtins.int) -> _SageObject: ...
    def apply_S(self, i: builtins.int) -> _SageObject: ...
    def apply_TS(self, i: builtins.int) -> _SageObject: ...
    def apply_T_alpha(
        self, i: builtins.int, alpha: builtins.int = ...
    ) -> _SageObject: ...
    def apply_J_epsilon(
        self, i: builtins.int, e1: builtins.object, e2: builtins.int = ...
    ) -> _SageObject: ...

def p1NFlist(self) -> _SageObject: ...
def lift_to_sl2_Ok(self, c: builtins.object, d: builtins.object) -> _SageObject: ...
def make_coprime(self, c: builtins.object, d: builtins.object) -> _SageObject: ...
def psi(self) -> _SageObject: ...
