# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

arith_int: _SageObject
arith_llong: _SageObject
def p1_normalize_int(N: builtins.object, u: builtins.object, v: builtins.object) -> _SageObject: ...

def p1list_int(N: builtins.object) -> _SageObject: ...

def p1_normalize_llong(N: builtins.object, u: builtins.object, v: builtins.object) -> _SageObject: ...

def p1list_llong(N: builtins.object) -> _SageObject: ...

def p1list(N: builtins.object) -> _SageObject: ...

def p1_normalize(N: builtins.object, u: builtins.object, v: builtins.object) -> _SageObject: ...

class P1List:
    def __init__(self, N: builtins.object) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __getitem__(self, n: builtins.object) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def lift_to_sl2z(self, i: builtins.object) -> _SageObject: ...
    def apply_I(self, i: builtins.object) -> _SageObject: ...
    def apply_S(self, i: builtins.object) -> _SageObject: ...
    def apply_T(self, i: builtins.object) -> _SageObject: ...
    def index(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def index_and_scalar(self, u: builtins.object, v: builtins.object, i: builtins.object, s: builtins.object) -> _SageObject: ...
    def index_of_normalized_pair(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def list(self) -> _SageObject: ...
    def normalize(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def normalize_with_scalar(self, u: builtins.object, v: builtins.object) -> _SageObject: ...
    def N(self) -> _SageObject: ...

class export:
    ...

def lift_to_sl2z_int(c: builtins.object, d: builtins.object, N: builtins.object) -> _SageObject: ...

def lift_to_sl2z_llong(c: builtins.object, d: builtins.object, N: builtins.object) -> _SageObject: ...

def lift_to_sl2z(c: builtins.object, d: builtins.object, N: builtins.object) -> _SageObject: ...
