# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

SPARSE: _SageObject
def modS_relations(syms: builtins.object) -> _SageObject: ...

def modI_relations(syms: builtins.object, sign: builtins.object) -> _SageObject: ...

def T_relation_matrix_wtk_g0(syms: builtins.object, mod: builtins.object, field: builtins.object, sparse: builtins.bool) -> _SageObject: ...

def gens_to_basis_matrix(syms: builtins.object, relation_matrix: builtins.object, mod: builtins.object, field: builtins.object, sparse: builtins.bool) -> _SageObject: ...

def compute_presentation(syms: builtins.object, sign: builtins.object, field: builtins.object, sparse: builtins.bool = ...) -> _SageObject: ...

def relation_matrix_wtk_g0(syms: builtins.object, sign: builtins.object, field: builtins.object, sparse: builtins.bool) -> _SageObject: ...

def sparse_2term_quotient(rels: builtins.object, n: builtins.int, F: builtins.object) -> _SageObject: ...
