from sage.matrix.matrix_dense import Matrix_dense
from sage.modular.hecke.morphism import HeckeModuleMorphism, HeckeModuleMorphism_matrix
from sage.modular.modsym.ambient import ModularSymbolsAmbient
from sage.modular.modsym.space import ModularSymbolsSpace
from sage.modules.free_module import FreeModule_generic
from sage.structure.factorization import Factorization

class ModularSymbolsSubspace(ModularSymbolsSpace):
    def __init__(
        self,
        ambient_hecke_module: ModularSymbolsAmbient,
        submodule: FreeModule_generic,
        dual_free_module: FreeModule_generic | None = None,
        check: bool = False,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def ambient_hecke_module(self) -> ModularSymbolsAmbient: ...
    def boundary_map(self) -> HeckeModuleMorphism_matrix: ...
    def cuspidal_submodule(self) -> ModularSymbolsSubspace: ...
    def dual_star_involution_matrix(self) -> Matrix_dense: ...
    def eisenstein_subspace(self) -> ModularSymbolsSubspace: ...
    def factorization(self) -> Factorization: ...
    def is_cuspidal(self) -> bool: ...
    def is_eisenstein(self) -> bool: ...
    def _set_is_cuspidal(self, t: bool) -> None: ...
    def star_involution(self) -> HeckeModuleMorphism: ...
