# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

cache: _SageObject
def BrandtModule(N: builtins.int, M: builtins.int = ..., weight: builtins.int = ..., base_ring: builtins.object = ..., use_cache: builtins.bool = ...) -> _SageObject: ...

def class_number(p: builtins.int, r: builtins.int, M: builtins.int) -> _SageObject: ...

class BrandtSubmodule:
    ...

class BrandtModuleElement:
    def __init__(self, parent: builtins.object, x: builtins.object) -> None: ...
    def monodromy_pairing(self, x: builtins.object) -> _SageObject: ...
    def __mul__(self, right: builtins.object) -> Self: ...

class BrandtModule_class:
    def __init__(self, N: builtins.int, M: builtins.int, weight: builtins.object, base_ring: builtins.object) -> None: ...
    Element: _SageObject
    def free_module(self) -> _SageObject: ...
    def N(self) -> _SageObject: ...
    def M(self) -> _SageObject: ...
    def character(self) -> _SageObject: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> _SageObject: ...
    def quaternion_algebra(self) -> _SageObject: ...
    def maximal_order(self) -> _SageObject: ...
    def order_of_level_N(self) -> _SageObject: ...
    def cyclic_submodules(self, I: builtins.int, p: builtins.int) -> _SageObject: ...
    def hecke_matrix(self, n: builtins.int, algorithm: builtins.str = ..., sparse: builtins.bool = ..., B: builtins.object = ...) -> _SageObject: ...
    def right_ideals(self, B: builtins.object = ...) -> _SageObject: ...
    def brandt_series(self, prec: builtins.int, var: builtins.str = ...) -> _SageObject: ...
    def eisenstein_subspace(self) -> _SageObject: ...
    def is_cuspidal(self) -> builtins.bool: ...
    def monodromy_weights(self) -> _SageObject: ...

def benchmark_magma(levels: builtins.object, silent: builtins.bool = ...) -> _SageObject: ...

def benchmark_sage(levels: builtins.object, silent: builtins.bool = ...) -> _SageObject: ...
