from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class FMatrix(SageObject):
    def _repr_(self) -> str: ...
    def clear_equations(self) -> Element: ...
    def clear_vars(self) -> Element: ...
    def _reset_solver_state(self) -> Element: ...
    def fmat(self, a: Element, b: Element, c: Element, d: int, x: Element, y: Element, data: Element | int | str | bool | None) -> Element: ...
    def fmatrix(self, a: Element, b: Element, c: Element, d: int) -> Element: ...
    def field(self) -> Element: ...
    def FR(self) -> Element: ...
    def findcases(self, output: Element | int | str | bool | None) -> Element: ...
    def f_from(self, a: Element, b: Element, c: Element, d: int) -> Element: ...
    def f_to(self, a: Element, b: Element, c: Element, d: int) -> Element: ...
    def get_fvars(self) -> Element: ...
    def get_poly_ring(self) -> Element: ...
    def get_non_cyclotomic_roots(self) -> Element: ...
    def get_qqbar_embedding(self) -> Element: ...
    def get_coerce_map_from_fr_cyclotomic_field(self) -> Element: ...
    def get_fvars_in_alg_field(self) -> Element: ...
    def get_radical_expression(self) -> Element: ...
    def _get_known_vals(self) -> Element: ...
    def _get_known_nonz(self) -> Element: ...
    def largest_fmat_size(self) -> Element: ...
    def get_fvars_by_size(self, n: int, indices: Element | int | str | bool | None) -> Element: ...
    def save_fvars(self, filename: Element | int | str | bool | None) -> Element: ...
    def load_fvars(self, filename: Element | int | str | bool | None) -> Element: ...
    def get_fr_str(self) -> Element: ...
    def _checkpoint(self, do_chkpt: Element | int | str | bool | None, status: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _restore_state(self, filename: Element | int | str | bool | None) -> Element: ...
    def start_worker_pool(self, processes: Element | int | str | bool | None) -> Element: ...
    def shutdown_worker_pool(self) -> Element: ...
    def _map_triv_reduce(self, mapper: Element | int | str | bool | None, input_iter: Element | int | str | bool | None, worker_pool: Element | int | str | bool | None, chunksize: Element | int | str | bool | None, mp_thresh: Element | int | str | bool | None) -> Element: ...
    def get_orthogonality_constraints(self, output: Element | int | str | bool | None) -> Element: ...
    def get_defining_equations(self, option: Element | int | str | bool | None, output: Element | int | str | bool | None) -> Element: ...
    def _tup_to_fpoly(self, eq_tup: Element | int | str | bool | None) -> Element: ...
    def _update_reduction_params(self, eqns: Element | int | str | bool | None) -> Element: ...
    def _triangular_elim(self, eqns: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def equations_graph(self, eqns: Element | int | str | bool | None) -> Element: ...
    def _partition_eqns(self, eqns: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _par_graph_gb(self, eqns: Element | int | str | bool | None, term_order: Element | int | str | bool | None, largest_comp: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _get_component_variety(self, var: str, eqns: Element | int | str | bool | None) -> Element: ...
    def attempt_number_field_computation(self) -> bool: ...
    def _get_explicit_solution(self, eqns: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def find_orthogonal_solution(self, checkpoint: Element | int | str | bool | None, save_results: Element | int | str | bool | None, warm_start: Element | int | str | bool | None, use_mp: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _fix_gauge(self, algorithm: str) -> Element: ...
    def _substitute_degree_one(self, eqns: Element | int | str | bool | None) -> Element: ...
    def _update_equations(self) -> Element: ...
    def find_cyclotomic_solution(self, equations: Element | int | str | bool | None, algorithm: str, verbose: bool, output: Element | int | str | bool | None) -> Element: ...
    def fmats_are_orthogonal(self) -> bool: ...
    def fvars_are_real(self) -> bool: ...
    def certify_pentagons(self, use_mp: Element | int | str | bool | None, verbose: bool) -> Element: ...
