import builtins

class _SageObject: ...

class FMatrix:
    pool: None
    mp_thresh: int

    def __init__(
        self,
        fusion_ring: builtins.object,
        fusion_label: builtins.str = ...,
        var_prefix: builtins.str = ...,
        inject_variables: builtins.bool = ...,
    ) -> None: ...
    def clear_equations(self) -> _SageObject: ...
    def clear_vars(self) -> _SageObject: ...
    def fmat(
        self,
        a: builtins.object,
        b: builtins.object,
        c: builtins.object,
        d: builtins.object,
        x: builtins.object,
        y: builtins.object,
        data: builtins.bool = ...,
    ) -> _SageObject: ...
    def fmatrix(
        self,
        a: builtins.object,
        b: builtins.object,
        c: builtins.object,
        d: builtins.object,
    ) -> _SageObject: ...
    def field(self) -> _SageObject: ...
    def FR(self) -> _SageObject: ...
    def findcases(self, output: builtins.bool = ...) -> _SageObject: ...
    def f_from(
        self,
        a: builtins.object,
        b: builtins.object,
        c: builtins.object,
        d: builtins.object,
    ) -> _SageObject: ...
    def f_to(
        self,
        a: builtins.object,
        b: builtins.object,
        c: builtins.object,
        d: builtins.object,
    ) -> _SageObject: ...
    def get_fvars(self) -> _SageObject: ...
    def get_poly_ring(self) -> _SageObject: ...
    def get_non_cyclotomic_roots(self) -> _SageObject: ...
    def get_qqbar_embedding(self) -> _SageObject: ...
    def get_coerce_map_from_fr_cyclotomic_field(self) -> _SageObject: ...
    def get_fvars_in_alg_field(self) -> _SageObject: ...
    def get_radical_expression(self) -> _SageObject: ...
    def largest_fmat_size(self) -> _SageObject: ...
    def get_fvars_by_size(
        self, n: builtins.int, indices: builtins.bool = ...
    ) -> _SageObject: ...
    def save_fvars(self, filename: builtins.object) -> _SageObject: ...
    def load_fvars(self, filename: builtins.object) -> _SageObject: ...
    def get_fr_str(self) -> _SageObject: ...
    def start_worker_pool(self, processes: builtins.object = ...) -> _SageObject: ...
    def shutdown_worker_pool(self) -> _SageObject: ...
    def get_orthogonality_constraints(
        self, output: builtins.bool = ...
    ) -> _SageObject: ...
    def get_defining_equations(
        self, option: builtins.object, output: builtins.bool = ...
    ) -> _SageObject: ...
    def equations_graph(self, eqns: builtins.object = ...) -> _SageObject: ...
    def attempt_number_field_computation(self) -> bool: ...
    def find_orthogonal_solution(
        self,
        checkpoint: builtins.bool = ...,
        save_results: builtins.str = ...,
        warm_start: builtins.str = ...,
        use_mp: builtins.bool = ...,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...
    def find_cyclotomic_solution(
        self,
        equations: builtins.object = ...,
        algorithm: builtins.str = ...,
        verbose: builtins.bool = ...,
        output: builtins.bool = ...,
    ) -> _SageObject: ...
    def fmats_are_orthogonal(self) -> bool: ...
    def fvars_are_real(self) -> bool: ...
    def certify_pentagons(
        self, use_mp: builtins.bool = ..., verbose: builtins.bool = ...
    ) -> _SageObject: ...
