# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def req_cy(basis: builtins.object, r_matrix: builtins.object, fvars: builtins.object, Nk_ij: builtins.object, id_anyon: builtins.object, sextuple: builtins.object) -> _SageObject: ...

def get_reduced_hexagons(factory: builtins.object, mp_params: builtins.object) -> _SageObject: ...

def feq_cy(basis: builtins.object, fvars: builtins.object, Nk_ij: builtins.object, id_anyon: builtins.object, zero: builtins.object, nonuple: builtins.object, prune: builtins.object = ...) -> _SageObject: ...

def get_reduced_pentagons(factory: builtins.object, mp_params: builtins.object) -> _SageObject: ...

def update_reduce(factory: builtins.object, eqns: builtins.object) -> _SageObject: ...

def compute_gb(factory: builtins.object, args: builtins.object) -> _SageObject: ...

def collect_eqns(eqns: builtins.object) -> _SageObject: ...

def executor(params: builtins.object) -> _SageObject: ...

def feq_verif(factory: builtins.object, worker_results: builtins.object, fvars: builtins.object, Nk_ij: builtins.object, id_anyon: builtins.object, nonuple: builtins.object, tol: builtins.object = ...) -> _SageObject: ...

def pent_verify(factory: builtins.object, mp_params: builtins.object) -> _SageObject: ...
