# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def mid_sig_ij(fusion_ring: builtins.object, row: builtins.object, col: builtins.object, a: builtins.object, b: builtins.object) -> _SageObject: ...

def odd_one_out_ij(fusion_ring: builtins.object, xi: builtins.object, xj: builtins.object, a: builtins.object, b: builtins.object) -> _SageObject: ...

def cached_mid_sig_ij(fusion_ring: builtins.object, row: builtins.object, col: builtins.object, a: builtins.object, b: builtins.object) -> _SageObject: ...

def cached_odd_one_out_ij(fusion_ring: builtins.object, xi: builtins.object, xj: builtins.object, a: builtins.object, b: builtins.object) -> _SageObject: ...

def sig_2k(fusion_ring: builtins.object, args: builtins.object) -> _SageObject: ...

def odd_one_out(fusion_ring: builtins.object, args: builtins.object) -> _SageObject: ...

def executor(params: builtins.object) -> _SageObject: ...
