# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FusionRing:
    @staticmethod
    def __classcall__(cls: builtins.object, ct: builtins.object, k: builtins.int, base_ring: builtins.object = ..., prefix: builtins.str = ..., style: builtins.str = ..., conjugate: builtins.bool = ..., cyclotomic_order: builtins.object = ..., fusion_labels: builtins.object = ..., inject_variables: builtins.bool = ...) -> _SageObject: ...
    def check_braid_representation(self, max_strands: builtins.int = ..., anyon: builtins.object = ...) -> _SageObject: ...
    def fusion_labels(self, labels: builtins.object = ..., inject_variables: builtins.bool = ...) -> _SageObject: ...
    def field(self) -> _SageObject: ...
    def fvars_field(self) -> _SageObject: ...
    def root_of_unity(self, r: builtins.int, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def get_order(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def fusion_level(self) -> _SageObject: ...
    def fusion_l(self) -> _SageObject: ...
    def virasoro_central_charge(self) -> _SageObject: ...
    def conj_matrix(self) -> _SageObject: ...
    def twists_matrix(self) -> _SageObject: ...
    def N_ijk(self, elt_i: builtins.object, elt_j: builtins.object, elt_k: builtins.object) -> _SageObject: ...
    def Nk_ij(self, elt_i: builtins.object, elt_j: builtins.object, elt_k: builtins.object) -> _SageObject: ...
    def s_ij(self, elt_i: builtins.object, elt_j: builtins.object, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def s_ijconj(self, elt_i: builtins.object, elt_j: builtins.object, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def s_matrix(self, unitary: builtins.bool = ..., base_coercion: builtins.bool = ...) -> _SageObject: ...
    def r_matrix(self, i: builtins.int, j: builtins.int, k: builtins.int, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def global_q_dimension(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def total_q_order(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def D_plus(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def D_minus(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def is_multiplicity_free(self) -> builtins.bool: ...
    def get_computational_basis(self, a: builtins.object, b: builtins.object, n_strands: builtins.object) -> _SageObject: ...
    def get_fmatrix(self, *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def get_braid_generators(self, fusing_anyon: builtins.object, total_charge_anyon: builtins.object, n_strands: builtins.object, checkpoint: builtins.bool = ..., save_results: builtins.str = ..., warm_start: builtins.str = ..., use_mp: builtins.bool = ..., verbose: builtins.bool = ...) -> _SageObject: ...
    def gens_satisfy_braid_gp_rels(self, sig: builtins.object) -> _SageObject: ...
    class Element:
        def is_simple_object(self) -> builtins.bool: ...
        def weight(self) -> _SageObject: ...
        def twist(self, reduced: builtins.bool = ...) -> _SageObject: ...
        def ribbon(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
        def q_dimension(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
