import builtins

class _SageObject: ...

class FusionDouble:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        G: builtins.object,
        prefix: builtins.str = ...,
        inject_variables: builtins.bool = ...,
    ) -> _SageObject: ...
    def __init__(self, G: builtins.object, prefix: builtins.str = ...) -> None: ...
    def inject_variables(self) -> _SageObject: ...
    def s_ij(
        self,
        i: builtins.int,
        j: builtins.int,
        unitary: builtins.bool = ...,
        base_coercion: builtins.bool = ...,
    ) -> _SageObject: ...
    def s_ijconj(
        self,
        i: builtins.int,
        j: builtins.int,
        unitary: builtins.bool = ...,
        base_coercion: builtins.bool = ...,
    ) -> _SageObject: ...
    def s_matrix(
        self, unitary: builtins.bool = ..., base_coercion: builtins.bool = ...
    ) -> _SageObject: ...
    def N_ijk(
        self, i: builtins.int, j: builtins.int, k: builtins.int
    ) -> _SageObject: ...
    def Nk_ij(
        self,
        i: builtins.int,
        j: builtins.int,
        k: builtins.int,
        use_characters: builtins.bool = ...,
    ) -> _SageObject: ...
    def field(self) -> _SageObject: ...
    def fvars_field(self) -> _SageObject: ...
    def root_of_unity(
        self, r: builtins.int, base_coercion: builtins.bool = ...
    ) -> _SageObject: ...
    def r_matrix(
        self,
        i: builtins.int,
        j: builtins.int,
        k: builtins.int,
        base_coercion: builtins.bool = ...,
    ) -> _SageObject: ...
    def global_q_dimension(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
    def total_q_order(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
    D_minus: _SageObject
    D_plus: _SageObject

    def is_multiplicity_free(self, verbose: builtins.bool = ...) -> bool: ...
    def one_basis(self) -> _SageObject: ...
    def dual(self, i: builtins.int) -> _SageObject: ...
    def product_on_basis(
        self, a: builtins.object, b: builtins.object
    ) -> _SageObject: ...
    def group(self) -> _SageObject: ...
    def get_fmatrix(
        self, *args: builtins.object, **kwargs: builtins.object
    ) -> _SageObject: ...

    class Element:
        def is_simple_object(self) -> builtins.bool: ...
        def g(self) -> _SageObject: ...
        def char(self) -> _SageObject: ...
        def ribbon(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
        def twist(self, reduced: builtins.bool = ...) -> _SageObject: ...
        def dual(self) -> _SageObject: ...
        def q_dimension(self, base_coercion: builtins.bool = ...) -> _SageObject: ...
