# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def poly_to_tup(poly: builtins.object) -> _SageObject: ...

def has_appropriate_linear_term(eq_tup: builtins.object) -> builtins.bool: ...

def tup_to_univ_poly(eq_tup: builtins.object, univ_poly_ring: builtins.object) -> _SageObject: ...

def resize(eq_tup: builtins.object, idx_map: builtins.object, nvars: builtins.object) -> _SageObject: ...

def degrees(poly_tup: builtins.object) -> _SageObject: ...

def get_variables_degrees(eqns: builtins.object, nvars: builtins.object) -> _SageObject: ...

def variables(eq_tup: builtins.object) -> _SageObject: ...

def constant_coeff(eq_tup: builtins.object, field: builtins.object) -> _SageObject: ...

def apply_coeff_map(eq_tup: builtins.object, coeff_map: builtins.object) -> _SageObject: ...

def tup_fixes_sq(eq_tup: builtins.object) -> _SageObject: ...

def subs_squares(eq_dict: builtins.object, known_sq: builtins.object) -> _SageObject: ...

def remove_gcf(eq_dict: builtins.object, nonz: builtins.object) -> _SageObject: ...

def to_monic(eq_dict: builtins.object, one: builtins.object) -> _SageObject: ...

def reduce_poly_dict(eq_dict: builtins.object, nonz: builtins.object, known_sq: builtins.object, one: builtins.object) -> _SageObject: ...

def compute_known_powers(max_degs: builtins.object, val_dict: builtins.object, one: builtins.object) -> _SageObject: ...

def subs(poly_tup: builtins.object, known_powers: builtins.object, one: builtins.object) -> _SageObject: ...

def tup_mul(p1: builtins.object, p2: builtins.object) -> _SageObject: ...

def monom_sortkey(exp: builtins.object) -> _SageObject: ...

def poly_tup_sortkey(eq_tup: builtins.object) -> _SageObject: ...
