# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KSHandler:
    def __init__(self, n_slots: builtins.object, field: builtins.object, use_mp: builtins.object = ..., init_data: builtins.object = ..., name: builtins.object = ...) -> None: ...
    def get(self, idx: builtins.object) -> _SageObject: ...
    def update(self, eqns: builtins.object) -> _SageObject: ...
    def setitem(self, idx: builtins.object, rhs: builtins.object) -> _SageObject: ...
    def contains(self, idx: builtins.object) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def items(self) -> _SageObject: ...

def make_KSHandler(n_slots: builtins.object, field: builtins.object, init_data: builtins.object) -> _SageObject: ...

class FvarsHandler:
    def __getitem__(self, sextuple: builtins.object) -> _SageObject: ...
    def __setitem__(self, sextuple: builtins.object, fvar: builtins.object) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def items(self) -> _SageObject: ...

def make_FvarsHandler(n: builtins.object, field: builtins.object, idx_map: builtins.object, init_data: builtins.object) -> _SageObject: ...
