import builtins
from typing import Self

class _SageObject: ...

class GenericDeclaration:
    def __init__(self, var: builtins.object, assumption: builtins.object) -> None: ...
    def has(self, arg: builtins.object) -> _SageObject: ...
    def assume(self) -> _SageObject: ...
    def forget(self) -> _SageObject: ...
    def contradicts(self, soln: builtins.object) -> _SageObject: ...

def preprocess_assumptions(self) -> _SageObject: ...
def assume(self, *args: builtins.object) -> _SageObject: ...
def forget(self, *args: builtins.object) -> _SageObject: ...
def assumptions(self, *args: builtins.object) -> _SageObject: ...

class assuming:
    def __init__(self, *args: builtins.object, **kwds: builtins.object) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> builtins.bool | None: ...
