import builtins

class _SageObject: ...

class AlgebraicConverter:
    def __init__(self, field: builtins.object) -> None: ...
    def pyobject(self, ex: builtins.object, obj: builtins.object) -> _SageObject: ...
    def arithmetic(
        self, ex: builtins.object, operator: builtins.object
    ) -> _SageObject: ...
    def composition(
        self, ex: builtins.object, operator: builtins.object
    ) -> _SageObject: ...

def algebraic(self, field: builtins.object) -> _SageObject: ...
