# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AlgebraicConverter:
    def __init__(self, field: builtins.object) -> None: ...
    def pyobject(self, ex: builtins.object, obj: builtins.object) -> _SageObject: ...
    def arithmetic(self, ex: builtins.object, operator: builtins.object) -> _SageObject: ...
    def composition(self, ex: builtins.object, operator: builtins.object) -> _SageObject: ...

def algebraic(ex: builtins.object, field: builtins.object) -> _SageObject: ...
