# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SympyConverter:
    def __init__(self) -> None: ...
    def __call__(self, ex: builtins.object = ...) -> _SageObject: ...
    def pyobject(self, ex: builtins.object, obj: builtins.object) -> _SageObject: ...
    def arithmetic(self, ex: builtins.object, operator: builtins.object) -> _SageObject: ...
    def symbol(self, ex: builtins.object) -> _SageObject: ...
    def relation(self, ex: builtins.object, op: builtins.object) -> _SageObject: ...
    def composition(self, ex: builtins.object, operator: builtins.object) -> _SageObject: ...
    def tuple(self, ex: builtins.object) -> _SageObject: ...
    def derivative(self, ex: builtins.object, operator: builtins.object) -> _SageObject: ...

sympy_converter: _SageObject
