from collections.abc import Iterable
from typing import Self

from sage.interfaces.interface import InterfaceFunctionElement
from sage.structure.parent import Parent
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression, SymbolicInput


class MaximaFunctionElementWrapper(InterfaceFunctionElement):
    def __call__(self, *args: SymbolicInput, **kwds: SymbolicInput) -> Expression: ...


class MaximaWrapper(SageObject):
    def __init__(self, exp: Expression) -> None: ...
    def __getattr__(self, s: str) -> MaximaFunctionElementWrapper: ...
    def __dir__(self) -> Iterable[str]: ...
    def sage(self) -> Expression: ...
    def _symbolic_(self, parent: Parent[Expression]) -> Expression: ...
    def __reduce__(self) -> tuple[type[Self], tuple[Expression]]: ...
    def _repr_(self) -> str: ...
