# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def check_relation_maxima(relation: builtins.object) -> _SageObject: ...

def check_relation_maxima_neq_as_not_eq(relation: builtins.object) -> _SageObject: ...

def string_to_list_of_solutions(s: builtins.object) -> _SageObject: ...

def solve(f: builtins.object, *args: builtins.object, explicit_solutions: builtins.object = ..., multiplicities: builtins.object = ..., to_poly_solve: builtins.object = ..., solution_dict: builtins.bool = ..., algorithm: builtins.str = ..., domain: builtins.object = ...) -> _SageObject: ...

def solve_mod(eqns: builtins.object, modulus: builtins.object, solution_dict: builtins.bool = ...) -> _SageObject: ...

def solve_ineq_univar(ineq: builtins.object) -> _SageObject: ...

def solve_ineq_fourier(ineq: builtins.object, vars: builtins.object = ...) -> _SageObject: ...

def solve_ineq(ineq: builtins.object, vars: builtins.object = ...) -> _SageObject: ...
