from collections.abc import Callable
from types import TracebackType
from typing import Self

from sage.categories.morphism import Morphism
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.sage_object import SageCoercionAtom, SageObject
from sage.symbolic.expression import Expression

class SymbolicRing(Parent):
    def __init__(self, base_ring: Parent | None = None) -> None: ...
    def __reduce__(self) -> tuple[Callable[[], SymbolicRing], tuple[()]]: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _coerce_map_from_(self, R: Parent) -> bool: ...
    def _element_constructor_(self, x: SageCoercionAtom) -> Expression: ...
    def _force_pyobject(
        self, x: SageCoercionAtom, force: bool = False, recursive: bool = True
    ) -> Element: ...
    def wild(self, n: int = 0) -> Element: ...
    def __contains__(self, x: object) -> bool: ...
    def characteristic(self) -> int: ...
    def _an_element_(self) -> Element: ...
    def is_field(self, proof: bool = True) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_exact(self) -> bool: ...
    def pi(self) -> Element: ...
    def I(self) -> Element: ...
    def symbol(
        self,
        name: str | None = None,
        latex_name: str | None = None,
        domain: str | None = None,
    ) -> Element: ...
    def temp_var(
        self, n: int | None = None, domain: str | None = None
    ) -> Element | tuple[Element, ...]: ...
    def cleanup_var(self, symbol: Element | list[Element]) -> None: ...
    def var(
        self,
        name: str,
        latex_name: str | None = None,
        n: int | None = None,
        domain: str | None = None,
    ) -> Expression | tuple[Expression, ...]: ...
    def zero(self) -> Expression: ...
    def _repr_element_(self, x: Element) -> str: ...
    def _latex_element_(self, x: Element) -> str: ...
    def _call_element_(
        self, element: Element, *args: Element, **kwds: Element
    ) -> Element: ...
    def subring(self, *args: Element, **kwds: Element) -> Parent: ...
    def _fricas_init_(self) -> str: ...

def the_SymbolicRing() -> SymbolicRing: ...

SR: SymbolicRing

class NumpyToSRMorphism(Morphism):
    def __init__(self, numpy_type: type[SageObject]) -> None: ...
    def _call_(self, a: SageCoercionAtom) -> Element: ...

class UnderscoreSageMorphism(Morphism):
    def __init__(self, t: type[SageObject], R: Parent) -> None: ...
    def _call_(self, a: SageObject) -> Element: ...

def var(name: str, **kwds: str | int | None) -> Element | tuple[Element, ...]: ...
def isidentifier(x: str) -> bool: ...

class TemporaryVariables(tuple[Element, ...]):
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
