from sage.rings.ring import Ring
from sage.symbolic.expression import Expression
from sage.structure.parent import Parent

class SymbolicSeries:
    def __init__(self, SR: Parent) -> None: ...
    def is_terminating_series(self) -> bool: ...
    def truncate(self) -> Expression: ...
    def default_variable(self) -> Expression: ...
    def coefficients(
        self, x: Expression | None = None, sparse: bool = True
    ) -> list[tuple[Expression, int]] | list[Expression]: ...
    def power_series(self, base_ring: Ring) -> Parent: ...
