import builtins

class _SageObject: ...

one: _SageObject
unitdict: _SageObject
unit_to_type: _SageObject
value_to_unit: _SageObject

def evalunitdict(self) -> _SageObject: ...

unit_docs: _SageObject
unit_derivations: _SageObject

def vars_in_str(self) -> _SageObject: ...
def unit_derivations_expr(self) -> _SageObject: ...

class UnitExpression: ...

def str_to_unit(self) -> _SageObject: ...

class Units:
    def __init__(self, data: builtins.object, name: builtins.str = ...) -> None: ...
    def __getstate__(self) -> _SageObject: ...
    def __setstate__(self, state: builtins.object) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __getattr__(self, name: builtins.str) -> _SageObject: ...

units: _SageObject

def unitdocs(self) -> _SageObject: ...
def is_unit(self) -> bool: ...
def convert(self, target: builtins.object) -> _SageObject: ...
def base_units(self) -> _SageObject: ...
def convert_temperature(self, target: builtins.object) -> _SageObject: ...
