from collections.abc import Iterable, Iterator
from typing import Self

from sage.categories.category import Category
from sage.structure.element import Element
from sage.structure.element_wrapper import ElementWrapper
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

class CartesianProduct(UniqueRepresentation, Parent):
    class Element(ElementWrapper):
        def cartesian_projection(self, i: int) -> Element: ...
        def __iter__(self) -> Iterator[Element]: ...
        def __len__(self) -> int: ...
        def cartesian_factors(self) -> tuple[Parent, ...]: ...

    def __init__(
        self,
        sets: Iterable[Parent],
        category: Category,
        flatten: bool = ...,
    ) -> None: ...
    def _element_constructor_(self, x: Iterable[object]) -> Element: ...
    def _repr_(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def cartesian_factors(self) -> tuple[Parent, ...]: ...
    def _sets_keys(self) -> tuple[int, ...]: ...
    def cartesian_projection(self, i: int) -> Parent: ...
    def _cartesian_product_of_elements(
        self, elements: Iterable[Element]
    ) -> Element: ...
    def construction(self) -> tuple[object, object] | None: ...
    def _coerce_map_from_(self, S: Parent) -> bool: ...
