from collections.abc import Hashable, Iterable, Iterator

from sage.rings.integer import Integer
from sage.structure.sage_object import SageObject

def DisjointSet(
    arg: Integer | int | Iterable[Hashable] | object,
) -> DisjointSet_of_integers | DisjointSet_of_hashables: ...

class DisjointSet_class(SageObject):
    def _repr_(self) -> str: ...
    def __iter__(self) -> Iterator[list[object]]: ...
    def __richcmp__(self, other: object, op: int) -> bool | None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...], list[int] | list[object]]: ...
    def cardinality(self) -> int: ...
    def number_of_subsets(self) -> int: ...

class DisjointSet_of_integers(DisjointSet_class):
    def __init__(self, n: Integer | int) -> None: ...
    def __getstate__(self) -> list[int]: ...
    def __setstate__(self, l: list[int]) -> None: ...
    def find(self, i: int) -> int: ...
    def union(self, i: int, j: int) -> None: ...
    def make_set(self) -> None: ...
    def root_to_elements_dict(self) -> dict[int, list[int]]: ...

class DisjointSet_of_hashables(DisjointSet_class):
    def __init__(self, iterable: Iterable[Hashable]) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...], list[int] | list[object]]: ...
    def __getstate__(self) -> list[object]: ...
    def __setstate__(self, l: list[object]) -> None: ...
    def find(self, x: Hashable) -> Hashable: ...
    def union(self, x: Hashable, y: Hashable) -> None: ...
    def make_set(self, new_elt: Hashable | None = ...) -> None: ...
    def root_to_elements_dict(self) -> dict[Hashable, list[Hashable]]: ...
