from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.parent import Parent

def fibers_args(
    f: object,
    domain: Parent,
    *args: object,
    **opts: object,
) -> dict[object, set[object]]: ...

class FiniteSetMap_MN:
    def __call__(self, i: int | object) -> int | Element: ...
    def __bool__(self) -> bool: ...

class FiniteSetMap_Set(FiniteSetMap_MN):
    def __init__(
        self,
        parent: Parent,
        fun: list[object] | dict[object, object],
        check: bool = ...,
    ) -> None: ...
    def __call__(self, i: object) -> Element: ...
    def _repr_(self) -> str: ...

class FiniteSetEndoMap_N(FiniteSetMap_MN):
    def __mul__(self, other: FiniteSetEndoMap_N) -> FiniteSetEndoMap_N: ...
    def __pow__(self, n: Integer | int, dummy: object = ...) -> FiniteSetEndoMap_N: ...

class FiniteSetEndoMap_Set(FiniteSetMap_Set):
    def __mul__(self, other: FiniteSetEndoMap_Set) -> FiniteSetEndoMap_Set: ...
    def __pow__(self, n: Integer | int, dummy: object = ...) -> FiniteSetEndoMap_Set: ...
