from collections.abc import Iterator, Sequence

from sage.categories.category import Category
from sage.categories.sets_cat import _SympySetLike
from sage.rings.integer import Integer
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

class NonNegativeIntegers(UniqueRepresentation, Parent):
    def __init__(self, category: Category | None = ...) -> None: ...
    def _repr_(self) -> str: ...
    def __contains__(self, elt: object) -> bool: ...
    def _element_constructor_(self, x: Integer | int) -> Integer: ...
    def __iter__(self) -> Iterator[Integer]: ...
    def an_element(self) -> Integer: ...
    def some_elements(self) -> Sequence[Integer]: ...
    def next(self, x: Integer) -> Integer: ...
    def unrank(self, r: int) -> Integer: ...
    def _sympy_(self) -> _SympySetLike: ...
