from sage.categories.sets_cat import _SympySetLike
from sage.rings.integer import Integer
from sage.structure.unique_representation import UniqueRepresentation

from .integer_range import IntegerRangeInfinite

class PositiveIntegers(IntegerRangeInfinite, UniqueRepresentation):
    def __init__(self) -> None: ...
    def _repr_(self) -> str: ...
    def an_element(self) -> Integer: ...
    def _sympy_(self) -> _SympySetLike: ...
