from collections.abc import Callable, Iterable, Iterator

from sage.categories.category import Category
from sage.graphs.digraph import DiGraph
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.parent import Parent

class RecursivelyEnumeratedSet(Parent):
    def __init__(
        self,
        seeds: Iterable[object],
        successors: Callable[[object], Iterable[object]],
        enumeration: str = ...,
        max_depth: float = ...,
        post_process: Callable[[object], object | None] | None = ...,
        facade: bool | None = ...,
        category: Category | None = ...,
    ) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def __getstate__(self) -> dict[str, object]: ...
    def __setstate__(self, l: dict[str, object]) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __contains__(self, elt: object) -> bool: ...
    def _repr_(self) -> str: ...
    def graded_component_iterator(self) -> Iterator[Iterable[Element]]: ...
    def elements_of_depth_iterator(self, depth: int) -> Iterator[Element]: ...
    def breadth_first_search_iterator(
        self, max_depth: float | None = ...
    ) -> Iterator[Element]: ...
    def _breadth_first_search_iterator_using_queue(self) -> Iterator[Element]: ...
    def naive_search_iterator(self) -> Iterator[Element]: ...
    def depth_first_search_iterator(self) -> Iterator[Element]: ...
    def to_digraph(
        self,
        max_depth: float | None = ...,
        loops: bool = ...,
        multiedges: bool = ...,
    ) -> DiGraph: ...

class RecursivelyEnumeratedSet_symmetric(RecursivelyEnumeratedSet):
    def breadth_first_search_iterator(
        self, max_depth: float | None = ...
    ) -> Iterator[Element]: ...
    def graded_component_iterator(self) -> Iterator[Iterable[Element]]: ...

class RecursivelyEnumeratedSet_graded(RecursivelyEnumeratedSet):
    def breadth_first_search_iterator(
        self, max_depth: float | None = ...
    ) -> Iterator[Element]: ...
    def graded_component_iterator(self) -> Iterator[Iterable[Element]]: ...

class RecursivelyEnumeratedSet_forest(Parent):
    def __init__(
        self,
        roots: Iterable[object] | None = ...,
        children: Callable[[object], Iterable[object]] | None = ...,
        post_process: Callable[[object], object | None] | None = ...,
        algorithm: str = ...,
        facade: bool | None = ...,
        category: Category | None = ...,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def roots(self) -> Iterable[object]: ...
    def children(self, x: object) -> Iterable[object]: ...
    def __iter__(self) -> Iterator[Element]: ...
    def depth_first_search_iterator(self) -> Iterator[Element]: ...
    def breadth_first_search_iterator(self) -> Iterator[Element]: ...
    def _elements_of_depth_iterator_rec(self, depth: int = ...) -> Iterator[Element]: ...
    def elements_of_depth_iterator(self, depth: int = ...) -> Iterator[Element]: ...
    def __contains__(self, elt: object) -> bool: ...
    def map_reduce(
        self,
        map_function: Callable[[object], object] | None = ...,
        reduce_function: Callable[[object, object], object] | None = ...,
        reduce_init: object = ...,
    ) -> Integer | Element: ...

def _imap_and_filter_none(
    function: Callable[[object], object | None],
    iterable: Iterable[object],
) -> Iterator[object]: ...

def search_forest_iterator(
    roots: Iterable[object],
    children: Callable[[object], Iterable[object]],
    algorithm: str = ...,
) -> Iterator[object]: ...
