from collections.abc import Iterable, Iterator
from typing import Generic, Self, TypeVar, overload

from sage.categories.category import Category
from sage.categories.sets_cat import Sets, _SympySetLike
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.parent import MembershipInput, Parent

_E = TypeVar("_E", default=Element, covariant=True)

class Set_generic(Parent[_E], Generic[_E]):
    ...

def has_finite_length(obj: object) -> bool: ...

@overload
def Set(X: Iterable[_E], category: Category | None = ...) -> Set_object_enumerated[_E]: ...
@overload
def Set(X: Parent[_E], category: Category | None = ...) -> Set_object[_E]: ...
@overload
def Set(X: None = ..., category: Category | None = ...) -> Set_object[Element]: ...

class Set_base:
    def union(self, X: Set_generic | Set_base) -> Set_generic: ...
    def intersection(self, X: Set_generic | Set_base) -> Set_generic: ...
    def difference(self, X: Set_generic | Set_base) -> Set_generic: ...
    def symmetric_difference(self, X: Set_generic | Set_base) -> Set_generic: ...
    def _test_as_set_object(self, tester: object | None = ..., **options: object) -> None: ...

class Set_boolean_operators:
    def __or__(self, X: Set_generic | Set_base) -> Set_generic: ...
    def __and__(self, X: Set_generic | Set_base) -> Set_generic: ...
    def __xor__(self, X: Set_generic | Set_base) -> Set_generic: ...

class Set_add_sub_operators:
    def __add__(self, X: Set_generic | Set_base) -> Set_generic: ...
    def __sub__(self, X: Set_generic | Set_base) -> Set_generic: ...

class Set_object(
    Set_generic[_E],
    Sets.ParentMethods[_E],
    Set_base,
    Set_boolean_operators,
    Set_add_sub_operators,
    Generic[_E],
):
    def __init__(self, X: object, category: Category | None = ...) -> None: ...
    def __hash__(self) -> int: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def __iter__(self) -> Iterator[_E]: ...
    def _an_element_(self) -> _E: ...
    def __contains__(self, x: MembershipInput) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool | None: ...
    def cardinality(self) -> Integer | PlusInfinity: ...
    def is_empty(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def subsets(self, *args: object, **kwargs: object) -> Parent: ...
    def subsets_lattice(self, *args: object, **kwargs: object) -> Parent: ...
    def _sympy_(self) -> _SympySetLike: ...
    def object(self) -> Element | Parent: ...

class Set_object_enumerated(Set_object[_E], Generic[_E]):
    def __init__(self, X: object, category: Category | None = ...) -> None: ...
    def random_element(self) -> Element: ...
    def is_finite(self) -> bool: ...
    def cardinality(self) -> Integer: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_E]: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def list(self) -> list[_E]: ...
    def set(self) -> set[_E]: ...
    def frozenset(self) -> frozenset[_E]: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: object, op: int) -> bool | None: ...
    def isdisjoint(self, other: Iterable[object] | Set_object_enumerated) -> bool: ...
    def issubset(self, other: Iterable[object] | Set_object_enumerated) -> bool: ...
    def issuperset(self, other: Iterable[object] | Set_object_enumerated) -> bool: ...
    def union(self, X: Set_generic | Set_base) -> Set_generic: ...
    def intersection(self, X: Set_generic | Set_base) -> Set_generic: ...
    def difference(self, X: Set_generic | Set_base) -> Set_generic: ...
    def symmetric_difference(self, X: Set_generic | Set_base) -> Set_generic: ...
    def _sympy_(self) -> _SympySetLike: ...

class Set_object_binary(Set_object):
    @classmethod
    def __classcall__(
        cls,
        X: Set_generic | Set_base,
        Y: Set_generic | Set_base,
        **options: object,
    ) -> Self: ...
    def __init__(
        self,
        X: Set_generic | Set_base,
        Y: Set_generic | Set_base,
        **options: object,
    ) -> None: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __hash__(self) -> int: ...

class Set_object_union(Set_object_binary):
    def __init__(
        self,
        X: Set_generic | Set_base,
        Y: Set_generic | Set_base,
        **options: object,
    ) -> None: ...
    def is_finite(self) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool | None: ...
    def __iter__(self) -> Iterator[object]: ...
    def __contains__(self, x: object) -> bool: ...
    def cardinality(self) -> int | PlusInfinity: ...
    def _sympy_(self) -> _SympySetLike: ...
    def __bool__(self) -> bool: ...

class Set_object_intersection(Set_object_binary):
    def __init__(
        self,
        X: Set_generic | Set_base,
        Y: Set_generic | Set_base,
        **options: object,
    ) -> None: ...
    def is_finite(self) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool | None: ...
    def __iter__(self) -> Iterator[object]: ...
    def __contains__(self, x: object) -> bool: ...
    def _sympy_(self) -> _SympySetLike: ...

class Set_object_difference(Set_object_binary):
    def __init__(
        self,
        X: Set_generic | Set_base,
        Y: Set_generic | Set_base,
        **options: object,
    ) -> None: ...
    def is_finite(self) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool | None: ...
    def __iter__(self) -> Iterator[object]: ...
    def __contains__(self, x: object) -> bool: ...
    def _sympy_(self) -> _SympySetLike: ...

class Set_object_symmetric_difference(Set_object_binary):
    def __init__(
        self,
        X: Set_generic | Set_base,
        Y: Set_generic | Set_base,
        **options: object,
    ) -> None: ...
    def is_finite(self) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool | None: ...
    def __iter__(self) -> Iterator[object]: ...
    def __contains__(self, x: object) -> bool: ...
    def _sympy_(self) -> _SympySetLike: ...
