from collections.abc import Callable, Iterable, Iterator

from sage.structure.element import Element
from sage.structure.parent import Parent

class EnumeratedSetFromIterator(Parent):
    def __init__(
        self,
        iterator: Callable[[], Iterator[object]],
        cardinality: int | None = ...,
        category: object | None = ...,
        cache: bool = ...,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def _repr_(self) -> str: ...
    def __contains__(self, x: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __iter__(self) -> Iterator[Element]: ...
    def unrank(self, r: int) -> Element: ...
    def _element_constructor_(self, x: object) -> Element: ...
    def clear_cache(self) -> None: ...

class Decorator:
    def _instancedoc_(self) -> str: ...
    def _sage_src_(self) -> str: ...
    def _sage_src_lines_(self) -> list[int]: ...
    def _sage_argspec_(self) -> tuple[list[str], str | None, tuple[str, ...], tuple[str, ...]]: ...
    def __call__(self, *args: object, **kwargs: object) -> EnumeratedSetFromIterator: ...

class EnumeratedSetFromIterator_function_decorator(Decorator):
    def __init__(self, f: Callable[..., Iterator[object]], **options: object) -> None: ...
    def __call__(self, *args: object, **kwargs: object) -> EnumeratedSetFromIterator: ...

class EnumeratedSetFromIterator_method_caller(Decorator):
    def __init__(self, f: Callable[..., Iterator[object]], **options: object) -> None: ...
    def __call__(self, *args: object, **kwargs: object) -> EnumeratedSetFromIterator: ...
    def __get__(
        self, obj: object, cls: type | None = ...
    ) -> EnumeratedSetFromIterator_method_caller: ...

class EnumeratedSetFromIterator_method_decorator:
    def __init__(self, f: Callable[..., Iterator[object]], **options: object) -> None: ...
    def __call__(self, meth: Callable[..., Iterator[object]]) -> EnumeratedSetFromIterator_method_caller: ...
    def __get__(
        self, obj: object, cls: type | None = ...
    ) -> EnumeratedSetFromIterator_method_caller: ...

class DummyExampleForPicklingTest:
    def f(self) -> Iterator[int]: ...
