from collections.abc import Iterable
from sage.structure.element import Element
from sage.structure.parent import Parent

from .finite_enumerated_set import FiniteEnumeratedSet

class TotallyOrderedFiniteSetElement(Element):
    value: object
    def __init__(self, parent: Parent, data: object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def _richcmp_(self, other: TotallyOrderedFiniteSetElement, op: int) -> bool: ...
    def _repr_(self) -> str: ...
    def __str__(self) -> str: ...

class TotallyOrderedFiniteSet(FiniteEnumeratedSet):
    def __classcall__(cls, *args: object, **options: object) -> TotallyOrderedFiniteSet: ...
    def __init__(
        self,
        elements: tuple[object, ...],
        facade: bool = ...,
    ) -> None: ...
    def _element_constructor_(self, x: object) -> TotallyOrderedFiniteSetElement | object: ...
    def le(self, x: object, y: object) -> bool: ...
