from collections.abc import Iterable, Iterator
from typing import Generic, Self, TypeVar

from sage.categories.sets_cat import Sets
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.parent import Parent

from .finite_enumerated_set import FiniteEnumeratedSet

_E = TypeVar("_E", default=Element)

class TotallyOrderedFiniteSetElement(Element):
    value: object

    def __init__(self, parent: Parent | Parent[Self], data: object) -> None: ...
    def __eq__(self, other: object | MembershipInput) -> bool: ...
    def __ne__(self, other: object | MembershipInput) -> bool: ...
    def _richcmp_(self, other: TotallyOrderedFiniteSetElement, op: int) -> bool: ...
    def _repr_(self) -> str: ...

class TotallyOrderedFiniteSet(FiniteEnumeratedSet, Sets.ParentMethods[_E], Generic[_E]):
    @staticmethod
    def __classcall__(
        cls, *args: object, **options: object
    ) -> TotallyOrderedFiniteSet: ...
    def __init__(self, elements: Iterable[_E], facade: bool = ...) -> None: ...
    def _element_constructor_(
        self, x: object
    ) -> TotallyOrderedFiniteSetElement | object: ...
    def __iter__(self) -> Iterator[TotallyOrderedFiniteSet]: ...
    def __len__(self) -> int: ...
    def cardinality(self) -> Integer: ...
    def list(self) -> list[TotallyOrderedFiniteSet]: ...
    def first(self) -> TotallyOrderedFiniteSet: ...
    def last(self) -> TotallyOrderedFiniteSet: ...
    def rank(self, x: _E) -> Integer: ...
    def unrank(self, i: int | Integer) -> TotallyOrderedFiniteSet: ...
    def le(self, x: _E, y: _E) -> bool: ...
