from collections.abc import Iterable, Iterator
from typing import Generic, TypeVar
from sage.categories.sets_cat import Sets
from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.parent import Parent

from .finite_enumerated_set import FiniteEnumeratedSet

_E = TypeVar("_E", default=Element)

class TotallyOrderedFiniteSetElement(Element):
    value: object
    def __init__(self, parent: Parent, data: object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def _richcmp_(self, other: TotallyOrderedFiniteSetElement, op: int) -> bool: ...
    def _repr_(self) -> str: ...

class TotallyOrderedFiniteSet(FiniteEnumeratedSet, Sets.ParentMethods[_E], Generic[_E]):
    def __classcall__(cls, *args: object, **options: object) -> TotallyOrderedFiniteSet: ...
    def __init__(
        self,
        elements: Iterable[_E],
        facade: bool = ...,
    ) -> None: ...
    def _element_constructor_(self, x: object) -> TotallyOrderedFiniteSetElement | object: ...
    def __iter__(self) -> Iterator[_E]: ...
    def __len__(self) -> int: ...
    def cardinality(self) -> Integer: ...
    def list(self) -> list[_E]: ...
    def first(self) -> _E: ...
    def last(self) -> _E: ...
    def rank(self, x: _E) -> Integer: ...
    def unrank(self, i: int | Integer) -> _E: ...
    def le(self, x: _E, y: _E) -> bool: ...
