import builtins

class _SageObject: ...

class AGCode:
    def base_function_field(self) -> _SageObject: ...

class EvaluationAGCode:
    def __init__(self, pls: builtins.object, G: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def basis_functions(self) -> _SageObject: ...
    def generator_matrix(self) -> _SageObject: ...
    def designed_distance(self) -> _SageObject: ...

class DifferentialAGCode:
    def __init__(self, pls: builtins.object, G: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def basis_differentials(self) -> _SageObject: ...
    def generator_matrix(self) -> _SageObject: ...
    def designed_distance(self) -> _SageObject: ...

class CartierCode:
    def __init__(
        self,
        pls: builtins.object,
        G: builtins.object,
        r: builtins.int = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def generator_matrix(self) -> _SageObject: ...
    def designed_distance(self) -> _SageObject: ...
