# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def random_error_vector(n: builtins.int, F: builtins.object, error_positions: builtins.object) -> _SageObject: ...

def format_interval(t: builtins.object) -> _SageObject: ...

class Channel:
    def __init__(self, input_space: builtins.object, output_space: builtins.object) -> None: ...
    def transmit(self, message: builtins.object) -> _SageObject: ...
    def input_space(self) -> _SageObject: ...
    def output_space(self) -> _SageObject: ...
    def transmit_unsafe(self, message: builtins.object) -> _SageObject: ...

class StaticErrorRateChannel:
    def __init__(self, space: builtins.object, number_errors: builtins.object) -> None: ...
    def transmit_unsafe(self, message: builtins.object) -> _SageObject: ...
    def number_errors(self) -> _SageObject: ...

class ErrorErasureChannel:
    def __init__(self, space: builtins.object, number_errors: builtins.object, number_erasures: builtins.object) -> None: ...
    def transmit_unsafe(self, message: builtins.object) -> _SageObject: ...
    def number_errors(self) -> _SageObject: ...
    def number_erasures(self) -> _SageObject: ...

class QarySymmetricChannel:
    def __init__(self, space: builtins.object, epsilon: builtins.object) -> None: ...
    def transmit_unsafe(self, message: builtins.object) -> _SageObject: ...
    def error_probability(self) -> _SageObject: ...
    def probability_of_exactly_t_errors(self, t: builtins.object) -> _SageObject: ...
    def probability_of_at_most_t_errors(self, t: builtins.object) -> _SageObject: ...
