import builtins

class _SageObject: ...

def permutation_action(self, v: builtins.object) -> _SageObject: ...
def walsh_matrix(self) -> _SageObject: ...
def DuadicCodeEvenPair(
    self, S1: builtins.object, S2: builtins.object
) -> _SageObject: ...
def DuadicCodeOddPair(
    self, S1: builtins.object, S2: builtins.object
) -> _SageObject: ...
def ExtendedQuadraticResidueCode(self, F: builtins.object) -> _SageObject: ...
def from_parity_check_matrix(self) -> _SageObject: ...
def QuadraticResidueCode(self, F: builtins.object) -> _SageObject: ...
def QuadraticResidueCodeEvenPair(self, F: builtins.object) -> _SageObject: ...
def QuadraticResidueCodeOddPair(self, F: builtins.object) -> _SageObject: ...
def random_linear_code(
    self, length: builtins.int, dimension: builtins.int
) -> _SageObject: ...
def ToricCode(self, F: builtins.object) -> _SageObject: ...
def WalshCode(self) -> _SageObject: ...
