# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def permutation_action(g: builtins.object, v: builtins.object) -> _SageObject: ...

def walsh_matrix(m0: builtins.object) -> _SageObject: ...

def DuadicCodeEvenPair(F: builtins.object, S1: builtins.object, S2: builtins.object) -> _SageObject: ...

def DuadicCodeOddPair(F: builtins.object, S1: builtins.object, S2: builtins.object) -> _SageObject: ...

def ExtendedQuadraticResidueCode(n: builtins.int, F: builtins.object) -> _SageObject: ...

def from_parity_check_matrix(H: builtins.object) -> _SageObject: ...

def QuadraticResidueCode(n: builtins.int, F: builtins.object) -> _SageObject: ...

def QuadraticResidueCodeEvenPair(n: builtins.int, F: builtins.object) -> _SageObject: ...

def QuadraticResidueCodeOddPair(n: builtins.int, F: builtins.object) -> _SageObject: ...

def random_linear_code(F: builtins.object, length: builtins.int, dimension: builtins.int) -> _SageObject: ...

def ToricCode(P: builtins.int, F: builtins.object) -> _SageObject: ...

def WalshCode(m: builtins.int) -> _SageObject: ...
