from typing import TYPE_CHECKING
from sage.structure.sage_object import SageObject

if TYPE_CHECKING:
    from sage.coding.linear_code import AbstractLinearCode
    from sage.coding.encoder import Encoder
    from sage.modules.free_module import VectorSpace
    from sage.modules.free_module_element import FreeModuleElement

class Decoder(SageObject):
    @classmethod
    def decoder_type(cls) -> set[str]: ...
    def __init__(self, code: AbstractLinearCode, input_space: object, connected_encoder_name: str) -> None: ...
    def __hash__(self) -> int: ...
    def decode_to_code(self, r: object) -> FreeModuleElement: ...
    def connected_encoder(self) -> Encoder: ...
    def decode_to_message(self, r: object) -> FreeModuleElement: ...
    def code(self) -> AbstractLinearCode: ...
    def message_space(self) -> VectorSpace: ...
    def input_space(self) -> VectorSpace: ...
    def decoding_radius(self, **kwargs: object) -> int: ...

class DecodingError(Exception):
    pass
