# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def krawtchouk(n: builtins.int, q: builtins.int, l: builtins.object, x: builtins.object, check: builtins.bool = ...) -> _SageObject: ...

def eberlein(n: builtins.int, w: builtins.object, k: builtins.int, u: builtins.object, check: builtins.bool = ...) -> _SageObject: ...

def delsarte_bound_constant_weight_code(n: builtins.int, d: builtins.object, w: builtins.object, return_data: builtins.bool = ..., solver: builtins.str = ..., isinteger: builtins.bool = ...) -> _SageObject: ...

def delsarte_bound_hamming_space(n: builtins.int, d: builtins.object, q: builtins.int, return_data: builtins.bool = ..., solver: builtins.str = ..., isinteger: builtins.bool = ...) -> _SageObject: ...

def delsarte_bound_additive_hamming_space(n: builtins.int, d: builtins.object, q: builtins.int, d_star: builtins.int = ..., q_base: builtins.int = ..., return_data: builtins.bool = ..., solver: builtins.str = ..., isinteger: builtins.bool = ...) -> _SageObject: ...

def delsarte_bound_Q_matrix(q: builtins.int, d: builtins.object, return_data: builtins.bool = ..., solver: builtins.str = ..., isinteger: builtins.bool = ...) -> _SageObject: ...
