import builtins

class _SageObject: ...

class ExtendedCode:
    def __init__(self, C: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def original_code(self) -> _SageObject: ...
    def parity_check_matrix(self) -> _SageObject: ...
    def random_element(self) -> _SageObject: ...

class ExtendedCodeExtendedMatrixEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def generator_matrix(self) -> _SageObject: ...

class ExtendedCodeOriginalCodeDecoder:
    def __init__(
        self,
        code: builtins.object,
        original_decoder: builtins.object = ...,
        **kwargs: builtins.object,
    ) -> None: ...
    def original_decoder(self) -> _SageObject: ...
    def decode_to_code(
        self, y: builtins.object, **kwargs: builtins.object
    ) -> _SageObject: ...
    def decoding_radius(
        self, *args: builtins.object, **kwargs: builtins.object
    ) -> _SageObject: ...
