import builtins

class _SageObject: ...

class GabidulinCode:
    def __init__(
        self,
        base_field: builtins.object,
        length: builtins.int,
        dimension: builtins.int,
        sub_field: builtins.object = ...,
        twisting_homomorphism: builtins.object = ...,
        evaluation_points: builtins.object = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def twisting_homomorphism(self) -> _SageObject: ...
    def minimum_distance(self) -> _SageObject: ...
    def parity_evaluation_points(self) -> _SageObject: ...
    def dual_code(self) -> _SageObject: ...
    def parity_check_matrix(self) -> _SageObject: ...
    def evaluation_points(self) -> _SageObject: ...

class GabidulinVectorEvaluationEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def generator_matrix(self) -> _SageObject: ...

class GabidulinPolynomialEvaluationEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def message_space(self) -> _SageObject: ...
    def encode(self, p: builtins.int, form: builtins.str = ...) -> _SageObject: ...
    def unencode_nocheck(self, c: builtins.object) -> _SageObject: ...

class GabidulinGaoDecoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def decode_to_code(self, r: builtins.int) -> _SageObject: ...
    def decode_to_message(self, r: builtins.int) -> _SageObject: ...
    def decoding_radius(self) -> _SageObject: ...
