# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class GoppaCode:
    def __init__(self, generating_pol: builtins.object, defining_set: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def parity_check_matrix(self) -> _SageObject: ...
    def distance_bound(self) -> _SageObject: ...

class GoppaCodeEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def generator_matrix(self) -> _SageObject: ...
