import builtins

class _SageObject: ...

class HammingCode:
    def __init__(self, base_field: builtins.object, order: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def parity_check_matrix(self) -> _SageObject: ...
    def minimum_distance(self) -> _SageObject: ...
