import builtins

class _SageObject: ...

class InformationSetAlgorithm:
    def __init__(
        self,
        code: builtins.object,
        decoding_interval: builtins.object,
        algorithm_name: builtins.str,
        parameters: builtins.object = ...,
    ) -> None: ...
    def name(self) -> _SageObject: ...
    def decode(self, r: builtins.int) -> _SageObject: ...
    def time_estimate(self) -> _SageObject: ...
    def calibrate(self) -> _SageObject: ...
    def code(self) -> _SageObject: ...
    def decoding_interval(self) -> _SageObject: ...
    def parameters(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...

class LeeBrickellISDAlgorithm:
    def __init__(
        self,
        code: builtins.object,
        decoding_interval: builtins.object,
        search_size: builtins.object = ...,
    ) -> None: ...
    def decode(self, r: builtins.int) -> _SageObject: ...
    def calibrate(self) -> _SageObject: ...

class LinearCodeInformationSetDecoder:
    def __init__(
        self,
        code: builtins.object,
        number_errors: builtins.object,
        algorithm: builtins.str = ...,
        **kwargs: builtins.object,
    ) -> None: ...
    @staticmethod
    def known_algorithms(dictionary: builtins.bool = ...) -> _SageObject: ...
    def algorithm(self) -> _SageObject: ...
    def decode_to_code(self, r: builtins.int) -> _SageObject: ...
    def decoding_radius(self) -> _SageObject: ...
    def decoding_interval(self) -> _SageObject: ...
