import builtins

class _SageObject: ...

class KasamiCode:
    def __init__(
        self, s: builtins.object, t: builtins.object, extended: builtins.object = ...
    ) -> None: ...
    def parameters(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def generator_matrix(self) -> _SageObject: ...
    def exp(row: builtins.object) -> _SageObject: ...
