# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class KasamiCode:
    def __init__(self, s: builtins.object, t: builtins.object, extended: builtins.object = ...) -> None: ...
    def parameters(self) -> _SageObject: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def generator_matrix(self) -> _SageObject: ...
    def exp(row: builtins.object) -> _SageObject: ...
