# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def to_matrix_representation(v: builtins.object, sub_field: builtins.object = ..., basis: builtins.object = ...) -> _SageObject: ...

def from_matrix_representation(w: builtins.object, base_field: builtins.object = ..., basis: builtins.object = ...) -> _SageObject: ...

def rank_weight(c: builtins.object, sub_field: builtins.object = ..., basis: builtins.object = ...) -> _SageObject: ...

def rank_distance(a: builtins.object, b: builtins.object, sub_field: builtins.object = ..., basis: builtins.object = ...) -> _SageObject: ...

class AbstractLinearRankMetricCode:
    def __init__(self, base_field: builtins.object, sub_field: builtins.object, length: builtins.int, default_encoder_name: builtins.str, default_decoder_name: builtins.str, basis: builtins.object = ...) -> None: ...
    def sub_field(self) -> _SageObject: ...
    def extension_degree(self) -> _SageObject: ...
    def field_extension(self) -> _SageObject: ...
    def rank_distance_between_vectors(self, left: builtins.object, right: builtins.object) -> _SageObject: ...
    def minimum_distance(self) -> _SageObject: ...
    def rank_weight_of_vector(self, word: builtins.object) -> _SageObject: ...
    def rank_support_of_vector(self, word: builtins.object, sub_field: builtins.object = ..., basis: builtins.object = ...) -> _SageObject: ...
    def matrix_form_of_vector(self, word: builtins.object) -> _SageObject: ...
    def vector_form_of_matrix(self, word: builtins.object) -> _SageObject: ...

class LinearRankMetricCode:
    def __init__(self, generator: builtins.object, sub_field: builtins.object = ..., basis: builtins.object = ...) -> None: ...
    def generator_matrix(self, encoder_name: builtins.str = ..., **kwargs: builtins.object) -> _SageObject: ...

class LinearRankMetricCodeNearestNeighborDecoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def decode_to_code(self, r: builtins.int) -> _SageObject: ...
    def decoding_radius(self) -> _SageObject: ...
