from sage.coding.decoder import Decoder
from sage.coding.encoder import Encoder
from sage.graphs.graph import Graph
from sage.matrix.matrix import Matrix
from sage.modules.free_module import FreeModule_ambient_field
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.finite_rings.finite_field_base import FiniteField
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ring import CommutativeRing

class AbstractLinearCode:
    _registered_encoders: dict[str, type]
    _registered_decoders: dict[str, type]

    def __init__(self, base_field: FiniteField, length: int,
                 default_encoder_name: str, default_decoder_name: str) -> None: ...

    def automorphism_group_gens(self, equivalence: str = 'semilinear') -> tuple[list[object], int]: ...
    def assmus_mattson_designs(self, t: int, mode: str | None = None) -> list[object] | int: ...
    def binomial_moment(self, i: int) -> int: ...
    def canonical_representative(self, equivalence: str = 'semilinear') -> AbstractLinearCode: ...
    def characteristic(self) -> int: ...
    def characteristic_polynomial(self) -> Polynomial: ...
    def chinen_polynomial(self, names: str = 'x', twisted: bool = False) -> Polynomial: ...
    def covering_radius(self) -> int: ...
    def divisor(self) -> int: ...
    def is_projective(self) -> bool: ...
    def direct_sum(self, other: AbstractLinearCode) -> LinearCode: ...
    def juxtapose(self, other: AbstractLinearCode) -> LinearCode: ...
    def u_u_plus_v_code(self, other: AbstractLinearCode) -> LinearCode: ...
    def product_code(self, other: AbstractLinearCode) -> LinearCode: ...
    def construction_x(self, other: AbstractLinearCode, aux: AbstractLinearCode) -> LinearCode: ...
    def extended_code(self) -> LinearCode: ...
    def galois_closure(self, F0: FiniteField) -> LinearCode: ...
    def genus(self) -> int: ...
    def is_permutation_equivalent(self, other: AbstractLinearCode, algorithm: str | None = None) -> bool: ...
    def is_galois_closed(self) -> bool: ...
    def minimum_distance(self, algorithm: str | None = None) -> int: ...
    def module_composition_factors(self, gp: object) -> list[object]: ...
    def permutation_automorphism_group(self, algorithm: str = 'partition') -> tuple[object, ...]: ...
    def punctured(self, L: list[int]) -> LinearCode: ...
    def relative_distance(self) -> float: ...
    def shortened(self, L: list[int]) -> LinearCode: ...
    def weight_distribution(self, algorithm: str | None = None) -> list[int]: ...
    def support(self) -> list[int]: ...
    def weight_enumerator(self, names: str | None = None, bivariate: bool = True) -> Polynomial: ...
    def zeta_polynomial(self, name: str = 'T') -> Polynomial: ...
    def zeta_function(self, name: str = 'T') -> Polynomial: ...
    def cosetGraph(self, immutable: bool = False) -> Graph: ...

    # From AbstractLinearCodeNoMetric
    def base_field(self) -> FiniteField: ...
    def base_ring(self) -> CommutativeRing: ...
    def dimension(self) -> int: ...
    def length(self) -> int: ...
    def ambient_space(self) -> FreeModule_ambient_field: ...
    def encoder(self, encoder_name: str | None = None, *args: object, **kwargs: object) -> Encoder: ...
    def decoder(self, decoder_name: str | None = None, *args: object, **kwargs: object) -> Decoder: ...
    def encoders_available(self, classes: bool = False) -> list[str] | dict[str, type]: ...
    def decoders_available(self, classes: bool = False) -> list[str] | dict[str, type]: ...
    def encode(self, word: object, encoder_name: str | None = None, *args: object, **kwargs: object) -> FreeModuleElement: ...
    def decode(self, r: object, decoder_name: str | None = None, *args: object, **kwargs: object) -> FreeModuleElement: ...
    def decode_to_code(self, r: object, decoder_name: str | None = None, *args: object, **kwargs: object) -> FreeModuleElement: ...
    def unencode(self, c: object, encoder_name: str | None = None, nocheck: bool = False, **kwargs: object) -> FreeModuleElement: ...
    def generator_matrix(self, encoder_name: str | None = None, **kwargs: object) -> Matrix: ...
    def parity_check_matrix(self, encoder_name: str | None = None, **kwargs: object) -> Matrix: ...
    def dual_code(self) -> LinearCode: ...
    def gens(self) -> tuple[FreeModuleElement, ...]: ...
    def basis(self) -> list[FreeModuleElement]: ...
    def information_set(self) -> list[int]: ...
    def is_self_orthogonal(self) -> bool: ...
    def is_self_dual(self) -> bool: ...
    def is_subcode(self, other: AbstractLinearCode) -> bool: ...
    def redundancy_matrix(self) -> Matrix: ...
    def standard_form(self, return_permutation: bool = True) -> LinearCode | tuple[LinearCode, object]: ...

class LinearCode(AbstractLinearCode):
    def __init__(self, generator: object, d: int | None = None) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def intersection(self, other: AbstractLinearCode) -> LinearCode: ...
    def generator_matrix(self, encoder_name: str | None = None, **kwargs: object) -> Matrix: ...

class LinearCodeGeneratorMatrixEncoder:
    def __init__(self, code: LinearCode) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def code(self) -> LinearCode: ...
    def message_space(self) -> FreeModule_ambient_field: ...
    def generator_matrix(self) -> Matrix: ...
    def encode(self, word: object) -> FreeModuleElement: ...
    def unencode(self, c: object, nocheck: bool = False) -> FreeModuleElement: ...
    def unencode_nocheck(self, c: object) -> FreeModuleElement: ...

class LinearCodeSyndromeDecoder:
    def __init__(self, code: LinearCode, maximum_error_weight: int | None = None) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def code(self) -> LinearCode: ...
    def message_space(self) -> FreeModule_ambient_field: ...
    def decode_to_code(self, r: object) -> FreeModuleElement: ...
    def maximum_error_weight(self) -> int: ...
    def decoding_radius(self) -> int: ...
    def syndrome_table(self) -> dict[FreeModuleElement, FreeModuleElement]: ...

class LinearCodeNearestNeighborDecoder:
    def __init__(self, code: LinearCode) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def code(self) -> LinearCode: ...
    def message_space(self) -> FreeModule_ambient_field: ...
    def decode_to_code(self, r: object) -> FreeModuleElement: ...
    def decoding_radius(self) -> int: ...
