# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ParityCheckCode:
    def __init__(self, base_field: builtins.object = ..., dimension: builtins.int = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def minimum_distance(self) -> _SageObject: ...

class ParityCheckCodeGeneratorMatrixEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def generator_matrix(self) -> _SageObject: ...

class ParityCheckCodeStraightforwardEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def encode(self, message: builtins.object) -> _SageObject: ...
    def unencode_nocheck(self, word: builtins.object) -> _SageObject: ...
    def message_space(self) -> _SageObject: ...
