import builtins

class _SageObject: ...

class PuncturedCode:
    def __init__(self, C: builtins.object, positions: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def punctured_positions(self) -> _SageObject: ...
    def original_code(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def random_element(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def encode(
        self,
        m: builtins.int,
        original_encode: builtins.bool = ...,
        encoder_name: builtins.str = ...,
        **kwargs: builtins.object,
    ) -> _SageObject: ...
    def structured_representation(self) -> _SageObject: ...

class PuncturedCodePuncturedMatrixEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def generator_matrix(self) -> _SageObject: ...

class PuncturedCodeOriginalCodeDecoder:
    def __init__(
        self,
        code: builtins.object,
        strategy: builtins.object = ...,
        original_decoder: builtins.object = ...,
        **kwargs: builtins.object,
    ) -> None: ...
    def original_decoder(self) -> _SageObject: ...
    def decode_to_code(self, y: builtins.object) -> _SageObject: ...
    def decoding_radius(
        self, number_erasures: builtins.object = ...
    ) -> _SageObject: ...
