import builtins

class _SageObject: ...

def ReedMullerCode(
    self, order: builtins.object, num_of_var: builtins.object
) -> _SageObject: ...

class QAryReedMullerCode:
    def __init__(
        self,
        base_field: builtins.object,
        order: builtins.object,
        num_of_var: builtins.object,
    ) -> None: ...
    def order(self) -> _SageObject: ...
    def number_of_variables(self) -> _SageObject: ...
    def minimum_distance(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...

class BinaryReedMullerCode:
    def __init__(self, order: builtins.object, num_of_var: builtins.object) -> None: ...
    def order(self) -> _SageObject: ...
    def number_of_variables(self) -> _SageObject: ...
    def minimum_distance(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...

class ReedMullerVectorEncoder:
    def __init__(self, code: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def generator_matrix(self) -> _SageObject: ...
    def points(self) -> _SageObject: ...

class ReedMullerPolynomialEncoder:
    def __init__(
        self, code: builtins.object, polynomial_ring: builtins.object = ...
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def encode(self, p: builtins.int) -> _SageObject: ...
    def unencode_nocheck(self, c: builtins.object) -> _SageObject: ...
    def message_space(self) -> _SageObject: ...
    def polynomial_ring(self) -> _SageObject: ...
    def points(self) -> _SageObject: ...
