from sage.rings.ring import CommutativeRing
from sage.rings.polynomial.multi_polynomial_ring_base import MPolynomialRing_base

class AffineSpace_generic:
    def dimension(self) -> int: ...
    def base_ring(self) -> CommutativeRing: ...
    def coordinate_ring(self) -> MPolynomialRing_base: ...
