# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ModularFormsAmbient_g0_Q:
    def __init__(self, level: builtins.object, weight: builtins.object) -> None: ...
    def cuspidal_submodule(self) -> _SageObject: ...
    def eisenstein_submodule(self) -> _SageObject: ...
