from sage.modular.hecke.element import HeckeModuleElement
from sage.rings.integer import Integer
from sage.modular.dirichlet import DirichletCharacter
from sage.modular.modform.space import ModularFormsSpace

class ModularForm_abstract(HeckeModuleElement): ...

class ModularFormElement(ModularForm_abstract):
    def __init__(self, parent: ModularFormsSpace, x: object, check: bool = ...) -> None: ...
    def atkin_lehner_eigenvalue(self, d: Integer | None = ..., embedding: object = ...) -> Integer: ...
    def twist(self, chi: DirichletCharacter | None = ..., level: Integer | None = ...) -> ModularFormElement: ...
