import builtins

class _SageObject: ...

scipy: _SageObject

class NumericalEigenforms:
    def __init__(
        self,
        group: builtins.object,
        weight: builtins.int = ...,
        eps: builtins.float = ...,
        delta: builtins.float = ...,
        tp: builtins.list[_SageObject] = ...,
    ) -> None: ...
    def __richcmp__(
        self, other: builtins.object, op: builtins.object
    ) -> _SageObject: ...
    def level(self) -> _SageObject: ...
    def weight(self) -> _SageObject: ...
    def modular_symbols(self) -> _SageObject: ...
    def ap(self, p: builtins.int) -> _SageObject: ...
    def eigenvalues(self, primes: builtins.object) -> _SageObject: ...
    def systems_of_eigenvalues(self, bound: builtins.object) -> _SageObject: ...
    def systems_of_abs(self, bound: builtins.object) -> _SageObject: ...

def support(self, eps: builtins.object) -> _SageObject: ...
