import builtins

class _SageObject: ...

def modular_ratio_space(self) -> _SageObject: ...
def modular_ratio_to_prec(
    self, qexp: builtins.object, prec: builtins.int
) -> _SageObject: ...
def hecke_stable_subspace(self, aux_prime: builtins.object = ...) -> _SageObject: ...
def dimension_wt1_cusp_forms(self) -> _SageObject: ...
def dimension_wt1_cusp_forms_gH(self) -> _SageObject: ...
