from collections.abc import Callable
from typing import Generic, Self, TypeVar

from sage.algebras.finite_dimensional_algebras.finite_dimensional_algebra import (
    FiniteDimensionalAlgebra,
    FiniteDimensionalAlgebraElementInput,
)
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import AlgebraElement, FieldElement, RingElement, Vector

_Scalar = TypeVar(
    "_Scalar",
    bound=FieldElement,
    default=FieldElement,
)

def unpickle_FiniteDimensionalAlgebraElement(
    A: FiniteDimensionalAlgebra[_Scalar],
    vec: Matrix[_Scalar],
    mat: Matrix[_Scalar] | None,
) -> FiniteDimensionalAlgebraElement[_Scalar]: ...

class FiniteDimensionalAlgebraElement(
    AlgebraElement,
    Generic[_Scalar],
):
    def __init__(
        self,
        A: FiniteDimensionalAlgebra[_Scalar],
        elt: FiniteDimensionalAlgebraElementInput[_Scalar] = None,
        check: bool = True,
    ) -> None: ...
    def parent(self) -> FiniteDimensionalAlgebra[_Scalar]: ...
    def __reduce__(
        self,
    ) -> tuple[
        Callable[
            [
                FiniteDimensionalAlgebra[_Scalar],
                Matrix[_Scalar],
                Matrix[_Scalar] | None,
            ],
            FiniteDimensionalAlgebraElement[_Scalar],
        ],
        tuple[
            FiniteDimensionalAlgebra[_Scalar],
            Matrix[_Scalar],
            Matrix[_Scalar] | None,
        ],
    ]: ...
    def __setstate__(
        self,
        state: tuple[
            FiniteDimensionalAlgebra[_Scalar],
            dict[str, Matrix[_Scalar] | Vector[_Scalar] | None],
        ],
    ) -> None: ...
    @property
    def _matrix(self) -> Matrix[_Scalar]: ...
    def vector(self) -> FreeModuleElement[_Scalar]: ...
    def matrix(self) -> Matrix[_Scalar]: ...
    def monomial_coefficients(self, copy: bool = True) -> dict[int, _Scalar]: ...
    def left_matrix(self) -> Matrix[_Scalar]: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, m: int | Integer) -> _Scalar: ...
    def __len__(self) -> int: ...
    def _richcmp_(self, other: Self, op: int) -> bool: ...
    def _add_(self, other: Self) -> Self: ...
    def _sub_(self, other: Self) -> Self: ...
    def _mul_(self, other: Self) -> Self: ...
    def _lmul_(self, other: RingElement) -> Self: ...
    def _rmul_(self, other: RingElement) -> Self: ...
    def __pow__(
        self,
        n: int | Integer,
        modulus: None = None,
    ) -> Self: ...
    def __invert__(self) -> Self: ...
    def is_invertible(self) -> bool: ...
    @property
    def _inverse(self) -> Self | None: ...
    def inverse(self) -> Self: ...
    def is_zerodivisor(self) -> bool: ...
    def is_nilpotent(self) -> bool: ...
    def minimal_polynomial(self) -> Polynomial: ...
    def characteristic_polynomial(self) -> Polynomial: ...
