import builtins

class _SageObject: ...

class FiniteDimensionalAlgebraIdeal:
    def __init__(
        self,
        A: builtins.object,
        gens: builtins.object = ...,
        given_by_matrix: builtins.bool = ...,
    ) -> bool: ...
    def __contains__(self, elt: object) -> bool: ...
    def basis_matrix(self) -> _SageObject: ...
    def vector_space(self) -> _SageObject: ...
