from sage.structure.element import Element

class BipartiteGraph(Graph):
    def _upgrade_from_graph(self) -> Element: ...
    def add_vertex(self, name: str, left: Element | int | str | bool | None, right: Element | int | str | bool | None) -> Element: ...
    def add_vertices(self, vertices: Element | int | str | bool | None, left: Element | int | str | bool | None, right: Element | int | str | bool | None) -> Element: ...
    def delete_vertex(self, vertex: Element | int | str | bool | None, in_order: Element | int | str | bool | None) -> Element: ...
    def delete_vertices(self, vertices: Element | int | str | bool | None) -> Element: ...
    def _flip_vertices(self, vertices: Element | int | str | bool | None) -> Element: ...
    def add_edge(self, u: Element | int | str | bool | None, v: Element, label: str) -> Element: ...
    def add_edges(self, edges: Element | int | str | bool | None, loops: Element | int | str | bool | None) -> Element: ...
    def _check_bipartition_for_add_edges(self, edges: Element | int | str | bool | None) -> Element: ...
    def allow_loops(self, new: Element | int | str | bool | None, check: bool) -> Element: ...
    def is_bipartite(self, certificate: Element | int | str | bool | None) -> bool: ...
    def complement(self) -> Element: ...
    def complement_bipartite(self) -> Element: ...
    def to_undirected(self) -> Element: ...
    def bipartition(self) -> Element: ...
    def project_left(self, immutable: Element | int | str | bool | None) -> Element: ...
    def project_right(self, immutable: Element | int | str | bool | None) -> Element: ...
    def plot(self) -> Element: ...
    def matching_polynomial(self, algorithm: str, name: str) -> Element: ...
    def perfect_matchings(self, labels: Element | int | str | bool | None) -> Element: ...
    def load_afile(self, fname: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def save_afile(self, fname: Element | int | str | bool | None) -> Element: ...
    def reduced_adjacency_matrix(self, sparse: Element | int | str | bool | None) -> Element: ...
    def matching(self, value_only: Element | int | str | bool | None, algorithm: str, use_edge_labels: Element | int | str | bool | None, solver: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def vertex_cover(self, algorithm: str, value_only: Element | int | str | bool | None, reduction_rules: Element | int | str | bool | None, solver: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def _subgraph_by_adding(self, vertices: Element | int | str | bool | None, edges: Element | int | str | bool | None, edge_property: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def _subgraph_by_deleting(self, vertices: Element | int | str | bool | None, edges: Element | int | str | bool | None, inplace: Element | int | str | bool | None, edge_property: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def canonical_label(self, partition: Element | int | str | bool | None, certificate: Element | int | str | bool | None, edge_labels: Element | int | str | bool | None, algorithm: str, return_graph: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...

class Graph: ...
