from sage.structure.element import Element

def centrality_betweenness(G: Element | int | str | bool | None, exact: Element | int | str | bool | None, normalize: Element | int | str | bool | None) -> Element: ...
def centrality_closeness_top_k(G: Element | int | str | bool | None, k: int, verbose: bool) -> Element: ...
def centrality_closeness_random_k(G: Element | int | str | bool | None, k: int) -> Element: ...
