# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def centrality_betweenness(G: builtins.object, exact: builtins.object = ..., normalize: builtins.object = ...) -> _SageObject: ...

def centrality_betweenness_C(G: builtins.object, _: builtins.object, normalize: builtins.object = ...) -> _SageObject: ...

def centrality_closeness_top_k(G: builtins.object, k: builtins.object = ..., verbose: builtins.object = ...) -> _SageObject: ...

def centrality_closeness_random_k(G: builtins.object, k: builtins.object = ...) -> _SageObject: ...
