from sage.structure.element import Element

def chromatic_polynomial(G: Element | int | str | bool | None, return_tree_basis: Element | int | str | bool | None, algorithm: str, cache: Element | int | str | bool | None) -> Element: ...
def chromatic_polynomial_with_cache(G: Element | int | str | bool | None, cache: Element | int | str | bool | None) -> Element: ...
