from sage.structure.element import Element

def max_clique(graph: Element | int | str | bool | None) -> Element: ...
def all_max_clique(graph: Element | int | str | bool | None) -> Element: ...
def all_cliques(graph: Element | int | str | bool | None, min_size: Element | int | str | bool | None, max_size: Element | int | str | bool | None) -> Element: ...
def clique_number(graph: Element | int | str | bool | None) -> Element: ...
