# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CoTree:
    def __init__(self, name: builtins.str = ...) -> None: ...
    def add_child(self, node: builtins.object) -> _SageObject: ...
    def copy_tree(self, T: builtins.object) -> _SageObject: ...
    def reset_info(self) -> _SageObject: ...

def rebuild_node(u: builtins.object, P: builtins.int) -> _SageObject: ...

def find_pivot(T: builtins.object) -> _SageObject: ...

def next_tree(T: builtins.object) -> _SageObject: ...

def cographs(n: builtins.int, as_graph: builtins.bool = ..., immutable: builtins.bool = ...) -> _SageObject: ...

def change_label(tree: builtins.object, status: builtins.object, counter: builtins.object) -> _SageObject: ...

def tree_to_graph(tree: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...
