import builtins

class _SageObject: ...

class CoTree:
    parent: None
    info: None
    name: builtins.str

    def __init__(self, name: builtins.str = ...) -> None: ...
    def add_child(self, node: builtins.object) -> _SageObject: ...
    def copy_tree(self, T: builtins.object) -> _SageObject: ...
    def reset_info(self) -> _SageObject: ...

def rebuild_node(self, P: builtins.int) -> _SageObject: ...
def find_pivot(self) -> _SageObject: ...
def next_tree(self) -> _SageObject: ...
def cographs(
    self, as_graph: builtins.bool = ..., immutable: builtins.bool = ...
) -> _SageObject: ...
def change_label(
    self, status: builtins.object, counter: builtins.object
) -> _SageObject: ...
def tree_to_graph(self, immutable: builtins.bool = ...) -> _SageObject: ...
