from sage.structure.element import Element
from sage.structure.parent import Parent

def rebuild_node(u: Element | int | str | bool | None, P: Parent) -> Element: ...
def find_pivot(T: Element | int | str | bool | None) -> Element: ...
def next_tree(T: Element | int | str | bool | None) -> Element: ...
def cographs(n: int, as_graph: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def change_label(tree: Element | int | str | bool | None, status: Element | int | str | bool | None, counter: Element | int | str | bool | None) -> Element: ...
def tree_to_graph(tree: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...

class CoTree:
    def add_child(self, node: Element | int | str | bool | None) -> Element: ...
    def copy_tree(self, T: Element | int | str | bool | None) -> Element: ...
    def reset_info(self) -> Element: ...
