from sage.structure.element import Element

class DiGraphGenerators:
    def ButterflyGraph(self, n: int, vertices: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def Path(self, n: int, immutable: Element | int | str | bool | None) -> Element: ...
    def StronglyRegular(self, n: int, immutable: Element | int | str | bool | None) -> Element: ...
    def Paley(self, q: int, immutable: Element | int | str | bool | None) -> Element: ...
    def TransitiveTournament(self, n: int, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomTournament(self, n: int, immutable: Element | int | str | bool | None) -> Element: ...
    def tournaments_nauty(self, n: int, min_out_degree: Element | int | str | bool | None, max_out_degree: Element | int | str | bool | None, strongly_connected: Element | int | str | bool | None, debug: Element | int | str | bool | None, options: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def nauty_directg(self, graphs: Element | int | str | bool | None, options: Element | int | str | bool | None, debug: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def nauty_posetg(self, options: Element | int | str | bool | None, debug: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def Complete(self, n: int, loops: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def Circuit(self, n: int, immutable: Element | int | str | bool | None) -> Element: ...
    def Circulant(self, n: int, integers: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def DeBruijn(self, k: int, n: int, vertices: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def GeneralizedDeBruijn(self, n: int, d: int, immutable: Element | int | str | bool | None, name: str) -> Element: ...
    def ImaseItoh(self, n: int, d: int, immutable: Element | int | str | bool | None, name: str) -> Element: ...
    def Kautz(self, k: int, D: Element | int | str | bool | None, vertices: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomDirectedAcyclicGraph(self, n: int, p: int, weight_max: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomDirectedGN(self, n: int, kernel: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomDirectedGNC(self, n: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomDirectedGNP(self, n: int, p: int, loops: Element | int | str | bool | None, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomDirectedGNM(self, n: int, m: int, loops: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomDirectedGNR(self, n: int, p: int, seed: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def RandomSemiComplete(self, n: int, immutable: Element | int | str | bool | None) -> Element: ...
