from collections.abc import Hashable, Iterable, Iterator
from typing import Literal, overload

from sage.geometry.polyhedron.base import Polyhedron_base
from sage.graphs.generic_graph import GenericGraph
from sage.graphs.graph import Graph
from sage.quivers.path_semigroup import PathSemigroup
from sage.rings.polynomial.polynomial_element import Polynomial

class DiGraph(GenericGraph):
    def __init__(
        self,
        data: object = ...,
        pos: object = ...,
        loops: object = ...,
        format: object = ...,
        weighted: object = ...,
        data_structure: object = ...,
        vertex_labels: object = ...,
        name: object = ...,
        multiedges: object = ...,
        convert_empty_dict_labels_to_None: object = ...,
        sparse: object = ...,
        immutable: object = ...,
        hash_labels: object = ...,
    ) -> None: ...
    def dig6_string(self) -> str: ...
    def is_directed(self) -> bool: ...
    def is_directed_acyclic(
        self, certificate: bool = ...
    ) -> bool | tuple[bool, object]: ...
    def to_directed(self) -> DiGraph: ...
    def to_undirected(
        self, data_structure: str | None = ..., sparse: bool | None = ...
    ) -> Graph: ...
    def incoming_edge_iterator(
        self, vertices: object, labels: bool = ...
    ) -> Iterator[object]: ...
    def incoming_edges(self, vertices: object, labels: bool = ...) -> list[object]: ...
    def outgoing_edge_iterator(
        self, vertices: object, labels: bool = ...
    ) -> Iterator[object]: ...
    def outgoing_edges(self, vertices: object, labels: bool = ...) -> list[object]: ...
    def neighbor_in_iterator(self, vertex: object) -> Iterator[object]: ...
    def neighbors_in(self, vertex: object) -> list[object]: ...
    def neighbor_out_iterator(self, vertex: object) -> Iterator[object]: ...
    def neighbors_out(self, vertex: object) -> list[object]: ...
    # digraph.py ``in_degree``: a vertex gives its in-degree; otherwise the
    # vertices (all when ``None``) give a list, or a dict when ``labels``.
    @overload
    def in_degree(
        self, vertices: None = None, labels: Literal[False] = False
    ) -> list[int]: ...
    @overload
    def in_degree(
        self, vertices: None = None, *, labels: Literal[True]
    ) -> dict[Hashable, int]: ...
    @overload
    def in_degree(
        self, vertices: Hashable | Iterable[Hashable], labels: bool = False
    ) -> int | list[int] | dict[Hashable, int]: ...
    def in_degree_iterator(
        self, vertices: object = ..., labels: bool = ...
    ) -> Iterator[object]: ...
    def in_degree_sequence(self) -> list[int]: ...
    def out_degree(
        self, vertices: object = ..., labels: bool = ...
    ) -> int | dict[object, int]: ...
    def out_degree_iterator(
        self, vertices: object = ..., labels: bool = ...
    ) -> Iterator[object]: ...
    def out_degree_sequence(self) -> list[int]: ...
    def sources(self) -> list[object]: ...
    def sinks(self) -> list[object]: ...
    def degree_polynomial(
        self, weight_function: object = ..., ring: object = ...
    ) -> Polynomial: ...
    def feedback_edge_set(
        self,
        constraint_generation: bool = ...,
        value_only: bool = ...,
        solver: object = ...,
        verbose: int = ...,
    ) -> list[tuple[object, object]] | int: ...
    def reverse(self, immutable: bool | None = None) -> DiGraph: ...
    def reverse_edge(
        self,
        u: object,
        v: object = ...,
        label: object = ...,
        inplace: bool = ...,
        multiedges: bool = ...,
    ) -> DiGraph | None: ...
    def reverse_edges(self, edges: object, inplace: bool = ...) -> DiGraph | None: ...
    def eccentricity(
        self,
        v: object = ...,
        by_weight: bool = ...,
        algorithm: str = ...,
        weight_function: object = ...,
        check_weight: bool = ...,
        dist_dict: object = ...,
        with_labels: bool = ...,
    ) -> float | dict[object, float]: ...
    def radius(
        self,
        by_weight: bool = ...,
        algorithm: str = ...,
        weight_function: object = ...,
        check_weight: bool = ...,
    ) -> float: ...
    def diameter(
        self,
        by_weight: bool = ...,
        algorithm: str = ...,
        weight_function: object = ...,
        check_weight: bool = ...,
    ) -> float: ...
    def center(
        self,
        by_weight: bool = ...,
        algorithm: str = ...,
        weight_function: object = ...,
        check_weight: bool = ...,
    ) -> list[object]: ...
    def periphery(
        self,
        by_weight: bool = ...,
        algorithm: str = ...,
        weight_function: object = ...,
        check_weight: bool = ...,
    ) -> list[object]: ...
    def path_semigroup(self) -> PathSemigroup: ...
    def auslander_reiten_quiver(self) -> DiGraph: ...
    def topological_sort(self, generate_path: bool = ...) -> list[object]: ...
    def topological_sort_generator(self) -> Iterator[list[object]]: ...
    def longest_dag_path(self) -> list[object]: ...
    def layout_acyclic(self, **options: object) -> dict[object, list[float]]: ...
    def layout_acyclic_dummy(self, **options: object) -> dict[object, list[float]]: ...
    def level_sets(self) -> list[list[Hashable]]: ...
    def is_aperiodic(self, certificate: bool = ...) -> bool | tuple[bool, object]: ...
    def period(self) -> int: ...
    def flow_polytope(
        self, flow_roots: dict[object, int] | None = ..., backend: str = ...
    ) -> Polyhedron_base: ...
    def is_tournament(self, certificate: bool = ...) -> bool | tuple[bool, object]: ...
    def out_branchings(self, root: object = ...) -> Iterator[Graph]: ...
    def in_branchings(self, root: object = ...) -> Iterator[Graph]: ...
    # Class-body import (digraph.py): ``from sage.graphs.base.static_sparse_graph
    # import tarjan_strongly_connected_components as strongly_connected_components``.
    def strongly_connected_components(self) -> list[list[Hashable]]: ...
