# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def c_shortest_path_all_pairs(G: builtins.object, vertex_list: builtins.object = ...) -> _SageObject: ...

def shortest_path_all_pairs(G: builtins.object) -> _SageObject: ...

def c_distances_all_pairs(G: builtins.object, vertex_list: builtins.object = ...) -> _SageObject: ...

def distances_all_pairs(G: builtins.object) -> _SageObject: ...

def is_distance_regular(G: builtins.object, parameters: builtins.object = ...) -> builtins.bool: ...

def distances_and_predecessors_all_pairs(G: builtins.object) -> _SageObject: ...

def c_eccentricity(G: builtins.object, vertex_list: builtins.object = ...) -> _SageObject: ...

def c_eccentricity_bounding(sd: builtins.object) -> _SageObject: ...

def c_eccentricity_DHV(sd: builtins.object) -> _SageObject: ...

def eccentricity(G: builtins.object, algorithm: builtins.object = ..., vertex_list: builtins.object = ...) -> _SageObject: ...

def diameter_DHV(g: builtins.object) -> _SageObject: ...

def diameter(G: builtins.object, algorithm: builtins.object = ..., source: builtins.object = ...) -> _SageObject: ...

def radius_DHV(G: builtins.object) -> _SageObject: ...

def wiener_index(G: builtins.object) -> _SageObject: ...

def c_szeged_index_low_memory(sd: builtins.object) -> _SageObject: ...

def c_szeged_index_high_memory(sd: builtins.object) -> _SageObject: ...

def szeged_index(G: builtins.object, algorithm: builtins.object = ...) -> _SageObject: ...

def distances_distribution(G: builtins.object) -> _SageObject: ...

def antipodal_graph(G: builtins.object) -> _SageObject: ...

def floyd_warshall(gg: builtins.object, paths: builtins.object = ..., distances: builtins.object = ...) -> _SageObject: ...
