from sage.structure.element import Element

def is_dominating(G: Element | int | str | bool | None, dom: Element | int | str | bool | None, focus: Element | int | str | bool | None) -> bool: ...
def is_redundant(G: Element | int | str | bool | None, dom: Element | int | str | bool | None, focus: Element | int | str | bool | None) -> bool: ...
def private_neighbors(G: Element | int | str | bool | None, vertex: Element | int | str | bool | None, dom: Element | int | str | bool | None) -> Element: ...
def dominating_sets(g: Element, k: int, independent: Element | int | str | bool | None, total: Element | int | str | bool | None, connected: Element | int | str | bool | None, solver: Element | int | str | bool | None, verbose: bool) -> Element: ...
def dominating_set(g: Element, k: int, independent: Element | int | str | bool | None, total: Element | int | str | bool | None, connected: Element | int | str | bool | None, value_only: Element | int | str | bool | None, solver: Element | int | str | bool | None, verbose: bool) -> Element: ...
def minimal_dominating_sets(G: Element | int | str | bool | None, to_dominate: Element | int | str | bool | None, work_on_copy: Element | int | str | bool | None, k: int) -> Element: ...
def greedy_dominating_set(G: Element | int | str | bool | None, k: int, vertices: Element | int | str | bool | None, ordering: Element | int | str | bool | None, return_sets: Element | int | str | bool | None, closest: Element | int | str | bool | None) -> Element: ...
def maximum_leaf_number(G: Element | int | str | bool | None, solver: Element | int | str | bool | None, verbose: bool, integrality_tolerance: Element | int | str | bool | None) -> Element: ...
