from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class GenericGraph_pyx(SageObject):
    def layout_split(self, layout_function: Element | int | str | bool | None, G: Element | int | str | bool | None, **options: Element | int | str | bool | None) -> Element: ...
    def int_to_binary_string(self, n: int) -> Element: ...
    def binary_string_to_graph6(self, x: Element) -> Element: ...
    def small_integer_to_graph6(self, n: int) -> Element: ...
    def length_and_string_from_graph6(self, s: int) -> Element: ...
    def binary_string_from_graph6(self, s: int, n: int) -> Element: ...
    def binary_string_from_dig6(self, s: int, n: int) -> Element: ...

class SubgraphSearch:
    def cardinality(self) -> Integer: ...
    def _initialization(self) -> Element: ...
    def _test_vectors_equal_inferior(self) -> Element: ...
    def transitive_reduction_acyclic(self, G: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
