class GenericGraph:
    def order(self) -> int: ...
    def size(self) -> int: ...
    def vertices(self, sort: bool = False) -> list[object]: ...
    def edges(self, labels: bool = True, sort: bool = False) -> list[tuple[object, object, object]] | list[tuple[object, object]]: ...
    def add_vertex(self, name: object | None = None) -> object | None: ...
    def add_edge(self, u: object, v: object, label: object | None = None) -> None: ...
    def degree(self, vertices: object | None = None) -> int | list[int]: ...
    def is_connected(self) -> bool: ...
    def connected_components(self) -> list[list[object]]: ...
    def shortest_path(self, u: object, v: object) -> list[object]: ...
    def distance(self, u: object, v: object) -> int: ...
    def complement(self) -> GenericGraph: ...
    def subgraph(self, vertices: object | None = None) -> GenericGraph: ...
