# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def from_whatever(data: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def from_graph6(data: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def from_sparse6(data: builtins.object, immutable: builtins.bool = ...) -> _SageObject: ...

def to_graph6(graphs: builtins.object, file: builtins.object = ..., output_list: builtins.bool = ...) -> _SageObject: ...

def to_sparse6(graphs: builtins.object, file: builtins.object = ..., output_list: builtins.bool = ...) -> _SageObject: ...

def to_graphics_array(graph_list: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def show_graphs(graph_list: builtins.object, **kwds: builtins.object) -> _SageObject: ...
