from sage.graphs.generic_graph import GenericGraph
from sage.combinat.sf.sfa import SymmetricFunctionAlgebra_generic_Element
from sage.combinat.ncsf_qsym.qsym import QuasiSymmetricFunctions
from sage.graphs.convexity_properties import ConvexityProperties
from sage.graphs.digraph import DiGraph
from sage.combinat.designs.twographs import TwoGraph
from sage.graphs.bipartite_graph import BipartiteGraph
from sage.matrix.matrix import Matrix
from sage.topology.simplicial_complex import SimplicialComplex
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.combinat.rooted_tree import LabelledRootedTree
from sage.rings.fraction_field_element import FractionFieldElement as RationalFunction
from sage.structure.element import Element

class Graph(GenericGraph):
    def __init__(self, data: object = ..., pos: object = ..., loops: object = ..., format: object = ..., weighted: object = ..., data_structure: object = ..., vertex_labels: object = ..., name: object = ..., multiedges: object = ..., convert_empty_dict_labels_to_None: object = ..., sparse: object = ..., immutable: object = ..., hash_labels: object = ...) -> None: ...
    def graph6_string(self) -> str: ...
    def sparse6_string(self) -> str: ...
    def is_directed(self) -> bool: ...
    def is_tree(self, certificate: bool = ..., output: str = ...) -> bool | tuple[bool, object]: ...
    def is_forest(self, certificate: bool = ..., output: str = ...) -> bool | tuple[bool, object]: ...
    def is_cactus(self) -> bool: ...
    def is_block_graph(self) -> bool: ...
    def is_cograph(self) -> bool: ...
    def is_apex(self) -> bool: ...
    def apex_vertices(self, k: int | None = ...) -> list[object]: ...
    def is_overfull(self) -> bool: ...
    def is_even_hole_free(self, certificate: bool = ...) -> bool | tuple[bool, object]: ...
    def is_odd_hole_free(self, certificate: bool = ...) -> bool | tuple[bool, object]: ...
    def is_triangle_free(self, algorithm: str = ..., certificate: bool = ...) -> bool | tuple[bool, object]: ...
    def is_split(self) -> bool: ...
    def is_perfect(self, certificate: bool = ...) -> bool | tuple[bool, object]: ...
    def is_edge_transitive(self) -> bool: ...
    def is_arc_transitive(self) -> bool: ...
    def is_half_transitive(self) -> bool: ...
    def is_semi_symmetric(self) -> bool: ...
    def is_path(self) -> bool: ...
    def is_chordal_bipartite(self, certificate: bool = ...) -> bool | tuple[bool, object]: ...
    def degree_constrained_subgraph(self, bounds: object, solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> Graph: ...
    def bipartite_color(self) -> dict[object, int]: ...
    def bipartite_sets(self) -> tuple[set[object], set[object]]: ...
    def chromatic_index(self, solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> int: ...
    def chromatic_number(self, algorithm: str = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> int: ...
    def coloring(self, algorithm: str = ..., hex_colors: bool = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> list[list[object]] | dict[object, str]: ...
    def chromatic_symmetric_function(self, R: object = ..., weights: object = ...) -> SymmetricFunctionAlgebra_generic_Element: ...
    def chromatic_quasisymmetric_function(self, t: object = ..., R: object = ...) -> QuasiSymmetricFunctions.Monomial.Element: ...
    def tutte_symmetric_function(self, R: object = ..., t: object = ...) -> SymmetricFunctionAlgebra_generic_Element: ...
    def fractional_clique_number(self, solver: object = ..., verbose: int = ..., check_components: bool = ..., check_bipartite: bool = ...) -> float: ...
    def maximum_average_degree(self, value_only: bool = ..., solver: object = ..., verbose: int = ...) -> float | list[object]: ...
    def independent_set_of_representatives(self, family: list[list[object]], solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> list[object]: ...
    def minor(self, H: object, solver: object = ..., verbose: int = ..., induced: bool = ..., integrality_tolerance: float = ...) -> dict[object, list[object]] | bool: ...
    def convexity_properties(self) -> ConvexityProperties: ...
    def centrality_degree(self, v: object = ...) -> float | dict[object, float]: ...
    def eccentricity(self, v: object = ..., by_weight: bool = ..., algorithm: str = ..., weight_function: object = ..., check_weight: bool = ..., dist_dict: object = ..., with_labels: bool = ...) -> float | dict[object, float]: ...
    def radius(self, by_weight: bool = ..., algorithm: str = ..., weight_function: object = ..., check_weight: bool = ...) -> float: ...
    def diameter(self, by_weight: bool = ..., algorithm: str = ..., weight_function: object = ..., check_weight: bool = ...) -> float: ...
    def center(self, by_weight: bool = ..., algorithm: str = ..., weight_function: object = ..., check_weight: bool = ...) -> list[object]: ...
    def periphery(self, by_weight: bool = ..., algorithm: str = ..., weight_function: object = ..., check_weight: bool = ...) -> list[object]: ...
    def distance_graph(self, dist: int | list[int]) -> Graph: ...
    def to_directed(self, data_structure: str | None = ..., sparse: bool | None = ...) -> DiGraph: ...
    def to_undirected(self) -> Graph: ...
    def join(self, other: Graph, labels: str = ..., immutable: bool | None = ...) -> Graph: ...
    def seidel_adjacency_matrix(self, vertices: list[object] = ..., base_ring: object = ..., **kwds: object) -> Matrix: ...
    def seidel_switching(self, s: list[object], inplace: bool = ...) -> Graph: ...
    def twograph(self) -> TwoGraph: ...
    def write_to_eps(self, filename: str, **options: object) -> None: ...
    def topological_minor(self, H: object, vertices: list[object] = ..., paths: bool = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> dict[object, list[object]] | bool: ...
    def cliques_maximal(self, algorithm: str = ...) -> list[list[object]]: ...
    def clique_maximum(self, algorithm: str = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> list[object]: ...
    def clique_number(self, algorithm: str = ..., cliques: list[list[object]] = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> int: ...
    def cliques_number_of(self, vertices: list[object] = ..., cliques: list[list[object]] = ...) -> int | dict[object, int]: ...
    def cliques_get_max_clique_graph(self) -> Graph: ...
    def cliques_get_clique_bipartite(self, **kwds: object) -> BipartiteGraph: ...
    def independent_set(self, algorithm: str = ..., value_only: bool = ..., reduction_rules: bool = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> list[object] | int: ...
    def vertex_cover(self, algorithm: str = ..., value_only: bool = ..., reduction_rules: bool = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> list[object] | int: ...
    def ear_decomposition(self) -> list[list[object]]: ...
    def cliques_vertex_clique_number(self, algorithm: str = ..., vertices: list[object] = ..., cliques: list[list[object]] = ...) -> int | dict[object, int]: ...
    def cliques_containing_vertex(self, vertices: list[object] = ..., cliques: list[list[object]] = ...) -> list[list[object]] | dict[object, list[list[object]]]: ...
    def clique_complex(self) -> SimplicialComplex: ...
    def clique_polynomial(self, t: object = ...) -> Polynomial: ...
    def cores(self, k: int | None = ..., with_labels: bool = ...) -> int | dict[object, int] | dict[int, list[object]]: ...
    def is_module(self, vertices: list[object]) -> bool: ...
    def modular_decomposition(self, algorithm: str = ..., style: str = ...) -> tuple[object, ...] | LabelledRootedTree: ...
    def is_polyhedral(self) -> bool: ...
    def is_circumscribable(self, solver: object = ..., verbose: int = ...) -> bool: ...
    def is_inscribable(self, solver: object = ..., verbose: int = ...) -> bool: ...
    def is_prime(self, algorithm: str = ...) -> bool: ...
    def gomory_hu_tree(self, algorithm: str = ..., solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> Graph: ...
    def two_factor_petersen(self, solver: object = ..., verbose: int = ..., integrality_tolerance: float = ...) -> Graph: ...
    def kirchhoff_symanzik_polynomial(self, name: str = ...) -> Polynomial: ...
    def magnitude_function(self) -> RationalFunction: ...
    def ihara_zeta_function_inverse(self) -> Polynomial: ...
    def effective_resistance(self, i: object, j: object, base_ring: object = ...) -> Element: ...
    def effective_resistance_matrix(self, vertices: list[object] = ..., nonedgesonly: bool = ..., base_ring: object = ..., **kwds: object) -> Matrix: ...
    def least_effective_resistance(self, nonedgesonly: bool = ...) -> tuple[object, object]: ...
    def common_neighbors_matrix(self, vertices: list[object] = ..., nonedgesonly: bool = ..., base_ring: object = ..., **kwds: object) -> Matrix: ...
    def most_common_neighbors(self, nonedgesonly: bool = ...) -> tuple[object, object]: ...
    def arboricity(self, certificate: bool = ...) -> int | tuple[int, object]: ...
    def is_antipodal(self) -> bool: ...
    def folded_graph(self, check: bool = ..., immutable: bool = ...) -> Graph: ...
    def antipodal_graph(self) -> Graph: ...
    def bipartite_double(self, extended: bool = ...) -> Graph: ...
    def is_projective_planar(self, return_map: bool = ...) -> bool | tuple[bool, object]: ...
