# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def from_graph6(G: builtins.object, g6_string: builtins.object) -> _SageObject: ...

def from_sparse6(G: builtins.object, g6_string: builtins.object) -> _SageObject: ...

def from_dig6(G: builtins.object, dig6_string: builtins.object) -> _SageObject: ...

def from_seidel_adjacency_matrix(G: builtins.object, M: builtins.int) -> _SageObject: ...

def from_adjacency_matrix(G: builtins.object, M: builtins.int, loops: builtins.bool = ..., multiedges: builtins.bool = ..., weighted: builtins.bool = ...) -> _SageObject: ...

def from_incidence_matrix(G: builtins.object, M: builtins.int, loops: builtins.bool = ..., multiedges: builtins.bool = ..., weighted: builtins.bool = ...) -> _SageObject: ...

def from_oriented_incidence_matrix(G: builtins.object, M: builtins.int, loops: builtins.bool = ..., multiedges: builtins.bool = ..., weighted: builtins.bool = ...) -> _SageObject: ...

def from_dict_of_dicts(G: builtins.object, M: builtins.int, loops: builtins.bool = ..., multiedges: builtins.bool = ..., weighted: builtins.bool = ..., convert_empty_dict_labels_to_None: builtins.bool = ...) -> _SageObject: ...

def from_dict_of_lists(G: builtins.object, D: builtins.object, loops: builtins.bool = ..., multiedges: builtins.bool = ..., weighted: builtins.bool = ...) -> _SageObject: ...

def from_networkx_graph(G: builtins.object, gnx: builtins.object, weighted: builtins.object = ..., loops: builtins.object = ..., multiedges: builtins.object = ..., convert_empty_dict_labels_to_None: builtins.object = ...) -> _SageObject: ...
