from sage.structure.element import Element

def canaug_traverse_vert(g: Element, aut_gens: Element | int | str | bool | None, max_verts: Element | int | str | bool | None, property: Element | int | str | bool | None, dig: Element | int | str | bool | None, loops: Element | int | str | bool | None, sparse: Element | int | str | bool | None) -> Element: ...
def check_aut(aut_gens: Element | int | str | bool | None, cut_vert: Element | int | str | bool | None, n: int) -> Element: ...
def canaug_traverse_edge(g: Element, aut_gens: Element | int | str | bool | None, property: Element | int | str | bool | None, dig: Element | int | str | bool | None, loops: Element | int | str | bool | None, sparse: Element | int | str | bool | None) -> Element: ...
def check_aut_edge(aut_gens: Element | int | str | bool | None, cut_edge: Element | int | str | bool | None, i: int, j: int, n: int, dig: Element | int | str | bool | None) -> Element: ...

class GraphGenerators:
    def nauty_geng(self, options: Element | int | str | bool | None, debug: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def nauty_genbg(self, options: Element | int | str | bool | None, debug: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def nauty_genktreeg(self, options: Element | int | str | bool | None, debug: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def cospectral_graphs(self, vertices: Element | int | str | bool | None, matrix_function: Element | int | str | bool | None, graphs: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def _read_planar_code(self, code_input: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def fullerenes(self, order: Element | int | str | bool | None, ipr: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def fusenes(self, hexagon_count: Element | int | str | bool | None, benzenoids: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def plantri_gen(self, options: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def planar_graphs(self, order: Element | int | str | bool | None, minimum_degree: Element | int | str | bool | None, minimum_connectivity: Element | int | str | bool | None, exact_connectivity: Element | int | str | bool | None, minimum_edges: Element | int | str | bool | None, maximum_edges: Element | int | str | bool | None, maximum_face_size: Element | int | str | bool | None, only_bipartite: Element | int | str | bool | None, dual: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def triangulations(self, order: Element | int | str | bool | None, minimum_degree: Element | int | str | bool | None, minimum_connectivity: Element | int | str | bool | None, exact_connectivity: Element | int | str | bool | None, only_eulerian: Element | int | str | bool | None, dual: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
    def quadrangulations(self, order: Element | int | str | bool | None, minimum_degree: Element | int | str | bool | None, minimum_connectivity: Element | int | str | bool | None, no_nonfacial_quadrangles: Element | int | str | bool | None, dual: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
