import builtins

class _SageObject: ...

def check_tkz_graph(self) -> _SageObject: ...
def have_tkz_graph(self) -> bool: ...
def setup_latex_preamble(self) -> _SageObject: ...

class GraphLatex:
    def __init__(self, graph: builtins.object, **options: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def set_option(
        self, option_name: builtins.str, option_value: builtins.object = ...
    ) -> _SageObject: ...
    def set_options(self, **kwds: builtins.object) -> _SageObject: ...
    def get_option(self, option_name: builtins.str) -> _SageObject: ...
    def latex(self) -> _SageObject: ...
    def dot2tex_picture(self) -> _SageObject: ...
    def tkz_picture(self) -> _SageObject: ...
