# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class HypergraphGenerators:
    def nauty(self, number_of_sets: builtins.object, number_of_vertices: builtins.object, multiple_sets: builtins.bool = ..., vertex_min_degree: builtins.object = ..., vertex_max_degree: builtins.object = ..., set_max_size: builtins.object = ..., set_min_size: builtins.object = ..., regular: builtins.bool = ..., uniform: builtins.bool = ..., max_intersection: builtins.object = ..., connected: builtins.bool = ..., debug: builtins.bool = ..., options: builtins.str = ...) -> _SageObject: ...
    def CompleteUniform(self, n: builtins.int, k: builtins.int) -> _SageObject: ...
    def UniformRandomUniform(self, n: builtins.int, k: builtins.int, m: builtins.int) -> _SageObject: ...
    def BinomialRandomUniform(self, n: builtins.int, k: builtins.int, p: builtins.int) -> _SageObject: ...

hypergraphs: _SageObject
