import builtins

class _SageObject: ...

class GraphClass:
    def __init__(
        self,
        name: builtins.str,
        gc_id: builtins.object,
        recognition_function: builtins.object = ...,
    ) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def forbidden_subgraphs(self) -> _SageObject: ...
    def __contains__(self, g: object) -> bool: ...
    def description(self) -> _SageObject: ...

class GraphClasses:
    def get_class(self, id: builtins.object) -> _SageObject: ...
    def classes(self) -> _SageObject: ...
    def inclusions(self) -> _SageObject: ...
    def smallgraphs(self) -> _SageObject: ...
    def inclusion_digraph(self) -> _SageObject: ...
    def update_db(self) -> _SageObject: ...
    def show_all(self) -> _SageObject: ...

graph_classes: _SageObject
