from sage.structure.element import Element

def is_line_graph(g: Element, certificate: Element | int | str | bool | None) -> bool: ...
def get_certificate(gg: Element | int | str | bool | None) -> Element: ...
def line_graph(g: Element, labels: Element | int | str | bool | None, return_labels: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def root_graph(g: Element, verbose: bool, immutable: Element | int | str | bool | None) -> Element: ...
