# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MatchingCoveredGraph:
    def __init__(self, data: builtins.object = ..., matching: builtins.object = ..., algorithm: builtins.str = ..., solver: builtins.object = ..., verbose: builtins.int = ..., integrality_tolerance: builtins.float = ..., *args: builtins.object, **kwds: builtins.object) -> None: ...
    def add_edge(self, u: builtins.object, v: builtins.object = ..., label: builtins.str = ...) -> _SageObject: ...
    def add_edges(self, edges: builtins.object, loops: builtins.bool = ...) -> _SageObject: ...
    def add_vertex(self, name: builtins.str = ...) -> _SageObject: ...
    def add_vertices(self, vertices: builtins.object) -> _SageObject: ...
    def allow_loops(self, new: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
    def allows_loops(self) -> _SageObject: ...
    def canonical_partition(self) -> _SageObject: ...
    def delete_vertex(self, vertex: builtins.object, in_order: builtins.bool = ...) -> _SageObject: ...
    def delete_vertices(self, vertices: builtins.object) -> _SageObject: ...
    def get_matching(self) -> _SageObject: ...
    def maximal_barrier(self, vertex: builtins.object) -> _SageObject: ...
    def has_loops(self) -> builtins.bool: ...
    def has_perfect_matching(G: builtins.object, algorithm: builtins.str = ..., solver: builtins.object = ..., verbose: builtins.int = ..., *, integrality_tolerance: builtins.float = ...) -> builtins.bool: ...
    def is_biconnected(self) -> builtins.bool: ...
    def is_brace(self, coNP_certificate: builtins.bool = ...) -> builtins.bool: ...
    def is_brick(self, coNP_certificate: builtins.bool = ...) -> builtins.bool: ...
    def loop_edges(self, labels: builtins.bool = ...) -> _SageObject: ...
    def loop_vertices(self) -> _SageObject: ...
    loops: _SageObject
    def number_of_loops(self) -> _SageObject: ...
    def remove_loops(self, vertices: builtins.object = ...) -> _SageObject: ...
    def subdivide_edge(self, *args: builtins.object) -> _SageObject: ...
    def subdivide_edges(self, edges: builtins.object, k: builtins.int) -> _SageObject: ...
    def update_matching(self, matching: builtins.object) -> _SageObject: ...
