# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def has_perfect_matching(G: builtins.object, algorithm: builtins.str = ..., solver: builtins.object = ..., verbose: builtins.int = ..., *, integrality_tolerance: builtins.float = ...) -> builtins.bool: ...

def is_bicritical(G: builtins.object, matching: builtins.object = ..., algorithm: builtins.str = ..., coNP_certificate: builtins.bool = ..., solver: builtins.object = ..., verbose: builtins.int = ..., *, integrality_tolerance: builtins.float = ...) -> builtins.bool: ...

def is_factor_critical(G: builtins.object, matching: builtins.object = ..., algorithm: builtins.str = ..., solver: builtins.object = ..., verbose: builtins.int = ..., *, integrality_tolerance: builtins.float = ...) -> builtins.bool: ...

def is_matching_covered(G: builtins.object, matching: builtins.object = ..., algorithm: builtins.str = ..., coNP_certificate: builtins.bool = ..., solver: builtins.object = ..., verbose: builtins.int = ..., *, integrality_tolerance: builtins.float = ...) -> builtins.bool: ...

def matching(G: builtins.object, value_only: builtins.bool = ..., algorithm: builtins.str = ..., use_edge_labels: builtins.bool = ..., solver: builtins.object = ..., verbose: builtins.int = ..., *, integrality_tolerance: builtins.float = ...) -> _SageObject: ...

def perfect_matchings(G: builtins.object, labels: builtins.bool = ...) -> _SageObject: ...

def M_alternating_even_mark(G: builtins.object, vertex: builtins.object, matching: builtins.object) -> _SageObject: ...
