from sage.structure.element import Element

def reduced_homeomorphic_graph(G: Element | int | str | bool | None, allow_multiple_edges: Element | int | str | bool | None, allow_loops: Element | int | str | bool | None, return_steps: Element | int | str | bool | None, immutable: Element | int | str | bool | None) -> Element: ...
def is_homeomorphic(G: Element | int | str | bool | None, H: Element | int | str | bool | None) -> bool: ...
def has_homomorphism_to(G: Element | int | str | bool | None, H: Element | int | str | bool | None, core: Element | int | str | bool | None, solver: Element | int | str | bool | None, verbose: bool) -> bool: ...
