import builtins

class _SageObject: ...

def breadth_first_level_search(self, start: builtins.int) -> _SageObject: ...
def depth_first_traversal(self, start: builtins.int) -> _SageObject: ...
def is_partial_cube(self, certificate: builtins.bool = ...) -> builtins.bool: ...
