# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def breadth_first_level_search(G: builtins.object, start: builtins.int) -> _SageObject: ...

def depth_first_traversal(G: builtins.object, start: builtins.int) -> _SageObject: ...

def is_partial_cube(G: builtins.object, certificate: builtins.bool = ...) -> builtins.bool: ...
