# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

FULL: _SageObject
PARTIAL: _SageObject
EMPTY: _SageObject
ALIGNED: _SageObject
UNALIGNED: _SageObject
impossible_msg: _SageObject
def reorder_sets(sets: builtins.object) -> _SageObject: ...

class PQ:
    def __init__(self, seq: builtins.object) -> None: ...
    def reverse(self) -> _SageObject: ...
    def __contains__(self, v: builtins.object) -> builtins.bool: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def number_of_children(self) -> _SageObject: ...
    def ordering(self) -> builtins.list[_SageObject]: ...
    def simplify(self, v: builtins.object, left: builtins.bool = ..., right: builtins.bool = ...) -> _SageObject: ...
    def flatten(self) -> _SageObject: ...

class P:
    def set_contiguous(self, v: builtins.object) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def orderings(self) -> _SageObject: ...

class Q:
    def set_contiguous(self, v: builtins.object) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def orderings(self) -> _SageObject: ...
