import builtins

class _SageObject: ...

def print_header_ps(self) -> _SageObject: ...
def print_header_eps(
    self,
    xmin: builtins.object,
    ymin: builtins.object,
    xmax: builtins.object,
    ymax: builtins.object,
) -> _SageObject: ...
def print_functions(self) -> _SageObject: ...
def print_graph_ps(
    self, edge_iter: builtins.object, pos_dict: builtins.object
) -> _SageObject: ...
def print_graph_eps(
    self, edge_iter: builtins.object, pos_dict: builtins.object
) -> _SageObject: ...
