# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

orthogonal_array: _SageObject
balanced_incomplete_block_design: _SageObject
GF: _SageObject
Matrix: _SageObject
LinearCode: _SageObject
def is_paley(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_mathon_PC_srg(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_muzychuk_S6(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_orthogonal_array_block_graph(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_johnson(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_steiner(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_affine_polar(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_orthogonal_polar(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_goethals_seidel(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_NOodd(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_NOperp_F5(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_NO_F2(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_NO_F3(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_NU(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_haemers(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_cossidente_penttila(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_complete_multipartite(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_polhill(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_RSHCD(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def SRG_from_RSHCD(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object, existence: builtins.object = ..., check: builtins.object = ...) -> _SageObject: ...

def is_unitary_polar(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_unitary_dual_polar(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_GQqmqp(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_twograph_descendant_of_srg(v: builtins.object, k0: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_taylor_twograph_srg(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_switch_skewhad(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_switch_OA_srg(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def is_nowhere0_twoweight(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> builtins.bool: ...

def eigenvalues(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> _SageObject: ...

def eigenmatrix(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> _SageObject: ...

def latin_squares_graph_parameters(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> _SageObject: ...

def SRG_100_44_18_20() -> _SageObject: ...

def SRG_100_45_20_20() -> _SageObject: ...

def SRG_105_32_4_12() -> _SageObject: ...

def SRG_120_77_52_44() -> _SageObject: ...

def SRG_144_39_6_12() -> _SageObject: ...

def SRG_176_49_12_14() -> _SageObject: ...

def SRG_176_105_68_54() -> _SageObject: ...

def SRG_210_99_48_45() -> _SageObject: ...

def SRG_243_110_37_60() -> _SageObject: ...

def SRG_253_140_87_65() -> _SageObject: ...

def SRG_196_91_42_42() -> _SageObject: ...

def SRG_220_84_38_28() -> _SageObject: ...

def SRG_276_140_58_84() -> _SageObject: ...

def SRG_280_135_70_60() -> _SageObject: ...

def SRG_280_117_44_52() -> _SageObject: ...

def strongly_regular_from_two_weight_code(L: builtins.object) -> _SageObject: ...

def SRG_416_100_36_20() -> _SageObject: ...

def SRG_560_208_72_80() -> _SageObject: ...

def strongly_regular_from_two_intersection_set(M: builtins.object) -> _SageObject: ...

def SRG_120_63_30_36() -> _SageObject: ...

def SRG_126_25_8_4() -> _SageObject: ...

def SRG_175_72_20_36() -> _SageObject: ...

def SRG_176_90_38_54() -> _SageObject: ...

def SRG_630_85_20_10() -> _SageObject: ...

def SRG_126_50_13_24() -> _SageObject: ...

def SRG_1288_792_476_504() -> _SageObject: ...

def seems_feasible(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object) -> _SageObject: ...

def strongly_regular_graph(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object = ..., existence: builtins.object = ..., check: builtins.object = ...) -> _SageObject: ...

def strongly_regular_graph_lazy(v: builtins.object, k: builtins.object, l: builtins.object, mu: builtins.object = ..., existence: builtins.object = ...) -> _SageObject: ...

def apparently_feasible_parameters(n: builtins.object) -> _SageObject: ...

def load_brouwer_database() -> _SageObject: ...
