from sage.rings.ring import Ring
from sage.structure.element import Element

def lex_BFS(G: Element | int | str | bool | None, reverse: Element | int | str | bool | None, tree: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None, algorithm: str) -> Element: ...
def lex_UP(G: Element | int | str | bool | None, reverse: Element | int | str | bool | None, tree: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...
def lex_DFS(G: Element | int | str | bool | None, reverse: Element | int | str | bool | None, tree: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...
def lex_DOWN(G: Element | int | str | bool | None, reverse: Element | int | str | bool | None, tree: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...
def lex_M(triangulation: Element | int | str | bool | None, labels: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None, algorithm: str) -> Element: ...
def lex_M_slow(G: Element | int | str | bool | None, triangulation: Element | int | str | bool | None, labels: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...
def lex_M_fast(G: Element | int | str | bool | None, triangulation: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...
def is_valid_lex_M_order(G: Element | int | str | bool | None, alpha: Element | int | str | bool | None, F: Ring) -> bool: ...
def maximum_cardinality_search(G: Element | int | str | bool | None, reverse: Element | int | str | bool | None, tree: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...
def maximum_cardinality_search_M(G: Element | int | str | bool | None, initial_vertex: Element | int | str | bool | None) -> Element: ...
