# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def removed_multiedge(G: builtins.object, unlabeled_edge: builtins.object) -> _SageObject: ...

def removed_edge(G: builtins.object, edge: builtins.object) -> _SageObject: ...

def contracted_edge(G: builtins.object, unlabeled_edge: builtins.object) -> _SageObject: ...

def removed_loops(G: builtins.object) -> _SageObject: ...

def underlying_graph(G: builtins.object) -> _SageObject: ...

def edge_multiplicities(G: builtins.object) -> _SageObject: ...

class Ear:
    def __init__(self, graph: builtins.object, end_points: builtins.object, interior: builtins.object, is_cycle: builtins.object) -> None: ...
    @property
    def s(self) -> _SageObject: ...
    @property
    def vertices(self) -> _SageObject: ...
    def unlabeled_edges(self) -> _SageObject: ...
    @staticmethod
    def find_ear(g: builtins.object) -> _SageObject: ...
    def removed_from(self, G: builtins.object) -> _SageObject: ...

class EdgeSelection:
    ...

class VertexOrder:
    def __init__(self, order: builtins.object) -> None: ...
    def __call__(self, graph: builtins.object) -> _SageObject: ...

class MinimizeSingleDegree:
    def __call__(self, graph: builtins.object) -> _SageObject: ...

class MinimizeDegree:
    def __call__(self, graph: builtins.object) -> _SageObject: ...

class MaximizeDegree:
    def __call__(self, graph: builtins.object) -> _SageObject: ...

def tutte_polynomial(G: builtins.object, edge_selector: builtins.object = ..., cache: builtins.object = ...) -> _SageObject: ...
