# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class EdgesView:
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __bool__(self) -> builtins.bool: ...
    def __eq__(self, right: builtins.object) -> builtins.bool: ...
    def __contains__(self, e: builtins.object) -> builtins.bool: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def __add__(left: builtins.object, right: builtins.object) -> Self: ...
    def __mul__(left: builtins.object, right: builtins.object) -> Self: ...
