from sage.structure.element import Element

def is_long_hole_free(g: Element, certificate: Element | int | str | bool | None) -> bool: ...
def is_long_antihole_free(g: Element, certificate: Element | int | str | bool | None) -> bool: ...
def is_weakly_chordal(g: Element, certificate: Element | int | str | bool | None) -> bool: ...
