# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ArikiKoikeAlgebra:
    @staticmethod
    def __classcall_private__(cls: builtins.object, r: builtins.int, n: builtins.int, q: builtins.int = ..., u: builtins.object = ..., R: builtins.int = ..., use_fraction_field: builtins.bool = ...) -> _SageObject: ...
    def __init__(self, r: builtins.int, n: builtins.int, q: builtins.int, u: builtins.object, R: builtins.int) -> None: ...
    def hecke_parameter(self) -> _SageObject: ...
    q: _SageObject
    def cyclotomic_parameters(self) -> _SageObject: ...
    u: _SageObject
    def a_realization(self) -> _SageObject: ...
    def specht_module(self, la: builtins.object) -> _SageObject: ...
    class LT:
        def __init__(self, algebra: builtins.object) -> None: ...
        def algebra_generators(self) -> _SageObject: ...
        def T(self, i: builtins.int = ...) -> _SageObject: ...
        def L(self, i: builtins.int = ...) -> _SageObject: ...
        def product_on_basis(self, m1: builtins.object, m2: builtins.object) -> _SageObject: ...
        def inverse_T(self, i: builtins.int) -> _SageObject: ...
        class Element:
            def __invert__(self) -> Self: ...
    class T:
        def __init__(self, algebra: builtins.object) -> None: ...
        def algebra_generators(self) -> _SageObject: ...
        def T(self, i: builtins.int = ...) -> _SageObject: ...
        def L(self, i: builtins.int = ...) -> _SageObject: ...
        def product_on_basis(self, m1: builtins.object, m2: builtins.object) -> _SageObject: ...
