from sage.structure.element import Element
from sage.structure.parent import Parent

class _Basis(CombinatorialFreeModule, BindableClass):
    def one_basis(self) -> Element: ...

class ArikiKoikeAlgebra(Parent, UniqueRepresentation):
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def hecke_parameter(self) -> Element: ...
    def cyclotomic_parameters(self) -> Element: ...
    def a_realization(self) -> Element: ...
    def specht_module(self, la: Element | int | str | bool | None) -> Element: ...

class BindableClass: ...

class CombinatorialFreeModule: ...

class UniqueRepresentation: ...
