import builtins

class _SageObject: ...

TEST_CODE: _SageObject

class BlissLibrary:
    def __init__(self) -> None: ...

class Bliss:
    def __init__(self) -> None: ...
    def is_present_at_runtime(self) -> builtins.bool: ...

def all_features(self) -> _SageObject: ...
