# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class DatabaseCremona:
    def __init__(self, name: builtins.str = ..., spkg: builtins.str = ..., type: builtins.str = ...) -> None: ...

class DatabaseEllcurves:
    def __init__(self) -> None: ...

class DatabaseGraphs:
    def __init__(self) -> None: ...

class DatabaseJones:
    def __init__(self) -> None: ...

class DatabaseKnotInfo:
    def __init__(self) -> None: ...

class DatabaseMatroids:
    def __init__(self) -> None: ...

class DatabaseCubicHecke:
    def __init__(self) -> None: ...

class DatabaseReflexivePolytopes:
    def __init__(self, name: builtins.str = ...) -> None: ...

def all_features() -> _SageObject: ...
