import builtins

class _SageObject: ...

class FriCAS:
    MINIMUM_VERSION: _SageObject

    def __init__(self) -> None: ...
    def get_version(self) -> _SageObject: ...
    def is_functional(self) -> builtins.bool: ...

def all_features(self) -> _SageObject: ...
