
class _SageObject: ...

class dot:
    def __init__(self) -> None: ...

class neato:
    def __init__(self) -> None: ...

class twopi:
    def __init__(self) -> None: ...

class Graphviz:
    def __init__(self) -> None: ...

def all_features(self) -> _SageObject: ...
