import builtins

class _SageObject: ...

class Magick:
    def __init__(self) -> None: ...
    def is_functional(self) -> builtins.bool: ...

class ImageMagick:
    def __init__(self) -> None: ...

def all_features(self) -> _SageObject: ...
