# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class JoinFeature:
    def __init__(self, name: builtins.str, features: builtins.object, spkg: builtins.object = ..., url: builtins.object = ..., description: builtins.object = ..., type: builtins.object = ..., **kwds: builtins.object) -> None: ...
    def hide(self) -> _SageObject: ...
    def unhide(self) -> _SageObject: ...
