
class _SageObject: ...

class cu2:
    def __init__(self) -> None: ...

class size222:
    def __init__(self) -> None: ...

class optimal:
    def __init__(self) -> None: ...

class mcube:
    def __init__(self) -> None: ...

class dikcube:
    def __init__(self) -> None: ...

class cubex:
    def __init__(self) -> None: ...

class Rubiks:
    def __init__(self) -> None: ...

def all_features(self) -> _SageObject: ...
