# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class sagemath_doc_html:
    def __init__(self) -> None: ...

class sage__combinat:
    def __init__(self) -> None: ...

class sage__geometry__polyhedron:
    def __init__(self) -> None: ...

class sage__graphs:
    def __init__(self) -> None: ...

class sage__groups:
    def __init__(self) -> None: ...

class sage__libs__braiding:
    def __init__(self) -> None: ...

class sage__libs__ecl:
    def __init__(self) -> None: ...

class sage__libs__flint:
    def __init__(self) -> None: ...

class sage__libs__gap:
    def __init__(self) -> None: ...

class sage__libs__linbox:
    def __init__(self) -> None: ...

class sage__libs__m4ri:
    def __init__(self) -> None: ...

class sage__libs__ntl:
    def __init__(self) -> None: ...

class sage__libs__giac:
    def __init__(self) -> None: ...

class sage__libs__pari:
    def __init__(self) -> None: ...

class sage__libs__singular:
    def __init__(self) -> None: ...

class sage__modular:
    def __init__(self) -> None: ...

class sage__modules:
    def __init__(self) -> None: ...

class sage__numerical__mip:
    def __init__(self) -> None: ...

class sage__plot:
    def __init__(self) -> None: ...

class sage__rings__complex_double:
    def __init__(self) -> None: ...

class sage__rings__finite_rings:
    def __init__(self) -> None: ...

class sage__rings__function_field:
    def __init__(self) -> None: ...

class sage__rings__number_field:
    def __init__(self) -> None: ...

class sage__rings__padics:
    def __init__(self) -> None: ...

class sage__rings__real_double:
    def __init__(self) -> None: ...

class sage__rings__real_mpfr:
    def __init__(self) -> None: ...

class sage__sat:
    def __init__(self) -> None: ...

class sage__schemes:
    def __init__(self) -> None: ...

class sage__symbolic:
    def __init__(self) -> None: ...

def all_features() -> _SageObject: ...
