import builtins

class _SageObject: ...

class ElementaryCellularAutomata:
    def __init__(
        self,
        rule: builtins.object,
        width: builtins.object = ...,
        initial_state: builtins.object = ...,
        boundary: builtins.tuple[_SageObject, ...] = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def evolve(self, number: builtins.object = ...) -> _SageObject: ...
    def print_state(self, number: builtins.object = ...) -> _SageObject: ...
    def print_states(self, number: builtins.object = ...) -> _SageObject: ...
    def plot(self, number: builtins.object = ...) -> _SageObject: ...
