import builtins

class _SageObject: ...

class SolitonCellularAutomata:
    def __init__(
        self,
        initial_state: builtins.object,
        cartan_type: builtins.int = ...,
        vacuum: builtins.int = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def evolve(
        self,
        carrier_capacity: builtins.object = ...,
        carrier_index: builtins.object = ...,
        number: builtins.object = ...,
    ) -> _SageObject: ...
    def state_evolution(self, num: builtins.object) -> _SageObject: ...
    def reset(self) -> _SageObject: ...
    def print_state(
        self,
        num: builtins.object = ...,
        vacuum_letter: builtins.str = ...,
        remove_trailing_vacuums: builtins.bool = ...,
    ) -> _SageObject: ...
    def print_states(
        self, num: builtins.object = ..., vacuum_letter: builtins.str = ...
    ) -> _SageObject: ...
    def latex_states(
        self,
        num: builtins.object = ...,
        as_array: builtins.bool = ...,
        box_width: builtins.str = ...,
    ) -> _SageObject: ...
    def print_state_evolution(self, num: builtins.object) -> _SageObject: ...
    def latex_state_evolution(
        self, num: builtins.object, scale: builtins.int = ...
    ) -> _SageObject: ...

class PeriodicSolitonCellularAutomata:
    def evolve(
        self,
        carrier_capacity: builtins.object = ...,
        carrier_index: builtins.object = ...,
        number: builtins.object = ...,
    ) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
