# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CyclicCover_generic:
    def __init__(self, AA: builtins.object, r: builtins.int, f: builtins.object, names: builtins.object = ...) -> None: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    base_extend: _SageObject
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def order(self) -> _SageObject: ...
    def genus(self) -> _SageObject: ...
    def projective_closure(self, **kwds: builtins.object) -> _SageObject: ...
    def cover_polynomial(self, K: builtins.int = ..., var: builtins.str = ...) -> _SageObject: ...
    def is_singular(self) -> builtins.bool: ...
    def is_smooth(self) -> builtins.bool: ...
