import builtins

class _SageObject: ...

class CyclicCover_generic:
    def __init__(
        self,
        AA: builtins.object,
        r: builtins.int,
        f: builtins.object,
        names: builtins.object = ...,
    ) -> None: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...
    base_extend: _SageObject

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def order(self) -> _SageObject: ...
    def genus(self) -> _SageObject: ...
    def projective_closure(self, **kwds: builtins.object) -> _SageObject: ...
    def cover_polynomial(
        self, K: builtins.int = ..., var: builtins.str = ...
    ) -> _SageObject: ...
    def is_singular(self) -> bool: ...
    def is_smooth(self) -> bool: ...
