from sage.structure.element import Element

class FreelyGeneratedLieConformalAlgebra(LieConformalAlgebraWithBasis):
    def lie_conformal_algebra_generators(self) -> Element: ...
    def central_elements(self) -> Family: ...

class Family: ...

class LieConformalAlgebraWithBasis: ...
