from sage.structure.element import Element

def cyclotomic_coeffs(nn: int, sparse: object = None) -> list[int] | dict[int, int]: ...
def cyclotomic_value(n: int, x: object) -> Element: ...
def bateman_bound(nn: int) -> int: ...
