from typing import TYPE_CHECKING, Iterator
from sage.structure.sage_object import SageObject
from sage.rings.integer import Integer

if TYPE_CHECKING:
    from sage.rings.polynomial.multi_polynomial_ideal import MPolynomialIdeal
    from sage.rings.polynomial.multi_polynomial_sequence import PolynomialSequence
    from sage.geometry.fan import Fan
    from sage.modules.free_module_element import vector

class PolyhedralCone(SageObject):
    def __init__(self, gfan_polyhedral_cone, ring=...) -> None: ...
    def _repr_(self) -> str: ...
    def facets(self) -> list[list[int]]: ...
    def ambient_dim(self) -> int: ...
    def dim(self) -> int: ...
    def lineality_dim(self) -> int: ...
    def relative_interior_point(self) -> list[int]: ...

class PolyhedralFan(SageObject):
    def __init__(self, gfan_polyhedral_fan, parameter_indices: list[int] | None = None) -> None: ...
    def _repr_(self) -> str: ...
    def ambient_dim(self) -> int: ...
    def dim(self) -> int: ...
    def lineality_dim(self) -> int: ...
    def rays(self) -> list[list[int]]: ...
    def cones(self) -> dict[int, list[list[int]]]: ...
    def maximal_cones(self) -> dict[int, list[list[int]]]: ...
    def f_vector(self) -> list[Integer]: ...
    def is_simplicial(self) -> bool: ...
    def to_RationalPolyhedralFan(self) -> Fan: ...

class InitialForm(SageObject):
    def __init__(self, cone: list[int], rays: list[list[int]], initial_forms: list) -> None: ...
    def cone(self) -> list[int]: ...
    def rays(self) -> list[list[int]]: ...
    def internal_ray(self): ...
    def initial_forms(self) -> list: ...

class TropicalPrevariety(PolyhedralFan):
    def initial_form_systems(self) -> list[InitialForm]: ...

class GroebnerFan(SageObject):
    def __init__(
        self,
        I: MPolynomialIdeal,
        is_groebner_basis: bool = False,
        symmetry: str | None = None,
        verbose: bool = False
    ) -> None: ...
    def _repr_(self) -> str: ...
    def __eq__(self, right: object) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, i: int) -> ReducedGroebnerBasis: ...
    def ideal(self) -> MPolynomialIdeal: ...
    def ring(self): ...
    def reduced_groebner_bases(self) -> list[ReducedGroebnerBasis]: ...
    def weight_vectors(self) -> list[vector]: ...
    def characteristic(self) -> int: ...
    def polyhedralfan(self) -> PolyhedralFan: ...
    def buchberger(self) -> list: ...
    def homogeneity_space(self) -> str: ...
    def render(
        self,
        file: str | None = None,
        larger: bool = False,
        shift: int = 0,
        rgbcolor: tuple[int, int, int] = (0, 0, 0),
        polyfill: bool = True,
        scale_colors: bool = True
    ): ...
    def render3d(self, verbose: bool = False): ...
    def tropical_basis(self, check: bool = True, verbose: bool = False) -> list: ...
    def tropical_intersection(
        self, parameters: tuple | None = None, symmetry_generators: str | None = None, *args, **kwds
    ) -> TropicalPrevariety: ...
    def mixed_volume(self) -> Integer: ...
    def interactive(self, *args, **kwds) -> None: ...
    def dimension_of_homogeneity_space(self) -> int: ...
    def maximal_total_degree_of_a_groebner_basis(self) -> int: ...
    def minimal_total_degree_of_a_groebner_basis(self) -> int: ...
    def number_of_reduced_groebner_bases(self) -> int: ...
    def number_of_variables(self) -> int: ...
    def gfan(self, cmd: str = 'bases', I: str | None = None) -> str: ...

class ReducedGroebnerBasis(SageObject, list):
    def __init__(self, groebner_fan: GroebnerFan, gens: PolynomialSequence, gfan_gens: str) -> None: ...
    def _repr_(self) -> str: ...
    def _gfan_gens(self) -> str: ...
    def _gfan(self) -> GroebnerFan: ...
    def groebner_cone(self, restrict: bool = False) -> PolyhedralCone: ...
    def ideal(self) -> MPolynomialIdeal: ...
    def interactive(
        self, latex: bool = False, flippable: bool = False, wall: bool = False,
        inequalities: bool = False, weight: bool = False
    ) -> None: ...
