from sage.rings.ideal import Ideal_pid
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ring import Field, Ring

class Ideal_1poly_field(Ideal_pid):
    def residue_class_degree(self) -> int: ...
    def residue_field(self, names: object = None, check: bool = True) -> Field: ...
    def groebner_basis(self, algorithm: object = None) -> list[Polynomial]: ...
    def change_ring(self, R: Ring) -> Ideal_1poly_field: ...
