from collections.abc import Iterator

from sage.rings.polynomial.commutative_polynomial import CommutativePolynomial
from sage.rings.polynomial.infinite_polynomial_ring import InfinitePolynomialRing_dense, InfinitePolynomialRing_sparse
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.structure.element import Element
from sage.structure.factorization import Factorization
from sage.structure.parent import Parent

class InfinitePolynomial(CommutativePolynomial):
    @staticmethod
    def __classcall_private__(cls: type[InfinitePolynomial], A: object, p: object) -> InfinitePolynomial: ...
    def __init__(self, A: object, p: object) -> None: ...
    def _repr_(self) -> str: ...
    def __hash__(self) -> int: ...
    def polynomial(self) -> MPolynomial: ...
    def _latex_(self) -> str: ...
    def _symbolic_(self, R: object) -> Element: ...
    def subs(self, fixed: object = None, **kwargs: object) -> InfinitePolynomial: ...
    def ring(self) -> InfinitePolynomialRing_sparse | InfinitePolynomialRing_dense: ...
    def is_unit(self) -> bool: ...
    def is_nilpotent(self) -> bool: ...
    def is_constant(self) -> bool: ...
    def constant_coefficient(self) -> Element: ...
    def is_monomial(self) -> bool: ...
    def is_term(self) -> bool: ...
    def degree(self, x: object = None, std_grading: bool = False) -> int | tuple[int, ...]: ...
    def numerator(self) -> InfinitePolynomial: ...
    def denominator(self) -> Element: ...
    def variables(self) -> list[InfinitePolynomial]: ...
    def monomials(self) -> list[InfinitePolynomial]: ...
    def monomial_coefficients(self, copy: object = None) -> dict[object, Element]: ...
    def exponents(self) -> list[tuple[int, ...]]: ...
    def degrees(self) -> dict[object, int]: ...
    def max_index(self) -> int: ...
    def _rmul_(self, left: Element) -> InfinitePolynomial: ...
    def _lmul_(self, right: Element) -> InfinitePolynomial: ...
    def _div_(self, x: InfinitePolynomial) -> InfinitePolynomial: ...
    def factor(self, proof: object = None) -> Factorization: ...
    def lm(self) -> InfinitePolynomial: ...
    def lc(self) -> Element: ...
    def lt(self) -> InfinitePolynomial: ...
    def tail(self) -> InfinitePolynomial: ...
    def squeezed(self) -> InfinitePolynomial: ...
    def footprint(self) -> dict[InfinitePolynomial, object]: ...
    def symmetric_cancellation_order(self, other: InfinitePolynomial) -> bool: ...
    def reduce(self, I: object, tailreduce: bool = False, report: object = None) -> InfinitePolynomial: ...
    def stretch(self, k: int) -> InfinitePolynomial: ...
    def __iter__(self) -> Iterator[tuple[Element, InfinitePolynomial]]: ...

class InfinitePolynomial_sparse(InfinitePolynomial):
    def __call__(self, *args: object, **kwargs: object) -> Element: ...
    def _common_polynomial_ring(self, x: object) -> Parent: ...
    def _add_(self, x: InfinitePolynomial) -> InfinitePolynomial_sparse: ...
    def _mul_(self, x: InfinitePolynomial) -> InfinitePolynomial_sparse: ...
    def _sub_(self, x: InfinitePolynomial) -> InfinitePolynomial_sparse: ...
    def _floordiv_(self, x: InfinitePolynomial) -> InfinitePolynomial_sparse: ...
    def __pow__(self, n: int) -> InfinitePolynomial_sparse: ...
    def _richcmp_(self, x: object, op: int) -> bool: ...
    def gcd(self, x: InfinitePolynomial) -> InfinitePolynomial_sparse: ...
    def quo_rem(self, x: InfinitePolynomial) -> tuple[InfinitePolynomial_sparse, InfinitePolynomial_sparse]: ...
    def monomial_coefficient(self, mon: object) -> Element: ...
    def coefficient(self, x: object) -> Element: ...

class InfinitePolynomial_dense(InfinitePolynomial):
    def __call__(self, *args: object, **kwargs: object) -> Element: ...
    def _richcmp_(self, x: object, op: int) -> bool: ...
    def _add_(self, x: InfinitePolynomial) -> InfinitePolynomial_dense: ...
    def _mul_(self, x: InfinitePolynomial) -> InfinitePolynomial_dense: ...
    def _sub_(self, x: InfinitePolynomial) -> InfinitePolynomial_dense: ...
    def _floordiv_(self, x: InfinitePolynomial) -> InfinitePolynomial_dense: ...
    def __pow__(self, n: int) -> InfinitePolynomial_dense: ...
    def gcd(self, x: InfinitePolynomial) -> InfinitePolynomial_dense: ...
    def quo_rem(self, x: InfinitePolynomial) -> tuple[InfinitePolynomial_dense, InfinitePolynomial_dense]: ...
    def monomial_coefficient(self, mon: object) -> Element: ...
    def coefficient(self, monomial: object) -> Element: ...
