from sage.structure.element import Element
from sage.structure.sequence import Sequence_generic

def _run_msolve(ideal: object, options: object) -> str: ...
def groebner_basis_degrevlex(ideal: object, proof: bool = True) -> Sequence_generic: ...
def variety(ideal: object, ring: object, *, proof: bool = True) -> set[tuple[Element, ...]]: ...
