from sage.structure.sequence import Sequence_generic

class PolynomialSequence_generic(Sequence_generic): ...
class PolynomialSequence_gf2(PolynomialSequence_generic): ...
class PolynomialSequence_gf2e(PolynomialSequence_generic): ...
