from collections.abc import Iterator
from contextlib import AbstractContextManager

from sage.categories.morphism import Morphism
from sage.interfaces.expect import ExpectElement
from sage.rings.polynomial.multi_polynomial import MPolynomial, MPolynomial_libsingular as MPolynomial_libsingular_base
from sage.rings.polynomial.multi_polynomial_ideal import MPolynomialIdeal
from sage.rings.polynomial.multi_polynomial_ring_base import MPolynomialRing_base
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.integer import Integer
from sage.rings.real_mpfr import RealNumber
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.factorization import Factorization

def unpickle_MPolynomialRing_libsingular(base_ring: object, names: object, term_order: object) -> MPolynomialRing_libsingular: ...
def unpickle_MPolynomial_libsingular(R: MPolynomialRing_libsingular, d: object) -> MPolynomial_libsingular: ...

class MPolynomialRing_libsingular(MPolynomialRing_base):
    def __init__(self, base_ring: Ring, n: int, names: object, order: str = 'degrevlex') -> None: ...
    def __copy__(self) -> MPolynomialRing_libsingular: ...
    def __deepcopy__(self, memo: object) -> MPolynomialRing_libsingular: ...
    def _coerce_map_from_(self, other: object) -> Morphism | bool | None: ...
    def _element_constructor_(self, element: object, check: bool = True) -> MPolynomial_libsingular: ...
    def _repr_(self) -> str: ...
    def ngens(self) -> Integer: ...
    def gen(self, n: int = 0) -> MPolynomial_libsingular: ...
    def ideal(self, *gens: object, **kwds: object) -> MPolynomialIdeal: ...
    def _macaulay2_(self, macaulay2: object = None) -> ExpectElement: ...
    def _macaulay2_init_(self, macaulay2: object = None) -> str: ...
    def _singular_(self, singular: object = None) -> ExpectElement: ...
    def _singular_init_(self, singular: object = None) -> str: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, right: object, op: int) -> bool: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def _temporarily_change_names(self, names: object, latex_names: object) -> AbstractContextManager[None]: ...
    def monomial_quotient(self, f: MPolynomial_libsingular, g: MPolynomial_libsingular, coeff: bool = False) -> MPolynomial_libsingular: ...
    def monomial_divides(self, a: MPolynomial_libsingular, b: MPolynomial_libsingular) -> bool: ...
    def monomial_lcm(self, f: MPolynomial_libsingular, g: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def monomial_reduce(self, f: MPolynomial_libsingular, G: object) -> MPolynomial_libsingular: ...
    def monomial_pairwise_prime(self, g: MPolynomial_libsingular, h: MPolynomial_libsingular) -> bool: ...
    def monomial_all_divisors(self, t: MPolynomial_libsingular) -> list[MPolynomial_libsingular]: ...

class MPolynomial_libsingular(MPolynomial_libsingular_base):
    def __init__(self, parent: MPolynomialRing_libsingular) -> None: ...
    def __copy__(self) -> MPolynomial_libsingular: ...
    def __deepcopy__(self, memo: object = {}) -> MPolynomial_libsingular: ...
    def _new_constant_poly(self, x: Element, P: MPolynomialRing_libsingular) -> MPolynomial_libsingular: ...
    def __call__(self, *x: object, **kwds: object) -> Element: ...
    def __hash__(self) -> int: ...
    def _richcmp_(self, right: object, op: int) -> bool: ...
    def _add_(self, right: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def _sub_(self, right: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def _lmul_(self, left: Element) -> MPolynomial_libsingular: ...
    def _mul_(self, right: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def _div_(self, right_ringelement: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def __pow__(self, exp: int, mod: object = ...) -> MPolynomial_libsingular: ...
    def __neg__(self) -> MPolynomial_libsingular: ...
    def _repr_(self) -> str: ...
    def _repr_short_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _repr_with_changed_varnames(self, varnames: object) -> str: ...
    def degree(self, x: object = None, std_grading: bool = False) -> int | tuple[int, ...]: ...
    def total_degree(self, std_grading: bool = False) -> int: ...
    def degrees(self) -> tuple[int, ...]: ...
    def coefficient(self, degrees: object) -> Element: ...
    def monomial_coefficient(self, mon: MPolynomial_libsingular) -> Element: ...
    def monomial_coefficients(self, copy: object = None) -> dict[object, Element]: ...
    def iterator_exp_coeff(self, as_ETuples: bool = True) -> Iterator[tuple[tuple[int, ...], Element]]: ...
    def number_of_terms(self) -> int: ...
    def __getitem__(self, x: object) -> Element: ...
    def __iter__(self) -> Iterator[tuple[tuple[int, ...], Element]]: ...
    def exponents(self, as_ETuples: bool = True) -> list[tuple[int, ...]]: ...
    def inverse_of_unit(self) -> MPolynomial_libsingular: ...
    def is_homogeneous(self) -> bool: ...
    def _homogenize(self, var: int) -> MPolynomial_libsingular: ...
    def is_monomial(self) -> bool: ...
    def is_term(self) -> bool: ...
    def subs(self, fixed: object = None, **kw: object) -> MPolynomial_libsingular: ...
    def monomials(self) -> list[MPolynomial_libsingular]: ...
    def constant_coefficient(self) -> Element: ...
    def univariate_polynomial(self, R: object = None) -> Polynomial: ...
    def is_univariate(self) -> bool: ...
    def _variable_indices_(self, sort: bool = True) -> list[int]: ...
    def variables(self) -> tuple[MPolynomial_libsingular, ...]: ...
    def variable(self, i: int = 0) -> MPolynomial_libsingular: ...
    def nvariables(self) -> int: ...
    def is_constant(self) -> bool: ...
    def lm(self) -> MPolynomial_libsingular: ...
    def lc(self) -> Element: ...
    def lt(self) -> MPolynomial_libsingular: ...
    def is_zero(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def _floordiv_(self, right: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def factor(self, proof: object = None, **kwargs: object) -> Factorization: ...
    def lift(self, I: object) -> MPolynomial_libsingular: ...
    def reduce(self, I: object) -> MPolynomial_libsingular: ...
    def divides(self, other: Polynomial) -> bool: ...
    def gcd(self, right: Polynomial, algorithm: object = None) -> MPolynomial_libsingular: ...
    def lcm(self, g: Polynomial) -> MPolynomial_libsingular: ...
    def is_squarefree(self) -> bool: ...
    def quo_rem(self, right: MPolynomial_libsingular) -> tuple[MPolynomial_libsingular, MPolynomial_libsingular]: ...
    def _singular_init_(self, singular: object = None) -> str: ...
    def _singular_(self, singular: object = None) -> ExpectElement: ...
    def sub_m_mul_q(self, m: MPolynomial_libsingular, q: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def _macaulay2_(self, macaulay2: object = None) -> ExpectElement: ...
    def add_m_mul_q(self, m: MPolynomial_libsingular, q: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def _im_gens_(self, codomain: object, im_gens: object, base_map: object = None) -> Element: ...
    def _derivative(self, var: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def integral(self, var: MPolynomial_libsingular) -> MPolynomial_libsingular: ...
    def resultant(self, other: Polynomial, variable: object = None) -> Element: ...
    def coefficients(self) -> list[Element]: ...
    def global_height(self, prec: object = None) -> RealNumber: ...
    def local_height(self, v: object, prec: object = None) -> RealNumber: ...
    def local_height_arch(self, i: int, prec: object = None) -> RealNumber: ...
    def gradient(self) -> list[MPolynomial]: ...
    def numerator(self) -> MPolynomial_libsingular: ...
    def in_subalgebra(self, J: object, algorithm: str = 'algebra_containment', *, certificate: bool = False) -> bool | Element: ...
