from collections.abc import Iterator

from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.polynomial.polynomial_singular_interface import Polynomial_singular_repr
from sage.rings.real_mpfr import RealNumber
from sage.structure.element import Element
from sage.structure.factorization import Factorization
from sage.structure.parent import Parent

def degree_lowest_rational_function(self, x: object) -> int: ...

class MPolynomial_element(MPolynomial):
    def __init__(self, parent: Parent, x: object) -> None: ...
    def _repr_(self) -> str: ...
    def __call__(self, *x: object, **kwds: object) -> Element: ...
    def _richcmp_(self, right: object, op: int) -> bool: ...
    def _im_gens_(
        self, codomain: object, im_gens: object, base_map: object = None
    ) -> Element: ...
    def number_of_terms(self) -> int: ...
    def __neg__(self) -> MPolynomial_element: ...
    def _add_(self, right: MPolynomial_element) -> MPolynomial_element: ...
    def _sub_(self, right: MPolynomial_element) -> MPolynomial_element: ...
    def _mul_(self, right: MPolynomial_element) -> MPolynomial_element: ...
    def _lmul_(self, a: Element) -> MPolynomial_element: ...
    def _rmul_(self, a: Element) -> MPolynomial_element: ...
    def _div_(self, right: MPolynomial_element) -> MPolynomial_element: ...
    def __rpow__(self, n: int) -> MPolynomial_element: ...
    def element(self) -> Element: ...

class MPolynomial_polydict(Polynomial_singular_repr, MPolynomial_element):
    def __init__(self, parent: Parent, x: object) -> None: ...
    def _new_constant_poly(self, x: Element, P: Parent) -> MPolynomial_polydict: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _repr_with_changed_varnames(self, varnames: object) -> str: ...
    def _macaulay2_(self, macaulay2: object = None) -> Element: ...
    def degrees(self) -> tuple[int, ...]: ...
    def degree(
        self, x: object = None, std_grading: bool = False
    ) -> int | tuple[int, ...]: ...
    def total_degree(self) -> int: ...
    def monomial_coefficient(self, mon: object) -> Element: ...
    def monomial_coefficients(self, copy: object = None) -> dict[object, Element]: ...
    def __iter__(self) -> Iterator[tuple[tuple[int, ...], Element]]: ...
    def __getitem__(self, x: object) -> Element: ...
    def iterator_exp_coeff(
        self, as_ETuples: bool = True
    ) -> Iterator[tuple[tuple[int, ...], Element]]: ...
    def coefficient(self, degrees: object) -> Element: ...
    def global_height(self, prec: object = None) -> RealNumber: ...
    def local_height(self, v: object, prec: object = None) -> RealNumber: ...
    def local_height_arch(self, i: int, prec: object = None) -> RealNumber: ...
    def exponents(self, as_ETuples: bool = True) -> list[tuple[int, ...]]: ...
    def inverse_of_unit(self) -> MPolynomial_polydict: ...
    def is_homogeneous(self) -> bool: ...
    def _homogenize(self, var: str) -> MPolynomial_polydict: ...
    def is_gen(self) -> bool: ...
    def is_monomial(self) -> bool: ...
    def is_term(self) -> bool: ...
    def subs(self, fixed: object = None, **kwds: object) -> MPolynomial_polydict: ...
    def monomials(self) -> list[MPolynomial_polydict]: ...
    def constant_coefficient(self) -> Element: ...
    def is_univariate(self) -> bool: ...
    def univariate_polynomial(self, R: object = None) -> Polynomial: ...
    def variables(self) -> tuple[MPolynomial_polydict, ...]: ...
    def variable(self, i: int) -> MPolynomial_polydict: ...
    def nvariables(self) -> int: ...
    def is_constant(self) -> bool: ...
    def lm(self) -> MPolynomial_polydict: ...
    def lc(self) -> Element: ...
    def lt(self) -> MPolynomial_polydict: ...
    def __eq__(self, right: object) -> bool: ...
    def __ne__(self, right: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def _floordiv_(self, right: MPolynomial_polydict) -> MPolynomial_polydict: ...
    def _derivative(self, var: object = None) -> MPolynomial_polydict: ...
    def integral(self, var: object = None) -> MPolynomial_polydict: ...
    def factor(self, proof: object = None, **kwargs: object) -> Factorization: ...
    def lift(self, I: object) -> MPolynomial_polydict: ...
    def quo_rem(
        self, right: MPolynomial_polydict
    ) -> tuple[MPolynomial_polydict, MPolynomial_polydict]: ...
    def resultant(
        self, other: MPolynomial_polydict, variable: object = None
    ) -> Element: ...
    def subresultants(
        self, other: MPolynomial, variable: object = None
    ) -> list[MPolynomial]: ...
    def reduce(self, I: object) -> MPolynomial_polydict: ...
