from typing import TYPE_CHECKING
from sage.rings.ideal import Ideal_generic
from sage.rings.integer import Integer
from sage.structure.sequence import Sequence

if TYPE_CHECKING:
    from sage.rings.polynomial.multi_polynomial import MPolynomial
    from sage.rings.polynomial.multi_polynomial_sequence import PolynomialSequence
    from sage.matrix.matrix2 import Matrix
    from sage.modules.free_module import FreeModule

class MPolynomialIdeal(Ideal_generic):
    def groebner_basis(self) -> PolynomialSequence: ...
    def basis_is_groebner(self) -> bool: ...
    def dimension(self) -> Integer: ...
    def vector_space_dimension(self): ...
    def hilbert_polynomial(self) -> MPolynomial: ...
    def hilbert_series(self): ...
    def variety(self, ring=...) -> list: ...
    def is_zero(self) -> bool: ...
    def is_one(self) -> bool: ...
    def radical(self) -> MPolynomialIdeal: ...
    def primary_decomposition(self, algorithm: str = 'sy') -> list[MPolynomialIdeal]: ...
    def triangular_decomposition(self, algorithm: str | None = None, singular=...) -> Sequence: ...
    def saturation(self, J: MPolynomialIdeal) -> tuple[MPolynomialIdeal, int]: ...
    def genus(self) -> Integer: ...
    def complete_primary_decomposition(self, algorithm: str = 'sy') -> Sequence: ...
    def associated_primes(self, algorithm: str = 'sy') -> list[MPolynomialIdeal]: ...
    def is_prime(self, **kwds: object) -> bool: ...
    def syzygy_module(self) -> Matrix: ...
    def intersection(self, other: MPolynomialIdeal) -> MPolynomialIdeal: ...
    def is_homogeneous(self) -> bool: ...
    def interreduced_basis(self) -> list[MPolynomial]: ...
    def transformed_basis(self, algorithm: str) -> list[MPolynomial]: ...
    def change_ring(self, ring) -> MPolynomialIdeal: ...
    def defining_polynomials(self) -> tuple[MPolynomial, ...]: ...
