from collections.abc import Callable

from sage.structure.element import Element
from sage.structure.factorization import Factorization

def MacMahonOmega(
    self,
    expression: object,
    denominator: object = None,
    op: Callable[[object, object], bool] = ...,
    Factorization_sort: bool = False,
    Factorization_simplify: bool = True,
) -> Factorization: ...
def _simplify_(self, terms: object) -> tuple[Element, ...]: ...
def _Omega_(self, decoded_factors: object) -> Element: ...
def Omega_ge(self, exponents: object) -> Element: ...
def _Omega_numerator_(self, x: object, y: object, t: object) -> Element: ...
def _Omega_numerator_P_(self, x: object, y: object, t: object) -> Element: ...
def _Omega_factors_denominator_(self, y: object) -> list[Element]: ...
def partition(
    self, predicate: Callable[..., bool] = ...
) -> tuple[list[object], list[object]]: ...
def homogeneous_symmetric_function(self, x: object) -> Element: ...
