from collections.abc import Callable

from sage.structure.element import Element
from sage.structure.factorization import Factorization

def MacMahonOmega(var: object, expression: object, denominator: object = None, op: Callable[[object, object], bool] = ..., Factorization_sort: bool = False, Factorization_simplify: bool = True) -> Factorization: ...
def _simplify_(numerator: object, terms: object) -> tuple[object, ...]: ...
def _Omega_(A: object, decoded_factors: object) -> Element: ...
def Omega_ge(a: object, exponents: object) -> Element: ...
def _Omega_numerator_(a: object, x: object, y: object, t: object) -> Element: ...
def _Omega_numerator_P_(a: object, x: object, y: object, t: object) -> Element: ...
def _Omega_factors_denominator_(x: object, y: object) -> list[Element]: ...
def partition(items: object, predicate: Callable[..., bool] = ...) -> tuple[list[object], list[object]]: ...
def homogeneous_symmetric_function(j: int, x: object) -> Element: ...
