from collections.abc import Iterator
from typing import TypeAlias

from sage.categories.map import Map
from sage.categories.morphism import Morphism
from sage.categories.rings import Rings
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.structure.element import AlgebraElement, Element, ModuleElement, RingElement
from sage.structure.parent import Parent

_RingElementList: TypeAlias = list[RingElement]

class OrePolynomial(AlgebraElement):
    def __init__(self, parent: Parent, construct: bool = False) -> None: ...
    def __hash__(self) -> int: ...
    def degree(self) -> Integer: ...
    def _new_constant_poly(self, a: RingElement, P: Parent) -> OrePolynomial: ...
    def __setitem__(self, n: int, value: object) -> None: ...
    def square(self) -> OrePolynomial: ...
    def constant_coefficient(self) -> RingElement: ...
    def leading_coefficient(self) -> RingElement: ...
    def is_unit(self) -> bool: ...
    def is_nilpotent(self) -> bool: ...
    def is_monic(self) -> bool: ...
    def left_monic(self) -> OrePolynomial: ...
    def right_monic(self) -> OrePolynomial: ...
    def _mod_(self, other: OrePolynomial) -> OrePolynomial: ...
    def _floordiv_(self, right: OrePolynomial) -> OrePolynomial: ...
    def _div_(self, right: OrePolynomial) -> OrePolynomial: ...
    def is_left_divisible_by(self, other: OrePolynomial) -> bool: ...
    def is_right_divisible_by(self, other: OrePolynomial) -> bool: ...
    def left_divides(self, other: OrePolynomial) -> bool: ...
    def right_divides(self, other: OrePolynomial) -> bool: ...
    def left_xgcd(self, other: OrePolynomial, monic: bool = True) -> tuple[OrePolynomial, OrePolynomial, OrePolynomial]: ...
    def left_quo_rem(self, other: OrePolynomial) -> tuple[OrePolynomial, OrePolynomial]: ...
    def right_quo_rem(self, other: OrePolynomial) -> tuple[OrePolynomial, OrePolynomial]: ...
    def right_xgcd(self, other: OrePolynomial, monic: bool = True) -> tuple[OrePolynomial, OrePolynomial, OrePolynomial]: ...
    def right_gcd(self, other: OrePolynomial, monic: bool = True) -> OrePolynomial: ...
    def left_gcd(self, other: OrePolynomial, monic: bool = True) -> OrePolynomial: ...
    def left_xlcm(self, other: OrePolynomial, monic: bool = True) -> OrePolynomial: ...
    def right_xlcm(self, other: OrePolynomial, monic: bool = True) -> OrePolynomial: ...
    def left_lcm(self, other: OrePolynomial, monic: bool = True) -> OrePolynomial: ...
    def right_lcm(self, other: OrePolynomial, monic: bool = True) -> OrePolynomial: ...
    def _repr_(self, name: str | None = None) -> str: ...
    def _latex_(self, name: str | None = None) -> str: ...
    def _is_atomic(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def base_ring(self) -> Rings.ParentMethods[RingElement]: ...
    def shift(self, n: int) -> OrePolynomial: ...
    def __lshift__(self, k: int) -> OrePolynomial: ...
    def __rshift__(self, k: int) -> OrePolynomial: ...
    def change_variable_name(self, var: str) -> OrePolynomial: ...
    def is_term(self) -> bool: ...
    def is_monomial(self) -> bool: ...
    def coefficients(self, sparse: bool = True) -> _RingElementList: ...
    def number_of_terms(self) -> int: ...
    def __copy__(self) -> OrePolynomial: ...
    def is_zero(self) -> bool: ...
    def is_one(self) -> bool: ...
    def right_mod(self, other: OrePolynomial) -> OrePolynomial: ...
    def left_mod(self, other: OrePolynomial) -> OrePolynomial: ...
    def is_constant(self) -> bool: ...
    def exponents(self) -> list[int]: ...
    def prec(self) -> int: ...
    def padded_list(self, n: int | None = None) -> _RingElementList: ...
    def variable_name(self) -> str: ...

class OrePolynomial_generic_dense(OrePolynomial):
    def __init__(self, parent: Parent, x: object = None, check: bool = True, construct: bool = False, **kwds: object) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def _richcmp_(self, right: object, op: int) -> bool: ...
    def __iter__(self) -> Iterator[RingElement]: ...
    def __getitem__(self, n: int) -> RingElement: ...
    def list(self, copy: bool = True) -> _RingElementList: ...
    def monomial_coefficients(self) -> dict[object, RingElement]: ...
    def degree(self) -> Integer: ...
    def _add_(self, right: OrePolynomial_generic_dense) -> OrePolynomial_generic_dense: ...
    def _sub_(self, right: OrePolynomial_generic_dense) -> OrePolynomial_generic_dense: ...
    def _neg_(self) -> OrePolynomial_generic_dense: ...
    def valuation(self) -> int | PlusInfinity: ...
    def truncate(self, n: int) -> OrePolynomial_generic_dense: ...
    def _lmul_(self, s: Element) -> ModuleElement: ...
    def _rmul_(self, s: Element) -> ModuleElement: ...
    def _mul_(self, other: OrePolynomial_generic_dense) -> OrePolynomial_generic_dense: ...
    def coefficients(self, sparse: bool = True) -> _RingElementList: ...
    def hilbert_shift(self, s: RingElement, var: str | None = None) -> OrePolynomial_generic_dense: ...

class ConstantOrePolynomialSection(Map):
    def _call_(self, x: object) -> Element: ...

class OrePolynomialBaseringInjection(Morphism):
    def __init__(self, domain: object, codomain: object) -> None: ...
    def an_element(self) -> OrePolynomial: ...
    def _call_(self, e: object) -> Element: ...
    def section(self) -> ConstantOrePolynomialSection: ...
