from typing import TypeAlias

from sage.categories.morphism import Morphism
from sage.rings.polynomial.multi_polynomial_ideal import NCPolynomialIdeal
from sage.rings.polynomial.multi_polynomial_libsingular import MPolynomialRing_libsingular
from sage.rings.polynomial.term_order import TermOrder
from sage.rings.ring import Ring
from sage.structure.element import Element, RingElement
from sage.structure.factory import FactoryArgument, FactoryCacheKey, FactoryExtraArgs, FactoryVersion, UniqueFactory

_PolyDict: TypeAlias = dict[object, Element]

def unpickle_NCPolynomial_plural(R: NCPolynomialRing_plural, d: object) -> NCPolynomial_plural: ...
def new_CRing(rw: object, base_ring: object) -> MPolynomialRing_libsingular: ...
def new_NRing(rw: object, base_ring: object) -> NCPolynomialRing_plural: ...
def new_Ring(rw: object, base_ring: object) -> Ring: ...
def SCA(base_ring: Ring, names: object, alt_vars: object, order: str = 'degrevlex') -> NCPolynomialRing_plural: ...
def ExteriorAlgebra(base_ring: Ring, names: object, order: str = 'degrevlex') -> NCPolynomialRing_plural: ...

class G_AlgFactory(UniqueFactory):
    def create_object(self, version: FactoryVersion, key: FactoryCacheKey, **extra_args: FactoryArgument) -> NCPolynomialRing_plural: ...
    def create_key_and_extra_args(self, *args: FactoryArgument, **kwds: FactoryArgument) -> tuple[FactoryCacheKey, FactoryExtraArgs]: ...

class NCPolynomialRing_plural(Ring):
    def __init__(self, base_ring: Ring, names: object, c: object, d: object, order: object, category: object, check: bool = True) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def _element_constructor_(self, element: object) -> NCPolynomial_plural: ...
    def _coerce_map_from_(self, S: object) -> Morphism | bool | None: ...
    def free_algebra(self) -> Ring: ...
    def __hash__(self) -> int: ...
    def __pow__(self, n: int, _: object) -> NCPolynomialRing_plural: ...
    def term_order(self) -> TermOrder: ...
    def is_field(self, *args: object, **kwargs: object) -> bool: ...
    def _repr_(self) -> str: ...
    def _ringlist(self) -> list[object]: ...
    def relations(self, add_commutative: bool = False) -> list[NCPolynomial_plural]: ...
    def ngens(self) -> int: ...
    def gen(self, n: int = 0) -> NCPolynomial_plural: ...
    def algebra_generators(self) -> list[NCPolynomial_plural]: ...
    def ideal(self, *gens: object, **kwds: object) -> NCPolynomialIdeal: ...
    def _list_to_ring(self, L: object) -> NCPolynomialRing_plural: ...
    def monomial_quotient(self, f: NCPolynomial_plural, g: NCPolynomial_plural, coeff: bool = False) -> NCPolynomial_plural: ...
    def monomial_divides(self, a: NCPolynomial_plural, b: NCPolynomial_plural) -> bool: ...
    def monomial_lcm(self, f: NCPolynomial_plural, g: NCPolynomial_plural) -> NCPolynomial_plural: ...
    def monomial_reduce(self, f: NCPolynomial_plural, G: object) -> NCPolynomial_plural: ...
    def monomial_pairwise_prime(self, g: NCPolynomial_plural, h: NCPolynomial_plural) -> bool: ...
    def monomial_all_divisors(self, t: NCPolynomial_plural) -> list[NCPolynomial_plural]: ...

class NCPolynomial_plural(RingElement):
    def __init__(self, parent: NCPolynomialRing_plural) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def __hash__(self) -> int: ...
    def _richcmp_(self, right: object, op: int) -> bool: ...
    def _add_(self, right: NCPolynomial_plural) -> NCPolynomial_plural: ...
    def _sub_(self, right: NCPolynomial_plural) -> NCPolynomial_plural: ...
    def _lmul_(self, left: Element) -> NCPolynomial_plural: ...
    def _mul_(self, right: NCPolynomial_plural) -> NCPolynomial_plural: ...
    def _div_(self, right: NCPolynomial_plural) -> NCPolynomial_plural: ...
    def __pow__(self, exp: int, mod: object = ...) -> NCPolynomial_plural: ...
    def __neg__(self) -> NCPolynomial_plural: ...
    def reduce(self, I: object) -> NCPolynomial_plural: ...
    def _repr_(self) -> str: ...
    def _repr_short_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _repr_with_changed_varnames(self, varnames: object) -> str: ...
    def degree(self, x: object = None) -> int | tuple[int, ...]: ...
    def total_degree(self) -> int: ...
    def degrees(self) -> tuple[int, ...]: ...
    def coefficient(self, degrees: object) -> Element: ...
    def monomial_coefficient(self, mon: NCPolynomial_plural) -> Element: ...
    def dict(self) -> _PolyDict: ...
    def monomial_coefficients(self, copy: bool = True) -> _PolyDict: ...
    def _im_gens_(self, codomain: object, im_gens: object, base_map: object = None) -> Element: ...
    def __getitem__(self, x: object) -> Element: ...
    def exponents(self, as_ETuples: bool = True) -> list[tuple[int, ...]]: ...
    def is_homogeneous(self) -> bool: ...
    def is_monomial(self) -> bool: ...
    def monomials(self) -> list[NCPolynomial_plural]: ...
    def constant_coefficient(self) -> Element: ...
    def is_constant(self) -> bool: ...
    def lm(self) -> NCPolynomial_plural: ...
    def lc(self) -> Element: ...
    def lt(self) -> NCPolynomial_plural: ...
    def is_zero(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __call__(self, *x: object, **kwds: object) -> Element: ...
