from typing import overload

from sage.geometry.newton_polygon import NewtonPolygon_element
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial, Polynomial_generic_dense, Polynomial_generic_dense_inexact
from sage.rings.rational import Rational
from sage.rings.polynomial.polynomial_singular_interface import Polynomial_singular_repr
from sage.structure.element import Element, EuclideanDomainElement, IntegralDomainElement
from sage.structure.parent import Parent

class Polynomial_generic_sparse(Polynomial):
    def __init__(self, parent: Parent, x: object = None, check: bool = True, is_gen: bool = False, construct: bool = False) -> None: ...
    def monomial_coefficients(self, copy: object = None) -> dict[object, Element]: ...
    def coefficients(self, sparse: bool = True) -> list[Element]: ...
    def exponents(self) -> list[int]: ...
    def valuation(self, p: object = None) -> int: ...
    def integral(self, var: object = None) -> Polynomial: ...
    @overload
    def __getitem__(self, n: int) -> Element: ...
    @overload
    def __getitem__(self, n: slice) -> Polynomial: ...
    def list(self, copy: bool = True) -> list[Element]: ...
    def degree(self, gen: object = None) -> Integer: ...
    def __floordiv__(self, right: Polynomial) -> Polynomial: ...
    def shift(self, n: int) -> Polynomial: ...
    def quo_rem(self, other: Polynomial) -> tuple[Polynomial, Polynomial]: ...
    def gcd(self, other: Polynomial, algorithm: object = None) -> Polynomial: ...
    def reverse(self, degree: int | None = None) -> Polynomial: ...
    def truncate(self, n: int) -> Polynomial: ...
    def number_of_terms(self) -> int: ...

class Polynomial_generic_domain(Polynomial, IntegralDomainElement):
    def __init__(self, parent: Parent, is_gen: bool = False, construct: bool = False) -> None: ...
    def is_unit(self) -> bool: ...

class Polynomial_generic_field(Polynomial_singular_repr, Polynomial_generic_domain, EuclideanDomainElement): ...
class Polynomial_generic_sparse_field(Polynomial_generic_sparse, Polynomial_generic_field): ...
class Polynomial_generic_dense_field(Polynomial_generic_dense, Polynomial_generic_field): ...

class Polynomial_generic_cdv(Polynomial_generic_domain):
    def newton_slopes(self, p: object = ..., lengths: bool = ...) -> list[Rational]: ...
    def newton_polygon(self) -> NewtonPolygon_element: ...
    def hensel_lift(self, a: Element) -> list[Polynomial]: ...
    def factor_of_slope(self, slope: object = None) -> Polynomial: ...
    def slope_factorization(self) -> list[Polynomial]: ...

class Polynomial_generic_dense_cdv(Polynomial_generic_dense_inexact, Polynomial_generic_cdv): ...
class Polynomial_generic_sparse_cdv(Polynomial_generic_sparse, Polynomial_generic_cdv): ...
class Polynomial_generic_cdvr(Polynomial_generic_cdv): ...
class Polynomial_generic_dense_cdvr(Polynomial_generic_dense_cdv, Polynomial_generic_cdvr): ...
class Polynomial_generic_sparse_cdvr(Polynomial_generic_sparse_cdv, Polynomial_generic_cdvr): ...
class Polynomial_generic_cdvf(Polynomial_generic_cdv, Polynomial_generic_field): ...
class Polynomial_generic_dense_cdvf(Polynomial_generic_dense_cdv, Polynomial_generic_cdvf): ...
class Polynomial_generic_sparse_cdvf(Polynomial_generic_sparse_cdv, Polynomial_generic_cdvf): ...
