from sage.rings.morphism import RingHomomorphism_from_base

class PolynomialRingHomomorphism_from_base(RingHomomorphism_from_base):
    def is_injective(self) -> bool: ...
    def is_surjective(self) -> bool: ...
