from sage.rings.polynomial.polynomial_element import Polynomial

def _mul_fateman_to_int2(self, g_list: list[int]) -> int: ...
def _mul_fateman_to_poly(self, padding: int) -> list[int]: ...
def _mul_fateman_mul(self, g: Polynomial) -> Polynomial: ...
