from typing import TypeAlias

from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.real_mpfi import RealIntervalFieldElement
from sage.rings.real_mpfr import RealNumber
from sage.structure.element import Element
from sage.structure.factorization import Factorization
from sage.structure.parent import Parent

class gen: ...

_RealIntervalList: TypeAlias = list[RealIntervalFieldElement]

class Polynomial_integer_dense_flint(Polynomial):
    def __init__(self, parent: Parent, x: object = None, check: bool = True, is_gen: bool = False, construct: bool = False) -> None: ...
    def _new_constant_poly(self, a: Integer, P: Parent) -> Polynomial: ...
    def _eval_mpfr_(self, a: RealNumber) -> RealNumber: ...
    def _eval_mpfi_(self, a: RealIntervalFieldElement) -> RealIntervalFieldElement: ...
    def __call__(self, *args: object, **kwds: object) -> Element: ...
    def content(self) -> Integer: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def _repr(self, name: str | None = None, latex: bool = False) -> str: ...
    def _latex_(self, name: str | None = None) -> str: ...
    def _add_(self, right: Polynomial_integer_dense_flint) -> Polynomial_integer_dense_flint: ...
    def _sub_(self, right: Polynomial_integer_dense_flint) -> Polynomial_integer_dense_flint: ...
    def _neg_(self) -> Polynomial_integer_dense_flint: ...
    def quo_rem(self, right: Polynomial_integer_dense_flint) -> tuple[Polynomial_integer_dense_flint, Polynomial_integer_dense_flint]: ...
    def is_zero(self) -> bool: ...
    def is_one(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def gcd(self, right: Polynomial) -> Polynomial_integer_dense_flint: ...
    def lcm(self, right: Polynomial) -> Polynomial_integer_dense_flint: ...
    def xgcd(self, right: Polynomial) -> tuple[Integer, Polynomial_integer_dense_flint, Polynomial_integer_dense_flint]: ...
    def _mul_(self, right: Polynomial_integer_dense_flint) -> Polynomial_integer_dense_flint: ...
    def _mul_trunc_(self, right: Polynomial, n: int) -> Polynomial: ...
    def _lmul_(self, right: Element) -> Polynomial_integer_dense_flint: ...
    def _rmul_(self, right: Element) -> Polynomial_integer_dense_flint: ...
    def __pow__(self, right: int, modulus: object = ...) -> Polynomial: ...
    def _power_trunc(self, n: int, prec: int) -> Polynomial: ...
    def __floordiv__(self, right: Polynomial) -> Polynomial_integer_dense_flint: ...
    def inverse_series_trunc(self, prec: int) -> Polynomial: ...
    def _unsafe_mutate(self, n: int, value: Integer) -> None: ...
    def real_root_intervals(self) -> _RealIntervalList: ...
    def degree(self, gen: object = None) -> Integer: ...
    def pseudo_divrem(self, B: Polynomial_integer_dense_flint) -> tuple[Polynomial_integer_dense_flint, Polynomial_integer_dense_flint, Integer]: ...
    def discriminant(self, proof: bool = True) -> Integer: ...
    def __pari__(self, variable: str | None = None) -> gen: ...
    def squarefree_decomposition(self) -> list[tuple[Polynomial, int]]: ...
    def _factor_pari(self) -> Factorization: ...
    def _factor_ntl(self) -> Factorization: ...
    def factor(self, **kwargs: object) -> Factorization: ...
    def factor_mod(self, p: Integer) -> Factorization: ...
    def factor_padic(self, p: Integer, prec: int = 10) -> Factorization: ...
    def list(self, copy: bool = True) -> list[Integer]: ...
    def resultant(self, other: Polynomial, proof: bool = True) -> Integer: ...
    def reverse(self, degree: int | None = None) -> Polynomial: ...
    def revert_series(self, n: int) -> Polynomial: ...
