from sage.categories.category import Category
from sage.rings.polynomial.polynomial_ring import PolynomialRing_generic
from sage.structure.parent import Parent

def PolynomialRing(self, *args: object, **kwds: object) -> PolynomialRing_generic: ...
def unpickle_PolynomialRing(
    self, arg1: object = None, arg2: object = None, sparse: bool = False
) -> PolynomialRing_generic: ...
def polynomial_default_category(self, n_variables: int) -> Category: ...
def BooleanPolynomialRing_constructor(
    self=None, names: object = None, order: str = "lex"
) -> Parent: ...
