from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.real_arb import RealBall
from sage.structure.element import Element
from sage.structure.parent import Parent

class Polynomial_real_arb(Polynomial):
    def __init__(self, parent: Parent, x: object = None, check: bool = True, is_gen: bool = False, construct: bool = False) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def degree(self, gen: object = None) -> Integer: ...
    def list(self, copy: bool = True) -> list[RealBall]: ...
    def __bool__(self) -> bool: ...
    def _add_(self, other: Polynomial_real_arb) -> Polynomial_real_arb: ...
    def _neg_(self) -> Polynomial_real_arb: ...
    def _sub_(self, other: Polynomial_real_arb) -> Polynomial_real_arb: ...
    def _mul_(self, other: Polynomial_real_arb) -> Polynomial_real_arb: ...
    def _lmul_(self, a: Element) -> Polynomial_real_arb: ...
    def _rmul_(self, a: Element) -> Polynomial_real_arb: ...
    def quo_rem(self, divisor: Polynomial_real_arb) -> tuple[Polynomial_real_arb, Polynomial_real_arb]: ...
    def truncate(self, n: int) -> Polynomial: ...
    def __lshift__(self, n: int) -> Polynomial_real_arb: ...
    def __rshift__(self, n: int) -> Polynomial_real_arb: ...
    def _mul_trunc_(self, other: Polynomial, n: int) -> Polynomial: ...
    def inverse_series_trunc(self, n: int) -> Polynomial: ...
    def _power_trunc(self, expo: int, n: int) -> Polynomial: ...
    def _log_series(self, n: int) -> Polynomial_real_arb: ...
    def _exp_series(self, n: int) -> Polynomial_real_arb: ...
    def _sqrt_series(self, n: int) -> Polynomial_real_arb: ...
    def _gamma_series(self, n: int) -> Polynomial_real_arb: ...
    def _lgamma_series(self, n: int) -> Polynomial_real_arb: ...
    def _rgamma_series(self, n: int) -> Polynomial_real_arb: ...
    def _lambert_w_series(self, n: int, branch: int = 0) -> Polynomial_real_arb: ...
    def _zeta_series(self, n: int, a: object = 1, deflate: bool = False) -> Polynomial_real_arb: ...
    def compose_trunc(self, other: Polynomial, n: int) -> Polynomial: ...
    def revert_series(self, n: int) -> Polynomial: ...
    def __call__(self, *args: object, **kwds: object) -> Element: ...
