from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element
from sage.structure.factorization import Factorization
from sage.structure.parent import Parent

class Polynomial_template(Polynomial): ...

class Polynomial_zmod_flint(Polynomial_template):
    def __init__(self, parent: Parent, x: object = None, check: bool = True, is_gen: bool = False, construct: bool = False) -> None: ...
    def _new_constant_poly(self, x: Element, P: Parent) -> Polynomial: ...
    def __call__(self, *args: object, **kwds: object) -> Element: ...
    def resultant(self, other: Polynomial) -> Element: ...
    def small_roots(self, *args: object, **kwds: object) -> list[Element]: ...
    def _unsafe_mutate(self, n: int, value: Element) -> None: ...
    def _mul_trunc_(self, right: Polynomial, n: int) -> Polynomial: ...
    def _mul_trunc_opposite(self, other: Polynomial_zmod_flint, n: int) -> Polynomial: ...
    def __pow__(self, right: int, modulus: object = ...) -> Polynomial: ...
    def _power_trunc(self, n: int, prec: int) -> Polynomial: ...
    def rational_reconstruction(self, m: object, n_deg: int | None = 0, d_deg: int | None = 0) -> tuple[Polynomial_zmod_flint, Polynomial_zmod_flint]: ...
    def is_irreducible(self) -> bool: ...
    def squarefree_decomposition(self) -> Factorization: ...
    def factor(self, **kwargs: object) -> Factorization: ...
    def monic(self) -> Polynomial_zmod_flint: ...
    def reverse(self, degree: int | None = None) -> Polynomial: ...
    def revert_series(self, n: int) -> Polynomial: ...
    def minpoly_mod(self, other: Polynomial_zmod_flint) -> Polynomial_zmod_flint: ...
    def compose_mod(self, other: Polynomial_zmod_flint, modulus: Polynomial_zmod_flint) -> Polynomial_zmod_flint: ...
