from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.real_mpfr import RealNumber
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.parent import Parent

class PolynomialRealDense(Polynomial):
    def __init__(
        self,
        parent: Parent,
        x: object | bool = 0,
        check: bool | None = None,
        is_gen: bool = False,
        construct: object = None,
    ) -> None: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...]]: ...
    def degree(self, gen: object = None) -> Integer: ...
    def truncate(self, n: int) -> Polynomial: ...
    def truncate_abs(self, bound: RealNumber) -> PolynomialRealDense: ...
    def shift(self, n: int) -> Polynomial: ...
    def list(self, copy: bool = True) -> list[RealNumber]: ...
    def __neg__(self) -> PolynomialRealDense: ...
    def _add_(self, _right: PolynomialRealDense) -> PolynomialRealDense: ...
    def _sub_(self, _right: PolynomialRealDense) -> PolynomialRealDense: ...
    def _lmul_(self, c: Element) -> PolynomialRealDense: ...
    def _mul_(self, _right: PolynomialRealDense) -> PolynomialRealDense: ...
    def _derivative(self, var: object = None) -> PolynomialRealDense: ...
    def integral(self, var: object = None) -> Polynomial: ...
    def reverse(self, degree: int | None = None) -> Polynomial: ...
    def quo_rem(
        self, other: PolynomialRealDense
    ) -> tuple[PolynomialRealDense, PolynomialRealDense]: ...
    def __call__(self, *args: object, **kwds: object) -> Element: ...
    def change_ring(self, R: Ring) -> Polynomial: ...

def make_PolynomialRealDense(parent: Parent, data: object) -> PolynomialRealDense: ...
