from collections.abc import Iterator

from sage.categories.morphism import Morphism
from sage.categories.pushout import CompletionFunctor
from sage.categories.rings import Rings
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.fraction_field import FractionField_generic
from sage.rings.ring import Field, Ring
from sage.structure.element import Element
from sage.structure.parent import Parent

class PolynomialRing_generic(Ring):
    def is_integral_domain(self, proof: bool = True) -> bool: ...
    def is_unique_factorization_domain(self, proof: bool = True) -> bool: ...
    def is_noetherian(self) -> bool: ...
    def some_elements(self) -> list[Element]: ...
    def monomials_of_degree(self, degree: int) -> tuple[Element, ...]: ...
    def flattening_morphism(self) -> Morphism: ...
    def construction(self) -> tuple[CompletionFunctor, Parent]: ...
    def completion(self, p: object = None, prec: int = 20, extras: object = None) -> Parent: ...
    def __hash__(self) -> int: ...
    def base_extend(self, R: Parent) -> PolynomialRing_generic: ...
    def change_ring(self, R: Parent) -> PolynomialRing_generic: ...
    def change_variable_name(self, var: str) -> PolynomialRing_generic: ...
    def extend_variables(self, added_names: object, order: str = "degrevlex") -> PolynomialRing_generic: ...
    def variable_names_recursive(self, depth: int | PlusInfinity = ...) -> tuple[str, ...]: ...
    def characteristic(self) -> Integer: ...
    def cyclotomic_polynomial(self, n: int) -> Polynomial: ...
    def gen(self, n: int = 0) -> Polynomial: ...
    def gens(self) -> tuple[Polynomial, ...]: ...
    def gens_dict(self, copy: bool = ...) -> dict[str, Element]: ...
    def parameter(self) -> Element: ...
    def is_exact(self) -> bool: ...
    def is_field(self, proof: bool = True) -> bool: ...
    def is_sparse(self) -> bool: ...
    def monomial(self, exponent: tuple[int, ...]) -> Element: ...
    def krull_dimension(self) -> int: ...
    def ngens(self) -> int: ...
    def random_element(self, degree: object = ..., *args: object, **kwds: object) -> Polynomial: ...
    def karatsuba_threshold(self) -> int: ...
    def set_karatsuba_threshold(self, Karatsuba_threshold: int) -> None: ...
    def polynomials(self, of_degree: int | None = None, max_degree: int | None = None) -> Iterator[Polynomial]: ...
    def monics(self, of_degree: int | None = None, max_degree: int | None = None) -> Iterator[Polynomial]: ...

class PolynomialRing_commutative(PolynomialRing_generic):
    def quotient_by_principal_ideal(self, f: Polynomial, names: object = None, **kwds: object) -> Parent: ...
    def weyl_algebra(self) -> Parent: ...

class PolynomialRing_integral_domain(PolynomialRing_commutative):
    def weil_polynomials(self, d: int, q: object, sign: int = 1, lead: object = 1) -> list[Polynomial]: ...
    def construction(self) -> tuple[CompletionFunctor, Parent]: ...

class PolynomialRing_field(PolynomialRing_integral_domain):
    def divided_difference(self, points: list[Element] | tuple[Element, ...], full_table: bool = False) -> Element: ...
    def fraction_field(self) -> Field: ...

class PolynomialRing_dense_finite_field(PolynomialRing_field):
    def __init__(self, base_ring: Ring, name: str = "x", element_class: type = ...) -> None: ...
    def irreducible_element(self, n: int, algorithm: object = None) -> Polynomial: ...

class PolynomialRing_cdvr(PolynomialRing_integral_domain): ...
class PolynomialRing_cdvf(PolynomialRing_cdvr, PolynomialRing_field): ...
class PolynomialRing_dense_padic_ring_generic(PolynomialRing_cdvr):
    def __init__(self, base_ring: Ring, name: str | None = None, implementation: object = ...) -> None: ...
class PolynomialRing_dense_padic_field_generic(PolynomialRing_cdvf):
    def __init__(self, base_ring: Ring, name: str | None = None, implementation: object = ...) -> None: ...
class PolynomialRing_dense_padic_ring_capped_relative(PolynomialRing_dense_padic_ring_generic):
    def __init__(self, base_ring: Ring, name: str | None = None, implementation: object = ...) -> None: ...
class PolynomialRing_dense_padic_ring_capped_absolute(PolynomialRing_dense_padic_ring_generic):
    def __init__(self, base_ring: Ring, name: str | None = None, implementation: object = ...) -> None: ...
class PolynomialRing_dense_padic_ring_fixed_mod(PolynomialRing_dense_padic_ring_generic):
    def __init__(self, base_ring: Ring, name: str | None = None, implementation: object = ...) -> None: ...
class PolynomialRing_dense_padic_field_capped_relative(PolynomialRing_dense_padic_field_generic):
    def __init__(self, base_ring: Ring, name: str | None = None, implementation: object = ...) -> None: ...
class PolynomialRing_dense_mod_n(PolynomialRing_commutative):
    def modulus(self) -> int: ...
    def residue_field(self, ideal: object, names: object = None) -> Parent: ...

class PolynomialRing_dense_mod_p(PolynomialRing_dense_finite_field, PolynomialRing_dense_mod_n):
    def __init__(self, base_ring: Ring, name: str = "x", implementation: object = ...) -> None: ...
    def irreducible_element(self, n: int, algorithm: object = None) -> Polynomial: ...
    def fraction_field(self) -> Field: ...

def polygen(ring_or_element: object, name: str = "x") -> Polynomial: ...
def polygens(base_ring: Ring, names: str | tuple[str, ...] = "x", *args: object) -> tuple[Polynomial, ...]: ...
