from typing import TypeAlias

from sage.rings.ideal import Ideal_generic as Ideal
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.lazy_series_ring import LazyPowerSeriesRing
from sage.rings.ring import CommutativeRing, Ring
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.power_series_ring import PowerSeriesRing_generic
from sage.structure.category_object import NameSpec

_RandomDegree: TypeAlias = int | Integer | tuple[int | Integer, int | Integer] | list[int | Integer]
_RandomArg: TypeAlias = int | Integer | bool | str | None
_QuotientIdeal: TypeAlias = Ideal | Polynomial | tuple[Polynomial, ...] | list[Polynomial]

class PolynomialRing_generic:
    def gen(self, n: int = 0) -> Polynomial: ...
    def gens(self) -> tuple[Polynomial, ...]: ...
    def ngens(self) -> Integer: ...
    def base_ring(self) -> CommutativeRing: ...
    def characteristic(self) -> Integer: ...
    def is_field(self, proof: bool = True) -> bool: ...
    def random_element(self, degree: _RandomDegree = ..., monic: bool = ..., *args: _RandomArg, **kwds: _RandomArg) -> Polynomial: ...
    def quotient(self, I: _QuotientIdeal, names: NameSpec = None, **kwds: _RandomArg) -> Ring: ...
    def fraction_field(self) -> Ring: ...
    def change_ring(self, R: CommutativeRing) -> PolynomialRing_generic: ...
    def completion(self, p: Polynomial | None = None, prec: int | Integer | PlusInfinity = 20, extras: dict[str, str] | None = None) -> PowerSeriesRing_generic | LazyPowerSeriesRing: ...
    def some_elements(self) -> tuple[Polynomial, ...]: ...

PolynomialRing_general = PolynomialRing_generic
