from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.element import Element
from sage.structure.parent import Parent

class gen: ...

class Polynomial_template(Polynomial): ...

def GF2X_BuildIrred_list(n: int) -> list[Element]: ...
def GF2X_BuildSparseIrred_list(n: int) -> list[Element]: ...
def GF2X_BuildRandomIrred_list(n: int) -> list[Element]: ...

class Polynomial_GF2X(Polynomial_template):
    def __init__(self, parent: Parent, x: object = None, check: bool = True, is_gen: bool = False, construct: bool = False) -> None: ...
    def __pari__(self, variable: str | None = None) -> gen: ...
    def modular_composition(self, g: Polynomial_GF2X, h: Polynomial_GF2X, algorithm: str | None = None) -> Polynomial_GF2X: ...
    def is_irreducible(self) -> bool: ...
