from collections.abc import Iterator

from sage.rings.polynomial.skew_polynomial_finite_order import SkewPolynomial_finite_order_dense
from sage.structure.factorization import Factorization

class SkewPolynomial_finite_field_dense(SkewPolynomial_finite_order_dense):
    def is_irreducible(self) -> bool: ...
    def type(self, N: object) -> list[int]: ...
    def _reduced_norm_factor_uniform(self) -> Factorization: ...
    def _irreducible_divisors(self, right: bool) -> list[SkewPolynomial_finite_field_dense]: ...
    def right_irreducible_divisor(self, uniform: bool = False) -> SkewPolynomial_finite_field_dense: ...
    def left_irreducible_divisor(self, uniform: bool = False) -> SkewPolynomial_finite_field_dense: ...
    def right_irreducible_divisors(self) -> list[SkewPolynomial_finite_field_dense]: ...
    def left_irreducible_divisors(self) -> list[SkewPolynomial_finite_field_dense]: ...
    def count_irreducible_divisors(self) -> int: ...
    def factor(self, uniform: bool = False) -> Factorization: ...
    def count_factorizations(self) -> int: ...
    def factorizations(self) -> Iterator[Factorization]: ...
