from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.structure.element import Element

def spol(g1: MPolynomial, g2: MPolynomial) -> MPolynomial: ...
def gpol(g1: MPolynomial, g2: MPolynomial) -> MPolynomial: ...
def LM(f: MPolynomial) -> MPolynomial: ...
def LC(f: MPolynomial) -> Element: ...
def d_basis(F: list[MPolynomial], strat: bool = True) -> list[MPolynomial]: ...
def select(P: list[tuple[int, int]]) -> tuple[int, int]: ...
def update(G: list[MPolynomial], B: list[tuple[int, int]], h: MPolynomial) -> list[tuple[int, int]]: ...
