from sage.matrix.matrix0 import Matrix
from sage.rings.polynomial.multi_polynomial import MPolynomial
from sage.structure.element import Element

def is_triangular(self) -> bool: ...
def coefficient_matrix(self) -> Matrix: ...
def is_linearly_dependent(self) -> bool: ...
def linear_representation(self, polys: list[MPolynomial]) -> list[Element]: ...
def triangular_factorization(self, n: int = -1) -> list[MPolynomial]: ...
def elim_pol(self, n: int = -1) -> list[MPolynomial]: ...
