from sage.structure.element import Element
from sage.rings.integer import Integer
from sage.matrix.matrix_integer_dense import Matrix_integer_dense
from sage.matrix.matrix_rational_dense import Matrix_rational_dense
from sage.algebras.quatalg.quaternion_algebra import QuaternionAlgebra_ab

def integral_matrix_and_denom_from_rational_quaternions(v: list[Element] | tuple[Element, ...], reverse: bool = False) -> tuple[Matrix_integer_dense, Integer]: ...
def rational_matrix_from_rational_quaternions(v: list[Element] | tuple[Element, ...], reverse: bool = False) -> Matrix_rational_dense: ...
def rational_quaternions_from_integral_matrix_and_denom(A: QuaternionAlgebra_ab, H: Matrix_integer_dense, d: int | Integer, reverse: bool = False) -> tuple[Element, ...]: ...
