# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def fricas_desolve(de: builtins.object, dvar: builtins.object, ics: builtins.object, ivar: builtins.object) -> _SageObject: ...

def fricas_desolve_system(des: builtins.object, dvars: builtins.object, ics: builtins.object, ivar: builtins.object) -> _SageObject: ...

def desolve(de: builtins.object, dvar: builtins.object, ics: builtins.object = ..., ivar: builtins.object = ..., show_method: builtins.bool = ..., contrib_ode: builtins.bool = ..., algorithm: builtins.str = ...) -> _SageObject: ...

def desolve_laplace(de: builtins.object, dvar: builtins.object, ics: builtins.object = ..., ivar: builtins.object = ...) -> _SageObject: ...

def desolve_system(des: builtins.object, vars: builtins.object, ics: builtins.object = ..., ivar: builtins.object = ..., algorithm: builtins.str = ...) -> _SageObject: ...

def eulers_method(f: builtins.object, x0: builtins.object, y0: builtins.object, h: builtins.object, x1: builtins.object, algorithm: builtins.str = ...) -> _SageObject: ...

def eulers_method_2x2(f: builtins.object, g: builtins.object, t0: builtins.object, x0: builtins.object, y0: builtins.object, h: builtins.object, t1: builtins.object, algorithm: builtins.str = ...) -> _SageObject: ...

def eulers_method_2x2_plot(f: builtins.object, g: builtins.object, t0: builtins.object, x0: builtins.object, y0: builtins.object, h: builtins.object, t1: builtins.object) -> _SageObject: ...

def desolve_rk4_determine_bounds(ics: builtins.object, end_points: builtins.object = ...) -> _SageObject: ...

def desolve_rk4(de: builtins.object, dvar: builtins.object, ics: builtins.object = ..., ivar: builtins.object = ..., end_points: builtins.object = ..., step: builtins.float = ..., output: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...

def desolve_system_rk4(des: builtins.object, vars: builtins.object, ics: builtins.object = ..., ivar: builtins.object = ..., end_points: builtins.object = ..., step: builtins.float = ...) -> _SageObject: ...

def desolve_odeint(des: builtins.object, ics: builtins.object, times: builtins.object, dvars: builtins.object, ivar: builtins.object = ..., compute_jac: builtins.bool = ..., args: builtins.tuple[_SageObject, ...] = ..., rtol: builtins.object = ..., atol: builtins.object = ..., tcrit: builtins.object = ..., h0: builtins.float = ..., hmax: builtins.float = ..., hmin: builtins.float = ..., ixpr: builtins.int = ..., mxstep: builtins.int = ..., mxhnil: builtins.int = ..., mxordn: builtins.int = ..., mxords: builtins.int = ..., printmessg: builtins.int = ...) -> _SageObject: ...

def desolve_mintides(f: builtins.object, ics: builtins.object, initial: builtins.object, final: builtins.object, delta: builtins.object, tolrel: builtins.float = ..., tolabs: builtins.float = ...) -> _SageObject: ...

def desolve_tides_mpfr(f: builtins.object, ics: builtins.object, initial: builtins.object, final: builtins.object, delta: builtins.object, tolrel: builtins.float = ..., tolabs: builtins.float = ..., digits: builtins.int = ...) -> _SageObject: ...
