# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def simplify(f: builtins.object, algorithm: builtins.str = ..., **kwds: builtins.object) -> _SageObject: ...

def derivative(f: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

diff: _SageObject
def integral(f: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

integrate: _SageObject
def limit(f: builtins.object, dir: builtins.object = ..., taylor: builtins.bool = ..., **argv: builtins.object) -> _SageObject: ...

lim: _SageObject
def taylor(f: builtins.object, *args: builtins.object) -> _SageObject: ...

def expand(x: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
