# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def polygon_spline(pts: builtins.object) -> _SageObject: ...

class PSpline:
    def __init__(self, pts: builtins.object) -> None: ...
    def value(self, t: builtins.object) -> _SageObject: ...
    def derivative(self, t: builtins.object) -> _SageObject: ...

def complex_cubic_spline(pts: builtins.object) -> _SageObject: ...

class CCSpline:
    def __init__(self, pts: builtins.object) -> None: ...
    def value(self, t: builtins.object) -> _SageObject: ...
    def derivative(self, t: builtins.object) -> _SageObject: ...
