from collections.abc import Sequence


type ComplexPoint = complex | tuple[float, float]


def polygon_spline(pts: Sequence[ComplexPoint]) -> PSpline: ...


class PSpline:
    def __init__(self, pts: Sequence[ComplexPoint]) -> None: ...
    def value(self, t: float) -> complex: ...
    def derivative(self, t: float) -> complex: ...


def complex_cubic_spline(pts: Sequence[ComplexPoint]) -> CCSpline: ...


class CCSpline:
    def __init__(self, pts: Sequence[ComplexPoint]) -> None: ...
    def value(self, t: float) -> complex: ...
    def derivative(self, t: float) -> complex: ...
