# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class PyFunctionWrapper:
    def set_yn(self, x: builtins.object) -> _SageObject: ...

class ode_system:
    def c_j(self, t: builtins.object, y: builtins.object, dfdy: builtins.object, dfdt: builtins.object) -> _SageObject: ...
    def c_f(self, t: builtins.object, y: builtins.object, dydt: builtins.object) -> _SageObject: ...

def c_jac_compiled(t: builtins.object, y: builtins.object, dfdy: builtins.object, dfdt: builtins.object, params: builtins.object) -> _SageObject: ...

def c_f_compiled(t: builtins.object, y: builtins.object, dydt: builtins.object, params: builtins.object) -> _SageObject: ...

def c_jac(t: builtins.object, y: builtins.object, dfdy: builtins.object, dfdt: builtins.object, params: builtins.object) -> _SageObject: ...

def c_f(t: builtins.object, y: builtins.object, dydt: builtins.object, params: builtins.object) -> _SageObject: ...

class ode_solver:
    def __setattr__(self, name: builtins.object, value: builtins.object) -> None: ...
    def interpolate_solution(self, i: builtins.object = ...) -> _SageObject: ...
    def plot_solution(self, i: builtins.object = ..., filename: builtins.object = ..., interpolate: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def ode_solve(self, t_span: builtins.object = ..., y_0: builtins.object = ..., num_points: builtins.object = ..., params: builtins.object = ...) -> _SageObject: ...
