# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def var(*args: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def function(s: builtins.object, **kwds: builtins.object) -> _SageObject: ...

def clear_vars() -> _SageObject: ...
