# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class BasisMatroid:
    def __init__(self, M: builtins.object = ..., groundset: builtins.object = ..., bases: builtins.object = ..., nonbases: builtins.object = ..., rank: builtins.object = ...) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def reset_current_basis(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def truncation(self) -> _SageObject: ...
    def relabel(self, mapping: builtins.object) -> _SageObject: ...
    def bases_count(self) -> _SageObject: ...
    def bases(self) -> _SageObject: ...
    def nonbases(self) -> _SageObject: ...
    def is_distinguished(self, e: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(left: builtins.object, right: builtins.object, op: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...

def binom_init(N: builtins.object, K: builtins.object) -> _SageObject: ...

def set_to_index(S: builtins.object) -> _SageObject: ...

def index_to_set(S: builtins.object, index: builtins.object, k: builtins.object, n: builtins.object) -> _SageObject: ...
