from sage.structure.element import Element

class BasisMatroid(BasisExchangeMatroid):
    def _repr_(self) -> str: ...
    def dual(self) -> Element: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def truncation(self) -> Element: ...
    def _extension(self, e: Element, H: Element | int | str | bool | None) -> Element: ...
    def _with_coloop(self, e: Element) -> Element: ...
    def relabel(self, mapping: Element | int | str | bool | None) -> Element: ...
    def bases_count(self) -> Element: ...
    def _is_relaxation(self, other: Element, morphism: Element | int | str | bool | None) -> Element: ...
    def _is_isomorphism(self, other: Element, morphism: Element | int | str | bool | None) -> Element: ...
    def _isomorphism(self, other: Element) -> Element: ...
    def _is_isomorphic(self, other: Element, certificate: Element | int | str | bool | None) -> Element: ...

class BasisExchangeMatroid: ...
