# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ChowRing:
    def __init__(self, R: builtins.int, M: builtins.int, augmented: builtins.object, presentation: builtins.object = ...) -> None: ...
    def matroid(self) -> _SageObject: ...
    def basis(self) -> _SageObject: ...
    def lefschetz_element(self) -> _SageObject: ...
    def poincare_pairing(self, el1: builtins.object, el2: builtins.object) -> _SageObject: ...
    def graded_character(self, G: builtins.object = ...) -> _SageObject: ...
    class Element:
        def to_vector(self, order: builtins.object = ...) -> _SageObject: ...
        def monomial_coefficients(self, copy: builtins.bool = ...) -> _SageObject: ...
        def degree(self) -> _SageObject: ...
        def homogeneous_degree(self) -> _SageObject: ...
