from sage.structure.element import Element

class ChowRingIdeal(MPolynomialIdeal):
    def matroid(self) -> Element: ...
    def _lattice_flats(self) -> tuple[Element, ...]: ...
    def flats_to_generator_dict(self) -> dict[Element, Element]: ...
    def _construct_ambient_poly_ring(self, names: str, flats_groundset_el: Element | int | str | bool | None) -> Element: ...

class ChowRingIdeal_nonaug_fy(ChowRingIdeal):
    def _gens_constructor(self, poly_ring: Element | int | str | bool | None) -> list[Element]: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def groebner_basis(self, algorithm: str) -> Element: ...
    def normal_basis(self, algorithm: str) -> Element: ...

class ChowRingIdeal_nonaug_af(ChowRingIdeal):
    def _gens_constructor(self, poly_ring: Element | int | str | bool | None) -> Element: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def groebner_basis(self, algorithm: str) -> Element: ...
    def normal_basis(self, algorithm: str) -> Element: ...

class ChowRingIdeal_nonaug_sp(ChowRingIdeal):
    def _gens_constructor(self, poly_ring: Element | int | str | bool | None) -> Element: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def groebner_basis(self, algorithm: str) -> Element: ...
    def normal_basis(self, algorithm: str) -> Element: ...

class AugmentedChowRingIdeal_fy(ChowRingIdeal):
    def _gens_constructor(self, poly_ring: Element | int | str | bool | None) -> list[Element]: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def groebner_basis(self, algorithm: str) -> Element: ...
    def normal_basis(self, algorithm: str) -> Element: ...

class AugmentedChowRingIdeal_atom_free(ChowRingIdeal):
    def _gens_constructor(self, poly_ring: Element | int | str | bool | None) -> list[Element]: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def groebner_basis(self, algorithm: str) -> Element: ...
    def normal_basis(self, algorithm: str) -> Element: ...

class MPolynomialIdeal: ...
