# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ChowRingIdeal:
    def matroid(self) -> _SageObject: ...
    def flats_to_generator_dict(self) -> builtins.dict[_SageObject, _SageObject]: ...

class ChowRingIdeal_nonaug_fy:
    def __init__(self, M: builtins.int, R: builtins.int) -> None: ...
    def groebner_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def normal_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...

class ChowRingIdeal_nonaug_af:
    def __init__(self, M: builtins.int, R: builtins.int) -> None: ...
    def groebner_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def normal_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...

class ChowRingIdeal_nonaug_sp:
    def __init__(self, M: builtins.int, R: builtins.int) -> None: ...
    def groebner_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def normal_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...

class AugmentedChowRingIdeal_fy:
    def __init__(self, M: builtins.int, R: builtins.int) -> None: ...
    def groebner_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def normal_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...

class AugmentedChowRingIdeal_atom_free:
    def __init__(self, M: builtins.int, R: builtins.int) -> None: ...
    def groebner_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
    def normal_basis(self, algorithm: builtins.str = ..., *args: builtins.object, **kwargs: builtins.object) -> _SageObject: ...
