# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CircuitsMatroid:
    def __init__(self, M: builtins.object = ..., groundset: builtins.object = ..., circuits: builtins.object = ..., nsc_defined: builtins.object = ...) -> None: ...
    def groundset(self) -> _SageObject: ...
    def full_rank(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(left: builtins.object, right: builtins.object, op: builtins.object) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def relabel(self, mapping: builtins.object) -> _SageObject: ...
    def bases_iterator(self) -> _SageObject: ...
    def independent_sets(self, k: builtins.object = ...) -> _SageObject: ...
    def dependent_sets(self, k: builtins.object) -> _SageObject: ...
    def circuits(self, k: builtins.object = ...) -> _SageObject: ...
    def circuits_iterator(self, k: builtins.object = ...) -> _SageObject: ...
    def nonspanning_circuits(self) -> _SageObject: ...
    def nonspanning_circuits_iterator(self) -> _SageObject: ...
    def no_broken_circuits_facets(self, ordering: builtins.object = ..., reduced: builtins.object = ...) -> _SageObject: ...
    def no_broken_circuits_sets(self, ordering: builtins.object = ..., reduced: builtins.object = ...) -> _SageObject: ...
    def broken_circuit_complex(self, ordering: builtins.object = ..., reduced: builtins.object = ...) -> _SageObject: ...
    def girth(self) -> _SageObject: ...
    def is_paving(self) -> builtins.bool: ...
    def is_valid(self, certificate: builtins.object = ...) -> builtins.bool: ...
