# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def U24(groundset: builtins.str = ...) -> _SageObject: ...

def U25(groundset: builtins.str = ...) -> _SageObject: ...

def U35(groundset: builtins.str = ...) -> _SageObject: ...

def K4(groundset: builtins.str = ...) -> _SageObject: ...

def Whirl3(groundset: builtins.str = ...) -> _SageObject: ...

def Q6(groundset: builtins.str = ...) -> _SageObject: ...

def P6(groundset: builtins.object = ...) -> _SageObject: ...

def U36(groundset: builtins.str = ...) -> _SageObject: ...

def R6(groundset: builtins.str = ...) -> _SageObject: ...

def Fano(groundset: builtins.str = ...) -> _SageObject: ...

def FanoDual(groundset: builtins.str = ...) -> _SageObject: ...

def NonFano(groundset: builtins.str = ...) -> _SageObject: ...

def NonFanoDual(groundset: builtins.str = ...) -> _SageObject: ...

def O7(groundset: builtins.str = ...) -> _SageObject: ...

def P7(groundset: builtins.str = ...) -> _SageObject: ...

def AG32(groundset: builtins.str = ...) -> _SageObject: ...

def AG32prime(groundset: builtins.object = ...) -> _SageObject: ...

def R8(groundset: builtins.str = ...) -> _SageObject: ...

def F8(groundset: builtins.object = ...) -> _SageObject: ...

def Q8(groundset: builtins.object = ...) -> _SageObject: ...

def L8(groundset: builtins.object = ...) -> _SageObject: ...

def S8(groundset: builtins.str = ...) -> _SageObject: ...

def Vamos(groundset: builtins.object = ...) -> _SageObject: ...

def T8(groundset: builtins.str = ...) -> _SageObject: ...

def J(groundset: builtins.str = ...) -> _SageObject: ...

def P8(groundset: builtins.str = ...) -> _SageObject: ...

def P8pp(groundset: builtins.object = ...) -> _SageObject: ...

def Wheel4(groundset: builtins.str = ...) -> _SageObject: ...

def Whirl4(groundset: builtins.str = ...) -> _SageObject: ...

def K33dual(groundset: builtins.str = ...) -> _SageObject: ...

def K33(groundset: builtins.str = ...) -> _SageObject: ...

def AG23(groundset: builtins.str = ...) -> _SageObject: ...

def TernaryDowling3(groundset: builtins.str = ...) -> _SageObject: ...

def R9(groundset: builtins.object = ...) -> _SageObject: ...

def Pappus(groundset: builtins.object = ...) -> _SageObject: ...

def NonPappus(groundset: builtins.object = ...) -> _SageObject: ...

def K5(groundset: builtins.str = ...) -> _SageObject: ...

def K5dual(groundset: builtins.str = ...) -> _SageObject: ...

def R10(groundset: builtins.str = ...) -> _SageObject: ...

def NonDesargues(groundset: builtins.object = ...) -> _SageObject: ...

def R12(groundset: builtins.str = ...) -> _SageObject: ...

def ExtendedTernaryGolayCode(groundset: builtins.str = ...) -> _SageObject: ...

def T12(groundset: builtins.str = ...) -> _SageObject: ...

def PG23(groundset: builtins.object = ...) -> _SageObject: ...

def Wheel(r: builtins.int, field: builtins.object = ..., ring: builtins.object = ..., groundset: builtins.object = ...) -> _SageObject: ...

def Whirl(r: builtins.int, groundset: builtins.object = ...) -> _SageObject: ...

def Uniform(r: builtins.int, n: builtins.int, groundset: builtins.object = ...) -> _SageObject: ...

def PG(n: builtins.int, q: builtins.int, x: builtins.object = ..., groundset: builtins.object = ...) -> _SageObject: ...

def AG(n: builtins.int, q: builtins.int, x: builtins.object = ..., groundset: builtins.object = ...) -> _SageObject: ...

def Z(r: builtins.int, t: builtins.bool = ..., groundset: builtins.object = ...) -> _SageObject: ...

def Spike(r: builtins.int, t: builtins.bool = ..., C3: builtins.list[_SageObject] = ..., groundset: builtins.object = ...) -> _SageObject: ...

def Theta(n: builtins.int, groundset: builtins.object = ...) -> _SageObject: ...

def Psi(r: builtins.int, groundset: builtins.object = ...) -> _SageObject: ...

def RelaxedNonFano(groundset: builtins.object = ...) -> _SageObject: ...

def TippedFree3spike(groundset: builtins.object = ...) -> _SageObject: ...

def AG23minusDY(groundset: builtins.object = ...) -> _SageObject: ...

def TQ8(groundset: builtins.object = ...) -> _SageObject: ...

def P8p(groundset: builtins.object = ...) -> _SageObject: ...

def KP8(groundset: builtins.object = ...) -> _SageObject: ...

def Sp8(groundset: builtins.object = ...) -> _SageObject: ...

def Sp8pp(groundset: builtins.object = ...) -> _SageObject: ...

def LP8(groundset: builtins.object = ...) -> _SageObject: ...

def WQ8(groundset: builtins.object = ...) -> _SageObject: ...

def BB9(groundset: builtins.object = ...) -> _SageObject: ...

def TQ9(groundset: builtins.object = ...) -> _SageObject: ...

def TQ9p(groundset: builtins.object = ...) -> _SageObject: ...

def M8591(groundset: builtins.object = ...) -> _SageObject: ...

def PP9(groundset: builtins.object = ...) -> _SageObject: ...

def BB9gDY(groundset: builtins.object = ...) -> _SageObject: ...

def A9(groundset: builtins.object = ...) -> _SageObject: ...

def FN9(groundset: builtins.object = ...) -> _SageObject: ...

def FX9(groundset: builtins.object = ...) -> _SageObject: ...

def KR9(groundset: builtins.object = ...) -> _SageObject: ...

def KQ9(groundset: builtins.object = ...) -> _SageObject: ...

def UG10(groundset: builtins.object = ...) -> _SageObject: ...

def FF10(groundset: builtins.object = ...) -> _SageObject: ...

def GP10(groundset: builtins.object = ...) -> _SageObject: ...

def FZ10(groundset: builtins.object = ...) -> _SageObject: ...

def UQ10(groundset: builtins.object = ...) -> _SageObject: ...

def FP10(groundset: builtins.object = ...) -> _SageObject: ...

def TQ10(groundset: builtins.object = ...) -> _SageObject: ...

def FY10(groundset: builtins.object = ...) -> _SageObject: ...

def PP10(groundset: builtins.object = ...) -> _SageObject: ...

def FU10(groundset: builtins.object = ...) -> _SageObject: ...

def D10(groundset: builtins.object = ...) -> _SageObject: ...

def UK10(groundset: builtins.object = ...) -> _SageObject: ...

def PK10(groundset: builtins.object = ...) -> _SageObject: ...

def GK10(groundset: builtins.object = ...) -> _SageObject: ...

def FT10(groundset: builtins.object = ...) -> _SageObject: ...

def TK10(groundset: builtins.object = ...) -> _SageObject: ...

def KT10(groundset: builtins.object = ...) -> _SageObject: ...

def TU10(groundset: builtins.object = ...) -> _SageObject: ...

def UT10(groundset: builtins.object = ...) -> _SageObject: ...

def FK10(groundset: builtins.object = ...) -> _SageObject: ...

def KF10(groundset: builtins.object = ...) -> _SageObject: ...

def FA11(groundset: builtins.object = ...) -> _SageObject: ...

def FR12(groundset: builtins.object = ...) -> _SageObject: ...

def GP12(groundset: builtins.object = ...) -> _SageObject: ...

def FQ12(groundset: builtins.object = ...) -> _SageObject: ...

def FF12(groundset: builtins.object = ...) -> _SageObject: ...

def FZ12(groundset: builtins.object = ...) -> _SageObject: ...

def UQ12(groundset: builtins.object = ...) -> _SageObject: ...

def FP12(groundset: builtins.object = ...) -> _SageObject: ...

def FS12(groundset: builtins.object = ...) -> _SageObject: ...

def UK12(groundset: builtins.object = ...) -> _SageObject: ...

def UA12(groundset: builtins.object = ...) -> _SageObject: ...

def AK12(groundset: builtins.object = ...) -> _SageObject: ...

def FK12(groundset: builtins.object = ...) -> _SageObject: ...

def KB12(groundset: builtins.object = ...) -> _SageObject: ...

def AF12(groundset: builtins.object = ...) -> _SageObject: ...

def NestOfTwistedCubes(groundset: builtins.object = ...) -> _SageObject: ...

def XY13(groundset: builtins.object = ...) -> _SageObject: ...

def N3(groundset: builtins.object = ...) -> _SageObject: ...

def N3pp(groundset: builtins.object = ...) -> _SageObject: ...

def UP14(groundset: builtins.object = ...) -> _SageObject: ...

def VP14(groundset: builtins.object = ...) -> _SageObject: ...

def FV14(groundset: builtins.object = ...) -> _SageObject: ...

def OW14(groundset: builtins.object = ...) -> _SageObject: ...

def FM14(groundset: builtins.object = ...) -> _SageObject: ...

def FA15(groundset: builtins.object = ...) -> _SageObject: ...

def N4(groundset: builtins.object = ...) -> _SageObject: ...

def NonVamos(groundset: builtins.object = ...) -> _SageObject: ...

def NotP8(groundset: builtins.str = ...) -> _SageObject: ...

def AG23minus(groundset: builtins.object = ...) -> _SageObject: ...

def P9(groundset: builtins.str = ...) -> _SageObject: ...

def R9A(groundset: builtins.object = ...) -> _SageObject: ...

def R9B(groundset: builtins.object = ...) -> _SageObject: ...

def Block_9_4(groundset: builtins.object = ...) -> _SageObject: ...

def TicTacToe(groundset: builtins.object = ...) -> _SageObject: ...

def N1(groundset: builtins.str = ...) -> _SageObject: ...

def Block_10_5(groundset: builtins.object = ...) -> _SageObject: ...

def Q10(groundset: builtins.str = ...) -> _SageObject: ...

def BetsyRoss(groundset: builtins.object = ...) -> _SageObject: ...

def N2(groundset: builtins.str = ...) -> _SageObject: ...

def D16(groundset: builtins.str = ...) -> _SageObject: ...

def Terrahawk(groundset: builtins.str = ...) -> _SageObject: ...

def ExtendedBinaryGolayCode(groundset: builtins.str = ...) -> _SageObject: ...

def CompleteGraphic(n: builtins.int, groundset: builtins.object = ...) -> _SageObject: ...
