# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def AllMatroids(n: builtins.int, r: builtins.int = ..., type: builtins.str = ...) -> _SageObject: ...

def OxleyMatroids() -> _SageObject: ...

def BrettellMatroids() -> _SageObject: ...

def VariousMatroids() -> _SageObject: ...
