# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class CutNode:
    def __cinit__(self, MC: builtins.object, N: builtins.object = ...) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def copy(self) -> _SageObject: ...
    def insert_plane(self, p0: builtins.object) -> _SageObject: ...
    def remove_plane(self, p0: builtins.object) -> _SageObject: ...
    def select_plane(self) -> _SageObject: ...
    def planes(self) -> _SageObject: ...

class LinearSubclassesIter:
    def __init__(self, MC: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...

class LinearSubclasses:
    def __init__(self, M: builtins.object, line_length: builtins.object = ..., subsets: builtins.object = ..., splice: builtins.object = ...) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __getitem__(self, node: builtins.object) -> _SageObject: ...

class MatroidExtensions:
    def __init__(self, M: builtins.object, e: builtins.object, line_length: builtins.object = ..., subsets: builtins.object = ..., splice: builtins.object = ..., orderly: builtins.object = ...) -> None: ...
    def __getitem__(self, node: builtins.object) -> _SageObject: ...
