# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Gammoid:
    def __init__(self, D: builtins.object, roots: builtins.object, groundset: builtins.object = ...) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def digraph(self) -> _SageObject: ...
    def digraph_plot(self) -> _SageObject: ...
    def groundset(self) -> _SageObject: ...
    def gammoid_extension(self, vertex: builtins.object, neighbors: builtins.list[_SageObject] = ...) -> _SageObject: ...
    def gammoid_extensions(self, vertices: builtins.object = ...) -> _SageObject: ...
