from sage.structure.element import Element

class GraphicMatroid(Matroid):
    def _repr_(self) -> str: ...
    def _vertex_stars(self) -> Element: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def _has_minor(self, N: Element | int | str | bool | None, certificate: Element | int | str | bool | None) -> Element: ...
    def _is_isomorphic(self, other: Element, certificate: Element | int | str | bool | None) -> Element: ...
    def _isomorphism(self, other: Element) -> Element: ...
    def is_valid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def graph(self) -> Element: ...
    def vertex_map(self) -> Element: ...
    def _groundset_to_edges(self, X: Element | int | str | bool | None) -> Element: ...
    def subgraph_from_set(self, X: Element | int | str | bool | None) -> Element: ...
    def _subgraph_from_set(self, X: Element | int | str | bool | None) -> Element: ...
    def graphic_extension(self, u: Element | int | str | bool | None, v: Element, element: Element | int | str | bool | None) -> Element: ...
    def graphic_extensions(self, element: Element | int | str | bool | None, vertices: Element | int | str | bool | None, simple: Element | int | str | bool | None) -> Element: ...
    def graphic_coextension(self, u: Element | int | str | bool | None, v: Element, X: Element | int | str | bool | None, element: Element | int | str | bool | None) -> Element: ...
    def graphic_coextensions(self, vertices: Element | int | str | bool | None, v: Element, element: Element | int | str | bool | None, cosimple: Element | int | str | bool | None) -> Element: ...
    def twist(self, X: Element | int | str | bool | None) -> Element: ...
    def one_sum(self, X: Element | int | str | bool | None, u: Element | int | str | bool | None, v: Element) -> Element: ...
    def regular_matroid(self) -> Element: ...
    def relabel(self, mapping: Element | int | str | bool | None) -> Element: ...

class Matroid: ...
