from sage.rings.integer import Integer
from sage.structure.element import Element

class LeanMatrix:
    def _matrix_(self) -> Element: ...
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...

class GenericMatrix(LeanMatrix):
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...

class BinaryMatrix(LeanMatrix):
    def _matrix_(self) -> Element: ...
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...

class TernaryMatrix(LeanMatrix):
    def _matrix_(self) -> Element: ...
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...

class QuaternaryMatrix(LeanMatrix):
    def _matrix_(self) -> Element: ...
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...

class PlusMinusOneMatrix(LeanMatrix):
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...

class RationalMatrix(LeanMatrix):
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...
