# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def gauss_jordan_reduce(A: builtins.object, columns: builtins.object) -> _SageObject: ...

def characteristic(A: builtins.object) -> _SageObject: ...

class LinearMatroid:
    def __init__(self, matrix: builtins.object = ..., groundset: builtins.object = ..., reduced_matrix: builtins.object = ..., ring: builtins.object = ..., keep_initial_representation: builtins.object = ...) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def representation(self, B: builtins.object = ..., reduced: builtins.object = ..., labels: builtins.object = ..., order: builtins.object = ..., lift_map: builtins.object = ...) -> _SageObject: ...
    def representation_vectors(self) -> _SageObject: ...
    def is_field_equivalent(self, other: builtins.object) -> builtins.bool: ...
    def is_field_isomorphism(self, other: builtins.object, morphism: builtins.object) -> builtins.bool: ...
    def is_field_isomorphic(self, other: builtins.object) -> builtins.bool: ...
    def __richcmp__(left: builtins.object, right: builtins.object, op: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def dual(self) -> _SageObject: ...
    def has_line_minor(self, k: builtins.object, hyperlines: builtins.object = ..., certificate: builtins.object = ...) -> builtins.bool: ...
    def has_field_minor(self, N: builtins.object) -> builtins.bool: ...
    def fundamental_cycle(self, B: builtins.object, e: builtins.object) -> _SageObject: ...
    def fundamental_cocycle(self, B: builtins.object, e: builtins.object) -> _SageObject: ...
    def cross_ratios(self, hyperlines: builtins.object = ...) -> _SageObject: ...
    def cross_ratio(self, F: builtins.object, a: builtins.object, b: builtins.object, c: builtins.object, d: builtins.object) -> _SageObject: ...
    def linear_extension(self, element: builtins.object, chain: builtins.object = ..., col: builtins.object = ...) -> _SageObject: ...
    def linear_coextension(self, element: builtins.object, cochain: builtins.object = ..., row: builtins.object = ...) -> _SageObject: ...
    def linear_extension_chains(self, F: builtins.object = ..., simple: builtins.object = ..., fundamentals: builtins.object = ...) -> _SageObject: ...
    def linear_coextension_cochains(self, F: builtins.object = ..., cosimple: builtins.object = ..., fundamentals: builtins.object = ...) -> _SageObject: ...
    def linear_extensions(self, element: builtins.object = ..., F: builtins.object = ..., simple: builtins.object = ..., fundamentals: builtins.object = ...) -> _SageObject: ...
    def linear_coextensions(self, element: builtins.object = ..., F: builtins.object = ..., cosimple: builtins.object = ..., fundamentals: builtins.object = ...) -> _SageObject: ...
    def is_valid(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def orlik_terao_algebra(self, R: builtins.object = ..., ordering: builtins.object = ..., **kwargs: builtins.object) -> _SageObject: ...
    def line_flats(self) -> _SageObject: ...
    def zonotopal_algebra(self, k: builtins.object, lines: builtins.object = ..., base_ring: builtins.object = ...) -> _SageObject: ...
    def central_zonotopal_algebra(self, base_ring: builtins.object = ...) -> _SageObject: ...
    def internal_zonotopal_algebra(self, base_ring: builtins.object = ...) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def relabel(self, mapping: builtins.object) -> _SageObject: ...

class BinaryMatroid:
    def __init__(self, matrix: builtins.object = ..., groundset: builtins.object = ..., reduced_matrix: builtins.object = ..., ring: builtins.object = ..., keep_initial_representation: builtins.object = ..., basis: builtins.object = ...) -> None: ...
    def base_ring(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def bicycle_dimension(self) -> _SageObject: ...
    def brown_invariant(self) -> _SageObject: ...
    def is_graphic(self) -> builtins.bool: ...
    def is_valid(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def binary_matroid(self, randomized_tests: builtins.object = ..., verify: builtins.object = ...) -> _SageObject: ...
    def is_binary(self, randomized_tests: builtins.object = ...) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def relabel(self, mapping: builtins.object) -> _SageObject: ...

class TernaryMatroid:
    def __init__(self, matrix: builtins.object = ..., groundset: builtins.object = ..., reduced_matrix: builtins.object = ..., ring: builtins.object = ..., keep_initial_representation: builtins.object = ..., basis: builtins.object = ...) -> None: ...
    def base_ring(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def bicycle_dimension(self) -> _SageObject: ...
    def character(self) -> _SageObject: ...
    def is_valid(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def ternary_matroid(self, randomized_tests: builtins.object = ..., verify: builtins.object = ...) -> _SageObject: ...
    def is_ternary(self, randomized_tests: builtins.object = ...) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def relabel(self, mapping: builtins.object) -> _SageObject: ...

class QuaternaryMatroid:
    def __init__(self, matrix: builtins.object = ..., groundset: builtins.object = ..., reduced_matrix: builtins.object = ..., ring: builtins.object = ..., keep_initial_representation: builtins.object = ..., basis: builtins.object = ...) -> None: ...
    def base_ring(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def bicycle_dimension(self) -> _SageObject: ...
    def is_valid(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def relabel(self, mapping: builtins.object) -> _SageObject: ...

class RegularMatroid:
    def __init__(self, matrix: builtins.object = ..., groundset: builtins.object = ..., reduced_matrix: builtins.object = ..., ring: builtins.object = ..., keep_initial_representation: builtins.object = ...) -> None: ...
    def base_ring(self) -> _SageObject: ...
    def characteristic(self) -> _SageObject: ...
    def bases_count(self) -> _SageObject: ...
    def has_line_minor(self, k: builtins.object, hyperlines: builtins.object = ..., certificate: builtins.object = ...) -> builtins.bool: ...
    def is_graphic(self) -> builtins.bool: ...
    def is_valid(self, certificate: builtins.object = ...) -> builtins.bool: ...
    def is_regular(self) -> builtins.bool: ...
    def binary_matroid(self, randomized_tests: builtins.object = ..., verify: builtins.object = ...) -> _SageObject: ...
    def is_binary(self, randomized_tests: builtins.object = ...) -> builtins.bool: ...
    def ternary_matroid(self, randomized_tests: builtins.object = ..., verify: builtins.object = ...) -> _SageObject: ...
    def is_ternary(self, randomized_tests: builtins.object = ...) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def relabel(self, mapping: builtins.object) -> _SageObject: ...
