from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.structure.element import Element

class LinearMatroid(BasisExchangeMatroid):
    def _forget(self) -> Element: ...
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...
    def _matrix_(self) -> Element: ...
    def _repr_(self) -> str: ...
    def representation(self, B: Element | int | str | bool | None, reduced: Element | int | str | bool | None, labels: Element | int | str | bool | None, order: Element | int | str | bool | None, lift_map: Element | int | str | bool | None) -> Element: ...
    def _current_rows_cols(self, B: Element | int | str | bool | None) -> Element: ...
    def representation_vectors(self) -> Element: ...
    def is_field_equivalent(self, other: Element) -> bool: ...
    def is_field_isomorphism(self, other: Element, morphism: Element | int | str | bool | None) -> bool: ...
    def _fast_isom_test(self, other: Element) -> Element: ...
    def is_field_isomorphic(self, other: Element) -> bool: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def dual(self) -> Element: ...
    def has_line_minor(self, k: int, hyperlines: Element | int | str | bool | None, certificate: Element | int | str | bool | None) -> bool: ...
    def has_field_minor(self, N: Element | int | str | bool | None) -> bool: ...
    def _exchange_value(self, e: Element, f: Element) -> Element: ...
    def fundamental_cycle(self, B: Element | int | str | bool | None, e: Element) -> Element: ...
    def fundamental_cocycle(self, B: Element | int | str | bool | None, e: Element) -> Element: ...
    def _line_ratios(self, F: Ring) -> Element: ...
    def _line_length(self, F: Ring) -> Element: ...
    def _line_cross_ratios(self, F: Ring) -> Element: ...
    def cross_ratios(self, hyperlines: Element | int | str | bool | None) -> Element: ...
    def cross_ratio(self, F: Ring, a: Element, b: Element, c: Element, d: int) -> Element: ...
    def _line_cross_ratio_test(self, F: Ring, x: Element, fundamentals: Element | int | str | bool | None) -> Element: ...
    def _cross_ratio_test(self, x: Element, fundamentals: Element | int | str | bool | None, hyperlines: Element | int | str | bool | None) -> Element: ...
    def linear_extension(self, element: Element | int | str | bool | None, chain: Element | int | str | bool | None, col: Element | int | str | bool | None) -> Element: ...
    def linear_coextension(self, element: Element | int | str | bool | None, cochain: Element | int | str | bool | None, row: Element | int | str | bool | None) -> Element: ...
    def _linear_extensions(self, element: Element | int | str | bool | None, chains: Element | int | str | bool | None) -> Element: ...
    def _linear_coextensions(self, element: Element | int | str | bool | None, cochains: Element | int | str | bool | None) -> Element: ...
    def linear_extension_chains(self, F: Ring, simple: Element | int | str | bool | None, fundamentals: Element | int | str | bool | None) -> Element: ...
    def linear_coextension_cochains(self, F: Ring, cosimple: Element | int | str | bool | None, fundamentals: Element | int | str | bool | None) -> Element: ...
    def linear_extensions(self, element: Element | int | str | bool | None, F: Ring, simple: Element | int | str | bool | None, fundamentals: Element | int | str | bool | None) -> Element: ...
    def linear_coextensions(self, element: Element | int | str | bool | None, F: Ring, cosimple: Element | int | str | bool | None, fundamentals: Element | int | str | bool | None) -> Element: ...
    def is_valid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def _is_3connected_shifting(self, certificate: Element | int | str | bool | None) -> Element: ...
    def _is_4connected_shifting(self, certificate: Element | int | str | bool | None) -> Element: ...
    def orlik_terao_algebra(self, R: Ring, ordering: Element | int | str | bool | None, **kwargs: Element | int | str | bool | None) -> Element: ...
    def zonotopal_algebra(self, k: int, lines: Element | int | str | bool | None, base_ring: Ring) -> Element: ...
    def central_zonotopal_algebra(self, base_ring: Ring) -> Element: ...
    def internal_zonotopal_algebra(self, base_ring: Ring) -> Element: ...
    def relabel(self, mapping: Element | int | str | bool | None) -> Element: ...

class BinaryMatroid(LinearMatroid):
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...
    def _repr_(self) -> str: ...
    def _current_rows_cols(self, B: Element | int | str | bool | None) -> Element: ...
    def _is_isomorphic(self, other: Element, certificate: Element | int | str | bool | None) -> Element: ...
    def _is_isomorphism(self, other: Element, morphism: Element | int | str | bool | None) -> Element: ...
    def _make_invariant(self) -> Element: ...
    def _invariant(self) -> Element: ...
    def bicycle_dimension(self) -> Element: ...
    def brown_invariant(self) -> Element: ...
    def _principal_tripartition(self) -> Element: ...
    def _fast_isom_test(self, other: Element) -> Element: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def is_valid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def binary_matroid(self, randomized_tests: Element | int | str | bool | None, verify: Element | int | str | bool | None) -> Element: ...
    def is_binary(self, randomized_tests: Element | int | str | bool | None) -> bool: ...
    def relabel(self, mapping: Element | int | str | bool | None) -> Element: ...

class TernaryMatroid(LinearMatroid):
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...
    def _repr_(self) -> str: ...
    def _current_rows_cols(self, B: Element | int | str | bool | None) -> Element: ...
    def _is_isomorphic(self, other: Element, certificate: Element | int | str | bool | None) -> Element: ...
    def _make_invariant(self) -> Element: ...
    def _invariant(self) -> Element: ...
    def bicycle_dimension(self) -> Element: ...
    def character(self) -> Element: ...
    def _principal_quadripartition(self) -> Element: ...
    def _fast_isom_test(self, other: Element) -> Element: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def is_valid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def ternary_matroid(self, randomized_tests: Element | int | str | bool | None, verify: Element | int | str | bool | None) -> Element: ...
    def is_ternary(self, randomized_tests: Element | int | str | bool | None) -> bool: ...
    def relabel(self, mapping: Element | int | str | bool | None) -> Element: ...

class QuaternaryMatroid(LinearMatroid):
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...
    def _repr_(self) -> str: ...
    def _current_rows_cols(self, B: Element | int | str | bool | None) -> Element: ...
    def _make_invariant(self) -> Element: ...
    def _invariant(self) -> Element: ...
    def bicycle_dimension(self) -> Element: ...
    def _principal_tripartition(self) -> Element: ...
    def _fast_isom_test(self, other: Element) -> Element: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def is_valid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def relabel(self, mapping: Element | int | str | bool | None) -> Element: ...

class RegularMatroid(LinearMatroid):
    def base_ring(self) -> Element: ...
    def characteristic(self) -> Integer: ...
    def _repr_(self) -> str: ...
    def bases_count(self) -> Element: ...
    def _projection(self) -> Element: ...
    def _invariant(self) -> Element: ...
    def _hypergraph(self) -> Element: ...
    def _is_isomorphic(self, other: Element, certificate: Element | int | str | bool | None) -> Element: ...
    def _fast_isom_test(self, other: Element) -> Element: ...
    def has_line_minor(self, k: int, hyperlines: Element | int | str | bool | None, certificate: Element | int | str | bool | None) -> bool: ...
    def _linear_extension_chains(self, F: Ring, fundamentals: Element | int | str | bool | None) -> Element: ...
    def is_valid(self, certificate: Element | int | str | bool | None) -> bool: ...
    def binary_matroid(self, randomized_tests: Element | int | str | bool | None, verify: Element | int | str | bool | None) -> Element: ...
    def is_binary(self, randomized_tests: Element | int | str | bool | None) -> bool: ...
    def ternary_matroid(self, randomized_tests: Element | int | str | bool | None, verify: Element | int | str | bool | None) -> Element: ...
    def is_ternary(self, randomized_tests: Element | int | str | bool | None) -> bool: ...
    def relabel(self, mapping: Element | int | str | bool | None) -> Element: ...

class BasisExchangeMatroid: ...
