from sage.structure.element import Element
from sage.structure.parent import Parent

def it(M: Element | int | str | bool | None, B1: Element | int | str | bool | None, nB1: Element | int | str | bool | None, lps: Element | int | str | bool | None) -> tuple[dict[Element, Element], list[Element], list[Element], list[Element]]: ...
def trigrid(tripts: Element | int | str | bool | None) -> list[list[Element]]: ...
def addnontripts(tripts_labels: Element | int | str | bool | None, nontripts_labels: Element | int | str | bool | None, ptsdict: Element | int | str | bool | None) -> dict[Element, Element]: ...
def createline(ptsdict: Element | int | str | bool | None, ll: Element | int | str | bool | None, lineorders2: Element | int | str | bool | None) -> tuple[list[Element], list[Element], list[Element], list[Element]]: ...
def slp(M1: Element | int | str | bool | None, pos_dict: Element | int | str | bool | None, B: Element | int | str | bool | None) -> tuple[Element, ...]: ...
def addlp(M: Element | int | str | bool | None, M1: Element | int | str | bool | None, L: Element | int | str | bool | None, P: Parent, ptsdict: Element | int | str | bool | None, G: Element | int | str | bool | None, limits: Element | int | str | bool | None) -> tuple[Element, ...]: ...
def line_hasorder(l: Element | int | str | bool | None, lodrs: Element | int | str | bool | None) -> tuple[bool, list[Element]]: ...
def lineorders_union(lineorders1: Element | int | str | bool | None, lineorders2: Element | int | str | bool | None) -> list[Element]: ...
def posdict_is_sane(M1: Element | int | str | bool | None, pos_dict: Element | int | str | bool | None) -> bool: ...
def tracklims(lims: Element | int | str | bool | None, x_i: Element | int | str | bool | None, y_i: Element | int | str | bool | None) -> list[Element]: ...
def geomrep(M1: Element | int | str | bool | None, B1: Element | int | str | bool | None, lineorders1: Element | int | str | bool | None, pd: Element | int | str | bool | None, sp: Element | int | str | bool | None) -> Element: ...
