# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MinorMatroid:
    def __init__(self, matroid: builtins.object, contractions: builtins.object = ..., deletions: builtins.object = ...) -> None: ...
    def groundset(self) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
