from sage.structure.element import Element

class MinorMatroid(Matroid):
    def groundset(self) -> Element: ...
    def _rank(self, X: Element | int | str | bool | None) -> Element: ...
    def _corank(self, X: Element | int | str | bool | None) -> Element: ...
    def _max_independent(self, X: Element | int | str | bool | None) -> Element: ...
    def _closure(self, X: Element | int | str | bool | None) -> Element: ...
    def _max_coindependent(self, X: Element | int | str | bool | None) -> Element: ...
    def _coclosure(self, X: Element | int | str | bool | None) -> Element: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def _repr_(self) -> str: ...

class Matroid: ...
