from sage.structure.element import Element

class RankMatroid(Matroid):
    def groundset(self) -> Element: ...
    def _rank(self, X: Element | int | str | bool | None) -> Element: ...

class Matroid: ...
