from sage.structure.element import Element
from sage.structure.parent import Parent

class SetSystem:
    def _complements(self) -> Element: ...
    def _get_groundset(self) -> Element: ...
    def is_connected(self) -> bool: ...
    def _equitable_partition(self, P: Parent, EP: Element | int | str | bool | None) -> Element: ...
    def _heuristic_partition(self, P: Parent, EP: Element | int | str | bool | None) -> Element: ...
    def _isomorphism(self, other: Element, SP: Element | int | str | bool | None, OP: Element | int | str | bool | None) -> Element: ...
    def _equivalence(self, is_equiv: Element | int | str | bool | None, other: Element, SP: Element | int | str | bool | None, OP: Element | int | str | bool | None) -> Element: ...

class SetSystemIterator:
    ...
