# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SetSystem:
    def __cinit__(self, groundset: builtins.object, subsets: builtins.object = ..., capacity: builtins.object = ...) -> _SageObject: ...
    def __init__(self, groundset: builtins.object, subsets: builtins.object = ..., capacity: builtins.object = ...) -> None: ...
    def __dealloc__(self) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __getitem__(self, k: builtins.object) -> _SageObject: ...
    def copy(self) -> _SageObject: ...
    def resize(self, k: builtins.object = ...) -> _SageObject: ...
    def append(self, X: builtins.object) -> _SageObject: ...
    def subset(self, k: builtins.object) -> _SageObject: ...
    def is_connected(self) -> builtins.bool: ...
    def subset_characteristic(self, P: builtins.object, e: builtins.object) -> _SageObject: ...
    def subsets_partition(self, P: builtins.object = ..., E: builtins.object = ...) -> _SageObject: ...
    def initial_partition(self, P: builtins.object = ..., E: builtins.object = ...) -> _SageObject: ...

class SetSystemIterator:
    def __init__(self, H: builtins.object) -> None: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
    def __next__(self) -> _SageObject: ...
