from sage.structure.element import Element

class TransversalMatroid(BasisExchangeMatroid):
    def _repr_(self) -> str: ...
    def graph(self) -> Element: ...
    def _minor(self, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
    def set_labels(self) -> Element: ...
    def reduce_presentation(self) -> Element: ...
    def transversal_extension(self, element: Element | int | str | bool | None, newset: Element | int | str | bool | None, sets: Element | int | str | bool | None) -> Element: ...
    def transversal_extensions(self, element: Element | int | str | bool | None, sets: Element | int | str | bool | None) -> Element: ...
    def is_valid(self, certificate: Element | int | str | bool | None) -> bool: ...

class BasisExchangeMatroid: ...
