from sage.structure.element import Element

def setprint(X: Element | int | str | bool | None) -> Element: ...
def setprint_s(X: Element | int | str | bool | None, toplevel: Element | int | str | bool | None) -> Element: ...
def newlabel(groundset: Element | int | str | bool | None) -> Element: ...
def sanitize_contractions_deletions(matroid: Element | int | str | bool | None, contractions: Element | int | str | bool | None, deletions: Element | int | str | bool | None) -> Element: ...
def make_regular_matroid_from_matroid(matroid: Element | int | str | bool | None) -> Element: ...
def get_nonisomorphic_matroids(MSet: Element | int | str | bool | None) -> Element: ...
def spanning_forest(M: Element | int | str | bool | None) -> Element: ...
def spanning_stars(M: Element | int | str | bool | None) -> Element: ...
def lift_cross_ratios(A: Element | int | str | bool | None, lift_map: Element | int | str | bool | None) -> Element: ...
def lift_map(target: Element | int | str | bool | None) -> Element: ...
def split_vertex(G: Element | int | str | bool | None, u: Element | int | str | bool | None, v: Element, edges: Element | int | str | bool | None) -> Element: ...
def cmp_elements_key(x: Element) -> Element: ...
