# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def setprint(X: builtins.object) -> _SageObject: ...

def setprint_s(X: builtins.object, toplevel: builtins.bool = ...) -> _SageObject: ...

def newlabel(groundset: builtins.object) -> _SageObject: ...

def sanitize_contractions_deletions(matroid: builtins.object, contractions: builtins.object, deletions: builtins.object) -> _SageObject: ...

def make_regular_matroid_from_matroid(matroid: builtins.object) -> _SageObject: ...

def get_nonisomorphic_matroids(MSet: builtins.object) -> _SageObject: ...

def spanning_forest(M: builtins.int) -> _SageObject: ...

def spanning_stars(M: builtins.int) -> _SageObject: ...

def lift_cross_ratios(A: builtins.object, lift_map: builtins.object = ...) -> _SageObject: ...

def lift_map(target: builtins.object) -> _SageObject: ...

def split_vertex(G: builtins.object, u: builtins.object, v: builtins.object = ..., edges: builtins.object = ...) -> _SageObject: ...

def cmp_elements_key(x: builtins.object) -> _SageObject: ...
