# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SIDH:
    def __init__(self, E: builtins.object, PA: builtins.object, QA: builtins.object, PB: builtins.object, QB: builtins.object) -> None: ...
    @classmethod
    def parameter_set_from_prime(cls, prime: builtins.object) -> Self: ...
    @classmethod
    def named_parameter_set(cls, name: builtins.str) -> Self: ...
    def parameters(self) -> _SageObject: ...
    def alice_secret_key(self) -> _SageObject: ...
    def bob_secret_key(self) -> _SageObject: ...
    def alice_public_key(self, alice_secret_key: builtins.object) -> _SageObject: ...
    def bob_public_key(self, bob_secret_key: builtins.object) -> _SageObject: ...
    def alice_compute_shared_secret(self, alice_secret_key: builtins.object, bob_public_key: builtins.object) -> _SageObject: ...
    def bob_compute_shared_secret(self, bob_secret_key: builtins.object, alice_public_key: builtins.object) -> _SageObject: ...
    def secret_isogeny_path(self, start_curve: builtins.object, secret_key: builtins.object, P: builtins.int, Q: builtins.int) -> _SageObject: ...
