from sage.modules.torsion_quadratic_module import TorsionQuadraticModule
from sage.rings.integer import Integer
from sage.structure.element import Matrix

class Genus_Symbol_p_adic_ring:
    def prime(self) -> Integer: ...
    def symbol_tuple_list(self) -> list[list[int]]: ...
    def canonical_symbol(self) -> list[list[int]]: ...
    def determinant(self) -> Integer: ...
    def dimension(self) -> int: ...
    def excess(self) -> Integer: ...
    def level(self) -> Integer: ...
    def is_even(self) -> bool: ...

class GenusSymbol_global_ring:
    def __hash__(self) -> int: ...
    def signature_pair(self) -> tuple[int, int]: ...
    def signature(self) -> int: ...
    def determinant(self) -> Integer: ...
    def dimension(self) -> int: ...
    def is_even(self) -> bool: ...
    def local_symbols(self) -> list[Genus_Symbol_p_adic_ring]: ...
    def local_symbol(self, p: int | Integer) -> Genus_Symbol_p_adic_ring: ...
    def discriminant_form(self) -> TorsionQuadraticModule: ...
    def representative(self) -> Matrix: ...
    def representatives(
        self, backend: str | None = ..., algorithm: str | None = ...
    ) -> tuple[Matrix, ...]: ...
    def spinor_generators(self, proper: bool) -> list[Integer]: ...

def Genus(
    A: Matrix,
    factored_determinant: list[tuple[Integer, Integer]] | None = ...,
) -> GenusSymbol_global_ring: ...
