from sage.structure.element import Matrix

def collect_small_blocks(self) -> list[Matrix]: ...
def p_adic_normal_form(
    self, p: object, precision: int | None = ..., partial: bool = ..., debug: bool = ...
) -> tuple[Matrix, Matrix]: ...
def _normalize(self, normal_odd: bool = ...) -> tuple[Matrix, Matrix]: ...
