# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class NilpotentLieGroup:
    def __init__(self, L: builtins.object, name: builtins.str, **kwds: builtins.object) -> None: ...
    def gens(self) -> builtins.tuple[_SageObject, ...]: ...
    def lie_algebra(self) -> _SageObject: ...
    def step(self) -> _SageObject: ...
    def chart_exp1(self) -> _SageObject: ...
    def chart_exp2(self) -> _SageObject: ...
    def exp(self, X: builtins.object) -> _SageObject: ...
    def log(self, x: builtins.object) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def left_translation(self, g: builtins.object) -> _SageObject: ...
    def left_invariant_frame(self, **kwds: builtins.object) -> _SageObject: ...
    livf: _SageObject
    def left_invariant_extension(self, X: builtins.object, name: builtins.str = ...) -> _SageObject: ...
    def right_translation(self, g: builtins.object) -> _SageObject: ...
    def right_invariant_frame(self, **kwds: builtins.object) -> _SageObject: ...
    rivf: _SageObject
    def right_invariant_extension(self, X: builtins.object, name: builtins.str = ...) -> _SageObject: ...
    def conjugation(self, g: builtins.object) -> _SageObject: ...
    def adjoint(self, g: builtins.object) -> _SageObject: ...
    class Element:
        def __init__(self, parent: builtins.object, **kwds: builtins.object) -> None: ...
        def __invert__(self) -> Self: ...
