from sage.structure.element import Element

class SteenrodAlgebra_generic:
    def prime(self) -> int: ...
    def basis(self, n: int) -> tuple[Element, ...]: ...
    def Sq(self, *args: int) -> Element: ...
