import builtins

class _SageObject: ...

def get_basis_name(
    self, p: builtins.int, generic: builtins.object = ...
) -> _SageObject: ...
def is_valid_profile(
    self,
    truncation_type: builtins.object,
    p: builtins.int = ...,
    generic: builtins.object = ...,
) -> bool: ...
def normalize_profile(
    self,
    precision: builtins.int = ...,
    truncation_type: builtins.str = ...,
    p: builtins.int = ...,
    generic: builtins.object = ...,
) -> _SageObject: ...
def milnor_mono_to_string(
    self, latex: builtins.bool = ..., generic: builtins.bool = ...
) -> _SageObject: ...
def serre_cartan_mono_to_string(
    self, latex: builtins.bool = ..., generic: builtins.bool = ...
) -> _SageObject: ...
def wood_mono_to_string(self, latex: builtins.bool = ...) -> _SageObject: ...
def wall_mono_to_string(self, latex: builtins.bool = ...) -> _SageObject: ...
def wall_long_mono_to_string(self, latex: builtins.bool = ...) -> _SageObject: ...
def arnonA_mono_to_string(
    self, latex: builtins.bool = ..., p: builtins.int = ...
) -> _SageObject: ...
def arnonA_long_mono_to_string(
    self, latex: builtins.bool = ..., p: builtins.int = ...
) -> _SageObject: ...
def pst_mono_to_string(
    self, latex: builtins.bool = ..., generic: builtins.bool = ...
) -> _SageObject: ...
def comm_mono_to_string(
    self, latex: builtins.bool = ..., generic: builtins.bool = ...
) -> _SageObject: ...
def comm_long_mono_to_string(
    self, p: builtins.int, latex: builtins.bool = ..., generic: builtins.bool = ...
) -> _SageObject: ...
def convert_perm(self) -> _SageObject: ...
