# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def get_basis_name(basis: builtins.object, p: builtins.int, generic: builtins.object = ...) -> _SageObject: ...

def is_valid_profile(profile: builtins.object, truncation_type: builtins.object, p: builtins.int = ..., generic: builtins.object = ...) -> builtins.bool: ...

def normalize_profile(profile: builtins.object, precision: builtins.int = ..., truncation_type: builtins.str = ..., p: builtins.int = ..., generic: builtins.object = ...) -> _SageObject: ...

def milnor_mono_to_string(mono: builtins.object, latex: builtins.bool = ..., generic: builtins.bool = ...) -> _SageObject: ...

def serre_cartan_mono_to_string(mono: builtins.object, latex: builtins.bool = ..., generic: builtins.bool = ...) -> _SageObject: ...

def wood_mono_to_string(mono: builtins.object, latex: builtins.bool = ...) -> _SageObject: ...

def wall_mono_to_string(mono: builtins.object, latex: builtins.bool = ...) -> _SageObject: ...

def wall_long_mono_to_string(mono: builtins.object, latex: builtins.bool = ...) -> _SageObject: ...

def arnonA_mono_to_string(mono: builtins.object, latex: builtins.bool = ..., p: builtins.int = ...) -> _SageObject: ...

def arnonA_long_mono_to_string(mono: builtins.object, latex: builtins.bool = ..., p: builtins.int = ...) -> _SageObject: ...

def pst_mono_to_string(mono: builtins.object, latex: builtins.bool = ..., generic: builtins.bool = ...) -> _SageObject: ...

def comm_mono_to_string(mono: builtins.object, latex: builtins.bool = ..., generic: builtins.bool = ...) -> _SageObject: ...

def comm_long_mono_to_string(mono: builtins.object, p: builtins.int, latex: builtins.bool = ..., generic: builtins.bool = ...) -> _SageObject: ...

def convert_perm(m: builtins.int) -> _SageObject: ...
