from sage.structure.element import Element

def get_basis_name(basis: Element | int | str | bool | None, p: int, generic: Element | int | str | bool | None) -> Element: ...
def is_valid_profile(profile: Element | int | str | bool | None, truncation_type: Element | int | str | bool | None, p: int, generic: Element | int | str | bool | None) -> bool: ...
def normalize_profile(profile: Element | int | str | bool | None, precision: int, truncation_type: Element | int | str | bool | None, p: int, generic: Element | int | str | bool | None) -> Element: ...
def milnor_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None, generic: Element | int | str | bool | None) -> Element: ...
def serre_cartan_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None, generic: Element | int | str | bool | None) -> Element: ...
def wood_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None) -> Element: ...
def wall_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None) -> Element: ...
def wall_long_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None) -> Element: ...
def arnonA_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None, p: int) -> Element: ...
def arnonA_long_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None, p: int) -> Element: ...
def pst_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None, generic: Element | int | str | bool | None) -> Element: ...
def comm_mono_to_string(mono: Element | int | str | bool | None, latex: Element | int | str | bool | None, generic: Element | int | str | bool | None) -> Element: ...
def comm_long_mono_to_string(mono: Element | int | str | bool | None, p: int, latex: Element | int | str | bool | None, generic: Element | int | str | bool | None) -> Element: ...
def convert_perm(m: int) -> Element: ...
