from sage.rings.integer import Integer
from sage.structure.element import Element

def SteenrodAlgebra(p: int, basis: Element | int | str | bool | None, generic: Element | int | str | bool | None) -> Element: ...
def AA(n: int, p: int) -> Element: ...
def Sq() -> Element: ...

class SteenrodAlgebra_generic(CombinatorialFreeModule):
    def _basis_key_iterator(self) -> Element: ...
    def prime(self) -> Element: ...
    def basis_name(self) -> str: ...
    def _has_nontrivial_profile(self) -> bool: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...
    def _repr_term(self, t: Element | int | str | bool | None) -> str: ...
    def _latex_term(self, t: Element | int | str | bool | None) -> str: ...
    def profile(self, i: int, component: Element | int | str | bool | None) -> Element: ...
    def homogeneous_component(self, n: int) -> Element: ...
    def one_basis(self) -> Element: ...
    def product_on_basis(self, t1: Element | int | str | bool | None, t2: Element | int | str | bool | None) -> Element: ...
    def coproduct_on_basis(self, t: Element | int | str | bool | None, algorithm: str) -> Element: ...
    def coproduct(self, x: Element, algorithm: str) -> Element: ...
    def antipode_on_basis(self, t: Element | int | str | bool | None) -> Element: ...
    def counit_on_basis(self, t: Element | int | str | bool | None) -> Element: ...
    def _milnor_on_basis(self, t: Element | int | str | bool | None) -> Element: ...
    def milnor(self) -> Element: ...
    def _change_basis_on_basis(self, t: Element | int | str | bool | None, basis: Element | int | str | bool | None) -> Element: ...
    def _change_basis(self, x: Element, basis: Element | int | str | bool | None) -> Element: ...
    def degree_on_basis(self, t: Element | int | str | bool | None) -> int: ...
    def _coerce_map_from_(self, S: Element | int | str | bool | None) -> Element: ...
    def _element_constructor_(self, x: Element) -> Element: ...
    def basis(self, d: int) -> Element: ...
    def _check_profile_on_basis(self, t: Element | int | str | bool | None) -> Element: ...
    def P(self) -> Element: ...
    def Q_exp(self) -> Element: ...
    def Q(self) -> Element: ...
    def _an_element_(self) -> Element: ...
    def pst(self, s: int, t: Element | int | str | bool | None) -> Element: ...
    def ngens(self) -> int: ...
    def gens(self) -> Family: ...
    def gen(self, i: int) -> Element: ...
    def is_commutative(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def dimension(self) -> int: ...
    def top_class(self) -> Element: ...
    def order(self) -> Integer: ...
    def is_division_algebra(self) -> bool: ...
    def is_field(self, proof: Element | int | str | bool | None) -> bool: ...
    def is_integral_domain(self, proof: Element | int | str | bool | None) -> bool: ...
    def is_noetherian(self) -> bool: ...
    def is_generic(self) -> bool: ...

class SteenrodAlgebra_mod_two(SteenrodAlgebra_generic):
    def Sq(self) -> Element: ...

class CombinatorialFreeModule: ...

class Family: ...
