from sage.structure.element import Element

def convert_to_milnor_matrix(n: int, basis: Element | int | str | bool | None, p: int, generic: Element | int | str | bool | None) -> Element: ...
def convert_from_milnor_matrix(n: int, basis: Element | int | str | bool | None, p: int, generic: Element | int | str | bool | None) -> Element: ...
def steenrod_algebra_basis(n: int, basis: Element | int | str | bool | None, p: int) -> Element: ...
def restricted_partitions(n: int, l: Element | int | str | bool | None, no_repeats: Element | int | str | bool | None) -> Element: ...
def xi_degrees(n: int, p: int, reverse: Element | int | str | bool | None) -> Element: ...
def milnor_basis(n: int, p: int) -> Element: ...
def serre_cartan_basis(n: int, p: int, bound: int) -> Element: ...
def atomic_basis(n: int, basis: Element | int | str | bool | None) -> Element: ...
def arnonC_basis(n: int, bound: int) -> Element: ...
def atomic_basis_odd(n: int, basis: Element | int | str | bool | None, p: int) -> Element: ...
def steenrod_basis_error_check(dim: Element | int | str | bool | None, p: int) -> Element: ...
