import builtins

class _SageObject: ...

def milnor_multiplication(self, s: builtins.object) -> _SageObject: ...
def multinomial(self) -> _SageObject: ...
def milnor_multiplication_odd(
    self, m2: builtins.object, p: builtins.int
) -> _SageObject: ...
def multinomial_odd(self, p: builtins.int) -> _SageObject: ...
def binomial_mod2(self, k: builtins.int) -> _SageObject: ...
def binomial_modp(self, k: builtins.int, p: builtins.int) -> _SageObject: ...
def adem(
    self,
    b: builtins.object,
    c: builtins.int = ...,
    p: builtins.int = ...,
    generic: builtins.object = ...,
) -> _SageObject: ...
def make_mono_admissible(
    self, p: builtins.int = ..., generic: builtins.object = ...
) -> _SageObject: ...
