from sage.structure.element import Element

def barker_foran(lattice: Element | int | str | bool | None) -> Element: ...
def downward_monotone(ambient_dim: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
def nonnegative_orthant(ambient_dim: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
def rearrangement(p: int, ambient_dim: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
def schur(ambient_dim: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
def trivial(ambient_dim: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
