import builtins

class _SageObject: ...

def barker_foran(self=...) -> _SageObject: ...
def downward_monotone(self=..., lattice: builtins.object = ...) -> _SageObject: ...
def nonnegative_orthant(self=..., lattice: builtins.object = ...) -> _SageObject: ...
def rearrangement(
    self, ambient_dim: builtins.object = ..., lattice: builtins.object = ...
) -> _SageObject: ...
def schur(self=..., lattice: builtins.object = ...) -> _SageObject: ...
def trivial(self=..., lattice: builtins.object = ...) -> _SageObject: ...
