from collections.abc import Container, Hashable, Iterable, Iterator, Sequence
from typing import Literal, TypeAlias, overload

from sage.combinat.posets.posets import FinitePoset
from sage.geometry.abc import (
    ConvexRationalPolyhedralCone as ConvexRationalPolyhedralCone_abc,
)
from sage.geometry.convex_set import ConvexSet_closed
from sage.geometry.point_collection import PointCollection
from sage.geometry.polyhedron.base import Polyhedron_base
from sage.geometry.relative_interior import RelativeInterior
from sage.geometry.toric_lattice import (
    ToricLattice_generic,
    ToricLattice_quotient,
    ToricLattice_quotient_element,
    ToricLattice_sublattice,
    ToricLattice_sublattice_with_basis,
)
from sage.geometry.toric_lattice_element import ToricLatticeElement, ToricPlot
from sage.interfaces.expect import Expect
from sage.matrix.matrix import Matrix
from sage.matrix.matrix_integer_dense import Matrix_integer_dense
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.vector_integer_dense import Vector_integer_dense
from sage.rings.integer import Integer
from sage.rings.integer_ring import IntegerRing_class
from sage.rings.rational import Rational
from sage.rings.rational_field import RationalField
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.sage_object import SageObject

ConeLattice: TypeAlias = (
    ToricLattice_generic
    | ToricLattice_quotient
    | FreeModule_generic[Integer]
)
ConeLatticeElement: TypeAlias = (
    ToricLatticeElement
    | ToricLattice_quotient_element
    | FreeModuleElement[Integer]
)
ConeRayInput: TypeAlias = (
    ConeLatticeElement
    | FreeModuleElement[RingElement]
    | Sequence[object]
)
ConeRaysInput: TypeAlias = Iterable[ConeRayInput] | PointCollection | Polyhedron_base
ConePointCollection: TypeAlias = PointCollection[ConeLatticeElement, ConeLattice]
ConeRegion: TypeAlias = Literal["whole cone", "interior", "relative interior"]
ConeFaces: TypeAlias = tuple[ConvexRationalPolyhedralCone, ...]


def Cone(
    rays: ConeRaysInput,
    lattice: ConeLattice | None = ...,
    check: bool = ...,
    normalize: bool = ...,
) -> ConvexRationalPolyhedralCone: ...


def integral_length(v: Iterable[object]) -> Rational: ...


def normalize_rays(
    rays: Iterable[ConeRayInput],
    lattice: ConeLattice | None,
) -> list[ConeLatticeElement]: ...


def classify_cone_2d(
    ray0: ConeRayInput,
    ray1: ConeRayInput,
    check: bool = ...,
) -> tuple[Integer, Integer]: ...


def random_cone(
    lattice: ConeLattice | None = ...,
    min_ambient_dim: int | Integer = ...,
    max_ambient_dim: int | Integer = ...,
    min_rays: int | Integer = ...,
    max_rays: int | Integer = ...,
    strictly_convex: bool | None = ...,
    solid: bool | None = ...,
) -> ConvexRationalPolyhedralCone: ...


class IntegralRayCollection(
    SageObject,
    Hashable,
    Iterable[ConeLatticeElement],
):
    def __init__(
        self,
        rays: Iterable[ConeLatticeElement],
        lattice: ConeLattice,
    ) -> None: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> Iterator[ConeLatticeElement]: ...
    def cartesian_product(
        self,
        other: IntegralRayCollection,
        lattice: ConeLattice | None = ...,
    ) -> IntegralRayCollection: ...
    def __neg__(self) -> IntegralRayCollection: ...
    def dim(self) -> int: ...
    dimension = dim
    def lattice(self) -> ConeLattice: ...
    def ambient_vector_space(
        self,
        base_field: Ring | None = ...,
    ) -> FreeModule_generic[RingElement]: ...
    def dual_lattice(self) -> ConeLattice: ...
    def lattice_dim(self) -> int: ...
    ambient_dim = lattice_dim
    ambient_dimension = lattice_dim
    def n_rays(self) -> int: ...
    nrays = n_rays
    def plot(self, **options: object) -> ToricPlot: ...
    def ray(self, n: int | Integer) -> ConeLatticeElement: ...
    def rays(
        self,
        *indices: int | Integer | Iterable[int | Integer],
    ) -> ConePointCollection: ...
    def codim(self) -> int: ...
    codimension = codim
    def span(
        self,
        base_ring: Ring | None = ...,
    ) -> FreeModule_generic[RingElement]: ...
    def _macaulay2_init_(self, macaulay2: Expect | None = ...) -> object: ...


class ConvexRationalPolyhedralCone(
    IntegralRayCollection,
    Container[object],
    ConvexSet_closed,
    ConvexRationalPolyhedralCone_abc,
):
    def __init__(
        self,
        rays: Iterable[ConeLatticeElement] | None = ...,
        lattice: ConeLattice | None = ...,
        ambient: object | None = ...,
        ambient_ray_indices: Iterable[int | Integer] | None = ...,
        PPL: object | None = ...,
    ) -> None: ...
    def _sage_input_(self, sib: object, coerced: bool) -> object: ...
    def _PPL_cone(self) -> object: ...
    def _macaulay2_init_(self, macaulay2: Expect | None = ...) -> object: ...
    def __contains__(self, point: object) -> bool: ...
    def __getstate__(self) -> dict[str, object]: ...
    def _contains(
        self,
        point: object,
        region: ConeRegion = ...,
    ) -> bool: ...
    def interior_contains(self, *point: object) -> bool: ...
    def interior(self) -> RelativeInterior | Polyhedron_base | ConvexRationalPolyhedralCone: ...
    def relative_interior_contains(self, *point: object) -> bool: ...
    def relative_interior(self) -> RelativeInterior | ConvexRationalPolyhedralCone: ...
    def cartesian_product(
        self,
        other: ConvexRationalPolyhedralCone,
        lattice: ConeLattice | None = ...,
    ) -> ConvexRationalPolyhedralCone: ...
    def __neg__(self) -> ConvexRationalPolyhedralCone: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def _some_elements_(self) -> Iterator[FreeModuleElement[RingElement]]: ...
    def _sort_faces(
        self,
        faces: Iterable[ConvexRationalPolyhedralCone],
    ) -> ConeFaces: ...
    def adjacent(self) -> ConeFaces: ...
    def ambient(self) -> object: ...
    def ambient_ray_indices(self) -> tuple[int, ...]: ...
    def contains(self, *point: object) -> bool: ...
    def dual(self) -> ConvexRationalPolyhedralCone: ...
    def embed(
        self,
        cone: ConvexRationalPolyhedralCone,
    ) -> ConvexRationalPolyhedralCone: ...
    def face_lattice(self) -> FinitePoset: ...
    @overload
    def faces(
        self,
        dim: int | Integer,
        codim: None = ...,
    ) -> ConeFaces: ...
    @overload
    def faces(
        self,
        dim: None = ...,
        codim: int | Integer = ...,
    ) -> ConeFaces: ...
    @overload
    def faces(
        self,
        dim: None = ...,
        codim: None = ...,
    ) -> tuple[ConeFaces, ...]: ...
    def facet_normals(self) -> ConePointCollection: ...
    def facet_of(self) -> ConeFaces: ...
    def facets(self) -> ConeFaces: ...
    def incidence_matrix(self) -> Matrix_integer_dense: ...
    def intersection(
        self,
        other: ConvexRationalPolyhedralCone,
    ) -> ConvexRationalPolyhedralCone: ...
    def is_equivalent(
        self,
        other: ConvexRationalPolyhedralCone,
    ) -> bool: ...
    def is_face_of(
        self,
        cone: ConvexRationalPolyhedralCone,
    ) -> bool: ...
    def is_isomorphic(
        self,
        other: ConvexRationalPolyhedralCone,
    ) -> bool: ...
    def is_simplicial(self) -> bool: ...
    def is_smooth(self) -> bool: ...
    def is_empty(self) -> bool: ...
    def is_trivial(self) -> bool: ...
    def is_strictly_convex(self) -> bool: ...
    def is_pointed(self) -> bool: ...
    def linear_subspace(self) -> FreeModule_generic[Rational]: ...
    def lines(self) -> ConePointCollection: ...
    def plot(self, **options: object) -> ToricPlot: ...
    def polyhedron(self, **kwds: object) -> Polyhedron_base: ...
    def an_affine_basis(self) -> list[FreeModuleElement[RingElement]]: ...
    def strict_quotient(self) -> ConvexRationalPolyhedralCone: ...
    def solid_restriction(self) -> ConvexRationalPolyhedralCone: ...
    def _split_ambient_lattice(self) -> None: ...
    @overload
    def sublattice(self) -> ToricLattice_sublattice_with_basis: ...
    @overload
    def sublattice(
        self,
        *coordinates: object,
        **kwds: object,
    ) -> ToricLatticeElement: ...
    @overload
    def sublattice_quotient(self) -> ToricLattice_quotient: ...
    @overload
    def sublattice_quotient(
        self,
        *coordinates: object,
        **kwds: object,
    ) -> ToricLattice_quotient_element: ...
    @overload
    def sublattice_complement(self) -> ToricLattice_sublattice_with_basis: ...
    @overload
    def sublattice_complement(
        self,
        *coordinates: object,
        **kwds: object,
    ) -> ToricLatticeElement: ...
    @overload
    def orthogonal_sublattice(self) -> ToricLattice_sublattice: ...
    @overload
    def orthogonal_sublattice(
        self,
        *coordinates: object,
        **kwds: object,
    ) -> ToricLatticeElement: ...
    def relative_quotient(
        self,
        subcone: ConvexRationalPolyhedralCone,
    ) -> ToricLattice_quotient: ...
    def relative_orthogonal_quotient(
        self,
        supercone: ConvexRationalPolyhedralCone,
    ) -> ToricLattice_quotient: ...
    def semigroup_generators(
        self,
    ) -> ConePointCollection | tuple[ConeLatticeElement, ...]: ...
    def Hilbert_basis(self) -> ConePointCollection: ...
    def Hilbert_coefficients(
        self,
        point: object,
        solver: str | None = ...,
        verbose: int = ...,
        *,
        integrality_tolerance: float = ...,
    ) -> Vector_integer_dense: ...
    def is_solid(self) -> bool: ...
    is_full_dimensional = is_solid
    def is_proper(self) -> bool: ...
    def is_full_space(self) -> bool: ...
    is_universe = is_full_space
    def lineality(self) -> int: ...
    def is_relatively_open(self) -> bool: ...
    def discrete_complementarity_set(
        self,
    ) -> tuple[tuple[ConeLatticeElement, ConeLatticeElement], ...]: ...
    def lyapunov_like_basis(self) -> list[Matrix[RingElement]]: ...
    def lyapunov_rank(self) -> int: ...
    @overload
    def random_element(
        self,
        ring: IntegerRing_class = ...,
    ) -> ConeLatticeElement: ...
    @overload
    def random_element(
        self,
        ring: RationalField,
    ) -> FreeModuleElement[Rational]: ...
    def positive_operators_gens(
        self,
        K2: ConvexRationalPolyhedralCone | None = ...,
    ) -> list[Matrix[RingElement]]: ...
    def _cross_positive_operators_dual(self) -> ConvexRationalPolyhedralCone: ...
    def cross_positive_operators_gens(self) -> list[Matrix[RingElement]]: ...
    def Z_operators_gens(self) -> list[Matrix[RingElement]]: ...
    def max_angle(
        self,
        other: ConvexRationalPolyhedralCone | None = ...,
        exact: bool = ...,
        epsilon: float = ...,
    ) -> RingElement | float: ...
    def irreducible_factors(self) -> tuple[ConvexRationalPolyhedralCone, ...]: ...
    def is_reducible(self) -> bool: ...
