from sage.rings.integer import Integer
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class AffineHullProjectionData:
    ...

class ConvexSet_base(SageObject, Set_base):
    def is_empty(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def cardinality(self) -> Integer: ...
    def is_universe(self) -> bool: ...
    def dim(self) -> int: ...
    def dimension(self) -> int: ...
    def ambient_vector_space(self, base_field: Element | int | str | bool | None) -> Element: ...
    def ambient(self) -> Element: ...
    def ambient_dim(self) -> Element: ...
    def ambient_dimension(self) -> Element: ...
    def an_affine_basis(self) -> Element: ...
    def _test_an_affine_basis(self, tester: Element | int | str | bool | None) -> Element: ...
    def affine_hull(self) -> Element: ...
    def _affine_hull_projection(self) -> Element: ...
    def affine_hull_projection(self, as_convex_set: Element | int | str | bool | None, as_affine_map: Element | int | str | bool | None, orthogonal: Element | int | str | bool | None, orthonormal: Element | int | str | bool | None, extend: Element | int | str | bool | None, minimal: Element | int | str | bool | None, return_all_data: Element | int | str | bool | None) -> Element: ...
    def codimension(self) -> Element: ...
    def is_full_dimensional(self) -> bool: ...
    def is_open(self) -> bool: ...
    def is_relatively_open(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def is_compact(self) -> bool: ...
    def closure(self) -> Element: ...
    def interior(self) -> Element: ...
    def relative_interior(self) -> Element: ...
    def representative_point(self) -> Element: ...
    def _test_convex_set(self, tester: Element | int | str | bool | None) -> Element: ...
    def an_element(self) -> Element: ...
    def some_elements(self) -> list[Element]: ...
    def _some_elements_(self) -> Element: ...
    def cartesian_product(self, other: Element) -> Element: ...
    def contains(self, point: Element | int | str | bool | None) -> bool: ...
    def _test_contains(self, tester: Element | int | str | bool | None) -> Element: ...
    def intersection(self, other: Element) -> Element: ...
    def dilation(self, scalar: Element | int | str | bool | None) -> Element: ...
    def linear_transformation(self, linear_transf: Element | int | str | bool | None) -> Element: ...
    def translation(self, displacement: Element | int | str | bool | None) -> Element: ...

class ConvexSet_closed(ConvexSet_base):
    ...

class ConvexSet_compact(ConvexSet_closed):
    ...

class ConvexSet_relatively_open(ConvexSet_base):
    ...

class ConvexSet_open(ConvexSet_relatively_open):
    ...

class Set_base: ...
