from collections.abc import Container, Iterator

from sage.interfaces.expect import Expect
from sage.rings.ring import Ring
from sage.structure.element import Element

def Fan(cones: Element | int | str | bool | None, rays: Element | int | str | bool | None, lattice: Element | int | str | bool | None, check: bool, normalize: Element | int | str | bool | None, is_complete: Element | int | str | bool | None, virtual_rays: Element | int | str | bool | None, discard_faces: Element | int | str | bool | None, allow_arrangement: Element | int | str | bool | None) -> Element: ...
def FaceFan(polytope: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
def NormalFan(polytope: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
def Fan2d(rays: Element | int | str | bool | None, lattice: Element | int | str | bool | None) -> Element: ...
def discard_faces(cones: Element | int | str | bool | None) -> Element: ...

class Cone_of_fan(ConvexRationalPolyhedralCone):
    def _repr_(self) -> str: ...
    def star_generator_indices(self) -> Element: ...
    def star_generators(self) -> Element: ...

class RationalPolyhedralFan(IntegralRayCollection, Container[Element]):
    def __contains__(self, x: object) -> bool: ...
    def _sage_input_(self, sib: Element | int | str | bool | None, coerced: Element | int | str | bool | None) -> Element: ...
    def _macaulay2_init_(self, macaulay2: Expect | None = None) -> str: ...
    def __iter__(self) -> Iterator[Element]: ...
    def _compute_cone_lattice(self) -> Element: ...
    def _contains(self, cone: Element | int | str | bool | None) -> bool: ...
    def support_contains(self) -> Element: ...
    def cartesian_product(self, other: Element, lattice: Element | int | str | bool | None) -> Element: ...
    def common_refinement(self, other: Element) -> Element: ...
    def _latex_(self) -> str: ...
    def _ray_to_cones(self, i: int) -> Element: ...
    def _subdivide_stellar(self, new_rays: Element | int | str | bool | None, verbose: bool) -> Element: ...
    def cone_containing(self) -> Element: ...
    def cone_lattice(self) -> Element: ...
    def f_vector(self) -> tuple[Element, ...]: ...
    def cones(self, dim: Element | int | str | bool | None, codim: Element | int | str | bool | None) -> Element: ...
    def contains(self, cone: Element | int | str | bool | None) -> bool: ...
    def embed(self, cone: Element | int | str | bool | None) -> Element: ...
    def Gale_transform(self) -> Element: ...
    def is_polytopal(self) -> bool: ...
    def generating_cone(self, n: int) -> Element: ...
    def generating_cones(self) -> Element: ...
    def vertex_graph(self) -> Element: ...
    def is_complete(self) -> bool: ...
    def is_equivalent(self, other: Element) -> bool: ...
    def is_isomorphic(self, other: Element) -> bool: ...
    def _2d_echelon_forms(self) -> Element: ...
    def _2d_echelon_form(self) -> Element: ...
    def isomorphism(self, other: Element) -> Element: ...
    def is_simplicial(self) -> bool: ...
    def is_smooth(self, codim: Element | int | str | bool | None) -> bool: ...
    def make_simplicial(self) -> Element: ...
    def n_generating_cones(self) -> int: ...
    def plot(self) -> Element: ...
    def subdivide(self, new_rays: Element | int | str | bool | None, make_simplicial: Element | int | str | bool | None, algorithm: str, verbose: bool) -> Element: ...
    def virtual_rays(self) -> Element: ...
    def primitive_collections(self) -> Element: ...
    def Stanley_Reisner_ideal(self, ring: Ring) -> Element: ...
    def linear_equivalence_ideal(self, ring: Ring) -> Element: ...
    def oriented_boundary(self, cone: Element | int | str | bool | None) -> Element: ...
    def toric_variety(self) -> Element: ...
    def complex(self, base_ring: Ring, extended: Element | int | str | bool | None) -> Element: ...

class ConvexRationalPolyhedralCone: ...

class IntegralRayCollection: ...
