import builtins

class _SageObject: ...
class FanNotIsomorphicError(Exception): ...

def fan_isomorphic_necessary_conditions(self, fan2: builtins.object) -> _SageObject: ...
def fan_isomorphism_generator(self, fan2: builtins.object) -> _SageObject: ...
def find_isomorphism(
    self, fan2: builtins.object, check: builtins.bool = ...
) -> _SageObject: ...
def fan_2d_cyclically_ordered_rays(self) -> _SageObject: ...
def fan_2d_echelon_forms(self) -> _SageObject: ...
def fan_2d_echelon_form(self) -> _SageObject: ...
