from sage.structure.element import Element

def lattice_from_incidences(atom_to_coatoms: Element | int | str | bool | None, coatom_to_atoms: Element | int | str | bool | None, face_constructor: Element | int | str | bool | None, required_atoms: Element | int | str | bool | None, key: Element | int | str | bool | None) -> Element: ...
