from collections.abc import Container, Hashable, Iterable, Iterator, Sequence
from typing import Literal, Self, TextIO, overload

from sage.combinat.posets.posets import FinitePoset
from sage.geometry.convex_set import ConvexSet_compact
from sage.geometry.fan import RationalPolyhedralFan
from sage.geometry.point_collection import PointCollection
from sage.geometry.polyhedron.base import Polyhedron_base
from sage.geometry.toric_lattice import (
    ToricLattice_generic,
    ToricLattice_sublattice_with_basis,
)
from sage.geometry.toric_lattice_element import ToricLatticeElement
from sage.graphs.graph import Graph
from sage.groups.perm_gps.permgroup import PermutationGroup_generic
from sage.groups.perm_gps.permgroup_element import PermutationGroupElement
from sage.interfaces.expect import Expect
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import (
    FreeModule_generic_field,
    FreeModule_generic_pid,
)
from sage.modules.free_module_element import FreeModuleElement
from sage.plot.plot3d.base import Graphics3d
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.structure.element import Element, FieldElement, RingElement
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject


type LatticePoint = ToricLatticeElement | FreeModuleElement[Integer]
type LatticeModule = ToricLattice_generic | FreeModule_generic_pid[Integer]
type LatticePointInput = (
    LatticePoint
    | Sequence[ElementConstructorInput]
)
type LatticePointInputs = Iterable[LatticePointInput]
type LatticePolytopeInput = (
    LatticePointInputs
    | PointCollection
    | Matrix[Integer]
    | str
    | TextIO
)
type LatticePointCollection = PointCollection[
    FreeModuleElement[Integer],
    FreeModule_generic_pid[Integer],
    Integer,
]
type LatticePolytopeFaces = tuple[LatticePolytopeClass, ...]
type LatticePolytopeFacesByDimension = tuple[LatticePolytopeFaces, ...]
type NefPartitionParts = tuple[tuple[int, ...], ...]


def LatticePolytope(
    data: LatticePolytopeInput,
    compute_vertices: bool = ...,
    n: int | Integer = ...,
    lattice: LatticeModule | None = ...,
) -> LatticePolytopeClass: ...
def ReflexivePolytope(
    dim: int | Integer,
    n: int | Integer,
) -> LatticePolytopeClass: ...
def ReflexivePolytopes(
    dim: int | Integer,
) -> tuple[LatticePolytopeClass, ...]: ...
def _palp_convert_permutation(
    permutation: str,
) -> PermutationGroupElement: ...
def _read_nef_x_partitions(
    data: str | TextIO,
) -> list[list[int]]: ...
def _read_poly_x_incidences(
    data: TextIO,
    dim: int | Integer,
) -> list[list[list[int]]]: ...
def all_cached_data(
    polytopes: Sequence[LatticePolytopeClass],
) -> None: ...
def all_nef_partitions(
    polytopes: Sequence[LatticePolytopeClass],
    keep_symmetric: bool = ...,
) -> None: ...
def all_points(
    polytopes: Sequence[LatticePolytopeClass],
) -> None: ...
def all_polars(
    polytopes: Sequence[LatticePolytopeClass],
) -> None: ...
all_facet_equations = all_polars
def convex_hull(
    points: LatticePointInputs,
) -> list[FreeModuleElement[Integer]]: ...
def filter_nef_partitions(
    partitions: Sequence[NefPartition],
    keep_symmetric: bool = ...,
    keep_products: bool = ...,
    keep_projections: bool = ...,
    hodge_numbers: bool = ...,
) -> list[NefPartition]: ...
def _palp(
    command: str,
    polytopes: Sequence[LatticePolytopeClass],
    reduce_dimension: bool = ...,
) -> str: ...
def read_all_polytopes(
    data: str | TextIO,
    lattice: LatticeModule | None = ...,
) -> list[LatticePolytopeClass]: ...
def skip_palp_matrix(data: TextIO) -> None: ...
def read_palp_matrix(data: TextIO) -> Matrix[Integer]: ...


class LatticePolytopeClass(
    Element,
    ConvexSet_compact,
    Container[LatticePoint],
    Hashable,
):
    def __init__(
        self,
        parent: LatticePolytopes,
        vertices: PointCollection,
        compute_vertices: bool = ...,
        ambient: LatticePolytopeClass | None = ...,
        ambient_vertex_indices: Iterable[int] | None = ...,
        ambient_facet_indices: Iterable[int] | None = ...,
    ) -> None: ...
    def parent(self) -> LatticePolytopes: ...
    def _sage_input_(
        self,
        sib: object,
        coerced: bool,
    ) -> object: ...
    def _macaulay2_init_(
        self,
        macaulay2: Expect | None = ...,
    ) -> object: ...
    def __contains__(self, point: object) -> bool: ...
    def __richcmp__(
        self,
        other: LatticePolytopeClass,
        op: int,
    ) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[object, ...], dict[str, object]]: ...
    def __setstate__(self, state: dict[str, object]) -> None: ...
    def _compute_embedding(self) -> None: ...
    def _compute_facets(self) -> None: ...
    def _contains(
        self,
        point: object,
        region: str = ...,
    ) -> bool: ...
    def _embed(
        self,
        data: object,
    ) -> LatticePoint | Matrix[Integer]: ...
    def _latex_(self) -> str: ...
    def _palp(
        self,
        command: str,
        reduce_dimension: bool = ...,
    ) -> str: ...
    def _PPL(self) -> object: ...
    def _pullback(
        self,
        data: object,
    ) -> FreeModuleElement[Rational] | Matrix[Rational]: ...
    def _read_equations(self, data: str | TextIO) -> None: ...
    def _read_nef_partitions(self, data: str | TextIO) -> None: ...
    def _repr_(self) -> str: ...
    def _sort_faces(
        self,
        faces: Iterable[LatticePolytopeClass],
    ) -> LatticePolytopeFaces: ...
    def adjacent(self) -> LatticePolytopeFaces: ...
    def affine_transform(
        self,
        a: RingElement | Matrix = ...,
        b: RingElement | Sequence[ElementConstructorInput] = ...,
    ) -> LatticePolytopeClass: ...
    linear_transformation = affine_transform
    def translation(
        self,
        v: RingElement | Sequence[ElementConstructorInput],
    ) -> LatticePolytopeClass: ...
    def ambient(self) -> LatticePolytopeClass: ...
    def ambient_facet_indices(self) -> tuple[int, ...]: ...
    def ambient_point_indices(self) -> tuple[int, ...]: ...
    def ambient_ordered_point_indices(self) -> tuple[int, ...]: ...
    def ambient_vertex_indices(self) -> tuple[int, ...]: ...
    def automorphism_group(self) -> PermutationGroup_generic: ...
    def boundary_point_indices(self) -> tuple[int, ...]: ...
    def boundary_points(self) -> LatticePointCollection: ...
    def contains(self, *args: object) -> bool: ...
    def dim(self) -> int: ...
    dimension = dim
    @overload
    def distances(self, point: None = ...) -> Matrix[Integer]: ...
    @overload
    def distances(
        self,
        point: LatticePointInput,
    ) -> FreeModuleElement[Integer]: ...
    def dual(self) -> LatticePolytopeClass: ...
    def dual_lattice(self) -> FreeModule_generic_pid[Integer]: ...
    def edges(self) -> LatticePolytopeFaces: ...
    def face_lattice(self) -> FinitePoset: ...
    @overload
    def faces(
        self,
        dim: int | Integer,
        codim: None = ...,
    ) -> LatticePolytopeFaces: ...
    @overload
    def faces(
        self,
        dim: None = ...,
        codim: int | Integer = ...,
    ) -> LatticePolytopeFaces: ...
    @overload
    def faces(
        self,
        dim: None = ...,
        codim: None = ...,
    ) -> LatticePolytopeFacesByDimension: ...
    def facet_constant(self, i: int | Integer) -> Integer: ...
    def facet_constants(self) -> FreeModuleElement[Integer]: ...
    def facet_normal(self, i: int | Integer) -> FreeModuleElement[Integer]: ...
    def facet_normals(self) -> LatticePointCollection: ...
    def facet_of(self) -> LatticePolytopeFaces: ...
    def facets(self) -> LatticePolytopeFaces: ...
    def incidence_matrix(self) -> Matrix[Integer]: ...
    def index(self) -> int: ...
    def interior_point_indices(self) -> tuple[int, ...]: ...
    def interior_points(self) -> LatticePointCollection: ...
    def is_reflexive(self) -> bool: ...
    def is_terminal(self) -> bool: ...
    def is_cayley(self) -> bool: ...
    def lattice(self) -> FreeModule_generic_pid[Integer]: ...
    def lattice_dim(self) -> int: ...
    ambient_dim = lattice_dim
    @overload
    def ambient_vector_space(
        self,
        base_field: None = ...,
    ) -> FreeModule_generic_field[Rational]: ...
    @overload
    def ambient_vector_space(
        self,
        base_field: Parent[FieldElement],
    ) -> FreeModule_generic_field[FieldElement]: ...
    def linearly_independent_vertices(self) -> tuple[int, ...]: ...
    def nef_partitions(
        self,
        keep_symmetric: bool = ...,
        keep_products: bool = ...,
        keep_projections: bool = ...,
        hodge_numbers: bool = ...,
    ) -> Sequence[NefPartition]: ...
    def nef_x(self, keys: str) -> str: ...
    def n_facets(self) -> int: ...
    nfacets = n_facets
    @overload
    def normal_form(
        self,
        algorithm: str = ...,
        permutation: Literal[False] = ...,
    ) -> LatticePointCollection: ...
    @overload
    def normal_form(
        self,
        algorithm: str = ...,
        permutation: Literal[True] = ...,
    ) -> tuple[LatticePointCollection, PermutationGroupElement]: ...
    def n_points(self) -> int: ...
    npoints = n_points
    def n_vertices(self) -> int: ...
    nvertices = n_vertices
    def ehrhart_polynomial(
        self,
        *args: object,
        **kwds: object,
    ) -> Polynomial: ...
    def origin(self) -> int | None: ...
    def plot3d(
        self,
        **kwds: object,
    ) -> Graphics3d: ...
    def polyhedron(self, **kwds: object) -> Polyhedron_base: ...
    def show3d(self) -> None: ...
    def point(self, i: int | Integer) -> FreeModuleElement[Integer]: ...
    def points(
        self,
        *indices: int,
        **kwds: object,
    ) -> LatticePointCollection: ...
    def _some_elements_(self) -> Iterator[FreeModuleElement[Rational]]: ...
    def polar(self) -> LatticePolytopeClass: ...
    def _mul_(self, other: LatticePolytopeClass) -> LatticePolytopeClass: ...
    def poly_x(
        self,
        keys: str,
        reduce_dimension: bool = ...,
    ) -> str: ...
    def skeleton(self) -> Graph: ...
    def skeleton_points(self, k: int | Integer = ...) -> list[int]: ...
    def skeleton_show(self, normal: object | None = ...) -> None: ...
    def traverse_boundary(self) -> list[int]: ...
    def vertex(self, i: int | Integer) -> FreeModuleElement[Integer]: ...
    def vertex_facet_pairing_matrix(self) -> Matrix[Integer]: ...
    def vertices(
        self,
        *indices: int,
        **kwds: object,
    ) -> LatticePointCollection: ...
    def normal_fan(self) -> RationalPolyhedralFan: ...
    def face_fan(self) -> RationalPolyhedralFan: ...
    def sublattice(self) -> ToricLattice_sublattice_with_basis: ...


class NefPartition(SageObject, Hashable):
    def __init__(
        self,
        data: Sequence[int | Integer],
        Delta_polar: LatticePolytopeClass,
        check: bool = ...,
    ) -> None: ...
    def __richcmp__(
        self,
        other: NefPartition,
        op: int,
    ) -> bool: ...
    def __hash__(self) -> int: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def codimension(self) -> int: ...
    def complete_intersection_dimension(self) -> int: ...
    dimension = complete_intersection_dimension
    def calculate_hodge_numbers(self) -> tuple[int, ...]: ...
    def hodge_numbers(self) -> tuple[int, ...]: ...
    def is_projection(self, i: int | Integer = ...) -> bool: ...
    def is_product(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def simpler(self) -> NefPartition: ...
    def n_parts(self) -> int: ...
    nparts = n_parts
    def part(self, i: int | Integer) -> tuple[int, ...]: ...
    def parts(self) -> NefPartitionParts: ...
    def part_of(self, i: int | Integer) -> int: ...
    def part_of_point(self, i: int | Integer) -> int: ...
    def part_of_point_chang(self, i: int | Integer) -> list[int]: ...
    def part_of_point_chang_all(self) -> list[list[int]]: ...
    def projection(self, i: int | Integer = ...) -> NefPartition: ...
    def Delta_polar(self) -> LatticePolytopeClass: ...
    def Delta(self, i: int | Integer | None = ...) -> LatticePolytopeClass: ...
    def nabla(self, i: int | Integer | None = ...) -> LatticePolytopeClass: ...
    def nabla_polar(self) -> LatticePolytopeClass: ...
    def dual(self) -> NefPartition: ...


class LatticePolytopes(Parent):
    Element: type[LatticePolytopeClass]

    def __init__(self) -> None: ...
    def _repr_(self) -> str: ...
    def one(self) -> LatticePolytopeClass: ...
    def _an_element_(self) -> LatticePolytopeClass: ...


SetOfAllLatticePolytopes: LatticePolytopes
