import builtins

from sage.geometry.point_collection import PointCollection
from sage.structure.element import Element

class _SageObject: ...

def LatticePolytope(
    self,
    compute_vertices: builtins.bool = ...,
    n: builtins.int = ...,
    lattice: builtins.object = ...,
) -> _SageObject: ...
def ReflexivePolytope(self, n: builtins.int) -> _SageObject: ...
def ReflexivePolytopes(self) -> _SageObject: ...

class LatticePolytopeClass:
    def __init__(
        self,
        parent: builtins.object,
        points: builtins.object = ...,
        compute_vertices: builtins.object = ...,
        ambient: builtins.object = ...,
        ambient_vertex_indices: builtins.object = ...,
        ambient_facet_indices: builtins.object = ...,
    ) -> None: ...
    def __contains__(self, point: object) -> bool: ...
    def __richcmp__(self, other: builtins.object, op: builtins.object) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __setstate__(self, state: builtins.object) -> _SageObject: ...
    def adjacent(self) -> tuple[Element, ...]: ...
    def affine_transform(
        self, a: builtins.int = ..., b: builtins.int = ...
    ) -> _SageObject: ...
    linear_transformation: _SageObject

    def translation(self, v: builtins.object) -> _SageObject: ...
    def ambient(self) -> _SageObject: ...
    def ambient_facet_indices(self) -> _SageObject: ...
    def ambient_point_indices(self) -> tuple[Element, ...]: ...
    def ambient_ordered_point_indices(self) -> tuple[Element, ...]: ...
    def ambient_vertex_indices(self) -> _SageObject: ...
    def boundary_point_indices(self) -> _SageObject: ...
    def boundary_points(self) -> _SageObject: ...
    def contains(self, *args: builtins.object) -> bool: ...
    def dim(self) -> _SageObject: ...
    def distances(self, point: builtins.object = ...) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def dual_lattice(self) -> _SageObject: ...
    def edges(self) -> _SageObject: ...
    def face_lattice(self) -> _SageObject: ...
    def faces(
        self, dim: builtins.object = ..., codim: builtins.object = ...
    ) -> _SageObject: ...
    def facet_constant(self, i: builtins.int) -> _SageObject: ...
    def facet_constants(self) -> _SageObject: ...
    def facet_normal(self, i: builtins.int) -> _SageObject: ...
    def facet_normals(self) -> _SageObject: ...
    def facet_of(self) -> _SageObject: ...
    def facets(self) -> _SageObject: ...
    def incidence_matrix(self) -> _SageObject: ...
    def index(self) -> _SageObject: ...
    def interior_point_indices(self) -> tuple[int, ...]: ...
    def interior_points(self) -> PointCollection: ...
    def is_reflexive(self) -> bool: ...
    def is_terminal(self) -> bool: ...
    def is_cayley(self) -> bool: ...
    def lattice(self) -> _SageObject: ...
    def lattice_dim(self) -> _SageObject: ...
    ambient_dim: _SageObject

    def ambient_vector_space(
        self, base_field: builtins.object = ...
    ) -> _SageObject: ...
    def linearly_independent_vertices(self) -> _SageObject: ...
    def nef_partitions(
        self,
        keep_symmetric: builtins.bool = ...,
        keep_products: builtins.bool = ...,
        keep_projections: builtins.bool = ...,
        hodge_numbers: builtins.bool = ...,
    ) -> _SageObject: ...
    def nef_x(self, keys: builtins.object) -> _SageObject: ...
    def n_facets(self) -> int: ...
    nfacets: _SageObject

    def normal_form(
        self, algorithm: builtins.str = ..., permutation: builtins.bool = ...
    ) -> _SageObject: ...
    def n_points(self) -> _SageObject: ...
    npoints: _SageObject

    def n_vertices(self) -> _SageObject: ...
    nvertices: _SageObject

    def ehrhart_polynomial(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def origin(self) -> _SageObject: ...
    def plot3d(
        self,
        show_facets: builtins.bool = ...,
        facet_opacity: builtins.float = ...,
        facet_color: builtins.tuple[_SageObject, ...] = ...,
        facet_colors: builtins.object = ...,
        show_edges: builtins.bool = ...,
        edge_thickness: builtins.int = ...,
        edge_color: builtins.tuple[_SageObject, ...] = ...,
        show_vertices: builtins.bool = ...,
        vertex_size: builtins.int = ...,
        vertex_color: builtins.tuple[_SageObject, ...] = ...,
        show_points: builtins.bool = ...,
        point_size: builtins.int = ...,
        point_color: builtins.tuple[_SageObject, ...] = ...,
        show_vindices: builtins.object = ...,
        vindex_color: builtins.tuple[_SageObject, ...] = ...,
        vlabels: builtins.object = ...,
        show_pindices: builtins.object = ...,
        pindex_color: builtins.tuple[_SageObject, ...] = ...,
        index_shift: builtins.float = ...,
    ) -> _SageObject: ...
    def polyhedron(self, **kwds: builtins.object) -> _SageObject: ...
    def show3d(self) -> _SageObject: ...
    def point(self, i: builtins.int) -> _SageObject: ...
    def points(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def polar(self) -> _SageObject: ...
    def poly_x(
        self, keys: builtins.object, reduce_dimension: builtins.bool = ...
    ) -> _SageObject: ...
    def skeleton(self) -> _SageObject: ...
    def skeleton_points(self, k: builtins.int = ...) -> _SageObject: ...
    def skeleton_show(self, normal: builtins.object = ...) -> _SageObject: ...
    def traverse_boundary(self) -> _SageObject: ...
    def vertex(self, i: builtins.int) -> _SageObject: ...
    def vertex_facet_pairing_matrix(self) -> _SageObject: ...
    def vertices(
        self, *args: builtins.object, **kwds: builtins.object
    ) -> PointCollection: ...

class NefPartition:
    def __init__(
        self,
        data: builtins.object,
        Delta_polar: builtins.object,
        check: builtins.bool = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> builtins.int: ...
    def __ne__(self, other: object) -> bool: ...
    def Delta(self, i: builtins.int = ...) -> _SageObject: ...
    def Delta_polar(self) -> _SageObject: ...
    def Deltas(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    def hodge_numbers(self) -> _SageObject: ...
    def nabla(self, i: builtins.int = ...) -> _SageObject: ...
    def nabla_polar(self) -> _SageObject: ...
    def nablas(self) -> _SageObject: ...
    def n_parts(self) -> _SageObject: ...
    nparts: _SageObject

    def part(self, i: builtins.int, all_points: builtins.bool = ...) -> _SageObject: ...
    def parts(self, all_points: builtins.bool = ...) -> _SageObject: ...
    def part_of(self, i: builtins.int) -> _SageObject: ...
    def part_of_point(self, i: builtins.int) -> _SageObject: ...

def all_cached_data(self) -> _SageObject: ...
def all_nef_partitions(self, keep_symmetric: builtins.bool = ...) -> _SageObject: ...
def all_points(self) -> _SageObject: ...
def all_polars(self) -> _SageObject: ...

all_facet_equations: _SageObject

def convex_hull(self) -> _SageObject: ...
def cross_polytope(self) -> _SageObject: ...
def minkowski_sum(self, points2: builtins.object) -> _SageObject: ...
def positive_integer_relations(self) -> _SageObject: ...
def read_all_polytopes(self) -> _SageObject: ...
def read_palp_matrix(self, permutation: builtins.bool = ...) -> _SageObject: ...
def set_palp_dimension(self) -> _SageObject: ...
def skip_palp_matrix(self, n: builtins.int = ...) -> _SageObject: ...
def write_palp_matrix(
    self,
    ofile: builtins.object = ...,
    comment: builtins.str = ...,
    format: builtins.object = ...,
) -> _SageObject: ...

class LatticePolytopes:
    def __init__(self) -> None: ...
    def one(self) -> _SageObject: ...
    Element: _SageObject
