from typing import Self

from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.parent import Parent

class LinearExpression(ModuleElement):
    def A(self) -> Element: ...
    def b(self) -> Element: ...
    def coefficients(self) -> list[Element]: ...
    def monomial_coefficients(self, copy: Element | int | str | bool | None) -> Element: ...
    def _repr_vector(self, variable: str) -> str: ...
    def _repr_linear(self, include_zero: Element | int | str | bool | None, include_constant: Element | int | str | bool | None, multiplication: Element | int | str | bool | None) -> str: ...
    def _add_(self, other: Element) -> Self: ...
    def _lmul_(self, scalar: Element | int | str | bool | None) -> Element: ...
    def _acted_upon_(self, scalar: Element | int | str | bool | None, self_on_left: Element | int | str | bool | None) -> Element: ...
    def change_ring(self, base_ring: Ring) -> Element: ...
    def __hash__(self) -> int: ...
    def _richcmp_(self, other: Element, op: Element | int | str | bool | None) -> Element: ...
    def evaluate(self, point: Element | int | str | bool | None) -> Element: ...

class LinearExpressionModule(Parent, UniqueRepresentation):
    def basis(self) -> Element: ...
    def ngens(self) -> int: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: int) -> Element: ...
    def _element_constructor_(self, arg0: Element | int | str | bool | None, arg1: Element | int | str | bool | None) -> Element: ...
    def random_element(self) -> Element: ...
    def ambient_module(self) -> Element: ...
    def ambient_vector_space(self) -> Element: ...
    def _coerce_map_from_(self, P: Parent) -> Element: ...
    def _repr_(self) -> str: ...

class ModuleElement: ...

class UniqueRepresentation: ...
