from typing import Self

from sage.structure.element import Element
from sage.structure.parent import Parent

class NewtonPolygon_element(Element):
    def _repr_(self) -> str: ...
    def vertices(self, copy: Element | int | str | bool | None) -> list[Element]: ...
    def last_slope(self) -> Element: ...
    def slopes(self, repetition: Element | int | str | bool | None) -> list[Element]: ...
    def _add_(self, other: Element) -> Self: ...
    def _mul_(self, other: Element) -> Self: ...
    def _richcmp_(self, other: Element, op: Element | int | str | bool | None) -> bool: ...
    def plot(self) -> Element: ...
    def reverse(self, degree: int) -> Element: ...

class ParentNewtonPolygon(Parent, UniqueRepresentation):
    def _an_element_(self) -> Element: ...
    def _element_constructor_(self, arg: Element | int | str | bool | None, sort_slopes: Element | int | str | bool | None, last_slope: Element | int | str | bool | None) -> Element: ...

class UniqueRepresentation: ...
