from collections.abc import Iterator

from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class PointCollection(SageObject):
    def _sage_input_(self, sib: Element | int | str | bool | None, coerced: Element | int | str | bool | None) -> Element: ...
    def __getitem__(self, n: int) -> Element: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __len__(self) -> int: ...
    def _latex_(self) -> str: ...
    def _matrix_(self, ring: Ring) -> Element: ...
    def _repr_(self) -> str: ...
    def basis(self) -> Element: ...
    def cardinality(self) -> Integer: ...
    def cartesian_product(self, other: Element, module: Element | int | str | bool | None) -> Element: ...
    def column_matrix(self) -> Element: ...
    def dimension(self) -> int: ...
    def dual_module(self) -> Element: ...
    def index(self, *args: Element | int | str | bool | None) -> Element: ...
    def matrix(self) -> Element: ...
    def module(self) -> Element: ...
    def output_format(self, format: Element | int | str | bool | None) -> Element: ...
    def set(self) -> Element: ...
    def write_for_palp(self, f: Element) -> Element: ...
    def read_palp_point_collection(self, f: Element, lattice: Element | int | str | bool | None, permutation: Element | int | str | bool | None) -> Element: ...
