from sage.rings.ring import Ring
from sage.structure.element import Element

def cells_list_to_cells_dict(cells_list: Element | int | str | bool | None) -> dict[Element, Element]: ...
def exploded_plot(polyhedra: Element | int | str | bool | None) -> Element: ...

class PolyhedralComplex(GenericCellComplex):
    def cells(self, subcomplex: Element | int | str | bool | None) -> dict[Element, Element]: ...
    def cell_iterator(self, increasing: Element | int | str | bool | None) -> Element: ...
    def _n_cells_sorted(self, n: int, subcomplex: Element | int | str | bool | None) -> list[Element]: ...
    def cells_sorted(self, subcomplex: Element | int | str | bool | None) -> list[Element]: ...
    def maximal_cells(self) -> dict[Element, Element]: ...
    def maximal_cell_iterator(self, increasing: Element | int | str | bool | None) -> Element: ...
    def n_maximal_cells(self, n: int) -> list[Element]: ...
    def _n_maximal_cells_sorted(self, n: int) -> list[Element]: ...
    def maximal_cells_sorted(self) -> list[Element]: ...
    def is_maximal_cell(self, c: Element) -> bool: ...
    def is_cell(self, c: Element) -> bool: ...
    def dimension(self) -> int: ...
    def ambient_dimension(self) -> Element: ...
    def plot(self) -> Element: ...
    def is_pure(self) -> bool: ...
    def is_full_dimensional(self) -> bool: ...
    def __hash__(self) -> int: ...
    def _an_element_(self) -> Element: ...
    def face_poset(self) -> Element: ...
    def is_subcomplex(self, other: Element) -> bool: ...
    def is_compact(self) -> bool: ...
    def graph(self, immutable: Element | int | str | bool | None) -> Element: ...
    def is_connected(self) -> bool: ...
    def connected_component(self, cell: Element | int | str | bool | None) -> Element: ...
    def connected_components(self) -> list[Element]: ...
    def n_skeleton(self, n: int) -> Element: ...
    def stratify(self, n: int) -> Element: ...
    def boundary_subcomplex(self) -> Element: ...
    def relative_boundary_cells(self) -> list[Element]: ...
    def is_convex(self) -> bool: ...
    def union_as_polyhedron(self) -> Element: ...
    def product(self, right: Element | int | str | bool | None) -> Element: ...
    def disjoint_union(self, right: Element | int | str | bool | None) -> Element: ...
    def union(self, right: Element | int | str | bool | None) -> Element: ...
    def join(self, right: Element | int | str | bool | None) -> Element: ...
    def wedge(self, right: Element | int | str | bool | None) -> Element: ...
    def chain_complex(self, subcomplex: Element | int | str | bool | None, augmented: Element | int | str | bool | None, verbose: bool, check: bool, dimensions: Element | int | str | bool | None, base_ring: Ring, cochain: Element | int | str | bool | None) -> Element: ...
    def alexander_whitney(self, cell: Element | int | str | bool | None, dim_left: Element | int | str | bool | None) -> Element: ...
    def _repr_(self) -> str: ...
    def set_immutable(self) -> None: ...
    def is_mutable(self) -> bool: ...
    def is_immutable(self) -> bool: ...
    def add_cell(self, cell: Element | int | str | bool | None) -> Element: ...
    def remove_cell(self, cell: Element | int | str | bool | None, check: bool) -> Element: ...
    def is_simplicial_complex(self) -> bool: ...
    def is_polyhedral_fan(self) -> bool: ...
    def is_simplicial_fan(self) -> bool: ...
    def subdivide(self, make_simplicial: Element | int | str | bool | None, new_vertices: Element | int | str | bool | None, new_rays: Element | int | str | bool | None) -> Element: ...

class GenericCellComplex: ...
