import builtins

class _SageObject: ...

class RelativeInterior:
    def __init__(self, polyhedron: builtins.object) -> None: ...
    def __hash__(self) -> int: ...
    def __contains__(self, point: object) -> bool: ...
    def ambient(self) -> _SageObject: ...
    def ambient_vector_space(
        self, base_field: builtins.object = ...
    ) -> _SageObject: ...
    def ambient_dim(self) -> _SageObject: ...
    def an_affine_basis(self) -> _SageObject: ...
    def dim(self) -> _SageObject: ...
    def interior(self) -> _SageObject: ...
    def relative_interior(self) -> _SageObject: ...
    def closure(self) -> _SageObject: ...
    def is_universe(self) -> builtins.bool: ...
    def is_closed(self) -> builtins.bool: ...
    def representative_point(self) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def dilation(self, scalar: builtins.object) -> _SageObject: ...
    def linear_transformation(
        self, linear_transf: builtins.object, **kwds: builtins.object
    ) -> _SageObject: ...
    def translation(self, displacement: builtins.object) -> _SageObject: ...
