import builtins

class _SageObject: ...

class RibbonGraph:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        sigma: builtins.object,
        rho: builtins.object,
        bipartite: builtins.bool = ...,
    ) -> _SageObject: ...
    def __init__(self, sigma: builtins.object, rho: builtins.object) -> None: ...
    def sigma(self) -> _SageObject: ...
    def rho(self) -> _SageObject: ...
    def number_boundaries(self) -> _SageObject: ...
    def contract_edge(self, k: builtins.int) -> _SageObject: ...
    def extrude_edge(
        self, vertex: builtins.object, dart1: builtins.object, dart2: builtins.object
    ) -> _SageObject: ...
    def genus(self) -> _SageObject: ...
    def mu(self) -> _SageObject: ...
    def boundary(self) -> _SageObject: ...
    def reduced(self) -> _SageObject: ...
    def make_generic(self) -> _SageObject: ...
    def homology_basis(self) -> _SageObject: ...
    def normalize(self) -> _SageObject: ...

def make_ribbon(self, r: builtins.int) -> _SageObject: ...
def bipartite_ribbon_graph(self, q: builtins.int) -> _SageObject: ...
