import builtins

from sage.modules.free_module_element import FreeModuleElement

class _SageObject: ...

class ToricPlotter:
    origin: FreeModuleElement
    dimension: builtins.int

    def __init__(
        self,
        all_options: builtins.object,
        dimension: builtins.int,
        generators: builtins.object = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def adjust_options(self) -> _SageObject: ...
    def include_points(
        self, points: builtins.object, force: builtins.bool = ...
    ) -> _SageObject: ...
    def plot_generators(self) -> _SageObject: ...
    def plot_labels(
        self, labels: builtins.object, positions: builtins.object
    ) -> _SageObject: ...
    def plot_lattice(self) -> _SageObject: ...
    def plot_points(self, points: builtins.object) -> _SageObject: ...
    def plot_ray_labels(self) -> _SageObject: ...
    def plot_rays(self) -> _SageObject: ...
    def plot_walls(self, walls: builtins.object) -> _SageObject: ...
    def set_rays(self, generators: builtins.object) -> _SageObject: ...

def color_list(self, n: builtins.int) -> _SageObject: ...
def label_list(
    self, n: builtins.int, math_mode: builtins.object, index_set: builtins.object = ...
) -> _SageObject: ...
def options(self=..., **kwds: builtins.object) -> _SageObject: ...
def reset_options(self) -> _SageObject: ...
def sector(
    self, ray2: builtins.object, **extra_options: builtins.object
) -> _SageObject: ...
