from sage.structure.element import Element
from sage.structure.parent import Parent

class ToricLatticeElement(Vector_integer_dense):
    def __hash__(self) -> int: ...
    def _act_on_(self, other: Element, self_on_left: Element | int | str | bool | None) -> Element: ...
    def _dot_product_(self, right: Element | int | str | bool | None) -> Element: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def plot(self, **options: Element | int | str | bool | None) -> Element: ...
    def unpickle_v1(self, parent: Parent, entries: Element | int | str | bool | None, degree: int, immutable: Element | int | str | bool | None) -> Element: ...

class Vector_integer_dense: ...
