# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class ToricPlotter:
    def __init__(self, all_options: builtins.object, dimension: builtins.int, generators: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def adjust_options(self) -> _SageObject: ...
    def include_points(self, points: builtins.object, force: builtins.bool = ...) -> _SageObject: ...
    def plot_generators(self) -> _SageObject: ...
    def plot_labels(self, labels: builtins.object, positions: builtins.object) -> _SageObject: ...
    def plot_lattice(self) -> _SageObject: ...
    def plot_points(self, points: builtins.object) -> _SageObject: ...
    def plot_ray_labels(self) -> _SageObject: ...
    def plot_rays(self) -> _SageObject: ...
    def plot_walls(self, walls: builtins.object) -> _SageObject: ...
    def set_rays(self, generators: builtins.object) -> _SageObject: ...

def color_list(color: builtins.object, n: builtins.int) -> _SageObject: ...

def label_list(label: builtins.str, n: builtins.int, math_mode: builtins.object, index_set: builtins.object = ...) -> _SageObject: ...

def options(option: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...

def reset_options() -> _SageObject: ...

def sector(ray1: builtins.object, ray2: builtins.object, **extra_options: builtins.object) -> _SageObject: ...
