from sage.structure.element import Element
from sage.structure.sage_object import SageObject

def color_list(color: Element | int | str | bool | None, n: int) -> Element: ...
def label_list(label: str, n: int, math_mode: Element | int | str | bool | None, index_set: Element | int | str | bool | None) -> Element: ...
def options(option: Element | int | str | bool | None) -> Element: ...
def reset_options() -> Element: ...
def sector(ray1: Element | int | str | bool | None, ray2: Element | int | str | bool | None) -> Element: ...

class ToricPlotter(SageObject):
    def adjust_options(self) -> Element: ...
    def include_points(self, points: Element | int | str | bool | None, force: Element | int | str | bool | None) -> Element: ...
    def plot_generators(self) -> Element: ...
    def plot_labels(self, labels: Element | int | str | bool | None, positions: Element | int | str | bool | None) -> Element: ...
    def plot_lattice(self) -> Element: ...
    def plot_points(self, points: Element | int | str | bool | None) -> Element: ...
    def plot_ray_labels(self) -> Element: ...
    def plot_rays(self) -> Element: ...
    def plot_walls(self, walls: Element | int | str | bool | None) -> Element: ...
    def set_rays(self, generators: Element | int | str | bool | None) -> Element: ...
