from sage.rings.ring import Ring
from sage.structure.element import Element

class ToricLatticeFactory(UniqueFactory):
    def create_key(self, rank: Element | int | str | bool | None, name: str, dual_name: Element | int | str | bool | None, latex_name: Element | int | str | bool | None, latex_dual_name: Element | int | str | bool | None) -> Element: ...
    def create_object(self, version: Element | int | str | bool | None, key: Element | int | str | bool | None) -> Element: ...

class ToricLattice_generic(FreeModule_generic_pid):
    def _coerce_map_from_(self, other: Element) -> Element: ...
    def construction(self) -> Element: ...
    def direct_sum(self, other: Element) -> Element: ...
    def intersection(self, other: Element) -> Element: ...
    def quotient(self, sub: Element | int | str | bool | None, check: bool, positive_point: Element | int | str | bool | None, positive_dual_point: Element | int | str | bool | None) -> Element: ...
    def saturation(self) -> Element: ...
    def span(self, gens: Element | int | str | bool | None, base_ring: Ring) -> Element: ...
    def span_of_basis(self, basis: Element | int | str | bool | None, base_ring: Ring) -> Element: ...

class ToricLattice_ambient(ToricLattice_generic, FreeModule_ambient_pid):
    def _sage_input_(self, sib: Element | int | str | bool | None, coerced: Element | int | str | bool | None) -> Element: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def ambient_module(self) -> Element: ...
    def dual(self) -> Element: ...
    def plot(self) -> Element: ...

class ToricLattice_sublattice_with_basis(ToricLattice_generic, FreeModule_submodule_with_basis_pid):
    ...

class ToricLattice_sublattice(ToricLattice_sublattice_with_basis, FreeModule_submodule_pid):
    ...

class ToricLattice_quotient_element(FGP_Element):
    def set_immutable(self) -> Element: ...

class ToricLattice_quotient(FGP_Module_class):
    def gens(self) -> tuple[Element, ...]: ...
    def _element_constructor_(self) -> Element: ...
    def _module_constructor(self, V: Element | int | str | bool | None, W: Element | int | str | bool | None, check: bool) -> Element: ...
    def base_extend(self, R: Ring) -> Element: ...
    def is_torsion_free(self) -> bool: ...
    def rank(self) -> int: ...
    def coordinate_vector(self, x: Element, reduce: Element | int | str | bool | None) -> Element: ...

class FGP_Element: ...

class FGP_Module_class: ...

class FreeModule_ambient_pid: ...

class FreeModule_generic_pid: ...

class FreeModule_submodule_pid: ...

class FreeModule_submodule_with_basis_pid: ...

class UniqueFactory: ...
