# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SymmetricFunctionAlgebra_AbreuNigro:
    @staticmethod
    def __classcall_private__(cls: builtins.object, Sym: builtins.object, q: builtins.str = ...) -> _SageObject: ...
    def __init__(self, Sym: builtins.object, q: builtins.int) -> None: ...
    def coproduct_on_generators(self, n: builtins.int) -> _SageObject: ...
