# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def KostkaFoulkesPolynomial(mu: builtins.object, nu: builtins.object, t: builtins.object = ...) -> _SageObject: ...

def kfpoly(mu: builtins.object, nu: builtins.object, t: builtins.object = ...) -> _SageObject: ...

def kfpoly_skew(lamu: builtins.object, nu: builtins.object, t: builtins.object = ...) -> _SageObject: ...

def schur_to_hl(mu: builtins.object, t: builtins.object = ...) -> _SageObject: ...

def riggings(part: builtins.object) -> _SageObject: ...

def compat(n: builtins.int, mu: builtins.object, nu: builtins.object) -> _SageObject: ...

def dom(mup: builtins.object, snu: builtins.object) -> _SageObject: ...

def weight(rg: builtins.object, t: builtins.object = ...) -> _SageObject: ...
