from __future__ import annotations
from typing import TYPE_CHECKING
from collections.abc import Callable

if TYPE_CHECKING:
    from sage.combinat.partition import Partition
    from sage.rings.ring import Ring
    from sage.structure.parent import Parent

class LLT_class:
    _k: int
    _sym: object
    t: object
    _m: object
    _name_suffix: str
    _name: str

    @staticmethod
    def __classcall__(cls, Sym: object, k: int, t: str | object = ...) -> LLT_class: ...
    def __init__(self, Sym: object, k: int, t: object) -> None: ...
    def __repr__(self) -> str: ...
    def symmetric_function_ring(self) -> Parent: ...
    def base_ring(self) -> Ring: ...
    def level(self) -> int: ...
    def _llt_generic(self, skp: Partition | list[Partition], stat: Callable[[object, Partition, int], Ring]) -> Parent: ...
    def spin_square(self, skp: Partition | list[Partition]) -> Parent: ...
    def cospin(self, skp: Partition | list[Partition]) -> Parent: ...
    def hcospin(self) -> LLT_cospin: ...
    def hspin(self) -> LLT_spin: ...

class LLT_generic:
    t: object
    _sym: object
    _llt: LLT_class
    _k: int
    _m: object
    _basis_name: str

    def __init__(self, llt: LLT_class, prefix: str) -> None: ...
    def construction(self) -> tuple[object, Ring]: ...
    def _m_to_self(self, x: object) -> LLT_generic.Element: ...
    def _self_to_m(self, x: object) -> LLT_generic.Element: ...
    def level(self) -> int: ...
    def llt_family(self) -> LLT_class: ...
    def product(self, left: object, right: object) -> LLT_generic.Element: ...
    def _m_cache(self, n: int) -> None: ...
    def base_ring(self) -> Ring: ...
    def basis_name(self) -> str: ...

    class Element:
        pass

class LLT_spin(LLT_generic):
    _self_to_m_cache: dict[int, dict[object, object]]
    _m_to_self_cache: dict[int, dict[object, object]]

    def __init__(self, llt: LLT_class) -> None: ...
    def _to_m(self, part: Partition) -> Callable[[Partition], Ring]: ...

    class Element(LLT_generic.Element):
        pass

class LLT_cospin(LLT_generic):
    _self_to_m_cache: dict[int, dict[object, object]]
    _m_to_self_cache: dict[int, dict[object, object]]

    def __init__(self, llt: LLT_class) -> None: ...
    def _to_m(self, part: Partition) -> Callable[[Partition], Ring]: ...

    class Element(LLT_generic.Element):
        pass
