
from sage.combinat.partition import Partition
from sage.rings.ring import Ring
from sage.structure.parent import Parent
class SymmetricFunctionAlgebra_monomial:
    def __init__(self, Sym: object) -> None: ...
    def _dual_basis_default(self) -> Parent: ...
    def product(
        self,
        left: SymmetricFunctionAlgebra_monomial.Element,
        right: SymmetricFunctionAlgebra_monomial.Element,
    ) -> SymmetricFunctionAlgebra_monomial.Element: ...
    def from_polynomial(self, f: object, check: bool = True) -> SymmetricFunctionAlgebra_monomial.Element: ...
    def from_polynomial_exp(self, p: object) -> SymmetricFunctionAlgebra_monomial.Element: ...
    def antipode_by_coercion(self, element: object) -> SymmetricFunctionAlgebra_monomial.Element: ...
    def _magma_init_(self, magma: object) -> str: ...
    def base_ring(self) -> Ring: ...
    def realization_of(self) -> Parent: ...
    def _from_dict(self, d: dict[Partition, object], remove_zeros: bool = ...) -> SymmetricFunctionAlgebra_monomial.Element: ...
    def zero(self) -> SymmetricFunctionAlgebra_monomial.Element: ...

    class Element:
        def expand(self, n: int, alphabet: str = 'x') -> Ring: ...
        def principal_specialization(self, n: object = ..., q: object | None = None) -> Ring: ...
        def exponential_specialization(self, t: object | None = None, q: object = ...) -> Ring: ...
        def parent(self) -> SymmetricFunctionAlgebra_monomial: ...
        def monomial_coefficients(self, copy: bool = ...) -> dict[Partition, object]: ...
        def coefficients(self, sort: bool = ...) -> list[object]: ...
