import builtins

from sage.categories.morphism import SetMorphism
from sage.interfaces.r import R
from sage.misc.constant_function import ConstantFunction

class _SageObject: ...

class KBoundedSubspace:
    one: ConstantFunction
    zero: ConstantFunction
    t: R
    k: builtins.int
    ambient: ConstantFunction
    base_ring: ConstantFunction
    indices: ConstantFunction

    def __init__(
        self, Sym: builtins.object, k: builtins.int, t: builtins.str = ...
    ) -> None: ...
    def retract(self, sym: builtins.object) -> _SageObject: ...
    def realizations(self) -> _SageObject: ...
    def kschur(self) -> _SageObject: ...
    def ksplit(self) -> _SageObject: ...
    def khomogeneous(self) -> _SageObject: ...
    def K_kschur(self) -> _SageObject: ...

class KBoundedSubspaceBases:
    t: builtins.str

    def __init__(self, base: builtins.object, t: builtins.str = ...) -> None: ...
    def super_categories(self) -> _SageObject: ...

    class ParentMethods:
        def __getitem__(self, c: builtins.object) -> _SageObject: ...
        def one_basis(self) -> _SageObject: ...
        def transition_matrix(
            self, other: builtins.object, n: builtins.int
        ) -> _SageObject: ...
        def degree_on_basis(self, b: builtins.object) -> _SageObject: ...
        def coproduct(self, element: builtins.object) -> _SageObject: ...
        def antipode(self, element: builtins.object) -> _SageObject: ...
        def counit(self, element: builtins.object) -> _SageObject: ...

    class ElementMethods:
        def hl_creation_operator(
            self, nu: builtins.object, t: builtins.object = ...
        ) -> _SageObject: ...
        def omega(self) -> _SageObject: ...
        def omega_t_inverse(self) -> _SageObject: ...
        def is_schur_positive(
            self, *args: builtins.object, **kwargs: builtins.object
        ) -> builtins.bool: ...
        def expand(
            self, *args: builtins.object, **kwargs: builtins.object
        ) -> _SageObject: ...
        def scalar(
            self, x: builtins.object, zee: builtins.object = ...
        ) -> _SageObject: ...

class kSchur:
    retract: SetMorphism
    ambient: ConstantFunction

    def __init__(self, kBoundedRing: builtins.object) -> None: ...
    def product_on_basis(
        self, left: builtins.object, right: builtins.object
    ) -> _SageObject: ...

class kSplit:
    retract: SetMorphism
    ambient: ConstantFunction

    def __init__(self, kBoundedRing: builtins.object) -> None: ...

class kHomogeneous:
    retract: SetMorphism
    ambient: ConstantFunction
    t: int

    def __init__(self, kBoundedRing: builtins.object) -> None: ...

class K_kSchur:
    ambient: ConstantFunction
    t: int

    def __init__(self, kBoundedRing: builtins.object) -> None: ...
    def homogeneous_basis_noncommutative_variables_zero_Hecke(
        self, la: builtins.object
    ) -> _SageObject: ...
    def K_k_Schur_non_commutative_variables(
        self, la: builtins.object
    ) -> _SageObject: ...
    def product(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
    def lift(self, x: builtins.object) -> _SageObject: ...
    def retract(self, x: builtins.object) -> _SageObject: ...
