from collections.abc import Callable
from sage.structure.element import Element
from sage.rings.ring import CommutativeRing, Ring
from sage.structure.parent import Parent
from sage.modules.module import Module
from sage.combinat.free_module import CombinatorialFreeModule
from sage.matrix.matrix import Matrix

class SymmetricFunctionAlgebra_generic(CombinatorialFreeModule):
    def base_ring(self) -> CommutativeRing: ...
    def gens(self) -> tuple[Element, ...]: ...

    def __init__(self, Sym: object, basis_name: object = ..., prefix: object = ..., graded: object = ...) -> None: ...
    def __getitem__(self, c: object) -> Element: ...
    def symmetric_function_ring(self) -> Parent: ...
    def prefix(self) -> str: ...
    def transition_matrix(self, basis: object, n: object) -> Matrix: ...
    def dual_basis(self, scalar: object = ..., scalar_name: object = ..., basis_name: object = ..., prefix: object = ...) -> Parent: ...
    def basis_name(self) -> str: ...
    def get_print_style(self) -> str: ...
    def set_print_style(self, ps: object) -> None: ...
    def from_polynomial(self, poly: object, check: object = ...) -> Element: ...
    def product_by_coercion(self, left: object, right: object) -> Element: ...
    def coproduct_by_coercion(self, elt: object) -> Element: ...
    def construction(self) -> tuple[object, CommutativeRing]: ...
    def change_ring(self, R: Ring) -> SymmetricFunctionAlgebra_generic: ...


class SymmetricFunctionAlgebra_generic_Element(CombinatorialFreeModule.Element):
    ...
