from __future__ import annotations
from typing import TYPE_CHECKING
from collections.abc import Callable

if TYPE_CHECKING:
    from sage.combinat.partition import Partition
    from sage.rings.ring import Ring
    from sage.structure.parent import Parent
    from sage.rings.commutative_ring_element import CommutativeRingElement
    from sage.structure.element import Element as SageElement

class SymmetricFunctionAlgebra_witt:
    _h: object
    _e: object
    _p: object

    def __init__(self, Sym: object) -> None: ...
    def _h_to_w_on_basis(self, lam: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...
    def _w_to_h_on_basis(self, lam: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...
    def _e_to_w_on_basis(self, lam: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...
    def _w_to_e_on_basis(self, lam: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...
    def _p_to_w_on_basis(self, lam: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...
    def _w_to_p_on_basis(self, lam: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...
    def coproduct(self, elt: SymmetricFunctionAlgebra_witt.Element) -> SageElement: ...
    def verschiebung(self, n: int) -> SymmetricFunctionAlgebra_witt.Element: ...
    def _omega_on_basis(self, lam: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...
    def _omega_even(self, lam_even: Partition) -> SymmetricFunctionAlgebra_witt.Element: ...

    class Element:
        def omega(self) -> SymmetricFunctionAlgebra_witt.Element: ...
