import builtins

class _SageObject: ...

class FractionWithFactoredDenominator:
    def __init__(
        self,
        parent: builtins.object,
        numerator: builtins.object,
        denominator_factored: builtins.object,
        reduce: builtins.bool = ...,
    ) -> None: ...
    def numerator(self) -> _SageObject: ...
    def denominator(self) -> _SageObject: ...
    def denominator_factored(self) -> _SageObject: ...
    @property
    def denominator_ring(self) -> _SageObject: ...
    @property
    def numerator_ring(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def quotient(self) -> _SageObject: ...
    def univariate_decomposition(self) -> _SageObject: ...
    def nullstellensatz_certificate(self) -> _SageObject: ...
    def nullstellensatz_decomposition(self) -> _SageObject: ...
    def algebraic_dependence_certificate(self) -> _SageObject: ...
    def algebraic_dependence_decomposition(
        self, whole_and_parts: builtins.bool = ...
    ) -> _SageObject: ...
    def leinartas_decomposition(self) -> _SageObject: ...
    def cohomology_decomposition(self) -> _SageObject: ...
    def asymptotic_decomposition(
        self, alpha: builtins.object, asy_var: builtins.object = ...
    ) -> _SageObject: ...
    def asymptotics(
        self,
        p: builtins.int,
        alpha: builtins.object,
        N: builtins.int,
        asy_var: builtins.object = ...,
        numerical: builtins.int = ...,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...
    def asymptotics_smooth(
        self,
        p: builtins.int,
        alpha: builtins.object,
        N: builtins.int,
        asy_var: builtins.object,
        coordinate: builtins.object = ...,
        numerical: builtins.int = ...,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...
    def asymptotics_multiple(
        self,
        p: builtins.int,
        alpha: builtins.object,
        N: builtins.int,
        asy_var: builtins.object,
        coordinate: builtins.object = ...,
        numerical: builtins.int = ...,
        verbose: builtins.bool = ...,
    ) -> _SageObject: ...
    def grads(self, p: builtins.int) -> _SageObject: ...
    def log_grads(self, p: builtins.int) -> _SageObject: ...
    def critical_cone(
        self, p: builtins.int, coordinate: builtins.object = ...
    ) -> _SageObject: ...
    def is_convenient_multiple_point(self, p: builtins.int) -> builtins.bool: ...
    def singular_ideal(self) -> _SageObject: ...
    def smooth_critical_ideal(self, alpha: builtins.object) -> _SageObject: ...
    def maclaurin_coefficients(
        self, multi_indices: builtins.object, numerical: builtins.int = ...
    ) -> _SageObject: ...
    def relative_error(
        self,
        approx: builtins.object,
        alpha: builtins.object,
        interval: builtins.object,
        exp_scale: builtins.object = ...,
        digits: builtins.int = ...,
    ) -> _SageObject: ...

class FractionWithFactoredDenominatorRing:
    @staticmethod
    def __classcall_private__(
        cls: builtins.object,
        denominator_ring: builtins.object,
        numerator_ring: builtins.object = ...,
        category: builtins.object = ...,
    ) -> _SageObject: ...
    def __init__(
        self,
        denominator_ring: builtins.object,
        numerator_ring: builtins.object = ...,
        category: builtins.object = ...,
    ) -> None: ...
    def base_ring(self) -> _SageObject: ...
    Element: _SageObject

class FractionWithFactoredDenominatorSum:
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def denominator_ring(self) -> _SageObject: ...
    def whole_and_parts(self) -> _SageObject: ...
    def sum(self) -> _SageObject: ...

def diff_prod(
    self,
    u: builtins.object,
    g: builtins.object,
    X: builtins.object,
    interval: builtins.object,
    end: builtins.object,
    uderivs: builtins.object,
    atc: builtins.object,
) -> _SageObject: ...
def subs_all(
    self, sub: builtins.object, simplify: builtins.bool = ...
) -> _SageObject: ...
def diff_all(
    self,
    V: builtins.object,
    n: builtins.int,
    ending: builtins.list[_SageObject] = ...,
    sub: builtins.object = ...,
    sub_final: builtins.object = ...,
    zero_order: builtins.int = ...,
    rekey: builtins.object = ...,
) -> _SageObject: ...
def diff_op(
    self,
    B: builtins.object,
    AB_derivs: builtins.object,
    V: builtins.object,
    M: builtins.int,
    r: builtins.int,
    N: builtins.int,
) -> _SageObject: ...
def diff_seq(self, s: builtins.object) -> _SageObject: ...
def diff_op_simple(
    self,
    B: builtins.object,
    AB_derivs: builtins.object,
    x: builtins.object,
    v: builtins.object,
    a: builtins.object,
    N: builtins.int,
) -> _SageObject: ...
def direction(self, coordinate: builtins.object = ...) -> _SageObject: ...
def coerce_point(self, p: builtins.int) -> _SageObject: ...
