from sage.misc.fast_methods import WithLocals
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.parent import Parent
from sage.structure.unique_representation import UniqueRepresentation

class AsymptoticExpansion: ...

class AsymptoticRing(Parent, UniqueRepresentation, WithLocals):
    def variable_names(self) -> tuple[str, ...]: ...
    def base_ring(self) -> Ring: ...
    def gens(self) -> tuple[Element, ...]: ...
