# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AsymptoticExpansionGenerators:
    @staticmethod
    def Stirling(var: builtins.object, precision: builtins.int = ..., skip_constant_factor: builtins.bool = ...) -> _SageObject: ...
    @staticmethod
    def log_Stirling(var: builtins.object, precision: builtins.int = ..., skip_constant_summand: builtins.bool = ...) -> _SageObject: ...
    @staticmethod
    def HarmonicNumber(var: builtins.object, precision: builtins.int = ..., skip_constant_summand: builtins.bool = ...) -> _SageObject: ...
    @staticmethod
    def Binomial_kn_over_n(var: builtins.object, k: builtins.int, precision: builtins.int = ..., skip_constant_factor: builtins.bool = ...) -> _SageObject: ...
    @staticmethod
    def SingularityAnalysis(var: builtins.object, zeta: builtins.int = ..., alpha: builtins.int = ..., beta: builtins.int = ..., delta: builtins.int = ..., precision: builtins.int = ..., normalized: builtins.bool = ...) -> _SageObject: ...
    @staticmethod
    def ImplicitExpansion(var: builtins.object, phi: builtins.object, tau: builtins.object = ..., precision: builtins.int = ...) -> _SageObject: ...
    @staticmethod
    def ImplicitExpansionPeriodicPart(var: builtins.object, phi: builtins.object, period: builtins.object, tau: builtins.object = ..., precision: builtins.int = ...) -> _SageObject: ...
    @staticmethod
    def InverseFunctionAnalysis(var: builtins.object, phi: builtins.object, tau: builtins.object = ..., period: builtins.int = ..., precision: builtins.int = ...) -> _SageObject: ...

asymptotic_expansions: _SageObject
