from typing import Self

from sage.categories.category import Category
from sage.categories.pushout import ConstructionFunctor, Functor
from sage.rings.asymptotic.asymptotic_ring import AsymptoticRing
from sage.rings.asymptotic.misc import WithLocals
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import MultiplicativeGroupElement
from sage.structure.factory import UniqueFactory
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject
from sage.structure.unique_representation import (
    CachedRepresentation,
    UniqueRepresentation,
)

class ValueError: ...

class Variable(CachedRepresentation, SageObject):
    def __init__(
        self,
        var: ElementConstructorInput,
        repr: ElementConstructorInput = ...,
        latex_name: str = ...,
        ignore: ElementConstructorInput = ...,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def variable_names(self) -> tuple[str, ...]: ...
    def is_monomial(self) -> bool: ...
    @staticmethod
    def extract_variable_names(
        s: GenericGrowthElement | ElementConstructorInput,
    ) -> GenericGrowthElement: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...

class PartialConversionValueError(ValueError):
    def __init__(
        self,
        element: GenericGrowthElement | ElementConstructorInput,
        *args: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> None: ...

class PartialConversionElement(SageObject):
    def __init__(
        self,
        growth_group: ElementConstructorInput,
        raw_element: ElementConstructorInput,
    ) -> None: ...
    def split(
        self,
    ) -> tuple[GenericGrowthElement, ...] | list[GenericGrowthElement]: ...
    def is_compatible(
        self, other: GenericGrowthElement | ElementConstructorInput
    ) -> bool: ...
    def _repr_(self) -> str: ...

class GenericGrowthElement(MultiplicativeGroupElement):
    def __init__(
        self, parent: AsymptoticRing, raw_element: ElementConstructorInput
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __invert__(self) -> Self: ...
    log: Self
    log_factor: Self
    rpow: Self

    def factors(
        self,
    ) -> tuple[GenericGrowthElement, ...] | list[GenericGrowthElement]: ...
    is_lt_one: bool

    def variable_names(self) -> tuple[str, ...]: ...
    def _repr_(self) -> str: ...

class GenericGrowthGroup(UniqueRepresentation, Parent, WithLocals):
    @staticmethod
    def __classcall__(
        class_: type[GenericGrowthGroup],
        base: ElementConstructorInput,
        var: ElementConstructorInput = ...,
        category: Category = ...,
        ignore_variables: ElementConstructorInput = ...,
    ) -> GenericGrowthGroup: ...
    def __init__(
        self,
        base: ElementConstructorInput,
        var: ElementConstructorInput,
        category: Category,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def some_elements(self) -> list[GenericGrowthElement]: ...
    def le(
        self,
        left: GenericGrowthElement | ElementConstructorInput,
        right: GenericGrowthElement | ElementConstructorInput,
    ) -> bool: ...
    def is_compatible(
        self, other: GenericGrowthElement | ElementConstructorInput
    ) -> bool: ...
    def gens_monomial(self) -> tuple[GenericGrowthElement, ...]: ...
    def gens(self) -> tuple[GenericGrowthElement, ...]: ...
    def gen(self, n: int | Integer = ...) -> GenericGrowthElement: ...
    def ngens(self) -> int | Integer: ...
    def variable_names(self) -> tuple[str, ...]: ...
    CartesianProduct: GenericGrowthElement

    def extended_by_non_growth_group(self) -> GenericGrowthGroup: ...
    def non_growth_group(self) -> GenericGrowthGroup: ...
    def _repr_(self, condense: Ring = ...) -> str: ...
    def _an_element_(self) -> GenericGrowthElement: ...
    def _element_constructor_(
        self, data: Ring, raw_element: Ring | None = ...
    ) -> GenericGrowthElement: ...
    def _coerce_map_from_(self, S: Ring | Parent) -> bool: ...

class AbstractGrowthGroupFunctor(ConstructionFunctor):
    rank: int | Integer

    def __init__(self, var: ElementConstructorInput, domain: Parent) -> None: ...
    def merge(
        self, other: GenericGrowthElement | ElementConstructorInput
    ) -> AsymptoticRing: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def _repr_(self) -> str: ...

class DecreasingGrowthElementError(ValueError):
    def __init__(
        self,
        element: GenericGrowthElement | ElementConstructorInput,
        *args: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> None: ...

class MonomialGrowthElement(GenericGrowthElement):
    @property
    def exponent(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __pow__(self, exponent: int | Integer | Rational) -> Self: ...
    def _repr_(self, latex: Ring = ...) -> str: ...
    def _latex_(self) -> str: ...

class MonomialGrowthGroup(GenericGrowthGroup):
    def gens_monomial(self) -> tuple[GenericGrowthElement, ...]: ...
    def gens_logarithmic(self) -> tuple[GenericGrowthElement, ...]: ...
    def construction(self) -> tuple[Functor, Parent] | None: ...
    @classmethod
    def factory(
        cls,
        base: Ring,
        var: Ring,
        extend_by_non_growth_group: Ring = ...,
        return_factors: Ring = ...,
        **kwds: ElementConstructorInput,
    ) -> MonomialGrowthGroup: ...
    def non_growth_group(self) -> GenericGrowthGroup: ...

class MonomialGrowthGroupFunctor(AbstractGrowthGroupFunctor):
    def __init__(self, var: ElementConstructorInput) -> None: ...

class ExponentialGrowthElement(GenericGrowthElement):
    @property
    def base(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __pow__(self, exponent: int | Integer | Rational) -> Self: ...
    def _repr_(self, latex: Ring = ...) -> str: ...
    def _latex_(self) -> str: ...

class ExponentialGrowthGroup(GenericGrowthGroup):
    def __init__(
        self,
        base: ElementConstructorInput,
        *args: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> None: ...
    def some_elements(self) -> list[GenericGrowthElement]: ...
    def gens(self) -> tuple[GenericGrowthElement, ...]: ...
    def construction(self) -> tuple[Functor, Parent] | None: ...
    @classmethod
    def factory(
        cls,
        base: Ring,
        var: Ring,
        extend_by_non_growth_group: Ring = ...,
        return_factors: Ring = ...,
        **kwds: ElementConstructorInput,
    ) -> ExponentialGrowthGroup: ...
    def non_growth_group(self) -> GenericGrowthGroup: ...
    def _an_element_(self) -> Self: ...

class ExponentialGrowthGroupFunctor(AbstractGrowthGroupFunctor):
    def __init__(self, var: ElementConstructorInput) -> None: ...

class GenericNonGrowthElement(GenericGrowthElement): ...
class GenericNonGrowthGroup(GenericGrowthGroup): ...
class ExponentialNonGrowthElement(
    GenericNonGrowthElement, ExponentialGrowthElement
): ...

class ExponentialNonGrowthGroup(GenericNonGrowthGroup, ExponentialGrowthGroup):
    def construction(self) -> tuple[Functor, Parent] | None: ...

class ExponentialNonGrowthGroupFunctor(ExponentialGrowthGroupFunctor): ...
class MonomialNonGrowthElement(GenericNonGrowthElement, MonomialGrowthElement): ...

class MonomialNonGrowthGroup(GenericNonGrowthGroup, MonomialGrowthGroup):
    def construction(self) -> tuple[Functor, Parent] | None: ...

class MonomialNonGrowthGroupFunctor(MonomialGrowthGroupFunctor): ...

GrowthGroupFactor: GenericGrowthElement

class GrowthGroupFactory(UniqueFactory):
    def create_key_and_extra_args(
        self, specification: ElementConstructorInput, **kwds: ElementConstructorInput
    ) -> AsymptoticRing: ...
    def create_object(
        self,
        version: int | tuple[int, ...],
        factors: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> GrowthGroupFactory: ...

GrowthGroup: GenericGrowthElement
