import builtins

class _SageObject: ...

def repr_short_to_parent(self) -> _SageObject: ...
def parent_to_repr_short(self) -> _SageObject: ...
def split_str_by_op(
    self, op: builtins.object, strip_parentheses: builtins.bool = ...
) -> _SageObject: ...
def repr_op(
    self, op: builtins.object, right: builtins.object = ..., latex: builtins.bool = ...
) -> _SageObject: ...
def combine_exceptions(self, *f: builtins.object) -> _SageObject: ...
def substitute_raise_exception(self, e: builtins.object) -> _SageObject: ...
def bidirectional_merge_overlapping(
    self, B: builtins.object, key: builtins.object = ...
) -> _SageObject: ...
def bidirectional_merge_sorted(
    self, B: builtins.object, key: builtins.object = ...
) -> _SageObject: ...
def log_string(self, base: builtins.object = ...) -> _SageObject: ...
def strip_symbolic(self) -> _SageObject: ...

class NotImplementedOZero:
    exact_part: builtins.int

    def __init__(
        self,
        asymptotic_ring: builtins.object = ...,
        var: builtins.object = ...,
        exact_part: builtins.int = ...,
    ) -> None: ...

class NotImplementedBZero:
    exact_part: builtins.int

    def __init__(
        self,
        asymptotic_ring: builtins.object = ...,
        var: builtins.object = ...,
        exact_part: builtins.int = ...,
    ) -> None: ...

def transform_category(
    self,
    subcategory_mapping: builtins.object,
    axiom_mapping: builtins.object,
    initial_category: builtins.object = ...,
) -> _SageObject: ...

class Locals:
    def __getitem__(self, key: builtins.object) -> _SageObject: ...
    def __setitem__(self, key: builtins.object, value: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def default_locals(self) -> _SageObject: ...

class WithLocals:
    def locals(self, locals: builtins.object = ...) -> _SageObject: ...
