from typing import Self

from sage.categories.category import Category
from sage.categories.pushout import Functor
from sage.rings.asymptotic.asymptotic_ring import AsymptoticRing
from sage.rings.asymptotic.misc import WithLocals
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.rings.ring import Ring
from sage.structure.element import MultiplicativeGroupElement, RingElement
from sage.structure.factory import UniqueFactory
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.unique_representation import UniqueRepresentation

class ValueError: ...
class ZeroCoefficientError(ValueError): ...

def absorption(
    left: GenericTerm | ElementConstructorInput,
    right: GenericTerm | ElementConstructorInput,
) -> GenericTerm: ...
def can_absorb(
    left: GenericTerm | ElementConstructorInput,
    right: GenericTerm | ElementConstructorInput,
) -> bool: ...

class GenericTerm(MultiplicativeGroupElement):
    def __init__(
        self, parent: AsymptoticRing, growth: ElementConstructorInput
    ) -> None: ...
    def construction(self) -> tuple[Functor, Parent] | None: ...
    def __invert__(self) -> Self: ...
    def __pow__(self, exponent: int | Integer | Rational) -> Self: ...
    def can_absorb(self, other: GenericTerm | ElementConstructorInput) -> bool: ...
    def absorb(
        self, other: GenericTerm | ElementConstructorInput, check: bool = ...
    ) -> GenericTerm: ...
    def log_term(self, base: Ring = ..., locals: Ring = ...) -> GenericTerm: ...
    def is_constant(self) -> bool: ...
    def is_exact(self) -> bool: ...
    def is_little_o_of_one(self) -> bool: ...
    def rpow(self, base: Ring) -> GenericTerm: ...
    def variable_names(self) -> tuple[str, ...]: ...
    def _repr_(self) -> str: ...
    def _latex_(self) -> str: ...

class GenericTermMonoid(UniqueRepresentation, Parent, WithLocals):
    @staticmethod
    def __classcall__(
        class_: type[GenericTermMonoid],
        term_monoid_factory: ElementConstructorInput,
        growth_group: ElementConstructorInput,
        coefficient_ring: ElementConstructorInput,
        category: Category = ...,
    ) -> GenericTermMonoid: ...
    def __init__(
        self,
        term_monoid_factory: ElementConstructorInput,
        growth_group: ElementConstructorInput,
        coefficient_ring: ElementConstructorInput,
        category: Category,
    ) -> None: ...
    @property
    def term_monoid_factory(self) -> GenericTerm: ...
    def term_monoid(self, type: int | Integer) -> GenericTerm: ...
    @property
    def growth_group(self) -> GenericTerm: ...
    @property
    def coefficient_ring(self) -> Ring: ...
    def change_parameter(
        self, growth_group: int | Integer = ..., coefficient_ring: int | Integer = ...
    ) -> GenericTerm: ...
    def from_construction(
        self, construction: Ring, **kwds_overrides: ElementConstructorInput
    ) -> GenericTerm: ...
    def some_elements(self) -> list[GenericTerm]: ...
    def le(
        self,
        left: GenericTerm | ElementConstructorInput,
        right: GenericTerm | ElementConstructorInput,
    ) -> bool: ...
    def _repr_(self) -> str: ...
    def _coerce_map_from_(self, S: Ring | Parent) -> bool: ...
    def _element_constructor_(
        self, data: int | Integer, **kwds: ElementConstructorInput
    ) -> GenericTerm | int | Integer: ...
    def _an_element_(self) -> GenericTerm: ...

class OTerm(GenericTerm):
    def __invert__(self) -> Self: ...
    def __pow__(self, exponent: int | Integer | Rational) -> Self: ...
    def can_absorb(self, other: GenericTerm | ElementConstructorInput) -> bool: ...
    def log_term(self, base: Ring = ..., locals: Ring = ...) -> GenericTerm: ...
    def is_little_o_of_one(self) -> bool: ...
    def rpow(self, base: Ring) -> GenericTerm: ...
    def _repr_(self, latex: Ring = ...) -> str: ...
    def _latex_(self) -> str: ...

class OTermMonoid(GenericTermMonoid):
    def _coerce_map_from_(self, S: Ring | Parent) -> GenericTerm | bool: ...
    def _repr_(self) -> str: ...

class TermWithCoefficient(GenericTerm):
    def __init__(
        self,
        parent: AsymptoticRing,
        growth: ElementConstructorInput,
        coefficient: RingElement | int | Integer | Rational,
    ) -> None: ...
    def construction(self) -> tuple[Functor, Parent] | None: ...
    def _repr_(self) -> str: ...

class TermWithCoefficientMonoid(GenericTermMonoid):
    def some_elements(self) -> list[GenericTerm]: ...
    def _repr_(self) -> str: ...
    def _an_element_(self) -> GenericTerm: ...

class ExactTerm(TermWithCoefficient):
    def __invert__(self) -> Self: ...
    def __pow__(self, exponent: int | Integer | Rational) -> Self: ...
    def can_absorb(self, other: GenericTerm | ElementConstructorInput) -> bool: ...
    def log_term(self, base: Ring = ..., locals: Ring = ...) -> GenericTerm: ...
    def is_constant(self) -> bool: ...
    def is_little_o_of_one(self) -> bool: ...
    def is_exact(self) -> bool: ...
    def rpow(self, base: Ring) -> GenericTerm: ...
    def _repr_(self, latex: Ring = ...) -> str: ...
    def _latex_(self) -> str: ...

class ExactTermMonoid(TermWithCoefficientMonoid):
    def _repr_(self) -> str: ...

class BTerm(TermWithCoefficient):
    def __init__(
        self,
        parent: AsymptoticRing,
        growth: ElementConstructorInput,
        valid_from: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> None: ...
    def construction(self) -> tuple[Functor, Parent] | None: ...
    def can_absorb(self, other: GenericTerm | ElementConstructorInput) -> bool: ...
    def _repr_(self, latex: ElementConstructorInput = ...) -> str: ...
    def _latex_(self) -> str: ...

class BTermMonoid(TermWithCoefficientMonoid):
    def some_elements(self) -> list[GenericTerm]: ...
    def _repr_(self) -> str: ...
    def _coerce_map_from_(self, S: Ring | Parent) -> GenericTerm | bool: ...
    def _an_element_(self) -> GenericTerm: ...

class TermMonoidFactory(UniqueRepresentation, UniqueFactory):
    def __init__(
        self,
        name: str,
        exact_term_monoid_class: ElementConstructorInput = ...,
        O_term_monoid_class: ElementConstructorInput = ...,
        B_term_monoid_class: ElementConstructorInput = ...,
    ) -> None: ...
    def create_key_and_extra_args(
        self,
        term_monoid: ElementConstructorInput,
        growth_group: ElementConstructorInput = ...,
        coefficient_ring: ElementConstructorInput = ...,
        asymptotic_ring: ElementConstructorInput = ...,
        **kwds: ElementConstructorInput,
    ) -> AsymptoticRing: ...
    def create_object(
        self,
        version: int | tuple[int, ...],
        key: tuple[ElementConstructorInput, ...],
        **kwds: ElementConstructorInput,
    ) -> TermMonoidFactory: ...
    def __hash__(self) -> int: ...
    def _repr_(self) -> str: ...

DefaultTermMonoidFactory: GenericTerm
