from sage.rings.ring import Ring
from sage.structure.element import Element

class SurfaceGenerators:
    def Catenoid(self, name: str) -> Element: ...
    def Crosscap(self, name: str) -> Element: ...
    def Dini(self, b: Element, name: str) -> Element: ...
    def Ellipsoid(self, axes: Element | int | str | bool | None, name: str) -> Element: ...
    def Enneper(self) -> Element: ...
    def Helicoid(self, name: str) -> Element: ...
    def Klein(self, name: str) -> Element: ...
    def MonkeySaddle(self) -> Element: ...
    def Paraboloid(self, b: Element, c: Element, elliptic: Element | int | str | bool | None, name: str) -> Element: ...
    def Sphere(self, R: Ring, name: str) -> Element: ...
    def Torus(self, R: Ring, name: str) -> Element: ...
    def WhitneyUmbrella(self) -> Element: ...
