# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FormalPolyhedraModule:
    @staticmethod
    def __classcall__(cls: builtins.object, base_ring: builtins.object, dimension: builtins.int, basis: builtins.object, category: builtins.object = ...) -> _SageObject: ...
    def __init__(self, base_ring: builtins.object, dimension: builtins.int, basis: builtins.object, category: builtins.object) -> None: ...
    def degree_on_basis(self, m: builtins.int) -> _SageObject: ...
