from sage.repl.image import Image
from sage.structure.element import Element

def mandelbrot_plot(f: Element | None = ..., **kwds: object) -> Image: ...
def external_ray(theta: Element | float | list[Element | int | float], **kwds: object) -> Image: ...
def kneading_sequence(theta: Element | float) -> str: ...
def julia_plot(f: Element | None = ..., **kwds: object) -> Image: ...
