# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def permutation(pi: builtins.object, invertible: builtins.bool = ...) -> _SageObject: ...

def one_line(xs: builtins.object) -> _SageObject: ...

def bitstring_rotation(n: builtins.int, ones: builtins.object = ...) -> _SageObject: ...

def striker_sweep(E: builtins.object, predicate: builtins.object, elements: builtins.object, lazy: builtins.bool = ...) -> _SageObject: ...

def syt_promotion(lam: builtins.object) -> _SageObject: ...

def order_ideal_rowmotion(P: builtins.int) -> _SageObject: ...

def semidistributive_rowmotion(L: builtins.object) -> _SageObject: ...

def bulgarian_solitaire(n: builtins.int) -> _SageObject: ...
