# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class TropicalSemiringElement:
    def __init__(self, parent: builtins.object, val: builtins.object = ...) -> None: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def __hash__(self) -> builtins.int: ...
    def __neg__(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __pow__(base: builtins.object, exp: builtins.object, dummy: builtins.object) -> Self: ...
    def multiplicative_order(self) -> _SageObject: ...
    def lift(self) -> _SageObject: ...

class TropicalSemiring:
    def __init__(self, base: builtins.object, use_min: builtins.object = ...) -> None: ...
    def zero(self) -> _SageObject: ...
    def one(self) -> _SageObject: ...
    def gens(self) -> _SageObject: ...

class TropicalToTropical:
    ...
