from typing import Self

from sage.matrix.matrix_generic_dense import Matrix_generic_dense
from sage.rings.semirings.tropical_semiring import TropicalSemiringElement
from sage.structure.element import ModuleElement

class Matrix_tropical_dense(Matrix_generic_dense):
    def extremum_cycle_mean(self) -> TropicalSemiringElement[ModuleElement]: ...
    def weak_transitive_closure(self) -> Self: ...
    def strong_transitive_closure(self) -> Self: ...
    def kleene_star(self) -> Self: ...
