from typing import Generic, Self, TypeVar

from sage.categories.map import Map
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.structure.element import Element, ModuleElement
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.unique_representation import UniqueRepresentation

_BaseElement = TypeVar("_BaseElement", bound=ModuleElement, default=ModuleElement)
_SourceBaseElement = TypeVar("_SourceBaseElement", bound=ModuleElement)
_TargetBaseElement = TypeVar("_TargetBaseElement", bound=ModuleElement)
_TropicalExponent = int | Integer | Rational | ModuleElement

class TropicalSemiringElement(Element, Generic[_BaseElement]):
    def __init__(
        self,
        parent: TropicalSemiring[_BaseElement],
        val: _BaseElement | None = ...,
    ) -> None: ...
    def __reduce__(
        self,
    ) -> tuple[
        type[TropicalSemiringElement[_BaseElement]],
        tuple[TropicalSemiring[_BaseElement], _BaseElement | None],
    ]: ...
    def __hash__(self) -> int: ...
    def __neg__(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __pow__(
        self,
        exp: _TropicalExponent,
        dummy: ElementConstructorInput | None = ...,
    ) -> Self: ...
    def multiplicative_order(self) -> Integer | PlusInfinity: ...
    def lift(self) -> _BaseElement | PlusInfinity: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def _add_(self, right: TropicalSemiringElement[_BaseElement]) -> Self: ...
    def _div_(self, right: TropicalSemiringElement[_BaseElement]) -> Self: ...
    def _mul_(self, right: TropicalSemiringElement[_BaseElement]) -> Self: ...
    def _richcmp_(
        self,
        right: TropicalSemiringElement[_BaseElement],
        op: int,
    ) -> bool: ...

class TropicalSemiring(
    Parent[TropicalSemiringElement[_BaseElement]],
    UniqueRepresentation,
    Generic[_BaseElement],
):
    Element: type[TropicalSemiringElement[_BaseElement]]
    def __init__(self, base: Parent[_BaseElement], use_min: bool = ...) -> None: ...
    def base(self) -> Parent[_BaseElement]: ...
    def zero(self) -> TropicalSemiringElement[_BaseElement]: ...
    def infinity(self) -> TropicalSemiringElement[_BaseElement]: ...
    def additive_identity(self) -> TropicalSemiringElement[_BaseElement]: ...
    def one(self) -> TropicalSemiringElement[_BaseElement]: ...
    def multiplicative_identity(self) -> TropicalSemiringElement[_BaseElement]: ...
    def gens(self) -> tuple[
        TropicalSemiringElement[_BaseElement],
        TropicalSemiringElement[_BaseElement],
    ]: ...
    def _coerce_map_from_(
        self,
        S: Parent[Element],
    ) -> TropicalToTropical[ModuleElement, _BaseElement] | None: ...
    def _element_constructor_(
        self,
        val: _BaseElement | ElementConstructorInput | None,
    ) -> TropicalSemiringElement[_BaseElement]: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...

class TropicalToTropical(
    Map[
        TropicalSemiringElement[_SourceBaseElement],
        TropicalSemiringElement[_TargetBaseElement],
    ],
    Generic[_SourceBaseElement, _TargetBaseElement],
):
    def _call_(
        self,
        x: TropicalSemiringElement[_SourceBaseElement],
    ) -> TropicalSemiringElement[_TargetBaseElement]: ...
