import builtins

class _SageObject: ...

class TropicalVariety:
    def __init__(self, poly: builtins.object) -> None: ...
    def dimension(self) -> _SageObject: ...
    def number_of_components(self) -> _SageObject: ...
    def components(self) -> _SageObject: ...
    def weight_vectors(self) -> _SageObject: ...

class TropicalSurface:
    def plot(self, color: builtins.str = ...) -> _SageObject: ...

class TropicalCurve:
    def vertices(self) -> _SageObject: ...
    def weight_vectors(self) -> _SageObject: ...
    def is_smooth(self) -> bool: ...
    def is_simple(self) -> bool: ...
    def genus(self) -> _SageObject: ...
    def contribution(self) -> _SageObject: ...
    def plot(self) -> _SageObject: ...
