# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class MatchingGame:
    def __init__(self, generator: builtins.object, revr: builtins.object = ...) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def plot(self) -> _SageObject: ...
    def bipartite_graph(self) -> _SageObject: ...
    def add_suitor(self, name: builtins.str = ...) -> _SageObject: ...
    def add_reviewer(self, name: builtins.str = ...) -> _SageObject: ...
    def suitors(self) -> _SageObject: ...
    def reviewers(self) -> _SageObject: ...
    def solve(self, invert: builtins.bool = ...) -> _SageObject: ...

class Player:
    def __init__(self, name: builtins.str) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __gt__(self, other: builtins.object) -> builtins.bool: ...
    def __ge__(self, other: builtins.object) -> builtins.bool: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
