# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

auto_optional_tags: _SageObject
class DocTestDefaults:
    def __init__(self, runtest_default: builtins.bool = ..., **kwds: builtins.object) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...

def skipdir(dirname: builtins.object) -> builtins.bool: ...

def skipfile(filename: builtins.object, tested_optional_tags: builtins.bool = ..., *, if_installed: builtins.bool = ..., log: builtins.object = ...) -> _SageObject: ...

class Logger:
    def __init__(self, *files: builtins.object) -> None: ...
    def write(self, x: builtins.object) -> _SageObject: ...
    def flush(self) -> _SageObject: ...

class DocTestController:
    def __init__(self, options: builtins.object, args: builtins.object) -> None: ...
    def __del__(self) -> _SageObject: ...
    def load_environment(self) -> _SageObject: ...
    def load_baseline_stats(self, filename: builtins.object) -> _SageObject: ...
    def load_stats(self, filename: builtins.object) -> _SageObject: ...
    def save_stats(self, filename: builtins.object) -> _SageObject: ...
    def log(self, s: builtins.object, end: builtins.str = ...) -> _SageObject: ...
    def create_run_id(self) -> _SageObject: ...
    def add_files(self) -> _SageObject: ...
    def expand_files_into_sources(self) -> _SageObject: ...
    def filter_sources(self) -> _SageObject: ...
    def sort_sources(self) -> _SageObject: ...
    def source_baseline(self, source: builtins.object) -> _SageObject: ...
    def run_doctests(self) -> _SageObject: ...
    def cleanup(self, final: builtins.bool = ...) -> _SageObject: ...
    def run_val_gdb(self, testing: builtins.bool = ...) -> _SageObject: ...
    def run(self) -> _SageObject: ...

def run_doctests(module: builtins.object, options: builtins.object = ...) -> _SageObject: ...

test_hide: _SageObject
