# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def signal_name(sig: builtins.object) -> builtins.str: ...

class DocTestReporter:
    def __init__(self, controller: builtins.object) -> None: ...
    def were_doctests_with_optional_tag_run(self, tag: builtins.object) -> _SageObject: ...
    def report_head(self, source: builtins.object, fail_msg: builtins.object = ...) -> _SageObject: ...
    def report(self, source: builtins.object, timeout: builtins.object, return_code: builtins.object, results: builtins.object, output: builtins.object, pid: builtins.object = ..., *, process_tree_before_kill: builtins.object = ...) -> _SageObject: ...
    def finalize(self) -> _SageObject: ...
