# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class FriezePattern:
    @staticmethod
    def __classcall_private__(cls: builtins.object, fp: builtins.object, field: builtins.object = ...) -> _SageObject: ...
    def check(self) -> _SageObject: ...
    def local_rule(self, i: builtins.int) -> _SageObject: ...
    def is_skew(self) -> builtins.bool: ...
    def width(self) -> _SageObject: ...
    def is_positive(self) -> builtins.bool: ...
    def is_integral(self) -> builtins.bool: ...
    def triangulation(self) -> _SageObject: ...
    def plot(self, model: builtins.str = ...) -> _SageObject: ...
    def change_ring(self, R: builtins.int) -> _SageObject: ...

class FriezePatterns:
    def __init__(self, field: builtins.object) -> None: ...
    Element: _SageObject
