import builtins

class _SageObject: ...

class PathTableau:
    def local_rule(self, i: builtins.int) -> _SageObject: ...
    def size(self) -> _SageObject: ...
    def initial_shape(self) -> _SageObject: ...
    def final_shape(self) -> _SageObject: ...
    def promotion(self) -> _SageObject: ...
    def evacuation(self) -> _SageObject: ...
    def commutor(
        self, other: builtins.object, verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def cactus(self, i: builtins.int, j: builtins.int) -> _SageObject: ...
    def orbit(self) -> _SageObject: ...
    def dual_equivalence_graph(self) -> _SageObject: ...

class PathTableaux:
    def __init__(self) -> None: ...

class CylindricalDiagram:
    def __init__(self, T: builtins.object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __len__(self) -> builtins.int: ...
    def pp(self) -> _SageObject: ...
