from sage.structure.element import Element
from sage.structure.sage_object import SageObject

class AffineSubspace(SageObject):
    def __hash__(self) -> int: ...
    def _repr_(self) -> str: ...
    def linear_part(self) -> Element: ...
    def point(self) -> Element: ...
    def dimension(self) -> int: ...
    def intersection(self, other: Element) -> Element: ...
