# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AffineSubspace:
    def __init__(self, p: builtins.int, V: builtins.object) -> None: ...
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __ne__(self, other: builtins.object) -> builtins.bool: ...
    def __le__(self, other: builtins.object) -> builtins.bool: ...
    def __lt__(self, other: builtins.object) -> builtins.bool: ...
    def __contains__(self, q: builtins.object) -> builtins.bool: ...
    def linear_part(self) -> _SageObject: ...
    def point(self) -> _SageObject: ...
    def dimension(self) -> _SageObject: ...
    def intersection(self, other: builtins.object) -> _SageObject: ...
