from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.structure.element import Element
from sage.structure.parent import Parent

class HyperplaneArrangementElement(Element):
    def _first_ngens(self, n: int) -> Element: ...
    def __getitem__(self, i: int) -> Element: ...
    def __hash__(self) -> int: ...
    def n_hyperplanes(self) -> Element: ...
    def hyperplanes(self) -> Element: ...
    def _repr_(self) -> str: ...
    def dimension(self) -> int: ...
    def rank(self) -> int: ...
    def backend(self) -> Element: ...
    def _richcmp_(self, other: Element, op: Element | int | str | bool | None) -> Element: ...
    def union(self, other: Element) -> Element: ...
    def plot(self) -> Element: ...
    def cone(self, variable: str) -> Element: ...
    def intersection_poset(self, element_label: Element | int | str | bool | None) -> Element: ...
    def _slow_characteristic_polynomial(self) -> Element: ...
    def characteristic_polynomial(self) -> Integer: ...
    def poincare_polynomial(self) -> Element: ...
    def cocharacteristic_polynomial(self) -> Element: ...
    def primitive_eulerian_polynomial(self) -> Element: ...
    def deletion(self, hyperplanes: Element | int | str | bool | None) -> Element: ...
    def restriction(self, hyperplane: Element | int | str | bool | None, repetitions: Element | int | str | bool | None) -> Element: ...
    def change_ring(self, base_ring: Ring) -> Element: ...
    def n_regions(self) -> Element: ...
    def n_bounded_regions(self) -> Element: ...
    def has_good_reduction(self, p: int) -> bool: ...
    def is_linear(self) -> bool: ...
    def is_essential(self) -> bool: ...
    def is_central(self, certificate: Element | int | str | bool | None) -> bool: ...
    def center(self) -> Element: ...
    def is_simplicial(self) -> bool: ...
    def essentialization(self) -> Element: ...
    def sign_vector(self, p: int) -> Element: ...
    def face_vector(self) -> Element: ...
    def _parallel_hyperplanes(self) -> tuple[Element, ...]: ...
    def vertices(self, exclude_sandwiched: Element | int | str | bool | None) -> Element: ...
    def _make_region(self, hyperplanes: Element | int | str | bool | None) -> Element: ...
    def regions(self) -> Element: ...
    def poset_of_regions(self, B: Element | int | str | bool | None, numbered_labels: Element | int | str | bool | None) -> Element: ...
    def closed_faces(self, labelled: Element | int | str | bool | None) -> Element: ...
    def face_product(self, F: Ring, G: Element | int | str | bool | None, normalize: Element | int | str | bool | None) -> Element: ...
    def face_semigroup_algebra(self, field: Element | int | str | bool | None, names: str) -> Element: ...
    def region_containing_point(self, p: int) -> Element: ...
    def _bounded_region_indices(self) -> Element: ...
    def bounded_regions(self) -> Element: ...
    def unbounded_regions(self) -> Element: ...
    def whitney_data(self) -> Element: ...
    def doubly_indexed_whitney_number(self, i: int, j: int, kind: Element | int | str | bool | None) -> Element: ...
    def whitney_number(self, k: int, kind: Element | int | str | bool | None) -> Element: ...
    def is_separating_hyperplane(self, region1: Element | int | str | bool | None, region2: Element | int | str | bool | None, hyperplane: Element | int | str | bool | None) -> bool: ...
    def distance_between_regions(self, region1: Element | int | str | bool | None, region2: Element | int | str | bool | None) -> Element: ...
    def distance_enumerator(self, base_region: Element | int | str | bool | None) -> Element: ...
    def varchenko_matrix(self, names: str) -> Element: ...
    def matroid(self) -> Element: ...
    def orlik_solomon_algebra(self, base_ring: Ring, ordering: Element | int | str | bool | None) -> Element: ...
    def orlik_terao_algebra(self, base_ring: Ring, ordering: Element | int | str | bool | None) -> Element: ...
    def minimal_generated_number(self) -> Element: ...
    def is_formal(self) -> bool: ...
    def defining_polynomial(self) -> Element: ...
    def derivation_module_free_chain(self) -> Element: ...
    def is_free(self, algorithm: str) -> bool: ...
    def derivation_module_basis(self, algorithm: str) -> Element: ...

class HyperplaneArrangements(Parent, UniqueRepresentation):
    def ambient_space(self) -> Element: ...
    def _element_constructor_(self) -> Element: ...
    def ngens(self) -> int: ...
    def gens(self) -> tuple[Element, ...]: ...
    def gen(self, i: int) -> Element: ...
    def _coerce_map_from_(self, P: Parent) -> Element: ...

class UniqueRepresentation: ...
