from sage.rings.ring import Ring
from sage.structure.element import Element

def make_parent(base_ring: Ring, dimension: Element | int | str | bool | None, names: str) -> Element: ...

class HyperplaneArrangementLibrary:
    def braid(self, n: int, K: Ring, names: str) -> Element: ...
    def bigraphical(self, G: Element | int | str | bool | None, A: Element | int | str | bool | None, K: Ring, names: str) -> Element: ...
    def Catalan(self, n: int, K: Ring, names: str) -> Element: ...
    def coordinate(self, n: int, K: Ring, names: str) -> Element: ...
    def Coxeter(self, data: Element | int | str | bool | None, K: Ring, names: str) -> Element: ...
    def G_semiorder(self, G: Element | int | str | bool | None, K: Ring, names: str) -> Element: ...
    def G_Shi(self, G: Element | int | str | bool | None, K: Ring, names: str) -> Element: ...
    def graphical(self, G: Element | int | str | bool | None, K: Ring, names: str) -> Element: ...
    def Ish(self, n: int, K: Ring, names: str) -> Element: ...
    def IshB(self, n: int, K: Ring, names: str) -> Element: ...
    def linial(self, n: int, K: Ring, names: str) -> Element: ...
    def semiorder(self, n: int, K: Ring, names: str) -> Element: ...
    def Shi(self, data: Element | int | str | bool | None, K: Ring, names: str, m: int) -> Element: ...
