import builtins

class _SageObject: ...

def make_parent(
    self, dimension: builtins.int, names: builtins.object = ...
) -> _SageObject: ...

class HyperplaneArrangementLibrary:
    def braid(
        self, n: builtins.int, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def bigraphical(
        self,
        G: builtins.object,
        A: builtins.object = ...,
        K: builtins.int = ...,
        names: builtins.object = ...,
    ) -> _SageObject: ...
    def Catalan(
        self, n: builtins.int, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def coordinate(
        self, n: builtins.int, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def Coxeter(
        self, data: builtins.object, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def G_semiorder(
        self, G: builtins.object, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def G_Shi(
        self, G: builtins.object, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def graphical(
        self, G: builtins.object, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def Ish(
        self, n: builtins.int, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def IshB(
        self, n: builtins.int, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def linial(
        self, n: builtins.int, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def semiorder(
        self, n: builtins.int, K: builtins.int = ..., names: builtins.object = ...
    ) -> _SageObject: ...
    def Shi(
        self,
        data: builtins.object,
        K: builtins.int = ...,
        names: builtins.object = ...,
        m: builtins.int = ...,
    ) -> _SageObject: ...

hyperplane_arrangements: _SageObject
