# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class OrderedHyperplaneArrangementElement:
    def __init__(self, parent: builtins.object, hyperplanes: builtins.object, check: builtins.bool = ..., backend: builtins.object = ...) -> None: ...
    def hyperplane_section(self, proj: builtins.bool = ...) -> _SageObject: ...
    def affine_fundamental_group(self) -> _SageObject: ...
    def affine_meridians(self) -> _SageObject: ...
    def projective_fundamental_group(self) -> _SageObject: ...
    def projective_meridians(self) -> _SageObject: ...

class OrderedHyperplaneArrangements:
    Element: _SageObject
