import builtins

class _SageObject: ...

def plot(self, **kwds: builtins.object) -> _SageObject: ...
def plot_hyperplane(self, **kwds: builtins.object) -> _SageObject: ...
def legend_3d(
    self, hyperplane_colors: builtins.object, length: builtins.int
) -> _SageObject: ...
