import builtins
from typing import Self

class _SageObject: ...

generate_real_LaTeX: _SageObject

def variable(self, v: builtins.object) -> _SageObject: ...

available_styles: _SageObject
current_style: _SageObject

def default_variable_name(self) -> _SageObject: ...
def style(self=...) -> _SageObject: ...

class InteractiveLPProblem:
    def __init__(
        self,
        A: builtins.object,
        b: builtins.object,
        c: builtins.object,
        x: builtins.str = ...,
        constraint_type: builtins.str = ...,
        variable_type: builtins.str = ...,
        problem_type: builtins.str = ...,
        base_ring: builtins.object = ...,
        is_primal: builtins.bool = ...,
        objective_constant_term: builtins.int = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def Abcx(self) -> _SageObject: ...
    def add_constraint(
        self,
        coefficients: builtins.object,
        constant_term: builtins.object,
        constraint_type: builtins.str = ...,
    ) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def constant_terms(self) -> _SageObject: ...
    def constraint_coefficients(self) -> _SageObject: ...
    def constraint_types(self) -> _SageObject: ...
    def decision_variables(self) -> _SageObject: ...
    def dual(self, y: builtins.object = ...) -> _SageObject: ...
    def feasible_set(self) -> _SageObject: ...
    def is_bounded(self) -> bool: ...
    def is_feasible(self, *x: builtins.object) -> bool: ...
    def is_negative(self) -> bool: ...
    def is_primal(self) -> bool: ...
    def is_optimal(self, *x: builtins.object) -> bool: ...
    def n_constraints(self) -> _SageObject: ...
    def n_variables(self) -> _SageObject: ...
    def objective_coefficients(self) -> _SageObject: ...
    def objective_constant_term(self) -> _SageObject: ...
    def objective_value(self, *x: builtins.object) -> _SageObject: ...
    def optimal_solution(self) -> _SageObject: ...
    def optimal_value(self) -> _SageObject: ...
    def plot(self, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def plot_feasible_set(
        self,
        xmin: builtins.object = ...,
        xmax: builtins.object = ...,
        ymin: builtins.object = ...,
        ymax: builtins.object = ...,
        alpha: builtins.float = ...,
    ) -> _SageObject: ...
    def problem_type(self) -> _SageObject: ...
    def standard_form(
        self, transformation: builtins.bool = ..., **kwds: builtins.object
    ) -> _SageObject: ...
    def variable_types(self) -> _SageObject: ...
    A: _SageObject
    b: _SageObject
    c: _SageObject
    x: _SageObject
    m: _SageObject
    n: _SageObject

class InteractiveLPProblemStandardForm:
    def __init__(
        self,
        A: builtins.object,
        b: builtins.object,
        c: builtins.object,
        x: builtins.str = ...,
        problem_type: builtins.str = ...,
        slack_variables: builtins.object = ...,
        auxiliary_variable: builtins.object = ...,
        base_ring: builtins.object = ...,
        is_primal: builtins.bool = ...,
        objective_name: builtins.str = ...,
        objective_constant_term: builtins.int = ...,
    ) -> None: ...
    @staticmethod
    def random_element(
        m: builtins.int,
        n: builtins.int,
        bound: builtins.int = ...,
        special_probability: builtins.float = ...,
        **kwds: builtins.object,
    ) -> _SageObject: ...
    def add_constraint(
        self,
        coefficients: builtins.object,
        constant_term: builtins.object,
        slack_variable: builtins.object = ...,
    ) -> _SageObject: ...
    def auxiliary_problem(self, objective_name: builtins.str = ...) -> _SageObject: ...
    def auxiliary_variable(self) -> _SageObject: ...
    def coordinate_ring(self) -> _SageObject: ...
    def dictionary(self, *x_B: builtins.object) -> _SageObject: ...
    def feasible_dictionary(
        self, auxiliary_dictionary: builtins.object
    ) -> _SageObject: ...
    def final_dictionary(self) -> _SageObject: ...
    def final_revised_dictionary(self) -> _SageObject: ...
    def initial_dictionary(self) -> _SageObject: ...
    def inject_variables(
        self, scope: builtins.object = ..., verbose: builtins.bool = ...
    ) -> _SageObject: ...
    def objective_name(self) -> _SageObject: ...
    def revised_dictionary(self, *x_B: builtins.object) -> _SageObject: ...
    def run_revised_simplex_method(self) -> _SageObject: ...
    def run_simplex_method(self) -> _SageObject: ...
    def slack_variables(self) -> _SageObject: ...

class LPAbstractDictionary:
    def __init__(self) -> None: ...
    def add_row(
        self,
        nonbasic_coefficients: builtins.object,
        constant: builtins.object,
        basic_variable: builtins.object = ...,
    ) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def basic_variables(self) -> _SageObject: ...
    def basic_solution(
        self, include_slack_variables: builtins.bool = ...
    ) -> _SageObject: ...
    def column_coefficients(self, v: builtins.object) -> _SageObject: ...
    def constant_terms(self) -> _SageObject: ...
    def coordinate_ring(self) -> _SageObject: ...
    def dual_ratios(self) -> _SageObject: ...
    def enter(self, v: builtins.object) -> _SageObject: ...
    def entering(self) -> _SageObject: ...
    def entering_coefficients(self) -> _SageObject: ...
    def is_dual_feasible(self) -> bool: ...
    def is_feasible(self) -> bool: ...
    def is_optimal(self) -> bool: ...
    def leave(self, v: builtins.object) -> _SageObject: ...
    def leaving(self) -> _SageObject: ...
    def leaving_coefficients(self) -> _SageObject: ...
    def nonbasic_variables(self) -> _SageObject: ...
    def objective_coefficients(self) -> _SageObject: ...
    def objective_name(self) -> _SageObject: ...
    def objective_value(self) -> _SageObject: ...
    def possible_dual_simplex_method_steps(self) -> _SageObject: ...
    def possible_entering(self) -> _SageObject: ...
    def possible_leaving(self) -> _SageObject: ...
    def possible_simplex_method_steps(self) -> _SageObject: ...
    def ratios(self) -> _SageObject: ...
    def row_coefficients(self, v: builtins.object) -> _SageObject: ...
    def run_dual_simplex_method(self) -> _SageObject: ...
    def run_simplex_method(self) -> _SageObject: ...
    def update(self) -> _SageObject: ...

class LPDictionary:
    def __init__(
        self,
        A: builtins.object,
        b: builtins.object,
        c: builtins.object,
        objective_value: builtins.object,
        basic_variables: builtins.object,
        nonbasic_variables: builtins.object,
        objective_name: builtins.str,
    ) -> None: ...
    def __copy__(self) -> Self: ...
    @staticmethod
    def random_element(
        m: builtins.int,
        n: builtins.int,
        bound: builtins.int = ...,
        special_probability: builtins.float = ...,
    ) -> _SageObject: ...
    def __eq__(self, other: object) -> bool: ...
    def add_row(
        self,
        nonbasic_coefficients: builtins.object,
        constant: builtins.object,
        basic_variable: builtins.object = ...,
    ) -> _SageObject: ...
    def basic_variables(self) -> _SageObject: ...
    def column_coefficients(self, v: builtins.object) -> _SageObject: ...
    def constant_terms(self) -> _SageObject: ...
    def nonbasic_variables(self) -> _SageObject: ...
    def objective_coefficients(self) -> _SageObject: ...
    def objective_name(self) -> _SageObject: ...
    def objective_value(self) -> _SageObject: ...
    def row_coefficients(self, v: builtins.object) -> _SageObject: ...
    def update(self) -> _SageObject: ...

random_dictionary: _SageObject

class LPRevisedDictionary:
    def __init__(
        self, problem: builtins.object, basic_variables: builtins.object
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def A(self, v: builtins.object) -> _SageObject: ...
    def A_N(self) -> _SageObject: ...
    def B(self) -> _SageObject: ...
    def B_inverse(self) -> _SageObject: ...
    def E(self) -> _SageObject: ...
    def E_inverse(self) -> _SageObject: ...
    def add_row(
        self,
        nonbasic_coefficients: builtins.object,
        constant: builtins.object,
        basic_variable: builtins.object = ...,
    ) -> _SageObject: ...
    def basic_indices(self) -> _SageObject: ...
    def basic_variables(self) -> _SageObject: ...
    def c_B(self) -> _SageObject: ...
    def c_N(self) -> _SageObject: ...
    def column_coefficients(self, v: builtins.object) -> _SageObject: ...
    def constant_terms(self) -> _SageObject: ...
    def dictionary(self) -> _SageObject: ...
    def nonbasic_indices(self) -> _SageObject: ...
    def nonbasic_variables(self) -> _SageObject: ...
    def objective_coefficients(self) -> _SageObject: ...
    def objective_name(self) -> _SageObject: ...
    def objective_value(self) -> _SageObject: ...
    def problem(self) -> _SageObject: ...
    def row_coefficients(self, v: builtins.object) -> _SageObject: ...
    def update(self) -> _SageObject: ...
    def y(self) -> _SageObject: ...
    x_B: _SageObject
    x_N: _SageObject
