import builtins

class _SageObject: ...

class Superincreasing:
    def __init__(self, seq: builtins.object = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def largest_less_than(self, N: builtins.int) -> _SageObject: ...
    def is_superincreasing(self, seq: builtins.object = ...) -> builtins.bool: ...
    def subset_sum(self, N: builtins.int) -> _SageObject: ...

def knapsack(
    self,
    binary: builtins.bool = ...,
    max: builtins.int = ...,
    value_only: builtins.bool = ...,
    solver: builtins.object = ...,
    verbose: builtins.int = ...,
    *,
    integrality_tolerance: builtins.float = ...,
) -> _SageObject: ...
