# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class LinearTensor:
    def __init__(self, parent: builtins.object, f: builtins.object) -> None: ...
    def __getitem__(self, indices: builtins.object) -> _SageObject: ...
    def dict(self) -> _SageObject: ...
    def coefficient(self, x: builtins.object) -> _SageObject: ...
    def __richcmp__(left: builtins.object, right: builtins.object, op: builtins.object) -> _SageObject: ...
    def __hash__(self) -> builtins.int: ...
