# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class SemidefiniteProgram:
    def linear_functions_parent(self) -> _SageObject: ...
    def linear_constraints_parent(self) -> _SageObject: ...
    def __call__(self, x: builtins.object) -> _SageObject: ...
    def __getitem__(self, v: builtins.object) -> _SageObject: ...
    def base_ring(self) -> _SageObject: ...
    def set_problem_name(self, name: builtins.object) -> _SageObject: ...
    def new_variable(self, name: builtins.object = ...) -> _SageObject: ...
    def gen(self, i: builtins.object) -> _SageObject: ...
    def number_of_constraints(self) -> _SageObject: ...
    def number_of_variables(self) -> _SageObject: ...
    def show(self) -> _SageObject: ...
    def get_values(self, *lists: builtins.object) -> _SageObject: ...
    def set_objective(self, obj: builtins.object) -> _SageObject: ...
    def add_constraint(self, linear_function: builtins.object, name: builtins.object = ...) -> _SageObject: ...
    def solve(self, objective_only: builtins.object = ...) -> _SageObject: ...
    def dual_variable(self, i: builtins.object, sparse: builtins.object = ...) -> _SageObject: ...
    def slack(self, i: builtins.object, sparse: builtins.object = ...) -> _SageObject: ...
    def solver_parameter(self, name: builtins.object, value: builtins.object = ...) -> _SageObject: ...
    def sum(self, L: builtins.object) -> _SageObject: ...
    def get_backend(self) -> _SageObject: ...

class SDPSolverException:
    ...

class SDPVariable:
    def __init__(self, parent: builtins.object, sdp: builtins.object, name: builtins.object) -> None: ...
    def __getitem__(self, i: builtins.object) -> _SageObject: ...
    def keys(self) -> _SageObject: ...
    def items(self) -> _SageObject: ...
    def values(self) -> _SageObject: ...

class SDPVariableParent:
    ...

sdp_variable_parent: _SageObject
