from collections.abc import Iterator, Mapping

class IndexedFreeModuleElement:
    def __init__(self, M: object, x: Mapping[object, object]) -> None: ...
    def __iter__(self) -> Iterator[tuple[object, object]]: ...
    def __contains__(self, x: object) -> bool: ...
    def __hash__(self) -> int: ...
    def support(self) -> list[object]: ...
    def coefficient(self, m: object) -> object: ...
    def __getitem__(self, m: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def _add_(self, other: IndexedFreeModuleElement) -> IndexedFreeModuleElement: ...
    def _sub_(self, other: IndexedFreeModuleElement) -> IndexedFreeModuleElement: ...
    def _mul_(self, other: object) -> IndexedFreeModuleElement: ...
    def _rmul_(self, other: object) -> IndexedFreeModuleElement: ...
    def _neg_(self) -> IndexedFreeModuleElement: ...
    def __copy__(self) -> IndexedFreeModuleElement: ...
