from collections.abc import Callable, Hashable, Iterator, Mapping
from typing import Generic, TypeVar

from sage.combinat.free_module import CombinatorialFreeModule
from sage.structure.element import RingElement

_Index = TypeVar("_Index", bound=Hashable, default=Hashable)
_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)
_NewScalar = TypeVar("_NewScalar", bound=RingElement)


class IndexedFreeModuleElement(
    CombinatorialFreeModule.Element,
    Generic[_Index, _Scalar],
):
    def parent(self) -> CombinatorialFreeModule: ...
    def support(self) -> list[_Index]: ...
    def monomial_coefficients(self, copy: bool = ...) -> dict[_Index, _Scalar]: ...
    def coefficient(self, index: _Index) -> _Scalar: ...
    __getitem__ = coefficient
    def terms(self) -> Iterator[IndexedFreeModuleElement[_Index, _Scalar]]: ...
    def leading_support(self, *args: object, **kwds: object) -> _Index: ...
    def leading_coefficient(self, *args: object, **kwds: object) -> _Scalar: ...
    def leading_item(self, *args: object, **kwds: object) -> tuple[_Index, _Scalar]: ...
    def trailing_support(self, *args: object, **kwds: object) -> _Index: ...
    def trailing_coefficient(self, *args: object, **kwds: object) -> _Scalar: ...
    def map_coefficients(
        self,
        function: Callable[[_Scalar], _NewScalar],
    ) -> IndexedFreeModuleElement[_Index, _NewScalar]: ...
    def map_support(
        self,
        function: Callable[[_Index], _Index],
    ) -> IndexedFreeModuleElement[_Index, _Scalar]: ...
    def apply_multilinear_morphism(
        self,
        function: Callable[..., _NewScalar],
        *others: IndexedFreeModuleElement[_Index, _Scalar],
    ) -> _NewScalar: ...
    def tensor(
        self,
        other: IndexedFreeModuleElement[Hashable, _Scalar],
    ) -> IndexedFreeModuleElement[tuple[_Index, Hashable], _Scalar]: ...
