from collections.abc import Hashable, Iterator, Mapping, Sequence
from typing import Self

from sage.structure.element import Element
from sage.structure.parent import Parent

class IndexedFreeModuleElement:
    def __init__(self, M: Parent, x: Mapping[Hashable, Element]) -> None: ...
    def __iter__(self) -> Iterator[tuple[Hashable, Element]]: ...
    def __contains__(self, x: Hashable) -> bool: ...
    def __hash__(self) -> int: ...
    def support(self) -> Sequence[Hashable]: ...
    def coefficient(self, m: Hashable) -> Element: ...
    def __getitem__(self, m: Hashable) -> Element: ...
    def __richcmp__(self, other: Self, op: int) -> bool: ...
    def _add_(self, other: Self) -> Self: ...
    def _sub_(self, other: Self) -> Self: ...
    def _mul_(self, other: Self) -> Self: ...
    def _rmul_(self, other: Element) -> Self: ...
    def _neg_(self) -> Self: ...
    def __copy__(self) -> Self: ...
