# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def matchings(A: builtins.object, B: builtins.object) -> _SageObject: ...

def nesting(la: builtins.object, nu: builtins.object) -> _SageObject: ...

class SymmetricFunctionsNonCommutingVariables:
    def __init__(self, R: builtins.int) -> None: ...
    def a_realization(self) -> _SageObject: ...
    def dual(self) -> _SageObject: ...
    class monomial:
        def __init__(self, NCSym: builtins.object) -> None: ...
        def from_symmetric_function(self, f: builtins.object) -> _SageObject: ...
        def dual_basis(self) -> _SageObject: ...
        def duality_pairing(self, x: builtins.object, y: builtins.object) -> _SageObject: ...
        def product_on_basis(self, A: builtins.object, B: builtins.object) -> _SageObject: ...
        def coproduct_on_basis(self, A: builtins.object) -> _SageObject: ...
        def internal_coproduct_on_basis(self, A: builtins.object) -> _SageObject: ...
        def sum_of_partitions(self, la: builtins.object) -> _SageObject: ...
        class Element:
            def expand(self, n: builtins.int, alphabet: builtins.str = ...) -> _SageObject: ...
            def to_symmetric_function(self) -> _SageObject: ...
    m: _SageObject
    class elementary:
        def __init__(self, NCSym: builtins.object) -> None: ...
        class Element:
            def omega(self) -> _SageObject: ...
            def to_symmetric_function(self) -> _SageObject: ...
    e: _SageObject
    class homogeneous:
        def __init__(self, NCSym: builtins.object) -> None: ...
        class Element:
            def omega(self) -> _SageObject: ...
            def to_symmetric_function(self) -> _SageObject: ...
    h: _SageObject
    class powersum:
        def __init__(self, NCSym: builtins.object) -> None: ...
        def coproduct_on_basis(self, A: builtins.object) -> _SageObject: ...
        def internal_coproduct_on_basis(self, A: builtins.object) -> _SageObject: ...
        def antipode_on_basis(self, A: builtins.object) -> _SageObject: ...
        def primitive(self, A: builtins.object, i: builtins.int = ...) -> _SageObject: ...
        class Element:
            def to_symmetric_function(self) -> _SageObject: ...
    p: _SageObject
    class coarse_powersum:
        def __init__(self, NCSym: builtins.object) -> None: ...
    cp: _SageObject
    class x_basis:
        def __init__(self, NCSym: builtins.object) -> None: ...
    x: _SageObject
    class deformed_coarse_powersum:
        def __init__(self, NCSym: builtins.object, q: builtins.int = ...) -> None: ...
        def q(self) -> _SageObject: ...
    rho: _SageObject
    class supercharacter:
        def __init__(self, NCSym: builtins.object, q: builtins.int = ...) -> None: ...
        def q(self) -> _SageObject: ...
    chi: _SageObject
