# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class M4RIE_finite_field:
    def __dealloc__(self) -> _SageObject: ...

def poly_to_word(f: builtins.object) -> _SageObject: ...

class Matrix_gf2e_dense:
    def __cinit__(self, *args: builtins.object, alloc: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __init__(self, parent: builtins.object, entries: builtins.object = ..., copy: builtins.object = ..., coerce: builtins.object = ...) -> None: ...
    def set_unsafe(self, i: builtins.object, j: builtins.object, value: builtins.object) -> _SageObject: ...
    def get_unsafe(self, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def copy_from_unsafe(self, iDst: builtins.object, jDst: builtins.object, src: builtins.object, iSrc: builtins.object, jSrc: builtins.object) -> _SageObject: ...
    def get_is_zero_unsafe(self, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def __neg__(self) -> Self: ...
    def __copy__(self) -> Self: ...
    def __bool__(self) -> builtins.bool: ...
    def randomize(self, density: builtins.object = ..., nonzero: builtins.object = ..., *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def echelonize(self, algorithm: builtins.object = ..., reduced: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def is_invertible(self) -> builtins.bool: ...
    def __invert__(self) -> Self: ...
    def rescale_row_c(self, row: builtins.object, multiple: builtins.object, start_col: builtins.object) -> _SageObject: ...
    def add_multiple_of_row_c(self, row_to: builtins.object, row_from: builtins.object, multiple: builtins.object, start_col: builtins.object) -> _SageObject: ...
    def swap_rows_c(self, row1: builtins.object, row2: builtins.object) -> _SageObject: ...
    def swap_columns_c(self, col1: builtins.object, col2: builtins.object) -> _SageObject: ...
    def augment(self, right: builtins.object) -> _SageObject: ...
    def rank(self) -> _SageObject: ...
    def __reduce__(self) -> builtins.str | builtins.tuple[builtins.object, ...]: ...
    def slice(self) -> _SageObject: ...
    def cling(self, *C: builtins.object) -> _SageObject: ...
    def determinant(self) -> _SageObject: ...

def unpickle_matrix_gf2e_dense_v0(a: builtins.object, base_ring: builtins.object, nrows: builtins.object, ncols: builtins.object) -> _SageObject: ...
