from typing import Generic, Self, TypeVar, overload

from sage.matrix.matrix import Matrix
from sage.modules.free_module_element import FreeModuleElement
from sage.structure.element import RingElement

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)


class MatrixWindow(Generic[_Scalar]):
    def __init__(
        self,
        matrix: Matrix[_Scalar],
        row: int,
        col: int,
        nrows: int,
        ncols: int,
    ) -> None: ...
    def new_matrix_window(
        self,
        matrix: Matrix[_Scalar],
        row: int,
        col: int,
        n_rows: int,
        n_cols: int,
    ) -> Self: ...
    def matrix_window(
        self,
        row: int,
        col: int,
        n_rows: int,
        n_cols: int,
    ) -> Self: ...
    def new_empty_window(self, nrows: int, ncols: int) -> Self: ...
    def __repr__(self) -> str: ...
    def set(self, src: Self) -> None: ...
    def set_unsafe(self, i: int, j: int, x: _Scalar) -> None: ...
    def get_unsafe(self, i: int, j: int) -> _Scalar: ...
    def __setitem__(self, ij: int | tuple[int, int], x: _Scalar) -> None: ...
    @overload
    def __getitem__(self, ij: tuple[int, int]) -> _Scalar: ...
    @overload
    def __getitem__(self, ij: int) -> FreeModuleElement[_Scalar]: ...
    def matrix(self) -> Matrix[_Scalar]: ...
    def to_matrix(self) -> Matrix[_Scalar]: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def set_to(self, A: Self) -> int: ...
    def set_to_zero(self) -> None: ...
    def add(self, A: Self) -> None: ...
    def subtract(self, A: Self) -> None: ...
    def set_to_sum(self, A: Self, B: Self) -> None: ...
    def set_to_diff(self, A: Self, B: Self) -> None: ...
    def set_to_prod(self, A: Self, B: Self) -> None: ...
    def add_prod(self, A: Self, B: Self) -> None: ...
    def subtract_prod(self, A: Self, B: Self) -> None: ...
    def swap_rows(self, a: int, b: int) -> None: ...
    def echelon_in_place(self) -> tuple[int, ...]: ...
    def element_is_zero(self, i: int, j: int) -> bool: ...
