from sage.matrix.matrix import Matrix_dense
from sage.structure.parent import Parent
from sage.rings.integer import Integer
from sage.matrix.matrix_rational_dense import Matrix_rational_dense
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.ideal import Ideal_generic
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement

class Matrix_integer_dense(Matrix_dense):
    def __init__(self, parent: Parent, entries: list[object] | None = None, copy: bool | None = None, coerce: bool = True) -> None: ...
    def __copy__(self) -> Matrix_integer_dense: ...
    def __bool__(self) -> bool: ...
    def is_one(self) -> bool: ...
    def __pow__(self, n: int, dummy: object = None) -> Matrix_integer_dense: ...
    def __neg__(self) -> Matrix_integer_dense: ...
    def is_primitive(self) -> bool: ...
    def charpoly(self, var: str = 'x', algorithm: str | None = None) -> Polynomial: ...
    def minpoly(self, var: str = 'x', algorithm: str | None = None) -> Polynomial: ...
    def height(self) -> Integer: ...
    def symplectic_form(self) -> Matrix_integer_dense: ...
    def echelon_form(self, algorithm: str = 'default', proof: bool | None = None, include_zero_rows: bool = True, **kwds: object) -> Matrix_integer_dense: ...
    def saturation(self, p: int = 0, proof: bool | None = None, max_dets: int = 5) -> Matrix_integer_dense: ...
    def index_in_saturation(self, proof: bool | None = None) -> Integer: ...
    def pivots(self) -> tuple[int, ...]: ...
    def elementary_divisors(self, algorithm: str = 'pari') -> list[Integer]: ...
    def smith_form(self, transformation: bool = True, integral: bool | None = None) -> tuple[Matrix_integer_dense, Matrix_integer_dense, Matrix_integer_dense] | Matrix_integer_dense: ...
    def frobenius_form(self, flag: int = 0, var: str = 'x') -> Matrix_integer_dense: ...
    def BKZ(self, delta: float | None = None, algorithm: str = 'fpLLL', fp: str | None = None, block_size: int = 10, prune: int = 0, use_givens: bool = False, proof: bool | None = None) -> Matrix_integer_dense: ...
    def LLL(self, delta: float | None = None, eta: float | None = None, algorithm: str = 'fpLLL:wrapper', fp: str | None = None, prec: int = 0, early_red: bool = False, use_givens: bool = False, use_siegel: bool = False, transformation: bool = False, **kwds: object) -> Matrix_integer_dense | tuple[Matrix_integer_dense, Matrix_integer_dense]: ...
    def is_LLL_reduced(self, delta: float | None = None, eta: float | None = None, algorithm: str = 'fpLLL') -> bool: ...
    def prod_of_row_sums(self, cols: int | tuple[int, ...]) -> Integer: ...
    def rational_reconstruction(self, N: Integer) -> Matrix_rational_dense: ...
    def randomize(self, density: float = 1, x: int | None = None, y: int | None = None, distribution: str | None = None, **kwds: object) -> None: ...
    def rank(self, algorithm: str = 'modp') -> Integer: ...
    def determinant(self, algorithm: str = 'default', proof: bool | None = None, stabilize: int = 2) -> Integer: ...
    def __invert__(self) -> Matrix_rational_dense: ...
    def inverse_of_unit(self) -> Matrix_integer_dense: ...
    def decomposition(self, **kwds: object) -> list[FreeModule_generic]: ...
    def row(self, i: int, from_list: bool = False) -> FreeModuleElement | list[Integer]: ...
    def column(self, i: int, from_list: bool = False) -> FreeModuleElement | list[Integer]: ...
    def augment(self, right: Matrix_dense, subdivide: bool = False) -> Matrix_integer_dense: ...
    def insert_row(self, index: int, row: object) -> Matrix_integer_dense: ...
    def gcd(self) -> Integer: ...
    def transpose(self) -> Matrix_integer_dense: ...
    def antitranspose(self) -> Matrix_integer_dense: ...
    def p_minimal_polynomials(self, p: int, s_max: int | None = None) -> list[Polynomial]: ...
    def null_ideal(self, b: int = 0) -> Ideal_generic: ...
    def integer_valued_polynomials_generators(self) -> list[Polynomial]: ...
