from collections.abc import Iterable, Iterator, Sequence

from sage.categories.pushout import ConstructionFunctor
from sage.matrix.matrix2 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.with_basis.subquotient import SubmoduleWithBasis
from sage.rings.integer import Integer
from sage.rings.ring import Ring
from sage.sets.family import AbstractFamily
from sage.structure.element import Element as SageElement, RingElement
from sage.structure.parent import Parent

type MatrixEntry = RingElement | SageElement | int | Integer
type MatrixData = Matrix | Sequence[MatrixEntry] | Sequence[Sequence[MatrixEntry]]
type MatrixIndexKeys = Iterable[SageElement | int | Integer | str] | AbstractFamily

class MatrixSpace(Parent):
    def __init__(self, base_ring: Ring, nrows: int | Integer, ncols: int | Integer, sparse: bool = ..., implementation: str | type[Matrix] | None = ...) -> None: ...
    @staticmethod
    def __classcall__(cls: type[MatrixSpace], base_ring: Ring, nrows_or_row_keys: int | Integer | MatrixIndexKeys | None = ..., ncols_or_column_keys: int | Integer | MatrixIndexKeys | None = ..., sparse: bool = ..., implementation: str | type[Matrix] | None = ..., *, nrows: int | Integer | None = ..., ncols: int | Integer | None = ..., row_keys: MatrixIndexKeys | None = ..., column_keys: MatrixIndexKeys | None = ...) -> MatrixSpace: ...
    def base_ring(self) -> Ring: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def dims(self) -> tuple[int, int]: ...
    def is_finite(self) -> bool: ...
    def is_sparse(self) -> bool: ...
    def gen(self, i: int) -> Matrix: ...
    def ngens(self) -> int: ...
    def random_element(self, *args: int | Integer, **kwargs: int | Integer | bool) -> Matrix: ...
    def some_elements(self) -> Iterator[Matrix]: ...
    def zero_matrix(self) -> Matrix: ...
    def identity_matrix(self) -> Matrix: ...
    @property
    def Element(self) -> type[Matrix]: ...

    # Additional public methods from Phase 1
    def cardinality(self) -> int: ...
    def characteristic(self) -> int: ...
    def is_exact(self) -> bool: ...
    @property
    def transposed(self) -> MatrixSpace: ...
    def change_ring(self, R: Ring) -> MatrixSpace: ...
    def base_extend(self, R: Ring) -> MatrixSpace: ...
    def construction(self) -> tuple[ConstructionFunctor, Ring]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Matrix]: ...
    def __getitem__(self, x: int | Integer | str) -> Matrix | Parent: ...
    def basis(self) -> AbstractFamily: ...
    def dimension(self) -> int: ...
    def submodule(self, gens: Iterable[Matrix], check: bool = ..., already_echelonized: bool = ..., unitriangular: bool = ..., support_order: Sequence[int] | None = ..., category: Parent | None = ...) -> SubmoduleWithBasis: ...
    def diagonal_matrix(self, entries: Sequence[MatrixEntry]) -> Matrix: ...
    def is_dense(self) -> bool: ...
    def zero(self) -> Matrix: ...
    def one(self) -> Matrix: ...
    def matrix(self, x: MatrixEntry | MatrixData = ..., **kwds: bool) -> Matrix: ...
    def matrix_space(self, nrows: int | Integer | None = ..., ncols: int | Integer | None = ..., sparse: bool = ...) -> MatrixSpace: ...
    def row_space(self) -> FreeModule_generic: ...
    def column_space(self) -> FreeModule_generic: ...
    def from_vector(self, vector: Sequence[MatrixEntry], order: str = ..., coerce: bool = ...) -> Matrix: ...
