from collections.abc import Iterator, Sequence
from typing import Self, TypeVar
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_homspace import FreeModuleHomspace
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_double import RealDoubleElement
from sage.rings.complex_double import ComplexDoubleElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

import builtins

class _SageObject: ...

class Matrix_sparse:
    def is_sparse_c(self) -> builtins.bool: ...
    def is_dense_c(self) -> builtins.bool: ...
    def change_ring(self, ring: builtins.object) -> FreeModule_generic: ...
    def __copy__(self) -> Self: ...
    def transpose(self) -> Self: ...
    def antitranspose(self) -> Matrix_sparse: ...
    def charpoly(
        self, var: builtins.object = ..., **kwds: builtins.object
    ) -> Polynomial: ...
    def determinant(self, **kwds: builtins.object) -> _Scalar: ...
    def apply_morphism(self, phi: builtins.object) -> Matrix_sparse: ...
    def apply_map(
        self,
        phi: builtins.object,
        R: builtins.object = ...,
        sparse: builtins.object = ...,
    ) -> Matrix_sparse: ...
    def density(self) -> Matrix_sparse: ...
    def matrix_from_rows_and_columns(
        self, rows: builtins.object, columns: builtins.object
    ) -> Matrix[_Scalar]: ...
    def augment(
        self, right: builtins.object, subdivide: builtins.object = ...
    ) -> Matrix_sparse: ...

def get_ij(
    v: builtins.object, i: builtins.object, j: builtins.object
) -> ElementConstructorInput: ...
