from collections.abc import Mapping, Sequence
from typing import Self

from sage.matrix.matrix_integer_dense import Matrix_integer_dense
from sage.matrix.matrix_sparse import Matrix_sparse
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.parent import ElementConstructorInput, Parent


class Matrix_integer_sparse(Matrix_sparse[Integer]):
    def __init__(
        self,
        parent: Parent[Self],
        entries: Sequence[ElementConstructorInput]
        | Mapping[tuple[int, int], ElementConstructorInput]
        | ElementConstructorInput = ...,
        copy: bool = ...,
        coerce: bool = ...,
    ) -> None: ...
    def __copy__(self) -> Self: ...
    def dict(self, copy: bool = ...) -> dict[tuple[int, int], Integer]: ...
    def row(self, i: int, from_list: bool = ...) -> FreeModuleElement[Integer]: ...
    def column(self, j: int, from_list: bool = ...) -> FreeModuleElement[Integer]: ...
    def determinant(self, algorithm: str = ...) -> Integer: ...
    det = determinant
    def trace(self) -> Integer: ...
    def rank(self, algorithm: str = ...) -> int: ...
    def echelonize(self, algorithm: str = ..., **kwds: object) -> None: ...
    def echelon_form(self, algorithm: str = ..., **kwds: object) -> Self: ...
    def characteristic_polynomial(self, var: str = ...) -> Polynomial: ...
    charpoly = characteristic_polynomial
    def transpose(self) -> Self: ...
    def dense_matrix(self) -> Matrix_integer_dense: ...
