# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Matrix_integer_sparse:
    def __cinit__(self) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __init__(self, parent: builtins.object, entries: builtins.object = ..., copy: builtins.object = ..., coerce: builtins.object = ...) -> None: ...
    def set_unsafe(self, i: builtins.object, j: builtins.object, x: builtins.object) -> _SageObject: ...
    def get_unsafe(self, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def copy_from_unsafe(self, iDst: builtins.object, jDst: builtins.object, src: builtins.object, iSrc: builtins.object, jSrc: builtins.object) -> _SageObject: ...
    def get_is_zero_unsafe(self, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def rational_reconstruction(self, N: builtins.object) -> _SageObject: ...
    def elementary_divisors(self, algorithm: builtins.object = ...) -> _SageObject: ...
    def smith_form(self, transformation: builtins.object = ..., integral: builtins.object = ...) -> _SageObject: ...
    def rank(self, algorithm: builtins.object = ...) -> _SageObject: ...
    def charpoly(self, var: builtins.object = ..., algorithm: builtins.object = ...) -> _SageObject: ...
    def minpoly(self, var: builtins.object = ..., algorithm: builtins.object = ...) -> _SageObject: ...
