# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def matrix_to_acb_mat(target: builtins.object, source: builtins.object) -> _SageObject: ...

def acb_mat_to_matrix(source: builtins.object, CIF: builtins.object) -> _SageObject: ...

def prec(mat: builtins.object) -> _SageObject: ...

class Matrix_complex_ball_dense:
    def __cinit__(self) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __init__(self, parent: builtins.object, entries: builtins.object = ..., copy: builtins.object = ..., coerce: builtins.object = ...) -> None: ...
    def set_unsafe(self, i: builtins.object, j: builtins.object, x: builtins.object) -> _SageObject: ...
    def get_unsafe(self, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def copy_from_unsafe(self, iDst: builtins.object, jDst: builtins.object, src: builtins.object, iSrc: builtins.object, jSrc: builtins.object) -> _SageObject: ...
    def identical(self, other: builtins.object) -> _SageObject: ...
    def overlaps(self, other: builtins.object) -> _SageObject: ...
    def contains(self, other: builtins.object) -> _SageObject: ...
    def __neg__(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def transpose(self) -> _SageObject: ...
    def determinant(self) -> _SageObject: ...
    def trace(self) -> _SageObject: ...
    def charpoly(self, var: builtins.object = ..., algorithm: builtins.object = ...) -> _SageObject: ...
    def eigenvalues(self, other: builtins.object = ..., extend: builtins.object = ...) -> _SageObject: ...
    def eigenvectors_right_approx(self, other: builtins.object = ..., extend: builtins.object = ...) -> _SageObject: ...
    def eigenvectors_right(self, other: builtins.object = ..., extend: builtins.object = ...) -> _SageObject: ...
    def eigenvectors_left_approx(self, other: builtins.object = ..., extend: builtins.object = ...) -> _SageObject: ...
    def eigenvectors_left(self, other: builtins.object = ..., extend: builtins.object = ...) -> _SageObject: ...
    def exp(self) -> _SageObject: ...
