from collections.abc import Iterator, Sequence
from typing import Self, TypeVar
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_homspace import FreeModuleHomspace
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_double import RealDoubleElement
from sage.rings.complex_double import ComplexDoubleElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

class Matrix(Matrix_element):
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def base_ring(self) -> CommutativeRing: ...
    def det(self, *args: str | None, **kwds: str | bool | None) -> _Scalar: ...
    def rank(self) -> Integer: ...
    def trace(self) -> _Scalar: ...
    def transpose(self) -> ElementConstructorInput: ...
    def inverse(self) -> ElementConstructorInput: ...
    def is_square(self) -> bool: ...
    def is_invertible(self) -> bool: ...
    def change_ring(self, ring: CommutativeRing) -> Matrix: ...
    def submatrix(
        self,
        row: int = 0,
        col: int = 0,
        nrows: int | None = None,
        ncols: int | None = None,
    ) -> Matrix[_Scalar]: ...
    def augment(
        self, right: ElementConstructorInput, subdivide: bool = False
    ) -> ElementConstructorInput: ...
    def stack(
        self, bottom: ElementConstructorInput, subdivide: bool = False
    ) -> ElementConstructorInput: ...

class Matrix_dense(Matrix):
    def __copy__(self) -> Matrix_dense: ...
    def transpose(self) -> Matrix_dense: ...
    def antitranspose(self) -> Matrix_dense: ...
