from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Generic, Self, TypeVar

from sage.categories.pushout import ConstructionFunctor
from sage.matrix.matrix import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.rings.integer import Integer
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput, Parent

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)
_NewScalar = TypeVar("_NewScalar", bound=RingElement)

type MatrixIndexKeys = Iterable[object] | Parent
type MatrixData = (
    Matrix[_Scalar]
    | Sequence[ElementConstructorInput]
    | Sequence[Sequence[ElementConstructorInput]]
    | Mapping[tuple[int, int], ElementConstructorInput]
)


class MatrixSpace(Parent[Matrix[_Scalar]], Generic[_Scalar]):
    Element: type[Matrix[_Scalar]]

    @staticmethod
    def __classcall__(
        class_: type[MatrixSpace[_Scalar]],
        base_ring: Parent[_Scalar],
        nrows_or_row_keys: int | Integer | MatrixIndexKeys | None = ...,
        ncols_or_column_keys: int | Integer | MatrixIndexKeys | None = ...,
        sparse: bool = ...,
        implementation: str | type[Matrix[_Scalar]] | None = ...,
        *,
        nrows: int | Integer | None = ...,
        ncols: int | Integer | None = ...,
        row_keys: MatrixIndexKeys | None = ...,
        column_keys: MatrixIndexKeys | None = ...,
    ) -> MatrixSpace[_Scalar]: ...
    def __init__(
        self,
        base_ring: Parent[_Scalar],
        nrows: int | Integer,
        ncols: int | Integer,
        sparse: bool = ...,
        implementation: str | type[Matrix[_Scalar]] | None = ...,
    ) -> None: ...
    def base_ring(self) -> Parent[_Scalar]: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def dimensions(self) -> tuple[int, int]: ...
    dims = dimensions
    def is_sparse(self) -> bool: ...
    def is_dense(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def cardinality(self) -> Integer: ...
    def characteristic(self) -> Integer: ...
    def dimension(self) -> int: ...
    def ngens(self) -> int: ...
    def gen(self, i: int) -> Matrix[_Scalar]: ...
    def gens(self) -> tuple[Matrix[_Scalar], ...]: ...
    def basis(self) -> tuple[Matrix[_Scalar], ...]: ...
    def zero(self) -> Matrix[_Scalar]: ...
    zero_matrix = zero
    def one(self) -> Matrix[_Scalar]: ...
    identity_matrix = one
    def random_element(self, *args: object, **kwds: object) -> Matrix[_Scalar]: ...
    def some_elements(self) -> Iterator[Matrix[_Scalar]]: ...
    def __iter__(self) -> Iterator[Matrix[_Scalar]]: ...
    def _element_constructor_(
        self,
        entries: MatrixData[_Scalar] | ElementConstructorInput = ...,
        **kwds: object,
    ) -> Matrix[_Scalar]: ...
    def matrix(
        self,
        entries: MatrixData[_Scalar] | ElementConstructorInput = ...,
        **kwds: object,
    ) -> Matrix[_Scalar]: ...
    def diagonal_matrix(self, entries: Sequence[ElementConstructorInput]) -> Matrix[_Scalar]: ...
    def row_space(self) -> FreeModule_generic[_Scalar]: ...
    def column_space(self) -> FreeModule_generic[_Scalar]: ...
    def transposed(self) -> MatrixSpace[_Scalar]: ...
    def change_ring(self, ring: Parent[_NewScalar]) -> MatrixSpace[_NewScalar]: ...
    def base_extend(self, ring: Parent[_NewScalar]) -> MatrixSpace[_NewScalar]: ...
    def construction(self) -> tuple[ConstructionFunctor, Parent[_Scalar]]: ...
