from collections.abc import Iterator, Sequence
from typing import Self, TypeVar
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_homspace import FreeModuleHomspace
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_double import RealDoubleElement
from sage.rings.complex_double import ComplexDoubleElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

import builtins

class _SageObject: ...

class Matrix_polynomial_dense:
    def degree(self) -> Integer: ...
    def degree_matrix(
        self, shifts: builtins.object = ..., row_wise: builtins.object = ...
    ) -> Matrix[_Scalar]: ...
    def constant_matrix(self) -> Matrix[_Scalar]: ...
    def is_constant(self) -> builtins.bool: ...
    def coefficient_matrix(
        self, d: builtins.object, row_wise: builtins.object = ...
    ) -> Matrix[_Scalar]: ...
    def truncate(
        self, d: builtins.object, row_wise: builtins.object = ...
    ) -> Matrix_polynomial_dense: ...
    def shift(
        self, d: builtins.object, row_wise: builtins.object = ...
    ) -> Matrix_polynomial_dense: ...
    def reverse(
        self,
        degree: builtins.object = ...,
        row_wise: builtins.object = ...,
        entry_wise: builtins.object = ...,
    ) -> Matrix_polynomial_dense: ...
    def inverse_series_trunc(self, d: builtins.object) -> Matrix_polynomial_dense: ...
    def solve_left_series_trunc(
        self, B: builtins.object, d: builtins.object
    ) -> Matrix_polynomial_dense: ...
    def solve_right_series_trunc(
        self, B: builtins.object, d: builtins.object
    ) -> Matrix_polynomial_dense: ...
    def row_degrees(self, shifts: builtins.object = ...) -> Matrix_polynomial_dense: ...
    def column_degrees(
        self, shifts: builtins.object = ...
    ) -> Matrix_polynomial_dense: ...
    def leading_matrix(
        self, shifts: builtins.object = ..., row_wise: builtins.object = ...
    ) -> Matrix[_Scalar]: ...
    def hermite_form(
        self,
        include_zero_rows: builtins.object = ...,
        transformation: builtins.object = ...,
    ) -> Matrix_polynomial_dense: ...
    def left_quo_rem(self, B: builtins.object) -> Matrix_polynomial_dense: ...
    def right_quo_rem(self, B: builtins.object) -> Matrix_polynomial_dense: ...
    def reduce(
        self,
        B: builtins.object,
        shifts: builtins.object = ...,
        row_wise: builtins.object = ...,
        return_quotient: builtins.object = ...,
    ) -> Matrix_polynomial_dense: ...
    def basis_completion(
        self, row_wise: builtins.object = ..., algorithm: builtins.object = ...
    ) -> Matrix_polynomial_dense: ...
