# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Matrix_double_sparse:
    def is_hermitian(self, tolerance: builtins.object = ...) -> builtins.bool: ...
    def is_skew_hermitian(self, tolerance: builtins.object = ...) -> builtins.bool: ...
    def cholesky(self) -> _SageObject: ...
