# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

ai: _SageObject
MAX_MODULUS: _SageObject
class Matrix_modn_sparse:
    def __cinit__(self) -> _SageObject: ...
    def __dealloc__(self) -> _SageObject: ...
    def __init__(self, parent: builtins.object, entries: builtins.object = ..., copy: builtins.object = ..., coerce: builtins.object = ...) -> None: ...
    def set_unsafe(self, i: builtins.object, j: builtins.object, value: builtins.object) -> _SageObject: ...
    def get_unsafe(self, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def copy_from_unsafe(self, iDst: builtins.object, jDst: builtins.object, src: builtins.object, iSrc: builtins.object, jSrc: builtins.object) -> _SageObject: ...
    def get_is_zero_unsafe(self, i: builtins.object, j: builtins.object) -> _SageObject: ...
    def swap_rows(self, r1: builtins.object, r2: builtins.object) -> _SageObject: ...
    def swap_rows_c(self, n1: builtins.object, n2: builtins.object) -> _SageObject: ...
    def density(self) -> _SageObject: ...
    def transpose(self) -> _SageObject: ...
    def matrix_from_rows(self, rows: builtins.object) -> _SageObject: ...
    def matrix_from_columns(self, cols: builtins.object) -> _SageObject: ...
    def rank(self, algorithm: builtins.object = ...) -> _SageObject: ...
    def determinant(self, algorithm: builtins.object = ...) -> _SageObject: ...
