# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class Matrix_sparse:
    def is_sparse_c(self) -> builtins.bool: ...
    def is_dense_c(self) -> builtins.bool: ...
    def change_ring(self, ring: builtins.object) -> _SageObject: ...
    def __copy__(self) -> Self: ...
    def transpose(self) -> _SageObject: ...
    def antitranspose(self) -> _SageObject: ...
    def charpoly(self, var: builtins.object = ..., **kwds: builtins.object) -> _SageObject: ...
    def determinant(self, **kwds: builtins.object) -> _SageObject: ...
    def apply_morphism(self, phi: builtins.object) -> _SageObject: ...
    def apply_map(self, phi: builtins.object, R: builtins.object = ..., sparse: builtins.object = ...) -> _SageObject: ...
    def density(self) -> _SageObject: ...
    def matrix_from_rows_and_columns(self, rows: builtins.object, columns: builtins.object) -> _SageObject: ...
    def augment(self, right: builtins.object, subdivide: builtins.object = ...) -> _SageObject: ...

def get_ij(v: builtins.object, i: builtins.object, j: builtins.object) -> _SageObject: ...
