from sage.sets.family import Family
from sage.modules.with_basis.subquotient import SubmoduleWithBasis
from sage.modules.free_module import FreeModule_generic
from collections.abc import Iterator
from sage.matrix.matrix import Matrix
from sage.rings.ring import CommutativeRing

class MatrixSpace:
    def __init__(self, base_ring: CommutativeRing, nrows: int, ncols: int, sparse: bool, implementation: type) -> None: ...
    @staticmethod
    def __classcall__(cls: type[MatrixSpace], base_ring: CommutativeRing, nrows_or_row_keys: object = ..., ncols_or_column_keys: object = ..., sparse: bool = ..., implementation: object = ..., *, nrows: int | None = ..., ncols: int | None = ..., row_keys: object = ..., column_keys: object = ..., **kwds: object) -> MatrixSpace: ...
    def base_ring(self) -> CommutativeRing: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def dims(self) -> tuple[int, int]: ...
    def is_finite(self) -> bool: ...
    def is_sparse(self) -> bool: ...
    def gen(self, i: int) -> Matrix: ...
    def ngens(self) -> int: ...
    def random_element(self, *args: object, **kwargs: object) -> Matrix: ...
    def some_elements(self) -> Iterator[Matrix]: ...
    def zero_matrix(self) -> Matrix: ...
    def identity_matrix(self) -> Matrix: ...
    def __call__(self, entries: object) -> Matrix: ...
    @property
    def Element(self) -> type[Matrix]: ...

    # Additional public methods from Phase 1
    def cardinality(self) -> int: ...
    def characteristic(self) -> int: ...
    def is_exact(self) -> bool: ...
    @property
    def transposed(self) -> MatrixSpace: ...
    def change_ring(self, R: CommutativeRing) -> MatrixSpace: ...
    def base_extend(self, R: CommutativeRing) -> MatrixSpace: ...
    def construction(self) -> tuple[object, CommutativeRing]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Matrix]: ...
    def __getitem__(self, x: object) -> Matrix: ...
    def basis(self) -> Family: ...
    def dimension(self) -> int: ...
    def submodule(self, gens: object, check: bool = ..., already_echelonized: bool = ..., unitriangular: bool = ..., support_order: object = ..., category: object = ..., *args: object, **opts: object) -> SubmoduleWithBasis: ...
    def diagonal_matrix(self, entries: list[object]) -> Matrix: ...
    def is_dense(self) -> bool: ...
    def zero(self) -> Matrix: ...
    def one(self) -> Matrix: ...
    def matrix(self, x: object = ..., **kwds: object) -> Matrix: ...
    def matrix_space(self, nrows: int | None = ..., ncols: int | None = ..., sparse: bool = ...) -> MatrixSpace: ...
    def row_space(self) -> FreeModule_generic: ...
    def column_space(self) -> FreeModule_generic: ...
    def from_vector(self, vector: object, order: object = ..., coerce: bool = ...) -> Matrix: ...
