from collections.abc import Iterator, Sequence
from typing import Self, TypeVar
from sage.matrix.matrix0 import Matrix
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_homspace import FreeModuleHomspace
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.rings.real_double import RealDoubleElement
from sage.rings.complex_double import ComplexDoubleElement
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.ring import Ring
from sage.structure.element import RingElement
from sage.structure.parent import ElementConstructorInput
from sage.structure.sage_object import SageObject
from sage.symbolic.expression import Expression

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

import builtins

class _SageObject: ...

class MatrixWindow:
    def new_empty_window(
        self, nrows: builtins.object, ncols: builtins.object
    ) -> ElementConstructorInput: ...
    def set(self, src: builtins.object) -> ElementConstructorInput: ...
    def set_unsafe(
        self, i: builtins.object, j: builtins.object, x: builtins.object
    ) -> ElementConstructorInput: ...
    def get_unsafe(
        self, i: builtins.object, j: builtins.object
    ) -> ElementConstructorInput: ...
    def __setitem__(self, ij: builtins.object, x: builtins.object) -> None: ...
    def __getitem__(
        self, ij: builtins.object
    ) -> FreeModuleElement[_Scalar] | _Scalar: ...
    def matrix(self) -> Matrix[_Scalar]: ...
    def to_matrix(self) -> Matrix[_Scalar]: ...
    def nrows(self) -> Integer: ...
    def ncols(self) -> Integer: ...
    def set_to(self, A: builtins.object) -> ElementConstructorInput: ...
    def set_to_zero(self) -> ElementConstructorInput: ...
    def add(self, A: builtins.object) -> ElementConstructorInput: ...
    def subtract(self, A: builtins.object) -> ElementConstructorInput: ...
    def set_to_sum(
        self, A: builtins.object, B: builtins.object
    ) -> ElementConstructorInput: ...
    def set_to_diff(
        self, A: builtins.object, B: builtins.object
    ) -> ElementConstructorInput: ...
    def set_to_prod(
        self, A: builtins.object, B: builtins.object
    ) -> ElementConstructorInput: ...
    def add_prod(
        self, A: builtins.object, B: builtins.object
    ) -> ElementConstructorInput: ...
    def subtract_prod(
        self, A: builtins.object, B: builtins.object
    ) -> ElementConstructorInput: ...
    def swap_rows(
        self, a: builtins.object, b: builtins.object
    ) -> ElementConstructorInput: ...
    def echelon_in_place(self) -> ElementConstructorInput: ...
    def element_is_zero(
        self, i: builtins.object, j: builtins.object
    ) -> ElementConstructorInput: ...
