from collections.abc import Iterator
from typing import Generic, Self, TypeVar

from sage.matrix.matrix import Matrix
from sage.modules.free_module_element import FreeModuleElement
from sage.structure.element import RingElement

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)


class MatrixWindow(Generic[_Scalar]):
    def __init__(
        self,
        matrix: Matrix[_Scalar],
        row: int,
        col: int,
        nrows: int,
        ncols: int,
    ) -> None: ...
    def matrix(self) -> Matrix[_Scalar]: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def dimensions(self) -> tuple[int, int]: ...
    def row(self, i: int) -> FreeModuleElement[_Scalar]: ...
    def column(self, j: int) -> FreeModuleElement[_Scalar]: ...
    def __iter__(self) -> Iterator[FreeModuleElement[_Scalar]]: ...
    def __getitem__(self, key: tuple[int, int]) -> _Scalar: ...
    def __setitem__(self, key: tuple[int, int], value: _Scalar) -> None: ...
    def window(
        self,
        row: int,
        col: int,
        nrows: int,
        ncols: int,
    ) -> Self: ...
    def set_to_zero(self) -> None: ...
    def set_to_identity(self) -> None: ...
    def add(self, left: Self, right: Self) -> None: ...
    def subtract(self, left: Self, right: Self) -> None: ...
    def multiply(self, left: Self, right: Self) -> None: ...
    def to_matrix(self) -> Matrix[_Scalar]: ...
