from typing import Generic, Self, TypeVar

from numpy import ndarray

from sage.matrix.matrix_dense import Matrix_dense
from sage.modules.free_module_element import FreeModuleElement
from sage.structure.element import RingElement

_DoubleScalar = TypeVar(
    "_DoubleScalar",
    bound=RingElement,
    default=RingElement,
)


class Matrix_double_dense(Matrix_dense[_DoubleScalar], Generic[_DoubleScalar]):
    def numpy(self) -> ndarray: ...
    def norm(self, p: int | float | str = ...) -> float: ...
    def condition(self, p: int | float | str = ...) -> float: ...
    def singular_values(self, eps: float | None = ...) -> list[float]: ...
    def SVD(self) -> tuple[Self, Self, Self]: ...
    def QR(self) -> tuple[Self, Self]: ...
    def schur(self) -> tuple[Self, Self]: ...
    def exp(self) -> Self: ...
    def logarithm(self) -> Self: ...
    def pseudoinverse(self, eps: float | None = ...) -> Self: ...
    def solve_right(self, B: Self | FreeModuleElement[_DoubleScalar]) -> Self | FreeModuleElement[_DoubleScalar]: ...
    def solve_left(self, B: Self | FreeModuleElement[_DoubleScalar]) -> Self | FreeModuleElement[_DoubleScalar]: ...
