from collections.abc import Callable, Iterable, Sequence
from typing import Generic, TypeVar

from sage.matrix.matrix import Matrix
from sage.plot.graphics import Graphics
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.structure.parent import ElementConstructorInput, Parent
from sage.structure.sage_object import SageObject

_Element = TypeVar("_Element")


class OperationTable(SageObject, Generic[_Element]):
    def __init__(
        self,
        S: Parent[_Element] | Iterable[_Element],
        operation: Callable[[_Element, _Element], _Element],
        names: str | Sequence[str] = ...,
        elements: Iterable[_Element | ElementConstructorInput] | None = ...,
        closed: bool = ...,
    ) -> None: ...
    def _name_maker(
        self,
        names: str | Sequence[str],
    ) -> tuple[int, list[str], list[str], dict[str, _Element]]: ...
    def __getitem__(self, pair: tuple[_Element, _Element]) -> _Element: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def _repr_(self) -> str: ...
    def set_print_symbols(self, ascii: str, latex: str) -> None: ...
    def column_keys(self) -> tuple[_Element, ...]: ...
    row_keys = column_keys
    def translation(self) -> dict[str, _Element]: ...
    def table(self) -> list[list[int]]: ...
    def change_names(self, names: str | Sequence[str]) -> None: ...
    def matrix_of_variables(self) -> Matrix[Polynomial]: ...
    def color_table(
        self,
        element_names: bool = ...,
        cmap: object | None = ...,
        **options: object,
    ) -> Graphics: ...
    def gray_table(self, **options: object) -> Graphics: ...
    def _ascii_table(self) -> str: ...
    def _latex_(self) -> str: ...
