from collections.abc import Sequence
from typing import overload

from sage.matrix.matrix0 import Matrix as _ConcreteMatrix
from sage.rings.integer import Integer
from sage.structure.element import Element, Matrix

type MatrixBlock = Matrix | Sequence[Sequence[Element | int | Integer]]

def block_diagonal_matrix(
    self, *blocks: MatrixBlock, sparse: bool = ...
) -> _ConcreteMatrix: ...
def identity_matrix(self, n: int | Integer = ..., sparse: bool = ...) -> Matrix: ...
def column_matrix(
    self, entries: Sequence[Element | int | Integer], sparse: bool = ...
) -> Matrix: ...
@overload
def diagonal_matrix(self, sparse: bool = ...) -> _ConcreteMatrix: ...
@overload
def diagonal_matrix(
    self, entries: Sequence[int | Integer], sparse: bool = ...
) -> _ConcreteMatrix: ...
