# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

cyclic_shift: _SageObject
def MOLS_10_2() -> _SageObject: ...

def MOLS_12_5() -> _SageObject: ...

def MOLS_14_4() -> _SageObject: ...

def MOLS_15_4() -> _SageObject: ...

def MOLS_18_3() -> _SageObject: ...

MOLS_constructions: _SageObject
LIST_OF_MOLS_CONSTRUCTIONS: _SageObject
def OA_7_18() -> _SageObject: ...

def OA_9_40() -> _SageObject: ...

def OA_7_66() -> _SageObject: ...

def OA_7_68() -> _SageObject: ...

def OA_8_69() -> _SageObject: ...

def OA_7_74() -> _SageObject: ...

def OA_8_76() -> _SageObject: ...

def OA_11_80() -> _SageObject: ...

def OA_15_112() -> _SageObject: ...

def OA_9_120() -> _SageObject: ...

def OA_9_135() -> _SageObject: ...

def OA_11_160() -> _SageObject: ...

def OA_16_176() -> _SageObject: ...

def OA_11_185() -> _SageObject: ...

def OA_10_205() -> _SageObject: ...

def OA_16_208() -> _SageObject: ...

def OA_15_224() -> _SageObject: ...

def OA_11_254() -> _SageObject: ...

def OA_20_352() -> _SageObject: ...

def OA_20_416() -> _SageObject: ...

def OA_20_544() -> _SageObject: ...

def OA_17_560() -> _SageObject: ...

def OA_11_640() -> _SageObject: ...

def OA_10_796() -> _SageObject: ...

def OA_10_469() -> _SageObject: ...

def OA_520_plus_x(x: builtins.object) -> _SageObject: ...

def OA_10_520() -> _SageObject: ...

def OA_12_522() -> _SageObject: ...

def OA_14_524() -> _SageObject: ...

def OA_15_896() -> _SageObject: ...

def OA_9_1078() -> _SageObject: ...

def OA_25_1262() -> _SageObject: ...

def OA_9_1612() -> _SageObject: ...

def OA_10_1620() -> _SageObject: ...

OA_constructions: _SageObject
LIST_OF_OA_CONSTRUCTIONS: _SageObject
def QDM_19_6_1_1_1() -> _SageObject: ...

def QDM_21_5_1_1_1() -> _SageObject: ...

def QDM_21_6_1_1_5() -> _SageObject: ...

def QDM_25_6_1_1_5() -> _SageObject: ...

def QDM_33_6_1_1_1() -> _SageObject: ...

def QDM_37_6_1_1_1() -> _SageObject: ...

def QDM_35_7_1_1_7() -> _SageObject: ...

def QDM_45_7_1_1_9() -> _SageObject: ...

def QDM_54_7_1_1_8() -> _SageObject: ...

def QDM_57_9_1_1_8() -> _SageObject: ...

QDM: _SageObject
LIST_OF_QDM: _SageObject
Vmt_vectors: _SageObject
LIST_OF_VMT_VECTORS: _SageObject
DF: _SageObject
LIST_OF_DF: _SageObject
def DM_12_6_1() -> _SageObject: ...

def DM_21_6_1() -> _SageObject: ...

def DM_24_8_1() -> _SageObject: ...

def DM_28_6_1() -> _SageObject: ...

def DM_33_6_1() -> _SageObject: ...

def DM_35_6_1() -> _SageObject: ...

def DM_36_9_1() -> _SageObject: ...

def DM_39_6_1() -> _SageObject: ...

def DM_44_6_1() -> _SageObject: ...

def DM_45_7_1() -> _SageObject: ...

def DM_48_9_1() -> _SageObject: ...

def DM_51_6_1() -> _SageObject: ...

def DM_52_6_1() -> _SageObject: ...

def DM_55_7_1() -> _SageObject: ...

def DM_56_8_1() -> _SageObject: ...

def DM_57_8_1() -> _SageObject: ...

def DM_60_6_1() -> _SageObject: ...

def DM_75_8_1() -> _SageObject: ...

def DM_273_17_1() -> _SageObject: ...

def DM_993_32_1() -> _SageObject: ...

DM: _SageObject
LIST_OF_DM: _SageObject
def RBIBD_120_8_1() -> _SageObject: ...

def BIBD_45_9_8(from_code: builtins.bool = ...) -> _SageObject: ...

def BIBD_66_6_1() -> _SageObject: ...

def BIBD_76_6_1() -> _SageObject: ...

def BIBD_96_6_1() -> _SageObject: ...

def BIBD_106_6_1() -> _SageObject: ...

def BIBD_111_6_1() -> _SageObject: ...

def BIBD_126_6_1() -> _SageObject: ...

def BIBD_136_6_1() -> _SageObject: ...

def BIBD_141_6_1() -> _SageObject: ...

def BIBD_171_6_1() -> _SageObject: ...

def HigmanSimsDesign() -> _SageObject: ...

def BIBD_196_6_1() -> _SageObject: ...

def BIBD_201_6_1() -> _SageObject: ...

def BIBD_79_13_2() -> _SageObject: ...

def BIBD_56_11_2() -> _SageObject: ...

BIBD_constructions: _SageObject
LIST_OF_BIBD: _SageObject
R: _SageObject
a: _SageObject
EDS: _SageObject
LIST_OF_EDS: _SageObject
def ca_11_2_5_3() -> _SageObject: ...

def ca_12_2_7_3() -> _SageObject: ...

def ca_13_2_9_3() -> _SageObject: ...

def ca_14_2_10_3() -> _SageObject: ...

def ca_15_2_20_3() -> _SageObject: ...

def ca_19_2_6_4() -> _SageObject: ...

def ca_21_2_7_4() -> _SageObject: ...

def ca_29_2_7_5() -> _SageObject: ...

def ca_37_2_4_6() -> _SageObject: ...

def ca_39_2_5_6() -> _SageObject: ...

def ca_41_2_6_6() -> _SageObject: ...

CA_constructions: _SageObject
LIST_OF_CA_CONSTRUCTIONS: _SageObject
