# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def is_covering_array(array: builtins.object, strength: builtins.object = ..., levels: builtins.object = ..., verbose: builtins.object = ..., parameters: builtins.object = ...) -> builtins.bool: ...

def is_orthogonal_array(OA: builtins.object, k: builtins.object, n: builtins.object, t: builtins.object = ..., verbose: builtins.object = ..., terminology: builtins.object = ...) -> builtins.bool: ...

def is_group_divisible_design(groups: builtins.object, blocks: builtins.object, v: builtins.object, G: builtins.object = ..., K: builtins.object = ..., lambd: builtins.object = ..., verbose: builtins.object = ...) -> builtins.bool: ...

def is_pairwise_balanced_design(blocks: builtins.object, v: builtins.object, K: builtins.object = ..., lambd: builtins.object = ..., verbose: builtins.object = ...) -> builtins.bool: ...

def is_projective_plane(blocks: builtins.object, verbose: builtins.object = ...) -> builtins.bool: ...

def is_difference_matrix(M: builtins.object, G: builtins.object, k: builtins.object, lmbda: builtins.object = ..., verbose: builtins.object = ...) -> builtins.bool: ...

def is_quasi_difference_matrix(M: builtins.object, G: builtins.object, k: builtins.object, lmbda: builtins.object, mu: builtins.object, u: builtins.object, verbose: builtins.object = ...) -> builtins.bool: ...
