# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def group_law(G: builtins.object) -> builtins.tuple[_SageObject, ...]: ...

def block_stabilizer(G: builtins.object, B: builtins.object) -> builtins.list[_SageObject]: ...

def is_difference_family(G: builtins.object, D: builtins.object, v: builtins.object = ..., k: builtins.int = ..., l: builtins.object = ..., verbose: builtins.bool = ...) -> builtins.bool: ...

def singer_difference_set(q: builtins.int, d: builtins.object) -> builtins.tuple[_SageObject, ...]: ...

def df_q_6_1(K: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def radical_difference_set(K: builtins.int, k: builtins.int, l: builtins.int = ..., existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def one_cyclic_tiling(A: builtins.object, n: builtins.int) -> _SageObject: ...

def one_radical_difference_family(K: builtins.int, k: builtins.int) -> _SageObject: ...

def radical_difference_family(K: builtins.int, k: builtins.int, l: builtins.int = ..., existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def twin_prime_powers_difference_set(p: builtins.int, check: builtins.bool = ...) -> _SageObject: ...

def are_mcfarland_1973_parameters(v: builtins.object, k: builtins.int, lmbda: builtins.object, return_parameters: builtins.bool = ...) -> _SageObject: ...

def mcfarland_1973_construction(q: builtins.int, s: builtins.object) -> _SageObject: ...

def are_hadamard_difference_set_parameters(v: builtins.object, k: builtins.int, lmbda: builtins.object) -> _SageObject: ...

def hadamard_difference_set_product_parameters(N: builtins.int) -> _SageObject: ...

def hadamard_difference_set_product(G1: builtins.object, D1: builtins.object, G2: builtins.object, D2: builtins.object) -> _SageObject: ...

def turyn_1965_3x3xK(k: builtins.int = ...) -> _SageObject: ...

def relative_difference_set_from_m_sequence(q: builtins.int, N: builtins.int, check: builtins.bool = ..., return_group: builtins.bool = ...) -> _SageObject: ...

def relative_difference_set_from_homomorphism(q: builtins.int, N: builtins.int, d: builtins.object, check: builtins.bool = ..., return_group: builtins.bool = ...) -> _SageObject: ...

def is_relative_difference_set(R: builtins.int, G: builtins.object, H: builtins.object, params: builtins.object, verbose: builtins.bool = ...) -> builtins.bool: ...

def is_supplementary_difference_set(Ks: builtins.object, v: builtins.object = ..., lmbda: builtins.object = ..., G: builtins.object = ..., verbose: builtins.bool = ...) -> builtins.bool: ...

def supplementary_difference_set_from_rel_diff_set(q: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def get_fixed_relative_difference_set(G: builtins.object, rel_diff_set: builtins.object, as_elements: builtins.bool = ...) -> _SageObject: ...

def is_fixed_relative_difference_set(R: builtins.int, q: builtins.int) -> builtins.bool: ...

def skew_supplementary_difference_set_over_polynomial_ring(n: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def skew_supplementary_difference_set_with_paley_todd(n: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def spin_goethals_seidel_difference_family(n: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def skew_spin_goethals_seidel_difference_family(n: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def skew_supplementary_difference_set(n: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ..., return_group: builtins.bool = ...) -> _SageObject: ...

def supplementary_difference_set_hadamard(n: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def are_complementary_difference_sets(G: builtins.object, A: builtins.object, B: builtins.object, verbose: builtins.bool = ...) -> _SageObject: ...

def complementary_difference_setsI(n: builtins.int, check: builtins.bool = ...) -> _SageObject: ...

def complementary_difference_setsII(n: builtins.int, check: builtins.bool = ...) -> _SageObject: ...

def complementary_difference_setsIII(n: builtins.int, check: builtins.bool = ...) -> _SageObject: ...

def complementary_difference_sets(n: builtins.int, existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def difference_family(v: builtins.object, k: builtins.int, l: builtins.int = ..., existence: builtins.bool = ..., explain_construction: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...
