# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def find_product_decomposition(g: builtins.object, k: builtins.int, lmbda: builtins.int = ...) -> _SageObject: ...

def difference_matrix_product(k: builtins.int, M1: builtins.object, G1: builtins.object, lmbda1: builtins.object, M2: builtins.object, G2: builtins.object, lmbda2: builtins.object, check: builtins.bool = ...) -> _SageObject: ...

def difference_matrix(g: builtins.object, k: builtins.int, lmbda: builtins.int = ..., existence: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...
