# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class EvenlyDistributedSetsBacktracker:
    def __init__(self, K: builtins.object, k: builtins.object, up_to_isomorphism: builtins.object = ..., check: builtins.object = ...) -> None: ...
    def to_difference_family(self, B: builtins.object, check: builtins.object = ...) -> _SageObject: ...
    def an_element(self) -> _SageObject: ...
    def cardinality(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
