# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

XML_NAMESPACE: _SageObject
DTRS_PROTOCOL: _SageObject
v2_b2_k2_icgsa: _SageObject
def dump_to_tmpfile(s: builtins.object) -> _SageObject: ...

def check_dtrs_protocols(input_name: builtins.str, input_pv: builtins.object) -> _SageObject: ...

def open_extrep_file(fname: builtins.object) -> _SageObject: ...

def open_extrep_url(url: builtins.object) -> _SageObject: ...

pattern_integer: _SageObject
pattern_decimal: _SageObject
pattern_rational: _SageObject
class XTree:
    def __init__(self, node: builtins.object) -> None: ...
    def __getattr__(self, attr: builtins.object) -> _SageObject: ...
    def __getitem__(self, i: builtins.int) -> _SageObject: ...
    def __len__(self) -> builtins.int: ...

class XTreeProcessor:
    def __init__(self) -> None: ...
    def parse(self, xml_source: builtins.object) -> _SageObject: ...

def designs_from_XML(fname: builtins.object) -> _SageObject: ...

def designs_from_XML_url(url: builtins.object) -> _SageObject: ...
