# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def is_GQ_with_spread(GQ: builtins.object, S: builtins.object, s: builtins.object = ..., t: builtins.object = ...) -> builtins.bool: ...

def dual_GQ_ovoid(GQ: builtins.object, O: builtins.object) -> _SageObject: ...

def generalised_quadrangle_symplectic_with_spread(q: builtins.object, check: builtins.object = ...) -> _SageObject: ...

def generalised_quadrangle_hermitian_with_ovoid(q: builtins.object) -> _SageObject: ...
