import builtins

class _SageObject: ...

def are_mutually_orthogonal_latin_squares(
    self, verbose: builtins.bool = ...
) -> _SageObject: ...
def mutually_orthogonal_latin_squares(
    self, n: builtins.int, partitions: builtins.bool = ..., check: builtins.bool = ...
) -> _SageObject: ...
def latin_square_product(
    self, N: builtins.int, *others: builtins.object
) -> _SageObject: ...
def MOLS_table(
    self,
    stop: builtins.int = ...,
    compare: builtins.bool = ...,
    width: builtins.object = ...,
) -> _SageObject: ...
