# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def are_mutually_orthogonal_latin_squares(l: builtins.object, verbose: builtins.bool = ...) -> _SageObject: ...

def mutually_orthogonal_latin_squares(k: builtins.int, n: builtins.int, partitions: builtins.bool = ..., check: builtins.bool = ...) -> _SageObject: ...

def latin_square_product(M: builtins.int, N: builtins.int, *others: builtins.object) -> _SageObject: ...

def MOLS_table(start: builtins.int, stop: builtins.int = ..., compare: builtins.bool = ..., width: builtins.object = ...) -> _SageObject: ...
