# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def resolvable_balanced_incomplete_block_design(v: builtins.object, k: builtins.int, existence: builtins.bool = ...) -> _SageObject: ...

def kirkman_triple_system(v: builtins.object, existence: builtins.bool = ...) -> _SageObject: ...

def v_4_1_rbibd(v: builtins.object, existence: builtins.bool = ...) -> _SageObject: ...

def PBD_4_7(v: builtins.object, check: builtins.bool = ..., existence: builtins.bool = ...) -> _SageObject: ...

def PBD_4_7_from_Y(gdd: builtins.object, check: builtins.bool = ...) -> _SageObject: ...
