# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

def two_n(B: builtins.object) -> _SageObject: ...

def three_n_minus_two(B: builtins.object) -> _SageObject: ...

def three_n_minus_eight(B: builtins.object) -> _SageObject: ...

def three_n_minus_four(B: builtins.object) -> _SageObject: ...

def four_n_minus_six(B: builtins.object) -> _SageObject: ...

def twelve_n_minus_ten(B: builtins.object) -> _SageObject: ...

def relabel_system(B: builtins.object) -> _SageObject: ...

def P(alpha: builtins.object, m: builtins.int) -> _SageObject: ...

def barP(eps: builtins.object, m: builtins.int) -> _SageObject: ...

def barP_system(m: builtins.int) -> _SageObject: ...

def steiner_quadruple_system(n: builtins.int, check: builtins.bool = ...) -> _SageObject: ...
