# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AffineGroup:
    @staticmethod
    def __classcall__(cls: builtins.object, *args: builtins.object, **kwds: builtins.object) -> _SageObject: ...
    def __init__(self, degree: builtins.int, ring: builtins.object) -> None: ...
    Element: _SageObject
    def cardinality(self) -> _SageObject: ...
    def degree(self) -> _SageObject: ...
    def matrix_space(self) -> _SageObject: ...
    def vector_space(self) -> _SageObject: ...
    def linear_space(self) -> _SageObject: ...
    def linear(self, A: builtins.object) -> _SageObject: ...
    def translation(self, b: builtins.object) -> _SageObject: ...
    def reflection(self, v: builtins.object) -> _SageObject: ...
    def random_element(self) -> _SageObject: ...
    def some_elements(self) -> _SageObject: ...
    def __iter__(self) -> _Iterator[_SageObject]: ...
