# Generated from the pinned Sage 10.7 source tree.
import builtins
from collections.abc import AsyncIterator as _AsyncIterator, Iterable as _Iterable, Iterator as _Iterator
from typing import Self

class _SageObject: ...

class AffineGroupElement:
    def __init__(self, parent: builtins.object, A: builtins.object, b: builtins.int = ..., convert: builtins.bool = ..., check: builtins.bool = ...) -> None: ...
    def A(self) -> _SageObject: ...
    def b(self) -> _SageObject: ...
    def matrix(self) -> _SageObject: ...
    def __call__(self, v: builtins.object) -> _SageObject: ...
    def __invert__(self) -> Self: ...
    def __hash__(self) -> builtins.int: ...
    def list(self) -> _SageObject: ...
